Sprint: Search::PersistentStateTree Class Reference
Search::PersistentStateTree Class Reference
Classes
struct Exit
Public Types
typedef std::map< Search::StateId, std::pair< Bliss::Phoneme::Id, Bliss::Phoneme::Id > > RootTransitDescriptions
Public Member Functions
PersistentStateTree (Core::Configuration config, Core::Ref< const Am::AcousticModel > acousticModel, Bliss::LexiconRef lexicon)
void build ()
Builds this state tree.
bool write (int transformation=0)
Writes the current state of the state tree into the file, Returns whether writing was successful.
bool read (int transformation=0)
Reads the state tree from the file.
HMMStateNetwork::CleanupResult cleanup (bool cleanupExits=true)
Cleans up the structure, saving memory and allowing a more efficient iteration.
void removeOutputs ()
Removes all outputs from the network Also performs a cleanup, so the search network must already be clean for indices to stay equal.
u32 getChecksum () const
void dumpDotGraph (std::string file, const std::vector< int > &nodeDepths)
Dump the search network as a dot graph into the given file.
bool isRoot (StateId node) const
Public Attributes
TreeIndex masterTree
--— state tree data: ---—
StateId rootState
StateId ciRootState
std::vector< Exit > exits
std::set< Search::StateId > coarticulatedRootStates
std::set< Search::StateId > unpushedCoarticulatedRootStates
std::set< StateId > pushedWordEndNodes
std::set< StateId > uncoarticulatedWordEndStates
RootTransitDescriptions rootTransitDescriptions
Search::HMMStateNetwork structure
Private Member Functions
std::string archiveEntry () const
void write (Core::MappedArchiveWriter writer)
bool read (Core::MappedArchiveReader reader)
Private Attributes
std::string archive_
Core::DependencySet dependencies_
Core::Ref< const Am::AcousticModel > acousticModel_
Bliss::LexiconRef lexicon_
Core::Configuration config_
Detailed Description
Definition at line 38 of file PersistentStateTree.hh.
Constructor & Destructor Documentation
Search::PersistentStateTree::PersistentStateTree (Core::Configuration config, Core::Ref< const Am::AcousticModel > acousticModel, Bliss::LexiconRef lexicon)
Parameters
lexicon This must be given if the resulting exits are supposed to be functional
Definition at line 169 of file PersistentStateTree.cc.
References Core::DependencySet::add(), Core::Ref< T >::get(), and required_cast.
Member Function Documentation
void Search::PersistentStateTree::build ()
Builds this state tree.
Definition at line 219 of file PersistentStateTree.cc.
References Search::ConvertTree::convert(), Core::Component::log(), masterTree, and Core::Application::us().
Referenced by Search::StaticSearchAutomaton::buildNetwork().
HMMStateNetwork::CleanupResult Search::PersistentStateTree::cleanup (bool cleanupExits = true)
Cleans up the structure, saving memory and allowing a more efficient iteration.
Node and tree IDs may be changed.
Returns
An object that contains a mapping representing the index changes.
Todo:
Go through the search tree, and collect the required coarticulated root nodes
Todo:
Also add the overall root node to coarticulatedRootNodes, then this is not needed
Definition at line 383 of file PersistentStateTree.cc.
References Search::HMMStateNetwork::addOutputToEdge(), Search::HMMStateNetwork::cleanup(), Core::Component::log(), masterTree, Search::HMMStateNetwork::state(), Search::HMMStateNetwork::stateCount(), Search::HMMState::successors, Core::Application::us(), and verify.
Referenced by Search::StaticSearchAutomaton::buildNetwork().
void Search::PersistentStateTree::dumpDotGraph (std::string file, const std::vector< int > & nodeDepths)
Dump the search network as a dot graph into the given file.
Definition at line 499 of file PersistentStateTree.cc.
References Core::form(), Bliss::LemmaPronunciation::invalidId, Search::HMMStateNetwork::state(), Search::HMMStateNetwork::stateCount(), Search::HMMState::stateDesc, and verify.
Referenced by Search::StaticSearchAutomaton::buildBatches().
bool Search::PersistentStateTree::read (int transformation = 0)
Reads the state tree from the file.
Returns
Whether the reading was successful.
Definition at line 195 of file PersistentStateTree.cc.
References Core::Application::getCacheArchiveReader(), Core::MappedArchiveReader::good(), Core::Component::log(), and Core::Application::us().
Referenced by Search::StaticSearchAutomaton::buildNetwork().
bool Search::PersistentStateTree::read (Core::MappedArchiveReader reader) private
Todo:
Eventually do memory-mapping
Definition at line 305 of file PersistentStateTree.cc.
References Core::MappedArchiveReader::good(), Core::Component::log(), masterTree, Search::HMMStateNetwork::read(), and Core::Application::us().
void Search::PersistentStateTree::removeOutputs ()
Removes all outputs from the network Also performs a cleanup, so the search network must already be clean for indices to stay equal.
Definition at line 340 of file PersistentStateTree.cc.
References Search::HMMStateNetwork::cleanup(), Core::Component::log(), masterTree, Search::HMMStateNetwork::stateCount(), Core::Application::us(), and verify.
Referenced by Search::StaticSearchAutomaton::buildBatches().
bool Search::PersistentStateTree::write (int transformation = 0)
Writes the current state of the state tree into the file, Returns whether writing was successful.
Definition at line 244 of file PersistentStateTree.cc.
References Core::Application::getCacheArchiveWriter(), Core::Component::log(), masterTree, Core::Application::us(), and Search::HMMStateNetwork::write().
Referenced by Search::StaticSearchAutomaton::buildNetwork().
Member Data Documentation
TreeIndex Search::PersistentStateTree::masterTree
--— state tree data: ---—
Definition at line 94 of file PersistentStateTree.hh.
Referenced by build(), cleanup(), read(), removeOutputs(), and write().
The documentation for this class was generated from the following files:
PersistentStateTree.hh
PersistentStateTree.cc