Sprint: Search::Wfst::Builder::CreateSubwordGrammar Class Reference
Search::Wfst::Builder::CreateSubwordGrammar Class Reference
Modify a subword LM transducer such that it is composable with a regular (fullword) G transducer.
#include <CreateOperations.hh>
Public Member Functions
CreateSubwordGrammar (const Core::Configuration &c, Resources &r)
Public Member Functions inherited from Search::Wfst::Builder::OutputTypeDependent
OutputTypeDependent (const Core::Configuration &c)
Public Member Functions inherited from Search::Wfst::Builder::SleeveOperation
SleeveOperation (const Core::Configuration &c, Resources &r)
virtual u32 nInputAutomata () const
number of automata required as input
virtual bool addInput (AutomatonRef f)
add input automaton (will be called nInputAutomata() times)
void deleteInput ()
Public Member Functions inherited from Search::Wfst::Builder::Operation
Operation (const Core::Configuration &c, Resources &r)
virtual bool consumeInput () const
should input automata be removed
virtual bool hasOutput () const
operation is expected to produce an output automaton.
AutomatonRef getResult ()
do the actual processing and create an output automaton
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Static Public Member Functions
static std::string name ()
Protected Member Functions
virtual AutomatonRef process ()
do the actual processing
bool readSubwordList (const std::string &filename)
bool addLemma (Fsa::LabelId synt)
bool addLemmaPronunciation (Fsa::LabelId lemma)
Protected Member Functions inherited from Search::Wfst::Builder::OutputTypeDependent
OutputType outputType () const
Protected Member Functions inherited from Search::Wfst::Builder::SleeveOperation
virtual bool precondition () const
precondition for getResult()
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes
std::unordered_set< Fsa::LabelId > subwordTokens_
Protected Attributes inherited from Search::Wfst::Builder::SleeveOperation
AutomatonRef input_
Protected Attributes inherited from Search::Wfst::Builder::Operation
Resources & resources_
Core::XmlChannel timerChannel_
Core::Timer timer_
Static Private Attributes
static const Core::ParameterString paramSubwordList
static const Core::ParameterString paramTransitionSymbol
Additional Inherited Members
Public Types inherited from Search::Wfst::Builder::Operation
typedef Automaton * AutomatonRef
Protected Types inherited from Search::Wfst::Builder::OutputTypeDependent
enum OutputType { outputLemmaPronunciations, outputLemmas, outputSyntacticTokens }
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Static Protected Attributes inherited from Search::Wfst::Builder::OutputTypeDependent
static const Core::ParameterChoice paramOutputType
static const Core::Choice choiceOutputType
Detailed Description
Modify a subword LM transducer such that it is composable with a regular (fullword) G transducer.
Adds loop transitions to a new initial state for all non subword tokens.
Definition at line 300 of file CreateOperations.hh.
Member Function Documentation
Operation::AutomatonRef CreateSubwordGrammar::process () protected virtual
do the actual processing
Implements Search::Wfst::Builder::Operation.
Definition at line 683 of file CreateOperations.cc.
References Fsa::Alphabet::begin(), OpenFst::convertLabelFromFsa(), Fsa::Alphabet::end(), Core::Component::error(), Fsa::Alphabet::index(), Core::Component::log(), and Core::Component::warning().
The documentation for this class was generated from the following files:
CreateOperations.hh
CreateOperations.cc