Sprint: Lattice::HtkReader Class Reference
Lattice::HtkReader Class Reference
Parse a lattice in HTK SLF format.
#include <HtkReader.hh>
Classes
struct Link
struct Node
struct State
Public Member Functions
HtkReader (const Core::Configuration &config, Bliss::LexiconRef lexiconRef, f64 amScale, f64 lmScale, f64 penaltyScale, f64 pronunciationScale, bool keepVariants)
void setWordPenalty (f64 penalty)
void setCapitalize (bool isCapitalize)
void setSilencePenalty (f64 penalty)
Fsa::ConstAlphabetRef getAlphabet ()
ConstWordLatticeRef read (std::istream &)
Protected Types
enum StatusEnum {
htkOk = 0, htkPropertyParseError, htkUnexpectedLine, htkUnexpectedNode,
htkParseNodeError, htkAddNodeError, htkParseLinkError, htkAddLinkError,
htkNoInitialStateError, htkNoFinalStateError
}
typedef enum Lattice::HtkReader::StatusEnum Status
Protected Member Functions
Fsa::Weight getWeight (const Link &, Fsa::LabelId)
Fsa::StateId getStateId (u32)
bool checkStatus (Status status)
Status init ()
Status addState (Node &node)
Status addArc (Link &link)
Status setInitialState ()
Status setFinalStates ()
void comment (const std::string &s)
Status start ()
Status header (const StringPairList &props)
Status node (Node &node)
Status link (Link &link)
Status end ()
Status add (const std::string &s, StringPairList &props)
LemmaRange parseLabel (std::string &label, const std::string &variant="")
Status set (const StringPairList &props, Node &node)
Status set (const StringPairList &props, Link &link)
Private Types
typedef HtkReader Self
typedef Core::Component Precursor
typedef std::pair< std::string, std::string > StringPair
typedef std::vector< StringPair > StringPairList
typedef Bliss::OrthographicParser::LemmaIterator LemmaIterator
typedef Bliss::OrthographicParser::LemmaRange LemmaRange
typedef std::vector< State > StateList
Private Types inherited from Lattice::Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Private Member Functions
void nextLine (std::istream &is, std::string &s)
Speech::TimeframeIndex timeframeIndex (f64 time) const
Private Member Functions inherited from Lattice::Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Private Member Functions inherited from Lattice::Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Private Attributes
Bliss::LexiconRef lexiconRef_
f64 amScale_
f64 lmScale_
f64 penaltyScale_
bool keepVariants_
f64 wordPenalty_
f64 silPenalty_
bool isCapitalize_
Fsa::LabelId unkLemmaId_
Fsa::LabelId silLemmaId_
Fsa::StorageAutomaton * lattice_
WordBoundaries * wordBoundaries_
StateList states_
f64 timeframeIndexScale_
f64 timeOffset_
Fsa::ConstAlphabetRef htkAlphabetRef_
Fsa::ConstAutomatonRef lemmaPronunciationToHtkTransducerRef_
Bliss::OrthographicParser * orthParser_
u32 line_
Status status_
Private Attributes inherited from Lattice::Core::Configurable
Configuration config
Static Private Attributes
static const Core::ParameterFloat paramTimeframeIndexScale
Detailed Description
Parse a lattice in HTK SLF format.
Definition at line 36 of file HtkReader.hh.
Member Function Documentation
HtkReader::Status HtkReader::addState (Node & node) protected
Todo:
across word model is not handled correctly yet
Definition at line 104 of file HtkReader.cc.
References Lattice::HtkReader::Link::amScore, Lattice::composeMatching(), Core::convertToUpperCase(), Lattice::HtkReader::Link::id, Lattice::HtkReader::Link::label, require, Lattice::HtkReader::Link::sourceState, Fsa::staticCopy(), Core::strconv(), and Core::stripWhitespace().
The documentation for this class was generated from the following files:
HtkReader.hh
HtkReader.cc