Sprint: Bliss::Evaluator Class Reference
Bliss::Evaluator Class Reference
Classes
class LetterAcceptorBuilder
Public Member Functions
Evaluator (const Core::Configuration &, Core::Ref< const Lexicon >)
void setReferenceTranscription (const std::string &)
u32 evaluateWords (Fsa::ConstAutomatonRef lemmaPron, const std::string &name)
Evaluate a word sequence or lattice.
u32 evaluatePhonemes (Fsa::ConstAutomatonRef phonemes, const std::string &name)
Evaluate a phoneme sequence or lattice.
u32 evaluate (Fsa::ConstAutomatonRef, const std::string &name)
Evaluate a sequence or a lattice.
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Private Member Functions
void reportLatticeDensity (Fsa::ConstAutomatonRef lattice, const Bliss::ErrorStatistic &latticeWordErrors)
Compute and report density of the lattice in terms of arcs per reference word.
Bliss::ErrorStatistic evaluateMetric (Fsa::ConstAutomatonRef correct, Fsa::ConstAutomatonRef candidate, const std::string &type, const std::string &name)
Private Attributes
bool shallComputeWordErrors_
bool shallComputeLetterErrors_
bool shallFilterLettersByEvalTokens_
bool shallComputePhonemeErrors_
Core::Ref< const Lexicon > lexicon_
Core::Ref< const OrthographicParser > orthParser_
Fsa::ConstAutomatonRef lemmaPronToLemma_
Fsa::ConstAutomatonRef lemmaPronToPhoneme_
Fsa::ConstAutomatonRef lemmaToSynt_
Fsa::ConstAutomatonRef lemmaToEval_
Fsa::ConstAutomatonRef lemmaToLemmaConfusion_
Fsa::ConstAutomatonRef lemmaToLetter_
Fsa::ConstAutomatonRef lemmaToPhoneme_
LetterAcceptorBuilder * letterAcceptorBuilder_
Bliss::EditDistance * editDistance_
struct {
Fsa::ConstAutomatonRef lemma
Fsa::ConstAutomatonRef eval
Fsa::ConstAutomatonRef phon
Fsa::ConstAutomatonRef orth
} correct_
Core::XmlChannel graphStatisticsChannel_
Core::XmlChannel graphDumpChannel_
Static Private Attributes
static const Core::ParameterBool paramWordErrors
static const Core::ParameterBool paramLetterErrors
static const Core::ParameterBool paramFilterLettersByEvalTokens
static const Core::ParameterBool paramPhonemeErrors
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Definition at line 31 of file Evaluation.hh.
Member Function Documentation
u32 Evaluator::evaluate (Fsa::ConstAutomatonRef aa, const std::string & name)
Evaluate a sequence or a lattice.
This function automatically dispatches to evaluateWords() or evaluatePhonemes().
Definition at line 372 of file Evaluation.cc.
References evaluatePhonemes(), evaluateWords(), and require.
Referenced by Speech::GerLatticeProcessorNode::processWordLattice().
u32 Evaluator::evaluatePhonemes (Fsa::ConstAutomatonRef phonemes, const std::string & name)
Evaluate a phoneme sequence or lattice.
This function is intended for use in a phoneme recognizer. The phoneme error rate of a word sequence or lattice can be evaluated using evaluateWords().
For "normal" single-best error rates, make sure that the automaton passed is linear. For non-linear automata oracle error rates are computed. The best sentence hypothesis in the lattice (according to the evaluation metric) is reported.
Parameters
phonemes an acceptor representing the single-best hypothesis or a phoneme lattice. The labels must be phonemes.
name a string identifier that will be attached to the result.
Definition at line 355 of file Evaluation.cc.
References reportLatticeDensity(), require, and Fsa::staticCopy().
Referenced by evaluate().
u32 Evaluator::evaluateWords (Fsa::ConstAutomatonRef lemmaPron, const std::string & name)
Evaluate a word sequence or lattice.
For "normal" single-best error rates, make sure that the automaton passed is linear. For non-linear automata oracle error rates are computed. The best sentence hypothesis in the lattice (according to the evaluation metric) is reported.
Parameters
lemmaPron an acceptor representing the single-best hypothesis or a word lattice. The labels must be lemma-pronunciations.
name a string identifier that will be attached to the result.
Definition at line 308 of file Evaluation.cc.
References reportLatticeDensity(), require, and Fsa::staticCopy().
Referenced by evaluate(), and Flf::Evaluator::logEvaluation().
void Evaluator::reportLatticeDensity (Fsa::ConstAutomatonRef lattice, const Bliss::ErrorStatistic & latticeWordErrors) private
Compute and report density of the lattice in terms of arcs per reference word.
Warning: The word lattice density as defined here is a bit "skewed": The denominator counts evaluation tokens, while the numerator counts lemma pronuncations. (Actually it is not even guatanteed that nWordArcs corresponds to lemma pronuncations, since the interface of this function is rather fexible.) However, this may be justified since eval tokens corrspond to "words that matter" and the number of arcs in the lattice to "search and storage effort. Therefore the resulting quotient is a figure of efficiency of the lattice. Another issue is that the number of eval tokens can be ambiguous (depending on the lexicon). This is addressed by using the sequence which yields the fewest errors.
Definition at line 294 of file Evaluation.cc.
References Fsa::count().
Referenced by evaluatePhonemes(), and evaluateWords().
The documentation for this class was generated from the following files:
Evaluation.hh
Evaluation.cc