Sprint: Signal::VectorSequenceAggregation< T > Class Template Reference
Signal::VectorSequenceAggregation< T > Class Template Reference
Public Member Functions
VectorSequenceAggregation (const Core::Configuration &c)
virtual bool setParameter (const std::string &name, const std::string &value)
Set node specific parameter.
virtual bool configure ()
Performs static (independent of input data) configuration of node.
virtual Flow::PortId getOutput (const std::string &name)
Ask for an output port.
Public Member Functions inherited from Signal::DelayNode
DelayNode (const Core::Configuration &c)
virtual Flow::PortId getInput (const std::string &name)
Ask for an input port.
virtual bool work (Flow::PortId)
Processes some data.
Public Member Functions inherited from Flow::Node
Node (const Core::Configuration &c)
Public Member Functions inherited from Flow::AbstractNode
AbstractNode (const Core::Configuration &c)
virtual void Run ()
void setThreaded (bool threaded=true)
void setThreaded (const std::string &threaded)
bool isThreaded () const
virtual bool addParameter (const std::string &name, const Core::StringExpression &value)
addParameter adds a parameter to the node Constant parameters are simply delegated to setParameter, parameters dependent on network parameters are stored in parameters_.
virtual ssize_t getRemainingDataLen (PortId out)
Returns the amount of remaining data items.
void addUnresolvedParameter (const std::string &key, const std::string &value)
Functions for saving and getting unresolved parameters.
const UnresolvedAttributes & unresolvedAttributes () const
bool operator< (const AbstractNode &n) const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Signal::SlidingWindow< Flow::DataPtr< Flow::Data > >
SlidingWindow (size_t maxSize=1, size_t right=0)
bool init (size_t maxSize, size_t right)
initializes the sliding window
void clear ()
void add (const Flow::DataPtr< Flow::Data > &add)
Adds a new element Removes the oldest element if number of past elements exceeded maxPastSize_.
void flush ()
Simulates adding one empty element.
void flushOut ()
Simulates adding at least so many (n) empty elements that output (.
bool get (int relativeIndex, Flow::DataPtr< Flow::Data > &out) const
returns the element at relative index
void getClosest (int relativeIndex, Flow::DataPtr< Flow::Data > &out) const
returns the closest existing element to relative index
bool out (Flow::DataPtr< Flow::Data > &out) const
returns the present element if contained.
bool presentEmpty () const
size_t futureSize () const
size_t maxFutureSize () const
size_t pastSize () const
size_t maxPastSize () const
bool removed (Flow::DataPtr< Flow::Data > &removed) const
bool removedValid () const
size_t maxSize () const
maximum number of elements set by the last call to init.
size_t size () const
number of elements
bool empty () const
bool full () const
const Flow::DataPtr< Flow::Data > & operator[] (size_t right) const
Flow::DataPtr< Flow::Data > & operator[] (size_t right)
const Flow::DataPtr< Flow::Data > & front () const
Flow::DataPtr< Flow::Data > & front ()
const Flow::DataPtr< Flow::Data > & back () const
Flow::DataPtr< Flow::Data > & back ()
ConstantIterator begin () const
Iterator begin ()
ConstantIterator end () const
Iterator end ()
ConstantReverseIterator reverseBegin () const
ReverseIterator reverseBegin ()
ConstantReverseIterator reverseEnd () const
ReverseIterator reverseEnd ()
Static Public Member Functions
static std::string filterName ()
Static Public Member Functions inherited from Signal::DelayNode
static std::string filterName ()
Protected Member Functions
virtual bool putData ()
override this function to produce output from the sliding window
Protected Member Functions inherited from Signal::DelayNode
void get (int relativeIndex, Flow::DataPtr< Flow::Data > &out) const
returns the at relative index
template<class T >
void get (int relativeIndex, Flow::DataPtr< T > &out) const
Protected Member Functions inherited from Flow::Node
virtual PortId connectInputPort (PortId, Link *)
Connect link to input port.
virtual void disconnectInputLink (Link *)
virtual PortId connectOutputPort (PortId, Link *)
virtual void disconnectOutputLink (Link *)
PortId addInput (PortId in=IllegalPortId)
Create an input port.
PortId addInputs (u32 nPorts)
Create several input ports.
virtual PortId nInputs () const
Link * getInputLink (PortId in) const
virtual PortId inputConnected (PortId in) const
bool validInputPort (PortId in) const
PortId addOutput (PortId out=IllegalPortId)
Add an output port.
PortId addOutputs (u32 nPorts)
Create several output ports.
virtual PortId nOutputs () const
bool validOutputPort (PortId out) const
virtual u32 nOutputLinks (PortId out) const
Number of link connceted to an output port.
bool configureDatatype (Core::Ref< const Attributes > a, const Datatype *d)
template<class T >
bool getData (PortId in, DataPtr< T > &d)
Fetch data packet from input port.
virtual bool putData (PortId out, Data *d)
Send data packet on output port.
bool putEos (PortId out)
Send end-of-stream on output port.
bool putOod (PortId out)
Send out-of-data on output port.
Core::Ref< const Attributes > getInputAttributes (PortId in)
Retrieve attribute set from input port.
void getInputAttributes (PortId, Attributes &)
bool putOutputAttributes (PortId out, Core::Ref< const Attributes > a)
Put attribute set on output port.
void eraseOutputAttributes ()
Erases attributes of all output links recursively.
Protected Member Functions inherited from Flow::AbstractNode
template<class T >
bool getData (Link *l, DataPtr< T > &d)
Fetch data packet from the "from" port of link.
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Private Types
typedef DelayNode Precursor
typedef Flow::TypedAggregate< Flow::Vector< T > >::DataType DataType
Private Attributes
bool expandTimestamp_
Additional Inherited Members
Public Types inherited from Flow::AbstractNode
typedef std::map< std::string, std::string > UnresolvedAttributes
Public Types inherited from Signal::SlidingWindow< Flow::DataPtr< Flow::Data > >
enum MarginPolicyType
enum MarginConditionType
typedef Precursor::const_iterator ConstantIterator
typedef Precursor::iterator Iterator
typedef Precursor::const_reverse_iterator ConstantReverseIterator
typedef Precursor::reverse_iterator ReverseIterator
Static Public Attributes inherited from Signal::DelayNode
static const Core::ParameterInt parameterMaxSize
static const Core::ParameterInt parameterRight
static const Core::Choice choiceMarginPolicyType
static const Core::ParameterChoice paramMarginPolicy
static const Core::Choice choiceMarginConditionType
static const Core::ParameterChoice paramMarginCondition
Static Public Attributes inherited from Flow::AbstractNode
static const Core::ParameterBool paramThreaded
static const Core::ParameterBool paramIgnoreUnknownParameters
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
template<class T>
class Signal::VectorSequenceAggregation< T >
Definition at line 38 of file VectorSequenceAggregation.hh.
Member Function Documentation
template<class T > bool Signal::VectorSequenceAggregation< T >::configure () virtual
Performs static (independent of input data) configuration of node.
Configure is called if one of the output attributes is not available. Override this function to evaluate all input attributes and pass them on to successor nodes. The default implementation simply forwards the merged attributes from all input links to all outputs. Note: -we assume no dead inputs here. -This function is the safest point to reset the algorithms used by the node. The alternative would be to reset the algorithms when a non-data object has been recieved. This solution can lead easily to unintended behaviour, since it is not garatinteed at all that every node receives for example a EOS object!
Reimplemented from Signal::DelayNode.
Definition at line 80 of file VectorSequenceAggregation.hh.
References Flow::Node::getInputAttributes(), and Flow::Node::putOutputAttributes().
template<class T > virtual Flow::PortId Signal::VectorSequenceAggregation< T >::getOutput (const std::string &) inline virtual
Ask for an output port.
Implement this function to provide a mapping form names to port IDs. Consider using a Core::Choice. Remeber to create ports using addOutput().
Returns
a valid port ID or IllegalPortId if there is to such port.
Reimplemented from Signal::DelayNode.
Definition at line 58 of file VectorSequenceAggregation.hh.
References Flow::Node::addOutput(), and Signal::paramVectorSequenceAggregationExpandTimestamp.
template<class T > bool Signal::VectorSequenceAggregation< T >::putData () protected virtual
override this function to produce output from the sliding window
Reimplemented from Signal::DelayNode.
Definition at line 93 of file VectorSequenceAggregation.hh.
References Flow::Timestamp::expandTimestamp(), and Signal::SlidingWindow< Flow::DataPtr< Flow::Data > >::out().
template<class T > bool Signal::VectorSequenceAggregation< T >::setParameter (const std::string & name, const std::string & value) virtual
Set node specific parameter.
Implement this template function to handle parameters specific to your Node.
Parameters
name name of parameter
value new value for the parameter
Returns
true if successful, false if parameter name is not understood.
Reimplemented from Signal::DelayNode.
Definition at line 71 of file VectorSequenceAggregation.hh.
References Signal::paramVectorSequenceAggregationExpandTimestamp, and Signal::DelayNode::setParameter().
The documentation for this class was generated from the following file:
VectorSequenceAggregation.hh