Sprint: Math::AnalyticFunctionFactory Class Reference
Math::AnalyticFunctionFactory Class Reference
Analytic function factory.
#include <AnalyticFunctionFactory.hh>
Public Types
enum DomainType { continuousDomain, discreteDomain, normalizedOmegaDomain }
Public Member Functions
AnalyticFunctionFactory (const Core::Configuration &)
UnaryAnalyticFunctionRef createUnaryFunction (const std::string &declaration) const
Creates a unary function by parsing.
BinaryAnalyticFunctionRef createBinaryFunction (const std::string &declaration) const
Creates a binary function by parsing.
void setSampleRate (UnaryAnalyticFunction::Argument sampleRate)
void setMaximalArgument (UnaryAnalyticFunction::Argument maximum)
void setDomainType (DomainType type)
UnaryAnalyticFunctionRef createMaximumNormalization (UnaryAnalyticFunctionRef f) const
Result is f' = constant * f where constant ensures f'(maxInput) = maxInput.
UnaryAnalyticFunctionRef createMelWarpingFunction (bool discretizeArgument=false) const
Creates an object implementing the Mel warping function f_{Mel} = 2595 * log10 (1 + f / 700)
UnaryAnalyticFunctionRef createBarkWarpingFunction () const
Creates an object implementing the Bark warping function Continuous input: f_{Bark} = 6 * ln(f / 600 + sqrt((f / 600)^2 + 1)) = 6 * asinh(f / 600); Remark:
UnaryAnalyticFunctionRef createTwoPieceLinearFunction (UnaryAnalyticFunction::Argument warpingFactor, UnaryAnalyticFunction::Argument limit) const
Two piece linear warping function.
UnaryAnalyticFunctionRef createBilinearWarpingFunction (UnaryAnalyticFunction::Argument warpingFactor) const
Bilinear Warping Function.
UnaryAnalyticFunctionRef createThreePieceAffineFunction (UnaryAnalyticFunction::Argument warpingFactor, UnaryAnalyticFunction::Argument aShift, UnaryAnalyticFunction::Argument lowerLimit, UnaryAnalyticFunction::Argument upperLimit) const
Three piece affine warping function.
UnaryAnalyticFunctionRef createEqualLoudnessPreemphasis () const
Creates equal loudness preemphasis object Note: If maximal-argument <= 4000 (i.e.
UnaryAnalyticFunctionRef createEqualLoudnessPreemphasis40dB () const
Creates equal loudness preemphasis object with 40dB.
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Member Functions
static UnaryAnalyticFunctionRef createConstant (UnaryAnalyticFunction::Argument c)
Creates a ConstantFunction object.
static UnaryAnalyticFunctionRef createIdentity ()
Creates a IdentityFunction object.
static UnaryAnalyticFunctionRef createScaling (UnaryAnalyticFunction::Argument a)
Creates a ScalingFunction object.
static UnaryAnalyticFunctionRef createOffset (UnaryAnalyticFunction::Argument b)
Creates a OffsetFunction object.
static UnaryAnalyticFunctionRef createLinear (UnaryAnalyticFunction::Argument a, UnaryAnalyticFunction::Argument b)
Creates an object for f(x) = a * x + b.
static UnaryAnalyticFunctionRef createFloorFloat ()
Creates a FloorFloatFunction object.
static BinaryAnalyticFunctionRef createAddition ()
Creates a AdditionFunction object.
static BinaryAnalyticFunctionRef createSubstraction ()
Creates a createSubstraction object.
static BinaryAnalyticFunctionRef createMultiplication ()
Creates a MultiplicationFunction object.
static BinaryAnalyticFunctionRef createDivision ()
Creates a DivisionFunction object.
static UnaryAnalyticFunctionRef createSinh ()
Creates an object of Sinh.
static UnaryAnalyticFunctionRef createCosh ()
Creates an object of Cosh.
static UnaryAnalyticFunctionRef createMelWarpingCore ()
Creates an object of MelWarpingCore.
Private Types
typedef AnalyticFunctionFactory Self
typedef Core::Ref< const AnalyticFunction > AnalyticFunctionRef
typedef AnalyticFunctionRef(Self::* ParserFunction) (const std::string &, std::string::size_type &) const
Prototype of a function declaration parser.
Private Member Functions
UnaryAnalyticFunctionRef castToUnaryFunction (AnalyticFunctionRef) const
BinaryAnalyticFunctionRef castToBinaryFunction (AnalyticFunctionRef) const
bool accept (const std::string &s, const std::string &declaration, std::string::size_type &position) const
Matches.
bool accept (UnaryAnalyticFunction::Argument &a, const std::string &declaration, std::string::size_type &position) const
Matches a number starting at position.
void acceptWhitespaces (const std::string &declaration, std::string::size_type &position) const
Accepts leading whitespaces starting at position.
void registerFunctionParser (ParserFunction function)
AnalyticFunctionRef create (const std::string &declaration) const
Creates a function by parsing.
AnalyticFunctionRef create (const std::string &declaration, std::string::size_type &position) const
Creates a function by parsing.
AnalyticFunctionRef parseNesting (const std::string &declaration, std::string::size_type &position) const
Creates a nested function object f(g(x)).
AnalyticFunctionRef parseInvertion (const std::string &declaration, std::string::size_type &position) const
Creates a inverse function object f(x)^(-1).
AnalyticFunctionRef parseMaximumNormalization (const std::string &declaration, std::string::size_type &position) const
Creates a maximum normalization function object f(x)^(-1).
AnalyticFunctionRef parseIdentity (const std::string &declaration, std::string::size_type &position) const
Creates an identity function object f(x) = x.
AnalyticFunctionRef parseConstant (const std::string &declaration, std::string::size_type &position) const
Creates a constant function object f(x) = c.
AnalyticFunctionRef parseOffset (const std::string &declaration, std::string::size_type &position) const
Creates an offset function object f(x) = x + b.
AnalyticFunctionRef parseScaling (const std::string &declaration, std::string::size_type &position) const
Creates an scaling function object f(x) = a * x.
AnalyticFunctionRef parseAddition (const std::string &declaration, std::string::size_type &position) const
Creates a addition function object f(x, y) = x + y.
AnalyticFunctionRef parseSubstraction (const std::string &declaration, std::string::size_type &position) const
Creates a addition function object f(x, y) = x - y.
AnalyticFunctionRef parseMultiplication (const std::string &declaration, std::string::size_type &position) const
Creates a addition function object f(x, y) = x * y.
AnalyticFunctionRef parseDivision (const std::string &declaration, std::string::size_type &position) const
Creates a addition function object f(x, y) = x / y.
AnalyticFunctionRef parseSinh (const std::string &declaration, std::string::size_type &position) const
Creates an Sinh function object f(x) = sinh(x).
AnalyticFunctionRef parseArcSinh (const std::string &declaration, std::string::size_type &position) const
Creates an ArcSinh function object f(x) = asinh(x).
AnalyticFunctionRef parseCosh (const std::string &declaration, std::string::size_type &position) const
Creates an Sinh function object f(x) = cosh(x).
AnalyticFunctionRef parseArcCosh (const std::string &declaration, std::string::size_type &position) const
Creates an ArcSinh function object f(x) = acosh(x).
AnalyticFunctionRef parseDiscreteToContinuous (const std::string &declaration, std::string::size_type &position) const
Creates an scaling function object f(x) = x / sampleRate_.
AnalyticFunctionRef parseContinuousToDiscrete (const std::string &declaration, std::string::size_type &position) const
Creates an scaling function object f(x) = x * sampleRate_.
AnalyticFunctionRef parseMelWarpingFunction (const std::string &declaration, std::string::size_type &position) const
Creates a mel warping function object (.
AnalyticFunctionRef parseBarkWarpingFunction (const std::string &declaration, std::string::size_type &position) const
Creates a bark warping function object (.
AnalyticFunctionRef parseTwoPieceLinearFunction (const std::string &declaration, std::string::size_type &position) const
Creates a two-piece linear function function object (.
AnalyticFunctionRef parseBilinearWarpingFunction (const std::string &declaration, std::string::size_type &position) const
Creates a bilinear warping function object (.
AnalyticFunctionRef parseThreePieceAffineFunction (const std::string &declaration, std::string::size_type &position) const
Creates a three-piece affine function function object (.
AnalyticFunctionRef parseEqualLoudnessPreemphasis (const std::string &declaration, std::string::size_type &position) const
Creates a equal loudness preemphasis object Declaration syntax: mel or equal-loudness-preemphasis.
AnalyticFunctionRef parseEqualLoudnessPreemphasis40dB (const std::string &declaration, std::string::size_type &position) const
Creates a equal loudness preemphasis object for 40dB For details.
Private Attributes
UnaryAnalyticFunction::Argument sampleRate_
UnaryAnalyticFunction::Argument maximalArgument_
DomainType domainType_
std::vector< ParserFunction > parserFunctions_
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Analytic function factory.
Definition at line 25 of file AnalyticFunctionFactory.hh.
Member Typedef Documentation
typedef AnalyticFunctionRef(Self::* Math::AnalyticFunctionFactory::ParserFunction) (const std::string &, std::string::size_type &) const private
Prototype of a function declaration parser.
Returns
is invalid if declaration at position
Parameters
position does not match the syntax.
position is set to the furthermost unparsed character (independent of success).
Definition at line 35 of file AnalyticFunctionFactory.hh.
Member Enumeration Documentation
enum Math::AnalyticFunctionFactory::DomainType
Enumerator
continuousDomain
unit of argument is an unknown continuous unit
discreteDomain
argument is discrete index corresponding to sampleRate_
normalizedOmegaDomain
omega = 2 * pi * n / N, where n is discrete frequency index and N is number of FFT points
Definition at line 39 of file AnalyticFunctionFactory.hh.
Member Function Documentation
bool AnalyticFunctionFactory::accept (const std::string & s, const std::string & declaration, std::string::size_type & position) const private
Matches.
Parameters
s in
declaration starting at position
position.
Returns
if true if match was successfull. If successfully matched
Parameters
position will point at the first unparsed position. Whitespaces are ignored.
Definition at line 61 of file AnalyticFunctionFactory.cc.
References require.
bool Math::AnalyticFunctionFactory::accept (UnaryAnalyticFunction::Argument & a, const std::string & declaration, std::string::size_type & position) const private
Matches a number starting at position.
Parameters
position.
Returns
if true if match was successfull. If successfully matched
Parameters
position will point at the first unparsed position. Whitespaces are ignored.
void AnalyticFunctionFactory::acceptWhitespaces (const std::string & declaration, std::string::size_type & position) const private
Accepts leading whitespaces starting at position.
Parameters
position.
position is set the position if the first non-whitespace character in
declaration starting from
position
Definition at line 95 of file AnalyticFunctionFactory.cc.
References Core::Ref< T >::get().
AnalyticFunctionFactory::AnalyticFunctionRef AnalyticFunctionFactory::create (const std::string & declaration) const private
Creates a function by parsing.
Parameters
declaration.
Returns
is invalid if parsing failed.
Definition at line 120 of file AnalyticFunctionFactory.cc.
Referenced by createBinaryFunction(), createUnaryFunction(), and parseNesting().
AnalyticFunctionFactory::AnalyticFunctionRef AnalyticFunctionFactory::create (const std::string & declaration, std::string::size_type & position) const private
Creates a function by parsing.
Parameters
declaration starting at position
position.
Returns
is invalid if parsing failed.
Definition at line 143 of file AnalyticFunctionFactory.cc.
static BinaryAnalyticFunctionRef Math::AnalyticFunctionFactory::createAddition () inline static
Creates a AdditionFunction object.
Definition at line 262 of file AnalyticFunctionFactory.hh.
UnaryAnalyticFunctionRef AnalyticFunctionFactory::createBarkWarpingFunction () const
Creates an object implementing the Bark warping function Continuous input: f_{Bark} = 6 * ln(f / 600 + sqrt((f / 600)^2 + 1)) = 6 * asinh(f / 600); Remark:
See also
ArchSinh Discrete input: i_{Bark} = 6 * asinh(i / frequencySampleRate / 600) * frequencySampleRate Normalized omega input: omega_{Mel} = 6 * asinh(omega * sampleRate / (2 * pi) / 600) * (2 * pi) / sampleRate Note: sampleRate is the one in time domain.
Definition at line 369 of file AnalyticFunctionFactory.cc.
References Math::nest().
Referenced by createMelWarpingCore().
UnaryAnalyticFunctionRef Math::AnalyticFunctionFactory::createBilinearWarpingFunction (UnaryAnalyticFunction::Argument warpingFactor) const inline
Bilinear Warping Function.
x_{B} = x - T / pi * arctan(a * sin(2 * pi / T * x) / (1 + a * cos(2 * pi / T * x))), where a = 1 - warping-factor, and T/2 is the point which is mapped on itself.
Definition at line 341 of file AnalyticFunctionFactory.hh.
References createEqualLoudnessPreemphasis(), createEqualLoudnessPreemphasis40dB(), and createThreePieceAffineFunction().
BinaryAnalyticFunctionRef Math::AnalyticFunctionFactory::createBinaryFunction (const std::string & declaration) const inline
Creates a binary function by parsing.
Parameters
declaration.
Returns
is invalid if parsing failed.
Definition at line 215 of file AnalyticFunctionFactory.hh.
References create().
static UnaryAnalyticFunctionRef Math::AnalyticFunctionFactory::createConstant (UnaryAnalyticFunction::Argument c) inline static
Creates a ConstantFunction object.
Definition at line 231 of file AnalyticFunctionFactory.hh.
References Math::createConstant().
static UnaryAnalyticFunctionRef Math::AnalyticFunctionFactory::createCosh () inline static
Creates an object of Cosh.
Definition at line 284 of file AnalyticFunctionFactory.hh.
static BinaryAnalyticFunctionRef Math::AnalyticFunctionFactory::createDivision () inline static
Creates a DivisionFunction object.
Definition at line 274 of file AnalyticFunctionFactory.hh.
UnaryAnalyticFunctionRef AnalyticFunctionFactory::createEqualLoudnessPreemphasis () const
Creates equal loudness preemphasis object Note: If maximal-argument <= 4000 (i.e.
: 4000 KHz) an optimized object (EqualLoudnessPreemphasis4Khz) is created.
Definition at line 543 of file AnalyticFunctionFactory.cc.
Referenced by createBilinearWarpingFunction().
UnaryAnalyticFunctionRef AnalyticFunctionFactory::createEqualLoudnessPreemphasis40dB () const
Creates equal loudness preemphasis object with 40dB.
Definition at line 566 of file AnalyticFunctionFactory.cc.
Referenced by createBilinearWarpingFunction().
static UnaryAnalyticFunctionRef Math::AnalyticFunctionFactory::createFloorFloat () inline static
Creates a FloorFloatFunction object.
Definition at line 252 of file AnalyticFunctionFactory.hh.
static UnaryAnalyticFunctionRef Math::AnalyticFunctionFactory::createIdentity () inline static
Creates a IdentityFunction object.
Definition at line 235 of file AnalyticFunctionFactory.hh.
Referenced by Signal::FilterBank::Boundary::init(), and Signal::CosineTransformNode::timeDomainSampleRate().
static UnaryAnalyticFunctionRef Math::AnalyticFunctionFactory::createLinear (UnaryAnalyticFunction::Argument a, UnaryAnalyticFunction::Argument b) inline static
Creates an object for f(x) = a * x + b.
Definition at line 247 of file AnalyticFunctionFactory.hh.
References createOffset(), createScaling(), and Math::nest().
UnaryAnalyticFunctionRef Math::AnalyticFunctionFactory::createMaximumNormalization (UnaryAnalyticFunctionRef f) const inline
Result is f' = constant * f where constant ensures f'(maxInput) = maxInput.
Definition at line 256 of file AnalyticFunctionFactory.hh.
References createScaling(), and Math::nest().
static UnaryAnalyticFunctionRef Math::AnalyticFunctionFactory::createMelWarpingCore () inline static
Creates an object of MelWarpingCore.
Definition at line 290 of file AnalyticFunctionFactory.hh.
References createBarkWarpingFunction(), createMelWarpingFunction(), and createTwoPieceLinearFunction().
UnaryAnalyticFunctionRef AnalyticFunctionFactory::createMelWarpingFunction (bool discretizeArgument = false) const
Creates an object implementing the Mel warping function f_{Mel} = 2595 * log10 (1 + f / 700)
Discrete input: i_{Mel} = 2595 * log10 (1 + i / frequencySampleRate / 700) * frequencySampleRate
if
Parameters
discretizeArgument is true then floorf is applied to the frequency: -'i / frequencySampleRate' replaced by 'floorf(i / frequencySampleRate)' -floorf gives less skipped warped indices -Acctually applied for combatibility with the old standard system.
Note: sampleRate has to be initialized by sampling rate on frequency axis: i.e.: #FFT-points / time-domain-sampling-rate.
Normalized omega input: omega_{Mel} = 2595 * log10 (1 + omega * sampleRate / (2 * pi) / 700) * (2 * pi) / sampleRate Note: sampleRate is the one in time domain.
Definition at line 338 of file AnalyticFunctionFactory.cc.
References Math::nest().
Referenced by createMelWarpingCore().
static BinaryAnalyticFunctionRef Math::AnalyticFunctionFactory::createMultiplication () inline static
Creates a MultiplicationFunction object.
Definition at line 270 of file AnalyticFunctionFactory.hh.
static UnaryAnalyticFunctionRef Math::AnalyticFunctionFactory::createOffset (UnaryAnalyticFunction::Argument b) inline static
Creates a OffsetFunction object.
Definition at line 243 of file AnalyticFunctionFactory.hh.
Referenced by createLinear().
static UnaryAnalyticFunctionRef Math::AnalyticFunctionFactory::createScaling (UnaryAnalyticFunction::Argument a) inline static
Creates a ScalingFunction object.
Definition at line 239 of file AnalyticFunctionFactory.hh.
Referenced by createLinear(), and createMaximumNormalization().
static UnaryAnalyticFunctionRef Math::AnalyticFunctionFactory::createSinh () inline static
Creates an object of Sinh.
Definition at line 280 of file AnalyticFunctionFactory.hh.
static BinaryAnalyticFunctionRef Math::AnalyticFunctionFactory::createSubstraction () inline static
Creates a createSubstraction object.
Definition at line 266 of file AnalyticFunctionFactory.hh.
UnaryAnalyticFunctionRef AnalyticFunctionFactory::createThreePieceAffineFunction (UnaryAnalyticFunction::Argument warpingFactor, UnaryAnalyticFunction::Argument aShift, UnaryAnalyticFunction::Argument lowerLimit, UnaryAnalyticFunction::Argument upperLimit) const
Three piece affine warping function.
a <= 1: f < lowerLimit : f_warped = ((a * lowerLimit + aShift * (a - 1))/lowerLimit) * f lowerLimit <= f < upperLimit : f_warped = a * f + aShift * (a-1) f >= upperLimit : f_warped = m * f + c where m = (1 - (a * upperLimit + aShift * (a - 1)))(1 - upperLimit)
a > 1 Note: this case is equal to the mathematical inverse of the warping function set up with (lowerLimit, upper_limit, 1/a).
Definition at line 457 of file AnalyticFunctionFactory.cc.
References Math::PiecewiseLinearFunction::normalize(), and require.
Referenced by createBilinearWarpingFunction().
UnaryAnalyticFunctionRef AnalyticFunctionFactory::createTwoPieceLinearFunction (UnaryAnalyticFunction::Argument warpingFactor, UnaryAnalyticFunction::Argument limit) const
Two piece linear warping function.
a <= 1: f < limit : f_warped = a * f f >= limit : f_warped = (1.0 - a * limit) / (1.0 - limit) * f
a > 1 f < limit / a : f_warped = a * f f >= limit / a : (a - a * limit) / (a - limit) * f Note: this case is equal to the mathematical inverse of the warping function set up with (limit, 1/a).
Definition at line 394 of file AnalyticFunctionFactory.cc.
References Math::PiecewiseLinearFunction::normalize(), and require.
Referenced by createMelWarpingCore(), and Signal::LinearWarpingNode::warping().
UnaryAnalyticFunctionRef Math::AnalyticFunctionFactory::createUnaryFunction (const std::string & declaration) const inline
Creates a unary function by parsing.
Parameters
declaration.
Returns
is invalid if parsing failed.
Definition at line 209 of file AnalyticFunctionFactory.hh.
References create().
Referenced by Signal::CosineTransformNode::timeDomainSampleRate().
AnalyticFunctionFactory::AnalyticFunctionRef AnalyticFunctionFactory::parseAddition (const std::string & declaration, std::string::size_type & position) const private
Creates a addition function object f(x, y) = x + y.
Declaration syntax: plus.
Definition at line 258 of file AnalyticFunctionFactory.cc.
AnalyticFunctionFactory::AnalyticFunctionRef AnalyticFunctionFactory::parseArcCosh (const std::string & declaration, std::string::size_type & position) const private
Creates an ArcSinh function object f(x) = acosh(x).
Declaration syntax: acosh.
Definition at line 314 of file AnalyticFunctionFactory.cc.
AnalyticFunctionFactory::AnalyticFunctionRef AnalyticFunctionFactory::parseArcSinh (const std::string & declaration, std::string::size_type & position) const private
Creates an ArcSinh function object f(x) = asinh(x).
Declaration syntax: asinh.
Definition at line 298 of file AnalyticFunctionFactory.cc.
AnalyticFunctionFactory::AnalyticFunctionRef AnalyticFunctionFactory::parseBarkWarpingFunction (const std::string & declaration, std::string::size_type & position) const private
Creates a bark warping function object (.
See also
createBarkWarpingFunction). Declaration syntax: bark.
Definition at line 386 of file AnalyticFunctionFactory.cc.
AnalyticFunctionFactory::AnalyticFunctionRef AnalyticFunctionFactory::parseBilinearWarpingFunction (const std::string & declaration, std::string::size_type & position) const private
Creates a bilinear warping function object (.
See also
createBilinearWarpingFunction). Declaration syntax: bilinear(a).
Definition at line 439 of file AnalyticFunctionFactory.cc.
AnalyticFunctionFactory::AnalyticFunctionRef AnalyticFunctionFactory::parseConstant (const std::string & declaration, std::string::size_type & position) const private
Creates a constant function object f(x) = c.
Declaration syntax: const(c).
Definition at line 219 of file AnalyticFunctionFactory.cc.
References Math::createConstant().
AnalyticFunctionFactory::AnalyticFunctionRef AnalyticFunctionFactory::parseContinuousToDiscrete (const std::string & declaration, std::string::size_type & position) const private
Creates an scaling function object f(x) = x * sampleRate_.
Declaration syntax: cont-to-disc.
Definition at line 330 of file AnalyticFunctionFactory.cc.
AnalyticFunctionFactory::AnalyticFunctionRef AnalyticFunctionFactory::parseCosh (const std::string & declaration, std::string::size_type & position) const private
Creates an Sinh function object f(x) = cosh(x).
Declaration syntax: cosh.
Definition at line 306 of file AnalyticFunctionFactory.cc.
AnalyticFunctionFactory::AnalyticFunctionRef AnalyticFunctionFactory::parseDiscreteToContinuous (const std::string & declaration, std::string::size_type & position) const private
Creates an scaling function object f(x) = x / sampleRate_.
Declaration syntax: disc-to-cont.
Definition at line 322 of file AnalyticFunctionFactory.cc.
AnalyticFunctionFactory::AnalyticFunctionRef AnalyticFunctionFactory::parseDivision (const std::string & declaration, std::string::size_type & position) const private
Creates a addition function object f(x, y) = x / y.
Declaration syntax: divides.
Definition at line 282 of file AnalyticFunctionFactory.cc.
AnalyticFunctionFactory::AnalyticFunctionRef AnalyticFunctionFactory::parseEqualLoudnessPreemphasis (const std::string & declaration, std::string::size_type & position) const private
Creates a equal loudness preemphasis object Declaration syntax: mel or equal-loudness-preemphasis.
For details
See also
createEqualLoudnessPreemphasis.
Definition at line 535 of file AnalyticFunctionFactory.cc.
AnalyticFunctionFactory::AnalyticFunctionRef AnalyticFunctionFactory::parseEqualLoudnessPreemphasis40dB (const std::string & declaration, std::string::size_type & position) const private
Creates a equal loudness preemphasis object for 40dB For details.
See also
createEqualLoudnessPreemphasis40dB.
Definition at line 558 of file AnalyticFunctionFactory.cc.
AnalyticFunctionFactory::AnalyticFunctionRef AnalyticFunctionFactory::parseIdentity (const std::string & declaration, std::string::size_type & position) const private
Creates an identity function object f(x) = x.
Declaration syntax: identity.
Definition at line 211 of file AnalyticFunctionFactory.cc.
AnalyticFunctionFactory::AnalyticFunctionRef AnalyticFunctionFactory::parseInvertion (const std::string & declaration, std::string::size_type & position) const private
Creates a inverse function object f(x)^(-1).
Declaration syntax: invert(f).
Definition at line 182 of file AnalyticFunctionFactory.cc.
AnalyticFunctionFactory::AnalyticFunctionRef AnalyticFunctionFactory::parseMaximumNormalization (const std::string & declaration, std::string::size_type & position) const private
Creates a maximum normalization function object f(x)^(-1).
Declaration syntax: norm-max(f).
Definition at line 198 of file AnalyticFunctionFactory.cc.
AnalyticFunctionFactory::AnalyticFunctionRef AnalyticFunctionFactory::parseMelWarpingFunction (const std::string & declaration, std::string::size_type & position) const private
Creates a mel warping function object (.
See also
createMelWarpingFunction). Declaration syntax: mel or mel(discretize-input).
Definition at line 359 of file AnalyticFunctionFactory.cc.
AnalyticFunctionFactory::AnalyticFunctionRef AnalyticFunctionFactory::parseMultiplication (const std::string & declaration, std::string::size_type & position) const private
Creates a addition function object f(x, y) = x * y.
Declaration syntax: multiplies.
Definition at line 274 of file AnalyticFunctionFactory.cc.
AnalyticFunctionFactory::AnalyticFunctionRef AnalyticFunctionFactory::parseNesting (const std::string & declaration, std::string::size_type & position) const private
Creates a nested function object f(g(x)).
Declaration syntax: nest(g, f). Remark: f and g are swaped in declaration syntax since g changes maximal argument of f. Parsing could be improved...
Definition at line 161 of file AnalyticFunctionFactory.cc.
References create(), and Math::nest().
AnalyticFunctionFactory::AnalyticFunctionRef AnalyticFunctionFactory::parseOffset (const std::string & declaration, std::string::size_type & position) const private
Creates an offset function object f(x) = x + b.
Declaration syntax: offset(b).
Definition at line 232 of file AnalyticFunctionFactory.cc.
AnalyticFunctionFactory::AnalyticFunctionRef AnalyticFunctionFactory::parseScaling (const std::string & declaration, std::string::size_type & position) const private
Creates an scaling function object f(x) = a * x.
Declaration syntax: scaling(a).
Definition at line 245 of file AnalyticFunctionFactory.cc.
AnalyticFunctionFactory::AnalyticFunctionRef AnalyticFunctionFactory::parseSinh (const std::string & declaration, std::string::size_type & position) const private
Creates an Sinh function object f(x) = sinh(x).
Declaration syntax: sinh.
Definition at line 290 of file AnalyticFunctionFactory.cc.
AnalyticFunctionFactory::AnalyticFunctionRef AnalyticFunctionFactory::parseSubstraction (const std::string & declaration, std::string::size_type & position) const private
Creates a addition function object f(x, y) = x - y.
Declaration syntax: minus.
Definition at line 266 of file AnalyticFunctionFactory.cc.
AnalyticFunctionFactory::AnalyticFunctionRef AnalyticFunctionFactory::parseThreePieceAffineFunction (const std::string & declaration, std::string::size_type & position) const private
Creates a three-piece affine function function object (.
See also
createThreePieceAffineFunction). Declaration syntax: affine-3(a, a-shift, lower-limit, upper-limit).
Definition at line 484 of file AnalyticFunctionFactory.cc.
AnalyticFunctionFactory::AnalyticFunctionRef AnalyticFunctionFactory::parseTwoPieceLinearFunction (const std::string & declaration, std::string::size_type & position) const private
Creates a two-piece linear function function object (.
See also
createTwoPieceLinearFunction). Declaration syntax: linear-2(a, limit).
Definition at line 411 of file AnalyticFunctionFactory.cc.
The documentation for this class was generated from the following files:
AnalyticFunctionFactory.hh
AnalyticFunctionFactory.cc