Sprint: Speech::LatticeSetGenerator Class Reference
Speech::LatticeSetGenerator Class Reference
LatticeSetGenerator.
#include <LatticeSetExtractor.hh>
Public Member Functions
LatticeSetGenerator (const Core::Configuration &)
virtual void signOn (CorpusVisitor &)
Override this function to sign on to services of the corpus visitor.
virtual void processWordLattice (Lattice::ConstWordLatticeRef, Bliss::SpeechSegment *)
Override this function to implement the processing of lattice sets.
virtual void initialize (Bliss::LexiconRef)
Override this function to achieve the lexicon of the input lattice set.
virtual void setSegmentwiseFeatureExtractor (Core::Ref< SegmentwiseFeatureExtractor >)
virtual void setAlignmentGenerator (Core::Ref< PhonemeSequenceAlignmentGenerator >)
virtual bool hasNnEmissionRescorer () const
virtual void leaveCorpus (Bliss::Corpus *corpus)
Override this function to perform post processing after the last segment of the corpus.
virtual std::string name () const
virtual void logComputationTime () const
Public Member Functions inherited from Speech::LatticeSetProcessor
LatticeSetProcessor (const Core::Configuration &)
LatticeSetProcessor.
void setProcessor (Core::Ref< LatticeSetProcessor > processor)
This lattice set processor is used for cascading.
virtual void enterCorpus (Bliss::Corpus *corpus)
Override this function to perform pre processing before the first segment of the corpus.
virtual void enterRecording (Bliss::Recording *recording)
Override this function to perform pre processing before the first segment of the recording.
virtual void leaveRecording (Bliss::Recording *recording)
Override this function to perform post processing after the last segment of the recording.
virtual void enterSegment (Bliss::Segment *s)
Override this function to perform preparations before first aligned features arrive.
virtual void leaveSegment (Bliss::Segment *s)
Override this function to perform post processing after the last aligned features of the segment.
virtual void enterSpeechSegment (Bliss::SpeechSegment *s)
Override this function to perform preparations before first features arrive.
virtual void leaveSpeechSegment (Bliss::SpeechSegment *s)
Override this function to perform post processing after the last features of the segment.
virtual void getWordLatticeDescription (Lattice::WordLatticeDescription &)
Override this function to create the description of the output word lattices.
virtual void setWordLatticeDescription (const Lattice::WordLatticeDescription &)
Override this function to achieve the attributes of the input lattice set.
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Public Member Functions inherited from Speech::LatticeSetExtractor
LatticeSetExtractor (const Core::Configuration &)
Private Types
enum SearchType { exactMatch, fullSearch }
typedef LatticeSetProcessor Precursor
typedef std::vector< LatticeExtractor * > LatticeExtractors
typedef Core::Ref< PhonemeSequenceAlignmentGenerator > AlignmentGeneratorRef
Private Member Functions
void initializeExtractors ()
Core::Ref< SegmentwiseFeatureExtractor > segmentwiseFeatureExtractor ()
Returns segmentwiseFeatureExtractor_ object.
AlignmentGeneratorRef alignmentGenerator ()
Returns alignmentGenerator_ object.
void appendAcousticRescorers ()
void appendEmissionRescorers ()
void appendNnEmissionRescorers ()
void appendTheanoEmissionRescorers ()
void appendTdpRescorers ()
void appendPronunciationRescorers ()
void appendLmRescorers ()
void appendCombinedLmRescorers ()
void appendRestorers ()
void appendReaders ()
void appendDistanceRescorers ()
void appendPosteriorRescorers ()
void appendPassRescorers ()
Private Attributes
Bliss::LexiconRef lexicon_
LatticeExtractors extractors_
Core::Ref< SegmentwiseFeatureExtractor > segmentwiseFeatureExtractor_
AlignmentGeneratorRef alignmentGenerator_
std::vector< f64 > timeRescorers_
Static Private Attributes
static Core::Choice choiceSearchType
LatticeSetGenerator.
static const Core::ParameterChoice paramSearchType
static const Core::ParameterBool paramShareAcousticModel
static const Core::ParameterBool paramLoadAcoustics
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Speech::LatticeSetProcessor
f64 timeProcessSegment_
Core::Ref< LatticeSetProcessor > processor_
Protected Attributes inherited from Core::Configurable
Configuration config
Static Protected Attributes inherited from Speech::LatticeSetExtractor
static const Core::ParameterStringVector paramAcousticExtractors
LatticeSetExtractor.
static const Core::ParameterStringVector paramEmissionExtractors
static const Core::ParameterStringVector paramNnEmissionExtractors
static const Core::ParameterStringVector paramTheanoEmissionExtractors
static const Core::ParameterStringVector paramTdpExtractors
static const Core::ParameterStringVector paramPronunciationExtractors
static const Core::ParameterStringVector paramLmExtractors
static const Core::ParameterStringVector paramCombinedLmExtractors
static const Core::ParameterStringVector paramRestorers
static const Core::ParameterStringVector paramReaders
static const Core::ParameterStringVector paramDistanceExtractors
static const Core::ParameterStringVector paramPosteriorExtractors
static const Core::ParameterStringVector paramPassExtractors
Detailed Description
LatticeSetGenerator.
Definition at line 67 of file LatticeSetExtractor.hh.
Member Function Documentation
LatticeSetGenerator::AlignmentGeneratorRef LatticeSetGenerator::alignmentGenerator () private
Returns alignmentGenerator_ object.
Object is created only on-demand thus the first time this function is called.
Definition at line 146 of file LatticeSetExtractor.cc.
References Speech::DistanceLatticeRescorer::createDistanceLatticeRescorer(), Core::Component::criticalError(), Core::Component::error(), Core::Component::log(), Core::ref(), Core::Component::respondToDelayedErrors(), Speech::SegmentwiseAlignmentGenerator::setSegmentwiseFeatureExtractor(), and verify.
void LatticeSetGenerator::initialize (Bliss::LexiconRef lexicon) virtual
Override this function to achieve the lexicon of the input lattice set.
Reimplemented from Speech::LatticeSetProcessor.
Definition at line 460 of file LatticeSetExtractor.cc.
References Core::Component::error(), and Core::Component::initialize().
void LatticeSetGenerator::leaveCorpus (Bliss::Corpus * corpus) virtual
Override this function to perform post processing after the last segment of the corpus.
Reimplemented from Speech::LatticeSetProcessor.
Definition at line 493 of file LatticeSetExtractor.cc.
References Speech::LatticeSetProcessor::leaveCorpus().
void LatticeSetGenerator::processWordLattice (Lattice::ConstWordLatticeRef lattice, Bliss::SpeechSegment * s) virtual
Override this function to implement the processing of lattice sets.
Reimplemented from Speech::LatticeSetProcessor.
Definition at line 422 of file LatticeSetExtractor.cc.
References Core::Component::log(), and Core::Component::warning().
Core::Ref< SegmentwiseFeatureExtractor > LatticeSetGenerator::segmentwiseFeatureExtractor () private
Returns segmentwiseFeatureExtractor_ object.
Object is created only on-demand thus the first time this function is called.
Definition at line 138 of file LatticeSetExtractor.cc.
References Core::ref().
void LatticeSetGenerator::signOn (CorpusVisitor & corpusVisitor) virtual
Override this function to sign on to services of the corpus visitor.
Note: call the signOn function of your predecessor.
Reimplemented from Speech::LatticeSetProcessor.
Definition at line 408 of file LatticeSetExtractor.cc.
Member Data Documentation
Core::Choice LatticeSetGenerator::choiceSearchType static private
LatticeSetGenerator.
Definition at line 76 of file LatticeSetExtractor.hh.
The documentation for this class was generated from the following files:
LatticeSetExtractor.hh
LatticeSetExtractor.cc