Sprint: AcousticModelTrainer Class Reference
AcousticModelTrainer Class Reference
Copyright 2020 RWTH Aachen University.
#include <AcousticModelTrainer.hh>
Public Types
enum Action {
actionNotGiven, actionDryRun, actionCreateModelAcceptors, actionShowMixtureSet,
actionConvertMixtureSet, actionClusterMixtureSet, actionCombineMixtureSets, actionCombineMixtureSetEstimators,
actionMapMixtureSet, actionAccumulateMixtureSetTextDependent, actionAccumulateMixtureSetTextDependentTied, actionAccumulateMixtureSetTextIndependent,
actionAccumulateTdcSumFile, actionCombineTdcSumFile, actionAccumulateCartExamples, actionMergeCartExamples,
actionEstimateCart, actionConvertMixtureSetToMixtureSetEstimator, actionScoreFeatures, actionEstimateScatterMatricesTextDependent,
actionEstimateScatterMatricesTextIndependent, actionEstimateLdaTextDependent, actionEstimateLdaTextIndependent, actionCombineScatterMatrixAccumulators,
actionEstimateScatterMatricesFromScatterMatrixAccumulator, actionEstimateLdaFromScatterMatrixAccumulator, actionEstimateLda, actionEstimateAffineFeatureTransform,
actionCalculateAffineFeatureTransform, actionCombineAffineFeatureTransformEstimators, actionScoreAffineFeatureTransform, actionEstimateModelTransform,
actionCalculateModelTransform, actionAccumulateNearestNeighborTree, actionCalculateAverageFeatureScorerActivation
}
Public Member Functions
virtual std::string getUsage () const
Overload this method to describe the usage of the application and to give a (short) description of the application.
virtual int main (const std::vector< std::string > &arguments)
Main entry point for an application.
Public Member Functions inherited from Core::Application
virtual std::string getVariable () const
Return the name of the environment variable.
std::string getBaseName () const
Return the applications basename.
std::string getPath () const
Return the applications path.
virtual std::string getApplicationDescription () const
virtual std::string getParameterDescription () const
virtual std::string getDefaultParameterDescription () const
void reportLowLevelError (const std::string &msg="")
Errors messages are collected and later (during closeLogging()) printed to the error channel.
void setDefaultLoadConfigurationFile (bool f)
Configure default behaviour of loading a configuration file.
void setDefaultOutputXmlHeader (bool f)
Configure default behaviour of adding a valid xml header to standard channels.
void setTitle (const std::string &t)
Set the title of the application.
void setCommentCharacters (const std::string &c)
Set the set of possible comment characters for this application.
const std::string & getCommentCharacters (void) const
Return the string of comment characters.
Core::Channel & debugChannel (void)
Returns the debug binary outpput channel.
Core::XmlChannel & debugXmlChannel (void)
Returns the debug XML channel.
MappedArchiveReader getCacheArchiveReader (const std::string &archive_name, const std::string &item)
Returns a pointer to the cache-archive reader for the archive, and the specified item contained by the archive.
MappedArchiveWriter getCacheArchiveWriter (const std::string &archive_name, const std::string &item)
Returns a pointer to the cache-archive writer for the archive, and the specified item contained by the archive.
void exit (int status)
Terminate program execution.
void atexit (std::function< void()> f)
Like std::atexit() but will be execute sooner, at our own uninit, at the end of our main(), or in our exit().
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Attributes
static const Core::Choice choiceAction
Copyright 2020 RWTH Aachen University.
static const Core::ParameterChoice paramAction
static const Core::ParameterBool paramMixtureSetFilenamesToCombineUseComma
static const Core::ParameterStringVector paramMixtureSetFilenamesToCombine
static const Core::ParameterStringVector paramMixtureSetFilenamesToCombineComma
static const Core::ParameterString paramMappingFilenameToMap
static const Core::ParameterBool paramForceExampleRegeneration
Private Member Functions
void visitCorpus (Speech::CorpusProcessor &)
void visitCorpus (Speech::CorpusProcessor *)
Passes ones over the whole corpus contolling the CorpusProcessor object.
void visitCorpus (Speech::AlignedFeatureProcessor &)
void visitCorpus (Speech::LabeledFeatureProcessor &)
void dryRun ()
void createModelAcceptors ()
void showMixtureSet ()
Print the mixture set estimator in XML format.
void convertMixtureSet ()
void clusterMixtureSet ()
void combineMixtureSets ()
void mapAdaptation ()
void combineMixtureSetEstimators ()
void mapMixtureSet ()
void accumulateMixtureSetTextDependent ()
void accumulateMixtureSetTextDependentTied ()
void accumulateMixtureSetTextIndependent ()
void accumulateTdcSumFile ()
void combineTdcSumFile ()
void accumulateCartExamples ()
void mergeCartExamples ()
void estimateCart ()
void convertMixtureSetToMixtureSetEstimator ()
void convertMixtureSetToLogLinearMixtureSet ()
void scoreFeatures ()
void estimateScatterMatricesTextDependent ()
void estimateScatterMatricesTextIndependent ()
void estimateLdaTextDependent ()
void estimateLdaTextIndependent ()
void combineScatterMatrixAccumulators ()
void estimateScatterMatricesFromScatterMatrixAccumulator ()
void estimateLdaFromScatterMatrixAccumulator ()
void estimateLda (Signal::ScatterMatricesEstimator &estimator)
void estimateLda ()
void estimateAffineFeatureTransform ()
void calculateAffineFeatureTransform ()
void combineAffineFeatureTransformEstimators ()
void scoreAffineFeatureTransform ()
void scoreAffineFeatureTransform2 ()
void estimateModelTransform ()
void calculateModelTransform ()
void accumulateNearestNeighborTree ()
void accumulateWeightHistogram ()
void calculateAverageFeatureScorerActivation ()
Additional Inherited Members
Static Public Member Functions inherited from Core::Application
static Application * us ()
Get the global instance of the application (Singleton)
static int main (int argc, char *argv[])
private
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Application
void logSystemInfo () const
void logVersion () const
void logResources () const
void logResourceUsage () const
void logMemoryUsage () const
MappedArchive * getCacheArchive (const std::string &archive)
void openLogging ()
Opens channels and makes initial logs.
void closeLogging (bool configAvailable=true)
Closes down channels and makes final logs.
int run (const std::vector< std::string > &arguments)
void runAtExitFuncs ()
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Static Protected Member Functions inherited from Core::Application
static bool setFromEnvironment (const std::string &variable)
static bool setFromFile (const std::string &filename)
static std::vector< std::string > setFromCommandline (const std::vector< std::string > &arguments)
Protected Attributes inherited from Core::Application
Channel::Manager * channelManager_
Core::Channel * debugChannel_
Core::XmlChannel * debugXmlChannel_
std::map< std::string, MappedArchive * > cacheArchives_
bool defaultLoadConfigurationFile_
bool defaultOutputXmlHeader_
std::string comment_
std::string configFileName_
Timer timer_
std::list< std::function< void()> > atExitFuncs_
Protected Attributes inherited from Core::Configurable
Configuration config
Static Protected Attributes inherited from Core::Application
static const ParameterBool paramLogConfiguration
static const ParameterBool paramLogResolvedResources
static const ParameterString paramConfig
static const ParameterString paramCacheArchiveFile
static const ParameterBool paramCacheArchiveReadOnly
static const ParameterBool paramHelp
static std::string path_ = "."
static std::string basename_ = ""
static Application * app_ = 0
Detailed Description
Copyright 2020 RWTH Aachen University.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. Actions:
dry: drives an aligner (given in *.aligner.type). Useful for generating and saving an alignment.
create-model-acceptors: activates the model-acceptor-cache object for each segment of the corpus
show-mixture-set: dumps mixture set in XML format
combine-mixture-sets: combines mixture sets given in old-mixture-set-template and old-mixture-set-ids
map-mixture-set: maps mixture set given mapping file
accumulate-mixture-set-text-dependent: mixtures set estimator accumulates features according to a given alignment
accumulate-mixture-set-ext-independent: mixtures set estimator accumulates features for set of acoustic conditions
accumulate-tdc-sum: decision tree sum file estimator accumulates features according to a given alignment
accumulate-discriminatively: mixtures set estimator discriminatively accumulates features according to a given (weighted) alignment
score-features: acoustic scores of a given alignment accumulated for set of acoustic conditions
estimate-scatter-matrices-text-dependent: estimates between and within class scatter matrices according to a given alignment
estimate-scatter-matrices-text-independent: estimates between and within class scatter matrices according to set of acoustic conditions
estimate-lda-text-dependent: creates projector matrix by LDA according to a given alignment
estimate-lda-text-independent: creates projector matrix by LDA according to set of acoustic conditions
estimate-lda: creates projector matrix by LDA based reading scatter matrices form files.
accumulate-weight-histogram: generates a histogram over all state weights in the alignment The target histogram file is set using the parameter weight-histogram-accumulator.histogram-file
Corpus description: configured in the selection "corpus" Aligner: configured in the selection "aligner"
See also
Speech::Application Trainers: E.g.: accumulater, scorer etc are configured in the selection "trainer"
Definition at line 52 of file Tools/AcousticModelTrainer/AcousticModelTrainer.hh.
Member Function Documentation
virtual std::string AcousticModelTrainer::getUsage () const inline virtual
Overload this method to describe the usage of the application and to give a (short) description of the application.
Default return string is "usage: " + getBaseName() + "[OPTION(S)]\n" Return the usage of the application.
Normally, that method does not have to be overloaded; overload getApplicationDescription() and getParamterDescription() and getDefaultParameterDescription() instead.
Reimplemented from Core::Application.
Definition at line 164 of file Tools/AcousticModelTrainer/AcousticModelTrainer.hh.
References main().
int AcousticModelTrainer::main (const std::vector< std::string > & arguments) virtual
Main entry point for an application.
Implements Core::Application.
Definition at line 136 of file Tools/AcousticModelTrainer/AcousticModelTrainer.cc.
References Core::Component::criticalError(), Core::Component::log(), and showMixtureSet().
Referenced by getUsage().
void AcousticModelTrainer::scoreAffineFeatureTransform2 () private
Todo:
give these functions a more descriptive name!
void AcousticModelTrainer::showMixtureSet () private
Print the mixture set estimator in XML format.
Following parameter combinations are supported:
old-mixture-set-file prints the mixture
old-mixture-set-file lexicon.file state-tying.type=monophone prints monophone state labels for each mixture (context is arbitrary)
old-mixture-set-file lexicon.file state-tying.type=cart state-tying.file=cart.xml prints cart labels for each mixture (i.e. mixture number)
Definition at line 262 of file Tools/AcousticModelTrainer/AcousticModelTrainer.cc.
References Bliss::CorpusDescription::accept(), Bliss::Lexicon::create(), Core::Component::criticalError(), Core::Component::error(), Core::Configuration::get(), Core::Component::log(), Speech::MixtureSetTrainer::paramOldMixtureSetFilename, Speech::AffineFeatureTransformEstimator::postProcess(), Core::ref(), Speech::CorpusProcessor::signOn(), Core::Application::us(), Signal::LinearDiscriminantAnalysis::work(), and Signal::ScatterTransform::write().
Referenced by main().
void AcousticModelTrainer::visitCorpus (Speech::CorpusProcessor * corpusProcessor) private
Passes ones over the whole corpus contolling the CorpusProcessor object.
Note: CorpusProcessor object is destroyed in the end.
Definition at line 563 of file Tools/AcousticModelTrainer/AcousticModelTrainer.cc.
Member Data Documentation
const Core::Choice AcousticModelTrainer::choiceAction static
Copyright 2020 RWTH Aachen University.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Definition at line 92 of file Tools/AcousticModelTrainer/AcousticModelTrainer.hh.
The documentation for this class was generated from the following files:
Tools/AcousticModelTrainer/AcousticModelTrainer.hh
Tools/AcousticModelTrainer/AcousticModelTrainer.cc