Sprint: Nn::PythonFeatureScorer Class Reference
Nn::PythonFeatureScorer Class Reference
Classes
class ContextScorer
Stores the current feature and the number of buffered features.
Public Types
typedef Core::Ref< const ContextScorer > Scorer
Public Types inherited from Mm::FeatureScorer
typedef Core::Ref< const ContextScorer > Scorer
Public Member Functions
PythonFeatureScorer (const Core::Configuration &c, Core::Ref< const Mm::MixtureSet > mixtureSet)
virtual Mm::EmissionIndex nMixtures () const
virtual void getFeatureDescription (Mm::FeatureDescription &description) const
virtual FeatureScorer::Scorer getScorer (Core::Ref< const Mm::Feature > f) const
Return a scorer for the current feature and append the given feature to the buffer.
virtual FeatureScorer::Scorer getScorer (const Mm::FeatureVector &f) const
virtual Mm::Score getScore (Mm::EmissionIndex e, u32 position) const
virtual void reset () const
reset should be overloaded/defined in/for featurescorer related to sign language recognition especially the tracking part
virtual void finalize () const
finalize should be overloaded/defined in classes using embedded flow networks to sent final end of sequence token if necessary
virtual bool isBuffered () const
Return true if the feature scorer buffers features.
virtual void addFeature (const Mm::FeatureVector &f) const
Add a feature to the feature buffer.
virtual void addFeature (Core::Ref< const Mm::Feature > f) const
virtual Mm::FeatureScorer::Scorer flush () const
Return a scorer for the current feature without adding a new feature to the buffer.
virtual bool bufferFilled () const
Return true if the feature buffer is full.
virtual bool bufferEmpty () const
Return true if the feature buffer is empty.
virtual u32 bufferSize () const
Return the number of buffered features required to execute getScorer().
virtual bool hasTimeIndexedCache () const
Like CachedNeuralNetworkFeatureScorer, used in SegmentwiseAlignmentGenerator.
virtual FeatureScorer::Scorer getTimeIndexedScorer (u32 time) const
Public Member Functions inherited from Mm::FeatureScorer
FeatureScorer (const Core::Configuration &c)
virtual void getDependencies (Core::DependencySet &dependencies) const
virtual Scorer getScorer (const FeatureVector &) const =0
virtual void setSegmentName (const std::string name) const
setSegmentName should be overloaded/defined in classes using embedded flow networks to create unambiguous ids for cache nodes
virtual void addFeature (const FeatureVector &f) const
Add a feature to the feature buffer.
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Protected Types
typedef Mm::FeatureScorer Precursor
typedef Mm::Score Float
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Attributes
u32 featureBufferSize_
u32 numFeaturesReceived_
u32 currentFeature_
bool scoresComputed_
std::vector< Mm::Score > scoresCache_
u32 scoresCachePosition_
u32 nClasses_
u32 inputDimension_
u32 batchIteration_
Nn::PythonControl pythonControl_
Protected Attributes inherited from Core::Configurable
Configuration config
Private Member Functions
void _addFeature (const Mm::FeatureVector &f) const
Additional Inherited Members
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Detailed Description
Definition at line 30 of file PythonFeatureScorer.hh.
Member Function Documentation
void Nn::PythonFeatureScorer::addFeature (const Mm::FeatureVector & f) const virtual
Add a feature to the feature buffer.
Definition at line 141 of file PythonFeatureScorer.cc.
Referenced by isBuffered().
bool Nn::PythonFeatureScorer::bufferEmpty () const virtual
Return true if the feature buffer is empty.
Reimplemented from Mm::FeatureScorer.
Definition at line 221 of file PythonFeatureScorer.cc.
Referenced by isBuffered().
bool Nn::PythonFeatureScorer::bufferFilled () const virtual
Return true if the feature buffer is full.
Reimplemented from Mm::FeatureScorer.
Definition at line 218 of file PythonFeatureScorer.cc.
Referenced by isBuffered().
u32 Nn::PythonFeatureScorer::bufferSize () const virtual
Return the number of buffered features required to execute getScorer().
This will be MAX_INT for this class, because there is no limit. Normally, you would just use bufferFilled()/bufferEmpy() instead.
Reimplemented from Mm::FeatureScorer.
Definition at line 224 of file PythonFeatureScorer.cc.
Referenced by isBuffered().
virtual void Nn::PythonFeatureScorer::finalize (void) const inline virtual
finalize should be overloaded/defined in classes using embedded flow networks to sent final end of sequence token if necessary
Reimplemented from Mm::FeatureScorer.
Definition at line 87 of file PythonFeatureScorer.hh.
Mm::FeatureScorer::Scorer Nn::PythonFeatureScorer::flush () const virtual
Return a scorer for the current feature without adding a new feature to the buffer.
Should be called until bufferEmpty() == true. Requires bufferEmpty() == false. Implementation required if isBuffered() == true
Reimplemented from Mm::FeatureScorer.
Definition at line 174 of file PythonFeatureScorer.cc.
References Core::Component::criticalError().
Referenced by isBuffered().
virtual FeatureScorer::Scorer Nn::PythonFeatureScorer::getScorer (Core::Ref< const Mm::Feature > f) const inline virtual
Return a scorer for the current feature and append the given feature to the buffer.
The current feature may not be the same as f because of the feature buffering. Requires bufferFilled() == true.
Implements Mm::FeatureScorer.
Definition at line 67 of file PythonFeatureScorer.hh.
References Mm::Feature::mainStream(), and reset().
Referenced by reset().
virtual bool Nn::PythonFeatureScorer::hasTimeIndexedCache () const inline virtual
Like CachedNeuralNetworkFeatureScorer, used in SegmentwiseAlignmentGenerator.
Reimplemented from Mm::FeatureScorer.
Definition at line 134 of file PythonFeatureScorer.hh.
virtual bool Nn::PythonFeatureScorer::isBuffered () const inline virtual
Return true if the feature scorer buffers features.
Reimplemented from Mm::FeatureScorer.
Definition at line 92 of file PythonFeatureScorer.hh.
References addFeature(), bufferEmpty(), bufferFilled(), bufferSize(), flush(), and Mm::Feature::mainStream().
void Nn::PythonFeatureScorer::reset (void) const virtual
reset should be overloaded/defined in/for featurescorer related to sign language recognition especially the tracking part
Reimplemented from Mm::FeatureScorer.
Definition at line 148 of file PythonFeatureScorer.cc.
References getScorer(), and Core::Description::Stream::setValue().
Referenced by getScorer().
The documentation for this class was generated from the following files:
PythonFeatureScorer.hh
PythonFeatureScorer.cc