Sprint: Signal::CorrFullCovMonoGaussianModel Class Reference
Signal::CorrFullCovMonoGaussianModel Class Reference
Public Member Functions
CorrFullCovMonoGaussianModel (u32 dim)
CorrFullCovMonoGaussianModel (u32 dim, f32 alpha)
CorrFullCovMonoGaussianModel (u32 dim, f32 alpha, const std::vector< CorrFullCovMonoGaussianModel > &models)
CorrFullCovMonoGaussianModel (u32 dim, const std::vector< CorrFullCovMonoGaussianModel > &models)
const Math::Vector< f32 > relativeFeature () const
const f32 score () const
void reset (f32 alpha)
updates the alpha weighting parmameter for the relative feature normalizrtion
void relativeFeatureNormalize (f32 weight)
weights and normalizes the relative feature vector (i.e.
void refresh ()
is rather an init function which initializes the relative features by the weighted and normalized relative likelihoods of its models
void correlationDistance (CorrFullCovMonoGaussianModel &x, CorrFullCovMonoGaussianModel &y)
calulate the correlation-based distance between the left model x and right model y
void mergeModels (CorrFullCovMonoGaussianModel &x, CorrFullCovMonoGaussianModel &y)
merges the left model x and right model y into the current model and calculate the correlation distance
void finalize (const std::vector< CorrFullCovMonoGaussianModel > &models)
finalize the current model and assign a new model-vector models
Public Member Functions inherited from Signal::BICFullCovMonoGaussianModel
BICFullCovMonoGaussianModel (u32 dim)
BICFullCovMonoGaussianModel (u32 dim, f32 alpha)
BICFullCovMonoGaussianModel (u32 dim, const std::vector< BICFullCovMonoGaussianModel > &models)
BICFullCovMonoGaussianModel (u32 dim, f32 alpha, const std::vector< BICFullCovMonoGaussianModel > &models)
const f32 likelihood () const
const f32 score () const
const f32 stopscore () const
void computeGLR (const BICFullCovMonoGaussianModel &x, const BICFullCovMonoGaussianModel &y)
compute Brandt's generalized likelihood ratio (GLR) for the BIC criterion.
void finalize (const std::vector< BICFullCovMonoGaussianModel >)
useless??
void finalize ()
finalize the mean vector and variance matrix
void mergeModels (const BICFullCovMonoGaussianModel &x, const BICFullCovMonoGaussianModel &y)
First, the mean vectors and variance matrices of the left FullCovMonoGaussianModel x and right FullCovMonoGaussianModel y are merged into the current model.
Public Member Functions inherited from Signal::FullCovMonoGaussianModel
FullCovMonoGaussianModel (u32 dim)
represented as N(logDeterminant(variance))
const u32 dim () const
returns the feature dimension
const u32 nFrames () const
returns the number of frames seen so far
const Math::Vector< f64 > & mean () const
returns the mean vector of size dim()
const Math::Matrix< f64 > & variance () const
returns the variance matrix of size dim()xdim()
bool accumulate (const std::vector< f32 > &vec)
update the mean vector, the variance matrix, and the frame count
bool finalize ()
finalize the mean vector and variance matrix
void mergeModels (const FullCovMonoGaussianModel &x, const FullCovMonoGaussianModel &y)
merges the mean vectors and variance matrices of the left FullCovMonoGaussianModel x and right FullCovMonoGaussianModel y into the current model.
void mergeMeans (const FullCovMonoGaussianModel &x, const FullCovMonoGaussianModel &y)
merges the mean vectors of the left FullCovMonoGaussianModel x and right FullCovMonoGaussianModel y
void mergeVariance (const FullCovMonoGaussianModel &x, const FullCovMonoGaussianModel &y)
merges the variance matrices of the left FullCovMonoGaussianModel x and right FullCovMonoGaussianModel y
void reset (f32 x)
?
const f32 computeComplexity ()
BIC is a likelihood criterion penalized by the model complexity: the number of parameters in the model.
void computeL ()
compute the likelihood as N(logDeterminant(variance))
const f32 relativeLikelihood (const FullCovMonoGaussianModel &x) const
compute the relative likelihood
Private Attributes
Math::Vector< f32 > relativeFeature_
bool refresh_
f32 corrdist_
f32 alpha_
const std::vector< CorrFullCovMonoGaussianModel > * models_
Additional Inherited Members
Protected Attributes inherited from Signal::FullCovMonoGaussianModel
Math::Vector< f64 > mean_
Math::Matrix< f64 > variance_
u32 nFrames_
f32 likelihood_
Detailed Description
Definition at line 256 of file SegmentClustering.hh.
Member Function Documentation
void CorrFullCovMonoGaussianModel::correlationDistance (CorrFullCovMonoGaussianModel & x, CorrFullCovMonoGaussianModel & y)
calulate the correlation-based distance between the left model x and right model y
Definition at line 187 of file SegmentClustering.cc.
References refresh(), and relativeFeature().
void CorrFullCovMonoGaussianModel::finalize (const std::vector< CorrFullCovMonoGaussianModel > & models)
finalize the current model and assign a new model-vector models
Definition at line 200 of file SegmentClustering.cc.
References Signal::BICFullCovMonoGaussianModel::finalize().
void CorrFullCovMonoGaussianModel::mergeModels (CorrFullCovMonoGaussianModel & x, CorrFullCovMonoGaussianModel & y)
merges the left model x and right model y into the current model and calculate the correlation distance
Definition at line 195 of file SegmentClustering.cc.
References Signal::BICFullCovMonoGaussianModel::mergeModels().
void CorrFullCovMonoGaussianModel::refresh ()
is rather an init function which initializes the relative features by the weighted and normalized relative likelihoods of its models
Todo:
: this should be a private function
Definition at line 177 of file SegmentClustering.cc.
Referenced by correlationDistance().
const Math::Vector<f32> Signal::CorrFullCovMonoGaussianModel::relativeFeature () const inline
Returns
the relative feature vector
Definition at line 293 of file SegmentClustering.hh.
Referenced by correlationDistance().
void CorrFullCovMonoGaussianModel::relativeFeatureNormalize (f32 weight)
weights and normalizes the relative feature vector (i.e.
the relative likelihoods of all models are weighted by a factor alpha)
Todo:
: this should be a private function
Definition at line 166 of file SegmentClustering.cc.
void Signal::CorrFullCovMonoGaussianModel::reset (f32 alpha) inline
updates the alpha weighting parmameter for the relative feature normalizrtion
Definition at line 303 of file SegmentClustering.hh.
const f32 Signal::CorrFullCovMonoGaussianModel::score () const inline
Returns
the correlation based distance
Definition at line 298 of file SegmentClustering.hh.
The documentation for this class was generated from the following files:
SegmentClustering.hh
SegmentClustering.cc