Sprint: Signal::CosineTransformNode Class Reference
Signal::CosineTransformNode Class Reference
Cosine Transform Node Performs cosine transform with several options: -arbitrary integrated warping function.
#include <CosineTransform.hh>
Public Member Functions
CosineTransformNode (const Core::Configuration &c)
Flow::PortId getInput (const std::string &name)
Ask for an input port.
Flow::PortId getOutput (const std::string &name)
Ask for an output port.
virtual bool setParameter (const std::string &name, const std::string &value)
Set node specific parameter.
virtual bool configure ()
Performs static (independent of input data) configuration of node.
virtual bool work (Flow::PortId p)
Processes some data.
Public Member Functions inherited from Flow::StringExpressionNode
StringExpressionNode (const Core::Configuration &c, PortId firstPortId)
void setTemplate (const std::string &)
bool configure (Attributes &result)
Performs configuration and merges its own input attributes into.
bool update (const Timestamp &timestamp)
Reads the input ports and resolves the string expression.
bool update ()
update without timestamp consideration
std::string value ()
void reset ()
Public Member Functions inherited from Flow::Node
Node (const Core::Configuration &c)
Public Member Functions inherited from Flow::AbstractNode
AbstractNode (const Core::Configuration &c)
virtual void Run ()
void setThreaded (bool threaded=true)
void setThreaded (const std::string &threaded)
bool isThreaded () const
virtual bool addParameter (const std::string &name, const Core::StringExpression &value)
addParameter adds a parameter to the node Constant parameters are simply delegated to setParameter, parameters dependent on network parameters are stored in parameters_.
virtual ssize_t getRemainingDataLen (PortId out)
Returns the amount of remaining data items.
void addUnresolvedParameter (const std::string &key, const std::string &value)
Functions for saving and getting unresolved parameters.
const UnresolvedAttributes & unresolvedAttributes () const
bool operator< (const AbstractNode &n) const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Member Functions
static std::string filterName ()
Static Public Member Functions inherited from Flow::StringExpressionNode
static std::string filterName ()
Static Public Attributes
static const Core::Choice choiceInputType
static const Core::ParameterChoice paramInputType
static const Core::ParameterInt paramOutputSize
static const Core::ParameterBool paramNormalize
static const Core::ParameterString paramWarpingFunction
static const Core::ParameterBool paramWarpDifferentialUnit
Static Public Attributes inherited from Flow::AbstractNode
static const Core::ParameterBool paramThreaded
static const Core::ParameterBool paramIgnoreUnknownParameters
Private Member Functions
void setInputType (InputType inputType)
void setOutputSize (size_t size)
void setNormalize (bool normalize)
Sets if result should be normalized by input length N For definition of N.
void setFrequencyDomainSampleRate (f64 s)
Sets sample rate of input.
f64 timeDomainSampleRate (size_t inputSize)
Calculates the time domain sample rate of the input.
Math::UnaryAnalyticFunctionRef createWarpingFunction (f64 sampleRate)
void setWarpDifferentialUnit (bool should)
void init (size_t inputSize)
Private Member Functions inherited from Signal::CosineTransform
void init (InputType inputType, size_t inputSize, size_t outputSize, bool normalize=false)
void init (InputType inputType, size_t inputSize, size_t outputSize, bool normalize, Math::UnaryAnalyticFunctionRef, bool shouldWarpDifferentialUnit)
void apply (const std::vector< Value > &in, std::vector< Value > &out) const
Calculates cosinus transform of.
size_t inputSize () const
Private Attributes
InputType inputType_
size_t outputSize_
f64 frequencyDomainSampleRate_
bool normalize_
bool shouldWarpDifferenctialUnit_
bool needInit_
Additional Inherited Members
Public Types inherited from Flow::AbstractNode
typedef std::map< std::string, std::string > UnresolvedAttributes
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Flow::Node
virtual PortId connectInputPort (PortId, Link *)
Connect link to input port.
virtual void disconnectInputLink (Link *)
virtual PortId connectOutputPort (PortId, Link *)
virtual void disconnectOutputLink (Link *)
PortId addInput (PortId in=IllegalPortId)
Create an input port.
PortId addInputs (u32 nPorts)
Create several input ports.
virtual PortId nInputs () const
Link * getInputLink (PortId in) const
virtual PortId inputConnected (PortId in) const
bool validInputPort (PortId in) const
PortId addOutput (PortId out=IllegalPortId)
Add an output port.
PortId addOutputs (u32 nPorts)
Create several output ports.
virtual PortId nOutputs () const
bool validOutputPort (PortId out) const
virtual u32 nOutputLinks (PortId out) const
Number of link connceted to an output port.
bool configureDatatype (Core::Ref< const Attributes > a, const Datatype *d)
template<class T >
bool getData (PortId in, DataPtr< T > &d)
Fetch data packet from input port.
virtual bool putData (PortId out, Data *d)
Send data packet on output port.
bool putEos (PortId out)
Send end-of-stream on output port.
bool putOod (PortId out)
Send out-of-data on output port.
Core::Ref< const Attributes > getInputAttributes (PortId in)
Retrieve attribute set from input port.
void getInputAttributes (PortId, Attributes &)
bool putOutputAttributes (PortId out, Core::Ref< const Attributes > a)
Put attribute set on output port.
void eraseOutputAttributes ()
Erases attributes of all output links recursively.
Protected Member Functions inherited from Flow::AbstractNode
template<class T >
bool getData (Link *l, DataPtr< T > &d)
Fetch data packet from the "from" port of link.
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Private Types inherited from Signal::CosineTransform
enum InputType { NplusOneData, evenAboutNminusHalf }
typedef f32 Value
Detailed Description
Cosine Transform Node Performs cosine transform with several options: -arbitrary integrated warping function.
-"N+1" and "even about N-1/2" input types -sample rate handling motivated by inverse fourier transform.
Parameter warping-function:
See also
FilterbankNode.
Definition at line 86 of file CosineTransform.hh.
Member Function Documentation
bool CosineTransformNode::configure () virtual
Performs static (independent of input data) configuration of node.
Configure is called if one of the output attributes is not available. Override this function to evaluate all input attributes and pass them on to successor nodes. The default implementation simply forwards the merged attributes from all input links to all outputs. Note: -we assume no dead inputs here. -This function is the safest point to reset the algorithms used by the node. The alternative would be to reset the algorithms when a non-data object has been recieved. This solution can lead easily to unintended behaviour, since it is not garatinteed at all that every node receives for example a EOS object!
Reimplemented from Flow::Node.
Definition at line 199 of file CosineTransform.cc.
Flow::PortId Signal::CosineTransformNode::getInput (const std::string &) inline virtual
Ask for an input port.
Implement this function to provide a mapping form names to port IDs. Consider using a Core::Choice. Remeber to create ports using addInput().
Returns
a valid port ID or IllegalPortId if there is to such port.
Reimplemented from Flow::StringExpressionNode.
Definition at line 163 of file CosineTransform.hh.
Flow::PortId Signal::CosineTransformNode::getOutput (const std::string &) inline virtual
Ask for an output port.
Implement this function to provide a mapping form names to port IDs. Consider using a Core::Choice. Remeber to create ports using addOutput().
Returns
a valid port ID or IllegalPortId if there is to such port.
Reimplemented from Flow::Node.
Definition at line 166 of file CosineTransform.hh.
void Signal::CosineTransformNode::setFrequencyDomainSampleRate (f64 s) inline private
Sets sample rate of input.
For motivation of sample rate
See also
timeDomainSampleRate.
Definition at line 128 of file CosineTransform.hh.
void Signal::CosineTransformNode::setNormalize (bool normalize) inline private
Sets if result should be normalized by input length N For definition of N.
See also
CosineTransform.
Definition at line 119 of file CosineTransform.hh.
bool CosineTransformNode::setParameter (const std::string & name, const std::string & value) virtual
Set node specific parameter.
Implement this template function to handle parameters specific to your Node.
Parameters
name name of parameter
value new value for the parameter
Returns
true if successful, false if parameter name is not understood.
Reimplemented from Flow::AbstractNode.
Definition at line 183 of file CosineTransform.cc.
f64 CosineTransformNode::timeDomainSampleRate (size_t inputSize) private
Calculates the time domain sample rate of the input.
Motivation: Since discrete cosine transform does not handle sample rate, conversion of sample rate is based on the similarity of cosine transform to inverse Fourier transform. Thus, input is assumed to be in frequency domain and output will be transformed into time domain. Further assumption is that input is only the first half of a symmetric function (similar to amplitude spectrum.). Formulas: -"N+1" input type: time-sample-rate = 2 * (inputSize - 1) / frequency-sample-rate. -"even about N-1/2" input type: time-sample-rate = 2 * inputSize / frequency-sample-rate.
Definition at line 147 of file CosineTransform.cc.
References Math::AnalyticFunctionFactory::createIdentity(), Math::AnalyticFunctionFactory::createUnaryFunction(), Core::Component::error(), Math::AnalyticFunctionFactory::normalizedOmegaDomain, require, and Core::Ref< T >::reset().
bool CosineTransformNode::work (Flow::PortId out) virtual
Processes some data.
Implement this function to do whatever your node is supposed to. You are required to produce at least one packet of data on the specified output out. You may send more packets, also to other outputs.
Returns
true on success, false on end-of-file or error. The idiom is:
return putData(out, d);
Implements Flow::Node.
Definition at line 212 of file CosineTransform.cc.
References Core::Component::criticalError().
The documentation for this class was generated from the following files:
CosineTransform.hh
CosineTransform.cc