Sprint: Speech::AllophoneStateGraphBuilder Class Reference
Speech::AllophoneStateGraphBuilder Class Reference
AllophoneStateGraphBuilder.
#include <AllophoneStateGraphBuilder.hh>
Classes
struct FinalizationFunctor
Converts a call to one of the finalizeTransducer functions into a functor.
struct Functor
Converts a call to one of the build functions into a functor.
class FunctorBase
Base class for build-functor classes.
struct TransducerFunctor
Converts a call to one of the buildTransducer functions into a functor.
Public Types
enum InputLevel { lemma, phone }
Builds allophone state acceptor for phoneme loops, cf.
Public Member Functions
AllophoneStateGraphBuilder (const Core::Configuration &, Core::Ref< const Bliss::Lexicon > lexicon, Core::Ref< const Am::AcousticModel > acousticModel, bool flatModelAcceptor=false)
void addSilenceOrNoise (const Bliss::Pronunciation *)
void addSilenceOrNoise (const Bliss::Lemma *lemma)
void setSilencesAndNoises (const std::vector< std::string > &)
AllophoneStateGraphRef build (const std::string &orth)
Builds allophone state acceptor from an orthography.
AllophoneStateGraphRef build (std::tuple< const std::string & > const &t)
AllophoneStateGraphRef build (const std::string &orth, const std::string &leftContextOrth, const std::string &rightContextOrth)
AllophoneStateGraphRef build (std::tuple< const std::string &, const std::string &, const std::string & > const &t)
Functor< const std::string > createFunctor (const std::string &id, const std::string &orth)
Functor< const std::string, const std::string, const std::string > createFunctor (const std::string &id, const std::string &orth, const std::string &leftContextOrth, const std::string &rightContextOrth)
Functor< const std::string > createFunctor (const Bliss::SpeechSegment &s)
AllophoneStateGraphRef build (const InputLevel &level)
AllophoneStateGraphRef build (std::tuple< const InputLevel & > const &t)
Functor< const InputLevel > createFunctor (const std::string &id, const InputLevel &level)
AllophoneStateGraphRef build (const Bliss::Pronunciation &p)
Builds allophone state acceptor from a (non-coarticulated) pronunciation.
Functor< const Bliss::Pronunciation & > createFunctor (const Bliss::Pronunciation &p)
AllophoneStateGraphRef build (const Bliss::Coarticulated< Bliss::Pronunciation > &)
Builds allophone state acceptor from a coarticulated pronunciation.
AllophoneStateGraphRef build (std::tuple< const Bliss::Coarticulated< Bliss::Pronunciation > & > t)
Functor< const Bliss::Coarticulated< Bliss::Pronunciation > > createFunctor (const Bliss::Coarticulated< Bliss::Pronunciation > &p)
AllophoneStateGraphRef build (const Alignment &)
Functor< const Alignment & > createFunctor (const std::string &id, const Alignment &a)
AllophoneStateGraphRef build (const Alignment &, const Bliss::Coarticulated< Bliss::Pronunciation > &)
Accelerated way of creating an alignment allophone state graph.
Fsa::ConstAutomatonRef buildTransducer (const std::string &orth)
Builds a allophone state to lemma pronunciation transducer from orthography.
Fsa::ConstAutomatonRef buildTransducer (std::string const &orth, std::string const &leftContextOrth, std::string const &rightContextOrth)
Fsa::ConstAutomatonRef buildTransducer (std::tuple< const std::string & > const &t)
Fsa::ConstAutomatonRef buildTransducer (std::tuple< std::string const &, std::string const &, std::string const & > const &t)
TransducerFunctor< const std::string > createTransducerFunctor (const std::string &id, const std::string &orth)
TransducerFunctor< const std::string, const std::string, const std::string > createTransducerFunctor (const std::string &id, const std::string &orth, const std::string &leftContextOrth, const std::string &rightContextOrth)
AllophoneStateGraphRef finalizeTransducer (Fsa::ConstAutomatonRef)
Creates a static epsilon free acceptor from the input transducer.
FinalizationFunctor createFinalizationFunctor (const std::string &id, Fsa::ConstAutomatonRef t)
AllophoneStateGraphRef build (Fsa::ConstAutomatonRef)
Builds allophone state acceptor from a lemma accertor.
Fsa::ConstAutomatonRef buildTransducer (Fsa::ConstAutomatonRef)
Builds a allophone state to lemma pronunciation transducer from lemma acceptor.
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Private Types
typedef Core::Component Precursor
Private Member Functions
Bliss::OrthographicParser & orthographicParser ()
Core::Ref< Fsa::StaticAutomaton > lemmaPronunciationToLemmaTransducer ()
Core::Ref< Fsa::StaticAutomaton > phonemeToLemmaPronunciationTransducer ()
Core::Ref< Fsa::StaticAutomaton > allophoneStateToPhonemeTransducer ()
Fsa::ConstAutomatonRef singlePronunciationAllophoneStateToPhonemeTransducer ()
Fsa::ConstAutomatonRef createAlignmentGraph (const Alignment &)
AllophoneStateGraphRef build (const Alignment &alignment, AllophoneStateGraphRef)
Private Attributes
Bliss::LexiconRef lexicon_
Core::Ref< const Am::AcousticModel > acousticModel_
Bliss::OrthographicParser * orthographicParser_
Core::Ref< Fsa::StaticAutomaton > lemmaPronunciationToLemmaTransducer_
Core::Ref< Fsa::StaticAutomaton > phonemeToLemmaPronunciationTransducer_
Core::Ref< Fsa::StaticAutomaton > allophoneStateToPhonemeTransducer_
Fsa::ConstAutomatonRef singlePronunciationAllophoneStateToPhonemeTransducer_
Core::XmlChannel modelChannel_
bool flatModelAcceptor_
std::vector< const Bliss::Pronunciation * > silencesAndNoises_
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
AllophoneStateGraphBuilder.
Definition at line 45 of file AllophoneStateGraphBuilder.hh.
Member Enumeration Documentation
enum Speech::AllophoneStateGraphBuilder::InputLevel
Builds allophone state acceptor for phoneme loops, cf.
phoneme recognition.
Definition at line 197 of file AllophoneStateGraphBuilder.hh.
Member Function Documentation
AllophoneStateGraphRef AllophoneStateGraphBuilder::build (const std::string & orth)
Builds allophone state acceptor from an orthography.
Definition at line 163 of file AllophoneStateGraphBuilder.cc.
References Core::Component::criticalError().
AllophoneStateGraphRef Speech::AllophoneStateGraphBuilder::build (const Bliss::Pronunciation & p) inline
Builds allophone state acceptor from a (non-coarticulated) pronunciation.
Definition at line 207 of file AllophoneStateGraphBuilder.hh.
AllophoneStateGraphRef AllophoneStateGraphBuilder::build (const Bliss::Coarticulated< Bliss::Pronunciation > & pronunciation)
Builds allophone state acceptor from a coarticulated pronunciation.
Definition at line 309 of file AllophoneStateGraphBuilder.cc.
AllophoneStateGraphRef AllophoneStateGraphBuilder::build (const Alignment & alignment, const Bliss::Coarticulated< Bliss::Pronunciation > & pronunciation)
Accelerated way of creating an alignment allophone state graph.
Pronuniciation restricts the allophone state graph with which the alignment graph is composed.
Definition at line 324 of file AllophoneStateGraphBuilder.cc.
References Fsa::PropertyStorage, and Core::Component::warning().
AllophoneStateGraphRef AllophoneStateGraphBuilder::build (Fsa::ConstAutomatonRef lemmaAcceptor)
Builds allophone state acceptor from a lemma accertor.
Definition at line 212 of file AllophoneStateGraphBuilder.cc.
Fsa::ConstAutomatonRef AllophoneStateGraphBuilder::buildTransducer (const std::string & orth)
Builds a allophone state to lemma pronunciation transducer from orthography.
Definition at line 190 of file AllophoneStateGraphBuilder.cc.
Fsa::ConstAutomatonRef AllophoneStateGraphBuilder::buildTransducer (Fsa::ConstAutomatonRef lemmaAcceptor)
Builds a allophone state to lemma pronunciation transducer from lemma acceptor.
Definition at line 216 of file AllophoneStateGraphBuilder.cc.
References Core::Component::criticalError(), Fsa::drawDot(), require, and Fsa::write().
AllophoneStateGraphRef AllophoneStateGraphBuilder::finalizeTransducer (Fsa::ConstAutomatonRef allophoneStateToLemmaPronuncationTransducer)
Creates a static epsilon free acceptor from the input transducer.
Definition at line 296 of file AllophoneStateGraphBuilder.cc.
References Fsa::drawDot(), and Fsa::write().
The documentation for this class was generated from the following files:
AllophoneStateGraphBuilder.hh
AllophoneStateGraphBuilder.cc