Sprint: Search::Aligner Class Reference
Search::Aligner Class Reference
Forced state-level alignment of network with observation seqeuence.
#include <Aligner.hh>
Classes
class SearchSpace
class WordLatticeBuilder
class WordLatticeBuilder
Public Types
enum Mode { modeViterbi, modeBaumWelch }
Public Member Functions
Aligner (const Core::Configuration &)
void setModel (Fsa::ConstAutomatonRef model, Core::Ref< const Am::AcousticModel >)
Fsa::ConstAutomatonRef getModel () const
void restart ()
void feed (Mm::FeatureScorer::Scorer scorer)
Feeds a single feature scorers into the aligner.
void feed (const std::vector< Mm::FeatureScorer::Scorer > &)
Feeds vector of feature scorers into the aligner.
Fsa::ConstAutomatonRef getAlignmentFsa () const
Returns an automaton representing the alignment of HMM model states and observations (features).
std::pair< Fsa::ConstAutomatonRef, Fsa::Weight > getAlignmentPosteriorFsa (Fsa::ConstAutomatonRef alignmentFsa) const
Returns an automaton which is topologically equivalent to the automaton returned by getAlignmentFsa(), but where arc weights represent (negative logarithmic) posterior probabilities.
void getAlignment (Speech::Alignment &, std::pair< Fsa::ConstAutomatonRef, Fsa::Weight > alignmentPosteriorFsa) const
void getAlignment (Speech::Alignment &) const
Score alignmentScore () const
bool reachedFinalState () const
void selectMode (Mode)
void selectMode ()
Mode getMode () const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Attributes
static const Core::Choice choiceMode
static const Core::ParameterChoice paramMode
static const Core::ParameterFloat paramMinAcousticPruningThreshold
static const Core::ParameterFloat paramMaxAcousticPruningThreshold
static const Core::ParameterFloat paramAcousticPruningThresholdIncrementFactor
static const Core::ParameterFloat paramMinAverageNumberOfStateHypotheses
static const Core::ParameterBool paramIncreasePruningUntilNoScoreDifference
static const Core::ParameterBool paramLogIterations
static const Core::ParameterFloat paramMinWeight
static const Core::ParameterInt paramNBestPruning
static const Core::ParameterBool paramUsePartialSums
static const Core::ParameterInt paramCollectGarbageTime
Private Types
typedef Speech::Score Score
Private Member Functions
Mm::Weight getLogWeightThreshold () const
Private Attributes
Fsa::ConstAutomatonRef model_
SearchSpace * ss_
Core::Ref< const Am::AcousticModel > acousticModel_
Score acousticPruningThreshold_
u32 nBestPruning_
Score minAcousticPruningThreshold_
Score maxAcousticPruningThreshold_
Score acousticPruningThresholdIncrementFactor_
f64 minAverageNumberOfStateHypotheses_
bool increasePruningUntilNoScoreDifference_
bool logIterations_
u32 nIterations_
bool viterbi_
Mm::Weight minWeight_
bool usePartialSums_
u32 collectGarbageTime_
Core::Statistics< u32 > nStateHypotheses_
Mm::ProbabilityStatistics statePosteriorStats_
Core::XmlChannel statisticsChannel_
Core::XmlChannel alignmentChannel_
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Forced state-level alignment of network with observation seqeuence.
Definition at line 36 of file Search/Aligner.hh.
Member Function Documentation
void Aligner::feed (Mm::FeatureScorer::Scorer scorer)
Feeds a single feature scorers into the aligner.
Acoustic pruninig treshold will be set to maxAcousticPruningThreshold_.
Definition at line 585 of file Search/Aligner.cc.
References require.
Referenced by feed().
void Aligner::feed (const std::vector< Mm::FeatureScorer::Scorer > & emissionScorers)
Feeds vector of feature scorers into the aligner.
Acoustic pruninig treshold will be optimized within the interval [0..maxAcousticPruningThreshold_].
Definition at line 594 of file Search/Aligner.cc.
References feed(), and Core::isAlmostEqual().
Fsa::ConstAutomatonRef Aligner::getAlignmentFsa () const
Returns an automaton representing the alignment of HMM model states and observations (features).
In the case of Viterbi training, the resulting acceptor has a simple linear structure representing the best path. With Baum-Welch Training, we have an acyclic graph representing the search space of the aligner limited to those paths which reached a final state. In either case, an allophone-state acceptor with arc weights being acoustic scores is returned. If the aligner does not reach a final state due pruning settings which are too restrictive, an empty automaton is returned.
Definition at line 732 of file Search/Aligner.cc.
References Fsa::drawDot(), Core::Component::warning(), and Fsa::write().
std::pair< Fsa::ConstAutomatonRef, Fsa::Weight > Aligner::getAlignmentPosteriorFsa (Fsa::ConstAutomatonRef alignmentFsa) const
Returns an automaton which is topologically equivalent to the automaton returned by getAlignmentFsa(), but where arc weights represent (negative logarithmic) posterior probabilities.
Definition at line 757 of file Search/Aligner.cc.
References Fsa::drawDot(), Fsa::multiply(), Fsa::prunePosterior(), and Fsa::write().
The documentation for this class was generated from the following files:
Search/Aligner.hh
Search/Aligner.cc