Sprint: Bliss::CorpusVisitor Class Reference
Bliss::CorpusVisitor Class Reference
Abstract visitor base class for corpus traversal.
#include <CorpusDescription.hh>
Public Member Functions
virtual void enterRecording (Recording *)
Template method called when corpus traversal enters a recording.
virtual void leaveRecording (Recording *)
Template method called when corpus traversal leaves a recording.
virtual void enterCorpus (Corpus *)
Template method notifying start of a (sub-) corpus.
virtual void leaveCorpus (Corpus *)
Template method notifying end of a (sub-) corpus.
Public Member Functions inherited from Bliss::SegmentVisitor
virtual void visitSegment (Segment *)
Template method for processing segments.
virtual void visitSpeechSegment (SpeechSegment *s)
Template method for processing speech segments.
Detailed Description
Abstract visitor base class for corpus traversal.
Implement the respective virtual function to process the part of the Corpus. Note: The concept of Visitors is described in Design Patterns.
Definition at line 500 of file CorpusDescription.hh.
Member Function Documentation
virtual void Bliss::CorpusVisitor::enterCorpus (Corpus *) inline virtual
Template method notifying start of a (sub-) corpus.
This is rarely needed.
Reimplemented in Bliss::ProgressReportingVisitorAdaptor, Bliss::CorpusDescription::ProgressIndicationVisitorAdaptor, Bliss::CorpusDescription::SegmentPartitionVisitorAdaptor, Speech::CorpusVisitor, Bliss::SegmentOrderingVisitor, and TestCorpusVisitor.
Definition at line 520 of file CorpusDescription.hh.
Referenced by Speech::CorpusVisitor::enterCorpus(), Bliss::CorpusDescription::SegmentPartitionVisitorAdaptor::enterCorpus(), and Bliss::CorpusDescription::ProgressIndicationVisitorAdaptor::enterCorpus().
virtual void Bliss::CorpusVisitor::enterRecording (Recording *) inline virtual
Template method called when corpus traversal enters a recording.
Implement this to take appropriate actions, e.g. opening the audio file.
Reimplemented in Bliss::ProgressReportingVisitorAdaptor, Bliss::CorpusDescription::ProgressIndicationVisitorAdaptor, Bliss::CorpusDescription::SegmentPartitionVisitorAdaptor, Bliss::CompositeCorpusStatisticsVisitor, Speech::CorpusVisitor, Bliss::SegmentOrderingVisitor, Bliss::CorpusSizeStatisticsVisitor, CorpusVisitor, and TestCorpusVisitor.
Definition at line 507 of file CorpusDescription.hh.
Referenced by Speech::CorpusVisitor::enterRecording(), and Bliss::CorpusDescription::ProgressIndicationVisitorAdaptor::enterRecording().
virtual void Bliss::CorpusVisitor::leaveCorpus (Corpus *) inline virtual
Template method notifying end of a (sub-) corpus.
This is rarely needed.
Reimplemented in Bliss::ProgressReportingVisitorAdaptor, Bliss::CorpusDescription::ProgressIndicationVisitorAdaptor, Bliss::CorpusDescription::SegmentPartitionVisitorAdaptor, Speech::CorpusVisitor, Bliss::SegmentOrderingVisitor, Bliss::PythonSegmentOrderingVisitor, Bliss::TheanoSegmentOrderingVisitor, and TestCorpusVisitor.
Definition at line 526 of file CorpusDescription.hh.
Referenced by Speech::CorpusVisitor::leaveCorpus(), Bliss::CorpusDescription::SegmentPartitionVisitorAdaptor::leaveCorpus(), and Bliss::CorpusDescription::ProgressIndicationVisitorAdaptor::leaveCorpus().
virtual void Bliss::CorpusVisitor::leaveRecording (Recording *) inline virtual
Template method called when corpus traversal leaves a recording.
Implement this to take appropriate clean-up actions, e.g. closing the audio file.
Reimplemented in Bliss::ProgressReportingVisitorAdaptor, Bliss::CorpusDescription::ProgressIndicationVisitorAdaptor, Bliss::CorpusDescription::SegmentPartitionVisitorAdaptor, Bliss::CompositeCorpusStatisticsVisitor, Speech::CorpusVisitor, and TestCorpusVisitor.
Definition at line 514 of file CorpusDescription.hh.
Referenced by Speech::CorpusVisitor::leaveRecording(), Bliss::CorpusDescription::SegmentPartitionVisitorAdaptor::leaveRecording(), and Bliss::CorpusDescription::ProgressIndicationVisitorAdaptor::leaveRecording().
The documentation for this class was generated from the following file:
CorpusDescription.hh