Sprint: Search::Wfst::TraceRecorder Class Reference
Search::Wfst::TraceRecorder Class Reference abstract
Interface for book keeping classes.
#include <BookKeeping.hh>
Public Types
typedef u32 TraceRef
Public Member Functions
virtual void clear ()=0
remove all trace objects
virtual TraceRef addTrace (TraceRef sibling, TraceRef predecessor, OpenFst::Label output, const StateSequence *input, TimeframeIndex time, Score score, Score arcScore, bool wordEnd)=0
add a new trace
virtual void updateTime (TraceRef t, TimeframeIndex time)=0
Update the timestamp of the given trace object.
virtual void purgeBegin ()
start purging process (reset all active flags)
virtual void purgeEnd ()
remove all trace objects not labeled as active
virtual void purgeNotify (TraceRef trace)
label the trace object and its predecessors as active (set active flag)
virtual void pruneBegin ()
start pruning process (for lattices only)
virtual void pruneEnd ()
finish pruning (for lattices only)
virtual void pruneNotify (TraceRef trace)
label the trace as currently active (for lattices only)
virtual size_t memoryUsage () const
memory usage in bytes.
virtual bool hasWordEndTime (const WordEndDetector &wordEnds, TraceRef end)=0
Check if the number of word boundary time stamps matches the number of output labels on the path ending in end.
virtual void createBestPath (const WordEndDetector &wordEnds, bool ignoreLast, TraceRef end, BestPath *path)=0
Find the first best path ending in end.
virtual Lattice * createLattice (TraceRef)=0
Create a lattice.
Static Public Attributes
static const TraceRef InvalidTraceRef = -1
Detailed Description
Interface for book keeping classes.
Definition at line 33 of file BookKeeping.hh.
Member Function Documentation
virtual TraceRef Search::Wfst::TraceRecorder::addTrace (TraceRef sibling, TraceRef predecessor, OpenFst::Label output, const StateSequence * input, TimeframeIndex time, Score score, Score arcScore, bool wordEnd) pure virtual
add a new trace
Implemented in Search::Wfst::HmmLatticeTraceRecorder, and Search::Wfst::FirstBestTraceRecorder.
virtual void Search::Wfst::TraceRecorder::clear () pure virtual
remove all trace objects
Implemented in Search::Wfst::HmmLatticeTraceRecorder, Search::Wfst::FirstBestTraceRecorder, and Search::Wfst::LatticeTraceRecorder.
virtual void Search::Wfst::TraceRecorder::createBestPath (const WordEndDetector & wordEnds, bool ignoreLast, TraceRef end, BestPath * path) pure virtual
Find the first best path ending in end.
Implemented in Search::Wfst::DetermisticHmmLatticeTraceRecorder, Search::Wfst::HmmLatticeTraceRecorder, and Search::Wfst::FirstBestTraceRecorder.
Referenced by memoryUsage(), and Search::Wfst::FirstBestTraceRecorder::memoryUsage().
virtual Lattice* Search::Wfst::TraceRecorder::createLattice (TraceRef) pure virtual
Create a lattice.
Implemented in Search::Wfst::HmmLatticeTraceRecorder, and Search::Wfst::FirstBestTraceRecorder.
Referenced by memoryUsage(), and Search::Wfst::FirstBestTraceRecorder::memoryUsage().
virtual bool Search::Wfst::TraceRecorder::hasWordEndTime (const WordEndDetector & wordEnds, TraceRef end) pure virtual
Check if the number of word boundary time stamps matches the number of output labels on the path ending in end.
Implemented in Search::Wfst::HmmLatticeTraceRecorder, and Search::Wfst::FirstBestTraceRecorder.
Referenced by memoryUsage(), and Search::Wfst::FirstBestTraceRecorder::memoryUsage().
virtual size_t Search::Wfst::TraceRecorder::memoryUsage () const inline virtual
memory usage in bytes.
Reimplemented in Search::Wfst::HmmLatticeTraceRecorder, Search::Wfst::FirstBestTraceRecorder, and Search::Wfst::LatticeTraceRecorder.
Definition at line 82 of file BookKeeping.hh.
References createBestPath(), createLattice(), and hasWordEndTime().
virtual void Search::Wfst::TraceRecorder::pruneBegin () inline virtual
start pruning process (for lattices only)
Reimplemented in Search::Wfst::HmmLatticeTraceRecorder.
Definition at line 69 of file BookKeeping.hh.
virtual void Search::Wfst::TraceRecorder::pruneEnd () inline virtual
finish pruning (for lattices only)
Reimplemented in Search::Wfst::HmmLatticeTraceRecorder.
Definition at line 73 of file BookKeeping.hh.
virtual void Search::Wfst::TraceRecorder::pruneNotify (TraceRef trace) inline virtual
label the trace as currently active (for lattices only)
Reimplemented in Search::Wfst::HmmLatticeTraceRecorder.
Definition at line 77 of file BookKeeping.hh.
virtual void Search::Wfst::TraceRecorder::purgeBegin () inline virtual
start purging process (reset all active flags)
Reimplemented in Search::Wfst::FirstBestTraceRecorder, and Search::Wfst::LatticeTraceRecorder.
Definition at line 57 of file BookKeeping.hh.
virtual void Search::Wfst::TraceRecorder::purgeEnd () inline virtual
remove all trace objects not labeled as active
Reimplemented in Search::Wfst::FirstBestTraceRecorder, and Search::Wfst::LatticeTraceRecorder.
Definition at line 61 of file BookKeeping.hh.
virtual void Search::Wfst::TraceRecorder::purgeNotify (TraceRef trace) inline virtual
label the trace object and its predecessors as active (set active flag)
Reimplemented in Search::Wfst::FirstBestTraceRecorder, and Search::Wfst::LatticeTraceRecorder.
Definition at line 65 of file BookKeeping.hh.
virtual void Search::Wfst::TraceRecorder::updateTime (TraceRef t, TimeframeIndex time) pure virtual
Update the timestamp of the given trace object.
Implemented in Search::Wfst::HmmLatticeTraceRecorder, and Search::Wfst::FirstBestTraceRecorder.
The documentation for this class was generated from the following file:
BookKeeping.hh