Sprint: Core::MappedArchiveReader Class Reference
Core::MappedArchiveReader Class Reference
Public Member Functions
MappedArchiveReader (const Core::Ref< MappedArchive::Reader > &rhs=Core::Ref< MappedArchive::Reader >())
template<class T >
void readValue (T &value)
template<class T >
void readVector (std::vector< T > &vec)
template<class T >
void readVectorVector (std::vector< std::vector< T >> &vectors)
template<class T >
void readVector (ConstantVector< T > &vec)
std::string name () const
void reset ()
Reset the reader into the state where it was after retrieving.
void invalidate ()
bool good () const
Returns Whether this object is valid, eg.
operator bool () const
template<class T >
MappedArchiveReader & operator>> (T &value)
template<class T >
MappedArchiveReader & operator>> (std::vector< T > &vector)
template<class T >
MappedArchiveReader & operator>> (ConstantVector< T > &vector)
MappedArchiveReader & operator>> (std::string &str)
template<class T >
MappedArchiveReader & operator>> (std::vector< std::vector< T >> &vectors)
template<class T >
bool check (T expected, std::string desc)
Convenience function for quick checking whether a read value equals the expected one On mismatch, returns false and logs the mismatch.
Additional Inherited Members
Private Types inherited from Core::Ref< MappedArchive::Reader >
typedef MappedArchive::Reader Object
Private Member Functions inherited from Core::Ref< MappedArchive::Reader >
Ref (Object *o)
Ref (const Ref &r)
Copy Constructor for the Type Ref<T>
Ref (const Ref< S > &r)
Template Copy Constuctor.
Ref (const WeakRef< S > &r)
Ref & operator= (const Ref &rhs)
Ref & operator= (const Ref< S > &rhs)
Ref & operator= (const WeakRef< S > &rhs)
void reset ()
Reset to void.
bool operator== (const Ref &r) const
Test for identity.
bool operator== (const Ref< S > &r) const
bool operator== (const WeakRef< S > &r) const
bool operator!= (const Ref &r) const
Test for non-identity.
bool operator!= (const Ref< S > &r) const
bool operator!= (const WeakRef< S > &r) const
operator bool () const
Test for non-voidness.
bool operator! () const
Test for voidness.
Object & operator* () const
Object * operator-> () const
Object * get () const
Explicit conversion to normal pointer.
Object * _get () const
Value of internal pointer.
Detailed Description
Definition at line 260 of file MappedArchive.hh.
Member Function Documentation
template<class T > bool Core::MappedArchiveReader::check (T expected, std::string desc) inline
Convenience function for quick checking whether a read value equals the expected one On mismatch, returns false and logs the mismatch.
expected The expected value desc Description of the value for logging the mismatch
Definition at line 382 of file MappedArchive.hh.
References Core::Component::log(), and Core::Application::us().
Referenced by AdvancedTreeSearch::AcousticLookAhead::AcousticLookAheadModel::estimate(), and Mm::DensityClusteringBase::load().
bool Core::MappedArchiveReader::good () const inline
Returns Whether this object is valid, eg.
can be used for reading. Upon trying to read data over the file boundaries, the reader becomes invalid, eg. good() returns false. After you've finished reading, you should always check this to verify that the reading was successful.
Definition at line 335 of file MappedArchive.hh.
Referenced by AdvancedTreeSearch::LanguageModelLookahead::buildCompressesLookaheadStructure(), AdvancedTreeSearch::AcousticLookAhead::AcousticLookAheadModel::estimate(), Mm::DensityClusteringBase::load(), Search::PersistentStateTree::read(), and Search::HMMStateNetwork::read().
void Core::MappedArchiveReader::reset () inline
Reset the reader into the state where it was after retrieving.
Definition at line 322 of file MappedArchive.hh.
References Core::Ref< T >::reset().
The documentation for this class was generated from the following file:
MappedArchive.hh