Sprint: Core::Thread Class Reference
Core::Thread Class Reference
Abstract Thread.
#include <Thread.hh>
Public Member Functions
bool start ()
Start the thread.
void wait ()
Wait for thread to exit.
virtual void run ()
Override this in a threaded class.
virtual void cleanup ()
Cleanup, when thread is ended.
Protected Member Functions
void enableCancel ()
Allow that the thread is cancelled by another thread.
void disableCancel ()
Forbid other threads to cancel this thread.
void setCancelDeferred ()
The thread can only be chancelled on certain points.
void setCancelAsync ()
The thread can be chanceled at any time.
void exitThread ()
Terminates the thread.
Static Private Member Functions
static void * startRun (void *obj)
static void startCleanup (void *obj)
Private Attributes
bool running_
pthread_t thread_
Detailed Description
Abstract Thread.
Thread implementation based on pthreads
Definition at line 34 of file Thread.hh.
Member Function Documentation
virtual void Core::Thread::cleanup () inline virtual
Cleanup, when thread is ended.
Definition at line 105 of file Thread.hh.
References cleanup(), and run().
Referenced by cleanup().
void Core::Thread::disableCancel () inline protected
Forbid other threads to cancel this thread.
Definition at line 72 of file Thread.hh.
void Core::Thread::enableCancel () inline protected
Allow that the thread is cancelled by another thread.
Definition at line 66 of file Thread.hh.
void Core::Thread::exitThread () inline protected
Terminates the thread.
Definition at line 91 of file Thread.hh.
virtual void Core::Thread::run () inline virtual
Override this in a threaded class.
Reimplemented in Core::ThreadPoolThread< Pool >, TestThread, and SimpleThreadPool::Thread.
Definition at line 101 of file Thread.hh.
Referenced by cleanup().
void Core::Thread::setCancelAsync () inline protected
The thread can be chanceled at any time.
Definition at line 84 of file Thread.hh.
void Core::Thread::setCancelDeferred () inline protected
The thread can only be chancelled on certain points.
Definition at line 78 of file Thread.hh.
bool Core::Thread::start () inline
Start the thread.
Definition at line 44 of file Thread.hh.
void Core::Thread::wait () inline
Wait for thread to exit.
Definition at line 56 of file Thread.hh.
Referenced by SimpleThreadPool::Thread::run(), and Core::Condition::wait().
The documentation for this class was generated from the following file:
Thread.hh