Sprint: Speech::AffineFeatureTransformEstimator Class Reference
Speech::AffineFeatureTransformEstimator Class Reference
AffineFeatureTransformEstimator.
#include <AffineFeatureTransformEstimator.hh>
Public Member Functions
AffineFeatureTransformEstimator (const Core::Configuration &c, Operation op=estimate)
void postProcess ()
void scoreTransforms ()
Public Member Functions inherited from Speech::KeyedEstimator
KeyedEstimator (const Core::Configuration &c, Operation op=estimate)
virtual void signOn (CorpusVisitor &corpusVisitor)
Override this function to sign on to services of the corpus visitor.
virtual void setFeatureDescription (const Mm::FeatureDescription &)
Override this function to achieve the attributes of the feature streams.
virtual void processAlignedFeature (Core::Ref< const Feature >, Am::AllophoneStateIndex)
Override this function to implement the processing of Viterbi-aligned feature vectors.
virtual void processAlignedFeature (Core::Ref< const Feature >, Am::AllophoneStateIndex, Mm::Weight)
Override this function to implement the processing of Baum-Welch-aligned feature vectors.
virtual void combine ()
Public Member Functions inherited from Speech::AcousticModelTrainer
AcousticModelTrainer (const Core::Configuration &c, Am::AcousticModel::Mode mode)
Public Member Functions inherited from Speech::AlignedFeatureProcessor
AlignedFeatureProcessor (const Core::Configuration &c)
virtual void enterCorpus (Bliss::Corpus *)
Override this function to perform preparations before first segment is processed.
virtual void leaveCorpus (Bliss::Corpus *)
Override this function to perform post processing after the last segment is processed.
virtual void enterSegment (Bliss::Segment *)
Override this function to perform preparations before first aligned features arrive.
virtual void leaveSegment (Bliss::Segment *)
Override this function to perform post processing after the last aligned features of the segment.
virtual void enterSpeechSegment (Bliss::SpeechSegment *)
Override this function to perform preparations before first aligned features arrive.
virtual void leaveSpeechSegment (Bliss::SpeechSegment *)
Override this function to perform post processing after the last aligned features of the segment.
virtual void processAlignedFeature (Core::Ref< const Feature >, Am::AllophoneStateIndex, Mm::Weight, Mm::Weight)
Override this function to implement the processing of feature vectors with two weights.
virtual void setDataSource (Core::Ref< DataSource >)
Override this function to obtain the data source of corpus processor which produces the labels.
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Attributes
static const Core::ParameterString paramInitialTransform
static const Core::ParameterString paramInitialTransformDirectory
static const Core::ParameterString paramTransformDirectory
static const Core::ParameterInt paramEstimationIterations
static const Core::ParameterFloat paramMinObservationWeight
static const Core::Choice optimizationCriterionChoice
static const Core::ParameterChoice paramOptimizationCriterion
Static Public Attributes inherited from Speech::KeyedEstimator
static const Core::ParameterFloat paramCombinationWeight
static const Core::ParameterInt paramFeatureStream
static const Core::ParameterString paramCorpusKeyMap
Protected Member Functions
void createAccumulator (std::string key)
std::string transformExtension () const
Protected Member Functions inherited from Speech::KeyedEstimator
void loadMixtureSet ()
void createAssigningFeatureScorer ()
void loadCorpusKeyMap ()
Protected Member Functions inherited from Speech::AcousticModelTrainer
Bliss::LexiconRef lexicon () const
Core::Ref< Am::AcousticModel > acousticModel () const
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Private Types
typedef KeyedEstimator Precursor
typedef Mm::AffineFeatureTransformAccumulator ConcreteAccumulator
Additional Inherited Members
Public Types inherited from Speech::KeyedEstimator
enum Operation { estimate, calculate, combines }
typedef Core::IoRef< Mm::AbstractAdaptationAccumulator > Accumulator
typedef Core::ObjectCache< Core::MruObjectCacheList< std::string, Accumulator, Core::StringHash, Core::StringEquality > > AccumulatorCache
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Attributes inherited from Speech::KeyedEstimator
Core::Ref< Bliss::CorpusKey > corpusKey_
Core::StringHashMap< std::string > corpusKeyMap_
size_t featureDimension_
size_t modelDimension_
size_t featureStream_
Operation operation_
Accumulator * currentAccumulator_
AccumulatorCache accumulatorCache_
AccumulatorCache * accumulatorCacheToAdd_
Core::Ref< const Mm::AssigningFeatureScorer > assigningFeatureScorer_
Core::Ref< Mm::MixtureSet > mixtureSet_
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
AffineFeatureTransformEstimator.
Definition at line 32 of file AffineFeatureTransformEstimator.hh.
Member Function Documentation
void AffineFeatureTransformEstimator::postProcess ()
Todo:
this is a more or less diry hack. what we want to do here is to modify the object without writing the modification back to cache
Definition at line 60 of file AffineFeatureTransformEstimator.cc.
References Core::createDirectory(), Core::directoryName(), Core::joinPaths(), and verify.
Referenced by AcousticModelTrainer::showMixtureSet().
The documentation for this class was generated from the following files:
AffineFeatureTransformEstimator.hh
AffineFeatureTransformEstimator.cc