Sprint: Speech::DelayedRecognizer Class Reference
Speech::DelayedRecognizer Class Reference
Recognizer with a delay in output, used for search algorithms with an acoustic look-ahead.
#include <DelayedRecognizer.hh>
Public Member Functions
DelayedRecognizer (const Core::Configuration &)
virtual void signOn (CorpusVisitor &corpusVisitor)
Override this function to sign on to services of the corpus visitor.
virtual void enterSpeechSegment (Bliss::SpeechSegment *)
virtual void processFeature (Core::Ref< const Feature >)
Override this function to achieve the features extracted form data source one-by-one.
virtual void leaveSpeechSegment (Bliss::SpeechSegment *)
Public Member Functions inherited from Speech::OfflineRecognizer
OfflineRecognizer (const Core::Configuration &, Am::AcousticModel::Mode=Am::AcousticModel::complete)
virtual void processResultAndLogStatistics (Bliss::SpeechSegment *s)
virtual void leaveSegment (Bliss::Segment *)
virtual void setFeatureDescription (const Mm::FeatureDescription &)
Override this function to achieve the attributes of the feature streams.
Public Member Functions inherited from Speech::FeatureExtractor
FeatureExtractor (const Core::Configuration &c, bool loadFromFile=true)
virtual void processSegment (Bliss::Segment *segment)
Public Member Functions inherited from Speech::DataExtractor
DataExtractor (const Core::Configuration &c, bool loadFromFile=true)
virtual void enterCorpus (Bliss::Corpus *)
virtual void leaveCorpus (Bliss::Corpus *)
virtual void enterRecording (Bliss::Recording *)
virtual void enterSegment (Bliss::Segment *)
Public Member Functions inherited from Speech::CorpusProcessor
CorpusProcessor (const Core::Configuration &c)
virtual void leaveRecording (Bliss::Recording *recoding)
virtual void processSpeechSegment (Bliss::SpeechSegment *segment)
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Speech::Recognizer
Recognizer (const Core::Configuration &)
Protected Attributes
RecognizerDelayHandler delay_
Protected Attributes inherited from Speech::OfflineRecognizer
bool shouldEvaluateResult_
bool shouldStoreLattice_
Bliss::Evaluator * evaluator_
Search::LatticeHandler * latticeHandler_
Lattice::ArchiveWriter * tracebackArchiveWriter_
Core::XmlChannel tracebackChannel_
bool timeConditionedLattice_
std::string layerName_
Protected Attributes inherited from Speech::CorpusProcessor
Core::XmlChannel channelTimer_
Core::Timer timer_
Protected Attributes inherited from Core::Configurable
Configuration config
Protected Attributes inherited from Speech::Recognizer
Core::Ref< const Bliss::Lexicon > lexicon_
Core::Ref< Am::AcousticModel > acousticModel_
Search::SearchAlgorithm * recognizer_
Additional Inherited Members
Static Public Attributes inherited from Speech::Recognizer
static const Core::Choice searchTypeChoice_
static const Core::ParameterChoice paramSearch
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Types inherited from Speech::Recognizer
typedef Search::SearchAlgorithm::Traceback Traceback
Protected Member Functions inherited from Speech::OfflineRecognizer
void processResult (Bliss::SpeechSegment *s)
void logTraceback (const Traceback &)
void addPartialToTraceback (Traceback &partialTraceback)
void processFeatureTimestamp (const Flow::Timestamp &timestamp)
void finishSegment (Bliss::SpeechSegment *segment)
Protected Member Functions inherited from Speech::DataExtractor
void setDataSource (Core::Ref< DataSource > s)
Core::Ref< DataSource > dataSource () const
Protected Member Functions inherited from Speech::CorpusProcessor
void reportRealTime (Flow::Time)
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Member Functions inherited from Speech::Recognizer
void initializeRecognizer (Am::AcousticModel::Mode acousticModelMode)
void initializeRecognizer (const Speech::ModelCombination &)
virtual void createRecognizer ()
Detailed Description
Recognizer with a delay in output, used for search algorithms with an acoustic look-ahead.
Definition at line 52 of file DelayedRecognizer.hh.
Member Function Documentation
void DelayedRecognizer::processFeature (Core::Ref< const Feature >) virtual
Override this function to achieve the features extracted form data source one-by-one.
Reimplemented from Speech::OfflineRecognizer.
Definition at line 37 of file DelayedRecognizer.cc.
References Mm::FeatureScorer::addFeature(), Mm::FeatureScorer::bufferFilled(), ensure, Mm::FeatureScorer::flush(), Core::Ref< T >::get(), Mm::FeatureScorer::isBuffered(), and verify.
void DelayedRecognizer::signOn (CorpusVisitor & corpusVisitor) virtual
Override this function to sign on to services of the corpus visitor.
Note: call the signOn function of your predecessor.
Reimplemented from Speech::OfflineRecognizer.
Definition at line 25 of file DelayedRecognizer.cc.
References Speech::DataExtractor::signOn().
The documentation for this class was generated from the following files:
DelayedRecognizer.hh
DelayedRecognizer.cc