Sprint: Core::XmlWriter Class Reference
Core::XmlWriter Class Reference
Stream adaptor for producing XML output.
#include <XmlStream.hh>
Classes
class Buffer
Public Member Functions
XmlWriter (std::ostream &)
void generateFormattingHints (bool enable=true)
Enable formatting hints.
void put (const std::string &)
void putDeclaration (const std::string &encoding="")
Generate the XML declaration that usually starts an XML document.
void put (const XmlOpen &)
void put (const XmlClose &)
void put (const XmlEmpty &)
void put (const XmlFull &)
void put (const XmlComment &)
void put (const XmlOpenComment &)
void put (const XmlCloseComment &)
void put (const XmlBlank &)
Self & operator<< (s8 t)
Self & operator<< (u8 t)
Self & operator<< (s16 t)
Self & operator<< (u16 t)
Self & operator<< (s32 t)
Self & operator<< (u32 t)
Self & operator<< (s64 t)
Self & operator<< (u64 t)
Self & operator<< (f32 t)
Self & operator<< (f64 t)
Self & operator<< (char t)
Self & operator<< (bool t)
Self & operator<< (void *t)
Self & operator<< (const char *t)
Self & operator<< (const std::string &s)
Self & operator<< (const XmlOpen &t)
Self & operator<< (const XmlClose &t)
Self & operator<< (const XmlEmpty &t)
Self & operator<< (const XmlFull &t)
Self & operator<< (const XmlComment &t)
Self & operator<< (const XmlOpenComment &t)
Self & operator<< (const XmlCloseComment &t)
Self & operator<< (const XmlBlank &t)
Protected Member Functions
bool shouldGenerateFormattingHints () const
void formattingHint (TextOutputStream::FormattingHint)
void putEscaped (const std::string &, const char *escape)
Put string but replace special characters.
void putTag (const XmlOpen &, bool isEmpty)
void putClosingTag (const XmlClose &)
XmlWriter (const XmlWriter &)
Protected Attributes
std::ostream & os_
u8 inComment_
bool formattingHints_
Private Types
typedef XmlWriter Self
Detailed Description
Stream adaptor for producing XML output.
Definition at line 149 of file XmlStream.hh.
Member Function Documentation
void Core::XmlWriter::generateFormattingHints (bool enable = true) inline
Enable formatting hints.
If formatting hints are enabled the XmlWriter will send control characters to the underlying stream, which enable nice structural formatting of the XML document. TextOutputStream is able to correctly interpret these control characters, so you should generate formatting hints only if the output stream is eventually processed by a TextOutputStream.
Definition at line 188 of file XmlStream.hh.
Referenced by Flf::ConfusionNetworkArchive::ConfusionNetworkArchive(), Flf::DumpPosteriorCnNode::finalize(), Flf::DumpConfusionNetworkNode::finalize(), Cart::Training::halfSplit(), Flf::DumpPosteriorCnNode::init(), Flf::DumpConfusionNetworkNode::init(), AllophoneTool::main(), Cart::FloatBox::HashFcn::operator()(), Flf::PosteriorCnArchive::PosteriorCnArchive(), putDeclaration(), and Speech::LatticeArcAccumulatorNode::~LatticeArcAccumulatorNode().
void XmlWriter::putDeclaration (const std::string & encoding = "")
Generate the XML declaration that usually starts an XML document.
If formatting hints are enabdled, the underlying text output stream is instructed to insert its actual character encoding in the header declaration. Otherwise the argument encoding is used. You should specify encoding only if you cannot use formatting hints and if you know for sure which encoding will be used.
Definition at line 94 of file XmlStream.cc.
References Core::TextOutputStream::describeEncoding, generateFormattingHints(), Core::TextOutputStream::indentMinus, Core::TextOutputStream::indentPlus, Core::TextOutputStream::newLine, Core::TextOutputStream::newWord, Core::TextOutputStream::protect, putEscaped(), require, Core::TextOutputStream::softBlank, and Core::TextOutputStream::unprotect.
Referenced by Flf::ConfusionNetworkArchive::ConfusionNetworkArchive(), Ftl::WriteXmlDfsState< _Automaton >::discoverState(), and Flf::PosteriorCnArchive::PosteriorCnArchive().
void XmlWriter::putEscaped (const std::string & s, const char * escape) protected
Put string but replace special characters.
The given string is output, but all characters listed in escape are replaced by XML character entities (e.g. <).
Definition at line 52 of file XmlStream.cc.
References require.
Referenced by putDeclaration().
The documentation for this class was generated from the following files:
XmlStream.hh
XmlStream.cc