Sprint: Search::LatticeAdaptor Class Reference
Search::LatticeAdaptor Class Reference abstract
Basic interface for various types of lattices generated by the decoders.
#include <LatticeAdaptor.hh>
Public Member Functions
virtual bool write (const std::string &id, LatticeHandler *handler) const =0
dispatch to corresponding method in LatticeHandler
virtual Lattice::ConstWordLatticeRef wordLattice (const LatticeHandler *handler) const =0
dispatch to corresponding method in LatticeHandler
virtual bool empty () const =0
return false if an actual lattice is contained
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Detailed Description
Basic interface for various types of lattices generated by the decoders.
The Lattice::WordLattice is used as default and fall-back format, all derived classes are expected to be able to convert their lattice into an Lattice::WordLattice. I/O is handled by LatticeHandler.
Definition at line 31 of file Search/LatticeAdaptor.hh.
Member Function Documentation
virtual bool Search::LatticeAdaptor::empty () const pure virtual
return false if an actual lattice is contained
Implemented in Lattice::WordLatticeAdaptor, Search::Wfst::WfstLatticeAdaptor, and Flf::FlfLatticeAdaptor.
Referenced by Speech::OfflineRecognizer::processResult().
virtual Lattice::ConstWordLatticeRef Search::LatticeAdaptor::wordLattice (const LatticeHandler * handler) const pure virtual
dispatch to corresponding method in LatticeHandler
Implemented in Lattice::WordLatticeAdaptor, Search::Wfst::WfstLatticeAdaptor, and Flf::FlfLatticeAdaptor.
Referenced by Speech::OfflineRecognizer::processResult(), and Flf::IncrementalRecognizer::startRecognition().
virtual bool Search::LatticeAdaptor::write (const std::string & id, LatticeHandler * handler) const pure virtual
dispatch to corresponding method in LatticeHandler
Implemented in Flf::FlfLatticeAdaptor, Lattice::WordLatticeAdaptor, and Search::Wfst::WfstLatticeAdaptor.
Referenced by Speech::OfflineRecognizer::processResult().
The documentation for this class was generated from the following file:
Search/LatticeAdaptor.hh