Sprint: Mm::RpropOptimization< T > Class Template Reference
Mm::RpropOptimization< T > Class Template Reference abstract
RpropOptimization.
#include <RpropOptimization.hh>
Public Types
typedef RpropSettings< T > Settings
Public Member Functions
RpropOptimization ()
RpropOptimization.
void apply (std::vector< T > &result)
void setStepSizes (const std::vector< T > &stepSizes)
void setStepSizes (u32 dimension, T stepSize)
const std::vector< T > & stepSizes () const
void setPreviousToPrevious (const std::vector< T > &p2p)
void setSettings (const Settings &settings)
Protected Member Functions
virtual T previous (ComponentIndex) const =0
virtual T gradient (ComponentIndex) const =0
Protected Attributes
std::vector< T > previousToPrevious_
std::vector< T > stepSizes_
Private Types
enum Action { decrease, increase, hold }
Private Member Functions
T minStepSize () const
T maxStepSize () const
T increasingFactor () const
T decreasingFactor () const
bool useWeightBacktracking () const
s8 sign (T x) const
s8 direction (ComponentIndex cmp) const
void increaseStepSize (ComponentIndex cmp)
void decreaseStepSize (ComponentIndex cmp)
void setHold (ComponentIndex cmp)
void unsetHold (ComponentIndex cmp)
bool isHold (ComponentIndex cmp) const
T stepSize (ComponentIndex cmp) const
Action action (ComponentIndex cmp) const
Private Attributes
Settings settings_
Detailed Description
template<class T>
class Mm::RpropOptimization< T >
RpropOptimization.
Definition at line 56 of file RpropOptimization.hh.
Constructor & Destructor Documentation
template<class T > Mm::RpropOptimization< T >::RpropOptimization ()
RpropOptimization.
Definition at line 78 of file RpropOptimization.hh.
References Core::abs(), and Mm::RpropOptimization< T >::RpropOptimization().
Referenced by Mm::RpropOptimization< T >::RpropOptimization().
The documentation for this class was generated from the following file:
RpropOptimization.hh