Sprint: Nn::BufferedFeatureExtractor< T > Class Template Reference
Nn::BufferedFeatureExtractor< T > Class Template Reference
Extension of the Speech::FeatureExtractor.
#include <BufferedFeatureExtractor.hh>
Public Types
enum BufferType { minibatch, batch, utterance }
Public Member Functions
BufferedFeatureExtractor (const Core::Configuration &config, bool loadFromFile=true)
virtual void enterSegment (Bliss::Segment *)
virtual void processSegment ()
virtual void processCorpus ()
virtual void processFeature (Core::Ref< const Speech::Feature > f)
Override this function to achieve the features extracted form data source one-by-one.
virtual void leaveSegment (Bliss::Segment *segment)
virtual void leaveCorpus (Bliss::Corpus *corpus)
u32 bufferSize () const
Returns the maximal size of the (feature) buffer in frames.
u32 numberOfBufferedFeatures () const
Return the current number of buffered features.
bool isShuffled () const
Returns whether data shuffling is active or not.
u32 shuffledIndex (u32 index) const
Return the index of the random feature in the buffer.
u32 batchSize () const
Return the current size of a mini-batch.
Bliss::Segment * getCurSegment () const
returns current segment if in segment mode
virtual NeuralNetworkTrainer< T > * createTrainer (const Core::Configuration &config)
virtual void signOn (Speech::CorpusVisitor &corpusVisitor)
Override this function to sign on to services of the corpus visitor.
virtual void initBuffer (std::vector< u32 > &nFeatures)
Initialize the (feature) buffer.
virtual void initBuffer (Core::Ref< const Speech::Feature > f)
Initialize the feature buffer.
virtual void updateBufferedFeature (Core::Ref< const Speech::Feature > f)
Initialize the feature buffer.
virtual void resetBuffer ()
Update the feature buffer.
virtual void prepareProcessBuffer ()
virtual void processBuffer ()
virtual void finalizeProcessBuffer ()
virtual void generateMiniBatch (std::vector< NnMatrix > &miniBatch, u32 batchSize)
virtual void initShuffle ()
Shuffle the indices of the buffer.
Public Member Functions inherited from Speech::FeatureExtractor
FeatureExtractor (const Core::Configuration &c, bool loadFromFile=true)
virtual void processSegment (Bliss::Segment *segment)
Public Member Functions inherited from Speech::DataExtractor
DataExtractor (const Core::Configuration &c, bool loadFromFile=true)
virtual void enterCorpus (Bliss::Corpus *)
virtual void enterRecording (Bliss::Recording *)
Public Member Functions inherited from Speech::CorpusProcessor
CorpusProcessor (const Core::Configuration &c)
virtual void leaveRecording (Bliss::Recording *recoding)
virtual void enterSpeechSegment (Bliss::SpeechSegment *)
virtual void processSpeechSegment (Bliss::SpeechSegment *segment)
virtual void leaveSpeechSegment (Bliss::SpeechSegment *)
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Protected Types
typedef Types< T >::NnVector NnVector
typedef Types< T >::NnMatrix NnMatrix
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions
void setWindowedFeature (u32 streamIndex, u32 indexInBuffer, u32 indexInMiniBatch, NnMatrix &miniBatch)
Initialize the shuffling.
void setWindowedFeatureDerivatives (u32 streamIndex, u32 indexInBuffer, u32 indexInMiniBatch, NnMatrix &miniBatch)
void getRelativePositionsInSlidingWindow (u32 indexOfCentralFeature, u32 windowSize, std::vector< s32 > &positions)
void computeFirstDerivative (u32 streamIndex, u32 indexInBuffer)
void computeSecondDerivative (u32 streamIndex, u32 indexInBuffer)
virtual void logProperties () const
void setEnteredSegment (Bliss::Segment *)
bool checkIsTooLongSegment ()
Protected Member Functions inherited from Speech::FeatureExtractor
virtual void setFeatureDescription (const Mm::FeatureDescription &)
Override this function to achieve the attributes of the feature streams.
Protected Member Functions inherited from Speech::DataExtractor
void setDataSource (Core::Ref< DataSource > s)
Core::Ref< DataSource > dataSource () const
Protected Member Functions inherited from Speech::CorpusProcessor
void reportRealTime (Flow::Time)
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes
const BufferType bufferType_
const u32 regressionWindowSize_
Type of the buffer (single, batch, sequence)
const u32 slidingWindowSize_
const u32 slidingWindowSizeDerivatives_
bool shuffle_
Flag if feature shuffling is active.
std::vector< Math::FastMatrix< T > > featureBuffer_
std::vector< Math::FastMatrix< T > > derivativesBuffer_
std::vector< u32 > segmentIndexBuffer_
u32 maxBufferSize_
u32 nBufferedFeatures_
Maximal size for the feature buffer.
bool utteranceOverflow_
Number of frames in the feature buffer.
u32 nProcessedFeatures_
Set via checkIsTooLongSegment()
u32 segmentIndex_
Number of processed frames since last call to resetBuffer.
Bliss::Segment * curSegment_
u32 batchSize_
bool derivativesComputed_
Size of a batch in mini-batch mode.
u32 maxBufferedFeatureStreams_
std::vector< u32 > shuffledIndices_
Number of maximal feature streams in the buffer.
std::mt19937 shuffleRandomEngine_
Shuffled indices.
bool processRemainingFeatures_
bool needInit_
u32 nProcessedMiniBatches_
Flag to check for buffer initialization.
u32 totalNumberOfProcessedMiniBatches_
number of processed mini-batches, reset at resetBuffer
NeuralNetworkTrainer< T > * trainer_
not reset until corpus completely processed
Protected Attributes inherited from Speech::CorpusProcessor
Core::XmlChannel channelTimer_
Core::Timer timer_
Protected Attributes inherited from Core::Configurable
Configuration config
Static Protected Attributes
static const Core::Choice choiceBufferType
static const Core::ParameterChoice paramBufferType
static const Core::ParameterInt paramBufferSize
static const Core::ParameterBool paramShuffleBuffer
static const Core::ParameterInt paramShuffleBufferSeed
static const Core::ParameterInt paramBatchSize
static const Core::ParameterInt paramRegressionWindowSize
static const Core::ParameterInt paramSlidingWindowSize
static const Core::ParameterInt paramSlidingWindowSizeDerivatives
Private Types
typedef Speech::FeatureExtractor Precursor
Detailed Description
template<class T>
class Nn::BufferedFeatureExtractor< T >
Extension of the Speech::FeatureExtractor.
Samples/features are collected in a buffer before they are processed. Shuffling the data is possible.
Definition at line 38 of file BufferedFeatureExtractor.hh.
Member Enumeration Documentation
template<class T> enum Nn::BufferedFeatureExtractor::BufferType
Enumerator
batch
each mini-batch contains batch_size frames
utterance
buffer contains all frames in a single mini-batch
Definition at line 46 of file BufferedFeatureExtractor.hh.
Member Function Documentation
template<class T> u32 Nn::BufferedFeatureExtractor< T >::batchSize () const inline
Return the current size of a mini-batch.
Definition at line 128 of file BufferedFeatureExtractor.hh.
Referenced by Nn::BufferedFeatureExtractor< f32 >::signOn().
template<class T> u32 Nn::BufferedFeatureExtractor< T >::bufferSize () const inline
Returns the maximal size of the (feature) buffer in frames.
Definition at line 112 of file BufferedFeatureExtractor.hh.
template<typename T > Bliss::Segment * BufferedFeatureExtractor::getCurSegment () const
returns current segment if in segment mode
Definition at line 544 of file BufferedFeatureExtractor.cc.
References Nn::BufferedFeatureExtractor< f32 >::batch, Core::Component::log(), Nn::BufferedFeatureExtractor< f32 >::regressionWindowSize_, Nn::BufferedFeatureExtractor< f32 >::shuffle_, and Nn::BufferedFeatureExtractor< f32 >::utterance.
Referenced by Nn::BufferedFeatureExtractor< f32 >::batchSize().
template<typename T > void BufferedFeatureExtractor::initBuffer (std::vector< u32 > & nFeatures) virtual
Initialize the (feature) buffer.
Initialize the (feature) buffer. The number of elements in the buffer is limited by
Parameters
nFrames * @parame nFeatures
nFeatures Dimension of the features
nFrames Number of frames
Definition at line 151 of file BufferedFeatureExtractor.cc.
References Nn::BufferedFeatureExtractor< f32 >::nBufferedFeatures_.
Referenced by Nn::BufferedFeatureExtractor< f32 >::signOn().
template<typename T > void BufferedFeatureExtractor::initBuffer (Core::Ref< const Speech::Feature > f) virtual
Initialize the feature buffer.
Reimplemented in Nn::BufferedAlignedFeatureProcessor< T >, and Nn::BufferedAlignedFeatureProcessor< f32 >.
Definition at line 172 of file BufferedFeatureExtractor.cc.
References Nn::BufferedAlignedFeatureProcessor< f32 >::initBuffer().
template<typename T > void BufferedFeatureExtractor::initShuffle () virtual
Shuffle the indices of the buffer.
Shuffle the indices of the buffer of maximal
Parameters
nFrames.
nFrames Maximal number of frames to be shuffled
Definition at line 114 of file BufferedFeatureExtractor.cc.
References Core::Component::log(), Nn::BufferedFeatureExtractor< f32 >::nBufferedFeatures_, Nn::BufferedFeatureExtractor< f32 >::shuffledIndices_, Nn::BufferedFeatureExtractor< f32 >::shuffleRandomEngine_, and verify.
Referenced by Nn::BufferedFeatureExtractor< f32 >::signOn().
template<class T> bool Nn::BufferedFeatureExtractor< T >::isShuffled () const inline
Returns whether data shuffling is active or not.
Definition at line 120 of file BufferedFeatureExtractor.hh.
template<class T> u32 Nn::BufferedFeatureExtractor< T >::numberOfBufferedFeatures () const inline
Return the current number of buffered features.
Definition at line 116 of file BufferedFeatureExtractor.hh.
template<typename T > void BufferedFeatureExtractor::processFeature (Core::Ref< const Speech::Feature >) virtual
Override this function to achieve the features extracted form data source one-by-one.
Reimplemented from Speech::FeatureExtractor.
Definition at line 243 of file BufferedFeatureExtractor.cc.
References Nn::BufferedFeatureExtractor< f32 >::batch, Nn::BufferedAlignedFeatureProcessor< f32 >::initBuffer(), Core::Component::log(), Nn::BufferedFeatureExtractor< f32 >::nBufferedFeatures_, Nn::BufferedFeatureExtractor< f32 >::updateBufferedFeature(), and Nn::BufferedFeatureExtractor< f32 >::utterance.
template<typename T > void BufferedFeatureExtractor::resetBuffer () virtual
Update the feature buffer.
Reset the feature buffer.
Clean up and free the feature buffer. The current number of frames are set to 0. The buffer has to be initialized again when used.
Reimplemented in Nn::BufferedAlignedFeatureProcessor< T >, and Nn::BufferedAlignedFeatureProcessor< f32 >.
Definition at line 192 of file BufferedFeatureExtractor.cc.
References Nn::BufferedFeatureExtractor< f32 >::derivativesComputed_, Nn::BufferedFeatureExtractor< f32 >::nBufferedFeatures_, Nn::BufferedFeatureExtractor< f32 >::nProcessedFeatures_, Nn::BufferedFeatureExtractor< f32 >::nProcessedMiniBatches_, and Nn::BufferedFeatureExtractor< f32 >::utteranceOverflow_.
Referenced by Nn::BufferedFeatureExtractor< f32 >::signOn().
template<typename T > void BufferedFeatureExtractor::setWindowedFeature (u32 streamIndex, u32 indexInBuffer, u32 indexInMiniBatch, NnMatrix & miniBatch) protected
Initialize the shuffling.
Definition at line 298 of file BufferedFeatureExtractor.cc.
References Nn::BufferedFeatureExtractor< f32 >::batchSize(), Nn::BufferedFeatureExtractor< f32 >::derivativesComputed_, Nn::NeuralNetworkTrainer< T >::estimator(), Nn::BufferedFeatureExtractor< f32 >::getCurSegment(), Nn::NeuralNetworkTrainer< T >::hasEstimator(), Nn::BufferedFeatureExtractor< f32 >::initShuffle(), Nn::NeuralNetworkTrainer< T >::isInitialized(), Core::Component::log(), Nn::BufferedFeatureExtractor< f32 >::nBufferedFeatures_, Nn::NeuralNetworkTrainer< T >::needsToProcessAllFeatures(), Nn::BufferedFeatureExtractor< f32 >::nProcessedFeatures_, Nn::BufferedFeatureExtractor< f32 >::nProcessedMiniBatches_, Nn::NeuralNetworkTrainer< T >::processBatch_feedInput(), Nn::NeuralNetworkTrainer< T >::processBatch_finish(), Nn::BufferedFeatureExtractor< f32 >::regressionWindowSize_, Nn::BufferedAlignedFeatureProcessor< f32 >::resetBuffer(), Nn::BufferedFeatureExtractor< f32 >::segmentIndex_, Nn::NeuralNetworkTrainer< T >::setBatchSize(), Nn::BufferedFeatureExtractor< f32 >::setWindowedFeature(), Nn::BufferedFeatureExtractor< f32 >::shuffle_, Nn::BufferedFeatureExtractor< f32 >::shuffledIndices_, Nn::BufferedFeatureExtractor< f32 >::totalNumberOfProcessedMiniBatches_, Nn::BufferedFeatureExtractor< f32 >::trainer_, Nn::BufferedFeatureExtractor< f32 >::utterance, and Nn::BufferedFeatureExtractor< f32 >::utteranceOverflow_.
Referenced by Nn::BufferedFeatureExtractor< f32 >::signOn().
template<class T> u32 Nn::BufferedFeatureExtractor< T >::shuffledIndex (u32 index) const inline
Return the index of the random feature in the buffer.
Definition at line 124 of file BufferedFeatureExtractor.hh.
template<class T> virtual void Nn::BufferedFeatureExtractor< T >::signOn (Speech::CorpusVisitor & corpusVisitor) inline virtual
Override this function to sign on to services of the corpus visitor.
Note: call the signOn function of your predecessor.
Reimplemented from Speech::DataExtractor.
Reimplemented in Nn::BufferedAlignedFeatureProcessor< T >, and Nn::BufferedAlignedFeatureProcessor< f32 >.
Definition at line 136 of file BufferedFeatureExtractor.hh.
template<typename T > void BufferedFeatureExtractor::updateBufferedFeature (Core::Ref< const Speech::Feature > f) virtual
Initialize the feature buffer.
Update the feature buffer at index.
Definition at line 211 of file BufferedFeatureExtractor.cc.
References Core::Component::log(), Nn::BufferedFeatureExtractor< f32 >::nBufferedFeatures_, Nn::BufferedFeatureExtractor< f32 >::segmentIndex_, Nn::BufferedFeatureExtractor< f32 >::utterance, and Nn::BufferedFeatureExtractor< f32 >::utteranceOverflow_.
Referenced by Nn::BufferedFeatureExtractor< f32 >::signOn().
Member Data Documentation
template<class T> bool Nn::BufferedFeatureExtractor< T >::derivativesComputed_ protected
Size of a batch in mini-batch mode.
Definition at line 81 of file BufferedFeatureExtractor.hh.
template<class T> u32 Nn::BufferedFeatureExtractor< T >::nBufferedFeatures_ protected
Maximal size for the feature buffer.
Definition at line 75 of file BufferedFeatureExtractor.hh.
Referenced by Nn::BufferedFeatureExtractor< f32 >::numberOfBufferedFeatures().
template<class T> u32 Nn::BufferedFeatureExtractor< T >::nProcessedFeatures_ protected
Set via checkIsTooLongSegment()
Definition at line 77 of file BufferedFeatureExtractor.hh.
template<class T> u32 Nn::BufferedFeatureExtractor< T >::nProcessedMiniBatches_ protected
Flag to check for buffer initialization.
Definition at line 90 of file BufferedFeatureExtractor.hh.
template<class T> const u32 Nn::BufferedFeatureExtractor< T >::regressionWindowSize_ protected
Type of the buffer (single, batch, sequence)
Definition at line 64 of file BufferedFeatureExtractor.hh.
template<class T> u32 Nn::BufferedFeatureExtractor< T >::segmentIndex_ protected
Number of processed frames since last call to resetBuffer.
Definition at line 78 of file BufferedFeatureExtractor.hh.
template<class T> bool Nn::BufferedFeatureExtractor< T >::shuffle_ protected
Flag if feature shuffling is active.
Definition at line 68 of file BufferedFeatureExtractor.hh.
Referenced by Nn::BufferedFeatureExtractor< f32 >::isShuffled().
template<class T> std::vector<u32> Nn::BufferedFeatureExtractor< T >::shuffledIndices_ protected
Number of maximal feature streams in the buffer.
Definition at line 83 of file BufferedFeatureExtractor.hh.
template<class T> std::mt19937 Nn::BufferedFeatureExtractor< T >::shuffleRandomEngine_ protected
Shuffled indices.
Definition at line 84 of file BufferedFeatureExtractor.hh.
template<class T> u32 Nn::BufferedFeatureExtractor< T >::totalNumberOfProcessedMiniBatches_ protected
number of processed mini-batches, reset at resetBuffer
Definition at line 91 of file BufferedFeatureExtractor.hh.
template<class T> NeuralNetworkTrainer<T>* Nn::BufferedFeatureExtractor< T >::trainer_ protected
not reset until corpus completely processed
Definition at line 92 of file BufferedFeatureExtractor.hh.
template<class T> bool Nn::BufferedFeatureExtractor< T >::utteranceOverflow_ protected
Number of frames in the feature buffer.
Definition at line 76 of file BufferedFeatureExtractor.hh.
The documentation for this class was generated from the following files:
BufferedFeatureExtractor.hh
BufferedFeatureExtractor.cc