Sprint: Core::FormatSet Class Reference
Core::FormatSet Class Reference
Set of format-qualifiers.
#include <FormatSet.hh>
Classes
struct Format
Interface class for type specific formats.
class TypeSpecificFormats
String map of format object references for the type T.
Public Types
enum AccessMode { modeRead, modeWrite }
typedef StringHashMap< Ref< ReferenceCounted > > Formats
String map of type specific format maps.
Public Member Functions
FormatSet (const Configuration &c)
template<class T >
void registerFormat (const std::string &qualifier, const Format< T > *format, bool isDefault=false)
Registers a format in the format set.
template<class T >
bool read (const std::string &filename, T &o) const
Reads the object o of type T from the file filename.
template<class T >
bool write (const std::string &filename, const T &o) const
Stores the object o of type T in the file filename.
template<class T >
bool write (const std::string &filename, const T &o, int precision) const
Stores the object o of type T in the file filename.
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Private Member Functions
template<class T >
void getTypeSpecificFormats (Ref< TypeSpecificFormats< T >> &)
template<class T >
void getTypeSpecificFormats (Ref< TypeSpecificFormats< T >> &) const
template<class T >
bool getFormat (const std::string &qualifier, Ref< const Format< T >> &format) const
bool checkFile (const std::string &filename, AccessMode mode) const
Static Private Member Functions
static std::string getQualifier (const std::string &filename)
static std::string stripQualifier (const std::string &filename)
Private Attributes
Formats formats_
Static Private Attributes
static const std::string defaultQualifier
static const std::string qualifierDelimiter
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Set of format-qualifiers.
Supports filenames with format qualifiers, e.g. bin:foo.matrix, xml:foo.vector, etc. Usage: 1) Instantiate this class in every library, tipically in Application classes. 2) For your class Foo, derive from the Format<Foo> class your own formats, e.g. FooFormat : FormatSet::Format<Foo> {..}. 3) Implement the required read/write methods in FooFormat class.R 4) Register the your format at your library FormatSet object. 5) To read or store foo objects call the I/O function of the fomat set, e.g. Application::us()->formatSet()->read("xml:foo.xml", foo); Note: -You can have different types of format objects in one format set.
Definition at line 44 of file FormatSet.hh.
Member Typedef Documentation
typedef StringHashMap<Ref<ReferenceCounted> > Core::FormatSet::Formats
String map of type specific format maps.
Since the different type specific formats maps have only one common precursor, this map stores the list by referencing ReferenceCounted derived object. The type specific maps are casted back to their oroginal type TypeSpecificFormats<T> on demand when the type T becomes known via a call to read or write methods.
See also
getTypeSpecificFormats.
Definition at line 84 of file FormatSet.hh.
Member Function Documentation
template<class T > bool Core::FormatSet::read (const std::string & filename, T & o) const
Reads the object o of type T from the file filename.
filename can contain a format qualifier, e.g. xml:foo.matrix, bin:foo.cart.
Returns
is false if the specified format is not registered for the type T, or if the I/O operation was not successful. In case of an error error messages are generated.
Definition at line 206 of file FormatSet.hh.
template<class T > void Core::FormatSet::registerFormat (const std::string & qualifier, const Format< T > * format, bool isDefault = false)
Registers a format in the format set.
defines the string constant which chooses identifies the Format<T> object per type T, e.g.: bin, xml, ascii, dot, ... is pointer to a class derived from Format<T>. This class has to implement the abstract virtual I/O functions declared in Format class. Type T defines the object the can be read or written. Implement these classes next to your class T, and register it in the format set of the you library. If $s isDefault is true, the format $c format will be used for filenames without a type qualifier. Note, that there is only one default format per type T.
Definition at line 175 of file FormatSet.hh.
References Core::Component::error(), Core::ref(), and require.
Referenced by Nn::Module_::formats(), and Mm::Module_::formats().
template<class T > bool Core::FormatSet::write (const std::string & filename, const T & o) const
Stores the object o of type T in the file filename.
filename can contain a format qualifier, e.g. xml:foo.matrix, bin:foo.cart.
Returns
is false if the specified format is not registered for the type T, or if the I/O operation was not successful. In case of an error error messages are generated.
Definition at line 215 of file FormatSet.hh.
template<class T > bool Core::FormatSet::write (const std::string & filename, const T & o, int precision) const
Stores the object o of type T in the file filename.
precision specifies the precision with which numbers are represented. This functionality is mainly meant for text formats thus the default behaviour is ignoring this parameter. filename can contain a format qualifier, e.g. xml:foo.matrix, bin:foo.cart.
Returns
is false if the specified format is not registered for the type T, or if the I/O operation was not successful. In case of an error error messages are generated.
Definition at line 224 of file FormatSet.hh.
The documentation for this class was generated from the following files:
FormatSet.hh
FormatSet.cc