Sprint: Bliss::Lexicon Class Reference
Bliss::Lexicon Class Reference
The Bliss lexicon.
#include <Lexicon.hh>
Classes
struct Internal
Public Types
typedef const Lemma *const * LemmaIterator
typedef PronunciationList::const_iterator PronunciationIterator
typedef LemmaPronunciationList::const_iterator LemmaPronunciationIterator
typedef const SyntacticToken *const * SyntacticTokenIterator
typedef const EvaluationToken *const * EvaluationTokenIterator
Public Member Functions
Lexicon (const Core::Configuration &)
const Core::Dependency & getDependency () const
Lemma * newLemma ()
Create a new lemma.
Lemma * newLemma (const std::string &)
Create a new lemma with forced name.
void setOrthographicForms (Lemma *lemma, const std::vector< std::string > &orths)
Set the list of orthographic forms for a lemma.
void setDefaultLemmaName (Lemma *lemma)
Set the unique name of a lemma.
Pronunciation * getPronunciation (const std::string &phon)
Get a pronunciation for a string representation.
void addPronunciation (Lemma *lemma, Pronunciation *pron, f32 weight=1.0)
Add a pronunciation to a lemma.
void normalizePronunciationWeights (Lemma *lemma)
void setSyntacticTokenSequence (Lemma *lemma, const std::vector< std::string > &synt)
Set the a syntactic token sequence for a lemma.
void setDefaultSyntacticToken (Lemma *lemma)
void addEvaluationTokenSequence (Lemma *lemma, const std::vector< std::string > &eval)
Set the a evaluation token sequence for a lemma.
void setDefaultEvaluationToken (Lemma *lemma)
void defineSpecialLemma (const std::string &name, Lemma *lemma)
Assign a symbolic name to a lemma.
void load (const std::string &filename)
Load lexicon from XML file.
void writeXml (Core::XmlWriter &) const
void logStatistics () const
u32 nLemmas () const
std::pair< LemmaIterator, LemmaIterator > lemmas () const
Iterator-range giving access to the set of lemmas.
const Lemma * lemma (const std::string &str) const
Find a lemma via ID string.
const Lemma * specialLemma (const std::string &name) const
Find a lemma for a given symbolic name.
Core::Ref< const LemmaAlphabet > lemmaAlphabet () const
void setPhonemeInventory (Core::Ref< const PhonemeInventory >)
Core::Ref< const PhonemeInventory > phonemeInventory () const
The phoneme inventory of the lexicon.
u32 nPronunciations () const
Number of distinct pronunciations defined in the lexicon.
std::pair< PronunciationIterator, PronunciationIterator > pronunciations () const
Iterator-range giving access to the set of pronunciations.
u32 nLemmaPronunciations () const
Number of distinct lemma pronunciations defined in the lexicon.
std::pair< LemmaPronunciationIterator, LemmaPronunciationIterator > lemmaPronunciations () const
Iterator-range giving access to the set of lemma-pronunciations.
Core::Ref< const LemmaPronunciationAlphabet > lemmaPronunciationAlphabet () const
const LemmaPronunciation * lemmaPronunciation (s32 id) const
u32 nSyntacticTokens () const
std::pair< SyntacticTokenIterator, SyntacticTokenIterator > syntacticTokens () const
Iterator-range giving access to the set of syntactic tokens.
const SyntacticToken * syntacticToken (const std::string &synt) const
Find a syntactic token given its symbolic name.
const TokenInventory & syntacticTokenInventory () const
Core::Ref< const SyntacticTokenAlphabet > syntacticTokenAlphabet () const
u32 nEvaluationTokens () const
std::pair< EvaluationTokenIterator, EvaluationTokenIterator > evaluationTokens () const
Iterator-range giving access to the set of syntactic tokens.
const TokenInventory & evaluationTokenInventory () const
Core::Ref< const EvaluationTokenAlphabet > evaluationTokenAlphabet () const
const Letter * letter (const std::string &) const
const TokenInventory & letterInventory () const
Core::Ref< const LetterAlphabet > letterAlphabet () const
Core::Ref< Fsa::Automaton > createLemmaToOrthographyTransducer (bool shallIncludeVariants=true, bool onlyWithEvalToken=false) const
Create conversion transducer from lemma to orthographic forms.
Core::Ref< PhonemeToLemmaPronunciationTransducer > createPhonemeToLemmaPronunciationTransducer (bool disambiguate=true) const
Create mapping transducer from phoneme sequences to lemma pronunciation sequences.
Core::Ref< PhonemeToLemmaPronunciationTransducer > createPhonemeToLemmaPronunciationTransducer (size_t nDisambiguators, bool disambiguate, bool markInitialPhonesAndSilence=false) const
Core::Ref< PhonemeToLemmaPronunciationTransducer > createPhonemeToLemmaPronunciationAndStickPunctuationTransducer () const
Core::Ref< LemmaPronunciationToLemmaTransducer > createLemmaPronunciationToLemmaTransducer (u32 nDisambiguators=0) const
Create mapping transducer from lemma pronunciation to lemma sequences.
Core::Ref< LemmaToSyntacticTokenTransducer > createLemmaToSyntacticTokenTransducer (bool useEmptySyntacticTokenSequences=true, size_t nDisambiguators=0) const
Create mapping transducer from lemma sequences to syntactic token sequences.
Core::Ref< LemmaToEvaluationTokenTransducer > createLemmaToEvaluationTokenTransducer (bool allowAlternatives=true) const
Create mapping transducer from lemma sequences to evaluation token sequences.
Core::Ref< LemmaToEvaluationTokenTransducer > createLemmaToPreferredEvaluationTokenSequenceTransducer () const
Create mapping transducer from lemma sequences to evaluation token sequences.
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Member Functions
static LexiconRef create (const Core::Configuration &)
Create a new lexicon from a Configuration.
Protected Types
typedef Core::StringHashMap< Lemma * > LemmaMap
typedef std::vector< const LemmaPronunciation * > LemmaPronunciationList
typedef std::vector< const Pronunciation * > PronunciationList
typedef std::unordered_set< Pronunciation *, Pronunciation::Hash, Pronunciation::Equality > PronunciationMap
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions
Pronunciation * getOrCreatePronunciation (const std::vector< Phoneme::Id > &phonemes)
SyntacticToken * getOrCreateSyntacticToken (Symbol)
EvaluationToken * getOrCreateEvaluationToken (Symbol)
void parsePronunciation (const std::string &, std::vector< Phoneme::Id > &) const
Convert phonemic string to sequence of phoneme ids.
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes
Core::Dependency dependency_
SymbolSet symbols_
central string storage contains: orthographic forms, letters, lemma names, and syntactic and evaluation symbols
SymbolSequenceSet< Symbol > symbolSequences_
orthographic form lists
TokenInventory letters_
Core::Ref< const PhonemeInventory > phonemeInventory_
TokenInventory lemmas_
LemmaMap specialLemmas_
LemmaPronunciationList lemmaPronunciationsByIndex_
Core::Obstack< LemmaPronunciation > lemmaPronunciations_
Core::Obstack< Phoneme::Id > phon_
pronunciations
PronunciationList pronunciations_
PronunciationMap pronunciationMap_
Core::Obstack< const SyntacticToken * > synts_
syntactic token sequences
TokenInventory syntacticTokens_
Core::Obstack< const EvaluationToken * > evals_
evaluation token sequences
TokenInventory evaluationTokens_
Internal * internal_
Protected Attributes inherited from Core::Configurable
Configuration config
Static Private Attributes
static Core::ParameterString paramFilename
Friends
class LexiconElement
class Bliss::LetterAlphabet
class Bliss::LemmaAlphabet
class Bliss::LemmaPronunciationAlphabet
class Bliss::SyntacticTokenAlphabet
class Bliss::EvaluationTokenAlphabet
Detailed Description
The Bliss lexicon.
See the Bliss documentation and Lexicon Format Reference for comporehensive explanation.
An entry of the lexicon are called "lemma". (The term "word" is avoided because of its ambiguity.) A lemma has one or more orthographic forms, zero or more pronunciations (aka "acoustic words") and zero or more syntactic tokens (aka "language model words").
A lemma may be assigned a symbolic name, which the system can use to identify lemmas which have a special meaning to it. E.g. the silence word is is identified by the symbolic name "silence". Such lemmas a called "special lemmas".
Definition at line 484 of file Bliss/Lexicon.hh.
Member Function Documentation
void Bliss::Lexicon::addEvaluationTokenSequence (Lemma * lemma, const std::vector< std::string > & eval)
Set the a evaluation token sequence for a lemma.
void Bliss::Lexicon::addPronunciation (Lemma * lemma, Pronunciation * pron, f32 weight = 1.0)
Add a pronunciation to a lemma.
Parameters
pron a pronunciation, typically obtained from getPronunciation()
weight a non negative (e.g. the observation count)
static LexiconRef Bliss::Lexicon::create (const Core::Configuration &) static
Create a new lexicon from a Configuration.
If a file name is specified, that file is loaded into the new lexicon.
Returns
the newly created lexicon or 0 in case of failure (e.g. file not found).
Referenced by AllophoneTool::main(), TestApplication::main(), MeanSumfileCreator::main(), LmUtilityTool::main(), Costa::main(), Speech::ModelCombination::ModelCombination(), and AcousticModelTrainer::showMixtureSet().
Core::Ref<LemmaPronunciationToLemmaTransducer> Bliss::Lexicon::createLemmaPronunciationToLemmaTransducer (u32 nDisambiguators = 0) const
Create mapping transducer from lemma pronunciation to lemma sequences.
Pronunciation prior probability is included in the weights: Each weight correspond to LemmaPronunciation::pronunciationScore(). This means the result transducer models p(pron | lemma).
Referenced by Speech::BaseWordLatticeMerger::initialize(), Speech::NumeratorFromDenominatorExtractor::initialize(), Search::Wfst::Builder::BuildGrammar::process(), Search::Wfst::Builder::BuildLexicon::process(), Search::Wfst::Builder::LemmaMapping::process(), Speech::SegmentwiseAlignmentGenerator::setSegmentwiseFeatureExtractor(), and Speech::NumeratorFromDenominatorNode::work().
Core::Ref<LemmaToEvaluationTokenTransducer> Bliss::Lexicon::createLemmaToEvaluationTokenTransducer (bool allowAlternatives = true) const
Create mapping transducer from lemma sequences to evaluation token sequences.
Necessary, e.g., for computation of word (graph) error rate.
Referenced by Speech::BaseWordLatticeMerger::initialize(), Speech::NumeratorFromDenominatorExtractor::initialize(), and Speech::NumeratorFromDenominatorNode::work().
Core::Ref<Fsa::Automaton> Bliss::Lexicon::createLemmaToOrthographyTransducer (bool shallIncludeVariants = true, bool onlyWithEvalToken = false) const
Create conversion transducer from lemma to orthographic forms.
Note: For conversion from text string to lemmata you may prefer to use OrthographicParser or LemmaAcceptorBuilder. lemma-to-orthography transducer properties:
The lemma label is the first input symbol.
Output labels are (Unicode) letters. (Yes, individual letters! There are nor orthographic tokens!)
Parameters
shallIncludeVariants if true, all orthographic forms are included. Otherwise only the preferred (first) orthographic form of each lemma is included.
onlyWithEvalToken if true, only orthographic forms of lemmas which have at least one eval token are included.
Core::Ref<LemmaToEvaluationTokenTransducer> Bliss::Lexicon::createLemmaToPreferredEvaluationTokenSequenceTransducer () const
Create mapping transducer from lemma sequences to evaluation token sequences.
In the presence of alternative evaluation token sequences, the first is used.
Core::Ref<LemmaToSyntacticTokenTransducer> Bliss::Lexicon::createLemmaToSyntacticTokenTransducer (bool useEmptySyntacticTokenSequences = true, size_t nDisambiguators = 0) const
Create mapping transducer from lemma sequences to syntactic token sequences.
Necessary for composition with language model transducers/acceptors.
The lemma is the first input label.
Syntactic token emission scores are included. Weights correspond to SyntacticToken::classEmissionScore(), i.e. this automaton models p(lemma | synt).
Parameters
if useEmptySyntacticTokenSequences is false, those lemmas with an empty syntactic token sequence are suppressed.
Referenced by Search::Wfst::Builder::BuildGrammar::process(), Search::Wfst::Builder::BuildLexicon::process(), and Search::Wfst::Builder::LemmaMapping::process().
Core::Ref<PhonemeToLemmaPronunciationTransducer> Bliss::Lexicon::createPhonemeToLemmaPronunciationTransducer (bool disambiguate = true) const
Create mapping transducer from phoneme sequences to lemma pronunciation sequences.
Properties of the result transducer:
Phonemes are input labels.
The LemmaPronunciation is the first output label.
All phoneme strings are terminated with a disambiguator which serves as an end-of-word maker.
If shallDisambiguate is true, homophones are terminated by different disambiguators, so that the resulting transducer is determinizable. Otherwise all pronunciations end with the same disambiguator.
No disambiguators occur on the output side.
All weights are one.
The transducer is cyclic an accepts zero or more word. Partial words are not accepted.
Parameters
disambiguate if true, disambiguation symbols are added on the input side.
Referenced by Search::Wfst::Builder::BuildOldLexicon::process().
void Bliss::Lexicon::defineSpecialLemma (const std::string & name, Lemma * lemma)
Assign a symbolic name to a lemma.
Parameters
name is a symbolic name to which lemma is to be assigned. name must not have been assigned before.
lemma to be assigned to name
std::pair<EvaluationTokenIterator, EvaluationTokenIterator> Bliss::Lexicon::evaluationTokens () const inline
Iterator-range giving access to the set of syntactic tokens.
Definition at line 789 of file Bliss/Lexicon.hh.
Pronunciation* Bliss::Lexicon::getPronunciation (const std::string & phon)
Get a pronunciation for a string representation.
Parameters
phon a string containing a white-space separate list of phoneme symbols.
const Lemma* Bliss::Lexicon::lemma (const std::string & str) const inline
Find a lemma via ID string.
This name can either be given upon creation of a lemma or by setting a list of orthographic forms. In the later case we simple take the preferred orthographic form, possibly disambiguating it. The only purpose you want to use the lemma name for, is referencing a lemma from an external file (e.g. a word lattice).
Warning
You must not assciate a particular meaning with the name of a lemma. Never hard-code lemma names! Use specialLemma() instead!
Parameters
str a string ID
Returns
the lemma with the requested ID or 0 if there is no such lemma. A return value of 0, usually indicates an error (e.g. wrong lexicon), but it is the callers duty to handle this.
Definition at line 685 of file Bliss/Lexicon.hh.
Referenced by Speech::OrthographyFrameStateAccuracyLatticeBuilder::OrthographyFrameStateAccuracyLatticeBuilder(), and Search::Wfst::Builder::CheckLabels::process().
std::pair<LemmaPronunciationIterator, LemmaPronunciationIterator> Bliss::Lexicon::lemmaPronunciations () const inline
Iterator-range giving access to the set of lemma-pronunciations.
Definition at line 735 of file Bliss/Lexicon.hh.
std::pair<LemmaIterator, LemmaIterator> Bliss::Lexicon::lemmas () const inline
Iterator-range giving access to the set of lemmas.
Definition at line 639 of file Bliss/Lexicon.hh.
References ensure, and Bliss::Token::id().
void Bliss::Lexicon::load (const std::string & filename)
Load lexicon from XML file.
Lemma* Bliss::Lexicon::newLemma ()
Create a new lemma.
Lemma* Bliss::Lexicon::newLemma (const std::string &)
Create a new lemma with forced name.
u32 Bliss::Lexicon::nLemmaPronunciations () const inline
Number of distinct lemma pronunciations defined in the lexicon.
Definition at line 728 of file Bliss/Lexicon.hh.
u32 Bliss::Lexicon::nPronunciations () const inline
Number of distinct pronunciations defined in the lexicon.
Definition at line 713 of file Bliss/Lexicon.hh.
void Bliss::Lexicon::parsePronunciation (const std::string & , std::vector< Phoneme::Id > &) const protected
Convert phonemic string to sequence of phoneme ids.
Core::Ref<const PhonemeInventory> Bliss::Lexicon::phonemeInventory () const inline
The phoneme inventory of the lexicon.
Definition at line 708 of file Bliss/Lexicon.hh.
Referenced by Search::SearchSpace::minimumWordEndScore(), Search::SearchSpace::optimizeSilenceInWordLattice(), Search::Wfst::Builder::BuildOldLexicon::process(), and Search::Wfst::NonWordTokens::setNonWordPhones().
std::pair<PronunciationIterator, PronunciationIterator> Bliss::Lexicon::pronunciations () const inline
Iterator-range giving access to the set of pronunciations.
Definition at line 720 of file Bliss/Lexicon.hh.
Referenced by Search::Wfst::Builder::AddPronunciationWeight::process(), and Search::StateTree::pronunciationSuffixTransitEntry().
void Bliss::Lexicon::setDefaultLemmaName (Lemma * lemma)
Set the unique name of a lemma.
void Bliss::Lexicon::setOrthographicForms (Lemma * lemma, const std::vector< std::string > & orths)
Set the list of orthographic forms for a lemma.
void Bliss::Lexicon::setSyntacticTokenSequence (Lemma * lemma, const std::vector< std::string > & synt)
Set the a syntactic token sequence for a lemma.
const Lemma* Bliss::Lexicon::specialLemma (const std::string & name) const
Find a lemma for a given symbolic name.
This function should be used to associate a particular meaning with a lemma.
Returns
the lemma which is assigned to name or 0 iff name has not been assigned. A return value of 0 indicates that the used has not added the requested special lemma. It is the callers duty to handle this case appropriately.
Referenced by Speech::OrthographyFrameStateAccuracyLatticeBuilder::OrthographyFrameStateAccuracyLatticeBuilder().
const SyntacticToken* Bliss::Lexicon::syntacticToken (const std::string & synt) const inline
Find a syntactic token given its symbolic name.
This function is intended to be used for language model initialization. The symbolic name of a syntactic token must not be associated with a particular meaning.
Returns
the syntactic token with the given name, or 0 if there is no such token.
Definition at line 770 of file Bliss/Lexicon.hh.
std::pair<SyntacticTokenIterator, SyntacticTokenIterator> Bliss::Lexicon::syntacticTokens () const inline
Iterator-range giving access to the set of syntactic tokens.
Definition at line 756 of file Bliss/Lexicon.hh.
Member Data Documentation
Core::Obstack<const EvaluationToken*> Bliss::Lexicon::evals_ protected
evaluation token sequences
Definition at line 537 of file Bliss/Lexicon.hh.
Core::Obstack<Phoneme::Id> Bliss::Lexicon::phon_ protected
pronunciations
Definition at line 520 of file Bliss/Lexicon.hh.
SymbolSet Bliss::Lexicon::symbols_ protected
central string storage contains: orthographic forms, letters, lemma names, and syntactic and evaluation symbols
Definition at line 496 of file Bliss/Lexicon.hh.
SymbolSequenceSet<Symbol> Bliss::Lexicon::symbolSequences_ protected
orthographic form lists
Definition at line 499 of file Bliss/Lexicon.hh.
Core::Obstack<const SyntacticToken*> Bliss::Lexicon::synts_ protected
syntactic token sequences
Definition at line 531 of file Bliss/Lexicon.hh.
The documentation for this class was generated from the following file:
Bliss/Lexicon.hh