Sprint: Lm::HistoryManager Class Reference
Lm::HistoryManager Class Reference abstract
The HistoryManager serves as a memory manger for the HistoryDescriptors used by a LanguageModel.
#include <HistoryManager.hh>
Protected Member Functions
virtual HistoryHandle acquire (HistoryHandle)=0
Create a new reference to this history.
virtual void release (HistoryHandle)=0
Destroy a reference to this history.
virtual HistoryHash hashKey (HistoryHandle) const =0
If isEquivalent() is true For two descriptors, hashKey() must return the same value for both of them.
virtual bool isEquivalent (HistoryHandle, HistoryHandle) const =0
Test if two descriptors represent the same context.
virtual std::string format (HistoryHandle hd) const
Friends
class History
Detailed Description
The HistoryManager serves as a memory manger for the HistoryDescriptors used by a LanguageModel.
Each LanguageModel creates an appropriate HistoryManager. Clients should never bother about this class. HistoryManager also plays the role of a virtual method table for HistoryHandle.
Definition at line 39 of file HistoryManager.hh.
Member Function Documentation
virtual HistoryHandle Lm::HistoryManager::acquire (HistoryHandle) protected pure virtual
Create a new reference to this history.
This function is called whenever a new pointer to this history is required. You may instantiate a copy, increase a reference count, or whatever
Implemented in Lm::ReferenceCountingHistoryManager, Lm::StaticHistoryManager, Lm::SingletonHistoryManager, and Lm::NNHistoryManager.
Referenced by Lm::History::SentinelHistoryManager::hashKey().
virtual HistoryHash Lm::HistoryManager::hashKey (HistoryHandle) const protected pure virtual
If isEquivalent() is true For two descriptors, hashKey() must return the same value for both of them.
Implemented in Lm::StaticHistoryManager, Lm::SingletonHistoryManager, Lm::WordlistInterfaceLm, Lm::NNHistoryManager, Lm::History::SentinelHistoryManager, and Lm::FsaLm::HistoryManager.
Referenced by Lm::History::isValid().
virtual bool Lm::HistoryManager::isEquivalent (HistoryHandle , HistoryHandle) const protected pure virtual
Test if two descriptors represent the same context.
Note: The "check for equal pointers" optimization is already done before this function is called.
Implemented in Lm::StaticHistoryManager, Lm::SingletonHistoryManager, Lm::WordlistInterfaceLm, Lm::NNHistoryManager, and Lm::FsaLm::HistoryManager.
Referenced by Lm::History::isValid().
virtual void Lm::HistoryManager::release (HistoryHandle) protected pure virtual
Destroy a reference to this history.
This function should be redefined to complement the chosen strategy fo acquire()
Implemented in Lm::ReferenceCountingHistoryManager, Lm::StaticHistoryManager, Lm::SingletonHistoryManager, and Lm::NNHistoryManager.
Referenced by Lm::History::SentinelHistoryManager::hashKey().
The documentation for this class was generated from the following file:
HistoryManager.hh