Sprint: Mm::RpropDiscriminativeMixtureSetEstimatorWithISmoothing Class Reference
Mm::RpropDiscriminativeMixtureSetEstimatorWithISmoothing Class Reference
DiscriminativeMixtureSetEstimatorWithISmoothing: Rprop.
#include <RpropDiscriminativeMixtureSetEstimator.hh>
Public Member Functions
RpropDiscriminativeMixtureSetEstimatorWithISmoothing (const Core::Configuration &)
DiscriminativeMixtureSetEstimatorWithISmoothing: Rprop.
Public Member Functions inherited from Mm::ISmoothingMixtureSetEstimator
ISmoothingMixtureSetEstimator (const Core::Configuration &)
void set (DiscriminativeMixtureSetEstimator *)
void loadISmoothingMixtureSet ()
Sum getObjectiveFunction (const MixtureSet &, const MixtureSetEstimatorIndexMap &, const CovarianceToMeanSetMap &)
Estimate i-smoothing portion of objective function w.r.t.
Weight weightsConstant () const
Weight meansConstant () const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Mm::RpropDiscriminativeMixtureSetEstimator
RpropDiscriminativeMixtureSetEstimator (const Core::Configuration &)
virtual void read (Core::BinaryInputStream &)
virtual void write (Core::BinaryOutputStream &)
bool distributePreviousToPreviousMixtureSet (const MixtureSet &)
Public Member Functions inherited from Mm::DiscriminativeMixtureSetEstimator
DiscriminativeMixtureSetEstimator (const Core::Configuration &)
DiscriminativeMixtureSetEstimator.
virtual void reset ()
virtual void write (Core::XmlWriter &)
virtual bool operator== (const AbstractMixtureSetEstimator &) const
virtual void estimate (MixtureSet &)
virtual bool accumulate (Core::BinaryInputStreams &is, Core::BinaryOutputStream &os)
virtual bool accumulate (const AbstractMixtureSetEstimator &)
void accumulateDenominator (MixtureIndex mixtureIndex, Core::Ref< const Feature::Vector >, Weight)
void accumulateObjectiveFunction (Score)
Sum objectiveFunction () const
bool distributePreviousMixtureSet (const MixtureSet &)
Public Member Functions inherited from Mm::AbstractMixtureSetEstimator
AbstractMixtureSetEstimator (const Core::Configuration &)
void setTopology (Core::Ref< const MixtureSet >)
MixtureIndex nMixtures () const
ComponentIndex dimension () const
MixtureEstimators * getMixtureEstimators ()
Weight minObservationWeight () const
Weight minRelativeWeight () const
void checkEventsWithZeroWeight ()
void setAssigningFeatureScorer (Core::Ref< const AssigningFeatureScorer > assigningFeatureScorer)
void accumulate (MixtureIndex mixtureIndex, Core::Ref< const Feature::Vector >)
void accumulate (MixtureIndex mixtureIndex, Core::Ref< const Feature::Vector >, Weight)
bool addMixtureEstimators (const AbstractMixtureSetEstimator &estimator)
add new mixture estimators
bool createPooledCovarianceEstimator ()
accumulate a single covariance estimator from all estimators.
bool createMixtureSpecificCovarianceEstimator ()
create a copy of a pooled covariance estimator and set it as mixture specific covariance estimator in all densities
Core::Ref< MixtureSet > estimate ()
void estimate (MixtureSet &, std::vector< Weight > &meanObservationWeights, std::vector< Weight > &covarianceObservationWeights)
bool equalTopology (const AbstractMixtureSetEstimator &) const
void writeStatistics () const
bool map (const std::string &mapping)
bool changeDensityMixtureAssignment (std::vector< std::vector< DensityIndex >> stateDensityTable)
void setWeightThreshold (Weight weightThreshold)
void setMixtureLabels (std::map< int, std::string > &labels)
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Protected Types
typedef ISmoothingMixtureSetEstimator ISmoothing
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions
virtual RpropDiscriminativeMixtureEstimatorWithISmoothing * createMixtureEstimator ()
virtual RpropDiscriminativeGaussDensityEstimatorWithISmoothing * createDensityEstimator ()
virtual RpropDiscriminativeGaussDensityEstimatorWithISmoothing * createDensityEstimator (const GaussDensity &)
virtual RpropDiscriminativeMeanEstimatorWithISmoothing * createMeanEstimator ()
virtual RpropDiscriminativeMeanEstimatorWithISmoothing * createMeanEstimator (const Mean &)
virtual RpropDiscriminativeCovarianceEstimatorWithISmoothing * createCovarianceEstimator ()
virtual RpropDiscriminativeCovarianceEstimatorWithISmoothing * createCovarianceEstimator (const Covariance &)
virtual RpropDiscriminativeMixtureEstimatorWithISmoothing & mixtureEstimator (MixtureIndex mixture)
virtual void setIMixture (Core::Ref< AbstractMixtureEstimator >, const Mixture *, Weight iSmoothing)
virtual void setIDensity (Core::Ref< GaussDensityEstimator >, const GaussDensity *)
virtual void setIMean (Core::Ref< AbstractMeanEstimator >, const Mean *, Weight iSmoothing)
virtual void setICovariance (Core::Ref< AbstractCovarianceEstimator >, const Covariance *, Weight iSmoothing)
virtual Weight getMixtureObjectiveFunction (Core::Ref< AbstractMixtureEstimator > estimator)
virtual Weight getCovarianceObjectiveFunction (Core::Ref< AbstractCovarianceEstimator > estimator, const CovarianceToMeanSetMap &meanSetMap)
virtual void load ()
virtual void finalize (MixtureSet &, const MixtureSetEstimatorIndexMap &, const CovarianceToMeanSetMap &)
Protected Member Functions inherited from Mm::ISmoothingMixtureSetEstimator
bool distributeISmoothingMixtureSet (const MixtureSet &)
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Member Functions inherited from Mm::RpropDiscriminativeMixtureSetEstimator
virtual bool accumulateMixture (Core::BinaryInputStreams &is, Core::BinaryOutputStream &os)
virtual const std::string magic () const
virtual void initialize (const MixtureSetEstimatorIndexMap &, const CovarianceToMeanSetMap &)
void loadStepSizes ()
void storeStepSizes ()
bool distributeStepSizes (const MixtureSet &stepSizes)
bool distributeStepSizes (Weight stepSizeWeights, Weight stepSizeMeans, Weight stepSizeVariances)
bool distributeSettings ()
void collectStepSizes (MixtureSet &stepSizes)
void loadPreviousToPreviousMixtureSet ()
Protected Member Functions inherited from Mm::DiscriminativeMixtureSetEstimator
void loadPreviousMixtureSet ()
Set the previous mixture set, i.e., the means and covariances.
Protected Member Functions inherited from Mm::AbstractMixtureSetEstimator
void removeDensitiesWithZeroWeight ()
void removeDensitiesWithLowWeight (Weight minObservationWeight, Weight minRelativeWeight)
DensityIndex densityIndex (MixtureIndex, Core::Ref< const Feature::Vector >)
void getDensityPosteriorProbabilities (MixtureIndex, Core::Ref< const Feature::Vector >, std::vector< Mm::Weight > &)
void readHeader (Core::BinaryInputStream &)
void writeHeader (Core::BinaryOutputStream &)
virtual bool accumulateDensity (Core::BinaryInputStreams &is, Core::BinaryOutputStream &os)
Private Types
typedef RpropDiscriminativeMixtureSetEstimator Precursor
Additional Inherited Members
Public Types inherited from Mm::AbstractMixtureSetEstimator
enum Mode { modeViterbi, modeBaumWelch }
typedef std::vector< Core::Ref< AbstractMixtureEstimator > > MixtureEstimators
Static Public Attributes inherited from Mm::AbstractMixtureSetEstimator
static const Core::Choice choiceMode
static const Core::ParameterChoice paramMode
static const Core::ParameterFloat paramMinObservationWeight
static const Core::ParameterFloat paramMinRelativeWeight
static const Core::ParameterFloat paramMinVariance
static const Core::ParameterBool paramAllowZeroWeights
static const Core::ParameterBool paramNormalizeMixtureWeights
Protected Attributes inherited from Core::Configurable
Configuration config
Protected Attributes inherited from Mm::DiscriminativeMixtureSetEstimator
Sum objectiveFunction_
Core::Configuration mixtureEstimatorConfig_
Protected Attributes inherited from Mm::AbstractMixtureSetEstimator
Core::Ref< const AssigningFeatureScorer > assigningFeatureScorer_
bool viterbi_
Weight weightThreshold_
Weight minObservationWeight_
Weight minRelativeWeight_
VarianceType minVariance_
bool allowZeroWeights_
bool normalizeMixtureWeights_
Core::Statistics< f64 > scoreStatistics_
ProbabilityStatistics weightStats_
ProbabilityStatistics dnsPosteriorStats_
ProbabilityStatistics finalWeightStats_
Core::XmlChannel accumulationChannel_
MixtureEstimators mixtureEstimators_
ComponentIndex dimension_
u32 version_
std::map< int, std::string > mixtureLabels_
Static Protected Attributes inherited from Mm::RpropDiscriminativeMixtureSetEstimator
static const Core::ParameterFloat paramInitialStepSizeWeights
RpropDiscriminativeMixtureSetEstimator.
static const Core::ParameterFloat paramInitialStepSizeMeans
static const Core::ParameterFloat paramInitialStepSizeVariances
static const Core::ParameterString paramNewStepSizesFilename
Detailed Description
DiscriminativeMixtureSetEstimatorWithISmoothing: Rprop.
Definition at line 75 of file RpropDiscriminativeMixtureSetEstimator.hh.
Constructor & Destructor Documentation
RpropDiscriminativeMixtureSetEstimatorWithISmoothing::RpropDiscriminativeMixtureSetEstimatorWithISmoothing (const Core::Configuration & c)
DiscriminativeMixtureSetEstimatorWithISmoothing: Rprop.
Definition at line 314 of file RpropDiscriminativeMixtureSetEstimator.cc.
References Core::Ref< T >::get(), Mm::ISmoothingMixtureSetEstimator::getObjectiveFunction(), Core::Component::log(), required_cast, and Mm::ISmoothingMixtureEstimator::setIMixture().
The documentation for this class was generated from the following files:
RpropDiscriminativeMixtureSetEstimator.hh
RpropDiscriminativeMixtureSetEstimator.cc