Sprint: Speech::TextDependentMixtureSetTrainer Class Reference
Speech::TextDependentMixtureSetTrainer Class Reference
TextDependentMixtureSetTrainer.
#include <AcousticModelTrainer.hh>
Public Member Functions
TextDependentMixtureSetTrainer (const Core::Configuration &)
Public Member Functions inherited from Speech::AcousticModelTrainer
void signOn (CorpusVisitor &corpusVisitor)
Override this function to sign on to services of the corpus visitor.
AcousticModelTrainer (const Core::Configuration &c, Am::AcousticModel::Mode mode)
Public Member Functions inherited from Speech::AlignedFeatureProcessor
AlignedFeatureProcessor (const Core::Configuration &c)
virtual void enterCorpus (Bliss::Corpus *)
Override this function to perform preparations before first segment is processed.
virtual void leaveCorpus (Bliss::Corpus *)
Override this function to perform post processing after the last segment is processed.
virtual void enterSegment (Bliss::Segment *)
Override this function to perform preparations before first aligned features arrive.
virtual void leaveSegment (Bliss::Segment *)
Override this function to perform post processing after the last aligned features of the segment.
virtual void enterSpeechSegment (Bliss::SpeechSegment *)
Override this function to perform preparations before first aligned features arrive.
virtual void leaveSpeechSegment (Bliss::SpeechSegment *)
Override this function to perform post processing after the last aligned features of the segment.
virtual void processAlignedFeature (Core::Ref< const Feature >, Am::AllophoneStateIndex, Mm::Weight, Mm::Weight)
Override this function to implement the processing of feature vectors with two weights.
virtual void setDataSource (Core::Ref< DataSource >)
Override this function to obtain the data source of corpus processor which produces the labels.
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Speech::MlMixtureSetTrainer
MlMixtureSetTrainer (const Core::Configuration &)
Maximum likelihood mixture set trainer.
Public Member Functions inherited from Speech::MixtureSetTrainer
MixtureSetTrainer (const Core::Configuration &)
void initializeAccumulation (size_t nMixtures, size_t dimension, Core::Ref< const Mm::AssigningFeatureScorer > assigningFeatureScorer=Core::Ref< Mm::AssigningFeatureScorer >(), Core::Ref< Mm::MixtureSet > mixtureSet=Core::Ref< Mm::MixtureSet >())
void accumulate (Core::Ref< const Feature::Vector > f, Mm::MixtureIndex m)
void accumulate (Core::Ref< const Feature::Vector > f, Mm::MixtureIndex m, Mm::Weight w)
virtual void read ()
bool combine (const std::vector< std::string > &toCombine)
bool combinePartitions (const std::vector< std::string > &toCombine)
void write () const
void write (Core::XmlWriter &o, std::map< int, std::string > &mixtureLabels) const
size_t dimension () const
size_t nMixtures () const
bool map (const std::string &mappingFilename)
void setWeightThreshold (Mm::Weight weightThreshold)
void setAssigningFeatureScorer (Core::Ref< const Mm::AssigningFeatureScorer > assigningFeatureScorer)
Protected Member Functions
virtual void setFeatureDescription (const Mm::FeatureDescription &)
Override this function to achieve the attributes of the feature streams.
virtual void processAlignedFeature (Core::Ref< const Feature > f, Am::AllophoneStateIndex e)
Override this function to implement the processing of Viterbi-aligned feature vectors.
virtual void processAlignedFeature (Core::Ref< const Feature > f, Am::AllophoneStateIndex e, Mm::Weight w)
Override this function to implement the processing of Baum-Welch-aligned feature vectors.
Protected Member Functions inherited from Speech::AcousticModelTrainer
Bliss::LexiconRef lexicon () const
Core::Ref< Am::AcousticModel > acousticModel () const
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Member Functions inherited from Speech::MlMixtureSetTrainer
virtual Mm::MixtureSetEstimator * createMixtureSetEstimator () const
Protected Member Functions inherited from Speech::MixtureSetTrainer
const Core::Ref< Mm::MixtureSet > estimate () const
void setAssigningFeatureScorer (const Core::Ref< Mm::MixtureSet >, Core::Ref< const Mm::AssigningFeatureScorer > assigningFeatureScorer=Core::Ref< Mm::AssigningFeatureScorer >())
bool firstRun ()
void checkCovarianceTying ()
void clear ()
bool read (const std::string &filename, Mm::AbstractMixtureSetEstimator &)
void read (const std::string &filename)
void write (const std::string &filename) const
virtual const Core::Ref< Mm::MixtureSet > getMixtureSet (size_t nMixtures, size_t dimension)
Private Attributes
Mm::FeatureDescription featureDescription_
bool initialized_
Additional Inherited Members
Static Public Attributes inherited from Speech::MixtureSetTrainer
static const Core::ParameterString paramOldMixtureSetFilename
Mixture set trainer: base class.
static const Core::ParameterString paramNewMixtureSetFilename
static const Core::ParameterBool paramSplitFirst
static const Core::ParameterBool paramForceCovarianceTying
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Attributes inherited from Core::Configurable
Configuration config
Protected Attributes inherited from Speech::MixtureSetTrainer
Mm::AbstractMixtureSetEstimator * estimator_
Core::Ref< const Mm::AssigningFeatureScorer > assigningFeatureScorer_
Detailed Description
TextDependentMixtureSetTrainer.
Definition at line 59 of file Speech/AcousticModelTrainer.hh.
Member Function Documentation
virtual void Speech::TextDependentMixtureSetTrainer::processAlignedFeature (Core::Ref< const Feature > f, Am::AllophoneStateIndex e) inline protected virtual
Override this function to implement the processing of Viterbi-aligned feature vectors.
Reimplemented from Speech::AcousticModelTrainer.
Definition at line 68 of file Speech/AcousticModelTrainer.hh.
References Mm::Feature::mainStream().
virtual void Speech::TextDependentMixtureSetTrainer::processAlignedFeature (Core::Ref< const Feature > , Am::AllophoneStateIndex , Mm::Weight) inline protected virtual
Override this function to implement the processing of Baum-Welch-aligned feature vectors.
Reimplemented from Speech::AcousticModelTrainer.
Definition at line 71 of file Speech/AcousticModelTrainer.hh.
References Mm::Feature::mainStream().
void TextDependentMixtureSetTrainer::setFeatureDescription (const Mm::FeatureDescription &) protected virtual
Override this function to achieve the attributes of the feature streams.
This function is called once before the first feature vector is processed.
Reimplemented from Speech::AlignedFeatureProcessor.
Definition at line 51 of file Speech/AcousticModelTrainer.cc.
References Core::Description::Stream::getValue(), and Speech::AlignedFeatureProcessor::setFeatureDescription().
The documentation for this class was generated from the following files:
Speech/AcousticModelTrainer.hh
Speech/AcousticModelTrainer.cc