Sprint: Cart::XmlQuestionRefListBuilderElement Class Reference
Cart::XmlQuestionRefListBuilderElement Class Reference
<questions> <question index="0" description="hmm-state"> <key> state </key> <values> 1, 2 </values> </question> <question description="sampling rate"> <key> 16kHz_sampling_rate </key> </question> ...
#include <Parser.hh>
Public Member Functions
XmlQuestionRefListBuilderElement (const char *name, Core::XmlContext *context)
void set (PropertyMapRef mapRef)
void start (const XmlAttributes atts)
Handle start of the current XML element.
void end ()
Handle end of the current XML element.
void characters (const char *ch, int len)
Handle charcter data in the current XML element.
Public Member Functions inherited from Core::XmlMixedElement
virtual XmlElement * element (const char *name)
Determine the state to be entered for a nested XML element.
XmlMixedElement (const char *_name, XmlContext *_context)
XmlMixedElement (const char *_name, XmlContext *_context, XmlElement *child,...)
Constructor.
void addChild (XmlElement *decl)
Add a new child element.
Public Member Functions inherited from Core::XmlParentElement
XmlParentElement (const char *_name, XmlContext *_context)
void flattenUnknownElements ()
void ignoreUnknownElements ()
Public Member Functions inherited from Core::XmlElement
XmlElement (const char *_name, XmlContext *_context)
const char * name () const
XmlContext * context () const
virtual XmlSchemaParser * parser ()
virtual bool matches (const char *_name) const
Public Member Functions inherited from Core::BuildDelegation< T >
void setParsedHandler (ParsedHandler *handler)
template<class HandlerClass >
void setParsedHandler (HandlerClass &handler, void(HandlerClass::*deleg)(const T &))
void resetParsedHandler ()
void setCreatedHandler (CreatedHandler *handler)
template<class HandlerClass >
void setCreatedHandler (HandlerClass &handler, void(HandlerClass::*deleg)(T *))
void resetCreatedHandler ()
Protected Types
typedef XmlQuestionRefListBuilderElement Self
typedef XmlMixedElement Precursor
Protected Member Functions
void addQuestion (const std::string &key, const std::string &value)
void addQuestion (const std::string &key, const std::vector< std::string > &values)
void forEachValue (const std::string &key)
void forEachKey ()
void key (const std::string &key)
void values (const std::string &values)
void startForEachKey (const Core::XmlAttributes atts)
void endForEachKey ()
void startForEachValue (const Core::XmlAttributes atts)
void endForEachValue ()
void startQuestion (const XmlAttributes atts)
void endQuestion ()
Protected Member Functions inherited from Core::XmlMixedElement
void vAddChildren (va_list)
Protected Member Functions inherited from Core::XmlParentElement
virtual XmlElement * unexpectedElement ()
Protected Member Functions inherited from Core::XmlElement
XmlElement * collect (XmlElement *child)
Collects child elements.
Protected Member Functions inherited from Core::BuildDelegation< T >
void delegate (T *t)
Calls first parsed handler and then created handler.
void delegateOrDelete (T *t)
Calls first parsed handler and then created handler; if no created handler exists, t is deleted.
T * delegateAndCreate (T *t)
Calls first parsed handler and then created handler; return t if no created handler exists, else return a newly created instance of T .
bool delegateParsed (const T &t)
Calls parsed handler.
bool delegateCreated (T *t)
Calls created handler.
Protected Member Functions inherited from Core::Delegation< const T & >
void set (Target *target)
void set (TargetClass &tc, void(TargetClass::*tm)(const T &))
void reset ()
bool hasTarget ()
void delegate (const T &t)
Protected Member Functions inherited from Core::Delegation< T * >
void set (Target *target)
void set (TargetClass &tc, void(TargetClass::*tm)(T *))
void reset ()
bool hasTarget ()
void delegate (T *t)
Private Attributes
PropertyMapRef mapRef_
QuestionRefList * questionRefs_
Question::QuestionIndex index_
std::string desc_
std::string key_
std::vector< std::string > values_
bool isForEachKey_
bool isForEachValue_
std::vector< std::string > keyList_
std::vector< std::string > valueList_
XmlStringBuilderElement * keyBuilder_
XmlStringBuilderElement * valueBuilder_
XmlStringBuilderElement * valuesBuilder_
XmlRegularElementRelay * questionElement_
XmlMixedElementRelay * forEachKeyElement_
XmlMixedElementRelay * forEachValueElement_
bool warnOnQuestionIndex_
Additional Inherited Members
Public Types inherited from Core::XmlElement
typedef XmlElement * pointer
Public Types inherited from Core::XmlContext
typedef XmlContext Self
typedef void(Self::* StartHandler) (const XmlAttributes atts)
typedef void(Self::* EndHandler) ()
typedef void(Self::* CharactersHandler) (const char *ch, int len)
Public Types inherited from Core::BuildDelegation< T >
typedef Delegation< const T & > ParsedDelegation
typedef Delegation< T * > CreatedDelegation
typedef ParsedDelegation::Target ParsedHandler
typedef CreatedDelegation::Target CreatedHandler
Static Public Member Functions inherited from Core::XmlContext
template<class T >
static StartHandler startHandler (void(T::*h)(const XmlAttributes atts))
template<class T >
static EndHandler endHandler (void(T::*h)())
template<class T >
static CharactersHandler charactersHandler (void(T::*h)(const char *ch, int len))
Static Public Attributes inherited from Core::XmlElement
static const char * wildcard = " * "
Protected Attributes inherited from Core::XmlMixedElement
std::vector< XmlElement * > children_
Protected Attributes inherited from Core::XmlParentElement
XmlElement * unexpectedElement_
Detailed Description
<questions> <question index="0" description="hmm-state"> <key> state </key> <values> 1, 2 </values> </question> <question description="sampling rate"> <key> 16kHz_sampling_rate </key> </question> ...
<for-each-key keys="history[1], history[0], central, future[0], future[1]"> <question description="vowels"> <values> a, e, i, o, u </values> </question> </for-each-key> ... <for-each-key> <for-each-value> <question> </for-each-value> </for-each-key> ... </questions>
Definition at line 154 of file Parser.hh.
Member Function Documentation
void XmlQuestionRefListBuilderElement::characters (const char * ch, int len) virtual
Handle charcter data in the current XML element.
Parameters
parser The XmlSchemaParser delegating the request.
Implements Core::XmlElement.
Definition at line 379 of file Parser.cc.
void XmlQuestionRefListBuilderElement::end () virtual
Handle end of the current XML element.
end() is called when end tag of the current element is found.
Parameters
parser The XmlSchemaParser delegating the request.
Reimplemented from Core::XmlElement.
Definition at line 374 of file Parser.cc.
References Core::BuildDelegation< T >::delegateOrDelete(), and Core::XmlEmptyElement::end().
void XmlQuestionRefListBuilderElement::start (const XmlAttributes atts) virtual
Handle start of the current XML element.
start() is called when the current state is entered.
Parameters
atts attributes of the XML start tag which caused the parser to enter this state. The name of the element will generally be implied by the fact that THIS state is entered.
Reimplemented from Core::XmlElement.
Definition at line 367 of file Parser.cc.
References require, and Core::XmlElement::start().
The documentation for this class was generated from the following files:
Parser.hh
Parser.cc