Sprint: Search::LinearSearch::Pronunciation Class Reference
Search::LinearSearch::Pronunciation Class Reference
Classes
struct MixtureItem
Public Types
typedef std::vector< MixtureItem > MixtureVector
Public Member Functions
const Bliss::LemmaPronunciation *const lemma ()
Pronunciation (const Bliss::LemmaPronunciation *const lemma, const Am::AcousticModel *acousticModel)
size_t nMixtures ()
MixtureVector & mixtures ()
bool isRegularWord () const
Private Member Functions
bool isRegularWordPrivate () const
Private Attributes
bool isRegularWord_
const Bliss::LemmaPronunciation *const lemma_
MixtureVector mixtures_
Detailed Description
Definition at line 45 of file LinearSearch.hh.
Constructor & Destructor Documentation
Search::LinearSearch::Pronunciation::Pronunciation (const Bliss::LemmaPronunciation *const lemma, const Am::AcousticModel * acousticModel)
Get the allophone:
Definition at line 32 of file LinearSearch.cc.
References Bliss::Lemma::evaluationTokenSequences(), Bliss::Pronunciation::length(), Bliss::PhonemeInventory::phoneme(), and verify.
The documentation for this class was generated from the following files:
LinearSearch.hh
LinearSearch.cc