Sprint: Nn::Adam< T > Class Template Reference
Nn::Adam< T > Class Template Reference
Public Member Functions
Adam (const Core::Configuration &config)
virtual void estimate (NeuralNetwork< T > &network, Statistics< T > &statistics)
virtual std::string type () const
virtual u32 requiredStatistics () const
bool isDefaultConfig ()
Public Member Functions inherited from Nn::Estimator< T >
Estimator (const Core::Configuration &config)
virtual bool fullBatchMode () const
virtual void setFullBatchMode (bool fullBatchMode)
virtual int accumulateMultipleBatches () const
virtual T learningRate () const
virtual T biasLearningRateFactor () const
virtual void setLearningRate (T rate)
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Attributes
static const Core::ParameterBool paramUsePredefinedLearningRateDecay
static const Core::ParameterFloat paramLearningRateTau
static const Core::ParameterInt paramNumberOfUpdates
static const Core::ParameterFloat paramClippingThreshold
static const Core::ParameterFloat paramMomentumFactor
static const Core::ParameterFloat paramBeta1
static const Core::ParameterFloat paramBeta2
static const Core::ParameterFloat paramEpsilon
Static Public Attributes inherited from Nn::Estimator< T >
static const Core::Choice choiceEstimatorType
static const Core::ParameterChoice paramEstimatorType
static const Core::ParameterBool paramBatchMode
static const Core::ParameterInt paramAccumulateMultipleBatches
static const Core::ParameterFloat paramLearningRate
static const Core::ParameterFloat paramBiasLearningRate
static const Core::ParameterBool paramLogStepSize
Protected Attributes
bool usePredefinedLearningRateDecay_
T tau_
u32 nUpdates_
T clippingThreshold_
T momentumFactor_
bool momentum_
Statistics< T > * oldDeltas_
std::map< u32, NnMatrix * > m_
std::map< u32, NnMatrix * > v_
std::map< u32, NnMatrix * > M_
std::map< u32, NnMatrix * > V_
std::map< u32, NnMatrix * > g2_
u32 max_stream_
T b1_
T b2_
T eps_
Protected Attributes inherited from Nn::Estimator< T >
Core::XmlChannel statisticsChannel_
bool fullBatchMode_
int accumulateMultipleBatches_
T initialLearningRate_
T biasLearningRate_
bool logStepSize_
Protected Attributes inherited from Core::Configurable
Configuration config
Private Types
typedef Estimator< T > Precursor
typedef Types< T >::NnVector NnVector
typedef Types< T >::NnMatrix NnMatrix
Additional Inherited Members
Public Types inherited from Nn::Estimator< T >
enum EstimatorType {
dummy, dryRun, steepestDescentEstimator, steepestDescentL1Clipping,
meanNormalizedSgd, meanNormalizedSgdL1Clipping, rprop, priorEstimator,
adam, adagrad, adadelta, rmsprop
}
Static Public Member Functions inherited from Nn::Estimator< T >
static Estimator< T > * createEstimator (const Core::Configuration &config)
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Detailed Description
template<typename T>
class Nn::Adam< T >
Definition at line 220 of file Estimator.hh.
Member Function Documentation
template<typename T > void Adam::estimate (NeuralNetwork< T > & network, Statistics< T > & statistics) virtual
data structures are allocated as follows: max_stream_ = maximum number of streams per layer (over all layers), e.g. 2 pointer maps are indexed using the following scheme (layer l, stream s) weights "w", bias "b"
0 -> l0s0w (0 * (2+1) + 0) 1 -> l0s1w (0 * (2+1) + 1) 2 -> l0b (0 * (2+1) + 2)
3 -> l1s0w (1 * (2+1) + 0) 5 -> l1b (1 * (2+1) + 2)
6 -> l2s0w (2 * (2+1) + 0) 8 -> l2b (2 * (2+1) + 2) ... for weight matrices: idx = layer * (max_stream_+1) + stream for bias vectors: idx = layer * (max_stream_+1) + max_stream_
Reimplemented from Nn::Estimator< T >.
Definition at line 429 of file Estimator.cc.
References Core::Component::error(), Nn::NeuralNetwork< T >::getLayer(), Nn::Statistics< T >::gradientWeights(), Core::Component::log(), require, and Core::vector2str().
The documentation for this class was generated from the following files:
Estimator.hh
Estimator.cc