Sprint: Core::TsRef< T > Class Template Reference
Core::TsRef< T > Class Template Reference
Class template for smart pointers using intrusive reference-counting in a multithreaded environment.
#include <ThreadSafeReference.hh>
Public Member Functions
TsRef (Object *o)
TsRef (const TsRef &r)
Copy Constructor for the Type Ref<T>
template<class S >
TsRef (const TsRef< S > &r)
Template Copy Constuctor Using templates solves the problem of casting ...
TsRef & operator= (const TsRef &rhs)
template<class S >
TsRef & operator= (const TsRef< S > &rhs)
void reset ()
Reset to void.
bool operator== (const TsRef &r) const
Test for identity.
template<class S >
bool operator== (const TsRef< S > &r) const
bool operator!= (const TsRef &r) const
Test for non-identity.
template<class S >
bool operator!= (const TsRef< S > &r) const
operator bool () const
Test for non-voidness.
bool operator! () const
Test for voidness.
Object & operator* () const
Object * operator-> () const
Object * get () const
Explicit conversion to normal pointer.
Object * _get () const
Copies the value of the pointer.
Protected Types
typedef T Object
Protected Member Functions
void referenceObject (Object *obj)
void reference ()
void unreference ()
void set (Object *o)
Takes over the value of.
Static Protected Member Functions
static Object * sentinel ()
Protected Attributes
Object * object_
Detailed Description
template<class T>
class Core::TsRef< T >
Class template for smart pointers using intrusive reference-counting in a multithreaded environment.
For more important comments
See also
Core::Ref
Definition at line 98 of file ThreadSafeReference.hh.
Constructor & Destructor Documentation
template<class T> Core::TsRef< T >::TsRef (const TsRef< T > & r) inline
Copy Constructor for the Type Ref<T>
Warning
: Implementaion of this constructor is necesseary although the template copy constructor implements exactly the same. If this constructor is not implemented, the compiler creates a default copy constructor instead of using the template one.
Definition at line 158 of file ThreadSafeReference.hh.
template<class T> template<class S > Core::TsRef< T >::TsRef (const TsRef< S > & r) inline
Template Copy Constuctor Using templates solves the problem of casting ...
-to const pointer -to precursor class pointer. For all classes S which are not derived from T, this constructor will not compile.
Definition at line 169 of file ThreadSafeReference.hh.
Member Function Documentation
template<class T> Object* Core::TsRef< T >::_get () const inline
Copies the value of the pointer.
Warning
Do not use this function. It is only used in the template copy contructor and the template operator= functions.
Definition at line 240 of file ThreadSafeReference.hh.
Referenced by Core::TsRef< Flow::DataAdaptor< Speech::Alignment > >::operator!=(), Core::TsRef< Flow::DataAdaptor< Speech::Alignment > >::operator==(), and Core::TsRef< Flow::DataAdaptor< Speech::Alignment > >::TsRef().
template<class T> Object* Core::TsRef< T >::get () const inline
Explicit conversion to normal pointer.
Warning
This defeats the reference counting mechanism. Use with caution!
Definition at line 233 of file ThreadSafeReference.hh.
Referenced by Speech::StatePosteriorFeatureScorerNode::work().
template<class T> Core::TsRef< T >::operator bool () const inline
Test for non-voidness.
Definition at line 212 of file ThreadSafeReference.hh.
template<class T> bool Core::TsRef< T >::operator! () const inline
Test for voidness.
Definition at line 216 of file ThreadSafeReference.hh.
template<class T> bool Core::TsRef< T >::operator!= (const TsRef< T > & r) const inline
Test for non-identity.
Definition at line 203 of file ThreadSafeReference.hh.
template<class T> bool Core::TsRef< T >::operator== (const TsRef< T > & r) const inline
Test for identity.
Definition at line 195 of file ThreadSafeReference.hh.
template<class T> void Core::TsRef< T >::reset () inline
Reset to void.
Corresponds to assigning zero to normal pointer.
Definition at line 190 of file ThreadSafeReference.hh.
Referenced by Flow::AbstractNode::getData(), Speech::Feature::take(), and Speech::AlignmentNode::work().
template<class T> void Core::TsRef< T >::set (Object * o) inline protected
Takes over the value of.
Parameters
o. -Handles self assignment, i.e. if
o == object_. -
See also
the function 'tsRef' about how to create a TsRef object conveniently from a pointer.
Definition at line 132 of file ThreadSafeReference.hh.
The documentation for this class was generated from the following file:
ThreadSafeReference.hh