Sprint: Core::XmlElement Class Reference
Core::XmlElement Class Reference abstract
Abstract XML element declaration for use with XmlSchemaParser.
#include <XmlParser.hh>
Public Types
typedef XmlElement * pointer
Public Types inherited from Core::XmlContext
typedef XmlContext Self
typedef void(Self::* StartHandler) (const XmlAttributes atts)
typedef void(Self::* EndHandler) ()
typedef void(Self::* CharactersHandler) (const char *ch, int len)
Public Member Functions
XmlElement (const char *_name, XmlContext *_context)
const char * name () const
XmlContext * context () const
virtual XmlSchemaParser * parser ()
virtual bool matches (const char *_name) const
virtual void start (const XmlAttributes atts)
Handle start of the current XML element.
virtual void end ()
Handle end of the current XML element.
virtual void characters (const char *ch, int len)=0
Handle charcter data in the current XML element.
virtual XmlElement * element (const char *name)=0
Determine the state to be entered for a nested XML element.
Static Public Attributes
static const char * wildcard = " * "
Protected Member Functions
XmlElement * collect (XmlElement *child)
Collects child elements.
Private Attributes
XmlContext * context_
const char * name_
XmlElementGarbageCollector garbageCollector_
Additional Inherited Members
Static Public Member Functions inherited from Core::XmlContext
template<class T >
static StartHandler startHandler (void(T::*h)(const XmlAttributes atts))
template<class T >
static EndHandler endHandler (void(T::*h)())
template<class T >
static CharactersHandler charactersHandler (void(T::*h)(const char *ch, int len))
Detailed Description
Abstract XML element declaration for use with XmlSchemaParser.
Instances of (decendants of) XmlElement determine the behaviour of an XmlSchemaParser (State pattern). In consequence they can be seen as content models for the various elements of an XML applications. XmlElement serves as an abstract base class for various content models.
When a state is entered start() is called with the attributes of the XML start tag which caused the parser to enter this state. When the corresponding end tag is found, end() is called. In between character data and nested XML elements may occur. These will cause calls to characters() and element() respectively. element() must return the state to be entered for the the respective element.
See also
XmlSchemaParser
Definition at line 270 of file XmlParser.hh.
Member Function Documentation
virtual void Core::XmlElement::characters (const char * ch, int len) pure virtual
Handle charcter data in the current XML element.
Parameters
parser The XmlSchemaParser delegating the request.
Implemented in Cart::XmlTrainingPlanBuilderElement, Cart::XmlStepBuilderElement, Cart::XmlExampleListMergerElement, Cart::XmlExampleListBuilderElement, Cart::XmlFloatBoxBuilderElement, Core::XmlRegularElement, Cart::XmlPropertiesBuilderElement, Core::XmlMixedElementRelay, Core::XmlDocumentElement, Cart::XmlDecisionTreeBuilderElement, Core::XmlFlattenElement, Core::XmlIgnoreElement, Cart::XmlBinaryTreeRootBuilderElement, Core::XmlEmptyElement, Cart::XmlTrainingInformationBuilderElement, Flf::Semiring::XmlElement, Cart::XmlQuestionRefListBuilderElement, Core::XmlDataOnlyBuilderElement< P, C >, Core::XmlDataOnlyBuilderElement< P, ChoiceConversion< P > >, XmlBuilder2::XmlChoiceBuilderElement, XmlBuilder2::XmlDataOnlyBuilderElement< std::string, StringConversion< std::string > >, Cart::XmlPropertiesDefinitionBuilderElement, XmlBuilder2::XmlDataOnlyBuilderElement< T, Converter >, and Cart::XmlIndexedStringBuilderElement.
XmlElement* Core::XmlElement::collect (XmlElement * child) inline protected
Collects child elements.
Call this function with the newly created child elements in order to collect and destroy them if they are not needed anymore.
Definition at line 286 of file XmlParser.hh.
virtual XmlElement* Core::XmlElement::element (const char * name) pure virtual
Determine the state to be entered for a nested XML element.
Parameters
name of the XML element encountered
Returns
XmlElement to handle the encountered element, or 0 if the element should not be allowed.
Parameters
parser The XmlSchemaParser delegating the request.
Implemented in Core::XmlRegularElement, Core::XmlMixedElement, Core::XmlDocumentElement, Core::XmlFlattenElement, Core::XmlIgnoreElement, and Core::XmlEmptyElement.
Referenced by Core::XmlFlattenElement::element(), and Core::XmlRegularElementRelay::end().
virtual void Core::XmlElement::end () inline virtual
Handle end of the current XML element.
end() is called when end tag of the current element is found.
Parameters
parser The XmlSchemaParser delegating the request.
Reimplemented in Cart::XmlTrainingPlanBuilderElement, Cart::XmlStepBuilderElement, Cart::XmlExampleListMergerElement, Cart::XmlExampleListBuilderElement, Core::XmlRegularElementRelay, Cart::XmlFloatBoxBuilderElement, Core::XmlRegularElement, Cart::XmlPropertiesBuilderElement, Core::XmlMixedElementRelay, Core::XmlDocumentElement, Cart::XmlDecisionTreeBuilderElement, Core::XmlFlattenElementRelay, Core::XmlFlattenElement, Core::XmlIgnoreElement, Cart::XmlBinaryTreeRootBuilderElement, Core::XmlEmptyElement, Cart::XmlTrainingInformationBuilderElement, Flf::Semiring::XmlElement, Cart::XmlQuestionRefListBuilderElement, Core::XmlDataOnlyBuilderElement< P, C >, Core::XmlDataOnlyBuilderElement< P, ChoiceConversion< P > >, XmlBuilder2::XmlChoiceBuilderElement, XmlBuilder2::XmlDataOnlyBuilderElement< std::string, StringConversion< std::string > >, XmlBuilder2::XmlDataOnlyBuilderElement< T, Converter >, Cart::XmlPropertiesDefinitionBuilderElement, and Cart::XmlIndexedStringBuilderElement.
Definition at line 324 of file XmlParser.hh.
virtual void Core::XmlElement::start (const XmlAttributes atts) inline virtual
Handle start of the current XML element.
start() is called when the current state is entered.
Parameters
atts attributes of the XML start tag which caused the parser to enter this state. The name of the element will generally be implied by the fact that THIS state is entered.
Reimplemented in Cart::XmlTrainingPlanBuilderElement, Cart::XmlStepBuilderElement, Cart::XmlExampleListMergerElement, Cart::XmlExampleListBuilderElement, Core::XmlRegularElementRelay, Cart::XmlFloatBoxBuilderElement, Core::XmlRegularElement, Cart::XmlPropertiesBuilderElement, Core::XmlMixedElementRelay, Core::XmlDocumentElement, Cart::XmlDecisionTreeBuilderElement, Core::XmlFlattenElementRelay, Core::XmlFlattenElement, Core::XmlIgnoreElement, Cart::XmlBinaryTreeRootBuilderElement, Core::XmlEmptyElementRelay, Cart::XmlTrainingInformationBuilderElement, Cart::XmlQuestionRefListBuilderElement, Core::XmlDataOnlyBuilderElement< P, C >, Core::XmlDataOnlyBuilderElement< P, ChoiceConversion< P > >, Cart::XmlPropertiesDefinitionBuilderElement, and Cart::XmlIndexedStringBuilderElement.
Definition at line 316 of file XmlParser.hh.
Referenced by Cart::XmlIndexedStringBuilderElement::start(), Cart::XmlPropertiesDefinitionBuilderElement::start(), Cart::XmlQuestionRefListBuilderElement::start(), Cart::XmlTrainingInformationBuilderElement::start(), Cart::XmlBinaryTreeRootBuilderElement::start(), Cart::XmlDecisionTreeBuilderElement::start(), Cart::XmlPropertiesBuilderElement::start(), Cart::XmlFloatBoxBuilderElement::start(), Cart::XmlExampleListBuilderElement::start(), Cart::XmlExampleListMergerElement::start(), Cart::XmlStepBuilderElement::start(), and Cart::XmlTrainingPlanBuilderElement::start().
The documentation for this class was generated from the following files:
XmlParser.hh
XmlParser.cc