Sprint: Math::GeneralizedEigenvalueProblem Class Reference
Math::GeneralizedEigenvalueProblem Class Reference abstract
Base class for generalized eigenvalue problems.
#include <EigenvalueProblem.hh>
Public Member Functions
GeneralizedEigenvalueProblem (const Core::Configuration &)
virtual bool solveSymmetric (const Matrix< ValueType > &a, Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)
Interface function for symmetric eigenvalue problem.
virtual bool solveSymmetric (const Matrix< ValueType > &a, const Matrix< ValueType > &b, Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)=0
Interface function for generalized symmetric eigenvalue problem.
bool solveSymmetricAndFinalize (const Matrix< ValueType > &a, const Matrix< ValueType > &b, Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)
Solves the symmetric generalized eigenvalue problem and performs finalization of results.
bool finalizeEigenvaluesAndVectors (const Matrix< ValueType > &a, const Matrix< ValueType > &b, Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)
Performs final processing of eigenvalues and eigenvectors.
bool finalize (const Matrix< ValueType > &a, const Matrix< ValueType > &b, Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)
Performs final processing and verifications.
bool isCorrectSolution (const Matrix< ValueType > &a, const Matrix< ValueType > &b, const Vector< ValueType > &eigenvalues, const Matrix< ValueType > &eigenvectors)
Verifies if eigenvectors and eigenvalues satisfy A*X = Lambda*B*X.
Public Member Functions inherited from Math::EigenvalueProblem
EigenvalueProblem (const Core::Configuration &)
bool solveSymmetricAndFinalize (const Matrix< ValueType > &a, Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)
Solves the symmetric eigenvalue problem and performs finalization of results.
bool finalize (const Matrix< ValueType > &a, Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)
Performs final processing and verifications.
bool finalizeEigenvaluesAndVectors (const Matrix< ValueType > &a, Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)
Performs final processing of eigenvalues and eigenvectors.
bool isCorrectSolution (const Matrix< ValueType > &a, const Vector< ValueType > &eigenvalues, const Matrix< ValueType > &eigenvectors)
Verifies if eigenvectors and eigenvalues satisfy A*X = Lambda*B*X.
void sortEigenvalues (Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)
Sorts eigenvalues in descending order.
bool real (const Vector< std::complex< ValueType >> &, Vector< ValueType > &)
Extracts real part of the input vector.
bool real (const Matrix< std::complex< ValueType >> &, Matrix< ValueType > &)
Extracts real part of the input matrix.
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Private Attributes
bool normalizeEigenvectorsUsingB_
Static Private Attributes
static const Core::ParameterBool paramNormalizeEigenvectorsUsingB
Additional Inherited Members
Public Types inherited from Math::EigenvalueProblem
enum Type { typeGeneral, typeSymmetric, typeSymmetricPositiveDefinite }
typedef f64 ValueType
Static Public Attributes inherited from Math::EigenvalueProblem
static const Core::Choice choiceType
static const Core::ParameterChoice paramType
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Math::EigenvalueProblem
bool areEqual (const Matrix< ValueType > &x, const Matrix< ValueType > &y)
bool normalizeDiagonal (const Matrix< ValueType > &a, Matrix< ValueType > &eigenvectors)
Eigenvectors are scaled so that eigenvector^T * A * eigenvector = I.
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Base class for generalized eigenvalue problems.
Definition at line 157 of file EigenvalueProblem.hh.
Member Function Documentation
bool GeneralizedEigenvalueProblem::finalize (const Matrix< ValueType > & a, const Matrix< ValueType > & b, Vector< ValueType > & eigenvalues, Matrix< ValueType > & eigenvectors)
Performs final processing and verifications.
1) Performs final processing of eigenvalues and eigenvectors. 2) Verifies solution.
Definition at line 266 of file EigenvalueProblem.cc.
References Core::Component::error().
bool GeneralizedEigenvalueProblem::finalizeEigenvaluesAndVectors (const Matrix< ValueType > & a, const Matrix< ValueType > & b, Vector< ValueType > & eigenvalues, Matrix< ValueType > & eigenvectors)
Performs final processing of eigenvalues and eigenvectors.
1) Normalizes eigenvectors (configurable) 2) Sorts eigenvalues
Definition at line 279 of file EigenvalueProblem.cc.
bool GeneralizedEigenvalueProblem::isCorrectSolution (const Matrix< ValueType > & a, const Matrix< ValueType > & b, const Vector< ValueType > & eigenvalues, const Matrix< ValueType > & eigenvectors)
Verifies if eigenvectors and eigenvalues satisfy A*X = Lambda*B*X.
Definition at line 289 of file EigenvalueProblem.cc.
References Core::Component::error().
virtual bool Math::GeneralizedEigenvalueProblem::solveSymmetric (const Matrix< ValueType > & a, Vector< ValueType > & eigenvalues, Matrix< ValueType > & eigenvectors) inline virtual
Interface function for symmetric eigenvalue problem.
Implements Math::EigenvalueProblem.
Definition at line 167 of file EigenvalueProblem.hh.
References Math::EigenvalueProblem::finalize(), Math::EigenvalueProblem::finalizeEigenvaluesAndVectors(), Math::EigenvalueProblem::isCorrectSolution(), Math::EigenvalueProblem::solveSymmetric(), and Math::EigenvalueProblem::solveSymmetricAndFinalize().
virtual bool Math::GeneralizedEigenvalueProblem::solveSymmetric (const Matrix< ValueType > & a, const Matrix< ValueType > & b, Vector< ValueType > & eigenvalues, Matrix< ValueType > & eigenvectors) pure virtual
Interface function for generalized symmetric eigenvalue problem.
Implemented in Math::Lapack::GenSymmetricDefiniteEigenProblem, and Math::Lapack::GenEigenProblemWithSchurDecomposition.
bool GeneralizedEigenvalueProblem::solveSymmetricAndFinalize (const Matrix< ValueType > & a, const Matrix< ValueType > & b, Vector< ValueType > & eigenvalues, Matrix< ValueType > & eigenvectors)
Solves the symmetric generalized eigenvalue problem and performs finalization of results.
If
Returns
is false, depending on the type of error, results can be stored in eigenvalues and eigenvectors
Definition at line 254 of file EigenvalueProblem.cc.
The documentation for this class was generated from the following files:
EigenvalueProblem.hh
EigenvalueProblem.cc