Sprint: Lattice::Core::Component Class Reference
Lattice::Core::Component Class Reference
Base class for configurable components with logging and error logging facilities.
#include <WeightedAccumulator.hh>
Classes
class Message
Helper class for generating error messages.
Public Member Functions
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Lattice::Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Protected Types
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Private Types
enum ErrorAction { ErrorActionIgnore, ErrorActionDelayedExit, ErrorActionImmediateExit }
typedef Configurable Precursor
Private Member Functions
void initialize ()
Performs initilization common in the different constructors.
XmlChannel * errorChannel (ErrorType mt) const
Get a channel for a warning/error message.
void errorOccured (ErrorType) const
void exit () const
Abort program execution.
Private Attributes
ErrorAction errorActions_ [nErrorTypes]
int errorCounts_ [nErrorTypes]
XmlChannel * errorChannels_ [nErrorTypes]
Static Private Attributes
static const Choice errorActionChoice
static const char * errorNames [nErrorTypes]
static const char * errorChannelNames [nErrorTypes]
static const Channel::Default errorChannelDefaults [nErrorTypes]
Friends
class Component::Message
Additional Inherited Members
Protected Attributes inherited from Lattice::Core::Configurable
Configuration config
Detailed Description
Base class for configurable components with logging and error logging facilities.
The error model supposes that there are three types of errors:
warnings: Things which are possibly wrong, but may well be correct.
errors: Things are most certainly wrong, but we can try to continue.
critical errors: Things are most definitelly wrong and there is no way to continue.
Remember that this is for runtime errors only. Logical program errors should be handled by Assertions.
For all types of errors a message is output on the corresponding channel. The default behaviour is to
continue after warnings (ignore)
immediatelly abort execution on errors (immediate-exit) -> andras used to mix up critical-errors and errors
immediatelly abort execution on ciritcal errors (immediate-exit)
This behaviour can be changed using the configuration options
on-warning
on-error
on-critical-error
Component predefines four channels:
log
warning
error
critical
Messages are formatted to an indented XML text. Each call to one of the message functions (log, warning, error, criticalError) creates an XML with the full name of the component and the system error ID. The message functions return a Message object which can be used for streaming complex information into the body of the message tag. The Xml... (XmlOpen, XmlClose, XmlEmpty, XmlComment) objects can be useful for creating a structured message bodies.
Definition at line 70 of file WeightedAccumulator.hh.
Member Function Documentation
Message Lattice::Core::Component::criticalError (const char * msg = 0, ...) const
Print a critical error message.
Call criticalError() when an error occurs and there is no way to continue in a meaningful way. The default behaviour is to abort execution immediatelly. You should assume, that criticalError() does not return, although the user can overide this behaviour.
Parameters
msg a printf-like format string
Returns
The stream output operator may be applied to the return value. Message should not include formatting characters ("\n" etc.). A line break is appended automatically.
See also
warning()
Message Lattice::Core::Component::error (const char * msg = 0, ...) const
Print an error message.
Call error() whenever an error occurs in the current component. The default behaviour is to continue until respondToDelayedErrors() is called. Clients can check if an error occurred by calling hasFatalErrors().
Parameters
msg a printf-like format string
Returns
The stream output operator may be applied to the return value. Message should not include formatting characters ("\n" etc.). A line break is appended automatically.
See also
warning()
respondToDelayedErrors()
XmlChannel* Lattice::Core::Component::errorChannel (ErrorType mt) const private
Get a channel for a warning/error message.
If necessary the requested channel is created first. All channels will be deleted by the destrutor.
Parameters
mt type of the channel
Returns
pointer to the channel to be used for messages of the given type.
void Lattice::Core::Component::exit () const private
Abort program execution.
exit() will print a message and call Application::exit() to terminate the programm. The exit status of the program can be configured by the "error-code" parameter.
bool Lattice::Core::Component::hasFatalErrors () const
Test whether non-ignored errors have occured.
See also
error()
Referenced by Speech::LatticeSetReader::initialize(), Speech::LatticeSetWriter::initialize(), and Speech::LatticeWriteNode::LatticeWriteNode().
void Lattice::Core::Component::initialize () private
Performs initilization common in the different constructors.
Message Lattice::Core::Component::log (const char * msg, ...) const
Print an information message.
Use this for all information you what to give the use on what your are currently doing. If anything abnormal occurs use waring() or error() instead.
Parameters
msg a printf-like format string
Returns
The stream output operator may be applied to the return value. A line break is appended automatically.
See also
warning(), error(), criticalError()
Referenced by Lattice::NBestListExtractor::getNBestListWithoutWordBoundaries().
void Lattice::Core::Component::respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
More specifically, terminate iff hasFatalErrors() returns true.
See also
error()
virtual XmlChannel* Lattice::Core::Component::vErrorMessage (ErrorType mt, const char * msg, va_list) const protected virtual
Output a warning/error message on the appropriate channel.
Parameters
mt type of the message
msg a printf-like format string
Returns
the channel the message was written to.
Message Lattice::Core::Component::warning (const char * msg = 0, ...) const
Print a warning message.
Parameters
msg a printf-like format string
Returns
The stream output operator may be applied to the return value. Message should not include formatting characters ("\n" etc.). A line break is appended automatically. Example: warning("mismatch ") << a << "!=" << b;
Referenced by Lattice::CheckPosteriorDfsState::finish().
The documentation for this class was generated from the following file:
WeightedAccumulator.hh