Sprint: Math::FastMatrix< T > Class Template Reference
Math::FastMatrix< T > Class Template Reference
Public Types
typedef T value_type
typedef T * iterator
typedef const T * const_iterator
Public Member Functions
s32 getNumberOfThreads ()
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
FastMatrix (u32 nRows=0, u32 nColumns=0)
FastMatrix (const FastMatrix< T > &X)
FastMatrix (const FastMatrix< T > &X, u32 rowIndexX, u32 colIndexX, u32 thisRowIndex, u32 thisColIndex, u32 nRows, u32 nCols)
T & operator() (u32 row, u32 column)
T const & operator() (u32 row, u32 column) const
void clear ()
void swap (FastMatrix< T > &X)
void setNumberOfThreads (int nThreads)
FastMatrix< T > & operator= (FastMatrix< T > X)
void resize (u32 nRows, u32 nColumns, bool minimalSize=false)
void resizeRowsAndKeepContent (u32 nRows)
void resizeColsAndKeepContent (u32 nColumns, bool minimalSize=false, bool efficientSize=true)
void removeColumn (u32 column)
template<typename S >
void copyStructure (const FastMatrix< S > &X)
u32 nRows () const
template<typename S >
void copy (const FastMatrix< S > &X)
template<typename S >
void copy (const S *X, u32 rowOffset=0, u32 colOffset=0)
template<typename S >
void copy (const Matrix< S > &matrix)
template<typename S >
void copy (const std::vector< S > &X, u32 rowOffset=0, u32 colOffset=0)
void copySelectedRowsOfMatrixIntoColumns (const FastMatrix< T > &matrix, const FastMatrix< T > &x)
template<typename S >
void convert (Matrix< S > &matrix) const
u32 nColumns () const
bool empty () const
bool isFinite () const
u32 size () const
void fill (T value)
void ensureMinimalValue (const T threshold)
T & at (u32 i, u32 j)
const T & at (u32 i, u32 j) const
void write (Core::BinaryOutputStream &o) const
void read (Core::BinaryInputStream &i)
void print (std::ostream &os) const
void printToFile (const std::string &filename) const
void show () const
void getRow (u32 rowIndex, Math::FastVector< T > &row) const
void getColumn (u32 columnIndex, Math::FastVector< T > &column) const
void copyBlockFromMatrix (const Math::FastMatrix< T > &X, u32 rowIndexX, u32 colIndexX, u32 thisRowIndex, u32 thisColIndex, u32 nRows, u32 nCols=1)
void setToZero ()
template<typename S >
void add (const FastMatrix< S > &X, S alpha=1.0)
T l1norm () const
T sumOfSquares () const
T dot (const FastMatrix< T > &X) const
void scale (T alpha)
void multiply (const FastVector< T > &x, FastVector< T > &y, bool transposed=false, T alpha=1.0, T beta=0.0, u32 lda=0) const
void addOuterProduct (const FastVector< T > &x, const FastVector< T > &y, T alpha, u32 lda=0)
template<typename S >
void addMatrixProduct (const FastMatrix< S > &matrixA, const FastMatrix< S > &matrixB, T scaleC=0, S scaleA=1, bool transposeA=false, bool transposeB=false)
template<typename S >
void gemm (bool transposedA, bool transposedB, int M, int N, int K, S scaleA, const S *matrixA, int lda, const S *matrixB, int ldb, T scaleC, T *matrixC, int ldc)
void sigmoid (T gamma=1.0)
void logSigmoid (T gamma=1.0)
void softmax ()
template<typename S >
void maxoutvar (const FastVector< S > &mixture, const FastVector< S > &offset, const FastMatrix< T > &input, FastMatrix< S > &maxIndexOutputMatrix)
template<typename S >
void maxoutErrorExpand (const FastVector< S > &mixture, const FastVector< S > &offset, const FastMatrix< S > &maxIndex, const FastMatrix< T > &input)
void elementwiseMultiplicationWithSigmoidDerivative (const FastMatrix< T > &X)
void elementwiseMultiplicationWithTanhDerivative (const FastMatrix< T > &X)
void multiplicationWithSoftmaxDerivative (const FastMatrix< T > &softmax)
void elementwiseMultiplicationWithRectifiedDerivative (const FastMatrix< T > &X)
template<typename S >
void addKroneckerDelta (const FastVector< S > &alignment, const T scale=1.0)
template<typename S , typename U >
void addKroneckerDelta (const FastVector< S > &alignment, const FastVector< U > &offset, const FastMatrix< U > &maxIndex, const T scale=1.0)
template<typename S >
u32 nClassificationErrors (const FastVector< S > &alignment)
template<typename S >
T crossEntropyObjectiveFunction (const FastVector< S > &alignment)
template<typename S >
T weightedCrossEntropyObjectiveFunction (const FastVector< S > &alignment, const FastVector< T > &weights)
template<typename S >
T squaredErrorObjectiveFunction (const FastVector< S > &alignment)
template<typename S >
T weightedSquaredErrorObjectiveFunction (const FastVector< S > &alignment, const FastVector< T > &weights)
template<typename S >
T binaryDivergenceObjectiveFunction (const FastVector< S > &alignment)
template<typename S >
T weightedBinaryDivergenceObjectiveFunction (const FastVector< S > &alignment, const FastVector< T > &weights)
template<typename S >
void binaryDivergenceSoftmaxGradient (const FastMatrix< T > &Y, const FastVector< S > &A)
T dotWithColumn (const FastMatrix< T > &X, u32 thisColumnIndex) const
void setToSecondOrderFeatures (const FastMatrix< T > &X)
void setToThirdOrderFeatures (const FastMatrix< T > &X)
void dropout (const T dropoutProbability)
void addGaussianNoise (const T standardDeviation)
void l1clipping (const T value)
void clip (const T maxAbsValue)
void tanh ()
void exp ()
void log ()
void pow (T exp)
u32 argAbsMax (u32 column) const
u32 argMax (u32 column) const
void elementwiseMultiplication (const FastMatrix< T > &X)
void elementwiseDivision (const FastMatrix< T > &X)
void addConstantElementwise (T c)
void addToAllColumns (const FastVector< T > &v, T alpha=1.0)
void addToAllColumnsWithOffset (const FastVector< T > &v, u32 offset, T alpha=1.0)
template<typename S >
void expandAddToAllColumns (const FastVector< S > &mixture, const FastVector< S > &offset, const FastVector< T > &v, T alpha)
void addToAllRows (const FastVector< T > &v, T alpha=1.0)
void addWithColumnWeights (const FastMatrix< T > &X, const FastVector< T > &v)
void multiplyColumnsByScalars (const FastVector< T > &scalars)
void divideColumnsByScalars (const FastVector< T > &scalars)
void multiplyRowsByScalars (const FastVector< T > &scalars)
void divideRowsByScalars (const FastVector< T > &scalars)
void addPoolingMax (const FastMatrix< T > &input, FastMatrix< u32 > &argmax, u32 poolingSize, bool poolingAbs)
void addPoolingPnorm (const FastMatrix< T > &input, u32 poolingSize, u32 pnorm)
void convExtractPatches (const FastMatrix< T > &input, const FastMatrix< s32 > &patchIdx, FastMatrix< s32 > &inverse_patches)
void convUnwarpFrames (const FastMatrix< T > &output_warped, const FastVector< T > &bias, u32 shifts_num)
void elu (T)
void elementwiseMultiplicationWithEluDerivative (const FastMatrix< T > &X)
Static Protected Member Functions
static s32 initialize ()
Protected Attributes
u32 nRows_
u32 nColumns_
T * elem_
u32 capacity_
s32 nThreads_
Static Protected Attributes
static bool initialized = false
static s32 maxThreads = 1
Private Member Functions
bool allocate (bool minimalSize=false)
Allocate the memory for the matrix.
void appendSecondOrderFeatures (const FastMatrix< T > &X, u32 offset)
void appendThirdOrderFeatures (const FastMatrix< T > &X, u32 offset)
template<>
void _gemm (bool transposedA, bool transposedB, int M, int N, int K, float scaleA, const float *matrixA, int lda, const float *matrixB, int ldb, double scaleC, double *matrixC, int ldc)
Static Private Member Functions
template<typename S >
static void _gemm (bool transposedA, bool transposedB, int M, int N, int K, S scaleA, const S *matrixA, int lda, const S *matrixB, int ldb, T scaleC, T *matrixC, int ldc)
Friends
class FastMatrix< f64 >
class FastMatrix< f32 >
class FastMatrix< s64 >
class FastMatrix< u64 >
class FastMatrix< s32 >
class FastMatrix< u32 >
class FastMatrix< s16 >
class FastMatrix< u16 >
class FastMatrix< s8 >
class FastMatrix< u8 >
Detailed Description
template<typename T>
class Math::FastMatrix< T >
Definition at line 53 of file FastMatrix.hh.
Member Function Documentation
template<typename T > bool Math::FastMatrix< T >::allocate (bool minimalSize = false) private
Allocate the memory for the matrix.
Allocate the memory for the matrix. If the size is 0 the pointer is ZERO.
Definition at line 529 of file FastMatrix.hh.
References Math::copy(), Core::Component::criticalError(), Math::dot(), Math::iamax(), Math::isnan(), Math::mt_scal(), Math::scal(), Math::FastVector< T >::setToZero(), Core::Application::us(), verify, and Core::Component::warning().
The documentation for this class was generated from the following file:
FastMatrix.hh