Sprint: Fsa::Alphabet::const_iterator Class Reference
Fsa::Alphabet::const_iterator Class Reference
Iterator that should be used to traverse an alphabet.
#include <Alphabet.hh>
Public Member Functions
const_iterator (Core::Ref< const Alphabet > a, LabelId i)
const_iterator & operator++ ()
bool operator== (const const_iterator &i) const
bool operator!= (const const_iterator &i) const
std::string operator* ()
Retrieve the string representation of the current symbol.
operator LabelId ()
Retrieve the label id of the current symbol.
operator LabelId () const
Protected Attributes
Core::Ref< const Alphabet > alphabet_
LabelId label_
Detailed Description
Iterator that should be used to traverse an alphabet.
If you derive from Alphabet to create your own implementation of an on-demand alphabet you should NOT modify this iterator. Instead overload appropriate virtual methods at your Alphabet class. You should not assume any ordering on the label ids or strings you get.
Definition at line 52 of file Alphabet.hh.
Member Function Documentation
Fsa::Alphabet::const_iterator::operator LabelId () inline
Retrieve the label id of the current symbol.
Definition at line 82 of file Alphabet.hh.
References Fsa::Alphabet::index(), Fsa::Alphabet::specialIndex(), Fsa::Alphabet::specialSymbol(), and Fsa::Alphabet::symbol().
std::string Fsa::Alphabet::const_iterator::operator* () inline
Retrieve the string representation of the current symbol.
Definition at line 75 of file Alphabet.hh.
The documentation for this class was generated from the following file:
Alphabet.hh