Sprint: Mm::AbstractMixtureSet Class Reference
Mm::AbstractMixtureSet Class Reference
AbstractMixtureSet administrates mixture objects and their relations.
#include <MixtureSet.hh>
Public Member Functions
AbstractMixtureSet (ComponentIndex dimension=0)
AbstractMixtureSet.
virtual void clear ()
ComponentIndex dimension () const
virtual void setOffset (ComponentIndex offset)
virtual void setDimension (ComponentIndex dimension)
MixtureIndex addMixture (MixtureIndex index, Mixture *mixture)
MixtureIndex addMixture (Mixture *mixture)
MixtureIndex nMixtures () const
Mixture * mixture (MixtureIndex index)
const Mixture * mixture (MixtureIndex index) const
DensityIndex addDensity (DensityIndex index, AbstractDensity *density)
DensityIndex addDensity (AbstractDensity *density)
DensityIndex nDensities () const
virtual AbstractDensity * density (DensityIndex index)
virtual const AbstractDensity * density (DensityIndex index) const
virtual bool write (Core::BinaryOutputStream &o) const
print/scan methods for std::iostreams used in operator<< resp.
virtual bool read (Core::BinaryInputStream &i)
virtual bool write (std::ostream &o) const
virtual bool read (std::istream &i)
virtual void removeDensitiesWithLowWeight (Weight minWeight, bool normalizeWeights=true)
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Protected Attributes
PointerVector< Mixture > mixtureTable_
PointerVector< AbstractDensity > densityTable_
ComponentIndex dimension_
Detailed Description
AbstractMixtureSet administrates mixture objects and their relations.
Data structure: -objects pointers are stored in tables; -objects points reference others by integer indexes. Advantage of pointer representation: -object types can be extended be deriving from the base types and without changing (much :-)) in other parts of this library Advantages to graph representation: -direct access to set of elements (e.g.: list of all covariances) -storing and load is straight forward Disadvantages: -hard to remove elements from the structure -since the tables contain pointers, each access needs +1 indirection. Thus this representation is not suitable for fast computations.
Definition at line 47 of file MixtureSet.hh.
Constructor & Destructor Documentation
AbstractMixtureSet::AbstractMixtureSet (ComponentIndex dimension = 0)
AbstractMixtureSet.
Definition at line 26 of file MixtureSet.cc.
References verify.
Member Function Documentation
virtual bool Mm::AbstractMixtureSet::write (Core::BinaryOutputStream & o) const inline virtual
print/scan methods for std::iostreams used in operator<< resp.
operator>> overwrite these methodes in inherited classes
Reimplemented in Mm::MixtureSet.
Definition at line 102 of file MixtureSet.hh.
References Core::Component::error(), Core::Application::us(), and write().
Referenced by write().
The documentation for this class was generated from the following files:
MixtureSet.hh
MixtureSet.cc