Sprint: Core::Description Class Reference
Core::Description Class Reference
Vector of stream descriptions Stream descriptions if a set of attributes describing a (feature) stream.
#include <Description.hh>
Classes
class Stream
Public Member Functions
Description (const std::string &name)
Constructor.
Stream & operator[] (size_t index)
const Stream & operator[] (size_t index) const
Core::Description::Stream & mainStream ()
const Core::Description::Stream & mainStream () const
void clear ()
size_t nStreams () const
bool verifyNumberOfStreams (size_t expectedNumber, bool critical=false) const
Compares the number of streams with.
void getDependencies (DependencySet &) const
bool operator== (const Description &d) const
bool operator!= (const Description &d) const
Static Public Member Functions
static std::string prepareName (const std::string &parent, const std::string &name)
Protected Member Functions
Stream & getStream (size_t index)
Protected Attributes
std::string name_
std::vector< Stream > streams_
Detailed Description
Vector of stream descriptions Stream descriptions if a set of attributes describing a (feature) stream.
For example: type, dimension, etc.
Definition at line 27 of file Description.hh.
Constructor & Destructor Documentation
Core::Description::Description (const std::string & name) inline
Constructor.
Since this object might be created frequently, it does not derive from Component. Error messages are passed to the Application object. name is used to identify this object.
Definition at line 96 of file Description.hh.
References require, and verifyNumberOfStreams().
Member Function Documentation
bool Description::verifyNumberOfStreams (size_t expectedNumber, bool critical = false) const
Compares the number of streams with.
Parameters
expectedNumber. If
critical is true and comparison fails, execution is aborted
Definition at line 53 of file Description.cc.
References Core::DependencySet::add(), Core::Component::error(), Core::form(), Core::Component::respondToDelayedErrors(), and Core::Application::us().
Referenced by Description(), Speech::CovarianceEstimator::setFeatureDescription(), Speech::TextDependentScatterMatricesEstimator::setFeatureDescription(), Speech::MeanEstimator::setFeatureDescription(), Speech::TextIndependentScatterMatricesEstimator::setFeatureDescription(), and Speech::FeatureVectorExtractor::setFeatureDescription().
The documentation for this class was generated from the following files:
Description.hh
Description.cc