Sprint: Speech::MinimumErrorSegmentwiseGmmTrainer Class Reference
Speech::MinimumErrorSegmentwiseGmmTrainer Class Reference
Public Member Functions
MinimumErrorSegmentwiseGmmTrainer (const Core::Configuration &)
virtual void processWordLattice (Lattice::ConstWordLatticeRef, Bliss::SpeechSegment *)
Override this function to implement the processing of lattice sets.
Public Member Functions inherited from Speech::SegmentwiseGmmTrainer
SegmentwiseGmmTrainer (const Core::Configuration &)
SegmentwiseGmmTrainer: base class.
virtual void leaveCorpus (Bliss::Corpus *)
Override this function to perform post processing after the last segment of the corpus.
virtual void write () const
Public Member Functions inherited from Speech::AcousticSegmentwiseTrainer< GmmAccumulator >
AcousticSegmentwiseTrainer (const Core::Configuration &c)
Public Member Functions inherited from Speech::AbstractAcousticSegmentwiseTrainer
AbstractAcousticSegmentwiseTrainer (const Core::Configuration &)
virtual void setSegmentwiseFeatureExtractor (Core::Ref< Speech::SegmentwiseFeatureExtractor >)
virtual void setAlignmentGenerator (Core::Ref< Speech::PhonemeSequenceAlignmentGenerator >)
Public Member Functions inherited from Speech::AbstractSegmentwiseTrainer
s32 posteriorTolerance () const
AbstractSegmentwiseTrainer (const Core::Configuration &)
virtual void initialize (Bliss::LexiconRef)
Override this function to achieve the lexicon of the input lattice set.
Public Member Functions inherited from Speech::LatticeSetProcessor
LatticeSetProcessor (const Core::Configuration &)
LatticeSetProcessor.
void setProcessor (Core::Ref< LatticeSetProcessor > processor)
This lattice set processor is used for cascading.
virtual void signOn (CorpusVisitor &corpusVisitor)
Override this function to sign on to services of the corpus visitor.
virtual void enterCorpus (Bliss::Corpus *corpus)
Override this function to perform pre processing before the first segment of the corpus.
virtual void enterRecording (Bliss::Recording *recording)
Override this function to perform pre processing before the first segment of the recording.
virtual void leaveRecording (Bliss::Recording *recording)
Override this function to perform post processing after the last segment of the recording.
virtual void enterSegment (Bliss::Segment *s)
Override this function to perform preparations before first aligned features arrive.
virtual void leaveSegment (Bliss::Segment *s)
Override this function to perform post processing after the last aligned features of the segment.
virtual void enterSpeechSegment (Bliss::SpeechSegment *s)
Override this function to perform preparations before first features arrive.
virtual void leaveSpeechSegment (Bliss::SpeechSegment *s)
Override this function to perform post processing after the last features of the segment.
virtual void getWordLatticeDescription (Lattice::WordLatticeDescription &)
Override this function to create the description of the output word lattices.
virtual void setWordLatticeDescription (const Lattice::WordLatticeDescription &)
Override this function to achieve the attributes of the input lattice set.
virtual std::string name () const
virtual void logComputationTime () const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Private Types
typedef SegmentwiseGmmTrainer Precursor
Additional Inherited Members
Public Types inherited from Speech::AbstractAcousticSegmentwiseTrainer
enum ModelType { gaussianMixture, maximumEntropy, neuralNetwork, neuralNetworkTheano }
Public Types inherited from Speech::AbstractSegmentwiseTrainer
enum Criterion {
maximumMutualInformation, weightedMaximumMutualInformation, minimumClassificationError, minimumError,
gisMinimumError, logMinimumError, contextPrior, contextAccuracy,
weightedMinimumError, legacyMinimumErrorWithISmoothing, minimumErrorWithISmoothing, logMinimumErrorWithISmoothing,
weightedMinimumErrorWithISmoothing, corrective, minimumLeastSquaredError, plain
}
Static Public Member Functions inherited from Speech::SegmentwiseGmmTrainer
static SegmentwiseGmmTrainer * createSegmentwiseGmmTrainer (const Core::Configuration &)
factory
Static Public Member Functions inherited from Speech::AbstractAcousticSegmentwiseTrainer
static AbstractAcousticSegmentwiseTrainer * createAbstractAcousticSegmentwiseTrainer (const Core::Configuration &)
Static Public Attributes inherited from Speech::AbstractAcousticSegmentwiseTrainer
static Core::Choice choiceModelType
factory
static Core::ParameterChoice paramModelType
Static Public Attributes inherited from Speech::AbstractSegmentwiseTrainer
static Core::Choice choiceCriterion
factory
static Core::ParameterChoice paramCriterion
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Speech::SegmentwiseGmmTrainer
virtual void setFeatureDescription (const Mm::FeatureDescription &)
virtual GmmAccumulator * createAcc ()
virtual GmmAccumulator * createNumAcc ()
virtual GmmAccumulator * createDenAcc ()
virtual GmmAccumulator * createMleAcc ()
void accumulateObjectiveFunction (f32)
void initializeMixtureSetTrainer ()
Protected Member Functions inherited from Speech::AcousticSegmentwiseTrainer< GmmAccumulator >
void resetAcc ()
const GmmAccumulator * acc ()
void accumulateNumerator (Fsa::ConstAutomatonRef fsa, Core::Ref< const Lattice::WordBoundaries > wb)
void accumulateDenominator (Fsa::ConstAutomatonRef fsa, Core::Ref< const Lattice::WordBoundaries > wb)
void accumulateMle (Fsa::ConstAutomatonRef fsa, Core::Ref< const Lattice::WordBoundaries > wb)
Protected Member Functions inherited from Speech::AbstractAcousticSegmentwiseTrainer
Core::Ref< SegmentwiseFeatureExtractor > segmentwiseFeatureExtractor () const
Core::Ref< PhonemeSequenceAlignmentGenerator > alignmentGenerator () const
Core::Ref< Am::AcousticModel > acousticModel () const
Flow::PortId portId () const
Flow::PortId sparsePortId () const
Flow::PortId accumulationPortId () const
Flow::PortId accumulationSparsePortId () const
ConstSegmentwiseFeaturesRef features (Flow::PortId portId, Flow::PortId sparsePortId) const
ConstSegmentwiseFeaturesRef features () const
ConstSegmentwiseFeaturesRef accumulationFeatures () const
Protected Member Functions inherited from Speech::AbstractSegmentwiseTrainer
Lattice::ConstWordLatticeRef extractNumerator (const std::string &orth, Lattice::ConstWordLatticeRef denominator) const
Mm::Weight weightThreshold () const
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Speech::SegmentwiseGmmTrainer
bool initialized_
DiscriminativeMixtureSetTrainer * mixtureSetTrainer_
Protected Attributes inherited from Speech::AbstractAcousticSegmentwiseTrainer
Core::Ref< SegmentwiseFeatureExtractor > segmentwiseFeatureExtractor_
Core::Ref< PhonemeSequenceAlignmentGenerator > alignmentGenerator_
Protected Attributes inherited from Speech::AbstractSegmentwiseTrainer
Bliss::OrthographicParser * orthToLemma_
Fsa::ConstAutomatonRef lemmaPronToLemma_
Fsa::ConstAutomatonRef lemmaToLemmaConfusion_
std::string part_
Protected Attributes inherited from Speech::LatticeSetProcessor
f64 timeProcessSegment_
Core::Ref< LatticeSetProcessor > processor_
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Definition at line 75 of file SegmentwiseGmmTrainer.hh.
Member Function Documentation
void MinimumErrorSegmentwiseGmmTrainer::processWordLattice (Lattice::ConstWordLatticeRef lattice, Bliss::SpeechSegment * s) virtual
Override this function to implement the processing of lattice sets.
accumulation of the covariance Cov(A, gradient(log(P)))
Reimplemented from Speech::AbstractAcousticSegmentwiseTrainer.
Definition at line 141 of file SegmentwiseGmmTrainer.cc.
References Lattice::WordLattice::accuracyFsa, Core::Component::criticalError(), Fsa::multiply(), and Speech::AbstractAcousticSegmentwiseTrainer::processWordLattice().
The documentation for this class was generated from the following files:
SegmentwiseGmmTrainer.hh
SegmentwiseGmmTrainer.cc