Sprint: Translation::ConditionalLexiconPlain Class Reference
Translation::ConditionalLexiconPlain Class Reference
Public Member Functions
ConditionalLexiconPlain (const Core::Configuration &config)
ConditionalLexiconPlain (const Core::Configuration &config, Fsa::ConstAlphabetRef alphabet)
virtual Translation::Cost getProb (const size_t index, const std::vector< std::string > &key) const
this is deprecated and should just exist as long as i am migrating to the new lexicon
virtual Translation::Cost getCost (const size_t index, const std::vector< Fsa::LabelId > &key) const
virtual Translation::Cost getReverseCost (const size_t index, const std::vector< Fsa::LabelId > &key) const
virtual Translation::Cost getProb (const size_t index, const std::vector< Fsa::LabelId > &key) const
get probability of a lexicon entry or floor if it does not exist
virtual void addValue (const size_t index, const std::vector< Fsa::LabelId > &key, Translation::Cost value)
add value to existing count/prob or create new if it does not exist
virtual void addValue (const size_t index, const std::vector< std::string > &key, Translation::Cost value)
add value to existing count/prob or create new if it does not exist
virtual void setValue (const size_t index, const std::vector< Fsa::LabelId > &key, Translation::Cost value)
set value of the given entry (overwrite if it exists, create if it doesnt)
virtual void setValue (const size_t index, const std::vector< std::string > &key, Translation::Cost value)
set value of the given entry (overwrite if it exists, create if it doesnt)
virtual void write (std::ostream &out)
write lexicon to stream
virtual void normalize (int normalizePoint)
normalize
virtual void read (std::istream &)
read a lexicon from a file stream
virtual void read ()
read a lexicon from a file stream
Public Member Functions inherited from Translation::ConditionalLexicon
ConditionalLexicon (const Core::Configuration &config)
ConditionalLexicon (const Core::Configuration &config, Fsa::ConstAlphabetRef alphabet)
ConstAlphabetRef getTokenAlphabet () const
return ConstAlphabetRef of the internal token alphabet for matching against other alphabets
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Private Types
typedef Translation::SimplePrefixTree< Fsa::LabelId, Translation::Cost > Lexicon
typedef Core::Ref< Lexicon > LexiconRef
Private Attributes
std::vector< LexiconRef > lexica_
holds lexica for the different types of transitions (if neccessary)
const std::string lexiconFilename_
filename as a string. read from the corresponding parameter
Translation::Cost floor_
floor probability for values that are not in the lexicon
Static Private Attributes
static Core::ParameterString paramFilename_
parameter giving the filename to read from
static Core::ParameterFloat paramFloor_
floor value for this lexicon
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Translation::ConditionalLexicon
Fsa::StaticAlphabet * tokens_
tokens (no distinctions between source or target)
Fsa::ConstAlphabetRef tokenRef_
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Definition at line 31 of file ConditionalLexiconPlain.hh.
Member Function Documentation
virtual void Translation::ConditionalLexiconPlain::addValue (const size_t index, const std::vector< Fsa::LabelId > & key, Translation::Cost value) inline virtual
add value to existing count/prob or create new if it does not exist
Implements Translation::ConditionalLexicon.
Definition at line 126 of file ConditionalLexiconPlain.hh.
References lexica_.
Referenced by addValue().
virtual void Translation::ConditionalLexiconPlain::addValue (const size_t index, const std::vector< std::string > & key, Translation::Cost value) inline virtual
add value to existing count/prob or create new if it does not exist
Implements Translation::ConditionalLexicon.
Definition at line 162 of file ConditionalLexiconPlain.hh.
References Fsa::StaticAlphabet::addSymbol(), addValue(), and Translation::ConditionalLexicon::tokens_.
virtual Translation::Cost Translation::ConditionalLexiconPlain::getProb (const size_t index, const std::vector< std::string > & key) const inline virtual
this is deprecated and should just exist as long as i am migrating to the new lexicon
Implements Translation::ConditionalLexicon.
Definition at line 59 of file ConditionalLexiconPlain.hh.
References floor_, Fsa::StaticAlphabet::index(), lexica_, and Translation::ConditionalLexicon::tokens_.
virtual Translation::Cost Translation::ConditionalLexiconPlain::getProb (const size_t index, const std::vector< Fsa::LabelId > & key) const inline virtual
get probability of a lexicon entry or floor if it does not exist
Implements Translation::ConditionalLexicon.
Definition at line 122 of file ConditionalLexiconPlain.hh.
virtual void Translation::ConditionalLexiconPlain::normalize (int normalizePoint) inline virtual
normalize
Implements Translation::ConditionalLexicon.
Definition at line 196 of file ConditionalLexiconPlain.hh.
References lexica_, and Core::Component::log().
void Translation::ConditionalLexiconPlain::read (std::istream & is) virtual
read a lexicon from a file stream
Implements Translation::ConditionalLexicon.
Definition at line 32 of file ConditionalLexiconPlain.cc.
References Fsa::StaticAlphabet::addSymbol(), lexica_, Core::split(), Core::strconv(), and Translation::ConditionalLexicon::tokens_.
void Translation::ConditionalLexiconPlain::read () virtual
read a lexicon from a file stream
Implements Translation::ConditionalLexicon.
Definition at line 25 of file ConditionalLexiconPlain.cc.
References lexiconFilename_.
virtual void Translation::ConditionalLexiconPlain::setValue (const size_t index, const std::vector< Fsa::LabelId > & key, Translation::Cost value) inline virtual
set value of the given entry (overwrite if it exists, create if it doesnt)
Implements Translation::ConditionalLexicon.
Definition at line 171 of file ConditionalLexiconPlain.hh.
References lexica_.
virtual void Translation::ConditionalLexiconPlain::setValue (const size_t index, const std::vector< std::string > & key, Translation::Cost value) inline virtual
set value of the given entry (overwrite if it exists, create if it doesnt)
Implements Translation::ConditionalLexicon.
Definition at line 176 of file ConditionalLexiconPlain.hh.
virtual void Translation::ConditionalLexiconPlain::write (std::ostream & out) inline virtual
write lexicon to stream
Implements Translation::ConditionalLexicon.
Definition at line 179 of file ConditionalLexiconPlain.hh.
References lexica_, Fsa::StaticAlphabet::symbol(), and Translation::ConditionalLexicon::tokens_.
Member Data Documentation
Translation::Cost Translation::ConditionalLexiconPlain::floor_ private
floor probability for values that are not in the lexicon
Definition at line 233 of file ConditionalLexiconPlain.hh.
Referenced by getProb().
std::vector<LexiconRef> Translation::ConditionalLexiconPlain::lexica_ private
holds lexica for the different types of transitions (if neccessary)
Definition at line 221 of file ConditionalLexiconPlain.hh.
Referenced by addValue(), getProb(), normalize(), read(), setValue(), and write().
const std::string Translation::ConditionalLexiconPlain::lexiconFilename_ private
filename as a string. read from the corresponding parameter
Definition at line 227 of file ConditionalLexiconPlain.hh.
Referenced by read().
Core::ParameterString Translation::ConditionalLexiconPlain::paramFilename_ static private
parameter giving the filename to read from
Definition at line 224 of file ConditionalLexiconPlain.hh.
Core::ParameterFloat Translation::ConditionalLexiconPlain::paramFloor_ static private
floor value for this lexicon
Definition at line 230 of file ConditionalLexiconPlain.hh.
The documentation for this class was generated from the following files:
ConditionalLexiconPlain.hh
ConditionalLexiconPlain.cc