Sprint: Core::PriorityQueueBase< T_Heap, T_PriorityFunction > Class Template Reference
Core::PriorityQueueBase< T_Heap, T_PriorityFunction > Class Template Reference
Public Types
typedef T_PriorityFunction PriorityFunction
typedef Precursor::Item Item
typedef Precursor::Index Index
Public Member Functions
PriorityQueueBase (u32 maxSize=Type< u32 >::max)
PriorityQueueBase (const PriorityFunction &precedes, u32 maxSize=Type< u32 >::max)
const Item & top () const
Return reference to top-most item in the queue.
void pop ()
Remove top-most item.
void changeTop (const Item &e)
Change top-most item.
void insert (const Item &e)
Insert new item.
Protected Member Functions
void upHeap (Index)
void downHeap (Index)
bool invariant () const
Protected Attributes
u32 maxSize_
PriorityFunction precedes_
Private Types
typedef T_Heap Precursor
Detailed Description
template<class T_Heap, class T_PriorityFunction>
class Core::PriorityQueueBase< T_Heap, T_PriorityFunction >
Definition at line 26 of file PriorityQueue.hh.
Member Function Documentation
template<class T_Heap, class T_PriorityFunction> void Core::PriorityQueueBase< T_Heap, T_PriorityFunction >::changeTop (const Item & e) inline
Change top-most item.
Equivalent to pop(); insert(), but usually more efficient.
Definition at line 67 of file PriorityQueue.hh.
template<class T_Heap, class T_PriorityFunction> void Core::PriorityQueueBase< T_Heap, T_PriorityFunction >::insert (const Item & e) inline
Insert new item.
Definition at line 74 of file PriorityQueue.hh.
Referenced by Flf::applyEpsClosureFilter(), Flf::FittingLattice::Boundaries::get(), Core::TracedPriorityQueue< T_Item, T_Key, T_KeyFunction, T_PriorityFunction, T_Hash_Obj >::insertOrRelax(), and Cart::Training::suggestSplit().
template<class T_Heap, class T_PriorityFunction> void Core::PriorityQueueBase< T_Heap, T_PriorityFunction >::pop () inline
Remove top-most item.
Definition at line 54 of file PriorityQueue.hh.
Referenced by Flf::applyEpsClosureFilter(), Flf::FittingLattice::Boundaries::get(), Cart::Training::halfSplit(), and Cart::Training::split().
template<class T_Heap, class T_PriorityFunction> const Item& Core::PriorityQueueBase< T_Heap, T_PriorityFunction >::top () const inline
Return reference to top-most item in the queue.
Definition at line 48 of file PriorityQueue.hh.
Referenced by Flf::applyEpsClosureFilter(), Flf::FittingLattice::Boundaries::get(), Cart::Training::halfSplit(), and Cart::Training::split().
The documentation for this class was generated from the following file:
PriorityQueue.hh