Sprint: Flf::EditDistance Class Reference
Flf::EditDistance Class Reference
Public Types
typedef u16 Cost
Public Member Functions
EditDistance (Fsa::ConstAlphabetRef alphabet, const Bliss::TokenAlphabet *toks)
Fsa::ConstAlphabetRef alphabet () const
Cost operator() (Fsa::LabelId label1, Fsa::LabelId label2) const
Edit distance.
Score cost (Fsa::LabelId label1, Fsa::LabelId label2) const
Edit distance.
Score normCost (Fsa::LabelId label1, Fsa::LabelId label2) const
Normalized edit distance.
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Static Public Member Functions
static ConstEditDistanceRef create (Lexicon::AlphabetId alphabetId)
Private Attributes
Fsa::ConstAlphabetRef alphabet_
const Bliss::TokenAlphabet * toks_
Cost * D_
Cost lengthD_
Detailed Description
Definition at line 258 of file Flf/Lexicon.hh.
Member Function Documentation
Score Flf::EditDistance::cost (Fsa::LabelId label1, Fsa::LabelId label2) const
Edit distance.
Definition at line 851 of file Flf/Lexicon.cc.
Score Flf::EditDistance::normCost (Fsa::LabelId label1, Fsa::LabelId label2) const
Normalized edit distance.
Definition at line 855 of file Flf/Lexicon.cc.
References Core::Component::criticalError(), Bliss::Token::symbol(), Core::Application::us(), and verify.
EditDistance::Cost Flf::EditDistance::operator() (Fsa::LabelId label1, Fsa::LabelId label2) const
Edit distance.
Definition at line 814 of file Flf/Lexicon.cc.
References Bliss::Symbol::str(), Bliss::Token::symbol(), and verify.
The documentation for this class was generated from the following files:
Flf/Lexicon.hh
Flf/Lexicon.cc