Sprint: Nn::SegmentwiseNnTrainer< T > Class Template Reference
Nn::SegmentwiseNnTrainer< T > Class Template Reference abstract
SegmentwiseNnTrainer.
#include <SegmentwiseNnTrainer.hh>
Public Member Functions
SegmentwiseNnTrainer (const Core::Configuration &config)
virtual void processWordLattice (Lattice::ConstWordLatticeRef l, Bliss::SpeechSegment *s)
Override this function to implement the processing of lattice sets.
virtual void setFeatureDescription (const Mm::FeatureDescription &)
virtual void leaveCorpus (Bliss::Corpus *corpus)
Override this function to perform post processing after the last segment of the corpus.
Public Member Functions inherited from Nn::NeuralNetworkTrainer< f32 >
NeuralNetworkTrainer (const Core::Configuration &config)
virtual void initializeTrainer (u32 batchSize)
virtual void initializeTrainer (u32 batchSize, std::vector< u32 > &streamSizes)
NnMatrix & getOutputActivation ()
get activations of output layer
bool hasNetwork () const
returns whether trainer has a network
bool hasEstimator () const
returns whether trainer has an estimator
bool weightedAccumulation () const
returns whether frame weights are used
u32 batchSize () const
returns current batch size (equal to size of activations)
bool isInitialized () const
returns whether trainer is initialized
bool measuresTime () const
returns whether trainer measures computation time
Criterion< f32 > & criterion ()
NeuralNetwork< f32 > & network ()
return reference to network
const NeuralNetwork< f32 > & network () const
u32 nLayers () const
return reference to network
Estimator< f32 > & estimator ()
return reference to estimator
const Estimator< f32 > & estimator () const
Regularizer< f32 > & regularizer ()
return reference to regularizer
const Regularizer< f32 > & regularizer () const
void setClassWeights (const Math::Vector< f32 > *vector)
sets class weights to values in vector
virtual bool needsToProcessAllFeatures () const
returns whether trainer needs to process all features, i.e.
virtual void setBatchSize (u32 batchSize)
resize activations (necessary when batch size has changed)
virtual bool isNetworkOutputRepresentingClassLabels ()
if we have a network, is its output layer representing the class label posterior probabilities
virtual bool hasClassLabelPosteriors ()
whether we can call getClassLabelPosteriors()
virtual NnMatrix & getClassLabelPosteriors ()
returns the posteriors after a call to processBatch_feedInput()
virtual int getClassLabelPosteriorDimension ()
returns posterior dimension
virtual bool allowsDownsampling () const
virtual void processBatch_feedInput (std::vector< NnMatrix > &features, NnVector *weights, Bliss::Segment *segment)
Override this method for the NN forward pass in NN training.
virtual void processBatch_finishWithError (f32error, NnMatrix &errorSignal)
Override this method for supervised training.
virtual void processBatch_finishWithError_naturalPairing (f32error, NnMatrix &errorSignal)
This is a special variant of processBatch_finishWithError(), where the error signal is already related to the natural pairing of the objective function with the last layer activation function.
virtual void processBatch_finishWithAlignment (Math::CudaVector< u32 > &alignment)
Override this method for supervised training with a criterion based on an alignment.
virtual void processBatch_finishWithSpeechSegment (Bliss::SpeechSegment &segment)
Override this method for supervised training with a criterion based on a segment.
virtual void processBatch_finish ()
Override this method for unsupervised training to finish a minibatch.
virtual void resetHistory ()
virtual void logBatchTimes () const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Speech::AbstractAcousticSegmentwiseTrainer
AbstractAcousticSegmentwiseTrainer (const Core::Configuration &)
virtual void setSegmentwiseFeatureExtractor (Core::Ref< Speech::SegmentwiseFeatureExtractor >)
virtual void setAlignmentGenerator (Core::Ref< Speech::PhonemeSequenceAlignmentGenerator >)
Public Member Functions inherited from Speech::AbstractSegmentwiseTrainer
s32 posteriorTolerance () const
AbstractSegmentwiseTrainer (const Core::Configuration &)
virtual void initialize (Bliss::LexiconRef)
Override this function to achieve the lexicon of the input lattice set.
Public Member Functions inherited from Speech::LatticeSetProcessor
LatticeSetProcessor (const Core::Configuration &)
LatticeSetProcessor.
void setProcessor (Core::Ref< LatticeSetProcessor > processor)
This lattice set processor is used for cascading.
virtual void signOn (CorpusVisitor &corpusVisitor)
Override this function to sign on to services of the corpus visitor.
virtual void enterCorpus (Bliss::Corpus *corpus)
Override this function to perform pre processing before the first segment of the corpus.
virtual void enterRecording (Bliss::Recording *recording)
Override this function to perform pre processing before the first segment of the recording.
virtual void leaveRecording (Bliss::Recording *recording)
Override this function to perform post processing after the last segment of the recording.
virtual void enterSegment (Bliss::Segment *s)
Override this function to perform preparations before first aligned features arrive.
virtual void leaveSegment (Bliss::Segment *s)
Override this function to perform post processing after the last aligned features of the segment.
virtual void enterSpeechSegment (Bliss::SpeechSegment *s)
Override this function to perform preparations before first features arrive.
virtual void leaveSpeechSegment (Bliss::SpeechSegment *s)
Override this function to perform post processing after the last features of the segment.
virtual void getWordLatticeDescription (Lattice::WordLatticeDescription &)
Override this function to create the description of the output word lattices.
virtual void setWordLatticeDescription (const Lattice::WordLatticeDescription &)
Override this function to achieve the attributes of the input lattice set.
virtual void logComputationTime () const
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Static Public Member Functions
static SegmentwiseNnTrainer * createSegmentwiseNnTrainer (const Core::Configuration &)
factory
Static Public Member Functions inherited from Nn::NeuralNetworkTrainer< f32 >
static NeuralNetworkTrainer< f32 > * createSupervisedTrainer (const Core::Configuration &config)
static NeuralNetworkTrainer< f32 > * createUnsupervisedTrainer (const Core::Configuration &config)
Static Public Member Functions inherited from Speech::AbstractAcousticSegmentwiseTrainer
static AbstractAcousticSegmentwiseTrainer * createAbstractAcousticSegmentwiseTrainer (const Core::Configuration &)
Protected Member Functions
virtual void initializeTrainer ()
virtual bool isInitialized () const
virtual void finalize ()
virtual void initSegment (Lattice::ConstWordLatticeRef lattice, Bliss::SpeechSegment *segment)
virtual bool computeInitialErrorSignal (Lattice::ConstWordLatticeRef lattice, Lattice::ConstWordLatticeRef numeratorLattice, Bliss::SpeechSegment *segment, T &objectiveFunction, bool objectiveFunctionOnly)=0
virtual void accumulateStatisticsOnLattice (Fsa::ConstAutomatonRef posterior, Core::Ref< const Lattice::WordBoundaries > wb, Mm::Weight factor)
virtual NnAccumulator * createAccumulator (Mm::Weight factor, Mm::Weight weightThreshold) const
virtual void logProperties () const
virtual void logSegmentStatistics () const
virtual void logTrainingStatistics () const
virtual void logProfilingStatistics () const
NeuralNetwork< f32 > & network () const
const ClassLabelWrapper & labelWrapper () const
virtual std::string name () const
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Member Functions inherited from Speech::AbstractAcousticSegmentwiseTrainer
Core::Ref< SegmentwiseFeatureExtractor > segmentwiseFeatureExtractor () const
Core::Ref< PhonemeSequenceAlignmentGenerator > alignmentGenerator () const
Core::Ref< Am::AcousticModel > acousticModel () const
Flow::PortId portId () const
Flow::PortId sparsePortId () const
Flow::PortId accumulationPortId () const
Flow::PortId accumulationSparsePortId () const
ConstSegmentwiseFeaturesRef features (Flow::PortId portId, Flow::PortId sparsePortId) const
ConstSegmentwiseFeaturesRef features () const
ConstSegmentwiseFeaturesRef accumulationFeatures () const
Protected Member Functions inherited from Speech::AbstractSegmentwiseTrainer
Lattice::ConstWordLatticeRef extractNumerator (const std::string &orth, Lattice::ConstWordLatticeRef denominator) const
Mm::Weight weightThreshold () const
Protected Attributes
const std::string statisticsFilename_
const f32 ceSmoothingWeight_
const f32 frameRejectionThreshold_
const bool accumulatePrior_
bool singlePrecision_
Statistics< T > * statistics_
Statistics< f32 > * priorStatistics_
u32 numberOfProcessedSegments_
u32 numberOfObservations_
u32 numberOfRejectedObservations_
T ceObjectiveFunction_
T localObjectiveFunction_
T localCeObjectiveFunction_
u32 localClassificationErrors_
std::vector< NnMatrixf32 > errorSignal_
ErrorSignalAccumulator< f32 > * accumulator_
bool segmentNeedsInit_
Math::CudaVector< u32 > alignment_
NnVectorf32 weights_
u32 sequenceLength_
Math::Vector< f32 > classWeights_
LinearAndSoftmaxLayer< f32 > * topLayer_
MaxoutVarLayer< f32 > * maxoutLayer_
NnVectorf32 prior_
f32 priorScale_
Mm::FeatureDescription featureDescription_
bool featureDescriptionNeedInit_
bool enableFeatureDescriptionCheck_
Protected Attributes inherited from Nn::NeuralNetworkTrainer< f32 >
Criterion< f32 > * criterion_
bool weightedAccumulation_
const Math::Vector< f32 > * classWeights_
const bool measureTime_
bool needsNetwork_
Core::XmlChannel statisticsChannel_
bool needInit_
NeuralNetwork< f32 > * network_
Estimator< f32 > * estimator_
Regularizer< f32 > * regularizer_
Protected Attributes inherited from Core::Configurable
Configuration config
Protected Attributes inherited from Speech::AbstractAcousticSegmentwiseTrainer
Core::Ref< SegmentwiseFeatureExtractor > segmentwiseFeatureExtractor_
Core::Ref< PhonemeSequenceAlignmentGenerator > alignmentGenerator_
Protected Attributes inherited from Speech::AbstractSegmentwiseTrainer
Bliss::OrthographicParser * orthToLemma_
Fsa::ConstAutomatonRef lemmaPronToLemma_
Fsa::ConstAutomatonRef lemmaToLemmaConfusion_
std::string part_
Protected Attributes inherited from Speech::LatticeSetProcessor
f64 timeProcessSegment_
Core::Ref< LatticeSetProcessor > processor_
Static Protected Attributes
static const Core::ParameterString paramStatisticsFilename
static const Core::ParameterFloat paramSilenceWeight
static const Core::ParameterString paramClassWeightsFile
static const Core::ParameterFloat paramCeSmoothingWeight
static const Core::ParameterFloat paramFrameRejectionThreshold
static const Core::ParameterBool paramAccumulatePrior
static const Core::ParameterBool paramEnableFeatureDescriptionCheck
Private Types
typedef Speech::AbstractAcousticSegmentwiseTrainer SpeechPrecursor
typedef Types< f32 >::NnVector NnVectorf32
typedef Types< f32 >::NnMatrix NnMatrixf32
typedef Types< f64 >::NnVector NnVectorf64
typedef Types< f64 >::NnMatrix NnMatrixf64
Private Member Functions
void setPrecision ()
void setClassWeights ()
bool getAlignmentVector (Lattice::ConstWordLatticeRef numeratorLattice)
void accumulatePrior ()
void accumulateBaseStatistics ()
void backpropagateError ()
T smoothErrorSignalWithCE ()
void collectGradient ()
void resizeErrorSignal ()
void updateModel ()
template<>
void setPrecision ()
template<>
void setPrecision ()
template<>
void updateModel ()
template<>
void updateModel ()
Private Attributes
f64 timeMemoryAllocation_
f64 timeNumeratorExtraction_
f64 timeAlignmentVector_
f64 timeErrorSignal_
f64 timeCESmoothing_
f64 timeBackpropagation_
f64 timeGradient_
f64 timeBaseStatistics_
f64 timeEstimationStep
f64 timeSync_
Additional Inherited Members
Public Types inherited from Nn::NeuralNetworkTrainer< f32 >
enum TrainerType
Public Types inherited from Speech::AbstractAcousticSegmentwiseTrainer
enum ModelType { gaussianMixture, maximumEntropy, neuralNetwork, neuralNetworkTheano }
Public Types inherited from Speech::AbstractSegmentwiseTrainer
enum Criterion {
maximumMutualInformation, weightedMaximumMutualInformation, minimumClassificationError, minimumError,
gisMinimumError, logMinimumError, contextPrior, contextAccuracy,
weightedMinimumError, legacyMinimumErrorWithISmoothing, minimumErrorWithISmoothing, logMinimumErrorWithISmoothing,
weightedMinimumErrorWithISmoothing, corrective, minimumLeastSquaredError, plain
}
Static Public Attributes inherited from Nn::NeuralNetworkTrainer< f32 >
static const Core::Choice choiceNetworkTrainer
static const Core::ParameterChoice paramNetworkTrainer
static const Core::ParameterInt paramEpoch
static const Core::ParameterBool paramWeightedAccumulation
static const Core::ParameterBool paramMeasureTime
Static Public Attributes inherited from Speech::AbstractAcousticSegmentwiseTrainer
static Core::Choice choiceModelType
factory
static Core::ParameterChoice paramModelType
Static Public Attributes inherited from Speech::AbstractSegmentwiseTrainer
static Core::Choice choiceCriterion
factory
static Core::ParameterChoice paramCriterion
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Detailed Description
template<typename T>
class Nn::SegmentwiseNnTrainer< T >
SegmentwiseNnTrainer.
performs sequence-discriminative training in lattice-based framework In order to implement a specific criterion, derive from SegmentwiseNnTrainer and implement computeInitialErrorSignal.
Definition at line 63 of file SegmentwiseNnTrainer.hh.
Member Function Documentation
template<typename T > SegmentwiseNnTrainer< T > * Nn::SegmentwiseNnTrainer< T >::createSegmentwiseNnTrainer (const Core::Configuration & config) static
factory
Definition at line 754 of file SegmentwiseNnTrainer.cc.
References defect.
Referenced by Speech::AbstractAcousticSegmentwiseTrainer::processWordLattice().
template<typename T > void Nn::SegmentwiseNnTrainer< T >::leaveCorpus (Bliss::Corpus * corpus) virtual
Override this function to perform post processing after the last segment of the corpus.
Reimplemented from Speech::LatticeSetProcessor.
Definition at line 278 of file SegmentwiseNnTrainer.cc.
References Core::Component::error(), Nn::Statistics< T >::initialize(), Core::Component::log(), require, Lattice::WordLattice::totalFsa, verify, and Core::Component::warning().
template<typename T > void Nn::SegmentwiseNnTrainer< T >::processWordLattice (Lattice::ConstWordLatticeRef lattice, Bliss::SpeechSegment * s) virtual
Override this function to implement the processing of lattice sets.
Reimplemented from Speech::AbstractAcousticSegmentwiseTrainer.
Definition at line 121 of file SegmentwiseNnTrainer.cc.
References Core::Component::criticalError(), Core::Component::error(), Core::Description::Stream::getValue(), Speech::LatticeSetProcessor::processWordLattice(), and Core::Component::warning().
The documentation for this class was generated from the following files:
SegmentwiseNnTrainer.hh
SegmentwiseNnTrainer.cc