Sprint: Math::FastVector< T > Class Template Reference
Math::FastVector< T > Class Template Reference
Public Types
typedef T value_type
typedef T * iterator
typedef const T * const_iterator
Public Member Functions
FastVector (u32 nRows=0)
FastVector (const FastVector< T > &vector)
Copy constructor.
u32 nRows () const
u32 nColumns () const
u32 size () const
bool empty () const
void resize (u32 newSize, T value=0, bool allocOnly=false)
void clear ()
template<typename S >
void copy (const FastVector< S > &vector)
Copy the vector.
template<typename S >
void copy (const Vector< S > &vector)
template<typename S >
void setAtOffset (const FastVector< S > &x, u32 offset=0, u32 num_elements=0)
template<typename S >
void convert (Math::Vector< S > &vector) const
void copyStructure (const FastVector< T > &vector)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
bool isFinite () const
template<typename S >
void add (const FastVector< S > &vector, S scale=1)
void addConstantElementwise (T c)
void scale (T value)
T sumOfSquares () const
T dot (const FastVector< T > &vector) const
void columnwiseInnerProduct (const FastMatrix< T > &A, const FastMatrix< T > &B)
void elementwiseMultiplication (const FastVector< T > &v)
void elementwiseDivision (const FastVector< T > &v)
void divide (T value)
void setToZero ()
Set all elements to 0.
void fill (T value)
Set all elements to a constant value.
void ensureMinimalValue (const T threshold)
Set all elements to be >= threshold.
FastVector< T > & operator= (FastVector< T > rhs)
T & operator() (u32 index)
T & operator[] (u32 index)
T & operator() (u32 index) const
T & operator[] (u32 index) const
T & at (u32 index)
const T & at (u32 index) const
T asum () const
T l1norm () const
T sum () const
T mean () const
template<typename S >
void addSummedColumns (const FastMatrix< S > &matrix, const S scale=1.0)
void addSquaredSummedColumns (const FastMatrix< T > &matrix, const T scale=1.0)
void addSummedRows (const FastMatrix< T > &matrix, const T scale=1.0)
void getMaxOfColumns (const FastMatrix< T > &X)
void l1clipping (const T value)
void clip (const T maxAbsValue)
T normEuclidean () const
void exp ()
void pow (T p)
void columnEntropy (const FastMatrix< T > &matrix)
void swap (FastVector< T > &vector)
void print (std::ostream &os, char delim= '\n') const
void printToFile (const std::string &filename) const
void write (Core::XmlWriter &os) const
void show () const
template<typename S >
void cast (const Math::Vector< S > &vector)
Protected Attributes
u32 nRows_
T * elem_
Friends
class FastVector< f32 >
class FastVector< f64 >
class FastVector< s32 >
class FastVector< u32 >
class FastVector< s16 >
class FastVector< u16 >
class FastVector< s8 >
class FastVector< u8 >
Detailed Description
template<typename T>
class Math::FastVector< T >
Definition at line 44 of file FastMatrix.hh.
Constructor & Destructor Documentation
template<typename T> Math::FastVector< T >::FastVector (const FastVector< T > & vector)
Copy constructor.
Definition at line 276 of file FastVector.hh.
References Math::FastVector< T >::copy(), Core::Component::criticalError(), and Core::Application::us().
Member Function Documentation
template<typename T > template<typename S > void Math::FastVector< T >::copy (const FastVector< S > & vector)
Copy the vector.
Definition at line 329 of file FastVector.hh.
References Math::dot(), Math::isnan(), and require.
Referenced by Math::FastVector< T >::FastVector().
template<typename T> void Math::FastVector< T >::ensureMinimalValue (const T threshold)
Set all elements to be >= threshold.
Definition at line 440 of file FastVector.hh.
template<typename T> void Math::FastVector< T >::fill (T value)
Set all elements to a constant value.
Set all elements in the vector to a constant value.
Definition at line 431 of file FastVector.hh.
template<typename T > void Math::FastVector< T >::setToZero ()
Set all elements to 0.
Set all elements in the vector to 0.
Definition at line 422 of file FastVector.hh.
Referenced by Math::FastMatrix< T >::allocate().
The documentation for this class was generated from the following files:
FastMatrix.hh
FastVector.hh