Sprint: Nn::MeanAndVarianceTrainer< T > Class Template Reference
Nn::MeanAndVarianceTrainer< T > Class Template Reference
computes mean and variance of input features
#include <NeuralNetworkTrainer.hh>
Public Member Functions
MeanAndVarianceTrainer (const Core::Configuration &config)
virtual void initializeTrainer (u32 batchSize, std::vector< u32 > &streamSizes)
initialization method
virtual void finalize ()
write statistics
virtual void writeMeanAndStandardDeviation (Statistics< T > &statistics)
compute mean and standard deviation and write it to file
virtual void processBatch_feedInput (std::vector< NnMatrix > &features, NnVector *weights, Bliss::Segment *segment)
accumulates mean and variance on mini-batch
virtual bool needsToProcessAllFeatures () const
returns whether trainer needs to process all features, i.e.
Public Member Functions inherited from Nn::NeuralNetworkTrainer< T >
NeuralNetworkTrainer (const Core::Configuration &config)
virtual void initializeTrainer (u32 batchSize)
NnMatrix & getOutputActivation ()
get activations of output layer
bool hasNetwork () const
returns whether trainer has a network
bool hasEstimator () const
returns whether trainer has an estimator
bool weightedAccumulation () const
returns whether frame weights are used
u32 batchSize () const
returns current batch size (equal to size of activations)
bool isInitialized () const
returns whether trainer is initialized
bool measuresTime () const
returns whether trainer measures computation time
Criterion< T > & criterion ()
NeuralNetwork< T > & network ()
return reference to network
const NeuralNetwork< T > & network () const
u32 nLayers () const
return reference to network
Estimator< T > & estimator ()
return reference to estimator
const Estimator< T > & estimator () const
Regularizer< T > & regularizer ()
return reference to regularizer
const Regularizer< T > & regularizer () const
void setClassWeights (const Math::Vector< T > *vector)
sets class weights to values in vector
virtual void setBatchSize (u32 batchSize)
resize activations (necessary when batch size has changed)
virtual bool isNetworkOutputRepresentingClassLabels ()
if we have a network, is its output layer representing the class label posterior probabilities
virtual bool hasClassLabelPosteriors ()
whether we can call getClassLabelPosteriors()
virtual NnMatrix & getClassLabelPosteriors ()
returns the posteriors after a call to processBatch_feedInput()
virtual int getClassLabelPosteriorDimension ()
returns posterior dimension
virtual bool allowsDownsampling () const
virtual void processBatch_finishWithError (T error, NnMatrix &errorSignal)
Override this method for supervised training.
virtual void processBatch_finishWithError_naturalPairing (T error, NnMatrix &errorSignal)
This is a special variant of processBatch_finishWithError(), where the error signal is already related to the natural pairing of the objective function with the last layer activation function.
virtual void processBatch_finishWithAlignment (Math::CudaVector< u32 > &alignment)
Override this method for supervised training with a criterion based on an alignment.
virtual void processBatch_finishWithSpeechSegment (Bliss::SpeechSegment &segment)
Override this method for supervised training with a criterion based on a segment.
virtual void processBatch_finish ()
Override this method for unsupervised training to finish a minibatch.
virtual void resetHistory ()
virtual void logBatchTimes () const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Attributes
static const Core::ParameterString paramMeanFile
static const Core::ParameterString paramStandardDeviationFile
static const Core::ParameterString paramStatisticsFile
Static Public Attributes inherited from Nn::NeuralNetworkTrainer< T >
static const Core::Choice choiceNetworkTrainer
static const Core::ParameterChoice paramNetworkTrainer
static const Core::ParameterInt paramEpoch
static const Core::ParameterBool paramWeightedAccumulation
static const Core::ParameterBool paramMeasureTime
Protected Types
typedef Types< T >::NnVector NnVector
typedef Types< T >::NnMatrix NnMatrix
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Attributes
NnVector * weights_
Statistics< T > * statistics_
Math::Vector< T > mean_
Math::Vector< T > standardDeviation_
NnMatrix tmp_
std::string meanFile_
std::string standardDeviationFile_
std::string statisticsFile_
Protected Attributes inherited from Nn::NeuralNetworkTrainer< T >
Criterion< T > * criterion_
bool weightedAccumulation_
const Math::Vector< T > * classWeights_
const bool measureTime_
bool needsNetwork_
Core::XmlChannel statisticsChannel_
bool needInit_
NeuralNetwork< T > * network_
Estimator< T > * estimator_
Regularizer< T > * regularizer_
Protected Attributes inherited from Core::Configurable
Configuration config
Private Types
typedef NeuralNetworkTrainer< T > Precursor
Private Member Functions
void saveVector (std::string &filename, Math::Vector< T > &vector)
Additional Inherited Members
Public Types inherited from Nn::NeuralNetworkTrainer< T >
enum TrainerType {
dummy, feedForwardTrainer, frameClassificationErrorAccumulator, meanAndVarianceAccumulator,
networkEvaluator, autoencoderTrainer, pythonTrainer, pythonEvaluator
}
Static Public Member Functions inherited from Nn::NeuralNetworkTrainer< T >
static NeuralNetworkTrainer< T > * createSupervisedTrainer (const Core::Configuration &config)
static NeuralNetworkTrainer< T > * createUnsupervisedTrainer (const Core::Configuration &config)
Protected Member Functions inherited from Nn::NeuralNetworkTrainer< T >
virtual void logProperties () const
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Detailed Description
template<class T>
class Nn::MeanAndVarianceTrainer< T >
computes mean and variance of input features
implemented as a NN trainer in order to get GPU support and to reuse the configuration of the network
Definition at line 336 of file NeuralNetworkTrainer.hh.
Member Function Documentation
template<typename T > void MeanAndVarianceTrainer::finalize (void) virtual
write statistics
Reimplemented from Nn::NeuralNetworkTrainer< T >.
Definition at line 441 of file NeuralNetworkTrainer.cc.
template<typename T > void MeanAndVarianceTrainer::initializeTrainer (u32 batchSize, std::vector< u32 > & streamSizes) virtual
initialization method
Reimplemented from Nn::NeuralNetworkTrainer< T >.
Definition at line 424 of file NeuralNetworkTrainer.cc.
References Core::Component::criticalError().
template<class T> virtual bool Nn::MeanAndVarianceTrainer< T >::needsToProcessAllFeatures () const inline virtual
returns whether trainer needs to process all features, i.e.
for batch training
Reimplemented from Nn::NeuralNetworkTrainer< T >.
Definition at line 375 of file NeuralNetworkTrainer.hh.
template<typename T > void MeanAndVarianceTrainer::processBatch_feedInput (std::vector< NnMatrix > & features, NnVector * weights, Bliss::Segment * segment) virtual
accumulates mean and variance on mini-batch
Reimplemented from Nn::NeuralNetworkTrainer< T >.
Definition at line 467 of file NeuralNetworkTrainer.cc.
References Core::Archive::create(), Core::Component::log(), and Core::Component::warning().
template<typename T> void MeanAndVarianceTrainer::writeMeanAndStandardDeviation (Statistics< T > & statistics) virtual
compute mean and standard deviation and write it to file
Definition at line 449 of file NeuralNetworkTrainer.cc.
References Nn::Statistics< T >::finalize(), and Core::Component::log().
Referenced by NnTrainer::main().
The documentation for this class was generated from the following files:
NeuralNetworkTrainer.hh
NeuralNetworkTrainer.cc