Sprint: Signal::TimeWindowBuffer< T > Class Template Reference
Signal::TimeWindowBuffer< T > Class Template Reference
TWindowBuffer is buffer collecting vectors of samples and delivering (overlapping) segments of a given length.
#include <TimeWindowBuffer.hh>
Public Types
enum FlushPolicy { SendRest, PadRest, DiscardRest }
typedef Flow::Time Time
typedef Flow::Vector< T > InputData
typedef Flow::Vector< T > OutputData
Public Member Functions
bool put (const Flow::Vector< T > &in)
adds an input vector
bool get (Flow::Vector< T > &out)
returns one vector of the given length_ and removes shift_ number of elements from the beginning of the buffer
bool flush (Flow::Vector< T > &out)
delivers the rest of the buffer_
virtual void reset ()
Clears the buffer and resets status variables.
void setShift (u32 shift)
set the number of samples removed after each call to get
u32 shift ()
the number of samples removed after each call to get
void setLength (u32 length)
sets the length of output vectors
u32 length () const
length of output vectors
void setSampleRate (Time sampleRate)
Time sampleRate () const
u32 nOutputs ()
number released of outputs
bool flushed ()
void setFlushAll (bool flushAll)
if
bool flushAll () const
void setFlushBeforeGap (bool flushBeforeGap)
bool shallFlushBeforeGap () const
Protected Member Functions
void setNeedInit ()
call to force initialization
virtual void init ()
overload to perform initialization
virtual void transform (Flow::Vector< T > &out)
overload to transform output vectors
Protected Attributes
u32 length_
length_ of output vectors
u32 shift_
number of elements removed from the beginning of the buffer after a call to get
Time bufferStartTime_
Time sampleRate_
bool flushBeforeGap_
std::deque< T > buffer_
u32 nOutputs_
number released of outputs
bool flushed_
true if buffer is flushed
bool flushAll_
if true, segments are delivered shift-by-shift until the buffer is empty if false, segments are delivered until the last segment contains the last sample
bool needInit_
Private Member Functions
void copy (Flow::Vector< T > &out, u32 length)
copies
Detailed Description
template<typename T>
class Signal::TimeWindowBuffer< T >
TWindowBuffer is buffer collecting vectors of samples and delivering (overlapping) segments of a given length.
A slightly modified version of WindowBuffer, with template functionality
Todo:
Code duplication: WindowBuffer should be a template instance: TWindowBuffer<f32>
Definition at line 34 of file TimeWindowBuffer.hh.
Member Function Documentation
template<typename T> void TimeWindowBuffer::copy (Flow::Vector< T > & out, u32 length) private
copies
Parameters
length element form the beginning of the buffer to
out and sets the beginning and end time of
out
Definition at line 71 of file TimeWindowBuffer.cc.
template<typename T> bool TimeWindowBuffer::flush (Flow::Vector< T > & out)
delivers the rest of the buffer_
Returns
is false if the buffer_ is empty
Caution: an assertion fails if the buffer is larger then 2 * max(length_, shift_)
Definition at line 98 of file TimeWindowBuffer.cc.
References verify.
Referenced by Signal::TimeWindowBuffer< Flow::Vector< f32 > >::transform().
template<typename T> bool Signal::TimeWindowBuffer< T >::flushed () inline
Returns
is true if the last output is following
Definition at line 143 of file TimeWindowBuffer.hh.
template<typename T> bool TimeWindowBuffer::get (Flow::Vector< T > & out)
returns one vector of the given length_ and removes shift_ number of elements from the beginning of the buffer
Returns
is false if buffer is smaller then 2 * max(length_, shift_)
Definition at line 82 of file TimeWindowBuffer.cc.
References verify.
template<typename T > void TimeWindowBuffer::init () protected virtual
overload to perform initialization
Reimplemented in Signal::TemporalIntegration.
Definition at line 35 of file TimeWindowBuffer.cc.
References verify.
Referenced by Signal::TimeWindowBuffer< Flow::Vector< f32 > >::setNeedInit().
template<typename T> u32 Signal::TimeWindowBuffer< T >::length () const inline
length of output vectors
Definition at line 126 of file TimeWindowBuffer.hh.
Referenced by Signal::TimeWindowBuffer< Flow::Vector< f32 > >::setLength().
template<typename T> u32 Signal::TimeWindowBuffer< T >::nOutputs () inline
number released of outputs
Definition at line 138 of file TimeWindowBuffer.hh.
template<typename T> bool TimeWindowBuffer::put (const Flow::Vector< T > & in)
adds an input vector
Returns
is false if there is a time gap between the end time of the buffer and start time of in
Definition at line 51 of file TimeWindowBuffer.cc.
References ensure.
Referenced by Signal::TimeWindowBuffer< Flow::Vector< f32 > >::transform().
template<typename T > void TimeWindowBuffer::reset (void) virtual
Clears the buffer and resets status variables.
Definition at line 43 of file TimeWindowBuffer.cc.
Referenced by Signal::TimeWindowBuffer< Flow::Vector< f32 > >::transform().
template<typename T> void Signal::TimeWindowBuffer< T >::setFlushAll (bool flushAll) inline
if
Parameters
flushAll is true, segments are delivered shift-by-shift until the buffer is empty if
flushAll false, segments are delivered until the last segment contains the last sample
Definition at line 152 of file TimeWindowBuffer.hh.
template<typename T> void Signal::TimeWindowBuffer< T >::setLength (u32 length) inline
sets the length of output vectors
Definition at line 122 of file TimeWindowBuffer.hh.
template<typename T> void Signal::TimeWindowBuffer< T >::setNeedInit () inline protected
call to force initialization
Definition at line 75 of file TimeWindowBuffer.hh.
template<typename T> void Signal::TimeWindowBuffer< T >::setShift (u32 shift) inline
set the number of samples removed after each call to get
Definition at line 113 of file TimeWindowBuffer.hh.
template<typename T> u32 Signal::TimeWindowBuffer< T >::shift () inline
the number of samples removed after each call to get
Definition at line 117 of file TimeWindowBuffer.hh.
Referenced by Signal::TimeWindowBuffer< Flow::Vector< f32 > >::setShift().
template<typename T> virtual void Signal::TimeWindowBuffer< T >::transform (Flow::Vector< T > & out) inline protected virtual
overload to transform output vectors
caution: update the start- and end-time of out if the size is changed
Definition at line 86 of file TimeWindowBuffer.hh.
Member Data Documentation
template<typename T> bool Signal::TimeWindowBuffer< T >::flushAll_ protected
if true, segments are delivered shift-by-shift until the buffer is empty if false, segments are delivered until the last segment contains the last sample
Definition at line 62 of file TimeWindowBuffer.hh.
Referenced by Signal::TimeWindowBuffer< Flow::Vector< f32 > >::setFlushAll().
template<typename T> bool Signal::TimeWindowBuffer< T >::flushed_ protected
true if buffer is flushed
Definition at line 58 of file TimeWindowBuffer.hh.
Referenced by Signal::TimeWindowBuffer< Flow::Vector< f32 > >::flushed().
template<typename T> u32 Signal::TimeWindowBuffer< T >::length_ protected
length_ of output vectors
Definition at line 45 of file TimeWindowBuffer.hh.
Referenced by Signal::TimeWindowBuffer< Flow::Vector< f32 > >::length().
template<typename T> u32 Signal::TimeWindowBuffer< T >::nOutputs_ protected
number released of outputs
Definition at line 55 of file TimeWindowBuffer.hh.
Referenced by Signal::TimeWindowBuffer< Flow::Vector< f32 > >::nOutputs().
template<typename T> u32 Signal::TimeWindowBuffer< T >::shift_ protected
number of elements removed from the beginning of the buffer after a call to get
Definition at line 47 of file TimeWindowBuffer.hh.
Referenced by Signal::TimeWindowBuffer< Flow::Vector< f32 > >::shift().
The documentation for this class was generated from the following files:
TimeWindowBuffer.hh
TimeWindowBuffer.cc