Sprint: Speech::MinimumBayesRiskSearchNode Class Reference
Speech::MinimumBayesRiskSearchNode Class Reference
Search the lattice for string with minimal Bayes risk.
#include <MinimumBayesRiskSearch.hh>
Public Member Functions
MinimumBayesRiskSearchNode (const Core::Configuration &config)
Standard constructor generating a configurable node.
virtual ~MinimumBayesRiskSearchNode ()
Virtual destructor.
void initialize (Bliss::LexiconRef lexicon)
Initialization of lexicon and evaluator.
virtual void processWordLattice (Lattice::ConstWordLatticeRef lattice, Bliss::SpeechSegment *segment)
The actual processing of the word lattice where the search will be performed.
Public Member Functions inherited from Speech::LatticeSetProcessor
LatticeSetProcessor (const Core::Configuration &)
LatticeSetProcessor.
void setProcessor (Core::Ref< LatticeSetProcessor > processor)
This lattice set processor is used for cascading.
virtual void signOn (CorpusVisitor &corpusVisitor)
Override this function to sign on to services of the corpus visitor.
virtual void enterCorpus (Bliss::Corpus *corpus)
Override this function to perform pre processing before the first segment of the corpus.
virtual void leaveCorpus (Bliss::Corpus *corpus)
Override this function to perform post processing after the last segment of the corpus.
virtual void enterRecording (Bliss::Recording *recording)
Override this function to perform pre processing before the first segment of the recording.
virtual void leaveRecording (Bliss::Recording *recording)
Override this function to perform post processing after the last segment of the recording.
virtual void enterSegment (Bliss::Segment *s)
Override this function to perform preparations before first aligned features arrive.
virtual void leaveSegment (Bliss::Segment *s)
Override this function to perform post processing after the last aligned features of the segment.
virtual void enterSpeechSegment (Bliss::SpeechSegment *s)
Override this function to perform preparations before first features arrive.
virtual void leaveSpeechSegment (Bliss::SpeechSegment *s)
Override this function to perform post processing after the last features of the segment.
virtual void getWordLatticeDescription (Lattice::WordLatticeDescription &)
Override this function to create the description of the output word lattices.
virtual void setWordLatticeDescription (const Lattice::WordLatticeDescription &)
Override this function to achieve the attributes of the input lattice set.
virtual void setSegmentwiseFeatureExtractor (Core::Ref< SegmentwiseFeatureExtractor >)
virtual void setAlignmentGenerator (Core::Ref< PhonemeSequenceAlignmentGenerator >)
virtual std::string name () const
virtual void logComputationTime () const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Private Types
enum SearchMethod { searchDryRun, searchMap, searchNBestListNaive, searchAStar }
Registered actions to perform for minimum Bayes risk.
typedef LatticeSetProcessor Precursor
To be documented!
Private Member Functions
Lattice::ConstWordLatticeRef mapEvalToLemmaPronunciation (Fsa::ConstAutomatonRef, Lattice::ConstWordLatticeRef)
Private Attributes
Search::MinimumBayesRiskSearch * search_
The search object performing the actual search.
Bliss::LexiconRef lexicon_
Fsa::ConstAutomatonRef lemmaPronToLemma_
Fsa::ConstAutomatonRef lemmaToEval_
NBestListExtractor * nBestListExtractor_
Static Private Attributes
static const Core::ParameterChoice paramSearchMethod
Choice which search method shall be applied.
static const Core::Choice choiceSearchMethod
The possible choices for search methods.
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Speech::LatticeSetProcessor
f64 timeProcessSegment_
Core::Ref< LatticeSetProcessor > processor_
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Search the lattice for string with minimal Bayes risk.
The result will always be a linear FSA representing a path in the lattice.
Definition at line 34 of file Speech/MinimumBayesRiskSearch.hh.
Member Typedef Documentation
typedef LatticeSetProcessor Speech::MinimumBayesRiskSearchNode::Precursor private
To be documented!
Definition at line 36 of file Speech/MinimumBayesRiskSearch.hh.
Member Enumeration Documentation
enum Speech::MinimumBayesRiskSearchNode::SearchMethod private
Registered actions to perform for minimum Bayes risk.
Definition at line 39 of file Speech/MinimumBayesRiskSearch.hh.
Constructor & Destructor Documentation
Speech::MinimumBayesRiskSearchNode::MinimumBayesRiskSearchNode (const Core::Configuration & config)
Standard constructor generating a configurable node.
The search object will be initialized here.
Parameters
config Configuration for this node.
Definition at line 42 of file Speech/MinimumBayesRiskSearch.cc.
References Core::Component::criticalError(), paramSearchMethod, and search_.
Speech::MinimumBayesRiskSearchNode::~MinimumBayesRiskSearchNode () virtual
Virtual destructor.
Here, the search object will be deleted.
Definition at line 66 of file Speech/MinimumBayesRiskSearch.cc.
References Lattice::composeMatching(), and search_.
Member Function Documentation
void Speech::MinimumBayesRiskSearchNode::initialize (Bliss::LexiconRef lexicon) virtual
Initialization of lexicon and evaluator.
Parameters
lexicon the Bliss lexicon for this corpus.
Reimplemented from Speech::LatticeSetProcessor.
Definition at line 78 of file Speech/MinimumBayesRiskSearch.cc.
References Core::Component::initialize(), and Fsa::multiply().
void Speech::MinimumBayesRiskSearchNode::processWordLattice (Lattice::ConstWordLatticeRef lattice, Bliss::SpeechSegment * segment) virtual
The actual processing of the word lattice where the search will be performed.
The lattice's Fsas will be linear combined each with weight 1.0 and the resulting total Fsa will be searched.
For the future, the Fsa to take should be made configurable!
Parameters
lattice the word lattice to be searched.
segment the speech segment, the lattice belongs to.
Assumption: fsa is an n-best list or lattice with evaluation tokens as input labels.
Reimplemented from Speech::LatticeSetProcessor.
Definition at line 91 of file Speech/MinimumBayesRiskSearch.cc.
References Core::Component::error(), Search::MinimumBayesRiskSearch::getBestAutomaton(), Search::MinimumBayesRiskSearch::performSearch(), Speech::LatticeSetProcessor::processWordLattice(), search_, and Lattice::WordLattice::totalFsa.
Member Data Documentation
const Core::Choice Speech::MinimumBayesRiskSearchNode::choiceSearchMethod static private
The possible choices for search methods.
Definition at line 55 of file Speech/MinimumBayesRiskSearch.hh.
const Core::ParameterChoice Speech::MinimumBayesRiskSearchNode::paramSearchMethod static private
Choice which search method shall be applied.
Definition at line 50 of file Speech/MinimumBayesRiskSearch.hh.
Referenced by MinimumBayesRiskSearchNode().
Search::MinimumBayesRiskSearch* Speech::MinimumBayesRiskSearchNode::search_ private
The search object performing the actual search.
To be deleted in destructor!
Definition at line 62 of file Speech/MinimumBayesRiskSearch.hh.
Referenced by MinimumBayesRiskSearchNode(), processWordLattice(), and ~MinimumBayesRiskSearchNode().
The documentation for this class was generated from the following files:
Speech/MinimumBayesRiskSearch.hh
Speech/MinimumBayesRiskSearch.cc