Sprint: Search::StateTree Class Reference
Search::StateTree Class Reference
Acoustic prefix tree.
#include <StateTree.hh>
Classes
struct BatchRequest
Build a new batch, i.e.
struct BuildRequest
Request for building a set of successors in the state tree.
class CoarticulationStructure
struct Exit
An exit point in the state tree.
struct LeapRequest
struct LevelStatistics
class PronunciationSuffix
Suffix of a pronunciation defined by a phoneme, a phoneme state and phoneme state substate (?)
class RecombiningRequestQueue
class RequestQueue
class ReverseTopologicalStateIterator
struct State
A node in the state tree.
struct StateDesc
Description of a state by its mixture index and its transition model.
class StraightRequestQueue
class SuccessorIterator
class SuffixSet
A set of pronuncation suffixes (.
Public Types
typedef s32 StateId
typedef std::list< Exit > ExitList
typedef ExitList::iterator ExitIterator
typedef ExitList::const_iterator const_ExitIterator
typedef s16 Depth
Public Member Functions
int compareSequences (const PronunciationSuffix &, const PronunciationSuffix &) const
u32 hashSequence (const PronunciationSuffix &) const
StateTree (const Core::Configuration &, Bliss::LexiconRef, Core::Ref< const Am::AcousticModel >)
StateId nStates () const
size_t memSizeStates () const
StateId nWordHeadStates () const
StateId root () const
StateId ciRoot () const
std::pair< Bliss::Phoneme::Id, Bliss::Phoneme::Id > describeRootState (StateId) const
Depth stateDepth (StateId s) const
const StateDesc & stateDesc (StateId s) const
const State & state (StateId s) const
const Am::StateTransitionModel * transitionModel (const StateDesc &desc) const
const Am::StateTransitionModel * transitionModel (StateId s) const
std::pair< SuccessorIterator, SuccessorIterator > successors (StateId s) const
std::pair< SuccessorIterator, SuccessorIterator > successors2 (StateId s) const
std::pair< const_ExitIterator, const_ExitIterator > wordEnds (StateId s) const
void logStatistics () const
void draw (std::ostream &, Core::Ref< const Bliss::PhonemeInventory > phi) const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Attributes
std::vector< State > states_
StateId root_
StateId ciRoot_
std::vector< StateId > batches_
Access to batches of states.
std::vector< BatchId > successorBatches_
Successors of batches.
BatchId emptyBatch_
StateId wordHeadsEnd_
Static Public Attributes
static const Depth invalidDepth = Core::Type<StateTree::Depth>::max
static const StateDesc::AcousticModelIndex invalidAcousticModel = Core::Type<StateTree::StateDesc::AcousticModelIndex>::max
static const BatchId invalidBatch = Core::Type<StateTree::BatchId>::max
static const Core::ParameterBool paramEarlyRecombination
static const Core::ParameterInt paramEarlyRecombinationLimit
static const Core::ParameterBool paramEnforcePathRecombinationInFanIn
static const Core::ParameterString paramFile
static const Core::ParameterBool paramSkipTransitions
static const Core::ParameterBool paramCiCrossWordTransitions
Private Types
typedef std::vector< Bliss::Phoneme::Id > PhonemeList
typedef s32 BatchId
Private Member Functions
Core::Ref< const Bliss::PhonemeInventory > phonemeInventory () const
bool advanceSubState (PronunciationSuffix &) const
Go to the next sub state of the current phoneme state in the current phoneme of s.
bool advancePhoneState (PronunciationSuffix &) const
Go to the next phoneme state of the current phoneme in s.
const Am::Allophone * getAllophone (const PronunciationSuffix &) const
Find the allophone for the current phoneme in s.
s8 nPhoneStates (const PronunciationSuffix &) const
s8 nSubStates (const PronunciationSuffix &) const
s16 boundary (const PronunciationSuffix &) const
Phoneme boundary (initial, final, or both) for the current phoneme in s.
u16 transitionModelIndex (const PronunciationSuffix &) const
Transition model for the current (sub-) state of c.
void advancePronunciationSuffix (const PronunciationSuffix &s, std::back_insert_iterator< std::vector< PronunciationSuffix >> continuing, std::back_insert_iterator< std::vector< PronunciationSuffix >> ending) const
Go to the next (sub-) state in the pronciation.
void leap (PronunciationSuffix &s) const
StateDesc head (const PronunciationSuffix &) const
Create a state description for the current phoneme in s.
u32 nStatesRemaining (const PronunciationSuffix &) const
StateId pronunciationSuffixTransitEntry (const PronunciationSuffix &) const
get the transit entry for the final phoneme of s with successor phoneme s.successorPhoneme_.
void buildNonCoarticulatedRootState (Bliss::LexiconRef)
void buildCoarticulatedRootStates (Bliss::LexiconRef)
void createExits (const std::vector< PronunciationSuffix > &, ExitList &)
Append for each ending pronunciation an exit object with the matching lemma pronunciation.
bool shouldLeap (const SuffixSet &, Depth) const
BatchId createBatch (BatchRequest *)
Create successor tree nodes and submit respective build requests.
StateId createLeapEntry (LeapRequest *)
void createSecondOrderBatches ()
Fill successorBatches_, the successors of batches.
bool isConsistent () const
void buildTreeLexicon (Bliss::LexiconRef)
bool hasMeshStructure () const
void getTransitionModels ()
Private Attributes
Core::Ref< const Am::AcousticModel > acousticModel_
PhonemeList * initialPhonemes_
bool isEarlyRecombinationEnabled_
bool isPathRecombinationInFanInEnabled_
s32 earlyRecombinationLimit_
bool haveSuccessorBatches_
bool allowSkipTransitions_
bool allowCiCrossWordTransitions_
std::vector< const Am::StateTransitionModel * > transitionModels_
CoarticulationStructure * coarticulationStructure_
RequestQueue * requests_
Friends
class SuffixSet
struct StateTree::BatchRequest
struct StateTree::LeapRequest
class StateTree::StraightRequestQueue
class StateTree::RecombiningRequestQueue
class StateTreeIo
class StateTreeWriter
class StateTreeReader
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Acoustic prefix tree.
Not strictly a tree anymore, but a DAG where the successors sets at each level of any two nodes are either identical or disjoint.
paramCiCrossWordTransitions: instead of allowing word boundary transitions a{b+#} -> a{#+d} use only transitions a{b+#} -> ci{#+#} with ci a context independent phone (silence, noise)
Definition at line 42 of file StateTree.hh.
Member Function Documentation
bool StateTree::advancePhoneState (PronunciationSuffix & s) const inline private
Go to the next phoneme state of the current phoneme in s.
Returns
last phone state was passed
Definition at line 209 of file StateTree.cc.
Referenced by advancePronunciationSuffix().
void StateTree::advancePronunciationSuffix (const PronunciationSuffix & _s, std::back_insert_iterator< std::vector< PronunciationSuffix >> out, std::back_insert_iterator< std::vector< PronunciationSuffix >> ends) const private
Go to the next (sub-) state in the pronciation.
Successor pronuncation suffixes appended to out If the pronunciation ends, it is appended to ends
Definition at line 297 of file StateTree.cc.
References advancePhoneState(), advanceSubState(), getAllophone(), Bliss::Pronunciation::length(), require, and verify.
bool StateTree::advanceSubState (PronunciationSuffix & s) const inline private
Go to the next sub state of the current phoneme state in the current phoneme of s.
Returns
last substate was passed
Definition at line 194 of file StateTree.cc.
Referenced by advancePronunciationSuffix().
s16 StateTree::boundary (const PronunciationSuffix & s) const inline private
Phoneme boundary (initial, final, or both) for the current phoneme in s.
Definition at line 249 of file StateTree.cc.
References Bliss::Pronunciation::length().
Referenced by getAllophone().
StateTree::BatchId StateTree::createBatch (BatchRequest * request) private
Create successor tree nodes and submit respective build requests.
Definition at line 1196 of file StateTree.cc.
References Search::StateTree::SuffixSet::advance(), batches_, createExits(), Core::Component::exit(), Search::StateTree::SuffixSet::partition(), require, states_, and verify.
void StateTree::createExits (const std::vector< PronunciationSuffix > & , ExitList &) private
Append for each ending pronunciation an exit object with the matching lemma pronunciation.
Definition at line 1159 of file StateTree.cc.
References Core::Component::exit(), Bliss::Pronunciation::lemmas(), pronunciationSuffixTransitEntry(), and require.
Referenced by createBatch(), and pronunciationSuffixTransitEntry().
void StateTree::createSecondOrderBatches () private
Fill successorBatches_, the successors of batches.
Definition at line 1266 of file StateTree.cc.
References batches_, states_, successorBatches_, and verify.
Referenced by pronunciationSuffixTransitEntry().
const Am::Allophone * StateTree::getAllophone (const PronunciationSuffix & s) const inline private
Find the allophone for the current phoneme in s.
Definition at line 222 of file StateTree.cc.
References boundary(), Bliss::Pronunciation::length(), and verify.
Referenced by advancePronunciationSuffix(), head(), and transitionModelIndex().
StateTree::StateDesc StateTree::head (const PronunciationSuffix & s) const private
Create a state description for the current phoneme in s.
Sets the acousticModel and the transitionModel of the state description.
Definition at line 277 of file StateTree.cc.
References getAllophone(), require, and transitionModelIndex().
Referenced by Search::StateTree::SuffixSet::partition().
StateTree::StateId StateTree::pronunciationSuffixTransitEntry (const PronunciationSuffix & s) const private
get the transit entry for the final phoneme of s with successor phoneme s.successorPhoneme_.
the transit entry is the root state for the coarticulated first state of s.successorPhoneme with s.finalPhonhme() as predecessor.
Definition at line 977 of file StateTree.cc.
References Search::StateTree::SuffixSet::advance(), batches_, createExits(), createSecondOrderBatches(), defect, ensure, Core::ProgressIndicator::finish(), Bliss::Pronunciation::length(), Core::ProgressIndicator::notify(), Bliss::Lexicon::pronunciations(), require, Core::ProgressIndicator::start(), states_, Search::StateTree::PronunciationSuffix::successorPhoneme(), verify, and Core::Component::warning().
Referenced by createExits().
u16 StateTree::transitionModelIndex (const PronunciationSuffix & s) const inline private
Transition model for the current (sub-) state of c.
Definition at line 261 of file StateTree.cc.
References getAllophone().
Referenced by head().
Member Data Documentation
std::vector<StateId> Search::StateTree::batches_
Access to batches of states.
Each element is the highest states_ index of a batch. States in batch b are batches_[b] .. batches_[b+1]
Definition at line 183 of file StateTree.hh.
Referenced by createBatch(), createSecondOrderBatches(), pronunciationSuffixTransitEntry(), and Search::StateTreeWriter::writeDependenciesPosition().
std::vector<State> Search::StateTree::states_
storage for all states
Definition at line 175 of file StateTree.hh.
Referenced by Search::ConvertTree::convert(), createBatch(), createSecondOrderBatches(), pronunciationSuffixTransitEntry(), and Search::StateTreeWriter::writeDependenciesPosition().
std::vector<BatchId> Search::StateTree::successorBatches_
Successors of batches.
Successor states of batch b are batches_[sb] .. batches_[sb+1] with sb = successorBatches_[b]
Definition at line 189 of file StateTree.hh.
Referenced by createSecondOrderBatches(), and Search::StateTreeWriter::writeDependenciesPosition().
The documentation for this class was generated from the following files:
StateTree.hh
StateTree.cc