Sprint: Translation::ConditionalLexiconSri Class Reference
Translation::ConditionalLexiconSri Class Reference
Public Member Functions
ConditionalLexiconSri (const Core::Configuration &config)
ConditionalLexiconSri (const Core::Configuration &config, Fsa::ConstAlphabetRef alphabet)
virtual Translation::Cost getProb (const size_t index, const std::vector< std::string > &key) const
this is deprecated and should just exist as long as i am migrating to the new lexicon
virtual Translation::Cost getCost (const size_t index, const std::vector< Fsa::LabelId > &key) const
virtual Translation::Cost getReverseCost (const size_t index, const std::vector< Fsa::LabelId > &key) const
virtual Translation::Cost getProb (const size_t index, const std::vector< Fsa::LabelId > &key) const
get probability of a lexicon entry or floor if it does not exist
virtual void addValue (const size_t index, const std::vector< Fsa::LabelId > &key, Translation::Cost value)
add value to existing count/prob or create new if it does not exist
virtual void addValue (const size_t index, const std::vector< std::string > &key, Translation::Cost value)
add value to existing count/prob or create new if it does not exist
virtual void setValue (const size_t index, const std::vector< Fsa::LabelId > &key, Translation::Cost value)
set value of the given entry (overwrite if it exists, create if it doesnt)
virtual void setValue (const size_t index, const std::vector< std::string > &key, Translation::Cost value)
set value of the given entry (overwrite if it exists, create if it doesnt)
virtual void write (std::ostream &)
write lexicon to stream
virtual void normalize (int order)
normalize
virtual void read (std::istream &)
read a lexicon from a file stream
virtual void read ()
read a lexicon from a file given as component parameter
Public Member Functions inherited from Translation::ConditionalLexicon
ConditionalLexicon (const Core::Configuration &config)
ConditionalLexicon (const Core::Configuration &config, Fsa::ConstAlphabetRef alphabet)
ConstAlphabetRef getTokenAlphabet () const
return ConstAlphabetRef of the internal token alphabet for matching against other alphabets
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Private Types
typedef Translation::SimplePrefixTree< Fsa::LabelId, Translation::Cost > Lexicon
typedef Core::Ref< Lexicon > LexiconRef
typedef MallocOptimizedHistory< VocabIndex > VocabIndexHistory
typedef hash_map< const LabelIdPair, VocabIndex, hash_LabelIdPair, equal_LabelIdPair > VocabMapType
Private Member Functions
VocabIndex mapToTupleIndexString_ (Fsa::LabelId s, Fsa::LabelId t) const
VocabIndex mapToTupleIndex_ (Fsa::LabelId s, Fsa::LabelId t) const
Private Attributes
std::vector< LexiconRef > lexica_
holds lexica for the different types of transitions (if neccessary)
Translation::Cost floor_
floor probability for values that are not in the lexicon
const std::string lexiconFilename_
filename as a string. read from the correspondinf parameter
Vocab sriTupleVocabulary_
Ngram srilm_
VocabIndex unknownIndex_
VocabIndex sentenceBeginIndex_
VocabIndex sentenceEndIndex_
VocabIndex * history_
Fsa::LabelId fsaSentenceBeginSymbol_
size_t lmOrder_
size_t userLmOrder_
VocabMapType vocabMap
Static Private Attributes
static Core::ParameterString paramFilename_
parameter giving the filename to read from
static Core::ParameterInt paramLmOrder_
paramter for overriding the language model order given in the file
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Translation::ConditionalLexicon
Fsa::StaticAlphabet * tokens_
tokens (no distinctions between source or target)
Fsa::ConstAlphabetRef tokenRef_
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Definition at line 66 of file ConditionalLexiconSri.hh.
Constructor & Destructor Documentation
Translation::ConditionalLexiconSri::ConditionalLexiconSri (const Core::Configuration & config) inline
Todo:
sentence begin symbol is hardcoded
Definition at line 68 of file ConditionalLexiconSri.hh.
Member Function Documentation
virtual void Translation::ConditionalLexiconSri::addValue (const size_t index, const std::vector< Fsa::LabelId > & key, Translation::Cost value) inline virtual
add value to existing count/prob or create new if it does not exist
Implements Translation::ConditionalLexicon.
Definition at line 135 of file ConditionalLexiconSri.hh.
virtual void Translation::ConditionalLexiconSri::addValue (const size_t index, const std::vector< std::string > & key, Translation::Cost value) inline virtual
add value to existing count/prob or create new if it does not exist
Implements Translation::ConditionalLexicon.
Definition at line 140 of file ConditionalLexiconSri.hh.
virtual Translation::Cost Translation::ConditionalLexiconSri::getProb (const size_t index, const std::vector< std::string > & key) const inline virtual
this is deprecated and should just exist as long as i am migrating to the new lexicon
Implements Translation::ConditionalLexicon.
Definition at line 93 of file ConditionalLexiconSri.hh.
virtual Translation::Cost Translation::ConditionalLexiconSri::getProb (const size_t index, const std::vector< Fsa::LabelId > & key) const inline virtual
get probability of a lexicon entry or floor if it does not exist
Implements Translation::ConditionalLexicon.
Definition at line 130 of file ConditionalLexiconSri.hh.
virtual void Translation::ConditionalLexiconSri::normalize (int order) inline virtual
normalize
Implements Translation::ConditionalLexicon.
Definition at line 158 of file ConditionalLexiconSri.hh.
virtual void Translation::ConditionalLexiconSri::read (std::istream &) inline virtual
read a lexicon from a file stream
Implements Translation::ConditionalLexicon.
Definition at line 216 of file ConditionalLexiconSri.hh.
PREPARE_MALLOC_OPTIMIZED_HISTORY void Translation::ConditionalLexiconSri::read () virtual
read a lexicon from a file given as component parameter
Implements Translation::ConditionalLexicon.
Definition at line 28 of file ConditionalLexiconSri.cc.
References Fsa::StaticAlphabet::addSymbol(), Core::Component::criticalError(), lexiconFilename_, Core::split(), and Translation::ConditionalLexicon::tokens_.
virtual void Translation::ConditionalLexiconSri::setValue (const size_t index, const std::vector< Fsa::LabelId > & key, Translation::Cost value) inline virtual
set value of the given entry (overwrite if it exists, create if it doesnt)
Implements Translation::ConditionalLexicon.
Definition at line 145 of file ConditionalLexiconSri.hh.
virtual void Translation::ConditionalLexiconSri::setValue (const size_t index, const std::vector< std::string > & key, Translation::Cost value) inline virtual
set value of the given entry (overwrite if it exists, create if it doesnt)
Implements Translation::ConditionalLexicon.
Definition at line 150 of file ConditionalLexiconSri.hh.
virtual void Translation::ConditionalLexiconSri::write (std::ostream &) inline virtual
write lexicon to stream
Implements Translation::ConditionalLexicon.
Definition at line 155 of file ConditionalLexiconSri.hh.
Member Data Documentation
Translation::Cost Translation::ConditionalLexiconSri::floor_ private
floor probability for values that are not in the lexicon
Definition at line 188 of file ConditionalLexiconSri.hh.
std::vector<LexiconRef> Translation::ConditionalLexiconSri::lexica_ private
holds lexica for the different types of transitions (if neccessary)
Definition at line 185 of file ConditionalLexiconSri.hh.
const std::string Translation::ConditionalLexiconSri::lexiconFilename_ private
filename as a string. read from the correspondinf parameter
Definition at line 194 of file ConditionalLexiconSri.hh.
Referenced by read().
Core::ParameterString Translation::ConditionalLexiconSri::paramFilename_ static private
parameter giving the filename to read from
Definition at line 191 of file ConditionalLexiconSri.hh.
Core::ParameterInt Translation::ConditionalLexiconSri::paramLmOrder_ static private
paramter for overriding the language model order given in the file
Definition at line 197 of file ConditionalLexiconSri.hh.
The documentation for this class was generated from the following files:
ConditionalLexiconSri.hh
ConditionalLexiconSri.cc