Sprint: Flf::ConfusionNetworkCombination Class Reference
Flf::ConfusionNetworkCombination Class Reference
Classes
class ExpectedError
The probability that the slot's top hypothesis will be wrong 1.0 - max_{w} { w_{ref} * p_{ref}(w) + w_{hyp} * p_{hyp}(w) }.
class ExpectedLoss
The expected number of errors caused by this slot sum_{w,v; w != v} p_{ref}(w) * p_{hyp}(v))
class WeightedCost
Public Types
typedef Core::Ref< WeightedCost > WeightedCostRef
Public Types inherited from Flf::ConfusionNetworkAlignment
typedef Core::Ref< const Cost > ConstCostRef
typedef std::vector< std::pair< u32, u32 > > Alignment
typedef Alignment::const_reverse_iterator const_iterator
Public Member Functions
void dump (std::ostream &os) const
bool verifyCn (const ConfusionNetwork &cn, Score norm) const
ConstConfusionNetworkRef combine (const ConstConfusionNetworkRefList &cns, ConfusionNetworkAlignmentPtrList *alignments=0) const
Public Member Functions inherited from Flf::ConfusionNetworkAlignment
ConfusionNetworkAlignment (ConstCostRef costFcn, u32 minBeamWidth)
void dump (std::ostream &os) const
ConstCostRef cost ()
u32 beamWidth () const
const_iterator begin () const
const_iterator end () const
Score align (const ConfusionNetwork &ref, const ConfusionNetwork &hyp) const
Levenshtein alignment with fixed beam around main diagonal.
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Static Public Member Functions
static ConstConfusionNetworkCombinationRef create (WeightedPosteriorCombinationHelperRef weightedCombo, WeightedCostRef weightedCostFcn, u32 minBeamWidth)
Private Types
typedef ConfusionNetworkAlignment Precursor
Private Member Functions
void init (ConfusionNetwork *combinedCn, ConstConfusionNetworkRef cn) const
Build CN by merging the aligned slots.
void add (const ConfusionNetworkAlignment &alignment, ConfusionNetwork *combinedCn, ConstConfusionNetworkRef cn, u32 i) const
ConfusionNetworkCombination (WeightedPosteriorCombinationHelperRef weightedCombo, WeightedCostRef weightedCostFcn, u32 minBeamWidth)
Private Attributes
WeightedPosteriorCombinationHelperRef weightedCombo_
WeightedCostRef weightedCostFcn_
ScoreList sumWeights_
Detailed Description
Definition at line 486 of file ConfusionNetworkCombination.cc.
Member Function Documentation
void Flf::ConfusionNetworkCombination::init (ConfusionNetwork * combinedCn, ConstConfusionNetworkRef cn) const inline private
Build CN by merging the aligned slots.
Definition at line 651 of file ConfusionNetworkCombination.cc.
References Flf::ConfusionNetworkAlignment::align(), Core::Component::criticalError(), Core::Vector< T >::get(), Core::round(), Core::Application::us(), and verify.
The documentation for this class was generated from the following file:
ConfusionNetworkCombination.cc