Sprint: Signal::FilterBank::Boundary Class Reference
Signal::FilterBank::Boundary Class Reference abstract
Base class for boundary types.
Public Member Functions
virtual void init (Frequency filterWidth, Frequency spacing, Frequency normalizedCenterPosition)
Initializes the object without maximumFrequency and warping.
virtual bool init (Frequency filterWidth, Frequency spacing, Frequency normalizedCenterPosition, Frequency minimumFrequency, Frequency maximumFrequency, Math::UnaryAnalyticFunctionRef warpingFunction)
Complete initialization of the object.
Frequency filterWidth () const
virtual Frequency center (size_t filterIndex) const =0
virtual size_t getNumberOfFilters () const =0
virtual Frequency outputSampleRate () const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Protected Types
typedef FilterBank::Frequency Frequency
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions
void setSpacing (Frequency Spacing)
bool setWarpingFunction (Math::UnaryAnalyticFunctionRef warpingFunction)
Frequency postprocessNumberOfFilters (Frequency nFilters) const
Boundary (const Core::Configuration &c)
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes
Frequency filterWidth_
Frequency spacing_
Frequency normalizedCenterPosition_
Frequency minimumFrequency_
Frequency maximumFrequency_
Math::UnaryAnalyticFunctionRef warpingFunction_
Math::UnaryAnalyticFunctionRef inverseWarpingFunction_
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Base class for boundary types.
Boundary classes control:
position of first filter
position of last filter
number of filters
spacing between filters
warping of filter center positions
Definition at line 361 of file Filterbank.cc.
Member Function Documentation
void Signal::FilterBank::Boundary::init (Frequency filterWidth, Frequency spacing, Frequency normalizedCenterPosition) virtual
Initializes the object without maximumFrequency and warping.
Use to initialize before calling outputSampleRate.
Definition at line 423 of file Filterbank.cc.
bool Signal::FilterBank::Boundary::init (Frequency filterWidth, Frequency spacing, Frequency normalizedCenterPosition, Frequency minimumFrequency, Frequency maximumFrequency, Math::UnaryAnalyticFunctionRef warpingFunction) virtual
Complete initialization of the object.
Reimplemented in StretchToCover.
Definition at line 429 of file Filterbank.cc.
References Math::AnalyticFunctionFactory::createIdentity(), Core::Component::error(), Signal::FilterBank::FilterBuilder::maximumFrequency_, Core::round(), and verify.
virtual Frequency Signal::FilterBank::Boundary::outputSampleRate () const inline virtual
Returns
is sample rate of the output of the filter-bank. Thus, output is inverse of distances between the filters. If centers are warped the distance is constant over the warped axes else distance is constant over the original unwarped axis.
Reimplemented in StretchToCover.
Definition at line 418 of file Filterbank.cc.
The documentation for this class was generated from the following file:
Filterbank.cc