Sprint: Speech::MeanEstimator Class Reference
Speech::MeanEstimator Class Reference
Public Member Functions
MeanEstimator (const Core::Configuration &c)
Public Member Functions inherited from Speech::FeatureExtractor
FeatureExtractor (const Core::Configuration &c, bool loadFromFile=true)
virtual void processSegment (Bliss::Segment *segment)
Public Member Functions inherited from Speech::DataExtractor
DataExtractor (const Core::Configuration &c, bool loadFromFile=true)
virtual void signOn (CorpusVisitor &corpusVisitor)
Override this function to sign on to services of the corpus visitor.
virtual void enterCorpus (Bliss::Corpus *)
virtual void leaveCorpus (Bliss::Corpus *)
virtual void enterRecording (Bliss::Recording *)
virtual void enterSegment (Bliss::Segment *)
virtual void leaveSegment (Bliss::Segment *)
Public Member Functions inherited from Speech::CorpusProcessor
CorpusProcessor (const Core::Configuration &c)
virtual void leaveRecording (Bliss::Recording *recoding)
virtual void enterSpeechSegment (Bliss::SpeechSegment *)
virtual void processSpeechSegment (Bliss::SpeechSegment *segment)
virtual void leaveSpeechSegment (Bliss::SpeechSegment *)
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Signal::MeanEstimator
MeanEstimator (const Core::Configuration &c)
void setDimension (size_t dimension)
void accumulate (const Math::Vector< Data > &)
bool finalize (Math::Vector< Data > &mean) const
bool write () const
Saves mean.
void reset ()
Protected Member Functions
virtual void processFeature (Core::Ref< const Feature > feature)
Override this function to achieve the features extracted form data source one-by-one.
virtual void setFeatureDescription (const Mm::FeatureDescription &description)
Override this function to achieve the attributes of the feature streams.
Protected Member Functions inherited from Speech::DataExtractor
void setDataSource (Core::Ref< DataSource > s)
Core::Ref< DataSource > dataSource () const
Protected Member Functions inherited from Speech::CorpusProcessor
void reportRealTime (Flow::Time)
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Static Protected Attributes
static const Core::ParameterString paramFile
Private Types
typedef FeatureExtractor Extractor
typedef Signal::MeanEstimator Estimator
Private Attributes
bool needResize_
Additional Inherited Members
Public Types inherited from Signal::MeanEstimator
typedef f32 Data
typedef f64 Sum
typedef u32 Count
Static Public Attributes inherited from Signal::MeanEstimator
static const Core::ParameterString paramFilename
static const Core::ParameterInt paramOutputPrecision
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Attributes inherited from Speech::CorpusProcessor
Core::XmlChannel channelTimer_
Core::Timer timer_
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Definition at line 23 of file Speech/MeanEstimator.hh.
Member Function Documentation
void MeanEstimator::processFeature (Core::Ref< const Feature >) protected virtual
Override this function to achieve the features extracted form data source one-by-one.
Reimplemented from Speech::FeatureExtractor.
Definition at line 30 of file Speech/MeanEstimator.cc.
References Mm::Feature::mainStream().
void MeanEstimator::setFeatureDescription (const Mm::FeatureDescription &) protected virtual
Override this function to achieve the attributes of the feature streams.
This function is called once before the first feature is processed.
Reimplemented from Speech::FeatureExtractor.
Definition at line 34 of file Speech/MeanEstimator.cc.
References Core::Description::Stream::getValue(), and Core::Description::verifyNumberOfStreams().
The documentation for this class was generated from the following files:
Speech/MeanEstimator.hh
Speech/MeanEstimator.cc