Sprint: Speech::LatticeSetProcessor Class Reference
Speech::LatticeSetProcessor Class Reference
LatticeSetProcessor is base class for algorithms processing lattice sets.
#include <LatticeSetProcessor.hh>
Public Member Functions
LatticeSetProcessor (const Core::Configuration &)
LatticeSetProcessor.
void setProcessor (Core::Ref< LatticeSetProcessor > processor)
This lattice set processor is used for cascading.
virtual void signOn (CorpusVisitor &corpusVisitor)
Override this function to sign on to services of the corpus visitor.
virtual void enterCorpus (Bliss::Corpus *corpus)
Override this function to perform pre processing before the first segment of the corpus.
virtual void leaveCorpus (Bliss::Corpus *corpus)
Override this function to perform post processing after the last segment of the corpus.
virtual void enterRecording (Bliss::Recording *recording)
Override this function to perform pre processing before the first segment of the recording.
virtual void leaveRecording (Bliss::Recording *recording)
Override this function to perform post processing after the last segment of the recording.
virtual void enterSegment (Bliss::Segment *s)
Override this function to perform preparations before first aligned features arrive.
virtual void leaveSegment (Bliss::Segment *s)
Override this function to perform post processing after the last aligned features of the segment.
virtual void enterSpeechSegment (Bliss::SpeechSegment *s)
Override this function to perform preparations before first features arrive.
virtual void leaveSpeechSegment (Bliss::SpeechSegment *s)
Override this function to perform post processing after the last features of the segment.
virtual void processWordLattice (Lattice::ConstWordLatticeRef, Bliss::SpeechSegment *)
Override this function to implement the processing of lattice sets.
virtual void getWordLatticeDescription (Lattice::WordLatticeDescription &)
Override this function to create the description of the output word lattices.
virtual void setWordLatticeDescription (const Lattice::WordLatticeDescription &)
Override this function to achieve the attributes of the input lattice set.
virtual void initialize (Bliss::LexiconRef lexicon)
Override this function to achieve the lexicon of the input lattice set.
virtual void setSegmentwiseFeatureExtractor (Core::Ref< SegmentwiseFeatureExtractor >)
virtual void setAlignmentGenerator (Core::Ref< PhonemeSequenceAlignmentGenerator >)
virtual std::string name () const
virtual void logComputationTime () const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Protected Attributes
f64 timeProcessSegment_
Core::Ref< LatticeSetProcessor > processor_
Protected Attributes inherited from Core::Configurable
Configuration config
Private Attributes
bool initialized_
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Detailed Description
LatticeSetProcessor is base class for algorithms processing lattice sets.
Remark: instance of this class can be used for dry runs since it does not have any abstract functions.
Definition at line 40 of file LatticeSetProcessor.hh.
Constructor & Destructor Documentation
LatticeSetProcessor::LatticeSetProcessor (const Core::Configuration & c)
LatticeSetProcessor.
Definition at line 40 of file LatticeSetProcessor.cc.
Member Function Documentation
virtual void Speech::LatticeSetProcessor::enterCorpus (Bliss::Corpus * corpus) inline virtual
Override this function to perform pre processing before the first segment of the corpus.
Definition at line 71 of file LatticeSetProcessor.hh.
Referenced by Speech::LatticeSetProcessorRoot::signOn().
virtual void Speech::LatticeSetProcessor::enterRecording (Bliss::Recording * recording) inline virtual
Override this function to perform pre processing before the first segment of the recording.
Definition at line 85 of file LatticeSetProcessor.hh.
Referenced by Speech::LatticeSetProcessorRoot::signOn().
virtual void Speech::LatticeSetProcessor::enterSegment (Bliss::Segment * s) inline virtual
Override this function to perform preparations before first aligned features arrive.
Definition at line 99 of file LatticeSetProcessor.hh.
Referenced by Speech::LatticeSetProcessorRoot::signOn().
virtual void Speech::LatticeSetProcessor::enterSpeechSegment (Bliss::SpeechSegment * s) inline virtual
Override this function to perform preparations before first features arrive.
Reimplemented in Speech::GerLatticeProcessorNode.
Definition at line 111 of file LatticeSetProcessor.hh.
Referenced by Speech::GerLatticeProcessorNode::enterSpeechSegment(), and Speech::LatticeSetProcessorRoot::signOn().
virtual void Speech::LatticeSetProcessor::getWordLatticeDescription (Lattice::WordLatticeDescription &) inline virtual
Override this function to create the description of the output word lattices.
Definition at line 128 of file LatticeSetProcessor.hh.
Referenced by processWordLattice().
virtual void Speech::LatticeSetProcessor::initialize (Bliss::LexiconRef lexicon) inline virtual
Override this function to achieve the lexicon of the input lattice set.
Reimplemented in Speech::GerLatticeProcessorNode, Speech::LatticeSetWriter, Speech::LatticeSetProcessorRoot, Speech::LatticeSetReader, Speech::NumeratorFromDenominatorExtractor, Speech::LatticeSetGenerator, Speech::LemmaPronunciationToSyntacticToken, Speech::LemmaPronunciationToEvaluationToken, Speech::WordLatticeMerger, Speech::AbstractSegmentwiseTrainer, Speech::MinimumBayesRiskSearchNode, Speech::TokenMappingLatticeProcessorNode, Speech::BaseWordLatticeMerger, Speech::NumeratorLatticeGenerator, Speech::WordLatticeUnion, Speech::NBestListLatticeProcessor, and Speech::WordLatticeWithoutRedundantSilencesAndNoises.
Definition at line 138 of file LatticeSetProcessor.hh.
virtual void Speech::LatticeSetProcessor::leaveCorpus (Bliss::Corpus * corpus) inline virtual
Override this function to perform post processing after the last segment of the corpus.
Reimplemented in Nn::SegmentwiseNnTrainer< T >, Speech::MinimumMaximumWeightNode, Speech::LatticeSetGenerator, and Speech::SegmentwiseGmmTrainer.
Definition at line 78 of file LatticeSetProcessor.hh.
Referenced by Speech::SegmentwiseGmmTrainer::leaveCorpus(), Speech::LatticeSetGenerator::leaveCorpus(), and Speech::LatticeSetProcessorRoot::signOn().
virtual void Speech::LatticeSetProcessor::leaveRecording (Bliss::Recording * recording) inline virtual
Override this function to perform post processing after the last segment of the recording.
Definition at line 92 of file LatticeSetProcessor.hh.
Referenced by Speech::LatticeSetProcessorRoot::signOn().
virtual void Speech::LatticeSetProcessor::leaveSegment (Bliss::Segment * s) inline virtual
Override this function to perform post processing after the last aligned features of the segment.
Definition at line 105 of file LatticeSetProcessor.hh.
Referenced by Speech::LatticeSetProcessorRoot::signOn().
virtual void Speech::LatticeSetProcessor::leaveSpeechSegment (Bliss::SpeechSegment * s) inline virtual
Override this function to perform post processing after the last features of the segment.
Definition at line 117 of file LatticeSetProcessor.hh.
Referenced by Speech::LatticeSetProcessorRoot::signOn().
void LatticeSetProcessor::processWordLattice (Lattice::ConstWordLatticeRef lattice, Bliss::SpeechSegment * s) virtual
Override this function to implement the processing of lattice sets.
Reimplemented in Speech::SkipEmptyLatticeNode, Speech::PartialNode, Speech::CopyNode, Speech::CacheNode, Speech::LinearCombinationLatticeProcessorNode, Speech::GerLatticeProcessorNode, Speech::DensityLatticeProcessorNode, Speech::DeterminizeNode, Speech::InfoLatticeProcessorNode, Speech::LatticeSetWriter, Speech::EpsilonRemoval, Speech::ExpmNode, Nn::SegmentwiseNnTrainer< T >, Speech::MinimumMaximumWeightNode, Speech::NumeratorFromDenominatorExtractor, Speech::DumpWordBoundariesNode, Speech::LatticeSetGenerator, Speech::LemmaPronunciationToSyntacticToken, Speech::SpokenAndCompetingListProcessor, Speech::AbstractAcousticSegmentwiseTrainer, Speech::MinimumBayesRiskSearchNode, Speech::LemmaPronunciationToEvaluationToken, Speech::WordLatticeMerger, Speech::BaseWordLatticeMerger, Speech::MinimumErrorSegmentwiseGmmTrainer, Speech::MapToNonCoarticulationLatticeProcessorNode, Speech::ExtendBestPathLatticeProcessorNode, Speech::MultiplyLatticeProcessorNode, Speech::WordLatticeUnion, Speech::TimeConditionedLatticeSetProcessor, Speech::NBestListLatticeProcessor, Speech::PruningLatticeSetNode, Speech::WordLatticeWithoutRedundantSilencesAndNoises, and Speech::ChangeSemiringLatticeProcessorNode.
Definition at line 45 of file LatticeSetProcessor.cc.
References Core::Component::error(), getWordLatticeDescription(), and Core::Component::log().
Referenced by Speech::LatticeSetReader::LatticeSetReader(), Speech::TimeConditionedLatticeSetProcessor::processWordLattice(), Speech::NBestListLatticeProcessor::processWordLattice(), Speech::ExtendBestPathLatticeProcessorNode::processWordLattice(), Speech::MapToNonCoarticulationLatticeProcessorNode::processWordLattice(), Speech::WordLatticeMerger::processWordLattice(), Speech::LemmaPronunciationToEvaluationToken::processWordLattice(), Speech::MinimumBayesRiskSearchNode::processWordLattice(), Speech::LemmaPronunciationToSyntacticToken::processWordLattice(), Speech::SpokenAndCompetingListProcessor::processWordLattice(), Speech::DumpWordBoundariesNode::processWordLattice(), Speech::NumeratorFromDenominatorExtractor::processWordLattice(), Speech::MinimumMaximumWeightNode::processWordLattice(), Nn::SegmentwiseNnTrainer< T >::processWordLattice(), Speech::ExpmNode::processWordLattice(), Speech::EpsilonRemoval::processWordLattice(), Speech::LatticeSetWriter::processWordLattice(), Speech::InfoLatticeProcessorNode::processWordLattice(), Speech::DensityLatticeProcessorNode::processWordLattice(), Speech::GerLatticeProcessorNode::processWordLattice(), Speech::LinearCombinationLatticeProcessorNode::processWordLattice(), Speech::CacheNode::processWordLattice(), Speech::CopyNode::processWordLattice(), Speech::PartialNode::processWordLattice(), Speech::SkipEmptyLatticeNode::processWordLattice(), and Speech::NumeratorLatticeGenerator::signOn().
void Speech::LatticeSetProcessor::setProcessor (Core::Ref< LatticeSetProcessor > processor) inline
This lattice set processor is used for cascading.
Definition at line 55 of file LatticeSetProcessor.hh.
References require, and verify.
Referenced by LatticeProcessor::main().
virtual void Speech::LatticeSetProcessor::setWordLatticeDescription (const Lattice::WordLatticeDescription &) inline virtual
Override this function to achieve the attributes of the input lattice set.
This function is called once before the first segment is processed.
Reimplemented in Speech::TimeConditionedLatticeSetProcessor.
Definition at line 133 of file LatticeSetProcessor.hh.
virtual void Speech::LatticeSetProcessor::signOn (CorpusVisitor & corpusVisitor) inline virtual
Override this function to sign on to services of the corpus visitor.
Note: call the signOn function of your predecessor.
Reimplemented in Speech::LatticeSetProcessorRoot, Speech::LatticeSetGenerator, and Speech::NumeratorLatticeGenerator.
Definition at line 64 of file LatticeSetProcessor.hh.
Referenced by Speech::LatticeSetProcessorRoot::signOn().
The documentation for this class was generated from the following files:
LatticeSetProcessor.hh
LatticeSetProcessor.cc