Sprint: Core::Vector< T > Class Template Reference
Core::Vector< T > Class Template Reference
Public Types
typedef std::vector< T > Precursor
typedef Precursor::iterator iterator
typedef Precursor::const_iterator const_iterator
Public Member Functions
Vector (size_t size)
Vector (size_t size, const T &def)
Vector (const Precursor &vector)
void grow (size_t maxId, const T &def=T())
grow to size maxId+1.
void yield ()
Free over-allocated storage.
void minimize ()
void set (size_t id, const T &val, const T &def=T())
safe set
T get (size_t id, const T &def=T()) const
safe get
size_t getMemoryUsed () const
Detailed Description
template<class T>
class Core::Vector< T >
Definition at line 24 of file Core/Vector.hh.
Member Function Documentation
template<class T> T Core::Vector< T >::get (size_t id, const T & def = T()) const inline
safe get
Definition at line 67 of file Core/Vector.hh.
Referenced by Flf::UnionBoundaries::get(), Flf::FwdBwdPruningNode::init(), and Flf::ConfusionNetworkCombination::init().
template<class T> void Core::Vector< T >::grow (size_t maxId, const T & def = T()) inline
grow to size maxId+1.
Definition at line 41 of file Core/Vector.hh.
Referenced by Aligner::WordLatticeBuilder::Converter::build(), Flf::cleanUp(), Ftl::DeterminizeAutomaton< _Automaton >::Substates::equal(), Ftl::InDegreeDfsState< _Automaton >::exploreNonTreeArc(), Ftl::InDegreeDfsState< _Automaton >::exploreTreeArc(), Fsa::StatePotentials64DfsState::finishState(), Flf::FwdBwd::Builder::TraverseLatticeProperties::finishState(), Ftl::TopologicallySortDfsState< _Automaton >::finishState(), Flf::FittingLattice::Boundaries::get(), Core::Vector< ExpandedToken >::set(), and Ftl::SsspForward4SpecialSymbols< _Automaton, _Semiring, _Weight >::ForwardPotential::walk2().
template<class T> void Core::Vector< T >::set (size_t id, const T & val, const T & def = T()) inline
safe set
Definition at line 61 of file Core/Vector.hh.
Referenced by Ftl::SsspBackward4SpecialSymbols< _Automaton >::finishState().
template<class T> void Core::Vector< T >::yield () inline
Free over-allocated storage.
Definition at line 50 of file Core/Vector.hh.
Referenced by Core::Vector< ExpandedToken >::yield().
The documentation for this class was generated from the following file:
Core/Vector.hh