Sprint: Signal::Window Class Reference
Signal::Window Class Reference
Window.
#include <Window.hh>
Public Types
typedef WindowBuffer Predecessor
typedef WindowBuffer::Time Time
typedef WindowBuffer::Sample Sample
Public Types inherited from Signal::WindowBuffer
enum FlushPolicy { SendRest, PadRest, DiscardRest }
typedef Flow::Time Time
typedef f32 Sample
typedef Flow::Vector< Sample > InputData
typedef Flow::Vector< Sample > OutputData
Public Member Functions
void setWindowFunction (WindowFunction *windowFunction)
void setSampleRate (f64 sampleRate)
void setLengthInS (Time length)
Time lengthInS () const
void setShiftInS (Time shift)
Time shiftInS () const
Public Member Functions inherited from Signal::WindowBuffer
bool put (const Flow::Vector< Sample > &in)
adds an input vector
bool get (Flow::Vector< Sample > &out)
returns one vector of the given length_ and removes shift_ number of elements from the begining of the buffer
bool flush (Flow::Vector< Sample > &out)
delivers the rest of the buffer_
virtual void reset ()
Clears the buffer and resets status variables.
void setShift (u32 shift)
set the number of samples removed after each call to get
u32 shift ()
the number of samples removed after each call to get
void setLength (u32 length)
sets the length of output vectors
u32 length () const
length of output vectors
void setSampleRate (Time sampleRate)
Time sampleRate () const
u32 nOutputs ()
number released of outputs
bool flushed ()
void setFlushAll (bool flushAll)
if
bool flushAll () const
void setFlushBeforeGap (bool flushBeforeGap)
bool shallFlushBeforeGap () const
Protected Member Functions
virtual void init ()
overload to perform initialization
virtual void transform (Flow::Vector< Sample > &out)
overload to transform output vectors
Protected Member Functions inherited from Signal::WindowBuffer
void setNeedInit ()
call to force initialization
Private Attributes
Time lengthInS_
Time shiftInS_
WindowFunction * windowFunction_
Additional Inherited Members
Protected Attributes inherited from Signal::WindowBuffer
u32 length_
length_ of output vectors
u32 shift_
number of elements removed from the beginning of the buffer after a call to get
Time bufferStartTime_
Time sampleRate_
bool flushBeforeGap_
std::deque< Sample > buffer_
u32 nOutputs_
number released of outputs
bool flushed_
true if buffer is flushed
bool flushAll_
if true, segments are delivered shift-by-shift until the buffer is empty if false, segments are delivered until the last segment contains the last sample
bool needInit_
Detailed Description
Window.
Definition at line 31 of file Window.hh.
Member Function Documentation
void Window::init () protected virtual
overload to perform initialization
Reimplemented from Signal::WindowBuffer.
Definition at line 64 of file Window.cc.
References verify.
Referenced by Signal::WindowBuffer::flush(), Signal::WindowBuffer::get(), and Signal::WindowBuffer::put().
void Window::transform (Flow::Vector< Sample > & out) protected virtual
overload to transform output vectors
caution: update the start- and end-time of out if the size is changed
Reimplemented from Signal::WindowBuffer.
Definition at line 74 of file Window.cc.
References hope.
Referenced by Signal::WindowBuffer::copy().
The documentation for this class was generated from the following files:
Window.hh
Window.cc