Sprint: Search::Wfst::Builder::AddNonWordTokens Class Reference
Search::Wfst::Builder::AddNonWordTokens Class Reference
adds non-word tokens (silence/noise) to the grammar transducer.
#include <CreateOperations.hh>
Public Member Functions
AddNonWordTokens (const Core::Configuration &c, Resources &r)
virtual u32 nInputAutomata () const
number of automata required as input
Public Member Functions inherited from Search::Wfst::Builder::OutputTypeDependent
OutputTypeDependent (const Core::Configuration &c)
Public Member Functions inherited from Search::Wfst::Builder::SleeveOperation
SleeveOperation (const Core::Configuration &c, Resources &r)
virtual bool addInput (AutomatonRef f)
add input automaton (will be called nInputAutomata() times)
void deleteInput ()
Public Member Functions inherited from Search::Wfst::Builder::Operation
Operation (const Core::Configuration &c, Resources &r)
virtual bool consumeInput () const
should input automata be removed
virtual bool hasOutput () const
operation is expected to produce an output automaton.
AutomatonRef getResult ()
do the actual processing and create an output automaton
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Static Public Member Functions
static std::string name ()
Protected Member Functions
virtual AutomatonRef process ()
do the actual processing
Protected Member Functions inherited from Search::Wfst::Builder::OutputTypeDependent
OutputType outputType () const
Protected Member Functions inherited from Search::Wfst::Builder::SleeveOperation
virtual bool precondition () const
precondition for getResult()
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Private Member Functions
void addArcs (OpenFst::StateId s, f32 weight, const std::vector< OpenFst::Label > &labels)
void getLabels (const std::vector< std::string > &lemmas, std::vector< OpenFst::Label > &labels) const
OpenFst::Label getLabel (const Bliss::Lemma *lemma) const
OpenFst::StateId getFinalState () const
OpenFst::StateId getUnigramState () const
void renormalizeWeights (OpenFst::StateId s)
Private Attributes
bool renormalize_
Static Private Attributes
static const Core::ParameterFloat paramWeight
static const Core::ParameterStringVector paramNonWordLemmas
static const Core::ParameterBool paramAllStates
static const Core::ParameterBool paramInitialState
static const Core::ParameterBool paramFinalState
static const Core::ParameterBool paramUnigramState
static const Core::ParameterBool paramRenormalize
Additional Inherited Members
Public Types inherited from Search::Wfst::Builder::Operation
typedef Automaton * AutomatonRef
Protected Types inherited from Search::Wfst::Builder::OutputTypeDependent
enum OutputType { outputLemmaPronunciations, outputLemmas, outputSyntacticTokens }
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Attributes inherited from Search::Wfst::Builder::SleeveOperation
AutomatonRef input_
Protected Attributes inherited from Search::Wfst::Builder::Operation
Resources & resources_
Core::XmlChannel timerChannel_
Core::Timer timer_
Static Protected Attributes inherited from Search::Wfst::Builder::OutputTypeDependent
static const Core::ParameterChoice paramOutputType
static const Core::Choice choiceOutputType
Detailed Description
adds non-word tokens (silence/noise) to the grammar transducer.
loop arcs are added either to all states (parmAllStates == true), to the initial state, to the final state (assuming only one final state), or to the unigram state.
Definition at line 242 of file CreateOperations.hh.
Member Function Documentation
virtual u32 Search::Wfst::Builder::AddNonWordTokens::nInputAutomata () const inline virtual
number of automata required as input
Reimplemented from Search::Wfst::Builder::SleeveOperation.
Definition at line 254 of file CreateOperations.hh.
References Search::Wfst::Builder::SleeveOperation::nInputAutomata(), and Search::Wfst::Builder::BuildGrammar::process().
Operation::AutomatonRef AddNonWordTokens::process () protected virtual
do the actual processing
Implements Search::Wfst::Builder::Operation.
Definition at line 530 of file CreateOperations.cc.
References Core::Component::log().
The documentation for this class was generated from the following files:
CreateOperations.hh
CreateOperations.cc