Sprint: Bliss::Segment Class Reference
Bliss::Segment Class Reference
General segment of a Recording.
#include <CorpusDescription.hh>
Public Types
enum Type { typeSpeech, typeOther, nTypes }
Public Member Functions
Segment (Type, Recording *)
Recording * recording () const
void setRecording (Recording *r)
Recording * parent () const
Type type () const
void setType (Type t)
Time start () const
Start time in seconds from begin of recording.
void setStart (Time s)
Time end () const
End time in seconds from begin of recording.
void setEnd (Time e)
TrackId track () const
Track number of this segment.
void setTrack (TrackId track)
const AcousticCondition * condition () const
Acoustic condition of this segment.
void setCondition (const AcousticCondition *condition)
virtual void accept (SegmentVisitor *)
Have this segment processed by a SegmentVisitor.
Public Member Functions inherited from Bliss::ParentEntity
bool isNameReserved (const std::string &n) const
void reserveName (const std::string &n)
Public Member Functions inherited from Bliss::NamedCorpusEntity
ParentEntity * parent () const
void setParent (ParentEntity *_parent)
const std::string & name () const
std::string fullName () const
void setName (const std::string &n)
bool isAnonymous () const
Static Public Attributes
static const char * typeId [nTypes]
Private Types
typedef ParentEntity Precursor
Private Attributes
Recording * recording_
Type type_
Time start_
Time end_
TrackId track_
const AcousticCondition * condition_
Friends
class CorpusDescriptionParser
Additional Inherited Members
Protected Member Functions inherited from Bliss::ParentEntity
ParentEntity (ParentEntity *_parent=0)
Protected Member Functions inherited from Bliss::NamedCorpusEntity
NamedCorpusEntity (ParentEntity *_parent=0)
Detailed Description
General segment of a Recording.
Each instance corresponds to a <segment> element.
See also
CorpusDescription
Bliss documentation
Definition at line 313 of file CorpusDescription.hh.
Member Function Documentation
void Segment::accept (SegmentVisitor * v) virtual
Have this segment processed by a SegmentVisitor.
(This is an application of the Visitor pattern, in order to avoid type-information and downcasts.)
Reimplemented in Bliss::SpeechSegment.
Definition at line 137 of file CorpusDescription.cc.
References Bliss::SegmentVisitor::visitSegment().
Referenced by Bliss::SegmentOrderingVisitor::leaveCorpus().
const AcousticCondition* Bliss::Segment::condition () const inline
Acoustic condition of this segment.
Returns
Condition of this segment, or 0 if no condition is specified in the corpus description.
See also
AcousticCondition
Definition at line 384 of file CorpusDescription.hh.
Referenced by Bliss::ProgressReportingVisitorAdaptor::leaveRecording(), Bliss::CorpusConditionStatisticsVisitor::visitSegment(), and TestCorpusVisitor::visitSpeechSegment().
Time Bliss::Segment::end () const inline
End time in seconds from begin of recording.
Definition at line 363 of file CorpusDescription.hh.
Referenced by Bliss::SegmentOrderingVisitor::enterCorpus(), Speech::DataSource::initialize(), Bliss::ProgressReportingVisitorAdaptor::leaveRecording(), Bliss::CorpusSizeStatisticsVisitor::visitSegment(), Bliss::CorpusSizeStatisticsVisitor::visitSpeechSegment(), and Bliss::CorpusSpeakerStatisticsVisitor::visitSpeechSegment().
Time Bliss::Segment::start () const inline
Start time in seconds from begin of recording.
Definition at line 355 of file CorpusDescription.hh.
Referenced by Bliss::SegmentOrderingVisitor::enterCorpus(), Speech::DataSource::initialize(), Bliss::ProgressReportingVisitorAdaptor::leaveRecording(), Bliss::CorpusSizeStatisticsVisitor::visitSegment(), Bliss::CorpusSizeStatisticsVisitor::visitSpeechSegment(), and Bliss::CorpusSpeakerStatisticsVisitor::visitSpeechSegment().
TrackId Bliss::Segment::track () const inline
Track number of this segment.
Definition at line 371 of file CorpusDescription.hh.
Referenced by Bliss::ProgressReportingVisitorAdaptor::leaveRecording().
Member Data Documentation
const char * Segment::typeId static
Initial value:
= {
        "speech",
        "other"}
Definition at line 321 of file CorpusDescription.hh.
The documentation for this class was generated from the following files:
CorpusDescription.hh
CorpusDescription.cc