Sprint: Aligner::WordLatticeBuilder::Converter Class Reference
Aligner::WordLatticeBuilder::Converter Class Reference
Classes
struct StateInfo
Public Member Functions
Converter (Fsa::ConstAutomatonRef allophoneToLemmaPronunciationTransducer, Am::ConstAllophoneStateAlphabetRef allophoneStateAlphabet)
Lattice::ConstWordLatticeRef build ()
Public Member Functions inherited from Ftl::DfsState< _Automaton >
DfsState (_ConstAutomatonRef f)
virtual void discoverState (_ConstStateRef sp)
Called upon first discovery of a state.
virtual void finishState (Fsa::StateId s)
Called after all subtrees starting at a previously discovered state have been processed.
virtual void exploreTreeArc (_ConstStateRef from, const _Arc &a)
Called upon discovery of a tree arc.
virtual void exploreNonTreeArc (_ConstStateRef from, const _Arc &a)
Called upon discovery of a non-tree arc.
virtual void finishArc (_ConstStateRef from, const _Arc &a)
Called after all subtrees starting at a previously explored arc have been processed.
virtual void finish ()
Called after all states reachable from the initial state have been processed.
Fsa::StateId maxStateId () const
Request the highest state id of the automaton.
Fsa::StateId size () const
Color color (Fsa::StateId s) const
Request the color of a state.
Fsa::StateId predecessor (Fsa::StateId s) const
Request the predecessor of a state.
void dfs (Core::ProgressIndicator *p=0)
Initiate searching the automaton.
void recursiveDfs (Core::ProgressIndicator *p=0)
Initiate searching the automaton.
Protected Member Functions
Fsa::State * getState (Fsa::StateId id)
void setCoarticulatedWordBoundary (Fsa::StateId s, TimeframeIndex time, Fsa::LabelId lastAllophone)
void exploreArc (Fsa::ConstStateRef fromState, const Fsa::Arc &a)
virtual void exploreTreeArc (Fsa::ConstStateRef from, const Fsa::Arc &a)
virtual void exploreNonTreeArc (Fsa::ConstStateRef from, const Fsa::Arc &a)
Private Types
typedef Fsa::DfsState Precursor
typedef Core::Vector< StateInfo > StateInfos
Private Attributes
Fsa::StaticAutomaton * t_
lattice acoustic fsa to build
Lattice::WordBoundaries * wordBoundaries_
word boundaries to build
Am::ConstAllophoneStateAlphabetRef allophoneStateAlphabet_
StateInfos stateInfos_
Additional Inherited Members
Public Types inherited from Ftl::DfsState< _Automaton >
typedef _Automaton::Arc _Arc
typedef _Automaton::State _State
typedef _Automaton::ConstStateRef _ConstStateRef
typedef _Automaton::ConstRef _ConstAutomatonRef
typedef Fsa::StateId Color
The possible colors of a state.
Static Public Attributes inherited from Ftl::DfsState< _Automaton >
static const Color White = 0xc0000000
static const Color Gray = 0x80000000
static const Color Black = 0x40000000
Protected Attributes inherited from Ftl::DfsState< _Automaton >
_ConstAutomatonRef fsa_
Core::Vector< Fsa::StateId > info_
Detailed Description
Definition at line 837 of file Search/Aligner.cc.
Member Function Documentation
Lattice::ConstWordLatticeRef Aligner::WordLatticeBuilder::Converter::build () inline
the following 2 lines are a workaround for the current Lattice::normalize procedure which produces correct new word boundaries only if all fsa states are accessed afterwards with 'Fsa::getState'
Definition at line 939 of file Search/Aligner.cc.
References Lattice::WordLattice::acousticFsa, Search::Aligner::WordLatticeBuilder::build(), build(), Fsa::drawDot(), Core::Component::error(), Core::Vector< T >::grow(), Aligner::WordLatticeBuilder::Converter::StateInfo::lastAllophone_, Fsa::multiply(), Core::ref(), require, Search::Aligner::WordLatticeBuilder::setModelTransducer(), Fsa::staticCopy(), Aligner::WordLatticeBuilder::Converter::StateInfo::time_, and Fsa::write().
Referenced by build().
Member Data Documentation
Fsa::StaticAutomaton* Aligner::WordLatticeBuilder::Converter::t_ private
lattice acoustic fsa to build
Definition at line 841 of file Search/Aligner.cc.
Lattice::WordBoundaries* Aligner::WordLatticeBuilder::Converter::wordBoundaries_ private
word boundaries to build
Definition at line 842 of file Search/Aligner.cc.
The documentation for this class was generated from the following file:
Search/Aligner.cc