Sprint: AdvancedTreeSearch::AcousticLookAhead Class Reference
AdvancedTreeSearch::AcousticLookAhead Class Reference
Classes
class AcousticLookAheadModel
struct ApplyNoLookahead
struct ApplyPreCachedLookAheadForId
struct CacheForTimeframe
Public Types
typedef Search::Score Score
Public Member Functions
AcousticLookAhead (const Core::Configuration &config, u32 checksum, bool load=true)
bool loaded () const
void initializeModelsFromNetwork (const Search::PersistentStateTree &network)
If loading failed,.
void initializeModels (EmissionSetCounter sets)
bool isEnabled () const
Whether acoustic look-ahead has been enabled through the configuration.
void startLookAhead (int timeframe, bool computeAll=false)
Has to be called at each timeframe, after the look-ahead feature vectors have been added, and before getLookAheadScore() is called for the nodes.
void getPreCachedLookAheadScores (Score *target, u32 index, u32 count) const
Search::Score getPreCachedLookAheadScore (u32 index)
void setDefaultModel (u32 defaultModel, u32 minSize=0)
Search::Score getPreCachedLookAheadScoreForId (u32 id) const
u32 getLookaheadId (u32 index)
Search::Score getCachedLookAheadScore (u32 index)
Search::Score getLookAheadScore (u32 index)
int length () const
Depth of the acoustic look-ahead (how many timeframes does it look into the future?) A matching number of features must be fed into the acoustic look-ahead before it can compute look-ahead scores.
void setLookAhead (std::vector< Mm::FeatureVector > lookahead)
void clear ()
Static Public Member Functions
static int getDepth (const Core::Configuration &config)
static Score getScale (const Core::Configuration &config)
static std::string getMixtureSetFilename (const Core::Configuration &config)
static bool isEnabled (const Core::Configuration &config)
Private Types
typedef std::vector< std::pair< int, Search::Score > > CacheVector
typedef Mm::SimdGaussDiagonalMaximumFeatureScorer::PreparedFeatureVector AcousticFeatureVector
Private Member Functions
void computeAllLookAheadScores ()
template<bool useAverage>
void computeAllLookAheadScoresInternal ()
void fillCacheForTimeframe (int currentTimeFrame_)
CacheForTimeframe & cacheForTimeframe (int timeframe)
Score getCachedScaledScore (int timeframe, u32 model)
const Core::Configuration & config () const
void getSuccessorMixtures (const Search::PersistentStateTree &network, Search::StateId state, std::set< Am::AcousticModel::EmissionIndex > &target, int depth, bool includeCurrent=false)
bool loadModels ()
void saveModels ()
std::string archiveEntry () const
u32 getCacheKeyForState (Search::StateId state)
Static Private Member Functions
static Score calculateDistance (const AcousticFeatureVector &mean1, const AcousticFeatureVector &mean2)
static Score calculateDistance (const Mm::SimdGaussDiagonalMaximumFeatureScorer::QuantizedType *mean1, const Mm::SimdGaussDiagonalMaximumFeatureScorer::QuantizedType *mean2, u32 dimension)
static Core::Configuration select (const Core::Configuration &config)
Private Attributes
f32 acousticLookAheadScale_
f32 splittingThreshold_
bool splitEmpty_
std::vector< AcousticLookAheadModel > acousticLookAheadModels_
AcousticFeatureVector means_
std::vector< u32 > modelForIndex_
std::vector< std::pair< AcousticFeatureVector, Mm::FeatureScorer::Scorer > > acousticLookAhead_
CacheVector currentLookAheadScores_
std::vector< Search::Score > preCachedLookAheadScores_
std::vector< CacheForTimeframe * > cachesForTimeframes_
Core::Ref< Mm::MixtureSet > mixtureSet_
Mm::SimdGaussDiagonalMaximumFeatureScorer * acousticLookAheadScorer_
Search::SearchSpace * ss_
s32 acousticLookaheadDepth_
s32 currentTimeFrame_
bool useAverage_
bool considerLabels_
s32 lookaheadModelCount_
s32 iterations_
bool multiplicity_
bool loaded_
u32 minCacheKey_
u32 nextCacheKey_
u32 checksum_
std::vector< u32 > cacheKeys_
Core::Configuration config_
bool includeCurrentStateModel_
f64 perDepthFactor_
Detailed Description
Definition at line 76 of file AcousticLookAhead.hh.
Member Function Documentation
void AcousticLookAhead::initializeModels (EmissionSetCounter sets)
Todo:
Introduce weights for the splits, try out the better models again
Todo:
Make this the only representation
Definition at line 431 of file AcousticLookAhead.cc.
References Core::Component::log(), Core::Application::us(), and verify.
void AcousticLookAhead::initializeModelsFromNetwork (const Search::PersistentStateTree & network)
If loading failed,.
Definition at line 414 of file AcousticLookAhead.cc.
References Search::HMMStateNetwork::stateCount().
Referenced by Search::SearchSpace::setAllowHmmSkips().
bool AdvancedTreeSearch::AcousticLookAhead::isEnabled () const inline
Whether acoustic look-ahead has been enabled through the configuration.
Definition at line 100 of file AcousticLookAhead.hh.
int AcousticLookAhead::length () const
Depth of the acoustic look-ahead (how many timeframes does it look into the future?) A matching number of features must be fed into the acoustic look-ahead before it can compute look-ahead scores.
Definition at line 619 of file AcousticLookAhead.cc.
References Search::HMMStateNetwork::state(), Search::HMMStateNetwork::stateCount(), Search::HMMState::stateDesc, and verify.
void AcousticLookAhead::startLookAhead (int timeframe, bool computeAll = false)
Has to be called at each timeframe, after the look-ahead feature vectors have been added, and before getLookAheadScore() is called for the nodes.
Parameters
computeAll If this is true, all look-ahead scores are computed immediately, and can be retrieved through getPreCachedLookAheadScore
Definition at line 699 of file AcousticLookAhead.cc.
References verify.
The documentation for this class was generated from the following files:
AcousticLookAhead.hh
AcousticLookAhead.cc