Sprint: Search::Wfst::ExpandingFsaSearch Class Reference
Search::Wfst::ExpandingFsaSearch Class Reference
A WFST-based decoder.
#include <ExpandingFsaSearch.hh>
Public Member Functions
ExpandingFsaSearch (const Core::Configuration &)
virtual Speech::ModelCombination::Mode modelCombinationNeeded () const
virtual bool setModelCombination (const Speech::ModelCombination &modelCombination)
virtual void setGrammar (Fsa::ConstAutomatonRef)
virtual void init ()
virtual void restart ()
virtual void setSegment (const std::string &name)
virtual void feed (const Mm::FeatureScorer::Scorer &)
virtual void getPartialSentence (Traceback &result)
Should return the longest fixed prefix of the final best sentence which has been been recognized since the last call to getPartialSentence.
virtual void getCurrentBestSentence (Traceback &result) const
Should return the whole currently best sentence.
virtual Core::Ref< const Search::LatticeAdaptor > getCurrentWordLattice () const
virtual void resetStatistics ()
virtual void logStatistics () const
Public Member Functions inherited from Search::SearchAlgorithm
SearchAlgorithm (const Core::Configuration &)
virtual void setSegment (Bliss::SpeechSegment const *segment)
virtual void getCurrentBestSentencePartial (Traceback &result) const
Should return the part of the current best sentence which has not yet been returned by getPartialSentence().
virtual Core::Ref< const LatticeAdaptor > getPartialWordLattice ()
virtual void setAllowHmmSkips (bool allow=true)
Allow HMM skips during decoding ? By default, HMM skips are allowed.
virtual u32 lookAheadLength ()
Length of acoustic look-ahead.
virtual void setLookAhead (const std::vector< Mm::FeatureVector > &)
Called before feed() with as many acoustic feature vectors from the future as returned by lookaheadLength().
virtual PruningRef describePruning ()
Returns a descriptor of the current pruning thresholds, which can be used to re-activate the current pruning thresholds using resetPruning.
virtual bool relaxPruning (f32 factor, f32 offset)
Relaxes the pruning. Returns false if relaxing failed, otherwise true.
virtual void resetPruning (PruningRef pruning)
Resets pruning according to the given descriptor.
virtual RecognitionContext setContext (RecognitionContext)
Set LM context to be prepended (prefix) or appended(suffix) to the search hypotheses, and the acoustic phoneme coarticulation to be used for startup.
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Private Member Functions
SearchSpaceBase * createSearchSpace ()
s32 silenceOutput () const
Private Attributes
Bliss::LexiconRef lexicon_
Core::XmlChannel statisticsChannel_
Core::XmlChannel memoryInfoChannel_
SearchSpaceBase * searchSpace_
bool createLattice_
OutputType outputType_
OpenFst::LabelMap * labelMap_
StateSequenceList * stateSequences_
Static Private Attributes
static const Core::Choice choiceNetworkType
static const Core::ParameterChoice paramNetworkType_
static const Core::Choice choiceOutputType
static const Core::ParameterChoice paramOutputType_
static const Core::Choice choiceWordEndType
static const Core::ParameterChoice paramWordEndType_
static const Core::ParameterString paramEmissionSequencesFile_
static const Core::ParameterString paramStateSequencesFile_
static const Core::ParameterFloat paramAcousticPruningThreshold_
static const Core::ParameterInt paramAcousticPruningLimit_
static const Core::ParameterInt paramAcousticPruningBins_
static const Core::ParameterBool paramInitialEpsilonPruning_
static const Core::ParameterBool paramEpsilonArcPruning_
static const Core::ParameterBool paramProspectivePruning_
static const Core::ParameterFloat paramLatticePruning_
static const Core::ParameterFloat paramWordEndPruning_
static const Core::ParameterBool paramMergeSilenceArcs_
static const Core::ParameterBool paramMergeEpsilonPaths_
static const Core::ParameterInt paramPurgeInterval
static const Core::ParameterBool paramCreateLattice
static const Core::ParameterFloat paramWeightScale
static const Core::ParameterBool paramAllowSkips
static const Core::ParameterString paramMapOutput
static const Core::ParameterBool paramNonWordOutput
static const Core::ParameterStringVector paramNonWordPhones
static const Core::ParameterBool paramHasNonWords
static const Core::ParameterBool paramIgnoreLastOutput
static const Core::ParameterBool paramDetailedStatistics
static const Core::Choice choiceLatticeType
static const Core::ParameterChoice paramLatticeType
Additional Inherited Members
Public Types inherited from Search::SearchAlgorithm
typedef Speech::Score Score
typedef Speech::TimeframeIndex TimeframeIndex
typedef Core::Ref< Pruning > PruningRef
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
A WFST-based decoder.
Supports dynamic expansion of HMM states (therefore "Expanding"). The WFST used as search network can be constructed statically or dynamically. This class serves as interface to the Speech::Recognizer object and handles the parameters. The main work is performed in SearchSpace.
Definition at line 41 of file ExpandingFsaSearch.hh.
Member Function Documentation
void ExpandingFsaSearch::getCurrentBestSentence (Traceback & result) const virtual
Should return the whole currently best sentence.
Implements Search::SearchAlgorithm.
Definition at line 239 of file ExpandingFsaSearch.cc.
References OpenFst::convertLabelFromFsa(), Core::Component::error(), Bliss::Token::id(), Core::Component::log(), Bliss::Lemma::nPronunciations(), Bliss::Lemma::pronunciations(), Core::ref(), require, and verify.
void ExpandingFsaSearch::getPartialSentence (Traceback & result) virtual
Should return the longest fixed prefix of the final best sentence which has been been recognized since the last call to getPartialSentence.
Optional: Only required for online recognition
Reimplemented from Search::SearchAlgorithm.
Definition at line 236 of file ExpandingFsaSearch.cc.
The documentation for this class was generated from the following files:
ExpandingFsaSearch.hh
ExpandingFsaSearch.cc