Sprint: Signal::HistogramNormalizationNode Class Reference
Signal::HistogramNormalizationNode Class Reference
HistogramNormalizationNode.
#include <HistogramNormalization.hh>
Public Member Functions
HistogramNormalizationNode (const Core::Configuration &c)
virtual bool setParameter (const std::string &name, const std::string &value)
Set node specific parameter.
virtual bool configure ()
Performs static (independent of input data) configuration of node.
virtual Flow::PortId getInput (const std::string &name)
Ask for an input port.
virtual Flow::PortId getOutput (const std::string &name)
Ask for an output port.
virtual bool work (Flow::PortId p)
Processes some data.
Public Member Functions inherited from Flow::Node
Node (const Core::Configuration &c)
Public Member Functions inherited from Flow::AbstractNode
AbstractNode (const Core::Configuration &c)
virtual void Run ()
void setThreaded (bool threaded=true)
void setThreaded (const std::string &threaded)
bool isThreaded () const
virtual bool addParameter (const std::string &name, const Core::StringExpression &value)
addParameter adds a parameter to the node Constant parameters are simply delegated to setParameter, parameters dependent on network parameters are stored in parameters_.
virtual ssize_t getRemainingDataLen (PortId out)
Returns the amount of remaining data items.
void addUnresolvedParameter (const std::string &key, const std::string &value)
Functions for saving and getting unresolved parameters.
const UnresolvedAttributes & unresolvedAttributes () const
bool operator< (const AbstractNode &n) const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Signal::HistogramNormalization
void apply (const std::vector< Value > &in, std::vector< Value > &out)
void setTrainingHistograms (const std::vector< Histogram< Value >> &trainingHistograms, Probability probabilityBucketSize)
void setTrainingHistograms (const std::vector< HistogramVector< Value >> &trainingHistograms, const std::vector< Value > &scales, Probability probabilityBucketSize)
size_t nTrainingHistograms () const
void setTestHistograms (const std::vector< Histogram< Value >> &testHistograms)
size_t nTestHistograms () const
Static Public Member Functions
static std::string filterName ()
Static Public Member Functions inherited from Signal::HistogramNormalization
static bool areScalesWellDefined (const std::vector< HistogramWeight > &scales)
static bool areScalesNormalized (const std::vector< HistogramWeight > &scales)
static void normalizeScales (std::vector< HistogramWeight > &scales)
Inserts a scale at the beginning, which makes the sum of scales to be zero.
Private Types
typedef HistogramNormalization::Probability Probability
typedef HistogramNormalization::Value Value
typedef Core::ObjectCache< Core::MruObjectCacheList< std::string, HistogramVector< Value >, Core::StringHash, Core::StringEquality > > HistogramCache
Private Member Functions
void init (size_t featureDimension)
void reset ()
void setProbabilityBucketSize (Probability r)
void setTrainingHistogramFilenames (const std::vector< std::string > &n)
void loadTrainingHistograms (size_t featureDimension)
bool updateTrainingHistograms ()
Configures the normalization algorithm with new training histograms scales.
void setTestHistograms (const std::string &corpusKey)
bool updateScales (const Flow::Timestamp &timestamp)
Histogram scale ports are read if necessary.
Private Attributes
Flow::PortId firstScalePortId_
Probability probabilityBucketSize_
std::vector< std::string > trainingHistogramFilenames_
std::vector< HistogramVector< Value > > trainingHistograms_
std::vector< Flow::DataAdaptor< HistogramWeight > > histogramScales_
HistogramCache testHistograms_
bool needInit_
Static Private Attributes
static const Core::ParameterFloat paramProbabilityBucketSize
static const Core::ParameterStringVector paramTrainingHistogramsFilenames
static const Core::ParameterString paramCorpusKey
static const std::string scalePortname_
Additional Inherited Members
Public Types inherited from Flow::AbstractNode
typedef std::map< std::string, std::string > UnresolvedAttributes
Public Types inherited from Signal::HistogramNormalization
typedef f32 Value
typedef Histogram< Value >::Probability Probability
typedef Histogram< Value >::Weight HistogramWeight
typedef LookupTable< Probability, Value > Cdf
typedef std::vector< Cdf > Cdfs
typedef LookupTable< Value, Probability > InverseCdf
typedef std::vector< InverseCdf > InverseCdfs
Static Public Attributes inherited from Flow::AbstractNode
static const Core::ParameterBool paramThreaded
static const Core::ParameterBool paramIgnoreUnknownParameters
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Flow::Node
virtual PortId connectInputPort (PortId, Link *)
Connect link to input port.
virtual void disconnectInputLink (Link *)
virtual PortId connectOutputPort (PortId, Link *)
virtual void disconnectOutputLink (Link *)
PortId addInput (PortId in=IllegalPortId)
Create an input port.
PortId addInputs (u32 nPorts)
Create several input ports.
virtual PortId nInputs () const
Link * getInputLink (PortId in) const
virtual PortId inputConnected (PortId in) const
bool validInputPort (PortId in) const
PortId addOutput (PortId out=IllegalPortId)
Add an output port.
PortId addOutputs (u32 nPorts)
Create several output ports.
virtual PortId nOutputs () const
bool validOutputPort (PortId out) const
virtual u32 nOutputLinks (PortId out) const
Number of link connceted to an output port.
bool configureDatatype (Core::Ref< const Attributes > a, const Datatype *d)
template<class T >
bool getData (PortId in, DataPtr< T > &d)
Fetch data packet from input port.
virtual bool putData (PortId out, Data *d)
Send data packet on output port.
bool putEos (PortId out)
Send end-of-stream on output port.
bool putOod (PortId out)
Send out-of-data on output port.
Core::Ref< const Attributes > getInputAttributes (PortId in)
Retrieve attribute set from input port.
void getInputAttributes (PortId, Attributes &)
bool putOutputAttributes (PortId out, Core::Ref< const Attributes > a)
Put attribute set on output port.
void eraseOutputAttributes ()
Erases attributes of all output links recursively.
Protected Member Functions inherited from Flow::AbstractNode
template<class T >
bool getData (Link *l, DataPtr< T > &d)
Fetch data packet from the "from" port of link.
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
HistogramNormalizationNode.
Definition at line 71 of file HistogramNormalization.hh.
Member Function Documentation
bool HistogramNormalizationNode::configure () virtual
Performs static (independent of input data) configuration of node.
Configure is called if one of the output attributes is not available. Override this function to evaluate all input attributes and pass them on to successor nodes. The default implementation simply forwards the merged attributes from all input links to all outputs. Note: -we assume no dead inputs here. -This function is the safest point to reset the algorithms used by the node. The alternative would be to reset the algorithms when a non-data object has been recieved. This solution can lead easily to unintended behaviour, since it is not garatinteed at all that every node receives for example a EOS object!
Reimplemented from Flow::Node.
Definition at line 143 of file HistogramNormalization.cc.
Flow::PortId HistogramNormalizationNode::getInput (const std::string &) virtual
Ask for an input port.
Implement this function to provide a mapping form names to port IDs. Consider using a Core::Choice. Remeber to create ports using addInput().
Returns
a valid port ID or IllegalPortId if there is to such port.
Reimplemented from Flow::Node.
Definition at line 162 of file HistogramNormalization.cc.
References Signal::HistogramNormalization::setTrainingHistograms(), and verify.
virtual Flow::PortId Signal::HistogramNormalizationNode::getOutput (const std::string &) inline virtual
Ask for an output port.
Implement this function to provide a mapping form names to port IDs. Consider using a Core::Choice. Remeber to create ports using addOutput().
Returns
a valid port ID or IllegalPortId if there is to such port.
Reimplemented from Flow::Node.
Definition at line 137 of file HistogramNormalization.hh.
bool HistogramNormalizationNode::setParameter (const std::string & name, const std::string & value) virtual
Set node specific parameter.
Implement this template function to handle parameters specific to your Node.
Parameters
name name of parameter
value new value for the parameter
Returns
true if successful, false if parameter name is not understood.
Reimplemented from Flow::AbstractNode.
Definition at line 131 of file HistogramNormalization.cc.
bool HistogramNormalizationNode::updateScales (const Flow::Timestamp & timestamp) private
Histogram scale ports are read if necessary.
Only those ports are read where the current histogram scale (
See also
histogramScales_) does not contain the timestamp. In this way the scales are synchornized to the main input stream.
Definition at line 238 of file HistogramNormalization.cc.
bool HistogramNormalizationNode::updateTrainingHistograms () private
Configures the normalization algorithm with new training histograms scales.
Definition at line 258 of file HistogramNormalization.cc.
References Signal::HistogramNormalization::areScalesNormalized(), Signal::HistogramNormalization::areScalesWellDefined(), Signal::HistogramNormalization::normalizeScales(), Signal::HistogramNormalization::setTrainingHistograms(), and verify.
bool HistogramNormalizationNode::work (Flow::PortId out) virtual
Processes some data.
Implement this function to do whatever your node is supposed to. You are required to produce at least one packet of data on the specified output out. You may send more packets, also to other outputs.
Returns
true on success, false on end-of-file or error. The idiom is:
return putData(out, d);
Implements Flow::Node.
Definition at line 222 of file HistogramNormalization.cc.
The documentation for this class was generated from the following files:
HistogramNormalization.hh
HistogramNormalization.cc