Sprint: Lm::Module_ Class Reference
Lm::Module_ Class Reference
Public Member Functions
Core::Ref< LanguageModel > createLanguageModel (const Core::Configuration &, Bliss::LexiconRef)
Creates and initializes a LanguageModel as configured.
Core::Ref< ScaledLanguageModel > createScaledLanguageModel (const Core::Configuration &, Core::Ref< LanguageModel >)
Creates a scaled language model from.
Core::Ref< ScaledLanguageModel > createScaledLanguageModel (const Core::Configuration &c, Bliss::LexiconRef l)
Creates a scaled language model as configured.
Static Private Attributes
static const Core::Choice lmTypeChoice
static const Core::ParameterChoice lmTypeParam
Detailed Description
Definition at line 28 of file Lm/Module.hh.
Member Function Documentation
Core::Ref< LanguageModel > Module_::createLanguageModel (const Core::Configuration & c, Bliss::LexiconRef l)
Creates and initializes a LanguageModel as configured.
Returns
a newly created instance of LanguageModel or a void reference if an error occured.
Definition at line 73 of file Lm/Module.cc.
References Core::Component::criticalError(), Core::Component::hasFatalErrors(), Lm::LanguageModel::init(), Core::ref(), Core::Ref< T >::reset(), and Core::Application::us().
Referenced by createScaledLanguageModel().
Core::Ref< ScaledLanguageModel > Module_::createScaledLanguageModel (const Core::Configuration & c, Core::Ref< LanguageModel > languageModel)
Creates a scaled language model from.
Parameters
languageModel.
Returns
a valid reference to the newly created instance of ScaledLanguageModel or an invalid reference if an error occured.
Definition at line 106 of file Lm/Module.cc.
References defect.
Referenced by createScaledLanguageModel().
Core::Ref<ScaledLanguageModel> Lm::Module_::createScaledLanguageModel (const Core::Configuration & c, Bliss::LexiconRef l) inline
Creates a scaled language model as configured.
Returns
a valid reference to the newly created instance of ScaledLanguageModel or an invalid reference if an error occured.
Definition at line 63 of file Lm/Module.hh.
References createLanguageModel(), and createScaledLanguageModel().
The documentation for this class was generated from the following files:
Lm/Module.hh
Lm/Module.cc