Sprint: Signal::Convolution Class Reference
Signal::Convolution Class Reference
Convolution: Fast Fourier Transform based implementation of time doimain convolution.
#include <Convolution.hh>
Public Types
typedef f32 Data
Public Member Functions
void setResponse (const std::vector< Data > &response, u32 maximalSignalSize)
sets response function
void setSymmetricResponse (const std::vector< Data > &responsePositiveSide, u32 maximalSignalSize)
set positive side (including zeroth element) of a symmetric response function
void apply (const std::vector< Data > &response, std::vector< Data > &signal)
returns the convolution of signal with the response
void apply (std::vector< Data > &signal)
returns the convolution of signal with the response
u32 maximalSignalSize () const
void setOutputBegin (u32 begin)
result of convolution is delived for the interval [outputBegin_..outputEnd_)
u32 outputBegin () const
void setOutputEnd (u32 end)
result of convolution is delived for the interval [outputBegin_..outputEnd_)
u32 outputEnd () const
Private Member Functions
u32 fourierTransformLength () const
minimum length which avoids wrap around
void copyResult (u32 signalSize, std::vector< Data > &output) const
Private Attributes
std::vector< Data > signalSpectrum_
u32 maximalSignalSize_
std::vector< Data > responseSpectrum_
u32 responseSize_
u32 outputBegin_
u32 outputEnd_
Detailed Description
Convolution: Fast Fourier Transform based implementation of time doimain convolution.
Definition at line 47 of file Convolution.hh.
Member Function Documentation
void Convolution::apply (const std::vector< Data > & response, std::vector< Data > & signal)
returns the convolution of signal with the response
Definition at line 92 of file Convolution.cc.
Referenced by fourierTransformLength().
void Convolution::apply (std::vector< Data > & signal)
returns the convolution of signal with the response
Definition at line 57 of file Convolution.cc.
References defect, Signal::FastFourierTransform::length(), Signal::FastFourierTransform::outputSampleRate(), require, Math::transformAlternatingComplexToAlternatingComplex(), and verify.
u32 Signal::Convolution::fourierTransformLength () const inline private
minimum length which avoids wrap around
Definition at line 63 of file Convolution.hh.
References apply(), setResponse(), and setSymmetricResponse().
void Signal::Convolution::setOutputBegin (u32 begin) inline
result of convolution is delived for the interval [outputBegin_..outputEnd_)
Definition at line 91 of file Convolution.hh.
void Signal::Convolution::setOutputEnd (u32 end) inline
result of convolution is delived for the interval [outputBegin_..outputEnd_)
If outputEnd_ is set to u32::max then end of the output interval is set to signalSize + responseSize - 1.
Definition at line 103 of file Convolution.hh.
void Convolution::setResponse (const std::vector< Data > & response, u32 maximalSignalSize)
sets response function
Definition at line 29 of file Convolution.cc.
Referenced by fourierTransformLength().
void Convolution::setSymmetricResponse (const std::vector< Data > & responsePositiveSide, u32 maximalSignalSize)
set positive side (including zeroth element) of a symmetric response function
remark: for symmetric responses, input signal needs to be extended only by half of the full response size.
Definition at line 38 of file Convolution.cc.
Referenced by fourierTransformLength().
The documentation for this class was generated from the following files:
Convolution.hh
Convolution.cc