Sprint: Math::Lapack::GenSymmetricDefiniteEigenProblem Class Reference
Math::Lapack::GenSymmetricDefiniteEigenProblem Class Reference
Wrapper for generalized symmetric positive definite eigenvalue problem.
#include <EigenvalueProblem.hh>
Public Member Functions
GenSymmetricDefiniteEigenProblem (const Core::Configuration &c)
virtual bool solveSymmetric (const Math::Matrix< ValueType > &a, const Math::Matrix< ValueType > &b, Math::Vector< ValueType > &eigenvalues, Math::Matrix< ValueType > &eigenvectors)
Interface function for generalized symmetric eigenvalue problem.
bool solve (const Math::Matrix< ValueType > &a, const Math::Matrix< ValueType > &b, Math::Vector< ValueType > &eigenvalues, Math::Matrix< ValueType > &eigenvectors)
Public Member Functions inherited from Math::GeneralizedEigenvalueProblem
GeneralizedEigenvalueProblem (const Core::Configuration &)
virtual bool solveSymmetric (const Matrix< ValueType > &a, Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)
Interface function for symmetric eigenvalue problem.
bool solveSymmetricAndFinalize (const Matrix< ValueType > &a, const Matrix< ValueType > &b, Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)
Solves the symmetric generalized eigenvalue problem and performs finalization of results.
bool finalizeEigenvaluesAndVectors (const Matrix< ValueType > &a, const Matrix< ValueType > &b, Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)
Performs final processing of eigenvalues and eigenvectors.
bool finalize (const Matrix< ValueType > &a, const Matrix< ValueType > &b, Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)
Performs final processing and verifications.
bool isCorrectSolution (const Matrix< ValueType > &a, const Matrix< ValueType > &b, const Vector< ValueType > &eigenvalues, const Matrix< ValueType > &eigenvectors)
Verifies if eigenvectors and eigenvalues satisfy A*X = Lambda*B*X.
Public Member Functions inherited from Math::EigenvalueProblem
EigenvalueProblem (const Core::Configuration &)
bool solveSymmetricAndFinalize (const Matrix< ValueType > &a, Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)
Solves the symmetric eigenvalue problem and performs finalization of results.
bool finalize (const Matrix< ValueType > &a, Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)
Performs final processing and verifications.
bool finalizeEigenvaluesAndVectors (const Matrix< ValueType > &a, Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)
Performs final processing of eigenvalues and eigenvectors.
bool isCorrectSolution (const Matrix< ValueType > &a, const Vector< ValueType > &eigenvalues, const Matrix< ValueType > &eigenvectors)
Verifies if eigenvectors and eigenvalues satisfy A*X = Lambda*B*X.
void sortEigenvalues (Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)
Sorts eigenvalues in descending order.
bool real (const Vector< std::complex< ValueType >> &, Vector< ValueType > &)
Extracts real part of the input vector.
bool real (const Matrix< std::complex< ValueType >> &, Matrix< ValueType > &)
Extracts real part of the input matrix.
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Math::Lapack::EigenvalueProblem
EigenvalueProblem (const Core::Configuration &)
Private Member Functions
bool solveWithExpertDriver (const Math::Matrix< ValueType > &a, const Math::Matrix< ValueType > &b, Math::Vector< ValueType > &eigenvalues, Math::Matrix< ValueType > &eigenvectors) const
bool dsygvx (Matrix< double > &a, Matrix< double > &b, int &nEigenvalues, Vector< double > &eigenvalues, Matrix< double > &eigenvectors) const
LAPACK driver function which solves the generalized symmetric definite eigenvalue problem.
bool isEigenvalueRangeValid () const
bool solveWithDivideAndConquerDriver (const Math::Matrix< ValueType > &a, const Math::Matrix< ValueType > &b, Math::Vector< ValueType > &eigenvalues, Math::Matrix< ValueType > &eigenvectors) const
bool dsygvd (Matrix< double > &a, Matrix< double > &b, Vector< double > &eigenvalues) const
LAPACK driver function which solves the generalized symmetric definite eigenvalue problem Eigenvectors are returned in a, eigenvalues in eigenvalues.
Additional Inherited Members
Public Types inherited from Math::EigenvalueProblem
enum Type { typeGeneral, typeSymmetric, typeSymmetricPositiveDefinite }
typedef f64 ValueType
Static Public Attributes inherited from Math::EigenvalueProblem
static const Core::Choice choiceType
static const Core::ParameterChoice paramType
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Types inherited from Math::Lapack::EigenvalueProblem
enum DriverType { driverExpert, driverRelativelyRobust, driverDivideAndConquer }
Different implementations types of the same algorithm -"expert" driver supports all features (e.g.
Protected Member Functions inherited from Math::EigenvalueProblem
bool areEqual (const Matrix< ValueType > &x, const Matrix< ValueType > &y)
bool normalizeDiagonal (const Matrix< ValueType > &a, Matrix< ValueType > &eigenvectors)
Eigenvectors are scaled so that eigenvector^T * A * eigenvector = I.
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Member Functions inherited from Math::Lapack::EigenvalueProblem
bool isEigenvalueRangeValid () const
char translateEigenvalueRange () const
double eigenvalueLowerBound () const
double eigenvalueUpperBound () const
DriverType driverType () const
bool shouldSupportEigenvectors () const
void supportEigenvectors (const Matrix< int, RowByRowStorage > &isuppz, Matrix< double > &eigenvectors) const
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Wrapper for generalized symmetric positive definite eigenvalue problem.
Definition at line 259 of file Lapack/EigenvalueProblem.hh.
Member Function Documentation
bool GenSymmetricDefiniteEigenProblem::dsygvd (Matrix< double > & a, Matrix< double > & b, Vector< double > & eigenvalues) const private
LAPACK driver function which solves the generalized symmetric definite eigenvalue problem Eigenvectors are returned in a, eigenvalues in eigenvalues.
A divide-and-conquer driver (name ending -GVD) solves the same problem as the simple driver. It is much faster than the simple driver for large matrices, but uses more workspace. The name divide-and-conquer refers to the underlying algorithm.
Definition at line 704 of file Lapack/EigenvalueProblem.cc.
References Core::Component::error(), and require.
bool GenSymmetricDefiniteEigenProblem::dsygvx (Matrix< double > & a, Matrix< double > & b, int & nEigenvalues, Vector< double > & eigenvalues, Matrix< double > & eigenvectors) const private
LAPACK driver function which solves the generalized symmetric definite eigenvalue problem.
This expert driver function can calculate a set of eigenvalues defined by (eigen-value-lower-bound..eigen-value-upper-bound]. Number of calculated eigenvalues is returned in nEigenvalues. Eigenvectors are returned in eigenvectors, eigenvalues in eigenvalues.
Definition at line 635 of file Lapack/EigenvalueProblem.cc.
References Math::copy(), Core::Component::error(), and require.
virtual bool Math::Lapack::GenSymmetricDefiniteEigenProblem::solveSymmetric (const Math::Matrix< ValueType > & a, const Math::Matrix< ValueType > & b, Math::Vector< ValueType > & eigenvalues, Math::Matrix< ValueType > & eigenvectors) inline virtual
Interface function for generalized symmetric eigenvalue problem.
Implements Math::GeneralizedEigenvalueProblem.
Definition at line 296 of file Lapack/EigenvalueProblem.hh.
The documentation for this class was generated from the following files:
Lapack/EigenvalueProblem.hh
Lapack/EigenvalueProblem.cc