Sprint: Search::Wfst::StateSequenceBuilder Class Reference
Search::Wfst::StateSequenceBuilder Class Reference
Create state sequences for the list of allophones.
#include <StateSequence.hh>
Public Types
typedef std::vector< std::list< Fsa::LabelId > > LabelToLabelsMap
Public Member Functions
StateSequenceBuilder (const Core::Configuration &c, Core::Ref< const Am::AcousticModel > model, Bliss::LexiconRef lexicon)
void setNumDisambiguators (u32 disambiguators)
void build ()
StateSequenceList * createStateSequenceList () const
void relabelTransducer (FstLib::MutableFst< OpenFst::Arc > *f) const
relabels the input symbols of f from allophone indexes to state sequence indexes.
OpenFst::SymbolTable * createSymbols () const
creates a symbol table with a textual representation of the tied allophones
const LabelToLabelsMap & tiedAllophones () const
OpenFst::VectorFst * createStateSequenceToEmissionTransducer () const
creates a transducer which rewrites sequences of emission indexes to a sequence of state sequence indexes.
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Member Functions
static bool isFsaDisambiguator (Fsa::LabelId label)
static bool isDisambiguator (OpenFst::Label label)
Protected Member Functions
void addToMap (Fsa::LabelId allophone, Fsa::LabelId label)
void addNonWordsToList (StateSequenceList *list) const
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes
Core::Ref< const Am::AcousticModel > am_
Bliss::LexiconRef lexicon_
u32 nDisambiguators_
AllophoneToAlloponeStateSequenceMap * map_
LabelToLabelsMap labelToAllophones_
std::vector< Fsa::LabelId > allophoneToLabel_
bool addNonWords_
NonWordTokens * nonWordTokens_
Protected Attributes inherited from Core::Configurable
Configuration config
Static Private Attributes
static const Core::ParameterBool paramRemoveDisambiguators
static const Core::ParameterBool paramTiedAllophones
static const Core::ParameterBool paramIgnoreFlags
static const Core::ParameterBool paramAddNonWords
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Detailed Description
Create state sequences for the list of allophones.
Definition at line 263 of file StateSequence.hh.
Member Function Documentation
OpenFst::VectorFst* Search::Wfst::StateSequenceBuilder::createStateSequenceToEmissionTransducer () const
creates a transducer which rewrites sequences of emission indexes to a sequence of state sequence indexes.
input: state sequence index output: emission index (mixture set id)
OpenFst::SymbolTable * Search::Wfst::StateSequenceBuilder::createSymbols () const
creates a symbol table with a textual representation of the tied allophones
Definition at line 312 of file StateSequence.cc.
References OpenFst::convertLabelFromFsa(), OpenFst::convertLabelToFsa(), Core::Component::error(), Bliss::Token::id(), Bliss::Pronunciation::length(), Core::Component::log(), Bliss::Pronunciation::phonemes(), Bliss::Lemma::pronunciations(), Core::split(), Core::stripWhitespace(), Am::AllophoneAlphabet::symbol(), and verify.
void Search::Wfst::StateSequenceBuilder::relabelTransducer (FstLib::MutableFst< OpenFst::Arc > * f) const
relabels the input symbols of f from allophone indexes to state sequence indexes.
also changes the input symbol table.
Definition at line 290 of file StateSequence.cc.
References OpenFst::convertLabelFromFsa().
The documentation for this class was generated from the following files:
StateSequence.hh
StateSequence.cc