Sprint: Core::BuildDelegation< T > Class Template Reference
Core::BuildDelegation< T > Class Template Reference
Public Types
typedef Delegation< const T & > ParsedDelegation
typedef Delegation< T * > CreatedDelegation
typedef ParsedDelegation::Target ParsedHandler
typedef CreatedDelegation::Target CreatedHandler
Public Member Functions
void setParsedHandler (ParsedHandler *handler)
template<class HandlerClass >
void setParsedHandler (HandlerClass &handler, void(HandlerClass::*deleg)(const T &))
void resetParsedHandler ()
void setCreatedHandler (CreatedHandler *handler)
template<class HandlerClass >
void setCreatedHandler (HandlerClass &handler, void(HandlerClass::*deleg)(T *))
void resetCreatedHandler ()
Protected Member Functions
void delegate (T *t)
Calls first parsed handler and then created handler.
void delegateOrDelete (T *t)
Calls first parsed handler and then created handler; if no created handler exists, t is deleted.
T * delegateAndCreate (T *t)
Calls first parsed handler and then created handler; return t if no created handler exists, else return a newly created instance of T .
bool delegateParsed (const T &t)
Calls parsed handler.
bool delegateCreated (T *t)
Calls created handler.
Protected Member Functions inherited from Core::Delegation< const T & >
void set (Target *target)
void set (TargetClass &tc, void(TargetClass::*tm)(const T &))
void reset ()
bool hasTarget ()
void delegate (const T &t)
Protected Member Functions inherited from Core::Delegation< T * >
void set (Target *target)
void set (TargetClass &tc, void(TargetClass::*tm)(T *))
void reset ()
bool hasTarget ()
void delegate (T *t)
Detailed Description
template<typename T>
class Core::BuildDelegation< T >
Definition at line 27 of file XmlBuilder2.hh.
Member Function Documentation
template<typename T> void Core::BuildDelegation< T >::delegate (T * t) protected
Calls first parsed handler and then created handler.
Definition at line 185 of file XmlBuilder2.hh.
Referenced by Cart::XmlPropertiesDefinitionBuilderElement::end(), Cart::XmlDecisionTreeBuilderElement::end(), Cart::XmlExampleListBuilderElement::end(), Cart::XmlExampleListMergerElement::end(), and Cart::XmlTrainingPlanBuilderElement::end().
template<typename T> T * Core::BuildDelegation< T >::delegateAndCreate (T * t) protected
Calls first parsed handler and then created handler; return t if no created handler exists, else return a newly created instance of T .
Definition at line 203 of file XmlBuilder2.hh.
Referenced by Cart::XmlIndexedStringBuilderElement::end(), and XmlBuilder2::XmlDataOnlyBuilderElement< T, Converter >::end().
template<typename T> bool Core::BuildDelegation< T >::delegateCreated (T * t) protected
Calls created handler.
Definition at line 227 of file XmlBuilder2.hh.
template<typename T> void Core::BuildDelegation< T >::delegateOrDelete (T * t) protected
Calls first parsed handler and then created handler; if no created handler exists, t is deleted.
Definition at line 193 of file XmlBuilder2.hh.
Referenced by Cart::XmlQuestionRefListBuilderElement::end(), Cart::XmlTrainingInformationBuilderElement::end(), Cart::XmlBinaryTreeRootBuilderElement::end(), Cart::XmlPropertiesBuilderElement::end(), Cart::XmlFloatBoxBuilderElement::end(), and Cart::XmlStepBuilderElement::end().
template<typename T> bool Core::BuildDelegation< T >::delegateParsed (const T & t) protected
Calls parsed handler.
Definition at line 217 of file XmlBuilder2.hh.
Referenced by XmlBuilder2::XmlDataOnlyBuilderElement< std::string, StringConversion< std::string > >::end(), and XmlBuilder2::XmlChoiceBuilderElement::end().
The documentation for this class was generated from the following file:
XmlBuilder2.hh