Sprint: Search::StaticSearchAutomaton Class Reference
Search::StaticSearchAutomaton Class Reference
Public Types
using Precursor = Core::Component
Public Member Functions
StaticSearchAutomaton (Core::Configuration config, Core::Ref< const Am::AcousticModel > acousticModel, Bliss::LexiconRef lexicon)
void buildNetwork ()
void buildDepths (bool onlyFromRoot=false)
void clearDepths ()
int fillStateDepths (Search::StateId state, int depth)
int findStateDepth (Search::StateId state)
int stateDepth (StateId idx)
void buildLabelDistances ()
void buildBatches ()
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Attributes
const u32 hmmLength
HMM length of a common phoneme.
bool minimized
PersistentStateTree network
Static representation of the search network:
std::vector< int > secondOrderEdgeSuccessorBatches
std::vector< u32 > quickLabelBatches
std::vector< s32 > slowLabelBatches
std::vector< int > singleLabels
std::vector< std::pair< u32, u32 > > lookAheadIds
std::vector< std::pair< u32, u32 > > lookAheadIdAndHash
std::vector< int > stateDepths
std::vector< int > invertedStateDepths
std::vector< unsigned char > truncatedInvertedStateDepths
std::vector< unsigned char > truncatedStateDepths
std::vector< unsigned > labelDistance
PrefixFilter * prefixFilter
Optional filter which allows limiting the search space to a certain word sequence prefix.
Private Attributes
Core::Ref< const Am::AcousticModel > acousticModel_
Bliss::LexiconRef lexicon_
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Definition at line 49 of file AdvancedTreeSearch/SearchSpace.hh.
Member Function Documentation
void Search::StaticSearchAutomaton::buildBatches ()
TODO: Use bitmask instead of label-batches
Definition at line 579 of file AdvancedTreeSearch/SearchSpace.cc.
References Search::HMMStateNetwork::batchSuccessorsSimple(), Search::PersistentStateTree::dumpDotGraph(), hmmLength, Core::Component::log(), network, Search::PersistentStateTree::removeOutputs(), Search::HMMStateNetwork::state(), Search::HMMStateNetwork::stateCount(), Search::HMMState::successors, and verify.
Referenced by Search::SearchSpace::setAllowHmmSkips().
void Search::StaticSearchAutomaton::buildNetwork ()
Todo:
Track the TreeBuilder configuration in transformation if minimizedTree
Definition at line 389 of file AdvancedTreeSearch/SearchSpace.cc.
References Search::PersistentStateTree::build(), Search::PersistentStateTree::cleanup(), fillStateDepths(), Core::Component::log(), network, Search::PersistentStateTree::read(), Search::HMMStateNetwork::stateCount(), verify, and Search::PersistentStateTree::write().
Referenced by Search::SearchSpace::setAllowHmmSkips().
int Search::StaticSearchAutomaton::fillStateDepths (Search::StateId state, int depth)
Todo:
Find out why this happens on some languages
Definition at line 484 of file AdvancedTreeSearch/SearchSpace.cc.
References network, Search::HMMStateNetwork::state(), Search::HMMStateNetwork::stateCount(), and verify.
Referenced by buildNetwork().
Member Data Documentation
const u32 Search::StaticSearchAutomaton::hmmLength
HMM length of a common phoneme.
Definition at line 54 of file AdvancedTreeSearch/SearchSpace.hh.
Referenced by buildBatches(), Search::SearchSpace::SearchSpace(), and Search::SearchSpace::setAllowHmmSkips().
PersistentStateTree Search::StaticSearchAutomaton::network
Static representation of the search network:
Definition at line 58 of file AdvancedTreeSearch/SearchSpace.hh.
Referenced by buildBatches(), buildNetwork(), fillStateDepths(), Search::SearchSpace::optimizeSilenceInWordLattice(), and Search::SearchSpace::setAllowHmmSkips().
PrefixFilter* Search::StaticSearchAutomaton::prefixFilter
Optional filter which allows limiting the search space to a certain word sequence prefix.
Definition at line 88 of file AdvancedTreeSearch/SearchSpace.hh.
Referenced by Search::SearchSpace::filterStates(), and Search::SearchSpace::setAllowHmmSkips().
The documentation for this class was generated from the following files:
AdvancedTreeSearch/SearchSpace.hh
AdvancedTreeSearch/SearchSpace.cc