Sprint: Nn::NeuralNetwork< T > Class Template Reference
Nn::NeuralNetwork< T > Class Template Reference
Neural network implementation.
#include <NeuralNetwork.hh>
Public Member Functions
NeuralNetwork (const Core::Configuration &config)
u32 nLayers () const
u32 nFreeParameters () const
u32 nTrainableLayers () const
u32 highestTrainableLayerIndex () const
u32 lowestTrainableLayerIndex () const
s32 layerIndexToTrainableLayerIndex (u32 layerIndex) const
bool measuresTime () const
u32 activationsSize () const
void resizeActivations (u32 newSize)
NeuralNetworkLayer< T > & getLayer (u32 index)
Get the layer at index given.
const NeuralNetworkLayer< T > & getLayer (u32 index) const
u32 getLayerIdByName (const std::string &name)
NeuralNetworkLayer< T > & getTopLayer ()
const NeuralNetworkLayer< T > & getTopLayer () const
NnMatrix & getTopLayerOutput ()
NnMatrix & getLayerOutput (u32 layer)
std::vector< NnMatrix * > & getLayerInput (u32 layer)
void resetPreviousActivations ()
NeuralNetworkLayer< T > * popLayer ()
T l1norm (bool trainableLayersOnly=false) const
bool forward (std::vector< NnMatrix > &inputStreams)
bool forward (NnMatrix &inputStream)
bool forward (const std::vector< T > &inputStream)
void forwardLayers (u32 startLayer=0)
bool applySoftmax ()
void finalize ()
void initializeNetwork (u32 batchSize, const std::string &filename="")
void initializeNetwork (u32 batchSize, std::vector< u32 > streamSizes, const std::string &filename="")
void loadNetworkParameters ()
void saveNetworkParameters ()
void saveParameters (const std::string &filename)
save the network parameters from file
void loadParameters (const std::string &filename)
load the network parameters from file
void initComputation (bool sync=true) const
void finishComputation (bool sync=true) const
bool isComputing () const
bool isInitialized () const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Protected Types
typedef Types< T >::NnVector NnVector
typedef Types< T >::NnMatrix NnMatrix
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions
void setInputActivations (std::vector< NnMatrix > &inputStreams)
void setInputActivations (NnMatrix &inputStream)
void setInputActivations (const std::vector< T > &inputStream)
void buildTopology ()
bool createLayer (const std::string &layerName)
void connectActivations ()
connect activations container with the corresponding layer inputs/output
void resizeInputActivations (const std::vector< u32 > &streamSizes)
void setInputDimensions ()
void initParameters (std::string filename)
Initialize the parameters of the layers.
bool formatConnection (const std::string &connection, u32 &srcPort, std::string &targetLayerName, u32 &targetPort)
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes
const std::string parametersOld_
const std::string parametersNew_
filename of the old parameters (-> load)
const bool isRecurrent_
filename of the new parameters (-> save)
const bool measureTime_
is a recurrent network (not supported yet)
const bool parameterFileSymbolic_
measure computation time
bool needInit_
u32 nTrainableLayers_
s32 highestTrainableLayerIndex_
s32 lowestTrainableLayerIndex_
NetworkTopology< T > topology_
std::vector< NeuralNetworkLayer< T > * > layers_
contains layers in topological order, => network can be forwarded by iterating through the layers in topology_-vector
std::vector< s32 > layerIndexToTrainableLayerIndex_
layerIndexToTrainableLayerIndex_[layerIndex] = trainableLayerIndex , if trainable, -1, else
bool isComputing_
u32 batchSize_
is in computing state (GPU)
Activations< T > activations_
number of columns of activations = batch size, e.g.
Activations< T > previousActivations_
Protected Attributes inherited from Core::Configurable
Configuration config
Private Types
typedef Core::Component Precursor
Private Member Functions
bool formatConnectionPart (const std::string &connection, bool lhs, u32 &port, std::string &layerName)
std::string getTopologyDescription ()
Static Private Attributes
static const Core::ParameterString paramNetworkNetworkFilenameOld
static const Core::ParameterString paramNetworkNetworkFilenameNew
static const Core::ParameterStringVector paramNetworkLinks
static const Core::ParameterBool paramIsRecurrent
static const Core::ParameterBool paramMeasureTime
static const Core::ParameterBool paramParameterFileSymbolic
Detailed Description
template<class T>
class Nn::NeuralNetwork< T >
Neural network implementation.
Definition at line 33 of file BatchEstimator.hh.
Member Function Documentation
template<typename T > void NeuralNetwork< T >::connectActivations () protected
connect activations container with the corresponding layer inputs/output
Definition at line 208 of file NeuralNetwork.cc.
template<typename T > NeuralNetworkLayer< T > & NeuralNetwork< T >::getLayer (u32 index) inline
Get the layer at index given.
Definition at line 259 of file NeuralNetwork.cc.
References Core::form(), Core::Component::log(), and require.
Referenced by Nn::MeanNormalizedSgd< T >::checkForStatistics(), Nn::MeanNormalizedSgd< T >::estimate(), Nn::MeanNormalizedSgdL1Clipping< T >::estimate(), Nn::Adam< T >::estimate(), Nn::AdaGrad< T >::estimate(), Nn::AdaDelta< T >::estimate(), Nn::RmsProp< T >::estimate(), and Nn::Statistics< T >::initialize().
template<typename T > void NeuralNetwork< T >::initParameters (std::string filename) protected
Initialize the parameters of the layers.
Definition at line 242 of file NeuralNetwork.cc.
References Core::Component::log().
template<typename T > void NeuralNetwork< T >::loadParameters (const std::string & filename)
load the network parameters from file
Definition at line 542 of file NeuralNetwork.cc.
template<typename T > void NeuralNetwork< T >::saveParameters (const std::string & filename)
save the network parameters from file
Definition at line 575 of file NeuralNetwork.cc.
References Core::split(), and Core::str2vector().
Referenced by NnTrainer::main().
Member Data Documentation
template<class T> Activations<T> Nn::NeuralNetwork< T >::activations_ protected
number of columns of activations = batch size, e.g.
in training
Definition at line 75 of file NeuralNetwork.hh.
template<class T> u32 Nn::NeuralNetwork< T >::batchSize_ protected
is in computing state (GPU)
Definition at line 72 of file NeuralNetwork.hh.
template<class T> const bool Nn::NeuralNetwork< T >::isRecurrent_ protected
filename of the new parameters (-> save)
Definition at line 55 of file NeuralNetwork.hh.
template<class T> std::vector<s32> Nn::NeuralNetwork< T >::layerIndexToTrainableLayerIndex_ protected
layerIndexToTrainableLayerIndex_[layerIndex] = trainableLayerIndex , if trainable, -1, else
Definition at line 69 of file NeuralNetwork.hh.
template<class T> std::vector<NeuralNetworkLayer<T>*> Nn::NeuralNetwork< T >::layers_ protected
contains layers in topological order, => network can be forwarded by iterating through the layers in topology_-vector
Definition at line 67 of file NeuralNetwork.hh.
template<class T> const bool Nn::NeuralNetwork< T >::measureTime_ protected
is a recurrent network (not supported yet)
Definition at line 56 of file NeuralNetwork.hh.
template<class T> const bool Nn::NeuralNetwork< T >::parameterFileSymbolic_ protected
measure computation time
Definition at line 57 of file NeuralNetwork.hh.
template<class T> const std::string Nn::NeuralNetwork< T >::parametersNew_ protected
filename of the old parameters (-> load)
Definition at line 54 of file NeuralNetwork.hh.
The documentation for this class was generated from the following files:
BatchEstimator.hh
NeuralNetwork.hh
NeuralNetwork.cc