Sprint: Mm::Feature Class Reference
Mm::Feature Class Reference
Feature is container for objects comming from different feature stream at the same time.
#include <Feature.hh>
Classes
class Vector
Public Types
typedef std::vector< Core::Ref< const Vector > >::const_iterator Iterator
Public Member Functions
Feature (size_t nStreams=0)
Creates an empty feature with.
Feature (const Core::Ref< const Vector > &f)
Creates a feature with a single stream containing the feature vector.
Feature (const FeatureVector &f)
Creates a feature with a single stream containing the feature vector.
size_t add (const Core::Ref< const Vector > &v)
Creates a new stream with.
void add (size_t newIndex, const Core::Ref< const Vector > &v)
Creates a new stream at index.
void set (size_t streamIndex, const Core::Ref< const Vector > &v)
Changes value of the stream at index.
void set (const std::vector< size_t > &indices, const Core::Ref< const Vector > &v)
Changes value of the stream at indices.
void clear ()
bool operator== (const Feature &r) const
Core::Ref< const Vector > operator[] (size_t streamIndex) const
Core::Ref< const Vector > mainStream () const
Main stream is used in application working only with one stream.
Iterator begin () const
Iterator end () const
void setNumberOfStreams (size_t nStreams)
size_t nStreams () const
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Static Public Member Functions
static Core::Ref< const Vector > convert (const FeatureVector &f)
Private Attributes
std::vector< Core::Ref< const Vector > > streams_
Detailed Description
Feature is container for objects comming from different feature stream at the same time.
Remark: applications working on sinlge streams should use the "main stream" which is currently the first stream. Note: Currently it can contain only vectors.
Definition at line 32 of file Mm/Feature.hh.
Constructor & Destructor Documentation
Mm::Feature::Feature (size_t nStreams = 0) inline
Creates an empty feature with.
Parameters
nStreams streams
Definition at line 57 of file Mm/Feature.hh.
Mm::Feature::Feature (const Core::Ref< const Vector > & f) inline explicit
Creates a feature with a single stream containing the feature vector.
Parameters
f.
Definition at line 61 of file Mm/Feature.hh.
Mm::Feature::Feature (const FeatureVector & f) inline explicit
Creates a feature with a single stream containing the feature vector.
Parameters
f.
Definition at line 66 of file Mm/Feature.hh.
Member Function Documentation
size_t Mm::Feature::add (const Core::Ref< const Vector > & v) inline
Creates a new stream with.
Parameters
v
Returns
is the new stream index.
Definition at line 74 of file Mm/Feature.hh.
Referenced by Speech::Feature::take().
void Feature::add (size_t newIndex, const Core::Ref< const Vector > & v)
Creates a new stream at index.
Parameters
newIndex with
v
Definition at line 20 of file Mm/Feature.cc.
Core::Ref<const Vector> Mm::Feature::mainStream () const inline
Main stream is used in application working only with one stream.
For example: training, basic feature scorer, etc.
Definition at line 114 of file Mm/Feature.hh.
Referenced by Nn::PythonFeatureScorer::getScorer(), Nn::TrainerFeatureScorer::getScorer(), Mm::BatchFeatureScorerBase::getScorer(), Nn::PythonFeatureScorer::isBuffered(), Nn::TrainerFeatureScorer::isBuffered(), Speech::TextDependentScatterMatricesEstimator::processAlignedFeature(), Speech::FeatureAccumulator::processAlignedFeature(), Speech::TextDependentMixtureSetTrainer::processAlignedFeature(), Speech::TiedTextDependentMixtureSetTrainer::processAlignedFeature(), Speech::CovarianceEstimator::processFeature(), Speech::MeanEstimator::processFeature(), Speech::FeatureVectorExtractor::processFeature(), Speech::TextIndependentMixtureSetTrainer::processLabeledFeature(), and Speech::TextIndependentScatterMatricesEstimator::processLabeledFeature().
bool Mm::Feature::operator== (const Feature & r) const inline
Returns
is true if all streams are identical
Definition at line 99 of file Mm/Feature.hh.
Core::Ref<const Vector> Mm::Feature::operator[] (size_t streamIndex) const inline
Returns
is value of the stream
Parameters
streamIndex
Definition at line 107 of file Mm/Feature.hh.
void Mm::Feature::set (size_t streamIndex, const Core::Ref< const Vector > & v) inline
Changes value of the stream at index.
Parameters
newIndex to
v
Definition at line 83 of file Mm/Feature.hh.
Referenced by Speech::FeatureScorerNode::configure().
void Mm::Feature::set (const std::vector< size_t > & indices, const Core::Ref< const Vector > & v) inline
Changes value of the stream at indices.
Parameters
indices to
v
Definition at line 89 of file Mm/Feature.hh.
The documentation for this class was generated from the following files:
Mm/Feature.hh
Mm/Feature.cc