Sprint: Speech::CorpusProcessor Class Reference
Speech::CorpusProcessor Class Reference
CorpusProcessor base class for algorithms driven by a CorpusVisitor.
#include <CorpusProcessor.hh>
Public Member Functions
CorpusProcessor (const Core::Configuration &c)
virtual void signOn (CorpusVisitor &corpusVisitor)
Override this function to sign on to services of the corpus visitor.
virtual void enterCorpus (Bliss::Corpus *corpus)
virtual void leaveCorpus (Bliss::Corpus *corpus)
virtual void enterRecording (Bliss::Recording *recoding)
virtual void leaveRecording (Bliss::Recording *recoding)
virtual void enterSegment (Bliss::Segment *segment)
virtual void processSegment (Bliss::Segment *segment)
virtual void leaveSegment (Bliss::Segment *segment)
virtual void enterSpeechSegment (Bliss::SpeechSegment *)
virtual void processSpeechSegment (Bliss::SpeechSegment *segment)
virtual void leaveSpeechSegment (Bliss::SpeechSegment *)
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Protected Member Functions
void reportRealTime (Flow::Time)
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes
Core::XmlChannel channelTimer_
Core::Timer timer_
Protected Attributes inherited from Core::Configurable
Configuration config
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Detailed Description
CorpusProcessor base class for algorithms driven by a CorpusVisitor.
Output (XML format):
CPU time and real time factor (channel: real-time-factor)
Definition at line 32 of file Speech/CorpusProcessor.hh.
Member Function Documentation
void CorpusProcessor::signOn (CorpusVisitor & corpusVisitor) virtual
Override this function to sign on to services of the corpus visitor.
Note: call the signOn function of your predecessor.
Reimplemented in Speech::LatticeSetProcessorRoot, Nn::BufferedFeatureExtractor< T >, Nn::BufferedFeatureExtractor< FloatT >, Nn::BufferedFeatureExtractor< f32 >, Speech::OfflineRecognizer, Nn::BufferedAlignedFeatureProcessor< T >, Nn::BufferedAlignedFeatureProcessor< f32 >, Speech::NumeratorLatticeGenerator, Speech::LabelingFeatureExtractor, Speech::AligningFeatureExtractor, Speech::DataExtractor, Speech::HistogramEstimator, Speech::DelayedRecognizer, and Speech::SegmentwiseFeatureExtractor.
Definition at line 26 of file Speech/CorpusProcessor.cc.
Referenced by FeatureStatistics::main(), SpeechRecognizer::main(), ExtractionApplication::main(), NnTrainer::main(), AcousticModelTrainer::showMixtureSet(), Speech::AligningFeatureExtractor::signOn(), and Speech::LatticeSetProcessorRoot::signOn().
The documentation for this class was generated from the following files:
Speech/CorpusProcessor.hh
Speech/CorpusProcessor.cc