Sprint: Speech::AlignedFeatureProcessor Class Reference
Speech::AlignedFeatureProcessor Class Reference
AlignedFeatureProcessor is base class for algorithms processing aligned feature vectors.
#include <AlignedFeatureProcessor.hh>
Public Member Functions
AlignedFeatureProcessor (const Core::Configuration &c)
virtual void signOn (CorpusVisitor &corpusVisitor)
Override this function to sign on to services of the corpus visitor.
virtual void enterCorpus (Bliss::Corpus *)
Override this function to perform preparations before first segment is processed.
virtual void leaveCorpus (Bliss::Corpus *)
Override this function to perform post processing after the last segment is processed.
virtual void enterSegment (Bliss::Segment *)
Override this function to perform preparations before first aligned features arrive.
virtual void leaveSegment (Bliss::Segment *)
Override this function to perform post processing after the last aligned features of the segment.
virtual void enterSpeechSegment (Bliss::SpeechSegment *)
Override this function to perform preparations before first aligned features arrive.
virtual void leaveSpeechSegment (Bliss::SpeechSegment *)
Override this function to perform post processing after the last aligned features of the segment.
virtual void processAlignedFeature (Core::Ref< const Feature > f, Am::AllophoneStateIndex e)
Override this function to implement the processing of Viterbi-aligned feature vectors.
virtual void processAlignedFeature (Core::Ref< const Feature >, Am::AllophoneStateIndex, Mm::Weight)
Override this function to implement the processing of Baum-Welch-aligned feature vectors.
virtual void processAlignedFeature (Core::Ref< const Feature >, Am::AllophoneStateIndex, Mm::Weight, Mm::Weight)
Override this function to implement the processing of feature vectors with two weights.
virtual void setDataSource (Core::Ref< DataSource >)
Override this function to obtain the data source of corpus processor which produces the labels.
virtual void setFeatureDescription (const Mm::FeatureDescription &)
Override this function to achieve the attributes of the feature streams.
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
AlignedFeatureProcessor is base class for algorithms processing aligned feature vectors.
The AlignedFeatureProcessor is usually driven by Speech::AlignedFeatureExtractor.
Remark: an instance of this class can be used for dry runs since it does not have any abstract functions.
Definition at line 31 of file AlignedFeatureProcessor.hh.
Member Function Documentation
virtual void Speech::AlignedFeatureProcessor::enterCorpus (Bliss::Corpus *) inline virtual
Override this function to perform preparations before first segment is processed.
Definition at line 44 of file AlignedFeatureProcessor.hh.
virtual void Speech::AlignedFeatureProcessor::enterSegment (Bliss::Segment *) inline virtual
Override this function to perform preparations before first aligned features arrive.
Definition at line 50 of file AlignedFeatureProcessor.hh.
virtual void Speech::AlignedFeatureProcessor::enterSpeechSegment (Bliss::SpeechSegment *) inline virtual
Override this function to perform preparations before first aligned features arrive.
Reimplemented in Speech::FeatureScorer.
Definition at line 56 of file AlignedFeatureProcessor.hh.
virtual void Speech::AlignedFeatureProcessor::leaveCorpus (Bliss::Corpus *) inline virtual
Override this function to perform post processing after the last segment is processed.
Definition at line 47 of file AlignedFeatureProcessor.hh.
virtual void Speech::AlignedFeatureProcessor::leaveSegment (Bliss::Segment *) inline virtual
Override this function to perform post processing after the last aligned features of the segment.
Definition at line 53 of file AlignedFeatureProcessor.hh.
virtual void Speech::AlignedFeatureProcessor::leaveSpeechSegment (Bliss::SpeechSegment *) inline virtual
Override this function to perform post processing after the last aligned features of the segment.
Reimplemented in Speech::FeatureScorer.
Definition at line 59 of file AlignedFeatureProcessor.hh.
virtual void Speech::AlignedFeatureProcessor::processAlignedFeature (Core::Ref< const Feature > f, Am::AllophoneStateIndex e) inline virtual
Override this function to implement the processing of Viterbi-aligned feature vectors.
Reimplemented in Speech::TiedTextDependentMixtureSetTrainer, Speech::FeatureScorer, Nn::BufferedAlignedFeatureProcessor< T >, Nn::BufferedAlignedFeatureProcessor< f32 >, Speech::KeyedEstimator, Speech::TextDependentMixtureSetTrainer, Speech::FeatureAccumulator, Speech::AcousticModelTrainer, and Speech::TextDependentScatterMatricesEstimator.
Definition at line 63 of file AlignedFeatureProcessor.hh.
virtual void Speech::AlignedFeatureProcessor::processAlignedFeature (Core::Ref< const Feature > , Am::AllophoneStateIndex , Mm::Weight) inline virtual
Override this function to implement the processing of Baum-Welch-aligned feature vectors.
Reimplemented in Speech::TiedTextDependentMixtureSetTrainer, Nn::BufferedAlignedFeatureProcessor< T >, Nn::BufferedAlignedFeatureProcessor< f32 >, Speech::KeyedEstimator, Speech::TextDependentMixtureSetTrainer, Speech::FeatureAccumulator, Speech::AcousticModelTrainer, and Speech::TextDependentScatterMatricesEstimator.
Definition at line 67 of file AlignedFeatureProcessor.hh.
virtual void Speech::AlignedFeatureProcessor::processAlignedFeature (Core::Ref< const Feature > , Am::AllophoneStateIndex , Mm::Weight , Mm::Weight) inline virtual
Override this function to implement the processing of feature vectors with two weights.
Definition at line 71 of file AlignedFeatureProcessor.hh.
virtual void Speech::AlignedFeatureProcessor::setDataSource (Core::Ref< DataSource >) inline virtual
Override this function to obtain the data source of corpus processor which produces the labels.
Reimplemented in Speech::FeatureScorer.
Definition at line 76 of file AlignedFeatureProcessor.hh.
virtual void Speech::AlignedFeatureProcessor::setFeatureDescription (const Mm::FeatureDescription &) inline virtual
Override this function to achieve the attributes of the feature streams.
This function is called once before the first feature vector is processed.
Reimplemented in Speech::FeatureScorer, Speech::TiedTextDependentMixtureSetTrainer, Speech::KeyedEstimator, Speech::TextDependentMixtureSetTrainer, and Speech::TextDependentScatterMatricesEstimator.
Definition at line 81 of file AlignedFeatureProcessor.hh.
Referenced by Speech::TextDependentMixtureSetTrainer::setFeatureDescription(), and Speech::TiedTextDependentMixtureSetTrainer::setFeatureDescription().
virtual void Speech::AlignedFeatureProcessor::signOn (CorpusVisitor & corpusVisitor) inline virtual
Override this function to sign on to services of the corpus visitor.
Note: call the signOn function of your predecessor.
Reimplemented in Speech::FeatureScorer, Nn::BufferedAlignedFeatureProcessor< T >, Nn::BufferedAlignedFeatureProcessor< f32 >, Speech::KeyedEstimator, and Speech::AcousticModelTrainer.
Definition at line 40 of file AlignedFeatureProcessor.hh.
Referenced by Nn::BufferedAlignedFeatureProcessor< f32 >::signOn().
The documentation for this class was generated from the following file:
AlignedFeatureProcessor.hh