Sprint: Speech::DataSource Class Reference
Speech::DataSource Class Reference
Flow::Network handling several ports.
#include <DataSource.hh>
Public Member Functions
DataSource (const Core::Configuration &c, bool loadFromFile=true)
void initialize (Bliss::Segment *)
Initializes progress indication and statistics objects.
void finalize ()
Finalizes progress indication and statistics objects.
template<class T >
bool getData (Flow::PortId out, Flow::DataPtr< T > &d)
Pulls one data object from the network.
template<class T >
bool getData (Flow::DataPtr< T > &d)
Pulls one data object from the main port of the network.
template<class T >
bool getData (Flow::PortId out, std::vector< T > &d)
Pulls all the data object from the network.
bool getData (Flow::PortId, Core::Ref< Feature > &)
Pulls one object from the network and converts it into a Feature object.
virtual bool getData (Core::Ref< Feature > &f)
Pulls a feature from main port of the network.
virtual bool getData ()
Pulls data from main port of the network.
virtual bool convert (Flow::DataPtr< Flow::Timestamp > from, Core::Ref< Feature > &to)
Converts an arbitrary Timestamp derived object to a Feature object.
Flow::PortId mainPortId () const
const std::vector< size_t > & nFrames () const
Flow::Time realTime () const
void setProgressIndication (bool enabled)
Public Member Functions inherited from Flow::DataSource
DataSource (const Core::Configuration &c, bool loadFromFile=true)
template<class T >
bool getData (Flow::PortId out, Flow::DataPtr< T > &d)
Pulls one data object from the network.
template<class T >
bool getData (Flow::PortId out, std::vector< T > &d)
Pulls all the data object from the network.
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Public Member Functions inherited from Flow::Network
Network (const Core::Configuration &c, bool loadFromFile=true)
void buildFromString (const std::string &network)
Construct network from XML description string.
void buildFromFile (const std::string &filename)
Construct network from XML description file.
void setTypeName (const std::string &typeName)
const std::string & getTypeName () const
bool addNode (AbstractNode *node)
AbstractNode * getNode (const std::string &name)
bool addLink (const std::string &fromNodeName, const std::string &fromPortName, const std::string &toNodeName, const std::string &toPortName, u32 buffer=0)
void declareParameter (const std::string &name)
bool addParameterUse (AbstractNode *node, const std::string &name, const Core::StringExpression &value)
Register a node as user of a parameter.
bool addInput (const std::string &name)
virtual PortId getInput (const std::string &name)
Ask for an input port.
bool addOutput (const std::string &name)
virtual PortId getOutput (const std::string &name)
Ask for an output port.
const std::string & outputName (PortId out) const
void outputs (std::vector< std::pair< PortId, std::string >> &outputs) const
void activateOutput (PortId)
Prepares the output port for external usage.
virtual bool putData (PortId in, Data *d)
Put data on input port of network.
bool putEos (PortId out)
Send end-of-stream on output port.
bool putOod (PortId out)
Send out-of-data on output port.
Link * getPortLink (PortId out)
template<class T >
bool getData (PortId out, DataPtr< T > &d)
Fetch data from output port of network.
bool putAttributes (PortId, Core::Ref< const Attributes >)
Put attribute set on input node of network.
const std::string getAttribute (PortId out, const std::string &name)
Inquire an attribute on an output port of the network.
virtual bool setParameter (const std::string &name, const std::string &value)
Set node specific parameter.
virtual bool configure ()
Creates empy input attibutes for input ports without one an attribute.
virtual bool work (PortId in)
Repeats last non-data input on input port.
virtual ssize_t getRemainingDataLen (PortId out)
Returns the amount of remaining data items.
void reset ()
Resets all links and nodes.
void go ()
void setFilename (const std::string &f)
const std::string & filename () const
Public Member Functions inherited from Flow::AbstractNode
AbstractNode (const Core::Configuration &c)
virtual void Run ()
void setThreaded (bool threaded=true)
void setThreaded (const std::string &threaded)
bool isThreaded () const
virtual bool addParameter (const std::string &name, const Core::StringExpression &value)
addParameter adds a parameter to the node Constant parameters are simply delegated to setParameter, parameters dependent on network parameters are stored in parameters_.
virtual void eraseOutputAttributes ()
Erases attributes of all output links recursively over all successor nodes.
void addUnresolvedParameter (const std::string &key, const std::string &value)
Functions for saving and getting unresolved parameters.
const UnresolvedAttributes & unresolvedAttributes () const
bool operator< (const AbstractNode &n) const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Protected Types
typedef Flow::DataSource Precursor
Protected Types inherited from Flow::DataSource
typedef Network Precursor
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions
void updateProgressStatus (Flow::PortId, const Flow::DataPtr< Flow::Data > d)
Protected Member Functions inherited from Flow::Network
virtual PortId nInputs () const
virtual PortId inputConnected (PortId in) const
bool validInputPort (PortId in) const
virtual PortId nOutputs () const
virtual u32 nOutputLinks (PortId out) const
bool validOutputPort (PortId out) const
virtual PortId connectInputPort (PortId, Link *)
virtual void disconnectInputLink (Link *)
virtual PortId connectOutputPort (PortId, Link *)
virtual void disconnectOutputLink (Link *)
Protected Member Functions inherited from Flow::AbstractNode
template<class T >
bool getData (Link *l, DataPtr< T > &d)
Fetch data packet from the "from" port of link.
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes
Flow::PortId mainPortId_
Protected Attributes inherited from Core::Configurable
Configuration config
Private Member Functions
Flow::Time segmentDuration (Bliss::Segment *s)
Private Attributes
Flow::Time startTime_
Flow::Time endTime_
std::vector< size_t > nFrames_
Core::ProgressIndicator progressIndicator_
bool noProgressIndication_
bool pushSinks_
Static Private Attributes
static const Core::ParameterString paramMainStreamName
static const Core::ParameterBool paramNoProgressIndication
static const Core::ParameterBool paramPushSinks
Additional Inherited Members
Public Types inherited from Flow::AbstractNode
typedef std::map< std::string, std::string > UnresolvedAttributes
Static Public Attributes inherited from Flow::AbstractNode
static const Core::ParameterBool paramThreaded
static const Core::ParameterBool paramIgnoreUnknownParameters
Detailed Description
Flow::Network handling several ports.
Output is a sequence of Feature object assembled form the output sequence of the different output ports Remark: Output type of Flow::Network must be Flow::Vector<Mm::FeatureType> >
Definition at line 31 of file Speech/DataSource.hh.
Member Function Documentation
bool DataSource::convert (Flow::DataPtr< Flow::Timestamp > from, Core::Ref< Feature > & to) virtual
Converts an arbitrary Timestamp derived object to a Feature object.
Returns
is false if conversion fails. In this case error, messages are generated.
Definition at line 103 of file DataSource.cc.
References Core::Component::error(), Core::ref(), and Speech::Feature::take().
Referenced by getData().
void DataSource::finalize (void)
Finalizes progress indication and statistics objects.
Definition at line 68 of file DataSource.cc.
Referenced by Flf::IncrementalRecognizer::startRecognition().
template<class T > bool Speech::DataSource::getData (Flow::PortId out, Flow::DataPtr< T > & d)
Pulls one data object from the network.
Returns
is false if the port could not deliver an output object.
Definition at line 133 of file Speech/DataSource.hh.
template<class T > bool Speech::DataSource::getData (Flow::DataPtr< T > & d) inline
Pulls one data object from the main port of the network.
Returns
is false if the main port could not deliver an output object.
Definition at line 75 of file Speech/DataSource.hh.
References getData().
template<class T > bool Speech::DataSource::getData (Flow::PortId out, std::vector< T > & d)
Pulls all the data object from the network.
Returns
is false if the port could not deliver any output object.
Definition at line 142 of file Speech/DataSource.hh.
References getData().
bool DataSource::getData (Flow::PortId portId, Core::Ref< Feature > & feature)
Pulls one object from the network and converts it into a Feature object.
Returns
is false: -if the port could not deliver an output object, -if the conversion fails. The following network types are supported: -FlowVector<f32>, -Flow::PointerVector<Flow::Vector<f32> >.
Definition at line 94 of file DataSource.cc.
virtual bool Speech::DataSource::getData (Core::Ref< Feature > & f) inline virtual
Pulls a feature from main port of the network.
See also
bool getData(Flow::PortId, Core::Ref<Feature> &).
Definition at line 98 of file Speech/DataSource.hh.
References getData().
virtual bool Speech::DataSource::getData () inline virtual
Pulls data from main port of the network.
Returns
is false if no output could be delivered.
Definition at line 104 of file Speech/DataSource.hh.
References convert().
Referenced by getData().
void DataSource::initialize (Bliss::Segment * s)
Initializes progress indication and statistics objects.
Definition at line 45 of file DataSource.cc.
References Bliss::Segment::end(), and Bliss::Segment::start().
Referenced by Flf::IncrementalRecognizer::startRecognition().
const std::vector<size_t>& Speech::DataSource::nFrames () const inline
Returns
number of frames per port
Definition at line 120 of file Speech/DataSource.hh.
The documentation for this class was generated from the following files:
Speech/DataSource.hh
DataSource.cc