Sprint: Signal::FullCovMonoGaussianModel Class Reference
Signal::FullCovMonoGaussianModel Class Reference
#include <SegmentClustering.hh>
Public Member Functions
FullCovMonoGaussianModel (u32 dim)
represented as N(logDeterminant(variance))
const u32 dim () const
returns the feature dimension
const u32 nFrames () const
returns the number of frames seen so far
const Math::Vector< f64 > & mean () const
returns the mean vector of size dim()
const Math::Matrix< f64 > & variance () const
returns the variance matrix of size dim()xdim()
bool accumulate (const std::vector< f32 > &vec)
update the mean vector, the variance matrix, and the frame count
bool finalize ()
finalize the mean vector and variance matrix
void mergeModels (const FullCovMonoGaussianModel &x, const FullCovMonoGaussianModel &y)
merges the mean vectors and variance matrices of the left FullCovMonoGaussianModel x and right FullCovMonoGaussianModel y into the current model.
void mergeMeans (const FullCovMonoGaussianModel &x, const FullCovMonoGaussianModel &y)
merges the mean vectors of the left FullCovMonoGaussianModel x and right FullCovMonoGaussianModel y
void mergeVariance (const FullCovMonoGaussianModel &x, const FullCovMonoGaussianModel &y)
merges the variance matrices of the left FullCovMonoGaussianModel x and right FullCovMonoGaussianModel y
void reset (f32 x)
?
const f32 computeComplexity ()
BIC is a likelihood criterion penalized by the model complexity: the number of parameters in the model.
void computeL ()
compute the likelihood as N(logDeterminant(variance))
const f32 relativeLikelihood (const FullCovMonoGaussianModel &x) const
compute the relative likelihood
Protected Attributes
Math::Vector< f64 > mean_
Math::Matrix< f64 > variance_
u32 nFrames_
f32 likelihood_
Detailed Description
Todo:
: this class should be derived from the abstract DiagCovMonoGaussianModel class
Definition at line 74 of file SegmentClustering.hh.
Constructor & Destructor Documentation
Signal::FullCovMonoGaussianModel::FullCovMonoGaussianModel (u32 dim) inline
represented as N(logDeterminant(variance))
Definition at line 81 of file SegmentClustering.hh.
Member Function Documentation
bool FullCovMonoGaussianModel::accumulate (const std::vector< f32 > & vec)
update the mean vector, the variance matrix, and the frame count
Definition at line 53 of file SegmentClustering.cc.
const f32 FullCovMonoGaussianModel::computeComplexity ()
BIC is a likelihood criterion penalized by the model complexity: the number of parameters in the model.
The number of parameters for each cluster is d+d/2(d+1)
with penalty function P = (1/2(d+d/2(d+1))) * log(N) = (2d/4 + d^2/4 + d/4) * log(N) = (1/4(d*(3+d))) * log(N)
Definition at line 47 of file SegmentClustering.cc.
void FullCovMonoGaussianModel::computeL ()
compute the likelihood as N(logDeterminant(variance))
Definition at line 105 of file SegmentClustering.cc.
Referenced by Signal::BICFullCovMonoGaussianModel::finalize(), and Signal::BICFullCovMonoGaussianModel::mergeModels().
const u32 Signal::FullCovMonoGaussianModel::dim () const inline
returns the feature dimension
Definition at line 89 of file SegmentClustering.hh.
bool FullCovMonoGaussianModel::finalize (void)
finalize the mean vector and variance matrix
Definition at line 63 of file SegmentClustering.cc.
References Core::Component::log(), and Core::Application::us().
Referenced by Signal::BICFullCovMonoGaussianModel::finalize().
const Math::Vector<f64>& Signal::FullCovMonoGaussianModel::mean () const inline
returns the mean vector of size dim()
Definition at line 99 of file SegmentClustering.hh.
void FullCovMonoGaussianModel::mergeMeans (const FullCovMonoGaussianModel & x, const FullCovMonoGaussianModel & y)
merges the mean vectors of the left FullCovMonoGaussianModel x and right FullCovMonoGaussianModel y
Todo:
: this should be a private function?
Definition at line 79 of file SegmentClustering.cc.
References nFrames().
Referenced by mergeModels().
void FullCovMonoGaussianModel::mergeModels (const FullCovMonoGaussianModel & x, const FullCovMonoGaussianModel & y)
merges the mean vectors and variance matrices of the left FullCovMonoGaussianModel x and right FullCovMonoGaussianModel y into the current model.
Definition at line 131 of file SegmentClustering.cc.
References mergeMeans(), and mergeVariance().
Referenced by Signal::BICFullCovMonoGaussianModel::mergeModels().
void FullCovMonoGaussianModel::mergeVariance (const FullCovMonoGaussianModel & x, const FullCovMonoGaussianModel & y)
merges the variance matrices of the left FullCovMonoGaussianModel x and right FullCovMonoGaussianModel y
Todo:
: this should be a private function?
Definition at line 88 of file SegmentClustering.cc.
References nFrames().
Referenced by mergeModels().
const u32 Signal::FullCovMonoGaussianModel::nFrames () const inline
returns the number of frames seen so far
Definition at line 94 of file SegmentClustering.hh.
Referenced by mergeMeans(), and mergeVariance().
const f32 FullCovMonoGaussianModel::relativeLikelihood (const FullCovMonoGaussianModel & x) const
compute the relative likelihood
Definition at line 110 of file SegmentClustering.cc.
Referenced by Signal::KL2FullCovMonoGaussianModel::computeKL2().
void Signal::FullCovMonoGaussianModel::reset (f32 x) inline
?
Definition at line 137 of file SegmentClustering.hh.
const Math::Matrix<f64>& Signal::FullCovMonoGaussianModel::variance () const inline
returns the variance matrix of size dim()xdim()
Definition at line 104 of file SegmentClustering.hh.
The documentation for this class was generated from the following files:
SegmentClustering.hh
SegmentClustering.cc