Sprint: Speech::OrthographyFrameStateAccuracyLatticeBuilder Class Reference
Speech::OrthographyFrameStateAccuracyLatticeBuilder Class Reference
Public Member Functions
OrthographyFrameStateAccuracyLatticeBuilder (const Core::Configuration &, Core::Ref< const Bliss::Lexicon >)
OrthographyFrameStateAccuracyLatticeBuilder.
Functor createFunctor (const std::string &id, const std::string &segmentId, Lattice::ConstWordLatticeRef lattice, Core::Ref< PhonemeSequenceAlignmentGenerator > alignmentGenerator)
virtual Fsa::ConstAutomatonRef build (Lattice::ConstWordLatticeRef)
Public Member Functions inherited from Speech::OrthographyTimeAlignmentBasedMetricLatticeBuilder
OrthographyTimeAlignmentBasedMetricLatticeBuilder (const Core::Configuration &, Core::Ref< const Bliss::Lexicon >)
OrthographyTimeAlignmentBasedMetricLatticeBuilder.
Functor createFunctor (const std::string &id, const std::string &orth, Lattice::ConstWordLatticeRef lattice)
Public Member Functions inherited from Speech::TimeAlignmentBasedMetricLatticeBuilder
TimeAlignmentBasedMetricLatticeBuilder (const Core::Configuration &, Core::Ref< const Bliss::Lexicon >)
Public Member Functions inherited from Speech::MetricFsaBuilder< Lattice::ConstWordLatticeRef >
MetricFsaBuilder (const Core::Configuration &c)
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Private Types
typedef OrthographyTimeAlignmentBasedMetricLatticeBuilder Precursor
Private Attributes
Core::Ref< const Bliss::Lexicon > lexicon_
Core::Ref< PhonemeSequenceAlignmentGenerator > alignmentGenerator_
Additional Inherited Members
Protected Types inherited from Speech::TimeAlignmentBasedMetricLatticeBuilder
enum TokenType {
noneType, lemmaPronunciationType, lemmaType, phoneType,
stateType
}
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Speech::TimeAlignmentBasedMetricLatticeBuilder
void setReference (Lattice::ConstWordLatticeRef reference)
void initializeShortPauses (Core::Ref< const Bliss::Lexicon >)
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Speech::OrthographyTimeAlignmentBasedMetricLatticeBuilder
Bliss::OrthographicParser * orthToLemma_
Fsa::ConstAutomatonRef lemmaPronToLemma_
Fsa::ConstAutomatonRef lemmaToLemmaConfusion_
Protected Attributes inherited from Speech::TimeAlignmentBasedMetricLatticeBuilder
Lattice::ShortPauses shortPauses_
TokenType tokenType_
Lattice::ConstWordLatticeRef reference_
Protected Attributes inherited from Core::Configurable
Configuration config
Static Protected Attributes inherited from Speech::TimeAlignmentBasedMetricLatticeBuilder
static const Core::ParameterStringVector paramShortPausesLemmata
TimeAlignmentBasedMetricLatticeBuilder.
static Core::Choice choiceTokenType
static Core::ParameterChoice paramTokenType
Detailed Description
Definition at line 62 of file AdvancedAccuracyFsaBuilder.hh.
Constructor & Destructor Documentation
OrthographyFrameStateAccuracyLatticeBuilder::OrthographyFrameStateAccuracyLatticeBuilder (const Core::Configuration & c, Core::Ref< const Bliss::Lexicon > lexicon)
OrthographyFrameStateAccuracyLatticeBuilder.
Definition at line 174 of file AdvancedAccuracyFsaBuilder.cc.
References Core::Component::error(), Bliss::Lexicon::lemma(), Core::Component::log(), Core::normalizeWhitespace(), Speech::TimeAlignmentBasedMetricLatticeBuilder::paramShortPausesLemmata, Bliss::Lexicon::specialLemma(), and Core::Component::warning().
The documentation for this class was generated from the following files:
AdvancedAccuracyFsaBuilder.hh
AdvancedAccuracyFsaBuilder.cc