Sprint: Flf::Semiring Class Reference
Flf::Semiring Class Reference abstract
Classes
class Collector
class Extender
class XmlElement
Public Types
typedef Core::Ref< Self > Ref
typedef Core::Ref< const Self > ConstRef
typedef std::unordered_map< Key, ScoreId, Core::StringHash > KeyMap
typedef s32 Tolerance
typedef Core::Ref< Extender > ExtenderRef
typedef Core::Ref< Collector > CollectorRef
Public Types inherited from Ftl::Semiring< ScoresRef >
typedef ScoresRef Weight
typedef Core::Ref< Self > Ref
typedef Core::Ref< const Self > ConstRef
typedef Ftl::Accumulator< ScoresRef > Accumulator
Public Member Functions
Semiring (size_t n, const ScoreList &scales=ScoreList(), const KeyList &keys=KeyList())
bool operator== (const Semiring &semiring) const
size_t size () const
size, type, and name
virtual std::string name () const =0
virtual Fsa::SemiringType type () const =0
void setTolerance (Tolerance tolerance) const
tolerance
Tolerance tolerance () const
virtual void setScales (const ScoreList &scales) const
scales
ScoreList & scales () const
virtual void setScale (ScoreId id, Score scale) const
Score scale (ScoreId id) const
u32 cmpScales (const ScoreList &scales) const
void setKeys (const KeyList &keys) const
identifier mapping
KeyList & keys () const
bool setKey (ScoreId id, const Key &key) const
bool hasKey (const Key &key) const
const Key & key (ScoreId id) const
bool hasId (ScoreId id) const
ScoreId id (const Key &key) const
virtual ScoresRef create () const
create and clone weights and standard weights
virtual ScoresRef clone (const ScoresRef &a) const
virtual ScoresRef one () const
virtual ScoresRef zero () const
virtual ScoresRef max () const
virtual ScoresRef invalid () const
virtual ScoresRef defaultWeight () const
virtual bool isDefault (const ScoresRef &a) const
virtual size_t hash (const ScoresRef &a) const
Scores::const_iterator begin (const ScoresRef &a) const
iterate over score dimensions
Scores::const_iterator end (const ScoresRef &a) const
Scores::iterator begin (ScoresRef &a) const
Scores::iterator end (ScoresRef &a) const
virtual ScoresRef extend (const ScoresRef &a, const ScoresRef &b) const
extend, collect, invert, project, and compare
virtual ScoresRef invert (const ScoresRef &a) const
virtual Score project (const ScoresRef &a) const
virtual int compare (const ScoresRef &a, const ScoresRef &b) const
virtual ExtenderRef createExtender () const
virtual CollectorRef createCollector () const
virtual bool read (ScoresRef &a, Core::BinaryInputStream &i) const
i/o
virtual bool write (const ScoresRef &a, Core::BinaryOutputStream &o) const
virtual std::string asString (const ScoresRef &a) const
virtual ScoresRef fromString (const std::string &s) const
virtual std::string describe (const ScoresRef &a, Fsa::Hint hint=Fsa::HintNone) const
virtual void compress (ByteVector &stream, const ScoresRef &a) const
virtual ScoresRef uncompress (ByteVector::const_iterator &) const
virtual size_t compressedSize () const
void write (Core::XmlWriter &xml) const
XML.
Public Member Functions inherited from Ftl::Semiring< ScoresRef >
Semiring (Fsa::Property properties)
Fsa::Property getProperties (Fsa::Property properties=Fsa::PropertyAll) const
bool hasProperty (Fsa::Property property) const
virtual ScoresRef clone (const ScoresRef &a) const =0
virtual ScoresRef extend (const ScoresRef &a, const ScoresRef &b) const =0
virtual ScoresRef collect (const ScoresRef &a, const ScoresRef &b) const =0
virtual ScoresRef invCollect (const ScoresRef &a, const ScoresRef &b) const
virtual bool hasInvCollect () const
virtual ScoresRef invert (const ScoresRef &a) const =0
virtual int compare (const ScoresRef &a, const ScoresRef &b) const =0
virtual size_t hash (const ScoresRef &a) const =0
virtual std::string asString (const ScoresRef &) const =0
virtual bool read (ScoresRef &a, Core::BinaryInputStream &i) const =0
virtual bool write (const ScoresRef &a, Core::BinaryOutputStream &o) const =0
virtual void compress (Core::Vector< u8 > &stream, const ScoresRef &a) const =0
virtual ScoresRef uncompress (Core::Vector< u8 >::const_iterator &) const =0
virtual bool isDefault (const ScoresRef &a) const
virtual std::string describe (const ScoresRef &a, Fsa::Hint hints=0) const
virtual Accumulator * getExtender (const ScoresRef &initial) const
Accumulator * getExtender () const
virtual Accumulator * getCollector (const ScoresRef &initial) const
Accumulator * getCollector () const
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Static Public Member Functions
static Key UndefinedKey ()
static bool equal (ConstSemiringRef semiring1, ConstSemiringRef semiring2)
compare semirings
static ConstSemiringRef create (Fsa::SemiringType, size_t n, const ScoreList &scales=ScoreList(), const KeyList &keys=KeyList())
create semirings
static ConstSemiringRef create (const Core::Configuration &config)
config
static XmlElement * xmlElement (Core::XmlContext *context)
static ConstSemiringRef read (std::istream &)
Static Public Attributes
static constexpr Score Zero = Core::Type<Score>::max
static constexpr Score One = Score(0)
static constexpr Score Max = Core::Type<Score>::max
static constexpr Score Invalid = Core::Type<Score>::min
static constexpr Score DefaultScale = Score(1)
static constexpr Score UndefinedScale = Core::Type<Score>::min
static constexpr ScoreId InvalidId = Core::Type<ScoreId>::max
static constexpr Tolerance DefaultTolerance = 1
Protected Member Functions
Scores * alloc () const
Scores * alloc (const ScoresRef &a) const
Scores * alloc (const Score &init) const
Scores::iterator begin (Scores *a) const
convinient wrappers to get score iterators
Scores::iterator end (Scores *a) const
Protected Attributes
const size_t n_
Tolerance tolerance_
ScoreList scales_
KeyList keys_
KeyMap keyMap_
ScoresRef one_
ScoresRef zero_
ScoresRef max_
ScoresRef invalid_
ScoresRef default_
Private Types
typedef Semiring Self
typedef Ftl::Semiring< ScoresRef > Precursor
Detailed Description
Definition at line 37 of file Flf/FlfCore/Semiring.hh.
Member Function Documentation
Scores::iterator Flf::Semiring::begin (Scores * a) const inline protected
convinient wrappers to get score iterators
Definition at line 85 of file Flf/FlfCore/Semiring.hh.
Referenced by begin().
Scores::const_iterator Flf::Semiring::begin (const ScoresRef & a) const inline
iterate over score dimensions
Definition at line 181 of file Flf/FlfCore/Semiring.hh.
References begin(), and extend().
virtual ScoresRef Flf::Semiring::create () const inline virtual
create and clone weights and standard weights
Implements Ftl::Semiring< ScoresRef >.
Definition at line 153 of file Flf/FlfCore/Semiring.hh.
Referenced by Flf::cloneSemiring(), create(), Flf::fromFsa(), Flf::ChangeSemiringNode::init(), Flf::ProjectSemiringNode::init(), Flf::UnionNode::init(), Flf::EvaluatorNode::init(), Flf::StringConverterNode::init(), Flf::CtmReaderNode::init(), Speech::LatticeSemiringNode::LatticeSemiringNode(), MyApplication::main(), Speech::LatticeSimpleModifyNode::work(), Speech::LatticeTransformNode::work(), Speech::LatticeTransform2Node::work(), and Flf::writeConfusionNetworkAsText().
ConstSemiringRef Flf::Semiring::create (Fsa::SemiringType type, size_t n, const ScoreList & scales = ScoreList(), const KeyList & keys = KeyList()) static
create semirings
Definition at line 391 of file Flf/FlfCore/Semiring.cc.
ConstSemiringRef Flf::Semiring::create (const Core::Configuration & config) static
config
type = tropical*|log tolerance = 1 keys = key1 key2 ... key1.scale = 1.0 key2.scale = 1.0 ...
Definition at line 417 of file Flf/FlfCore/Semiring.cc.
References create().
bool Flf::Semiring::equal (ConstSemiringRef semiring1, ConstSemiringRef semiring2) static
compare semirings
Definition at line 577 of file Flf/FlfCore/Semiring.cc.
References Core::Component::criticalError(), Core::Ref< T >::get(), read(), and Core::Application::us().
ScoresRef Flf::Semiring::extend (const ScoresRef & a, const ScoresRef & b) const virtual
extend, collect, invert, project, and compare
Definition at line 182 of file Flf/FlfCore/Semiring.cc.
References defect, and Core::isAlmostEqualUlp().
Referenced by begin(), and Flf::NBestBuilder::initialize().
bool Flf::Semiring::read (ScoresRef & a, Core::BinaryInputStream & i) const virtual
i/o
Definition at line 231 of file Flf/FlfCore/Semiring.cc.
References defect, Flf::exp(), Core::form(), and Flf::HintUnscaled.
Referenced by Flf::Semiring::XmlElement::characters(), equal(), and MyApplication::main().
void Flf::Semiring::setKeys (const KeyList & keys) const
identifier mapping
Definition at line 137 of file Flf/FlfCore/Semiring.cc.
References Core::Component::error(), Core::Application::us(), and verify.
Referenced by size().
void Flf::Semiring::setScales (const ScoreList & scales) const virtual
scales
Definition at line 110 of file Flf/FlfCore/Semiring.cc.
References verify.
Referenced by size().
void Flf::Semiring::setTolerance (Tolerance tolerance) const
tolerance
Definition at line 106 of file Flf/FlfCore/Semiring.cc.
Referenced by size().
size_t Flf::Semiring::size () const inline
size, type, and name
Definition at line 101 of file Flf/FlfCore/Semiring.hh.
References setKeys(), setScales(), and setTolerance().
void Flf::Semiring::write (Core::XmlWriter & xml) const
XML.
... <semiring> <type> tropical* | log </type> <tolerance> 1 </tolerance> <dimension> <key> dim-0 </key> <scale> 1.0 </scale> </dimension> <dimension> <key> dim-1 </key> <scale> 1.0 </scale> </dimension> ... </semiring> ...
Definition at line 434 of file Flf/FlfCore/Semiring.cc.
The documentation for this class was generated from the following files:
Flf/FlfCore/Semiring.hh
Flf/FlfCore/Semiring.cc