Sprint: Flf::UnknownAlphabet Class Reference
Flf::UnknownAlphabet Class Reference
Public Member Functions
virtual std::string symbol (Fsa::LabelId index) const
Returns the string representation of a symbol.
virtual Fsa::LabelId index (const std::string &symbol) const
Given a string representation of a symbol returns the label id.
virtual const_iterator begin () const
Returns an iterator pointing to the first symbol.
virtual const_iterator end () const
Returns an iterator pointing behind the last symbol.
Public Member Functions inherited from Fsa::Alphabet
std::string specialSymbol (LabelId index) const
Retrieve a string representation of a special label id.
LabelId specialIndex (const std::string &symbol) const
Map a string representation of a special symbol to its label id.
virtual LabelId next (LabelId id) const
Returns the label id of the next symbol in sequence.
virtual bool isDisambiguator (LabelId index) const
Determine wether a symbol is a disambiguator (see determinize for more details on the use of disambiguators).
virtual AlphabetTag tag (LabelId index) const
return symbol tag
virtual bool write (Core::BinaryOutputStream &o) const
Write the alphabet to BinaryOutputStream.
virtual void writeXml (Core::XmlWriter &o) const
Write the alphabet to an XmlWriter.
virtual size_t getMemoryUsed () const
Return the amount of memory used by this object.
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Detailed Description
Definition at line 27 of file Flf/Lexicon.cc.
Member Function Documentation
virtual const_iterator Flf::UnknownAlphabet::begin () const inline virtual
Returns an iterator pointing to the first symbol.
Note, that if the alphabet contains a hole in the space of label ids at the beginning the iterator must be winded to the first existing symbol.
Returns
a const iterator pointing to the first symbol or end()
Reimplemented from Fsa::Alphabet.
Definition at line 61 of file Flf/Lexicon.cc.
virtual const_iterator Flf::UnknownAlphabet::end () const inline virtual
Returns an iterator pointing behind the last symbol.
This usually does not need to be overloaded except for the case you need a different internal representation of the end iterator. Currently, InvalidLabelId is being used as end iterator.
Returns
a const iterator pointing to the first symbol or end()
Reimplemented from Fsa::Alphabet.
Definition at line 64 of file Flf/Lexicon.cc.
References defect, ensure, Bliss::Lemma::evaluationTokenSequences(), Core::Ref< T >::get(), Bliss::Lemma::hasEvaluationTokenSequence(), Bliss::Lemma::hasName(), Bliss::Lemma::hasSyntacticTokenSequence(), Bliss::Token::id(), index(), Bliss::Pronunciation::length(), Bliss::Lemma::nPronunciations(), Bliss::Lemma::orthographicForms(), Bliss::Lemma::pronunciations(), require, Bliss::Symbol::str(), symbol(), Bliss::Token::symbol(), and verify.
virtual Fsa::LabelId Flf::UnknownAlphabet::index (const std::string & symbol) const inline virtual
Given a string representation of a symbol returns the label id.
Parameters
symbol the string representation of a symbol
Returns
the label id of the symbol or InvalidLabelId if the string represents no valid symbol
Reimplemented from Fsa::Alphabet.
Definition at line 43 of file Flf/Lexicon.cc.
References Core::Component::error(), Core::strconv(), and Core::Application::us().
Referenced by end().
virtual std::string Flf::UnknownAlphabet::symbol (Fsa::LabelId index) const inline virtual
Returns the string representation of a symbol.
Parameters
index the symbol's label id
Returns
the string representation of the symbol or an empty string if there is no symbol with that label id
Implements Fsa::Alphabet.
Definition at line 29 of file Flf/Lexicon.cc.
References Core::form().
Referenced by end().
The documentation for this class was generated from the following file:
Flf/Lexicon.cc