Sprint: Nn::CtcCriterion< FloatT > Class Template Reference
Nn::CtcCriterion< FloatT > Class Template Reference
Public Member Functions
CtcCriterion (const Core::Configuration &c)
virtual void inputSpeechSegment (Bliss::SpeechSegment &segment, NnMatrix &nnOutput, NnVector *weights=NULL)
Override for a segment (without lattice) criterion (e.g.
virtual void getObjectiveFunction (FloatT &value)
Override to calculate the objective function.
virtual void getErrorSignal (NnMatrix &errorSignal)
Override to calculate the error signal.
virtual void getErrorSignal_naturalPairing (NnMatrix &errorSignal, NeuralNetworkLayer< FloatT > &lastLayer)
Override to calculate the error signal with natural pairing of the last layer activation function.
virtual NnMatrix * getPseudoTargets ()
Some criterions will calculate some kind of pseudo targets and have the gradient -{y} / y w.r.t.
virtual bool discardCurrentInput ()
Overrwrite if you want to signal any trainer to ignore this input.
Core::Ref< Am::AcousticModel > getAcousticModel ()
bool getAlignment (Speech::Alignment &out, NnMatrix &logPosteriors, const std::string &orthography, FloatT minProbGT=0.0, FloatT gamma=1.0)
Public Member Functions inherited from Nn::SegmentCriterion< FloatT >
SegmentCriterion (const Core::Configuration &c)
virtual void input (NnMatrix &nnOutput, NnVector *weights=NULL)
Override for an unsupervised criterion.
Public Member Functions inherited from Nn::Criterion< FloatT >
Criterion (const Core::Configuration &c)
virtual void inputAlignment (Math::CudaVector< u32 > &alignment, NnMatrix &nnOutput, NnVector *weights=NULL)
Override for an alignment-based criterion (usually frame-wise, e.g.
virtual void reset ()
virtual void reinputWithNewNnOutput (NnMatrix &nnOutput)
virtual Type getType () const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Protected Types
typedef Types< FloatT >::NnVector NnVector
typedef Types< FloatT >::NnMatrix NnMatrix
Protected Types inherited from Nn::SegmentCriterion< FloatT >
typedef Types< FloatT >::NnVector NnVector
typedef Types< FloatT >::NnMatrix NnMatrix
Protected Types inherited from Nn::Criterion< FloatT >
typedef Types< FloatT >::NnVector NnVector
typedef Types< FloatT >::NnMatrix NnMatrix
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions
void initLexicon ()
void initAcousticModel ()
void initAllophoneStateGraphBuilder ()
void initSearchAligner ()
void initStatePriors ()
void initFixedMixtureSet ()
void initDebug ()
u32 nEmissions () const
u32 getCurSegmentTimeLen () const
virtual u32 getBatchLen ()
virtual FloatT getStateScore (u32 timeIdx, u32 emissionIdx)
void getStateScorers_MixtureSet (std::vector< Core::Ref< const Mm::FeatureScorer::ContextScorer >> &scorers)
void getStateScorers (std::vector< Core::Ref< const Mm::FeatureScorer::ContextScorer >> &scorers)
Core::Ref< const Fsa::Automaton > getHypothesesAllophoneStateFsa ()
Core::Ref< const Fsa::Automaton > getTimeAlignedFsa_SearchAligner ()
Core::Ref< TimeAlignedAutomaton< FloatT > > getTimeAlignedFsa_custom ()
Core::Ref< const Fsa::Automaton > getTimeAlignedFsa ()
Core::Ref< const Fsa::Automaton > getPosteriorFsa ()
bool calcStateProbErrors (FloatT &error, NnMatrix &referenceProb)
void dumpViterbiAlignments ()
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes
Core::Ref< Am::AcousticModel > acousticModel_
Core::Ref< const Bliss::Lexicon > lexicon_
std::shared_ptr< Speech::AllophoneStateGraphBuilder > allophoneStateGraphBuilder_
bool useSearchAligner_
std::shared_ptr< Search::Aligner > aligner_
bool useDirectAlignmentExtraction_
FloatT minAcousticPruningThreshold_
FloatT maxAcousticPruningThreshold_
FloatT statePosteriorScale_
FloatT statePosteriorLogBackoff_
std::shared_ptr< Prior< FloatT > > statePriors_
Core::Ref< Mm::ScaledFeatureScorer > fixedMixtureSetFeatureScorer_
Core::Ref< Speech::DataSource > fixedMixtureSetFeatureExtractionDataSource_
std::string fixedMixtureSetExtractAlignmentsPortName_
bool posteriorUseSearchAligner_
bool posteriorTotalNormalize_
FloatT posteriorArcLogThreshold_
FloatT posteriorScale_
unsigned int posteriorNBestLimit_
std::shared_ptr< Core::Archive > dumpViterbiAlignmentsArchive_
std::shared_ptr< Core::Archive > dumpReferenceProbsArchive_
bool doDebugDumps_
bool logTimeStatistics_
bool useCrossEntropyAsLoss_
bool inputInLogSpace_
NnMatrix stateLogPosteriors_
bool discardCurrentInput_
Protected Attributes inherited from Nn::Criterion< FloatT >
NnMatrix * nnOutput_
NnVector * weights_
Math::CudaVector< u32 > * alignment_
Bliss::SpeechSegment * segment_
FloatT objectiveFunction_
bool needRecalc_objectiveFunction_
NnMatrix errorSignal_
bool needRecalc_errorSignal_
Type criterionType_
Protected Attributes inherited from Core::Configurable
Configuration config
Private Types
typedef SegmentCriterion< FloatT > Precursor
Additional Inherited Members
Public Types inherited from Nn::Criterion< FloatT >
enum Type {
none, crossEntropy, squaredError, binaryDivergence,
ctc
}
Static Public Member Functions inherited from Nn::Criterion< FloatT >
static Criterion< FloatT > * create (const Core::Configuration &config)
Static Public Attributes inherited from Nn::Criterion< FloatT >
static const Core::Choice choiceCriterion
static const Core::ParameterChoice paramCriterion
Detailed Description
template<typename FloatT>
class Nn::CtcCriterion< FloatT >
Definition at line 62 of file CtcCriterion.hh.
Member Function Documentation
template<typename FloatT> virtual bool Nn::CtcCriterion< FloatT >::discardCurrentInput () inline virtual
Overrwrite if you want to signal any trainer to ignore this input.
Reimplemented from Nn::Criterion< FloatT >.
Definition at line 135 of file CtcCriterion.hh.
template<typename FloatT > void Nn::CtcCriterion< FloatT >::getErrorSignal (NnMatrix & errorSignal) virtual
Override to calculate the error signal.
Some input* function was called before. This is thus the error signal of the NN output.
Reimplemented from Nn::Criterion< FloatT >.
Definition at line 1178 of file CtcCriterion.cc.
template<typename FloatT > void Nn::CtcCriterion< FloatT >::getErrorSignal_naturalPairing (NnMatrix & errorSignal, NeuralNetworkLayer< FloatT > & lastLayer) virtual
Override to calculate the error signal with natural pairing of the last layer activation function.
This is thus the error signal of the linear part of the last layer. This function is usually used in frame-wise training with a fixed alignment, via BufferedAlignedFeatureProcessor.
Reimplemented from Nn::Criterion< FloatT >.
Definition at line 1200 of file CtcCriterion.cc.
References Core::Component::warning().
template<typename FloatT > void Nn::CtcCriterion< FloatT >::getObjectiveFunction (FloatT & value) virtual
Override to calculate the objective function.
Some input* function was called before.
Reimplemented from Nn::Criterion< FloatT >.
Definition at line 1169 of file CtcCriterion.cc.
template<typename FloatT > CtcCriterion< FloatT >::NnMatrix * Nn::CtcCriterion< FloatT >::getPseudoTargets () virtual
Some criterions will calculate some kind of pseudo targets and have the gradient -{y} / y w.r.t.
y, and when y = softmax(a), they have the gradient y - {y} w.r.t. a. In that case, we call {y} the pseudo targets. Examples: Cross-Entropy and CTC. Can return NULL. Otherwise the pointer will be valid until the next input.
Reimplemented from Nn::Criterion< FloatT >.
Definition at line 1226 of file CtcCriterion.cc.
template<typename FloatT > void Nn::CtcCriterion< FloatT >::inputSpeechSegment (Bliss::SpeechSegment & segment, NnMatrix & nnOutput, NnVector * weights = NULL) virtual
Override for a segment (without lattice) criterion (e.g.
CTC)
Reimplemented from Nn::SegmentCriterion< FloatT >.
Definition at line 1105 of file CtcCriterion.cc.
References Core::Component::error(), Math::isnan(), require, and verify.
The documentation for this class was generated from the following files:
CtcCriterion.hh
CtcCriterion.cc