Sprint: Core::MemoryInfo Class Reference
Core::MemoryInfo Class Reference
process memory information
#include <MemoryInfo.hh>
Public Types
typedef u64 SizeType
Public Member Functions
void update ()
update memory information
SizeType size () const
total virtual memory size in bytes
SizeType residentSetSize () const
resident set size in bytes
SizeType sharedPages () const
shared pages
SizeType codeSize () const
code size in bytes
SizeType libSize () const
library size in bytes
SizeType dataSize () const
data/stack size in bytes
std::string peak () const
peak vmem size (formatted string)
void write (XmlWriter &os) const
Private Member Functions
void updateLinux ()
Private Attributes
SizeType size_
SizeType rss_
SizeType share_
SizeType text_
SizeType lib_
SizeType data_
u32 pageSize_
Detailed Description
process memory information
Definition at line 25 of file MemoryInfo.hh.
Member Function Documentation
SizeType Core::MemoryInfo::codeSize () const inline
code size in bytes
Definition at line 57 of file MemoryInfo.hh.
SizeType Core::MemoryInfo::dataSize () const inline
data/stack size in bytes
Definition at line 69 of file MemoryInfo.hh.
References peak().
SizeType Core::MemoryInfo::libSize () const inline
library size in bytes
Definition at line 63 of file MemoryInfo.hh.
std::string MemoryInfo::peak () const
peak vmem size (formatted string)
Definition at line 54 of file MemoryInfo.cc.
References Core::form(), Core::stripWhitespace(), Core::Application::us(), and Core::Component::warning().
Referenced by dataSize(), and Core::Application::setCommentCharacters().
SizeType Core::MemoryInfo::residentSetSize () const inline
resident set size in bytes
Definition at line 45 of file MemoryInfo.hh.
SizeType Core::MemoryInfo::sharedPages () const inline
shared pages
Definition at line 51 of file MemoryInfo.hh.
SizeType Core::MemoryInfo::size () const inline
total virtual memory size in bytes
Definition at line 39 of file MemoryInfo.hh.
Referenced by Core::Application::setCommentCharacters().
void MemoryInfo::update ()
update memory information
Definition at line 29 of file MemoryInfo.cc.
References Core::form(), Core::Application::us(), and Core::Component::warning().
The documentation for this class was generated from the following files:
MemoryInfo.hh
MemoryInfo.cc