Sprint: Speech::Alignment Class Reference
Speech::Alignment Class Reference
Public Types
enum LabelType { allophoneStateIds, emissionIds }
typedef std::pair< Alignment::iterator, Alignment::iterator > Frame
Public Member Functions
Alignment (const Alignment &alignment)
void setScore (Score score)
Score score () const
Returns the score of the alignment, if available.
bool setAlphabet (Core::Ref< const Fsa::Alphabet > alphabet, bool skipMismatch=false)
Set a mapping alphabet.
bool hasWeights () const
Returns true, if at least one alignment item has a weight different from one.
void sortItems (bool byDecreasingWeight=true)
Sorts the alignment items, such that timeframes have ascending order and secondly weight have descending order.
void sortStableItems ()
void combineItems (Fsa::ConstSemiringRef sr=Fsa::TropicalSemiring)
Combines all alignment items which differ only in their weight.
void expm ()
Builds weights from negative logarithm of item weights.
void addWeight (Mm::Weight weight)
Adds.
void filterWeights (Mm::Weight minWeight, Mm::Weight maxWeight=1.0)
Filter alignment items by their weights.
void filterWeightsGT (Mm::Weight minWeight)
Remove alignment items by their weights.
void normalizeWeights ()
Normalize weights, such that for each timeframe the sum of weights is one.
void shiftMinToZeroWeights ()
shift per time such that for each timeframe the min of weights is 0.
void clipWeights (Mm::Weight a=0.0, Mm::Weight b=1.0)
Clip all weights into the interval [a..b].
void resetWeightsSmallerThan (Mm::Weight a=0.0, Mm::Weight b=0.0)
void resetWeightsLargerThan (Mm::Weight a=1.0, Mm::Weight b=1.0)
void multiplyWeights (Mm::Weight c)
Multiply all weights with the specified value.
void gammaCorrection (Mc::Scale gamma)
Raise all weights to the given power gamma.
void getFrames (std::vector< Frame > &rows)
For each time frame, get a pair of begin and end iterator.
Alignment & operator*= (const Alignment &)
Component-wise weight multiplication.
LabelType labelType () const
get alignment labelType
void setLabelType (LabelType labeltype)
set alignment labelType, only allowed for empty alignments, no mapping is performed
void mapToEmissionIdLabels (const Core::Ref< Am::AcousticModel > &acousticModel)
change alignment label type to emission id, all allophone state ids are mapped to emission ids
void write (std::ostream &) const
void writeXml (Core::XmlWriter &) const
void addTimeOffset (TimeframeIndex)
Private Types
typedef std::vector< AlignmentItem > Precursor
Private Member Functions
void mapAlphabet (bool skipMismatch)
Private Attributes
Score score_
Core::Ref< const Fsa::Alphabet > alphabet_
std::map< u32, std::string > archiveAlphabet_
LabelType labelType_
Static Private Attributes
static const char * magic = "ALIGNRLE"
static const char * magic_alphabet = "AALPHRLE"
static const char * magic_emission = "ALIGNEMI"
static const size_t magicSize = 8
Friends
Core::BinaryInputStream & operator>> (Core::BinaryInputStream &, Alignment &)
Core::BinaryOutputStream & operator<< (Core::BinaryOutputStream &, const Alignment &)
Core::XmlWriter & operator<< (Core::XmlWriter &, const Alignment &)
Detailed Description
Definition at line 59 of file Alignment.hh.
Member Function Documentation
void Alignment::addWeight (Mm::Weight weight)
Adds.
Parameters
weight to each item weight.
Definition at line 481 of file Alignment.cc.
Referenced by Speech::AlignmentAddWeightNode::setParameter().
void Alignment::clipWeights (Mm::Weight a = 0.0, Mm::Weight b = 1.0)
Clip all weights into the interval [a..b].
Definition at line 568 of file Alignment.cc.
void Alignment::combineItems (Fsa::ConstSemiringRef sr = Fsa::TropicalSemiring)
Combines all alignment items which differ only in their weight.
Definition at line 455 of file Alignment.cc.
Referenced by Speech::AlignmentGammaCorrectionNode::setParameter(), and Speech::SetAlignmentWeightsByTiedStateAlignmentWeightsNode::work().
void Alignment::expm ()
Builds weights from negative logarithm of item weights.
Definition at line 475 of file Alignment.cc.
Referenced by Speech::AlignmentExpmNode::AlignmentExpmNode().
void Alignment::filterWeights (Mm::Weight minWeight, Mm::Weight maxWeight = 1.0)
Filter alignment items by their weights.
(>= min && <= max)
Definition at line 487 of file Alignment.cc.
Referenced by Speech::AlignmentFilterWeightsNode::setParameter().
void Alignment::filterWeightsGT (Mm::Weight minWeight)
Remove alignment items by their weights.
(> min)
Definition at line 498 of file Alignment.cc.
void Alignment::gammaCorrection (Mc::Scale gamma)
Raise all weights to the given power gamma.
Note that the weights are not normalized afterwards. This function is intended to approximate a re-alignment with a different acoustic-model scale.
Definition at line 509 of file Alignment.cc.
Referenced by Speech::AlignmentGammaCorrectionNode::setParameter().
void Alignment::getFrames (std::vector< Frame > & rows)
For each time frame, get a pair of begin and end iterator.
Definition at line 610 of file Alignment.cc.
Referenced by Speech::AlignmentResetWeightsNode::setParameter(), Speech::AlignmentDumpNode::work(), and Speech::SetAlignmentWeightsByTiedStateAlignmentWeightsNode::work().
bool Alignment::hasWeights () const
Returns true, if at least one alignment item has a weight different from one.
Definition at line 600 of file Alignment.cc.
LabelType Speech::Alignment::labelType () const inline
get alignment labelType
Definition at line 149 of file Alignment.hh.
void Alignment::mapToEmissionIdLabels (const Core::Ref< Am::AcousticModel > & acousticModel)
change alignment label type to emission id, all allophone state ids are mapped to emission ids
Definition at line 640 of file Alignment.cc.
References require.
Referenced by Speech::PhonemeSequenceAlignmentGenerator::Cache::initializeArchive().
void Alignment::multiplyWeights (Mm::Weight c)
Multiply all weights with the specified value.
Definition at line 519 of file Alignment.cc.
Referenced by Speech::AlignmentMultiplyWeightsNode::setParameter().
void Alignment::normalizeWeights ()
Normalize weights, such that for each timeframe the sum of weights is one.
Definition at line 530 of file Alignment.cc.
Referenced by Speech::AlignmentGammaCorrectionNode::setParameter().
Alignment & Alignment::operator*= (const Alignment & a2)
Component-wise weight multiplication.
Definition at line 623 of file Alignment.cc.
References require.
Score Speech::Alignment::score () const inline
Returns the score of the alignment, if available.
Definition at line 87 of file Alignment.hh.
Referenced by Speech::PhonemeSequenceAlignmentGenerator::alignmentScore(), and Speech::PhonemeSequenceAlignmentGenerator::getAlignment().
bool Alignment::setAlphabet (Core::Ref< const Fsa::Alphabet > alphabet, bool skipMismatch = false)
Set a mapping alphabet.
When this is set, the alphabet is used to robustly map allophone indices between different alphabets. If skipMismatch is true, then alignment items which could not be mapped into the new alphabet are simply removed. Otherwise an error is raised for such items.
Definition at line 345 of file Alignment.cc.
References Core::form(), Fsa::Alphabet::symbol(), and verify.
Referenced by Speech::AlignmentMapAlphabet::AlignmentMapAlphabet(), Speech::AlignmentFromLatticeNode::work(), Speech::AlignmentNode::work(), and Speech::SetAlignmentWeightsByTiedStateAlignmentWeightsNode::work().
void Speech::Alignment::setLabelType (LabelType labeltype) inline
set alignment labelType, only allowed for empty alignments, no mapping is performed
Definition at line 154 of file Alignment.hh.
void Alignment::shiftMinToZeroWeights ()
shift per time such that for each timeframe the min of weights is 0.
Definition at line 549 of file Alignment.cc.
void Alignment::sortItems (bool byDecreasingWeight = true)
Sorts the alignment items, such that timeframes have ascending order and secondly weight have descending order.
Definition at line 442 of file Alignment.cc.
Referenced by Flf::readPosteriorCnFromXml().
The documentation for this class was generated from the following files:
Alignment.hh
Alignment.cc