Sprint: Bliss::CorpusSizeStatisticsVisitor Class Reference
Bliss::CorpusSizeStatisticsVisitor Class Reference
Public Member Functions
CorpusSizeStatisticsVisitor (const Core::Configuration &c)
virtual void enterRecording (Recording *)
Template method called when corpus traversal enters a recording.
virtual void visitSegment (Segment *)
Template method for processing segments.
virtual void visitSpeechSegment (SpeechSegment *)
Template method for processing speech segments.
virtual void reset ()
virtual void writeReport (Core::XmlWriter &) const
Public Member Functions inherited from Bliss::CorpusStatisticsVisitor
CorpusStatisticsVisitor (const Core::Configuration &c)
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Bliss::CorpusVisitor
virtual void leaveRecording (Recording *)
Template method called when corpus traversal leaves a recording.
virtual void enterCorpus (Corpus *)
Template method notifying start of a (sub-) corpus.
virtual void leaveCorpus (Corpus *)
Template method notifying end of a (sub-) corpus.
Private Attributes
unsigned int nRecordings_
unsigned int nSpeechSegments_
unsigned int nOtherSegments_
Time totalNetDuration_
Time totalGrossDuration_
unsigned int nNetTimeFrames_
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Definition at line 41 of file Bliss/CorpusStatistics.hh.
Member Function Documentation
void CorpusSizeStatisticsVisitor::enterRecording (Recording *) virtual
Template method called when corpus traversal enters a recording.
Implement this to take appropriate actions, e.g. opening the audio file.
Reimplemented from Bliss::CorpusVisitor.
Definition at line 34 of file Bliss/CorpusStatistics.cc.
void CorpusSizeStatisticsVisitor::visitSegment (Segment *) virtual
Template method for processing segments.
Implement this to process speech and non-speech segments of a corpus.
Reimplemented from Bliss::SegmentVisitor.
Definition at line 40 of file Bliss/CorpusStatistics.cc.
References Bliss::Segment::end(), and Bliss::Segment::start().
void CorpusSizeStatisticsVisitor::visitSpeechSegment (SpeechSegment * s) virtual
Template method for processing speech segments.
Implement this to process the speech segments of a corpus. By default the request will be forwarded to visitSegment(), so ignore this if you want to treat speech and non-speech segments alike.
Reimplemented from Bliss::SegmentVisitor.
Definition at line 46 of file Bliss/CorpusStatistics.cc.
References Bliss::Segment::end(), and Bliss::Segment::start().
The documentation for this class was generated from the following files:
Bliss/CorpusStatistics.hh
Bliss/CorpusStatistics.cc