Sprint: Signal::CrossCorrelationNode Class Reference
Signal::CrossCorrelationNode Class Reference
CrossCorrelationNode.
#include <CrossCorrelation.hh>
Public Member Functions
CrossCorrelationNode (const Core::Configuration &c)
Flow::PortId getInput (const std::string &name)
Ask for an input port.
Flow::PortId getOutput (const std::string &name)
Ask for an output port.
virtual bool setParameter (const std::string &name, const std::string &value)
Set node specific parameter.
virtual bool configure ()
Performs static (independent of input data) configuration of node.
virtual bool work (Flow::PortId p)
Processes some data.
Public Member Functions inherited from Flow::Node
Node (const Core::Configuration &c)
Public Member Functions inherited from Flow::AbstractNode
AbstractNode (const Core::Configuration &c)
virtual void Run ()
void setThreaded (bool threaded=true)
void setThreaded (const std::string &threaded)
bool isThreaded () const
virtual bool addParameter (const std::string &name, const Core::StringExpression &value)
addParameter adds a parameter to the node Constant parameters are simply delegated to setParameter, parameters dependent on network parameters are stored in parameters_.
virtual ssize_t getRemainingDataLen (PortId out)
Returns the amount of remaining data items.
void addUnresolvedParameter (const std::string &key, const std::string &value)
Functions for saving and getting unresolved parameters.
const UnresolvedAttributes & unresolvedAttributes () const
bool operator< (const AbstractNode &n) const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Signal::CrossCorrelation
void apply (const std::vector< Data > &x, const std::vector< Data > &y, std::vector< Data > &Rxy)
void apply (const std::vector< Data > &x, const std::vector< Data > &y, std::vector< Data > &Rxy, Core::Component &errorChannels)
void setBegin (s32 begin)
void setEnd (s32 end)
void setSimilarityFunctionType (const SimilarityFunctionType similarityFunctionType)
void setPower (const f64 power)
void setNormalizationType (const NormalizationType normalizationType)
void setUseFastFourierTransform (const bool use)
Static Public Member Functions
static std::string filterName ()
Static Public Attributes
static const Core::ParameterFloat paramBegin
static const Core::ParameterFloat paramEnd
static const Core::ParameterInt paramNumberOfCoefficients
static const Core::Choice choiceSimilarityFunctionType
static const Core::ParameterChoice paramSimilarityFunctionType
static const Core::ParameterFloat paramPower
static const Core::Choice choiceNormalizationType
static const Core::ParameterChoice paramNormalizationType
static const Core::ParameterBool paramUseFastFourierTransform
Static Public Attributes inherited from Flow::AbstractNode
static const Core::ParameterBool paramThreaded
static const Core::ParameterBool paramIgnoreUnknownParameters
Private Member Functions
void setSampleRate (f64 sampleRate)
void setContinuousBegin (f64 begin)
void setContinuousEnd (f64 end)
void setNumberOfCoefficients (size_t n)
void init ()
bool getData (Flow::DataPtr< Flow::Vector< f32 >> &x, Flow::DataPtr< Flow::Vector< f32 >> &y)
Private Attributes
f64 continuousBegin_
Corss-correlation calculated on the constinuous interval [begin..end)
f64 continuousEnd_
f64 sampleRate_
size_t nCoefficients_
Corss-correlation calculated on the discrete interval [0..nCoefficients_) Note: if not 0, this parameter overwrites the interval given by continuousBegin_ and continuousend_.
bool needInit_
Additional Inherited Members
Public Types inherited from Flow::AbstractNode
typedef std::map< std::string, std::string > UnresolvedAttributes
Public Types inherited from Signal::CrossCorrelation
enum SimilarityFunctionType { Multiplication, AbsoluteDifference }
enum NormalizationType { None, UnbiasedEstimate, UpperBound }
typedef f32 Data
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Flow::Node
virtual PortId connectInputPort (PortId, Link *)
Connect link to input port.
virtual void disconnectInputLink (Link *)
virtual PortId connectOutputPort (PortId, Link *)
virtual void disconnectOutputLink (Link *)
PortId addInput (PortId in=IllegalPortId)
Create an input port.
PortId addInputs (u32 nPorts)
Create several input ports.
virtual PortId nInputs () const
Link * getInputLink (PortId in) const
virtual PortId inputConnected (PortId in) const
bool validInputPort (PortId in) const
PortId addOutput (PortId out=IllegalPortId)
Add an output port.
PortId addOutputs (u32 nPorts)
Create several output ports.
virtual PortId nOutputs () const
bool validOutputPort (PortId out) const
virtual u32 nOutputLinks (PortId out) const
Number of link connceted to an output port.
bool configureDatatype (Core::Ref< const Attributes > a, const Datatype *d)
template<class T >
bool getData (PortId in, DataPtr< T > &d)
Fetch data packet from input port.
virtual bool putData (PortId out, Data *d)
Send data packet on output port.
bool putEos (PortId out)
Send end-of-stream on output port.
bool putOod (PortId out)
Send out-of-data on output port.
Core::Ref< const Attributes > getInputAttributes (PortId in)
Retrieve attribute set from input port.
void getInputAttributes (PortId, Attributes &)
bool putOutputAttributes (PortId out, Core::Ref< const Attributes > a)
Put attribute set on output port.
void eraseOutputAttributes ()
Erases attributes of all output links recursively.
Protected Member Functions inherited from Flow::AbstractNode
template<class T >
bool getData (Link *l, DataPtr< T > &d)
Fetch data packet from the "from" port of link.
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
CrossCorrelationNode.
Definition at line 256 of file CrossCorrelation.hh.
Member Function Documentation
bool CrossCorrelationNode::configure () virtual
Performs static (independent of input data) configuration of node.
Configure is called if one of the output attributes is not available. Override this function to evaluate all input attributes and pass them on to successor nodes. The default implementation simply forwards the merged attributes from all input links to all outputs. Note: -we assume no dead inputs here. -This function is the safest point to reset the algorithms used by the node. The alternative would be to reset the algorithms when a non-data object has been recieved. This solution can lead easily to unintended behaviour, since it is not garatinteed at all that every node receives for example a EOS object!
Reimplemented from Flow::Node.
Definition at line 234 of file CrossCorrelation.cc.
References Core::Component::error(), and Core::isAlmostEqual().
Flow::PortId CrossCorrelationNode::getInput (const std::string &) virtual
Ask for an input port.
Implement this function to provide a mapping form names to port IDs. Consider using a Core::Choice. Remeber to create ports using addInput().
Returns
a valid port ID or IllegalPortId if there is to such port.
Reimplemented from Flow::Node.
Definition at line 254 of file CrossCorrelation.cc.
Flow::PortId Signal::CrossCorrelationNode::getOutput (const std::string &) inline virtual
Ask for an output port.
Implement this function to provide a mapping form names to port IDs. Consider using a Core::Choice. Remeber to create ports using addOutput().
Returns
a valid port ID or IllegalPortId if there is to such port.
Reimplemented from Flow::Node.
Definition at line 317 of file CrossCorrelation.hh.
bool CrossCorrelationNode::setParameter (const std::string & name, const std::string & value) virtual
Set node specific parameter.
Implement this template function to handle parameters specific to your Node.
Parameters
name name of parameter
value new value for the parameter
Returns
true if successful, false if parameter name is not understood.
Reimplemented from Flow::AbstractNode.
Definition at line 262 of file CrossCorrelation.cc.
References Core::Component::criticalError().
bool CrossCorrelationNode::work (Flow::PortId out) virtual
Processes some data.
Implement this function to do whatever your node is supposed to. You are required to produce at least one packet of data on the specified output out. You may send more packets, also to other outputs.
Returns
true on success, false on end-of-file or error. The idiom is:
return putData(out, d);
Implements Flow::Node.
Definition at line 301 of file CrossCorrelation.cc.
Member Data Documentation
f64 Signal::CrossCorrelationNode::continuousBegin_ private
Corss-correlation calculated on the constinuous interval [begin..end)
Definition at line 270 of file CrossCorrelation.hh.
size_t Signal::CrossCorrelationNode::nCoefficients_ private
Corss-correlation calculated on the discrete interval [0..nCoefficients_) Note: if not 0, this parameter overwrites the interval given by continuousBegin_ and continuousend_.
Definition at line 277 of file CrossCorrelation.hh.
The documentation for this class was generated from the following files:
CrossCorrelation.hh
CrossCorrelation.cc