Sprint: Ftl::CopyDfsState< _Automaton > Class Template Reference
Ftl::CopyDfsState< _Automaton > Class Template Reference
Public Types
typedef _Automaton::State _State
typedef _Automaton::ConstStateRef _ConstStateRef
typedef _Automaton::ConstRef _ConstAutomatonRef
Public Types inherited from Ftl::DfsState< _Automaton >
typedef _Automaton::Arc _Arc
typedef _Automaton::State _State
typedef _Automaton::ConstStateRef _ConstStateRef
typedef _Automaton::ConstRef _ConstAutomatonRef
typedef Fsa::StateId Color
The possible colors of a state.
Public Member Functions
CopyDfsState (StorageAutomaton< _Automaton > *f, _ConstAutomatonRef f2)
virtual void discoverState (_ConstStateRef sp)
Called upon first discovery of a state.
Public Member Functions inherited from Ftl::DfsState< _Automaton >
DfsState (_ConstAutomatonRef f)
virtual void finishState (Fsa::StateId s)
Called after all subtrees starting at a previously discovered state have been processed.
virtual void exploreTreeArc (_ConstStateRef from, const _Arc &a)
Called upon discovery of a tree arc.
virtual void exploreNonTreeArc (_ConstStateRef from, const _Arc &a)
Called upon discovery of a non-tree arc.
virtual void finishArc (_ConstStateRef from, const _Arc &a)
Called after all subtrees starting at a previously explored arc have been processed.
virtual void finish ()
Called after all states reachable from the initial state have been processed.
Fsa::StateId maxStateId () const
Request the highest state id of the automaton.
Fsa::StateId size () const
Color color (Fsa::StateId s) const
Request the color of a state.
Fsa::StateId predecessor (Fsa::StateId s) const
Request the predecessor of a state.
void dfs (Core::ProgressIndicator *p=0)
Initiate searching the automaton.
void recursiveDfs (Core::ProgressIndicator *p=0)
Initiate searching the automaton.
Private Types
typedef DfsState< _Automaton > Precursor
Private Attributes
StorageAutomaton< _Automaton > * fsa_
Additional Inherited Members
Static Public Attributes inherited from Ftl::DfsState< _Automaton >
static const Color White = 0xc0000000
static const Color Gray = 0x80000000
static const Color Black = 0x40000000
Protected Attributes inherited from Ftl::DfsState< _Automaton >
_ConstAutomatonRef fsa_
Core::Vector< Fsa::StateId > info_
Detailed Description
template<class _Automaton>
class Ftl::CopyDfsState< _Automaton >
Definition at line 23 of file tCopy.cc.
Member Function Documentation
template<class _Automaton> virtual void Ftl::CopyDfsState< _Automaton >::discoverState (_ConstStateRef sp) inline virtual
Called upon first discovery of a state.
Parameters
sp reference to state
Reimplemented from Ftl::DfsState< _Automaton >.
Definition at line 38 of file tCopy.cc.
References Fsa::StaticAlphabet::addSymbol(), Ftl::DfsState< _Automaton >::dfs(), and Core::ref().
The documentation for this class was generated from the following file:
tCopy.cc