Sprint: Signal::FastFourierTransform Class Reference
Signal::FastFourierTransform Class Reference abstract
FastFourierTransform: base class to perform fast fourier transform.
#include <FastFourierTransform.hh>
Public Types
typedef f32 Data
Public Member Functions
FastFourierTransform (u32 length=0, Data sampleRate=1)
virtual bool transform (std::vector< Data > &data)
u32 length () const
u32 setLength (u32 length)
sets the number of FFT points (length_) as the -smallest number which is -power of 2 -larger than
virtual u32 maximalInputSize () const =0
virtual void setInputSize (u32 inputSize)=0
Sets the number of FFT points necesseary for transforming an input of length.
virtual u32 outputSize () const =0
void setInputSampleRate (f64 sampleRate)
Sample-rate of input vector.
f64 outputSampleRate () const
Sample-rate of output vector.
const std::string & lastError () const
Returns the description of the last error.
Protected Member Functions
virtual bool zeroPadding (std::vector< Data > &data)
virtual bool applyAlgorithm (std::vector< Data > &data)=0
virtual bool estimateContinuous (std::vector< Data > &data)
Calculates an estimation of the continuous values.
Protected Attributes
u32 length_
f64 sampleRate_
sample rate of input vector.
Math::FastFourierTransform fft_
std::string lastError_
Detailed Description
FastFourierTransform: base class to perform fast fourier transform.
Definition at line 26 of file Signal/FastFourierTransform.hh.
Member Function Documentation
bool FastFourierTransform::estimateContinuous (std::vector< Data > & data) protected virtual
Calculates an estimation of the continuous values.
Each element is multiplied by { t} resp. { }.
Reimplemented in Signal::RealInverseFastFourierTransform.
Definition at line 47 of file Signal/FastFourierTransform.cc.
References Core::form(), and Math::FastFourierTransform::transform().
const std::string& Signal::FastFourierTransform::lastError () const inline
Returns the description of the last error.
Definition at line 87 of file Signal/FastFourierTransform.hh.
u32 Signal::FastFourierTransform::length () const inline
Returns
number of FFT points.
Definition at line 52 of file Signal/FastFourierTransform.hh.
References maximalInputSize(), setInputSize(), and setLength().
Referenced by Signal::Convolution::apply(), Signal::FastFourierTransformNode< Algorithm >::configure(), Signal::CrossCorrelation::crossCorrelation(), Signal::ComplexFastFourierTransform::maximalInputSize(), Signal::RealFastFourierTransform::maximalInputSize(), Signal::RealInverseFastFourierTransform::maximalInputSize(), Signal::ComplexFastFourierTransform::setInputSize(), Signal::RealFastFourierTransform::setInputSize(), and Signal::RealInverseFastFourierTransform::setInputSize().
virtual u32 Signal::FastFourierTransform::maximalInputSize () const pure virtual
Returns
maximum input size for the number of FFT points.
Implemented in Signal::RealInverseFastFourierTransform, Signal::RealFastFourierTransform, and Signal::ComplexFastFourierTransform.
Referenced by length().
f64 Signal::FastFourierTransform::outputSampleRate () const inline
Sample-rate of output vector.
I.e.: inverse of distance between two output samples. (length_ / sampleRate_).
Definition at line 82 of file Signal/FastFourierTransform.hh.
References sampleRate_.
Referenced by Signal::Convolution::apply(), and Signal::CrossCorrelation::crossCorrelation().
void Signal::FastFourierTransform::setInputSampleRate (f64 sampleRate) inline
Sample-rate of input vector.
(
See also
outputSampleRate() too.)
Definition at line 75 of file Signal/FastFourierTransform.hh.
References require.
virtual void Signal::FastFourierTransform::setInputSize (u32 inputSize) pure virtual
Sets the number of FFT points necesseary for transforming an input of length.
Parameters
inputSize.
Implemented in Signal::RealInverseFastFourierTransform, Signal::RealFastFourierTransform, and Signal::ComplexFastFourierTransform.
Referenced by length().
u32 FastFourierTransform::setLength (u32 length)
sets the number of FFT points (length_) as the -smallest number which is -power of 2 -larger than
Parameters
length
Returns
number of FFT points.
Definition at line 28 of file Signal/FastFourierTransform.cc.
References ensure, and Core::isAlmostEqual().
Referenced by length(), Signal::ComplexFastFourierTransform::setInputSize(), Signal::RealFastFourierTransform::setInputSize(), and Signal::RealInverseFastFourierTransform::setInputSize().
Member Data Documentation
f64 Signal::FastFourierTransform::sampleRate_ protected
sample rate of input vector.
Definition at line 33 of file Signal/FastFourierTransform.hh.
Referenced by outputSampleRate().
The documentation for this class was generated from the following files:
Signal/FastFourierTransform.hh
Signal/FastFourierTransform.cc