Sprint: Core::Choice Class Reference
Core::Choice Class Reference
Choice class.
#include <Choice.hh>
Classes
struct comp_by_value
class Item
Public Types
typedef s32 Value
typedef std::pair< std::string, Value > IdentifierValuePair
typedef std::vector< IdentifierValuePair > IdentifierValuePairList
typedef std::set< Item >::const_iterator const_iterator
Iterator.
Public Member Functions
Choice (const char *ident, const Value value,...)
Constructs the choice.
Choice (const IdentifierValuePairList &)
Constructs the choice.
Choice (const std::vector< std::string > &)
Constructs the choice.
void addChoice (const char *, Value)
Value addChoice (const char *)
Add identifier for smalles unused value.
u32 nChoices () const
Returns the number of different choices.
void getValues (std::vector< Value > &) const
Get a list of possible values (may contain duplicates)
void getIdentifiers (std::vector< std::string > &) const
Get a list of possible identifiers (may contain duplicates)
Value operator[] (const std::string &ident) const
Returns the enumeration value of a choice or Choice::Illegal if ident is not a valid identifier.
const std::string & operator[] (const Value &value) const
Returns the identifier of a choice or an empty string if ident is not a valid identifier.
bool operator== (const Choice &choice) const
Returns true, iff both choices define exactly the same mapping.
void printIdentifiers (std::ostream &) const
Print a comma separated list of all identifiers.
const_iterator begin () const
const_iterator end () const
Static Public Member Functions
static const char * endMark ()
Static Public Attributes
static const Value IllegalValue = -1
static const char *const IllegalIdentifier = ""
Private Attributes
const std::string illegalIdentifier
std::set< Item > items_by_ident
std::set< Item, comp_by_value > items_by_value
Detailed Description
Choice class.
A choice is the symbolic mapping between enumerations and strings. Choices are used to specify enumerative parameters.
Definition at line 33 of file Choice.hh.
Member Typedef Documentation
typedef std::set<Item>::const_iterator Core::Choice::const_iterator
Iterator.
Definition at line 153 of file Choice.hh.
Constructor & Destructor Documentation
Choice::Choice (const char * ident, const Value value, ...)
Constructs the choice.
The parameters are specified as a list of pairs of strings and enumeration (integer) values. varargs are used to allow for an arbitrary number of different choices. The last identifier must be 0 to mark the end of the list.
Definition at line 44 of file Choice.cc.
Choice::Choice (const IdentifierValuePairList & pairs)
Constructs the choice.
Definition at line 76 of file Choice.cc.
Choice::Choice (const std::vector< std::string > & keys)
Constructs the choice.
The vector of strings is mapped to a consecutive list of numbers starting with 0, i.e. the identifier is the string and the value equals the index.
Definition at line 83 of file Choice.cc.
Member Function Documentation
Choice::Value Choice::addChoice (const char * ident)
Add identifier for smalles unused value.
Definition at line 90 of file Choice.cc.
void Choice::getIdentifiers (std::vector< std::string > & out) const
Get a list of possible identifiers (may contain duplicates)
Definition at line 103 of file Choice.cc.
Referenced by nChoices().
void Choice::getValues (std::vector< Value > & out) const
Get a list of possible values (may contain duplicates)
Definition at line 98 of file Choice.cc.
Referenced by nChoices().
u32 Core::Choice::nChoices () const inline
Returns the number of different choices.
Definition at line 110 of file Choice.hh.
References getIdentifiers(), getValues(), operator[](), and printIdentifiers().
Referenced by Cart::XmlPropertiesBuilderElement::characters().
bool Choice::operator== (const Choice & choice) const
Returns true, iff both choices define exactly the same mapping.
Parameters
choice instance of Choice
Definition at line 122 of file Choice.cc.
Choice::Value Choice::operator[] (const std::string & ident) const
Returns the enumeration value of a choice or Choice::Illegal if ident is not a valid identifier.
Parameters
ident choice identifier
Definition at line 108 of file Choice.cc.
Referenced by nChoices().
const std::string & Choice::operator[] (const Value & value) const
Returns the identifier of a choice or an empty string if ident is not a valid identifier.
Parameters
value enumeration value
Definition at line 115 of file Choice.cc.
void Choice::printIdentifiers (std::ostream & os) const
Print a comma separated list of all identifiers.
Definition at line 126 of file Choice.cc.
References Core::boolChoice, and Core::infinityChoice.
Referenced by FsaTool::getUsage(), and nChoices().
The documentation for this class was generated from the following files:
Choice.hh
Choice.cc