Sprint: Bliss::Pronunciation Class Reference
Bliss::Pronunciation Class Reference
A pronunciation in the Bliss lexicon.
#include <Lexicon.hh>
Classes
struct Equality
struct Hash
class LemmaIterator
Public Member Functions
u32 nLemmas () const
The number of lemmata this pronunciation occurs in.
std::pair< LemmaIterator, LemmaIterator > lemmas () const
Iterator-range giving access to the set of lemmata this pronunciation occurs in.
const Phoneme::Id * phonemes () const
Phoneme sequence terminated by Phoneme::term.
u32 length () const
Length of pronunciation in number of phonemes.
Phoneme::Id operator[] (unsigned i) const
std::string format (Core::Ref< const PhonemeInventory >) const
Create string representation.
Protected Member Functions
Pronunciation (const Phoneme::Id *phonemes)
Private Attributes
LemmaPronunciation * lemmas_
const Phoneme::Id * phonemes_
Friends
class Lexicon
Detailed Description
A pronunciation in the Bliss lexicon.
See also
Bliss documentation
Definition at line 270 of file Bliss/Lexicon.hh.
Member Function Documentation
std::string Pronunciation::format (Core::Ref< const PhonemeInventory > phonemeInventory) const
Create string representation.
Definition at line 99 of file Bliss/Lexicon.cc.
References Bliss::PhonemeInventory::phoneme(), require, and Bliss::Token::symbol().
Referenced by TestApplication::getUsage(), Bliss::LemmaPronunciationAlphabet::index(), Speech::LemmaPronunciationId_hash_map::init(), and Bliss::LemmaPronunciationAlphabet::symbol().
std::pair<LemmaIterator, LemmaIterator> Bliss::Pronunciation::lemmas () const inline
Iterator-range giving access to the set of lemmata this pronunciation occurs in.
Definition at line 330 of file Bliss/Lexicon.hh.
Referenced by Search::StateTree::createExits().
u32 Pronunciation::length () const
Length of pronunciation in number of phonemes.
Definition at line 61 of file Bliss/Lexicon.cc.
Referenced by Am::AllophoneAlphabet::add(), Search::StateTree::advancePronunciationSuffix(), Bliss::ContextPhonology::append(), Search::StateTree::boundary(), Search::Wfst::StateSequenceBuilder::createSymbols(), Flf::UnknownAlphabet::end(), Flf::expandTransits(), Search::StateTree::getAllophone(), Search::SearchSpace::minimumWordEndScore(), Search::LinearSearch::Pronunciation::Pronunciation(), Search::StateTree::PronunciationSuffix::PronunciationSuffix(), and Search::StateTree::pronunciationSuffixTransitEntry().
u32 Pronunciation::nLemmas () const
The number of lemmata this pronunciation occurs in.
Definition at line 92 of file Bliss/Lexicon.cc.
const Phoneme::Id* Bliss::Pronunciation::phonemes () const inline
Phoneme sequence terminated by Phoneme::term.
Definition at line 336 of file Bliss/Lexicon.hh.
Referenced by Search::Wfst::LexiconBuilder::build(), Search::Wfst::StateSequenceBuilder::createSymbols(), Flf::expandTransits(), TestApplication::getUsage(), and Search::SearchSpace::minimumWordEndScore().
The documentation for this class was generated from the following files:
Bliss/Lexicon.hh
Bliss/Lexicon.cc