Sprint: Speech::AligningFeatureExtractor Class Reference
Speech::AligningFeatureExtractor Class Reference
AligningFeatureExtractor.
#include <AligningFeatureExtractor.hh>
Public Member Functions
AligningFeatureExtractor (const Core::Configuration &, AlignedFeatureProcessor &)
virtual void signOn (CorpusVisitor &)
Override this function to sign on to services of the corpus visitor.
virtual void enterCorpus (Bliss::Corpus *)
virtual void leaveCorpus (Bliss::Corpus *)
virtual void enterSegment (Bliss::Segment *)
virtual void leaveSegment (Bliss::Segment *)
virtual void enterSpeechSegment (Bliss::SpeechSegment *)
virtual void leaveSpeechSegment (Bliss::SpeechSegment *)
virtual void processSegment (Bliss::Segment *)
Public Member Functions inherited from Speech::FeatureExtractor
FeatureExtractor (const Core::Configuration &c, bool loadFromFile=true)
Public Member Functions inherited from Speech::DataExtractor
DataExtractor (const Core::Configuration &c, bool loadFromFile=true)
virtual void enterRecording (Bliss::Recording *)
Public Member Functions inherited from Speech::CorpusProcessor
CorpusProcessor (const Core::Configuration &c)
virtual void leaveRecording (Bliss::Recording *recoding)
virtual void processSpeechSegment (Bliss::SpeechSegment *segment)
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Attributes
static const Core::ParameterString paramAlignmentPortName
static const Core::ParameterBool paramEnforceWeightedProcessing
static const Core::ParameterString paramAlignment2PortName
Protected Member Functions
virtual void setFeatureDescription (const Mm::FeatureDescription &description)
Override this function to achieve the attributes of the feature streams.
virtual void processFeature (Core::Ref< const Feature > f)
Override this function to achieve the features extracted form data source one-by-one.
void unaryProcessFeature (Core::Ref< const Feature > f)
void binaryProcessFeature (Core::Ref< const Feature > f)
bool initializeAlignment ()
Protected Member Functions inherited from Speech::DataExtractor
void setDataSource (Core::Ref< DataSource > s)
Core::Ref< DataSource > dataSource () const
Protected Member Functions inherited from Speech::CorpusProcessor
void reportRealTime (Flow::Time)
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes
AlignedFeatureProcessor & alignedFeatureProcessor_
Flow::PortId alignmentPortId_
TimeframeIndex currentFeatureId_
Alignment::const_iterator currentAlignmentItem_
bool processWeighted_
Flow::DataPtr< Flow::DataAdaptor< Alignment > > alignmentRef_
const Alignment * alignment_
Fast access to the alignment object.
Flow::PortId alignment2PortId_
Alignment::const_iterator currentAlignment2Item_
Flow::DataPtr< Flow::DataAdaptor< Alignment > > alignment2Ref_
const Alignment * alignment2_
Fast access to the alignment-2 object.
Protected Attributes inherited from Speech::CorpusProcessor
Core::XmlChannel channelTimer_
Core::Timer timer_
Protected Attributes inherited from Core::Configurable
Configuration config
Private Types
typedef FeatureExtractor Precursor
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Detailed Description
AligningFeatureExtractor.
Definition at line 27 of file AligningFeatureExtractor.hh.
Member Function Documentation
void AligningFeatureExtractor::processFeature (Core::Ref< const Feature >) protected virtual
Override this function to achieve the features extracted form data source one-by-one.
Reimplemented from Speech::FeatureExtractor.
Definition at line 106 of file AligningFeatureExtractor.cc.
References Core::Component::error(), verify, and Core::Component::warning().
void AligningFeatureExtractor::setFeatureDescription (const Mm::FeatureDescription &) protected virtual
Override this function to achieve the attributes of the feature streams.
This function is called once before the first feature is processed.
Reimplemented from Speech::FeatureExtractor.
Definition at line 102 of file AligningFeatureExtractor.cc.
void AligningFeatureExtractor::signOn (CorpusVisitor & corpusVisitor) virtual
Override this function to sign on to services of the corpus visitor.
Note: call the signOn function of your predecessor.
Reimplemented from Speech::DataExtractor.
Definition at line 57 of file AligningFeatureExtractor.cc.
References Core::Component::log(), Speech::CorpusProcessor::signOn(), and verify.
Member Data Documentation
const Alignment* Speech::AligningFeatureExtractor::alignment2_ protected
Fast access to the alignment-2 object.
Definition at line 49 of file AligningFeatureExtractor.hh.
const Alignment* Speech::AligningFeatureExtractor::alignment_ protected
Fast access to the alignment object.
Definition at line 43 of file AligningFeatureExtractor.hh.
The documentation for this class was generated from the following files:
AligningFeatureExtractor.hh
AligningFeatureExtractor.cc