Sprint: InternalIc::Icb Class Reference
InternalIc::Icb Class Reference
iteration constants b
Public Member Functions
Icb (const Core::Configuration &, const MixtureEstimators &, const CovarianceToDensitySetMap &, IterationConstant stepSize)
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Protected Types
typedef AbstractMixtureSetEstimator::MixtureEstimators MixtureEstimators
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions
VarianceType minimumVariance (const CovarianceToDensitySetMap &) const
IterationConstant sigmaMinimum () const
void setSigmaMinimum (const CovarianceToDensitySetMap &)
IterationConstant minimumDk (CovarianceToDensitySetMap::const_iterator, const CovarianceToMeanSetMap::MeanSet &)
calculate D_k_min
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes
const IterationConstant default_
IterationConstant sigmaMinimum_
IterationConstant stepSize_
Xi xi_
ComponentIndex dimension_
Protected Attributes inherited from Core::Configurable
Configuration config
Private Types
typedef Core::Component Precursor
Static Private Attributes
static const Core::ParameterFloat paramSigmaMinimum
static const Core::ParameterFloat paramSigmaMinimumFactor
Detailed Description
iteration constants b
t1 := -Gamma_{s,l}(x_d^2) + sigma_min·Gamma_{s,l}(1) t2 := 2·Gamma_{s,l}(x_d) - Gamma_{s,l}(1)·mu_{s,l,d} t3 := Gamma_{s,l}(x_d) - Gamma_{s,l}(1)·mu_{s,l,d}
              sum_{s*,l*} [ t1 + t2·mu_{s,l,d} + xi_s·t3^2 ]
D_k^min = max_d { -------------------------------------------— } sum_{s*,l*} [ c_{s,l}·(sigma*^2-sigma_min) ]
with sigma*^2 in {sigma_{s,l,d}^2, sigma_{s_d}^2, sigma_d^2}
Definition at line 215 of file IterationConstants.cc.
Member Function Documentation
IterationConstant InternalIc::Icb::minimumDk (CovarianceToDensitySetMap::const_iterator covarianceAndDensitySet, const CovarianceToMeanSetMap::MeanSet & meanSet) protected
calculate D_k_min
Definition at line 298 of file IterationConstants.cc.
References Core::form(), and required_cast.
Referenced by InternalIc::GlobalIcb::GlobalIcb(), and InternalIc::LocalIcb::LocalIcb().
The documentation for this class was generated from the following file:
IterationConstants.cc