Sprint: Bliss::Token Class Reference
Bliss::Token Class Reference
Public Types
typedef s32 Id
Public Member Functions
Symbol symbol () const
A unique string identifier for the token.
Id id () const
The numerical ID of the token.
Static Public Attributes
static const Id invalidId = -1
Protected Member Functions
Token (Id _id, Bliss::Symbol _symbol)
Token (Id _id)
Token (Bliss::Symbol _symbol)
void setId (Id id)
void setSymbol (Symbol s)
Private Attributes
Id id_
Symbol symbol_
Friends
class TokenInventory
Detailed Description
Definition at line 157 of file Symbol.hh.
Member Function Documentation
Id Bliss::Token::id () const inline
The numerical ID of the token.
Definition at line 192 of file Symbol.hh.
Referenced by Search::Wfst::LexiconBuilder::build(), Search::Wfst::StateSequenceBuilder::createSymbols(), Flf::decodeRescoreLm(), Flf::UnknownAlphabet::end(), Lm::FFNeuralNetworkLanguageModel::extendedHistory(), Lm::TFRecurrentLanguageModel::extendedHistory(), Lm::BackingOffLm::extendedHistory(), Lm::BackingOffLm::getBatch(), Search::Wfst::ExpandingFsaSearch::getCurrentBestSentence(), Search::Wfst::LexiconBuilder::getSentenceEnd(), Bliss::TokenAlphabet::index(), Bliss::PhonemeAlphabet::index(), Am::AllophoneAlphabet::index(), Bliss::Lexicon::lemmas(), TestApplication::main(), Lm::BackingOffLm::Internal::mountImage(), Bliss::OrthographicParser::parse(), Search::Wfst::Builder::BuildGrammar::process(), Search::Wfst::Builder::CheckLabels::process(), Lm::FFNeuralNetworkLanguageModel::score(), Lm::TFRecurrentLanguageModel::score(), Lm::BackingOffLm::score(), and Speech::LatticeArcAccumulatorNode::~LatticeArcAccumulatorNode().
Symbol Bliss::Token::symbol () const inline
A unique string identifier for the token.
Definition at line 187 of file Symbol.hh.
Referenced by Bliss::ContextPhonology::append(), Bliss::PhonemeInventory::assignSymbol(), Search::Wfst::LexiconBuilder::build(), Lm::BackingOffLm::Internal::draw(), Flf::UnknownAlphabet::end(), Bliss::Pronunciation::format(), TestApplication::getUsage(), Flf::EditDistance::normCost(), Flf::EditDistance::operator()(), Search::SearchSpace::optimizeSilenceInWordLattice(), Search::Wfst::Builder::CheckLabels::process(), and Lm::BackingOffLm::reducedHistory().
The documentation for this class was generated from the following files:
Symbol.hh
Symbol.cc