Sprint: Bliss::OrthographicParser Class Reference
Bliss::OrthographicParser Class Reference
Parses an orthographic sentence into lemmas.
#include <Orthography.hh>
Classes
class Handler
class LemmaIterator
Parse a string and return two iterators, the begin and the end of the matching lemmas.
Public Types
typedef void * Node
typedef std::pair< LemmaIterator, LemmaIterator > LemmaRange
Public Member Functions
Core::Ref< const Lexicon > lexicon () const
const Lemma * unknownLemma () const
OrthographicParser (const Core::Configuration &, Core::Ref< const Lexicon >)
void suppressSilenceRepetitions ()
void parse (const std::string &orth, Handler &handler) const
Parse an orthographic string and make appropriate calls the the given handler.
LemmaRange lemmas (std::string &orth) const
Core::Ref< LemmaAcceptor > createLemmaAcceptor (const std::string &orth) const
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Private Attributes
Core::Ref< const Lexicon > lexicon_
const Lemma * unknownLemma_
OrthographicPrefixTree prefixTree_
bool allowForSilenceRepetitions_
Private Attributes inherited from Core::Configurable
Configuration config
Additional Inherited Members
Private Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Private Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Private Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Detailed Description
Parses an orthographic sentence into lemmas.
Definition at line 50 of file Orthography.hh.
Member Function Documentation
void OrthographicParser::parse (const std::string & orth, Handler & handler) const
Parse an orthographic string and make appropriate calls the the given handler.
Definition at line 80 of file Orthography.cc.
References Core::Ref< T >::_get(), Core::enforceTrailingBlank(), Core::Component::error(), Bliss::Token::id(), Core::Component::initialize(), Core::isWhitespaceNormalized(), require, Ftl::StaticAutomaton< _Automaton >::size(), and verify.
The documentation for this class was generated from the following files:
Orthography.hh
Orthography.cc