Sprint: Flow::Data Class Reference
Flow::Data Class Reference
Base class for Data class in Flow Features: -Multithread safe reference counting.
#include <Data.hh>
Public Member Functions
Data (const Data &data)
virtual Data * clone () const
const Datatype * datatype () const
virtual bool operator== (const Data &other) const
virtual Core::XmlWriter & dump (Core::XmlWriter &) const
virtual bool read (Core::BinaryInputStream &)
virtual bool write (Core::BinaryOutputStream &) const
Public Member Functions inherited from Core::ThreadSafeReferenceCounted
ThreadSafeReferenceCounted (const ThreadSafeReferenceCounted &)
ThreadSafeReferenceCounted & operator= (const ThreadSafeReferenceCounted &)
virtual ~ThreadSafeReferenceCounted ()
Constructor for static objects.
u32 refCount () const
Static Public Member Functions
static Data * eos ()
End of stream (EOS) sentinel.
static Data * ood ()
Out of data (OOD) sentinel This sentinel has been introduced to support partial processing of longer external input sequence.
static bool isSentinel (const ThreadSafeReferenceCounted *object)
static bool isNotSentinel (const ThreadSafeReferenceCounted *object)
Protected Member Functions
virtual void free () const
void lock () const
void release () const
void increment () const
bool decrement () const
Data (const Datatype *dt)
Core::XmlOpen xmlOpen () const
Core::XmlClose xmlClose () const
Protected Member Functions inherited from Core::ThreadSafeReferenceCounted
void lock () const
void release () const
void increment () const
bool decrement () const
ThreadSafeReferenceCounted (u32 rc)
Private Types
typedef Data Self
typedef Core::ThreadSafeReferenceCounted Precursor
Private Member Functions
Data (u32 rc)
Static Private Member Functions
static const Datatype * type ()
static Data * sentinel ()
sentinel for void pointer Note: Precursor::Sentinel is overriden to create a sentinel of Data instead the precursor class.
Private Attributes
const Datatype * datatype_
Friends
template<class T >
class Core::TsRef
template<class T >
class DataPtr
class Datatype
class Link
class Node
Detailed Description
Base class for Data class in Flow Features: -Multithread safe reference counting.
I.e. objects can be accessed by DataPtr. -Polymorfic I/O operation.
Definition at line 34 of file Data.hh.
Member Function Documentation
static Data* Flow::Data::eos () inline static
End of stream (EOS) sentinel.
Definition at line 122 of file Data.hh.
Referenced by Speech::FeatureScorerNode::configure(), ood(), Flow::Node::putEos(), Tensorflow::TensorflowForwardNode::work(), Flow::WarpTimeFilterNode::work(), Flow::PipeNode::work(), Signal::SlidingAlgorithmNode< Algorithm >::work(), Flow::VectorDemultiplexNode< T >::work(), Signal::MeanEstimatorNode::work(), Signal::PreemphasisNode::work(), Signal::SpectralIntegrationNode::work(), Nn::NeuralNetworkForwardNode::work(), Tensorflow::TensorflowOverlappingForwardNode::work(), Signal::MatrixMultiplicationNode< T >::work(), Signal::DelayNode::work(), Flow::SynchronizationNode< Algorithm >::work(), Signal::GammaToneNode::work(), and Signal::NormalizationNode::work().
static Data* Flow::Data::ood () inline static
Out of data (OOD) sentinel This sentinel has been introduced to support partial processing of longer external input sequence.
Nodes supporting OOD handling freeze their status and forward the OOD object on recieving an OOD object. Currently, only single input single output nodes support OOD. Extending nodes with several input and/or output ports requires a larger redesign. Possible alternative to the OOD concept is using multithreading.
Definition at line 134 of file Data.hh.
References eos(), and sentinel().
Referenced by Flow::Node::putOod().
static Data* Flow::Data::sentinel () inline static private
sentinel for void pointer Note: Precursor::Sentinel is overriden to create a sentinel of Data instead the precursor class.
In this way, all the sentinels are Data objects and can be handled equally.
See also
dump method as an example.
Definition at line 58 of file Data.hh.
References defect.
Referenced by ood(), and Flow::DataPtr< Flow::DataAdaptor< Speech::Alignment > >::operator==().
The documentation for this class was generated from the following files:
Data.hh
Data.cc