Sprint: Search::Wfst::Builder::BuildGrammar Class Reference
Search::Wfst::Builder::BuildGrammar Class Reference
build the language model transducer
#include <CreateOperations.hh>
Public Member Functions
BuildGrammar (const Core::Configuration &c, Resources &r)
Public Member Functions inherited from Search::Wfst::Builder::Operation
Operation (const Core::Configuration &c, Resources &r)
virtual u32 nInputAutomata () const
number of automata required as input
virtual bool consumeInput () const
should input automata be removed
virtual bool hasOutput () const
operation is expected to produce an output automaton.
virtual bool addInput (AutomatonRef)
add input automaton (will be called nInputAutomata() times)
AutomatonRef getResult ()
do the actual processing and create an output automaton
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Search::Wfst::Builder::OutputTypeDependent
OutputTypeDependent (const Core::Configuration &c)
Static Public Member Functions
static std::string name ()
Protected Member Functions
virtual AutomatonRef process ()
do the actual processing
void addSentenceBoundaries (Core::Ref< Fsa::StaticAutomaton > g, Fsa::LabelId sb, Fsa::LabelId se, bool addSb, bool addSe) const
AutomatonRef mapSymbols (AutomatonRef g) const
Protected Member Functions inherited from Search::Wfst::Builder::Operation
virtual bool precondition () const
precondition for getResult()
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Member Functions inherited from Search::Wfst::Builder::OutputTypeDependent
OutputType outputType () const
Static Protected Attributes
static const Core::ParameterBool paramAddEmptySyntacticTokens
static const Core::ParameterBool paramAddSentenceBoundaries
static const Core::ParameterBool paramAddSentenceBegin
static const Core::ParameterBool paramAddSentenceEnd
Static Protected Attributes inherited from Search::Wfst::Builder::OutputTypeDependent
static const Core::ParameterChoice paramOutputType
static const Core::Choice choiceOutputType
Additional Inherited Members
Public Types inherited from Search::Wfst::Builder::Operation
typedef Automaton * AutomatonRef
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Types inherited from Search::Wfst::Builder::OutputTypeDependent
enum OutputType { outputLemmaPronunciations, outputLemmas, outputSyntacticTokens }
Protected Attributes inherited from Search::Wfst::Builder::Operation
Resources & resources_
Core::XmlChannel timerChannel_
Core::Timer timer_
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
build the language model transducer
Definition at line 30 of file CreateOperations.hh.
Member Function Documentation
Operation::AutomatonRef BuildGrammar::process () protected virtual
do the actual processing
Implements Search::Wfst::Builder::Operation.
Definition at line 65 of file CreateOperations.cc.
References Fsa::count(), Bliss::Lexicon::createLemmaPronunciationToLemmaTransducer(), Bliss::Lexicon::createLemmaToSyntacticTokenTransducer(), Lm::LanguageModel::getFsa(), Bliss::Token::id(), Core::Component::log(), Ftl::StaticAutomaton< _Automaton >::maxStateId(), require, Core::Ref< T >::reset(), Fsa::staticCopy(), verify, and Core::Component::warning().
Referenced by Search::Wfst::Builder::BuildLexicon::consumeInput(), Search::Wfst::Builder::ContextBuilder::consumeInput(), Search::Wfst::Builder::HmmBuilder::consumeInput(), Search::Wfst::Builder::ConvertStateSequences::hasOutput(), Search::Wfst::Builder::LemmaMapping::nInputAutomata(), Search::Wfst::Builder::AddPronunciationWeight::nInputAutomata(), Search::Wfst::Builder::RemovePhoneDisambiguators::nInputAutomata(), and Search::Wfst::Builder::AddNonWordTokens::nInputAutomata().
The documentation for this class was generated from the following files:
CreateOperations.hh
CreateOperations.cc