Sprint: Flow::DataSource Class Reference
Flow::DataSource Class Reference
Flow::Network handling several ports.
#include <DataSource.hh>
Public Member Functions
DataSource (const Core::Configuration &c, bool loadFromFile=true)
template<class T >
bool getData (Flow::PortId out, Flow::DataPtr< T > &d)
Pulls one data object from the network.
template<class T >
bool getData (Flow::PortId out, std::vector< T > &d)
Pulls all the data object from the network.
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Public Member Functions inherited from Flow::Network
Network (const Core::Configuration &c, bool loadFromFile=true)
void buildFromString (const std::string &network)
Construct network from XML description string.
void buildFromFile (const std::string &filename)
Construct network from XML description file.
void setTypeName (const std::string &typeName)
const std::string & getTypeName () const
bool addNode (AbstractNode *node)
AbstractNode * getNode (const std::string &name)
bool addLink (const std::string &fromNodeName, const std::string &fromPortName, const std::string &toNodeName, const std::string &toPortName, u32 buffer=0)
void declareParameter (const std::string &name)
bool addParameterUse (AbstractNode *node, const std::string &name, const Core::StringExpression &value)
Register a node as user of a parameter.
bool addInput (const std::string &name)
virtual PortId getInput (const std::string &name)
Ask for an input port.
bool addOutput (const std::string &name)
virtual PortId getOutput (const std::string &name)
Ask for an output port.
const std::string & outputName (PortId out) const
void outputs (std::vector< std::pair< PortId, std::string >> &outputs) const
void activateOutput (PortId)
Prepares the output port for external usage.
virtual bool putData (PortId in, Data *d)
Put data on input port of network.
bool putEos (PortId out)
Send end-of-stream on output port.
bool putOod (PortId out)
Send out-of-data on output port.
Link * getPortLink (PortId out)
template<class T >
bool getData (PortId out, DataPtr< T > &d)
Fetch data from output port of network.
bool putAttributes (PortId, Core::Ref< const Attributes >)
Put attribute set on input node of network.
const std::string getAttribute (PortId out, const std::string &name)
Inquire an attribute on an output port of the network.
virtual bool setParameter (const std::string &name, const std::string &value)
Set node specific parameter.
virtual bool configure ()
Creates empy input attibutes for input ports without one an attribute.
virtual bool work (PortId in)
Repeats last non-data input on input port.
virtual ssize_t getRemainingDataLen (PortId out)
Returns the amount of remaining data items.
void reset ()
Resets all links and nodes.
void go ()
void setFilename (const std::string &f)
const std::string & filename () const
Public Member Functions inherited from Flow::AbstractNode
AbstractNode (const Core::Configuration &c)
virtual void Run ()
void setThreaded (bool threaded=true)
void setThreaded (const std::string &threaded)
bool isThreaded () const
virtual bool addParameter (const std::string &name, const Core::StringExpression &value)
addParameter adds a parameter to the node Constant parameters are simply delegated to setParameter, parameters dependent on network parameters are stored in parameters_.
virtual void eraseOutputAttributes ()
Erases attributes of all output links recursively over all successor nodes.
void addUnresolvedParameter (const std::string &key, const std::string &value)
Functions for saving and getting unresolved parameters.
const UnresolvedAttributes & unresolvedAttributes () const
bool operator< (const AbstractNode &n) const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Protected Types
typedef Network Precursor
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Additional Inherited Members
Public Types inherited from Flow::AbstractNode
typedef std::map< std::string, std::string > UnresolvedAttributes
Static Public Attributes inherited from Flow::AbstractNode
static const Core::ParameterBool paramThreaded
static const Core::ParameterBool paramIgnoreUnknownParameters
Protected Member Functions inherited from Flow::Network
virtual PortId nInputs () const
virtual PortId inputConnected (PortId in) const
bool validInputPort (PortId in) const
virtual PortId nOutputs () const
virtual u32 nOutputLinks (PortId out) const
bool validOutputPort (PortId out) const
virtual PortId connectInputPort (PortId, Link *)
virtual void disconnectInputLink (Link *)
virtual PortId connectOutputPort (PortId, Link *)
virtual void disconnectOutputLink (Link *)
Protected Member Functions inherited from Flow::AbstractNode
template<class T >
bool getData (Link *l, DataPtr< T > &d)
Fetch data packet from the "from" port of link.
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Flow::Network handling several ports.
Definition at line 25 of file Flow/DataSource.hh.
Member Function Documentation
template<class T > bool Flow::DataSource::getData (Flow::PortId out, Flow::DataPtr< T > & d)
Pulls one data object from the network.
Returns
is false if the port could not deliver an output object.
Definition at line 50 of file Flow/DataSource.hh.
References Flow::Network::getData().
Referenced by getData().
template<class T > bool Flow::DataSource::getData (Flow::PortId out, std::vector< T > & d)
Pulls all the data object from the network.
Returns
is false if the port could not deliver any output object.
Definition at line 58 of file Flow/DataSource.hh.
References getData().
The documentation for this class was generated from the following file:
Flow/DataSource.hh