Sprint: Search::Wfst::Builder::Minimize Class Reference
Search::Wfst::Builder::Minimize Class Reference
minimize weighted transducer
#include <FstOperations.hh>
Public Member Functions
Minimize (const Core::Configuration &c, Resources &r)
Public Member Functions inherited from Search::Wfst::Builder::SleeveOperation
SleeveOperation (const Core::Configuration &c, Resources &r)
virtual u32 nInputAutomata () const
number of automata required as input
virtual bool addInput (AutomatonRef f)
add input automaton (will be called nInputAutomata() times)
void deleteInput ()
Public Member Functions inherited from Search::Wfst::Builder::Operation
Operation (const Core::Configuration &c, Resources &r)
virtual bool consumeInput () const
should input automata be removed
virtual bool hasOutput () const
operation is expected to produce an output automaton.
AutomatonRef getResult ()
do the actual processing and create an output automaton
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Search::Wfst::Builder::SemiringDependent
SemiringType semiring () const
SemiringDependent (const Core::Configuration &c)
Static Public Member Functions
static std::string name ()
Protected Member Functions
virtual AutomatonRef process ()
do the actual processing
Protected Member Functions inherited from Search::Wfst::Builder::SleeveOperation
virtual bool precondition () const
precondition for getResult()
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Private Member Functions
template<class A >
void minimize (FstLib::VectorFst< A > *a, uint32 encodeFlags) const
Static Private Attributes
static const Core::ParameterBool paramEncodeWeights
static const Core::ParameterBool paramEncodeLabels
Additional Inherited Members
Public Types inherited from Search::Wfst::Builder::Operation
typedef Automaton * AutomatonRef
Public Types inherited from Search::Wfst::Builder::SemiringDependent
enum SemiringType { tropicalSemiring, logSemiring }
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Attributes inherited from Search::Wfst::Builder::SleeveOperation
AutomatonRef input_
Protected Attributes inherited from Search::Wfst::Builder::Operation
Resources & resources_
Core::XmlChannel timerChannel_
Core::Timer timer_
Protected Attributes inherited from Core::Configurable
Configuration config
Static Protected Attributes inherited from Search::Wfst::Builder::SemiringDependent
static const Core::Choice choiceSemiring
static const Core::ParameterChoice paramSemiring
Detailed Description
minimize weighted transducer
Definition at line 28 of file FstOperations.hh.
Member Function Documentation
Operation::AutomatonRef Minimize::process () protected virtual
do the actual processing
Implements Search::Wfst::Builder::Operation.
Definition at line 38 of file FstOperations.cc.
References Core::Component::log().
Referenced by Search::Wfst::Builder::CreateLookahead::hasOutput(), and Search::Wfst::Builder::Compose::nInputAutomata().
The documentation for this class was generated from the following files:
FstOperations.hh
FstOperations.cc