Sprint: Mm::BatchFeatureScorerBase Class Reference
Mm::BatchFeatureScorerBase Class Reference abstract
Feature scorer computing scores for multiple feature vectors in advance.
#include <BatchFeatureScorer.hh>
Classes
struct AllDensitySelector
class ContextScorer
Stores the current feature and the number of buffered features.
Public Types
typedef Core::Ref< const ContextScorer > Scorer
Public Types inherited from Mm::FeatureScorer
typedef Core::Ref< const ContextScorer > Scorer
Public Member Functions
BatchFeatureScorerBase (const Core::Configuration &c)
virtual void init (const MixtureSet &mixtureSet)=0
Initialize the internal data structures.
virtual EmissionIndex nMixtures () const
virtual void getFeatureDescription (FeatureDescription &description) const
virtual FeatureScorer::Scorer getScorer (Core::Ref< const Feature > f) const
Return a scorer for the current feature and append the given feature to the buffer.
virtual FeatureScorer::Scorer getScorer (const FeatureVector &f) const
virtual void reset () const
Clear the feature buffer and the score cache.
virtual void addFeature (const FeatureVector &f) const
Add a feature to the feature buffer.
virtual void addFeature (Core::Ref< const Feature > f) const
virtual FeatureScorer::Scorer flush () const
Return a scorer for the current feature without adding a new feature to the buffer.
virtual bool isBuffered () const
This feature scorer is buffered.
virtual bool bufferFilled () const
Return true if the feature buffer is full.
virtual bool bufferEmpty () const
Return true if the feature buffer is empty.
virtual u32 bufferSize () const
Return the number of required buffered features.
Public Member Functions inherited from Mm::FeatureScorer
FeatureScorer (const Core::Configuration &c)
virtual void getDependencies (Core::DependencySet &dependencies) const
virtual void setSegmentName (const std::string name) const
setSegmentName should be overloaded/defined in classes using embedded flow networks to create unambiguous ids for cache nodes
virtual void finalize () const
finalize should be overloaded/defined in classes using embedded flow networks to sent final end of sequence token if necessary
virtual bool hasTimeIndexedCache () const
virtual Scorer getTimeIndexedScorer (u32 time) const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Protected Member Functions
void invalidateCache (size_t pos) const
Mark the scores for all mixtures as invalid for the given buffer position.
void initialize (const MixtureSet &mixtureSet)
Fill offsets_, cached_ allocate scores_, set nMixtures_, nDensities_.
Score getScore (EmissionIndex e, u32 featureIndex, u32 length) const
virtual void setFeature (size_t pos, const FeatureVector &f) const =0
Preprocess the feature vector and store it in the feature buffer at the given position.
virtual void fillScoreCache (EmissionIndex e, u32 featureIndex, u32 length) const =0
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes
std::vector< size_t > offsets_
mapping from mixture to densities: densities for mixture m: [offsets_[m] .
std::vector< bool > cached_
is score cached? layout: (mixture 0, pos 0), ..., (mixture_0, pos bufferSize_), (mixture 1, pos 0), ..., (mixture_1, pos bufferSize_), ....
f32 * scores_
cached scores for each mixture and buffer position.
u32 paddedDimension_
u32 dimension_
u32 nMixtures_
u32 nDensities_
s32 currentFeature_
position of the current feature
s32 buffered_
number of buffered features
s32 bufferSize_
total buffer size.
Protected Attributes inherited from Core::Configurable
Configuration config
Static Protected Attributes
static const Core::ParameterInt paramBufferSize
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Detailed Description
Feature scorer computing scores for multiple feature vectors in advance.
Design is a bit crude, but this code has to be very fast and design aspects are therefore neglected.
Definition at line 34 of file Mm/BatchFeatureScorer.hh.
Member Function Documentation
void BatchFeatureScorerBase::addFeature (const FeatureVector & f) const virtual
Add a feature to the feature buffer.
Requires bufferFilled() == false.
Reimplemented from Mm::FeatureScorer.
Definition at line 46 of file Mm/BatchFeatureScorer.cc.
References require.
Referenced by getScorer().
virtual bool Mm::BatchFeatureScorerBase::bufferEmpty () const inline virtual
Return true if the feature buffer is empty.
Reimplemented from Mm::FeatureScorer.
Definition at line 133 of file Mm/BatchFeatureScorer.hh.
References buffered_.
Referenced by Nn::BatchFeatureScorer::flush().
virtual bool Mm::BatchFeatureScorerBase::bufferFilled () const inline virtual
Return true if the feature buffer is full.
Reimplemented from Mm::FeatureScorer.
Definition at line 126 of file Mm/BatchFeatureScorer.hh.
References buffered_, and bufferSize_.
Referenced by Nn::BatchFeatureScorer::addFeature(), and Nn::BatchFeatureScorer::reset().
virtual u32 Mm::BatchFeatureScorerBase::bufferSize () const inline virtual
Return the number of required buffered features.
Reimplemented from Mm::FeatureScorer.
Definition at line 140 of file Mm/BatchFeatureScorer.hh.
References bufferSize_, Core::Component::initialize(), invalidateCache(), and setFeature().
FeatureScorer::Scorer BatchFeatureScorerBase::flush () const virtual
Return a scorer for the current feature without adding a new feature to the buffer.
Should be called until bufferEmpty() == true. Requires bufferEmpty() == false.
Reimplemented from Mm::FeatureScorer.
Definition at line 89 of file Mm/BatchFeatureScorer.cc.
References require, and verify.
Referenced by getScorer().
virtual FeatureScorer::Scorer Mm::BatchFeatureScorerBase::getScorer (Core::Ref< const Feature > f) const inline virtual
Return a scorer for the current feature and append the given feature to the buffer.
The current feature may not be the same as f because of the feature buffering. Requires bufferFilled() == true.
Implements Mm::FeatureScorer.
Definition at line 88 of file Mm/BatchFeatureScorer.hh.
References addFeature(), flush(), Mm::Feature::mainStream(), and reset().
virtual void Mm::BatchFeatureScorerBase::init (const MixtureSet & mixtureSet) pure virtual
Initialize the internal data structures.
mixtureSet is not required afterwards and may be deleted.
Implemented in Mm::BatchUnrolledIntFeatureScorer, Mm::BatchPreselectionIntFeatureScorer, Mm::BatchIntFeatureScorer, Mm::BatchPreselectionFloatFeatureScorer, and Mm::BatchFloatFeatureScorer.
void BatchFeatureScorerBase::initialize (const MixtureSet & mixtureSet) protected
Fill offsets_, cached_ allocate scores_, set nMixtures_, nDensities_.
Definition at line 62 of file Mm/BatchFeatureScorer.cc.
References require.
void BatchFeatureScorerBase::invalidateCache (size_t pos) const protected
Mark the scores for all mixtures as invalid for the given buffer position.
Definition at line 56 of file Mm/BatchFeatureScorer.cc.
Referenced by bufferSize().
virtual bool Mm::BatchFeatureScorerBase::isBuffered () const inline virtual
This feature scorer is buffered.
Reimplemented from Mm::FeatureScorer.
Definition at line 119 of file Mm/BatchFeatureScorer.hh.
void BatchFeatureScorerBase::reset () const virtual
Clear the feature buffer and the score cache.
Must be called before a new feature segment is entered.
Reimplemented from Mm::FeatureScorer.
Definition at line 40 of file Mm/BatchFeatureScorer.cc.
Referenced by getScorer().
virtual void Mm::BatchFeatureScorerBase::setFeature (size_t pos, const FeatureVector & f) const protected pure virtual
Preprocess the feature vector and store it in the feature buffer at the given position.
Implemented in Mm::BatchPreselectionIntFeatureScorer, Mm::BatchIntFeatureScorer, Mm::BatchPreselectionFloatFeatureScorer, and Mm::BatchFloatFeatureScorer.
Referenced by bufferSize().
Member Data Documentation
s32 Mm::BatchFeatureScorerBase::buffered_ mutable protected
number of buffered features
Definition at line 194 of file Mm/BatchFeatureScorer.hh.
Referenced by bufferEmpty(), and bufferFilled().
s32 Mm::BatchFeatureScorerBase::bufferSize_ protected
total buffer size.
Definition at line 198 of file Mm/BatchFeatureScorer.hh.
Referenced by bufferFilled(), bufferSize(), Nn::BatchFeatureScorer::flush(), and Nn::BatchFeatureScorer::reset().
std::vector<bool> Mm::BatchFeatureScorerBase::cached_ mutable protected
is score cached? layout: (mixture 0, pos 0), ..., (mixture_0, pos bufferSize_), (mixture 1, pos 0), ..., (mixture_1, pos bufferSize_), ....
Definition at line 178 of file Mm/BatchFeatureScorer.hh.
s32 Mm::BatchFeatureScorerBase::currentFeature_ mutable protected
position of the current feature
Definition at line 190 of file Mm/BatchFeatureScorer.hh.
Referenced by Nn::BatchFeatureScorer::flush(), and Nn::BatchFeatureScorer::reset().
std::vector<size_t> Mm::BatchFeatureScorerBase::offsets_ protected
mapping from mixture to densities: densities for mixture m: [offsets_[m] .
. offsets_[m+1])
Definition at line 162 of file Mm/BatchFeatureScorer.hh.
f32* Mm::BatchFeatureScorerBase::scores_ mutable protected
cached scores for each mixture and buffer position.
same layout as cached_
Definition at line 183 of file Mm/BatchFeatureScorer.hh.
The documentation for this class was generated from the following files:
Mm/BatchFeatureScorer.hh
Mm/BatchFeatureScorer.cc