Sprint: Flf::Boundaries Class Reference
Flf::Boundaries Class Reference abstract
State Boundaries; collection of state boundary.
#include <Boundaries.hh>
Public Member Functions
virtual bool valid () const =0
false, if the lattice provides no boundaries
virtual bool valid (Fsa::StateId sid) const =0
false, if that specific boundary does not exist or is invalid, e.g.
virtual const Boundary & get (Fsa::StateId sid) const =0
return a specific boundary; for every sid a boundary is returned !valid(sid) => !get(sid).valid()
Speech::TimeframeIndex time (Fsa::StateId sid) const
undefined, if !valid(sid)
Boundary::Transit transit (Fsa::StateId sid) const
undefined, if !valid(sid)
void dumpBoundary (Fsa::StateId sid, std::ostream &os) const
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Detailed Description
State Boundaries; collection of state boundary.
Definition at line 117 of file Boundaries.hh.
Member Function Documentation
virtual const Boundary& Flf::Boundaries::get (Fsa::StateId sid) const pure virtual
return a specific boundary; for every sid a boundary is returned !valid(sid) => !get(sid).valid()
Implemented in Flf::TopologicalOrderLattice::TopologicalOrderBoundaries, Flf::StaticBoundaries, Flf::MappedBoundaries, Flf::FittingLattice::Boundaries, Flf::UnionBoundaries, and Flf::InvalidBoundaries_.
Referenced by Flf::NBestBuilder::initialize().
Speech::TimeframeIndex Flf::Boundaries::time (Fsa::StateId sid) const inline
undefined, if !valid(sid)
Definition at line 143 of file Boundaries.hh.
Referenced by Flf::ExpandTransitsNode::sync().
Boundary::Transit Flf::Boundaries::transit (Fsa::StateId sid) const inline
undefined, if !valid(sid)
Definition at line 149 of file Boundaries.hh.
Referenced by Flf::ExpandTransitsNode::sync().
virtual bool Flf::Boundaries::valid () const pure virtual
false, if the lattice provides no boundaries
Implemented in Flf::TopologicalOrderLattice::TopologicalOrderBoundaries, Flf::StaticBoundaries, Flf::MappedBoundaries, Flf::FittingLattice::Boundaries, Flf::UnionBoundaries, and Flf::InvalidBoundaries_.
Referenced by Flf::NBestBuilder::initialize(), and Flf::StaticBoundaries::set().
virtual bool Flf::Boundaries::valid (Fsa::StateId sid) const pure virtual
false, if that specific boundary does not exist or is invalid, e.g.
not set !valid() => !valid(sid) for all state id
Implemented in Flf::TopologicalOrderLattice::TopologicalOrderBoundaries, Flf::StaticBoundaries, Flf::MappedBoundaries, Flf::FittingLattice::Boundaries, Flf::UnionBoundaries, and Flf::InvalidBoundaries_.
The documentation for this class was generated from the following files:
Boundaries.hh
Boundaries.cc