Sprint: Mc::Component Class Reference
Mc::Component Class Reference
Base class scaled model combination components.
#include <Component.hh>
Public Member Functions
Component (const Core::Configuration &c)
void updateScales (ScaleUpdate update)
Updates the scale of this and the child objects.
void load ()
Loads map file and updates scales.
void setOwnScale (Scale)
Sets ownScale_ and updates scale_.
void setParentScale (Scale scale)
Updates scale_ with parent's scale (.
Scale scale () const
parent-scale * own-scale
Scale ownScale () const
Scale parentScale () const
void getDependencies (Core::DependencySet &) const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Attributes
static const Core::ParameterFloat paramScale
Protected Member Functions
virtual void distributeScaleUpdate (const ScaleUpdate &scaleUpdate)
Override this function -to perform updates after scale_ has new value -to distibute.
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Private Member Functions
void setScale (Scale ownScale, Scale parentScale, ScaleUpdate update)
Private Attributes
Scale ownScale_
original scale
Scale scale_
parent-scale * own-scale
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Base class scaled model combination components.
Definition at line 55 of file Mc/Component.hh.
Member Function Documentation
virtual void Mc::Component::distributeScaleUpdate (const ScaleUpdate & scaleUpdate) inline protected virtual
Override this function -to perform updates after scale_ has new value -to distibute.
Parameters
scaleUpdate to child objects.
scaleUpdate contains -object-name to scale map -scale of this object as parentScale
Reimplemented in Am::CombinedTransitionModel, Am::ScaledTransitionModel, Am::ClassicAcousticModel, Mm::CombinedFeatureScorer, and Speech::ModelCombination.
Definition at line 74 of file Mc/Component.hh.
void Component::load ()
Loads map file and updates scales.
Definition at line 83 of file Mc/Component.cc.
References Mc::ScaleUpdate::setMap().
Referenced by Speech::AlignmentMapAlphabet::AlignmentMapAlphabet(), Speech::AlignmentWithLinearSegmentationNode::configure(), Speech::AlignmentNode::configure(), TestApplication::main(), Speech::LmLatticeRescorerAutomaton::score(), Speech::SetAlignmentWeightsByTiedStateAlignmentWeightsNode::SetAlignmentWeightsByTiedStateAlignmentWeightsNode(), Speech::AlignmentFilterWeightsNode::setParameter(), Speech::LatticeSetProcessorRoot::signOn(), and Speech::AlignmentNode::work().
Scale Mc::Component::scale () const inline
parent-scale * own-scale
Definition at line 97 of file Mc/Component.hh.
Referenced by Lm::addLemmaScoreOmitExtension(), Search::Instance::addLmScore(), WordConditionedTreeSearch::SearchSpace::WordEndHypothesis::addLmScore(), Lm::addSyntacticTokenScore(), Mm::FeatureScorerScaling::bufferSize(), Lm::LanguageModelScaling::compileBatchRequest(), Lm::compose(), Speech::ModelCombination::distributeScaleUpdate(), Search::SearchSpace::eventuallyDeactivateTree(), Search::SearchSpace::PruningDesc::extend(), Mm::FeatureScorerScaling::flush(), Lm::LanguageModelScaling::getFsa(), Search::SearchSpace::getSentenceEnd(), Search::SearchSpace::getSentenceEndFallBack(), Search::SearchSpace::hypothesizeEpsilonPronunciations(), Speech::ModelCombination::ModelCombination(), Lm::CombineLanguageModel::score(), Lm::LanguageModelScaling::score(), Lm::CombineLanguageModel::sentenceEndScore(), Lm::LanguageModelScaling::sentenceEndScore(), and Search::SearchSpace::setAllowHmmSkips().
void Component::setOwnScale (Scale scale)
Sets ownScale_ and updates scale_.
If necessary updates the child objects.
Definition at line 92 of file Mc/Component.cc.
void Component::setParentScale (Scale scale)
Updates scale_ with parent's scale (.
Parameters
scale). If necessary updates the child objects.
Definition at line 98 of file Mc/Component.cc.
References Core::DependencySet::add().
Referenced by Speech::ModelCombination::ModelCombination().
void Component::updateScales (ScaleUpdate update)
Updates the scale of this and the child objects.
If
Parameters
update object does not contain new scale for this object, old one is kept. Passes the modified update to the child objects.
Definition at line 75 of file Mc/Component.cc.
References Core::Configurable::fullName(), and Core::Component::log().
Referenced by Speech::ModelCombination::distributeScaleUpdate().
Member Data Documentation
Scale Mc::Component::ownScale_ private
original scale
Definition at line 60 of file Mc/Component.hh.
Scale Mc::Component::scale_ private
parent-scale * own-scale
Definition at line 62 of file Mc/Component.hh.
The documentation for this class was generated from the following files:
Mc/Component.hh
Mc/Component.cc