Sprint: Signal::SegmentClustering< Model > Class Template Reference
Signal::SegmentClustering< Model > Class Template Reference
Segment Clustering.
#include <SegmentClustering.hh>
Public Member Functions
SegmentClustering (const Core::Configuration &c)
void setMinFrames (int frames)
minimum number of frames to consider the segment for segment clustering
u32 minFrames () const
void setMincluster (int value)
set the minimum number of clusters
void setMaxcluster (int value)
set the maximum number of clusters
void setThreshold (float value)
void setLambda (float value)
set penalty weight in BIC criterion, although only lambda=1 corresponds to the definition of BIC
void setAmalgamation (int value)
set bayesian amalgamation value
void setFilename (std::string value)
set the output filename to print the clustering info
void setInFile (std::string value)
set the input filename to read an existing clustering
void setAlpha (float value)
BBN proposed a log-likelihood ratio distance measure with distances between consecutive segments scaled down by a parameter alpha - is it the same value here ???
void setAlphaMax (float value)
set the minimum alpha scaling value to be used for alpha optimization in computeAlpha() method
void setAlphaMin (float value)
set the maximum alpha scaling value to be used for alpha optimization in computeAlpha() method
void setId (std::string value)
void pushBackId ()
void pushDefaultId ()
const f32 alpha () const
void initDistMatrix (std::vector< Model > &models)
Initializing distance matrix for clustering and initialize the model trackers.
void initMatrixTracker ()
void initTracker (u32 dim)
void computePenalty (std::vector< Model > &models)
computes the penalty P of the BIC criterion P = * log(N) * (1/2(d+d/2(d+1)))
f32 computeAverage (const Math::Matrix< f32 > &relativeFeature, const f32 alpha)
compute the average (score?) for a given scaling factor alpha
void computeRelativeFeatures (const std::vector< Model > &models, Math::Matrix< f32 > &relativeFeature)
compute relative features to be used for alpha optimization
void computeAlpha (std::vector< Model > &models)
compute alpha scaling value for correlation-based distance scaling
void initSegmentClustering (std::vector< Model > &models)
initializes the clustering process
void findBestPair ()
find the best two segments to be merged
void maxLinkage ()
void concatenation (std::vector< Model > &models)
void updateDistMat (std::vector< Model > &models)
void insertTracker ()
void condenseDistMatrix (std::vector< Model > &models)
merge current parent parent_ and child child_ previously determined by findBestPair() method
void loadClustering ()
void printClustering ()
const u32 findBestBIC () const
find the best segment index w.r.t.
void returnClustering ()
void clusterUpdate (std::vector< Model > &models)
void integratePredefinedClusters (std::vector< Model > &models)
std::vector< Model > filterModelsByFrames (const std::vector< Model > &models)
bool cluster (std::vector< Model > &models)
clustering of the finalized models
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Private Attributes
std::vector< Model > modelTracker_
Math::Matrix< f32 > distMatrix_
std::vector< s32 > matrixTracker_
u32 parent_
u32 child_
f32 bestscore_
Math::Vector< u32 > classid_
u32 nrsegments_
u32 nrcluster_
u32 totalframes_
u32 minframes_
u32 mincluster_
u32 maxcluster_
f32 threshold_
std::string outfile_
f32 lambda_
f32 alpha_
f32 alphaMin_
f32 alphaMax_
u32 amalgamation_
std::ifstream infile_
std::string segmentId_
std::vector< std::string > segmentIds_
std::vector< std::string > defaultIds_
std::vector< s32 > predefinedClusters_
std::vector< Tracker > mergeTracker_
Core::XmlChannel infoChannel_
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
template<class Model>
class Signal::SegmentClustering< Model >
Segment Clustering.
Todo:
: class is derive from component now, so ppplication logging should be done via the info channel
Definition at line 399 of file SegmentClustering.hh.
Constructor & Destructor Documentation
template<class Model > Signal::SegmentClustering< Model >::SegmentClustering (const Core::Configuration & c) inline
Todo:
: -99999.9 is maybe not the best value ...
Definition at line 441 of file SegmentClustering.hh.
Member Function Documentation
template<class Model > const f32 Signal::SegmentClustering< Model >::alpha () const inline
Returns
the alpha scaling parameter for the relative faeture weighting
Definition at line 524 of file SegmentClustering.hh.
template<class Model > bool Signal::SegmentClustering< Model >::cluster (std::vector< Model > & models) inline
clustering of the finalized models
Definition at line 842 of file SegmentClustering.hh.
Referenced by Signal::SegmentClusteringNode< Model >::~SegmentClusteringNode().
template<class Model > void Signal::SegmentClustering< Model >::computeAlpha (std::vector< Model > & models) inline
compute alpha scaling value for correlation-based distance scaling
Definition at line 600 of file SegmentClustering.hh.
References Core::isAlmostEqualUlp().
template<class Model > f32 Signal::SegmentClustering< Model >::computeAverage (const Math::Matrix< f32 > & relativeFeature, const f32 alpha) inline
compute the average (score?) for a given scaling factor alpha
Definition at line 571 of file SegmentClustering.hh.
template<class Model > void Signal::SegmentClustering< Model >::computePenalty (std::vector< Model > & models) inline
computes the penalty P of the BIC criterion P = * log(N) * (1/2(d+d/2(d+1)))
Definition at line 562 of file SegmentClustering.hh.
References Core::log().
template<class Model > void Signal::SegmentClustering< Model >::computeRelativeFeatures (const std::vector< Model > & models, Math::Matrix< f32 > & relativeFeature) inline
compute relative features to be used for alpha optimization
Definition at line 586 of file SegmentClustering.hh.
template<class Model > void Signal::SegmentClustering< Model >::condenseDistMatrix (std::vector< Model > & models) inline
merge current parent parent_ and child child_ previously determined by findBestPair() method
Definition at line 719 of file SegmentClustering.hh.
template<class Model > const u32 Signal::SegmentClustering< Model >::findBestBIC () const inline
find the best segment index w.r.t.
the BIC scores
Definition at line 767 of file SegmentClustering.hh.
template<class Model > void Signal::SegmentClustering< Model >::findBestPair () inline
find the best two segments to be merged
Definition at line 663 of file SegmentClustering.hh.
template<class Model > void Signal::SegmentClustering< Model >::initDistMatrix (std::vector< Model > & models) inline
Initializing distance matrix for clustering and initialize the model trackers.
Definition at line 529 of file SegmentClustering.hh.
template<class Model > void Signal::SegmentClustering< Model >::initSegmentClustering (std::vector< Model > & models) inline
initializes the clustering process
Definition at line 640 of file SegmentClustering.hh.
template<class Model > void Signal::SegmentClustering< Model >::setAlpha (float value) inline
BBN proposed a log-likelihood ratio distance measure with distances between consecutive segments scaled down by a parameter alpha - is it the same value here ???
Definition at line 499 of file SegmentClustering.hh.
template<class Model > void Signal::SegmentClustering< Model >::setAlphaMax (float value) inline
set the minimum alpha scaling value to be used for alpha optimization in computeAlpha() method
Definition at line 504 of file SegmentClustering.hh.
template<class Model > void Signal::SegmentClustering< Model >::setAlphaMin (float value) inline
set the maximum alpha scaling value to be used for alpha optimization in computeAlpha() method
Definition at line 509 of file SegmentClustering.hh.
template<class Model > void Signal::SegmentClustering< Model >::setAmalgamation (int value) inline
set bayesian amalgamation value
Definition at line 479 of file SegmentClustering.hh.
template<class Model > void Signal::SegmentClustering< Model >::setFilename (std::string value) inline
set the output filename to print the clustering info
Definition at line 484 of file SegmentClustering.hh.
template<class Model > void Signal::SegmentClustering< Model >::setInFile (std::string value) inline
set the input filename to read an existing clustering
Definition at line 489 of file SegmentClustering.hh.
template<class Model > void Signal::SegmentClustering< Model >::setLambda (float value) inline
set penalty weight in BIC criterion, although only lambda=1 corresponds to the definition of BIC
Definition at line 474 of file SegmentClustering.hh.
template<class Model > void Signal::SegmentClustering< Model >::setMaxcluster (int value) inline
set the maximum number of clusters
Definition at line 464 of file SegmentClustering.hh.
template<class Model > void Signal::SegmentClustering< Model >::setMincluster (int value) inline
set the minimum number of clusters
Definition at line 459 of file SegmentClustering.hh.
template<class Model > void Signal::SegmentClustering< Model >::setMinFrames (int frames) inline
minimum number of frames to consider the segment for segment clustering
Definition at line 450 of file SegmentClustering.hh.
The documentation for this class was generated from the following file:
SegmentClustering.hh