Sprint: Bliss::PhonemeInventory Class Reference
Bliss::PhonemeInventory Class Reference
Inventory of phonemic symbols.
#include <Phoneme.hh>
Classes
struct Internal
Public Types
typedef const Phoneme *const * PhonemeIterator
Public Member Functions
u32 nPhonemes () const
Size of the phoneme inventory.
const Phoneme * phoneme (const std::string &symbol) const
Get phoneme by symbol.
bool isValidPhonemeId (Phoneme::Id id) const
const Phoneme * phoneme (Phoneme::Id id) const
Get phoneme by ID.
std::pair< PhonemeIterator, PhonemeIterator > phonemes () const
Phoneme * newPhoneme ()
Create a new phoneme.
void assignSymbol (Phoneme *, const std::string &)
Assign a symbol to a phoneme.
void writeBinary (Core::BinaryOutputStream &) const
void writeXml (Core::XmlWriter &) const
std::set< Bliss::Phoneme::Id > parseSelection (std::string selection) const
Returns all phones which match the given phoneme selection.
Core::Ref< const PhonemeAlphabet > phonemeAlphabet () const
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Private Attributes
TokenInventory phonemes_
Internal * internal_
Friends
class PhonemeAlphabet
Detailed Description
Inventory of phonemic symbols.
Definition at line 143 of file Phoneme.hh.
Member Function Documentation
void PhonemeInventory::assignSymbol (Phoneme * pho, const std::string & sym)
Assign a symbol to a phoneme.
Definition at line 61 of file Phoneme.cc.
References require, and Bliss::Token::symbol().
Phoneme * PhonemeInventory::newPhoneme ()
Create a new phoneme.
Definition at line 55 of file Phoneme.cc.
u32 Bliss::PhonemeInventory::nPhonemes () const inline
Size of the phoneme inventory.
Definition at line 152 of file Phoneme.hh.
Referenced by Am::ClassicStateTying::createClassicStateTyingRef(), Search::SearchSpace::minimumWordEndScore(), and Search::Wfst::NonWordTokens::setNonWordPhones().
std::set< Phoneme::Id > PhonemeInventory::parseSelection (std::string selection) const
Returns all phones which match the given phoneme selection.
The selection may contain wildcards at boundaries to match multiple phonemes.
Definition at line 102 of file Phoneme.cc.
Referenced by TransitionModel::Applicator::stateType().
const Phoneme* Bliss::PhonemeInventory::phoneme (const std::string & symbol) const inline
Get phoneme by symbol.
Parameters
symbol a string containing a phoneme symbol.
Returns
the phoneme which is assigned to the symbol symbol, or 0 if none is found.
Definition at line 162 of file Phoneme.hh.
Referenced by Bliss::ContextPhonology::append(), Bliss::Pronunciation::format(), TestApplication::getUsage(), TestApplication::main(), Search::SearchSpace::minimumWordEndScore(), Search::SearchSpace::optimizeSilenceInWordLattice(), and Search::LinearSearch::Pronunciation::Pronunciation().
const Phoneme* Bliss::PhonemeInventory::phoneme (Phoneme::Id id) const inline
Get phoneme by ID.
Parameters
id the requested phoneme id. id must be a valid phoneme Id. This can be tested with isValidPhonemeId().
Returns
the phoneme with id number id.
Definition at line 176 of file Phoneme.hh.
References require.
void PhonemeInventory::writeBinary (Core::BinaryOutputStream & os) const
Todo:
PhonemeInventory::writeBinary not implemented
Definition at line 89 of file Phoneme.cc.
References defect, and Core::ref().
The documentation for this class was generated from the following files:
Phoneme.hh
Phoneme.cc