Sprint: Fsa::Alphabet Class Reference
Fsa::Alphabet Class Reference abstract
The abstract definition of an alphabet.
#include <Alphabet.hh>
Classes
class const_iterator
Iterator that should be used to traverse an alphabet.
Public Member Functions
std::string specialSymbol (LabelId index) const
Retrieve a string representation of a special label id.
LabelId specialIndex (const std::string &symbol) const
Map a string representation of a special symbol to its label id.
virtual const_iterator begin () const
Returns an iterator pointing to the first symbol.
virtual const_iterator end () const
Returns an iterator pointing behind the last symbol.
virtual LabelId next (LabelId id) const
Returns the label id of the next symbol in sequence.
virtual std::string symbol (LabelId index) const =0
Returns the string representation of a symbol.
virtual LabelId index (const std::string &symbol) const
Given a string representation of a symbol returns the label id.
virtual bool isDisambiguator (LabelId index) const
Determine wether a symbol is a disambiguator (see determinize for more details on the use of disambiguators).
virtual AlphabetTag tag (LabelId index) const
return symbol tag
virtual bool write (Core::BinaryOutputStream &o) const
Write the alphabet to BinaryOutputStream.
virtual void writeXml (Core::XmlWriter &o) const
Write the alphabet to an XmlWriter.
virtual size_t getMemoryUsed () const
Return the amount of memory used by this object.
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Detailed Description
The abstract definition of an alphabet.
An alphabet serves the purpose of mapping strings (the external representation of an alphabet) to label ids (used internally for efficiency reasons). As all objects, alphabets are reference counted and despite in the case you create an alphabet on your own, you should only handle alphabets by using the ConstAlphabetRef type.
As alphabets are virtually infinte, this interface class defines a lazy interface. Use the Alphabet::const_iterator to traverse an alphabet if you need to.
The empty string is not a valid symbol's name.
Definition at line 43 of file Alphabet.hh.
Member Function Documentation
virtual const_iterator Fsa::Alphabet::begin () const inline virtual
Returns an iterator pointing to the first symbol.
Note, that if the alphabet contains a hole in the space of label ids at the beginning the iterator must be winded to the first existing symbol.
Returns
a const iterator pointing to the first symbol or end()
Reimplemented in Am::AllophoneStateAlphabet, Fsa::StaticAlphabet, Am::AllophoneAlphabet, Bliss::PhonemeAlphabet, and Flf::UnknownAlphabet.
Definition at line 118 of file Alphabet.hh.
Referenced by Search::Wfst::Builder::CreateSubwordGrammar::process(), write(), and writeXml().
virtual const_iterator Fsa::Alphabet::end () const inline virtual
Returns an iterator pointing behind the last symbol.
This usually does not need to be overloaded except for the case you need a different internal representation of the end iterator. Currently, InvalidLabelId is being used as end iterator.
Returns
a const iterator pointing to the first symbol or end()
Reimplemented in Am::AllophoneStateAlphabet, Fsa::StaticAlphabet, Am::AllophoneAlphabet, Am::AllophoneStateAlphabet, Bliss::LemmaPronunciationAlphabet, Bliss::PhonemeAlphabet, Flf::UnknownAlphabet, Am::EmissionAlphabet, Am::EmissionAlphabet, and Bliss::TokenAlphabet.
Definition at line 130 of file Alphabet.hh.
Referenced by Search::Wfst::Builder::CreateSubwordGrammar::process(), write(), and writeXml().
virtual size_t Fsa::Alphabet::getMemoryUsed () const inline virtual
Return the amount of memory used by this object.
Returns
the amount of memory in bytes
Reimplemented in Fsa::StaticAlphabet.
Definition at line 196 of file Alphabet.hh.
Referenced by Fsa::StaticAlphabet::end().
LabelId Fsa::Alphabet::index (const std::string & symbol) const virtual
Given a string representation of a symbol returns the label id.
Parameters
symbol the string representation of a symbol
Returns
the label id of the symbol or InvalidLabelId if the string represents no valid symbol
Reimplemented in Am::AllophoneStateAlphabet, Fsa::StaticAlphabet, Am::AllophoneAlphabet, Bliss::LemmaPronunciationAlphabet, Bliss::PhonemeAlphabet, Am::EmissionAlphabet, Bliss::TokenAlphabet, and Flf::UnknownAlphabet.
Definition at line 47 of file Alphabet.cc.
Referenced by Fsa::StaticAlphabet::addIndexedSymbol(), Fsa::StaticAlphabet::addSymbol(), Fsa::StaticAlphabet::end(), Fsa::StaticAlphabet::isDisambiguator(), next(), Fsa::StaticAlphabet::next(), Fsa::Alphabet::const_iterator::operator LabelId(), Search::Wfst::Builder::CreateSubwordGrammar::process(), Fsa::StaticAlphabet::symbol(), and Fsa::StaticAlphabet::tag().
bool Fsa::Alphabet::isDisambiguator (LabelId index) const virtual
Determine wether a symbol is a disambiguator (see determinize for more details on the use of disambiguators).
Parameters
index the symbol's label id
Returns
true if the symbol is a disambiguator.
Reimplemented in Am::AllophoneStateAlphabet, Fsa::StaticAlphabet, Am::AllophoneAlphabet, Bliss::LemmaPronunciationAlphabet, Am::AllophoneStateAlphabet, Bliss::TokenAlphabet, Am::EmissionAlphabet, and Am::EmissionAlphabet.
Definition at line 58 of file Alphabet.cc.
Referenced by Fsa::StaticAlphabet::end(), next(), TransitionModel::Applicator::stateType(), write(), and writeXml().
virtual LabelId Fsa::Alphabet::next (LabelId id) const inline virtual
Returns the label id of the next symbol in sequence.
Users can savely assume that holes in the space of label ids are being skipped automatically.
Parameters
id the current symbol
Returns
the label id of the next symbol
Reimplemented in Fsa::StaticAlphabet, and Am::AllophoneStateAlphabet.
Definition at line 141 of file Alphabet.hh.
References index(), isDisambiguator(), symbol(), tag(), write(), and writeXml().
Referenced by Fsa::StaticAlphabet::end().
LabelId Fsa::Alphabet::specialIndex (const std::string & symbol) const
Map a string representation of a special symbol to its label id.
Special labels are default to all alphabets. This methods is NOT virtual as you are not allowed to change it.
Parameters
symbol the string representation of the special symbol
Returns
the label id of the special symbol
Definition at line 35 of file Alphabet.cc.
Referenced by Am::EmissionAlphabet::index(), and Fsa::Alphabet::const_iterator::operator LabelId().
std::string Fsa::Alphabet::specialSymbol (LabelId index) const
Retrieve a string representation of a special label id.
Special labels are default to all alphabets. This methods is NOT virtual as you are not allowed to change it.
Parameters
index the label id of the special symbol
Returns
the string representation of the special symbol
Definition at line 19 of file Alphabet.cc.
Referenced by Fsa::Alphabet::const_iterator::operator LabelId(), and Am::EmissionAlphabet::symbol().
virtual std::string Fsa::Alphabet::symbol (LabelId index) const pure virtual
Returns the string representation of a symbol.
Parameters
index the symbol's label id
Returns
the string representation of the symbol or an empty string if there is no symbol with that label id
Implemented in Am::AllophoneStateAlphabet, Fsa::StaticAlphabet, Am::AllophoneAlphabet, Am::AllophoneStateAlphabet, Bliss::LemmaPronunciationAlphabet, Bliss::PhonemeAlphabet, Am::EmissionAlphabet, Am::EmissionAlphabet, Bliss::TokenAlphabet, and Flf::UnknownAlphabet.
Referenced by Fsa::StaticAlphabet::addIndexedSymbol(), Fsa::StaticAlphabet::addSymbol(), Fsa::StaticAlphabet::end(), next(), Fsa::Alphabet::const_iterator::operator LabelId(), Speech::Alignment::setAlphabet(), and Fsa::StaticAlphabet::tag().
AlphabetTag Fsa::Alphabet::tag (LabelId index) const virtual
return symbol tag
Parameters
index the symbol's label id
Returns
symbol's tag
Reimplemented in Fsa::StaticAlphabet.
Definition at line 63 of file Alphabet.cc.
Referenced by Fsa::StaticAlphabet::addIndexedSymbol(), Fsa::StaticAlphabet::end(), next(), and Fsa::StaticAlphabet::tag().
bool Fsa::Alphabet::write (Core::BinaryOutputStream & o) const virtual
Write the alphabet to BinaryOutputStream.
Parameters
o the BinaryOutputStream
Returns
true if the operation was successfull for all symbols, false otherwise
Definition at line 68 of file Alphabet.cc.
References begin(), end(), and isDisambiguator().
Referenced by next().
void Fsa::Alphabet::writeXml (Core::XmlWriter & o) const virtual
Write the alphabet to an XmlWriter.
Parameters
o the XmlWriter
Returns
true if the operation was successfull for all symbols, false otherwise
Reimplemented in Am::AllophoneStateAlphabet, Am::AllophoneAlphabet, Am::AllophoneStateAlphabet, Bliss::LemmaPronunciationAlphabet, Bliss::PhonemeAlphabet, Am::EmissionAlphabet, Am::EmissionAlphabet, and Bliss::TokenAlphabet.
Definition at line 81 of file Alphabet.cc.
References begin(), end(), and isDisambiguator().
Referenced by FsaTool::getUsage(), next(), Bliss::TokenAlphabet::writeXml(), Bliss::PhonemeAlphabet::writeXml(), and Bliss::LemmaPronunciationAlphabet::writeXml().
The documentation for this class was generated from the following files:
Alphabet.hh
Alphabet.cc