Sprint: Nn::EmissionLatticeRescorer Class Reference
Nn::EmissionLatticeRescorer Class Reference
Public Member Functions
EmissionLatticeRescorer (const Core::Configuration &, bool initialize=true)
EmissionLatticeRescorer (const Core::Configuration &, Core::Ref< Am::AcousticModel >)
void setSegmentwiseFeatureExtractor (Core::Ref< Speech::SegmentwiseFeatureExtractor >)
virtual void setAlignmentGenerator (AlignmentGeneratorRef alignmentGenerator)
virtual void finalize ()
override this function to perform something when all data has been processed
Public Member Functions inherited from Speech::AcousticLatticeRescorer
AcousticLatticeRescorer (const Core::Configuration &)
virtual void signOn (Speech::CorpusVisitor &corpusVisitor)
Override this function to add triggers to the corpus visitor.
Public Member Functions inherited from Speech::AcousticLatticeRescorerBase
AcousticLatticeRescorerBase (const Core::Configuration &)
Core::Ref< Am::AcousticModel > acousticModel () const
Public Member Functions inherited from Speech::LatticeRescorer
LatticeRescorer (const Core::Configuration &)
virtual Lattice::ConstWordLatticeRef extract (Lattice::ConstWordLatticeRef, Bliss::SpeechSegment *)
Public Member Functions inherited from Speech::LatticeExtractor
LatticeExtractor (const Core::Configuration &)
const std::string & level () const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Protected Member Functions
virtual Lattice::ConstWordLatticeRef work (Lattice::ConstWordLatticeRef, Bliss::SpeechSegment *)
void logProperties () const
NeuralNetwork< f32 > & network () const
const ClassLabelWrapper & labelWrapper () const
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes
Core::Ref< Speech::SegmentwiseFeatureExtractor > segmentwiseFeatureExtractor_
Flow::PortId portId_
Protected Attributes inherited from Speech::AcousticLatticeRescorer
AlignmentGeneratorRef alignmentGenerator_
Protected Attributes inherited from Speech::AcousticLatticeRescorerBase
Core::Ref< Am::AcousticModel > acousticModel_
Protected Attributes inherited from Core::Configurable
Configuration config
Private Types
typedef Speech::AcousticLatticeRescorer Precursor
Private Attributes
const bool measureTime_
const bool checkValues_
f64 timeMemoryAllocation_
f64 timeForwarding_
f64 timeIO_
Static Private Attributes
static const Core::ParameterString paramPortName
static const Core::ParameterBool paramCheckValues
static const Core::ParameterBool paramMeasureTime
Additional Inherited Members
Public Types inherited from Speech::AcousticLatticeRescorer
typedef Core::Ref< PhonemeSequenceAlignmentGenerator > AlignmentGeneratorRef
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Static Protected Attributes inherited from Speech::LatticeExtractor
static const Core::ParameterString paramLevel
Detailed Description
Definition at line 41 of file EmissionLatticeRescorer.hh.
Member Function Documentation
void EmissionLatticeRescorer::finalize (void) virtual
override this function to perform something when all data has been processed
Reimplemented from Speech::LatticeExtractor.
Definition at line 131 of file EmissionLatticeRescorer.cc.
References Math::copy(), Core::Component::criticalError(), Core::Component::error(), Core::Component::log(), require, required_cast, Core::Application::us(), verify, and Core::Component::warning().
The documentation for this class was generated from the following files:
EmissionLatticeRescorer.hh
EmissionLatticeRescorer.cc