Sprint: Search::Wfst::LexiconBuilder Class Reference
Search::Wfst::LexiconBuilder Class Reference
Construction of the lexicon transducer.
#include <LexiconBuilder.hh>
Classes
struct Options
Public Member Functions
LexiconBuilder (const Core::Configuration &c, const Bliss::Lexicon &lexicon)
OpenFst::VectorFst * build (bool buildClosed)
construct the lexicon transducer.
void close (OpenFst::VectorFst *lexiconTransducer, bool useEmptyTokens)
build the closure.
void setGrammarDisambiguators (s32 nDisambiguators)
bool addWordDisambiguators () const
s32 nPhoneDisambiguators () const
void setInitialPhoneOffset (int offset)
s32 initialPhoneOffset () const
void setWordLabelOffset (int offset)
s32 wordLabelOffset () const
void setDisambiguatorOffset (int offset)
s32 disambiguatorOffset () const
void createSymbolTables ()
create input (phones) and output (pronunciation) symbol tables.
const OpenFst::SymbolTable * inputSymbols () const
const OpenFst::SymbolTable * outputSymbols () const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Member Functions
static std::string phoneDisambiguatorSymbol (u32 disambiguator)
Static Public Attributes
static const char * initialSuffix = "@i"
static const char * finalSuffix = "@f"
static const char * sentenceEndSymbol = "#$"
Private Types
typedef std::unordered_map< const Bliss::Pronunciation *, int, Bliss::Pronunciation::Hash, Bliss::Pronunciation::Equality > PronunciationHashMap
Private Member Functions
void addPronunciation (const Bliss::LemmaPronunciation *pron, OpenFst::Label output, bool close)
OpenFst::Label inputLabel (Bliss::Phoneme::Id phone, bool initial=false, bool final=false) const
void addDisambiguatorLoop ()
void addNonWordLoop (OpenFst::StateId s, OpenFst::Weight w)
void addOptionalNonWordArcs (OpenFst::StateId from, OpenFst::StateId to)
void addWordDisambiguatorLabels ()
void addBoundaryPhoneLabels (bool addFinal)
void addSentenceEnd (OpenFst::Label output, bool close)
void logSettings (bool buildClosed) const
OpenFst::Label phoneDisambiguator (u32 disambiguator)
void getSentenceEnd ()
find the the sentence end lemma sets sentenceEndLemma_
void getPronsWithoutNonWords (const std::vector< std::string > &lemmas)
sets pronsWithoutNonWords_
Private Attributes
const Options * options_
OpenFst::VectorFst * result_
OpenFst::SymbolTable * inputSymbols_
OpenFst::SymbolTable * outputSymbols_
NonWordTokens * nonWordTokens_
const Bliss::Lexicon & lexicon_
s32 nGrammarDisambiguators_
s32 phoneDisambiguatorOffset_
s32 nPhoneDisambiguators_
s32 initialPhoneOffset_
s32 wordLabelOffset_
s32 disambiguatorOffset_
s32 sentenceEndLemma_
OpenFst::Label silencePhone_
OpenFst::StateId initialState_
std::set< OpenFst::Label > pronsWithoutNonWords_
PronunciationHashMap homophones_
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Construction of the lexicon transducer.
For each lemma pronunciation a separate path from the initial state to a final state is created. The lexicon is not closed, i.e. no transitions from final states to the initial state are created. The closure is added using close(). Closure can be done using either only a epsilon transition or additional transitions for all lemma pronunciation with an empty syntactic token sequence (silence and noise).
Options: add empty tokens: add lemma pronunciations with empty syntactic token sequence to the lexicon transducer. mark initial phones: add an offset to all input labels (phonemes) leaving the initial state. required for the context dependency transducer construction using across-word models. add word boundary phones: add input labels word phones at the initial and final position of a pronunciation add word disambiguators: add a transition after each pronunciation with input label = wordLabelOffset() + lemma pronunciation id. intended for adding "word" labels at the word end. disambiguate homophones: add disambiguators for homophones. not required if word disambiguators are used. disambiguators are in the range disambiguatorOffset() .. disambiguatorOffset() + nPhoneDisambiguators()
Definition at line 60 of file LexiconBuilder.hh.
Member Function Documentation
OpenFst::VectorFst * LexiconBuilder::build (bool buildClosed)
construct the lexicon transducer.
Definition at line 279 of file LexiconBuilder.cc.
References close(), OpenFst::convertLabelFromFsa(), createSymbolTables(), Core::form(), getPronsWithoutNonWords(), getSentenceEnd(), Bliss::Token::id(), Bliss::Pronunciation::phonemes(), Bliss::Symbol::str(), Bliss::Token::symbol(), verify, and Core::Component::warning().
Referenced by Search::Wfst::Builder::BuildLexicon::process().
void LexiconBuilder::close (OpenFst::VectorFst * lexiconTransducer, bool useEmptyTokens)
build the closure.
requires initialPhoneOffset_
Definition at line 549 of file LexiconBuilder.cc.
References OpenFst::convertLabelFromFsa(), require, and verify.
Referenced by build(), Search::Wfst::Builder::BuildLexicon::process(), and Search::Wfst::Builder::CloseLexicon::process().
void LexiconBuilder::createSymbolTables ()
create input (phones) and output (pronunciation) symbol tables.
sets inputSymbols_, outputSymbols_ , disambiguatorOffset_, initialPhoneOffset_, wordLabelOffset_
Definition at line 236 of file LexiconBuilder.cc.
References OpenFst::convertAlphabet(), Core::Component::error(), and verify.
Referenced by build().
void LexiconBuilder::getPronsWithoutNonWords (const std::vector< std::string > & lemmas) private
sets pronsWithoutNonWords_
Definition at line 217 of file LexiconBuilder.cc.
References OpenFst::convertLabelFromFsa(), Core::Component::error(), and Bliss::Lemma::pronunciations().
Referenced by build().
void LexiconBuilder::getSentenceEnd () private
find the the sentence end lemma sets sentenceEndLemma_
Definition at line 208 of file LexiconBuilder.cc.
References Bliss::Token::id(), and verify.
Referenced by build().
The documentation for this class was generated from the following files:
LexiconBuilder.hh
LexiconBuilder.cc