Sprint: Signal::BayesClassification Class Reference
Signal::BayesClassification Class Reference
Implementation of bayes decision rule for "simple" distributions.
#include <BayesClassification.hh>
Public Types
enum AprioriProbabilityType { Uniform }
enum LikelihoodFunctionType { IndependentSequence }
typedef LikelihoodFunction::Data Data
typedef LikelihoodFunction::Score Score
typedef LikelihoodFunction::ScoreVector ScoreVector
typedef LikelihoodFunction::Weight Weight
typedef Flow::Time Time
typedef std::pair< Time, Time > StartEndTime
Public Member Functions
BayesClassification (const Core::Configuration &c)
void feed (const Flow::Vector< Data > &featureVector, Weight featureScoreWeight=1)
Accumulates the scores for.
bool classify (Flow::String &classLabel)
Carries out the classification based on accumulated scores.
bool classify (Flow::String &classLabel, const Flow::Vector< Data > &featureVector, Weight featureScoreWeight=1)
After updating scores by.
bool getScores (Flow::Vector< Score > &scores)
bool getScores (Flow::Vector< Score > &scores, const Flow::Vector< Data > &featureVector, Weight featureScoreWeight)
void reset ()
Clears accumulated results.
bool needMoreFeatureVectors () const
Have been sufficient features vectors processed?
void setAprioriProbability (AprioriProbabilityType type)
void setLikelihoodFunction (LikelihoodFunctionType type)
void setClassLabels (const std::string &fileName)
void setClassLabels (u32 nClasses)
void setNumUsedFeatures (u32 nFeatures)
void setUseSlidingWindow (bool useWindow, int windowLength, int windowRight)
u32 nClasses () const
void setDelay (u32 delay)
Decision is made only after.
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Private Types
typedef Component Predecessor
Private Member Functions
void init (size_t inputSize)
const std::string & argMin () const
Bayes decision rule.
void writeStatistics (Core::XmlWriter &, u32 minClassIndex, const Core::Statistics< Score > &) const
void updateTimes (const Flow::Timestamp &timestamp)
Updated firstStartTime_ and lastEndTime_ by using the member newData_.
Private Attributes
std::vector< std::string > classLabels_
AprioriProbability * aprioriProbability_
LikelihoodFunction * likelihoodFunction_
u32 nFeatures_
u32 nFeaturesBuffered_
u32 delay_
u32 nUsedFeatures_
bool useSlidingWindow_
SlidingWindow< ScoreVector > scoreWindow_
Scores for each feature vector in the sliding window.
SlidingWindow< StartEndTime > timeWindow_
Start and end time of the features in the sliding window.
Time firstStartTime_
Start-time of the first feature vector since the last successful classification.
Time lastEndTime_
End-time of the last feature vector.
bool newData_
function classify returns false if there came no new data since the last call to it.
bool needInit_
Core::XmlChannel statisticsChannel_
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Implementation of bayes decision rule for "simple" distributions.
Provides the class k with maximum a-posterioiry probability i.e minimum with -log(a-posterioiry probability):
argmin_{k} -log(p(k) * p(x|k)) where p(k) is the apriori probablity of the classes and p(x|k) is the class dependent likelihood function.
Definition at line 36 of file BayesClassification.hh.
Member Function Documentation
const std::string & BayesClassification::argMin () const private
Bayes decision rule.
Returns
is class label with minimal score.
Definition at line 135 of file BayesClassification.cc.
References Signal::SlidingWindow< T >::begin(), and verify.
bool BayesClassification::classify (Flow::String & classLabel)
Carries out the classification based on accumulated scores.
Result of classification is stored in
Parameters
classLabel.
Returns
is false if no features has been seen or if there came no new data since the last call.
Definition at line 80 of file BayesClassification.cc.
bool BayesClassification::classify (Flow::String & classLabel, const Flow::Vector< Data > & featureVector, Weight featureScoreWeight = 1)
After updating scores by.
Parameters
featureVector,classification is carried out. Result of classification is stored in
classLabel.
Returns
is false if decision could not be made yet (
See also
setDelay) or if there came no new data since the last call.
Definition at line 103 of file BayesClassification.cc.
References classify().
Referenced by classify().
void BayesClassification::feed (const Flow::Vector< Data > & featureVector, Weight featureScoreWeight = 1)
Accumulates the scores for.
Parameters
featureVector.
Definition at line 59 of file BayesClassification.cc.
bool BayesClassification::needMoreFeatureVectors () const
Have been sufficient features vectors processed?
Definition at line 263 of file BayesClassification.cc.
void BayesClassification::reset (void)
Clears accumulated results.
Definition at line 191 of file BayesClassification.cc.
References defect, and Core::XmlParser::parseFile().
void BayesClassification::setDelay (u32 delay)
Decision is made only after.
Parameters
delay number of features.
Definition at line 249 of file BayesClassification.cc.
void BayesClassification::updateTimes (const Flow::Timestamp & timestamp) private
Updated firstStartTime_ and lastEndTime_ by using the member newData_.
Definition at line 72 of file BayesClassification.cc.
Member Data Documentation
Time Signal::BayesClassification::firstStartTime_ private
Start-time of the first feature vector since the last successful classification.
Definition at line 70 of file BayesClassification.hh.
Time Signal::BayesClassification::lastEndTime_ private
End-time of the last feature vector.
Definition at line 73 of file BayesClassification.hh.
bool Signal::BayesClassification::newData_ private
function classify returns false if there came no new data since the last call to it.
Definition at line 77 of file BayesClassification.hh.
SlidingWindow<ScoreVector> Signal::BayesClassification::scoreWindow_ private
Scores for each feature vector in the sliding window.
Definition at line 63 of file BayesClassification.hh.
SlidingWindow<StartEndTime> Signal::BayesClassification::timeWindow_ private
Start and end time of the features in the sliding window.
Definition at line 66 of file BayesClassification.hh.
The documentation for this class was generated from the following files:
BayesClassification.hh
BayesClassification.cc