Sprint: Nn::FeedForwardTrainer< T > Class Template Reference
Nn::FeedForwardTrainer< T > Class Template Reference
Base class for all supervised feed forward trainer.
#include <FeedForwardTrainer.hh>
Public Member Functions
FeedForwardTrainer (const Core::Configuration &config)
virtual void initializeTrainer (u32 batchSize)
virtual void initializeTrainer (u32 batchSize, std::vector< u32 > &streamSizes)
virtual void finalize ()
Statistics< T > & statistics ()
returns reference to statistics
virtual void processBatch_feedInput (std::vector< NnMatrix > &features, NnVector *weights, Bliss::Segment *segment)
feed forward
virtual void processBatch_finishWithError_naturalPairing (T error, NnMatrix &errorSignal)
backprop + update model
virtual void processBatch_finishWithAlignment (Math::CudaVector< u32 > &alignment)
process mini-batch of aligned features
virtual void processBatch_finishWithSpeechSegment (Bliss::SpeechSegment &segment)
process segment
void processBatch_finishDiscard ()
virtual void logBatchTimes () const
Public Member Functions inherited from Nn::NeuralNetworkTrainer< T >
NeuralNetworkTrainer (const Core::Configuration &config)
NnMatrix & getOutputActivation ()
get activations of output layer
bool hasNetwork () const
returns whether trainer has a network
bool hasEstimator () const
returns whether trainer has an estimator
bool weightedAccumulation () const
returns whether frame weights are used
u32 batchSize () const
returns current batch size (equal to size of activations)
bool isInitialized () const
returns whether trainer is initialized
bool measuresTime () const
returns whether trainer measures computation time
Criterion< T > & criterion ()
NeuralNetwork< T > & network ()
return reference to network
const NeuralNetwork< T > & network () const
u32 nLayers () const
return reference to network
Estimator< T > & estimator ()
return reference to estimator
const Estimator< T > & estimator () const
Regularizer< T > & regularizer ()
return reference to regularizer
const Regularizer< T > & regularizer () const
void setClassWeights (const Math::Vector< T > *vector)
sets class weights to values in vector
virtual bool needsToProcessAllFeatures () const
returns whether trainer needs to process all features, i.e.
virtual bool isNetworkOutputRepresentingClassLabels ()
if we have a network, is its output layer representing the class label posterior probabilities
virtual bool hasClassLabelPosteriors ()
whether we can call getClassLabelPosteriors()
virtual NnMatrix & getClassLabelPosteriors ()
returns the posteriors after a call to processBatch_feedInput()
virtual int getClassLabelPosteriorDimension ()
returns posterior dimension
virtual bool allowsDownsampling () const
virtual void processBatch_finishWithError (T error, NnMatrix &errorSignal)
Override this method for supervised training.
virtual void processBatch_finish ()
Override this method for unsupervised training to finish a minibatch.
virtual void resetHistory ()
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Protected Types
typedef Types< T >::NnVector NnVector
typedef Types< T >::NnMatrix NnMatrix
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions
void errorBackpropagation ()
void collectGradient ()
void updateClassCounts (const Math::CudaVector< u32 > &alignment, Statistics< T > &statistics)
virtual void setBatchSize (u32 batchSize)
resize activations (necessary when batch size has changed)
virtual void initializeDoublePrecisionStatistics ()
T getNewError ()
void gradientCheck ()
template<typename Params >
void gradientCheckComponent (T grad, T *paramPtr, Params &params, u32 layerIdx)
void simpleGradientCheck (T oldError)
T getDirectionalEstimate ()
bool convergenceCheckRepeat (T &error, NnMatrix &errorSignal)
virtual void resetBatchTimes ()
template<>
void initializeDoublePrecisionStatistics ()
template<>
void initializeDoublePrecisionStatistics ()
Protected Member Functions inherited from Nn::NeuralNetworkTrainer< T >
virtual void logProperties () const
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes
const std::string statisticsFilename_
const bool useDoublePrecisionAccumulator_
Statistics< T > * statistics_
Statistics< f64 > * doublePrecisionStatistics_
bool convergenceCheck_
T convergenceCheckLearningRateFactor_
T convergenceCheckGradNormLimit_
bool gradientCheck_
T gradientCheckPerturbation_
int gradientCheckPrecision_
bool simpleGradientCheck_
bool normalizeByNOfObservations_
T errorSignalClip_
bool logFrameEntropy_
std::vector< NnMatrix > errorSignal_
std::vector< std::vector< NnMatrix * > > errorSignalOut_
s32 lowestTrainableLayerIndex_
NnVector * weights_
double timeSync_
double timeForwardPass_
double timeInitialErrorSignal_
double timeBackwardPass_
double timeGradient_
double timeBaseStatistics_
double timeRegularization_
double timeEstimation_
double timeSyncBatch_
double timeForwardPassBatch_
double timeInitialErrorSignalBatch_
double timeBackwardPassBatch_
double timeGradientBatch_
double timeBaseStatisticsBatch_
double timeRegularizationBatch_
double timeEstimationBatch_
u32 minibatchCount_
u32 discardedMinibatchCount_
Protected Attributes inherited from Nn::NeuralNetworkTrainer< T >
Criterion< T > * criterion_
bool weightedAccumulation_
const Math::Vector< T > * classWeights_
const bool measureTime_
bool needsNetwork_
Core::XmlChannel statisticsChannel_
bool needInit_
NeuralNetwork< T > * network_
Estimator< T > * estimator_
Regularizer< T > * regularizer_
Protected Attributes inherited from Core::Configurable
Configuration config
Static Protected Attributes
static const Core::ParameterString paramStatisticsFilename
static const Core::ParameterBool paramDoublePrecisionAccumulator
static const Core::ParameterBool paramConvergenceCheck
static const Core::ParameterFloat paramConvergenceCheckLearningRateFactor
static const Core::ParameterFloat paramConvergenceCheckGradNormLimit
static const Core::ParameterBool paramGradientCheck
static const Core::ParameterFloat paramGradientCheckPerturbation
static const Core::ParameterInt paramGradientCheckPrecision
static const Core::ParameterBool paramSimpleGradientCheck
static const Core::ParameterBool paramNormalizeByNOfObservations
static const Core::ParameterFloat paramErrorSignalClip
static const Core::ParameterBool paramLogFrameEntropy
Private Types
typedef NeuralNetworkTrainer< T > Precursor
Additional Inherited Members
Public Types inherited from Nn::NeuralNetworkTrainer< T >
enum TrainerType {
dummy, feedForwardTrainer, frameClassificationErrorAccumulator, meanAndVarianceAccumulator,
networkEvaluator, autoencoderTrainer, pythonTrainer, pythonEvaluator
}
Static Public Member Functions inherited from Nn::NeuralNetworkTrainer< T >
static NeuralNetworkTrainer< T > * createSupervisedTrainer (const Core::Configuration &config)
static NeuralNetworkTrainer< T > * createUnsupervisedTrainer (const Core::Configuration &config)
Static Public Attributes inherited from Nn::NeuralNetworkTrainer< T >
static const Core::Choice choiceNetworkTrainer
static const Core::ParameterChoice paramNetworkTrainer
static const Core::ParameterInt paramEpoch
static const Core::ParameterBool paramWeightedAccumulation
static const Core::ParameterBool paramMeasureTime
Detailed Description
template<class T>
class Nn::FeedForwardTrainer< T >
Base class for all supervised feed forward trainer.
Note that frame-wise training will probably use FeedForwardAlignedTrainer.
Definition at line 43 of file FeedForwardTrainer.hh.
Member Function Documentation
template<typename T > void FeedForwardTrainer::processBatch_feedInput (std::vector< NnMatrix > & features, NnVector * weights, Bliss::Segment * segment) virtual
feed forward
Reimplemented from Nn::NeuralNetworkTrainer< T >.
Reimplemented in Nn::FeedForwardAutoTrainer< T >.
Definition at line 250 of file FeedForwardTrainer.cc.
References Core::Component::warning().
Referenced by Nn::FeedForwardTrainer< f64 >::statistics().
template<typename T > void FeedForwardTrainer::processBatch_finishWithAlignment (Math::CudaVector< u32 > & alignment) virtual
process mini-batch of aligned features
Reimplemented from Nn::NeuralNetworkTrainer< T >.
Reimplemented in Nn::FeedForwardAutoTrainer< T >.
Definition at line 460 of file FeedForwardTrainer.cc.
References Core::Component::error().
Referenced by Nn::FeedForwardTrainer< f64 >::statistics().
template<typename T> void FeedForwardTrainer::processBatch_finishWithError_naturalPairing (T error, NnMatrix & errorSignal) virtual
backprop + update model
Reimplemented from Nn::NeuralNetworkTrainer< T >.
Definition at line 307 of file FeedForwardTrainer.cc.
References require.
Referenced by Nn::FeedForwardTrainer< f64 >::statistics().
template<typename T > void FeedForwardTrainer::processBatch_finishWithSpeechSegment (Bliss::SpeechSegment & segment) virtual
process segment
Reimplemented from Nn::NeuralNetworkTrainer< T >.
Definition at line 505 of file FeedForwardTrainer.cc.
References Core::Component::error().
Referenced by Nn::FeedForwardTrainer< f64 >::statistics().
template<typename T > void FeedForwardTrainer::setBatchSize (u32 batchSize) protected virtual
resize activations (necessary when batch size has changed)
Reimplemented from Nn::NeuralNetworkTrainer< T >.
Definition at line 591 of file FeedForwardTrainer.cc.
References Core::Component::log().
Referenced by Nn::FeedForwardTrainer< f64 >::statistics().
template<class T> Statistics<T>& Nn::FeedForwardTrainer< T >::statistics () inline
returns reference to statistics
Definition at line 129 of file FeedForwardTrainer.hh.
Referenced by Nn::FeedForwardTrainer< f64 >::statistics().
The documentation for this class was generated from the following files:
FeedForwardTrainer.hh
FeedForwardTrainer.cc
GradientCheck.cc