Sprint: Signal::CrossCorrelation Class Reference
Signal::CrossCorrelation Class Reference
CrossCorrelation Rxy(m) = sum_{t = max(0, -m)}^{min(sizeX_ - m, sizeY_)} similarity(x_{t + m}, y_{t})
#include <CrossCorrelation.hh>
Public Types
enum SimilarityFunctionType { Multiplication, AbsoluteDifference }
enum NormalizationType { None, UnbiasedEstimate, UpperBound }
typedef f32 Data
Public Member Functions
void apply (const std::vector< Data > &x, const std::vector< Data > &y, std::vector< Data > &Rxy)
void apply (const std::vector< Data > &x, const std::vector< Data > &y, std::vector< Data > &Rxy, Core::Component &errorChannels)
void setBegin (s32 begin)
void setEnd (s32 end)
void setSimilarityFunctionType (const SimilarityFunctionType similarityFunctionType)
void setPower (const f64 power)
void setNormalizationType (const NormalizationType normalizationType)
void setUseFastFourierTransform (const bool use)
Private Member Functions
void crossCorrelation (const std::vector< Data > &x, const std::vector< Data > &y, std::vector< Data > &Rxy)
CorssCorrelation: corss-correlation implemented in frequency domain.
template<class OperationProduct >
void crossCorrelation (const std::vector< Data > &x, const std::vector< Data > &y, std::vector< Data > &Rxy, OperationProduct product) const
CorssCorrelation: corss-correlation implemented in time domain.
template<class OperationNormalization >
void normalize (const std::vector< Data > &x, const std::vector< Data > &y, std::vector< Data > &Rxy, OperationNormalization normalization) const
void init ()
void crossCorrelationWithMultiplication (const std::vector< Data > &x, const std::vector< Data > &y, std::vector< Data > &Rxy)
void crossCorrelationWithAbsoluteDifference (const std::vector< Data > &x, const std::vector< Data > &y, std::vector< Data > &Rxy) const
void normalizeUpperBound (const std::vector< Data > &x, const std::vector< Data > &y, std::vector< Data > &Rxy) const
Private Attributes
std::vector< Data > X_
std::vector< Data > Y_
s32 begin_
Corss-correlation calculated on the interval [begin..end)
s32 end_
SimilarityFunctionType similarityFunctionType_
f64 power_
NormalizationType normalizationType_
bool useFastFourierTransform_
Detailed Description
CrossCorrelation Rxy(m) = sum_{t = max(0, -m)}^{min(sizeX_ - m, sizeY_)} similarity(x_{t + m}, y_{t})
where: "similarty" can be: multiplication: x_{t + m} * y_{t} absolute difference: |x_{t + m} - y_{t}|^power
m is element of [begin..end); begin and end are give in continuous units (e.g.: sec, Hz)
normalitions: Rxy(m) can be normalized by
number of addands: leads to unbiased estimate of cross-correlation
upper bound: leads to |Rxy(t)| <= 1
application of fast Fourier Transform: can be applied if similarity function is the multiplication. controlled over the parameter useFastFourierTransform
Definition at line 128 of file CrossCorrelation.hh.
Member Function Documentation
void CrossCorrelation::crossCorrelation (const std::vector< Data > & x, const std::vector< Data > & y, std::vector< Data > & Rxy) private
CorssCorrelation: corss-correlation implemented in frequency domain.
Definition at line 26 of file CrossCorrelation.cc.
References Core::abs(), defect, Core::Component::error(), hope, Core::isMalformed(), Signal::FastFourierTransform::length(), Signal::FastFourierTransform::outputSampleRate(), and Math::transformAlternatingComplexToAlternatingComplex().
template<class OperationProduct > void Signal::CrossCorrelation::crossCorrelation (const std::vector< Data > & x, const std::vector< Data > & y, std::vector< Data > & Rxy, OperationProduct product) const inline private
CorssCorrelation: corss-correlation implemented in time domain.
Parameters
product is a binary functor implementing an arbitrary similarity function
remark: This implementation compares only the overlapping part of the shifted x and y. It does not extend any of the signals by zeros. This does not make any difference if applying 'multiplication' as similarity function but it do make a significant difference for absolute-difference kind of similarity functions.
Definition at line 168 of file CrossCorrelation.hh.
References ensure.
Member Data Documentation
s32 Signal::CrossCorrelation::begin_ private
Corss-correlation calculated on the interval [begin..end)
Definition at line 143 of file CrossCorrelation.hh.
The documentation for this class was generated from the following files:
CrossCorrelation.hh
CrossCorrelation.cc