Sprint: Test::TestSuiteRegistry Class Reference
Test::TestSuiteRegistry Class Reference
Registry for all test cases.
#include <Registry.hh>
Public Types
typedef void(* TestMethod) ()
Public Member Functions
bool addTest (const std::string &module, const std::string &suiteName, CppUnit::Test *test)
add a test case to the given test suite.
CppUnit::Test * makeTest ()
generate a CppUnit test case including all registered test cases.
CppUnit::Test * makeTest (const std::string &module)
generate a CppUnit test case including all registered test cases for the given module.
Static Public Member Functions
static TestSuiteRegistry & instance ()
return the only TestSuiteRegistry instance (singleton)
Protected Types
typedef std::map< std::string, CppUnit::TestSuite * > SuiteMap
typedef std::map< std::string, SuiteMap > ModuleMap
Protected Attributes
ModuleMap modules_
Static Private Attributes
static TestSuiteRegistry * instance_ = 0
Detailed Description
Registry for all test cases.
Definition at line 30 of file Test/Registry.hh.
Member Function Documentation
bool TestSuiteRegistry::addTest (const std::string & module, const std::string & suiteName, CppUnit::Test * test)
add a test case to the given test suite.
Definition at line 33 of file Test/Registry.cc.
TestSuiteRegistry & TestSuiteRegistry::instance () static
return the only TestSuiteRegistry instance (singleton)
Definition at line 22 of file Test/Registry.cc.
Referenced by UnitTester::main().
CppUnit::Test * TestSuiteRegistry::makeTest ()
generate a CppUnit test case including all registered test cases.
Definition at line 48 of file Test/Registry.cc.
Referenced by UnitTester::main(), and makeTest().
CppUnit::Test * TestSuiteRegistry::makeTest (const std::string & module)
generate a CppUnit test case including all registered test cases for the given module.
Definition at line 58 of file Test/Registry.cc.
References makeTest().
The documentation for this class was generated from the following files:
Test/Registry.hh
Test/Registry.cc