Sprint: ArchiverApplication Class Reference
ArchiverApplication Class Reference
Public Member Functions
bool addFile (Archive *archive, std::istream &src, const std::string &name)
bool compareFileToArchive (Archive *archive, std::istream &src, const std::string &name)
bool writeFileToArchive (Archive *a, std::istream &src, const std::string &archiveName)
void addFile (Archive *a, const std::string &name, const std::string &archiveName)
void addDirectory (Archive *a, const std::string &name)
bool copyAllFiles (Archive *a, const std::string &name)
bool copySelectedFiles (Archive *a, StringVector::const_iterator namesBegin, StringVector::const_iterator namesEnd, Selection &selection)
bool addArchive (Archive *a, const std::string &name)
bool extractFile (Archive *a, const std::string &name, const std::string outputName="")
void loadSelection (const std::string &filename, Selection &selection)
bool showFile (Archive *a, const std::string &filename)
void showMatrix (const std::string &filename)
void showFlowCache (Archive *a, const std::string &filename)
void getStateInfo (int emission, u32 &allo, u32 &state)
int main (const std::vector< std::string > &arguments)
Main entry point for an application.
Public Member Functions inherited from Core::Application
virtual std::string getVariable () const
Return the name of the environment variable.
std::string getBaseName () const
Return the applications basename.
std::string getPath () const
Return the applications path.
virtual std::string getApplicationDescription () const
virtual std::string getParameterDescription () const
virtual std::string getDefaultParameterDescription () const
void reportLowLevelError (const std::string &msg="")
Errors messages are collected and later (during closeLogging()) printed to the error channel.
void setDefaultLoadConfigurationFile (bool f)
Configure default behaviour of loading a configuration file.
void setDefaultOutputXmlHeader (bool f)
Configure default behaviour of adding a valid xml header to standard channels.
void setTitle (const std::string &t)
Set the title of the application.
void setCommentCharacters (const std::string &c)
Set the set of possible comment characters for this application.
const std::string & getCommentCharacters (void) const
Return the string of comment characters.
Core::Channel & debugChannel (void)
Returns the debug binary outpput channel.
Core::XmlChannel & debugXmlChannel (void)
Returns the debug XML channel.
MappedArchiveReader getCacheArchiveReader (const std::string &archive_name, const std::string &item)
Returns a pointer to the cache-archive reader for the archive, and the specified item contained by the archive.
MappedArchiveWriter getCacheArchiveWriter (const std::string &archive_name, const std::string &item)
Returns a pointer to the cache-archive writer for the archive, and the specified item contained by the archive.
void exit (int status)
Terminate program execution.
void atexit (std::function< void()> f)
Like std::atexit() but will be execute sooner, at our own uninit, at the end of our main(), or in our exit().
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Private Member Functions
std::string getUsage () const
Overload this method to describe the usage of the application and to give a (short) description of the application.
Private Attributes
Mode mode_
bool verbose_
bool quiet_
bool compress_
FileType type_
bool fullPrecision_
std::vector< std::string > allophones_
OverwriteMode overwrite_
std::string prefix_
Additional Inherited Members
Static Public Member Functions inherited from Core::Application
static Application * us ()
Get the global instance of the application (Singleton)
static int main (int argc, char *argv[])
private
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Application
void logSystemInfo () const
void logVersion () const
void logResources () const
void logResourceUsage () const
void logMemoryUsage () const
MappedArchive * getCacheArchive (const std::string &archive)
void openLogging ()
Opens channels and makes initial logs.
void closeLogging (bool configAvailable=true)
Closes down channels and makes final logs.
int run (const std::vector< std::string > &arguments)
void runAtExitFuncs ()
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Static Protected Member Functions inherited from Core::Application
static bool setFromEnvironment (const std::string &variable)
static bool setFromFile (const std::string &filename)
static std::vector< std::string > setFromCommandline (const std::vector< std::string > &arguments)
Protected Attributes inherited from Core::Application
Channel::Manager * channelManager_
Core::Channel * debugChannel_
Core::XmlChannel * debugXmlChannel_
std::map< std::string, MappedArchive * > cacheArchives_
bool defaultLoadConfigurationFile_
bool defaultOutputXmlHeader_
std::string comment_
std::string configFileName_
Timer timer_
std::list< std::function< void()> > atExitFuncs_
Protected Attributes inherited from Core::Configurable
Configuration config
Static Protected Attributes inherited from Core::Application
static const ParameterBool paramLogConfiguration
static const ParameterBool paramLogResolvedResources
static const ParameterString paramConfig
static const ParameterString paramCacheArchiveFile
static const ParameterBool paramCacheArchiveReadOnly
static const ParameterBool paramHelp
static std::string path_ = "."
static std::string basename_ = ""
static Application * app_ = 0
Detailed Description
Definition at line 112 of file Archiver.cc.
Member Function Documentation
std::string ArchiverApplication::getUsage () const inline private virtual
Overload this method to describe the usage of the application and to give a (short) description of the application.
Default return string is "usage: " + getBaseName() + "[OPTION(S)]\n" Return the usage of the application.
Normally, that method does not have to be overloaded; overload getApplicationDescription() and getParamterDescription() and getDefaultParameterDescription() instead.
Reimplemented from Core::Application.
Definition at line 125 of file Archiver.cc.
References Core::Archive::create(), Core::createDirectory(), defect, Core::directoryName(), Core::form(), Core::getline(), Core::isDirectory(), Core::Channel::isOpen(), Core::joinPaths(), Core::normalizeWhitespace(), Core::ref(), Core::suppressTrailingBlank(), and verify.
int ArchiverApplication::main (const std::vector< std::string > & arguments) inline virtual
Main entry point for an application.
Implements Core::Application.
Definition at line 526 of file Archiver.cc.
References Core::baseName(), Core::Archive::create(), defect, Core::getline(), Core::log(), Core::normalizeWhitespace(), Core::Archive::recover(), and Core::suppressTrailingBlank().
The documentation for this class was generated from the following file:
Archiver.cc