Sprint: Signal::PolinomialVectorInterpolation Class Reference
Signal::PolinomialVectorInterpolation Class Reference abstract
PolinomialVectorInterpolation: creates new vectors at given target start-times by polinomial interpolation.
#include <PolinomialVectorInterpolation.hh>
Public Types
typedef Flow::Time Time
typedef Flow::Vector< f32 > Data
typedef Flow::DataPtr< Data > DataPointer
Public Member Functions
bool work (const Flow::Timestamp &time, DataPointer &out)
void setOrder (u32 order)
sets the order of interpolation polinom
std::string lastError () const
void reset ()
Static Public Member Functions
static std::string name ()
Protected Member Functions
virtual bool nextData (DataPointer &dataPointer)=0
override nextData to supply control points on demand
Private Member Functions
void seek (Time time)
Seeks in the input stream until.
bool checkInterpolationTime (Time time)
Checks if.
bool copyControlPoint (Time time, DataPointer &out) const
Avoids solving of the linear equation system for.
void resize ()
updates the size of linear equation system
void calculateParameters ()
calculates the interpolation parameters
bool calculateOutput (Time time, DataPointer &out)
creates a new element at
Private Attributes
Math::Lapack::Matrix< f64 > A_
Math::Lapack::Matrix< f64 > B_
Math::Lapack::Vector< int > pivotIndices_
std::string lastError_
SlidingWindow< DataPointer > slidingWindow_
bool equationSystemSolved_
Detailed Description
PolinomialVectorInterpolation: creates new vectors at given target start-times by polinomial interpolation.
Error messages: -there exists a target start-time outside of the input start-time interval
Definition at line 33 of file PolinomialVectorInterpolation.hh.
Member Function Documentation
bool PolinomialVectorInterpolation::calculateOutput (Time time, DataPointer & out) private
creates a new element at
Parameters
time Start and end time of
out are both set to
time!
Definition at line 103 of file PolinomialVectorInterpolation.cc.
References verify.
void PolinomialVectorInterpolation::calculateParameters () private
calculates the interpolation parameters
Definition at line 85 of file PolinomialVectorInterpolation.cc.
References defect, and verify.
bool PolinomialVectorInterpolation::checkInterpolationTime (Time time) private
Checks if.
Parameters
time does not lie outside of the input control points.
Returns
is false if -
Parameters
time is earlier than the very first input stream start-time or later then the very last input stream start-time.
Definition at line 51 of file PolinomialVectorInterpolation.cc.
References Core::form(), and verify.
bool PolinomialVectorInterpolation::copyControlPoint (Time time, DataPointer & out) const private
Avoids solving of the linear equation system for.
Parameters
time values equal to the start-time of one of the control points.
Returns
is true if
Parameters
time is equal to the start-time of one of the control points. If a control point is found, it is copied to
out.
Definition at line 63 of file PolinomialVectorInterpolation.cc.
References Signal::SlidingWindow< T >::end(), and Core::isAlmostEqual().
virtual bool Signal::PolinomialVectorInterpolation::nextData (DataPointer & dataPointer) protected pure virtual
override nextData to supply control points on demand
void PolinomialVectorInterpolation::resize () private
updates the size of linear equation system
Definition at line 78 of file PolinomialVectorInterpolation.cc.
References verify.
void PolinomialVectorInterpolation::seek (Time time) private
Seeks in the input stream until.
Parameters
time is found.
At the beginning slidingWindow_ is filled to its maximum size. After end-of-stream the last elements in the slidingWindow_ are kept until reset() is called. After seeking slidingWindow_ contains contol points directly left and right from the
Parameters
time.
Definition at line 38 of file PolinomialVectorInterpolation.cc.
void PolinomialVectorInterpolation::setOrder (u32 order)
sets the order of interpolation polinom
Definition at line 119 of file PolinomialVectorInterpolation.cc.
bool PolinomialVectorInterpolation::work (const Flow::Timestamp & time, DataPointer & out)
Returns
is the vector created by interpolation at
Parameters
time If
time is found in the input stream: start-time and end-time are delivered un-changed Else: start-time and end-time of a predicted output are both set to
time. If
Returns
false call lastError() to get a explanation.
Definition at line 26 of file PolinomialVectorInterpolation.cc.
The documentation for this class was generated from the following files:
PolinomialVectorInterpolation.hh
PolinomialVectorInterpolation.cc