Sprint: Signal::ScatterTransform Class Reference
Signal::ScatterTransform Class Reference
Base class for scatter matrix based tranformations.
#include <ScatterTransform.hh>
Public Types
typedef Math::EigenvalueProblem::ValueType EigenType
typedef Math::Matrix< f32 > TransformationMatrix
Public Member Functions
ScatterTransform (const Core::Configuration &c, const std::string &transformationTypename)
Consturctor.
const TransformationMatrix & transform () const
bool write ()
Saves the transformation matrix under name given by param paramTransformationFilename;.
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Protected Member Functions
bool work ()
Performs final steps of calculating the transformation.
bool readScatterMatrix (const std::string &filename, const std::string &scatterType, ScatterMatrix &scatterMatrix) const
void writeScatterMatrix (Core::XmlWriter &os, const std::string &scatterType, const ScatterMatrix &scatterMatrix, Math::EigenvalueProblem *eigenvalueProblem=0) const
Writes given scatter matrix to the output stream.
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes
TransformationMatrix transform_
TransformationMatrix::Type transformScale_
Protected Attributes inherited from Core::Configurable
Configuration config
Static Protected Attributes
static const Core::ParameterInt paramOutputPrecision
static const Core::ParameterString paramTotalScatterFilename
static const Core::ParameterString paramBetweenClassScatterFilename
static const Core::ParameterString paramWithinClassScatterFilename
Private Types
typedef Core::Component Precursor
Private Attributes
const Core::ParameterString paramTransformationFilename
Static Private Attributes
static const Core::ParameterFloat paramTransformScale
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Detailed Description
Base class for scatter matrix based tranformations.
Features: -Basic I/O
Definition at line 29 of file ScatterTransform.hh.
Constructor & Destructor Documentation
ScatterTransform::ScatterTransform (const Core::Configuration & c, const std::string & transformationTypename)
Consturctor.
transformationTypename specifies the parameter name of the output file. E.g.: projector-matrix, normalization, etc.
Definition at line 34 of file ScatterTransform.cc.
Member Function Documentation
bool ScatterTransform::work () protected
Performs final steps of calculating the transformation.
Steps: -scaling
Definition at line 42 of file ScatterTransform.cc.
Referenced by writeScatterMatrix().
bool ScatterTransform::write ()
Saves the transformation matrix under name given by param paramTransformationFilename;.
Definition at line 48 of file ScatterTransform.cc.
References Core::Component::error(), and Core::Component::log().
Referenced by FeatureStatistics::main(), AcousticModelTrainer::showMixtureSet(), and writeScatterMatrix().
void ScatterTransform::writeScatterMatrix (Core::XmlWriter & os, const std::string & scatterType, const ScatterMatrix & scatterMatrix, Math::EigenvalueProblem * eigenvalueProblem = 0) const protected
Writes given scatter matrix to the output stream.
scatterType is used when creating XML tag names. If eigenvalueProblem not zero, eigenvalues of scatter matrix are dumped as well.
Definition at line 72 of file ScatterTransform.cc.
References Core::abs(), Core::Component::error(), Core::Component::log(), Math::EigenvalueProblem::solveSymmetricAndFinalize(), Math::Vector< T, P >::takeReciprocal(), Math::Vector< T, P >::takeSquareRoot(), work(), and write().
The documentation for this class was generated from the following files:
ScatterTransform.hh
ScatterTransform.cc