Sprint: Math::LevinsonLeastSquares Class Reference
Math::LevinsonLeastSquares Class Reference
Levinson algorithm to estimate all-pole linear predication parameters.
#include <LevinsonLse.hh>
Public Types
typedef f64 Data
typedef f32 InputData
Public Member Functions
bool work (const std::vector< InputData > &R)
Performs the Levinson algorithm on the autocorrelation coeffitients (.
Data gain () const
Retrieves calculated parameter gain.
template<class T >
void a (std::vector< T > &result) const
Retrieves calculated parameters a1..aN.
Data predictionError () const
Retrieves remaining prediction error.
Private Member Functions
void setOrder (size_t)
size_t order () const
Private Attributes
Vector< Data > E_
Vector< Data > k_
Matrix< Data > alpha_
Detailed Description
Levinson algorithm to estimate all-pole linear predication parameters.
y[n] = gain delta(t) - a1 y[n-1] - a2 y[n-1] - ... - aN y[n-N] Algorithm see in Rabiner-Schafer: Digital Processing of Speech Signal, 1978, page 411.
Definition at line 26 of file LevinsonLse.hh.
Member Function Documentation
template<class T > void Math::LevinsonLeastSquares::a (std::vector< T > & result) const
Retrieves calculated parameters a1..aN.
Definition at line 63 of file LevinsonLse.hh.
Referenced by gain().
Data Math::LevinsonLeastSquares::gain () const inline
Retrieves calculated parameter gain.
Definition at line 50 of file LevinsonLse.hh.
References a(), and predictionError().
Data Math::LevinsonLeastSquares::predictionError () const inline
Retrieves remaining prediction error.
Definition at line 57 of file LevinsonLse.hh.
Referenced by gain().
bool LevinsonLeastSquares::work (const std::vector< InputData > & R)
Performs the Levinson algorithm on the autocorrelation coeffitients (.
Parameters
R)
Definition at line 34 of file LevinsonLse.cc.
References Core::isAlmostEqual(), and require.
The documentation for this class was generated from the following files:
LevinsonLse.hh
LevinsonLse.cc