Sprint: Bliss::Symbol Class Reference
Bliss::Symbol Class Reference
Symbols are character strings which are collected in a SymbolSet.
#include <Symbol.hh>
Classes
struct Equality
struct Hash
Public Types
typedef char Char
typedef std::string String
Public Member Functions
Symbol (const Symbol &_s)
bool operator== (const Symbol &rhs) const
bool operator!= (const Symbol &rhs) const
size_t length () const
operator bool () const
Test if symbol is not void.
bool operator! () const
Test if symbol is void.
const Char * str () const
C string (zero-terminated character pointer)
operator String () const
C++ string.
Static Public Member Functions
static Symbol cast (void *p)
Protected Member Functions
Symbol (const Char *_s)
Private Attributes
const Char * s
Friends
class SymbolSet
std::ostream & operator<< (std::ostream &os, const Bliss::Symbol &s)
Core::XmlWriter & operator<< (Core::XmlWriter &xw, const Bliss::Symbol &s)
Detailed Description
Symbols are character strings which are collected in a SymbolSet.
Copying and equality test is very efficient. Two Symbols from different SymbolSets are un-equal, even if their strings are the same (This is a feature, not a bug!). A special void symbol is created by the default constructor, any other symbol can only be created by a SymbolSet or by copying.
Implementation: A Symbol is just a char pointer into the SymbolSet. Since a SymbolSet contains each character string at most once, Symbols can be compared and hashed very efficiently by looking at the pointers only.
Definition at line 45 of file Symbol.hh.
Member Function Documentation
Bliss::Symbol::operator bool () const inline
Test if symbol is not void.
Definition at line 75 of file Symbol.hh.
Bliss::Symbol::operator String () const inline
C++ string.
Definition at line 89 of file Symbol.hh.
References str().
bool Bliss::Symbol::operator! () const inline
Test if symbol is void.
Definition at line 79 of file Symbol.hh.
const Char* Bliss::Symbol::str () const inline
C string (zero-terminated character pointer)
Definition at line 84 of file Symbol.hh.
Referenced by Search::Wfst::LexiconBuilder::build(), Lm::BackingOffLm::Internal::draw(), Flf::UnknownAlphabet::end(), TestApplication::getUsage(), operator String(), Flf::EditDistance::operator()(), Search::SearchSpace::optimizeSilenceInWordLattice(), and Search::Wfst::Builder::CheckLabels::process().
The documentation for this class was generated from the following file:
Symbol.hh