Sprint: Am::Module_ Class Reference
Am::Module_ Class Reference
Classes
class ClassicStateTyingFactory
Public Member Functions
Core::Ref< AcousticModel > createAcousticModel (const Core::Configuration &, Bliss::LexiconRef, AcousticModel::Mode=AcousticModel::complete)
Creates and initializes a AcousticModel as configured.
template<class T >
void registerStateTying (ClassicAcousticModel::StateTyingType id)
ClassicStateTying * getStateTying (ClassicAcousticModel::StateTyingType id, const Core::Configuration &c, ClassicStateModelRef m)
Private Types
enum Type { typeClassic, typeAdapted, typeFastAdapted, typeCombined }
Private Attributes
ClassicStateTyingFactory stateTyingFactory_
Static Private Attributes
static const Core::Choice choiceAmType
static const Core::ParameterChoice paramAmType
Detailed Description
Definition at line 26 of file Am/Module.hh.
Member Function Documentation
Core::Ref< AcousticModel > Module_::createAcousticModel (const Core::Configuration & c, Bliss::LexiconRef l, AcousticModel::Mode mode = AcousticModel::complete)
Creates and initializes a AcousticModel as configured.
Returns
a newly created instance of AcousticModel or 0 if an error occured.
Definition at line 51 of file Am/Module.cc.
References defect, Core::Component::hasFatalErrors(), Core::Component::log(), Core::ref(), Core::Ref< T >::reset(), and Core::Application::us().
The documentation for this class was generated from the following files:
Am/Module.hh
Am/Module.cc