Sprint: Flow::AbstractNode Class Reference
Flow::AbstractNode Class Reference abstract
Abstract flow network node.
#include <AbstractNode.hh>
Public Types
typedef std::map< std::string, std::string > UnresolvedAttributes
Public Member Functions
AbstractNode (const Core::Configuration &c)
virtual void Run ()
void setThreaded (bool threaded=true)
void setThreaded (const std::string &threaded)
bool isThreaded () const
virtual bool addParameter (const std::string &name, const Core::StringExpression &value)
addParameter adds a parameter to the node Constant parameters are simply delegated to setParameter, parameters dependent on network parameters are stored in parameters_.
virtual bool setParameter (const std::string &name, const std::string &value)
Set node specific parameter.
virtual void eraseOutputAttributes ()
Erases attributes of all output links recursively over all successor nodes.
virtual bool configure ()=0
Performs static (independent of input data) configuration of node.
virtual bool work (PortId out)=0
Process some data.
virtual ssize_t getRemainingDataLen (PortId out)
Returns the amount of remaining data items.
void addUnresolvedParameter (const std::string &key, const std::string &value)
Functions for saving and getting unresolved parameters.
const UnresolvedAttributes & unresolvedAttributes () const
bool operator< (const AbstractNode &n) const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Attributes
static const Core::ParameterBool paramThreaded
static const Core::ParameterBool paramIgnoreUnknownParameters
Protected Member Functions
virtual PortId getInput (const std::string &)=0
Ask for an input port.
virtual PortId connectInputPort (PortId, Link *)=0
virtual void disconnectInputLink (Link *)=0
virtual PortId getOutput (const std::string &)=0
Ask for an output port.
virtual PortId connectOutputPort (PortId, Link *)=0
virtual void disconnectOutputLink (Link *)=0
virtual PortId nInputs () const =0
virtual PortId inputConnected (PortId in) const =0
virtual PortId nOutputs () const =0
virtual u32 nOutputLinks (PortId port) const =0
template<class T >
bool getData (Link *l, DataPtr< T > &d)
Fetch data packet from the "from" port of link.
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Private Types
typedef Core::StringHashMap< Core::StringExpression > Parameters
Private Member Functions
bool setNetworkParameter (const std::string &parameterName, const std::string &networkParameterName, const std::string &networkParameterValue)
setNetworkParameter is called by the Network if a network parameter gets a new value.
bool checkAndSetParameter (const std::string &name, const std::string &value)
Calls setParameter; return true if parameter is succesfully set or unknown parameters are allowed.
Private Attributes
bool threaded_
bool ignoreUnknownParameters_
Parameters parameters_
UnresolvedAttributes dumpParameters_
Friends
class Network
std::ostream & operator<< (std::ostream &o, const AbstractNode &n)
std::ostream & operator<< (std::ostream &o, const AbstractNode *n)
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Abstract flow network node.
stores the unresolved attributes of
<node>
-tags provided in the Flow-file for the reasons of further serialization
serialization-related members are:
unresolvedParameters_ : map<string,string> - stores the attributes
addUnresolvedAttribute(key, value) - adds a new attribute
unresolvedAttributes() - returns the stored attributes
Definition at line 38 of file AbstractNode.hh.
Member Function Documentation
bool AbstractNode::addParameter (const std::string & name, const Core::StringExpression & value) virtual
addParameter adds a parameter to the node Constant parameters are simply delegated to setParameter, parameters dependent on network parameters are stored in parameters_.
The setParameter is called, if the configuration can resolve the parameter.
Definition at line 66 of file AbstractNode.cc.
References defect, Core::Component::error(), Core::StringExpression::isConstant(), and Core::StringExpression::value().
Referenced by Flow::NodeBuilder::createNode(), and getData().
void AbstractNode::addUnresolvedParameter (const std::string & key, const std::string & value)
Functions for saving and getting unresolved parameters.
Definition at line 155 of file AbstractNode.cc.
Referenced by getRemainingDataLen(), and Flow::Network::reset().
bool AbstractNode::checkAndSetParameter (const std::string & name, const std::string & value) private
Calls setParameter; return true if parameter is succesfully set or unknown parameters are allowed.
It would be better to make sure that checkAndSetParameter is only called when parameters changed
Definition at line 46 of file AbstractNode.cc.
References Core::Configuration::get(), and Core::Component::warning().
virtual bool Flow::AbstractNode::configure () pure virtual
Performs static (independent of input data) configuration of node.
Configure is called if one of the output attributes is not available. Override this function to evaluate all input attributes and pass them on to successor nodes. Note: we assume no dead inputs here.
Implemented in Flow::SimpleFunctionNode< Function >, Flow::Network, Speech::LatticeDumpCtmNode, Signal::QuantileEqualizationNode, Speech::LatticeNBestNode, Signal::CrossCorrelationNode, Signal::NormalizationNode, Speech::SetAlignmentWeightsByTiedStateAlignmentWeightsNode, Signal::SilenceDetectionNode, Speech::AlignmentRemoveEmissionScoreNode, Signal::GammaToneNode, Signal::FilterBankNode, Signal::VectorCutNode< Algorithm >, Speech::AcousticLatticeRescorerNode, Speech::LatticeTransform2Node, Signal::FastFourierTransformNode< Algorithm >, Speech::LatticeTransformNode, Speech::AlignmentToSequenceSelectionNode, Signal::VectorNormalizationNode< NormalizationFunction >, Speech::LatticeSimpleModifyNode, Signal::WindowingFirFilterNode, Flow::CacheNode, Audio::SinkNode, Signal::BayesClassificationNode, Signal::ComplexVectorFunctionNode< Function >, Signal::MrastaFilteringNode, Signal::DcDetectionNode, Speech::SoftFramePhoneAccuracyLatticeRescorerNode, Flow::Node, Speech::AlignmentDumpNode, Signal::CosineTransformNode, Speech::LatticeSemiringNode, Signal::LinearFilterNode, Speech::BinaryAlignmentTransformNode, Signal::HarmonicSumNode, Signal::PeakDetectionNode, Signal::SampleNormalizationNode, Audio::SourceNode, Signal::SilenceNormalizationNode, Flow::SynchronizationNode< Algorithm >, Signal::TemporalPatternNode, Speech::LatticeWriteNode, Flow::TypedDisaggregateNode< T >, Signal::SegmentwiseFormantExtractionNode, Signal::HistogramNormalizationNode, Signal::NthOrderFeaturesNode, Flow::TypeConverterNode< C >, Flow::VectorScalarFunctionNode< Function >, Flow::VectorMalformedNode< T, Policy >, Speech::AlignmentNode, Signal::DelayNode, Speech::ApproximateDistanceLatticeRescorerNode, Signal::AutocorrelationToAutoregressionNode, Flow::AggregationNode, Speech::LatticeIoNode, Signal::MatrixMultiplicationNode< T >, Speech::FeatureShiftAdaptor, Signal::TemporalIntegrationNode, Flow::CollectorNode< I, O >, Nn::NeuralNetworkForwardNode, Flow::CollectorNode< Vector< T >, Vector< T > >, Flow::CollectorNode< Aggregate::DataType, Aggregate >, Flow::CollectorNode< TypedAggregate< T >::DataType, TypedAggregate< T > >, Flow::CollectorNode< Flow::Vector< f32 >, Flow::Vector< f32 > >, Signal::SpectralIntegrationNode, Signal::WindowNode, Signal::ContinuousVectorTransformNode, Flow::DemoNode, Signal::LinearWarpingNode, Speech::ModelCombinationNode, Speech::LatticeArcAccumulatorNode, Signal::MeanEstimatorNode, Signal::AutoregressionToSpectrumNode, Signal::PreemphasisNode, Speech::SegmentwiseFeaturesNode, Flow::CoprusKeyMapNode, Flow::VectorSplitNode< T >, Signal::AllPolesPowerSpectrumNode, Signal::RandomVectorNode, Speech::AlignmentWithLinearSegmentationNode, Flow::VectorSelectNode< T >, Speech::AlignmentBaseNode, Flow::VectorAbsValDumpNode< content >, Signal::AutoregressionToCepstrumNode, Signal::VectorResizeNode< T >, Flow::SequenceFilterNode, Flow::VectorTextInputNodeBase, Flow::VectorDemultiplexNode< T >, Signal::VectorSequenceAggregation< T >, Flow::CutterNode, Signal::VectorSequenceConcatenation< T >, Signal::GenericWarpingNode, Speech::AlignmentFromLatticeNode, Flow::VectorConcatNode< T >, Signal::LinearPredictionCodingNode, Signal::ProjectionNode< T >, Flow::WarpTimeFilterNode, Speech::StatePosteriorFeatureScorerNode, Flow::MergerNode< I, O >, Flow::MergerNode< Vector< T >, Vector< T > >, Flow::MergerNode< Aggregate::DataType, Aggregate >, Flow::MergerNode< TypedAggregate< T >::DataType, TypedAggregate< T > >, Flow::MergerNode< Flow::Vector< f32 >, Flow::Vector< f32 > >, Speech::SegmentNode, Speech::FeatureScorerNode, Speech::LatticeRescorerNode, Signal::SleeveNode, Speech::AlignmentGeneratorNode, and Speech::AlignmentTransformNode.
Referenced by Flow::Network::configureOutputPort(), eraseOutputAttributes(), and Flow::Node::getInputAttributes().
virtual void Flow::AbstractNode::eraseOutputAttributes () inline virtual
Erases attributes of all output links recursively over all successor nodes.
Signals that node needs the get reconfigured.
Reimplemented in Flow::Node.
Definition at line 160 of file AbstractNode.hh.
References configure(), and work().
Referenced by Flow::Node::eraseOutputAttributes().
template<class T > bool Flow::AbstractNode::getData (Link * l, DataPtr< T > & d) inline protected
Fetch data packet from the "from" port of link.
Parameters
l.
d data pointer to which retrieved packet is attached
Returns
true on success, or false if the out-of-data
Definition at line 107 of file AbstractNode.hh.
References addParameter(), Core::Component::error(), Core::TsRef< T >::reset(), and work().
Referenced by Flow::Node::getData(), and Flow::Network::getData().
virtual PortId Flow::AbstractNode::getInput (const std::string &) protected pure virtual
Ask for an input port.
Implement this function to provide a mapping form names to port IDs. Consider using a Core::Choice. Remeber to create ports using addInput().
Returns
a valid port ID or IllegalPortId if there is to such port.
Implemented in Speech::LatticeDumpCtmNode, Flow::Network, Signal::CrossCorrelationNode, Speech::SetAlignmentWeightsByTiedStateAlignmentWeightsNode, Speech::AlignmentRemoveEmissionScoreNode, Signal::GammaToneNode, Signal::FilterBankNode, Signal::WarpingNode, Speech::LatticeTransform2Node, Speech::AcousticLatticeRescorerNode, Flow::SleeveNode, Speech::AlignmentToSequenceSelectionNode, Flow::SinkNode, Signal::WindowingFirFilterNode, Speech::AlignmentMultiplyAlignmentsNode, Flow::CacheNode, Signal::BayesClassificationNode, Audio::SinkNode, Signal::LinearFilterNode, Signal::CosineTransformNode, Speech::AlignmentDumpNode, Flow::Node, Signal::PeakDetectionNode, Speech::LatticeWriteNode, Flow::SynchronizationNode< Algorithm >, Flow::TypedDisaggregateNode< T >, Signal::HistogramNormalizationNode, Signal::DelayNode, Speech::ApproximateDistanceLatticeRescorerNode, Signal::MatrixMultiplicationNode< T >, Tensorflow::TensorflowOverlappingForwardNode, Flow::CollectorNode< I, O >, Flow::CollectorNode< Vector< T >, Vector< T > >, Flow::CollectorNode< Aggregate::DataType, Aggregate >, Flow::CollectorNode< TypedAggregate< T >::DataType, TypedAggregate< T > >, Flow::CollectorNode< Flow::Vector< f32 >, Flow::Vector< f32 > >, Flow::DemoNode, Speech::FeatureShiftAdaptor, Signal::LinearWarpingNode, Flow::StringExpressionNode, Speech::LatticeArcAccumulatorNode, Speech::SegmentwiseFeaturesNode, Signal::LinearPredictionCodingNode, Flow::SequenceFilterNode, Signal::GenericWarpingNode, Speech::AlignmentFromLatticeNode, Signal::ProjectionNode< T >, Tensorflow::TensorflowForwardNode, Flow::WarpTimeFilterNode, Speech::LatticeRescorerNode, Speech::AlignmentGeneratorNode, and Flow::RepeaterNode.
Referenced by Flow::Network::addParameterUse(), and Flow::Network::connectNodeInput().
virtual PortId Flow::AbstractNode::getOutput (const std::string &) protected pure virtual
Ask for an output port.
Implement this function to provide a mapping form names to port IDs. Consider using a Core::Choice. Remeber to create ports using addOutput().
Returns
a valid port ID or IllegalPortId if there is to such port.
Implemented in Flow::Network, Signal::CrossCorrelationNode, Signal::SilenceDetectionNode, Signal::GammaToneNode, Signal::FilterBankNode, Signal::WarpingNode, Flow::SleeveNode, Flow::SourceNode, Speech::AlignmentToSequenceSelectionNode, Flow::CacheNode, Audio::SinkNode, Signal::CosineTransformNode, Speech::AlignmentDumpNode, Flow::Node, Signal::PeakDetectionNode, Audio::SourceNode, Flow::SynchronizationNode< Algorithm >, Flow::TypedDisaggregateNode< T >, Signal::HistogramNormalizationNode, Signal::SegmentwiseFormantExtractionNode, Signal::DelayNode, Signal::MatrixMultiplicationNode< T >, Speech::FeatureShiftAdaptor, Flow::DemoNode, Flow::VectorSplitNode< T >, Signal::VectorSequenceAggregation< T >, Signal::VectorSequenceConcatenation< T >, Flow::SequenceFilterNode, Signal::LinearPredictionCodingNode, Signal::ProjectionNode< T >, Tensorflow::TensorflowForwardNode, Flow::WarpTimeFilterNode, and Flow::RepeaterNode.
Referenced by Flow::Network::connectNodeOutput(), and Flow::Network::connectOutputFromInside().
virtual ssize_t Flow::AbstractNode::getRemainingDataLen (PortId out) inline virtual
Returns the amount of remaining data items.
Should be fast.
Returns
-1 if not possible to calculate.
Reimplemented in Flow::Network, and Flow::CacheNode.
Definition at line 182 of file AbstractNode.hh.
References addUnresolvedParameter().
bool AbstractNode::setNetworkParameter (const std::string & parameterName, const std::string & networkParameterName, const std::string & networkParameterValue) private
setNetworkParameter is called by the Network if a network parameter gets a new value.
It sets the corresponding parameters and calls setParameter for all the entirely resolved parameters.
Parameters
key is the key of the parameter
networkParameterName is the key of the network parameter
networkParameterValue is the value of the network parameter
Returns
is false if key does not contain this variable
Definition at line 87 of file AbstractNode.cc.
References defect, Core::Component::error(), and verify.
virtual bool Flow::AbstractNode::setParameter (const std::string & name, const std::string & value) inline virtual
Set node specific parameter.
Implement this template function to handle parameters specific to your Node.
Parameters
name name of parameter
value new value for the parameter
Returns
true if successful, false if parameter name is not understood.
Reimplemented in Signal::SegmentClusteringNode< Model >, Flow::SimpleFunctionNode< Function >, Flow::Network, Speech::LatticeDumpCtmNode, Speech::LatticeNBestNode, Signal::CrossCorrelationNode, Signal::QuantileEqualizationNode, Signal::NormalizationNode, Speech::SetAlignmentWeightsByTiedStateAlignmentWeightsNode, Signal::GammaToneNode, Signal::FilterBankNode, Signal::WarpingNode, Signal::SilenceDetectionNode, Signal::VectorCutNode< Algorithm >, Signal::FastFourierTransformNode< Algorithm >, Speech::AlignmentAddWeightNode, Speech::AlignmentToSequenceSelectionNode, Speech::AlignmentMultiplyWeightsNode, Signal::VectorNormalizationNode< NormalizationFunction >, Speech::LatticeSimpleModifyNode, Signal::ComplexVectorFunctionNode< Function >, Signal::WindowingFirFilterNode, Signal::MrastaFilteringNode, Flow::CacheNode, Signal::BayesClassificationNode, Signal::DcDetectionNode, Speech::AlignmentDumpNode, Signal::CosineTransformNode, Signal::LinearFilterNode, Speech::LatticeSemiringNode, Signal::HarmonicSumNode, Signal::PeakDetectionNode, Signal::SampleNormalizationNode, Flow::SynchronizationNode< Algorithm >, Signal::SilenceNormalizationNode, Signal::TemporalPatternNode, Speech::AlignmentResetWeightsNode, Audio::SourceNode, Signal::SegmentwiseFormantExtractionNode, Signal::HistogramNormalizationNode, Signal::NthOrderFeaturesNode, Flow::VectorScalarFunctionNode< Function >, Speech::AlignmentFilterWeightsNode, Signal::DelayNode, Signal::RegressionNode, Speech::CorpusProcessorNode< CorpusProcessorType >, Speech::FeatureShiftAdaptor, Signal::MatrixMultiplicationNode< T >, Speech::LatticeIoNode, Tensorflow::TensorflowOverlappingForwardNode, Signal::TemporalIntegrationNode, Nn::NeuralNetworkForwardNode, Flow::CollectorNode< I, O >, Flow::CollectorNode< Vector< T >, Vector< T > >, Flow::CollectorNode< Aggregate::DataType, Aggregate >, Flow::CollectorNode< TypedAggregate< T >::DataType, TypedAggregate< T > >, Flow::CollectorNode< Flow::Vector< f32 >, Flow::Vector< f32 > >, Signal::SpectralIntegrationNode, Signal::ContinuousVectorTransformNode, Signal::WindowNode, Audio::Node, Flow::DemoNode, Signal::LinearWarpingNode, Speech::AlignmentGammaCorrectionNode, Signal::VectorResizeNode< T >, Signal::AutoregressionToSpectrumNode, Speech::ModelCombinationNode, Signal::AllPolesPowerSpectrumNode, Signal::PreemphasisNode, Flow::CoprusKeyMapNode, Signal::RandomVectorNode, Speech::NumeratorFromDenominatorNode, Flow::VectorDemultiplexNode< T >, Speech::LatticeArcAccumulatorNode, Audio::RawFileInputNode, Flow::VectorSelectNode< T >, Speech::AlignmentBaseNode, Signal::AutoregressionToCepstrumNode, Flow::VectorSplitNode< T >, Flow::VectorSequenceNode< T >, Flow::VectorTextInputNodeBase, Signal::VectorSequenceAggregation< T >, Flow::CutterNode, Signal::GenericWarpingNode, Signal::VectorSequenceConcatenation< T >, Signal::FastMatrixMultiplicationNode< T >, Signal::ProjectionNode< T >, Flow::WarpTimeFilterNode, Speech::AlignmentFromLatticeNode, Signal::LinearPredictionCodingNode, Signal::FramePredictionNode< Algorithm >, Tensorflow::TensorflowForwardNode, Flow::PipeNode, Flow::DumpNode, Flow::MergerNode< I, O >, Flow::MergerNode< Vector< T >, Vector< T > >, Flow::MergerNode< Aggregate::DataType, Aggregate >, Flow::MergerNode< TypedAggregate< T >::DataType, TypedAggregate< T > >, Flow::MergerNode< Flow::Vector< f32 >, Flow::Vector< f32 > >, Speech::SegmentNode, Audio::FfmpegInputNode, Signal::FrameInterpolationNode< Algorithm >, and Audio::RawSourceNode.
Definition at line 154 of file AbstractNode.hh.
Referenced by Flow::WarpTimeFilterNode::setParameter(), Speech::AlignmentGammaCorrectionNode::setParameter(), Speech::AlignmentFilterWeightsNode::setParameter(), Speech::AlignmentResetWeightsNode::setParameter(), Speech::AlignmentMultiplyWeightsNode::setParameter(), and Speech::AlignmentAddWeightNode::setParameter().
virtual bool Flow::AbstractNode::work (PortId out) pure virtual
Process some data.
Implement this function to do whatever your node is supposed to. You are required to produce at least one packet of data on the specified output out. You may send more packets, also to other outputs.
Returns
true on success, false on end-of-file or error. The idiom is:
return putData(out, d);
Implemented in Signal::SegmentClusteringNode< Model >, Flow::SimpleFunctionNode< Function >, Flow::Network, Signal::QuantileEqualizationNode, Speech::LatticeDumpCtmNode, Speech::LatticeNBestNode, Signal::CrossCorrelationNode, Signal::NormalizationNode, Speech::SetAlignmentWeightsByTiedStateAlignmentWeightsNode, Signal::SilenceDetectionNode, Speech::AlignmentRemoveEmissionScoreNode, Signal::VectorCutNode< Algorithm >, Signal::GammaToneNode, Signal::FilterBankNode, Signal::WarpingNode, Speech::AcousticLatticeRescorerNode, Speech::LatticeTransform2Node, Signal::FastFourierTransformNode< Algorithm >, Speech::LatticeTransformNode, Speech::AlignmentToSequenceSelectionNode, Signal::VectorNormalizationNode< NormalizationFunction >, Signal::BayesClassificationScoreNode, Speech::LatticeSimpleModifyNode, Signal::ComplexVectorFunctionNode< Function >, Signal::WindowingFirFilterNode, Flow::Node, Flow::CacheNode, Audio::SinkNode, Signal::BayesClassificationNode, Signal::MrastaFilteringNode, Speech::SoftFramePhoneAccuracyLatticeRescorerNode, Speech::AlignmentDumpNode, Signal::CosineTransformNode, Signal::LinearFilterNode, Speech::LatticeSemiringNode, Speech::BinaryAlignmentTransformNode, Signal::PeakDetectionNode, Signal::HarmonicSumNode, Flow::SynchronizationNode< Algorithm >, Audio::SourceNode, Signal::TemporalPatternNode, Speech::LatticeWriteNode, Flow::TypedDisaggregateNode< T >, Signal::HistogramNormalizationNode, Signal::SegmentwiseFormantExtractionNode, Signal::NthOrderFeaturesNode, Flow::TypeConverterNode< C >, Flow::VectorScalarFunctionNode< Function >, Flow::VectorMalformedNode< T, Policy >, Speech::LatticeReadNode, Signal::DelayNode, Speech::AlignmentNode, Speech::ApproximateDistanceLatticeRescorerNode, Signal::AutocorrelationToAutoregressionNode, Flow::VectorSplitNode< T >, Signal::MatrixMultiplicationNode< T >, Speech::LatticeIoNode, Speech::FeatureShiftAdaptor, Tensorflow::TensorflowOverlappingForwardNode, Flow::CollectorNode< I, O >, Nn::NeuralNetworkForwardNode, Flow::CollectorNode< Vector< T >, Vector< T > >, Flow::CollectorNode< Aggregate::DataType, Aggregate >, Flow::CollectorNode< TypedAggregate< T >::DataType, TypedAggregate< T > >, Flow::CollectorNode< Flow::Vector< f32 >, Flow::Vector< f32 > >, Signal::VectorResizeNode< T >, Signal::SpectralIntegrationNode, Signal::ContinuousVectorTransformNode, Flow::DemoNode, Speech::LatticeArcAccumulatorNode, Signal::PreemphasisNode, Speech::ModelCombinationNode, Flow::VectorDemultiplexNode< T >, Signal::AutoregressionToSpectrumNode, Signal::MeanEstimatorNode, Flow::VectorAbsValDumpNode< content >, Signal::AllPolesPowerSpectrumNode, Speech::SegmentwiseFeaturesNode, Flow::CoprusKeyMapNode, Flow::VectorSequenceNode< T >, Signal::RandomVectorNode, Speech::NumeratorFromDenominatorNode, Speech::AlignmentWithLinearSegmentationNode, Flow::VectorSelectNode< T >, Signal::AutoregressionToCepstrumNode, Flow::VectorTextInputNodeBase, Flow::SequenceFilterNode, Flow::MergerNode< I, O >, Signal::LinearPredictionCodingNode, Flow::MergerNode< Vector< T >, Vector< T > >, Flow::MergerNode< Aggregate::DataType, Aggregate >, Flow::MergerNode< TypedAggregate< T >::DataType, TypedAggregate< T > >, Flow::MergerNode< Flow::Vector< f32 >, Flow::Vector< f32 > >, Flow::CutterNode, Flow::PipeNode, Signal::SlidingAlgorithmNode< Algorithm >, Signal::SlidingAlgorithmNode< LengthDependentSampleNormalization >, Signal::SlidingAlgorithmNode< WindowingFirFilter >, Signal::SlidingAlgorithmNode< SilenceNormalization >, Signal::SlidingAlgorithmNode< DcDetection >, Signal::SlidingAlgorithmNode< Window >, Signal::SlidingAlgorithmNode< TemporalIntegration >, Signal::FastMatrixMultiplicationNode< T >, Speech::CorpusProcessorNode< CorpusProcessorType >, Signal::ProjectionNode< T >, Speech::AlignmentFromLatticeNode, Flow::WarpTimeFilterNode, Speech::StatePosteriorFeatureScorerNode, Tensorflow::TensorflowForwardNode, Flow::DumpNode, Speech::SegmentNode, Speech::FeatureScorerNode, Speech::AlignmentGeneratorNode, Flow::RepeaterNode, and Speech::AlignmentTransformNode.
Referenced by eraseOutputAttributes(), and getData().
The documentation for this class was generated from the following files:
AbstractNode.hh
AbstractNode.cc