Sprint: Core::ProgressIndicator Class Reference
Core::ProgressIndicator Class Reference
Provide assurance to impatient users.
#include <ProgressIndicator.hh>
Classes
class DrawBuffer
Public Types
enum Alignment { Left, Right }
Public Member Functions
ProgressIndicator (const std::string &task, const std::string &unit="")
void start (u32 total=0)
Indicate start of the operation.
void setTask (const std::string &, Alignment align=Left)
Change task description.
void setTotal (u32 total)
Update estimate of total work.
void notify (u32 done)
Indicate the current state of operation.
void notify (u32 done, u32 total)
Indicate the current state of operation and update estimate of total work.
void notify ()
Indicate that the operation is going on.
void finish (bool hide=true)
Indicate completion of the operation.
Private Member Functions
void hide ()
void print ()
void update ()
void updateSize ()
void activate ()
void deactivate ()
bool isEnabled () const
bool isInForeground () const
int windowSize ()
Static Private Member Functions
static void sigAlarmHandler (int)
static void sigStopContinueHandler (int)
static void sigWinchHandler (int)
Private Attributes
Alignment align_
std::string task_
std::string unit_
u32 tick_
u32 done_
u32 total_
u32 doneAtLastUpdate_
u32 totalAtLastUpdate_
time_t startTime_
bool isVisible_
DrawBuffer * draw
ssize_t write_return_val_
Static Private Attributes
static const int defaultLength = 90
static const int fd = 2
static ProgressIndicator * activeInstance = 0
static const float updateInterval = 0.2
Detailed Description
Provide assurance to impatient users.
A progress indicators provides a sign of activity during lengthy operations. The only purpose is to reassure the user that the machine is still working and will eventually complete.
This class has been designed for minimal performance penalty. Unlike simple-minded printf("%d\r", i) approaches, you may safely use ProgressIndicator::notify() from the inner-most loop of a highly compute intensive algorithm.
Usage:
Usually you will have some way to measure the amount of work done. E.g. "bytes transferred", "time frames processed", "lines read". Ideally you know the total number of these "work units" in advance, or have an upper bound which will be lowered later on.
Create an instance of ProgressIndicator.
Call start(). If known, provide the total number units to process.
Call notify() with the current number of units processed each time you come around. If necessary you can also update the total. If you have no idea how much work has been done, just call notify without arguments.
When your task is complete, call finish(). This will hide the progress indicator.
Limitations:
Currently there can be at most one progress indicator active at any time.
There are no provisions for thread safety.
TODO:
Should detect if cout is connected to a TTY, and suppress messages otherwise.
see Limitations
Definition at line 65 of file ProgressIndicator.hh.
Constructor & Destructor Documentation
ProgressIndicator::ProgressIndicator (const std::string & task, const std::string & unit = "")
Parameters
task a terse description of the operation, which is displayed to the left of the progress indicator.
unit a optional name of the unit progress is measured in (e.g. bytes, lines, states, nodes...)
Definition at line 221 of file ProgressIndicator.cc.
References finish().
Member Function Documentation
void ProgressIndicator::finish (bool hide = true)
Indicate completion of the operation.
Parameters
hide,if true (default) the progress indicator is erased, otherwise it remains visible.
Definition at line 317 of file ProgressIndicator.cc.
References require, Core::Channel::Manager::unblockTty(), and Core::Channel::Manager::us().
Referenced by Am::AllophoneAlphabet::add(), Flf::ConfusionNetworkAlignment::align(), Am::ClassicStateTying::createClassicStateTyingRef(), Ftl::DfsState< _Automaton >::dfs(), Bliss::CorpusDescription::ProgressIndicationVisitorAdaptor::leaveCorpus(), notify(), Search::MinimumBayesRiskNBestListNaiveSearch::performSearch(), ProgressIndicator(), Search::StateTree::pronunciationSuffixTransitEntry(), Lm::ArpaLm::read(), Ftl::DfsState< _Automaton >::recursiveDfs(), Core::FileArchive::remove(), Ftl::sssp(), and TransitionModel::Applicator::stateType().
void Core::ProgressIndicator::notify (u32 done) inline
Indicate the current state of operation.
You may call notify() very frequently, e.g. from your inner loop. The run-time penalty of notify() is very small, since actual updates of the indicator (involving output) are done only a few times per second.
Definition at line 138 of file ProgressIndicator.hh.
Referenced by Am::AllophoneAlphabet::add(), Flf::ConfusionNetworkAlignment::align(), Am::ClassicStateTying::createClassicStateTyingRef(), Ftl::DfsState< _Automaton >::dfs(), Search::MinimumBayesRiskNBestListNaiveSearch::performSearch(), Search::StateTree::pronunciationSuffixTransitEntry(), Lm::ArpaLm::read(), Ftl::DfsState< _Automaton >::recursiveDfs(), Core::FileArchive::remove(), Ftl::sssp(), TransitionModel::Applicator::stateType(), Bliss::CorpusDescription::ProgressIndicationVisitorAdaptor::visitSegment(), and Bliss::CorpusDescription::ProgressIndicationVisitorAdaptor::visitSpeechSegment().
void Core::ProgressIndicator::notify (u32 done, u32 total) inline
Indicate the current state of operation and update estimate of total work.
This is similar to notify(done).
Definition at line 147 of file ProgressIndicator.hh.
References notify(), and setTotal().
void Core::ProgressIndicator::notify () inline
Indicate that the operation is going on.
Definition at line 155 of file ProgressIndicator.hh.
References finish().
Referenced by notify().
void ProgressIndicator::setTask (const std::string & t, Alignment align = Left)
Change task description.
Parameters
task a terse description of the operation, which is
align indicate whether description should be left or right aligned displayed to the left of the progress indicator.
Definition at line 231 of file ProgressIndicator.cc.
Referenced by Bliss::CorpusDescription::ProgressIndicationVisitorAdaptor::enterCorpus().
void Core::ProgressIndicator::setTotal (u32 total) inline
Update estimate of total work.
Definition at line 126 of file ProgressIndicator.hh.
Referenced by Ftl::DfsState< _Automaton >::dfs(), notify(), Lm::ArpaLm::read(), and Ftl::DfsState< _Automaton >::recursiveDfs().
void ProgressIndicator::start (u32 total = 0)
Indicate start of the operation.
Parameters
total (estimated) amount of work to do.
Definition at line 255 of file ProgressIndicator.cc.
References Core::Channel::Manager::blockTty(), Core::floor(), require, and Core::Channel::Manager::us().
Referenced by Am::AllophoneAlphabet::add(), Flf::ConfusionNetworkAlignment::align(), Am::ClassicStateTying::createClassicStateTyingRef(), Ftl::DfsState< _Automaton >::dfs(), Bliss::CorpusDescription::ProgressIndicationVisitorAdaptor::enterCorpus(), Search::MinimumBayesRiskNBestListNaiveSearch::performSearch(), Search::StateTree::pronunciationSuffixTransitEntry(), Lm::ArpaLm::read(), Ftl::DfsState< _Automaton >::recursiveDfs(), Core::FileArchive::remove(), Ftl::sssp(), and TransitionModel::Applicator::stateType().
The documentation for this class was generated from the following files:
ProgressIndicator.hh
ProgressIndicator.cc