Sprint: Search::LinearSearch Class Reference
Search::LinearSearch Class Reference
Classes
struct Book
class Pronunciation
Public Types
typedef std::vector< WordPronunciationStatePointer > WordPronunciationStateVector
Public Types inherited from Search::SearchAlgorithm
typedef Speech::Score Score
typedef Speech::TimeframeIndex TimeframeIndex
typedef Core::Ref< Pruning > PruningRef
Public Member Functions
LinearSearch (const Core::Configuration &)
virtual bool setModelCombination (const Speech::ModelCombination &modelCombination)
virtual void setGrammar (Fsa::ConstAutomatonRef)
virtual void restart ()
virtual void feed (const Mm::FeatureScorer::Scorer &)
virtual void getPartialSentence (Traceback &result)
Should return the longest fixed prefix of the final best sentence which has been been recognized since the last call to getPartialSentence.
virtual void getCurrentBestSentence (Traceback &result) const
Should return the whole currently best sentence.
virtual Core::Ref< const LatticeAdaptor > getCurrentWordLattice () const
virtual void resetStatistics ()
virtual void logStatistics () const
Public Member Functions inherited from Search::SearchAlgorithm
SearchAlgorithm (const Core::Configuration &)
virtual Speech::ModelCombination::Mode modelCombinationNeeded () const
virtual void init ()
virtual void setSegment (Bliss::SpeechSegment const *segment)
virtual void getCurrentBestSentencePartial (Traceback &result) const
Should return the part of the current best sentence which has not yet been returned by getPartialSentence().
virtual Core::Ref< const LatticeAdaptor > getPartialWordLattice ()
virtual void setAllowHmmSkips (bool allow=true)
Allow HMM skips during decoding ? By default, HMM skips are allowed.
virtual u32 lookAheadLength ()
Length of acoustic look-ahead.
virtual void setLookAhead (const std::vector< Mm::FeatureVector > &)
Called before feed() with as many acoustic feature vectors from the future as returned by lookaheadLength().
virtual PruningRef describePruning ()
Returns a descriptor of the current pruning thresholds, which can be used to re-activate the current pruning thresholds using resetPruning.
virtual bool relaxPruning (f32 factor, f32 offset)
Relaxes the pruning. Returns false if relaxing failed, otherwise true.
virtual void resetPruning (PruningRef pruning)
Resets pruning according to the given descriptor.
virtual RecognitionContext setContext (RecognitionContext)
Set LM context to be prepended (prefix) or appended(suffix) to the search hypotheses, and the acoustic phoneme coarticulation to be used for startup.
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Private Types
typedef std::deque< Book > BookVector
Private Member Functions
bool isRegularWord (const Pronunciation *pron)
void bookKeeping (Book &book, bool irregular=false)
template<class IteratorType >
LinearSearchHistoryData addPronunciations (std::pair< IteratorType, IteratorType > pronunciations)
bool removePronunciations (const LinearSearchHistoryData &data)
bool isUnigram () const
For now this always returns true, because only unigrams are completely supported.
Private Attributes
Bliss::LexiconRef lexicon_
const Bliss::Lemma * silence_
Core::Ref< const Am::AcousticModel > acousticModel_
Core::Ref< const Lm::ScaledLanguageModel > lm_
const LanguageModelLookahead * lmLookahead_
Score pronunciationScale_
bool singleWordRecognition_
WordPronunciationStateVector state_
TimeframeIndex time_
BookVector book_
BookVector irregularBook_
Static Private Attributes
static const Core::ParameterBool paramSingleWordRecognition_
Friends
struct LinearSearchHistoryData
class WordPronunciationState
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Definition at line 40 of file LinearSearch.hh.
Member Function Documentation
void Search::LinearSearch::feed (const Mm::FeatureScorer::Scorer & emissionScores) virtual
Bigram
Implements Search::SearchAlgorithm.
Definition at line 227 of file LinearSearch.cc.
References Lm::addLemmaPronunciationScore(), Core::Component::exit(), Lm::extendHistoryByLemmaPronunciation(), isUnigram(), Search::LinearSearch::Book::lmScore, require, and verify.
void Search::LinearSearch::getCurrentBestSentence (Traceback & result) const virtual
Should return the whole currently best sentence.
Implements Search::SearchAlgorithm.
Definition at line 432 of file LinearSearch.cc.
References Lm::extendHistoryByLemmaPronunciation(), and Search::LinearSearch::Book::lmScore.
Referenced by getPartialSentence().
void Search::LinearSearch::getPartialSentence (Traceback & result) virtual
Should return the longest fixed prefix of the final best sentence which has been been recognized since the last call to getPartialSentence.
Optional: Only required for online recognition
Reimplemented from Search::SearchAlgorithm.
Definition at line 464 of file LinearSearch.cc.
References Lm::addLemmaPronunciationScore(), getCurrentBestSentence(), and Core::ref().
bool Search::LinearSearch::isUnigram () const private
For now this always returns true, because only unigrams are completely supported.
Definition at line 428 of file LinearSearch.cc.
Referenced by feed().
bool Search::LinearSearch::removePronunciations (const LinearSearchHistoryData & data) private
Make more efficient
Definition at line 509 of file LinearSearch.cc.
The documentation for this class was generated from the following files:
LinearSearch.hh
LinearSearch.cc