Sprint: Speech::GerLatticeProcessorNode Class Reference
Speech::GerLatticeProcessorNode Class Reference
Public Member Functions
GerLatticeProcessorNode (const Core::Configuration &)
GerLatticeProcessorNode.
virtual void enterSpeechSegment (Bliss::SpeechSegment *)
Override this function to perform preparations before first features arrive.
virtual void processWordLattice (Lattice::ConstWordLatticeRef, Bliss::SpeechSegment *)
Override this function to implement the processing of lattice sets.
virtual void initialize (Bliss::LexiconRef)
Override this function to achieve the lexicon of the input lattice set.
Public Member Functions inherited from Speech::LatticeSetProcessor
LatticeSetProcessor (const Core::Configuration &)
LatticeSetProcessor.
void setProcessor (Core::Ref< LatticeSetProcessor > processor)
This lattice set processor is used for cascading.
virtual void signOn (CorpusVisitor &corpusVisitor)
Override this function to sign on to services of the corpus visitor.
virtual void enterCorpus (Bliss::Corpus *corpus)
Override this function to perform pre processing before the first segment of the corpus.
virtual void leaveCorpus (Bliss::Corpus *corpus)
Override this function to perform post processing after the last segment of the corpus.
virtual void enterRecording (Bliss::Recording *recording)
Override this function to perform pre processing before the first segment of the recording.
virtual void leaveRecording (Bliss::Recording *recording)
Override this function to perform post processing after the last segment of the recording.
virtual void enterSegment (Bliss::Segment *s)
Override this function to perform preparations before first aligned features arrive.
virtual void leaveSegment (Bliss::Segment *s)
Override this function to perform post processing after the last aligned features of the segment.
virtual void leaveSpeechSegment (Bliss::SpeechSegment *s)
Override this function to perform post processing after the last features of the segment.
virtual void getWordLatticeDescription (Lattice::WordLatticeDescription &)
Override this function to create the description of the output word lattices.
virtual void setWordLatticeDescription (const Lattice::WordLatticeDescription &)
Override this function to achieve the attributes of the input lattice set.
virtual void setSegmentwiseFeatureExtractor (Core::Ref< SegmentwiseFeatureExtractor >)
virtual void setAlignmentGenerator (Core::Ref< PhonemeSequenceAlignmentGenerator >)
virtual std::string name () const
virtual void logComputationTime () const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Private Types
typedef LatticeSetProcessor Precursor
Private Attributes
Bliss::Evaluator * evaluator_
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Speech::LatticeSetProcessor
f64 timeProcessSegment_
Core::Ref< LatticeSetProcessor > processor_
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Definition at line 208 of file LatticeSetProcessor.hh.
Constructor & Destructor Documentation
GerLatticeProcessorNode::GerLatticeProcessorNode (const Core::Configuration & c)
GerLatticeProcessorNode.
Definition at line 204 of file LatticeSetProcessor.cc.
Member Function Documentation
void GerLatticeProcessorNode::enterSpeechSegment (Bliss::SpeechSegment * s) virtual
Override this function to perform preparations before first features arrive.
Reimplemented from Speech::LatticeSetProcessor.
Definition at line 213 of file LatticeSetProcessor.cc.
References Speech::LatticeSetProcessor::enterSpeechSegment(), and verify.
void GerLatticeProcessorNode::initialize (Bliss::LexiconRef lexicon) virtual
Override this function to achieve the lexicon of the input lattice set.
Reimplemented from Speech::LatticeSetProcessor.
Definition at line 226 of file LatticeSetProcessor.cc.
References Core::Component::criticalError(), Core::Component::error(), Core::Component::initialize(), Core::Component::log(), Speech::LinearCombinationLatticeProcessorNode::paramOutputs, Lattice::WordLattice::totalFsa, and verify.
void GerLatticeProcessorNode::processWordLattice (Lattice::ConstWordLatticeRef lattice, Bliss::SpeechSegment * s) virtual
Override this function to implement the processing of lattice sets.
Reimplemented from Speech::LatticeSetProcessor.
Definition at line 219 of file LatticeSetProcessor.cc.
References Bliss::Evaluator::evaluate(), Speech::LatticeSetProcessor::processWordLattice(), and verify.
The documentation for this class was generated from the following files:
LatticeSetProcessor.hh
LatticeSetProcessor.cc