Sprint: Audio::WavInputNode Class Reference
Audio::WavInputNode Class Reference
Flow node for reading Microsoft .WAV RIFF audio files.
#include <Wav.hh>
Public Member Functions
WavInputNode (const Core::Configuration &c)
Public Member Functions inherited from Audio::SourceNode
bool setStartTime (Flow::Time)
bool setEndTime (Flow::Time)
SourceNode (const Core::Configuration &c)
virtual bool setParameter (const std::string &name, const std::string &value)
Set node specific parameter.
virtual Flow::PortId getOutput (const std::string &name)
Ask for an output port.
virtual bool configure ()
Post sample format to output port.
virtual bool work (Flow::PortId out)
Processes some data.
Public Member Functions inherited from Audio::Node
virtual void setSampleRate (Flow::Time _sampleRate)
virtual void setSampleSize (u8 _sampleSize)
virtual void setTrackCount (u8 _trackCount)
bool openFile ()
void closeFile ()
virtual void setFilename (const std::string &_filename)
Node (const Core::Configuration &c)
Public Member Functions inherited from Flow::Node
Node (const Core::Configuration &c)
virtual PortId getInput (const std::string &name)
Ask for an input port.
Public Member Functions inherited from Flow::AbstractNode
AbstractNode (const Core::Configuration &c)
virtual void Run ()
void setThreaded (bool threaded=true)
void setThreaded (const std::string &threaded)
bool isThreaded () const
virtual bool addParameter (const std::string &name, const Core::StringExpression &value)
addParameter adds a parameter to the node Constant parameters are simply delegated to setParameter, parameters dependent on network parameters are stored in parameters_.
virtual ssize_t getRemainingDataLen (PortId out)
Returns the amount of remaining data items.
void addUnresolvedParameter (const std::string &key, const std::string &value)
Functions for saving and getting unresolved parameters.
const UnresolvedAttributes & unresolvedAttributes () const
bool operator< (const AbstractNode &n) const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Member Functions
static std::string filterName ()
Private Types
typedef void Handle
Private Member Functions
virtual bool isFileOpen () const
virtual bool openFile_ ()
Open audio file and read sample format.
virtual void closeFile_ ()
virtual bool seek (SampleCount newSamplePos)
Set file position.
template<typename T >
u32 readTyped (u32 nSamples, Flow::Timestamp *&d)
virtual u32 read (u32 nSamples, Flow::Timestamp *&d)
Read at most nSamples samples from file.
Private Attributes
Handle * sf_
Additional Inherited Members
Public Types inherited from Audio::Node
typedef u32 SampleCount
Public Types inherited from Flow::AbstractNode
typedef std::map< std::string, std::string > UnresolvedAttributes
Static Public Attributes inherited from Audio::SourceNode
static const Core::ParameterInt paramBlockSize
static const Core::ParameterFloat paramStartTime
static const Core::ParameterFloat paramEndTime
Static Public Attributes inherited from Audio::Node
static const SampleCount invalidSampleCount
static const Core::ParameterString paramFilename
Static Public Attributes inherited from Flow::AbstractNode
static const Core::ParameterBool paramThreaded
static const Core::ParameterBool paramIgnoreUnknownParameters
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Audio::SourceNode
void setTotalSampleCount (SampleCount)
Set total number of sample in audio file.
SampleCount getStartSample () const
SampleCount getEndSample () const
void setBlockSize (u32 blockSize)
u32 blockSize () const
Protected Member Functions inherited from Flow::Node
virtual PortId connectInputPort (PortId, Link *)
Connect link to input port.
virtual void disconnectInputLink (Link *)
virtual PortId connectOutputPort (PortId, Link *)
virtual void disconnectOutputLink (Link *)
PortId addInput (PortId in=IllegalPortId)
Create an input port.
PortId addInputs (u32 nPorts)
Create several input ports.
virtual PortId nInputs () const
Link * getInputLink (PortId in) const
virtual PortId inputConnected (PortId in) const
bool validInputPort (PortId in) const
PortId addOutput (PortId out=IllegalPortId)
Add an output port.
PortId addOutputs (u32 nPorts)
Create several output ports.
virtual PortId nOutputs () const
bool validOutputPort (PortId out) const
virtual u32 nOutputLinks (PortId out) const
Number of link connceted to an output port.
bool configureDatatype (Core::Ref< const Attributes > a, const Datatype *d)
template<class T >
bool getData (PortId in, DataPtr< T > &d)
Fetch data packet from input port.
virtual bool putData (PortId out, Data *d)
Send data packet on output port.
bool putEos (PortId out)
Send end-of-stream on output port.
bool putOod (PortId out)
Send out-of-data on output port.
Core::Ref< const Attributes > getInputAttributes (PortId in)
Retrieve attribute set from input port.
void getInputAttributes (PortId, Attributes &)
bool putOutputAttributes (PortId out, Core::Ref< const Attributes > a)
Put attribute set on output port.
void eraseOutputAttributes ()
Erases attributes of all output links recursively.
Protected Member Functions inherited from Flow::AbstractNode
template<class T >
bool getData (Link *l, DataPtr< T > &d)
Fetch data packet from the "from" port of link.
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Audio::Node
std::string filename_
Flow::Time sampleRate_
u8 sampleSize_
u8 trackCount_
SampleCount sampleCount_
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Flow node for reading Microsoft .WAV RIFF audio files.
Definition at line 23 of file Wav.hh.
Member Function Documentation
bool WavInputNode::openFile_ () private virtual
Open audio file and read sample format.
Implement this in concrete input nodes.
Returns
true on success. On failure call error() and return false.
Implements Audio::SourceNode.
Definition at line 86 of file Wav.cc.
References Core::Component::criticalError().
u32 WavInputNode::read (u32 nSamples, Flow::Timestamp *& d) private virtual
Read at most nSamples samples from file.
Implement this in concrete input nodes.
Parameters
nSamples number of samples to read
d store pointer of new data packet here. If EOF or an error occurs d must be set to zero.
Returns
number of samples read, may be less than nSamples. On failure call error() and return 0. Note: One samples always means one sample per track!
Implements Audio::SourceNode.
Definition at line 136 of file Wav.cc.
References Core::Component::error(), and require.
bool WavInputNode::seek (SampleCount newSamplePos) private virtual
Set file position.
Implement this in concrete file input nodes, iff seeking is possible. Default implementation disallows seeking.
Parameters
newSamplePos number of next sample to be read, counted from beginning of stream
Returns
true on success. On failure call error() and return false.
Reimplemented from Audio::SourceNode.
Definition at line 106 of file Wav.cc.
References Core::Component::error(), and require.
The documentation for this class was generated from the following files:
Wav.hh
Wav.cc