Sprint: Lm::History Class Reference
Lm::History Class Reference
Classes
struct Hash
class SentinelHistoryManager
Public Member Functions
History (const History &hh)
History (History &&other)
HistoryHandle handle () const
const History & operator= (const History &rhs)
bool operator< (const History &rhs) const
History & operator= (History &&other)
bool isValid () const
Test for non-voidness.
bool isManagedBy (HistoryManager const *manager) const
bool operator== (const History &rhs) const
HistoryHash hashKey () const
std::string format () const
Create string representation (for debugging puposes).
Private Member Functions
History (HistoryManager *hm, HistoryHandle hd)
Private Attributes
HistoryManager * mang_
HistoryHandle desc_
Static Private Attributes
static SentinelHistoryManager sentinel
Friends
class LanguageModel
Detailed Description
Definition at line 47 of file Lm/LanguageModel.hh.
Member Function Documentation
std::string Lm::History::format () const inline
Create string representation (for debugging puposes).
The preferred way to access this function is through calling LanguageModel::formatHistory(), since some language models specialize this formatHistory() to give more readable information. If your language model is m-gram like, describe the history chronologically, i.e. most recent word last.
Definition at line 143 of file Lm/LanguageModel.hh.
Referenced by Lm::WordlistInterfaceLm::formatHistory(), and Lm::LanguageModel::formatHistory().
bool Lm::History::isValid () const inline
Test for non-voidness.
Definition at line 104 of file Lm/LanguageModel.hh.
References Lm::History::SentinelHistoryManager::hashKey(), Lm::HistoryManager::hashKey(), and Lm::HistoryManager::isEquivalent().
Referenced by Search::SearchSpace::activateLmLookahead(), Search::SearchSpace::activateOrUpdateTree(), Flf::decodeRescoreLm(), Search::SearchSpace::getBackOffInstance(), Search::SearchSpace::getSentenceEnd(), Search::SearchSpace::getSentenceEndFallBack(), and Search::SearchSpace::optimizeSilenceInWordLattice().
The documentation for this class was generated from the following files:
Lm/LanguageModel.hh
Lm/LanguageModel.cc