Sprint: Speech::SegmentwiseAlignmentGenerator Class Reference
Speech::SegmentwiseAlignmentGenerator Class Reference
SegmentwiseAlignmentGenerator.
#include <SegmentwiseAlignmentGenerator.hh>
Public Member Functions
SegmentwiseAlignmentGenerator (const Core::Configuration &, Core::Ref< const ModelCombination >=Core::Ref< const ModelCombination >())
virtual void setSegmentwiseFeatureExtractor (Core::Ref< SegmentwiseFeatureExtractor >)
This segmentwise feature extractor provides the features, if set.
void setFeatures (ConstSegmentwiseFeaturesRef features)
The features can be also set directly.
virtual const ConstSegmentwiseFeaturesRef features () const
virtual void setSpeechSegmentId (const std::string &)
virtual void setSpeechSegment (Bliss::SpeechSegment *)
virtual void signOn (Speech::CorpusVisitor &corpusVisitor)
Core::Ref< const ModelCombination > modelCombination () const
Core::Ref< Am::AcousticModel > acousticModel () const
Fsa::ConstAlphabetRef allophoneStateAlphabet () const
const Core::DependencySet & dependencies () const
AllophoneStateGraphBuilder * allophoneStateGraphBuilder ()
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Protected Member Functions
FsaCache * createFsaCache (const Core::Configuration &config)
void getScorers (std::vector< Mm::FeatureScorer::Scorer > &) const
void getScorers (TimeframeIndex tbeg, TimeframeIndex tend, std::vector< Mm::FeatureScorer::Scorer > &) const
void update (const std::string &segmentId)
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes
Flow::PortId portId_
Core::Ref< SegmentwiseFeatureExtractor > segmentwiseFeatureExtractor_
ConstSegmentwiseFeaturesRef features_
Core::Ref< const ModelCombination > modelCombination_
AllophoneStateGraphBuilder * allophoneStateGraphBuilder_
Search::Aligner aligner_
Core::DependencySet dependencySet_
bool checkCompatibility_
Protected Attributes inherited from Core::Configurable
Configuration config
Static Private Attributes
static const Core::ParameterString paramPortName
static const Core::ParameterStringVector paramSilencesAndNoises
static const Core::ParameterBool paramCheckCompatibility
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Detailed Description
SegmentwiseAlignmentGenerator.
Definition at line 53 of file SegmentwiseAlignmentGenerator.hh.
Member Function Documentation
void Speech::SegmentwiseAlignmentGenerator::setFeatures (ConstSegmentwiseFeaturesRef features) inline
The features can be also set directly.
This, however, is only possible if
Parameters
segmentwiseFeatureExtractor_ is not set.
Definition at line 90 of file SegmentwiseAlignmentGenerator.hh.
References require.
Referenced by Speech::AlignmentGeneratorNode::work().
void SegmentwiseAlignmentGenerator::setSegmentwiseFeatureExtractor (Core::Ref< SegmentwiseFeatureExtractor > segmentwiseFeatureExtractor) virtual
This segmentwise feature extractor provides the features, if set.
Otherwise the features are set by setFeatures, see below.
Definition at line 76 of file SegmentwiseAlignmentGenerator.cc.
References Mm::FeatureScorer::addFeature(), Mm::FeatureScorer::bufferFilled(), Core::Archive::create(), Bliss::Lexicon::createLemmaPronunciationToLemmaTransducer(), Core::Ref< T >::get(), Mm::FeatureScorer::isBuffered(), require, Mm::FeatureScorer::reset(), and verify.
Referenced by Speech::LatticeSetGenerator::alignmentGenerator().
The documentation for this class was generated from the following files:
SegmentwiseAlignmentGenerator.hh
SegmentwiseAlignmentGenerator.cc