Sprint: NnTrainer Class Reference
NnTrainer Class Reference
Copyright 2020 RWTH Aachen University.
#include <NnTrainer.hh>
Public Types
enum Action {
actionNotGiven, actionUnsupervisedTraining, actionSupervisedTraining, actionSupervisedSegmentwiseTraining,
actionBatchEstimation, actionInitNetwork, actionPythonControl, actionCombineStatistics,
actionGetLogPriorFromMixtureSet, actionEstimateMeanAndStandardDeviation, actionShowStatistics
}
Public Member Functions
virtual std::string getUsage () const
Overload this method to describe the usage of the application and to give a (short) description of the application.
virtual int main (const std::vector< std::string > &arguments)
Main entry point for an application.
Public Member Functions inherited from Core::Application
virtual std::string getVariable () const
Return the name of the environment variable.
std::string getBaseName () const
Return the applications basename.
std::string getPath () const
Return the applications path.
virtual std::string getApplicationDescription () const
virtual std::string getParameterDescription () const
virtual std::string getDefaultParameterDescription () const
void reportLowLevelError (const std::string &msg="")
Errors messages are collected and later (during closeLogging()) printed to the error channel.
void setDefaultLoadConfigurationFile (bool f)
Configure default behaviour of loading a configuration file.
void setDefaultOutputXmlHeader (bool f)
Configure default behaviour of adding a valid xml header to standard channels.
void setTitle (const std::string &t)
Set the title of the application.
void setCommentCharacters (const std::string &c)
Set the set of possible comment characters for this application.
const std::string & getCommentCharacters (void) const
Return the string of comment characters.
Core::Channel & debugChannel (void)
Returns the debug binary outpput channel.
Core::XmlChannel & debugXmlChannel (void)
Returns the debug XML channel.
MappedArchiveReader getCacheArchiveReader (const std::string &archive_name, const std::string &item)
Returns a pointer to the cache-archive reader for the archive, and the specified item contained by the archive.
MappedArchiveWriter getCacheArchiveWriter (const std::string &archive_name, const std::string &item)
Returns a pointer to the cache-archive writer for the archive, and the specified item contained by the archive.
void exit (int status)
Terminate program execution.
void atexit (std::function< void()> f)
Like std::atexit() but will be execute sooner, at our own uninit, at the end of our main(), or in our exit().
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Attributes
static const Core::Choice choiceAction
Copyright 2020 RWTH Aachen University.
static const Core::ParameterChoice paramAction
static const Core::ParameterBool paramSinglePrecision
static const Core::ParameterString paramPriorFile
static const Core::ParameterInt paramSeed
static const Core::ParameterString paramFilenameInit
static const Core::ParameterStringVector paramStatisticsFiles
static const Core::ParameterString paramStatisticsFile
Private Member Functions
void visitCorpus (Speech::CorpusProcessor &)
void visitCorpus (Speech::AlignedFeatureProcessor &)
template<typename T >
void neuralNetworkTrainingUnsupervised ()
template<typename T >
void neuralNetworkTrainingSupervised ()
template<typename T >
void neuralNetworkTrainingSupervisedSegmentwise ()
template<typename T >
void neuralNetworkBatchEstimation ()
template<typename T >
void neuralNetworkInit ()
void pythonControl ()
void getLogPriorFromMixtureSet ()
template<typename T >
void combineStatistics ()
template<typename T >
void estimateMeanAndStandardDeviation ()
template<typename T >
void showStatistics ()
Additional Inherited Members
Static Public Member Functions inherited from Core::Application
static Application * us ()
Get the global instance of the application (Singleton)
static int main (int argc, char *argv[])
private
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Application
void logSystemInfo () const
void logVersion () const
void logResources () const
void logResourceUsage () const
void logMemoryUsage () const
MappedArchive * getCacheArchive (const std::string &archive)
void openLogging ()
Opens channels and makes initial logs.
void closeLogging (bool configAvailable=true)
Closes down channels and makes final logs.
int run (const std::vector< std::string > &arguments)
void runAtExitFuncs ()
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Static Protected Member Functions inherited from Core::Application
static bool setFromEnvironment (const std::string &variable)
static bool setFromFile (const std::string &filename)
static std::vector< std::string > setFromCommandline (const std::vector< std::string > &arguments)
Protected Attributes inherited from Core::Application
Channel::Manager * channelManager_
Core::Channel * debugChannel_
Core::XmlChannel * debugXmlChannel_
std::map< std::string, MappedArchive * > cacheArchives_
bool defaultLoadConfigurationFile_
bool defaultOutputXmlHeader_
std::string comment_
std::string configFileName_
Timer timer_
std::list< std::function< void()> > atExitFuncs_
Protected Attributes inherited from Core::Configurable
Configuration config
Static Protected Attributes inherited from Core::Application
static const ParameterBool paramLogConfiguration
static const ParameterBool paramLogResolvedResources
static const ParameterString paramConfig
static const ParameterString paramCacheArchiveFile
static const ParameterBool paramCacheArchiveReadOnly
static const ParameterBool paramHelp
static std::string path_ = "."
static std::string basename_ = ""
static Application * app_ = 0
Detailed Description
Copyright 2020 RWTH Aachen University.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.Train the weights of a neural network
Definition at line 26 of file NnTrainer.hh.
Member Function Documentation
virtual std::string NnTrainer::getUsage () const inline virtual
Overload this method to describe the usage of the application and to give a (short) description of the application.
Default return string is "usage: " + getBaseName() + "[OPTION(S)]\n" Return the usage of the application.
Normally, that method does not have to be overloaded; overload getApplicationDescription() and getParamterDescription() and getDefaultParameterDescription() instead.
Reimplemented from Core::Application.
Definition at line 94 of file NnTrainer.hh.
References main().
int NnTrainer::main (const std::vector< std::string > & arguments) virtual
Main entry point for an application.
Implements Core::Application.
Definition at line 105 of file NnTrainer.cc.
References Bliss::CorpusDescription::accept(), Core::Component::criticalError(), Core::Component::error(), Core::Component::log(), Nn::NeuralNetwork< T >::saveParameters(), Nn::Prior< T >::setFromMixtureSet(), Speech::CorpusProcessor::signOn(), verify, and Nn::MeanAndVarianceTrainer< T >::writeMeanAndStandardDeviation().
Referenced by getUsage().
Member Data Documentation
const Core::Choice NnTrainer::choiceAction static
Copyright 2020 RWTH Aachen University.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Definition at line 41 of file NnTrainer.hh.
The documentation for this class was generated from the following files:
NnTrainer.hh
NnTrainer.cc