Sprint: Sparse::SingleValueSparseVector< Content > Class Template Reference
Sparse::SingleValueSparseVector< Content > Class Template Reference
Sparse vector.
#include <SingleValSparseVector.hh>
Classes
class IteratorBase
Public Types
typedef u32 index_type
typedef IteratorBase< typename InternalVector::iterator, typename InternalVector::iterator::value_type::second_type > iterator
typedef IteratorBase< typename InternalVector::const_iterator, const typename InternalVector::const_iterator::value_type::second_type > const_iterator
Public Member Functions
SingleValueSparseVector (size_t size=0, Content defaultValue=0)
Creates a new sparse vector of given size.
SingleValueSparseVector (const SingleValueSparseVector< Content > &sv)
bool operator== (const SingleValueSparseVector &sv)
bool operator!= (const SingleValueSparseVector &sv)
iterator begin ()
Returns a begin iterator.
iterator end ()
Returns an "after end" iterator.
const_iterator begin () const
Returns a begin const_iterator.
const_iterator end () const
Returns an "after end" const_iterator.
const Content & operator[] (const const_iterator &i) const
complexity: constant
Content & operator[] (const iterator &i)
complexity: constant
const Content & get (const index_type index) const
complexity: linear
Content & operator[] (const index_type index)
complexity: linear
void clear ()
sets all active elements to null the size of the vector is unchanged
void setDefault (Content defaultValue)
sets the value of non-active components
Content getDefault ()
get the value of non-active components
void resize (size_t new_size)
sets the dimension of the vector
void resize (size_t new_size, Content defaultValue)
sets the dimension of the vector and changes the value of ALL non-active components
Content & front ()
void push_back (index_type index, Content value)
push_back of a new active entry requires: index > index of last active entry if index < size: size is unchanged if index >= size: size = index + 1
size_t size () const
bool empty () const
size_t nActiveElements () const
void concatenate (const SingleValueSparseVector< Content > &bsv)
Concatenates an other block sparse vector.
void concatenate (const std::vector< Content > &v, u32 startPosition)
Concatenates a standard vector to the current sparse vector.
SingleValueSparseVector< Content > & operator*= (const Content &)
Scales the content of a block sparse vector with all its elements.
SingleValueSparseVector< Content > & operator+= (const SingleValueSparseVector< Content > &)
Adds a block sparse vector to the recent one.
template<typename C >
SingleValueSparseVector< Content > & add (const Content &weight, const SingleValueSparseVector< C > &)
in place weighted operator+=
template<typename C >
SingleValueSparseVector< Content > & add (const Content &weight, const std::map< u32, C > &)
virtual Core::XmlWriter & dump (Core::XmlWriter &o) const
Dumps the sparse vector to an XML stream.
virtual bool read (Core::BinaryInputStream &i)
Reads a sparse vector from a binary stream.
virtual bool write (Core::BinaryOutputStream &o) const
Writes a sparse vector to a binary stream.
Private Types
typedef std::vector< std::pair< index_type, Content > > InternalVector
Private Attributes
InternalVector v_
size_t size_
Content default_
InternalVector::iterator pos_
Friends
template<class T , class V >
class IteratorBase
template<typename C >
Core::BinaryInputStream & operator>> (Core::BinaryInputStream &, SingleValueSparseVector< C > &)
template<typename C >
Core::BinaryOutputStream & operator<< (Core::BinaryOutputStream &, const SingleValueSparseVector< C > &)
template<typename C >
Core::XmlWriter & operator<< (Core::XmlWriter &, const SingleValueSparseVector< C > &)
Detailed Description
template<typename Content>
class Sparse::SingleValueSparseVector< Content >
Sparse vector.
Implements basic functions of a sparse vector. For performance purposes, this vector does not provide random access. Elements of the vector can be accessed by (1) sparse vector iterators (recommended), i.e. by iterating from begin to end. Given an iterator, the value can be accessed by dereferencing or by using the pseudo-random access operator[](SparseVectorIterator). complexity: constant in the number of active entries (2) using the pseudo random access operator operator[](index_type index) complexity: linear Instead, only The SparseVectorIterator supports reset, increment and decrement, but no other access. The iterator can be converted to an integer, which is needed by methods providing matrix or vector multiplications.
The class is not thread-safe.
Internally the vector is a vector of index-value pairs corresponding to the active elements
Definition at line 49 of file SingleValSparseVector.hh.
Constructor & Destructor Documentation
template<typename Content> Sparse::SingleValueSparseVector< Content >::SingleValueSparseVector (size_t size = 0, Content defaultValue = 0)
Creates a new sparse vector of given size.
Parameters
size Size.
Definition at line 392 of file SingleValSparseVector.hh.
Member Function Documentation
template<typename Content> template<typename C > SingleValueSparseVector< Content > & Sparse::SingleValueSparseVector< Content >::add (const Content & weight, const SingleValueSparseVector< C > & bsv)
in place weighted operator+=
Definition at line 542 of file SingleValSparseVector.hh.
References Sparse::SingleValueSparseVector< Content >::begin(), defect, Sparse::SingleValueSparseVector< Content >::end(), Core::Component::error(), Sparse::SingleValueSparseVector< Content >::push_back(), Sparse::SingleValueSparseVector< Content >::size(), and Core::Application::us().
Referenced by Sparse::SingleValueSparseVector< T >::size().
template<typename Content> iterator Sparse::SingleValueSparseVector< Content >::begin () inline
Returns a begin iterator.
Definition at line 174 of file SingleValSparseVector.hh.
Referenced by Sparse::SingleValueSparseVector< Content >::add(), Sparse::SingleValueSparseVector< T >::get(), Sparse::SingleValueSparseVector< Content >::operator+=(), and Sparse::SingleValueSparseVector< Content >::write().
template<typename Content> const_iterator Sparse::SingleValueSparseVector< Content >::begin () const inline
Returns a begin const_iterator.
Definition at line 184 of file SingleValSparseVector.hh.
template<typename Content> void Sparse::SingleValueSparseVector< Content >::clear () inline
sets all active elements to null the size of the vector is unchanged
Definition at line 271 of file SingleValSparseVector.hh.
template<typename Content> void Sparse::SingleValueSparseVector< Content >::concatenate (const SingleValueSparseVector< Content > & bsv)
Concatenates an other block sparse vector.
Parameters
bsv vector to concatenate
Definition at line 419 of file SingleValSparseVector.hh.
Referenced by Sparse::SingleValueSparseVector< T >::size().
template<typename Content> void Sparse::SingleValueSparseVector< Content >::concatenate (const std::vector< Content > & v, u32 startPos)
Concatenates a standard vector to the current sparse vector.
Concatenates a full vector at a given position.
Parameters
v Vector to concatenate.
startPos Start position.
requires startPos >= previous dimension
Parameters
v vector to concatenate
startPos position where v is inserted
Definition at line 437 of file SingleValSparseVector.hh.
References require.
template<typename Content > Core::XmlWriter & Sparse::SingleValueSparseVector< Content >::dump (Core::XmlWriter & o) const virtual
Dumps the sparse vector to an XML stream.
Parameters
o XML output stream to write to.
Reimplemented in Sparse::Vector< T >.
Definition at line 612 of file SingleValSparseVector.hh.
Referenced by Sparse::SingleValueSparseVector< T >::size(), and Sparse::SingleValueSparseVector< Content >::write().
template<typename Content> iterator Sparse::SingleValueSparseVector< Content >::end () inline
Returns an "after end" iterator.
Definition at line 179 of file SingleValSparseVector.hh.
Referenced by Sparse::SingleValueSparseVector< Content >::add(), Sparse::SingleValueSparseVector< T >::get(), and Sparse::SingleValueSparseVector< Content >::write().
template<typename Content> const_iterator Sparse::SingleValueSparseVector< Content >::end () const inline
Returns an "after end" const_iterator.
Definition at line 189 of file SingleValSparseVector.hh.
template<typename Content> Content& Sparse::SingleValueSparseVector< Content >::front () inline
Returns
reference to the zeroth component
Definition at line 310 of file SingleValSparseVector.hh.
template<typename Content> const Content& Sparse::SingleValueSparseVector< Content >::get (const index_type index) const inline
complexity: linear
Parameters
index component index
Returns
content at the given index
Definition at line 216 of file SingleValSparseVector.hh.
template<typename Content> Content Sparse::SingleValueSparseVector< Content >::getDefault () inline
get the value of non-active components
Definition at line 285 of file SingleValSparseVector.hh.
template<typename Content> SingleValueSparseVector< Content > & Sparse::SingleValueSparseVector< Content >::operator*= (const Content & factor)
Scales the content of a block sparse vector with all its elements.
Definition at line 450 of file SingleValSparseVector.hh.
Referenced by Sparse::SingleValueSparseVector< T >::size().
template<typename Content> SingleValueSparseVector< Content > & Sparse::SingleValueSparseVector< Content >::operator+= (const SingleValueSparseVector< Content > & bsv)
Adds a block sparse vector to the recent one.
Definition at line 458 of file SingleValSparseVector.hh.
References Sparse::SingleValueSparseVector< Content >::begin(), defect, Core::Component::error(), Sparse::SingleValueSparseVector< Content >::push_back(), and Core::Application::us().
Referenced by Sparse::SingleValueSparseVector< T >::size().
template<typename Content> const Content& Sparse::SingleValueSparseVector< Content >::operator[] (const const_iterator & i) const inline
complexity: constant
Parameters
i const_iterator pointing to the content.
Returns
reference to the const_iterator's position.
Definition at line 198 of file SingleValSparseVector.hh.
template<typename Content> Content& Sparse::SingleValueSparseVector< Content >::operator[] (const iterator & i) inline
complexity: constant
Parameters
i iterator pointing to the content.
Returns
content at the given iterator's position.
Definition at line 207 of file SingleValSparseVector.hh.
template<typename Content> Content& Sparse::SingleValueSparseVector< Content >::operator[] (const index_type index) inline
complexity: linear
Returns
reference to the component at the given index, if the component at the given index is not active, a null entry is inserted
Parameters
index component index
Definition at line 248 of file SingleValSparseVector.hh.
template<typename Content> void Sparse::SingleValueSparseVector< Content >::push_back (index_type index, Content value)
push_back of a new active entry requires: index > index of last active entry if index < size: size is unchanged if index >= size: size = index + 1
Adds a new element.
Parameters
index index of new entry
value value of new entry
requires: index > index of last active component size of vector = max(index + 1, previous dimension)
Parameters
index Position where the new element should be added.
value New element to add.
Definition at line 406 of file SingleValSparseVector.hh.
References require.
Referenced by Sparse::SingleValueSparseVector< Content >::add(), Sparse::SingleValueSparseVector< T >::front(), Sparse::SingleValueSparseVector< Content >::operator+=(), Sparse::SingleValueSparseVector< T >::operator[](), and Speech::StatePosteriorFeatureScorerNode::work().
template<typename Content > bool Sparse::SingleValueSparseVector< Content >::read (Core::BinaryInputStream & i) virtual
Reads a sparse vector from a binary stream.
Parameters
i Stream to read from.
Reimplemented in Sparse::Vector< T >.
Definition at line 626 of file SingleValSparseVector.hh.
References Sparse::SingleValueSparseVector< Content >::size().
Referenced by Sparse::SingleValueSparseVector< T >::size(), and Sparse::SingleValueSparseVector< Content >::write().
template<typename Content> void Sparse::SingleValueSparseVector< Content >::resize (size_t new_size) inline
sets the dimension of the vector
Parameters
new_size new dimension
Definition at line 293 of file SingleValSparseVector.hh.
template<typename Content> void Sparse::SingleValueSparseVector< Content >::resize (size_t new_size, Content defaultValue) inline
sets the dimension of the vector and changes the value of ALL non-active components
Parameters
new_size new dimension
null value of non-active components
Definition at line 302 of file SingleValSparseVector.hh.
template<typename Content> void Sparse::SingleValueSparseVector< Content >::setDefault (Content defaultValue) inline
sets the value of non-active components
Definition at line 278 of file SingleValSparseVector.hh.
template<typename Content> size_t Sparse::SingleValueSparseVector< Content >::size () const inline
Returns
vector's size
Definition at line 324 of file SingleValSparseVector.hh.
Referenced by Sparse::SingleValueSparseVector< Content >::add(), and Sparse::SingleValueSparseVector< Content >::read().
template<typename Content > bool Sparse::SingleValueSparseVector< Content >::write (Core::BinaryOutputStream & o) const virtual
Writes a sparse vector to a binary stream.
Parameters
o Stream to write to.
Reimplemented in Sparse::Vector< T >.
Definition at line 645 of file SingleValSparseVector.hh.
References Sparse::SingleValueSparseVector< Content >::begin(), Sparse::SingleValueSparseVector< Content >::dump(), Sparse::SingleValueSparseVector< Content >::end(), Sparse::SingleValueSparseVector< Content >::read(), and Sparse::SingleValueSparseVector< Content >::write().
Referenced by Sparse::SingleValueSparseVector< T >::size(), and Sparse::SingleValueSparseVector< Content >::write().
The documentation for this class was generated from the following file:
SingleValSparseVector.hh