Sprint: Lm::ArpaLm Class Reference
Lm::ArpaLm Class Reference
ARPA backing-off language model.
#include <ArpaLm.hh>
Classes
class InitData
Public Member Functions
ArpaLm (const Core::Configuration &, Bliss::LexiconRef)
Public Member Functions inherited from Lm::BackingOffLm
virtual void load ()
virtual History startHistory () const
Language model history for beginning of a sentence.
virtual Lm::Score sentenceBeginScore () const
virtual History extendedHistory (const History &, Token w) const
Language model history for the next sentence position.
virtual History reducedHistory (const History &, u32 limit) const
Reduce amount on conditioning information.
virtual std::string formatHistory (const History &) const
Create string representation of history (mainly for debugging purposes).
virtual Lm::Score score (const History &, Token w) const
Probability of a token to occur with a given history.
virtual void getBatch (const History &, const CompiledBatchRequest *, std::vector< f32 > &result) const
Get probabilities for a (large) set of syntactic tokens given a history.
virtual Fsa::ConstAutomatonRef getFsa () const
Convert language model into an EQUIVALENT acceptor.
void historyTokens (const History &history, const Bliss::Token **target, u32 &size, u32 arraySize) const
Writes all tokens stored in the given history into the given vector.
u32 historyLenght (const History &history) const
BackOffScores getBackOffScores (const History &history, int depth=0) const
Directly returns the scores stored in the LM for the given context history.
Score getAccumulatedBackOffScore (const History &history, int limit) const
Returns the accumulated backing-off scores up the the given limit (not the actual contained word-scores) Examples: With limit 0, returns the sum of the back-off offsets up to the zerogram level.
Public Member Functions inherited from Lm::LanguageModel
Token sentenceBeginToken () const
Token sentenceEndToken () const
Token sentenceBoundaryToken () const
virtual void init ()
precondition: the token inventory is set and fixed
virtual void getDependencies (Core::DependencySet &dependencies) const
Bliss::LexiconRef lexicon () const
const TokenInventory & tokenInventory () const
Fsa::ConstAlphabetRef tokenAlphabet () const
virtual bool scoreCached (const History &, Token w) const
Some LMs might cache scores and thus provide fast access.
virtual Score sentenceEndScore (const History &) const
Probability for sentence to end in current position.
virtual CompiledBatchRequest * compileBatchRequest (const BatchRequest &, Score scale=1.0) const
Preprocess a batch request.
virtual Core::Ref< const LanguageModel > lookaheadLanguageModel () const
Returns the LanguageModel that shall be used for lookahead (useful for CombinedLM when we do not want to reinstanciate the model)
virtual Core::Ref< const LanguageModel > recombinationLanguageModel () const
Returns the LanguageModel that shall be used for recombination (useful for CombinedLM when we do not want to reinstanciate the model)
virtual void setSegment (Bliss::SpeechSegment const *s)
For some cheating language models we need to know the correct transcription.
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Private Member Functions
virtual void read ()
Implement this this function to read the language model from a file.
Static Private Attributes
static const Core::ParameterString paramFilename
static const Core::ParameterString paramEncoding
static const Core::ParameterBool paramSkipInfScore
static const Core::ParameterBool paramReverseLm
static const f64 InfScore = -99
Since log(0) (minus infinity) has no portable representation, such values are mapped to a large negative number.
Additional Inherited Members
Public Types inherited from Lm::BackingOffLm
typedef Node HistoryDescriptor
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Lm::BackingOffLm
BackingOffLm (const Core::Configuration &, Bliss::LexiconRef)
void initialize (InitItem *begin, InitItem *end)
Initialize back-off language model from list of InitItems.
void initialize (Core::Ref< Internal >)
Alternative initialization method.
Protected Member Functions inherited from Lm::LanguageModel
History history (HistoryHandle hd) const
template<class LM >
const LM::HistoryDescriptor * descriptor (const History &hh) const
void setTokenInventory (const TokenInventory *_tokenInventory)
void setTokenInventoryAndAlphabet (const TokenInventory *_tokenInventory, Fsa::ConstAlphabetRef _tokenAlphabet)
Token getToken (const std::string &word) const
virtual Token getSpecialToken (const std::string &name, bool required=false) const
const Bliss::SyntacticToken * getSpecialSyntacticToken (const std::string &name, bool required) const
Token fallbackToken () const
Find token to use for unknown words.
virtual void createSpecialTokens ()
void requireSentenceBoundaryToken ()
Call this function before init(), iff your language model requires a sentence boundary token to be defined in the lexicon.
LanguageModel (const Core::Configuration &c, Bliss::LexiconRef l)
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Lm::LanguageModel
HistoryManager * historyManager_
Concrete LanguageModels should set this member in their constructor or load() method.
Core::Dependency dependency_
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
ARPA backing-off language model.
Actually just a reader for the ARPA standard format introduced by Doug Paul. The LM implementation is just inherited from BackingOffLm.
Edited quote from documentation header by CMU software:
p(w3|w1,w2) = if (trigram exists) p_3(w1,w2,w3) else if (bigram w1,w2 exists) bo_wt_2(w1,w2)*p(w3|w2) else p(w3|w2)
p(w2|w1) = if (bigram exists) p_2(w1,w2) else if (unigram w1 exists) bo_wt_1(w1)*p_1(w2) else p_1(w2)
All probs and back-off weights (bo_wt) are given in log10 form. Missing back-off weights are set to zero.
Data format:
\ ngram 1=nr # number of unigrams ngram 2=nr # number of bigrams ngram 3=nr # number of trigrams
\1-grams: p_1 w1 bo_wt_1
\2-grams: p_2 w1 w2 bo_wt_2
\3-grams: p_3 w1 w2 w3
\
Notes:
Format and implementation are not restricted to tri-grams.
Currently we assume that the LM file is in UTF-8 encoding.
Definition at line 70 of file ArpaLm.hh.
Member Function Documentation
void ArpaLm::read () private virtual
Implement this this function to read the language model from a file.
Reserve memory only for a fraction of the LM, assume that some part of the LM is discarded because of a resricted vocabulary.
Implements Lm::BackingOffLm.
Definition at line 101 of file ArpaLm.cc.
References defect, BisonParser::ArithmeticExpressionParser::error(), Core::ProgressIndicator::finish(), hope, Core::isAlmostEqual(), Core::normalizeWhitespace(), Core::ProgressIndicator::notify(), Core::ProgressIndicator::setTotal(), Core::ProgressIndicator::start(), and Core::suppressTrailingBlank().
Member Data Documentation
const f64 ArpaLm::InfScore = -99 static private
Since log(0) (minus infinity) has no portable representation, such values are mapped to a large negative number.
However, the designated dummy value (-99 in SRILM) should be interpreted as log(0) when read back from file into memory. [man ngram-format]
Definition at line 77 of file ArpaLm.hh.
The documentation for this class was generated from the following files:
ArpaLm.hh
ArpaLm.cc