Sprint: SimpleThreadPool::Thread Class Reference
SimpleThreadPool::Thread Class Reference
Copyright 2020 RWTH Aachen University.
Public Member Functions
void stopThread ()
void startJob (Job *job)
virtual void run ()
Override this in a threaded class.
Public Member Functions inherited from Core::Thread
bool start ()
Start the thread.
void wait ()
Wait for thread to exit.
virtual void cleanup ()
Cleanup, when thread is ended.
Public Attributes
Job * job_
bool jobReady_
bool waiting_
Core::Condition wait_
Additional Inherited Members
Protected Member Functions inherited from Core::Thread
void enableCancel ()
Allow that the thread is cancelled by another thread.
void disableCancel ()
Forbid other threads to cancel this thread.
void setCancelDeferred ()
The thread can only be chancelled on certain points.
void setCancelAsync ()
The thread can be chanceled at any time.
void exitThread ()
Terminates the thread.
Detailed Description
Copyright 2020 RWTH Aachen University.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Definition at line 19 of file SimpleThreadPool.cc.
Member Function Documentation
void SimpleThreadPool::Thread::run () virtual
Override this in a threaded class.
Reimplemented from Core::Thread.
Definition at line 52 of file SimpleThreadPool.cc.
References Core::Condition::broadcast(), SimpleThreadPool::Job::run(), verify, Core::Thread::wait(), and Core::Condition::wait().
The documentation for this class was generated from the following file:
SimpleThreadPool.cc