Sprint: Core::StringExpression Class Reference
Core::StringExpression Class Reference
String parameter with variable parts.
#include <StringExpression.hh>
Classes
class Token
Public Member Functions
bool isConstant () const
isConstant
bool hasVariable (const std::string &name) const
setVariable sets the value of a variable in the string expression which name is
Returns
is false if variable does not exist
bool setVariable (const std::string &name, const std::string &value)
bool setVariables (const Core::Configuration &c)
setVariable set the values of all variables in the string expression by querying the configuration
clear clears the value the variables
Returns
is false if variable does not exist in
bool clear (const std::string &name)
void clear ()
clear clears the value of all variables
bool value (std::string &v, bool ignore_unknown_parameters=false) const
value return the resolved paramerer in v
Private Types
typedef std::vector< Token > Tokens
typedef std::vector< u32 > TokenReferences
typedef Core::StringHashMap< TokenReferences > Variables
Private Member Functions
void setValue (const TokenReferences &references, const std::string &value)
void clear (const TokenReferences &references)
void pushBackToken (const std::string &token)
void pushBackVariableToken (const std::string &token)
Private Attributes
Tokens tokens_
Variables variables_
Friends
class StringExpressionParser
Detailed Description
String parameter with variable parts.
A string expression consits of constant and variable tokens. E.g.: "prefix-$(var).ext" where "var" is a variable
See also
StringExpressionParser for details about creating StringExpression object
Definition at line 34 of file StringExpression.hh.
Member Function Documentation
void StringExpression::clear ()
clear clears the value of all variables
Definition at line 74 of file StringExpression.cc.
Referenced by setVariables(), and value().
bool Core::StringExpression::isConstant () const inline
isConstant
Returns
is true if the string expression does not contain any variables
Definition at line 87 of file StringExpression.hh.
References setVariables().
Referenced by Flow::AbstractNode::addParameter(), and Flow::NodeBuilder::createNode().
bool StringExpression::setVariables (const Core::Configuration & c)
setVariable set the values of all variables in the string expression by querying the configuration
Returns
is false if variable does not exist
Definition at line 53 of file StringExpression.cc.
References clear(), Core::Configuration::get(), and value().
Referenced by Flow::NodeBuilder::createNode(), and isConstant().
bool StringExpression::value (std::string & v, bool ignore_unknown_parameters = false) const
value return the resolved paramerer in v
Returns
is true if there are no unset variables in the parameter
Definition at line 79 of file StringExpression.cc.
References clear().
Referenced by Flow::AbstractNode::addParameter(), setVariables(), and Flow::CoprusKeyMapNode::work().
The documentation for this class was generated from the following files:
StringExpression.hh
StringExpression.cc