Sprint: TransitionModel::Applicator Class Reference
TransitionModel::Applicator Class Reference
Apply TransitionModel to a flat automaton.
Classes
struct StackItem
struct State
struct State
struct State
class StateDegrees
class StateDegrees
Public Member Functions
Applicator (const TransitionModel &tm)
Fsa::ConstAutomatonRef apply (Fsa::ConstAutomatonRef in)
Private Types
typedef std::stack< StackItem > StateStack
typedef std::unordered_map< State, Fsa::StateId, State::Hash, State::Equality > StateMap
Private Member Functions
bool isStateLegitimate (const State &s) const
Fsa::StateId getStateId (State::Mask m, Fsa::LabelId e, StateType t, Fsa::StateId r)
Core::Ref< Fsa::State > createState (const State &s)
Fsa::Weight weight (const State &s, StateTransitionModel::TransitionType type) const
StateType stateType (Fsa::LabelId emission) const
void doEpsilon (const StackItem &current, const Fsa::Arc *ra)
void doForward (const StackItem &current, const Fsa::Arc *ra)
void doLoop (const StackItem &current)
void doSkip (const StackItem &current, const Fsa::Arc *ra)
void doExit (const StackItem &current, const Fsa::Arc *ra)
void doDischarge (const StackItem &current)
Private Attributes
const TransitionModel & transitionModel_
Fsa::LabelId silenceLabel_
Fsa::ConstAutomatonRef in_
Core::Ref< Fsa::StaticAutomaton > t_
Fsa::ConstAlphabetRef alphabet_
bool applyExitTransitionToFinalStates_
StateDegrees * rightStateDegrees_
StateStack todo_
StateMap states_
Friends
class TransitionModel
Detailed Description
Apply TransitionModel to a flat automaton.
What is does: The purpose of this algorithm is to add loop and skip transitions to a "flat" automaton. (Flat meaning that it does not contain loops and skips.) The emission labels, i.e. the labels that are repeated or skipped are on the input side of the automaton, while the output labels will be unchanged.
This can be viewed as a specialized compose algorithm for the time-distortion transducer (left) and a given automaton (right). If you read on, you will discover that considerable care must be taken to creating compact results.
How it works: The state space is expanded so that we remember the most recent emission label, this is called "left state" in the following. "Right state" refers to the corresponding state in the original automaton. This expansion is necessary to provide the loop transitions. The representation of the left state is rather verbose. It consists of a mask stating which kinds of transition are possible, a reference to the state's transition model, and of course the most recent emission label. In fact only a small number of combinations of the possible values are actually used. (One could slim down the data structure to represent only the valid combinations. However priority was given to clarity and maintainability of the code, over the small increase in efficiency.) The function isStateLegitimate() specifies which potential states can be used. It is good to make these constraints as tight as possible in order to ensure the result automaton does not contain unnecessary states.
The most recent emission label may be empty (Fsa::Epsilon). We call this a "discharged" state. This happens for three reasons: 1) At the word start no emission label has been consumed. 2) After processing an input epsilon arc. 3) In some situations we deliberately forget the emission label (see below).
In the expanded state space, loop transitions are simple to implement. (In "discharged" states they are not allowed.) Concerning the other (forward, exit and skip) transitions, there is a little twist: When a right state has multiple incoming and outgoing arcs, we choose to first discharge the recent-most emission label by going to an appropriate left state via an epsilon transition. The alternative would be to avoid the epsilon transition and directly connect to all successor states. However, in practice this would dramatically increase the total number of arcs needed. So discharging is the preferable alternative. The discharged state can be thought of as the state when we have decided to leave the current state, but not yet chosen where to go to. As mentioned before, the appropriate set of transition weights is recorded, so that we know what to do when we forward or skip from the discharged state.
Concerning skips: In general, a skip consists of two transitions: First an epsilon transition goes to an intermediate state that allows a forward only, and then another transition leads to the target state. In "favorable" situations this is optimized into a single transitions (skip optimization). If you have read so far, you are certainly able to figure out what these favorable conditions are.
As you noticed, there is some freedom in designing the discharge transitions. It turns out that compact results can be obtained by combining the forward discharge with the intermediate skip states, and to combine exit and loop discharge states.
Any disambiguator label is interpreted as a word boundary and is given the following special treatment: No loop transition, since the word boundary cannot be repeated. No skip transitions: The word boundary cannot be skipped and the final state before the boundary cannot be skipped. The latter is done for consistency with WordConditionedTreeSearch.
Once the state space is constructed as describe above, it is relatively straight forward to figure out, which transition weight (aka time distortion penalty or TDP) must be applied to which arc. Unfortunately the current scheme is not able to distinguish phone-1 from phone-2 states. This will require additional state space expansion by counting repetitive emission labels. Alternatively, and probably simpler, we change the labels to allow the distinction between phone-1 and phone-2.
Todo:
An even better condition for discharging would be: (number of DIFFERENT incoming arc labels > 1) && (number of outgoing arcs > 1) Presently it is (number of incoming arcs > 1) && (number of outgoing arcs > 1).
Implement proper distinction between between phone-1 and phone-2 states.
Reconsider the transition model. (see discussion in Wiki)
It might be nice to convert this to lazy evaluation (should be straight forward).
Definition at line 248 of file TransitionModel.cc.
Member Function Documentation
StateType TransitionModel::Applicator::stateType (Fsa::LabelId emission) const inline private
Todo:
proper distinction between phone-1 and phone-2 states
Definition at line 441 of file TransitionModel.cc.
References Core::Component::criticalError(), TransitionModel::Applicator::State::emission, Core::ProgressIndicator::finish(), Core::form(), Core::Ref< T >::get(), Fsa::Alphabet::isDisambiguator(), TransitionModel::Applicator::State::mask, Core::ProgressIndicator::notify(), Bliss::PhonemeInventory::parseSelection(), Core::ref(), require, Core::Ref< T >::reset(), Core::ProgressIndicator::start(), verify, Core::Component::warning(), and TransitionModel::Applicator::State::weights.
The documentation for this class was generated from the following file:
TransitionModel.cc