Sprint: Nn::PythonTrainer< T > Class Template Reference
Nn::PythonTrainer< T > Class Template Reference
Public Types
enum TargetMode {
criterionBySprint, targetGeneric, targetAlignment, targetSegmentOrth,
unsupervised, forwardOnly
}
typedef NeuralNetworkTrainer< T > Precursor
typedef Types< T >::NnVector NnVector
typedef Types< T >::NnMatrix NnMatrix
typedef Math::FastVector< T > FastVector
typedef Math::FastMatrix< T > FastMatrix
Public Types inherited from Nn::NeuralNetworkTrainer< T >
enum TrainerType {
dummy, feedForwardTrainer, frameClassificationErrorAccumulator, meanAndVarianceAccumulator,
networkEvaluator, autoencoderTrainer, pythonTrainer, pythonEvaluator
}
Public Member Functions
PythonTrainer (const Core::Configuration &config)
virtual bool isNetworkOutputRepresentingClassLabels ()
if we have a network, is its output layer representing the class label posterior probabilities
virtual bool hasClassLabelPosteriors ()
whether we can call getClassLabelPosteriors()
virtual NnMatrix & getClassLabelPosteriors ()
returns the posteriors after a call to processBatch_feedInput()
virtual int getClassLabelPosteriorDimension ()
returns posterior dimension
virtual bool allowsDownsampling () const
virtual void initializeTrainer (u32 batchSize, std::vector< u32 > &streamSizes)
virtual void finalize ()
virtual void processBatch_feedInput (std::vector< NnMatrix > &features, NnVector *weights, Bliss::Segment *segment)
Override this method for the NN forward pass in NN training.
virtual void processBatch_finishWithAlignment (Math::CudaVector< u32 > &alignment)
Override this method for supervised training with a criterion based on an alignment.
virtual void processBatch_finishWithSpeechSegment (Bliss::SpeechSegment &segment)
Override this method for supervised training with a criterion based on a segment.
virtual void processBatch_finish ()
Override this method for unsupervised training to finish a minibatch.
void python_feedInput ()
void python_feedInputAndTarget (Math::CudaVector< u32 > *alignment)
void python_feedInputAndTargetAlignment (Math::CudaVector< u32 > &alignment)
void python_feedInputAndTargetSegmentOrth (Bliss::SpeechSegment &segment)
Core::Component::Message pythonCriticalError (const char *msg=0,...)
Python::CriticalErrorFunc getPythonCriticalErrorFunc ()
Public Member Functions inherited from Nn::NeuralNetworkTrainer< T >
NeuralNetworkTrainer (const Core::Configuration &config)
virtual void initializeTrainer (u32 batchSize)
NnMatrix & getOutputActivation ()
get activations of output layer
bool hasNetwork () const
returns whether trainer has a network
bool hasEstimator () const
returns whether trainer has an estimator
bool weightedAccumulation () const
returns whether frame weights are used
u32 batchSize () const
returns current batch size (equal to size of activations)
bool isInitialized () const
returns whether trainer is initialized
bool measuresTime () const
returns whether trainer measures computation time
Criterion< T > & criterion ()
NeuralNetwork< T > & network ()
return reference to network
const NeuralNetwork< T > & network () const
u32 nLayers () const
return reference to network
Estimator< T > & estimator ()
return reference to estimator
const Estimator< T > & estimator () const
Regularizer< T > & regularizer ()
return reference to regularizer
const Regularizer< T > & regularizer () const
void setClassWeights (const Math::Vector< T > *vector)
sets class weights to values in vector
virtual bool needsToProcessAllFeatures () const
returns whether trainer needs to process all features, i.e.
virtual void setBatchSize (u32 batchSize)
resize activations (necessary when batch size has changed)
virtual void processBatch_finishWithError (T error, NnMatrix &errorSignal)
Override this method for supervised training.
virtual void processBatch_finishWithError_naturalPairing (T error, NnMatrix &errorSignal)
This is a special variant of processBatch_finishWithError(), where the error signal is already related to the natural pairing of the objective function with the last layer activation function.
virtual void resetHistory ()
virtual void logBatchTimes () const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Protected Member Functions
void passErrorSignalToPython ()
Protected Member Functions inherited from Nn::NeuralNetworkTrainer< T >
virtual void logProperties () const
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes
TargetMode targetMode_
bool useNetwork_
int inputDim_
int outputDim_
bool allowDownsampling_
Python::Initializer pythonInitializer_
std::string pyModPath_
std::string pyModName_
PyObject * pyMod_
NnMatrix * features_
NnVector * weights_
Bliss::Segment * segment_
NnMatrix posteriors_
NeuralNetworkLayer< T > * naturalPairingLayer_
Protected Attributes inherited from Nn::NeuralNetworkTrainer< T >
Criterion< T > * criterion_
bool weightedAccumulation_
const Math::Vector< T > * classWeights_
const bool measureTime_
bool needsNetwork_
Core::XmlChannel statisticsChannel_
bool needInit_
NeuralNetwork< T > * network_
Estimator< T > * estimator_
Regularizer< T > * regularizer_
Protected Attributes inherited from Core::Configurable
Configuration config
Additional Inherited Members
Static Public Member Functions inherited from Nn::NeuralNetworkTrainer< T >
static NeuralNetworkTrainer< T > * createSupervisedTrainer (const Core::Configuration &config)
static NeuralNetworkTrainer< T > * createUnsupervisedTrainer (const Core::Configuration &config)
Static Public Attributes inherited from Nn::NeuralNetworkTrainer< T >
static const Core::Choice choiceNetworkTrainer
static const Core::ParameterChoice paramNetworkTrainer
static const Core::ParameterInt paramEpoch
static const Core::ParameterBool paramWeightedAccumulation
static const Core::ParameterBool paramMeasureTime
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Detailed Description
template<class T>
class Nn::PythonTrainer< T >
Definition at line 28 of file PythonTrainer.hh.
Member Function Documentation
template<class T > virtual int Nn::PythonTrainer< T >::getClassLabelPosteriorDimension () inline virtual
returns posterior dimension
Reimplemented from Nn::NeuralNetworkTrainer< T >.
Definition at line 75 of file PythonTrainer.hh.
References Nn::NeuralNetworkTrainer< T >::batchSize(), Nn::PythonTrainer< T >::processBatch_feedInput(), Nn::PythonTrainer< T >::processBatch_finish(), Nn::PythonTrainer< T >::processBatch_finishWithAlignment(), and Nn::PythonTrainer< T >::processBatch_finishWithSpeechSegment().
template<class T > virtual NnMatrix& Nn::PythonTrainer< T >::getClassLabelPosteriors () inline virtual
returns the posteriors after a call to processBatch_feedInput()
Reimplemented from Nn::NeuralNetworkTrainer< T >.
Definition at line 72 of file PythonTrainer.hh.
template<typename T > bool Nn::PythonTrainer< T >::hasClassLabelPosteriors () virtual
whether we can call getClassLabelPosteriors()
Reimplemented from Nn::NeuralNetworkTrainer< T >.
Definition at line 211 of file PythonTrainer.cc.
References Core::Component::criticalError(), require, and Core::Component::warning().
Referenced by Nn::PythonTrainer< T >::isNetworkOutputRepresentingClassLabels().
template<class T > virtual bool Nn::PythonTrainer< T >::isNetworkOutputRepresentingClassLabels () inline virtual
if we have a network, is its output layer representing the class label posterior probabilities
Reimplemented from Nn::NeuralNetworkTrainer< T >.
Definition at line 68 of file PythonTrainer.hh.
References Nn::PythonTrainer< T >::hasClassLabelPosteriors().
template<typename T > void Nn::PythonTrainer< T >::processBatch_feedInput (std::vector< NnMatrix > & features, NnVector * weights, Bliss::Segment * segment) virtual
Override this method for the NN forward pass in NN training.
The weights are for the individual frames. Note that the pointer has to stay valid until the processBatch_finish* call. Can be NULL. The segment is only given if the calling feature extractor is in segmentwise mode. Otherwise it's NULL.
Reimplemented from Nn::NeuralNetworkTrainer< T >.
Definition at line 317 of file PythonTrainer.cc.
References Core::Component::criticalError(), verify, and Core::Component::warning().
Referenced by Nn::PythonTrainer< T >::getClassLabelPosteriorDimension().
template<typename T > void Nn::PythonTrainer< T >::processBatch_finish () virtual
Override this method for unsupervised training to finish a minibatch.
Reimplemented from Nn::NeuralNetworkTrainer< T >.
Reimplemented in Nn::PythonEvaluator< T >.
Definition at line 604 of file PythonTrainer.cc.
References Core::Archive::create(), Core::Component::criticalError(), Core::Component::log(), require, and Core::Component::warning().
Referenced by Nn::PythonTrainer< T >::getClassLabelPosteriorDimension().
template<typename T > void Nn::PythonTrainer< T >::processBatch_finishWithAlignment (Math::CudaVector< u32 > & alignment) virtual
Override this method for supervised training with a criterion based on an alignment.
Reimplemented from Nn::NeuralNetworkTrainer< T >.
Definition at line 429 of file PythonTrainer.cc.
References Core::Component::criticalError(), Bliss::SpeechSegment::speaker(), and verify.
Referenced by Nn::PythonTrainer< T >::getClassLabelPosteriorDimension().
template<typename T > void Nn::PythonTrainer< T >::processBatch_finishWithSpeechSegment (Bliss::SpeechSegment & segment) virtual
Override this method for supervised training with a criterion based on a segment.
Reimplemented from Nn::NeuralNetworkTrainer< T >.
Reimplemented in Nn::PythonEvaluator< T >.
Definition at line 549 of file PythonTrainer.cc.
References Core::Component::criticalError().
Referenced by Nn::PythonTrainer< T >::getClassLabelPosteriorDimension().
The documentation for this class was generated from the following files:
PythonTrainer.hh
PythonTrainer.cc