Sprint: Lattice::NBestListExtractor Class Reference
Lattice::NBestListExtractor Class Reference
NBestListExtractor Produces an n-best list with word boundaries.
#include <Best.hh>
Public Member Functions
NBestListExtractor ()
NBestListExtractor.
ConstWordLatticeRef getNBestList (ConstWordLatticeRef)
void initialize (Bliss::LexiconRef)
void setNumberOfHypotheses (u32 nHypotheses)
void setMinPruningThreshold (f32 minThreshold)
void setMaxPruningThreshold (f32 maxThreshold)
void setPruningIncrement (f32 thresholdIncrement)
void setWorkOnOutput (bool workOnOutput)
void setLatticeIsDeterministic (bool isDeterministic)
void setHasFailArcs (bool hasFailArcs)
void setNormalize (bool normalize)
Private Member Functions
Fsa::ConstAutomatonRef mapLemmaPronToEval (Fsa::ConstAutomatonRef) const
Fsa::ConstAutomatonRef mapEvalToLemmaPron (Fsa::ConstAutomatonRef) const
Fsa::ConstAutomatonRef getNBestListWithoutWordBoundaries (Fsa::ConstAutomatonRef, f32 &threshold)
Private Attributes
Fsa::ConstAutomatonRef lemmaPronToLemma_
Fsa::ConstAutomatonRef lemmaToEval_
u32 targetNHypotheses_
f32 minThreshold_
f32 maxThreshold_
f32 thresholdIncrement_
bool workOnOutput_
bool latticeIsDeterministic_
bool hasFailArcs_
bool normalize_
Detailed Description
NBestListExtractor Produces an n-best list with word boundaries.
All hypotheses in the n-best list are distinct w.r.t. the evaluation tokens.
Definition at line 30 of file Lattice/Best.hh.
Constructor & Destructor Documentation
Lattice::NBestListExtractor::NBestListExtractor ()
NBestListExtractor.
Definition at line 38 of file Lattice/Best.cc.
References Fsa::multiply(), and require.
Member Function Documentation
Fsa::ConstAutomatonRef Lattice::NBestListExtractor::getNBestListWithoutWordBoundaries (Fsa::ConstAutomatonRef fsa, f32 & threshold) private
Stop if number of hypotheses has not changed since the last iteration. It is very likely that the automaton does not contain more hypotheses.
Stop if n-best list is complete. This is the case if the target number of hypotheses is reached and the least hypothesis has lower score than the relative pruning threshold.
Definition at line 85 of file Lattice/Best.cc.
References Lattice::Core::Component::log(), Fsa::prunePosterior(), Fsa::staticCopy(), and Lattice::Core::Application::us().
The documentation for this class was generated from the following files:
Lattice/Best.hh
Lattice/Best.cc