Sprint: Core::Description::Stream Class Reference
Core::Description::Stream Class Reference
Public Member Functions
Stream (const std::string &name)
template<class ValueType >
void setValue (const std::string &name, const ValueType &value)
Set the value of attribute.
bool getValue (const std::string &name, std::string &value) const
Retrieves the value of attribute.
std::string getValue (const std::string &name, bool critical=true) const
Retrieves the value of attribute.
template<class ValueType >
bool getValue (const std::string &name, ValueType &value) const
Retrieves the value of attribute.
template<class ValueType >
bool verifyValue (const std::string &name, const ValueType &expected, bool critical=false) const
Compares the value of the attribute.
void getDependencies (const std::string &prefix, std::string &value) const
bool operator== (const Stream &s) const
Private Attributes
std::string name_
StringHashMap< std::string > attributes_
Detailed Description
Definition at line 29 of file Description.hh.
Member Function Documentation
bool Description::Stream::getValue (const std::string & name, std::string & value) const
Retrieves the value of attribute.
Parameters
name. If attribute
name is not found, result is false.
Definition at line 37 of file Description.cc.
References Core::form().
Referenced by getValue(), Nn::SegmentwiseNnTrainer< T >::processWordLattice(), Speech::SegmentwiseGmmTrainer::SegmentwiseGmmTrainer(), Speech::CovarianceEstimator::setFeatureDescription(), Speech::TextDependentScatterMatricesEstimator::setFeatureDescription(), Speech::MeanEstimator::setFeatureDescription(), Speech::TextIndependentMixtureSetTrainer::setFeatureDescription(), Speech::TextIndependentScatterMatricesEstimator::setFeatureDescription(), Speech::TextDependentMixtureSetTrainer::setFeatureDescription(), Speech::TiedTextDependentMixtureSetTrainer::setFeatureDescription(), Speech::HistogramEstimator::setFeatureVectorDescription(), setValue(), and verifyValue().
std::string Description::Stream::getValue (const std::string & name, bool critical = true) const
Retrieves the value of attribute.
Parameters
name. If attribute
name is not found, error is raised. In case of an error, if critical is true, program terminates.
Definition at line 27 of file Description.cc.
References Core::Component::error(), Core::Component::respondToDelayedErrors(), and Core::Application::us().
template<class ValueType > bool Core::Description::Stream::getValue (const std::string & name, ValueType & value) const
Retrieves the value of attribute.
Parameters
name. If attribute
name is not found, result is false.
Definition at line 138 of file Description.hh.
References ensure, and getValue().
template<class ValueType > void Core::Description::Stream::setValue (const std::string & name, const ValueType & value) inline
Set the value of attribute.
Parameters
name.
Definition at line 40 of file Description.hh.
References ensure, getValue(), and verifyValue().
Referenced by Mm::FeatureDescription::FeatureDescription(), Nn::PythonFeatureScorer::reset(), and Nn::TrainerFeatureScorer::reset().
template<class ValueType > bool Core::Description::Stream::verifyValue (const std::string & name, const ValueType & expected, bool critical = false) const
Compares the value of the attribute.
Parameters
name with the
expected. If
critical is true and comparison fails, execution is aborted
Definition at line 150 of file Description.hh.
References Core::Component::error(), getValue(), Core::Component::respondToDelayedErrors(), and Core::Application::us().
Referenced by setValue().
The documentation for this class was generated from the following files:
Description.hh
Description.cc