Sprint: Search::Wfst::LatticeTraceRecorder Class Reference
Search::Wfst::LatticeTraceRecorder Class Reference
Base class for lattice constructing TraceRecorders.
#include <LatticeGenerator.hh>
Public Types
enum LatticeType {
HmmLattice, DetermisticHmmLattice, SimpleWordLattice, SimpleNonDetWordLattice,
WordLattice
}
Public Types inherited from Search::Wfst::TraceRecorder
typedef u32 TraceRef
Public Member Functions
void setSilence (const StateSequence *hmm, OpenFst::Label output)
Set input and output label of silence arcs.
void setMergeSilence (bool merge)
Enable/disable merging of silence arcs.
void setPruningThreshold (Score threshold)
Set threshold used for lattice pruning.
virtual void clear ()
remove all trace objects
void purgeBegin ()
start purging process (reset all active flags)
void purgeEnd ()
remove all trace objects not labeled as active
void purgeNotify (TraceRef trace)
label the trace object and its predecessors as active (set active flag)
size_t memoryUsage () const
memory usage in bytes.
Public Member Functions inherited from Search::Wfst::TraceRecorder
virtual TraceRef addTrace (TraceRef sibling, TraceRef predecessor, OpenFst::Label output, const StateSequence *input, TimeframeIndex time, Score score, Score arcScore, bool wordEnd)=0
add a new trace
virtual void updateTime (TraceRef t, TimeframeIndex time)=0
Update the timestamp of the given trace object.
virtual void pruneBegin ()
start pruning process (for lattices only)
virtual void pruneEnd ()
finish pruning (for lattices only)
virtual void pruneNotify (TraceRef trace)
label the trace as currently active (for lattices only)
virtual bool hasWordEndTime (const WordEndDetector &wordEnds, TraceRef end)=0
Check if the number of word boundary time stamps matches the number of output labels on the path ending in end.
virtual void createBestPath (const WordEndDetector &wordEnds, bool ignoreLast, TraceRef end, BestPath *path)=0
Find the first best path ending in end.
virtual Lattice * createLattice (TraceRef)=0
Create a lattice.
Static Public Member Functions
static LatticeTraceRecorder * create (LatticeType type, const StateSequenceList &s)
Factory function.
Protected Types
typedef Search::Wfst::Lattice Lattice
typedef Lattice::Arc Arc
typedef Arc::StateId StateId
typedef Arc::Label Label
typedef Arc::Weight Weight
typedef FstLib::StateIterator< Lattice > StateIterator
typedef FstLib::ArcIterator< Lattice > ArcIterator
typedef FstLib::MutableArcIterator< Lattice > MutableArcIterator
Protected Member Functions
LatticeTraceRecorder (const StateSequenceList &hmms)
Label getInputLabel (const StateSequence *hmm) const
Convert Hmm Pointer to input label.
const StateSequence * getHmm (Label label) const
Convert input label to Hmm Pointer.
StateId newState ()
Add a state to the lattice.
virtual void enlarge (StateId s)
Called if a state is added to lattice_.
virtual void finalize (TraceRef end)
Finish the lattice construction with the given trace as final state.
virtual void endLattice (TraceRef end)
Set end as final state.
virtual void finalizeReverseLattice ()
Perform optimization of lattice with reversed arcs.
virtual void trimLattice ()
Remove non-accessible states.
virtual void reverseLattice ()
Reverse the lattice transducer.
virtual void optimizeLattice ()
Perform final optimizations on the lattice.
void removeEpsilon (bool connect)
Remove epsilon arcs.
void shortestPath (BestPath *path) const
Generate the shortest path (using OpenFst's ShortestPath)
Protected Attributes
const StateSequence *const hmmsBegin_
Lattice * lattice_
Label silence_
Label silenceOutput_
bool mergeSilence_
Score pruningThreshold_
std::vector< bool > active_
Private Attributes
std::vector< StateId > unusedStates_
Additional Inherited Members
Static Public Attributes inherited from Search::Wfst::TraceRecorder
static const TraceRef InvalidTraceRef = -1
Detailed Description
Base class for lattice constructing TraceRecorders.
Definition at line 32 of file LatticeGenerator.hh.
Member Function Documentation
void LatticeTraceRecorder::clear () virtual
remove all trace objects
Implements Search::Wfst::TraceRecorder.
Reimplemented in Search::Wfst::HmmLatticeTraceRecorder.
Definition at line 117 of file LatticeGenerator.cc.
Referenced by Search::Wfst::HmmLatticeTraceRecorder::clear(), and setPruningThreshold().
LatticeTraceRecorder * LatticeTraceRecorder::create (LatticeType type, const StateSequenceList & s) static
Factory function.
Definition at line 84 of file LatticeGenerator.cc.
Referenced by setPruningThreshold().
void LatticeTraceRecorder::endLattice (TraceRef end) protected virtual
Set end as final state.
Definition at line 175 of file LatticeGenerator.cc.
Referenced by enlarge().
virtual void Search::Wfst::LatticeTraceRecorder::enlarge (StateId s) inline protected virtual
Called if a state is added to lattice_.
Allows to maintain data structures with additional state information in derived classes.
Reimplemented in Search::Wfst::HmmLatticeTraceRecorder.
Definition at line 103 of file LatticeGenerator.hh.
References endLattice(), and finalize().
void LatticeTraceRecorder::finalize (TraceRef end) protected virtual
Finish the lattice construction with the given trace as final state.
Executes following sequence of calls to virtual functions: endLattice() finalizeReverseLattice() trimLattice() reverseLattice() optimizeLattice()
Reimplemented in Search::Wfst::HmmLatticeTraceRecorder.
Definition at line 186 of file LatticeGenerator.cc.
Referenced by enlarge(), and Search::Wfst::HmmLatticeTraceRecorder::finalize().
virtual void Search::Wfst::LatticeTraceRecorder::finalizeReverseLattice () inline protected virtual
Perform optimization of lattice with reversed arcs.
Reimplemented in Search::Wfst::SimpleWordLatticeRecorder, Search::Wfst::DetermisticHmmLatticeTraceRecorder, and Search::Wfst::HmmLatticeTraceRecorder.
Definition at line 122 of file LatticeGenerator.hh.
const StateSequence * LatticeTraceRecorder::getHmm (Label label) const protected
Convert input label to Hmm Pointer.
Definition at line 141 of file LatticeGenerator.cc.
Referenced by setPruningThreshold().
LatticeTraceRecorder::Label LatticeTraceRecorder::getInputLabel (const StateSequence * hmm) const protected
Convert Hmm Pointer to input label.
Definition at line 136 of file LatticeGenerator.cc.
Referenced by setPruningThreshold().
size_t LatticeTraceRecorder::memoryUsage () const virtual
memory usage in bytes.
Reimplemented from Search::Wfst::TraceRecorder.
Reimplemented in Search::Wfst::HmmLatticeTraceRecorder.
Definition at line 221 of file LatticeGenerator.cc.
Referenced by Search::Wfst::HmmLatticeTraceRecorder::memoryUsage(), and setPruningThreshold().
LatticeTraceRecorder::StateId LatticeTraceRecorder::newState () protected
Add a state to the lattice.
Tries to re-use deleted states.
Definition at line 123 of file LatticeGenerator.cc.
Referenced by setPruningThreshold().
virtual void Search::Wfst::LatticeTraceRecorder::optimizeLattice () inline protected virtual
Perform final optimizations on the lattice.
Reimplemented in Search::Wfst::SimpleNonDetWordLatticeRecorder, Search::Wfst::SimpleWordLatticeRecorder, Search::Wfst::DetermisticHmmLatticeTraceRecorder, and Search::Wfst::HmmLatticeTraceRecorder.
Definition at line 134 of file LatticeGenerator.hh.
References removeEpsilon(), and shortestPath().
Referenced by Search::Wfst::SimpleWordLatticeRecorder::finalizeReverseLattice().
void LatticeTraceRecorder::purgeBegin () virtual
start purging process (reset all active flags)
Reimplemented from Search::Wfst::TraceRecorder.
Definition at line 146 of file LatticeGenerator.cc.
Referenced by setPruningThreshold().
void LatticeTraceRecorder::purgeEnd () virtual
remove all trace objects not labeled as active
Reimplemented from Search::Wfst::TraceRecorder.
Definition at line 151 of file LatticeGenerator.cc.
Referenced by setPruningThreshold().
void LatticeTraceRecorder::purgeNotify (TraceRef trace) virtual
label the trace object and its predecessors as active (set active flag)
Reimplemented from Search::Wfst::TraceRecorder.
Definition at line 161 of file LatticeGenerator.cc.
Referenced by setPruningThreshold().
void LatticeTraceRecorder::removeEpsilon (bool connect) protected
Remove epsilon arcs.
Definition at line 194 of file LatticeGenerator.cc.
Referenced by optimizeLattice().
void LatticeTraceRecorder::reverseLattice () protected virtual
Reverse the lattice transducer.
Reimplemented in Search::Wfst::HmmLatticeTraceRecorder.
Definition at line 180 of file LatticeGenerator.cc.
Referenced by Search::Wfst::HmmLatticeTraceRecorder::reverseLattice(), and trimLattice().
void Search::Wfst::LatticeTraceRecorder::setMergeSilence (bool merge) inline
Enable/disable merging of silence arcs.
Definition at line 51 of file LatticeGenerator.hh.
void Search::Wfst::LatticeTraceRecorder::setPruningThreshold (Score threshold) inline
Set threshold used for lattice pruning.
Derived classes have to override pruneBegin(), pruneNotify(), pruneEnd(), as declared in TraceRecoder.
Definition at line 59 of file LatticeGenerator.hh.
References clear(), create(), getHmm(), getInputLabel(), memoryUsage(), newState(), purgeBegin(), purgeEnd(), and purgeNotify().
void LatticeTraceRecorder::setSilence (const StateSequence * hmm, OpenFst::Label output)
Set input and output label of silence arcs.
Definition at line 112 of file LatticeGenerator.cc.
void LatticeTraceRecorder::shortestPath (BestPath * path) const protected
Generate the shortest path (using OpenFst's ShortestPath)
Definition at line 198 of file LatticeGenerator.cc.
Referenced by optimizeLattice().
virtual void Search::Wfst::LatticeTraceRecorder::trimLattice () inline protected virtual
Remove non-accessible states.
Reimplemented in Search::Wfst::SimpleWordLatticeRecorder, Search::Wfst::DetermisticHmmLatticeTraceRecorder, and Search::Wfst::HmmLatticeTraceRecorder.
Definition at line 126 of file LatticeGenerator.hh.
References reverseLattice().
Referenced by Search::Wfst::SimpleWordLatticeRecorder::finalizeReverseLattice().
The documentation for this class was generated from the following files:
LatticeGenerator.hh
LatticeGenerator.cc