Sprint: AdvancedTreeSearch::LanguageModelLookahead Class Reference
AdvancedTreeSearch::LanguageModelLookahead Class Reference
Language model look-ahead.
#include <LanguageModelLookahead.hh>
Classes
class ContextLookahead
class LookAheadNodesForDepth
struct Node
Public Types
typedef u32 LookaheadId
typedef f32 Score
typedef Core::Ref< const ContextLookahead > ContextLookaheadReference
Public Member Functions
LanguageModelLookahead (Core::Configuration const &, Lm::Score wpScale, Core::Ref< const Lm::ScaledLanguageModel >, Search::HMMStateNetwork const &tree, Search::StateId rootNode, std::vector< Search::PersistentStateTree::Exit > const &exits, Core::Ref< const Am::AcousticModel >)
void draw (std::ostream &) const
LookaheadId lookaheadId (Search::StateTree::StateId s) const
uint lookaheadHash (Search::StateTree::StateId s) const
int nodeDepth (LookaheadId node) const
Lm::History getReducedHistory (const Lm::History &history) const
ContextLookaheadReference getLookahead (const Lm::History &, bool noHistoryLimit=false) const
Returns the LM look-ahead table for the given history.
ContextLookaheadReference tryToGetLookahead (const Lm::History &, bool noHistoryLimit=false) const
Returns the LM look-ahead table for the given history.
void fill (ContextLookaheadReference lah, bool sparse=false, bool approx=false)
Fills the LM look-ahead table.
void fillZero (ContextLookaheadReference lah)
Fills the LM look-ahead table with zeroes (non-sparse).
LookaheadId lastNodeOnDepth (int depth) const
u32 numNodes () const
void collectStatistics () const
void logStatistics () const
bool isSingleWordNode (LookaheadId node) const
returns true if the given look-ahead node leads to exactly one word-end
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Attributes
static const Core::ParameterInt paramHistoryLimit
static const Core::ParameterInt paramTreeCutoff
static const Core::ParameterInt paramMinimumRepresentation
static const Core::ParameterInt paramCacheSizeLow
static const Core::ParameterInt paramCacheSizeHigh
static const Core::ParameterBool paramConsiderBackOffInMaximization
static const Core::ParameterBool paramSparseThresholdExpectationBased
static const Core::ParameterBool paramConsiderPronunciationScore
static const Core::ParameterBool paramConsiderExitPenalty
static const Core::ParameterFloat paramSparseLookAheadThreshold
static const Core::ParameterFloat paramSparseHashSizeFactor
static const Core::ParameterFloat paramSparseHashResizeAtFill
static const Core::ParameterFloat paramLmLookaheadScale
static const Core::ParameterString paramObservationStats
static const Core::ParameterInt paramCollisionHashSize
static const Core::ParameterFloat paramMaxCollisionDeviation
static const Core::ParameterString paramCacheArchive
Private Types
typedef std::vector< const Bliss::LemmaPronunciation * > Ends
typedef Core::ConstantVector< LookaheadId > Successors
typedef std::list< ContextLookahead * > List
typedef std::unordered_map< Lm::History, ContextLookahead *, Lm::History::Hash > Map
Private Member Functions
bool shouldPruneConstructionNode (const ConstructionNode &sn) const
Decide whether a look-ahead node should be merged with its father.
void buildCompressesLookaheadStructure (u32 nodeStart, u32 numNodes, ConstructionTree const &)
Initialize internal compact look-ahead structure from construction tree.
void buildBatchRequest ()
void buildHash ()
void buildLookaheadStructure (Search::HMMStateNetwork const &tree, Search::StateId rootNode, std::vector< Search::PersistentStateTree::Exit > const &exits)
void computeScores (Lm::History const &, std::vector< Score > &) const
template<bool approx>
bool computeScoresSparse (ContextLookahead &lookahead) const
ContextLookahead * acquireTable (Lm::History const &) const
ContextLookahead * getCachedTable (Lm::History const &) const
void releaseTable (ContextLookahead const *) const
Score getLmScale () const
std::string archiveEntry () const
u32 nTables () const
u32 nActiveTables () const
void buildDepths ()
template<class Hash >
void assignHashes (std::string hashName, Hash &hash, u32 testHashSize)
void propagateDepth (int node, int depth)
bool readPersistentCache ()
void writePersistentCache ()
Private Attributes
s32 historyLimit_
s32 cutoffDepth_
u32 minimumRepresentation_
Lm::Score wpScale_
u32 maxDepth_
Core::Ref< const Lm::ScaledLanguageModel > lm_
Search::HMMStateNetwork const & tree_
Search::LinearPrediction sparseNodesPrediction_
Ends ends_
Core::ConstantVector< Score > endOffsets_
Successors successors_
Successors parents_
Core::ConstantVector< Node > nodes_
Core::ConstantVector< std::pair< LookaheadId, Score > > nodeForToken_
Core::ConstantVector< u32 > firstNodeForToken_
int invalidFirstNodeForTokenIndex_
LookaheadId nEntries_
Core::ConstantVector< LookaheadId > nodeId_
Core::ConstantVector< u32 > hashForState_
Core::ConstantVector< u32 > hashForNode_
const Lm::CompiledBatchRequest * batchRequest_
u32 cacheSizeHighMark_
u32 cacheSizeLowMark_
List tables_
List freeTables_
u32 nTables_
u32 nFreeTables_
Map map_
CacheStatistics * cacheStatistics_
Core::XmlChannel statisticsChannel_
bool considerBackOffInMaximization_
bool considerPronunciationScore_
bool considerExitPenalty_
bool sparseThresholdExpectationBased_
float logSemiringFactor_
f64 sparseLookAheadThreshold_
f32 sparseHashSizeFactor_
u32 sparseHashResizeAtFillFraction_
Core::Ref< const Am::AcousticModel > acousticModel_
std::vector< LookAheadNodesForDepth > waitingLookaheadNodesByDepth_
std::vector< u32 > nodeRecombination_
bool accumulateNodeObservations_
f32 scale_
Static Private Attributes
static const LookaheadId invalidId = Core::Type<LanguageModelLookahead::LookaheadId>::max
Friends
class LanguageModelLookahead::ConstructionTree
class ContextLookahead
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Language model look-ahead.
Definition at line 65 of file AdvancedTreeSearch/LanguageModelLookahead.hh.
Member Function Documentation
void LanguageModelLookahead::buildCompressesLookaheadStructure (u32 nodeStart, u32 numNodes, ConstructionTree const & ct) private
Initialize internal compact look-ahead structure from construction tree.
Definition at line 1101 of file AdvancedTreeSearch/LanguageModelLookahead.cc.
References Core::form(), Core::Application::getCacheArchiveReader(), Core::Application::getCacheArchiveWriter(), Core::MappedArchiveReader::good(), Core::Channel::isOpen(), Core::Component::log(), require, Search::HMMStateNetwork::stateCount(), Core::Application::us(), and verify.
template<bool approx> bool LanguageModelLookahead::computeScoresSparse (LanguageModelLookahead::ContextLookahead & lookahead) const private
Todo:
Not required once tables are managed properly
Definition at line 1642 of file AdvancedTreeSearch/LanguageModelLookahead.cc.
References ensure, Lm::BackingOffLm::getBackOffScores(), Lm::BackingOffLm::reducedHistory(), require, and verify.
void LanguageModelLookahead::fill (ContextLookaheadReference lah, bool sparse = false, bool approx = false)
Fills the LM look-ahead table.
This must be called before tables retrieved through getLookahead can be used.
Todo:
If another thread is filling this table, wait
Definition at line 2012 of file AdvancedTreeSearch/LanguageModelLookahead.cc.
References Core::Ref< T >::get(), and verify.
Referenced by Search::SearchSpace::activateLmLookahead(), and Search::SearchSpace::setAllowHmmSkips().
void LanguageModelLookahead::fillZero (ContextLookaheadReference lah)
Fills the LM look-ahead table with zeroes (non-sparse).
Definition at line 2038 of file AdvancedTreeSearch/LanguageModelLookahead.cc.
References Core::Ref< T >::get().
Referenced by Search::SearchSpace::setAllowHmmSkips().
LanguageModelLookahead::ContextLookaheadReference LanguageModelLookahead::getLookahead (const Lm::History & fh, bool noHistoryLimit = false) const
Returns the LM look-ahead table for the given history.
The table may be unfinished, fill(..) must be called to fill it.
Definition at line 1994 of file AdvancedTreeSearch/LanguageModelLookahead.cc.
References ensure.
Referenced by Search::SearchSpace::activateLmLookahead(), and Search::SearchSpace::setAllowHmmSkips().
bool AdvancedTreeSearch::LanguageModelLookahead::isSingleWordNode (LanguageModelLookahead::LookaheadId node) const inline
returns true if the given look-ahead node leads to exactly one word-end
Definition at line 370 of file AdvancedTreeSearch/LanguageModelLookahead.hh.
bool LanguageModelLookahead::shouldPruneConstructionNode (const ConstructionNode & sn) const private
Decide whether a look-ahead node should be merged with its father.
Definition at line 792 of file AdvancedTreeSearch/LanguageModelLookahead.cc.
LanguageModelLookahead::ContextLookaheadReference LanguageModelLookahead::tryToGetLookahead (const Lm::History & fh, bool noHistoryLimit = false) const
Returns the LM look-ahead table for the given history.
The table is always filled.
Definition at line 2049 of file AdvancedTreeSearch/LanguageModelLookahead.cc.
References ensure, and verify.
Referenced by Search::SearchSpace::activateLmLookahead().
The documentation for this class was generated from the following files:
AdvancedTreeSearch/LanguageModelLookahead.hh
AdvancedTreeSearch/LanguageModelLookahead.cc