Sprint: Flow::Link Class Reference
Flow::Link Class Reference
Public Member Functions
void clear ()
bool isDataAvailable ()
template<class T >
bool getData (DataPtr< T > &d)
ssize_t getRemainingDataLen ()
bool putData (Data *d)
Send data packet to down-stream Node.
const Datatype * datatype () const
Datatype as advertised by source node.
void setDatatype (const std::string &dt)
void setAttributes (Core::Ref< const Attributes > a)
Core::Ref< const Attributes > attributes () const
void eraseAttributes ()
bool areAttributesAvailable () const
void setNodeNames (std::string from_n, std::string from_p, std::string to_n, std::string to_p)
void getNodeNames (std::string *const from_n, std::string *from_p, std::string *to_n, std::string *to_p) const
void configure ()
bool isFast ()
void setFromNode (AbstractNode *n)
void setFromPort (PortId id)
void setToNode (AbstractNode *n)
void setToPort (PortId id)
void setBuffer (u32 size)
u32 getBuffer ()
AbstractNode * getFromNode () const
PortId getFromPort () const
AbstractNode * getToNode () const
PortId getToPort () const
Static Private Member Functions
static Data * sentinelEmpty ()
Represents the status of fast_data_.
static bool isEmpty (Data *t)
Private Attributes
AbstractNode * from_node_
PortId from_port_
AbstractNode * to_node_
PortId to_port_
bool is_fast_
std::string from_node_name_
std::string from_port_name_
std::string to_node_name_
std::string to_port_name_
u32 buffer_
Queue queue_
const Datatype * datatype_
Core::Ref< const Attributes > attributes_
Data * fast_data_
Friends
std::ostream & operator<< (std::ostream &o, const Link &l)
std::ostream & operator<< (std::ostream &o, const Link *l)
Detailed Description
Definition at line 30 of file Link.hh.
Member Function Documentation
const Datatype* Flow::Link::datatype () const inline
Datatype as advertised by source node.
Definition at line 122 of file Link.hh.
References Core::Ref< T >::reset().
Referenced by putData().
bool Flow::Link::putData (Data * d) inline
Send data packet to down-stream Node.
Returns
true on success (Note: Won't fail anyway.)
Definition at line 96 of file Link.hh.
References datatype(), require, and sentinelEmpty().
static Data* Flow::Link::sentinelEmpty () inline static private
Represents the status of fast_data_.
fast_data_ can be either "empty" or occupied by a data or also by a non-data object. Link does not differentiate data and non-data objects.
Definition at line 53 of file Link.hh.
References verify.
Referenced by putData().
The documentation for this class was generated from the following files:
Link.hh
Link.cc