Sprint: Speech::AlignmentNode Class Reference
Speech::AlignmentNode Class Reference
AlignmentNode.
#include <AlignmentNode.hh>
Public Types
enum PhonemeSequenceSet { lemmaLoop, phoneLoop, orthography }
Public Types inherited from Flow::AbstractNode
typedef std::map< std::string, std::string > UnresolvedAttributes
Public Member Functions
AlignmentNode (const Core::Configuration &)
virtual bool configure ()
Performs static (independent of input data) configuration of node.
virtual bool work (Flow::PortId)
Processes some data.
Public Member Functions inherited from Speech::AlignmentBaseNode
AlignmentBaseNode (const Core::Configuration &)
virtual bool setParameter (const std::string &name, const std::string &value)
Set node specific parameter.
Public Member Functions inherited from Flow::SleeveNode
SleeveNode (const Core::Configuration &c)
virtual PortId getInput (const std::string &name)
Ask for an input port.
virtual PortId getOutput (const std::string &name)
Ask for an output port.
Public Member Functions inherited from Flow::Node
Node (const Core::Configuration &c)
Public Member Functions inherited from Flow::AbstractNode
AbstractNode (const Core::Configuration &c)
virtual void Run ()
void setThreaded (bool threaded=true)
void setThreaded (const std::string &threaded)
bool isThreaded () const
virtual bool addParameter (const std::string &name, const Core::StringExpression &value)
addParameter adds a parameter to the node Constant parameters are simply delegated to setParameter, parameters dependent on network parameters are stored in parameters_.
virtual ssize_t getRemainingDataLen (PortId out)
Returns the amount of remaining data items.
void addUnresolvedParameter (const std::string &key, const std::string &value)
Functions for saving and getting unresolved parameters.
const UnresolvedAttributes & unresolvedAttributes () const
bool operator< (const AbstractNode &n) const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Member Functions
static std::string filterName ()
Static Public Attributes
static const Core::ParameterBool paramStoreLattices
AlignmentNode.
static const Core::ParameterBool paramUseTracebacks
static const Core::ParameterBool paramWriteAlphabet
static const Core::Choice choicePhonemeSequenceSet
static const Core::ParameterChoice paramPhonemeSequenceSet
static const Core::ParameterBool paramNoDependencyCheck
Static Public Attributes inherited from Speech::AlignmentBaseNode
static const Core::ParameterString paramSegmentId
AlignmentBaseNode.
static const Core::ParameterString paramOrthography
static const Core::ParameterString paramLeftContextOrthography
static const Core::ParameterString paramRightContextOrthography
Static Public Attributes inherited from Flow::AbstractNode
static const Core::ParameterBool paramThreaded
static const Core::ParameterBool paramIgnoreUnknownParameters
Protected Member Functions
virtual void initialize ()
virtual void createModel ()
void checkFeatureDependencies (const Mm::Feature &) const
void logTraceback (Lattice::ConstWordLatticeRef) const
void createWordLattice (Fsa::ConstAutomatonRef alignmentFsa) const
Protected Member Functions inherited from Speech::AlignmentBaseNode
bool configure (const Flow::Datatype *)
Protected Member Functions inherited from Flow::Node
virtual PortId connectInputPort (PortId, Link *)
Connect link to input port.
virtual void disconnectInputLink (Link *)
virtual PortId connectOutputPort (PortId, Link *)
virtual void disconnectOutputLink (Link *)
PortId addInput (PortId in=IllegalPortId)
Create an input port.
PortId addInputs (u32 nPorts)
Create several input ports.
virtual PortId nInputs () const
Link * getInputLink (PortId in) const
virtual PortId inputConnected (PortId in) const
bool validInputPort (PortId in) const
PortId addOutput (PortId out=IllegalPortId)
Add an output port.
PortId addOutputs (u32 nPorts)
Create several output ports.
virtual PortId nOutputs () const
bool validOutputPort (PortId out) const
virtual u32 nOutputLinks (PortId out) const
Number of link connceted to an output port.
bool configureDatatype (Core::Ref< const Attributes > a, const Datatype *d)
template<class T >
bool getData (PortId in, DataPtr< T > &d)
Fetch data packet from input port.
virtual bool putData (PortId out, Data *d)
Send data packet on output port.
bool putEos (PortId out)
Send end-of-stream on output port.
bool putOod (PortId out)
Send out-of-data on output port.
Core::Ref< const Attributes > getInputAttributes (PortId in)
Retrieve attribute set from input port.
void getInputAttributes (PortId, Attributes &)
bool putOutputAttributes (PortId out, Core::Ref< const Attributes > a)
Put attribute set on output port.
void eraseOutputAttributes ()
Erases attributes of all output links recursively.
Protected Member Functions inherited from Flow::AbstractNode
template<class T >
bool getData (Link *l, DataPtr< T > &d)
Fetch data packet from the "from" port of link.
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes
Core::Ref< Am::AcousticModel > acousticModel_
Core::XmlChannel tracebackChannel_
std::vector< Flow::Timestamp > featureTimes_
Lattice::ArchiveWriter * latticeArchiveWriter_
Lattice::ArchiveReader * tracebackArchiveReader_
FsaCache * transducerCache_
Search::Aligner aligner_
bool writeAlphabet_
Protected Attributes inherited from Speech::AlignmentBaseNode
std::string segmentId_
std::string orthography_
std::string leftContextOrthography_
std::string rightContextOrthography_
AllophoneStateGraphBuilder * allophoneStateGraphBuilder_
Fsa::ConstAutomatonRef lemmaPronunciationToLemma_
FsaCache * modelCache_
bool needInit_
Protected Attributes inherited from Core::Configurable
Configuration config
Private Types
typedef AlignmentBaseNode Precursor
Private Attributes
Search::Aligner::WordLatticeBuilder * wordLatticeBuilder_
PhonemeSequenceSet phonemeSequenceSet_
const bool noDependencyCheck_
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Detailed Description
AlignmentNode.
Definition at line 69 of file AlignmentNode.hh.
Member Function Documentation
bool AlignmentNode::configure () virtual
Performs static (independent of input data) configuration of node.
Configure is called if one of the output attributes is not available. Override this function to evaluate all input attributes and pass them on to successor nodes. The default implementation simply forwards the merged attributes from all input links to all outputs. Note: -we assume no dead inputs here. -This function is the safest point to reset the algorithms used by the node. The alternative would be to reset the algorithms when a non-data object has been recieved. This solution can lead easily to unintended behaviour, since it is not garatinteed at all that every node receives for example a EOS object!
Reimplemented from Speech::AlignmentBaseNode.
Definition at line 151 of file AlignmentNode.cc.
References Lattice::WordLattice::acousticFsa, Speech::SegmentNode::configure(), Core::Component::criticalError(), Core::Ref< T >::get(), Core::Component::initialize(), Mc::Component::load(), Core::Component::log(), verify, and Core::Component::warning().
bool AlignmentNode::work (Flow::PortId out) virtual
Processes some data.
Implement this function to do whatever your node is supposed to. You are required to produce at least one packet of data on the specified output out. You may send more packets, also to other outputs.
Returns
true on success, false on end-of-file or error. The idiom is:
return putData(out, d);
Implements Flow::Node.
Definition at line 272 of file AlignmentNode.cc.
References Lattice::WordLattice::acousticFsa, Flow::Node::addInputs(), Flow::Node::addOutputs(), Core::Component::error(), Flow::Node::getData(), Mc::Component::load(), Speech::AlignmentDumpNode::paramFilename, Speech::SegmentNode::paramSegmentId, Flow::Node::putData(), Core::TsRef< T >::reset(), Speech::Alignment::setAlphabet(), Core::strconv(), verify, and Core::Component::warning().
Member Data Documentation
const Core::ParameterBool AlignmentNode::paramStoreLattices static
AlignmentNode.
Definition at line 73 of file AlignmentNode.hh.
Referenced by Speech::AlignmentBaseNode::configure().
The documentation for this class was generated from the following files:
AlignmentNode.hh
AlignmentNode.cc