Sprint: Bliss::ProgressReportingVisitorAdaptor Class Reference
Bliss::ProgressReportingVisitorAdaptor Class Reference
Public Member Functions
ProgressReportingVisitorAdaptor (Core::XmlChannel &ch, bool reportOrth=false)
void setVisitor (CorpusVisitor *v)
virtual void enterCorpus (Corpus *c)
Template method notifying start of a (sub-) corpus.
virtual void leaveCorpus (Corpus *c)
Template method notifying end of a (sub-) corpus.
virtual void enterRecording (Recording *r)
Template method called when corpus traversal enters a recording.
virtual void leaveRecording (Bliss::Recording *r)
Template method called when corpus traversal leaves a recording.
virtual void visitSegment (Segment *s)
Template method for processing segments.
virtual void visitSpeechSegment (SpeechSegment *s)
Template method for processing speech segments.
Private Member Functions
void openSegment (Segment *s)
void closeSegment (Segment *s)
Private Attributes
CorpusVisitor * visitor_
Core::XmlChannel & channel_
bool reportSegmentOrth_
Detailed Description
Definition at line 612 of file CorpusDescription.hh.
Member Function Documentation
void ProgressReportingVisitorAdaptor::enterCorpus (Corpus *) virtual
Template method notifying start of a (sub-) corpus.
This is rarely needed.
Reimplemented from Bliss::CorpusVisitor.
Definition at line 337 of file CorpusDescription.cc.
void ProgressReportingVisitorAdaptor::enterRecording (Recording *) virtual
Template method called when corpus traversal enters a recording.
Implement this to take appropriate actions, e.g. opening the audio file.
Reimplemented from Bliss::CorpusVisitor.
Definition at line 347 of file CorpusDescription.cc.
void ProgressReportingVisitorAdaptor::leaveCorpus (Corpus *) virtual
Template method notifying end of a (sub-) corpus.
This is rarely needed.
Reimplemented from Bliss::CorpusVisitor.
Definition at line 342 of file CorpusDescription.cc.
void ProgressReportingVisitorAdaptor::leaveRecording (Bliss::Recording *) virtual
Template method called when corpus traversal leaves a recording.
Implement this to take appropriate clean-up actions, e.g. closing the audio file.
Reimplemented from Bliss::CorpusVisitor.
Definition at line 359 of file CorpusDescription.cc.
References Bliss::Segment::condition(), Bliss::Segment::end(), Bliss::Segment::start(), and Bliss::Segment::track().
void ProgressReportingVisitorAdaptor::visitSegment (Segment *) virtual
Template method for processing segments.
Implement this to process speech and non-speech segments of a corpus.
Reimplemented from Bliss::SegmentVisitor.
Definition at line 375 of file CorpusDescription.cc.
void ProgressReportingVisitorAdaptor::visitSpeechSegment (SpeechSegment * s) virtual
Template method for processing speech segments.
Implement this to process the speech segments of a corpus. By default the request will be forwarded to visitSegment(), so ignore this if you want to treat speech and non-speech segments alike.
Reimplemented from Bliss::SegmentVisitor.
Definition at line 380 of file CorpusDescription.cc.
References Bliss::SpeechSegment::speaker().
The documentation for this class was generated from the following files:
CorpusDescription.hh
CorpusDescription.cc