Sprint: Ftl::DfsState< _Automaton > Class Template Reference
Ftl::DfsState< _Automaton > Class Template Reference
Due to the principle of on-demand computation, exploring automata becomes an important issue as states are not directly accessable.
#include <tDfs.hh>
Public Types
typedef _Automaton::Arc _Arc
typedef _Automaton::State _State
typedef _Automaton::ConstStateRef _ConstStateRef
typedef _Automaton::ConstRef _ConstAutomatonRef
typedef Fsa::StateId Color
The possible colors of a state.
Public Member Functions
DfsState (_ConstAutomatonRef f)
virtual void discoverState (_ConstStateRef sp)
Called upon first discovery of a state.
virtual void finishState (Fsa::StateId s)
Called after all subtrees starting at a previously discovered state have been processed.
virtual void exploreTreeArc (_ConstStateRef from, const _Arc &a)
Called upon discovery of a tree arc.
virtual void exploreNonTreeArc (_ConstStateRef from, const _Arc &a)
Called upon discovery of a non-tree arc.
virtual void finishArc (_ConstStateRef from, const _Arc &a)
Called after all subtrees starting at a previously explored arc have been processed.
virtual void finish ()
Called after all states reachable from the initial state have been processed.
Fsa::StateId maxStateId () const
Request the highest state id of the automaton.
Fsa::StateId size () const
Color color (Fsa::StateId s) const
Request the color of a state.
Fsa::StateId predecessor (Fsa::StateId s) const
Request the predecessor of a state.
void dfs (Core::ProgressIndicator *p=0)
Initiate searching the automaton.
void recursiveDfs (Core::ProgressIndicator *p=0)
Initiate searching the automaton.
Static Public Attributes
static const Color White = 0xc0000000
static const Color Gray = 0x80000000
static const Color Black = 0x40000000
Protected Attributes
_ConstAutomatonRef fsa_
Core::Vector< Fsa::StateId > info_
Private Member Functions
void setColor (Fsa::StateId s, Color c)
void setPredecessor (Fsa::StateId s, Fsa::StateId p)
Detailed Description
template<class _Automaton>
class Ftl::DfsState< _Automaton >
Due to the principle of on-demand computation, exploring automata becomes an important issue as states are not directly accessable.
Fsa provides this general implementation of depth-first search and makes intense use of it itself. Details of the algorithm can be looked up in (Cormen et al.). It stores state information in a single vector. DfsState uses the design pattern of a state. Intended use is as follows:
derive a specialized depth-first search state from DfsState
overload callback methods appropriately
create an instance of your state and pass automaton to it
call dfs to process your automaton
The use of the state design pattern allows that information gathered upon traversal of the automaton is being kept after traversal.
Definition at line 43 of file tDfs.hh.
Member Typedef Documentation
template<class _Automaton > typedef Fsa::StateId Ftl::DfsState< _Automaton >::Color
The possible colors of a state.
Definition at line 52 of file tDfs.hh.
Member Function Documentation
template<class _Automaton > Color Ftl::DfsState< _Automaton >::color (Fsa::StateId s) const inline
Request the color of a state.
Parameters
s the state id
Returns
the color of the state (see above)
Definition at line 140 of file tDfs.hh.
template<class _Automaton > void Ftl::DfsState< _Automaton >::dfs (Core::ProgressIndicator * p = 0)
Initiate searching the automaton.
Parameters
p a pointer to a progress indicator
Definition at line 21 of file tDfs.cc.
References Core::ProgressIndicator::finish(), Core::ProgressIndicator::notify(), Core::ProgressIndicator::setTotal(), and Core::ProgressIndicator::start().
Referenced by Ftl::count(), Ftl::countInput(), Ftl::countLinearStates(), Ftl::countOutput(), Lattice::density(), Ftl::CopyDfsState< _Automaton >::discoverState(), Ftl::DrawDotDfsState< _Automaton >::discoverState(), Ftl::WriteAttDfsState< _Automaton >::discoverState(), Ftl::WriteBinaryDfsState< _Automaton >::discoverState(), Ftl::WriteLinearDfsState< _Automaton >::discoverState(), Ftl::WriteXmlDfsState< _Automaton >::discoverState(), Ftl::TransposeDfsState< _Automaton >::discoverState(), Lattice::SmoothedFrameStateAccuracyAutomaton::LatticeToActiveStates::finish(), Lattice::CheckPosteriorDfsState::finish(), Ftl::EdgeTrWGWriter< _Automaton >::finish(), Lattice::WeightedFramePhoneAccuracyAutomaton::SetDerivativesDfsState::finish(), Fsa::StatePotentials64DfsState::finishState(), Fsa::StatePotentialsEDfsState::finishState(), Ftl::inDegree(), Ftl::isAcyclic(), Ftl::isEmpty(), Ftl::DfsState< _Automaton >::predecessor(), and Ftl::topologicallySort().
template<class _Automaton > virtual void Ftl::DfsState< _Automaton >::discoverState (_ConstStateRef sp) inline virtual
Called upon first discovery of a state.
Parameters
sp reference to state
Reimplemented in Ftl::AllSuffixesAutomaton< _Automaton >::ReachableStateFinder, Ftl::AllPrefixesAutomaton< _Automaton >::ProductiveStateFinder, Ftl::TransposeDfsState< _Automaton >, Ftl::NodeTrWGWriter< _Automaton >, Ftl::WriteXmlDfsState< _Automaton >, Ftl::WriteLinearDfsState< _Automaton >, Ftl::CountOutputDfsState< _Automaton >, Ftl::CountInputDfsState< _Automaton >, Ftl::WriteBinaryDfsState< _Automaton >, Ftl::CountLinearStatesDfsState< _Automaton >, OpenFst::ConvertFsaDfsState< _Automaton >, Ftl::WriteAttDfsState< _Automaton >, Ftl::DrawDotDfsState< _Automaton >, Ftl::CoaccessibleDfsState< _Automaton >, Ftl::CopyDfsState< _Automaton >, and Ftl::CountDfsState< _Automaton >.
Definition at line 78 of file tDfs.hh.
template<class _Automaton > virtual void Ftl::DfsState< _Automaton >::exploreNonTreeArc (_ConstStateRef from, const _Arc & a) inline virtual
Called upon discovery of a non-tree arc.
Non-tree arcs may close a loop, but this is not necessarily the case. To be precise, a loop occurs if the target state is grey. Such arcs are called "backward" arcs. Trivial loops (source state is target state) are also non tree arcs.
Parameters
from reference to the start state
a reference to the arc
Reimplemented in Ftl::AllPrefixesAutomaton< _Automaton >::ProductiveStateFinder, Ftl::EdgeTrWGWriter< _Automaton >, Ftl::TopologicallySortDfsState< _Automaton >, Ftl::InDegreeDfsState< _Automaton >, and Ftl::CoaccessibleDfsState< _Automaton >.
Definition at line 106 of file tDfs.hh.
template<class _Automaton > virtual void Ftl::DfsState< _Automaton >::exploreTreeArc (_ConstStateRef from, const _Arc & a) inline virtual
Called upon discovery of a tree arc.
Tree arcs never close a loop. For this reason they are "forward" arcs.
Parameters
from reference to the start state
a reference to the arc
Reimplemented in Ftl::EdgeTrWGWriter< _Automaton >, and Ftl::InDegreeDfsState< _Automaton >.
Definition at line 94 of file tDfs.hh.
Referenced by Ftl::EdgeTrWGWriter< _Automaton >::exploreNonTreeArc().
template<class _Automaton > virtual void Ftl::DfsState< _Automaton >::finish () inline virtual
Called after all states reachable from the initial state have been processed.
Reimplemented in Lattice::WeightedFramePhoneAccuracyAutomaton::SetDerivativesDfsState, Ftl::EdgeTrWGWriter< _Automaton >, Ftl::NodeTrWGWriter< _Automaton >, Lattice::CachedAcousticAccumulator< Trainer >, Lattice::TimeframeErrorDfsState, Lattice::DensityDfsState, Lattice::DensityCachedAcousticAccumulator< Trainer >, Lattice::CachedAcousticSparseAccumulator< Trainer >, Lattice::CheckPosteriorDfsState, Nn::CachedAcousticAccumulator< Trainer >, and Lattice::SmoothedFrameStateAccuracyAutomaton::LatticeToActiveStates.
Definition at line 121 of file tDfs.hh.
template<class _Automaton > virtual void Ftl::DfsState< _Automaton >::finishArc (_ConstStateRef from, const _Arc & a) inline virtual
Called after all subtrees starting at a previously explored arc have been processed.
Note: This function is called only within the recursive traversal.
Parameters
from reference to the start state
a reference to the arc
Definition at line 115 of file tDfs.hh.
template<class _Automaton > virtual void Ftl::DfsState< _Automaton >::finishState (Fsa::StateId s) inline virtual
Called after all subtrees starting at a previously discovered state have been processed.
Parameters
s index of the state
Reimplemented in Flf::FindTopologicalOrder, Flf::SortInTopologicalOrder, Ftl::SsspBackward4SpecialSymbols< _Automaton, _Semiring, _Weight >, Ftl::SsspBackward4SpecialSymbols< _Automaton >, Ftl::TopologicallySortDfsState< _Automaton >, Fsa::StatePotentialsEDfsState, Flf::FwdBwd::Builder::TraverseLatticeProperties, Fsa::StatePotentials64DfsState, and Ftl::CoaccessibleDfsState< _Automaton >.
Definition at line 85 of file tDfs.hh.
template<class _Automaton > Fsa::StateId Ftl::DfsState< _Automaton >::maxStateId () const inline
Request the highest state id of the automaton.
Returns
the state id
Definition at line 127 of file tDfs.hh.
template<class _Automaton > Fsa::StateId Ftl::DfsState< _Automaton >::predecessor (Fsa::StateId s) const inline
Request the predecessor of a state.
Parameters
s the state id
Returns
the predecessor of a state
Definition at line 149 of file tDfs.hh.
References Ftl::DfsState< _Automaton >::dfs(), and Ftl::DfsState< _Automaton >::recursiveDfs().
template<class _Automaton > void Ftl::DfsState< _Automaton >::recursiveDfs (Core::ProgressIndicator * p = 0)
Initiate searching the automaton.
Unlike dfs(), recursiveDfs() visits the arc in the same order like a recursive depth first search.
Parameters
p a pointer to a progress indicator
Definition at line 71 of file tDfs.cc.
References Core::ProgressIndicator::finish(), Core::ProgressIndicator::notify(), require, Core::ProgressIndicator::setTotal(), and Core::ProgressIndicator::start().
Referenced by Ftl::DfsState< _Automaton >::predecessor().
The documentation for this class was generated from the following files:
tDfs.hh
tDfs.cc