Sprint: Search::StateTreeWriter Class Reference
Search::StateTreeWriter Class Reference
Writes a state tree to a binary file.
#include <StateTreeIo.hh>
Public Member Functions
StateTreeWriter (Bliss::LexiconRef lexicon, Am::AcousticModelRef acousticModel)
bool write (const StateTree &tree, const std::string &filename)
Public Member Functions inherited from Search::StateTreeIo
StateTreeIo (Bliss::LexiconRef lexicon, Am::AcousticModelRef acousticModel)
Protected Member Functions
Position writeHeader (Core::BinaryOutputStream &) const
void writeDependenciesPosition (Core::BinaryOutputStream &, Position) const
Write position of the dependencies to the file at position position.
bool writeDependencies (const std::string &filename, Position) const
bool writeTree (const StateTree &tree, Core::BinaryOutputStream &) const
Protected Member Functions inherited from Search::StateTreeIo
void getDependencies ()
void getTreeDependencies (const StateTree &tree)
template<class T >
void read (Input &i, T &v) const
template<class T >
void write (Output &o, const T &v) const
template<class T , template< typename, typename > class Container>
void read (Input &i, Container< T, std::allocator< T >> &c) const
template<class T , template< typename, typename > class Container>
void write (Output &o, const Container< T, std::allocator< T >> c) const
template<class Iterator >
void write (Output &o, Iterator begin, Iterator end) const
template<class Iterator >
void read (Input &i, Iterator begin, Iterator end) const
Additional Inherited Members
Protected Types inherited from Search::StateTreeIo
typedef Core::BinaryInputStream Input
typedef Core::BinaryOutputStream Output
typedef u64 Position
typedef u32 ContainerSize
Protected Attributes inherited from Search::StateTreeIo
Core::DependencySet dependencies_
Static Protected Attributes inherited from Search::StateTreeIo
static const std::string magic = "SPRINT-ST"
static const int fileFormatVersion = 5
static const std::string sectionDependencies
static const std::string sectionStateTree
Detailed Description
Writes a state tree to a binary file.
Definition at line 127 of file StateTreeIo.hh.
Member Function Documentation
void StateTreeWriter::writeDependenciesPosition (Core::BinaryOutputStream & out, Position position) const protected
Write position of the dependencies to the file at position position.
Definition at line 142 of file StateTreeIo.cc.
References Search::StateTree::batches_, Core::Component::error(), Core::Component::log(), Core::DependencySet::satisfies(), Search::StateTree::states_, Search::StateTree::successorBatches_, verify, and Core::Component::warning().
The documentation for this class was generated from the following files:
StateTreeIo.hh
StateTreeIo.cc