Sprint: Core::Application Class Reference
Core::Application Class Reference abstract
Application class:
#include <Application.hh>
Public Member Functions
virtual std::string getVariable () const
Return the name of the environment variable.
std::string getBaseName () const
Return the applications basename.
std::string getPath () const
Return the applications path.
virtual std::string getUsage () const
Overload this method to describe the usage of the application and to give a (short) description of the application.
virtual std::string getApplicationDescription () const
virtual std::string getParameterDescription () const
virtual std::string getDefaultParameterDescription () const
void reportLowLevelError (const std::string &msg="")
Errors messages are collected and later (during closeLogging()) printed to the error channel.
void setDefaultLoadConfigurationFile (bool f)
Configure default behaviour of loading a configuration file.
void setDefaultOutputXmlHeader (bool f)
Configure default behaviour of adding a valid xml header to standard channels.
void setTitle (const std::string &t)
Set the title of the application.
void setCommentCharacters (const std::string &c)
Set the set of possible comment characters for this application.
const std::string & getCommentCharacters (void) const
Return the string of comment characters.
Core::Channel & debugChannel (void)
Returns the debug binary outpput channel.
Core::XmlChannel & debugXmlChannel (void)
Returns the debug XML channel.
MappedArchiveReader getCacheArchiveReader (const std::string &archive_name, const std::string &item)
Returns a pointer to the cache-archive reader for the archive, and the specified item contained by the archive.
MappedArchiveWriter getCacheArchiveWriter (const std::string &archive_name, const std::string &item)
Returns a pointer to the cache-archive writer for the archive, and the specified item contained by the archive.
virtual int main (const std::vector< std::string > &arguments)=0
Main entry point for an application.
void exit (int status)
Terminate program execution.
void atexit (std::function< void()> f)
Like std::atexit() but will be execute sooner, at our own uninit, at the end of our main(), or in our exit().
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Member Functions
static Application * us ()
Get the global instance of the application (Singleton)
static int main (int argc, char *argv[])
private
Protected Member Functions
void logSystemInfo () const
void logVersion () const
void logResources () const
void logResourceUsage () const
void logMemoryUsage () const
MappedArchive * getCacheArchive (const std::string &archive)
void openLogging ()
Opens channels and makes initial logs.
void closeLogging (bool configAvailable=true)
Closes down channels and makes final logs.
int run (const std::vector< std::string > &arguments)
void runAtExitFuncs ()
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Static Protected Member Functions
static bool setFromEnvironment (const std::string &variable)
static bool setFromFile (const std::string &filename)
static std::vector< std::string > setFromCommandline (const std::vector< std::string > &arguments)
Protected Attributes
Channel::Manager * channelManager_
Core::Channel * debugChannel_
Core::XmlChannel * debugXmlChannel_
std::map< std::string, MappedArchive * > cacheArchives_
bool defaultLoadConfigurationFile_
bool defaultOutputXmlHeader_
std::string comment_
std::string configFileName_
Timer timer_
std::list< std::function< void()> > atExitFuncs_
Protected Attributes inherited from Core::Configurable
Configuration config
Static Protected Attributes
static const ParameterBool paramLogConfiguration
static const ParameterBool paramLogResolvedResources
static const ParameterString paramConfig
static const ParameterString paramCacheArchiveFile
static const ParameterBool paramCacheArchiveReadOnly
static const ParameterBool paramHelp
static std::string path_ = "."
static std::string basename_ = ""
static Application * app_ = 0
Private Attributes
std::vector< std::string > lowLevelErrorMessages_
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Detailed Description
Application class:
The application class provides a suitable wrapper for
global initializations
configuration
C++-like entry and exit points
The default configuration mechanism consists of
preparsing the commandline arguments and look for parameter '–config'
reading the configuration file
parsing the environment variable
final parsing of the commandline arguments
The default name of the configuration file is the application title provided to the constructor concatenated by '.config'. The default name of the environment variable is the capitalized application title.
To build a concrete application, derive from Core::Application and use the macro APPLICATION(ConcreteApplicationClass) to create the class instance and the global entry point. Individual modules have to be initialized in the application class constructor using INIT_MODULE(Module). Initialization is required to register Flow nodes etc.
Definition at line 71 of file Application.hh.
Member Function Documentation
void Application::atexit (std::function< void()> f)
Like std::atexit() but will be execute sooner, at our own uninit, at the end of our main(), or in our exit().
Definition at line 269 of file Application.cc.
Referenced by getCommentCharacters().
void Application::closeLogging (bool configAvailable = true) protected
Closes down channels and makes final logs.
Parameters
configAvailable is used if this function is called from the destructor of an application instance. In this case the global static configuration database might already be destroyed.
Definition at line 300 of file Application.cc.
References Core::Component::error().
Core::Channel & Application::debugChannel (void)
Returns the debug binary outpput channel.
Definition at line 99 of file Application.cc.
References Core::Component::error().
Referenced by getCommentCharacters().
Core::XmlChannel & Application::debugXmlChannel (void)
Returns the debug XML channel.
Definition at line 109 of file Application.cc.
References Core::Component::error().
Referenced by getCommentCharacters().
void Application::exit (int status)
Terminate program execution.
This function never returns.
Parameters
status
Definition at line 261 of file Application.cc.
References Core::Component::exit().
std::string Application::getBaseName () const
Return the applications basename.
Definition at line 140 of file Application.cc.
Referenced by us().
MappedArchiveReader Application::getCacheArchiveReader (const std::string & archive_name, const std::string & item)
Returns a pointer to the cache-archive reader for the archive, and the specified item contained by the archive.
Returns zero if the given cache-archive was not configured, or if the item doesn't exist in the archive.
The archive has to be configured through "archive-name.file=X" configuration
Definition at line 372 of file Application.cc.
References Core::MappedArchive::getReader(), and Core::Component::log().
Referenced by AdvancedTreeSearch::LanguageModelLookahead::buildCompressesLookaheadStructure(), AdvancedTreeSearch::AcousticLookAhead::AcousticLookAheadModel::estimate(), getCommentCharacters(), Mm::DensityClusteringBase::load(), and Search::PersistentStateTree::read().
MappedArchiveWriter Application::getCacheArchiveWriter (const std::string & archive_name, const std::string & item)
Returns a pointer to the cache-archive writer for the archive, and the specified item contained by the archive.
Returns zero if the given cache-archive was not configured, or is configured read-only (default: false).
The archive has to be configured through "archive-name.file=..." and "archive-name.read-only=..." configuration
Definition at line 381 of file Application.cc.
References Core::baseName(), Core::directoryName(), Core::MappedArchive::getWriter(), and Core::Component::log().
Referenced by AdvancedTreeSearch::LanguageModelLookahead::buildCompressesLookaheadStructure(), AdvancedTreeSearch::AcousticLookAhead::AcousticLookAheadModel::estimate(), getCommentCharacters(), Search::PersistentStateTree::write(), and Mm::DensityClusteringBase::write().
const std::string& Core::Application::getCommentCharacters (void) const inline
Return the string of comment characters.
Definition at line 212 of file Application.hh.
References atexit(), debugChannel(), debugXmlChannel(), Core::Component::exit(), getCacheArchiveReader(), getCacheArchiveWriter(), and main().
Referenced by Core::Configuration::parseInclude().
std::string Application::getPath () const
Return the applications path.
Definition at line 144 of file Application.cc.
Referenced by us().
std::string Application::getUsage () const virtual
Overload this method to describe the usage of the application and to give a (short) description of the application.
Default return string is "usage: " + getBaseName() + "[OPTION(S)]\n" Return the usage of the application.
Normally, that method does not have to be overloaded; overload getApplicationDescription() and getParamterDescription() and getDefaultParameterDescription() instead.
Reimplemented in AcousticModelTrainer, FsaTool, ArchiverApplication, TestApplication, TestApplication, NnTrainer, Costa, UnitTester, MyApplication, Aligner, CartViewer, FeatureStatistics, TestApplication, TestApplication, TestApplication, SpeechRecognizer, TestApplication, TestApplication, MatrixProfiler, TestApplication, AllophoneTool, MeanSumfileCreator, TestApplication, TestApplication, MyApplication, CartTrainer, TestApplication, TestApplication, TestApplication, TestApplication, TestApplication, MyApplication, TestApplication, TestApplication, TestApplication, TestApplication, TestApplication, TestApplication, and TestApplication.
Definition at line 172 of file Application.cc.
Referenced by us().
std::string Application::getVariable () const virtual
Return the name of the environment variable.
Overload this method to set the name of the environment variable.
Definition at line 133 of file Application.cc.
Referenced by us().
virtual int Core::Application::main (const std::vector< std::string > & arguments) pure virtual
Main entry point for an application.
Implemented in ArchiverApplication, TestApplication, FsaTool, LatticeProcessor, AcousticModelTrainer, FsaSearchBuilderTool, FlfTool, TestApplication, TestApplication, Costa, NnTrainer, UnitTester, Aligner, MyApplication, LmUtilityTool, Math::MatrixTool, CartViewer, ExtractionApplication, SpeechRecognizer, TestApplication, MatrixProfiler, FeatureStatistics, TestApplication, TestApplication, MeanSumfileCreator, TestApplication, TestApplication, TestApplication, TestApplication, AllophoneTool, MyApplication, TestApplication, CartTrainer, TestApplication, TestApplication, TestApplication, TestApplication, TestApplication, TestApplication, TestApplication, MyApplication, TestApplication, TestApplication, TestApplication, and TestApplication.
Referenced by getCommentCharacters().
int Application::main (int argc, char * argv[]) static
private
Bug:
This is a workaround for possible bug in LIBC 2.3.2. We are waiting for an answer on our bug report.
Definition at line 320 of file Application.cc.
void Application::openLogging () protected
Opens channels and makes initial logs.
Definition at line 288 of file Application.cc.
References Core::Configuration::enableLogging().
void Application::reportLowLevelError (const std::string & msg = "")
Errors messages are collected and later (during closeLogging()) printed to the error channel.
Use this, when the error can not be reported with Core::Component::error().
Parameters
msg the error message
Definition at line 257 of file Application.cc.
Referenced by us().
void Application::setCommentCharacters (const std::string & c)
Set the set of possible comment characters for this application.
Comment characters are configurable and global to an application.
Parameters
c string of possible comment characters.
Definition at line 190 of file Application.cc.
References Core::MemoryInfo::peak(), Core::MemoryInfo::size(), Core::Component::warning(), Core::Configuration::writeResolvedResources(), Core::Configuration::writeResources(), Core::Configuration::writeSources(), and Core::Configuration::writeUsage().
Referenced by us().
void Application::setDefaultLoadConfigurationFile (bool f)
Configure default behaviour of loading a configuration file.
You should call this in the constructor of your application, but not after that, because configuration files are loaded before entering main.
Parameters
f set to false if you don't want configuration files to be loaded
Definition at line 119 of file Application.cc.
Referenced by us().
void Application::setDefaultOutputXmlHeader (bool f)
Configure default behaviour of adding a valid xml header to standard channels.
You should call this in the constructor of your application, but not after that, because the xml header is output on creation of channels.
Parameters
f set to false if you don't want the xml header to be output.
Definition at line 123 of file Application.cc.
Referenced by us().
void Application::setTitle (const std::string & t)
Set the title of the application.
You should call this in the constructor of your application, but not after that, because the default configuration is not reparsed.
Parameters
t title of the application
Definition at line 127 of file Application.cc.
References ensure.
Referenced by TestApplication::getUsage(), MeanSumfileCreator::getUsage(), SpeechRecognizer::getUsage(), LatticeProcessor::LatticeProcessor(), TestApplication::TestApplication(), and us().
static Application* Core::Application::us () inline static
Get the global instance of the application (Singleton)
Definition at line 127 of file Application.hh.
References getBaseName(), getPath(), getUsage(), getVariable(), reportLowLevelError(), setCommentCharacters(), setDefaultLoadConfigurationFile(), setDefaultOutputXmlHeader(), and setTitle().
Referenced by Core::DependencySet::add(), Sparse::SingleValueSparseVector< Content >::add(), Math::CudaMatrix< T >::addMatrixProduct(), Flf::ConfusionNetworkAlignment::align(), Math::FastMatrix< T >::allocate(), Tools::BatchBuilder< SubTreeListId, StateId, Search::HMMState, invalidBatch_, 0 >::appendToBatchPrivate(), Search::PersistentStateTree::build(), Flf::buildBoundedSegments(), AdvancedTreeSearch::LanguageModelLookahead::buildCompressesLookaheadStructure(), Core::MappedArchiveReader::check(), Search::PersistentStateTree::cleanup(), Search::HMMStateNetwork::cleanup(), Flf::cleanUp(), Flow::Network::configureOutputPort(), Mm::Module_::convertMixtureSet(), Am::Module_::createAcousticModel(), Math::Module_::createEigenvalueProblem(), Mm::Module_::createFeatureScorer(), Math::Module_::createGeneralizedEigenvalueProblem(), Lm::Module_::createLanguageModel(), Mm::Module_::createMixtureSet(), Mm::Module_::createMixtureSetEstimator(), Mm::Module_::createScaledFeatureScorer(), Flf::drawDot(), Flf::Semiring::equal(), Nn::MeanNormalizedSgdL1Clipping< T >::estimate(), AdvancedTreeSearch::AcousticLookAhead::AcousticLookAheadModel::estimate(), Mm::EbwDiscriminativeMixtureEstimator::estimateMixtureWeights(), Flf::expandTransits(), Math::FastVector< T >::FastVector(), Nn::EmissionLatticeRescorer::finalize(), Signal::FullCovMonoGaussianModel::finalize(), Flf::FwdBwd::Builder::TraverseLatticeProperties::finishState(), Math::Module_::formats(), Nn::Module_::formats(), Mm::Module_::formats(), Flf::fromFsa(), Flf::FittingLattice::Boundaries::get(), Core::MappedArchive::getReader(), Search::SearchSpace::getSentenceEndFallBack(), Core::Description::Stream::getValue(), Core::MappedArchive::getWriter(), Nn::Statistics< T >::gradientL1Norm(), Flf::UnknownAlphabet::index(), Flf::Module_::init(), Flf::FwdBwdPruningNode::init(), Flf::ConfusionNetworkCombination::init(), Flf::RoverCombination::init(), Flf::NBestBuilder::initialize(), AdvancedTreeSearch::AcousticLookAhead::initializeModels(), Bliss::TheanoSegmentOrderingVisitor::leaveCorpus(), Bliss::SegmentOrderingVisitor::leaveCorpus(), Bliss::CorpusDescription::SegmentPartitionVisitorAdaptor::leaveCorpus(), Mm::DensityClusteringBase::load(), Mm::MixtureToMixtureMap::load(), Fsa::mapAlphabet(), Flf::EditDistance::normCost(), Sparse::SingleValueSparseVector< Content >::operator+=(), Search::SearchSpace::optimizeSilenceInWordLattice(), Core::Configuration::parseInclude(), Core::MemoryInfo::peak(), Tools::BatchBuilder< SubTreeListId, StateId, Search::HMMState, invalidBatch_, 0 >::print(), Speech::AbstractAcousticSegmentwiseTrainer::processWordLattice(), Flf::pruneByFwdBwdScores(), Search::PersistentStateTree::read(), Flf::readConfusionNetworkFromXml(), Mm::Module_::readMixtureSet(), Mm::Module_::readMixtureSetEstimator(), Flf::readPosteriorCnFromXml(), Mm::DiscriminativeMixtureEstimator::removeDensitiesWithLowWeight(), Search::PersistentStateTree::removeOutputs(), Mm::MixtureSet::replaceMeans(), Core::DependencySet::satisfies(), Flf::sausageLattice2cn(), Speech::LmLatticeRescorerAutomaton::score(), Flf::ComposeNode::sendLattice(), Nn::NeuralNetworkTrainer< T >::setClassWeights(), Flf::Semiring::setKeys(), Flf::Evaluator::setReference(), AcousticModelTrainer::showMixtureSet(), Core::MMappedFile::size(), Flf::stripExtension(), Flf::ExpandTransitsNode::sync(), Core::MemoryInfo::update(), Core::ResourceUsageInfo::update(), Core::Description::verifyNumberOfStreams(), Core::Description::Stream::verifyValue(), Core::DependencySet::weak_satisfies(), Flow::VectorAbsValDumpNode< content >::work(), Search::PersistentStateTree::write(), Mm::DensityClusteringBase::write(), Mm::AbstractMixtureSet::write(), Mm::Covariance::write(), Mm::MixtureSet::write(), and Mm::Module_::writeMixtureSetEstimator().
The documentation for this class was generated from the following files:
Application.hh
Application.cc