Sprint: TestApplication Class Reference
TestApplication Class Reference
Copyright 2020 RWTH Aachen University.
Public Member Functions
virtual std::string getUsage () const
Overload this method to describe the usage of the application and to give a (short) description of the application.
int main (const std::vector< std::string > &arguments)
Main entry point for an application.
virtual std::string getUsage () const
Overload this method to describe the usage of the application and to give a (short) description of the application.
int main (const std::vector< std::string > &arguments)
Main entry point for an application.
virtual std::string getUsage () const
Overload this method to describe the usage of the application and to give a (short) description of the application.
int main (const std::vector< std::string > &arguments)
Main entry point for an application.
virtual std::string getUsage () const
Overload this method to describe the usage of the application and to give a (short) description of the application.
int main (const std::vector< std::string > &arguments)
Main entry point for an application.
virtual std::string getUsage () const
Overload this method to describe the usage of the application and to give a (short) description of the application.
int main (const std::vector< std::string > &arguments)
Main entry point for an application.
std::string getUsage () const
Overload this method to describe the usage of the application and to give a (short) description of the application.
int main (const std::vector< std::string > &arguments)
Main entry point for an application.
std::string getUsage () const
Overload this method to describe the usage of the application and to give a (short) description of the application.
int main (const std::vector< std::string > &arguments)
Main entry point for an application.
std::string getUsage () const
Overload this method to describe the usage of the application and to give a (short) description of the application.
int main (const std::vector< std::string > &arguments)
Main entry point for an application.
virtual std::string getUsage () const
Overload this method to describe the usage of the application and to give a (short) description of the application.
virtual int main (const std::vector< std::string > &arguments)
Main entry point for an application.
virtual std::string getUsage () const
Overload this method to describe the usage of the application and to give a (short) description of the application.
int main (const std::vector< std::string > &arguments)
Main entry point for an application.
virtual std::string getUsage () const
Overload this method to describe the usage of the application and to give a (short) description of the application.
int main (const std::vector< std::string > &arguments)
Main entry point for an application.
virtual string getUsage () const
Overload this method to describe the usage of the application and to give a (short) description of the application.
int main (const std::vector< string > &arguments)
Main entry point for an application.
virtual std::string getUsage () const
Overload this method to describe the usage of the application and to give a (short) description of the application.
int main (const std::vector< std::string > &arguments)
Main entry point for an application.
std::string getUsage () const
Overload this method to describe the usage of the application and to give a (short) description of the application.
int main (const std::vector< std::string > &arguments)
Main entry point for an application.
virtual std::string getUsage () const
Overload this method to describe the usage of the application and to give a (short) description of the application.
int main (const std::vector< std::string > &arguments)
Main entry point for an application.
std::string getUsage () const
Overload this method to describe the usage of the application and to give a (short) description of the application.
int main (const std::vector< std::string > &arguments)
Main entry point for an application.
TestApplication ()
Standard constructor for setting title.
std::string getUsage () const
Overload this method to describe the usage of the application and to give a (short) description of the application.
int main (const std::vector< std::string > &arguments)
Main entry point for an application.
TestApplication ()
Standard constructor for setting title.
std::string getUsage () const
Overload this method to describe the usage of the application and to give a (short) description of the application.
int main (const std::vector< std::string > &arguments)
Main entry point for an application.
TestApplication ()
Standard constructor for setting title.
std::string getUsage () const
Overload this method to describe the usage of the application and to give a (short) description of the application.
void createPhoneSequence (const Am::Allophone &a, OpenFst::VectorFst *seq) const
void createPhoneSequence (const Bliss::Phoneme::Id *pron, OpenFst::VectorFst *seq) const
int checkAllophones (Core::Ref< Am::AcousticModel > am, const OpenFst::VectorFst *f) const
bool isLinearFst (const OpenFst::VectorFst &result) const
void printAllophoneSequence (Core::Ref< const Am::AllophoneAlphabet > allophones, const OpenFst::VectorFst &result) const
bool checkWord (Core::Ref< const Am::AllophoneAlphabet > allophones, Core::Ref< const Bliss::PhonemeInventory > pi, const Bliss::Phoneme::Id *pron, const OpenFst::VectorFst &result) const
int checkWords (Core::Ref< Am::AcousticModel > am, Bliss::LexiconRef lexicon, const OpenFst::VectorFst *f) const
int main (const std::vector< std::string > &arguments)
Main entry point for an application.
std::string getUsage () const
Overload this method to describe the usage of the application and to give a (short) description of the application.
int main (const std::vector< std::string > &arguments)
Main entry point for an application.
std::string getUsage () const
Overload this method to describe the usage of the application and to give a (short) description of the application.
int main (const std::vector< std::string > &arguments)
Main entry point for an application.
std::string getUsage () const
Overload this method to describe the usage of the application and to give a (short) description of the application.
int main (const std::vector< std::string > &arguments)
Main entry point for an application.
Public Member Functions inherited from Core::Application
virtual std::string getVariable () const
Return the name of the environment variable.
std::string getBaseName () const
Return the applications basename.
std::string getPath () const
Return the applications path.
virtual std::string getApplicationDescription () const
virtual std::string getParameterDescription () const
virtual std::string getDefaultParameterDescription () const
void reportLowLevelError (const std::string &msg="")
Errors messages are collected and later (during closeLogging()) printed to the error channel.
void setDefaultLoadConfigurationFile (bool f)
Configure default behaviour of loading a configuration file.
void setDefaultOutputXmlHeader (bool f)
Configure default behaviour of adding a valid xml header to standard channels.
void setTitle (const std::string &t)
Set the title of the application.
void setCommentCharacters (const std::string &c)
Set the set of possible comment characters for this application.
const std::string & getCommentCharacters (void) const
Return the string of comment characters.
Core::Channel & debugChannel (void)
Returns the debug binary outpput channel.
Core::XmlChannel & debugXmlChannel (void)
Returns the debug XML channel.
MappedArchiveReader getCacheArchiveReader (const std::string &archive_name, const std::string &item)
Returns a pointer to the cache-archive reader for the archive, and the specified item contained by the archive.
MappedArchiveWriter getCacheArchiveWriter (const std::string &archive_name, const std::string &item)
Returns a pointer to the cache-archive writer for the archive, and the specified item contained by the archive.
void exit (int status)
Terminate program execution.
void atexit (std::function< void()> f)
Like std::atexit() but will be execute sooner, at our own uninit, at the end of our main(), or in our exit().
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Attributes
static const Core::ParameterString p_network
Protected Attributes
Bliss::Phoneme::Id sil_
OpenFst::Label initialOffset_
OpenFst::Label seqEnd_
Core::Ref< Am::AcousticModel > am
const OpenFst::SymbolTable * phoneSymbols_
bool verbose_
Protected Attributes inherited from Core::Application
Channel::Manager * channelManager_
Core::Channel * debugChannel_
Core::XmlChannel * debugXmlChannel_
std::map< std::string, MappedArchive * > cacheArchives_
bool defaultLoadConfigurationFile_
bool defaultOutputXmlHeader_
std::string comment_
std::string configFileName_
Timer timer_
std::list< std::function< void()> > atExitFuncs_
Protected Attributes inherited from Core::Configurable
Configuration config
Static Protected Attributes
static const Core::ParameterInt paramInitialPhoneOffset
static const Core::ParameterString paramSilencePhone
static const Core::ParameterBool paramVerbose
static const Core::ParameterString paramSequenceEnd
Static Protected Attributes inherited from Core::Application
static const ParameterBool paramLogConfiguration
static const ParameterBool paramLogResolvedResources
static const ParameterString paramConfig
static const ParameterString paramCacheArchiveFile
static const ParameterBool paramCacheArchiveReadOnly
static const ParameterBool paramHelp
static std::string path_ = "."
static std::string basename_ = ""
static Application * app_ = 0
Static Private Attributes
static const Core::ParameterString paramDumpLexiconFsa_
static const Core::ParameterString paramDumpLmFsa_
static const Core::ParameterString paramDrawLmFsa_
Additional Inherited Members
Static Public Member Functions inherited from Core::Application
static Application * us ()
Get the global instance of the application (Singleton)
static int main (int argc, char *argv[])
private
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Application
void logSystemInfo () const
void logVersion () const
void logResources () const
void logResourceUsage () const
void logMemoryUsage () const
MappedArchive * getCacheArchive (const std::string &archive)
void openLogging ()
Opens channels and makes initial logs.
void closeLogging (bool configAvailable=true)
Closes down channels and makes final logs.
int run (const std::vector< std::string > &arguments)
void runAtExitFuncs ()
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Static Protected Member Functions inherited from Core::Application
static bool setFromEnvironment (const std::string &variable)
static bool setFromFile (const std::string &filename)
static std::vector< std::string > setFromCommandline (const std::vector< std::string > &arguments)
Detailed Description
Copyright 2020 RWTH Aachen University.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. Test suite for the Search module of SPRINT.
Definition at line 26 of file Am/check.cc.
Constructor & Destructor Documentation
TestApplication::TestApplication () inline
Standard constructor for setting title.
Definition at line 34 of file Search/check.cc.
References Core::Application::setTitle().
TestApplication::TestApplication () inline
Standard constructor for setting title.
Definition at line 32 of file Search/Wfst/check.cc.
References Core::Application::setTitle().
TestApplication::TestApplication () inline
Standard constructor for setting title.
Definition at line 36 of file check_ctrans.cc.
References Core::Application::setTitle().
Member Function Documentation
virtual std::string TestApplication::getUsage () const inline virtual
Overload this method to describe the usage of the application and to give a (short) description of the application.
Default return string is "usage: " + getBaseName() + "[OPTION(S)]\n" Return the usage of the application.
Normally, that method does not have to be overloaded; overload getApplicationDescription() and getParamterDescription() and getDefaultParameterDescription() instead.
Reimplemented from Core::Application.
Definition at line 19 of file OpenFst/check.cc.
References Core::Application::setTitle().
std::string TestApplication::getUsage () const inline virtual
Overload this method to describe the usage of the application and to give a (short) description of the application.
Default return string is "usage: " + getBaseName() + "[OPTION(S)]\n" Return the usage of the application.
Normally, that method does not have to be overloaded; overload getApplicationDescription() and getParamterDescription() and getDefaultParameterDescription() instead.
Reimplemented from Core::Application.
Definition at line 21 of file Signal/check.cc.
virtual std::string TestApplication::getUsage () const inline virtual
Overload this method to describe the usage of the application and to give a (short) description of the application.
Default return string is "usage: " + getBaseName() + "[OPTION(S)]\n" Return the usage of the application.
Normally, that method does not have to be overloaded; overload getApplicationDescription() and getParamterDescription() and getDefaultParameterDescription() instead.
Reimplemented from Core::Application.
Definition at line 22 of file Math/Lapack/check.cc.
virtual string TestApplication::getUsage () const inline virtual
Overload this method to describe the usage of the application and to give a (short) description of the application.
Default return string is "usage: " + getBaseName() + "[OPTION(S)]\n" Return the usage of the application.
Normally, that method does not have to be overloaded; overload getApplicationDescription() and getParamterDescription() and getDefaultParameterDescription() instead.
Reimplemented from Core::Application.
Definition at line 22 of file Math/Nr/check.cc.
virtual std::string TestApplication::getUsage () const inline virtual
Overload this method to describe the usage of the application and to give a (short) description of the application.
Default return string is "usage: " + getBaseName() + "[OPTION(S)]\n" Return the usage of the application.
Normally, that method does not have to be overloaded; overload getApplicationDescription() and getParamterDescription() and getDefaultParameterDescription() instead.
Reimplemented from Core::Application.
Definition at line 22 of file Math/check.cc.
References Core::Application::setTitle().
std::string TestApplication::getUsage () const inline virtual
Overload this method to describe the usage of the application and to give a (short) description of the application.
Default return string is "usage: " + getBaseName() + "[OPTION(S)]\n" Return the usage of the application.
Normally, that method does not have to be overloaded; overload getApplicationDescription() and getParamterDescription() and getDefaultParameterDescription() instead.
Reimplemented from Core::Application.
Definition at line 23 of file Flow/check.cc.
std::string TestApplication::getUsage () const inline virtual
Overload this method to describe the usage of the application and to give a (short) description of the application.
Default return string is "usage: " + getBaseName() + "[OPTION(S)]\n" Return the usage of the application.
Normally, that method does not have to be overloaded; overload getApplicationDescription() and getParamterDescription() and getDefaultParameterDescription() instead.
Reimplemented from Core::Application.
Definition at line 23 of file Nn/check.cc.
virtual std::string TestApplication::getUsage () const inline virtual
Overload this method to describe the usage of the application and to give a (short) description of the application.
Default return string is "usage: " + getBaseName() + "[OPTION(S)]\n" Return the usage of the application.
Normally, that method does not have to be overloaded; overload getApplicationDescription() and getParamterDescription() and getDefaultParameterDescription() instead.
Reimplemented from Core::Application.
Definition at line 26 of file Audio/check.cc.
References Core::Application::setTitle().
std::string TestApplication::getUsage () const inline virtual
Overload this method to describe the usage of the application and to give a (short) description of the application.
Default return string is "usage: " + getBaseName() + "[OPTION(S)]\n" Return the usage of the application.
Normally, that method does not have to be overloaded; overload getApplicationDescription() and getParamterDescription() and getDefaultParameterDescription() instead.
Reimplemented from Core::Application.
Definition at line 26 of file Tensorflow/check.cc.
virtual std::string TestApplication::getUsage () const inline virtual
Overload this method to describe the usage of the application and to give a (short) description of the application.
Default return string is "usage: " + getBaseName() + "[OPTION(S)]\n" Return the usage of the application.
Normally, that method does not have to be overloaded; overload getApplicationDescription() and getParamterDescription() and getDefaultParameterDescription() instead.
Reimplemented from Core::Application.
Definition at line 27 of file Cart/check.cc.
References main(), and require.
std::string TestApplication::getUsage () const inline virtual
Overload this method to describe the usage of the application and to give a (short) description of the application.
Default return string is "usage: " + getBaseName() + "[OPTION(S)]\n" Return the usage of the application.
Normally, that method does not have to be overloaded; overload getApplicationDescription() and getParamterDescription() and getDefaultParameterDescription() instead.
Reimplemented from Core::Application.
Definition at line 28 of file Speech/check.cc.
std::string TestApplication::getUsage () const inline virtual
Overload this method to describe the usage of the application and to give a (short) description of the application.
Default return string is "usage: " + getBaseName() + "[OPTION(S)]\n" Return the usage of the application.
Normally, that method does not have to be overloaded; overload getApplicationDescription() and getParamterDescription() and getDefaultParameterDescription() instead.
Reimplemented from Core::Application.
Definition at line 28 of file Python/check.cc.
virtual std::string TestApplication::getUsage () const inline virtual
Overload this method to describe the usage of the application and to give a (short) description of the application.
Default return string is "usage: " + getBaseName() + "[OPTION(S)]\n" Return the usage of the application.
Normally, that method does not have to be overloaded; overload getApplicationDescription() and getParamterDescription() and getDefaultParameterDescription() instead.
Reimplemented from Core::Application.
Definition at line 29 of file Bliss/check.cc.
References Core::Application::setTitle().
virtual std::string TestApplication::getUsage () const inline virtual
Overload this method to describe the usage of the application and to give a (short) description of the application.
Default return string is "usage: " + getBaseName() + "[OPTION(S)]\n" Return the usage of the application.
Normally, that method does not have to be overloaded; overload getApplicationDescription() and getParamterDescription() and getDefaultParameterDescription() instead.
Reimplemented from Core::Application.
Definition at line 30 of file Mm/check.cc.
References main().
virtual std::string TestApplication::getUsage () const inline virtual
Overload this method to describe the usage of the application and to give a (short) description of the application.
Default return string is "usage: " + getBaseName() + "[OPTION(S)]\n" Return the usage of the application.
Normally, that method does not have to be overloaded; overload getApplicationDescription() and getParamterDescription() and getDefaultParameterDescription() instead.
Reimplemented from Core::Application.
Definition at line 32 of file Am/check.cc.
References main().
std::string TestApplication::getUsage () const inline virtual
Overload this method to describe the usage of the application and to give a (short) description of the application.
Default return string is "usage: " + getBaseName() + "[OPTION(S)]\n" Return the usage of the application.
Normally, that method does not have to be overloaded; overload getApplicationDescription() and getParamterDescription() and getDefaultParameterDescription() instead.
Reimplemented from Core::Application.
Definition at line 35 of file Lattice/check.cc.
std::string TestApplication::getUsage () const inline virtual
Overload this method to describe the usage of the application and to give a (short) description of the application.
Default return string is "usage: " + getBaseName() + "[OPTION(S)]\n" Return the usage of the application.
Normally, that method does not have to be overloaded; overload getApplicationDescription() and getParamterDescription() and getDefaultParameterDescription() instead.
Reimplemented from Core::Application.
Definition at line 37 of file Search/Wfst/check.cc.
std::string TestApplication::getUsage () const inline virtual
Overload this method to describe the usage of the application and to give a (short) description of the application.
Default return string is "usage: " + getBaseName() + "[OPTION(S)]\n" Return the usage of the application.
Normally, that method does not have to be overloaded; overload getApplicationDescription() and getParamterDescription() and getDefaultParameterDescription() instead.
Reimplemented from Core::Application.
Definition at line 39 of file Search/check.cc.
std::string TestApplication::getUsage () const inline virtual
Overload this method to describe the usage of the application and to give a (short) description of the application.
Default return string is "usage: " + getBaseName() + "[OPTION(S)]\n" Return the usage of the application.
Normally, that method does not have to be overloaded; overload getApplicationDescription() and getParamterDescription() and getDefaultParameterDescription() instead.
Reimplemented from Core::Application.
Definition at line 42 of file check_ctrans.cc.
References OpenFst::convertLabelToFsa(), Core::Component::error(), Core::form(), Bliss::Pronunciation::format(), Bliss::PhonemeInventory::phoneme(), Bliss::Pronunciation::phonemes(), Bliss::Symbol::str(), Am::AllophoneAlphabet::symbol(), Bliss::Token::symbol(), and verify.
virtual std::string TestApplication::getUsage () const inline virtual
Overload this method to describe the usage of the application and to give a (short) description of the application.
Default return string is "usage: " + getBaseName() + "[OPTION(S)]\n" Return the usage of the application.
Normally, that method does not have to be overloaded; overload getApplicationDescription() and getParamterDescription() and getDefaultParameterDescription() instead.
Reimplemented from Core::Application.
Definition at line 49 of file Lm/check.cc.
References Core::Application::setTitle().
std::string TestApplication::getUsage () const inline virtual
Overload this method to describe the usage of the application and to give a (short) description of the application.
Default return string is "usage: " + getBaseName() + "[OPTION(S)]\n" Return the usage of the application.
Normally, that method does not have to be overloaded; overload getApplicationDescription() and getParamterDescription() and getDefaultParameterDescription() instead.
Reimplemented from Core::Application.
Definition at line 98 of file Core/check.cc.
virtual std::string TestApplication::getUsage () const inline virtual
Overload this method to describe the usage of the application and to give a (short) description of the application.
Default return string is "usage: " + getBaseName() + "[OPTION(S)]\n" Return the usage of the application.
Normally, that method does not have to be overloaded; overload getApplicationDescription() and getParamterDescription() and getDefaultParameterDescription() instead.
Reimplemented from Core::Application.
Definition at line 106 of file check-xml.cc.
int TestApplication::main (const std::vector< std::string > & arguments) inline virtual
Main entry point for an application.
Implements Core::Application.
Definition at line 25 of file Signal/check.cc.
int TestApplication::main (const std::vector< std::string > & arguments) inline virtual
Main entry point for an application.
Implements Core::Application.
Definition at line 27 of file Nn/check.cc.
int TestApplication::main (const std::vector< std::string > & arguments) inline virtual
Main entry point for an application.
Implements Core::Application.
Definition at line 27 of file Flow/check.cc.
int TestApplication::main (const std::vector< std::string > & arguments) inline virtual
Main entry point for an application.
Implements Core::Application.
Definition at line 27 of file OpenFst/check.cc.
int TestApplication::main (const std::vector< std::string > & arguments) virtual
Main entry point for an application.
Implements Core::Application.
int TestApplication::main (const std::vector< std::string > & arguments) inline virtual
Main entry point for an application.
Implements Core::Application.
Definition at line 30 of file Tensorflow/check.cc.
References require.
int TestApplication::main (const std::vector< std::string > & arguments) inline virtual
Main entry point for an application.
Implements Core::Application.
Definition at line 31 of file Math/check.cc.
References Core::Component::log().
int TestApplication::main (const std::vector< string > & arguments) inline virtual
Main entry point for an application.
Implements Core::Application.
Definition at line 31 of file Math/Nr/check.cc.
int TestApplication::main (const std::vector< std::string > & arguments) inline virtual
Main entry point for an application.
Implements Core::Application.
Definition at line 31 of file Math/Lapack/check.cc.
int TestApplication::main (const std::vector< std::string > & arguments) inline virtual
Main entry point for an application.
Implements Core::Application.
Definition at line 32 of file Python/check.cc.
int TestApplication::main (const std::vector< std::string > & arguments) inline virtual
Main entry point for an application.
Implements Core::Application.
Definition at line 32 of file Speech/check.cc.
int TestApplication::main (const std::vector< std::string > & arguments) virtual
Main entry point for an application.
Implements Core::Application.
int TestApplication::main (const std::vector< std::string > & arguments) virtual
Main entry point for an application.
Implements Core::Application.
Definition at line 38 of file Am/check.cc.
References Bliss::Lexicon::create(), Core::Component::log(), and Core::ref().
Referenced by getUsage().
int TestApplication::main (const std::vector< std::string > & arguments) inline virtual
Main entry point for an application.
Implements Core::Application.
Definition at line 38 of file Audio/check.cc.
References Flow::Network::buildFromFile().
int TestApplication::main (const std::vector< std::string > & arguments) inline virtual
Main entry point for an application.
Implements Core::Application.
Definition at line 38 of file Bliss/check.cc.
References Bliss::Lexicon::create().
int TestApplication::main (const std::vector< std::string > & arguments) inline virtual
Main entry point for an application.
Implements Core::Application.
Definition at line 39 of file Lattice/check.cc.
References Lattice::WordLattice::acousticFsa, Mc::Component::load(), Core::log(), and verify.
int TestApplication::main (const std::vector< std::string > & arguments) inline virtual
Main entry point for an application.
Implements Core::Application.
Definition at line 41 of file Search/Wfst/check.cc.
References Core::Component::log().
int TestApplication::main (const std::vector< std::string > & arguments) inline virtual
Main entry point for an application.
Implements Core::Application.
Definition at line 43 of file Search/check.cc.
virtual int TestApplication::main (const std::vector< std::string > & arguments) inline virtual
Main entry point for an application.
Implements Core::Application.
Definition at line 69 of file Lm/check.cc.
References Bliss::Lexicon::create(), Core::Component::criticalError(), Core::Ref< T >::get(), and Core::Component::log().
int TestApplication::main (const std::vector< std::string > & arguments) inline virtual
Main entry point for an application.
Implements Core::Application.
Definition at line 102 of file Core/check.cc.
int TestApplication::main (const std::vector< std::string > & arguments) inline virtual
Main entry point for an application.
Implements Core::Application.
Definition at line 110 of file check-xml.cc.
References Core::XmlParser::parseFile().
int TestApplication::main (const std::vector< std::string > & arguments) inline virtual
Main entry point for an application.
Implements Core::Application.
Definition at line 291 of file check_ctrans.cc.
References Bliss::Lexicon::create(), Bliss::Token::id(), Core::Component::log(), Bliss::PhonemeInventory::phoneme(), and verify.
The documentation for this class was generated from the following files:
Am/check.cc
check_ctrans.cc
check-xml.cc