Sprint: Cart::Training Class Reference
Cart::Training Class Reference
Classes
struct Node
A node together with associated examples.
struct QuestionStatistic
Collection of some information about the usage of a specific question in the decision tree.
struct Split
(Possible) split of a given node.
class SplitHypothesesManager
Manages split hypotheses, supports randomization.
struct SplitHypothesis
Split hypothesis; used for finding the best split for a node.
struct SplitPtrGreaterThan
Public Member Functions
Training (const Core::Configuration &config, const Scorer &scorer, const TrainingPlan &plan, const ExampleList &examples, DecisionTree *tree)
ClusterList * train ()
void write (std::ostream &os) const
void writeXml (Core::XmlWriter &xml) const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Attributes
static const Core::ParameterBool paramDoParallel
Private Types
typedef DecisionTree::QuestionId QuestionId
typedef std::vector< QuestionId > QuestionIdList
typedef DecisionTree::ClassId ClassId
typedef DecisionTreeTrainer::Information Information
typedef DecisionTreeTrainer::TrainingPlan TrainingPlan
typedef std::vector< QuestionStatistic > QuestionStatisticList
typedef std::deque< Node * > NodePtrQueue
typedef std::vector< SplitHypothesis * > SplitHypothesisPtrList
typedef Core::PriorityQueue< Split *, SplitPtrGreaterThan > SplitPtrQueue
typedef std::vector< Cluster * > ClusterPtrList
Private Member Functions
Node * init ()
void writeXml (Core::XmlWriter &xml, const Split &split)
Split * splitNode (Node *node, QuestionIdList *questionIds, bool strict=false)
void insertSplit (Split *split)
insert split into tree
void suggestSplit (Node *node, QuestionIdList *questionIds)
queues the best split of the node
void commitSplit (Split *split)
commits a split, suggests new splits for left and right child
Node * commitHalfSplit (Split *split)
commits a split, suggests new split for the right child (i.e.
void rollbackSplit (Split *split)
rollback split
void split ()
action: split find tuple of node and question causing best split, split using best split, repeat procedure until no splits left or max.
void halfSplit (bool finalizeLeftNodes=false)
action: partition(->finalizeLeftNodes=false) or cluster(->finalizeLeftNodes=true) same as split, but put only right node back into queue for further splitting; if finalizeLeftNodes=false, then put left nodes back into queue for the next step, otherwise each left node will become a leaf
void start (Node *root)
DecisionTree::Node * commitNode (Node *node)
ClusterList * finish (Node *root)
Private Attributes
bool parallel_
const Scorer & scorer_
const TrainingPlan & plan_
const ExampleList & examples_
DecisionTree * tree_
Score score_
u32 nObs_
u32 nSplit_
u32 nNumber_
u32 nLeaf_
u32 nCluster_
Score gain_
const TrainingPlan::Step * step_
SplitHypothesesManager splitHyps_
SplitPtrQueue splits_
NodePtrQueue nodes_
QuestionRefList questionRefs_
QuestionStatisticList questionStats_
QuestionIdList questionIdMap_
ClusterPtrList clusters_
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Definition at line 122 of file Cart/DecisionTreeTrainer.cc.
Member Function Documentation
Node* Cart::Training::commitHalfSplit (Split * split) inline private
commits a split, suggests new split for the right child (i.e.
question answer=NO) and returns the left child (i.e. question answer=YES)
Definition at line 587 of file Cart/DecisionTreeTrainer.cc.
void Cart::Training::commitSplit (Split * split) inline private
commits a split, suggests new splits for left and right child
Definition at line 572 of file Cart/DecisionTreeTrainer.cc.
void Cart::Training::halfSplit (bool finalizeLeftNodes = false) inline private
action: partition(->finalizeLeftNodes=false) or cluster(->finalizeLeftNodes=true) same as split, but put only right node back into queue for further splitting; if finalizeLeftNodes=false, then put left nodes back into queue for the next step, otherwise each left node will become a leaf
Definition at line 649 of file Cart/DecisionTreeTrainer.cc.
References Core::Component::criticalError(), Core::Component::error(), Core::XmlWriter::generateFormattingHints(), Core::Ref< T >::get(), Core::PriorityQueueBase< T_Heap, T_PriorityFunction >::pop(), require, Core::PriorityQueueBase< T_Heap, T_PriorityFunction >::top(), verify, Core::Component::warning(), and Cart::ID3::write().
void Cart::Training::insertSplit (Split * split) inline private
insert split into tree
Definition at line 530 of file Cart/DecisionTreeTrainer.cc.
void Cart::Training::rollbackSplit (Split * split) inline private
rollback split
Definition at line 600 of file Cart/DecisionTreeTrainer.cc.
void Cart::Training::split () inline private
action: split find tuple of node and question causing best split, split using best split, repeat procedure until no splits left or max.
leaf number is reached
Definition at line 623 of file Cart/DecisionTreeTrainer.cc.
References Core::PriorityQueueBase< T_Heap, T_PriorityFunction >::pop(), and Core::PriorityQueueBase< T_Heap, T_PriorityFunction >::top().
void Cart::Training::suggestSplit (Node * node, QuestionIdList * questionIds) inline private
queues the best split of the node
Definition at line 557 of file Cart/DecisionTreeTrainer.cc.
References Core::PriorityQueueBase< T_Heap, T_PriorityFunction >::insert().
The documentation for this class was generated from the following file:
Cart/DecisionTreeTrainer.cc