Sprint: Search::MinimumBayesRiskNBestListNaiveSearch Class Reference
Search::MinimumBayesRiskNBestListNaiveSearch Class Reference
Implementation of the naive approach for minimum Bayes risk using an nbestlist for both the evaluation space as well as for the summation space.
#include <MinimumBayesRiskNBestListSearch.hh>
Public Member Functions
MinimumBayesRiskNBestListNaiveSearch (const Core::Configuration &)
Standard constructor.
virtual ~MinimumBayesRiskNBestListNaiveSearch ()
Virtual destructor.
virtual void performSearch (Fsa::ConstAutomatonRef nBestList)
Performs the search for the string with minimal Bayes risk on the specified nbestlist.
Fsa::Weight getMinimumBayesRisk () const
Public Member Functions inherited from Search::MinimumBayesRiskNBestListSearch
MinimumBayesRiskNBestListSearch (const Core::Configuration &)
Initialization of probs to zero, sentences to empty sentences.
virtual ~MinimumBayesRiskNBestListSearch ()
Virtual destructor.
Public Member Functions inherited from Search::MinimumBayesRiskSearch
MinimumBayesRiskSearch (const Core::Configuration &)
The only arguments a minimum Bayes risk search takes are a configuration.
virtual ~MinimumBayesRiskSearch ()
Virtual desructor without special purpose.
virtual Fsa::ConstAutomatonRef getBestAutomaton () const
Getter for bestAutomaton .
u32 getEvaluationSpaceSize () const
Getter for evaluationSpace .
u32 getSummationSpaceSize () const
Getter for summationSpaceSize .
u32 getNumberEvaluations () const
Getter for numberEvaluations .
u32 getNumberComputations () const
Getter for numberComputations .
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Private Member Functions
bool oneHalfCriterion () const
bool distanceOneCriterion () const
void setDistanceOneCriterion (const Fsa::Weight &distanceOne, const Fsa::Weight &maxDistanceOne)
Private Attributes
bool distanceOneCriterion_
Flag whether the distance-one criterion is fulfilled.
Static Private Attributes
static const Core::ParameterInt paramNumberHypothesesSummation
The number of hypotheses used for summation.
static const Core::ParameterInt paramNumberHypothesesEvaluation
The number of hypotheses used for minimization.
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Search::MinimumBayesRiskNBestListSearch
std::vector< Fsa::LabelId > mapSentence_
The string having maximum a-posteriori probability.
Fsa::Weight mapProbability_
The negative logarithm of the probability of the MAP string.
Fsa::Weight mapRisk_
The negative logarithm of the Bayes risk of the MAP string.
std::vector< Fsa::LabelId > mbrSentence_
The string having minimal Bayes risk.
Fsa::Weight mbrProbability_
The negative logarithm of the probability of the sentence minimizing the Bayes risk.
Fsa::Weight mbrRisk_
The negative logarithm of the minimal Bayes risk.
std::vector< StringHypothesis > * summationSpace_
to be deleted in dtor.
std::vector< StringHypothesis > * evaluationSpace_
Protected Attributes inherited from Search::MinimumBayesRiskSearch
Fsa::ConstAutomatonRef fsa_
The automaton to be searched.
Fsa::ConstAutomatonRef bestAutomaton_
The optimal string represented as a linear Fsa.
u32 evaluationSpaceSize_
The number of hypotheses which can be evaluated during the search.
u32 summationSpaceSize_
The number of hypotheses which are used for the summation in the Bayes risk formula.
u32 numberEvaluations_
The number of hypotheses that were actually used for minimization.
u32 numberComputations_
The number of relevant computations depending on the kind of search.
Core::XmlChannel statisticsChannel_
Protected Attributes inherited from Core::Configurable
Configuration config
Static Protected Attributes inherited from Search::MinimumBayesRiskNBestListSearch
static const Core::ParameterInt paramNumberHypotheses
The overall number of hypotheses.
Detailed Description
Implementation of the naive approach for minimum Bayes risk using an nbestlist for both the evaluation space as well as for the summation space.
The search can be performed on two different nbestlists depending on how much hypotheses shall be used for minimization or summation. In order to stay conform to the MinimumBayesRiskSearch interface, the search itself will be given a single nbestlist from which the two lists for evaluation space and summation space will be extracted up to a configurable number of string hypotheses. In addition there exist two criteria which can abbreviate the search process. Their application can be configured. If fulfilled, this information will be logged to the information channel. It should be noted that the computation of the two criteria do not afford additional computation time but come along with the computation process.
Definition at line 91 of file MinimumBayesRiskNBestListSearch.hh.
Constructor & Destructor Documentation
Search::MinimumBayesRiskNBestListNaiveSearch::MinimumBayesRiskNBestListNaiveSearch (const Core::Configuration & config)
Standard constructor.
Parameters
config the configuration.
Definition at line 46 of file MinimumBayesRiskNBestListSearch.cc.
Search::MinimumBayesRiskNBestListNaiveSearch::~MinimumBayesRiskNBestListNaiveSearch () virtual
Virtual destructor.
Definition at line 50 of file MinimumBayesRiskNBestListSearch.cc.
References distanceOneCriterion_, and Search::MinimumBayesRiskNBestListSearch::mapProbability_.
Member Function Documentation
Fsa::Weight Search::MinimumBayesRiskNBestListNaiveSearch::getMinimumBayesRisk () const
Returns
the actual value of the Bayes risk.
void Search::MinimumBayesRiskNBestListNaiveSearch::performSearch (Fsa::ConstAutomatonRef nBestList) virtual
Performs the search for the string with minimal Bayes risk on the specified nbestlist.
Parameters
nBestList the nbestlist on which the search will be performed.
If one of the criteria is fulfilled, then the searchcomputation does not have to be carried out, but the MAP sentence is guaranteed to minimize the Bayes risk w.r.t. Levenshtein loss. Only if neither of both criteria is fulfilled, the search will be carried out.
Implements Search::MinimumBayesRiskNBestListSearch.
Definition at line 65 of file MinimumBayesRiskNBestListSearch.cc.
References Search::MinimumBayesRiskSearch::bestAutomaton_, Search::MinimumBayesRiskSearch::evaluationSpaceSize_, Core::ProgressIndicator::finish(), Search::MinimumBayesRiskNBestListSearch::mapProbability_, Search::MinimumBayesRiskNBestListSearch::mapRisk_, Search::MinimumBayesRiskNBestListSearch::mapSentence_, Search::MinimumBayesRiskNBestListSearch::mbrProbability_, Search::MinimumBayesRiskNBestListSearch::mbrRisk_, Search::MinimumBayesRiskNBestListSearch::mbrSentence_, Core::ProgressIndicator::notify(), paramNumberHypothesesEvaluation, paramNumberHypothesesSummation, Search::MinimumBayesRiskSearch::performSearch(), Search::posteriorRiskNBestList(), require, Core::ProgressIndicator::start(), and Search::MinimumBayesRiskSearch::summationSpaceSize_.
Member Data Documentation
bool Search::MinimumBayesRiskNBestListNaiveSearch::distanceOneCriterion_ private
Flag whether the distance-one criterion is fulfilled.
Definition at line 94 of file MinimumBayesRiskNBestListSearch.hh.
Referenced by ~MinimumBayesRiskNBestListNaiveSearch().
const Core::ParameterInt Search::MinimumBayesRiskNBestListNaiveSearch::paramNumberHypothesesEvaluation static private
The number of hypotheses used for minimization.
Definition at line 100 of file MinimumBayesRiskNBestListSearch.hh.
Referenced by performSearch(), and Search::MinimumBayesRiskNBestListSearch::~MinimumBayesRiskNBestListSearch().
const Core::ParameterInt Search::MinimumBayesRiskNBestListNaiveSearch::paramNumberHypothesesSummation static private
The number of hypotheses used for summation.
Definition at line 97 of file MinimumBayesRiskNBestListSearch.hh.
Referenced by performSearch(), and Search::MinimumBayesRiskNBestListSearch::~MinimumBayesRiskNBestListSearch().
The documentation for this class was generated from the following files:
MinimumBayesRiskNBestListSearch.hh
MinimumBayesRiskNBestListSearch.cc