Sprint: Ftl::State< _Arc, _ArcContainer > Class Template Reference
Ftl::State< _Arc, _ArcContainer > Class Template Reference
The basic state class.
#include <tAutomaton.hh>
Public Types
typedef Core::Ref< Self > Ref
typedef Core::Ref< const Self > ConstRef
typedef _Arc Arc
typedef _Arc::Weight Weight
typedef ArcContainer::iterator iterator
typedef ArcContainer::const_iterator const_iterator
typedef ArcContainer::reverse_iterator reverse_iterator
typedef ArcContainer::const_reverse_iterator const_reverse_iterator
Public Member Functions
State (Fsa::StateId id=0, Fsa::StateTag tags=Fsa::StateTagNone)
State (Fsa::StateId id, Fsa::StateTag tags, const Weight &weight)
State (const Self &o)
template<template< typename > class _OtherArcContainer>
State (const State< _Arc, _OtherArcContainer > &o)
template<template< typename > class _OtherArcContainer>
operator State< _Arc, _OtherArcContainer > ()
void clear ()
Weight weight () const
void setWeight (const Weight &weight)
void setId (Fsa::StateId id)
Fsa::StateId id () const
void addTags (Fsa::StateTag tags)
void setTags (Fsa::StateTag tags)
bool hasTags (Fsa::StateTag tags) const
Fsa::StateTag tags () const
bool isFinal () const
void setFinal (const Weight &weight)
void unsetFinal ()
const Arc * operator[] (unsigned i) const
const Arc * getArc (unsigned i) const
Arc * newArc ()
Warning: the returned pointer can become invalid after a new call of newArc()
Arc * newArc (Fsa::StateId target, Weight weight, Fsa::LabelId input)
Arc * newArc (Fsa::StateId target, Weight weight, Fsa::LabelId input, Fsa::LabelId output)
bool hasArcs () const
u32 nArcs () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
void truncate (iterator i)
void resize (size_t s)
void minimize ()
iterator insert (iterator pos, const Arc &a)
template<class Predicate >
void remove (Predicate pred)
template<class T , class StrictWeakOrdering >
iterator lower_bound (const T &value, StrictWeakOrdering comp)
template<class T , class StrictWeakOrdering >
const_iterator lower_bound (const T &value, StrictWeakOrdering comp) const
template<class StrictWeakOrdering >
void sort (StrictWeakOrdering comp)
size_t getMemoryUsed () const
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Public Attributes
Weight weight_
Protected Attributes
ArcContainer arcs_
Private Types
typedef State< _Arc, _ArcContainer > Self
typedef _ArcContainer< _Arc > ArcContainer
Private Attributes
Fsa::StateId idAndTags_
Detailed Description
template<class _Arc, template< class T > class _ArcContainer = VectorArcContainer>
class Ftl::State< _Arc, _ArcContainer >
The basic state class.
States are reference counted as you can't know when to delete them.
Definition at line 198 of file tAutomaton.hh.
Member Function Documentation
template<class _Arc , template< class T > class _ArcContainer> _Arc * Ftl::State< _Arc, _ArcContainer >::newArc ()
Warning: the returned pointer can become invalid after a new call of newArc()
Definition at line 20 of file tAutomaton.cc.
Referenced by Flf::cleanUp(), Flf::FittingLattice::Boundaries::get(), Flf::NBestBuilder::initialize(), Flf::sausageLattice2cn(), Flf::StringConverterNode::sendLattice(), and Flf::ExpandTransitsNode::sync().
The documentation for this class was generated from the following files:
tAutomaton.hh
tAutomaton.cc