Sprint: WordConditionedTreeSearch::SearchSpace Class Reference
WordConditionedTreeSearch::SearchSpace Class Reference
search space for word conditioned tree search
Classes
struct StateHypothesis
struct TreeInstance
tree instance (a.k.a.
struct TreeInstance
tree instance (a.k.a.
struct TreeInstance
tree instance (a.k.a.
struct WordEndHypothesis
struct WordEndHypothesis
struct WordEndHypothesis
Public Types
typedef std::vector< StateHypothesis > StateHypothesesList
Public Member Functions
SearchSpace (const StateTree *, const LanguageModelLookahead *, u32 nStateHistogramBins, u32 nWordEndHistogramBins)
void setPruningThreshold (Score threshold)
void setAnticipatedLookaheadPruning (bool prune)
void setTreeDeletionLatency (u32 l)
void clear ()
reset the search space
void expand ()
expand all state hypotheses in all active trees.
void addAcousticScores (const Mm::FeatureScorer::Scorer &)
add acoustic scores to all active state hypotheses.
void activateLmLookahead (s32 laziness)
void determinePruningCriterion ()
calculate s.prospect (using LM lookahead) and find best state hypothesis in all active trees.
StateHypothesesList::const_iterator bestStateHypothesis () const
best state hypothesis w.r.t.
Score minimumStateScore () const
Score quantileStateScore (Score min, Score max, u32 nHyp) const
score s where the nHyps active state hypotheses have a score s' <= s
void pruneStates (Score threshold)
remove all state hypotheses s with s.prospect > threshold.
void rescale (Score)
adjust scores such that the smallest score is 0.
void findWordEnds (Core::Ref< const Lm::ScaledLanguageModel >, Score wpScale)
find word ends in stateHypotheses and create word end hypotheses
Score minimumWordEndScore () const
score of the best word end hypothesis in wordEndHypotheses
Score quantileWordEndScore (Score min, Score max, u32 nHyp) const
score s where the nHyps active word end hypotheses have a score s' <= s
void pruneWordEnds (Score lmPruningThreshold)
remove word end hypotheses with a score > threshold
void recombineWordEnds (bool shallCreateLattice=false)
find equal word end hypotheses (same history and same transit) and keep only the best one
void createTraces (TimeframeIndex time)
update the bookkeeping entrys for all word end hypotheses
void pruneSilenceSiblingTraces (Core::Ref< Trace >, const Bliss::Lemma *silence)
Remove sibling traces that are silence.
void optimizeSilenceInWordLattice (const Bliss::Lemma *silence)
This is the simple lattice optimization selected by optimize-lattice=simple.
void hypothesizeEpsilonPronunciations (Core::Ref< const Lm::ScaledLanguageModel >, Score wpScale, Score threshold)
create word end hypotheses for words ending at the coarticulated root state of the state tree (with an empty phoneme sequence).
void addStartupWordEndHypothesis (const Lm::History &, TimeframeIndex)
create initial (empty) word end hypothesis.
void dumpWordEnds (std::ostream &, Core::Ref< const Bliss::PhonemeInventory >) const
void startNewTrees ()
create or update tree instances for word ends in wordEndHypotheses
Ref< Trace > getSentenceEnd (Core::Ref< const Lm::ScaledLanguageModel >, TimeframeIndex, bool shallCreateLattice)
Find the best sentence end hypothesis.
Ref< Trace > getSentenceEndFallBack (Core::Ref< const Lm::ScaledLanguageModel >, TimeframeIndex, bool shallCreateLattice)
Fall back strategy for finding the best sentence hypothesis when there is no active word end hypothesis.
Ref< Trace > getLastUnambiguousTrace () const
void killTrace (Ref< Trace >)
u32 nStateHypotheses () const
u32 nWordEndHypotheses () const
u32 nActiveTrees () const
Private Types
typedef s32 StateHypothesisIndex
typedef s32 TraceId
typedef std::vector< TreeInstance * > TreeInstanceList
typedef std::vector< WordEndHypothesis > WordEndHypothesisList
typedef std::unordered_set< WordEndHypothesisList::iterator, WordEndHypothesis::Hash, WordEndHypothesis::Equality > WordEndHypothesisRecombinationMap
Private Member Functions
TreeInstance * activateTree (Lm::History)
create a new tree
void activateOrUpdateTree (const Ref< Trace > &, Lm::History, StateTree::StateId, Score)
create a new tree or update an existing tree with the same history.
void deactivateTree (TreeInstance *)
delete a currently active tree
bool mayDeactivateTree (TreeInstance *)
Check whether tree should be deactivated, and if so do it.
void activateOrUpdateStateHypothesis (StateTree::StateId, TraceId, Score)
create or update score and trace of a state hypothesis.
void expandState (const StateHypothesis &)
expand state sh using forward, loop, and skip transitions.
void expandTree (TreeInstance &)
expand all state hypotheses in tree at
Private Attributes
const StateTree * tree_
const LanguageModelLookahead * lmLookahead_
f64 globalScoreOffset_
StateHypothesesList stateHypotheses
StateHypothesesList newStateHypotheses
StateHypothesesList::const_iterator bestStateHypothesis_
TreeInstanceList activeTrees
std::unordered_map< Lm::History, TreeInstance *, Lm::History::Hash > activeTreeMap
u32 treeDeletionLatency_
std::vector< StateHypothesisIndex > stateHypothesisForTreeState
StateHypothesisIndex currentTreeFirstNewStateHypothesis
WordEndHypothesisList wordEndHypotheses
WordEndHypothesisRecombinationMap wordEndHypothesisMap
Histogram stateHistogram_
Histogram wordEndHistogram_
LanguageModelLookahead::ContextLookaheadReference currentLookahead_
Score currentStateTreshold_
Score currentBestScore_
Score pruningThreshold_
bool anticipatedLookaheadPruning_
Static Private Attributes
static const TraceId invalidTraceId = -1
Detailed Description
search space for word conditioned tree search
Definition at line 114 of file WordConditionedTreeSearch.cc.
Member Function Documentation
void WordConditionedTreeSearch::SearchSpace::activateOrUpdateStateHypothesis (StateTree::StateId state, TraceId trace, Score score) inline private
create or update score and trace of a state hypothesis.
a state hypothesis is updated if a state hypothesis for the same exists with a higher score
Definition at line 431 of file WordConditionedTreeSearch.cc.
void WordConditionedTreeSearch::SearchSpace::activateOrUpdateTree (const Ref< Trace > & trace, Lm::History history, StateTree::StateId entry, Score score) private
create a new tree or update an existing tree with the same history.
a entry state hypothesis is created with the given trace, state, and score
Definition at line 377 of file WordConditionedTreeSearch.cc.
References verify.
WordConditionedTreeSearch::SearchSpace::TreeInstance * WordConditionedTreeSearch::SearchSpace::activateTree (Lm::History history) private
create a new tree
Definition at line 363 of file WordConditionedTreeSearch.cc.
References require.
void WordConditionedTreeSearch::SearchSpace::addAcousticScores (const Mm::FeatureScorer::Scorer & featureScorer)
add acoustic scores to all active state hypotheses.
the best state hypothesis (w.r.t s.prospect) is written in bestStateHypothesis_. the aoustic score is added to both s.score and s.prospect
Definition at line 529 of file WordConditionedTreeSearch.cc.
References require.
void WordConditionedTreeSearch::SearchSpace::addStartupWordEndHypothesis (const Lm::History & h, TimeframeIndex time)
create initial (empty) word end hypothesis.
used only at the begin of a segment (t=0, history = <eps>)
Definition at line 858 of file WordConditionedTreeSearch.cc.
WordConditionedTreeSearch::SearchSpace::StateHypothesesList::const_iterator WordConditionedTreeSearch::SearchSpace::bestStateHypothesis () const
best state hypothesis w.r.t.
state prospect (score + lm lookahed). if bestStateHypothesis_ is set, this will be used, otherwise the searched by iterating over all state hypotheses
Definition at line 597 of file WordConditionedTreeSearch.cc.
void WordConditionedTreeSearch::SearchSpace::clear ()
reset the search space
Definition at line 346 of file WordConditionedTreeSearch.cc.
void WordConditionedTreeSearch::SearchSpace::createTraces (TimeframeIndex time)
update the bookkeeping entrys for all word end hypotheses
Definition at line 753 of file WordConditionedTreeSearch.cc.
References Core::ref().
void WordConditionedTreeSearch::SearchSpace::deactivateTree (TreeInstance * t) private
delete a currently active tree
Definition at line 395 of file WordConditionedTreeSearch.cc.
References require, and verify.
void WordConditionedTreeSearch::SearchSpace::determinePruningCriterion ()
calculate s.prospect (using LM lookahead) and find best state hypothesis in all active trees.
result: bestStateHypothesis_
Definition at line 562 of file WordConditionedTreeSearch.cc.
void WordConditionedTreeSearch::SearchSpace::expand ()
expand all state hypotheses in all active trees.
bestStateHypothesis_ is invalidated
Definition at line 514 of file WordConditionedTreeSearch.cc.
void WordConditionedTreeSearch::SearchSpace::expandState (const StateHypothesis & sh) inline private
expand state sh using forward, loop, and skip transitions.
new state hypotheses are stored in newStateHypotheses
Definition at line 468 of file WordConditionedTreeSearch.cc.
void WordConditionedTreeSearch::SearchSpace::expandTree (TreeInstance & at) private
expand all state hypotheses in tree at
Definition at line 496 of file WordConditionedTreeSearch.cc.
void WordConditionedTreeSearch::SearchSpace::findWordEnds (Core::Ref< const Lm::ScaledLanguageModel > lm, Score wpScale)
find word ends in stateHypotheses and create word end hypotheses
Definition at line 695 of file WordConditionedTreeSearch.cc.
References WordConditionedTreeSearch::SearchSpace::WordEndHypothesis::addLmScore(), and require.
Ref< WordConditionedTreeSearch::Trace > WordConditionedTreeSearch::SearchSpace::getSentenceEnd (Core::Ref< const Lm::ScaledLanguageModel > lm, TimeframeIndex time, bool shallCreateLattice)
Find the best sentence end hypothesis.
Returns a back-trace reference which can be used to determine the word sequence. The returned reference immediately points a trace-back item which includes the language model sentence end score. Its predecessor indicates the final word of the sentence. In case no word-end hypothesis is active, a null reference is returned. If creation of the word lattice is requested, the returned trace has siblings corresponding to sub-optimal sentence ends.
Definition at line 895 of file WordConditionedTreeSearch.cc.
References Lm::LanguageModel::sentenceEndScore().
Ref< WordConditionedTreeSearch::Trace > WordConditionedTreeSearch::SearchSpace::getSentenceEndFallBack (Core::Ref< const Lm::ScaledLanguageModel > lm, TimeframeIndex time, bool shallCreateLattice)
Fall back strategy for finding the best sentence hypothesis when there is no active word end hypothesis.
Typically used when getBestSentenceEnd() fails. This problem can occur when the recording is truncated in the middle of a word and pruning is tight. The strategy is to select the best state from each active tree and consider it as a "word end" without a pronunciation.
Definition at line 930 of file WordConditionedTreeSearch.cc.
References Core::Ref< T >::get(), Core::Ref< T >::reset(), Lm::LanguageModel::sentenceEndScore(), and verify.
void WordConditionedTreeSearch::SearchSpace::hypothesizeEpsilonPronunciations (Core::Ref< const Lm::ScaledLanguageModel > lm, Score wpScale, Score threshold)
create word end hypotheses for words ending at the coarticulated root state of the state tree (with an empty phoneme sequence).
this will be 0 new word end hypotheses with nearly all usual lexicons
Definition at line 766 of file WordConditionedTreeSearch.cc.
References WordConditionedTreeSearch::SearchSpace::WordEndHypothesis::addLmScore(), and Core::ref().
bool WordConditionedTreeSearch::SearchSpace::mayDeactivateTree (TreeInstance * at) inline private
Check whether tree should be deactivated, and if so do it.
check if tree instance at can be disabled, delete it if possible.
Returns
true iff tree has been deactivared
a state hypothesis can be disabled if it has no active state hypotheses and it is inactive for more then treeDeletetionLatency time steps
Definition at line 408 of file WordConditionedTreeSearch.cc.
References WordConditionedTreeSearch::SearchSpace::TreeInstance::inactive.
Score WordConditionedTreeSearch::SearchSpace::minimumWordEndScore () const
score of the best word end hypothesis in wordEndHypotheses
Definition at line 718 of file WordConditionedTreeSearch.cc.
void WordConditionedTreeSearch::SearchSpace::optimizeSilenceInWordLattice (const Bliss::Lemma * silence)
This is the simple lattice optimization selected by optimize-lattice=simple.
The effect is this: All partial sentence hypotheses ending with silence are suppressed from the lattice - except that the best scoring hypothesis is always preserved, even if it ends with silence.
Definition at line 849 of file WordConditionedTreeSearch.cc.
void WordConditionedTreeSearch::SearchSpace::pruneSilenceSiblingTraces (Core::Ref< Trace > trace, const Bliss::Lemma * silence)
Remove sibling traces that are silence.
Definition at line 833 of file WordConditionedTreeSearch.cc.
void WordConditionedTreeSearch::SearchSpace::pruneStates (Score threshold)
remove all state hypotheses s with s.prospect > threshold.
empty trees are removed. bestStateHypothesis_ is invalidated
Definition at line 627 of file WordConditionedTreeSearch.cc.
void WordConditionedTreeSearch::SearchSpace::pruneWordEnds (Score lmPruningThreshold)
remove word end hypotheses with a score > threshold
Definition at line 742 of file WordConditionedTreeSearch.cc.
Score WordConditionedTreeSearch::SearchSpace::quantileStateScore (Score min, Score max, u32 nHyp) const
score s where the nHyps active state hypotheses have a score s' <= s
Definition at line 612 of file WordConditionedTreeSearch.cc.
Score WordConditionedTreeSearch::SearchSpace::quantileWordEndScore (Score min, Score max, u32 nHyp) const
score s where the nHyps active word end hypotheses have a score s' <= s
Definition at line 730 of file WordConditionedTreeSearch.cc.
void WordConditionedTreeSearch::SearchSpace::recombineWordEnds (bool shallCreateLattice = false)
find equal word end hypotheses (same history and same transit) and keep only the best one
Definition at line 793 of file WordConditionedTreeSearch.cc.
References verify.
void WordConditionedTreeSearch::SearchSpace::rescale (Score offset)
adjust scores such that the smallest score is 0.
the offset is added to globalScoreOffset_
Definition at line 653 of file WordConditionedTreeSearch.cc.
References require.
void WordConditionedTreeSearch::SearchSpace::startNewTrees ()
create or update tree instances for word ends in wordEndHypotheses
Definition at line 878 of file WordConditionedTreeSearch.cc.
The documentation for this class was generated from the following file:
WordConditionedTreeSearch.cc