Sprint: Sparse::Vector< T > Class Template Reference
Sparse::Vector< T > Class Template Reference
Block sparse vector with integration into the Flow network.
#include <Vector.hh>
Public Types
typedef IteratorBase< typename InternalVector::const_iterator, const typename InternalVector::const_iterator::value_type::second_type > const_iterator
typedef IteratorBase< typename InternalVector::iterator, typename InternalVector::iterator::value_type::second_type > iterator
Public Types inherited from Sparse::SingleValueSparseVector< T >
typedef u32 index_type
typedef IteratorBase< typename InternalVector::iterator, typename InternalVector::iterator::value_type::second_type > iterator
typedef IteratorBase< typename InternalVector::const_iterator, const typename InternalVector::const_iterator::value_type::second_type > const_iterator
Public Member Functions
Vector ()
Creates a new sparse vector.
Vector (int size)
Creates a new sparse vector with given size.
Vector (int size, T contentToFill)
Creates a new sparse vector with given size and content.
Vector (const Vector< T > &v)
Copy constructor.
Vector (const Precursor &v)
Copy constructor from Precursor.
virtual ~Vector ()
Destroys the sparse vector.
virtual Data * clone () const
Returns a pointer of a vector clone.
virtual Core::XmlWriter & dump (Core::XmlWriter &o) const
Dumps the sparse vector to an XML stream.
virtual bool read (Core::BinaryInputStream &i)
Reads a sparse vector from a binary stream.
virtual bool write (Core::BinaryOutputStream &o) const
Writes a sparse vector to a binary stream.
Public Member Functions inherited from Flow::Timestamp
Timestamp (Time start=0, Time end=0)
void setStartTime (Time start)
Time getStartTime () const
Time startTime () const
void setEndTime (Time end)
Time getEndTime () const
Time endTime () const
void setTimestamp (const Timestamp &t)
void expandTimestamp (const Timestamp &t)
start_ = min(start_, t.start_) and end_ = max(end_, t.end_)
void invalidateTimestamp ()
bool isValidTimestamp ()
bool equalsToStartTime (Time t) const
bool equalStartTime (const Timestamp &t) const
bool equalsToEndTime (Time t) const
bool equalEndTime (const Timestamp &t) const
bool contains (Time t) const
bool contains (const Timestamp &t) const
bool overlap (const Timestamp &t) const
Public Member Functions inherited from Flow::Data
Data (const Data &data)
const Datatype * datatype () const
virtual bool operator== (const Data &other) const
Public Member Functions inherited from Core::ThreadSafeReferenceCounted
ThreadSafeReferenceCounted (const ThreadSafeReferenceCounted &)
ThreadSafeReferenceCounted & operator= (const ThreadSafeReferenceCounted &)
virtual ~ThreadSafeReferenceCounted ()
Constructor for static objects.
u32 refCount () const
Public Member Functions inherited from Sparse::SingleValueSparseVector< T >
SingleValueSparseVector (size_t size=0, TdefaultValue=0)
Creates a new sparse vector of given size.
SingleValueSparseVector (const SingleValueSparseVector< T > &sv)
bool operator== (const SingleValueSparseVector &sv)
bool operator!= (const SingleValueSparseVector &sv)
iterator begin ()
Returns a begin iterator.
const_iterator begin () const
Returns a begin const_iterator.
iterator end ()
Returns an "after end" iterator.
const_iterator end () const
Returns an "after end" const_iterator.
const T & operator[] (const const_iterator &i) const
complexity: constant
T & operator[] (const iterator &i)
complexity: constant
T & operator[] (const index_type index)
complexity: linear
const T & get (const index_type index) const
complexity: linear
void clear ()
sets all active elements to null the size of the vector is unchanged
void setDefault (TdefaultValue)
sets the value of non-active components
T getDefault ()
get the value of non-active components
void resize (size_t new_size)
sets the dimension of the vector
void resize (size_t new_size, TdefaultValue)
sets the dimension of the vector and changes the value of ALL non-active components
T & front ()
void push_back (index_type index, Tvalue)
push_back of a new active entry requires: index > index of last active entry if index < size: size is unchanged if index >= size: size = index + 1
size_t size () const
bool empty () const
size_t nActiveElements () const
void concatenate (const SingleValueSparseVector< T > &bsv)
Concatenates an other block sparse vector.
void concatenate (const std::vector< T > &v, u32 startPosition)
Concatenates a standard vector to the current sparse vector.
SingleValueSparseVector< T > & operator*= (const T &)
Scales the content of a block sparse vector with all its elements.
SingleValueSparseVector< T > & operator+= (const SingleValueSparseVector< T > &)
Adds a block sparse vector to the recent one.
SingleValueSparseVector< T > & add (const T &weight, const SingleValueSparseVector< C > &)
in place weighted operator+=
SingleValueSparseVector< T > & add (const T &weight, const std::map< u32, C > &)
Static Public Member Functions
static const Flow::Datatype * type ()
Static Public Member Functions inherited from Flow::Timestamp
static const Datatype * type ()
Static Public Member Functions inherited from Flow::Data
static Data * eos ()
End of stream (EOS) sentinel.
static Data * ood ()
Out of data (OOD) sentinel This sentinel has been introduced to support partial processing of longer external input sequence.
static bool isSentinel (const ThreadSafeReferenceCounted *object)
static bool isNotSentinel (const ThreadSafeReferenceCounted *object)
Private Types
typedef Vector< T > Self
typedef SingleValueSparseVector< T > Precursor
Additional Inherited Members
Protected Member Functions inherited from Flow::Timestamp
Timestamp (const Datatype *dt)
Core::XmlOpen xmlOpen () const
Protected Member Functions inherited from Flow::Data
virtual void free () const
void lock () const
void release () const
void increment () const
bool decrement () const
Data (const Datatype *dt)
Core::XmlOpen xmlOpen () const
Core::XmlClose xmlClose () const
Protected Member Functions inherited from Core::ThreadSafeReferenceCounted
void lock () const
void release () const
void increment () const
bool decrement () const
ThreadSafeReferenceCounted (u32 rc)
Detailed Description
template<class T>
class Sparse::Vector< T >
Block sparse vector with integration into the Flow network.
Previosly: Flow::SparseVector
Definition at line 36 of file Sparse/Vector.hh.
Constructor & Destructor Documentation
template<class T> Sparse::Vector< T >::Vector () inline
Creates a new sparse vector.
Definition at line 62 of file Sparse/Vector.hh.
template<class T> Sparse::Vector< T >::Vector (int size) inline
Creates a new sparse vector with given size.
Parameters
size Initial size.
Definition at line 69 of file Sparse/Vector.hh.
template<class T> Sparse::Vector< T >::Vector (int size, T contentToFill) inline
Creates a new sparse vector with given size and content.
Parameters
size Initial size
contentToFill Content to fill the sparse vector with.
Definition at line 77 of file Sparse/Vector.hh.
template<class T> Sparse::Vector< T >::Vector (const Vector< T > & v) inline
Copy constructor.
Parameters
v Original data.
Definition at line 84 of file Sparse/Vector.hh.
template<class T> Sparse::Vector< T >::Vector (const Precursor & v) inline
Copy constructor from Precursor.
Parameters
v Original data.
Definition at line 91 of file Sparse/Vector.hh.
template<class T> virtual Sparse::Vector< T >::~Vector () inline virtual
Destroys the sparse vector.
Definition at line 95 of file Sparse/Vector.hh.
Member Function Documentation
template<class T> virtual Data* Sparse::Vector< T >::clone () const inline virtual
Returns a pointer of a vector clone.
Reimplemented from Flow::Data.
Definition at line 98 of file Sparse/Vector.hh.
References Sparse::Vector< T >::dump(), Sparse::Vector< T >::read(), and Sparse::Vector< T >::write().
template<typename T > Core::XmlWriter & Sparse::Vector< T >::dump (Core::XmlWriter & o) const virtual
Dumps the sparse vector to an XML stream.
Parameters
o XML output stream to write to.
Reimplemented from Flow::Timestamp.
Definition at line 112 of file Sparse/Vector.hh.
References Sparse::SingleValueSparseVector< T >::dump(), and Sparse::SingleValueSparseVector< T >::size().
Referenced by Sparse::Vector< T >::clone().
template<typename T > bool Sparse::Vector< T >::read (Core::BinaryInputStream & i) virtual
Reads a sparse vector from a binary stream.
Parameters
i Stream to read from.
Reimplemented from Flow::Timestamp.
Definition at line 124 of file Sparse/Vector.hh.
References Sparse::SingleValueSparseVector< T >::read().
Referenced by Sparse::Vector< T >::clone(), and Sparse::operator>>().
template<typename T > bool Sparse::Vector< T >::write (Core::BinaryOutputStream & o) const virtual
Writes a sparse vector to a binary stream.
Parameters
o Stream to write to.
Reimplemented from Flow::Timestamp.
Definition at line 135 of file Sparse/Vector.hh.
References Sparse::SingleValueSparseVector< T >::write().
Referenced by Sparse::Vector< T >::clone().
The documentation for this class was generated from the following file:
Sparse/Vector.hh