Sprint: Math::Lapack::GenEigenProblemWithSchurDecomposition Class Reference
Math::Lapack::GenEigenProblemWithSchurDecomposition Class Reference
Wrapper for generalized generalized eigenvalue problem.
#include <EigenvalueProblem.hh>
Public Member Functions
GenEigenProblemWithSchurDecomposition (const Core::Configuration &)
virtual bool solveSymmetric (const Math::Matrix< ValueType > &a, const Math::Matrix< ValueType > &b, Math::Vector< ValueType > &eigenvalues, Math::Matrix< ValueType > &eigenvectors)
Interface function for generalized symmetric eigenvalue problem.
bool solve (const Math::Matrix< ValueType > &a, const Math::Matrix< ValueType > &b, Math::Vector< std::complex< ValueType >> &eigenvalues, Math::Matrix< std::complex< ValueType >> &leftEigenvectors, Math::Matrix< std::complex< ValueType >> &rightEigenvectors)
Public Member Functions inherited from Math::GeneralizedEigenvalueProblem
GeneralizedEigenvalueProblem (const Core::Configuration &)
virtual bool solveSymmetric (const Matrix< ValueType > &a, Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)
Interface function for symmetric eigenvalue problem.
bool solveSymmetricAndFinalize (const Matrix< ValueType > &a, const Matrix< ValueType > &b, Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)
Solves the symmetric generalized eigenvalue problem and performs finalization of results.
bool finalizeEigenvaluesAndVectors (const Matrix< ValueType > &a, const Matrix< ValueType > &b, Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)
Performs final processing of eigenvalues and eigenvectors.
bool finalize (const Matrix< ValueType > &a, const Matrix< ValueType > &b, Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)
Performs final processing and verifications.
bool isCorrectSolution (const Matrix< ValueType > &a, const Matrix< ValueType > &b, const Vector< ValueType > &eigenvalues, const Matrix< ValueType > &eigenvectors)
Verifies if eigenvectors and eigenvalues satisfy A*X = Lambda*B*X.
Public Member Functions inherited from Math::EigenvalueProblem
EigenvalueProblem (const Core::Configuration &)
bool solveSymmetricAndFinalize (const Matrix< ValueType > &a, Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)
Solves the symmetric eigenvalue problem and performs finalization of results.
bool finalize (const Matrix< ValueType > &a, Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)
Performs final processing and verifications.
bool finalizeEigenvaluesAndVectors (const Matrix< ValueType > &a, Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)
Performs final processing of eigenvalues and eigenvectors.
bool isCorrectSolution (const Matrix< ValueType > &a, const Vector< ValueType > &eigenvalues, const Matrix< ValueType > &eigenvectors)
Verifies if eigenvectors and eigenvalues satisfy A*X = Lambda*B*X.
void sortEigenvalues (Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)
Sorts eigenvalues in descending order.
bool real (const Vector< std::complex< ValueType >> &, Vector< ValueType > &)
Extracts real part of the input vector.
bool real (const Matrix< std::complex< ValueType >> &, Matrix< ValueType > &)
Extracts real part of the input matrix.
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Math::Lapack::EigenvalueProblem
EigenvalueProblem (const Core::Configuration &)
Private Types
enum BalancingType { noneBalancing, permute, scale, permuteAndScale }
If input matrices have widely varying magnitudes then they should be first balanced.
Private Member Functions
bool solveWithExpertDriver (const Math::Matrix< ValueType > &a, const Math::Matrix< ValueType > &b, Math::Vector< std::complex< ValueType >> &eigenvalues, Math::Matrix< std::complex< ValueType >> &leftEigenvectors, Math::Matrix< std::complex< ValueType >> &rightEigenvectors) const
bool dggevx (Matrix< double > &a, Matrix< double > &b, Vector< double > &realAlphas, Vector< double > &imaginaryAlphas, Vector< double > &betas, Matrix< double > &leftEigenvectors, Matrix< double > &rightEigenvectors, Vector< double > &eigenvalueReciprocalConditionNumbers, Vector< double > &eigenvectorReciprocalConditionNumbers, double &oneNormOfBalancedA, double &oneNormOfBalancedB, double &leftMaxPerMinScaling, double &rightMaxPerMinScaling) const
LAPACK function which solves the generalized eigenvalue problem.
double maxPerMinScaling (const Vector< double > &scales, int ilo, int ihi) const
void copyAlphas (const Vector< double > &realAlphas, const Vector< double > &imaginaryAlphas, Math::Vector< std::complex< ValueType >> &betas) const
Copies alphar and alphai in std::complex array.
void copyEigenvalues (const Math::Vector< std::complex< ValueType >> &alphas, const Vector< double > &betas, Math::Vector< std::complex< ValueType >> &eigenvalues) const
Copies eigenvalues form the LAPACK data structures alphas, and betas.
std::complex< ValueType > calculateEigenvalue (std::complex< ValueType > alpha, ValueType alphaMinimum, ValueType beta, ValueType betaMinimum, std::string &warningDescription) const
Calculates the eigenvalue from alpha and beta.
void copyEigenvectors (const Math::Vector< std::complex< ValueType >> &alphas, const Matrix< ValueType > &v, Math::Matrix< std::complex< ValueType >> &eigenvectors) const
Copies eigenvectors form the LAPACK data structure v.
void writeConditionNumbers (Core::XmlWriter &os, const Math::Vector< std::complex< ValueType >> &alphas, const Vector< double > &betas, const Math::Vector< std::complex< ValueType >> &eigenvalues, const Vector< double > &eigenvalueReciprocalConditionNumbers, const Vector< double > &eigenvectorReciprocalConditionNumbers, double oneNormOfBalancedA, double oneNormOfBalancedB, double &leftMaxPerMinScaling, double &rightMaxPerMinScaling) const
char translateBalancingType (BalancingType) const
char translateSensitivity () const
Private Attributes
double relativeAlphaMinimum_
double relativeBetaMinimum_
Core::XmlChannel conditionNumberChannel_
Static Private Attributes
static const Core::ParameterFloat paramRelativeAlphaMinimum
static const Core::ParameterFloat paramRelativeBetaMinimum
static const Core::Choice choiceBalancing
static const Core::ParameterChoice paramBalancing
Additional Inherited Members
Public Types inherited from Math::EigenvalueProblem
enum Type { typeGeneral, typeSymmetric, typeSymmetricPositiveDefinite }
typedef f64 ValueType
Static Public Attributes inherited from Math::EigenvalueProblem
static const Core::Choice choiceType
static const Core::ParameterChoice paramType
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Types inherited from Math::Lapack::EigenvalueProblem
enum DriverType { driverExpert, driverRelativelyRobust, driverDivideAndConquer }
Different implementations types of the same algorithm -"expert" driver supports all features (e.g.
Protected Member Functions inherited from Math::EigenvalueProblem
bool areEqual (const Matrix< ValueType > &x, const Matrix< ValueType > &y)
bool normalizeDiagonal (const Matrix< ValueType > &a, Matrix< ValueType > &eigenvectors)
Eigenvectors are scaled so that eigenvector^T * A * eigenvector = I.
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Member Functions inherited from Math::Lapack::EigenvalueProblem
bool isEigenvalueRangeValid () const
char translateEigenvalueRange () const
double eigenvalueLowerBound () const
double eigenvalueUpperBound () const
DriverType driverType () const
bool shouldSupportEigenvectors () const
void supportEigenvectors (const Matrix< int, RowByRowStorage > &isuppz, Matrix< double > &eigenvectors) const
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Wrapper for generalized generalized eigenvalue problem.
Definition at line 136 of file Lapack/EigenvalueProblem.hh.
Member Enumeration Documentation
enum Math::Lapack::GenEigenProblemWithSchurDecomposition::BalancingType private
If input matrices have widely varying magnitudes then they should be first balanced.
The algorithm is O(n^2). Balancing a matrix pair (A,B) includes, first, permuting rows and columns to isolate eigenvalues, second, applying diagonal similarity transformation to the rows and columns to make the rows and columns as close in norm as possible. The computed reciprocal condition numbers correspond to the balanced matrix. Permuting rows and columns will not change the condition numbers (in exact arithmetic) but diagonal scaling will. For further explanation of balancing, see section 4.11.1.2 of LAPACK Users' Guide.
Definition at line 153 of file Lapack/EigenvalueProblem.hh.
Member Function Documentation
std::complex< Math::EigenvalueProblem::ValueType > GenEigenProblemWithSchurDecomposition::calculateEigenvalue (std::complex< ValueType > alpha, ValueType alphaMinimum, ValueType beta, ValueType betaMinimum, std::string & warningDescription) const private
Calculates the eigenvalue from alpha and beta.
Warnings are generated if abs(alpha) < alphaMinimum or abs(beta) < betaMinimum. For these pairs resulting eigenvalue is set to zero.
Definition at line 480 of file Lapack/EigenvalueProblem.cc.
References Core::abs(), and Core::form().
void GenEigenProblemWithSchurDecomposition::copyAlphas (const Vector< double > & realAlphas, const Vector< double > & imaginaryAlphas, Math::Vector< std::complex< ValueType >> & betas) const private
Copies alphar and alphai in std::complex array.
Definition at line 448 of file Lapack/EigenvalueProblem.cc.
References require.
void GenEigenProblemWithSchurDecomposition::copyEigenvalues (const Math::Vector< std::complex< ValueType >> & alphas, const Vector< double > & betas, Math::Vector< std::complex< ValueType >> & eigenvalues) const private
Copies eigenvalues form the LAPACK data structures alphas, and betas.
Definition at line 456 of file Lapack/EigenvalueProblem.cc.
References Core::maxAbsoluteElement(), require, and Core::Component::warning().
void GenEigenProblemWithSchurDecomposition::copyEigenvectors (const Math::Vector< std::complex< ValueType >> & alphas, const Matrix< ValueType > & v, Math::Matrix< std::complex< ValueType >> & eigenvectors) const private
Copies eigenvectors form the LAPACK data structure v.
alphas are necessary to decide if column of v contain real values or complex conjugate pairs.
Definition at line 502 of file Lapack/EigenvalueProblem.cc.
References Math::copy(), defect, Core::Component::error(), require, and verify.
bool GenEigenProblemWithSchurDecomposition::dggevx (Matrix< double > & a, Matrix< double > & b, Vector< double > & realAlphas, Vector< double > & imaginaryAlphas, Vector< double > & betas, Matrix< double > & leftEigenvectors, Matrix< double > & rightEigenvectors, Vector< double > & eigenvalueReciprocalConditionNumbers, Vector< double > & eigenvectorReciprocalConditionNumbers, double & oneNormOfBalancedA, double & oneNormOfBalancedB, double & leftMaxPerMinScaling, double & rightMaxPerMinScaling) const private
LAPACK function which solves the generalized eigenvalue problem.
Eigenvalues are returned in alphar, alphar, and beta. Left and right eigenvectors are returned in vl and vr.
See also
copyEigenvalues and copyEigenvectors.
Definition at line 356 of file Lapack/EigenvalueProblem.cc.
References Core::Component::error(), and require.
bool GenEigenProblemWithSchurDecomposition::solveSymmetric (const Math::Matrix< ValueType > & a, const Math::Matrix< ValueType > & b, Math::Vector< ValueType > & eigenvalues, Math::Matrix< ValueType > & eigenvectors) virtual
Interface function for generalized symmetric eigenvalue problem.
Implements Math::GeneralizedEigenvalueProblem.
Definition at line 283 of file Lapack/EigenvalueProblem.cc.
References Math::copy(), Core::Component::error(), and Math::EigenvalueProblem::real().
The documentation for this class was generated from the following files:
Lapack/EigenvalueProblem.hh
Lapack/EigenvalueProblem.cc