Sprint: Flf::NBestBuilder Class Reference
Flf::NBestBuilder Class Reference
Classes
struct Arc
class Detour
struct DetourPtrWeakOrder
class DissenterList
struct Node
class Path
class PrefixTree
Public Types
typedef const Arc * ConstArcPtr
typedef std::vector< ConstArcPtr > ConstArcPtrList
typedef std::vector< Path > PathList
typedef std::vector< u32 > PathIdList
typedef Detour * DetourPtr
typedef BinaryPriorityQueue< DetourPtr, DetourPtrWeakOrder > DetourPtrQueue
Public Member Functions
NBestBuilder (ConstLatticeRef l, u32 n, bool removeDuplicates=true, bool ignoreNonWords=true)
void dumpStatistics (Core::XmlWriter &xml)
StaticLatticeRef lattice (ScoreId scoreId=Semiring::InvalidId)
Private Member Functions
void initialize (bool ignoreNonWords)
Calculate.
void find (u32 n)
Private Attributes
ConstLatticeRef l_
bool removeDuplicates_
u32 nUniquePaths_
PathList paths_
PathIdList validPathIds_
Arc * arcs_
Node * nodes_
u32 nodesSize_
Score bestScore_
PrefixTree prefixTree_
Detailed Description
Definition at line 300 of file NBest.cc.
Member Function Documentation
void Flf::NBestBuilder::initialize (bool ignoreNonWords) private
Calculate.
state fwd./bwd. scores
arc dissenter score: additional cost of using arc instead of (locally) best path
Definition at line 585 of file NBest.cc.
References Core::Component::criticalError(), defect, Flf::determinize(), Flf::Semiring::extend(), Core::form(), Flf::Boundaries::get(), Flf::StaticBoundaries::get(), Core::isAlmostEqualUlp(), Ftl::State< _Arc, _ArcContainer >::newArc(), Flf::StaticBoundaries::set(), Flf::sortTopologically(), Core::Application::us(), Flf::Boundaries::valid(), verify, and Core::Component::warning().
The documentation for this class was generated from the following file:
NBest.cc