Sprint: Flf::Node Class Reference
Flf::Node Class Reference
Classes
struct Link
Public Types
typedef u32 Port
typedef Core::Vector< Link > LinkList
Public Member Functions
LinkList & in ()
LinkList & out ()
bool connected (Port from) const
ConstLatticeRef requestLattice (Port from=0)
This section defines request handler for some common data types.
Fsa::ConstAutomatonRef requestFsa (Port from)
ConstPosteriorCnRef requestPosteriorCn (Port from)
ConstConfusionNetworkRef requestCn (Port from)
ConstSegmentRef requestSegment (Port from)
bool requestBool (Port from)
s32 requestInt (Port from)
f64 requestFloat (Port from)
std::string requestString (Port from)
const void * requestData (Port from)
Node (const std::string &name, const Core::Configuration &config)
virtual void init (const std::vector< std::string > &arguments)
init, good, pull, and finalize are making up the used network protocol.
virtual void sync ()
Is called at every node before pull is called at the final nodes (see below); all nodes are initialized before sync is called the first time.
virtual bool blockSync () const
virtual bool good ()
Is called immediately after sync and has to return true, iff another data request is accepted.
virtual void finalize ()
Finalize is called before any node in the network is deallocated.
virtual void pull ()
Is called after a sync for each final node.
virtual ConstLatticeRef sendLattice (Port to)
This section defines send handler for some common data types.
virtual Fsa::ConstAutomatonRef sendFsa (Port to)
virtual ConstPosteriorCnRef sendPosteriorCn (Port to)
virtual ConstConfusionNetworkRef sendCn (Port to)
virtual ConstSegmentRef sendSegment (Port to)
virtual bool sendBool (Port to)
virtual s32 sendInt (Port to)
virtual f64 sendFloat (Port to)
virtual std::string sendString (Port to)
virtual const void * sendData (Port to)
void dump (std::ostream &o) const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Public Attributes
const std::string name
Static Public Attributes
static const Port InvalidPort = Core::Type<Node::Port>::max
Protected Member Functions
virtual bool init_ (NetworkCrawler &crawler, const std::vector< std::string > &arguments)
init_ is called directly before init(...) init_ should only be used by intermediate nodes and has to be passed through (in opposite to init(...), which should not be used by intermediate nodes at all) dito for sync_ and finalize_
virtual bool sync_ (NetworkCrawler &crawler)
virtual void finalize_ (NetworkCrawler &crawler)
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Private Attributes
u32 id_
LinkList in_
LinkList out_
Friends
class Network
class NetworkParser
class NetworkCrawler
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Definition at line 55 of file Flf/Network.hh.
Member Function Documentation
virtual void Flf::Node::finalize (void) inline virtual
Finalize is called before any node in the network is deallocated.
Reimplemented in Flf::IncrementalRecognizerNode, Flf::OracleAlignmentNode, Flf::RoverCombinationNode, Flf::StateClusterCnBuilderNode, Flf::LocalCostDecoderNode, Flf::PivotArcCnBuilderNode, Flf::PosteriorCnArchiveWriterNode, Flf::ConfusionNetworkCombinationNode, Flf::CenterFrameCnBuilderNode, Flf::PosteriorCnArchiveReaderNode, Flf::AppendScoresNode, Flf::WordListExtractorNode, Flf::RecognizerNode, Flf::DumpConfusionNetworkNode, Flf::ConfusionNetworkArchiveWriterNode, Flf::ConfusionNetworkArchiveReaderNode, Flf::CnDecoderNode, Flf::ConcatenateFCnsNode, Flf::InfoNode, Flf::DumpPosteriorCnNode, Flf::ConcatenateLatticesNode, Flf::TimeAlignmentNode, Flf::LatticeArchiveWriterNode, Flf::TimeframeErrorNode, Flf::LatticeArchiveReaderNode, Flf::UnionNode, and Flf::BatchNode.
Definition at line 175 of file Flf/Network.hh.
virtual bool Flf::Node::good () inline virtual
Is called immediately after sync and has to return true, iff another data request is accepted.
By default a node with no incoming arc is not good;
Reimplemented in Flf::BatchNode, and Flf::SpeechSegmentNode.
Definition at line 168 of file Flf/Network.hh.
virtual void Flf::Node::init (const std::vector< std::string > & arguments) inline virtual
init, good, pull, and finalize are making up the used network protocol.
they are called in the following order.
init while good: if is_final_node: pull sync finalize Is called after network is completely build and before the first lattice is processed by any node.
<arguments> is the argument of Core::Appliation::main, i.e. the not-sprint relevant command line arguments.
Reimplemented in Flf::IncrementalRecognizerNode, Flf::OracleAlignmentNode, Flf::RoverCombinationNode, Flf::StateClusterCnBuilderNode, Flf::LabelMapNode, Flf::DumpNBestNode, Flf::FwdBwdBuilderNode, Flf::SelectNBestNode, Flf::LocalCostDecoderNode, Flf::NBestNode, Flf::PivotArcCnBuilderNode, Flf::PosteriorCnArchiveWriterNode, Flf::CnFeatureNode, Flf::ConfusionNetworkCombinationNode, Flf::CenterFrameCnBuilderNode, Flf::PosteriorCnArchiveReaderNode, Flf::LatticeWriterNode, Flf::MinimumFrameWerDecoderNode, Flf::AppendScoresNode, Flf::WriterNode, Flf::WordListExtractorNode, Flf::MeshNode, Flf::SegmentBuilderNode, Flf::RecognizerNode, Flf::UniqueSentenceAlignmentFilterNode, Flf::CtmReaderNode, Flf::CnPruningNode, Flf::DumpConfusionNetworkNode, Flf::ConfusionNetworkArchiveWriterNode, Flf::CleanUpNode, Flf::AlphabetMapNode, Flf::ConfusionNetworkArchiveReaderNode, Flf::Sink, Flf::FwdBwdPruningNode, Flf::LatticeBufferNode, Flf::CnDecoderNode, Flf::DumpTracebackNode, Flf::FsaReaderNode, Flf::ConcatenateFCnsNode, Flf::DummyFilterNode, Flf::ExtendByPenaltyNode, Flf::InfoNode, Flf::FramePosteriorCnFeatureNode, Flf::FitLatticeNode, Flf::DumpPosteriorCnNode, Flf::LatticeReaderNode, Flf::ConcatenateLatticesNode, Flf::StringConverterNode, Flf::ReaderNode, Flf::TimeAlignmentNode, Flf::ComposeWithFsaNode, Flf::DumpAllPairsShortestDistanceNode, Flf::ExtendByPosteriorCnConfidenceNode, Flf::DecodeRescoreLmNode, Flf::LatticeArchiveWriterNode, Flf::EvaluatorNode, Flf::ComposeWithLmNode, Flf::FramePosteriorCnCombinationNode, Flf::FramePosteriorCnBuilderNode, Flf::TimeframeErrorNode, Flf::LatticeArchiveReaderNode, Flf::UnionNode, Flf::ProjectSemiringNode, Flf::ArcRemovalNode, Flf::BestNode, Flf::ArithmeticNode< Func >, Flf::ChangeSemiringNode, Flf::FilterArcNode, Flf::ReduceScoresNode, Flf::CnGammaCorrectionNode, Flf::BatchNode, Flf::PushForwardRescoringNode, Flf::DeterminizeNode, and Flf::SpeechSegmentNode.
Definition at line 149 of file Flf/Network.hh.
bool Flf::Node::init_ (NetworkCrawler & crawler, const std::vector< std::string > & arguments) protected virtual
init_ is called directly before init(...) init_ should only be used by intermediate nodes and has to be passed through (in opposite to init(...), which should not be used by intermediate nodes at all) dito for sync_ and finalize_
Reimplemented in Flf::FilterNode, Flf::ConcatenateNode, Flf::ComposeNode, Flf::RescoreSingleDimensionNode, and Flf::RescoreNode.
Definition at line 106 of file Flf/Network.cc.
References Core::Component::log().
void Flf::Node::pull () virtual
Is called after a sync for each final node.
Reimplemented in Flf::Sink.
Definition at line 228 of file Flf/Network.cc.
References Core::Component::criticalError().
ConstLatticeRef Flf::Node::requestLattice (Port from = 0)
This section defines request handler for some common data types.
Note: Deliberately, no advanced, powerful, abstract data type handling was implemented. Keep software simple!
Definition at line 138 of file Flf/Network.cc.
References require.
Referenced by Flf::MinimumFrameWerDecoderNode::sendLattice().
ConstLatticeRef Flf::Node::sendLattice (Port to = 0) virtual
This section defines send handler for some common data types.
Note: Deliberately, no advanced, powerful, abstract data type handling was implemented. Keep software simple!
Reimplemented in Flf::IncrementalRecognizerNode, Flf::RoverCombinationNode, Flf::StateClusterCnBuilderNode, Flf::FwdBwdBuilderNode, Flf::LocalCostDecoderNode, Flf::SelectNBestNode, Flf::PivotArcCnBuilderNode, Flf::ConfusionNetworkCombinationNode, Flf::CenterFrameCnBuilderNode, Flf::MinimumFrameWerDecoderNode, Flf::AppendScoresNode, Flf::RecognizerNode, Flf::CtmReaderNode, Flf::DumpConfusionNetworkNode, Flf::FsaReaderNode, Flf::CnDecoderNode, Flf::DummyFilterNode, Flf::DumpPosteriorCnNode, Flf::LatticeReaderNode, Flf::ConcatenateLatticesNode, Flf::StringConverterNode, Flf::LatticeArchiveWriterNode, Flf::FramePosteriorCnCombinationNode, Flf::LatticeArchiveReaderNode, Flf::FramePosteriorCnBuilderNode, Flf::FilterNode, Flf::UnionNode, and Flf::ComposeNode.
Definition at line 178 of file Flf/Network.cc.
References Core::Component::criticalError().
virtual void Flf::Node::sync () inline virtual
Is called at every node before pull is called at the final nodes (see below); all nodes are initialized before sync is called the first time.
The sync request is propagated from the final nodes through all nodes which return 'false' on blockSync() (see below)
Reimplemented in Flf::IncrementalRecognizerNode, Flf::OracleAlignmentNode, Flf::RoverCombinationNode, Flf::StateClusterCnBuilderNode, Flf::FwdBwdBuilderNode, Flf::LocalCostDecoderNode, Flf::SelectNBestNode, Flf::PivotArcCnBuilderNode, Flf::NBestNode, Flf::ConfusionNetworkCombinationNode, Flf::PosteriorCnArchiveWriterNode, Flf::CenterFrameCnBuilderNode, Flf::PosteriorCnArchiveReaderNode, Flf::MinimumFrameWerDecoderNode, Flf::AppendScoresNode, Flf::RecognizerNode, Flf::MeshNode, Flf::SegmentBuilderNode, Flf::CtmReaderNode, Flf::DumpConfusionNetworkNode, Flf::ConfusionNetworkArchiveWriterNode, Flf::ConfusionNetworkArchiveReaderNode, Flf::CnDecoderNode, Flf::LatticeBufferNode, Flf::FsaReaderNode, Flf::ConcatenateFCnsNode, Flf::DumpPosteriorCnNode, Flf::LatticeReaderNode, Flf::ExpandTransitsNode, Flf::ConcatenateLatticesNode, Flf::StringConverterNode, Flf::ReaderNode, Flf::DumpAllPairsShortestDistanceNode, Flf::DecodeRescoreLmNode, Flf::LatticeArchiveWriterNode, Flf::FramePosteriorCnCombinationNode, Flf::FramePosteriorCnBuilderNode, Flf::EvaluatorNode, Flf::TimeframeErrorNode, Flf::LatticeArchiveReaderNode, Flf::UnionNode, Flf::BatchNode, Flf::PushForwardRescoringNode, and Flf::SpeechSegmentNode.
Definition at line 157 of file Flf/Network.hh.
The documentation for this class was generated from the following files:
Flf/Network.hh
Flf/Network.cc