Sprint: Flf::FittingLattice::Boundaries Class Reference
Flf::FittingLattice::Boundaries Class Reference
Private Member Functions
Boundaries (ConstBoundariesRef srcBoundaries, s32 startTime, s32 endTime)
virtual bool valid () const
false, if the lattice provides no boundaries
virtual bool valid (Fsa::StateId sid) const
false, if that specific boundary does not exist or is invalid, e.g.
virtual const Boundary & get (Fsa::StateId sid) const
return a specific boundary; for every sid a boundary is returned !valid(sid) => !get(sid).valid()
Private Attributes
ConstBoundariesRef srcBoundaries_
s32 startTime_
s32 endTime_
Core::Vector< Boundary > boundaries_
Boundary initialBoundary_
Boundary finalBoundary_
Boundary finalTm1Boundary_
Friends
class FittingLattice
Additional Inherited Members
Public Member Functions inherited from Flf::Boundaries
Speech::TimeframeIndex time (Fsa::StateId sid) const
undefined, if !valid(sid)
Boundary::Transit transit (Fsa::StateId sid) const
undefined, if !valid(sid)
void dumpBoundary (Fsa::StateId sid, std::ostream &os) const
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Detailed Description
Definition at line 47 of file Miscellaneous.cc.
Member Function Documentation
virtual const Boundary& Flf::FittingLattice::Boundaries::get (Fsa::StateId sid) const inline private virtual
return a specific boundary; for every sid a boundary is returned !valid(sid) => !get(sid).valid()
Implements Flf::Boundaries.
Definition at line 81 of file Miscellaneous.cc.
References defect, Core::Component::error(), Core::form(), Core::Ref< T >::get(), Core::Vector< T >::grow(), Flf::HintUnscaled, Core::PriorityQueueBase< T_Heap, T_PriorityFunction >::insert(), Ftl::State< _Arc, _ArcContainer >::newArc(), Core::PriorityQueueBase< T_Heap, T_PriorityFunction >::pop(), Core::PriorityQueueBase< T_Heap, T_PriorityFunction >::top(), Core::Application::us(), and verify.
virtual bool Flf::FittingLattice::Boundaries::valid () const inline private virtual
false, if the lattice provides no boundaries
Implements Flf::Boundaries.
Definition at line 70 of file Miscellaneous.cc.
virtual bool Flf::FittingLattice::Boundaries::valid (Fsa::StateId sid) const inline private virtual
false, if that specific boundary does not exist or is invalid, e.g.
not set !valid() => !valid(sid) for all state id
Implements Flf::Boundaries.
Definition at line 73 of file Miscellaneous.cc.
The documentation for this class was generated from the following file:
Miscellaneous.cc