Sprint: Bliss::CorpusDescription Class Reference
Bliss::CorpusDescription Class Reference
Classes
class ProgressIndicationVisitorAdaptor
class SegmentCountingVisitor
class SegmentPartitionVisitorAdaptor
Public Member Functions
CorpusDescription (const Core::Configuration &)
const std::string & file () const
void accept (CorpusVisitor *)
Traverse corpus.
u32 totalSegmentCount ()
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Attributes
static const Core::ParameterString paramFilename
static const Core::ParameterBool paramAllowEmptyWhitelist
static const Core::ParameterString paramEncoding
static const Core::ParameterInt paramPartition
static const Core::ParameterInt paramPartitionSelection
static const Core::ParameterInt paramSkipFirstSegments
static const Core::ParameterStringVector paramSegmentsToSkip
static const Core::ParameterBool paramRecordingBasedPartition
static const Core::ParameterString paramSegmentOrder
static const Core::ParameterBool paramSegmentOrderLookupName
static const Core::ParameterBool paramSegmentOrderShuffle
static const Core::ParameterInt paramSegmentOrderShuffleSeed
static const Core::ParameterBool paramSegmentOrderSortByTimeLength
static const Core::ParameterInt paramSegmentOrderSortByTimeLengthChunkSize
static const Core::ParameterBool paramProgressReportingSegmentOrth
static const Core::ParameterBool paramTheanoSegmentOrder
static const Core::ParameterBool paramPythonSegmentOrder
static const Core::ParameterString paramPythonSegmentOrderModPath
static const Core::ParameterString paramPythonSegmentOrderModName
static const Core::ParameterString paramPythonSegmentOrderConfig
Private Types
enum ProgressIndcationMode { noProgress, localProgress, globalProgress }
Private Attributes
std::string filename_
SegmentPartitionVisitorAdaptor * selector_
Core::XmlChannel progressChannel_
ProgressReportingVisitorAdaptor * reporter_
ProgressIndcationMode progressIndicationMode_
ProgressIndicationVisitorAdaptor * indicator_
SegmentOrderingVisitor * ordering_
Static Private Attributes
static const Core::Choice progressIndicationChoice
static const Core::ParameterChoice paramProgressIndication
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Definition at line 551 of file CorpusDescription.hh.
Member Function Documentation
void CorpusDescription::accept (CorpusVisitor * visitor)
Traverse corpus.
Each corpus element is processed by the given visitor. (This is an application of the Visitor pattern, in order to avoid concentrate the iteration logic in one place.)
Definition at line 598 of file CorpusDescription.cc.
Referenced by FeatureStatistics::main(), SpeechRecognizer::main(), ExtractionApplication::main(), NnTrainer::main(), Costa::main(), AcousticModelTrainer::showMixtureSet(), LatticeProcessor::visitCorpus(), BuildSegmentToOrthMapVisitor::visitSpeechSegment(), and Speech::CorpusProcessorNode< CorpusProcessorType >::work().
The documentation for this class was generated from the following files:
CorpusDescription.hh
CorpusDescription.cc