Sprint: Core::ObjectCache< List > Class Template Reference
Core::ObjectCache< List > Class Template Reference
ObjectCache: implements the caching of larger objects.
#include <ObjectCache.hh>
Public Member Functions
ObjectCache (const Configuration &c, u8 mode=createObjectCacheMode)
ObjectCache.
const Data * findForReadAccess (const Key &key)
Data * findForWriteAccess (const Key &key)
bool insert (const Key &key, Data *data)
Inserts a new object into the cache.
void writeBack (const Key &key)
saves the object of the key and removes it from the memory
void writeBack ()
saves all objects and removes them from the memory
void clear ()
clears the memory and and the directory
std::set< Key > keys ()
return a 'std::set' of all the keys, both in memory and on disk.
std::string getDirectory () const
getDirectory
void setDirectory (const std::string &directoryName)
setDirectory
void setMaxSize (u32 maxSize)
setMaxSize
u32 size ()
size
void setDump (bool shouldDump)
For each object a *.dump file is created in XML format.
bool setParameter (const std::string &name, const std::string &value)
supports parametrization by name syntax of parameter name (as one would do in a configuration file: cacheName.parameter-name = "something"
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Private Types
typedef List::Key Key
typedef List::Data Data
typedef List::Iterator ListIterator
Private Member Functions
std::string createFilename (const Key &key) const
std::string fileExtension () const
bool openInputStream (const Key &key, BinaryInputStream &is)
void writeBack (ListIterator item)
Saves the object stored by.
ListIterator access (const Key &key)
bool parameterName (std::string &n)
Private Attributes
List list_
u32 maxSize_
std::string directoryName_
u8 mode_
bool dump_
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
template<class List>
class Core::ObjectCache< List >
ObjectCache: implements the caching of larger objects.
Datas are created by the ObjectCache. Datas can be accessed by their keys. Access is devided into readAccess and writeAccess to minimize the number of file operations. If more then maxSize_ object are referenced the last object in the CacheList is written back to its file if necesseary and it is removed from the memory. The last object is given by the cache strategy implemented by the CacheList. The files are stored in one directory. The file names are the keys of the Datas. Datas can be explicitly saved (writeBack) and explicitly removed (erase) from the memory. Store references to Datas with care! References are valid until the next access to the cache.
Definition at line 347 of file ObjectCache.hh.
Constructor & Destructor Documentation
template<class List > Core::ObjectCache< List >::ObjectCache (const Configuration & c, u8 mode = createObjectCacheMode)
ObjectCache.
Parameters
mode controls handling of files: reuseObjectCacheMode does not allow creation of new objects appendObjectCacheMode reuses existing objects and allows creation of new objects createObjectCacheMode deletes exisiting objects and create new ones
Definition at line 468 of file ObjectCache.hh.
References Core::joinPaths(), Core::ObjectCache< List >::setDirectory(), Core::ObjectCache< List >::setDump(), and Core::ObjectCache< List >::setMaxSize().
Member Function Documentation
template<class List > void Core::ObjectCache< List >::clear ()
clears the memory and and the directory
Definition at line 579 of file ObjectCache.hh.
References Core::joinPaths().
Referenced by Speech::HistogramEstimator::processFeatureVector(), and Core::ObjectCache< List >::setDirectory().
template<class List> const Data* Core::ObjectCache< List >::findForReadAccess (const Key & key) inline
Returns
is a constant pointer to the object of the key if the object is in the cache or is stored in the cache directory; otherwise return is zero pointer.
Definition at line 392 of file ObjectCache.hh.
template<class List> Data* Core::ObjectCache< List >::findForWriteAccess (const Key & key) inline
Returns
is a pointer to the object of the key if the object is in the cache or is stored in the cache directory; otherwise return is zero pointer.
Definition at line 400 of file ObjectCache.hh.
template<class List> std::string Core::ObjectCache< List >::getDirectory () const inline
getDirectory
Definition at line 436 of file ObjectCache.hh.
template<class List > bool Core::ObjectCache< List >::insert (const Key & key, Data * data)
Inserts a new object into the cache.
Returns
is false if the
Parameters
key already exists.
Definition at line 545 of file ObjectCache.hh.
References Core::ObjectCache< List >::size(), and Core::ObjectCache< List >::writeBack().
template<class List> std::set<Key> Core::ObjectCache< List >::keys () inline
return a 'std::set' of all the keys, both in memory and on disk.
Definition at line 419 of file ObjectCache.hh.
template<class List > void Core::ObjectCache< List >::setDirectory (const std::string & directoryName)
setDirectory
Parameters
directoryName is the directory storing the objects
Definition at line 589 of file ObjectCache.hh.
References Core::ObjectCache< List >::clear(), Core::directoryName(), and Core::ObjectCache< List >::writeBack().
Referenced by Core::ObjectCache< List >::ObjectCache(), and Core::ObjectCache< List >::setParameter().
template<class List> void Core::ObjectCache< List >::setDump (bool shouldDump) inline
For each object a *.dump file is created in XML format.
Definition at line 456 of file ObjectCache.hh.
Referenced by Core::ObjectCache< List >::ObjectCache(), and Core::ObjectCache< List >::setParameter().
template<class List > void Core::ObjectCache< List >::setMaxSize (u32 maxSize)
setMaxSize
Parameters
maxSize is max number of objects in the memory
Definition at line 600 of file ObjectCache.hh.
References Core::ObjectCache< List >::writeBack().
Referenced by Core::ObjectCache< List >::ObjectCache(), and Core::ObjectCache< List >::setParameter().
template<class List > bool Core::ObjectCache< List >::setParameter (const std::string & name, const std::string & value)
supports parametrization by name syntax of parameter name (as one would do in a configuration file: cacheName.parameter-name = "something"
Definition at line 607 of file ObjectCache.hh.
References Core::ObjectCache< List >::setDirectory(), Core::ObjectCache< List >::setDump(), and Core::ObjectCache< List >::setMaxSize().
template<class List> u32 Core::ObjectCache< List >::size () inline
size
Returns
is the number of objects in the memory
Definition at line 451 of file ObjectCache.hh.
Referenced by Core::ObjectCache< List >::insert().
template<class List > void Core::ObjectCache< List >::writeBack (ListIterator item) private
Saves the object stored by.
Parameters
item and removes the
item from the list_. Note: iterators on the list_ gets invalid after a call to this funciton.
Definition at line 487 of file ObjectCache.hh.
References Core::createDirectory(), Core::directoryName(), Core::Component::error(), Core::isDirectory(), and Core::ObjectCache< List >::writeBack().
template<class List > void Core::ObjectCache< List >::writeBack (const Key & key)
saves the object of the key and removes it from the memory
Definition at line 566 of file ObjectCache.hh.
References Core::ObjectCache< List >::writeBack().
template<class List > void Core::ObjectCache< List >::writeBack ()
saves all objects and removes them from the memory
Definition at line 573 of file ObjectCache.hh.
Referenced by Core::ObjectCache< List >::insert(), Core::ObjectCache< List >::setDirectory(), Core::ObjectCache< List >::setMaxSize(), and Core::ObjectCache< List >::writeBack().
The documentation for this class was generated from the following file:
ObjectCache.hh