Sprint: Search::Wfst::HmmLatticeTraceRecorder Class Reference
Search::Wfst::HmmLatticeTraceRecorder Class Reference
Constructs lattices with HMM input labels and word output labels.
#include <LatticeGenerator.hh>
Classes
struct StateInfo
Public Member Functions
HmmLatticeTraceRecorder (const StateSequenceList &hmms)
void clear ()
remove all trace objects
TraceRef addTrace (TraceRef sibling, TraceRef predecessor, OpenFst::Label output, const StateSequence *hmm, TimeframeIndex time, Score score, Score arcScore, bool wordEnd)
add a new trace
void updateTime (TraceRef t, TimeframeIndex time)
Update the timestamp of the given trace object.
bool hasWordEndTime (const WordEndDetector &wordEnds, TraceRef end)
Check if the number of word boundary time stamps matches the number of output labels on the path ending in end.
void createBestPath (const WordEndDetector &wordEnds, bool ignoreLast, TraceRef end, BestPath *path)
Find the first best path ending in end.
Lattice * createLattice (TraceRef)
Create a lattice.
void pruneBegin ()
start pruning process (for lattices only)
void pruneEnd ()
finish pruning (for lattices only)
void pruneNotify (TraceRef trace)
label the trace as currently active (for lattices only)
size_t memoryUsage () const
memory usage in bytes.
Public Member Functions inherited from Search::Wfst::LatticeTraceRecorder
void setSilence (const StateSequence *hmm, OpenFst::Label output)
Set input and output label of silence arcs.
void setMergeSilence (bool merge)
Enable/disable merging of silence arcs.
void setPruningThreshold (Score threshold)
Set threshold used for lattice pruning.
void purgeBegin ()
start purging process (reset all active flags)
void purgeEnd ()
remove all trace objects not labeled as active
void purgeNotify (TraceRef trace)
label the trace object and its predecessors as active (set active flag)
Protected Member Functions
StateId getState (TimeframeIndex time)
void addArc (StateId state, const Arc &arc, Score totalScore)
void enlarge (StateId s)
Called if a state is added to lattice_.
void prune (const std::vector< TraceRef > &finalStates)
void calculatePruningScores (const std::vector< TraceRef > &finalStates)
calculate for each states the difference in score between the best path through the state and the overall best path (w.r.t the given final states)
void mergeArc (StateId state, Arc *arc)
void mergeEpsilonArc (Arc *arc) const
bool mergePredecessorArcs (StateId state, const Arc &newArc, Score score)
void reviseSilenceLabels ()
void finalizeReverseLattice ()
Perform optimization of lattice with reversed arcs.
void reverseLattice ()
Reverse the lattice transducer.
void trimLattice ()
Similar to FstLib::Connect, but keeps the StateInfo.
void optimizeLattice ()
Perform final optimizations on the lattice.
void finalize (TraceRef end)
Finish the lattice construction with the given trace as final state.
void invalidateTimestamps ()
void addArc (StateId state, const Arc &arc)
Protected Member Functions inherited from Search::Wfst::LatticeTraceRecorder
LatticeTraceRecorder (const StateSequenceList &hmms)
Label getInputLabel (const StateSequence *hmm) const
Convert Hmm Pointer to input label.
const StateSequence * getHmm (Label label) const
Convert input label to Hmm Pointer.
StateId newState ()
Add a state to the lattice.
virtual void endLattice (TraceRef end)
Set end as final state.
void removeEpsilon (bool connect)
Remove epsilon arcs.
void shortestPath (BestPath *path) const
Generate the shortest path (using OpenFst's ShortestPath)
Protected Attributes
std::vector< TraceRef > curTraces_
std::vector< StateInfo > states_
std::vector< bool > hasEps_
bool finished_
Protected Attributes inherited from Search::Wfst::LatticeTraceRecorder
const StateSequence *const hmmsBegin_
Lattice * lattice_
Label silence_
Label silenceOutput_
bool mergeSilence_
Score pruningThreshold_
std::vector< bool > active_
Additional Inherited Members
Public Types inherited from Search::Wfst::LatticeTraceRecorder
enum LatticeType {
HmmLattice, DetermisticHmmLattice, SimpleWordLattice, SimpleNonDetWordLattice,
WordLattice
}
Public Types inherited from Search::Wfst::TraceRecorder
typedef u32 TraceRef
Static Public Member Functions inherited from Search::Wfst::LatticeTraceRecorder
static LatticeTraceRecorder * create (LatticeType type, const StateSequenceList &s)
Factory function.
Static Public Attributes inherited from Search::Wfst::TraceRecorder
static const TraceRef InvalidTraceRef = -1
Protected Types inherited from Search::Wfst::LatticeTraceRecorder
typedef Search::Wfst::Lattice Lattice
typedef Lattice::Arc Arc
typedef Arc::StateId StateId
typedef Arc::Label Label
typedef Arc::Weight Weight
typedef FstLib::StateIterator< Lattice > StateIterator
typedef FstLib::ArcIterator< Lattice > ArcIterator
typedef FstLib::MutableArcIterator< Lattice > MutableArcIterator
Detailed Description
Constructs lattices with HMM input labels and word output labels.
Performs intermediate and final pruning.
Definition at line 160 of file LatticeGenerator.hh.
Member Function Documentation
TraceRecorder::TraceRef HmmLatticeTraceRecorder::addTrace (TraceRef sibling, TraceRef predecessor, OpenFst::Label output, const StateSequence * input, TimeframeIndex time, Score score, Score arcScore, bool wordEnd) virtual
add a new trace
Implements Search::Wfst::TraceRecorder.
Definition at line 320 of file LatticeGenerator.cc.
void HmmLatticeTraceRecorder::calculatePruningScores (const std::vector< TraceRef > & finalStates) protected
calculate for each states the difference in score between the best path through the state and the overall best path (w.r.t the given final states)
Definition at line 526 of file LatticeGenerator.cc.
References require.
void HmmLatticeTraceRecorder::clear () virtual
remove all trace objects
Reimplemented from Search::Wfst::LatticeTraceRecorder.
Definition at line 238 of file LatticeGenerator.cc.
References Search::Wfst::LatticeTraceRecorder::clear().
void HmmLatticeTraceRecorder::createBestPath (const WordEndDetector & wordEnds, bool ignoreLast, TraceRef end, BestPath * path) virtual
Find the first best path ending in end.
Implements Search::Wfst::TraceRecorder.
Reimplemented in Search::Wfst::DetermisticHmmLatticeTraceRecorder.
Definition at line 397 of file LatticeGenerator.cc.
References verify.
LatticeTraceRecorder::Lattice * HmmLatticeTraceRecorder::createLattice (TraceRef) virtual
Create a lattice.
Implements Search::Wfst::TraceRecorder.
Definition at line 444 of file LatticeGenerator.cc.
void HmmLatticeTraceRecorder::enlarge (StateId s) protected virtual
Called if a state is added to lattice_.
Allows to maintain data structures with additional state information in derived classes.
Reimplemented from Search::Wfst::LatticeTraceRecorder.
Definition at line 273 of file LatticeGenerator.cc.
void HmmLatticeTraceRecorder::finalize (TraceRef end) protected virtual
Finish the lattice construction with the given trace as final state.
Executes following sequence of calls to virtual functions: endLattice() finalizeReverseLattice() trimLattice() reverseLattice() optimizeLattice()
Reimplemented from Search::Wfst::LatticeTraceRecorder.
Definition at line 489 of file LatticeGenerator.cc.
References Search::Wfst::LatticeTraceRecorder::finalize().
void HmmLatticeTraceRecorder::finalizeReverseLattice () protected virtual
Perform optimization of lattice with reversed arcs.
Reimplemented from Search::Wfst::LatticeTraceRecorder.
Reimplemented in Search::Wfst::SimpleWordLatticeRecorder, and Search::Wfst::DetermisticHmmLatticeTraceRecorder.
Definition at line 463 of file LatticeGenerator.cc.
bool HmmLatticeTraceRecorder::hasWordEndTime (const WordEndDetector & wordEnds, TraceRef end) virtual
Check if the number of word boundary time stamps matches the number of output labels on the path ending in end.
Implements Search::Wfst::TraceRecorder.
Definition at line 393 of file LatticeGenerator.cc.
size_t HmmLatticeTraceRecorder::memoryUsage () const virtual
memory usage in bytes.
Reimplemented from Search::Wfst::LatticeTraceRecorder.
Definition at line 602 of file LatticeGenerator.cc.
References Search::Wfst::LatticeTraceRecorder::memoryUsage().
void HmmLatticeTraceRecorder::optimizeLattice () protected virtual
Perform final optimizations on the lattice.
Reimplemented from Search::Wfst::LatticeTraceRecorder.
Reimplemented in Search::Wfst::SimpleNonDetWordLatticeRecorder, Search::Wfst::SimpleWordLatticeRecorder, and Search::Wfst::DetermisticHmmLatticeTraceRecorder.
Definition at line 467 of file LatticeGenerator.cc.
Referenced by Search::Wfst::DetermisticHmmLatticeTraceRecorder::optimizeLattice().
void HmmLatticeTraceRecorder::pruneBegin () virtual
start pruning process (for lattices only)
Reimplemented from Search::Wfst::TraceRecorder.
Definition at line 503 of file LatticeGenerator.cc.
void HmmLatticeTraceRecorder::pruneEnd () virtual
finish pruning (for lattices only)
Reimplemented from Search::Wfst::TraceRecorder.
Definition at line 518 of file LatticeGenerator.cc.
void HmmLatticeTraceRecorder::pruneNotify (TraceRef trace) virtual
label the trace as currently active (for lattices only)
Reimplemented from Search::Wfst::TraceRecorder.
Definition at line 509 of file LatticeGenerator.cc.
void HmmLatticeTraceRecorder::reverseLattice () protected virtual
Reverse the lattice transducer.
Reimplemented from Search::Wfst::LatticeTraceRecorder.
Definition at line 453 of file LatticeGenerator.cc.
References Search::Wfst::LatticeTraceRecorder::reverseLattice().
void HmmLatticeTraceRecorder::trimLattice () protected virtual
Similar to FstLib::Connect, but keeps the StateInfo.
Generates an intermediate copy of lattice_
Reimplemented from Search::Wfst::LatticeTraceRecorder.
Reimplemented in Search::Wfst::SimpleWordLatticeRecorder, and Search::Wfst::DetermisticHmmLatticeTraceRecorder.
Definition at line 284 of file LatticeGenerator.cc.
void HmmLatticeTraceRecorder::updateTime (TraceRef t, TimeframeIndex time) virtual
Update the timestamp of the given trace object.
Implements Search::Wfst::TraceRecorder.
Definition at line 389 of file LatticeGenerator.cc.
The documentation for this class was generated from the following files:
LatticeGenerator.hh
LatticeGenerator.cc