Sprint: Bliss::CorpusDescriptionParser Class Reference
Bliss::CorpusDescriptionParser Class Reference
Parser for Bliss corpus description files.
#include <CorpusParser.hh>
Public Member Functions
CorpusDescriptionParser (const Core::Configuration &)
int accept (const std::string &filename, CorpusVisitor *)
Public Member Functions inherited from Core::XmlSchemaParser
virtual XmlSchemaParser * parser ()
Public Member Functions inherited from Core::XmlParser
Location location () const
void warnAboutUnexpectedElement (const char *element, const char *context)
Issue a warning about an unexpected element.
XmlParser (const Configuration &)
int parseString (const char *str)
Parse a character string.
int parseStream (std::istream &i, const std::string &filename="from stream")
Parse a stream.
int parseFile (const char *filename)
Parse a file.
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Core::XmlDocumentElement
virtual void start (const XmlAttributes atts)
Handle start of the current XML element.
virtual void end ()
Handle end of the current XML element.
virtual XmlElement * element (const char *name)
Determine the state to be entered for a nested XML element.
const XmlElement * root () const
XmlDocumentElement (XmlElement *_root=0)
Public Member Functions inherited from Core::XmlParentElement
XmlParentElement (const char *_name, XmlContext *_context)
void flattenUnknownElements ()
void ignoreUnknownElements ()
Public Member Functions inherited from Core::XmlElement
XmlElement (const char *_name, XmlContext *_context)
const char * name () const
XmlContext * context () const
virtual bool matches (const char *_name) const
Static Public Attributes
static const Core::ParameterString paramAudioDir
static const Core::ParameterString paramVideoDir
static const Core::ParameterBool paramCaptializeTranscriptions
static const Core::ParameterBool paramGemenizeTranscriptions
static const Core::ParameterBool paramProgress
Static Public Attributes inherited from Core::XmlParser
static const ParameterBool paramWarnAboutUnexpectedElements
Static Public Attributes inherited from Core::XmlElement
static const char * wildcard = " * "
Private Types
typedef CorpusDescriptionParser Self
Private Member Functions
const Speaker * getSpeaker (const std::string &name) const
const AcousticCondition * getCondition (const std::string &name) const
void startCorpus (const Core::XmlAttributes atts)
void endCorpus ()
void startSubcorpus (const Core::XmlAttributes atts)
void endSubcorpus ()
void include (const Core::XmlAttributes atts)
void startRecording (const Core::XmlAttributes atts)
void endRecording ()
void startSegment (const Core::XmlAttributes atts)
void endSegment ()
void defineSpeaker (std::unique_ptr< Speaker > &)
void selectDefaultSpeaker (const Core::XmlAttributes atts)
void defineSegmentSpeaker (std::unique_ptr< Speaker > &)
void selectSegmentSpeaker (const Core::XmlAttributes atts)
void defineCondition (std::unique_ptr< AcousticCondition > &)
void selectDefaultCondition (const Core::XmlAttributes atts)
void defineSegmentCondition (std::unique_ptr< AcousticCondition > &)
void selectSegmentCondition (const Core::XmlAttributes atts)
std::string processOrth (std::string const &)
void setOrth (std::string const &)
void setLeftContextOrth (std::string const &)
void setRightContextOrth (std::string const &)
void includeFile (const std::string &relativeFilename)
Include another corpus file at current (logical) position.
void initSchema ()
CorpusDescriptionParser (const Core::Configuration &, Corpus *)
Private Attributes
CorpusVisitor * corpusVisitor_
Core::ProgressIndicator * progressIndicator_
std::string corpusDir_
std::string audioDir_
std::string videoDir_
bool shallCaptializeTranscriptions_
bool shallGemenizeTranscriptions_
bool isSubParser_
Corpus * superCorpus_
Corpus * corpus_
Recording * recording_
SpeechSegment * segment_
int segmentNum_
CorpusSection * currentSection_
Additional Inherited Members
Public Types inherited from Core::XmlElement
typedef XmlElement * pointer
Public Types inherited from Core::XmlContext
typedef XmlContext Self
typedef void(Self::* StartHandler) (const XmlAttributes atts)
typedef void(Self::* EndHandler) ()
typedef void(Self::* CharactersHandler) (const char *ch, int len)
Static Public Member Functions inherited from Core::XmlContext
template<class T >
static StartHandler startHandler (void(T::*h)(const XmlAttributes atts))
template<class T >
static EndHandler endHandler (void(T::*h)())
template<class T >
static CharactersHandler charactersHandler (void(T::*h)(const char *ch, int len))
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::XmlSchemaParser
virtual void startDocument ()
virtual void endDocument ()
virtual void startElement (const char *name, const XmlAttributes atts)
virtual void endElement (const char *name)
virtual void characters (const char *ch, int len)
XmlSchemaParser (const Configuration &)
Protected Member Functions inherited from Core::XmlParser
virtual int isStandalone ()
virtual int hasInternalSubset ()
virtual int hasExternalSubset ()
virtual xmlParserInputPtr resolveEntity (const char *publicId, const char *systemId)
virtual void internalSubset (const char *name, const char *ExternalID, const char *SystemID)
virtual void externalSubset (const char *name, const char *ExternalID, const char *SystemID)
virtual xmlEntityPtr getEntity (const char *name)
virtual xmlEntityPtr getParameterEntity (const char *name)
virtual void entityDecl (const char *name, int type, const char *publicId, const char *systemId, const char *content)
virtual void notationDecl (const char *name, const char *publicId, const char *systemId)
virtual void attributeDecl (const char *elem, const char *name, int type, int def, const char *defaultValue, xmlEnumerationPtr tree)
virtual void elementDecl (const char *name, int type, xmlElementContentPtr content)
virtual void unparsedEntityDecl (const char *name, const char *publicId, const char *systemId, const char *notationName)
virtual void reference (const char *name)
virtual void cdataBlock (const char *ch, int len)
virtual void ignorableWhitespace (const char *ch, int len)
virtual void processingInstruction (const char *target, const char *data)
virtual void comment (const char *value)
int parse ()
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
void giveUp ()
Disable parsing.
Protected Member Functions inherited from Core::XmlDocumentElement
void setRoot (XmlElement *)
Protected Member Functions inherited from Core::XmlParentElement
virtual XmlElement * unexpectedElement ()
Protected Member Functions inherited from Core::XmlElement
XmlElement * collect (XmlElement *child)
Collects child elements.
Protected Attributes inherited from Core::Configurable
Configuration config
Protected Attributes inherited from Core::XmlParentElement
XmlElement * unexpectedElement_
Detailed Description
Parser for Bliss corpus description files.
This class implements parsing of the corpus description XML format described in Corpus Description Format Reference. It is normally not used directly but through CorpusDescription.
Definition at line 36 of file CorpusParser.hh.
Member Function Documentation
void CorpusDescriptionParser::includeFile (const std::string & relativeFilename) private
Include another corpus file at current (logical) position.
Parameters
relativeFilename path of the corpus file to be included. filename is resolved against the configuration and treated as a path relative to the current file.
Definition at line 326 of file CorpusParser.cc.
References Core::convertToLowerCase(), Core::convertToUpperCase(), Core::directoryName(), Core::enforceTrailingBlank(), Core::form(), Core::joinPaths(), require, and verify.
The documentation for this class was generated from the following files:
CorpusParser.hh
CorpusParser.cc