Sprint: Bliss::LemmaPronunciationAlphabet Class Reference
Bliss::LemmaPronunciationAlphabet Class Reference
Adaptor: Lexicon as FSA alphabet of lemma-pronunciations.
#include <Fsa.hh>
Public Member Functions
Fsa::LabelId index (const LemmaPronunciation *l) const
const LemmaPronunciation * lemmaPronunciation (Fsa::LabelId id) const
virtual const_iterator end () const
Returns an iterator pointing behind the last symbol.
virtual Fsa::LabelId index (const std::string &) const
Given a string representation of a symbol returns the label id.
virtual std::string symbol (Fsa::LabelId) const
Returns the string representation of a symbol.
virtual void writeXml (Core::XmlWriter &os) const
Write the alphabet to an XmlWriter.
u32 nDisambiguators () const
Fsa::LabelId disambiguator (u32) const
virtual bool isDisambiguator (Fsa::LabelId) const
Determine wether a symbol is a disambiguator (see determinize for more details on the use of disambiguators).
Public Member Functions inherited from Fsa::Alphabet
std::string specialSymbol (LabelId index) const
Retrieve a string representation of a special label id.
LabelId specialIndex (const std::string &symbol) const
Map a string representation of a special symbol to its label id.
virtual const_iterator begin () const
Returns an iterator pointing to the first symbol.
virtual LabelId next (LabelId id) const
Returns the label id of the next symbol in sequence.
virtual AlphabetTag tag (LabelId index) const
return symbol tag
virtual bool write (Core::BinaryOutputStream &o) const
Write the alphabet to BinaryOutputStream.
virtual size_t getMemoryUsed () const
Return the amount of memory used by this object.
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Private Member Functions
LemmaPronunciationAlphabet (LexiconRef l)
Private Attributes
LexiconRef lexicon_
u32 nDisambiguators_
Friends
class Lexicon
Detailed Description
Adaptor: Lexicon as FSA alphabet of lemma-pronunciations.
Definition at line 113 of file Fsa.hh.
Member Function Documentation
virtual const_iterator Bliss::LemmaPronunciationAlphabet::end () const inline virtual
Returns an iterator pointing behind the last symbol.
This usually does not need to be overloaded except for the case you need a different internal representation of the end iterator. Currently, InvalidLabelId is being used as end iterator.
Returns
a const iterator pointing to the first symbol or end()
Reimplemented from Fsa::Alphabet.
Definition at line 132 of file Fsa.hh.
References Bliss::TokenAlphabet::index(), Bliss::TokenAlphabet::isDisambiguator(), Bliss::TokenAlphabet::symbol(), and Bliss::TokenAlphabet::writeXml().
Fsa::LabelId LemmaPronunciationAlphabet::index (const std::string & symbol) const virtual
Given a string representation of a symbol returns the label id.
Parameters
symbol the string representation of a symbol
Returns
the label id of the symbol or InvalidLabelId if the string represents no valid symbol
Reimplemented from Fsa::Alphabet.
Definition at line 143 of file Bliss/Fsa.cc.
References Bliss::Pronunciation::format(), and Bliss::Lemma::pronunciations().
bool LemmaPronunciationAlphabet::isDisambiguator (Fsa::LabelId index) const virtual
Determine wether a symbol is a disambiguator (see determinize for more details on the use of disambiguators).
Parameters
index the symbol's label id
Returns
true if the symbol is a disambiguator.
Reimplemented from Fsa::Alphabet.
Definition at line 206 of file Bliss/Fsa.cc.
std::string LemmaPronunciationAlphabet::symbol (Fsa::LabelId index) const virtual
Returns the string representation of a symbol.
Parameters
index the symbol's label id
Returns
the string representation of the symbol or an empty string if there is no symbol with that label id
Implements Fsa::Alphabet.
Definition at line 175 of file Bliss/Fsa.cc.
References Bliss::Pronunciation::format(), Bliss::Lemma::name(), and verify.
void LemmaPronunciationAlphabet::writeXml (Core::XmlWriter & o) const virtual
Write the alphabet to an XmlWriter.
Parameters
o the XmlWriter
Returns
true if the operation was successfull for all symbols, false otherwise
Reimplemented from Fsa::Alphabet.
Definition at line 186 of file Bliss/Fsa.cc.
References require, and Fsa::Alphabet::writeXml().
The documentation for this class was generated from the following files:
Fsa.hh
Bliss/Fsa.cc