Sprint: Math::Matrix< T, P > Class Template Reference
Math::Matrix< T, P > Class Template Reference
Class for two-dimensional arrays.
#include <Matrix.hh>
Public Types
typedef T Type
Public Member Functions
Matrix (int n, int m)
Matrix (int n)
template<class S >
Matrix (const Matrix< S > &x)
Matrix (const Vector< T, P > &a, const Vector< T, P > &b)
Matrix (const Vector< T, P > &a, size_t n, size_t m)
template<class S >
Matrix< T > & operator= (const Matrix< S > &x)
size_t nRows () const
Vector< T, P > row (size_t row) const
size_t nColumns () const
Vector< T, P > column (size_t col) const
bool empty () const
size_t size () const
std::pair< size_t, size_t > isAlmostEqual (const Matrix< T, P > &m, T tolerance) const
void resize (size_t nRows, size_t nColumns, T init=T(0))
void resize (int i)
Set matrix dimension to i x i.
void clear ()
void fill (T x)
void addRow (const Vector< T, P > &v)
void insertRow (size_t position, const Vector< T, P > &v)
void setRow (size_t position, const Vector< T, P > &v)
void removeRow (size_t position)
void addColumn (const Vector< T, P > &v)
void insertColumn (size_t position, const Vector< T, P > &v)
void setColumn (size_t position, const Vector< T, P > &v)
void removeColumn (size_t position)
void setDiagonal (const Vector< T, P > &diagonal)
const Vector< T, P > diagonal () const
Matrix< T, P > transpose () const
T trace () const
T productTrace (const Matrix< T, P > &rs) const
T transposedProductTrace (const Matrix< T, P > &rs) const
T maxElement () const
T l2Norm () const
void squareVector (const std::vector< T > &vec)
T vvt (const Vector< T, P > &)
T columnNorm (size_t column, f64 norm)
Returns norm-th norm of column column.
void normalizeColumns (f64 norm)
Ensures that $c norm-th norm of each column is 1.
void normalizeColumnDirection ()
Ensures that first non-zero element of each column vector is positive.
void permuteColumns (const std::vector< size_t > &permutation)
Matrix operator* (const T &scalar) const
Matrix operator/ (const T &scalar) const
Vector< T, P > operator* (const Vector< T, P > &v) const
Matrix< T, P > operator* (const Matrix< T, P > &rs) const
Matrix< T, P > multiplyElementwise (const Matrix< T, P > &m) const
Matrix< T, P > operator+ (const Matrix< T, P > &) const
Matrix< T, P > & operator+= (const Matrix< T, P > &)
Matrix< T, P > operator- (const Matrix< T, P > &) const
Matrix< T, P > & operator-= (const Matrix< T, P > &)
Matrix< T, P > & operator*= (const T &)
Matrix< T, P > & operator/= (const T &v)
Vector< T, P > & operator[] (size_t i)
const Vector< T, P > & operator[] (size_t i) const
void write (Core::BinaryOutputStream &) const
void write (Core::XmlWriter &) const
void read (Core::BinaryInputStream &)
void read (std::istream &)
void print (std::ostream &=std::cout) const
void print_large (std::ostream &=std::cout) const
void print_maple (std::ostream &os=std::cout, u16 prec=3) const
void print_raw (std::ostream &os=std::cout) const
Private Attributes
size_t nRows_
size_t nColumns_
Vector< Vector< T, P >, P > elem_
Detailed Description
template<class T, class P = VectorRangeCheckOffPolicy>
class Math::Matrix< T, P >
Class for two-dimensional arrays.
Definition at line 36 of file Matrix.hh.
Member Function Documentation
template<class T , class P > T Math::Matrix< T, P >::columnNorm (size_t column, f64 norm)
Returns norm-th norm of column column.
Definition at line 369 of file Matrix.hh.
References Core::abs().
Referenced by Math::Matrix< T, P >::normalizeColumns(), Math::EigenvalueProblem::normalizeDiagonal(), and Math::Matrix< Value >::resize().
template<class T, class P> std::pair< size_t, size_t > Math::Matrix< T, P >::isAlmostEqual (const Matrix< T, P > & m, T tolerance) const
Returns
is (row, column) index of the first not-equal elements. If none,
is (nRows(), nColumns()).
Definition at line 201 of file Matrix.hh.
References Core::isAlmostEqual(), and require.
Referenced by Math::EigenvalueProblem::areEqual().
template<class T , class P > void Math::Matrix< T, P >::normalizeColumnDirection ()
Ensures that first non-zero element of each column vector is positive.
Definition at line 388 of file Matrix.hh.
References Core::abs(), and ensure.
Referenced by Math::EigenvalueProblem::finalizeEigenvaluesAndVectors(), and Math::Matrix< Value >::resize().
template<class T , class P > void Math::Matrix< T, P >::normalizeColumns (f64 norm)
Ensures that $c norm-th norm of each column is 1.
Definition at line 377 of file Matrix.hh.
References Math::Matrix< T, P >::columnNorm().
Referenced by Math::EigenvalueProblem::finalizeEigenvaluesAndVectors(), and Math::Matrix< Value >::resize().
template<class T, class P = VectorRangeCheckOffPolicy> void Math::Matrix< T, P >::resize (int i) inline
Set matrix dimension to i x i.
Definition at line 95 of file Matrix.hh.
The documentation for this class was generated from the following file:
Matrix.hh