Sprint: Flf::TopologicalOrderLattice::TopologicalOrderBoundaries Class Reference
Flf::TopologicalOrderLattice::TopologicalOrderBoundaries Class Reference
Public Member Functions
TopologicalOrderBoundaries (ConstBoundariesRef boundaries, ConstStateMapRef topologicalSort)
bool valid () const
false, if the lattice provides no boundaries
bool valid (Fsa::StateId sid) const
false, if that specific boundary does not exist or is invalid, e.g.
const Boundary & get (Fsa::StateId sid) const
return a specific boundary; for every sid a boundary is returned !valid(sid) => !get(sid).valid()
Public Member Functions inherited from Flf::Boundaries
Speech::TimeframeIndex time (Fsa::StateId sid) const
undefined, if !valid(sid)
Boundary::Transit transit (Fsa::StateId sid) const
undefined, if !valid(sid)
void dumpBoundary (Fsa::StateId sid, std::ostream &os) const
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Private Attributes
ConstBoundariesRef boundaries_
ConstStateMapRef topologicalSort_
Detailed Description
Definition at line 426 of file Flf/FlfCore/Basic.cc.
Member Function Documentation
const Boundary& Flf::TopologicalOrderLattice::TopologicalOrderBoundaries::get (Fsa::StateId sid) const inline virtual
return a specific boundary; for every sid a boundary is returned !valid(sid) => !get(sid).valid()
Implements Flf::Boundaries.
Definition at line 440 of file Flf/FlfCore/Basic.cc.
References Core::form(), Core::Ref< T >::get(), Flf::sortTopologically(), and verify.
bool Flf::TopologicalOrderLattice::TopologicalOrderBoundaries::valid () const inline virtual
false, if the lattice provides no boundaries
Implements Flf::Boundaries.
Definition at line 434 of file Flf/FlfCore/Basic.cc.
bool Flf::TopologicalOrderLattice::TopologicalOrderBoundaries::valid (Fsa::StateId sid) const inline virtual
false, if that specific boundary does not exist or is invalid, e.g.
not set !valid() => !valid(sid) for all state id
Implements Flf::Boundaries.
Definition at line 437 of file Flf/FlfCore/Basic.cc.
The documentation for this class was generated from the following file:
Flf/FlfCore/Basic.cc