Sprint: Core::FileArchive Class Reference
Core::FileArchive Class Reference
Classes
class _const_iterator
struct FileInfo
Public Member Functions
FileArchive (const Configuration &config, const std::string &path="", AccessMode access=AccessModeReadWrite)
virtual const_iterator files () const
virtual bool clear ()
Resets the complete archive.
virtual bool recover ()
Recover broken archive.
Public Member Functions inherited from Core::Archive
const std::string & path () const
bool hasAccess (AccessMode a) const
bool hasFile (const std::string &name) const
bool readFile (const std::string &name, std::string &buffer)
bool writeFile (const std::string &name, const std::string &ufferb, bool compress=true)
bool removeFile (const std::string &name)
bool copyFile (const Archive &src, const std::string &name, const std::string &prefix=std::string())
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Protected Member Functions
virtual bool discover (const std::string &name, Sizes &sizes) const
virtual bool read (const std::string &name, std::string &b) const
virtual bool write (const std::string &name, const std::string &b, const Sizes &sizes)
virtual bool remove (const std::string &name)
Protected Member Functions inherited from Core::Archive
bool setAccess (AccessMode access)
void lock () const
void release () const
Archive (const Configuration &config, const std::string &path="", AccessMode access=AccessModeReadWrite)
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Private Member Functions
bool add (const FileInfo &)
bool readFileInfoTable ()
bool writeFileInfoTable ()
u32 getChecksum (const std::string &b) const
FileInfo * file (const std::string &name)
const FileInfo * file (const std::string &name) const
void setChanged ()
bool scanArchive ()
Static Private Member Functions
static bool test (const std::string &path)
Private Attributes
bool allowOverwrite_
BinaryStream * stream_
bool open_
bool changed_
std::streampos endOfArchive_
std::map< std::string, u32 > hashedFiles_
std::vector< FileInfo > files_
std::vector< FileInfo > emptyFiles_
Static Private Attributes
static const ParameterBool paramOverwrite
Friends
class _const_iterator
class Archive
Additional Inherited Members
Public Types inherited from Core::Archive
enum Type { TypeUnknown, TypeDirectory, TypeFile, TypeBundle }
Different types of archives handled by this class.
typedef u32 AccessMode
Different access types to archives.
typedef u32 Size
Static Public Member Functions inherited from Core::Archive
static Type test (const std::string &path)
Returns the archive type of a given filesystem object.
static Archive * create (const Configuration &config, const std::string &path="", AccessMode access=AccessModeReadWrite)
Creates and returns an archive.
Static Public Attributes inherited from Core::Archive
static const AccessMode AccessModeNone = 0
static const AccessMode AccessModeRead = 1
static const AccessMode AccessModeWrite = 2
static const AccessMode AccessModeReadWrite = 3
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Definition at line 24 of file FileArchive.hh.
Member Function Documentation
bool FileArchive::clear () virtual
Resets the complete archive.
Implements Core::Archive.
Definition at line 225 of file FileArchive.cc.
bool FileArchive::recover () virtual
Recover broken archive.
Implements Core::Archive.
Definition at line 562 of file FileArchive.cc.
References Core::Component::error(), and Core::log().
bool FileArchive::remove (const std::string & name) protected virtual
Todo:
merge empty segments
Implements Core::Archive.
Definition at line 248 of file FileArchive.cc.
References Core::Component::error(), Core::ProgressIndicator::finish(), Core::log(), Core::ProgressIndicator::notify(), require, Core::ProgressIndicator::start(), verify, and Core::Component::warning().
bool FileArchive::write (const std::string & name, const std::string & b, const Sizes & sizes) protected virtual
Todo:
improve empty block usage
Implements Core::Archive.
Definition at line 500 of file FileArchive.cc.
References Core::Component::error(), and require.
The documentation for this class was generated from the following files:
FileArchive.hh
FileArchive.cc