Sprint: Signal::LinearWarpingNode Class Reference
Signal::LinearWarpingNode Class Reference
Two piece linear warping function node.
#include <LinearWarping.hh>
Classes
struct hash
Public Types
typedef std::unordered_map< f64, Warping *, hash > WarpingCache
typedef Flow::Time Time
Public Types inherited from Flow::AbstractNode
typedef std::map< std::string, std::string > UnresolvedAttributes
Public Member Functions
LinearWarpingNode (const Core::Configuration &c)
virtual bool setParameter (const std::string &name, const std::string &value)
Set node specific parameter.
virtual bool configure ()
Performs static (independent of input data) configuration of node.
virtual Flow::PortId getInput (const std::string &name)
Ask for an input port.
Public Member Functions inherited from Signal::WarpingNode
WarpingNode (const Core::Configuration &c)
Flow::PortId getInput (const std::string &name)
Ask for an input port.
Flow::PortId getOutput (const std::string &name)
Ask for an output port.
virtual bool work (Flow::PortId p)
Processes some data.
Public Member Functions inherited from Flow::Node
Node (const Core::Configuration &c)
Public Member Functions inherited from Flow::AbstractNode
AbstractNode (const Core::Configuration &c)
virtual void Run ()
void setThreaded (bool threaded=true)
void setThreaded (const std::string &threaded)
bool isThreaded () const
virtual bool addParameter (const std::string &name, const Core::StringExpression &value)
addParameter adds a parameter to the node Constant parameters are simply delegated to setParameter, parameters dependent on network parameters are stored in parameters_.
virtual ssize_t getRemainingDataLen (PortId out)
Returns the amount of remaining data items.
void addUnresolvedParameter (const std::string &key, const std::string &value)
Functions for saving and getting unresolved parameters.
const UnresolvedAttributes & unresolvedAttributes () const
bool operator< (const AbstractNode &n) const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Member Functions
static std::string filterName ()
Static Public Attributes
static Core::ParameterFloat paramWarpingFactor
static Core::ParameterFloat paramWarpingLimit
Static Public Attributes inherited from Signal::WarpingNode
static const Core::Choice choiceMergeType
static const Core::ParameterChoice paramMergeType
static const Core::Choice choiceInterpolationType
static const Core::ParameterChoice paramInterpolationType
static const Core::ParameterBool paramInterpolateOverWarpedAxis
Static Public Attributes inherited from Flow::AbstractNode
static const Core::ParameterBool paramThreaded
static const Core::ParameterBool paramIgnoreUnknownParameters
Protected Member Functions
virtual void initWarping ()
Override this function to perform own initialization.
virtual void apply (const Flow::Vector< f32 > &in, std::vector< f32 > &out)
Override this function to perform the specific warping.
Protected Member Functions inherited from Signal::WarpingNode
void init (size_t inputSize)
void setSampleRate (f64 sampleRate)
void setMergeType (const Warping::MergeType type)
void setInterpolationType (const Warping::InterpolationType type)
void setInterpolateOverWarpedAxis (bool InterpolateOverWarpedAxis)
void setNeedInit ()
void resetNeedInit ()
bool configure (const Flow::Attributes &successorAttributes)
Performs configuration Steps: 1) Retrieves attributes of own input port.
Protected Member Functions inherited from Flow::Node
virtual PortId connectInputPort (PortId, Link *)
Connect link to input port.
virtual void disconnectInputLink (Link *)
virtual PortId connectOutputPort (PortId, Link *)
virtual void disconnectOutputLink (Link *)
PortId addInput (PortId in=IllegalPortId)
Create an input port.
PortId addInputs (u32 nPorts)
Create several input ports.
virtual PortId nInputs () const
Link * getInputLink (PortId in) const
virtual PortId inputConnected (PortId in) const
bool validInputPort (PortId in) const
PortId addOutput (PortId out=IllegalPortId)
Add an output port.
PortId addOutputs (u32 nPorts)
Create several output ports.
virtual PortId nOutputs () const
bool validOutputPort (PortId out) const
virtual u32 nOutputLinks (PortId out) const
Number of link connceted to an output port.
bool configureDatatype (Core::Ref< const Attributes > a, const Datatype *d)
template<class T >
bool getData (PortId in, DataPtr< T > &d)
Fetch data packet from input port.
virtual bool putData (PortId out, Data *d)
Send data packet on output port.
bool putEos (PortId out)
Send end-of-stream on output port.
bool putOod (PortId out)
Send out-of-data on output port.
Core::Ref< const Attributes > getInputAttributes (PortId in)
Retrieve attribute set from input port.
void getInputAttributes (PortId, Attributes &)
bool putOutputAttributes (PortId out, Core::Ref< const Attributes > a)
Put attribute set on output port.
void eraseOutputAttributes ()
Erases attributes of all output links recursively.
Protected Member Functions inherited from Flow::AbstractNode
template<class T >
bool getData (Link *l, DataPtr< T > &d)
Fetch data packet from the "from" port of link.
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Private Types
typedef WarpingNode Predecessor
Private Member Functions
void updateWarpingFactor (const Flow::Timestamp &featureTimeStamp)
void setWarpingFactor (f64 warpingFactor)
void setWarpingLimit (f64 warpingLimit)
const Warping & warping ()
Searches for warping object in the cache and creates a new one if not found.
Warping * createWarping ()
void clear ()
Removes Warping objects from the cache.
void reset ()
Private Attributes
Flow::Float64 warpingFactor_
f64 warpingLimit_
WarpingCache warpingCache_
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Attributes inherited from Signal::WarpingNode
size_t inputSize_
f64 sampleRate_
Warping::MergeType mergeType_
Warping::InterpolationType interpolationType_
bool interpolateOverWarpedAxis_
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Two piece linear warping function node.
Equal to generic warping node parmetrized for linear warping up the speed of changing warping factor. A warping function cache is used to change warping function faster. Thus different warping functions can be applied even for each time frame.
Definition at line 30 of file LinearWarping.hh.
Member Function Documentation
void LinearWarpingNode::apply (const Flow::Vector< f32 > & in, std::vector< f32 > & out) protected virtual
Override this function to perform the specific warping.
Implements Signal::WarpingNode.
Definition at line 125 of file LinearWarping.cc.
References Core::Component::criticalError(), and verify.
Referenced by initWarping().
void LinearWarpingNode::clear () private
Removes Warping objects from the cache.
Definition at line 80 of file LinearWarping.cc.
Referenced by initWarping().
bool LinearWarpingNode::configure () virtual
Performs static (independent of input data) configuration of node.
Configure is called if one of the output attributes is not available. Override this function to evaluate all input attributes and pass them on to successor nodes. The default implementation simply forwards the merged attributes from all input links to all outputs. Note: -we assume no dead inputs here. -This function is the safest point to reset the algorithms used by the node. The alternative would be to reset the algorithms when a non-data object has been recieved. This solution can lead easily to unintended behaviour, since it is not garatinteed at all that every node receives for example a EOS object!
Reimplemented from Flow::Node.
Definition at line 110 of file LinearWarping.cc.
Referenced by initWarping().
Flow::PortId LinearWarpingNode::getInput (const std::string &) virtual
Ask for an input port.
Implement this function to provide a mapping form names to port IDs. Consider using a Core::Choice. Remeber to create ports using addInput().
Returns
a valid port ID or IllegalPortId if there is to such port.
Reimplemented from Flow::Node.
Definition at line 92 of file LinearWarping.cc.
Referenced by initWarping().
virtual void Signal::LinearWarpingNode::initWarping () inline protected virtual
Override this function to perform own initialization.
Reimplemented from Signal::WarpingNode.
Definition at line 66 of file LinearWarping.hh.
References apply(), clear(), configure(), getInput(), and setParameter().
bool LinearWarpingNode::setParameter (const std::string & name, const std::string & value) virtual
Set node specific parameter.
Implement this template function to handle parameters specific to your Node.
Parameters
name name of parameter
value new value for the parameter
Returns
true if successful, false if parameter name is not understood.
Reimplemented from Signal::WarpingNode.
Definition at line 100 of file LinearWarping.cc.
Referenced by initWarping().
const Warping & LinearWarpingNode::warping () private
Searches for warping object in the cache and creates a new one if not found.
Definition at line 50 of file LinearWarping.cc.
References Math::AnalyticFunctionFactory::createTwoPieceLinearFunction(), Math::AnalyticFunctionFactory::discreteDomain, ensure, Core::Component::error(), Core::Component::respondToDelayedErrors(), Signal::Warping::setInverseWarpingFunction(), and Signal::Warping::setWarpingFunction().
The documentation for this class was generated from the following files:
LinearWarping.hh
LinearWarping.cc