Sprint: Core::Channel Class Reference
Core::Channel Class Reference
Configurable text output stream.
#include <Channel.hh>
Classes
class Dispatcher
class Manager
Central management of channel output.
class Target
Public Types
enum TargetType { plainTarget, xmlTarget }
enum Default { disabled, standard, error }
Public Member Functions
Channel (const Configuration &, const std::string &name, Default defaultTarget=disabled, TargetType __type=plainTarget)
bool isOpen () const
Test whether channel output is actually used.
Static Public Attributes
static const Core::ParameterString paramTargets
Private Attributes
bool isOpen_
Detailed Description
Configurable text output stream.
See also
Channels
Definition at line 107 of file Channel.hh.
Constructor & Destructor Documentation
Core::Channel::Channel (const Configuration & c, const std::string & name, Default defaultTarget = disabled, TargetType __type = plainTarget)
Todo:
should prevent deletion in destructor.
Definition at line 407 of file Channel.cc.
References defect, and Core::Channel::Manager::us().
Member Function Documentation
bool Core::Channel::isOpen () const inline
Test whether channel output is actually used.
Definition at line 127 of file Channel.hh.
Referenced by Search::LanguageModelLookahead::buildCompressesLookaheadStructure(), AdvancedTreeSearch::LanguageModelLookahead::buildCompressesLookaheadStructure(), Flf::DumpPosteriorCnNode::finalize(), Flf::DumpConfusionNetworkNode::finalize(), ArchiverApplication::getUsage(), Flf::DumpPosteriorCnNode::init(), Flf::DumpTracebackNode::init(), Flf::DumpConfusionNetworkNode::init(), Flf::ConcatenateNode::init_(), Lm::BackingOffLm::initialize(), CartTrainer::main(), AllophoneTool::main(), CartViewer::main(), and Search::Wfst::Builder::ConvertStateSequences::process().
The documentation for this class was generated from the following files:
Channel.hh
Channel.cc