Sprint: Flf::RoverCombination Class Reference
Flf::RoverCombination Class Reference
Classes
class NistScliteCost
class NistScliteTimeMediatedCost
D(correct) = | T1(ref) - T1(hyp) | + | T2(ref) - T2(hyp) | D(insertion) = T2(hyp) - T1(hyp) D(deletion) = T2(ref) - T1(ref) D(substitution) = | T1(ref) - T1(hyp) | + | T2(ref) - T2(hyp) | + 0.001 Distance for an Insertion or Deletion of the NULL Token '@' = 0.001.
class NistScliteWordCost
Description of the cost structure: 0 -> Correct 0.001 -> Insertion, deletion of '@' (a NULL) 1 -> Substitution of '@' for '@' 3 -> Deletion or insertion 4 -> Substitution.
Public Types
typedef Core::Ref< NistScliteCost > NistScliteCostRef
Public Types inherited from Flf::ConfusionNetworkAlignment
typedef Core::Ref< const Cost > ConstCostRef
typedef std::vector< std::pair< u32, u32 > > Alignment
typedef Alignment::const_reverse_iterator const_iterator
Public Member Functions
void dump (std::ostream &os) const
ConstConfusionNetworkRef combine (const ConstConfusionNetworkRefList &cns, ConfusionNetworkAlignmentPtrList *alignments=0) const
ConstConfusionNetworkRef combine (const ConstLatticeRefList &lats, ConfusionNetworkAlignmentPtrList *alignments=0) const
Public Member Functions inherited from Flf::ConfusionNetworkAlignment
ConfusionNetworkAlignment (ConstCostRef costFcn, u32 minBeamWidth)
void dump (std::ostream &os) const
ConstCostRef cost ()
u32 beamWidth () const
const_iterator begin () const
const_iterator end () const
Score align (const ConfusionNetwork &ref, const ConfusionNetwork &hyp) const
Levenshtein alignment with fixed beam around main diagonal.
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Static Public Member Functions
static ConstRoverCombinationRef create (WeightedPosteriorCombinationHelperRef weightedCombo, NistScliteCostRef scliteCostFcn, Score nullConfidence, Score alpha, bool removeEps, u32 minBeamWidth)
Private Types
typedef ConfusionNetworkAlignment Precursor
Private Member Functions
void init (ConfusionNetwork *combinedCn, std::vector< ScoreList > &confidences, ConstConfusionNetworkRef cn) const
Build CN by merging the aligned slots.
void add (const ConfusionNetworkAlignment &alignment, ConfusionNetwork *combinedCn, std::vector< ScoreList > &confidences, ConstConfusionNetworkRef cn, u32 i) const
void calcScores (ConfusionNetwork *combinedCn, const std::vector< ScoreList > &confidences) const
ConstConfusionNetworkRef _combine (const ConstConfusionNetworkRefList &cns, ConfusionNetworkAlignmentPtrList *alignments=0) const
RoverCombination (WeightedPosteriorCombinationHelperRef weightedCombo, NistScliteCostRef scliteCostFcn, Score nullConfidence, Score alpha, bool removeEps, u32 minBeamWidth)
Private Attributes
WeightedPosteriorCombinationHelperRef weightedCombo_
NistScliteCostRef scliteCostFcn_
Score nullConfidence_
Score alpha_
bool removeEps_
std::vector< ScoreList > confidences_
Detailed Description
Definition at line 1016 of file ConfusionNetworkCombination.cc.
Member Function Documentation
void Flf::RoverCombination::init (ConfusionNetwork * combinedCn, std::vector< ScoreList > & confidences, ConstConfusionNetworkRef cn) const inline private
Build CN by merging the aligned slots.
Definition at line 1298 of file ConfusionNetworkCombination.cc.
References Flf::ConfusionNetworkAlignment::align(), Core::Ref< T >::get(), Flf::sausageLattice2cn(), Core::Application::us(), verify, and Core::Component::warning().
The documentation for this class was generated from the following file:
ConfusionNetworkCombination.cc