Sprint: Signal::RealInverseFastFourierTransform Class Reference
Signal::RealInverseFastFourierTransform Class Reference
RealInverseFastFourierTransform: performs inverse fourier transform of real vector Algorithm taken from "Numerical Recepies in C++" Input: N / 2 + 1 complex values real and imaginary part alternating; Output N real values; where N is number of FFT points.
#include <FastFourierTransform.hh>
Public Member Functions
RealInverseFastFourierTransform (u32 length=0, Data sampleRate=1)
virtual u32 maximalInputSize () const
virtual void setInputSize (u32 inputSize)
Sets the number of FFT points necesseary for transforming an input of length.
virtual u32 outputSize () const
Public Member Functions inherited from Signal::FastFourierTransform
FastFourierTransform (u32 length=0, Data sampleRate=1)
virtual bool transform (std::vector< Data > &data)
u32 length () const
u32 setLength (u32 length)
sets the number of FFT points (length_) as the -smallest number which is -power of 2 -larger than
void setInputSampleRate (f64 sampleRate)
Sample-rate of input vector.
f64 outputSampleRate () const
Sample-rate of output vector.
const std::string & lastError () const
Returns the description of the last error.
Static Public Member Functions
static std::string name ()
Protected Member Functions
bool pack (std::vector< f32 > &data)
virtual bool applyAlgorithm (std::vector< Data > &data)
virtual bool estimateContinuous (std::vector< Data > &data)
Calculates an estimation of the continuous values.
Protected Member Functions inherited from Signal::FastFourierTransform
virtual bool zeroPadding (std::vector< Data > &data)
Private Types
typedef FastFourierTransform Predecessor
Additional Inherited Members
Public Types inherited from Signal::FastFourierTransform
typedef f32 Data
Protected Attributes inherited from Signal::FastFourierTransform
u32 length_
f64 sampleRate_
sample rate of input vector.
Math::FastFourierTransform fft_
std::string lastError_
Detailed Description
RealInverseFastFourierTransform: performs inverse fourier transform of real vector Algorithm taken from "Numerical Recepies in C++" Input: N / 2 + 1 complex values real and imaginary part alternating; Output N real values; where N is number of FFT points.
Definition at line 183 of file Signal/FastFourierTransform.hh.
Member Function Documentation
bool RealInverseFastFourierTransform::estimateContinuous (std::vector< Data > & data) protected virtual
Calculates an estimation of the continuous values.
Each element is multiplied by { t} resp. { }.
Reimplemented from Signal::FastFourierTransform.
Definition at line 108 of file Signal/FastFourierTransform.cc.
virtual u32 Signal::RealInverseFastFourierTransform::maximalInputSize () const inline virtual
Returns
maximum input size for the number of FFT points.
Implements Signal::FastFourierTransform.
Definition at line 199 of file Signal/FastFourierTransform.hh.
References Signal::FastFourierTransform::length().
virtual void Signal::RealInverseFastFourierTransform::setInputSize (u32 inputSize) inline virtual
Sets the number of FFT points necesseary for transforming an input of length.
Parameters
inputSize.
Implements Signal::FastFourierTransform.
Definition at line 202 of file Signal/FastFourierTransform.hh.
References Signal::FastFourierTransform::length(), and Signal::FastFourierTransform::setLength().
The documentation for this class was generated from the following files:
Signal/FastFourierTransform.hh
Signal/FastFourierTransform.cc