Sprint: AdvancedTreeSearch::AcousticLookAhead::AcousticLookAheadModel Class Reference
AdvancedTreeSearch::AcousticLookAhead::AcousticLookAheadModel Class Reference
Public Member Functions
AcousticLookAheadModel (const AcousticFeatureVector &mean=AcousticFeatureVector())
AcousticLookAheadModel (Core::MappedArchiveReader reader)
Score distance (const AcousticFeatureVector &mean) const
u32 dimension () const
void split (const AcousticLookAheadModel &other)
void estimate (const std::vector< u32 > &assigned, const std::vector< AcousticFeatureVector > &means, u32 splits)
void write (Core::MappedArchiveWriter writer)
Public Attributes
std::vector< AcousticFeatureVector > means_
Detailed Description
Definition at line 296 of file AcousticLookAhead.hh.
Member Function Documentation
void AcousticLookAhead::AcousticLookAheadModel::estimate (const std::vector< u32 > & assigned, const std::vector< AcousticFeatureVector > & means, u32 splits)
Step 1: Split all means
Step 2: Assign every observation to the closest mean
Step 3: Accumulate means
Definition at line 289 of file AcousticLookAhead.cc.
References Core::MappedArchiveReader::check(), Core::Application::getCacheArchiveReader(), Core::Application::getCacheArchiveWriter(), Core::MappedArchiveReader::good(), Core::Application::us(), and verify.
The documentation for this class was generated from the following files:
AcousticLookAhead.hh
AcousticLookAhead.cc