Sprint: Speech::Feature Class Reference
Speech::Feature Class Reference
Interface conversion between Flow::VectorPointer<...> and Mm::Feature.
#include <Feature.hh>
Public Types
typedef Flow::Vector< Mm::FeatureType > FlowVector
typedef Flow::TypedAggregate< FlowVector > FlowFeature
Public Types inherited from Mm::Feature
typedef std::vector< Core::Ref< const Vector > >::const_iterator Iterator
Public Member Functions
Feature (Flow::DataPtr< FlowVector > &v)
Feature (Flow::DataPtr< FlowFeature > &f)
void take (Flow::DataPtr< FlowVector > &v)
Converts the content of.
void take (Flow::DataPtr< FlowFeature > &f)
Converts the content of.
bool take (Flow::DataPtr< Flow::Timestamp > &t)
Converts the content of.
void setTimestamp (const Flow::Timestamp &t)
const Flow::Timestamp & timestamp () const
virtual Mm::FeatureDescription * getDescription (const Core::Configurable &parent) const
Public Member Functions inherited from Mm::Feature
Feature (size_t nStreams=0)
Creates an empty feature with.
Feature (const Core::Ref< const Vector > &f)
Creates a feature with a single stream containing the feature vector.
Feature (const FeatureVector &f)
Creates a feature with a single stream containing the feature vector.
size_t add (const Core::Ref< const Vector > &v)
Creates a new stream with.
void add (size_t newIndex, const Core::Ref< const Vector > &v)
Creates a new stream at index.
void set (size_t streamIndex, const Core::Ref< const Vector > &v)
Changes value of the stream at index.
void set (const std::vector< size_t > &indices, const Core::Ref< const Vector > &v)
Changes value of the stream at indices.
void clear ()
bool operator== (const Feature &r) const
Core::Ref< const Vector > operator[] (size_t streamIndex) const
Core::Ref< const Vector > mainStream () const
Main stream is used in application working only with one stream.
Iterator begin () const
Iterator end () const
void setNumberOfStreams (size_t nStreams)
size_t nStreams () const
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Private Types
typedef Feature Self
typedef Mm::Feature Precursor
Static Private Member Functions
static Core::Ref< const Vector > convert (Flow::DataPtr< FlowVector > &)
Private Attributes
Flow::Timestamp timestamp_
Remark: Flow::Data part of this data structure is superflouos.
Additional Inherited Members
Static Public Member Functions inherited from Mm::Feature
static Core::Ref< const Vector > convert (const FeatureVector &f)
Detailed Description
Interface conversion between Flow::VectorPointer<...> and Mm::Feature.
Although, Flow::VectorPointer<...> can be accessed by Core::TsRef<...> even outside of Flow, Feature copies the elements of Flow::VectorPointer<...> into an Mm::Feature object. Advantage is that Mm::Feature is not multithread safe thus it can be accessed by the light-weight Core::Ref.
See also
Flow::TypedAggregate for more comments.
Definition at line 30 of file Speech/Feature.hh.
Member Function Documentation
void Feature::take (Flow::DataPtr< FlowVector > & v)
Converts the content of.
Parameters
v. Note: content of v gets destroyed (
See also
convert(..)).
Definition at line 27 of file Speech/Feature.cc.
References Mm::Feature::add().
Referenced by Speech::DataSource::convert(), and take().
void Feature::take (Flow::DataPtr< FlowFeature > & f)
Converts the content of.
Parameters
f. Note: content of f gets destroyed (
See also
convert(..)).
Definition at line 35 of file Speech/Feature.cc.
References Mm::Feature::add().
bool Feature::take (Flow::DataPtr< Flow::Timestamp > & t)
Converts the content of.
Parameters
t. Note: content of t gets destroyed (
See also
convert(...)).
Returns
is false if elements of
Parameters
t could not be converted.
Definition at line 51 of file Speech/Feature.cc.
References Core::TsRef< T >::reset(), and take().
Member Data Documentation
Flow::Timestamp Speech::Feature::timestamp_ private
Remark: Flow::Data part of this data structure is superflouos.
Redesign of Flow::Timestamp could solve this problem.
Definition at line 42 of file Speech/Feature.hh.
The documentation for this class was generated from the following files:
Speech/Feature.hh
Speech/Feature.cc