Sprint: Fsa::StaticAlphabet Class Reference
Fsa::StaticAlphabet Class Reference
The implementation of a statically allocated alphabet.
#include <Alphabet.hh>
Classes
struct Symbol
Public Member Functions
void clear ()
Clears the whole alphabet.
LabelId addSymbol (const std::string &symbol, AlphabetTag tag=0)
Adds a symbol to the alphabet.
bool addIndexedSymbol (const std::string &symbol, LabelId index, AlphabetTag tag=0)
Adds a symbol to the alphabet together with an already known, associated index.
virtual const_iterator begin () const
Returns an iterator pointing to the first symbol.
virtual const_iterator end () const
Returns an iterator pointing behind the last symbol.
virtual LabelId next (LabelId id) const
Returns the label id of the next symbol in sequence.
virtual bool hasIndex (LabelId index) const
virtual std::string symbol (LabelId index) const
Returns the string representation of a symbol.
virtual LabelId index (const std::string &symbol) const
Given a string representation of a symbol returns the label id.
virtual bool isDisambiguator (LabelId index) const
Determine wether a symbol is a disambiguator (see determinize for more details on the use of disambiguators).
virtual AlphabetTag tag (LabelId index) const
return symbol tag
virtual bool read (Core::BinaryInputStream &i)
virtual size_t getMemoryUsed () const
Return the amount of memory used by this object.
Public Member Functions inherited from Fsa::Alphabet
std::string specialSymbol (LabelId index) const
Retrieve a string representation of a special label id.
LabelId specialIndex (const std::string &symbol) const
Map a string representation of a special symbol to its label id.
virtual bool write (Core::BinaryOutputStream &o) const
Write the alphabet to BinaryOutputStream.
virtual void writeXml (Core::XmlWriter &o) const
Write the alphabet to an XmlWriter.
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Private Attributes
Core::Vector< Symbol > symbols_
std::unordered_map< std::string, LabelId, Core::StringHash > indices_
Detailed Description
The implementation of a statically allocated alphabet.
All methods are overloaded appropriately. Static alphabets are used automatically when reading automata from disk.
Definition at line 213 of file Alphabet.hh.
Member Function Documentation
bool Fsa::StaticAlphabet::addIndexedSymbol (const std::string & symbol, LabelId index, AlphabetTag tag = 0)
Adds a symbol to the alphabet together with an already known, associated index.
Parameters
symbol the symbol
index the associated index
isDisambiguator mark this symbol as a disambiguator (see determinize for more information on disambiguation symbols)
Returns
false if the string was not a valid symbol or the index was already assigned to a different symbol
Definition at line 115 of file Alphabet.cc.
References Fsa::Alphabet::index(), Fsa::Alphabet::symbol(), and Fsa::Alphabet::tag().
Referenced by OpenFst::convertAlphabet(), and Fsa::staticCopy().
LabelId Fsa::StaticAlphabet::addSymbol (const std::string & symbol, AlphabetTag tag = 0)
Adds a symbol to the alphabet.
Parameters
symbol the symbol
isDisambiguator mark this symbol as a disambiguator (see determinize for more information on disambiguation symbols)
Returns
the index of the newly added symbol or InvalidLabelId if the string was not a valid symbol
Definition at line 103 of file Alphabet.cc.
References Fsa::Alphabet::index(), and Fsa::Alphabet::symbol().
Referenced by Translation::ConditionalLexiconPlain::addValue(), Ftl::CopyDfsState< _Automaton >::discoverState(), Translation::ConditionalLexiconSri::read(), Translation::ConditionalLexiconPlain::read(), and Ftl::ConcatUnionAutomaton< _Automaton >::uniteAlphabets().
Alphabet::const_iterator Fsa::StaticAlphabet::begin () const virtual
Returns an iterator pointing to the first symbol.
Note, that if the alphabet contains a hole in the space of label ids at the beginning the iterator must be winded to the first existing symbol.
Returns
a const iterator pointing to the first symbol or end()
Reimplemented from Fsa::Alphabet.
Definition at line 137 of file Alphabet.cc.
void Fsa::StaticAlphabet::clear ()
Clears the whole alphabet.
Resets it to a state right after initialization.
Definition at line 94 of file Alphabet.cc.
virtual const_iterator Fsa::StaticAlphabet::end () const inline virtual
Returns an iterator pointing behind the last symbol.
This usually does not need to be overloaded except for the case you need a different internal representation of the end iterator. Currently, InvalidLabelId is being used as end iterator.
Returns
a const iterator pointing to the first symbol or end()
Reimplemented from Fsa::Alphabet.
Definition at line 262 of file Alphabet.hh.
References Fsa::Alphabet::getMemoryUsed(), Fsa::Alphabet::index(), Fsa::Alphabet::isDisambiguator(), Fsa::Alphabet::next(), Fsa::staticCopy(), Fsa::Alphabet::symbol(), and Fsa::Alphabet::tag().
size_t Fsa::StaticAlphabet::getMemoryUsed () const virtual
Return the amount of memory used by this object.
Returns
the amount of memory in bytes
Reimplemented from Fsa::Alphabet.
Definition at line 241 of file Alphabet.cc.
LabelId Fsa::StaticAlphabet::index (const std::string & symbol) const virtual
Given a string representation of a symbol returns the label id.
Parameters
symbol the string representation of a symbol
Returns
the label id of the symbol or InvalidLabelId if the string represents no valid symbol
Reimplemented from Fsa::Alphabet.
Definition at line 187 of file Alphabet.cc.
Referenced by Translation::ConditionalLexiconPlain::getProb().
bool Fsa::StaticAlphabet::isDisambiguator (LabelId index) const virtual
Determine wether a symbol is a disambiguator (see determinize for more details on the use of disambiguators).
Parameters
index the symbol's label id
Returns
true if the symbol is a disambiguator.
Reimplemented from Fsa::Alphabet.
Definition at line 195 of file Alphabet.cc.
References Fsa::Alphabet::index().
LabelId Fsa::StaticAlphabet::next (LabelId id) const virtual
Returns the label id of the next symbol in sequence.
Users can savely assume that holes in the space of label ids are being skipped automatically.
Parameters
id the current symbol
Returns
the label id of the next symbol
Reimplemented from Fsa::Alphabet.
Definition at line 144 of file Alphabet.cc.
References Fsa::Alphabet::index().
std::string Fsa::StaticAlphabet::symbol (LabelId index) const virtual
Returns the string representation of a symbol.
Parameters
index the symbol's label id
Returns
the string representation of the symbol or an empty string if there is no symbol with that label id
Implements Fsa::Alphabet.
Definition at line 168 of file Alphabet.cc.
References Core::form(), and Fsa::Alphabet::index().
Referenced by Translation::ConditionalLexiconPlain::write().
AlphabetTag Fsa::StaticAlphabet::tag (LabelId index) const virtual
return symbol tag
Parameters
index the symbol's label id
Returns
symbol's tag
Reimplemented from Fsa::Alphabet.
Definition at line 200 of file Alphabet.cc.
References Fsa::Alphabet::index(), Fsa::Alphabet::symbol(), and Fsa::Alphabet::tag().
The documentation for this class was generated from the following files:
Alphabet.hh
Alphabet.cc