Sprint: Mm::MixtureToMixtureMap Class Reference
Mm::MixtureToMixtureMap Class Reference
defines a mixture-to-mixture id mapping based on a mapping file
#include <AbstractMixtureSetEstimator.hh>
Public Types
typedef std::unordered_set< MixtureIndex > MixtureSet
typedef std::vector< MixtureSet > MixtureMap
Public Member Functions
MixtureSet & mixtureSet (size_t m)
virtual bool load (const std::string &filename)
loads a white-space separated mixture-to-mixture id mapping file
virtual bool save (const std::string &filename) const
u32 nMixtures () const
u32 nMappedMixtures () const
Protected Attributes
u32 nOfMappedMixtures_
Detailed Description
defines a mixture-to-mixture id mapping based on a mapping file
Definition at line 213 of file AbstractMixtureSetEstimator.hh.
Member Function Documentation
bool MixtureToMixtureMap::load (const std::string & filename) virtual
loads a white-space separated mixture-to-mixture id mapping file
Definition at line 753 of file AbstractMixtureSetEstimator.cc.
References Core::getline(), Core::Component::log(), Core::split(), Core::Application::us(), and verify.
The documentation for this class was generated from the following files:
AbstractMixtureSetEstimator.hh
AbstractMixtureSetEstimator.cc