Sprint: Mm::Module_ Class Reference
Mm::Module_ Class Reference
Public Types
enum FeatureScorerType {
batchFloatDiagonalMaximum, batchPreselectionFloatDiagonalMaximum, batchPreselectionIntDiagonalMaximum, batchIntDiagonalMaximum,
batchIntDiagonalMaximumFast, diagonalMaximum, diagonalMaximumL1, laplaceDiagonalMaximum,
diagonalMaximumClipped, simdDiagonalMaximum, preselectionSimdDiagonalMaximum, diagonalMaximumWeightedFeature,
diagonalSum, fastFloatLogLinear, logLinear, simdLogLinear,
nearestNeighbor, statePosterior, passThrough, hybridPassThrough,
invalidFeatureScorer
}
enum CovarianceTyingType { noCovarianceTying, pooledCovariance, mixtureSpecificCovariance }
enum EstimatorType {
maximumLikelihood, discriminative, legacyDiscriminativeWithISmoothing, discriminativeWithISmoothing,
rPropDiscriminative, rPropDiscriminativeWithISmoothing
}
Public Member Functions
Core::Ref< MixtureSet > createMixtureSet (const Core::Configuration &, size_t nMixtures, size_t dimension, size_t nDensitiesPerMixture=1) const
Creates an empty mixture set with.
Core::Ref< MixtureSet > createMixtureSet (CovarianceTyingType covarianceTying, size_t nMixtures, size_t dimension, size_t nDensitiesPerMixture=1) const
Creates an empty mixture set with.
Core::Ref< MixtureSet > createEmptyMixtureSet (const Core::Configuration &) const
create an empty mixture set.
Core::Ref< MixtureSet > readMixtureSet (const std::string &file, const Core::Configuration &c) const
Loads a MixtureSet object from the file.
Core::Ref< MixtureSet > readMixtureSet (const Core::Configuration &c) const
Loads a MixtureSet object from the file given in.
void convertMixtureSet (const Core::Configuration &) const
Core::Ref< AbstractMixtureSet > readAbstractMixtureSet (const Core::Configuration &configuration) const
Load mixture set from the file given in.
Core::Ref< AbstractMixtureSet > readAbstractMixtureSet (const std::string &filename, const Core::Configuration &configuration) const
Load mixture set from file.
bool writeMixtureSet (const std::string &filename, const AbstractMixtureSet &ms, u32 precision=6) const
AbstractMixtureSetEstimator * createMixtureSetEstimator (const Core::Configuration &) const
Creates an empty mixture set estimator.
AbstractMixtureSetEstimator * createMixtureSetEstimator (const Core::Configuration &, size_t nMixtures, size_t dimension, size_t nDensitiesPerMixture=1) const
Creates an empty mixture set estimator with.
bool readMixtureSetEstimator (const std::string &filename, AbstractMixtureSetEstimator &)
Read a MixtureSetEstimator object from file.
bool writeMixtureSetEstimator (const std::string &filename, AbstractMixtureSetEstimator &)
Saves a MixtureSetEstimator object in the file.
Core::Ref< FeatureScorer > createFeatureScorer (const Core::Configuration &c, const Core::Ref< const AbstractMixtureSet > m) const
Creates and initializes a FeatureScorer as configured.
Core::Ref< AssigningFeatureScorer > createAssigningFeatureScorer (const Core::Configuration &, const Core::Ref< const AbstractMixtureSet >) const
Creates and initializes an AssigningFeatureScorer as configured.
Core::Ref< FeatureScorer > createFeatureScorer (const Core::Configuration &c) const
Loads a mixture set and creates and initializes a FeatureScorer with it, as configured.
Core::Ref< ScaledFeatureScorer > createScaledFeatureScorer (const Core::Configuration &c, Core::Ref< FeatureScorer > featureScorer) const
Creates a ScaledFeatureScorer by wraping.
Core::Ref< ScaledFeatureScorer > createScaledFeatureScorer (const Core::Configuration &c, const Core::Ref< Mm::AbstractMixtureSet > m) const
Creates and initializes a ScaledFeatureScorer as configured.
Core::Ref< ScaledFeatureScorer > createScaledFeatureScorer (const Core::Configuration &c) const
Loads a mixture set and creates and initializes a ScaledFeatureScorer with it, as configured.
Core::FormatSet & formats ()
Set of file format class.
FeatureScorerFactory * featureScorerFactory () const
Public Attributes
Core::ParameterChoice paramFeatureScorerType
Static Public Attributes
static const Core::ParameterString paramMixtureSetFilename
static const Core::ParameterString paramNewMixtureSetFilename
static const Core::ParameterInt paramReducedMixtureSetDimension
static const Core::ParameterInt paramReducedMixtureSetDimensionOffset
static const Core::ParameterInt paramMixtureSetDimension
static const Core::Choice choiceCovarianceTyingType
static const Core::ParameterChoice paramCovarianceTyingType
static const Core::Choice choiceEstimatorType
static const Core::ParameterChoice paramEstimatorType
Private Attributes
Core::FormatSet * formats_
FeatureScorerFactory * featureScorerFactory_
Detailed Description
Definition at line 39 of file Mm/Module.hh.
Member Function Documentation
void Mm::Module_::convertMixtureSet (const Core::Configuration & configuration) const
Todo:
this function needs some cleanup!
Definition at line 199 of file Mm/Module.cc.
References Core::Ref< T >::get(), Core::Component::log(), Core::Application::us(), and verify.
Core::Ref< AssigningFeatureScorer > Mm::Module_::createAssigningFeatureScorer (const Core::Configuration & c, const Core::Ref< const AbstractMixtureSet > m) const
Creates and initializes an AssigningFeatureScorer as configured.
Returns
a newly created instance of AssigningFeatureScorer or 0 if an error occured.
Definition at line 311 of file Mm/Module.cc.
References ensure, and Core::Ref< T >::reset().
Core::Ref< MixtureSet > Mm::Module_::createEmptyMixtureSet (const Core::Configuration & configuration) const
create an empty mixture set.
uses paramMixtureSetDimension
Definition at line 148 of file Mm/Module.cc.
Core::Ref< FeatureScorer > Mm::Module_::createFeatureScorer (const Core::Configuration & c, const Core::Ref< const AbstractMixtureSet > m) const
Creates and initializes a FeatureScorer as configured.
Returns
a newly created instance of FeatureScorer or 0 if an error occured.
Definition at line 301 of file Mm/Module.cc.
References Core::Component::criticalError(), and Core::Application::us().
Core::Ref< FeatureScorer > Mm::Module_::createFeatureScorer (const Core::Configuration & c) const
Loads a mixture set and creates and initializes a FeatureScorer with it, as configured.
Returns
a newly created instance of FeatureScorer or 0 if an error occured.
Definition at line 321 of file Mm/Module.cc.
Core::Ref< MixtureSet > Mm::Module_::createMixtureSet (const Core::Configuration & configuration, size_t nMixtures, size_t dimension, size_t nDensitiesPerMixture = 1) const
Creates an empty mixture set with.
Parameters
nMixtures of
dimension. type of covariance tying is given in
Configuration (paramCovarianceTyingType)
Definition at line 115 of file Mm/Module.cc.
Core::Ref< MixtureSet > Mm::Module_::createMixtureSet (CovarianceTyingType covarianceTying, size_t nMixtures, size_t dimension, size_t nDensitiesPerMixture = 1) const
Creates an empty mixture set with.
Parameters
nMixtures of
dimension.
Definition at line 122 of file Mm/Module.cc.
References Core::Component::error(), Core::ref(), and Core::Application::us().
AbstractMixtureSetEstimator * Mm::Module_::createMixtureSetEstimator (const Core::Configuration & configuration) const
Creates an empty mixture set estimator.
Definition at line 211 of file Mm/Module.cc.
References Core::Component::criticalError(), and Core::Application::us().
AbstractMixtureSetEstimator * Mm::Module_::createMixtureSetEstimator (const Core::Configuration & configuration, size_t nMixtures, size_t dimension, size_t nDensitiesPerMixture = 1) const
Creates an empty mixture set estimator with.
Parameters
nMixtures of
dimension.
Definition at line 255 of file Mm/Module.cc.
Core::Ref< ScaledFeatureScorer > Mm::Module_::createScaledFeatureScorer (const Core::Configuration & c, Core::Ref< FeatureScorer > featureScorer) const
Creates a ScaledFeatureScorer by wraping.
Parameters
featureScorer.
Returns
a newly created instance of ScaledFeatureScorer or 0 if an error occured.
Definition at line 326 of file Mm/Module.cc.
References Core::Component::error(), Core::Component::log(), and Core::Application::us().
Core::Ref<ScaledFeatureScorer> Mm::Module_::createScaledFeatureScorer (const Core::Configuration & c, const Core::Ref< Mm::AbstractMixtureSet > m) const inline
Creates and initializes a ScaledFeatureScorer as configured.
Returns
a newly created instance of FeatureScorer or 0 if an error occured.
Definition at line 188 of file Mm/Module.hh.
Core::Ref<ScaledFeatureScorer> Mm::Module_::createScaledFeatureScorer (const Core::Configuration & c) const inline
Loads a mixture set and creates and initializes a ScaledFeatureScorer with it, as configured.
Returns
a newly created instance of ScaledFeatureScorer or 0 if an error occured.
Definition at line 195 of file Mm/Module.hh.
Core::FormatSet & Mm::Module_::formats ()
Set of file format class.
Definition at line 341 of file Mm/Module.cc.
References Core::FormatSet::registerFormat(), and Core::Application::us().
Core::Ref< AbstractMixtureSet > Mm::Module_::readAbstractMixtureSet (const Core::Configuration & configuration) const
Load mixture set from the file given in.
Parameters
Configuration (paramMixtureSetFilename). Type of mixture set depends on paramFeatureScorerType
Definition at line 195 of file Mm/Module.cc.
Core::Ref< AbstractMixtureSet > Mm::Module_::readAbstractMixtureSet (const std::string & filename, const Core::Configuration & configuration) const
Load mixture set from file.
Parameters
filename. Type of mixture set depends on paramFeatureScorerType
Definition at line 188 of file Mm/Module.cc.
References verify.
Core::Ref< MixtureSet > Mm::Module_::readMixtureSet (const std::string & file, const Core::Configuration & c) const
Loads a MixtureSet object from the file.
Parameters
file.
Definition at line 152 of file Mm/Module.cc.
References Core::Component::error(), Core::Component::log(), Mm::MixtureSetReader::read(), and Core::Application::us().
Core::Ref< MixtureSet > Mm::Module_::readMixtureSet (const Core::Configuration & c) const
Loads a MixtureSet object from the file given in.
Parameters
Configuration (paramMixtureSetFilename).
Definition at line 184 of file Mm/Module.cc.
bool Mm::Module_::readMixtureSetEstimator (const std::string & filename, AbstractMixtureSetEstimator & e)
Read a MixtureSetEstimator object from file.
Definition at line 268 of file Mm/Module.cc.
References Core::Application::us().
bool Mm::Module_::writeMixtureSetEstimator (const std::string & filename, AbstractMixtureSetEstimator & estimator)
Saves a MixtureSetEstimator object in the file.
Parameters
filename.
Definition at line 273 of file Mm/Module.cc.
References Core::Component::error(), Core::isRegularFile(), Core::Component::log(), require, and Core::Application::us().
The documentation for this class was generated from the following files:
Mm/Module.hh
Mm/Module.cc