Sprint: Speech::ModelCombination Class Reference
Speech::ModelCombination Class Reference
Combination of a lexicon, an acoustic model, and a language model.
#include <ModelCombination.hh>
Public Types
typedef u32 Mode
Public Member Functions
ModelCombination (const Core::Configuration &, Mode=complete, Am::AcousticModel::Mode=Am::AcousticModel::complete)
ModelCombination (const Core::Configuration &, Bliss::LexiconRef, Core::Ref< Am::AcousticModel >, Core::Ref< Lm::ScaledLanguageModel >)
void getDependencies (Core::DependencySet &) const
Bliss::LexiconRef lexicon () const
void setLexicon (Bliss::LexiconRef)
Mm::Score pronunciationScale () const
Core::Ref< Am::AcousticModel > acousticModel () const
void setAcousticModel (Core::Ref< Am::AcousticModel >)
Core::Ref< Lm::ScaledLanguageModel > languageModel () const
void setLanguageModel (Core::Ref< Lm::ScaledLanguageModel >)
Public Member Functions inherited from Mc::Component
Component (const Core::Configuration &c)
void updateScales (ScaleUpdate update)
Updates the scale of this and the child objects.
void load ()
Loads map file and updates scales.
void setOwnScale (Scale)
Sets ownScale_ and updates scale_.
void setParentScale (Scale scale)
Updates scale_ with parent's scale (.
Scale scale () const
parent-scale * own-scale
Scale ownScale () const
Scale parentScale () const
void getDependencies (Core::DependencySet &) const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Static Public Attributes
static const Mode complete = 0xFFFF
static const Mode useLexicon = 0x0
static const Mode useAcousticModel = 0x1
static const Mode useLanguageModel = 0x2
static const Core::ParameterFloat paramPronunciationScale
Static Public Attributes inherited from Mc::Component
static const Core::ParameterFloat paramScale
Protected Member Functions
virtual void distributeScaleUpdate (const Mc::ScaleUpdate &scaleUpdate)
Override this function -to perform updates after scale_ has new value -to distibute.
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes
Bliss::LexiconRef lexicon_
Mm::Score pronunciationScale_
Core::Ref< Am::AcousticModel > acousticModel_
Core::Ref< Lm::ScaledLanguageModel > languageModel_
Protected Attributes inherited from Core::Configurable
Configuration config
Private Member Functions
void setPronunciationScale (Mm::Score scale)
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Detailed Description
Combination of a lexicon, an acoustic model, and a language model.
It supports creation and initialization of these three mutually dependent objects.
Usage: 1) create ModelCombination object locally to create the three parts: lexicon, acoustic model, and language model.Store references of those parts which you 2) call function load, to load the scaling values 3) Store the references to those parts you will use later. 4) When the local ModelCombination object get destructed, the unreferenced parts gets freed as well.
Definition at line 37 of file ModelCombination.hh.
Constructor & Destructor Documentation
ModelCombination::ModelCombination (const Core::Configuration & c, Mode mode = complete, Am::AcousticModel::Mode acousticModelMode = Am::AcousticModel::complete)
Todo:
Scalable lexicon not implemented yet
Definition at line 31 of file ModelCombination.cc.
References Bliss::Lexicon::create(), Core::Component::criticalError(), Mc::Component::scale(), and Mc::Component::setParentScale().
Member Function Documentation
void ModelCombination::distributeScaleUpdate (const Mc::ScaleUpdate & scaleUpdate) protected virtual
Override this function -to perform updates after scale_ has new value -to distibute.
Parameters
scaleUpdate to child objects.
scaleUpdate contains -object-name to scale map -scale of this object as parentScale
Reimplemented from Mc::Component.
Definition at line 87 of file ModelCombination.cc.
References Core::DependencySet::add(), Core::Configurable::fullName(), Core::Component::log(), Mc::Component::scale(), and Mc::Component::updateScales().
The documentation for this class was generated from the following files:
ModelCombination.hh
ModelCombination.cc