Sprint: Flf::Evaluator Class Reference
Flf::Evaluator Class Reference
Public Member Functions
Evaluator (const Core::Configuration &config, const std::string &name)
Bliss::Evaluator * blissEvaluator ()
void setReference (const std::string &ref)
Set reference and evaluate lattice against single best and best in lattice (as specified in config), lattice output can be any alphabet specified by the current lexicon.
void setNormalizedReference (const std::string &ref)
void evaluate (ConstLatticeRef l)
void logEvaluation (ConstLatticeRef l, const std::string &name="")
Log the evaluation of the given lattice against the current segment's orth; lattice output has to be lemma, lemma-pronunciation, or eval alphabet.
void logOrthography (ConstLatticeRef l, const std::string &name="")
Log the preferred orthographic representation of a linear lattice; lattice output has to be lemma alphabet.
Public Member Functions inherited from Flf::LayeredComponent
LayeredComponent (const Core::Configuration &config, const std::string &layerName="")
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Attributes
static const Core::ParameterBool paramSingleBest
static const Core::ParameterBool paramBestInLattice
static const Core::Choice choiceSsspAlgorithm
static const Core::ParameterChoice paramSsspAlgorithm
Protected Attributes
SingleSourceShortestPathAlgorithm ssspAlgorithm_
Protected Attributes inherited from Core::Configurable
Configuration config
Private Attributes
Bliss::Evaluator * blissEvaluator_
u32 lastLemmaUpdates_
bool logSingleBest_
bool logBestInLattice_
Fsa::ConstAutomatonRef emptyFsa_
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Flf::LayeredComponent
void openLayer (const std::string &name="")
void closeLayer ()
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Detailed Description
Definition at line 34 of file Evaluate.cc.
Member Function Documentation
void Flf::Evaluator::logEvaluation (ConstLatticeRef l, const std::string & name = "")
Log the evaluation of the given lattice against the current segment's orth; lattice output has to be lemma, lemma-pronunciation, or eval alphabet.
logEvaluation is null reference save
Definition at line 144 of file Evaluate.cc.
References Bliss::Evaluator::evaluateWords(), Core::Component::log(), and Flf::toFsa().
Referenced by setReference().
void Flf::Evaluator::logOrthography (ConstLatticeRef l, const std::string & name = "")
Log the preferred orthographic representation of a linear lattice; lattice output has to be lemma alphabet.
logOrthography is null reference save
void Flf::Evaluator::setReference (const std::string & ref)
Set reference and evaluate lattice against single best and best in lattice (as specified in config), lattice output can be any alphabet specified by the current lexicon.
evaluate is null reference save
Definition at line 159 of file Evaluate.cc.
References Core::enforceTrailingBlank(), logEvaluation(), Core::normalizeWhitespace(), setReference(), and Core::Application::us().
Referenced by setReference().
The documentation for this class was generated from the following file:
Evaluate.cc