Sprint: Bliss::CorpusDescription::SegmentPartitionVisitorAdaptor Class Reference
Bliss::CorpusDescription::SegmentPartitionVisitorAdaptor Class Reference
Public Member Functions
void loadSegmentList (const std::string &filename, const std::string &encoding)
const Core::StringHashSet & segmentsToKeep () const
void setPartitioning (u32 nPartitions, u32 selectedPartition, bool recordingBased=false)
void setSkippedSegments (u32 nSkippedSegments)
void setSegmentsToSkip (const Core::StringHashSet &segmentsToSkip)
void setVisitor (CorpusVisitor *v)
virtual void visitSegment (Segment *s)
Template method for processing segments.
virtual void visitSpeechSegment (SpeechSegment *s)
Template method for processing speech segments.
virtual void enterRecording (Recording *r)
Template method called when corpus traversal enters a recording.
virtual void leaveRecording (Recording *r)
Template method called when corpus traversal leaves a recording.
virtual void enterCorpus (Corpus *c)
Template method notifying start of a (sub-) corpus.
virtual void leaveCorpus (Corpus *c)
Template method notifying end of a (sub-) corpus.
Private Member Functions
bool shouldVisit (Segment *s)
Private Attributes
u32 segmentIndex_
u32 recordingIndex_
u32 nPartitions_
u32 selectedPartition_
u32 nSkippedSegments_
Core::StringHashSet segmentsToSkip_
Core::StringHashSet segmentsToKeep_
Recording * currentRecording_
bool isVisitorInCurrentRecording_
bool recordingBasedPartitions_
CorpusVisitor * visitor_
Detailed Description
Definition at line 230 of file CorpusDescription.cc.
Member Function Documentation
virtual void Bliss::CorpusDescription::SegmentPartitionVisitorAdaptor::enterCorpus (Corpus *) inline virtual
Template method notifying start of a (sub-) corpus.
This is rarely needed.
Reimplemented from Bliss::CorpusVisitor.
Definition at line 304 of file CorpusDescription.cc.
References Bliss::CorpusVisitor::enterCorpus().
virtual void Bliss::CorpusDescription::SegmentPartitionVisitorAdaptor::enterRecording (Recording *) inline virtual
Template method called when corpus traversal enters a recording.
Implement this to take appropriate actions, e.g. opening the audio file.
Reimplemented from Bliss::CorpusVisitor.
Definition at line 294 of file CorpusDescription.cc.
virtual void Bliss::CorpusDescription::SegmentPartitionVisitorAdaptor::leaveCorpus (Corpus *) inline virtual
Template method notifying end of a (sub-) corpus.
This is rarely needed.
Reimplemented from Bliss::CorpusVisitor.
Definition at line 311 of file CorpusDescription.cc.
References Core::Component::criticalError(), Core::getline(), Bliss::CorpusVisitor::leaveCorpus(), Core::stripWhitespace(), and Core::Application::us().
virtual void Bliss::CorpusDescription::SegmentPartitionVisitorAdaptor::leaveRecording (Recording *) inline virtual
Template method called when corpus traversal leaves a recording.
Implement this to take appropriate clean-up actions, e.g. closing the audio file.
Reimplemented from Bliss::CorpusVisitor.
Definition at line 299 of file CorpusDescription.cc.
References Bliss::CorpusVisitor::leaveRecording().
virtual void Bliss::CorpusDescription::SegmentPartitionVisitorAdaptor::visitSegment (Segment *) inline virtual
Template method for processing segments.
Implement this to process speech and non-speech segments of a corpus.
Reimplemented from Bliss::SegmentVisitor.
Definition at line 286 of file CorpusDescription.cc.
References Bliss::SegmentVisitor::visitSegment().
virtual void Bliss::CorpusDescription::SegmentPartitionVisitorAdaptor::visitSpeechSegment (SpeechSegment * s) inline virtual
Template method for processing speech segments.
Implement this to process the speech segments of a corpus. By default the request will be forwarded to visitSegment(), so ignore this if you want to treat speech and non-speech segments alike.
Reimplemented from Bliss::SegmentVisitor.
Definition at line 290 of file CorpusDescription.cc.
References Bliss::SegmentVisitor::visitSpeechSegment().
The documentation for this class was generated from the following file:
CorpusDescription.cc