Sprint: Core::DependencySet Class Reference
Core::DependencySet Class Reference
Public Member Functions
void clear ()
void add (const std::string &name, const DependencySet &dependencySet)
Adds a complete dependency set to this one.
void add (const std::string &, const Dependency &)
void add (const std::string &, const bool)
void add (const std::string &, const std::string &)
void add (const std::string &, const int)
void add (const std::string &, const double)
bool operator== (const DependencySet &) const
bool satisfies (const DependencySet &required) const
bool weak_satisfies (const DependencySet &required, bool warn=false) const
unsigned int getChecksum () const
bool read (const Configuration &config, std::istream &)
bool read (const Configuration &config, const std::string &filename)
bool write (Core::XmlWriter &) const
bool write (const std::string &filename) const
Private Types
typedef std::map< std::string, Dependency > Dependencies
Private Attributes
Dependencies dependencies_
Static Private Attributes
static const std::string nameSeparator_
Friends
std::ostream & operator<< (std::ostream &o, const DependencySet &s)
Detailed Description
Definition at line 61 of file Dependency.hh.
Member Function Documentation
void DependencySet::add (const std::string & name, const DependencySet & dependencySet)
Adds a complete dependency set to this one.
Before appending this set, each name in
Parameters
dependencySet is extended by
name. Use this add function to build a hierarchy of dependencies, i.e. to differentiate resources instantiated more than once.
Definition at line 112 of file Dependency.cc.
References Core::Component::criticalError(), require, Core::Application::us(), and Core::Component::warning().
Referenced by Speech::ModelCombination::distributeScaleUpdate(), Mm::CombinedFeatureScorer::distributeScaleUpdate(), Am::AcousticModel::isCompatible(), Am::AcousticModel::isWeakCompatible(), Search::PersistentStateTree::PersistentStateTree(), Lm::LanguageModel::requireSentenceBoundaryToken(), Mc::Component::setParentScale(), and Core::Description::verifyNumberOfStreams().
bool DependencySet::satisfies (const DependencySet & required) const
Returns
is true of all dependencies in
Parameters
required are equal.
Definition at line 176 of file Dependency.cc.
References Core::Application::us(), and Core::Component::warning().
Referenced by Am::AcousticModel::isCompatible(), Speech::FsaCache::setDependencies(), and Search::StateTreeWriter::writeDependenciesPosition().
bool DependencySet::weak_satisfies (const DependencySet & required, bool warn = false) const
Returns
is true if all dependencies in
Parameters
required are greater or equal. you should use this method with care.
Definition at line 200 of file Dependency.cc.
References Core::Application::us(), and Core::Component::warning().
Referenced by Am::AcousticModel::isWeakCompatible().
The documentation for this class was generated from the following files:
Dependency.hh
Dependency.cc