Sprint: Speech::OfflineRecognizer Class Reference
Speech::OfflineRecognizer Class Reference
Public Member Functions
OfflineRecognizer (const Core::Configuration &, Am::AcousticModel::Mode=Am::AcousticModel::complete)
virtual void signOn (CorpusVisitor &corpusVisitor)
Override this function to sign on to services of the corpus visitor.
virtual void processResultAndLogStatistics (Bliss::SpeechSegment *s)
virtual void enterSpeechSegment (Bliss::SpeechSegment *)
virtual void leaveSpeechSegment (Bliss::SpeechSegment *)
virtual void leaveSegment (Bliss::Segment *)
virtual void processFeature (Core::Ref< const Feature >)
Override this function to achieve the features extracted form data source one-by-one.
virtual void setFeatureDescription (const Mm::FeatureDescription &)
Override this function to achieve the attributes of the feature streams.
Public Member Functions inherited from Speech::FeatureExtractor
FeatureExtractor (const Core::Configuration &c, bool loadFromFile=true)
virtual void processSegment (Bliss::Segment *segment)
Public Member Functions inherited from Speech::DataExtractor
DataExtractor (const Core::Configuration &c, bool loadFromFile=true)
virtual void enterCorpus (Bliss::Corpus *)
virtual void leaveCorpus (Bliss::Corpus *)
virtual void enterRecording (Bliss::Recording *)
virtual void enterSegment (Bliss::Segment *)
Public Member Functions inherited from Speech::CorpusProcessor
CorpusProcessor (const Core::Configuration &c)
virtual void leaveRecording (Bliss::Recording *recoding)
virtual void processSpeechSegment (Bliss::SpeechSegment *segment)
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Speech::Recognizer
Recognizer (const Core::Configuration &)
Protected Member Functions
void processResult (Bliss::SpeechSegment *s)
void logTraceback (const Traceback &)
void addPartialToTraceback (Traceback &partialTraceback)
void processFeatureTimestamp (const Flow::Timestamp &timestamp)
void finishSegment (Bliss::SpeechSegment *segment)
Protected Member Functions inherited from Speech::DataExtractor
void setDataSource (Core::Ref< DataSource > s)
Core::Ref< DataSource > dataSource () const
Protected Member Functions inherited from Speech::CorpusProcessor
void reportRealTime (Flow::Time)
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Member Functions inherited from Speech::Recognizer
void initializeRecognizer (Am::AcousticModel::Mode acousticModelMode)
void initializeRecognizer (const Speech::ModelCombination &)
virtual void createRecognizer ()
Protected Attributes
bool shouldEvaluateResult_
bool shouldStoreLattice_
Bliss::Evaluator * evaluator_
Search::LatticeHandler * latticeHandler_
Lattice::ArchiveWriter * tracebackArchiveWriter_
Core::XmlChannel tracebackChannel_
bool timeConditionedLattice_
std::string layerName_
Protected Attributes inherited from Speech::CorpusProcessor
Core::XmlChannel channelTimer_
Core::Timer timer_
Protected Attributes inherited from Core::Configurable
Configuration config
Protected Attributes inherited from Speech::Recognizer
Core::Ref< const Bliss::Lexicon > lexicon_
Core::Ref< Am::AcousticModel > acousticModel_
Search::SearchAlgorithm * recognizer_
Private Types
typedef FeatureExtractor Precursor
Private Attributes
std::vector< Flow::Timestamp > featureTimes_
Flow::Time partialResultInterval_
Flow::Time lastPartialResult_
Traceback traceback_
bool noDependencyCheck_
Static Private Attributes
static const Core::ParameterBool paramStoreLattices
static const Core::ParameterBool paramStoreTracebacks
static const Core::ParameterBool paramTimeConditionedLattice
static const Core::ParameterString paramLayerName
static const Core::ParameterFloat paramPartialResultInterval
static const Core::ParameterBool paramEvaluteResult
static const Core::ParameterBool paramNoDependencyCheck
Additional Inherited Members
Static Public Attributes inherited from Speech::Recognizer
static const Core::Choice searchTypeChoice_
static const Core::ParameterChoice paramSearch
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Types inherited from Speech::Recognizer
typedef Search::SearchAlgorithm::Traceback Traceback
Detailed Description
Definition at line 63 of file Speech/Recognizer.hh.
Member Function Documentation
void OfflineRecognizer::processFeature (Core::Ref< const Feature >) virtual
Override this function to achieve the features extracted form data source one-by-one.
Reimplemented from Speech::FeatureExtractor.
Reimplemented in Speech::DelayedRecognizer.
Definition at line 272 of file Speech/Recognizer.cc.
References Mm::FeatureScorer::addFeature(), Mm::FeatureScorer::bufferFilled(), and Mm::FeatureScorer::isBuffered().
void OfflineRecognizer::processResult (Bliss::SpeechSegment * s) protected
Todo:
Should stop timer here: evaluation may take some time we don't want to count it.
Definition at line 216 of file Speech/Recognizer.cc.
References Search::LatticeAdaptor::empty(), Core::Component::error(), Core::ref(), Search::LatticeAdaptor::wordLattice(), and Search::LatticeAdaptor::write().
void OfflineRecognizer::setFeatureDescription (const Mm::FeatureDescription &) virtual
Override this function to achieve the attributes of the feature streams.
This function is called once before the first feature is processed.
Reimplemented from Speech::FeatureExtractor.
Definition at line 298 of file Speech/Recognizer.cc.
References Core::Ref< T >::get(), Lm::LanguageModel::getFsa(), Lattice::WordLattice::lmFsa, Core::Component::log(), Fsa::multiply(), require, Fsa::staticCopy(), and verify.
void OfflineRecognizer::signOn (CorpusVisitor & corpusVisitor) virtual
Override this function to sign on to services of the corpus visitor.
Note: call the signOn function of your predecessor.
Reimplemented from Speech::DataExtractor.
Reimplemented in Speech::DelayedRecognizer.
Definition at line 158 of file Speech/Recognizer.cc.
References Mm::FeatureScorer::bufferEmpty(), Core::Component::error(), Mm::FeatureScorer::flush(), and Mm::FeatureScorer::isBuffered().
The documentation for this class was generated from the following files:
Speech/Recognizer.hh
Speech/Recognizer.cc