Sprint: Core::ParameterBitVector Class Reference
Core::ParameterBitVector Class Reference
Declaration class for bit vector parameters.
#include <Parameter.hh>
Public Member Functions
virtual bool parseString (const std::string &in, Value &out) const
Parse bit-vector specification.
ParameterBitVector (const char *ident, const char *s_desc, const Value &defaultValue=Value(), const char *l_desc="")
Public Member Functions inherited from Core::Parameter< std::vector< bool > >
virtual bool isValid (const Value &v) const
Parameter (const char *ident, const char *s_desc, const Value &defaultValue, const char *l_desc="")
const Value & defaultValue () const
Value operator() (const std::string &str) const
Obtain parameter value from string.
Value operator() (const class Configuration &c, const Value &_defaultValue) const
Retrieve parameter value from configuration.
Value operator() (const class Configuration &c) const
Retrieve parameter value from configuration.
Public Member Functions inherited from Core::AbstractParameter
AbstractParameter (const AbstractParameter &p)
AbstractParameter (const char *ident, const char abbrev, const char *short_desc, const char *long_desc, const bool needs_arg)
std::string name () const
bool match (const std::string &query) const
bool hasAbbreviation () const
char getAbbreviation () const
std::string getShortDescription () const
std::string getLongDescription () const
void printShortHelp (std::ostream &ostr) const
virtual void printParseHelp (std::ostream &os) const
Print help on how a wellformed setting looks.
virtual void printValidityHelp (std::ostream &os) const
Print help on what values are acceptable.
bool operator== (const AbstractParameter &p) const
bool operator< (const AbstractParameter &p) const
Static Public Member Functions
static bool parseRangeList (const std::string &in, Value &out)
Parse comma-separated list of ranges.
static bool parseBinary (const std::string &in, Value &out)
Parse sequence of zeroes and ones.
Additional Inherited Members
Public Types inherited from Core::Parameter< std::vector< bool > >
typedef std::vector< bool > Value
Protected Member Functions inherited from Core::Parameter< std::vector< bool > >
Value getValue (const std::string &str) const
Value getValue (const class Configuration &c, const Value &_defaultValue) const
Value getValue (const class Configuration &c) const
Protected Attributes inherited from Core::Parameter< std::vector< bool > >
Value defaultValue_
Protected Attributes inherited from Core::AbstractParameter
std::string ident
char abbrev
const char * short_desc
const char * long_desc
bool needs_arg_
Detailed Description
Declaration class for bit vector parameters.
Values can be specified either as sequence of zeroes and ones, or as as comma-separated list of ranges.
Definition at line 291 of file Parameter.hh.
Member Function Documentation
bool ParameterBitVector::parseBinary (const std::string & in, Value & out) static
Parse sequence of zeroes and ones.
Definition at line 295 of file Parameter.cc.
bool ParameterBitVector::parseRangeList (const std::string & in, Value & out) static
Parse comma-separated list of ranges.
Each comma-seperated item can be either a single number or range (a-b). All bits mentioned in the list are true, all others are false
Definition at line 247 of file Parameter.cc.
Referenced by Flow::VectorSplitNode< T >::getOutput().
bool ParameterBitVector::parseString (const std::string & in, Value & out) const virtual
Parse bit-vector specification.
Try to interpret as binary representation first, if that fails parse as range list.
Implements Core::Parameter< std::vector< bool > >.
Definition at line 312 of file Parameter.cc.
References Core::form(), Core::Configuration::get(), require, and Core::str2vector().
The documentation for this class was generated from the following files:
Parameter.hh
Parameter.cc