Sprint: Core::XmlParser Class Reference
Core::XmlParser Class Reference
Basic event driven XML parser.
#include <XmlParser.hh>
Classes
struct Location
Public Member Functions
Location location () const
void warnAboutUnexpectedElement (const char *element, const char *context)
Issue a warning about an unexpected element.
XmlParser (const Configuration &)
int parseString (const char *str)
Parse a character string.
int parseStream (std::istream &i, const std::string &filename="from stream")
Parse a stream.
int parseFile (const char *filename)
Parse a file.
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Attributes
static const ParameterBool paramWarnAboutUnexpectedElements
Protected Member Functions
virtual int isStandalone ()
virtual int hasInternalSubset ()
virtual int hasExternalSubset ()
virtual xmlParserInputPtr resolveEntity (const char *publicId, const char *systemId)
virtual void internalSubset (const char *name, const char *ExternalID, const char *SystemID)
virtual void externalSubset (const char *name, const char *ExternalID, const char *SystemID)
virtual xmlEntityPtr getEntity (const char *name)
virtual xmlEntityPtr getParameterEntity (const char *name)
virtual void entityDecl (const char *name, int type, const char *publicId, const char *systemId, const char *content)
virtual void notationDecl (const char *name, const char *publicId, const char *systemId)
virtual void attributeDecl (const char *elem, const char *name, int type, int def, const char *defaultValue, xmlEnumerationPtr tree)
virtual void elementDecl (const char *name, int type, xmlElementContentPtr content)
virtual void unparsedEntityDecl (const char *name, const char *publicId, const char *systemId, const char *notationName)
virtual void startDocument ()
virtual void endDocument ()
virtual void startElement (const char *name, const XmlAttributes atts)
virtual void endElement (const char *name)
virtual void reference (const char *name)
virtual void characters (const char *ch, int len)
virtual void cdataBlock (const char *ch, int len)
virtual void ignorableWhitespace (const char *ch, int len)
virtual void processingInstruction (const char *target, const char *data)
virtual void comment (const char *value)
int parse ()
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
void giveUp ()
Disable parsing.
Private Types
typedef XmlParser self
Private Member Functions
size_t readChunk (std::istream &is, char *buffer, size_t bufferSize)
Reads a chunk of size.
Static Private Member Functions
static xmlParserInputPtr SAX_resolveEntity_callback (void *ctx, const xmlChar *publicId, const xmlChar *systemId)
static void SAX_internalSubset_callback (void *ctx, const xmlChar *name, const xmlChar *ExternalID, const xmlChar *SystemID)
static void SAX_externalSubset_callback (void *ctx, const xmlChar *name, const xmlChar *ExternalID, const xmlChar *SystemID)
static xmlEntityPtr SAX_getEntity_callback (void *ctx, const xmlChar *name)
static xmlEntityPtr SAX_getParameterEntity_callback (void *ctx, const xmlChar *name)
static void SAX_entityDecl_callback (void *ctx, const xmlChar *name, int type, const xmlChar *publicId, const xmlChar *systemId, xmlChar *content)
static void SAX_notationDecl_callback (void *ctx, const xmlChar *name, const xmlChar *publicId, const xmlChar *systemId)
static void SAX_attributeDecl_callback (void *ctx, const xmlChar *elem, const xmlChar *name, int type, int def, const xmlChar *defaultValue, xmlEnumerationPtr tree)
static void SAX_elementDecl_callback (void *ctx, const xmlChar *name, int type, xmlElementContentPtr content)
static void SAX_unparsedEntityDecl_callback (void *ctx, const xmlChar *name, const xmlChar *publicId, const xmlChar *systemId, const xmlChar *notationName)
static void SAX_startDocument_callback (void *ctx)
static void SAX_endDocument_callback (void *ctx)
static void SAX_startElement_callback (void *ctx, const xmlChar *name, const xmlChar **atts)
static void SAX_endElement_callback (void *ctx, const xmlChar *name)
static void SAX_reference_callback (void *ctx, const xmlChar *name)
static void SAX_characters_callback (void *ctx, const xmlChar *ch, int len)
static void SAX_cdataBlock_callback (void *ctx, const xmlChar *ch, int len)
static void SAX_ignorableWhitespace_callback (void *ctx, const xmlChar *ch, int len)
static void SAX_processingInstruction_callback (void *ctx, const xmlChar *target, const xmlChar *data)
static void SAX_comment_callback (void *ctx, const xmlChar *value)
static void SAX_warning_callback (void *ctx, const char *msg,...) __attribute__((format(printf
static void static void SAX_error_callback (void *ctx, const char *msg,...) __attribute__((format(printf
static void static void static void SAX_fatalError_callback (void *ctx, const char *msg,...) __attribute__((format(printf
static void static void static void static int SAX_isStandalone_callback (void *ctx)
static int SAX_hasInternalSubset_callback (void *ctx)
static int SAX_hasExternalSubset_callback (void *ctx)
Private Attributes
xmlParserCtxtPtr ctxt_
bool warnAboutUnexpectedElements_
Static Private Attributes
static const xmlSAXHandler SAX_callbacks
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Basic event driven XML parser.
The XML Parser is built in top of libxml2 (the XML parser for Gnome). This class provides a thin wrapper around the SAX interface of libxml. All callback entries are converted into virtual member functions which can (and should) be overridden to implement event driven Xml parsers.
See also
full documentation of libxml: local or on the web
Definition at line 80 of file XmlParser.hh.
Member Function Documentation
void XmlParser::giveUp () protected
Disable parsing.
Call giveUp() if it seems hopeless trying to continue parsing.
Definition at line 303 of file XmlParser.cc.
int XmlParser::parseFile (const char * filename)
Parse a file.
Returns
0 on success
Definition at line 408 of file XmlParser.cc.
Referenced by Nn::LogarithmPreprocessingLayer< T >::_forward(), TestApplication::main(), Signal::BayesClassification::reset(), Mc::ScaleUpdate::setMap(), and Speech::FeatureShiftAdaptor::work().
int XmlParser::parseStream (std::istream & is, const std::string & filename = "from stream")
Parse a stream.
Implementation issues:
Returns
0 on success
xmlCreatePushParserCtxt needs at least 4 bytes to allow content encoding detection
xmlParseChunk does only seem to work if called at least twice!
Definition at line 372 of file XmlParser.cc.
int XmlParser::parseString (const char * str)
Parse a character string.
Returns
0 on success
Definition at line 357 of file XmlParser.cc.
size_t XmlParser::readChunk (std::istream & is, char * buffer, size_t bufferSize) private
Reads a chunk of size.
Parameters
bufferSize from
is and stores the result in
buffer.
Returns
number of read characters
Definition at line 396 of file XmlParser.cc.
References require.
XmlChannel * XmlParser::vErrorMessage (ErrorType mt, const char * msg, va_list ap) const protected virtual
Output a warning/error message on the appropriate channel.
All error message will be augmented by file name and line number where the error occured.
Reimplemented from Core::Component.
Definition at line 283 of file XmlParser.cc.
References Core::Component::vErrorMessage().
void XmlParser::warnAboutUnexpectedElement (const char * element, const char * context)
Issue a warning about an unexpected element.
This method must be called by decendents of XmlParentElement whenever they use their unexpectedElement(). The reason that this deserves an extra method is that these warnings can be turned of. It is not a good idea to silently ignore unknown element, because they might be typos.
Definition at line 327 of file XmlParser.cc.
Referenced by Core::XmlMixedElement::element(), and Core::XmlRegularElement::element().
Member Data Documentation
const xmlSAXHandler XmlParser::SAX_callbacks static private
Initial value:
= {
        XmlParser::SAX_internalSubset_callback,
        XmlParser::SAX_isStandalone_callback,
        XmlParser::SAX_hasInternalSubset_callback,
        XmlParser::SAX_hasExternalSubset_callback,
        XmlParser::SAX_resolveEntity_callback,
        XmlParser::SAX_getEntity_callback,
        XmlParser::SAX_entityDecl_callback,
        XmlParser::SAX_notationDecl_callback,
        XmlParser::SAX_attributeDecl_callback,
        XmlParser::SAX_elementDecl_callback,
        XmlParser::SAX_unparsedEntityDecl_callback,
        0,
        XmlParser::SAX_startDocument_callback,
        XmlParser::SAX_endDocument_callback,
        XmlParser::SAX_startElement_callback,
        XmlParser::SAX_endElement_callback,
        XmlParser::SAX_reference_callback,
        XmlParser::SAX_characters_callback,
        XmlParser::SAX_ignorableWhitespace_callback,
        XmlParser::SAX_processingInstruction_callback,
        XmlParser::SAX_comment_callback,
        XmlParser::SAX_warning_callback,
        XmlParser::SAX_error_callback,
        XmlParser::SAX_fatalError_callback,
        XmlParser::SAX_getParameterEntity_callback,
        XmlParser::SAX_cdataBlock_callback,
        XmlParser::SAX_externalSubset_callback,
}
Definition at line 111 of file XmlParser.hh.
The documentation for this class was generated from the following files:
XmlParser.hh
XmlParser.cc