Sprint: Signal::HistogramNormalization Class Reference
Signal::HistogramNormalization Class Reference
HistogramNormalization.
#include <HistogramNormalization.hh>
Public Types
typedef f32 Value
typedef Histogram< Value >::Probability Probability
typedef Histogram< Value >::Weight HistogramWeight
typedef LookupTable< Probability, Value > Cdf
typedef std::vector< Cdf > Cdfs
typedef LookupTable< Value, Probability > InverseCdf
typedef std::vector< InverseCdf > InverseCdfs
Public Member Functions
void apply (const std::vector< Value > &in, std::vector< Value > &out)
void setTrainingHistograms (const std::vector< Histogram< Value >> &trainingHistograms, Probability probabilityBucketSize)
void setTrainingHistograms (const std::vector< HistogramVector< Value >> &trainingHistograms, const std::vector< Value > &scales, Probability probabilityBucketSize)
size_t nTrainingHistograms () const
void setTestHistograms (const std::vector< Histogram< Value >> &testHistograms)
size_t nTestHistograms () const
Static Public Member Functions
static bool areScalesWellDefined (const std::vector< HistogramWeight > &scales)
static bool areScalesNormalized (const std::vector< HistogramWeight > &scales)
static void normalizeScales (std::vector< HistogramWeight > &scales)
Inserts a scale at the beginning, which makes the sum of scales to be zero.
Private Attributes
Cdfs testCdfs_
InverseCdfs inverseTrainingCdfs_
Detailed Description
HistogramNormalization.
Definition at line 26 of file HistogramNormalization.hh.
Member Function Documentation
bool HistogramNormalization::areScalesNormalized (const std::vector< HistogramWeight > & scales) static
Returns
is true if the sum of weights is one.
Definition at line 86 of file HistogramNormalization.cc.
References Core::isAlmostEqual().
Referenced by Signal::HistogramNormalizationNode::updateTrainingHistograms().
bool HistogramNormalization::areScalesWellDefined (const std::vector< HistogramWeight > & scales) static
Returns
is false if one of the weights is smaller than larger than one.
Definition at line 77 of file HistogramNormalization.cc.
Referenced by Signal::HistogramNormalizationNode::updateTrainingHistograms().
void HistogramNormalization::normalizeScales (std::vector< HistogramWeight > & scales) static
Inserts a scale at the beginning, which makes the sum of scales to be zero.
Definition at line 91 of file HistogramNormalization.cc.
Referenced by Signal::HistogramNormalizationNode::updateTrainingHistograms().
void HistogramNormalization::setTrainingHistograms (const std::vector< Histogram< Value >> & trainingHistograms, Probability probabilityBucketSize)
Parameters
probabilityBucketSize is bucket size of the inverse training cumulative density functions
Definition at line 24 of file HistogramNormalization.cc.
References require, and verify.
Referenced by Signal::HistogramNormalizationNode::getInput(), and Signal::HistogramNormalizationNode::updateTrainingHistograms().
The documentation for this class was generated from the following files:
HistogramNormalization.hh
HistogramNormalization.cc