Sprint: Bliss::TokenAlphabet Class Reference
Bliss::TokenAlphabet Class Reference
Public Member Functions
virtual Fsa::LabelId index (const std::string &) const
Given a string representation of a symbol returns the label id.
virtual std::string symbol (Fsa::LabelId) const
Returns the string representation of a symbol.
virtual const_iterator end () const
Returns an iterator pointing behind the last symbol.
virtual void writeXml (Core::XmlWriter &os) const
Write the alphabet to an XmlWriter.
virtual void describe (Core::XmlWriter &os) const
Fsa::LabelId index (const Token *tt) const
const Token * token (Fsa::LabelId ii) const
u32 nDisambiguators () const
Fsa::LabelId disambiguator (u32) const
virtual bool isDisambiguator (Fsa::LabelId) const
Determine wether a symbol is a disambiguator (see determinize for more details on the use of disambiguators).
Public Member Functions inherited from Fsa::Alphabet
std::string specialSymbol (LabelId index) const
Retrieve a string representation of a special label id.
LabelId specialIndex (const std::string &symbol) const
Map a string representation of a special symbol to its label id.
virtual const_iterator begin () const
Returns an iterator pointing to the first symbol.
virtual LabelId next (LabelId id) const
Returns the label id of the next symbol in sequence.
virtual AlphabetTag tag (LabelId index) const
return symbol tag
virtual bool write (Core::BinaryOutputStream &o) const
Write the alphabet to BinaryOutputStream.
virtual size_t getMemoryUsed () const
Return the amount of memory used by this object.
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Protected Member Functions
TokenAlphabet (const TokenInventory &)
TokenAlphabet (LexiconRef, const TokenInventory &)
Protected Attributes
LexiconRef lexicon_
Private Attributes
const TokenInventory & tokens_
u32 nDisambiguators_
Friends
class Lexicon
Detailed Description
Definition at line 29 of file Fsa.hh.
Member Function Documentation
Fsa::Alphabet::const_iterator TokenAlphabet::end () const virtual
Returns an iterator pointing behind the last symbol.
This usually does not need to be overloaded except for the case you need a different internal representation of the end iterator. Currently, InvalidLabelId is being used as end iterator.
Returns
a const iterator pointing to the first symbol or end()
Reimplemented from Fsa::Alphabet.
Reimplemented in Bliss::PhonemeAlphabet.
Definition at line 56 of file Bliss/Fsa.cc.
Fsa::LabelId TokenAlphabet::index (const std::string & symbol) const virtual
Given a string representation of a symbol returns the label id.
Parameters
symbol the string representation of a symbol
Returns
the label id of the symbol or InvalidLabelId if the string represents no valid symbol
Reimplemented from Fsa::Alphabet.
Reimplemented in Bliss::PhonemeAlphabet.
Definition at line 29 of file Bliss/Fsa.cc.
References Bliss::Token::id().
Referenced by Bliss::LemmaPronunciationAlphabet::end(), and Search::Wfst::Builder::RemoveEmptyPath::process().
bool TokenAlphabet::isDisambiguator (Fsa::LabelId index) const virtual
Determine wether a symbol is a disambiguator (see determinize for more details on the use of disambiguators).
Parameters
index the symbol's label id
Returns
true if the symbol is a disambiguator.
Reimplemented from Fsa::Alphabet.
Definition at line 84 of file Bliss/Fsa.cc.
Referenced by Bliss::LemmaPronunciationAlphabet::end().
std::string TokenAlphabet::symbol (Fsa::LabelId index) const virtual
Returns the string representation of a symbol.
Parameters
index the symbol's label id
Returns
the string representation of the symbol or an empty string if there is no symbol with that label id
Implements Fsa::Alphabet.
Reimplemented in Bliss::PhonemeAlphabet.
Definition at line 45 of file Bliss/Fsa.cc.
Referenced by Bliss::LemmaPronunciationAlphabet::end().
void TokenAlphabet::writeXml (Core::XmlWriter & o) const virtual
Write the alphabet to an XmlWriter.
Parameters
o the XmlWriter
Returns
true if the operation was successfull for all symbols, false otherwise
Reimplemented from Fsa::Alphabet.
Reimplemented in Bliss::PhonemeAlphabet.
Definition at line 61 of file Bliss/Fsa.cc.
References require, and Fsa::Alphabet::writeXml().
Referenced by Bliss::LemmaPronunciationAlphabet::end().
The documentation for this class was generated from the following files:
Fsa.hh
Bliss/Fsa.cc