Sprint: Bliss::EditDistance Class Reference
Bliss::EditDistance Class Reference
Calculation of Levenshtein alignment.
#include <EditDistance.hh>
Classes
class Alignment
struct AlignmentItem
struct Hyp
struct State
struct Trace
Public Types
enum EditOperation {
Deletion, Insertion, Substitution, Correct,
Empty
}
enum AlignmentFormat { FormatBliss, FormatNist }
typedef f32 Score
typedef u32 Cost
typedef std::pair< EditOperation, Cost > EditCost
Public Member Functions
EditDistance (const Core::Configuration &)
Alignment newAlignment () const
void align (Fsa::ConstAutomatonRef, Fsa::ConstAutomatonRef, Alignment &out) const
Find best Levenshtein alignment.
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Attributes
static const Core::Choice AlignmentFormatChoice
static const Core::ParameterChoice paramAlignmentFormat
static const Core::ParameterInt paramInsertionCost
static const Core::ParameterInt paramDeletionCost
static const Core::ParameterInt paramSubstitutionCost
static const Core::ParameterBool paramAllowBrokenWords
Private Member Functions
EditCost delCost (const Token *a) const
EditCost insCost (const Token *b) const
EditCost subCost (const Token *a, const Token *b) const
EditCost cost (const Token *a, const Token *b) const
Private Attributes
AlignmentFormat format_
bool allowBrokenWords_
Cost deletionCost_
Cost insertionCost_
Cost substitutionCost_
Core::Statistics< u32 > statSearchSpace_
Core::Statistics< u32 > statMaxStackSize_
Core::Statistics< u32 > statNExpansions_
Core::XmlChannel debugChannel_
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Calculation of Levenshtein alignment.
The Levenshtein distance of two strings and is the minimum number of edit operations required to transform into , where a editing operation is either a deletetion, an insertion or a substitution. By the Levenshtein alignment we mean the corresponding optimal sequence of pairs , where , , and represents an insertion, a deletion, and otherwise a substitution.
Here we generalize this notion from sequences to directed graphs (or equivalently FSAs). The minimization extends not only over the set of editing operations, but also over all strings represented in either graph. This has several applications in NLP, e.g. word error rate, word graph error rate, phoneme error rate in the presence of pronunciation variation.
In the formalism of FSTs the problem can be stated as follows: The Levenshtein transducer is defined as follows: There is a single state with self transitions. For each there are transitions (correct) with zero cost, (deletion) with cost 1 and (insertion) with cost 1. For each there is transition with cost 1 (substitution). To determine the optimal Levenshtein alignment of FSAs and we just form the composition and determine the best path.
Definition at line 63 of file EditDistance.hh.
Member Function Documentation
void EditDistance::align (Fsa::ConstAutomatonRef a, Fsa::ConstAutomatonRef b, Alignment & out) const
Find best Levenshtein alignment.
Implementation notes:
In practice it would be very memory consuming to construct either the Levenshtein transducer L or the composition explicitly. Since has exactly one state we can represent the vertices of by a pairs where / is a Node in / . The transitions are coded explicitly.
The optimal alignment is determined by Dijkstra's shortest-path algorithm. The search is admissible (i.e. no search errors are possible). In the low-error regime it is far more efficient than the simple dynamic-programming algorithm, even for linear chains. All costs must be non-negative (which is the case). Traceback information is managed via reference counting.
Subtle issues: This algorithm appears not to handle epsilon arcs. Nevertheless the result is correct. The point is that the true distinction between insertions, deletions and substitutions is done in the cost() function. So "substituting" epsilon for A is counted as a deletion; "substituting" epsilon for epsilon is counted as correct; "deleting" epsilon is counted as correct; and so forth.
Suggestions for the future: We could convert this routine to a lazy Fsa::Automaton and have the search done by Fsa's SSSP implmentation. But currently Fsa implements only depth-first search which is probably not efficent in this case. A note for the case that efficency problems (for large graphs) should arise: It should be possible to implement admissible rest-costs (i.e. A*-search) by counting the minimum number of insertions/deletions required from any given point. Currently this seems not worth the effort.
Definition at line 291 of file EditDistance.cc.
References Core::Component::error(), Core::Ref< T >::get(), Core::TracedPriorityQueue< T_Item, T_Key, T_KeyFunction, T_PriorityFunction, T_Hash_Obj >::insertOrRelax(), Core::PriorityQueueBase< TracedHeap< T_Item, T_Key, T_KeyFunction, DefaultHashMap, T_Hash_Obj >, T_PriorityFunction >::pop(), Core::ref(), require, Core::PriorityQueueBase< TracedHeap< T_Item, T_Key, T_KeyFunction, DefaultHashMap, T_Hash_Obj >, T_PriorityFunction >::top(), and verify.
The documentation for this class was generated from the following files:
EditDistance.hh
EditDistance.cc