Sprint: Speech::CorpusVisitor Class Reference
Speech::CorpusVisitor Class Reference
CorpusVisitor traverses the corpus description and configures the registered objects.
#include <CorpusVisitor.hh>
Public Member Functions
CorpusVisitor (const Core::Configuration &c)
void signOn (CorpusProcessor *p)
void signOn (Core::Ref< DataSource > d)
void signOn (Core::Ref< Bliss::CorpusKey > k)
void clearRegistrations ()
bool isSignedOn (Core::Ref< DataSource > d) const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Protected Member Functions
virtual void enterCorpus (Bliss::Corpus *)
Template method notifying start of a (sub-) corpus.
virtual void leaveCorpus (Bliss::Corpus *)
Template method notifying end of a (sub-) corpus.
virtual void enterRecording (Bliss::Recording *)
Template method called when corpus traversal enters a recording.
virtual void leaveRecording (Bliss::Recording *)
Template method called when corpus traversal leaves a recording.
virtual void visitSegment (Bliss::Segment *)
Template method for processing segments.
virtual void visitSpeechSegment (Bliss::SpeechSegment *)
Template method for processing speech segments.
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Private Member Functions
template<class Reference >
void signOn (std::vector< Reference > &v, Reference r)
template<class Reference >
bool isSignedOn (const std::vector< Reference > &v, Reference r) const
Private Attributes
std::vector< Core::Ref< Bliss::CorpusKey > > corpusKeys_
std::vector< Core::Ref< DataSource > > dataSources_
std::vector< CorpusProcessor * > corpusProcessors_
size_t recordingIndex_
size_t segmentIndex_
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
CorpusVisitor traverses the corpus description and configures the registered objects.
Following types can be registered (sign on):
CorpusProcessor
DataSource
CorpusKey
Definition at line 37 of file CorpusVisitor.hh.
Member Function Documentation
void CorpusVisitor::enterCorpus (Bliss::Corpus *) protected virtual
Template method notifying start of a (sub-) corpus.
This is rarely needed.
Reimplemented from Bliss::CorpusVisitor.
Definition at line 148 of file CorpusVisitor.cc.
References Bliss::CorpusVisitor::enterCorpus().
void CorpusVisitor::enterRecording (Bliss::Recording *) protected virtual
Template method called when corpus traversal enters a recording.
Implement this to take appropriate actions, e.g. opening the audio file.
Reimplemented from Bliss::CorpusVisitor.
Definition at line 162 of file CorpusVisitor.cc.
References Bliss::CorpusVisitor::enterRecording().
void CorpusVisitor::leaveCorpus (Bliss::Corpus *) protected virtual
Template method notifying end of a (sub-) corpus.
This is rarely needed.
Reimplemented from Bliss::CorpusVisitor.
Definition at line 155 of file CorpusVisitor.cc.
References Bliss::CorpusVisitor::leaveCorpus().
void CorpusVisitor::leaveRecording (Bliss::Recording *) protected virtual
Template method called when corpus traversal leaves a recording.
Implement this to take appropriate clean-up actions, e.g. closing the audio file.
Reimplemented from Bliss::CorpusVisitor.
Definition at line 173 of file CorpusVisitor.cc.
References Bliss::CorpusVisitor::leaveRecording().
void CorpusVisitor::visitSegment (Bliss::Segment *) protected virtual
Template method for processing segments.
Implement this to process speech and non-speech segments of a corpus.
Reimplemented from Bliss::SegmentVisitor.
Definition at line 181 of file CorpusVisitor.cc.
void CorpusVisitor::visitSpeechSegment (Bliss::SpeechSegment * s) protected virtual
Template method for processing speech segments.
Implement this to process the speech segments of a corpus. By default the request will be forwarded to visitSegment(), so ignore this if you want to treat speech and non-speech segments alike.
Reimplemented from Bliss::SegmentVisitor.
Definition at line 194 of file CorpusVisitor.cc.
The documentation for this class was generated from the following files:
CorpusVisitor.hh
CorpusVisitor.cc