Sprint: Signal::LookupTable< Value, Index > Class Template Reference
Signal::LookupTable< Value, Index > Class Template Reference
LookupTable: array of Values indexed by arbitrary numbers of type Index.
#include <LookupTable.hh>
Public Types
typedef Value ValueType
typedef Index IndexType
typedef std::deque< ValueType >::iterator Iterator
typedef std::deque< ValueType >::const_iterator ConstIterator
Public Member Functions
LookupTable (const Index bucketSize=0)
Creates a lookup table with variable amount of buckets.
LookupTable (const Index bucketSize, const Index min, const Index max)
Creates a lookup table with constant amount of buckets.
void clear ()
Iterator insert (const Index index, const Value init=0)
ConstIterator find (const Index index, const Value defaultValue=0) const
Value & operator[] (const Index index)
const Value & operator[] (const Index index) const
Iterator begin ()
ConstIterator begin () const
Iterator end ()
ConstIterator end () const
Index bucketSize () const
size_t size () const
bool empty () const
Value sum () const
Value surface () const
void normalizeSurface ()
int isMonotonous (Value equalityTolerance=1) const
Returns how monotonous the function is.
void getInverse (LookupTable< Index, Value > &inverse) const
Value proposeBucketSizeForInverse () const
LookupTable< Value, Index > & operator+= (const LookupTable< Value, Index > &toAdd)
LookupTable< Value, Index > & operator*= (const Value scalar)
bool read (Core::BinaryInputStream &i)
bool write (Core::BinaryOutputStream &o) const
Private Types
typedef s32 BucketIndex
Private Member Functions
BucketIndex bucket (const Index index) const
Index index (const BucketIndex b) const
Private Attributes
Index bucketSize_
BucketIndex offset_
std::deque< Value > f_
bool grow_
Friends
LookupTable< Value, Index > operator* (const Value scalar, const LookupTable< Value, Index > &lt)
Core::XmlWriter & operator<< (Core::XmlWriter &o, const LookupTable< Value, Index > &lt)
Detailed Description
template<class Value, class Index>
class Signal::LookupTable< Value, Index >
LookupTable: array of Values indexed by arbitrary numbers of type Index.
Maps the Index interval to the [0..(max_index - min_index) * bucketSize] integer inteval. Integer interval is automatically extended, if a new Index does not fit into it.
Values can be reached by Value& operator[](Index i) (do not extend the integer interval) iterator (do not extend the integer interval) iterator insert(Index i, Value init) (extends the integer interval)
getInverse creates a LookupTable of the inverse function.
Definition at line 29 of file LookupTable.hh.
Constructor & Destructor Documentation
template<class Value, class Index> Signal::LookupTable< Value, Index >::LookupTable (const Index bucketSize = 0) inline
Creates a lookup table with variable amount of buckets.
Definition at line 82 of file LookupTable.hh.
Referenced by Signal::LookupTable< f32, Value >::LookupTable().
template<class Value , class Index> Signal::LookupTable< Value, Index >::LookupTable (const Index bucketSize, const Index min, const Index max)
Creates a lookup table with constant amount of buckets.
Index values smaller than min or larger than max will be set back to min resp. max.
Definition at line 166 of file LookupTable.hh.
References require.
Member Function Documentation
template<class Value, class Index > int Signal::LookupTable< Value, Index >::isMonotonous (Value equalityTolerance = 1) const
Returns how monotonous the function is.
Returns
is: 0: not monotonous 1: monotonous with constant parts 2: strictly monotonous @
Parameters
equalityTolerance controls how large jitter is accepted in constant part.
Definition at line 208 of file LookupTable.hh.
References Core::isAlmostEqual(), require, and verify.
Referenced by Signal::LookupTable< f32, Value >::LookupTable().
The documentation for this class was generated from the following file:
LookupTable.hh