Sprint: Bliss::Lemma Class Reference
Bliss::Lemma Class Reference
An entry in the Bliss lexion.
#include <Lexicon.hh>
Classes
class PronunciationIterator
Public Types
typedef std::pair< PronunciationIterator, PronunciationIterator > LemmaPronunciationRange
typedef EvaluationTokenSequenceList::const_iterator EvaluationTokenSequenceIterator
Public Types inherited from Bliss::Token
typedef s32 Id
Public Member Functions
bool hasName () const
Test for presence of a name.
Symbol name () const
A unique string identifier for the lemma.
OrthographicFormList::Size nOrthographicForms () const
Number of orthographic forms of this lemma.
const OrthographicFormList & orthographicForms () const
Set of orthographic forms of this lemma.
OrthographicForm preferredOrthographicForm () const
Preferred (standard) orthographic form of this lemma.
u32 nPronunciations () const
Number of pronunciations assigned to this lemma.
LemmaPronunciationRange pronunciations () const
Iterator-range giving access to the set of pronunciations.
bool hasPronunciation (const Pronunciation *) const
Test if a pronunciation is one of the possible pronunciations for htis lemms.
bool hasSyntacticTokenSequence () const
Syntactic token sequence Under all normal circumstances the answer is "yes".
const SyntacticTokenSequence & syntacticTokenSequence () const
bool hasEvaluationTokenSequence () const
Evaluation token sequence.
u32 nEvaluationTokenSequences () const
Number of evaluation token sequences assigned to this lemma;
0, see above.
std::pair< EvaluationTokenSequenceIterator, EvaluationTokenSequenceIterator > evaluationTokenSequences () const
Iterator-range giving access to the set of pronunciations.
Public Member Functions inherited from Bliss::Token
Symbol symbol () const
A unique string identifier for the token.
Id id () const
The numerical ID of the token.
Protected Member Functions
void setName (Symbol)
void setOrthographicForms (const OrthographicFormList &orth)
void setSyntacticTokenSequence (const SyntacticTokenSequence &synt)
void addEvaluationTokenSequence (const EvaluationTokenSequence &eval)
Protected Member Functions inherited from Bliss::Token
Token (Id _id, Bliss::Symbol _symbol)
Token (Id _id)
Token (Bliss::Symbol _symbol)
void setId (Id id)
void setSymbol (Symbol s)
Private Attributes
OrthographicFormList orth_
LemmaPronunciation * pronunciations_
SyntacticTokenSequence syntacticTokens_
EvaluationTokenSequenceList evaluationTokensList_
Friends
class Lexicon
Additional Inherited Members
Static Public Attributes inherited from Bliss::Token
static const Id invalidId = -1
Detailed Description
An entry in the Bliss lexion.
See also
Bliss documentation
Definition at line 115 of file Bliss/Lexicon.hh.
Member Function Documentation
std::pair<EvaluationTokenSequenceIterator, EvaluationTokenSequenceIterator> Bliss::Lemma::evaluationTokenSequences () const inline
Iterator-range giving access to the set of pronunciations.
Definition at line 252 of file Bliss/Lexicon.hh.
Referenced by Flf::UnknownAlphabet::end(), Search::SearchSpace::filterStates(), and Search::LinearSearch::Pronunciation::Pronunciation().
bool Bliss::Lemma::hasEvaluationTokenSequence () const inline
Evaluation token sequence.
Under all normal circumstances the answer is "yes". You don't have to test for this.
Definition at line 239 of file Bliss/Lexicon.hh.
Referenced by Flf::UnknownAlphabet::end(), and Search::SearchSpace::filterStates().
bool Bliss::Lemma::hasName () const inline
Test for presence of a name.
Under all normal circumstances the answer is "yes". You don't have to test for this.
Definition at line 149 of file Bliss/Lexicon.hh.
Referenced by Flf::UnknownAlphabet::end().
bool Lemma::hasPronunciation (const Pronunciation * pron) const
Test if a pronunciation is one of the possible pronunciations for htis lemms.
This is used for preventing duplicate pronunciations.
Definition at line 48 of file Bliss/Lexicon.cc.
bool Bliss::Lemma::hasSyntacticTokenSequence () const inline
Syntactic token sequence Under all normal circumstances the answer is "yes".
You don't have to test for this.
Definition at line 227 of file Bliss/Lexicon.hh.
References require.
Referenced by Flf::decodeRescoreLm(), Flf::UnknownAlphabet::end(), and Lm::CheatingSegmentLm::setSegment().
Symbol Bliss::Lemma::name () const inline
A unique string identifier for the lemma.
The sole purpose of the name is to be used as a reference to the lemma lemma from an external data file (e.g. a word lattice).
Definition at line 159 of file Bliss/Lexicon.hh.
Referenced by Bliss::LemmaPronunciationAlphabet::symbol(), and Bliss::CorpusLexicalStatisticsVisitor::visitSpeechSegment().
u32 Bliss::Lemma::nEvaluationTokenSequences () const inline
Number of evaluation token sequences assigned to this lemma;
0, see above.
Definition at line 245 of file Bliss/Lexicon.hh.
OrthographicFormList::Size Bliss::Lemma::nOrthographicForms () const inline
Number of orthographic forms of this lemma.
Definition at line 164 of file Bliss/Lexicon.hh.
u32 Lemma::nPronunciations () const
Number of pronunciations assigned to this lemma.
Definition at line 41 of file Bliss/Lexicon.cc.
Referenced by Flf::UnknownAlphabet::end(), Search::Wfst::ExpandingFsaSearch::getCurrentBestSentence(), and Search::Wfst::Builder::CheckLabels::process().
const OrthographicFormList& Bliss::Lemma::orthographicForms () const inline
Set of orthographic forms of this lemma.
Definition at line 169 of file Bliss/Lexicon.hh.
Referenced by Flf::UnknownAlphabet::end().
OrthographicForm Bliss::Lemma::preferredOrthographicForm () const inline
Preferred (standard) orthographic form of this lemma.
Definition at line 174 of file Bliss/Lexicon.hh.
References require.
Referenced by Speech::LemmaPronunciationId_hash_map::init(), and Bliss::CorpusLexicalStatisticsVisitor::visitSpeechSegment().
LemmaPronunciationRange Bliss::Lemma::pronunciations () const inline
Iterator-range giving access to the set of pronunciations.
Definition at line 212 of file Bliss/Lexicon.hh.
Referenced by Search::Wfst::StateSequenceBuilder::createSymbols(), Flf::UnknownAlphabet::end(), Search::Wfst::ExpandingFsaSearch::getCurrentBestSentence(), Search::Wfst::LexiconBuilder::getPronsWithoutNonWords(), Bliss::LemmaPronunciationAlphabet::index(), Search::Wfst::Builder::CheckLabels::process(), Search::Wfst::Builder::RemoveEmptyPath::process(), and Am::AllophoneAlphabet::store().
The documentation for this class was generated from the following files:
Bliss/Lexicon.hh
Bliss/Lexicon.cc