Sprint: Speech::LemmaPronunciationId_hash_map Class Reference
Speech::LemmaPronunciationId_hash_map Class Reference
LemmaPronunciationId_hash_map.
#include <LatticeArcAccumulator.hh>
Public Member Functions
void init (Bliss::LexiconRef lexicon)
LemmaPronunciationId_hash_map.
void read (const std::string &filename)
void write (const std::string &filename)
Private Attributes
Bliss::LexiconRef lexicon
Detailed Description
LemmaPronunciationId_hash_map.
Definition at line 27 of file LatticeArcAccumulator.hh.
Member Function Documentation
void Speech::LemmaPronunciationId_hash_map::init (Bliss::LexiconRef lexicon)
LemmaPronunciationId_hash_map.
Definition at line 29 of file LatticeArcAccumulator.cc.
References Core::TextOutputStream::close(), Bliss::Pronunciation::format(), Speech::LatticeArcAccumulatorNode::paramLexiconFilename, Bliss::Lemma::preferredOrthographicForm(), Core::split(), and verify.
The documentation for this class was generated from the following files:
LatticeArcAccumulator.hh
LatticeArcAccumulator.cc