Sprint: Speech::LatticeSetReader Class Reference
Speech::LatticeSetReader Class Reference
LatticeSetReader.
#include <LatticeSetExtractor.hh>
Public Member Functions
LatticeSetReader (const Core::Configuration &)
LatticeSetReader.
virtual void leaveSpeechSegment (Bliss::SpeechSegment *)
virtual void initialize (Bliss::LexiconRef)
Override this function to achieve the lexicon of the input lattice set.
virtual std::string name () const
Public Member Functions inherited from Speech::LatticeSetProcessorRoot
LatticeSetProcessorRoot (const Core::Configuration &)
LatticeSetProcessorRoot.
virtual void signOn (CorpusVisitor &)
Override this function to sign on to services of the corpus visitor.
virtual void enterCorpus (Bliss::Corpus *)
virtual void leaveCorpus (Bliss::Corpus *)
virtual void enterRecording (Bliss::Recording *)
virtual void leaveRecording (Bliss::Recording *)
virtual void enterSegment (Bliss::Segment *)
virtual void leaveSegment (Bliss::Segment *)
virtual void enterSpeechSegment (Bliss::SpeechSegment *)
void initialize ()
Public Member Functions inherited from Speech::CorpusProcessor
CorpusProcessor (const Core::Configuration &c)
virtual void processSegment (Bliss::Segment *segment)
virtual void processSpeechSegment (Bliss::SpeechSegment *segment)
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Speech::LatticeSetProcessor
LatticeSetProcessor (const Core::Configuration &)
LatticeSetProcessor.
void setProcessor (Core::Ref< LatticeSetProcessor > processor)
This lattice set processor is used for cascading.
virtual void processWordLattice (Lattice::ConstWordLatticeRef, Bliss::SpeechSegment *)
Override this function to implement the processing of lattice sets.
virtual void getWordLatticeDescription (Lattice::WordLatticeDescription &)
Override this function to create the description of the output word lattices.
virtual void setWordLatticeDescription (const Lattice::WordLatticeDescription &)
Override this function to achieve the attributes of the input lattice set.
virtual void setSegmentwiseFeatureExtractor (Core::Ref< SegmentwiseFeatureExtractor >)
virtual void setAlignmentGenerator (Core::Ref< PhonemeSequenceAlignmentGenerator >)
virtual void logComputationTime () const
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Public Member Functions inherited from Speech::LatticeSetExtractor
LatticeSetExtractor (const Core::Configuration &)
Private Types
typedef LatticeSetProcessorRoot Precursor
typedef std::vector< std::string > LatticeReaders
Private Member Functions
void initializeReaders ()
void appendAcousticReaders ()
void appendEmissionReaders ()
void appendTdpReaders ()
void appendPronunciationReaders ()
void appendLmReaders ()
void appendCombinedLmReaders ()
void appendReaders ()
void appendPassReaders ()
Private Attributes
LatticeReaders readers_
Lattice::ArchiveReader * archiveReader_
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Speech::CorpusProcessor
void reportRealTime (Flow::Time)
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Speech::CorpusProcessor
Core::XmlChannel channelTimer_
Core::Timer timer_
Protected Attributes inherited from Core::Configurable
Configuration config
Protected Attributes inherited from Speech::LatticeSetProcessor
f64 timeProcessSegment_
Core::Ref< LatticeSetProcessor > processor_
Static Protected Attributes inherited from Speech::LatticeSetExtractor
static const Core::ParameterStringVector paramAcousticExtractors
LatticeSetExtractor.
static const Core::ParameterStringVector paramEmissionExtractors
static const Core::ParameterStringVector paramNnEmissionExtractors
static const Core::ParameterStringVector paramTheanoEmissionExtractors
static const Core::ParameterStringVector paramTdpExtractors
static const Core::ParameterStringVector paramPronunciationExtractors
static const Core::ParameterStringVector paramLmExtractors
static const Core::ParameterStringVector paramCombinedLmExtractors
static const Core::ParameterStringVector paramRestorers
static const Core::ParameterStringVector paramReaders
static const Core::ParameterStringVector paramDistanceExtractors
static const Core::ParameterStringVector paramPosteriorExtractors
static const Core::ParameterStringVector paramPassExtractors
Detailed Description
LatticeSetReader.
Definition at line 138 of file LatticeSetExtractor.hh.
Constructor & Destructor Documentation
LatticeSetReader::LatticeSetReader (const Core::Configuration & c)
LatticeSetReader.
Definition at line 504 of file LatticeSetExtractor.cc.
References Core::Component::criticalError(), Core::Component::log(), Speech::LatticeSetExtractor::paramAcousticExtractors, Speech::LatticeSetProcessor::processWordLattice(), and require.
Member Function Documentation
void LatticeSetReader::initialize (Bliss::LexiconRef lexicon) virtual
Override this function to achieve the lexicon of the input lattice set.
Reimplemented from Speech::LatticeSetProcessorRoot.
Definition at line 628 of file LatticeSetExtractor.cc.
References Core::Component::error(), Lattice::Core::Component::hasFatalErrors(), and verify.
The documentation for this class was generated from the following files:
LatticeSetExtractor.hh
LatticeSetExtractor.cc