Sprint: Search::HMMStateNetwork Class Reference
Search::HMMStateNetwork Class Reference
Classes
class ChangePlan
The change is applied when apply() is called.
struct CleanupResult
class EfficientBatchTargetIterator
class EfficientSingleTargetIterator
struct SuccessorIterator
Public Types
enum { EmptyTreeIndex = 0 }
enum { DiskFormatVersion = 1 }
typedef Tools::BatchIndexIterator< SubTreeListId, StateId, InvalidBatchId, 0 > SubTreeIterator
Public Member Functions
Tree & tree (TreeIndex index)
****** STATE MANAGEMENT ******************************************************************************************
inline_ HMMState & state (StateId state)
Do not keep pointers to the returned state, the address may change when the network is manipulated.
const HMMState & state (StateId state) const
Do not keep pointers to the returned state, the address may change when the network is manipulated.
TreeIndex allocateTree ()
Allocates a new tree.
StateId allocateTreeNode (TreeIndex parent)
Allocates a new subtree, and adds it into the subtree list of the given parent.
u32 getNodeCount (TreeIndex parent)
Returns the count of nodes contained by the tree.
StateId getTreeNode (TreeIndex parent, u32 number)
Returns the number th node contained in the given parent tree.
u32 getNodeNumber (TreeIndex parent, StateId node)
Returns the number of nodes contained by the given parent tree.
u32 getNodeNumberCleanStructure (TreeIndex parent, StateId node)
Much faster version of getNodeNumber, that only works when the structure has been cleaned.
u32 treeCount () const
Returns the total number of trees, which is the maximum upper bound for a valid TreeIndex.
u32 stateCount () const
Returns the total number of nodes, which is the maximum upper bound for a valid TreeNodeIndex.
CleanupResult cleanup (std::list< Search::StateId > startNodes, Search::TreeIndex masterTree, bool clearDeadEnds=true, bool onlyBatches=false)
Completely removes all trees and nodes that are not reachable from the given start-nodes, compressing the structure.
void addNodeToEdge (SuccessorBatchId &list, StateId target)
****** EDGE MANAGEMENT *******************************************************************************************
void addOutputToEdge (SuccessorBatchId &list, u32 outputIndex)
Adds the given target to the list of targets for the given edge. The referenced id will be changed.
void addTargetToNode (StateId node, StateId target)
void addOutputToNode (StateId node, u32 outputIndex)
void removeTargetFromNode (StateId node, StateId target)
void removeOutputFromNode (StateId node, u32 outputIndex)
void clearOutputEdges (StateId node)
Clears all connections behind the given node. The memory will be lost unless a cleanup is done afterwards.
u32 getChecksum () const
ChangePlan change (StateId node)
SuccessorIterator batchSuccessors (Search::SuccessorBatchId list) const
SuccessorIterator successors (StateId node) const
SuccessorIterator successors (const HMMState &node) const
template<class FunctionObject >
void efficientlyIterateTargets (const HMMState &node, FunctionObject &object) const
std::set< StateId > targetNodeSet (StateId node) const
Convenience function: Returns the set of target nodes of the given tree node.
std::set< uint > targetOutputSet (StateId node) const
Convenience function: Returns the set of target outputs of the given tree node.
std::set< StateId > targetSet (StateId node) const
Convenience function: Returns the set of target nodes and outputs of the given tree node Outputs are encoded with IS_OUTPUT and OUTPUT_FROM_INDEX.
template<bool considerOutputs>
std::pair< int, int > batchSuccessorsSimple (SuccessorBatchId list) const
Returns -1, -1 if this simple version does not work. Then "edgeTargets" has to be used.
std::pair< int, int > batchSuccessorsSimpleIgnoreLabels (SuccessorBatchId list) const
Does not work with single-batches! Those must be checked before.
std::pair< int, int > batchNodeRange (SuccessorBatchId batch) const
Reads out the node-range associated to the given batch.
bool write (Core::MappedArchiveWriter writer)
bool read (Core::MappedArchiveReader reader)
Returns whether reading was successful. Reading will fail on format version mismatch.
const std::vector< StateId > & edgeTargetBatches () const
Private Member Functions
void addTargetToEdge (SuccessorBatchId &batch, u32 target)
u32 countReachableEnds (std::vector< u32 > &counts, StateId node) const
Private Attributes
std::vector< StateId > subTreeListBatches_
std::vector< HMMState > states_
Tools::BatchManager< SubTreeListId, StateId, HMMState, true, InvalidBatchId > subTreeManager_
std::vector< SuccessorBatchId > edgeTargetLists_
std::vector< StateId > edgeTargetBatches_
Tools::BatchManager< SuccessorBatchId, StateId, HMMState, false, InvalidBatchId, SingleSuccessorBatchMask > edgeTargetManager_
std::vector< Tree > trees_
Detailed Description
Definition at line 113 of file TreeStructure.hh.
Member Function Documentation
void Search::HMMStateNetwork::addNodeToEdge (SuccessorBatchId & list, StateId target)
****** EDGE MANAGEMENT *******************************************************************************************
Adds the given target to the list of targets for the given edge. The referenced id will be changed.
Definition at line 99 of file TreeStructure.cc.
References verify.
Referenced by Search::ConvertTree::convert().
void Search::HMMStateNetwork::addOutputToEdge (SuccessorBatchId & list, u32 outputIndex)
Adds the given target to the list of targets for the given edge. The referenced id will be changed.
Definition at line 112 of file TreeStructure.cc.
References Search::ID_FROM_LABEL().
Referenced by Search::PersistentStateTree::cleanup(), and Search::ConvertTree::convert().
TreeIndex Search::HMMStateNetwork::allocateTree ()
Allocates a new tree.
Definition at line 30 of file TreeStructure.cc.
StateId Search::HMMStateNetwork::allocateTreeNode (TreeIndex parent)
Allocates a new subtree, and adds it into the subtree list of the given parent.
As many subtrees for the same parent should be allocated in a row as possible, so batch-merging can happen Returns a fully valid subtree(With initialized edge-list)
Definition at line 35 of file TreeStructure.cc.
References verify.
Referenced by Search::ConvertTree::convert().
std::pair< int, int > Search::HMMStateNetwork::batchNodeRange (SuccessorBatchId batch) const inline
Reads out the node-range associated to the given batch.
Does not verify whether the batch is a single-batch or has successor-batches, this has to be checked beforehand.
Definition at line 467 of file TreeStructure.hh.
template<bool considerOutputs> std::pair< int, int > Search::HMMStateNetwork::batchSuccessorsSimple (SuccessorBatchId list) const inline
Returns -1, -1 if this simple version does not work. Then "edgeTargets" has to be used.
Definition at line 444 of file TreeStructure.hh.
References Search::IS_LABEL(), and Search::SingleSuccessorBatchMask.
Referenced by Search::StaticSearchAutomaton::buildBatches(), and Search::SearchSpace::eventuallyDeactivateTree().
std::pair< int, int > Search::HMMStateNetwork::batchSuccessorsSimpleIgnoreLabels (SuccessorBatchId list) const inline
Does not work with single-batches! Those must be checked before.
Definition at line 429 of file TreeStructure.hh.
Referenced by Search::SearchSpace::eventuallyDeactivateTree().
HMMStateNetwork::CleanupResult Search::HMMStateNetwork::cleanup (std::list< Search::StateId > startNodes, Search::TreeIndex masterTree, bool clearDeadEnds = true, bool onlyBatches = false)
Completely removes all trees and nodes that are not reachable from the given start-nodes, compressing the structure.
Mark all reachable trees and nodes
Todo:
Build a topology and order the nodes in a stable way based on that
Check again and make sure the same count of nodes is reachable
Definition at line 156 of file TreeStructure.cc.
References Tools::BatchManager< BatchIdType, NodeIdType, NodeType, manageNodes, invalidBatch_, singleBatchMask_, mergeBatches_, debug_ >::appendToBatch(), Search::IS_LABEL(), Core::Component::log(), Core::Application::us(), verify, and Search::SubTreeWalker< Token, Base >::visit().
Referenced by Search::PersistentStateTree::cleanup(), and Search::PersistentStateTree::removeOutputs().
void Search::HMMStateNetwork::clearOutputEdges (StateId node)
Clears all connections behind the given node. The memory will be lost unless a cleanup is done afterwards.
Definition at line 41 of file TreeStructure.cc.
References Search::ID_FROM_LABEL(), Search::IS_LABEL(), Search::LABEL_FROM_ID(), and verify.
u32 Search::HMMStateNetwork::getNodeCount (Search::TreeIndex parent) inline
Returns the count of nodes contained by the tree.
Definition at line 471 of file TreeStructure.hh.
u32 Search::HMMStateNetwork::getNodeNumber (TreeIndex parent, StateId node) inline
Returns the number of nodes contained by the given parent tree.
Definition at line 481 of file TreeStructure.hh.
References Tools::BatchIndexIterator< BatchIdType, NodeIdType, invalidBatch_, singleBatchMask_, debug_ >::countUntil().
u32 Search::HMMStateNetwork::getNodeNumberCleanStructure (TreeIndex parent, StateId node) inline
Much faster version of getNodeNumber, that only works when the structure has been cleaned.
Definition at line 240 of file TreeStructure.hh.
StateId Search::HMMStateNetwork::getTreeNode (Search::TreeIndex parent, u32 number) inline
Returns the number th node contained in the given parent tree.
Definition at line 475 of file TreeStructure.hh.
bool Search::HMMStateNetwork::read (Core::MappedArchiveReader reader)
Returns whether reading was successful. Reading will fail on format version mismatch.
Definition at line 130 of file TreeStructure.cc.
References Core::MappedArchiveReader::good().
Referenced by Search::PersistentStateTree::read().
inline_ HMMState& Search::HMMStateNetwork::state (StateId state) inline
Do not keep pointers to the returned state, the address may change when the network is manipulated.
Definition at line 211 of file TreeStructure.hh.
Referenced by Search::LanguageModelLookahead::ConstructionTree::build(), Search::StaticSearchAutomaton::buildBatches(), Search::PersistentStateTree::cleanup(), Search::ConvertTree::convert(), Search::PersistentStateTree::dumpDotGraph(), Search::SearchSpace::eventuallyDeactivateTree(), Search::StaticSearchAutomaton::fillStateDepths(), Search::SearchSpace::filterStates(), Search::SearchSpace::findWordEndsInternal(), Search::SearchSpace::hypothesizeEpsilonPronunciations(), and AdvancedTreeSearch::AcousticLookAhead::length().
const HMMState& Search::HMMStateNetwork::state (StateId state) const inline
Do not keep pointers to the returned state, the address may change when the network is manipulated.
Definition at line 217 of file TreeStructure.hh.
u32 Search::HMMStateNetwork::stateCount () const
Returns the total number of nodes, which is the maximum upper bound for a valid TreeNodeIndex.
Definition at line 120 of file TreeStructure.cc.
Referenced by Search::LanguageModelLookahead::ConstructionTree::build(), Search::StaticSearchAutomaton::buildBatches(), AdvancedTreeSearch::LanguageModelLookahead::buildCompressesLookaheadStructure(), Search::StaticSearchAutomaton::buildNetwork(), Search::PersistentStateTree::cleanup(), Search::PersistentStateTree::dumpDotGraph(), Search::StaticSearchAutomaton::fillStateDepths(), AdvancedTreeSearch::AcousticLookAhead::initializeModelsFromNetwork(), AdvancedTreeSearch::AcousticLookAhead::length(), Search::SearchSpace::optimizeSilenceInWordLattice(), Search::PersistentStateTree::removeOutputs(), and Search::SearchSpace::setAllowHmmSkips().
std::set<StateId> Search::HMMStateNetwork::targetNodeSet (StateId node) const inline
Convenience function: Returns the set of target nodes of the given tree node.
Definition at line 360 of file TreeStructure.hh.
References Search::HMMState::successors.
std::set<uint> Search::HMMStateNetwork::targetOutputSet (StateId node) const inline
Convenience function: Returns the set of target outputs of the given tree node.
Definition at line 369 of file TreeStructure.hh.
References Search::HMMState::successors.
std::set<StateId> Search::HMMStateNetwork::targetSet (StateId node) const inline
Convenience function: Returns the set of target nodes and outputs of the given tree node Outputs are encoded with IS_OUTPUT and OUTPUT_FROM_INDEX.
Definition at line 379 of file TreeStructure.hh.
References Search::HMMState::successors.
Tree& Search::HMMStateNetwork::tree (TreeIndex index) inline
****** STATE MANAGEMENT ******************************************************************************************
Do not keep pointers/references to the returned tree, the address may change
Definition at line 205 of file TreeStructure.hh.
u32 Search::HMMStateNetwork::treeCount () const
Returns the total number of trees, which is the maximum upper bound for a valid TreeIndex.
Definition at line 116 of file TreeStructure.cc.
bool Search::HMMStateNetwork::write (Core::MappedArchiveWriter writer)
Definition at line 124 of file TreeStructure.cc.
Referenced by Search::PersistentStateTree::write().
The documentation for this class was generated from the following files:
TreeStructure.hh
TreeStructure.cc