Sprint: Core::Channel::Manager Class Reference
Core::Channel::Manager Class Reference
Central management of channel output.
#include <Channel.hh>
Public Member Functions
Manager (const Core::Configuration &, bool outputXmlHeader)
Target * get (TargetType, const std::string &)
void flushAll ()
Write any pending output on all channels.
void flushTty ()
Write any pending output on channels connected to the terminal.
void blockTty ()
Temporarily block all output on the terminal.
void unblockTty ()
Re-enable TTY targets.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Member Functions
static Manager * us ()
Return the (single) instance.
Private Types
typedef StringHashMap< Channel::Target * > TargetMap
typedef std::list< Channel::Target * > TargetList
Private Member Functions
Channel::Target * createTarget (TargetType, const Core::Configuration &, const std::string &defaultFilename)
Private Member Functions inherited from Core::Mutex
Mutex (const pthread_mutex_t &m)
bool lock ()
bool unlock ()
bool release ()
bool trylock ()
Private Attributes
u32 blockedTargetBufferLimit_
std::streambuf * originalStreamBuffers [3]
TargetMap targets_
TargetList ttyTargets_
Static Private Attributes
static const Core::ParameterInt paramBlockedTargetBufferLimit
static Manager * singleton_ = 0
Additional Inherited Members
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Central management of channel output.
The manager is usually owned the Core::Application instance. Singleton: this class must be instantiated only once.
Definition at line 156 of file Channel.hh.
Member Function Documentation
void Channel::Manager::blockTty ()
Temporarily block all output on the terminal.
Also flushes buffers. This is used to prevent corrupting the progress indicator. You MUST release the TTY targets with unblockTty(). Between calls to blockTty() and unblockTty(), output to TTY targets is retained in internal buffers. (However, the implementation is not strict: If the buffers grow unduely large they are flushed anyway. The limit in configurable.)
Definition at line 347 of file Channel.cc.
Referenced by Core::ProgressIndicator::start().
void Channel::Manager::flushAll ()
Write any pending output on all channels.
Definition at line 332 of file Channel.cc.
void Channel::Manager::flushTty ()
Write any pending output on channels connected to the terminal.
Definition at line 340 of file Channel.cc.
void Channel::Manager::unblockTty ()
Re-enable TTY targets.
Definition at line 356 of file Channel.cc.
References defect.
Referenced by Core::ProgressIndicator::finish().
Channel::Manager * Channel::Manager::us () static
Return the (single) instance.
Definition at line 312 of file Channel.cc.
Referenced by Core::Channel::Channel(), Core::ProgressIndicator::finish(), and Core::ProgressIndicator::start().
The documentation for this class was generated from the following files:
Channel.hh
Channel.cc