Sprint: Signal::KL2FullCovMonoGaussianModel Class Reference
Signal::KL2FullCovMonoGaussianModel Class Reference
Public Member Functions
KL2FullCovMonoGaussianModel (u32 dim)
KL2FullCovMonoGaussianModel (u32 dim, f32 alpha)
KL2FullCovMonoGaussianModel (u32 dim, const std::vector< KL2FullCovMonoGaussianModel > &models)
KL2FullCovMonoGaussianModel (u32 dim, f32 alpha, const std::vector< KL2FullCovMonoGaussianModel > &models)
const f32 score () const
void computeKL2 (const KL2FullCovMonoGaussianModel &x, const KL2FullCovMonoGaussianModel &y)
compute the KL2 distance using relative likelihoods of the left and right model
void mergeModels (const KL2FullCovMonoGaussianModel &x, const KL2FullCovMonoGaussianModel &y)
First, the mean vectors and variance matrices of the left FullCovMonoGaussianModel x and right FullCovMonoGaussianModel y are merged into the current model.
Public Member Functions inherited from Signal::BICFullCovMonoGaussianModel
BICFullCovMonoGaussianModel (u32 dim)
BICFullCovMonoGaussianModel (u32 dim, f32 alpha)
BICFullCovMonoGaussianModel (u32 dim, const std::vector< BICFullCovMonoGaussianModel > &models)
BICFullCovMonoGaussianModel (u32 dim, f32 alpha, const std::vector< BICFullCovMonoGaussianModel > &models)
const f32 likelihood () const
const f32 score () const
const f32 stopscore () const
void computeGLR (const BICFullCovMonoGaussianModel &x, const BICFullCovMonoGaussianModel &y)
compute Brandt's generalized likelihood ratio (GLR) for the BIC criterion.
void finalize (const std::vector< BICFullCovMonoGaussianModel >)
useless??
void finalize ()
finalize the mean vector and variance matrix
void mergeModels (const BICFullCovMonoGaussianModel &x, const BICFullCovMonoGaussianModel &y)
First, the mean vectors and variance matrices of the left FullCovMonoGaussianModel x and right FullCovMonoGaussianModel y are merged into the current model.
Public Member Functions inherited from Signal::FullCovMonoGaussianModel
FullCovMonoGaussianModel (u32 dim)
represented as N(logDeterminant(variance))
const u32 dim () const
returns the feature dimension
const u32 nFrames () const
returns the number of frames seen so far
const Math::Vector< f64 > & mean () const
returns the mean vector of size dim()
const Math::Matrix< f64 > & variance () const
returns the variance matrix of size dim()xdim()
bool accumulate (const std::vector< f32 > &vec)
update the mean vector, the variance matrix, and the frame count
bool finalize ()
finalize the mean vector and variance matrix
void mergeModels (const FullCovMonoGaussianModel &x, const FullCovMonoGaussianModel &y)
merges the mean vectors and variance matrices of the left FullCovMonoGaussianModel x and right FullCovMonoGaussianModel y into the current model.
void mergeMeans (const FullCovMonoGaussianModel &x, const FullCovMonoGaussianModel &y)
merges the mean vectors of the left FullCovMonoGaussianModel x and right FullCovMonoGaussianModel y
void mergeVariance (const FullCovMonoGaussianModel &x, const FullCovMonoGaussianModel &y)
merges the variance matrices of the left FullCovMonoGaussianModel x and right FullCovMonoGaussianModel y
void reset (f32 x)
?
const f32 computeComplexity ()
BIC is a likelihood criterion penalized by the model complexity: the number of parameters in the model.
void computeL ()
compute the likelihood as N(logDeterminant(variance))
const f32 relativeLikelihood (const FullCovMonoGaussianModel &x) const
compute the relative likelihood
Private Attributes
f32 kl2_
Additional Inherited Members
Protected Attributes inherited from Signal::FullCovMonoGaussianModel
Math::Vector< f64 > mean_
Math::Matrix< f64 > variance_
u32 nFrames_
f32 likelihood_
Detailed Description
Definition at line 219 of file SegmentClustering.hh.
Member Function Documentation
void KL2FullCovMonoGaussianModel::computeKL2 (const KL2FullCovMonoGaussianModel & x, const KL2FullCovMonoGaussianModel & y)
compute the KL2 distance using relative likelihoods of the left and right model
Definition at line 153 of file SegmentClustering.cc.
References Signal::FullCovMonoGaussianModel::relativeLikelihood().
Referenced by mergeModels().
void KL2FullCovMonoGaussianModel::mergeModels (const KL2FullCovMonoGaussianModel & x, const KL2FullCovMonoGaussianModel & y)
First, the mean vectors and variance matrices of the left FullCovMonoGaussianModel x and right FullCovMonoGaussianModel y are merged into the current model.
Second, the KL2 distance is calculated for the merged, the left, and the right model.
Definition at line 160 of file SegmentClustering.cc.
References computeKL2(), and Signal::BICFullCovMonoGaussianModel::mergeModels().
const f32 Signal::KL2FullCovMonoGaussianModel::score () const inline
Returns
the KL2 distance
Definition at line 235 of file SegmentClustering.hh.
The documentation for this class was generated from the following files:
SegmentClustering.hh
SegmentClustering.cc