Sprint: TrapezeRastaFilterBuilder Class Reference
TrapezeRastaFilterBuilder Class Reference
TrapezeRasta Filter Builder.
Public Member Functions
TrapezeRastaFilterBuilder (const Core::Configuration &c)
virtual FilterBank::Frequency normalizedCenterPosition () const
virtual bool setStart ()
Just round the index of the start position.
virtual bool setEnd ()
Just round the index of the end position.
Public Member Functions inherited from Signal::FilterBank::FilterBuilder
FilterBuilder (const Core::Configuration &)
Core::Ref< FilterBank::Filter > create (Frequency center, Frequency width, Frequency minimumFrequency, Frequency maximumFrequency, Math::UnaryAnalyticFunctionRef discreteToContinuousFunction, Math::UnaryAnalyticFunctionRef warpingFunction, bool warpDifferentialUnit)
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Protected Member Functions
virtual FilterBank::FilterWeight weight (FilterBank::Frequency) const
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Private Member Functions
FilterBank::Frequency normalizedMiddleBorder () const
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Attributes inherited from Signal::FilterBank::FilterBuilder
size_t start_
Start of filter to build (.
size_t end_
End of filter to build (.
std::vector< FilterWeight > weights_
Weights of filter to build (.
Frequency center_
Center point of filter to build.
Frequency width_
Width of filter to build.
Frequency maximumFrequency_
Maximal and minimal input frequency.
Frequency minimumFrequency_
Math::UnaryAnalyticFunctionRef discreteToContinuousFunction_
Mapping from discrete input indices to continuous values.
Math::UnaryAnalyticFunctionRef continuousToDiscreteFunction_
Mapping from continuous values to discrete input indices.
Math::UnaryAnalyticFunctionRef derivedWarpingFunction_
Used for calculating the delta unit in the warped domain: delta warped-omega = d warping-function / d omega * delta omega.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
TrapezeRasta Filter Builder.
(based on the trapeze filter in the ICSI-Sprachcore-Toolkit (Rasta.c))
Definition at line 283 of file Filterbank.cc.
Member Function Documentation
bool TrapezeRastaFilterBuilder::setEnd () virtual
Just round the index of the end position.
Reimplemented from Signal::FilterBank::FilterBuilder.
Definition at line 334 of file Filterbank.cc.
References Signal::FilterBank::FilterBuilder::center_, Signal::FilterBank::FilterBuilder::continuousToDiscreteFunction_, Core::Component::error(), Signal::FilterBank::FilterBuilder::maximumFrequency_, Core::round(), Signal::FilterBank::FilterBuilder::start_, and Signal::FilterBank::FilterBuilder::width_.
bool TrapezeRastaFilterBuilder::setStart () virtual
Just round the index of the start position.
Reimplemented from Signal::FilterBank::FilterBuilder.
Definition at line 318 of file Filterbank.cc.
References Signal::FilterBank::FilterBuilder::center_, Signal::FilterBank::FilterBuilder::continuousToDiscreteFunction_, Core::Component::error(), Core::round(), Signal::FilterBank::FilterBuilder::start_, and Signal::FilterBank::FilterBuilder::width_.
The documentation for this class was generated from the following file:
Filterbank.cc