Sprint: Core::MMappedFile Class Reference
Core::MMappedFile Class Reference
This class represents a simple memory-mapped file.
#include <MappedArchive.hh>
Public Member Functions
bool load (std::string file)
Maps the whole file.
void unload ()
Unmaps the file.
template<class Type >
const Type * data (size_t offset=0) const
Access the mapped data at a given offset in bytes.
size_t size () const
Returns the size of the mapped file.
Private Attributes
char * data_
int desc_
size_t size_
Detailed Description
This class represents a simple memory-mapped file.
The whole contents of the file is mapped upon calling "load", and can be accessed through the data(offset) member function.
Definition at line 33 of file MappedArchive.hh.
Member Function Documentation
template<class Type > const Type* Core::MMappedFile::data (size_t offset = 0) const inline
Access the mapped data at a given offset in bytes.
Definition at line 45 of file MappedArchive.hh.
References size().
Referenced by Core::ConstantVector< LookaheadId >::edit().
bool Core::MMappedFile::load (std::string file)
Maps the whole file.
Definition at line 61 of file MappedArchive.cc.
Referenced by Core::MappedArchive::getReader().
size_t Core::MMappedFile::size () const
Returns the size of the mapped file.
Definition at line 93 of file MappedArchive.cc.
References Core::Component::log(), and Core::Application::us().
Referenced by data(), Core::ConstantVector< LookaheadId >::edit(), and Core::ConstantVector< LookaheadId >::resize().
void Core::MMappedFile::unload ()
Unmaps the file.
Definition at line 82 of file MappedArchive.cc.
The documentation for this class was generated from the following files:
MappedArchive.hh
MappedArchive.cc