Sprint: Core::Component Class Reference
Core::Component Class Reference
Base class for configurable components with logging and error logging facilities.
#include <Component.hh>
Inherits Core::Configurable.
Inherited by AdvancedTreeSearch::LanguageModelLookahead, Search::Aligner::SearchSpace, Am::AcousticModelAdaptor [virtual], Am::AdaptationTree, Am::AllophoneAlphabet, Am::AllophoneStateAlphabet, Am::ClassicHmmTopologySet [virtual], Am::ClassicStateTying [virtual], Am::HmmTopology, Am::HmmTopologySet, Am::LexiconUtilities [virtual], Am::PropertyMapDiff [private], Am::StateTying [virtual], Am::TransitionModel [virtual], Bliss::CorpusDescription, Bliss::CorpusKey [virtual], Bliss::CorpusStatisticsVisitor, Bliss::EditDistance, Bliss::Evaluator, Bliss::Lexicon, Bliss::OrthographicParser [private], Bliss::TheanoCommunicator, Cart::BinaryTree, Cart::ClusterList [private], Cart::DecisionTreeTrainer, Cart::ExampleList [private], Cart::PropertyMapDiff, Cart::Scorer, Cart::Training, Lm::CompressedVectorFactory< float >, Core::Application, Core::Archive, Core::CodeGenerator, Core::FormatSet, Core::ObjectCache< List > [virtual], Core::XmlParser, Nn::Criterion< f32 >, Nn::Criterion< f64 >, Nn::Criterion< Float >, Nn::Criterion< T >, Nn::Estimator< f32 > [virtual], Nn::Estimator< f64 > [virtual], Nn::Estimator< Float > [virtual], Nn::Estimator< FloatT > [virtual], Signal::FilterBank::Boundary [virtual], Signal::FilterBank::FilterBuilder [virtual], Flf::Archive, Flf::ClusterBuilder, Flf::FwdBwdBuilder::Internal, Flf::FwdBwdPruner::Internal, Flf::HtkSlfBuilder, Flf::LatticeReader, Flf::LatticeWriter, Flf::LayeredComponent [virtual], Flf::LocalCostDecoderBuilder, Flf::MinimumFrameWerDecoder, Flf::MinimumFrameWerDecoder::SearchSpace, Flf::Network, Flf::Node, Flf::Processor [virtual], Flf::PushForwardRescorer, Flf::SegmentwiseFeatureExtractor [virtual], Flf::TimeAlignmentBuilder::Internal, Flow::AbstractNode [virtual], Flow::Cache [virtual], Flow::ExternalInput< T > [virtual], Flow::NodeBuilder [virtual], Flow::NormFunction< T > [virtual], Flow::ScalarToStringConverter< In > [virtual], Flow::StringConverter< Out > [virtual], Flow::VectorToScalarConverter< In, Out > [virtual], Fsa::Archive, Search::Wfst::FstNetwork< FstLib::ComposeFst< FstLib::StdArc > >, Search::Wfst::FstNetwork< OpenFst::VectorFst >, InternalIc::Icb, InternalIc::Xi, Speech::LinearSegmenter::Delimiter, Lm::ClassLm [virtual], Lm::ClassMapping, Lm::CompressedVectorFactory< T >, Lm::LanguageModel [virtual], Lm::SoftmaxAdapter, Lm::StateManager, Math::AnalyticFunctionFactory, Math::EigenvalueProblem [virtual], Math::Lapack::EigenvalueProblem [virtual], Mc::Component [virtual], Speech::MetricFsaBuilder< Fsa::ConstAutomatonRef >, Speech::MetricFsaBuilder< Lattice::ConstWordLatticeRef >, Mm::AbstractMixtureSetEstimator [virtual], Mm::Adaptor, Mm::AdaptorEstimator, Mm::DensityClusteringBase, Mm::FeatureScorer [virtual], Mm::ISmoothingMixtureSetEstimator [virtual], Mm::IterationConstants, Mm::MixtureSetReader, Mm::MixtureSetReader::Reader, Mm::MixtureSetSplitter [virtual], Nn::NeuralNetwork< f32 > [virtual], Nn::NeuralNetwork< f64 > [virtual], Nn::NeuralNetwork< FeatureType > [virtual], Nn::NeuralNetwork< Float > [virtual], Nn::NeuralNetwork< FloatT > [virtual], Nn::NeuralNetworkLayer< f32 > [virtual], Nn::NeuralNetworkLayer< f64 > [virtual], Nn::NeuralNetworkTrainer< f32 > [virtual], Nn::NeuralNetworkTrainer< f64 > [virtual], Nn::NeuralNetworkTrainer< Float > [virtual], Nn::NeuralNetworkTrainer< FloatT > [virtual], Nn::AllophoneStateFsaExporter [private], Nn::BatchEstimator< T > [virtual], Nn::ClassLabelWrapper, Nn::Criterion< FloatT >, Nn::Estimator< T > [virtual], Nn::NeuralNetwork< T > [virtual], Nn::NeuralNetworkLayer< T > [virtual], Nn::NeuralNetworkTrainer< T > [virtual], Nn::Prior< T >, Nn::PythonControl [virtual], Nn::PythonControl::Internal, Nn::Regularizer< T > [virtual], Flow::NormFunction< content > [virtual], Flow::NormFunction< Value > [virtual], Core::ObjectCache< Core::MruObjectCacheList< std::string, Accumulator, Core::StringHash, Core::StringEquality > > [virtual], Core::ObjectCache< Core::MruObjectCacheList< std::string, Core::IoRef< Mm::Adaptor >, Core::StringHash, Core::StringEquality > > [virtual], Core::ObjectCache< Core::MruObjectCacheList< std::string, Core::IoRef< Mm::AdaptorEstimator >, Core::StringHash, Core::StringEquality > > [virtual], Core::ObjectCache< Core::MruObjectCacheList< std::string, HistogramVector, Core::StringHash, Core::StringEquality > > [virtual], Core::ObjectCache< Core::MruObjectCacheList< std::string, HistogramVector< Value >, Core::StringHash, Core::StringEquality > > [virtual], Nn::Prior< f32 >, Nn::Prior< Float >, Nn::Regularizer< f32 > [virtual], Nn::Regularizer< f64 > [virtual], Nn::Regularizer< Float > [virtual], Nn::Regularizer< FloatT > [virtual], Search::Aligner, Search::Aligner::WordLatticeBuilder, Search::DynamicBeamPruningStrategy, Search::LanguageModelLookahead, Search::LatticeHandler, Search::MinimumBayesRiskSearch, Search::SearchAlgorithm [virtual], Search::SearchSpace, Search::StateTree [virtual], Search::StaticSearchAutomaton, Search::Wfst::Builder::Operation, Search::Wfst::Builder::Resources, Search::Wfst::CombinedGrammarFst, Search::Wfst::ComposedGrammarFst, Search::Wfst::CompressedNetwork, Search::Wfst::ContextTransducerBuilder, Search::Wfst::DynamicGrammarFst, Search::Wfst::FstNetwork< F >, Search::Wfst::HmmListConverter, Search::Wfst::LatticeArchive, Search::Wfst::LexicalFstFactory, Search::Wfst::LexiconBuilder, Search::Wfst::NonWordTokens [private], Search::Wfst::StateSequenceBuilder, Search::Wfst::StateTreeConverter, Search::WordSequenceAligner, Signal::AprioriProbability [virtual], Signal::BayesClassification [virtual], Signal::Delimiter, Signal::DivideByMean, Signal::FilterBank [virtual], Signal::FormantExtraction [virtual], Signal::LikelihoodFunction [virtual], Signal::MeanAndVarianceNormalization, Signal::MeanAndVarianceNormalization1D, Signal::MeanEstimator [virtual], Signal::MeanNormNormalization, Signal::ScatterMatrixEstimator [virtual], Signal::ScatterTransform [virtual], Signal::SegmentClustering< Model > [virtual], Speech::AlignedFeatureProcessor [virtual], Speech::AlignmentToSequenceSelectionNode::Set, Speech::AllophoneStateGraphBuilder, Speech::Confidences, Speech::CorpusProcessor [virtual], Speech::CorpusVisitor, Speech::FsaCache, Speech::LabeledFeatureProcessor [virtual], Speech::LatticeExtractor, Speech::LatticeSetExtractor [virtual], Speech::LatticeSetProcessor [virtual], Speech::LinearSegmenter, Speech::MetricFsaBuilder< BuilderInput >, Speech::MixtureSetTrainer [virtual], Speech::NBestListExtractor, Speech::PhonemeSequenceAlignmentGenerator::Cache, Speech::Recognizer [virtual], Speech::SegmentwiseAlignmentGenerator, Speech::SigmoidFunction, Tensorflow::GraphLoader [virtual], Tensorflow::Session, Tensorflow::TensorMap< Info >, Tensorflow::TensorMap< TensorInputInfo >, Tensorflow::TensorMap< TensorOutputInfo >, Tester, and Translation::ConditionalLexicon.
Classes
class Message
Helper class for generating error messages.
Public Member Functions
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Protected Types
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Private Types
enum ErrorAction { ErrorActionIgnore, ErrorActionDelayedExit, ErrorActionImmediateExit }
typedef Configurable Precursor
Private Member Functions
void initialize ()
Performs initilization common in the different constructors.
XmlChannel * errorChannel (ErrorType mt) const
Get a channel for a warning/error message.
void errorOccured (ErrorType) const
void exit () const
Abort program execution.
Private Attributes
ErrorAction errorActions_ [nErrorTypes]
int errorCounts_ [nErrorTypes]
XmlChannel * errorChannels_ [nErrorTypes]
Static Private Attributes
static const Choice errorActionChoice
static const char * errorNames [nErrorTypes]
static const char * errorChannelNames [nErrorTypes]
static const Channel::Default errorChannelDefaults [nErrorTypes]
Friends
class Component::Message
Additional Inherited Members
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Base class for configurable components with logging and error logging facilities.
The error model supposes that there are three types of errors:
warnings: Things which are possibly wrong, but may well be correct.
errors: Things are most certainly wrong, but we can try to continue.
critical errors: Things are most definitelly wrong and there is no way to continue.
Remember that this is for runtime errors only. Logical program errors should be handled by Assertions.
For all types of errors a message is output on the corresponding channel. The default behaviour is to
continue after warnings (ignore)
immediatelly abort execution on errors (immediate-exit) -> andras used to mix up critical-errors and errors
immediatelly abort execution on ciritcal errors (immediate-exit)
This behaviour can be changed using the configuration options
on-warning
on-error
on-critical-error
Component predefines four channels:
log
warning
error
critical
Messages are formatted to an indented XML text. Each call to one of the message functions (log, warning, error, criticalError) creates an XML with the full name of the component and the system error ID. The message functions return a Message object which can be used for streaming complex information into the body of the message tag. The Xml... (XmlOpen, XmlClose, XmlEmpty, XmlComment) objects can be useful for creating a structured message bodies.
Definition at line 70 of file Core/Component.hh.
Member Function Documentation
Component::Message Core::Component::criticalError (const char * msg = 0, ...) const
Print a critical error message.
Call criticalError() when an error occurs and there is no way to continue in a meaningful way. The default behaviour is to abort execution immediatelly. You should assume, that criticalError() does not return, although the user can overide this behaviour.
Parameters
msg a printf-like format string
Returns
The stream output operator may be applied to the return value. Message should not include formatting characters ("\n" etc.). A line break is appended automatically.
See also
warning()
Definition at line 255 of file Core/Component.cc.
References vErrorMessage().
Referenced by Core::DependencySet::add(), Flf::ConfusionNetworkAlignment::align(), Speech::LatticeSetGenerator::alignmentGenerator(), Math::FastMatrix< T >::allocate(), Signal::LinearWarpingNode::apply(), Speech::ArchiveApproximateWordAccuracyLatticeBuilder::ArchiveApproximateWordAccuracyLatticeBuilder(), Speech::AllophoneStateGraphBuilder::build(), Speech::AllophoneStateGraphBuilder::buildTransducer(), Cart::XmlPropertiesBuilderElement::characters(), Flf::cleanUp(), Speech::AlignmentNode::configure(), Flf::ConfusionNetworkArchive::ConfusionNetworkArchive(), Speech::ConvertMixtureSetTrainer::ConvertMixtureSetTrainer(), Mm::Module_::createFeatureScorer(), Lm::Module_::createLanguageModel(), Mm::Module_::createMixtureSetEstimator(), Flf::Semiring::equal(), Nn::MeanNormalizedSgdL1Clipping< T >::estimate(), Math::FastVector< T >::FastVector(), Nn::EmissionLatticeRescorer::finalize(), Flf::FwdBwd::Builder::TraverseLatticeProperties::finishState(), Signal::Normalization::flush(), Nn::PythonFeatureScorer::flush(), Nn::CrossEntropyCriterion< FloatT >::getErrorSignal(), Nn::SquaredErrorCriterion< FloatT >::getErrorSignal(), Nn::BinaryDivergenceCriterion< FloatT >::getErrorSignal(), Nn::CrossEntropyCriterion< FloatT >::getErrorSignal_naturalPairing(), Nn::SquaredErrorCriterion< FloatT >::getErrorSignal_naturalPairing(), Nn::BinaryDivergenceCriterion< FloatT >::getErrorSignal_naturalPairing(), Lm::LanguageModel::getFsa(), Nn::Statistics< T >::gradientL1Norm(), Cart::Training::halfSplit(), Nn::PythonTrainer< T >::hasClassLabelPosteriors(), Am::AllophoneAlphabet::index(), Mm::BatchFloatFeatureScorer::init(), Flf::LatticeArchiveReaderNode::init(), Flf::TimeframeErrorNode::init(), Flf::FramePosteriorCnCombinationNode::init(), Flf::EvaluatorNode::init(), Flf::LatticeArchiveWriterNode::init(), Mm::BatchIntFeatureScorer::init(), Mm::BatchUnrolledIntFeatureScorer::init(), Flf::LatticeBufferNode::init(), Flf::FwdBwdPruningNode::init(), Flf::ConfusionNetworkArchiveReaderNode::init(), Flf::ConfusionNetworkArchiveWriterNode::init(), Flf::ConfusionNetworkCombination::init(), Flf::RecognizerNode::init(), Flf::AppendScoresNode::init(), Flf::MinimumFrameWerDecoderNode::init(), Flf::PosteriorCnArchiveReaderNode::init(), Flf::PosteriorCnArchiveWriterNode::init(), Flf::StateClusterCnBuilderNode::init(), Flf::RescoreSingleDimensionNode::init_(), Flf::FilterNode::init_(), Speech::WordLatticeMerger::initialize(), Speech::GerLatticeProcessorNode::initialize(), Flf::NBestBuilder::initialize(), Nn::MeanAndVarianceTrainer< T >::initializeTrainer(), LatticeProcessor::LatticeProcessor(), Speech::LatticeSetReader::LatticeSetReader(), Bliss::CorpusDescription::SegmentPartitionVisitorAdaptor::leaveCorpus(), Search::Wfst::LexicalFstFactory::load(), Mm::DiscriminativeMixtureSetEstimator::loadPreviousMixtureSet(), MeanSumfileCreator::main(), FeatureStatistics::main(), TestApplication::main(), NnTrainer::main(), AcousticModelTrainer::main(), LatticeProcessor::main(), Speech::MinimumBayesRiskSearchNode::MinimumBayesRiskSearchNode(), Speech::ModelCombination::ModelCombination(), Flf::EditDistance::normCost(), Audio::WavInputNode::openFile_(), Search::SearchSpace::optimizeSilenceInWordLattice(), Speech::OrthographyApproximateWordAccuracyLatticeBuilder::OrthographyApproximateWordAccuracyLatticeBuilder(), Speech::OrthographySmoothedFrameStateAccuracyLatticeBuilder::OrthographySmoothedFrameStateAccuracyLatticeBuilder(), LatticeProcessor::parseActionsSelections(), Flf::PosteriorCnArchive::PosteriorCnArchive(), Search::Wfst::Builder::Count::process(), Search::Wfst::Builder::CreateStateSequenceSymbols::process(), Search::Wfst::Builder::CheckLabels::process(), Search::Wfst::Builder::Factorize::process(), Search::Wfst::Builder::ExpandStates::process(), Speech::AcousticModelTrainer::processAlignedFeature(), Speech::FeatureScorer::processAlignedFeature(), Nn::PythonTrainer< T >::processBatch_feedInput(), Nn::PythonTrainer< T >::processBatch_finish(), Nn::PythonTrainer< T >::processBatch_finishWithAlignment(), Nn::PythonTrainer< T >::processBatch_finishWithSpeechSegment(), Speech::LabelingFeatureExtractor::processFeature(), Speech::TextIndependentScatterMatricesEstimator::processLabeledFeature(), Speech::PruningLatticeSetNode::processWordLattice(), Speech::MultiplyLatticeProcessorNode::processWordLattice(), Speech::MinimumErrorSegmentwiseGmmTrainer::processWordLattice(), Speech::LemmaPronunciationToEvaluationToken::processWordLattice(), Speech::AbstractAcousticSegmentwiseTrainer::processWordLattice(), Speech::LemmaPronunciationToSyntacticToken::processWordLattice(), Speech::SpokenAndCompetingListProcessor::processWordLattice(), Nn::SegmentwiseNnTrainer< T >::processWordLattice(), Flf::Node::pull(), Flow::CollectorNode< I, O >::putNullData(), Translation::ConditionalLexiconSri::read(), Mm::MixtureSet::replaceMeans(), Flf::sausageLattice2cn(), Speech::SegmentwiseGmmTrainer::SegmentwiseGmmTrainer(), Flf::Node::sendLattice(), Flf::LatticeArchiveWriterNode::sendLattice(), Lm::FsaLm::sentenceEndScore(), Nn::NeuralNetworkTrainer< T >::setClassWeights(), Speech::FeatureScorer::setDataSource(), Speech::TextIndependentMixtureSetTrainer::setFeatureDescription(), Speech::FeatureScorer::setFeatureDescription(), Signal::HarmonicSumNode::setParameter(), Signal::CrossCorrelationNode::setParameter(), Speech::TimeConditionedLatticeSetProcessor::setWordLatticeDescription(), AcousticModelTrainer::showMixtureSet(), Speech::SoftFramePhoneAccuracyLatticeRescorerNode::SoftFramePhoneAccuracyLatticeRescorerNode(), TransitionModel::Applicator::stateType(), Flf::SpeechSegmentNode::sync(), Flf::ExpandTransitsNode::sync(), Speech::FeatureShiftAdaptor::work(), Signal::CosineTransformNode::work(), Speech::AlignmentDumpNode::work(), Speech::AcousticLatticeRescorerNode::work(), Signal::FilterBankNode::work(), and Mm::MixtureSet::write().
Component::Message Core::Component::error (const char * msg = 0, ...) const
Print an error message.
Call error() whenever an error occurs in the current component. The default behaviour is to continue until respondToDelayedErrors() is called. Clients can check if an error occurred by calling hasFatalErrors().
Parameters
msg a printf-like format string
Returns
The stream output operator may be applied to the return value. Message should not include formatting characters ("\n" etc.). A line break is appended automatically.
See also
warning()
respondToDelayedErrors()
Definition at line 240 of file Core/Component.cc.
References vErrorMessage().
Referenced by Nn::MaxoutVarLayer< T >::_forward(), Nn::ExponentialLinearLayer< T >::_forward(), Am::AllophoneAlphabet::add(), Sparse::SingleValueSparseVector< Content >::add(), Search::Wfst::Builder::RemovePhoneDisambiguators::addInput(), Math::CudaMatrix< T >::addMatrixProduct(), Flow::AbstractNode::addParameter(), Flow::Network::addParameterUse(), Bliss::EditDistance::align(), Speech::LatticeSetGenerator::alignmentGenerator(), Speech::AlignmentMapAlphabet::AlignmentMapAlphabet(), Signal::CosineTransform::apply(), Math::EigenvalueProblem::areEqual(), Aligner::WordLatticeBuilder::Converter::build(), Flow::NetworkParser::buildFromFile(), Flow::Network::buildFromFile(), Flow::Network::buildFromString(), Core::XmlRegularElement::characters(), Core::Application::closeLogging(), Speech::ConfidenceArchive::ConfidenceArchive(), Speech::AlignmentBaseNode::configure(), Signal::AllPolesPowerSpectrumNode::configure(), Flow::DemoNode::configure(), Nn::NeuralNetworkForwardNode::configure(), Audio::SourceNode::configure(), Speech::AlignmentDumpNode::configure(), Flow::Node::configure(), Signal::GammaToneNode::configure(), Signal::NormalizationNode::configure(), Signal::CrossCorrelationNode::configure(), Flow::Network::configureOutputPort(), Flow::Network::connectInputFromInside(), Flow::Network::connectNodeInput(), Flow::Network::connectNodeOutput(), Flow::Network::connectOutputFromInside(), Flow::Network::connectOutputPort(), Speech::DataSource::convert(), Math::Lapack::GenEigenProblemWithSchurDecomposition::copyEigenvectors(), Math::Module_::createEigenvalueProblem(), Math::Module_::createGeneralizedEigenvalueProblem(), Mm::Module_::createMixtureSet(), Flow::NodeBuilder::createNode(), Mm::Module_::createScaledFeatureScorer(), Search::Wfst::StateSequenceBuilder::createSymbols(), Search::Wfst::LexiconBuilder::createSymbolTables(), Signal::CrossCorrelation::crossCorrelation(), Core::Application::debugChannel(), Core::Application::debugXmlChannel(), Math::Lapack::GenEigenProblemWithSchurDecomposition::dggevx(), Math::Lapack::SymmetricEigenvalueProblem::dsyevd(), Math::Lapack::SymmetricEigenvalueProblem::dsyevr(), Math::Lapack::SymmetricEigenvalueProblem::dsyevx(), Math::Lapack::GenSymmetricDefiniteEigenProblem::dsygvd(), Math::Lapack::GenSymmetricDefiniteEigenProblem::dsygvx(), Core::XmlRegularElement::end(), Cart::XmlFloatBoxBuilderElement::end(), Nn::Adam< T >::estimate(), Nn::AdaGrad< T >::estimate(), Nn::AdaDelta< T >::estimate(), Nn::EmissionLatticeRescorer::finalize(), Math::EigenvalueProblem::finalize(), Math::GeneralizedEigenvalueProblem::finalize(), Math::EigenvalueProblem::finalizeEigenvaluesAndVectors(), Flf::FittingLattice::Boundaries::get(), Flow::Network::getAttribute(), Search::Wfst::ExpandingFsaSearch::getCurrentBestSentence(), Search::AdvancedTreeSearchManager::getCurrentBestSentence(), Flow::AbstractNode::getData(), SietillDelimiter::getDelimitation(), Flow::Node::getInputAttributes(), Search::Wfst::LexiconBuilder::getPronsWithoutNonWords(), TestApplication::getUsage(), Core::Description::Stream::getValue(), Nn::Statistics< T >::gradientL1Norm(), Cart::Training::halfSplit(), Flf::UnknownAlphabet::index(), Flf::SpeechSegmentNode::init(), Signal::BandpassAutocorrelation::init(), Signal::FilterBank::Boundary::init(), Flf::LatticeBufferNode::init(), Flf::Sink::init(), Flf::RescoreSingleDimensionNode::init_(), Speech::LatticeSetGenerator::initialize(), Speech::LatticeSetReader::initialize(), Speech::LatticeSetWriter::initialize(), Speech::GerLatticeProcessorNode::initialize(), Nn::CtcCriterion< FloatT >::inputSpeechSegment(), Math::EigenvalueProblem::isCorrectSolution(), Math::GeneralizedEigenvalueProblem::isCorrectSolution(), Lm::FsaLm::HistoryManager::isEquivalent(), Am::AcousticModel::isWeakCompatible(), Speech::LatticeWriteNode::LatticeWriteNode(), Bliss::TheanoSegmentOrderingVisitor::leaveCorpus(), Bliss::SegmentOrderingVisitor::leaveCorpus(), Speech::MinimumMaximumWeightNode::leaveCorpus(), Nn::SegmentwiseNnTrainer< T >::leaveCorpus(), CartTrainer::main(), MeanSumfileCreator::main(), CartViewer::main(), Math::MatrixTool::main(), NnTrainer::main(), Costa::main(), Math::EigenvalueProblem::normalizeDiagonal(), Audio::FlacInputNode::openFile_(), Audio::FfmpegInputNode::openFile_(), Audio::RawFileInputNode::openFile_(), Audio::WavOutputNode::openFile_(), Sparse::SingleValueSparseVector< Content >::operator+=(), Search::SearchSpace::optimizeSilenceInWordLattice(), Speech::OrthographyFrameStateAccuracyLatticeBuilder::OrthographyFrameStateAccuracyLatticeBuilder(), Speech::OrthographyTimeAlignmentBasedMetricLatticeBuilder::OrthographyTimeAlignmentBasedMetricLatticeBuilder(), Bliss::OrthographicParser::parse(), LatticeProcessor::parseActionsSelections(), Search::Wfst::Builder::FileOperation::precondition(), Search::Wfst::Builder::ReadFst::process(), Search::Wfst::Builder::BuildLexicon::process(), Search::Wfst::Builder::ReadFsa::process(), Search::Wfst::Builder::WriteFst::process(), Search::Wfst::Builder::WriteFsa::process(), Search::Wfst::Builder::Compress::process(), Search::Wfst::Builder::CheckLabels::process(), Search::Wfst::Builder::RemoveEmptyPath::process(), Search::Wfst::Builder::CreateSubwordGrammar::process(), Search::Wfst::Builder::ScaleLabelWeights::process(), Search::Wfst::Builder::BuildStateTree::process(), Nn::FrameErrorEvaluator< T >::processBatch_feedInput(), Nn::PythonEvaluator< T >::processBatch_finish(), Nn::NetworkEvaluator< T >::processBatch_finish(), Nn::FeedForwardTrainer< T >::processBatch_finishWithAlignment(), Nn::FeedForwardTrainer< T >::processBatch_finishWithSpeechSegment(), Speech::AligningFeatureExtractor::processFeature(), Speech::OfflineRecognizer::processResult(), Speech::MinimumBayesRiskSearchNode::processWordLattice(), Speech::LatticeSetProcessor::processWordLattice(), Speech::DumpWordBoundariesNode::processWordLattice(), Nn::SegmentwiseNnTrainer< T >::processWordLattice(), Speech::ExpmNode::processWordLattice(), Speech::EpsilonRemoval::processWordLattice(), Speech::CacheNode::processWordLattice(), Speech::CopyNode::processWordLattice(), Speech::PartialNode::processWordLattice(), Speech::SkipEmptyLatticeNode::processWordLattice(), Flow::Network::putOod(), Audio::FlacInputNode::read(), Audio::WavInputNode::read(), Mm::MixtureSetReader::read(), Audio::FfmpegInputNode::read(), Audio::RawFileInputNode::read(), Mm::Module_::readMixtureSet(), Math::EigenvalueProblem::real(), Core::FileArchive::recover(), Core::FormatSet::registerFormat(), Core::FileArchive::remove(), Mm::MixtureSet::replaceMeans(), Speech::LmLatticeRescorerAutomaton::score(), Audio::FlacInputNode::seek(), Audio::WavInputNode::seek(), Audio::RawFileInputNode::seek(), Audio::FfmpegInputNode::seek(), Audio::SourceNode::seek(), Flf::LatticeArchiveWriterNode::sendLattice(), Search::SearchSpace::setAllowHmmSkips(), TrapezeRastaFilterBuilder::setEnd(), Am::AdaptedAcousticModel::setKey(), Flf::Semiring::setKeys(), Flow::AbstractNode::setNetworkParameter(), Signal::FastMatrixMultiplicationNode< T >::setParameter(), Signal::AutoregressionToCepstrumNode::setParameter(), Signal::AutoregressionToSpectrumNode::setParameter(), Signal::MatrixMultiplicationNode< T >::setParameter(), Speech::AlignmentResetWeightsNode::setParameter(), Nn::LinearLayer< T >::setParameters(), TrapezeRastaFilterBuilder::setStart(), AcousticModelTrainer::showMixtureSet(), Speech::OfflineRecognizer::signOn(), Math::Lapack::GenEigenProblemWithSchurDecomposition::solveSymmetric(), Math::EigenvalueProblem::sortEigenvalues(), Cart::XmlIndexedStringBuilderElement::start(), Cart::XmlBinaryTreeRootBuilderElement::start(), Cart::XmlFloatBoxBuilderElement::start(), Lm::FsaLm::startHistory(), Nn::FeedForwardTrainer< f64 >::statistics(), Am::AllophoneAlphabet::store(), Flf::stripExtension(), Signal::CosineTransformNode::timeDomainSampleRate(), Core::Description::verifyNumberOfStreams(), Core::Description::Stream::verifyValue(), Lm::CorpusStatisticsVisitor::visitSpeechSegment(), Signal::LinearWarpingNode::warping(), Speech::AlignmentGeneratorNode::work(), Signal::ProjectionNode< T >::work(), Signal::FastMatrixMultiplicationNode< T >::work(), Flow::MergerNode< I, O >::work(), Flow::VectorSelectNode< T >::work(), Flow::VectorSequenceNode< T >::work(), Flow::CoprusKeyMapNode::work(), Signal::MatrixMultiplicationNode< T >::work(), Speech::ApproximateDistanceLatticeRescorerNode::work(), Speech::AlignmentNode::work(), Speech::LatticeWriteNode::work(), Signal::TemporalPatternNode::work(), Speech::BinaryAlignmentTransformNode::work(), Speech::AlignmentDumpNode::work(), Speech::SoftFramePhoneAccuracyLatticeRescorerNode::work(), Speech::LatticeTransformNode::work(), Speech::LatticeTransform2Node::work(), Speech::AcousticLatticeRescorerNode::work(), Core::FileArchive::write(), Audio::WavOutputNode::write(), Signal::ScatterTransform::write(), Mm::AbstractMixtureSet::write(), Mm::Covariance::write(), Mm::MixtureSet::write(), Core::ObjectCache< List >::writeBack(), Search::StateTreeWriter::writeDependenciesPosition(), Mm::Module_::writeMixtureSetEstimator(), and Signal::ScatterTransform::writeScatterMatrix().
XmlChannel * Core::Component::errorChannel (ErrorType mt) const private
Get a channel for a warning/error message.
If necessary the requested channel is created first. All channels will be deleted by the destrutor.
Parameters
mt type of the channel
Returns
pointer to the channel to be used for messages of the given type.
Definition at line 111 of file Core/Component.cc.
References defect, exit(), and require.
Referenced by exit(), log(), and vErrorMessage().
void Core::Component::exit () const private
Abort program execution.
exit() will print a message and call Application::exit() to terminate the programm. The exit status of the program can be configured by the "error-code" parameter.
Definition at line 160 of file Core/Component.cc.
References errorChannel(), and Core::Configurable::fullName().
Referenced by Search::SearchSpace::activateOrUpdateTree(), Search::StateTree::createBatch(), Search::StateTree::createExits(), errorChannel(), Core::Application::exit(), Search::LinearSearch::feed(), Search::SearchSpace::findWordEndsInternal(), Core::Application::getCommentCharacters(), Search::SearchSpace::hypothesizeEpsilonPronunciations(), and respondToDelayedErrors().
bool Core::Component::hasFatalErrors () const
Test whether non-ignored errors have occured.
See also
error()
Definition at line 138 of file Core/Component.cc.
References defect.
Referenced by Flow::NetworkParser::buildFromFile(), Flow::Network::configureOutputPort(), Core::Archive::create(), Am::Module_::createAcousticModel(), Am::ClassicStateTying::createClassicStateTyingRef(), Lm::Module_::createLanguageModel(), Flf::LatticeArchive::getReader(), Flf::LatticeArchiveReaderNode::init(), Flf::LatticeArchiveWriterNode::init(), Flf::ConcatenateLatticesNode::init(), Flf::ConcatenateFCnsNode::init(), Flf::ConfusionNetworkArchiveReaderNode::init(), Flf::ConfusionNetworkArchiveWriterNode::init(), Flf::PosteriorCnArchiveReaderNode::init(), Flf::PosteriorCnArchiveWriterNode::init(), and respondToDelayedErrors().
void Core::Component::initialize () private
Performs initilization common in the different constructors.
Definition at line 77 of file Core/Component.cc.
References warning().
Referenced by Speech::ApproximatePhoneAccuracyLatticeRescorerNode::ApproximatePhoneAccuracyLatticeRescorerNode(), Mm::BatchFeatureScorerBase::bufferSize(), Speech::AlignmentNode::configure(), Mm::EbwDiscriminativeMixtureSetEstimator::EbwDiscriminativeMixtureSetEstimator(), Speech::FramePhoneAccuracyLatticeRescorerNode::FramePhoneAccuracyLatticeRescorerNode(), Speech::NBestListLatticeProcessor::initialize(), Speech::TokenMappingLatticeProcessorNode::initialize(), Speech::MinimumBayesRiskSearchNode::initialize(), Speech::WordLatticeMerger::initialize(), Speech::LemmaPronunciationToEvaluationToken::initialize(), Speech::LemmaPronunciationToSyntacticToken::initialize(), Speech::LatticeSetGenerator::initialize(), Speech::NumeratorFromDenominatorExtractor::initialize(), Speech::LatticeSetWriter::initialize(), Speech::GerLatticeProcessorNode::initialize(), Speech::LatticeWriteNode::LatticeWriteNode(), Mm::DiscriminativeMixtureSetEstimator::loadPreviousMixtureSet(), Bliss::OrthographicParser::parse(), Speech::LmLatticeRescorerAutomaton::score(), Mm::IterationConstants::set(), Speech::SoftFramePhoneAccuracyLatticeRescorerNode::SoftFramePhoneAccuracyLatticeRescorerNode(), Speech::WeightedFramePhoneAccuracyLatticeRescorerNode::WeightedFramePhoneAccuracyLatticeRescorerNode(), Speech::AlignmentGeneratorNode::work(), Speech::NumeratorFromDenominatorNode::work(), Nn::NeuralNetworkForwardNode::work(), Speech::LatticeIoNode::work(), and Speech::AcousticLatticeRescorerNode::work().
Component::Message Core::Component::log (const char * msg, ...) const
Print an information message.
Use this for all information you what to give the use on what your are currently doing. If anything abnormal occurs use waring() or error() instead.
Parameters
msg a printf-like format string
Returns
The stream output operator may be applied to the return value. A line break is appended automatically.
See also
warning(), error(), criticalError()
Definition at line 204 of file Core/Component.cc.
References errorChannel(), Core::Configurable::fullName(), require, and vErrorMessage().
Referenced by Nn::LinearAndSigmoidLayer< T >::_forward(), Nn::SigmoidLayer< T >::_forward(), Nn::SoftmaxLayer< T >::_forward(), Nn::MaxoutVarLayer< T >::_forward(), Nn::RectifiedLayer< T >::_forward(), Nn::ExponentialLinearLayer< T >::_forward(), Mm::FullAdaptorViterbiEstimator::adaptor(), Search::Wfst::Builder::DisambiguatorDependentOperation::addInput(), Search::Wfst::Builder::CreateLookahead::addInput(), Speech::LatticeSetGenerator::alignmentGenerator(), Tools::BatchBuilder< SubTreeListId, StateId, Search::HMMState, invalidBatch_, 0 >::appendToBatchPrivate(), Search::PersistentStateTree::build(), Search::StaticSearchAutomaton::buildBatches(), AdvancedTreeSearch::LanguageModelLookahead::buildCompressesLookaheadStructure(), Flow::Network::buildFromFile(), Search::StaticSearchAutomaton::buildNetwork(), Cart::XmlBinaryTreeRootBuilderElement::characters(), Core::MappedArchiveReader::check(), Search::PersistentStateTree::cleanup(), Search::HMMStateNetwork::cleanup(), Flf::cleanUp(), Nn::NeuralNetworkForwardNode::configure(), Speech::AlignmentNode::configure(), Mm::Module_::convertMixtureSet(), Am::Module_::createAcousticModel(), Mm::Module_::createScaledFeatureScorer(), Search::Wfst::StateSequenceBuilder::createSymbols(), Speech::ModelCombination::distributeScaleUpdate(), Mm::EbwDiscriminativeMixtureSetEstimator::EbwDiscriminativeMixtureSetEstimator(), Mm::EbwDiscriminativeMixtureSetEstimatorWithISmoothing::EbwDiscriminativeMixtureSetEstimatorWithISmoothing(), Cart::XmlFloatBoxBuilderElement::end(), Nn::Adam< T >::estimate(), Nn::AdaGrad< T >::estimate(), Nn::AdaDelta< T >::estimate(), Nn::RmsProp< T >::estimate(), Mm::EbwDiscriminativeMixtureEstimator::estimateMixtureWeights(), Nn::EmissionLatticeRescorer::finalize(), Signal::FullCovMonoGaussianModel::finalize(), Core::Application::getCacheArchiveReader(), Core::Application::getCacheArchiveWriter(), Search::Wfst::ExpandingFsaSearch::getCurrentBestSentence(), Nn::BufferedFeatureExtractor< T >::getCurSegment(), Nn::NeuralNetwork< T >::getLayer(), Signal::ProjectionNode< T >::getOutput(), Core::MappedArchive::getReader(), Mm::SimdGaussDiagonalMaximumFeatureScorer::getScaling(), Search::SearchSpace::getSentenceEndFallBack(), Core::MappedArchive::getWriter(), InternalIc::GlobalIcb::GlobalIcb(), Nn::Statistics< T >::gradientL1Norm(), Mm::DensityClusteringBase::init(), Flf::DeterminizeNode::init(), Flf::CnGammaCorrectionNode::init(), Flf::FramePosteriorCnCombinationNode::init(), Flf::Node::init_(), Speech::GerLatticeProcessorNode::initialize(), AdvancedTreeSearch::AcousticLookAhead::initializeModels(), Nn::NeuralNetwork< T >::initParameters(), Nn::BufferedFeatureExtractor< T >::initShuffle(), LatticeProcessor::LatticeProcessor(), Speech::LatticeSetReader::LatticeSetReader(), Nn::SegmentwiseNnTrainer< T >::leaveCorpus(), Speech::FeatureScorer::leaveSpeechSegment(), Search::Wfst::LexicalFstFactory::load(), Mm::MixtureToMixtureMap::load(), Nn::LinearLayer< T >::loadNetworkParameters(), Mm::DiscriminativeMixtureSetEstimator::loadPreviousMixtureSet(), Flf::Evaluator::logEvaluation(), TestApplication::main(), MatrixProfiler::main(), NnTrainer::main(), FlfTool::main(), AcousticModelTrainer::main(), Mm::SimdGaussDiagonalMaximumFeatureScorer::multiplyAndQuantize(), Translation::ConditionalLexiconPlain::normalize(), Math::EigenvalueProblem::normalizeDiagonal(), Speech::OrthographyFrameStateAccuracyLatticeBuilder::OrthographyFrameStateAccuracyLatticeBuilder(), Search::Wfst::Builder::FileOperation::precondition(), Tools::BatchBuilder< SubTreeListId, StateId, Search::HMMState, invalidBatch_, 0 >::print(), Search::Wfst::Builder::Minimize::process(), Search::Wfst::Builder::RemoveHmmDisambiguators::process(), Search::Wfst::Builder::BuildGrammar::process(), Search::Wfst::Builder::Info::process(), Search::Wfst::Builder::Determinize::process(), Search::Wfst::Builder::ReadFst::process(), Search::Wfst::Builder::Count::process(), Search::Wfst::Builder::ArcInputSort::process(), Search::Wfst::Builder::BuildLexicon::process(), Search::Wfst::Builder::ReadFsa::process(), Search::Wfst::Builder::CreateStateSequenceSymbols::process(), Search::Wfst::Builder::ArcOutputSort::process(), Search::Wfst::Builder::BuildOldLexicon::process(), Search::Wfst::Builder::WriteFst::process(), Search::Wfst::Builder::CloseLexicon::process(), Search::Wfst::Builder::Compose::process(), Search::Wfst::Builder::WriteFsa::process(), Search::Wfst::Builder::LemmaMapping::process(), Search::Wfst::Builder::Compress::process(), Search::Wfst::Builder::LabelEncode::process(), Search::Wfst::Builder::AddPronunciationWeight::process(), Search::Wfst::Builder::RestoreOutputSymbols::process(), Search::Wfst::Builder::LabelDecode::process(), Search::Wfst::Builder::RemovePhoneDisambiguators::process(), Search::Wfst::Builder::WeightEncode::process(), Search::Wfst::Builder::PushOutputLabels::process(), Search::Wfst::Builder::Relabel::process(), Search::Wfst::Builder::CheckLabels::process(), Search::Wfst::Builder::PushWeights::process(), Search::Wfst::Builder::PushLabels::process(), Search::Wfst::Builder::AddNonWordTokens::process(), Search::Wfst::Builder::NormalizeEpsilon::process(), Search::Wfst::Builder::RemoveEmptyPath::process(), Search::Wfst::Builder::Project::process(), Search::Wfst::Builder::CreateSubwordGrammar::process(), Search::Wfst::Builder::RemoveEpsilon::process(), Search::Wfst::Builder::Synchronize::process(), Search::Wfst::Builder::ContextBuilder::process(), Search::Wfst::Builder::Invert::process(), Search::Wfst::Builder::HmmBuilder::process(), Search::Wfst::Builder::CreateStateSequences::process(), Search::Wfst::Builder::CreateLookahead::process(), Search::Wfst::Builder::ReachableCompose::process(), Search::Wfst::Builder::Factorize::process(), Search::Wfst::Builder::ScaleWeights::process(), Search::Wfst::Builder::ExpandStates::process(), Search::Wfst::Builder::ScaleLabelWeights::process(), Search::Wfst::Builder::RemoveWeights::process(), Search::Wfst::Builder::ConvertStateSequences::process(), Nn::BufferedAlignedFeatureProcessor< T >::processAlignedFeature(), Nn::MeanAndVarianceTrainer< T >::processBatch_feedInput(), Nn::PythonTrainer< T >::processBatch_finish(), Nn::FrameErrorEvaluator< T >::processBatch_finish(), Nn::FrameErrorEvaluator< T >::processBatch_finishWithAlignment(), Nn::FrameErrorEvaluator< T >::processBatch_finishWithSpeechSegment(), Nn::BufferedFeatureExtractor< T >::processFeature(), Speech::WordLatticeMerger::processWordLattice(), Speech::LatticeSetGenerator::processWordLattice(), Speech::LatticeSetProcessor::processWordLattice(), Speech::InfoLatticeProcessorNode::processWordLattice(), Speech::DensityLatticeProcessorNode::processWordLattice(), Flf::pruneByFwdBwdScores(), Search::PersistentStateTree::read(), Mm::Module_::readMixtureSet(), Mm::DiscriminativeMixtureEstimator::removeDensitiesWithLowWeight(), Search::PersistentStateTree::removeOutputs(), Mm::RpropDiscriminativeMixtureSetEstimatorWithISmoothing::RpropDiscriminativeMixtureSetEstimatorWithISmoothing(), Nn::BiasLayer< T >::saveNetworkParameters(), Speech::LmLatticeRescorerAutomaton::score(), Search::SearchSpace::SearchSpace(), Flf::FilterNode::sendLattice(), Search::SearchSpace::setAllowHmmSkips(), Nn::FeedForwardTrainer< T >::setBatchSize(), Nn::NeuralNetworkTrainer< T >::setClassWeights(), Speech::OfflineRecognizer::setFeatureDescription(), Nn::Prior< T >::setFromMixtureSet(), Am::AdaptedAcousticModel::setKey(), Speech::AlignmentFilterWeightsNode::setParameter(), Speech::AlignmentResetWeightsNode::setParameter(), Nn::LinearLayer< T >::setParameters(), Lm::WordlistInterfaceLm::setSignificantHistoryLength(), Nn::BufferedFeatureExtractor< T >::setWindowedFeature(), AcousticModelTrainer::showMixtureSet(), Speech::AligningFeatureExtractor::signOn(), Speech::NumeratorLatticeGenerator::signOn(), Core::MMappedFile::size(), Nn::BufferedFeatureExtractor< T >::updateBufferedFeature(), Mc::Component::updateScales(), Flow::WarpTimeFilterNode::work(), Flow::VectorAbsValDumpNode< content >::work(), Speech::FeatureShiftAdaptor::work(), Search::PersistentStateTree::write(), Signal::ScatterTransform::write(), Speech::StateTyingDecisionTreeTrainer::LogLikelihoodGain::write(), Search::StateTreeWriter::writeDependenciesPosition(), Nn::MeanAndVarianceTrainer< T >::writeMeanAndStandardDeviation(), Mm::Module_::writeMixtureSetEstimator(), and Signal::ScatterTransform::writeScatterMatrix().
void Core::Component::respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
More specifically, terminate iff hasFatalErrors() returns true.
See also
error()
Definition at line 155 of file Core/Component.cc.
References exit(), and hasFatalErrors().
Referenced by Speech::LatticeSetGenerator::alignmentGenerator(), Speech::AlignmentRemoveEmissionScoreNode::AlignmentRemoveEmissionScoreNode(), Signal::CosineTransform::apply(), Signal::AllPolesPowerSpectrumNode::configure(), SietillDelimiter::getDelimitation(), Core::Description::Stream::getValue(), Speech::LatticeWriteNode::LatticeWriteNode(), FeatureStatistics::main(), Speech::OrthographyTimeAlignmentBasedMetricLatticeBuilder::OrthographyTimeAlignmentBasedMetricLatticeBuilder(), Signal::AutoregressionToCepstrumNode::setParameter(), Signal::AutoregressionToSpectrumNode::setParameter(), Speech::NumeratorLatticeGenerator::signOn(), Speech::LatticeSetProcessorRoot::signOn(), Core::Description::verifyNumberOfStreams(), Core::Description::Stream::verifyValue(), Signal::LinearWarpingNode::warping(), Speech::CorpusProcessorNode< CorpusProcessorType >::work(), and Signal::TemporalPatternNode::work().
XmlChannel * Core::Component::vErrorMessage (ErrorType mt, const char * msg, va_list ap) const protected virtual
Output a warning/error message on the appropriate channel.
Parameters
mt type of the message
msg a printf-like format string
Returns
the channel the message was written to.
Todo:
strerror() is not thread safe. But strerror_r() does not seems to work.
Reimplemented in Core::XmlParser.
Definition at line 175 of file Core/Component.cc.
References errorChannel(), Core::Configurable::fullName(), and require.
Referenced by criticalError(), error(), log(), Core::XmlParser::vErrorMessage(), and warning().
Component::Message Core::Component::warning (const char * msg = 0, ...) const
Print a warning message.
Parameters
msg a printf-like format string
Returns
The stream output operator may be applied to the return value. Message should not include formatting characters ("\n" etc.). A line break is appended automatically. Example: warning("mismatch ") << a << "!=" << b;
Definition at line 225 of file Core/Component.cc.
References vErrorMessage().
Referenced by Core::DependencySet::add(), Am::AllophoneAlphabet::add(), Search::StateTree::SuffixSet::advance(), Math::FastMatrix< T >::allocate(), Signal::CosineTransform::apply(), Speech::ApproximatePhoneAccuracyLatticeBuilder::ApproximatePhoneAccuracyLatticeBuilder(), Speech::ArchiveApproximatePhoneAccuracyLatticeBuilder::ArchiveApproximatePhoneAccuracyLatticeBuilder(), Speech::ArchiveApproximateWordAccuracyLatticeBuilder::ArchiveApproximateWordAccuracyLatticeBuilder(), Speech::ArchiveFrameStateAccuracyLatticeBuilder::ArchiveFrameStateAccuracyLatticeBuilder(), Search::Wfst::LexiconBuilder::build(), Speech::AllophoneStateGraphBuilder::build(), Flf::buildBoundedSegments(), Cart::XmlBinaryTreeRootBuilderElement::characters(), Cart::XmlPropertiesBuilderElement::characters(), Flow::AbstractNode::checkAndSetParameter(), Nn::MeanNormalizedSgd< T >::checkForStatistics(), Flf::cleanUp(), Signal::VectorResizeNode< T >::configure(), Speech::AlignmentBaseNode::configure(), Signal::AllPolesPowerSpectrumNode::configure(), Speech::AlignmentNode::configure(), Flow::Network::configure(), Flf::ConfusionNetworkArchive::ConfusionNetworkArchive(), Math::Lapack::GenEigenProblemWithSchurDecomposition::copyEigenvalues(), Flf::drawDot(), Cart::XmlFloatBoxBuilderElement::end(), Mm::EbwDiscriminativeMixtureEstimator::estimateMixtureWeights(), Flf::expandTransits(), Nn::EmissionLatticeRescorer::finalize(), Flf::ConfusionNetworkArchiveReaderNode::finalize(), Flf::RecognizerNode::finalize(), Flf::PosteriorCnArchiveReaderNode::finalize(), Signal::Normalization::flush(), Flf::fromFsa(), Search::Aligner::getAlignmentFsa(), Search::AdvancedTreeSearchManager::getCurrentBestSentencePartial(), SietillDelimiter::getDelimitation(), Nn::CtcCriterion< FloatT >::getErrorSignal_naturalPairing(), Flow::Node::getInputAttributes(), Search::SearchSpace::getSentenceEndFallBack(), Cart::Training::halfSplit(), Nn::PythonTrainer< T >::hasClassLabelPosteriors(), Signal::BandpassAutocorrelation::init(), Flf::DummyFilterNode::init(), Flf::FwdBwdPruningNode::init(), Flf::RecognizerNode::init(), Flf::SegmentBuilderNode::init(), Flf::RoverCombination::init(), initialize(), Flf::NBestBuilder::initialize(), Am::AcousticModel::isCompatible(), Nn::SegmentwiseNnTrainer< T >::leaveCorpus(), Mm::DensityClusteringBase::load(), CartTrainer::main(), AllophoneTool::main(), Fsa::mapAlphabet(), Speech::OrthographyApproximatePhoneAccuracyLatticeBuilder::OrthographyApproximatePhoneAccuracyLatticeBuilder(), Speech::OrthographyApproximatePhoneAccuracyMaskLatticeBuilder::OrthographyApproximatePhoneAccuracyMaskLatticeBuilder(), Speech::OrthographyApproximateWordAccuracyLatticeBuilder::OrthographyApproximateWordAccuracyLatticeBuilder(), Speech::OrthographyFramePhoneAccuracyLatticeBuilder::OrthographyFramePhoneAccuracyLatticeBuilder(), Speech::OrthographyFrameStateAccuracyLatticeBuilder::OrthographyFrameStateAccuracyLatticeBuilder(), Speech::OrthographySmoothedFrameStateAccuracyLatticeBuilder::OrthographySmoothedFrameStateAccuracyLatticeBuilder(), Core::MemoryInfo::peak(), Flf::PosteriorCnArchive::PosteriorCnArchive(), Search::Wfst::Builder::CreateStateSequences::precondition(), Search::Wfst::Builder::BuildGrammar::process(), Search::Wfst::Builder::BuildOldLexicon::process(), Search::Wfst::Builder::Relabel::process(), Search::Wfst::Builder::CheckLabels::process(), Search::Wfst::Builder::CreateSubwordGrammar::process(), Speech::FeatureAccumulator::processAlignedFeature(), Nn::PythonTrainer< T >::processBatch_feedInput(), Nn::FeedForwardTrainer< T >::processBatch_feedInput(), Nn::MeanAndVarianceTrainer< T >::processBatch_feedInput(), Nn::PythonTrainer< T >::processBatch_finish(), Speech::AligningFeatureExtractor::processFeature(), Speech::WordLatticeMerger::processWordLattice(), Speech::SpokenAndCompetingListProcessor::processWordLattice(), Speech::LatticeSetGenerator::processWordLattice(), Nn::SegmentwiseNnTrainer< T >::processWordLattice(), Search::StateTree::pronunciationSuffixTransitEntry(), Flf::pruneByFwdBwdScores(), Core::FileArchive::remove(), Core::DependencySet::satisfies(), Flf::sausageLattice2cn(), Search::SearchSpace::SearchSpace(), Flf::ComposeNode::sendLattice(), Flf::LatticeArchiveReaderNode::sendLattice(), Search::SearchSpace::setAllowHmmSkips(), Nn::NeuralNetworkTrainer< T >::setClassWeights(), Core::Application::setCommentCharacters(), Flow::Network::Port::setNode(), Flow::WarpTimeFilterNode::setParameter(), Lm::WordlistInterfaceLm::setSignificantHistoryLength(), Speech::SoftFramePhoneAccuracyLatticeBuilder::SoftFramePhoneAccuracyLatticeBuilder(), TransitionModel::Applicator::stateType(), Nn::FeedForwardTrainer< f64 >::statistics(), Flf::stripExtension(), Am::AllophoneAlphabet::symbol(), Flf::ExpandTransitsNode::sync(), Core::MemoryInfo::update(), Core::ResourceUsageInfo::update(), Core::DependencySet::weak_satisfies(), Speech::AlignmentWithLinearSegmentationNode::work(), Signal::VectorResizeNode< T >::work(), Speech::AlignmentNode::work(), Speech::AlignmentDumpNode::work(), Speech::SetAlignmentWeightsByTiedStateAlignmentWeightsNode::work(), and Search::StateTreeWriter::writeDependenciesPosition().
Member Data Documentation
const Channel::Default Core::Component::errorChannelDefaults static private
Initial value:
= {
        Channel::standard,
        Channel::error,
        Channel::error,
        Channel::error}
Definition at line 95 of file Core/Component.hh.
const char * Core::Component::errorChannelNames static private
Initial value:
= {
        "log",
        "warning",
        "error",
        "critical"}
Definition at line 94 of file Core/Component.hh.
const char * Core::Component::errorNames static private
Initial value:
= {
        "information",
        "warning",
        "error",
        "critical-error"}
Definition at line 93 of file Core/Component.hh.
The documentation for this class was generated from the following files:
Core/Component.hh
Core/Component.cc