Sprint: Math::Lapack::SymmetricEigenvalueProblem Class Reference
Math::Lapack::SymmetricEigenvalueProblem Class Reference
Wrapper for symmetric eigenvalue problem.
#include <EigenvalueProblem.hh>
Public Member Functions
SymmetricEigenvalueProblem (const Core::Configuration &)
virtual bool solveSymmetric (const Math::Matrix< ValueType > &a, Math::Vector< ValueType > &eigenvalues, Math::Matrix< ValueType > &eigenvectors)
Interface function for symmetric eigenvalue problem.
bool solve (const Math::Matrix< ValueType > &a, Math::Vector< ValueType > &eigenvalues, Math::Matrix< ValueType > &eigenvectors)
Public Member Functions inherited from Math::EigenvalueProblem
EigenvalueProblem (const Core::Configuration &)
bool solveSymmetricAndFinalize (const Matrix< ValueType > &a, Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)
Solves the symmetric eigenvalue problem and performs finalization of results.
bool finalize (const Matrix< ValueType > &a, Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)
Performs final processing and verifications.
bool finalizeEigenvaluesAndVectors (const Matrix< ValueType > &a, Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)
Performs final processing of eigenvalues and eigenvectors.
bool isCorrectSolution (const Matrix< ValueType > &a, const Vector< ValueType > &eigenvalues, const Matrix< ValueType > &eigenvectors)
Verifies if eigenvectors and eigenvalues satisfy A*X = Lambda*B*X.
void sortEigenvalues (Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)
Sorts eigenvalues in descending order.
bool real (const Vector< std::complex< ValueType >> &, Vector< ValueType > &)
Extracts real part of the input vector.
bool real (const Matrix< std::complex< ValueType >> &, Matrix< ValueType > &)
Extracts real part of the input matrix.
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Math::Lapack::EigenvalueProblem
EigenvalueProblem (const Core::Configuration &)
Private Member Functions
bool solveWithExpertOrRelativelyRobustDriver (const Math::Matrix< ValueType > &a, Math::Vector< ValueType > &eigenvalues, Math::Matrix< ValueType > &eigenvectors) const
bool dsyevx (Matrix< double > &a, int &nEigenvalues, Vector< double > &eigenvalues, Matrix< double > &eigenvectors) const
Expert LAPACK driver which solves the symmetric eigenvalue problem.
bool dsyevr (Matrix< double > &a, int &nEigenvalues, Vector< double > &eigenvalues, Matrix< double > &eigenvectors) const
Relatively robust LAPACK driver which solves the symmetric eigenvalue problem.
bool solveWithDivideAndConquerDriver (const Math::Matrix< ValueType > &a, Math::Vector< ValueType > &eigenvalues, Math::Matrix< ValueType > &eigenvectors) const
bool dsyevd (Matrix< double > &a, Vector< double > &eigenvalues) const
Divide and conquer LAPACK driver which solves the symmetric eigenvalue problem.
Additional Inherited Members
Public Types inherited from Math::EigenvalueProblem
enum Type { typeGeneral, typeSymmetric, typeSymmetricPositiveDefinite }
typedef f64 ValueType
Static Public Attributes inherited from Math::EigenvalueProblem
static const Core::Choice choiceType
static const Core::ParameterChoice paramType
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Types inherited from Math::Lapack::EigenvalueProblem
enum DriverType { driverExpert, driverRelativelyRobust, driverDivideAndConquer }
Different implementations types of the same algorithm -"expert" driver supports all features (e.g.
Protected Member Functions inherited from Math::EigenvalueProblem
bool areEqual (const Matrix< ValueType > &x, const Matrix< ValueType > &y)
bool normalizeDiagonal (const Matrix< ValueType > &a, Matrix< ValueType > &eigenvectors)
Eigenvectors are scaled so that eigenvector^T * A * eigenvector = I.
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Member Functions inherited from Math::Lapack::EigenvalueProblem
bool isEigenvalueRangeValid () const
char translateEigenvalueRange () const
double eigenvalueLowerBound () const
double eigenvalueUpperBound () const
DriverType driverType () const
bool shouldSupportEigenvectors () const
void supportEigenvectors (const Matrix< int, RowByRowStorage > &isuppz, Matrix< double > &eigenvectors) const
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Wrapper for symmetric eigenvalue problem.
Definition at line 82 of file Lapack/EigenvalueProblem.hh.
Member Function Documentation
bool SymmetricEigenvalueProblem::dsyevd (Matrix< double > & a, Vector< double > & eigenvalues) const private
Divide and conquer LAPACK driver which solves the symmetric eigenvalue problem.
Eigenvectors are returned in a, eigenvalues in eigenvalues.
Definition at line 226 of file Lapack/EigenvalueProblem.cc.
References Core::Component::error().
bool SymmetricEigenvalueProblem::dsyevr (Matrix< double > & a, int & nEigenvalues, Vector< double > & eigenvalues, Matrix< double > & eigenvectors) const private
Relatively robust LAPACK driver which solves the symmetric eigenvalue problem.
This driver function can calculate a set of eigenvalues defined by (eigen-value-lower-bound..eigen-value-upper-bound]. Number of calculated eigenvalues is returned in nEigenvalues. Eigenvectors are returned in eigenvectors, eigenvalues in eigenvalues. If shouldSupportEigenvectors() is true, elements of the eigenvectors smaller than a threshold are set to zero. (
See also
also LAPACK manual variable izuppz).
Definition at line 168 of file Lapack/EigenvalueProblem.cc.
References Math::copy(), and Core::Component::error().
bool SymmetricEigenvalueProblem::dsyevx (Matrix< double > & a, int & nEigenvalues, Vector< double > & eigenvalues, Matrix< double > & eigenvectors) const private
Expert LAPACK driver which solves the symmetric eigenvalue problem.
This expert driver function can calculate a set of eigenvalues defined by (eigen-value-lower-bound..eigen-value-upper-bound]. Number of calculated eigenvalues is returned in nEigenvalues. Eigenvectors are returned in eigenvectors, eigenvalues in eigenvalues.
Definition at line 127 of file Lapack/EigenvalueProblem.cc.
References Core::Component::error().
virtual bool Math::Lapack::SymmetricEigenvalueProblem::solveSymmetric (const Math::Matrix< ValueType > & a, Math::Vector< ValueType > & eigenvalues, Math::Matrix< ValueType > & eigenvectors) inline virtual
Interface function for symmetric eigenvalue problem.
Implements Math::EigenvalueProblem.
Definition at line 123 of file Lapack/EigenvalueProblem.hh.
The documentation for this class was generated from the following files:
Lapack/EigenvalueProblem.hh
Lapack/EigenvalueProblem.cc