Sprint: Am::AcousticModel Class Reference
Am::AcousticModel Class Reference abstract
Interface class for acoustic models Concepts and Future Plans: -An acoustic model consist of: -Emission probability set.
#include <AcousticModel.hh>
Public Types
typedef u32 Mode
typedef Mm::MixtureIndex EmissionIndex
typedef int StateTransitionIndex
Public Member Functions
AcousticModel (const Core::Configuration &c)
virtual void load (Mode mode=complete)=0
virtual void getDependencies (Core::DependencySet &) const =0
virtual Core::Ref< TransducerBuilder > createTransducerBuilder () const =0
virtual Core::Ref< const Bliss::PhonemeInventory > phonemeInventory () const =0
virtual Core::Ref< const AllophoneAlphabet > allophoneAlphabet () const =0
virtual Core::Ref< const AllophoneStateAlphabet > allophoneStateAlphabet () const =0
virtual Core::Ref< const Phonology > phonology () const =0
virtual Bliss::Phoneme::Id silence () const =0
virtual AllophoneStateIndex silenceAllophoneStateIndex () const =0
virtual Core::Ref< Mm::AbstractMixtureSet > mixtureSet ()=0
virtual Core::Ref< const Mm::ScaledFeatureScorer > featureScorer ()=0
virtual Core::Ref< Mm::ScaledFeatureScorer > mutableFeatureScorer ()=0
virtual bool setFeatureScorer (Core::Ref< Mm::ScaledFeatureScorer >)=0
virtual EmissionIndex emissionIndex (AllophoneState) const =0
virtual EmissionIndex emissionIndex (AllophoneStateIndex) const =0
virtual EmissionIndex nEmissions () const =0
Core::Ref< const EmissionAlphabet > emissionAlphabet () const
virtual StateTransitionIndex nStateTransitions () const =0
virtual const StateTransitionModel * stateTransition (StateTransitionIndex) const =0
virtual StateTransitionIndex stateTransitionIndex (AllophoneState, s8 subState=0) const =0
virtual StateTransitionIndex stateTransitionIndex (AllophoneStateIndex, s8 subState=0) const =0
virtual Core::Ref< const ClassicHmmTopologySet > hmmTopologySet () const =0
virtual const ClassicHmmTopology * hmmTopology (Bliss::Phoneme::Id phoneme) const =0
virtual bool isAcrossWordModelEnabled () const =0
bool isCompatible (const Mm::FeatureDescription &description) const
Check if feature source is compatible with the acoustic model.
bool isWeakCompatible (const Mm::FeatureDescription &description) const
Check if feature source is almost compatible with the acoustic model.
virtual void signOn (Speech::CorpusVisitor &corpusVisitor)
Override this function to add triggers to the corpus visitor.
virtual bool setKey (const std::string &key)
Override this function to trigger manually (needed in 'Flow')
Public Member Functions inherited from Mc::Component
Component (const Core::Configuration &c)
void updateScales (ScaleUpdate update)
Updates the scale of this and the child objects.
void load ()
Loads map file and updates scales.
void setOwnScale (Scale)
Sets ownScale_ and updates scale_.
void setParentScale (Scale scale)
Updates scale_ with parent's scale (.
Scale scale () const
parent-scale * own-scale
Scale ownScale () const
Scale parentScale () const
void getDependencies (Core::DependencySet &) const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Static Public Attributes
static const Mode complete = 0x0
static const Mode noEmissions = 0x1
static const Mode noStateTying = 0x2
static const Mode noStateTransition = 0x4
Static Public Attributes inherited from Mc::Component
static const Core::ParameterFloat paramScale
Private Attributes
Core::WeakRef< const EmissionAlphabet > emissionAlphabet_
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Mc::Component
virtual void distributeScaleUpdate (const ScaleUpdate &scaleUpdate)
Override this function -to perform updates after scale_ has new value -to distibute.
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Interface class for acoustic models Concepts and Future Plans: -An acoustic model consist of: -Emission probability set.
Interface: Mm::FeatureScorer -Tying of allophone states concerning the emission probabilities. Interface: emissionIndex(...) -Transition probability set (only preliminary implementation) -Tying of transition probability concerning transitions. (Not implemented yet.) -HMM topology. Preliminary interface: hmmTopology(...) Further functionalities -Create allophone state to phoneme transducer. Interface createAllophoneStateToPhonemeTransducer -Deliver the phoneme inventory. Interface phonemeInventory(). -Deliver the allophone state alphabet. Interface allophoneStateAlphabet(). -Deliver a phonology object. (Needs refinements.) Interface phonology(). -Deliver the silence identifier. (Not sure if necessary.) Interface silence(). -Delivers if across-word model is enabled. (Not sure if necessary.) Interface isAcrossWordModelEnabled().
Definition at line 51 of file AcousticModel.hh.
Member Function Documentation
bool AcousticModel::isCompatible (const Mm::FeatureDescription & description) const
Check if feature source is compatible with the acoustic model.
Definition at line 26 of file AcousticModel.cc.
References Core::DependencySet::add(), Core::DependencySet::satisfies(), and Core::Component::warning().
Referenced by Speech::AlignmentRemoveEmissionScoreNode::AlignmentRemoveEmissionScoreNode().
bool AcousticModel::isWeakCompatible (const Mm::FeatureDescription & description) const
Check if feature source is almost compatible with the acoustic model.
Definition at line 42 of file AcousticModel.cc.
References Core::DependencySet::add(), Core::Component::error(), and Core::DependencySet::weak_satisfies().
virtual StateTransitionIndex Am::AcousticModel::nStateTransitions () const pure virtual
Todo:
Concept of transition tying not complete yet!
Implemented in Am::ClassicAcousticModel.
bool AcousticModel::setKey (const std::string & key) virtual
Override this function to trigger manually (needed in 'Flow')
Reimplemented in Am::AdaptedAcousticModel.
Definition at line 58 of file AcousticModel.cc.
References Core::ref().
Referenced by signOn().
virtual void Am::AcousticModel::signOn (Speech::CorpusVisitor & corpusVisitor) inline virtual
Override this function to add triggers to the corpus visitor.
Reimplemented in Am::AdaptedAcousticModel.
Definition at line 111 of file AcousticModel.hh.
References setKey().
The documentation for this class was generated from the following files:
AcousticModel.hh
AcousticModel.cc