Sprint: Core::Ref< T > Class Template Reference
Core::Ref< T > Class Template Reference
Class template for smart pointers using intrusive reference-counting.
#include <ReferenceCounting.hh>
Public Types
typedef T Object
Public Member Functions
Ref (Object *o)
Ref (const Ref &r)
Copy Constructor for the Type Ref<T>
template<class S >
Ref (const Ref< S > &r)
Template Copy Constuctor.
template<class S >
Ref (const WeakRef< S > &r)
Ref & operator= (const Ref &rhs)
template<class S >
Ref & operator= (const Ref< S > &rhs)
template<class S >
Ref & operator= (const WeakRef< S > &rhs)
void reset ()
Reset to void.
bool operator== (const Ref &r) const
Test for identity.
template<class S >
bool operator== (const Ref< S > &r) const
template<class S >
bool operator== (const WeakRef< S > &r) const
bool operator!= (const Ref &r) const
Test for non-identity.
template<class S >
bool operator!= (const Ref< S > &r) const
template<class S >
bool operator!= (const WeakRef< S > &r) const
operator bool () const
Test for non-voidness.
bool operator! () const
Test for voidness.
Object & operator* () const
Object * operator-> () const
Object * get () const
Explicit conversion to normal pointer.
Object * _get () const
Value of internal pointer.
Private Member Functions
void set (Object *o)
Takes over the value of.
Static Private Member Functions
static Object * sentinel ()
Private Attributes
Object * object_
Detailed Description
template<class T>
class Core::Ref< T >
Class template for smart pointers using intrusive reference-counting.
Naming: Concrete smart pointer types should have a "Ref" suffix: e.g. typedef Ref<Foo> FooRef; (Obviously calling this class "Ref" instead of more correcly "Reference" deviates from the naming conventions. However since this class is used extensively a shorter name is mandated. "Ref" is analogious to the "REF" keyword in Modula-3.)
T should be a decendent of ReferenceCounted.
Note: Virtual derivation from ReferenceCounted is not allowed currently. Reasons are many but the most imporatant one is that we use a sentinel instead of null to represent a reference is invalid (i.e. void). Advantage of using a sentinel is that in the most frequently used functions (e.g. copy constructor) the sentinel can be treated as if it was a normal object. Thus we save a few if-clauses. Once we use a sentinel, the static sentinel object (delivered by ReferenceCounted::sentinel()) of type ReferenceCounted needs to get casted to the type Object. It is a dirty solution but is the only way to make the usage of the sentinel fast. In order to be independent of the order of derivation in case of multiple inheritance - i.e. if ReferenceCounted is the first precursor class or not - static_cast is used to cast the sentinel to the type Object. Usage of reinterpret_cast would work only if we could ensure that ReferenceCounted was the very first class in the type Object. Finally, closing the series of arguments, virtual derivation from ReferenceCounted is not permitted by static_cast. It does not mean that ReferenceCounting and virtual inheritance does not go along at all: Make your virtual inheritance hiearchy first, and derive only the most specific class from ReferenceCounted.
Definition at line 29 of file ReferenceCounting.hh.
Constructor & Destructor Documentation
template<class T> Core::Ref< T >::Ref (const Ref< T > & r) inline
Copy Constructor for the Type Ref<T>
Warning
: Implementaion of this constructor is necesseary although the template copy constructor implements exactly the same function. If this constructor is not defined, the compiler creates a default copy constructor instead of using the template one.
Definition at line 180 of file ReferenceCounting.hh.
template<class T> template<class S > Core::Ref< T >::Ref (const Ref< S > & r) inline
Template Copy Constuctor.
Using a template allows automatic conversion in following cases:
from non-const to const reference
from derived to precursor class reference For all classes S which are not derived from T, this constructor will fail to compile.
Definition at line 194 of file ReferenceCounting.hh.
Member Function Documentation
template<class T> Object* Core::Ref< T >::_get () const inline
Value of internal pointer.
Warning
Do not use this function. It is only used in the template copy contructor and the template operator= functions.
Definition at line 294 of file ReferenceCounting.hh.
Referenced by Core::Ref< AbstractMixtureEstimator >::operator!=(), Core::WeakRef< const LemmaPronunciationAlphabet >::operator!=(), Core::Ref< AbstractMixtureEstimator >::operator==(), Core::WeakRef< const LemmaPronunciationAlphabet >::operator==(), Bliss::OrthographicParser::parse(), Core::Ref< AbstractMixtureEstimator >::Ref(), and Core::WeakRef< const LemmaPronunciationAlphabet >::WeakRef().
template<class T> Object* Core::Ref< T >::get () const inline
Explicit conversion to normal pointer.
Warning
This defeats the reference counting mechanism. Use with caution!
Definition at line 287 of file ReferenceCounting.hh.
Referenced by Math::AnalyticFunctionFactory::acceptWhitespaces(), Search::SearchSpace::activateLmLookahead(), Bliss::EditDistance::align(), Speech::AlignmentNode::configure(), Mm::Module_::convertMixtureSet(), Flf::decodeRescoreLm(), Mm::EbwDiscriminativeMixtureSetEstimatorWithISmoothing::EbwDiscriminativeMixtureSetEstimatorWithISmoothing(), Flf::UnknownAlphabet::end(), Flf::Semiring::equal(), Search::SearchSpace::eventuallyDeactivateTree(), Mm::FeatureScorerFactory::featureScorerNames(), AdvancedTreeSearch::LanguageModelLookahead::fill(), AdvancedTreeSearch::LanguageModelLookahead::fillZero(), Lattice::SmoothedFrameStateAccuracyAutomaton::LatticeToActiveStates::finish(), Flf::FittingLattice::Boundaries::get(), Flf::MappedBoundaries::get(), Flf::TopologicalOrderLattice::TopologicalOrderBoundaries::get(), Search::AdvancedTreeSearchManager::getCurrentBestSentencePartial(), Search::SearchSpace::getSentenceEnd(), WordConditionedTreeSearch::SearchSpace::getSentenceEndFallBack(), Cart::Training::halfSplit(), Flf::RoverCombination::init(), Flf::RescoreSingleDimensionNode::init_(), Lm::BackingOffLm::initialize(), Search::SearchSpace::instanceForKey(), LatticeProcessor::LatticeProcessor(), TestApplication::main(), LatticeProcessor::main(), Search::SearchSpace::PruningDesc::maxMasterBeam(), Search::PersistentStateTree::PersistentStateTree(), Speech::DelayedRecognizer::processFeature(), Mm::MixtureSetReader::read(), Flf::readBoundariesBinary(), Flf::readConfusionNetworkFromXml(), Flf::readPosteriorCnFromXml(), Mm::RpropDiscriminativeMixtureSetEstimatorWithISmoothing::RpropDiscriminativeMixtureSetEstimatorWithISmoothing(), Flf::sausageLattice2cn(), Speech::LmLatticeRescorerAutomaton::score(), Search::SearchSpace::SearchSpace(), Flf::ComposeNode::sendLattice(), Flf::FwdBwdBuilderNode::sendLattice(), Speech::FsaCache::setDependencies(), Speech::TiedTextDependentMixtureSetTrainer::setFeatureDescription(), Speech::OfflineRecognizer::setFeatureDescription(), Speech::SegmentwiseAlignmentGenerator::setSegmentwiseFeatureExtractor(), Flf::IncrementalRecognizer::startRecognition(), TransitionModel::Applicator::stateType(), and Flf::ExpandTransitsNode::sync().
template<class T> Core::Ref< T >::operator bool () const inline
Test for non-voidness.
Definition at line 265 of file ReferenceCounting.hh.
template<class T> bool Core::Ref< T >::operator! () const inline
Test for voidness.
Definition at line 269 of file ReferenceCounting.hh.
template<class T> bool Core::Ref< T >::operator!= (const Ref< T > & r) const inline
Test for non-identity.
Definition at line 252 of file ReferenceCounting.hh.
template<class T> bool Core::Ref< T >::operator== (const Ref< T > & r) const inline
Test for identity.
Definition at line 240 of file ReferenceCounting.hh.
template<class T> void Core::Ref< T >::reset () inline
Reset to void.
Corresponds to assigning zero to normal pointer.
Definition at line 230 of file ReferenceCounting.hh.
Referenced by Search::SearchSpace::clear(), Am::Module_::createAcousticModel(), Mm::Module_::createAssigningFeatureScorer(), Lm::Module_::createLanguageModel(), Flow::Link::datatype(), Flf::FindTopologicalOrder::finishState(), WordConditionedTreeSearch::SearchSpace::getSentenceEndFallBack(), Flf::ConcatenateNode::init_(), Search::SearchSpace::instanceForKey(), FsaTool::main(), Search::Wfst::Builder::BuildGrammar::process(), Search::Wfst::Builder::BuildOldLexicon::process(), Search::Wfst::Builder::LemmaMapping::process(), Mm::FeatureScorerScaling::reset(), Core::MappedArchiveReader::reset(), Search::SearchSpace::setAllowHmmSkips(), Speech::FsaCache::setDependencies(), Flf::IncrementalRecognizer::startRecognition(), TransitionModel::Applicator::stateType(), Flf::UnionNode::sync(), Flf::LatticeArchiveReaderNode::sync(), Flf::FramePosteriorCnBuilderNode::sync(), Flf::FramePosteriorCnCombinationNode::sync(), Flf::LatticeArchiveWriterNode::sync(), Flf::DecodeRescoreLmNode::sync(), Flf::StringConverterNode::sync(), Flf::ConcatenateLatticesNode::sync(), Flf::ExpandTransitsNode::sync(), Flf::LatticeReaderNode::sync(), Flf::DumpPosteriorCnNode::sync(), Flf::ConcatenateFCnsNode::sync(), Flf::FsaReaderNode::sync(), Flf::LatticeBufferNode::sync(), Flf::CnDecoderNode::sync(), Flf::ConfusionNetworkArchiveReaderNode::sync(), Flf::ConfusionNetworkArchiveWriterNode::sync(), Flf::DumpConfusionNetworkNode::sync(), Flf::CtmReaderNode::sync(), Flf::SegmentBuilderNode::sync(), Flf::MeshNode::sync(), Flf::AppendScoresNode::sync(), Flf::MinimumFrameWerDecoderNode::sync(), Flf::PosteriorCnArchiveReaderNode::sync(), Flf::CenterFrameCnBuilderNode::sync(), Flf::PosteriorCnArchiveWriterNode::sync(), Flf::ConfusionNetworkCombinationNode::sync(), Flf::NBestNode::sync(), Flf::PivotArcCnBuilderNode::sync(), Flf::SelectNBestNode::sync(), Flf::LocalCostDecoderNode::sync(), Flf::FwdBwdBuilderNode::sync(), Flf::StateClusterCnBuilderNode::sync(), Flf::RoverCombinationNode::sync(), Flf::OracleAlignmentNode::sync(), Signal::CosineTransformNode::timeDomainSampleRate(), Signal::MatrixMultiplicationNode< T >::work(), and Flf::writeConfusionNetworkAsText().
template<class T> void Core::Ref< T >::set (Object * o) inline private
Takes over the value of.
Parameters
o.
Correctly handles self assignment, i.e. if
o == object_.
See also
the function ref() for how to create a Ref object conveniently from a pointer.
Definition at line 150 of file ReferenceCounting.hh.
The documentation for this class was generated from the following file:
ReferenceCounting.hh