Sprint: Core::WeakRef< T > Class Template Reference
Core::WeakRef< T > Class Template Reference
Class template for smart pointers provining weak referencing.
#include <ReferenceCounting.hh>
Public Member Functions
WeakRef (Object *o)
WeakRef (const WeakRef &r)
Copy Constructor for the type WeakRef<T>
template<class S >
WeakRef (const WeakRef< S > &r)
Template Copy Constuctor.
template<class S >
WeakRef (const Ref< S > &r)
WeakRef & operator= (const WeakRef &rhs)
template<class S >
WeakRef & operator= (const WeakRef< S > &rhs)
template<class S >
WeakRef & operator= (const Ref< S > &rhs)
void reset ()
Reset to void.
bool operator== (const WeakRef &r) const
Test for identity.
template<class S >
bool operator== (const WeakRef< S > &r) const
template<class S >
bool operator== (const Ref< S > &r) const
bool operator!= (const WeakRef &r) const
Test for non-identity.
template<class S >
bool operator!= (const WeakRef< S > &r) const
template<class S >
bool operator!= (const Ref< S > &r) const
operator bool () const
Test for non-voidness.
bool operator! () const
Test for voidness.
Object & operator* () const
Object * operator-> () const
Object * get () const
Explicit conversion to normal pointer.
Object * _get () const
Value of internal pointer.
Private Types
typedef T Object
Private Member Functions
void release ()
void acquire ()
void set (Object *o)
virtual void invalidate ()
Static Private Member Functions
static Object * sentinel ()
Private Attributes
Object * object_
Detailed Description
template<class T>
class Core::WeakRef< T >
Class template for smart pointers provining weak referencing.
A weak reference does not prevent the target object from being deleted. (In so far it is much like a regular pointer.) Instead, the weak reference will be reset when the target object is deleted. Weak reference are useful to avoid cyclic references which would normally lead to memory leakage. You always have to test a weak reference before using it. Obviously there are issues with thread safety here! Also note that weak references are slower that normal references (at least in the current implementation).
Definition at line 92 of file ReferenceCounting.hh.
Constructor & Destructor Documentation
template<class T> Core::WeakRef< T >::WeakRef (const WeakRef< T > & r) inline
Copy Constructor for the type WeakRef<T>
Warning
: Implementaion of this constructor is necesseary although the template copy constructor implements exactly the same function. If this constructor is not defined, the compiler creates a default copy constructor instead of using the template one.
Definition at line 376 of file ReferenceCounting.hh.
template<class T> template<class S > Core::WeakRef< T >::WeakRef (const WeakRef< S > & r) inline
Template Copy Constuctor.
Using a template allows automatic conversion in following cases:
from non-const to const reference
from derived to precursor class reference For all classes S which are not derived from T, this constructor will fail to compile.
Definition at line 391 of file ReferenceCounting.hh.
Member Function Documentation
template<class T> Object* Core::WeakRef< T >::_get () const inline
Value of internal pointer.
Warning
Do not use!
Definition at line 480 of file ReferenceCounting.hh.
Referenced by Core::Ref< AbstractMixtureEstimator >::operator!=(), Core::WeakRef< const LemmaPronunciationAlphabet >::operator!=(), Core::Ref< AbstractMixtureEstimator >::operator==(), Core::WeakRef< const LemmaPronunciationAlphabet >::operator==(), Core::Ref< AbstractMixtureEstimator >::Ref(), and Core::WeakRef< const LemmaPronunciationAlphabet >::WeakRef().
template<class T> Object* Core::WeakRef< T >::get () const inline
Explicit conversion to normal pointer.
Definition at line 474 of file ReferenceCounting.hh.
template<class T> Core::WeakRef< T >::operator bool () const inline
Test for non-voidness.
Definition at line 455 of file ReferenceCounting.hh.
template<class T> bool Core::WeakRef< T >::operator! () const inline
Test for voidness.
Definition at line 459 of file ReferenceCounting.hh.
template<class T> bool Core::WeakRef< T >::operator!= (const WeakRef< T > & r) const inline
Test for non-identity.
Definition at line 442 of file ReferenceCounting.hh.
template<class T> bool Core::WeakRef< T >::operator== (const WeakRef< T > & r) const inline
Test for identity.
Definition at line 430 of file ReferenceCounting.hh.
template<class T> void Core::WeakRef< T >::reset () inline
Reset to void.
Corresponds to assigning zero to normal pointer.
Definition at line 424 of file ReferenceCounting.hh.
The documentation for this class was generated from the following file:
ReferenceCounting.hh