Sprint: Flf::StaticBoundaries Class Reference
Flf::StaticBoundaries Class Reference
Public Types
typedef Precursor::iterator iterator
typedef Precursor::const_iterator const_iterator
Public Types inherited from Core::Vector< Boundary >
typedef std::vector< Boundary > Precursor
typedef Precursor::iterator iterator
typedef Precursor::const_iterator const_iterator
Public Member Functions
bool operator== (const StaticBoundaries &boundaries) const
virtual bool valid () const
false, if the lattice provides no boundaries
virtual bool valid (Fsa::StateId sid) const
false, if that specific boundary does not exist or is invalid, e.g.
virtual const Boundary & get (Fsa::StateId sid) const
return a specific boundary; for every sid a boundary is returned !valid(sid) => !get(sid).valid()
bool set (Fsa::StateId sid, const Boundary &boundary)
set and return true, if precondition !valid(sid)
void del (Fsa::StateId sid)
postcondition: !valid(sid)
Public Member Functions inherited from Core::Vector< Boundary >
Vector (size_t size)
Vector (size_t size, const Boundary &def)
Vector (const Precursor &vector)
void grow (size_t maxId, const Boundary &def=Boundary())
grow to size maxId+1.
void yield ()
Free over-allocated storage.
void minimize ()
void set (size_t id, const Boundary &val, const Boundary &def=Boundary())
safe set
Boundary get (size_t id, const Boundary &def=Boundary()) const
safe get
size_t getMemoryUsed () const
Public Member Functions inherited from Flf::Boundaries
Speech::TimeframeIndex time (Fsa::StateId sid) const
undefined, if !valid(sid)
Boundary::Transit transit (Fsa::StateId sid) const
undefined, if !valid(sid)
void dumpBoundary (Fsa::StateId sid, std::ostream &os) const
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Private Types
typedef Core::Vector< Boundary > Precursor
Detailed Description
Definition at line 183 of file Boundaries.hh.
Member Function Documentation
void Flf::StaticBoundaries::del (Fsa::StateId sid)
postcondition: !valid(sid)
Definition at line 77 of file Boundaries.cc.
virtual const Boundary& Flf::StaticBoundaries::get (Fsa::StateId sid) const inline virtual
return a specific boundary; for every sid a boundary is returned !valid(sid) => !get(sid).valid()
Implements Flf::Boundaries.
Definition at line 204 of file Boundaries.hh.
Referenced by Flf::NBestBuilder::initialize(), and Flf::ExpandTransitsNode::sync().
bool Flf::StaticBoundaries::set (Fsa::StateId sid, const Boundary & boundary)
set and return true, if precondition !valid(sid)
Definition at line 69 of file Boundaries.cc.
References Flf::Boundaries::valid().
Referenced by Flf::decodeRescoreLm(), Flf::expandTransits(), Flf::NBestBuilder::initialize(), Flf::sausageLattice2cn(), and Flf::ExpandTransitsNode::sync().
virtual bool Flf::StaticBoundaries::valid () const inline virtual
false, if the lattice provides no boundaries
Implements Flf::Boundaries.
Definition at line 198 of file Boundaries.hh.
virtual bool Flf::StaticBoundaries::valid (Fsa::StateId sid) const inline virtual
false, if that specific boundary does not exist or is invalid, e.g.
not set !valid() => !valid(sid) for all state id
Implements Flf::Boundaries.
Definition at line 201 of file Boundaries.hh.
The documentation for this class was generated from the following files:
Boundaries.hh
Boundaries.cc