Sprint: Ftl::ConcatUnionAutomaton< _Automaton > Class Template Reference
Ftl::ConcatUnionAutomaton< _Automaton > Class Template Reference abstract
Public Types
typedef _Automaton::ConstSemiringRef _ConstSemiringRef
typedef _Automaton::ConstRef _ConstAutomatonRef
Public Member Functions
virtual Fsa::StateId initialStateId () const
ConcatUnionAutomaton (const Core::Vector< _ConstAutomatonRef > &fsa)
virtual std::string name () const =0
virtual Fsa::Type type () const
virtual _ConstSemiringRef semiring () const
virtual Fsa::ConstAlphabetRef getInputAlphabet () const
virtual Fsa::ConstAlphabetRef getOutputAlphabet () const
virtual void dumpState (Fsa::StateId s, std::ostream &o) const
virtual size_t getMemoryUsed () const
virtual void dumpMemoryUsage (Core::XmlWriter &o) const
virtual std::string describe () const
u32 subAutomaton (Fsa::StateId s) const
Index of sub-automaton.
Fsa::StateId subStateId (Fsa::StateId s) const
Id of state in sub-automaton.
Protected Member Functions
Fsa::StateId superStateId (u32 automaton, Fsa::StateId subState) const
Id of state in super-automaton.
Static Protected Member Functions
static Fsa::ConstAlphabetRef uniteAlphabets (const Core::Vector< Fsa::ConstAlphabetRef > &alphabets, Core::Vector< Fsa::AlphabetMapping > &mappings)
Compute union of alphabets.
Protected Attributes
Fsa::Type type_
_ConstSemiringRef semiring_
Core::Vector< _ConstAutomatonRef > fsa_
Fsa::ConstAlphabetRef input_
Fsa::ConstAlphabetRef output_
Core::Vector< Fsa::AlphabetMapping > inputMappings_
Core::Vector< Fsa::AlphabetMapping > outputMappings_
Private Types
typedef _Automaton Precursor
Detailed Description
template<class _Automaton>
class Ftl::ConcatUnionAutomaton< _Automaton >
Definition at line 197 of file tRational.cc.
Member Function Documentation
template<class _Automaton > u32 Ftl::ConcatUnionAutomaton< _Automaton >::subAutomaton (Fsa::StateId s) const inline
Index of sub-automaton.
Definition at line 327 of file tRational.cc.
template<class _Automaton > Fsa::StateId Ftl::ConcatUnionAutomaton< _Automaton >::subStateId (Fsa::StateId s) const inline
Id of state in sub-automaton.
Definition at line 331 of file tRational.cc.
template<class _Automaton > Fsa::StateId Ftl::ConcatUnionAutomaton< _Automaton >::superStateId (u32 automaton, Fsa::StateId subState) const inline protected
Id of state in super-automaton.
Definition at line 212 of file tRational.cc.
template<class _Automaton > static Fsa::ConstAlphabetRef Ftl::ConcatUnionAutomaton< _Automaton >::uniteAlphabets (const Core::Vector< Fsa::ConstAlphabetRef > & alphabets, Core::Vector< Fsa::AlphabetMapping > & mappings) inline static protected
Compute union of alphabets.
If the first alphabet already contains all symbols, it is returned. Otherwise a StaticAlphabet is created and all symbols from all alphabets are added to it. In both cases a list of mapping is created, which map to the alphabet that is returned.
Parameters
alphabets input: a list of alphabets
mappings output: a list of mappings that map each alphabet to the returned union alphabet.
Returns
an alphabet containing the union of all symbols of all alphabets
Definition at line 229 of file tRational.cc.
References Fsa::StaticAlphabet::addSymbol(), Fsa::AlphabetMapping::map(), Fsa::mapAlphabet(), Fsa::PropertyStorage, Fsa::AlphabetMapping::type(), and Fsa::AlphabetMapping::typeComplete.
The documentation for this class was generated from the following file:
tRational.cc