Sprint: BisonParser::ArithmeticExpressionParser Class Reference
BisonParser::ArithmeticExpressionParser Class Reference
A Bison parser.
#include <ArithmeticExpressionParser.hh>
Classes
struct basic_symbol
A complete symbol.
struct by_state
Type access provider for state based symbols.
struct by_type
Type access provider for token (enum) based symbols.
union semantic_type
Symbol semantic values.
struct stack_symbol_type
"Internal" symbol: element of the stack.
struct syntax_error
Syntax errors thrown from user actions.
struct token
Tokens.
Public Types
enum { empty_symbol = -2 }
The symbol type number to denote an empty symbol.
typedef location location_type
Symbol locations.
typedef token::yytokentype token_type
(External) token type, as returned by yylex.
typedef int symbol_number_type
Symbol type: an internal symbol number.
typedef unsigned char token_number_type
Internal symbol number for tokens (subsumed by symbol_number_type).
typedef basic_symbol< by_type > symbol_type
"External" symbols: returned by the scanner.
typedef int debug_level_type
Type for debugging levels.
Public Member Functions
ArithmeticExpressionParser (Core::ArithmeticExpressionParserDriver *driver_yyarg)
Build a parser object.
virtual int parse ()
Parse.
std::ostream & debug_stream () const YY_ATTRIBUTE_PURE
The current debugging stream.
void set_debug_stream (std::ostream &)
Set the current debugging stream.
debug_level_type debug_level () const YY_ATTRIBUTE_PURE
The current debugging level.
void set_debug_level (debug_level_type l)
Set the current debugging level.
virtual void error (const location_type &loc, const std::string &msg)
Report a syntax error.
void error (const syntax_error &err)
Report a syntax error.
Private Types
enum {
yyeof_ = 0, yylast_ = 39, yynnts_ = 3, yyfinal_ = 10,
yyterror_ = 1, yyerrcode_ = 256, yyntokens_ = 14
}
Constants.
typedef int state_type
State numbers.
typedef stack< stack_symbol_type > stack_type
Stack type.
Private Member Functions
ArithmeticExpressionParser (const ArithmeticExpressionParser &)
This class is not copyable.
ArithmeticExpressionParser & operator= (const ArithmeticExpressionParser &)
virtual std::string yysyntax_error_ (state_type yystate, const symbol_type &yyla) const
Generate an error message.
state_type yy_lr_goto_state_ (state_type yystate, int yysym)
Compute post-reduction state.
virtual void yy_reduce_print_ (int r)
Report on the debug stream that the rule r is going to be reduced.
virtual void yystack_print_ ()
Print the state stack on the debug stream.
template<typename Base >
void yy_print_ (std::ostream &yyo, const basic_symbol< Base > &yysym) const
Display a symbol type, value and location.
template<typename Base >
void yy_destroy_ (const char *yymsg, basic_symbol< Base > &yysym) const
Reclaim the memory associated to a symbol.
void yypush_ (const char *m, stack_symbol_type &s)
Push a new state on the stack.
void yypush_ (const char *m, state_type s, symbol_type &sym)
Push a new look ahead token on the state on the stack.
void yypop_ (unsigned int n=1)
Pop n symbols the three stacks.
Static Private Member Functions
static bool yy_pact_value_is_default_ (int yyvalue)
Whether the given yypact_ value indicates a defaulted state.
static bool yy_table_value_is_error_ (int yyvalue)
Whether the given yytable_ value indicates a syntax error.
static token_number_type yytranslate_ (int t)
Convert a scanner token number t to a symbol number.
static std::string yytnamerr_ (const char *n)
Convert the symbol name n to a form suitable for a diagnostic.
Private Attributes
int yydebug_
std::ostream * yycdebug_
stack_type yystack_
The stack.
Core::ArithmeticExpressionParserDriver * driver
Static Private Attributes
static const signed char yypact_ninf_ = -7
static const signed char yytable_ninf_ = -1
static const signed char yypact_ []
static const unsigned char yydefact_ []
static const signed char yypgoto_ []
static const signed char yydefgoto_ []
static const unsigned char yytable_ []
static const signed char yycheck_ []
static const unsigned char yystos_ []
static const unsigned char yyr1_ []
static const unsigned char yyr2_ []
static const char *const yytname_ []
For a symbol, its name in clear.
static const unsigned char yyrline_ []
Detailed Description
A Bison parser.
Definition at line 197 of file ArithmeticExpressionParser.hh.
Member Typedef Documentation
typedef int BisonParser::ArithmeticExpressionParser::debug_level_type
Type for debugging levels.
Definition at line 351 of file ArithmeticExpressionParser.hh.
typedef location BisonParser::ArithmeticExpressionParser::location_type
Symbol locations.
Definition at line 215 of file ArithmeticExpressionParser.hh.
typedef stack<stack_symbol_type> BisonParser::ArithmeticExpressionParser::stack_type private
Stack type.
Definition at line 513 of file ArithmeticExpressionParser.hh.
typedef int BisonParser::ArithmeticExpressionParser::state_type private
State numbers.
Definition at line 372 of file ArithmeticExpressionParser.hh.
typedef int BisonParser::ArithmeticExpressionParser::symbol_number_type
Symbol type: an internal symbol number.
Definition at line 240 of file ArithmeticExpressionParser.hh.
typedef basic_symbol<by_type> BisonParser::ArithmeticExpressionParser::symbol_type
"External" symbols: returned by the scanner.
Definition at line 333 of file ArithmeticExpressionParser.hh.
typedef unsigned char BisonParser::ArithmeticExpressionParser::token_number_type
Internal symbol number for tokens (subsumed by symbol_number_type).
Definition at line 246 of file ArithmeticExpressionParser.hh.
typedef token::yytokentype BisonParser::ArithmeticExpressionParser::token_type
(External) token type, as returned by yylex.
Definition at line 237 of file ArithmeticExpressionParser.hh.
Member Enumeration Documentation
anonymous enum
The symbol type number to denote an empty symbol.
Definition at line 243 of file ArithmeticExpressionParser.hh.
anonymous enum private
Constants.
Enumerator
yylast_
Last index in yytable_.
yynnts_
Number of nonterminal symbols.
yyfinal_
Termination state number.
yyntokens_
Number of tokens.
Definition at line 537 of file ArithmeticExpressionParser.hh.
Constructor & Destructor Documentation
BisonParser::ArithmeticExpressionParser::ArithmeticExpressionParser (Core::ArithmeticExpressionParserDriver * driver_yyarg)
Build a parser object.
Definition at line 194 of file ArithmeticExpressionParser.cc.
BisonParser::ArithmeticExpressionParser::ArithmeticExpressionParser (const ArithmeticExpressionParser &) private
This class is not copyable.
Member Function Documentation
ArithmeticExpressionParser::debug_level_type BisonParser::ArithmeticExpressionParser::debug_level () const
The current debugging level.
Definition at line 482 of file ArithmeticExpressionParser.cc.
std::ostream & BisonParser::ArithmeticExpressionParser::debug_stream () const
The current debugging stream.
Definition at line 469 of file ArithmeticExpressionParser.cc.
Referenced by yy_print_().
virtual void BisonParser::ArithmeticExpressionParser::error (const location_type & loc, const std::string & msg) virtual
Report a syntax error.
Parameters
loc where the syntax error is found.
msg a description of the syntax error.
Referenced by error(), parse(), Lm::ArpaLm::read(), and yytranslate_().
void BisonParser::ArithmeticExpressionParser::error (const syntax_error & err)
Report a syntax error.
Definition at line 863 of file ArithmeticExpressionParser.cc.
References error().
int BisonParser::ArithmeticExpressionParser::parse () virtual
Parse.
Returns
0 iff parsing succeeded.
Length of the RHS of the rule being reduced.
The lookahead symbol.
The locations where the error started and ended.
The return value of parse ().
Definition at line 517 of file ArithmeticExpressionParser.cc.
References BisonParser::ArithmeticExpressionParser::basic_symbol< Base >::clear(), BisonParser::ArithmeticExpressionParser::basic_symbol< Base >::empty(), error(), BisonParser::location::location(), BisonParser::ArithmeticExpressionParser::basic_symbol< Base >::location, BisonParser::ArithmeticExpressionParser::by_state::state, BisonParser::ArithmeticExpressionParser::basic_symbol< Base >::value, BisonParser::ArithmeticExpressionParser::basic_symbol< by_state >::value, yy_destroy_(), yy_lr_goto_state_(), yy_pact_value_is_default_(), yy_table_value_is_error_(), yyfinal_, yylast_, yypop_(), yypush_(), yystack_, yysyntax_error_(), and yytranslate_().
void BisonParser::ArithmeticExpressionParser::set_debug_level (debug_level_type l)
Set the current debugging level.
Definition at line 488 of file ArithmeticExpressionParser.cc.
void BisonParser::ArithmeticExpressionParser::set_debug_stream (std::ostream & o)
Set the current debugging stream.
Definition at line 475 of file ArithmeticExpressionParser.cc.
template<typename Base > void BisonParser::ArithmeticExpressionParser::yy_destroy_ (const char * yymsg, basic_symbol< Base > & yysym) const inline private
Reclaim the memory associated to a symbol.
Parameters
yymsg Why this token is reclaimed. If null, print nothing.
yysym The symbol.
Definition at line 394 of file ArithmeticExpressionParser.cc.
Referenced by parse().
ArithmeticExpressionParser::state_type BisonParser::ArithmeticExpressionParser::yy_lr_goto_state_ (state_type yystate, int yysym) inline private
Compute post-reduction state.
Parameters
yystate the current state
yysym the nonterminal to push on the stack
Definition at line 495 of file ArithmeticExpressionParser.cc.
References yylast_, and yyntokens_.
Referenced by parse().
bool BisonParser::ArithmeticExpressionParser::yy_pact_value_is_default_ (int yyvalue) inline static private
Whether the given yypact_ value indicates a defaulted state.
Parameters
yyvalue the value to check
Definition at line 505 of file ArithmeticExpressionParser.cc.
Referenced by parse(), and yysyntax_error_().
template<typename Base > void BisonParser::ArithmeticExpressionParser::yy_print_ (std::ostream & yyo, const basic_symbol< Base > & yysym) const private
Display a symbol type, value and location.
Parameters
yyo The output stream.
yysym The symbol.
Definition at line 406 of file ArithmeticExpressionParser.cc.
References debug_stream(), BisonParser::ArithmeticExpressionParser::basic_symbol< Base >::empty(), BisonParser::ArithmeticExpressionParser::basic_symbol< Base >::location, BisonParser::ArithmeticExpressionParser::basic_symbol< Base >::value, yyntokens_, and yytname_.
void BisonParser::ArithmeticExpressionParser::yy_reduce_print_ (int r) private virtual
Report on the debug stream that the rule r is going to be reduced.
Definition at line 1072 of file ArithmeticExpressionParser.cc.
References yystack_.
bool BisonParser::ArithmeticExpressionParser::yy_table_value_is_error_ (int yyvalue) inline static private
Whether the given yytable_ value indicates a syntax error.
Parameters
yyvalue the value to check
Definition at line 511 of file ArithmeticExpressionParser.cc.
Referenced by parse(), and yysyntax_error_().
void BisonParser::ArithmeticExpressionParser::yypop_ (unsigned int n = 1) inline private
Pop n symbols the three stacks.
Definition at line 462 of file ArithmeticExpressionParser.cc.
References yystack_.
Referenced by parse().
void BisonParser::ArithmeticExpressionParser::yypush_ (const char * m, stack_symbol_type & s) inline private
Push a new state on the stack.
Parameters
m a debug message to display if null, no trace is output.
s the symbol
Warning
the contents of s.value is stolen.
Definition at line 453 of file ArithmeticExpressionParser.cc.
References BisonParser::stack< T, S >::push(), and yystack_.
Referenced by parse(), and yypush_().
void BisonParser::ArithmeticExpressionParser::yypush_ (const char * m, state_type s, symbol_type & sym) inline private
Push a new look ahead token on the state on the stack.
Parameters
m a debug message to display if null, no trace is output.
s the state
sym the symbol (for its value and location).
Warning
the contents of s.value is stolen.
Definition at line 445 of file ArithmeticExpressionParser.cc.
References yypush_().
void BisonParser::ArithmeticExpressionParser::yystack_print_ () private virtual
Print the state stack on the debug stream.
Definition at line 1059 of file ArithmeticExpressionParser.cc.
References yystack_.
std::string BisonParser::ArithmeticExpressionParser::yysyntax_error_ (state_type yystate, const symbol_type & yyla) const private virtual
Generate an error message.
Parameters
yystate the state where the error occurred.
yyla the lookahead token.
Definition at line 870 of file ArithmeticExpressionParser.cc.
References BisonParser::ArithmeticExpressionParser::basic_symbol< Base >::empty(), yy_pact_value_is_default_(), yy_table_value_is_error_(), yylast_, yyntokens_, yytname_, and yytnamerr_().
Referenced by parse().
std::string BisonParser::ArithmeticExpressionParser::yytnamerr_ (const char * n) static private
Convert the symbol name n to a form suitable for a diagnostic.
Definition at line 161 of file ArithmeticExpressionParser.cc.
Referenced by yysyntax_error_().
ArithmeticExpressionParser::token_number_type BisonParser::ArithmeticExpressionParser::yytranslate_ (int t) inline static private
Convert a scanner token number t to a symbol number.
Definition at line 1089 of file ArithmeticExpressionParser.cc.
References error(), and Core::form().
Referenced by parse().
Member Data Documentation
const signed char BisonParser::ArithmeticExpressionParser::yycheck_ static private
Initial value:
=
  {
       3,     4,     8,     9,     7,    11,     0,    12,    11,    12,
      13,    14,    15,     3,     4,    11,    -1,     7,     6,     7,
       8,     9,    12,    11,    -1,    13,     6,     7,     8,     9,
      -1,    11,    -1,    13,     6,     7,     8,     9,    -1,    11
  }
Definition at line 420 of file ArithmeticExpressionParser.hh.
const unsigned char BisonParser::ArithmeticExpressionParser::yydefact_ static private
Initial value:
=
  {
       0,     0,     3,     0,     0,     0,     2,     0,     9,     0,
       1,     0,     0,     0,     0,     0,     0,    11,     5,     6,
       7,     8,    10,     4
  }
Definition at line 407 of file ArithmeticExpressionParser.hh.
const signed char BisonParser::ArithmeticExpressionParser::yydefgoto_ static private
Initial value:
=
  {
      -1,     5,     6
  }
Definition at line 413 of file ArithmeticExpressionParser.hh.
const signed char BisonParser::ArithmeticExpressionParser::yypact_ static private
Initial value:
=
  {
      10,    -5,    -7,    10,    10,     6,    28,    10,     4,    12,
      -7,    10,    10,    10,    10,    10,    20,    -7,    -6,    -6,
       4,     4,     4,    -7
  }
Definition at line 402 of file ArithmeticExpressionParser.hh.
const signed char BisonParser::ArithmeticExpressionParser::yypgoto_ static private
Initial value:
=
  {
      -7,    -7,    -3
  }
Definition at line 410 of file ArithmeticExpressionParser.hh.
const unsigned char BisonParser::ArithmeticExpressionParser::yyr1_ static private
Initial value:
=
  {
       0,    14,    15,    16,    16,    16,    16,    16,    16,    16,
      16,    16
  }
Definition at line 427 of file ArithmeticExpressionParser.hh.
const unsigned char BisonParser::ArithmeticExpressionParser::yyr2_ static private
Initial value:
=
  {
       0,     2,     1,     1,     4,     3,     3,     3,     3,     2,
       3,     3
  }
Definition at line 430 of file ArithmeticExpressionParser.hh.
const unsigned char BisonParser::ArithmeticExpressionParser::yyrline_ static private
Initial value:
=
  {
       0,   108,   108,   115,   116,   117,   118,   119,   120,   121,
     122,   123
  }
Definition at line 441 of file ArithmeticExpressionParser.hh.
stack_type BisonParser::ArithmeticExpressionParser::yystack_ private
The stack.
Definition at line 516 of file ArithmeticExpressionParser.hh.
Referenced by parse(), yy_reduce_print_(), yypop_(), yypush_(), and yystack_print_().
const unsigned char BisonParser::ArithmeticExpressionParser::yystos_ static private
Initial value:
=
  {
       0,     3,     4,     7,    12,    15,    16,    12,    16,    16,
       0,     6,     7,     8,     9,    11,    16,    13,    16,    16,
      16,    16,    16,    13
  }
Definition at line 424 of file ArithmeticExpressionParser.hh.
const unsigned char BisonParser::ArithmeticExpressionParser::yytable_ static private
Initial value:
=
  {
       8,     9,    13,    14,    16,    15,    10,     7,    18,    19,
      20,    21,    22,     1,     2,    15,     0,     3,    11,    12,
      13,    14,     4,    15,     0,    17,    11,    12,    13,    14,
       0,    15,     0,    23,    11,    12,    13,    14,     0,    15
  }
Definition at line 418 of file ArithmeticExpressionParser.hh.
const char *const BisonParser::ArithmeticExpressionParser::yytname_ static private
Initial value:
=
  {
  "\"end of string\"", "error", "$undefined", "\"function\"",
  "\"number\"", "\"expression\"", "'+'", "'-'", "'*'", "'/'", "NEG", "'^'",
  "'('", "')'", "$accept", "unit", "exp", YY_NULLPTR
  }
For a symbol, its name in clear.
Definition at line 438 of file ArithmeticExpressionParser.hh.
Referenced by yy_print_(), and yysyntax_error_().
The documentation for this class was generated from the following files:
ArithmeticExpressionParser.hh
ArithmeticExpressionParser.cc