Sprint: Lm::LanguageModel Class Reference
Lm::LanguageModel Class Reference abstract
Abstract language model.
#include <LanguageModel.hh>
Classes
class NonCompiledBatchRequest
Public Member Functions
Token sentenceBeginToken () const
virtual Lm::Score sentenceBeginScore () const
Token sentenceEndToken () const
Token sentenceBoundaryToken () const
virtual void init ()
precondition: the token inventory is set and fixed
virtual void getDependencies (Core::DependencySet &dependencies) const
Bliss::LexiconRef lexicon () const
const TokenInventory & tokenInventory () const
Fsa::ConstAlphabetRef tokenAlphabet () const
virtual Fsa::ConstAutomatonRef getFsa () const
Convert language model into an EQUIVALENT acceptor.
virtual History startHistory () const =0
Language model history for beginning of a sentence.
virtual History extendedHistory (const History &, Token w) const =0
Language model history for the next sentence position.
virtual History reducedHistory (const History &, u32 limit) const
Reduce amount on conditioning information.
virtual std::string formatHistory (const History &h) const
Create string representation of history (mainly for debugging purposes).
virtual Score score (const History &, Token w) const =0
Probability of a token to occur with a given history.
virtual bool scoreCached (const History &, Token w) const
Some LMs might cache scores and thus provide fast access.
virtual Score sentenceEndScore (const History &) const
Probability for sentence to end in current position.
virtual CompiledBatchRequest * compileBatchRequest (const BatchRequest &, Score scale=1.0) const
Preprocess a batch request.
virtual void getBatch (const History &h, const CompiledBatchRequest *r, std::vector< f32 > &result) const
Get probabilities for a (large) set of syntactic tokens given a history.
virtual Core::Ref< const LanguageModel > lookaheadLanguageModel () const
Returns the LanguageModel that shall be used for lookahead (useful for CombinedLM when we do not want to reinstanciate the model)
virtual Core::Ref< const LanguageModel > recombinationLanguageModel () const
Returns the LanguageModel that shall be used for recombination (useful for CombinedLM when we do not want to reinstanciate the model)
virtual void setSegment (Bliss::SpeechSegment const *s)
For some cheating language models we need to know the correct transcription.
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Protected Member Functions
History history (HistoryHandle hd) const
template<class LM >
const LM::HistoryDescriptor * descriptor (const History &hh) const
void setTokenInventory (const TokenInventory *_tokenInventory)
void setTokenInventoryAndAlphabet (const TokenInventory *_tokenInventory, Fsa::ConstAlphabetRef _tokenAlphabet)
Token getToken (const std::string &word) const
virtual Token getSpecialToken (const std::string &name, bool required=false) const
const Bliss::SyntacticToken * getSpecialSyntacticToken (const std::string &name, bool required) const
Token fallbackToken () const
Find token to use for unknown words.
virtual void createSpecialTokens ()
virtual void load ()
void requireSentenceBoundaryToken ()
Call this function before init(), iff your language model requires a sentence boundary token to be defined in the lexicon.
LanguageModel (const Core::Configuration &c, Bliss::LexiconRef l)
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes
HistoryManager * historyManager_
Concrete LanguageModels should set this member in their constructor or load() method.
Core::Dependency dependency_
Protected Attributes inherited from Core::Configurable
Configuration config
Private Attributes
Bliss::LexiconRef lexicon_
const TokenInventory * tokenInventory_
Fsa::ConstAlphabetRef tokenAlphabet_
Token fallbackToken_
Token sentenceBeginToken_
Token sentenceEndToken_
bool requiresSentenceBoundaryToken_
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Detailed Description
Abstract language model.
This class provides the abtract state machine interface used by all language models in Sprint.
Design: An abstract state object (of class History) is used to describe the history (preceeding words). History object can be used to inquire the probability of the next word (score()), and they can be extended by a word (extendHistory()). The (concrete) language model itself specifies what information is stored in the history descriptor.
Building your own language model: Mimimally, you have to implement the three abstract (prue virtual) methods startHistory(), extendHistory() and score(). Some other methods only have inefficient default implmentations, you might have to overload them.
On sentence boundaries: In order to fit sentence boundary modelling smoothly into the n-gram method, one commoly introduces special sentence boundary tokens. Finite state grammars will normally not do this: Here the initial state and final scores do the job. For n-gram models however, there are two common conventions: A. The nesting-oriented (two symbol) approach uses one token for the beginning of the sentence and one for the end of the sentence. Borrowing from XML/SGML syntax these are commonly denoted as "<s>" and "</s>" respectively. It is silently assumed that p(<s> | </s>) = 1. B. The stream-oriented (one symbol) approach uses only a single sentence boundary symbol. In XML-ish syntax it should be called "<s/>", but common symbols are "@", "<s>" (which would be aprropriate in SGML), and "</s>" (which would be wrong in both XML and SGML).
Definition at line 240 of file Lm/LanguageModel.hh.
Member Function Documentation
CompiledBatchRequest * LanguageModel::compileBatchRequest (const BatchRequest & request, Score scale = 1.0) const virtual
Preprocess a batch request.
Returns
a pre-compiled batch request which can be used with getBatch()
Reimplemented in Lm::LanguageModelScaling.
Definition at line 169 of file Lm/LanguageModel.cc.
Referenced by Lm::LanguageModelScaling::compileBatchRequest(), and Lm::FsaLm::sentenceEndScore().
virtual History Lm::LanguageModel::extendedHistory (const History & , Token w) const pure virtual
Language model history for the next sentence position.
This is the given history with given word appended, i.e. w becomes the most recent word. Typically the returned history will reflect the finite memory of the language model: for an m-gram it will only contain the m-1 most recent words. In WFST terminology this is the target state of the outgoin arc labeled w.
Implemented in Lm::ArpaClassLm, Lm::WordlistInterfaceLm, Lm::BackingOffLm, Lm::TFRecurrentLanguageModel, Lm::LanguageModelScaling, Lm::FsaLm, Lm::CombineLanguageModel, Lm::FFNeuralNetworkLanguageModel, and Lm::Zerogram.
Referenced by Lm::addLemmaScore(), Lm::addLemmaScoreOmitExtension(), Lm::LanguageModelScaling::extendedHistory(), Lm::extendHistoryByLemma(), and Search::SearchSpace::optimizeSilenceInWordLattice().
Token Lm::LanguageModel::fallbackToken () const inline protected
Find token to use for unknown words.
This function should be used by language model initialization routines to replace any syntactic token that is unknown to the language model. (In this case a warning must be issued.)
Definition at line 300 of file Lm/LanguageModel.hh.
virtual std::string Lm::LanguageModel::formatHistory (const History & h) const inline virtual
Create string representation of history (mainly for debugging purposes).
By default this function just delegates to History::format(), but language models may specialize formatHistory() to give more readable information, which would be inaccessible from the HistoryDescriptor alone. If your language model is m-gram like, describe the history chronologically, i.e. most recent word last.
Reimplemented in Lm::WordlistInterfaceLm, Lm::BackingOffLm, and Lm::LanguageModelScaling.
Definition at line 431 of file Lm/LanguageModel.hh.
References Lm::History::format().
Referenced by Lm::LanguageModelScaling::formatHistory(), and LmComposeInternal::ComposeAutomaton::history().
void LanguageModel::getBatch (const History & h, const CompiledBatchRequest * r, std::vector< f32 > & result) const virtual
Get probabilities for a (large) set of syntactic tokens given a history.
This is mainly useful for LanguageModelLookahead.
Warning
Default implementation is inefficient.
Parameters
h history
r pre-compiled batch request created using compileBatchRequest()
result a vector in which results are stored (output parameter)
Reimplemented in Lm::BackingOffLm, and Lm::LanguageModelScaling.
Definition at line 175 of file Lm/LanguageModel.cc.
References required_cast.
Referenced by Lm::LanguageModelScaling::getBatch(), and Lm::FsaLm::sentenceEndScore().
Fsa::ConstAutomatonRef LanguageModel::getFsa () const virtual
Convert language model into an EQUIVALENT acceptor.
Keep in mind that the default method may produce transducers that are very large. Note: This does just convert your language model to a different format, it does NOT implement the language model.
Labels of the resulting acceptor are syntactic token ids.
Reimplemented in Lm::ArpaClassLm, Lm::BackingOffLm, Lm::LanguageModelScaling, Lm::FsaLm, and Lm::Zerogram.
Definition at line 154 of file Lm/LanguageModel.cc.
References Core::Component::criticalError().
Referenced by Lm::LanguageModelScaling::getFsa(), Search::Wfst::Builder::BuildGrammar::process(), and Speech::OfflineRecognizer::setFeatureDescription().
void LanguageModel::init () virtual
precondition: the token inventory is set and fixed
Initalize language model. This method is called immeditelly after construction. Implement this function in order to perform all non-trivial initialization, like reading the language model from a file.
Reimplemented in Lm::LanguageModelScaling.
Definition at line 52 of file Lm/LanguageModel.cc.
References require.
Referenced by Lm::Module_::createLanguageModel(), and Lm::LanguageModelScaling::init().
Core::Ref< const LanguageModel > LanguageModel::lookaheadLanguageModel () const virtual
Returns the LanguageModel that shall be used for lookahead (useful for CombinedLM when we do not want to reinstanciate the model)
Returns
the LM that should be used for lookahead, can be nullptr (in that case this LM should be used)
Reimplemented in Lm::LanguageModelScaling, and Lm::CombineLanguageModel.
Definition at line 202 of file Lm/LanguageModel.cc.
Referenced by Lm::LanguageModelScaling::lookaheadLanguageModel(), and Search::SearchSpace::SearchSpace().
Core::Ref< const LanguageModel > LanguageModel::recombinationLanguageModel () const virtual
Returns the LanguageModel that shall be used for recombination (useful for CombinedLM when we do not want to reinstanciate the model)
Returns
the LM that should be used for recombination, can be nullptr (in that case this LM should be used)
Reimplemented in Lm::LanguageModelScaling, and Lm::CombineLanguageModel.
Definition at line 206 of file Lm/LanguageModel.cc.
Referenced by Lm::LanguageModelScaling::recombinationLanguageModel(), and Search::SearchSpace::SearchSpace().
History LanguageModel::reducedHistory (const History & h, u32 limit) const virtual
Reduce amount on conditioning information.
In theory extendHistory() adds more and more information to the distory descriptor. Most reasonable language models will drop irrelevant information. E.g. a trigram LM will actually store only two words in its history objects; so the number of distinct histories is size of vocabulary squared. In some situations one wants to limit the number of histories considered, by reducing the amount of conditioning information in the history. E.g. when using a bigram lookahead in a trigram search. This is the purpose of reducedHistory().
Parameters
limit Maximum amount of conditioning information in the returned history. The meaning this parameter is dependent on the language model. In general higher values mean more longer histories. The default implementation returns the given history unchanged.
Reimplemented in Lm::WordlistInterfaceLm, Lm::BackingOffLm, Lm::TFRecurrentLanguageModel, Lm::LanguageModelScaling, and Lm::CombineLanguageModel.
Definition at line 159 of file Lm/LanguageModel.cc.
Referenced by Lm::LanguageModelScaling::reducedHistory(), and Search::SearchSpace::setAllowHmmSkips().
void Lm::LanguageModel::requireSentenceBoundaryToken () inline protected
Call this function before init(), iff your language model requires a sentence boundary token to be defined in the lexicon.
Definition at line 334 of file Lm/LanguageModel.hh.
References Core::DependencySet::add(), and require.
virtual Score Lm::LanguageModel::score (const History & , Token w) const pure virtual
Probability of a token to occur with a given history.
Returns
: negative natural(!) logarithm of probability of the token w to occur with history h , i.e. -log(p(w|h))
Note on syntactic classes: The Bliss lexicon can map several lexicon entries (lemmas) to the same syntactic token. Conceptually we can write this case as p(lemma | history) = p(lemma | synt) p(synt | history). However this function returns only p(synt | history). Clients have to add the lemmaScore -log(p(lemma | synt)) when needed.
Note on pronunciation variants: Pronuciation probabilities are not into account.
Implemented in Lm::ArpaClassLm, Lm::BackingOffLm, Lm::TFRecurrentLanguageModel, Lm::LanguageModelScaling, Lm::FsaLm, Lm::CombineLanguageModel, Lm::FFNeuralNetworkLanguageModel, and Lm::Zerogram.
Referenced by Lm::addLemmaPronunciationScore(), Lm::addLemmaPronunciationScoreOmitExtension(), Lm::addLemmaScoreOmitExtension(), Lm::addSyntacticTokenScore(), and Lm::LanguageModelScaling::score().
virtual bool Lm::LanguageModel::scoreCached (const History & , Token w) const inline virtual
Some LMs might cache scores and thus provide fast access.
If we use the skip heuristic in the combined LM we do not have to skip if the score is computed anyway.
Reimplemented in Lm::TFRecurrentLanguageModel.
Definition at line 459 of file Lm/LanguageModel.hh.
Lm::Score LanguageModel::sentenceEndScore (const History & h) const virtual
Probability for sentence to end in current position.
In WFST terminology this is the final weight. If the lexicon defines a "sentence-end" special token this must be equivalent to getScore(h, sentenceBoundaryToken()). The default implementation does just this.
Returns
negative natural(!) logarithm of probability of sentence end, i.e. -log(p(EOS|h))
Reimplemented in Lm::LanguageModelScaling, Lm::FsaLm, and Lm::CombineLanguageModel.
Definition at line 163 of file Lm/LanguageModel.cc.
References require.
Referenced by Flf::decodeRescoreLm(), WordConditionedTreeSearch::SearchSpace::getSentenceEnd(), Search::SearchSpace::getSentenceEnd(), WordConditionedTreeSearch::SearchSpace::getSentenceEndFallBack(), Search::SearchSpace::getSentenceEndFallBack(), LmComposeInternal::ComposeAutomaton::history(), and Lm::LanguageModelScaling::sentenceEndScore().
void LanguageModel::setSegment (Bliss::SpeechSegment const * s) virtual
For some cheating language models we need to know the correct transcription.
Language models that are used for real recognition MUST NOT implement this.
Parameters
s the current segment
Reimplemented in Lm::LanguageModelScaling, Lm::CombineLanguageModel, and Lm::CheatingSegmentLm.
Definition at line 210 of file Lm/LanguageModel.cc.
Referenced by Lm::LanguageModelScaling::setSegment().
virtual History Lm::LanguageModel::startHistory () const pure virtual
Language model history for beginning of a sentence.
Typically this is the bigram history which contains just the sentence start (or boundary) token. In the terminology of finite-state automata this is the initial state.
Implemented in Lm::WordlistInterfaceLm, Lm::BackingOffLm, Lm::TFRecurrentLanguageModel, Lm::LanguageModelScaling, Lm::FsaLm, Lm::CombineLanguageModel, Lm::FFNeuralNetworkLanguageModel, and Lm::Zerogram.
Referenced by Flf::decodeRescoreLm(), Search::SearchSpace::optimizeSilenceInWordLattice(), Search::SearchSpace::setAllowHmmSkips(), and Lm::LanguageModelScaling::startHistory().
Member Data Documentation
HistoryManager* Lm::LanguageModel::historyManager_ protected
Concrete LanguageModels should set this member in their constructor or load() method.
It is entirely legitimate to inherit HistoryManager and set historyManager_ = this.
Definition at line 248 of file Lm/LanguageModel.hh.
Referenced by Lm::FsaLm::HistoryManager::isEquivalent().
The documentation for this class was generated from the following files:
Lm/LanguageModel.hh
Lm/LanguageModel.cc