Sprint: Bliss::CorpusDescription::ProgressIndicationVisitorAdaptor Class Reference
Bliss::CorpusDescription::ProgressIndicationVisitorAdaptor Class Reference
Public Member Functions
void setVisitor (CorpusVisitor *v)
void setTotal (u32 n)
virtual void visitSegment (Segment *s)
Template method for processing segments.
virtual void visitSpeechSegment (SpeechSegment *s)
Template method for processing speech segments.
virtual void enterRecording (Recording *r)
Template method called when corpus traversal enters a recording.
virtual void leaveRecording (Recording *r)
Template method called when corpus traversal leaves a recording.
virtual void enterCorpus (Corpus *c)
Template method notifying start of a (sub-) corpus.
virtual void leaveCorpus (Corpus *c)
Template method notifying end of a (sub-) corpus.
Private Attributes
u32 nSegments_
CorpusVisitor * visitor_
Core::ProgressIndicator pi_
Detailed Description
Definition at line 423 of file CorpusDescription.cc.
Member Function Documentation
virtual void Bliss::CorpusDescription::ProgressIndicationVisitorAdaptor::enterCorpus (Corpus *) inline virtual
Template method notifying start of a (sub-) corpus.
This is rarely needed.
Reimplemented from Bliss::CorpusVisitor.
Definition at line 452 of file CorpusDescription.cc.
References Bliss::CorpusVisitor::enterCorpus(), Core::ProgressIndicator::setTask(), and Core::ProgressIndicator::start().
virtual void Bliss::CorpusDescription::ProgressIndicationVisitorAdaptor::enterRecording (Recording *) inline virtual
Template method called when corpus traversal enters a recording.
Implement this to take appropriate actions, e.g. opening the audio file.
Reimplemented from Bliss::CorpusVisitor.
Definition at line 446 of file CorpusDescription.cc.
References Bliss::CorpusVisitor::enterRecording().
virtual void Bliss::CorpusDescription::ProgressIndicationVisitorAdaptor::leaveCorpus (Corpus *) inline virtual
Template method notifying end of a (sub-) corpus.
This is rarely needed.
Reimplemented from Bliss::CorpusVisitor.
Definition at line 458 of file CorpusDescription.cc.
References defect, Core::ProgressIndicator::finish(), Bliss::CorpusVisitor::leaveCorpus(), and verify.
virtual void Bliss::CorpusDescription::ProgressIndicationVisitorAdaptor::leaveRecording (Recording *) inline virtual
Template method called when corpus traversal leaves a recording.
Implement this to take appropriate clean-up actions, e.g. closing the audio file.
Reimplemented from Bliss::CorpusVisitor.
Definition at line 449 of file CorpusDescription.cc.
References Bliss::CorpusVisitor::leaveRecording().
virtual void Bliss::CorpusDescription::ProgressIndicationVisitorAdaptor::visitSegment (Segment *) inline virtual
Template method for processing segments.
Implement this to process speech and non-speech segments of a corpus.
Reimplemented from Bliss::SegmentVisitor.
Definition at line 438 of file CorpusDescription.cc.
References Core::ProgressIndicator::notify(), and Bliss::SegmentVisitor::visitSegment().
virtual void Bliss::CorpusDescription::ProgressIndicationVisitorAdaptor::visitSpeechSegment (SpeechSegment * s) inline virtual
Template method for processing speech segments.
Implement this to process the speech segments of a corpus. By default the request will be forwarded to visitSegment(), so ignore this if you want to treat speech and non-speech segments alike.
Reimplemented from Bliss::SegmentVisitor.
Definition at line 442 of file CorpusDescription.cc.
References Core::ProgressIndicator::notify(), and Bliss::SegmentVisitor::visitSpeechSegment().
The documentation for this class was generated from the following file:
CorpusDescription.cc