Sprint: Search::LanguageModelLookahead::ConstructionTree Class Reference
Search::LanguageModelLookahead::ConstructionTree Class Reference
Classes
struct LevelStatistics
Public Member Functions
bool isWellOrdered () const
Check wether each node has a lower index than its parent.
void writeStatistics (std::ostream &) const
void build (HMMStateNetwork const &tree, StateId rootNode, const std::vector< PersistentStateTree::Exit > &exits, Bliss::LexiconRef lexicon)
void prune (const LanguageModelLookahead *master)
Merge nodes of construction tree which should be pruned with their parents.
void purge ()
Remove pruned nodes from construction tree.
LookaheadId nNodes () const
const ConstructionNode & node (LookaheadId i) const
bool isWellOrdered () const
void writeStatistics (std::ostream &) const
void build (const StateTree *st)
void prune (const LanguageModelLookahead *master)
void purge ()
LookaheadId nNodes () const
const ConstructionNode & node (LookaheadId i) const
Private Types
typedef std::vector< ConstructionNode * > NodeList
typedef std::vector< ConstructionNode * > NodeList
Private Attributes
NodeList nodeList_
Detailed Description
Definition at line 506 of file AdvancedTreeSearch/LanguageModelLookahead.cc.
Member Function Documentation
void Search::LanguageModelLookahead::ConstructionTree::build (HMMStateNetwork const & tree, StateId rootNode, const std::vector< PersistentStateTree::Exit > & exits, Bliss::LexiconRef lexicon)
Forward the node. No branching, so no new node needs to be created
Branching happens in this place, need a new node that has the others as followers
Definition at line 584 of file AdvancedTreeSearch/LanguageModelLookahead.cc.
References ensure, Bliss::LemmaPronunciation::invalidId, Search::HMMStateNetwork::state(), Search::HMMStateNetwork::stateCount(), Search::HMMState::stateDesc, and verify.
Referenced by Search::LanguageModelLookahead::buildCompressesLookaheadStructure().
bool Search::LanguageModelLookahead::ConstructionTree::isWellOrdered () const
Check wether each node has a lower index than its parent.
Definition at line 540 of file AdvancedTreeSearch/LanguageModelLookahead.cc.
References verify.
Referenced by Search::LanguageModelLookahead::buildCompressesLookaheadStructure().
void Search::LanguageModelLookahead::ConstructionTree::prune (const LanguageModelLookahead * master)
Merge nodes of construction tree which should be pruned with their parents.
Proceed in in bottom-up direction. A pruned nodes is indicated by its id field being invalid. Call purge() to remove pruned nodes.
Definition at line 805 of file AdvancedTreeSearch/LanguageModelLookahead.cc.
References ensure, Search::LanguageModelLookahead::shouldPruneConstructionNode(), and verify.
Referenced by Search::LanguageModelLookahead::buildCompressesLookaheadStructure(), and Search::LanguageModelLookahead::shouldPruneConstructionNode().
void Search::LanguageModelLookahead::ConstructionTree::purge ()
Remove pruned nodes from construction tree.
Definition at line 835 of file AdvancedTreeSearch/LanguageModelLookahead.cc.
References ensure.
Referenced by Search::LanguageModelLookahead::buildCompressesLookaheadStructure(), and Search::LanguageModelLookahead::shouldPruneConstructionNode().
The documentation for this class was generated from the following file:
AdvancedTreeSearch/LanguageModelLookahead.cc