Sprint: Search::Wfst::Builder::FileOperation Class Reference
Search::Wfst::Builder::FileOperation Class Reference
base class for file operations
#include <IoOperations.hh>
Public Member Functions
FileOperation (const Core::Configuration &c, Resources &r)
Public Member Functions inherited from Search::Wfst::Builder::Operation
Operation (const Core::Configuration &c, Resources &r)
virtual u32 nInputAutomata () const
number of automata required as input
virtual bool consumeInput () const
should input automata be removed
virtual bool hasOutput () const
operation is expected to produce an output automaton.
virtual bool addInput (AutomatonRef)
add input automaton (will be called nInputAutomata() times)
AutomatonRef getResult ()
do the actual processing and create an output automaton
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Protected Types
enum FileType { TypeVector, TypeConst, TypeCompact, TypeNGram }
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions
std::string filename () const
virtual bool precondition () const
precondition for getResult()
Protected Member Functions inherited from Search::Wfst::Builder::Operation
virtual AutomatonRef process ()=0
do the actual processing
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Static Protected Attributes
static const Core::ParameterString paramFilename
static const Core::Choice choiceType
static const Core::ParameterChoice paramType
Additional Inherited Members
Public Types inherited from Search::Wfst::Builder::Operation
typedef Automaton * AutomatonRef
Protected Attributes inherited from Search::Wfst::Builder::Operation
Resources & resources_
Core::XmlChannel timerChannel_
Core::Timer timer_
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
base class for file operations
Definition at line 27 of file IoOperations.hh.
Member Function Documentation
bool FileOperation::precondition () const protected virtual
precondition for getResult()
Reimplemented from Search::Wfst::Builder::Operation.
Reimplemented in Search::Wfst::Builder::WriteOperation.
Definition at line 41 of file IoOperations.cc.
References Core::Component::error(), Core::Component::log(), Core::split(), and verify.
Referenced by Search::Wfst::Builder::WriteOperation::precondition().
The documentation for this class was generated from the following files:
IoOperations.hh
IoOperations.cc