Sprint: Search::Wfst::LexicalFstFactory Class Reference
Search::Wfst::LexicalFstFactory Class Reference
Loads and creates (expanded) lexicon transducers (C o L)
#include <LexiconFst.hh>
Classes
struct Options
Public Types
enum AccumulatorType { DefaultAccumulator, LogAccumulator, FastLogAccumulator }
Public Member Functions
LexicalFstFactory (const Core::Configuration &c)
AbstractLexicalFst * load (const std::string &filename, GrammarType gType, AbstractGrammarFst *g) const
creates LexicalFst from the given filename using parameter values.
AbstractLexicalFst * load (const std::string &filename, const Options &o, AbstractGrammarFst *g) const
creates LexicalFst from the given filename using parameter values, with default values from the given options.
AbstractLexicalFst * convert (OpenFst::VectorFst *base, GrammarType gType, AbstractGrammarFst *g) const
AbstractLexicalFst * convert (OpenFst::VectorFst *base, const Options &o, AbstractGrammarFst *g) const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Member Functions
static AbstractLexicalFst * create (const Options &options)
Factory function to create LexicalFst objects.
Private Types
typedef AbstractGrammarFst::GrammarType GrammarType
typedef FstLib::StdFst StdFst
typedef StdFst::Arc Arc
Private Member Functions
Options parseOptions () const
Options parseOptions (const Options &defaultValues) const
void logOptions (const Options &options) const
AbstractLexicalFst * read (const std::string &filename, const Options &o, bool isMatcherFst, f32 scale, AbstractGrammarFst *g) const
void convert (OpenFst::VectorFst *base, f32 scale, AbstractLexicalFst *result, AbstractGrammarFst *g) const
Static Private Member Functions
template<template< class > class N>
static AbstractLexicalFst * createFst (AccumulatorType t)
Internal helper function for create(options).
Static Private Attributes
static const Core::ParameterChoice paramAccumulatorType_
static const Core::ParameterChoice paramLookAheadType_
static const Core::Choice choiceAccumulatorType_
static const Core::Choice choiceLookAheadType_
static const Core::ParameterBool paramMatcherFst_
static const Core::ParameterFloat paramScale_
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Loads and creates (expanded) lexicon transducers (C o L)
Definition at line 38 of file LexiconFst.hh.
Member Function Documentation
AbstractLexicalFst * LexicalFstFactory::create (const Options & options) static
Factory function to create LexicalFst objects.
Definition at line 144 of file LexiconFst.cc.
References defect.
Referenced by load().
template<template< class > class N> AbstractLexicalFst * LexicalFstFactory::createFst (AccumulatorType t) static private
Internal helper function for create(options).
Selects accumulator
Definition at line 171 of file LexiconFst.cc.
References defect.
AbstractLexicalFst * LexicalFstFactory::load (const std::string & filename, AbstractGrammarFst::GrammarType gType, AbstractGrammarFst * g) const
creates LexicalFst from the given filename using parameter values.
relabels g if necessary.
Definition at line 76 of file LexiconFst.cc.
AbstractLexicalFst * LexicalFstFactory::load (const std::string & filename, const Options & o, AbstractGrammarFst * g) const
creates LexicalFst from the given filename using parameter values, with default values from the given options.
relabels g if necessary.
Definition at line 82 of file LexiconFst.cc.
References create(), Core::Component::criticalError(), ensure, Core::isAlmostEqual(), Core::Component::log(), and verify.
The documentation for this class was generated from the following files:
LexiconFst.hh
LexiconFst.cc