Sprint: Core::XmlRegularElement Class Reference
Core::XmlRegularElement Class Reference
XML element declaration for the regular content model.
#include <XmlParser.hh>
Classes
struct Transition
Public Types
typedef int State
Public Types inherited from Core::XmlElement
typedef XmlElement * pointer
Public Types inherited from Core::XmlContext
typedef XmlContext Self
typedef void(Self::* StartHandler) (const XmlAttributes atts)
typedef void(Self::* EndHandler) ()
typedef void(Self::* CharactersHandler) (const char *ch, int len)
Public Member Functions
XmlRegularElement (const char *_name, XmlContext *_context)
virtual void start (const XmlAttributes atts)
Handle start of the current XML element.
virtual void end ()
Handle end of the current XML element.
virtual void characters (const char *ch, int len)
Handle charcter data in the current XML element.
virtual XmlElement * element (const char *name)
Determine the state to be entered for a nested XML element.
void addTransition (State from, State to, XmlElement *child)
Add a transition to the automaton.
void addFinalState (State state)
Mark state as final.
void draw (std::ostream &) const
Write automaton in Graphviz Dot format.
Public Member Functions inherited from Core::XmlParentElement
XmlParentElement (const char *_name, XmlContext *_context)
void flattenUnknownElements ()
void ignoreUnknownElements ()
Public Member Functions inherited from Core::XmlElement
XmlElement (const char *_name, XmlContext *_context)
const char * name () const
XmlContext * context () const
virtual XmlSchemaParser * parser ()
virtual bool matches (const char *_name) const
Static Public Attributes
static const State initial = 0
static const State final = -1
Static Public Attributes inherited from Core::XmlElement
static const char * wildcard = " * "
Private Types
typedef std::vector< Transition > TransitionList
Private Attributes
State state_
TransitionList transitions_
Additional Inherited Members
Static Public Member Functions inherited from Core::XmlContext
template<class T >
static StartHandler startHandler (void(T::*h)(const XmlAttributes atts))
template<class T >
static EndHandler endHandler (void(T::*h)())
template<class T >
static CharactersHandler charactersHandler (void(T::*h)(const char *ch, int len))
Protected Member Functions inherited from Core::XmlParentElement
virtual XmlElement * unexpectedElement ()
Protected Member Functions inherited from Core::XmlElement
XmlElement * collect (XmlElement *child)
Collects child elements.
Protected Attributes inherited from Core::XmlParentElement
XmlElement * unexpectedElement_
Detailed Description
XML element declaration for the regular content model.
XML elements following the regular content model have child elements according to a regular language. (Character data is not allowed.) In the DTD this language is specified by a regular expression. XmlRegularElement does (currently) not provide regular expression parsing. Instead the language must be specified as a deterministic, epsilon-free finite state automaton. The construction of this automaton is left to the user. States are identified with integers. The initial state is initial, any state may be marked as final with addFinalState(). Transitions can be defined using addTransition(). Remember that the automaton must be deterministic, since this is not checked for and can lead to unexpected results!
Warning
An XmlRegularElement cannot be an (indirect) child of itself.
Definition at line 548 of file XmlParser.hh.
Member Function Documentation
void XmlRegularElement::addFinalState (State state)
Mark state as final.
Definition at line 716 of file XmlParser.cc.
Referenced by Flf::writeConfusionNetworkAsText(), and Flf::writePosteriorCnAsText().
void XmlRegularElement::addTransition (State from, State to, XmlElement * child)
Add a transition to the automaton.
Definition at line 707 of file XmlParser.cc.
References require.
Referenced by Flf::writeConfusionNetworkAsText(), and Flf::writePosteriorCnAsText().
void XmlRegularElement::characters (const char * ch, int len) virtual
Handle charcter data in the current XML element.
Parameters
parser The XmlSchemaParser delegating the request.
Implements Core::XmlElement.
Reimplemented in Cart::XmlTrainingPlanBuilderElement, Cart::XmlExampleListMergerElement, Cart::XmlExampleListBuilderElement, Cart::XmlPropertiesBuilderElement, Cart::XmlDecisionTreeBuilderElement, and Cart::XmlPropertiesDefinitionBuilderElement.
Definition at line 741 of file XmlParser.cc.
References Core::Component::error().
void XmlRegularElement::draw (std::ostream & os) const
Write automaton in Graphviz Dot format.
(for debugging purposes mainly.)
Definition at line 770 of file XmlParser.cc.
XmlElement * XmlRegularElement::element (const char * name) virtual
Determine the state to be entered for a nested XML element.
Parameters
name of the XML element encountered
Returns
XmlElement to handle the encountered element, or 0 if the element should not be allowed.
Parameters
parser The XmlSchemaParser delegating the request.
Implements Core::XmlElement.
Definition at line 729 of file XmlParser.cc.
References Core::XmlParser::warnAboutUnexpectedElement().
void XmlRegularElement::end () virtual
Handle end of the current XML element.
end() is called when end tag of the current element is found.
Parameters
parser The XmlSchemaParser delegating the request.
Reimplemented from Core::XmlElement.
Reimplemented in Cart::XmlTrainingPlanBuilderElement, Cart::XmlExampleListMergerElement, Cart::XmlExampleListBuilderElement, Core::XmlRegularElementRelay, Cart::XmlPropertiesBuilderElement, Cart::XmlDecisionTreeBuilderElement, and Cart::XmlPropertiesDefinitionBuilderElement.
Definition at line 749 of file XmlParser.cc.
References Core::Component::error().
void XmlRegularElement::start (const XmlAttributes atts) virtual
Handle start of the current XML element.
start() is called when the current state is entered.
Parameters
atts attributes of the XML start tag which caused the parser to enter this state. The name of the element will generally be implied by the fact that THIS state is entered.
Reimplemented from Core::XmlElement.
Reimplemented in Cart::XmlTrainingPlanBuilderElement, Cart::XmlExampleListMergerElement, Cart::XmlExampleListBuilderElement, Core::XmlRegularElementRelay, Cart::XmlPropertiesBuilderElement, Cart::XmlDecisionTreeBuilderElement, and Cart::XmlPropertiesDefinitionBuilderElement.
Definition at line 724 of file XmlParser.cc.
References require.
The documentation for this class was generated from the following files:
XmlParser.hh
XmlParser.cc