Sprint: Math::Module_ Class Reference
Math::Module_ Class Reference
Public Member Functions
Core::FormatSet & formats ()
Set of file format class.
EigenvalueProblem * createEigenvalueProblem (const Core::Configuration &) const
Creates object for solving eigenvalue problem with the given configuration.
GeneralizedEigenvalueProblem * createGeneralizedEigenvalueProblem (const Core::Configuration &) const
Creates object for solving generalized eigenvalue problem with the given configuration.
Private Attributes
Core::FormatSet * formats_
Detailed Description
Definition at line 26 of file Math/Module.hh.
Member Function Documentation
EigenvalueProblem * Module_::createEigenvalueProblem (const Core::Configuration & configuration) const
Creates object for solving eigenvalue problem with the given configuration.
Definition at line 53 of file Math/Module.cc.
References Core::Component::error(), and Core::Application::us().
GeneralizedEigenvalueProblem * Module_::createGeneralizedEigenvalueProblem (const Core::Configuration & configuration) const
Creates object for solving generalized eigenvalue problem with the given configuration.
Definition at line 65 of file Math/Module.cc.
References Core::Component::error(), and Core::Application::us().
Core::FormatSet & Module_::formats ()
Set of file format class.
Definition at line 31 of file Math/Module.cc.
References Core::Application::us().
The documentation for this class was generated from the following files:
Math/Module.hh
Math/Module.cc