Sprint: Mm::FeatureScorer Class Reference
Mm::FeatureScorer Class Reference abstract
Abstract feature scorer interface.
#include <FeatureScorer.hh>
Classes
class ContextScorer
Implement emission independent precalculations for feature vector.
class DummyContextScorer
Public Types
typedef Core::Ref< const ContextScorer > Scorer
Public Member Functions
FeatureScorer (const Core::Configuration &c)
virtual EmissionIndex nMixtures () const =0
virtual void getFeatureDescription (FeatureDescription &description) const =0
virtual void getDependencies (Core::DependencySet &dependencies) const
virtual Scorer getScorer (Core::Ref< const Feature >) const =0
virtual Scorer getScorer (const FeatureVector &) const =0
virtual void reset () const
reset should be overloaded/defined in/for featurescorer related to sign language recognition especially the tracking part
virtual void setSegmentName (const std::string name) const
setSegmentName should be overloaded/defined in classes using embedded flow networks to create unambiguous ids for cache nodes
virtual void finalize () const
finalize should be overloaded/defined in classes using embedded flow networks to sent final end of sequence token if necessary
virtual bool isBuffered () const
Return true if the feature scorer buffers features.
virtual void addFeature (const FeatureVector &f) const
Add a feature to the feature buffer.
virtual void addFeature (Core::Ref< const Feature > f) const
virtual Scorer flush () const
Return a scorer for the current feature without adding a new feature to the buffer.
virtual bool bufferFilled () const
Return true if the feature buffer is full.
virtual bool bufferEmpty () const
Return true if the feature buffer is empty.
virtual u32 bufferSize () const
Return the number of buffered features required to execute getScorer().
virtual bool hasTimeIndexedCache () const
virtual Scorer getTimeIndexedScorer (u32 time) const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Friends
class ContextScorer
class DummyContextScorer
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Abstract feature scorer interface.
Definition at line 28 of file Mm/FeatureScorer.hh.
Member Function Documentation
virtual void Mm::FeatureScorer::addFeature (const FeatureVector & f) const inline virtual
Add a feature to the feature buffer.
Implementation required if isBuffered() == true
Reimplemented in Mm::FeatureScorerScaling, and Mm::BatchFeatureScorerBase.
Definition at line 97 of file Mm/FeatureScorer.hh.
Referenced by Mm::FeatureScorerScaling::addFeature(), Speech::DelayedRecognizer::processFeature(), Speech::OfflineRecognizer::processFeature(), and Speech::SegmentwiseAlignmentGenerator::setSegmentwiseFeatureExtractor().
virtual bool Mm::FeatureScorer::bufferEmpty () const inline virtual
Return true if the feature buffer is empty.
Implementation required if isBuffered() == true
Reimplemented in Nn::BatchFeatureScorer, Mm::FeatureScorerScaling, Mm::BatchFeatureScorerBase, Nn::TrainerFeatureScorer, and Nn::PythonFeatureScorer.
Definition at line 123 of file Mm/FeatureScorer.hh.
Referenced by Speech::OfflineRecognizer::signOn().
virtual bool Mm::FeatureScorer::bufferFilled () const inline virtual
Return true if the feature buffer is full.
Implementation required if isBuffered() == true
Reimplemented in Nn::BatchFeatureScorer, Mm::FeatureScorerScaling, Mm::BatchFeatureScorerBase, Nn::TrainerFeatureScorer, and Nn::PythonFeatureScorer.
Definition at line 115 of file Mm/FeatureScorer.hh.
Referenced by Speech::DelayedRecognizer::processFeature(), Speech::OfflineRecognizer::processFeature(), and Speech::SegmentwiseAlignmentGenerator::setSegmentwiseFeatureExtractor().
virtual u32 Mm::FeatureScorer::bufferSize () const inline virtual
Return the number of buffered features required to execute getScorer().
Implementation required if isBuffered() == true
Reimplemented in Nn::BatchFeatureScorer, Mm::BatchFeatureScorerBase, Mm::FeatureScorerScaling, Nn::TrainerFeatureScorer, and Nn::PythonFeatureScorer.
Definition at line 132 of file Mm/FeatureScorer.hh.
virtual void Mm::FeatureScorer::finalize (void) const inline virtual
finalize should be overloaded/defined in classes using embedded flow networks to sent final end of sequence token if necessary
Reimplemented in Nn::BatchFeatureScorer, Mm::FeatureScorerScaling, Nn::TrainerFeatureScorer, and Nn::PythonFeatureScorer.
Definition at line 84 of file Mm/FeatureScorer.hh.
virtual Scorer Mm::FeatureScorer::flush () const inline virtual
Return a scorer for the current feature without adding a new feature to the buffer.
Should be called until bufferEmpty() == true. Requires bufferEmpty() == false. Implementation required if isBuffered() == true
Reimplemented in Nn::BatchFeatureScorer, Mm::FeatureScorerScaling, Mm::BatchFeatureScorerBase, Nn::TrainerFeatureScorer, and Nn::PythonFeatureScorer.
Definition at line 107 of file Mm/FeatureScorer.hh.
Referenced by Speech::DelayedRecognizer::processFeature(), and Speech::OfflineRecognizer::signOn().
virtual bool Mm::FeatureScorer::isBuffered () const inline virtual
Return true if the feature scorer buffers features.
Reimplemented in Nn::BatchFeatureScorer, Mm::BatchFeatureScorerBase, Mm::FeatureScorerScaling, Nn::TrainerFeatureScorer, and Nn::PythonFeatureScorer.
Definition at line 89 of file Mm/FeatureScorer.hh.
Referenced by Speech::DelayedRecognizer::processFeature(), Speech::OfflineRecognizer::processFeature(), Speech::SegmentwiseAlignmentGenerator::setSegmentwiseFeatureExtractor(), and Speech::OfflineRecognizer::signOn().
virtual void Mm::FeatureScorer::reset () const inline virtual
reset should be overloaded/defined in/for featurescorer related to sign language recognition especially the tracking part
Reimplemented in Nn::BatchFeatureScorer, Mm::FeatureScorerScaling, Mm::BatchFeatureScorerBase, Nn::TrainerFeatureScorer, and Nn::PythonFeatureScorer.
Definition at line 70 of file Mm/FeatureScorer.hh.
Referenced by Speech::SegmentwiseAlignmentGenerator::setSegmentwiseFeatureExtractor().
virtual void Mm::FeatureScorer::setSegmentName (const std::string name) const inline virtual
setSegmentName should be overloaded/defined in classes using embedded flow networks to create unambiguous ids for cache nodes
Reimplemented in Mm::FeatureScorerScaling.
Definition at line 77 of file Mm/FeatureScorer.hh.
The documentation for this class was generated from the following file:
Mm/FeatureScorer.hh