Sprint: Search::Wfst::Builder::BuildLexicon Class Reference
Search::Wfst::Builder::BuildLexicon Class Reference
build a transducer for the lexicon (phoneme to outputType() mapping).
#include <CreateOperations.hh>
Public Member Functions
BuildLexicon (const Core::Configuration &c, Resources &r)
virtual bool consumeInput () const
should input automata be removed
Public Member Functions inherited from Search::Wfst::Builder::DisambiguatorDependentOperation
DisambiguatorDependentOperation (const Core::Configuration &c, Resources &r)
virtual u32 nInputAutomata () const
number of automata required as input
virtual bool addInput (AutomatonRef f)
add input automaton (will be called nInputAutomata() times)
Public Member Functions inherited from Search::Wfst::Builder::Operation
Operation (const Core::Configuration &c, Resources &r)
virtual bool hasOutput () const
operation is expected to produce an output automaton.
AutomatonRef getResult ()
do the actual processing and create an output automaton
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Search::Wfst::Builder::OutputTypeDependent
OutputTypeDependent (const Core::Configuration &c)
Static Public Member Functions
static std::string name ()
Static Public Attributes
static const Core::ParameterBool paramCloseWithSilence
static const char * attrInitialPhoneOffset = "initialPhoneOffset"
static const char * attrWordLabelOffset = "wordLabelOffset"
static const char * attrDisambiguatorOffset = "disambiguatorOffset"
Protected Member Functions
virtual AutomatonRef process ()
do the actual processing
void mapOutputSymbols (OpenFst::VectorFst *l) const
Protected Member Functions inherited from Search::Wfst::Builder::Operation
virtual bool precondition () const
precondition for getResult()
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Member Functions inherited from Search::Wfst::Builder::OutputTypeDependent
OutputType outputType () const
Static Protected Attributes
static const Core::ParameterBool paramCloseLexicon
Static Protected Attributes inherited from Search::Wfst::Builder::DisambiguatorDependentOperation
static const Core::ParameterInt paramDisambiguators
Static Protected Attributes inherited from Search::Wfst::Builder::OutputTypeDependent
static const Core::ParameterChoice paramOutputType
static const Core::Choice choiceOutputType
Additional Inherited Members
Public Types inherited from Search::Wfst::Builder::Operation
typedef Automaton * AutomatonRef
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Types inherited from Search::Wfst::Builder::OutputTypeDependent
enum OutputType { outputLemmaPronunciations, outputLemmas, outputSyntacticTokens }
Protected Attributes inherited from Search::Wfst::Builder::DisambiguatorDependentOperation
s32 nDisambiguators_
Protected Attributes inherited from Search::Wfst::Builder::Operation
Resources & resources_
Core::XmlChannel timerChannel_
Core::Timer timer_
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
build a transducer for the lexicon (phoneme to outputType() mapping).
Definition at line 57 of file CreateOperations.hh.
Member Function Documentation
virtual bool Search::Wfst::Builder::BuildLexicon::consumeInput () const inline virtual
should input automata be removed
Reimplemented from Search::Wfst::Builder::Operation.
Definition at line 67 of file CreateOperations.hh.
References Search::Wfst::Builder::BuildGrammar::process().
Operation::AutomatonRef BuildLexicon::process () protected virtual
do the actual processing
Implements Search::Wfst::Builder::Operation.
Reimplemented in Search::Wfst::Builder::BuildOldLexicon.
Definition at line 179 of file CreateOperations.cc.
References Search::Wfst::LexiconBuilder::build(), Search::Wfst::LexiconBuilder::close(), Bliss::Lexicon::createLemmaPronunciationToLemmaTransducer(), Bliss::Lexicon::createLemmaToSyntacticTokenTransducer(), Core::Component::error(), and Core::Component::log().
The documentation for this class was generated from the following files:
CreateOperations.hh
CreateOperations.cc