Sprint: Signal::CosineTransform Class Reference
Signal::CosineTransform Class Reference
Discrete Cosine Transform with an optional warping of the input 'omega' range.
#include <CosineTransform.hh>
Public Types
enum InputType { NplusOneData, evenAboutNminusHalf }
typedef f32 Value
Public Member Functions
void init (InputType inputType, size_t inputSize, size_t outputSize, bool normalize=false)
void init (InputType inputType, size_t inputSize, size_t outputSize, bool normalize, Math::UnaryAnalyticFunctionRef, bool shouldWarpDifferentialUnit)
void apply (const std::vector< Value > &in, std::vector< Value > &out) const
Calculates cosinus transform of.
size_t inputSize () const
Private Member Functions
void initNplusOneData (size_t inputSize, size_t outputSize, Math::UnaryAnalyticFunctionRef warpingFunction, Math::UnaryAnalyticFunctionRef derivedWarpingFunction)
Input data f assumed to have N+1 elments: F_k = 1/2[f_0 + (-1)^k] + sum_{n=1}^{N-1}(f_n cos(warp(pi*n/N) * k).
void initEvenAboutNminusHalf (size_t inputSize, size_t outputSize, Math::UnaryAnalyticFunctionRef warpingFunction, Math::UnaryAnalyticFunctionRef derivedWarpingFunction)
Input data f of length N is extended by N new elements such that it is even about N + 1/2 and periodic: F_k = sum_{n=0}^{N-1}(f_n cos(warp(pi*(n+1/2)/N) * k).
Private Attributes
Math::Matrix< Value > transformation_
size_t N_
Depends on input type.
bool normalize_
Detailed Description
Discrete Cosine Transform with an optional warping of the input 'omega' range.
Definition at line 26 of file CosineTransform.hh.
Member Function Documentation
void CosineTransform::apply (const std::vector< Value > & in, std::vector< Value > & out) const
Calculates cosinus transform of.
Parameters
in. If normalization is set at initialization, the result (
out) is is divided by N. Remark: Normalization is not included in the transformation matrix, as it neither is in (inverse) FFT.
Definition at line 75 of file CosineTransform.cc.
References Core::Component::error(), Core::Component::respondToDelayedErrors(), and Core::Component::warning().
void CosineTransform::initEvenAboutNminusHalf (size_t inputSize, size_t outputSize, Math::UnaryAnalyticFunctionRef warpingFunction, Math::UnaryAnalyticFunctionRef derivedWarpingFunction) private
Input data f of length N is extended by N new elements such that it is even about N + 1/2 and periodic: F_k = sum_{n=0}^{N-1}(f_n cos(warp(pi*(n+1/2)/N) * k).
Definition at line 61 of file CosineTransform.cc.
void CosineTransform::initNplusOneData (size_t inputSize, size_t outputSize, Math::UnaryAnalyticFunctionRef warpingFunction, Math::UnaryAnalyticFunctionRef derivedWarpingFunction) private
Input data f assumed to have N+1 elments: F_k = 1/2[f_0 + (-1)^k] + sum_{n=1}^{N-1}(f_n cos(warp(pi*n/N) * k).
Definition at line 45 of file CosineTransform.cc.
Member Data Documentation
size_t Signal::CosineTransform::N_ private
Depends on input type.
See also
initNplusOneData and initEvenAboutNminusHalf
Definition at line 36 of file CosineTransform.hh.
The documentation for this class was generated from the following files:
CosineTransform.hh
CosineTransform.cc