Sprint: Search::SearchAlgorithm Class Reference
Search::SearchAlgorithm Class Reference abstract
Classes
class Pruning
struct RecognitionContext
struct ScoreVector
class Traceback
struct TracebackItem
Public Types
typedef Speech::Score Score
typedef Speech::TimeframeIndex TimeframeIndex
typedef Core::Ref< Pruning > PruningRef
Public Member Functions
SearchAlgorithm (const Core::Configuration &)
virtual Speech::ModelCombination::Mode modelCombinationNeeded () const
virtual bool setModelCombination (const Speech::ModelCombination &modelCombination)=0
virtual void setGrammar (Fsa::ConstAutomatonRef)=0
virtual void init ()
virtual void restart ()=0
virtual void setSegment (Bliss::SpeechSegment const *segment)
virtual void feed (const Mm::FeatureScorer::Scorer &)=0
virtual void getPartialSentence (Traceback &result)
Should return the longest fixed prefix of the final best sentence which has been been recognized since the last call to getPartialSentence.
virtual void getCurrentBestSentencePartial (Traceback &result) const
Should return the part of the current best sentence which has not yet been returned by getPartialSentence().
virtual void getCurrentBestSentence (Traceback &result) const =0
Should return the whole currently best sentence.
virtual Core::Ref< const LatticeAdaptor > getCurrentWordLattice () const =0
virtual Core::Ref< const LatticeAdaptor > getPartialWordLattice ()
virtual void resetStatistics ()=0
virtual void logStatistics () const =0
virtual void setAllowHmmSkips (bool allow=true)
Allow HMM skips during decoding ? By default, HMM skips are allowed.
virtual u32 lookAheadLength ()
Length of acoustic look-ahead.
virtual void setLookAhead (const std::vector< Mm::FeatureVector > &)
Called before feed() with as many acoustic feature vectors from the future as returned by lookaheadLength().
virtual PruningRef describePruning ()
Returns a descriptor of the current pruning thresholds, which can be used to re-activate the current pruning thresholds using resetPruning.
virtual bool relaxPruning (f32 factor, f32 offset)
Relaxes the pruning. Returns false if relaxing failed, otherwise true.
virtual void resetPruning (PruningRef pruning)
Resets pruning according to the given descriptor.
virtual RecognitionContext setContext (RecognitionContext)
Set LM context to be prepended (prefix) or appended(suffix) to the search hypotheses, and the acoustic phoneme coarticulation to be used for startup.
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Definition at line 35 of file Search/Search.hh.
Member Function Documentation
SearchAlgorithm::PruningRef SearchAlgorithm::describePruning () virtual
Returns a descriptor of the current pruning thresholds, which can be used to re-activate the current pruning thresholds using resetPruning.
Reimplemented in Search::AdvancedTreeSearchManager.
Definition at line 90 of file Search.cc.
Referenced by Search::SearchAlgorithm::Pruning::checkSearchSpace().
virtual void Search::SearchAlgorithm::getCurrentBestSentence (Traceback & result) const pure virtual
Should return the whole currently best sentence.
Implemented in Search::WordConditionedTreeSearch, Search::AdvancedTreeSearchManager, Search::Wfst::ExpandingFsaSearch, and Search::LinearSearch.
void SearchAlgorithm::getCurrentBestSentencePartial (SearchAlgorithm::Traceback & result) const virtual
Should return the part of the current best sentence which has not yet been returned by getPartialSentence().
Optional: Only required for online recognition
Reimplemented in Search::AdvancedTreeSearchManager.
Definition at line 84 of file Search.cc.
void SearchAlgorithm::getPartialSentence (SearchAlgorithm::Traceback & result) virtual
Should return the longest fixed prefix of the final best sentence which has been been recognized since the last call to getPartialSentence.
Optional: Only required for online recognition
Reimplemented in Search::WordConditionedTreeSearch, Search::AdvancedTreeSearchManager, Search::Wfst::ExpandingFsaSearch, and Search::LinearSearch.
Definition at line 87 of file Search.cc.
virtual u32 Search::SearchAlgorithm::lookAheadLength () inline virtual
Length of acoustic look-ahead.
0 means no look-ahead is used.
Reimplemented in Search::AdvancedTreeSearchManager.
Definition at line 121 of file Search/Search.hh.
bool SearchAlgorithm::relaxPruning (f32 factor, f32 offset) virtual
Relaxes the pruning. Returns false if relaxing failed, otherwise true.
Reimplemented in Search::AdvancedTreeSearchManager.
Definition at line 94 of file Search.cc.
Referenced by Search::SearchAlgorithm::Pruning::checkSearchSpace().
void SearchAlgorithm::resetPruning (SearchAlgorithm::PruningRef pruning) virtual
Resets pruning according to the given descriptor.
Reimplemented in Search::AdvancedTreeSearchManager.
Definition at line 98 of file Search.cc.
Referenced by Search::SearchAlgorithm::Pruning::checkSearchSpace().
virtual void Search::SearchAlgorithm::setAllowHmmSkips (bool allow = true) inline virtual
Allow HMM skips during decoding ? By default, HMM skips are allowed.
Reimplemented in Search::AdvancedTreeSearchManager.
Definition at line 115 of file Search/Search.hh.
virtual RecognitionContext Search::SearchAlgorithm::setContext (RecognitionContext) inline virtual
Set LM context to be prepended (prefix) or appended(suffix) to the search hypotheses, and the acoustic phoneme coarticulation to be used for startup.
The context should never be forgotten, but can be reset by calling this function with default arguments. Should return the context which was used previously.
Reimplemented in Search::AdvancedTreeSearchManager.
Definition at line 194 of file Search/Search.hh.
virtual void Search::SearchAlgorithm::setLookAhead (const std::vector< Mm::FeatureVector > &) inline virtual
Called before feed() with as many acoustic feature vectors from the future as returned by lookaheadLength().
At the end of a segment, less than requested, or even zero feature vectors may be given.
Reimplemented in Search::AdvancedTreeSearchManager.
Definition at line 129 of file Search/Search.hh.
The documentation for this class was generated from the following files:
Search/Search.hh
Search.cc