Sprint: Mm::MixtureSetReader Class Reference
Mm::MixtureSetReader Class Reference
Read a mixture set from various file formats.
#include <MixtureSetReader.hh>
Classes
class FormatReader
mixture set readable using stream operators
class MixtureSetEstimatorReader
load mixture set estimator and estimate mixture set
class Reader
Interface for read classes.
class RefReader
mixture set in legacy format
Public Member Functions
MixtureSetReader (const Core::Configuration &c)
template<class MixtureType >
Core::Ref< MixtureType > read (const std::string &filename) const
read mixture set from file filename and try to cast it into type MixtureType
template<>
Core::Ref< LogLinearMixtureSet > read (const std::string &filename) const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Private Types
typedef Core::Ref< AbstractMixtureSet > MixtureSetRef
Private Member Functions
template<class T >
void registerReader (const std::string &id)
register reader class using its name and the associated filename extension
Static Private Attributes
static Core::ComponentFactory< Reader, const std::string > * reader_ = 0
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Read a mixture set from various file formats.
Definition at line 30 of file MixtureSetReader.hh.
Member Function Documentation
template<class MixtureType > Core::Ref< MixtureType > Mm::MixtureSetReader::read (const std::string & filename) const
read mixture set from file filename and try to cast it into type MixtureType
Definition at line 106 of file MixtureSetReader.hh.
References Core::Component::error(), Core::filenameExtension(), and Core::Ref< T >::get().
Referenced by Mm::Module_::readMixtureSet().
template<class T > void Mm::MixtureSetReader::registerReader (const std::string & id) inline private
register reader class using its name and the associated filename extension
Definition at line 100 of file MixtureSetReader.hh.
References Core::Factory< BaseClass, BaseClass *(*)(const Core::Configuration &), Identifier >::registerClass().
The documentation for this class was generated from the following files:
MixtureSetReader.hh
MixtureSetReader.cc