Sprint: Lm::LanguageModelScaling Class Reference
Lm::LanguageModelScaling Class Reference
Scaling of language model scores Wrapper class which multiplies the scores of an arbitrary language model object by predefined scale.
#include <ScaledLanguageModel.hh>
Public Member Functions
LanguageModelScaling (const Core::Configuration &, Core::Ref< LanguageModel >)
virtual void init ()
precondition: the token inventory is set and fixed
virtual void getDependencies (Core::DependencySet &) const
virtual Core::Ref< const LanguageModel > unscaled () const
virtual Fsa::ConstAutomatonRef getFsa () const
Convert language model into an EQUIVALENT acceptor.
virtual History startHistory () const
Language model history for beginning of a sentence.
virtual History extendedHistory (const History &h, Token w) const
Language model history for the next sentence position.
virtual History reducedHistory (const History &h, u32 limit) const
Reduce amount on conditioning information.
virtual std::string formatHistory (const History &h) const
Create string representation of history (mainly for debugging purposes).
virtual Score score (const History &h, Token w) const
Probability of a token to occur with a given history.
virtual Score sentenceEndScore (const History &h) const
Probability for sentence to end in current position.
virtual Score sentenceBeginScore () const
virtual CompiledBatchRequest * compileBatchRequest (const BatchRequest &r, Score scale=1.0) const
Preprocess a batch request.
virtual void getBatch (const History &h, const CompiledBatchRequest *r, std::vector< f32 > &result) const
Get probabilities for a (large) set of syntactic tokens given a history.
virtual Core::Ref< const LanguageModel > lookaheadLanguageModel () const
Returns the LanguageModel that shall be used for lookahead (useful for CombinedLM when we do not want to reinstanciate the model)
virtual Core::Ref< const LanguageModel > recombinationLanguageModel () const
Returns the LanguageModel that shall be used for recombination (useful for CombinedLM when we do not want to reinstanciate the model)
virtual void setSegment (Bliss::SpeechSegment const *s)
For some cheating language models we need to know the correct transcription.
Public Member Functions inherited from Lm::LanguageModel
Token sentenceBeginToken () const
Token sentenceEndToken () const
Token sentenceBoundaryToken () const
Bliss::LexiconRef lexicon () const
const TokenInventory & tokenInventory () const
Fsa::ConstAlphabetRef tokenAlphabet () const
virtual bool scoreCached (const History &, Token w) const
Some LMs might cache scores and thus provide fast access.
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Mc::Component
Component (const Core::Configuration &c)
void updateScales (ScaleUpdate update)
Updates the scale of this and the child objects.
void load ()
Loads map file and updates scales.
void setOwnScale (Scale)
Sets ownScale_ and updates scale_.
void setParentScale (Scale scale)
Updates scale_ with parent's scale (.
Scale scale () const
parent-scale * own-scale
Scale ownScale () const
Scale parentScale () const
void getDependencies (Core::DependencySet &) const
Private Types
typedef ScaledLanguageModel Precursor
Private Attributes
Core::Ref< LanguageModel > languageModel_
Additional Inherited Members
Static Public Attributes inherited from Mc::Component
static const Core::ParameterFloat paramScale
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Lm::ScaledLanguageModel
ScaledLanguageModel (const Core::Configuration &c, const Bliss::LexiconRef l)
Protected Member Functions inherited from Lm::LanguageModel
History history (HistoryHandle hd) const
template<class LM >
const LM::HistoryDescriptor * descriptor (const History &hh) const
void setTokenInventory (const TokenInventory *_tokenInventory)
void setTokenInventoryAndAlphabet (const TokenInventory *_tokenInventory, Fsa::ConstAlphabetRef _tokenAlphabet)
Token getToken (const std::string &word) const
virtual Token getSpecialToken (const std::string &name, bool required=false) const
const Bliss::SyntacticToken * getSpecialSyntacticToken (const std::string &name, bool required) const
Token fallbackToken () const
Find token to use for unknown words.
virtual void createSpecialTokens ()
virtual void load ()
void requireSentenceBoundaryToken ()
Call this function before init(), iff your language model requires a sentence boundary token to be defined in the lexicon.
LanguageModel (const Core::Configuration &c, Bliss::LexiconRef l)
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Member Functions inherited from Mc::Component
virtual void distributeScaleUpdate (const ScaleUpdate &scaleUpdate)
Override this function -to perform updates after scale_ has new value -to distibute.
Protected Attributes inherited from Lm::LanguageModel
HistoryManager * historyManager_
Concrete LanguageModels should set this member in their constructor or load() method.
Core::Dependency dependency_
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Scaling of language model scores Wrapper class which multiplies the scores of an arbitrary language model object by predefined scale.
Definition at line 45 of file ScaledLanguageModel.hh.
Member Function Documentation
virtual CompiledBatchRequest* Lm::LanguageModelScaling::compileBatchRequest (const BatchRequest & request, Score scale = 1.0) const inline virtual
Preprocess a batch request.
Returns
a pre-compiled batch request which can be used with getBatch()
Reimplemented from Lm::LanguageModel.
Definition at line 93 of file ScaledLanguageModel.hh.
References Lm::LanguageModel::compileBatchRequest(), and Mc::Component::scale().
virtual History Lm::LanguageModelScaling::extendedHistory (const History & , Token w) const inline virtual
Language model history for the next sentence position.
This is the given history with given word appended, i.e. w becomes the most recent word. Typically the returned history will reflect the finite memory of the language model: for an m-gram it will only contain the m-1 most recent words. In WFST terminology this is the target state of the outgoin arc labeled w.
Implements Lm::LanguageModel.
Definition at line 72 of file ScaledLanguageModel.hh.
References Lm::LanguageModel::extendedHistory().
virtual std::string Lm::LanguageModelScaling::formatHistory (const History & h) const inline virtual
Create string representation of history (mainly for debugging purposes).
By default this function just delegates to History::format(), but language models may specialize formatHistory() to give more readable information, which would be inaccessible from the HistoryDescriptor alone. If your language model is m-gram like, describe the history chronologically, i.e. most recent word last.
Reimplemented from Lm::LanguageModel.
Definition at line 78 of file ScaledLanguageModel.hh.
References Lm::LanguageModel::formatHistory().
virtual void Lm::LanguageModelScaling::getBatch (const History & h, const CompiledBatchRequest * r, std::vector< f32 > & result) const inline virtual
Get probabilities for a (large) set of syntactic tokens given a history.
This is mainly useful for LanguageModelLookahead.
Warning
Default implementation is inefficient.
Parameters
h history
r pre-compiled batch request created using compileBatchRequest()
result a vector in which results are stored (output parameter)
Reimplemented from Lm::LanguageModel.
Definition at line 96 of file ScaledLanguageModel.hh.
References Lm::LanguageModel::getBatch().
virtual Fsa::ConstAutomatonRef Lm::LanguageModelScaling::getFsa () const inline virtual
Convert language model into an EQUIVALENT acceptor.
Keep in mind that the default method may produce transducers that are very large. Note: This does just convert your language model to a different format, it does NOT implement the language model.
Labels of the resulting acceptor are syntactic token ids.
Reimplemented from Lm::LanguageModel.
Definition at line 65 of file ScaledLanguageModel.hh.
References Lm::LanguageModel::getFsa(), Fsa::multiply(), and Mc::Component::scale().
virtual void Lm::LanguageModelScaling::init () inline virtual
precondition: the token inventory is set and fixed
Initalize language model. This method is called immeditelly after construction. Implement this function in order to perform all non-trivial initialization, like reading the language model from a file.
Reimplemented from Lm::LanguageModel.
Definition at line 55 of file ScaledLanguageModel.hh.
References Lm::LanguageModel::init().
virtual Core::Ref<const LanguageModel> Lm::LanguageModelScaling::lookaheadLanguageModel () const inline virtual
Returns the LanguageModel that shall be used for lookahead (useful for CombinedLM when we do not want to reinstanciate the model)
Returns
the LM that should be used for lookahead, can be nullptr (in that case this LM should be used)
Reimplemented from Lm::LanguageModel.
Definition at line 101 of file ScaledLanguageModel.hh.
References Lm::LanguageModel::lookaheadLanguageModel().
virtual Core::Ref<const LanguageModel> Lm::LanguageModelScaling::recombinationLanguageModel () const inline virtual
Returns the LanguageModel that shall be used for recombination (useful for CombinedLM when we do not want to reinstanciate the model)
Returns
the LM that should be used for recombination, can be nullptr (in that case this LM should be used)
Reimplemented from Lm::LanguageModel.
Definition at line 104 of file ScaledLanguageModel.hh.
References Lm::LanguageModel::recombinationLanguageModel().
virtual History Lm::LanguageModelScaling::reducedHistory (const History & h, u32 limit) const inline virtual
Reduce amount on conditioning information.
In theory extendHistory() adds more and more information to the distory descriptor. Most reasonable language models will drop irrelevant information. E.g. a trigram LM will actually store only two words in its history objects; so the number of distinct histories is size of vocabulary squared. In some situations one wants to limit the number of histories considered, by reducing the amount of conditioning information in the history. E.g. when using a bigram lookahead in a trigram search. This is the purpose of reducedHistory().
Parameters
limit Maximum amount of conditioning information in the returned history. The meaning this parameter is dependent on the language model. In general higher values mean more longer histories. The default implementation returns the given history unchanged.
Reimplemented from Lm::LanguageModel.
Definition at line 75 of file ScaledLanguageModel.hh.
References Lm::LanguageModel::reducedHistory().
virtual Score Lm::LanguageModelScaling::score (const History & , Token w) const inline virtual
Probability of a token to occur with a given history.
Returns
: negative natural(!) logarithm of probability of the token w to occur with history h , i.e. -log(p(w|h))
Note on syntactic classes: The Bliss lexicon can map several lexicon entries (lemmas) to the same syntactic token. Conceptually we can write this case as p(lemma | history) = p(lemma | synt) p(synt | history). However this function returns only p(synt | history). Clients have to add the lemmaScore -log(p(lemma | synt)) when needed.
Note on pronunciation variants: Pronuciation probabilities are not into account.
Implements Lm::LanguageModel.
Definition at line 82 of file ScaledLanguageModel.hh.
References Mc::Component::scale(), and Lm::LanguageModel::score().
virtual Score Lm::LanguageModelScaling::sentenceEndScore (const History & h) const inline virtual
Probability for sentence to end in current position.
In WFST terminology this is the final weight. If the lexicon defines a "sentence-end" special token this must be equivalent to getScore(h, sentenceBoundaryToken()). The default implementation does just this.
Returns
negative natural(!) logarithm of probability of sentence end, i.e. -log(p(EOS|h))
Reimplemented from Lm::LanguageModel.
Definition at line 85 of file ScaledLanguageModel.hh.
References Mc::Component::scale(), and Lm::LanguageModel::sentenceEndScore().
virtual void Lm::LanguageModelScaling::setSegment (Bliss::SpeechSegment const * s) inline virtual
For some cheating language models we need to know the correct transcription.
Language models that are used for real recognition MUST NOT implement this.
Parameters
s the current segment
Reimplemented from Lm::LanguageModel.
Definition at line 107 of file ScaledLanguageModel.hh.
References Lm::LanguageModel::setSegment().
virtual History Lm::LanguageModelScaling::startHistory () const inline virtual
Language model history for beginning of a sentence.
Typically this is the bigram history which contains just the sentence start (or boundary) token. In the terminology of finite-state automata this is the initial state.
Implements Lm::LanguageModel.
Definition at line 69 of file ScaledLanguageModel.hh.
References Lm::LanguageModel::startHistory().
The documentation for this class was generated from the following files:
ScaledLanguageModel.hh
ScaledLanguageModel.cc