Sprint: Am::AllophoneStateAlphabet Class Reference
Am::AllophoneStateAlphabet Class Reference
Public Types
typedef Fsa::LabelId Index
Public Member Functions
AllophoneStateAlphabet (const Core::Configuration &config, ConstAllophoneAlphabetRef allophoneAlphabet, ClassicHmmTopologySetRef hmmTopologies)
bool isSilence (const AllophoneState &alloState) const
AllophoneState allophoneState (Fsa::LabelId) const
AllophoneState allophoneState (const Allophone *allo, s16 state) const
Fsa::LabelId index (const AllophoneState &) const
std::string toString (const AllophoneState &alloState) const
virtual Fsa::LabelId index (const std::string &symbol) const
Given a string representation of a symbol returns the label id.
Fsa::LabelId index (const std::string &symbol, bool create) const
virtual std::string symbol (Fsa::LabelId) const
Returns the string representation of a symbol.
Fsa::LabelId index (const Allophone *allo, s16 state, bool create=true) const
std::pair< Fsa::LabelId, s16 > allophoneIndexAndState (Fsa::LabelId) const
std::pair< AllophoneStateIterator, AllophoneStateIterator > allophoneStates () const
Fsa::LabelId nClasses () const
Fsa::LabelId nDisambiguators () const
Fsa::LabelId disambiguator (Fsa::LabelId d) const
virtual bool isDisambiguator (Fsa::LabelId id) const
Determine wether a symbol is a disambiguator (see determinize for more details on the use of disambiguators).
virtual const_iterator begin () const
Returns an iterator pointing to the first symbol.
virtual const_iterator end () const
Returns an iterator pointing behind the last symbol.
virtual void writeXml (Core::XmlWriter &os) const
Write the alphabet to an XmlWriter.
void dump (Core::XmlWriter &xml) const
void dumpPlain (std::ostream &os) const
AllophoneStateAlphabet (Core::Ref< const Bliss::PhonemeInventory >, u32 contextLength=0, u32 nStates=0)
void set (Core::Ref< const Bliss::PhonemeInventory >, u32 contextLength, u32 nStates)
Core::Ref< const Bliss::PhonemeInventory > phonemeInventory () const
Fsa::LabelId nClasses () const
Fsa::LabelId index (const AllophoneState &) const
AllophoneState allophoneState (Fsa::LabelId) const
u32 nDisambiguators () const
Fsa::LabelId disambiguator (u32 d) const
virtual bool isDisambiguator (Fsa::LabelId m) const
Determine wether a symbol is a disambiguator (see determinize for more details on the use of disambiguators).
virtual const_iterator end () const
Returns an iterator pointing behind the last symbol.
virtual Fsa::LabelId next (Fsa::LabelId id) const
Returns the label id of the next symbol in sequence.
virtual std::string symbol (Fsa::LabelId) const
Returns the string representation of a symbol.
virtual void writeXml (Core::XmlWriter &os) const
Write the alphabet to an XmlWriter.
Public Member Functions inherited from Fsa::Alphabet
std::string specialSymbol (LabelId index) const
Retrieve a string representation of a special label id.
LabelId specialIndex (const std::string &symbol) const
Map a string representation of a special symbol to its label id.
virtual AlphabetTag tag (LabelId index) const
return symbol tag
virtual bool write (Core::BinaryOutputStream &o) const
Write the alphabet to BinaryOutputStream.
virtual size_t getMemoryUsed () const
Return the amount of memory used by this object.
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Attributes
static const s16 MaxStateId = 0x000f
static const Fsa::LabelId StateMask = 0x3c000000
Private Member Functions
void calcNClasses ()
Private Attributes
ConstAllophoneAlphabetRef allophoneAlphabet_
HmmTopologySetRef hmmTopologies_
Core::Ref< const Bliss::PhonemeInventory > pi_
u32 contextLength_
u32 nStates_
u32 nClasses_
u32 nDisambiguators_
Friends
class AllophoneStateIterator
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Definition at line 304 of file ClassicStateModel.hh.
Member Function Documentation
AllophoneStateAlphabet::const_iterator AllophoneStateAlphabet::begin () const virtual
Returns an iterator pointing to the first symbol.
Note, that if the alphabet contains a hole in the space of label ids at the beginning the iterator must be winded to the first existing symbol.
Returns
a const iterator pointing to the first symbol or end()
Reimplemented from Fsa::Alphabet.
Definition at line 777 of file ClassicStateModel.cc.
virtual const_iterator Am::AllophoneStateAlphabet::end () const inline virtual
Returns an iterator pointing behind the last symbol.
This usually does not need to be overloaded except for the case you need a different internal representation of the end iterator. Currently, InvalidLabelId is being used as end iterator.
Returns
a const iterator pointing to the first symbol or end()
Reimplemented from Fsa::Alphabet.
Definition at line 137 of file StateModel.hh.
AllophoneStateAlphabet::const_iterator AllophoneStateAlphabet::end () const virtual
Returns an iterator pointing behind the last symbol.
This usually does not need to be overloaded except for the case you need a different internal representation of the end iterator. Currently, InvalidLabelId is being used as end iterator.
Returns
a const iterator pointing to the first symbol or end()
Reimplemented from Fsa::Alphabet.
Definition at line 781 of file ClassicStateModel.cc.
virtual Fsa::LabelId Am::AllophoneStateAlphabet::index (const std::string & symbol) const inline virtual
Given a string representation of a symbol returns the label id.
Parameters
symbol the string representation of a symbol
Returns
the label id of the symbol or InvalidLabelId if the string represents no valid symbol
Reimplemented from Fsa::Alphabet.
Definition at line 331 of file ClassicStateModel.hh.
virtual bool Am::AllophoneStateAlphabet::isDisambiguator (Fsa::LabelId index) const inline virtual
Determine wether a symbol is a disambiguator (see determinize for more details on the use of disambiguators).
Parameters
index the symbol's label id
Returns
true if the symbol is a disambiguator.
Reimplemented from Fsa::Alphabet.
Definition at line 133 of file StateModel.hh.
virtual bool Am::AllophoneStateAlphabet::isDisambiguator (Fsa::LabelId index) const inline virtual
Determine wether a symbol is a disambiguator (see determinize for more details on the use of disambiguators).
Parameters
index the symbol's label id
Returns
true if the symbol is a disambiguator.
Reimplemented from Fsa::Alphabet.
Definition at line 354 of file ClassicStateModel.hh.
virtual Fsa::LabelId Am::AllophoneStateAlphabet::next (Fsa::LabelId id) const inline virtual
Returns the label id of the next symbol in sequence.
Users can savely assume that holes in the space of label ids are being skipped automatically.
Parameters
id the current symbol
Returns
the label id of the next symbol
Reimplemented from Fsa::Alphabet.
Definition at line 140 of file StateModel.hh.
References Am::EmissionAlphabet::symbol(), and Am::EmissionAlphabet::writeXml().
virtual std::string Am::AllophoneStateAlphabet::symbol (Fsa::LabelId index) const virtual
Returns the string representation of a symbol.
Parameters
index the symbol's label id
Returns
the string representation of the symbol or an empty string if there is no symbol with that label id
Implements Fsa::Alphabet.
std::string AllophoneStateAlphabet::symbol (Fsa::LabelId index) const virtual
Returns the string representation of a symbol.
Parameters
index the symbol's label id
Returns
the string representation of the symbol or an empty string if there is no symbol with that label id
Implements Fsa::Alphabet.
Definition at line 758 of file ClassicStateModel.cc.
References Core::form(), and Core::ref().
virtual void Am::AllophoneStateAlphabet::writeXml (Core::XmlWriter & o) const virtual
Write the alphabet to an XmlWriter.
Parameters
o the XmlWriter
Returns
true if the operation was successfull for all symbols, false otherwise
Reimplemented from Fsa::Alphabet.
void AllophoneStateAlphabet::writeXml (Core::XmlWriter & o) const virtual
Write the alphabet to an XmlWriter.
Parameters
o the XmlWriter
Returns
true if the operation was successfull for all symbols, false otherwise
Reimplemented from Fsa::Alphabet.
Definition at line 785 of file ClassicStateModel.cc.
References Core::form(), and verify.
The documentation for this class was generated from the following files:
ClassicStateModel.hh
StateModel.hh
ClassicStateModel.cc