Sprint: Core::XmlMixedElement Class Reference
Core::XmlMixedElement Class Reference
XML element declaration for the mixed content model.
#include <XmlParser.hh>
Public Member Functions
virtual XmlElement * element (const char *name)
Determine the state to be entered for a nested XML element.
XmlMixedElement (const char *_name, XmlContext *_context)
XmlMixedElement (const char *_name, XmlContext *_context, XmlElement *child,...)
Constructor.
void addChild (XmlElement *decl)
Add a new child element.
Public Member Functions inherited from Core::XmlParentElement
XmlParentElement (const char *_name, XmlContext *_context)
void flattenUnknownElements ()
void ignoreUnknownElements ()
Public Member Functions inherited from Core::XmlElement
XmlElement (const char *_name, XmlContext *_context)
const char * name () const
XmlContext * context () const
virtual XmlSchemaParser * parser ()
virtual bool matches (const char *_name) const
virtual void start (const XmlAttributes atts)
Handle start of the current XML element.
virtual void end ()
Handle end of the current XML element.
virtual void characters (const char *ch, int len)=0
Handle charcter data in the current XML element.
Protected Member Functions
void vAddChildren (va_list)
Protected Member Functions inherited from Core::XmlParentElement
virtual XmlElement * unexpectedElement ()
Protected Member Functions inherited from Core::XmlElement
XmlElement * collect (XmlElement *child)
Collects child elements.
Protected Attributes
std::vector< XmlElement * > children_
Protected Attributes inherited from Core::XmlParentElement
XmlElement * unexpectedElement_
Additional Inherited Members
Public Types inherited from Core::XmlElement
typedef XmlElement * pointer
Public Types inherited from Core::XmlContext
typedef XmlContext Self
typedef void(Self::* StartHandler) (const XmlAttributes atts)
typedef void(Self::* EndHandler) ()
typedef void(Self::* CharactersHandler) (const char *ch, int len)
Static Public Member Functions inherited from Core::XmlContext
template<class T >
static StartHandler startHandler (void(T::*h)(const XmlAttributes atts))
template<class T >
static EndHandler endHandler (void(T::*h)())
template<class T >
static CharactersHandler charactersHandler (void(T::*h)(const char *ch, int len))
Static Public Attributes inherited from Core::XmlElement
static const char * wildcard = " * "
Detailed Description
XML element declaration for the mixed content model.
XmlMixedElement allows character data interspersed with the elements declared in children_. Neither order nor number of elements and character data is restricted.
Definition at line 478 of file XmlParser.hh.
Constructor & Destructor Documentation
XmlMixedElement::XmlMixedElement (const char * _name, XmlContext * _context, XmlElement * child, ...)
Constructor.
Parameters
... List of const XmlElement* element declarations which may occur within the current element. The list must be terminated with XML_NO_MORE_CHILDREN and each item must be explicitly type-marked with XML_CHILD.
Definition at line 623 of file XmlParser.cc.
References addChild().
Member Function Documentation
void XmlMixedElement::addChild (XmlElement * decl)
Add a new child element.
Parameters
decl XML element declaration to be used when an XML element of the same name occurs within the current element.
Definition at line 638 of file XmlParser.cc.
References require.
Referenced by element(), and XmlMixedElement().
XmlElement * XmlMixedElement::element (const char * name) virtual
Determine the state to be entered for a nested XML element.
Parameters
name of the XML element encountered
Returns
XmlElement to handle the encountered element, or 0 if the element should not be allowed.
Parameters
parser The XmlSchemaParser delegating the request.
Implements Core::XmlElement.
Definition at line 649 of file XmlParser.cc.
References addChild(), and Core::XmlParser::warnAboutUnexpectedElement().
The documentation for this class was generated from the following files:
XmlParser.hh
XmlParser.cc