Sprint: Speech::HistogramEstimator Class Reference
Speech::HistogramEstimator Class Reference
HistogramEstimator.
#include <HistogramEstimator.hh>
Public Types
typedef f32 Value
Public Member Functions
HistogramEstimator (const Core::Configuration &)
virtual void signOn (CorpusVisitor &)
Override this function to sign on to services of the corpus visitor.
void clear ()
Public Member Functions inherited from Speech::FeatureVectorExtractor
FeatureVectorExtractor (const Core::Configuration &c)
Public Member Functions inherited from Speech::FeatureExtractor
FeatureExtractor (const Core::Configuration &c, bool loadFromFile=true)
virtual void processSegment (Bliss::Segment *segment)
Public Member Functions inherited from Speech::DataExtractor
DataExtractor (const Core::Configuration &c, bool loadFromFile=true)
virtual void enterCorpus (Bliss::Corpus *)
virtual void leaveCorpus (Bliss::Corpus *)
virtual void enterRecording (Bliss::Recording *)
virtual void enterSegment (Bliss::Segment *)
virtual void leaveSegment (Bliss::Segment *)
Public Member Functions inherited from Speech::CorpusProcessor
CorpusProcessor (const Core::Configuration &c)
virtual void leaveRecording (Bliss::Recording *recoding)
virtual void enterSpeechSegment (Bliss::SpeechSegment *)
virtual void processSpeechSegment (Bliss::SpeechSegment *segment)
virtual void leaveSpeechSegment (Bliss::SpeechSegment *)
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Attributes
static const Core::ParameterFloat paramBucketSize
Protected Member Functions
virtual void setFeatureVectorDescription (const Mm::FeatureDescription::Stream &)
Override this function to achieve the attributes of the feature vector.
virtual void processFeatureVector (Core::Ref< const Feature::Vector > f)
Override this function to achieve the feature vectors extracted form data source one-by-one.
Protected Member Functions inherited from Speech::FeatureVectorExtractor
virtual void setFeatureDescription (const Mm::FeatureDescription &d)
Override this function to achieve the attributes of the feature streams.
virtual void processFeature (Core::Ref< const Feature > f)
Override this function to achieve the features extracted form data source one-by-one.
Protected Member Functions inherited from Speech::DataExtractor
void setDataSource (Core::Ref< DataSource > s)
Core::Ref< DataSource > dataSource () const
Protected Member Functions inherited from Speech::CorpusProcessor
void reportRealTime (Flow::Time)
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Private Types
typedef FeatureVectorExtractor Precursor
typedef Signal::HistogramVector< Value > HistogramVector
typedef Core::ObjectCache< Core::MruObjectCacheList< std::string, HistogramVector, Core::StringHash, Core::StringEquality > > HistogramVectorCache
Private Member Functions
Signal::HistogramVector< Value > * histogramVector (size_t featureDimension)
Private Attributes
Core::Ref< Bliss::CorpusKey > corpusKey_
HistogramVector * currentHistogramVector_
size_t featureDimension_
Value bucketSize_
HistogramVectorCache histogramVectorCache_
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Attributes inherited from Speech::CorpusProcessor
Core::XmlChannel channelTimer_
Core::Timer timer_
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
HistogramEstimator.
Definition at line 25 of file HistogramEstimator.hh.
Member Function Documentation
virtual void Speech::HistogramEstimator::processFeatureVector (Core::Ref< const Feature::Vector >) inline protected virtual
Override this function to achieve the feature vectors extracted form data source one-by-one.
Reimplemented from Speech::FeatureVectorExtractor.
Definition at line 51 of file HistogramEstimator.hh.
References Core::ObjectCache< List >::clear(), and signOn().
void HistogramEstimator::setFeatureVectorDescription (const Mm::FeatureDescription::Stream &) protected virtual
Override this function to achieve the attributes of the feature vector.
This function is called once before the first feature vector is processed.
Reimplemented from Speech::FeatureVectorExtractor.
Definition at line 36 of file HistogramEstimator.cc.
References defect, Core::Description::Stream::getValue(), and verify.
void HistogramEstimator::signOn (CorpusVisitor & corpusVisitor) virtual
Override this function to sign on to services of the corpus visitor.
Note: call the signOn function of your predecessor.
Reimplemented from Speech::DataExtractor.
Definition at line 31 of file HistogramEstimator.cc.
Referenced by processFeatureVector().
The documentation for this class was generated from the following files:
HistogramEstimator.hh
HistogramEstimator.cc