Sprint: Lm::TFRecurrentLanguageModel Class Reference
Lm::TFRecurrentLanguageModel Class Reference
Classes
struct TimeStatistics
Public Types
typedef AbstractNNLanguageModel Precursor
typedef moodycamel::BlockingReaderWriterQueue< History const * > HistoryQueue
Public Types inherited from Lm::AbstractNNLanguageModel
typedef LanguageModel Precursor
Public Member Functions
TFRecurrentLanguageModel (Core::Configuration const &c, Bliss::LexiconRef l)
virtual History startHistory () const
Language model history for beginning of a sentence.
virtual History extendedHistory (History const &hist, Token w) const
Language model history for the next sentence position.
virtual History extendedHistory (History const &hist, Bliss::Token::Id w) const
virtual History reducedHistory (History const &hist, u32 limit) const
Reduce amount on conditioning information.
virtual Score score (History const &hist, Token w) const
Probability of a token to occur with a given history.
virtual bool scoreCached (History const &hist, Token w) const
Some LMs might cache scores and thus provide fast access.
virtual void startFrame (Search::TimeframeIndex time) const
virtual void setInfo (History const &hist, SearchSpaceInformation const &info) const
Public Member Functions inherited from Lm::AbstractNNLanguageModel
AbstractNNLanguageModel (Core::Configuration const &c, Bliss::LexiconRef l)
Public Member Functions inherited from Lm::LanguageModel
Token sentenceBeginToken () const
virtual Lm::Score sentenceBeginScore () const
Token sentenceEndToken () const
Token sentenceBoundaryToken () const
virtual void init ()
precondition: the token inventory is set and fixed
virtual void getDependencies (Core::DependencySet &dependencies) const
Bliss::LexiconRef lexicon () const
const TokenInventory & tokenInventory () const
Fsa::ConstAlphabetRef tokenAlphabet () const
virtual Fsa::ConstAutomatonRef getFsa () const
Convert language model into an EQUIVALENT acceptor.
virtual std::string formatHistory (const History &h) const
Create string representation of history (mainly for debugging purposes).
virtual Score sentenceEndScore (const History &) const
Probability for sentence to end in current position.
virtual CompiledBatchRequest * compileBatchRequest (const BatchRequest &, Score scale=1.0) const
Preprocess a batch request.
virtual void getBatch (const History &h, const CompiledBatchRequest *r, std::vector< f32 > &result) const
Get probabilities for a (large) set of syntactic tokens given a history.
virtual Core::Ref< const LanguageModel > lookaheadLanguageModel () const
Returns the LanguageModel that shall be used for lookahead (useful for CombinedLM when we do not want to reinstanciate the model)
virtual Core::Ref< const LanguageModel > recombinationLanguageModel () const
Returns the LanguageModel that shall be used for recombination (useful for CombinedLM when we do not want to reinstanciate the model)
virtual void setSegment (Bliss::SpeechSegment const *s)
For some cheating language models we need to know the correct transcription.
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Attributes
static const Core::ParameterBool paramTransformOuputLog
static const Core::ParameterBool paramTransformOuputNegate
static const Core::ParameterInt paramMinBatchSize
static const Core::ParameterInt paramOptBatchSize
static const Core::ParameterInt paramMaxBatchSize
static const Core::ParameterInt paramHistoryPruningThreshold
static const Core::ParameterInt paramPrunedHistoryLength
static const Core::ParameterFloat paramBatchPruningThreshold
static const Core::ParameterBool paramAllowReducedHistory
static const Core::ParameterBool paramDumpInputs
static const Core::ParameterString paramDumpInputsPrefix
static const Core::ParameterBool paramDumpScores
static const Core::ParameterString paramDumpScoresPrefix
static const Core::ParameterBool paramLogMemory
static const Core::ParameterBool paramFreeMemory
static const Core::ParameterInt paramFreeMemoryDelay
static const Core::ParameterBool paramAsync
static const Core::ParameterBool paramSingleStepOnly
static const Core::ParameterBool paramVerbose
Static Public Attributes inherited from Lm::AbstractNNLanguageModel
static Core::ParameterBool paramCollectStatistics
static Core::ParameterString paramVocabularyFile
static Core::ParameterString paramVocabUnknownWord
Protected Member Functions
virtual void load ()
Protected Member Functions inherited from Lm::AbstractNNLanguageModel
void loadVocabulary ()
void useOutput (NNCacheWithStats const &cache, size_t idx) const
void onRelease (HistoryHandle handle)
void logStatistics () const
Protected Member Functions inherited from Lm::LanguageModel
History history (HistoryHandle hd) const
template<class LM >
const LM::HistoryDescriptor * descriptor (const History &hh) const
void setTokenInventory (const TokenInventory *_tokenInventory)
void setTokenInventoryAndAlphabet (const TokenInventory *_tokenInventory, Fsa::ConstAlphabetRef _tokenAlphabet)
Token getToken (const std::string &word) const
virtual Token getSpecialToken (const std::string &name, bool required=false) const
const Bliss::SyntacticToken * getSpecialSyntacticToken (const std::string &name, bool required) const
Token fallbackToken () const
Find token to use for unknown words.
virtual void createSpecialTokens ()
void requireSentenceBoundaryToken ()
Call this function before init(), iff your language model requires a sentence boundary token to be defined in the lexicon.
LanguageModel (const Core::Configuration &c, Bliss::LexiconRef l)
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Private Member Functions
History extendHistoryWithOutputIdx (History const &hist, size_t w) const
void background_forward () const
template<bool async>
void forward (Lm::History const *hist) const
Private Attributes
bool transform_output_log_
bool transform_output_negate_
std::function< Score(Score)> output_transform_function_
size_t min_batch_size_
size_t opt_batch_size_
size_t max_batch_size_
size_t history_pruning_threshold_
size_t pruned_history_length_
Score batch_pruning_threshold_
bool allow_reduced_history_
bool dump_inputs_
std::string dump_inputs_prefix_
bool dump_scores_
std::string dump_scores_prefix_
bool log_memory_
bool free_memory_
Search::TimeframeIndex free_memory_delay_
bool async_
bool single_step_only_
bool verbose_
Tensorflow::Session session_
std::unique_ptr< Tensorflow::GraphLoader > loader_
std::unique_ptr< Tensorflow::Graph > graph_
Tensorflow::TensorInputMap tensor_input_map_
Tensorflow::TensorOutputMap tensor_output_map_
CompressedVectorFactoryPtr< float > state_comp_vec_factory_
CompressedVectorFactoryPtr< float > nn_output_comp_vec_factory_
std::vector< Tensorflow::Variable > state_variables_
std::unique_ptr< StateManager > state_manager_
std::unique_ptr< SoftmaxAdapter > softmax_adapter_
std::vector< std::string > initializer_tensor_names_
std::vector< std::string > output_tensor_names_
std::vector< std::string > read_vars_tensor_names_
History empty_history_
Core::XmlChannel statistics_
Search::TimeframeIndex current_time_
std::vector< double > run_time_
std::vector< size_t > run_count_
double total_wait_time_
double total_start_frame_time_
double total_expand_hist_time_
TimeStatistics fwd_statistics_
size_t dump_inputs_counter_
std::thread background_forwarder_thread_
bool should_stop_
std::atomic< History const * > to_fwd_
std::promise< History const * > to_fwd_finished_
std::vector< History const * > pending_
HistoryQueue fwd_queue_
HistoryQueue finished_queue_
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Attributes inherited from Lm::AbstractNNLanguageModel
bool collect_statistics_
std::string vocab_file_
std::string unknown_word_
Bliss::LexiconRef lexicon_
size_t num_outputs_
std::vector< size_t > lexicon_mapping_
std::vector< u32 > usage_histogram_
Protected Attributes inherited from Lm::LanguageModel
HistoryManager * historyManager_
Concrete LanguageModels should set this member in their constructor or load() method.
Core::Dependency dependency_
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Definition at line 36 of file TFRecurrentLanguageModel.hh.
Member Function Documentation
History Lm::TFRecurrentLanguageModel::extendedHistory (History const & , Token w) const virtual
Language model history for the next sentence position.
This is the given history with given word appended, i.e. w becomes the most recent word. Typically the returned history will reflect the finite memory of the language model: for an m-gram it will only contain the m-1 most recent words. In WFST terminology this is the target state of the outgoin arc labeled w.
Implements Lm::LanguageModel.
Definition at line 437 of file TFRecurrentLanguageModel.cc.
References Bliss::Token::id().
History Lm::TFRecurrentLanguageModel::reducedHistory (History const & h, u32 limit) const virtual
Reduce amount on conditioning information.
In theory extendHistory() adds more and more information to the distory descriptor. Most reasonable language models will drop irrelevant information. E.g. a trigram LM will actually store only two words in its history objects; so the number of distinct histories is size of vocabulary squared. In some situations one wants to limit the number of histories considered, by reducing the amount of conditioning information in the history. E.g. when using a bigram lookahead in a trigram search. This is the purpose of reducedHistory().
Parameters
limit Maximum amount of conditioning information in the returned history. The meaning this parameter is dependent on the language model. In general higher values mean more longer histories. The default implementation returns the given history unchanged.
Reimplemented from Lm::LanguageModel.
Definition at line 445 of file TFRecurrentLanguageModel.cc.
Score Lm::TFRecurrentLanguageModel::score (History const & , Token w) const virtual
Probability of a token to occur with a given history.
Returns
: negative natural(!) logarithm of probability of the token w to occur with history h , i.e. -log(p(w|h))
Note on syntactic classes: The Bliss lexicon can map several lexicon entries (lemmas) to the same syntactic token. Conceptually we can write this case as p(lemma | history) = p(lemma | synt) p(synt | history). However this function returns only p(synt | history). Clients have to add the lemmaScore -log(p(lemma | synt)) when needed.
Note on pronunciation variants: Pronuciation probabilities are not into account.
Implements Lm::LanguageModel.
Definition at line 457 of file TFRecurrentLanguageModel.cc.
References Bliss::Token::id(), and require.
bool Lm::TFRecurrentLanguageModel::scoreCached (History const & , Token w) const virtual
Some LMs might cache scores and thus provide fast access.
If we use the skip heuristic in the combined LM we do not have to skip if the score is computed anyway.
Reimplemented from Lm::LanguageModel.
Definition at line 494 of file TFRecurrentLanguageModel.cc.
References Math::isinf(), and require.
History Lm::TFRecurrentLanguageModel::startHistory () const virtual
Language model history for beginning of a sentence.
Typically this is the bigram history which contains just the sentence start (or boundary) token. In the terminology of finite-state automata this is the initial state.
Implements Lm::LanguageModel.
Definition at line 427 of file TFRecurrentLanguageModel.cc.
The documentation for this class was generated from the following files:
TFRecurrentLanguageModel.hh
TFRecurrentLanguageModel.cc