Sprint: Am::AllophoneAlphabet Class Reference
Am::AllophoneAlphabet Class Reference
Classes
struct AllophonePtrEq
struct AllophonePtrHash
Public Types
typedef std::vector< const Allophone * > AllophoneList
Public Member Functions
AllophoneAlphabet (const Core::Configuration &config, ConstPhonologyRef phonology, Bliss::LexiconRef lexicon)
const Allophone * allophone (Fsa::LabelId) const
Fsa::LabelId index (const Allophone *, bool create=true) const
bool hasIndex (const Allophone *) const
const Allophone * allophone (const Allophone &allo) const
Fsa::LabelId index (const Allophone &allo, bool create=true) const
virtual std::string symbol (Fsa::LabelId) const
Returns the string representation of a symbol.
virtual Fsa::LabelId index (const std::string &symbol) const
Given a string representation of a symbol returns the label id.
Allophone fromString (const std::string &s) const
std::string toString (const Allophone &allo) const
bool isSilence (const Allophone &allo) const
const AllophoneList & allophones () const
ConstPhonologyRef phonology () const
Fsa::LabelId nClasses () const
Fsa::LabelId nDisambiguators () const
Fsa::LabelId disambiguator (Fsa::LabelId d) const
virtual bool isDisambiguator (Fsa::LabelId id) const
Determine wether a symbol is a disambiguator (see determinize for more details on the use of disambiguators).
virtual const_iterator begin () const
Returns an iterator pointing to the first symbol.
virtual const_iterator end () const
Returns an iterator pointing behind the last symbol.
virtual void writeXml (Core::XmlWriter &os) const
Write the alphabet to an XmlWriter.
void dump (Core::XmlWriter &xml) const
void dumpPlain (std::ostream &os) const
Public Member Functions inherited from Fsa::Alphabet
std::string specialSymbol (LabelId index) const
Retrieve a string representation of a special label id.
LabelId specialIndex (const std::string &symbol) const
Map a string representation of a special symbol to its label id.
virtual LabelId next (LabelId id) const
Returns the label id of the next symbol in sequence.
virtual AlphabetTag tag (LabelId index) const
return symbol tag
virtual bool write (Core::BinaryOutputStream &o) const
Write the alphabet to BinaryOutputStream.
virtual size_t getMemoryUsed () const
Return the amount of memory used by this object.
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Attributes
static const Fsa::LabelId MaxId = 0x03ffffff
static const Fsa::LabelId DisambiguatorFlag = 0x40000000
static const Fsa::LabelId IdMask = 0x03ffffff
static const Fsa::LabelId DisambiguatorMask = 0x3fffffff
static const Core::ParameterString paramAddFromFile
static const Core::ParameterString paramStoreToFile
static const Core::ParameterBool paramAddFromLexicon
static const Core::ParameterBool paramAddAll
Protected Member Functions
std::pair< AllophoneMap::iterator, bool > insert (const Allophone *allo) const
takes ownership
std::pair< AllophoneMap::iterator, bool > insert (const Allophone &allo) const
std::pair< AllophoneMap::iterator, bool > createAndInsert (const std::vector< bool > &cd, const Bliss::Pronunciation &p, s32 b, s32 c, s32 e, s16 boundary) const
void clear ()
reset
void add (Core::Ref< const Bliss::PhonemeInventory > pi)
Index all allophones.
void add (Bliss::LexiconRef lexicon)
Index allophones in lexicon.
void load (const std::string &filename)
void store (const std::string &filename)
Store list of allophones in alphabet.
void setSilence (Bliss::LexiconRef lexicon)
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Private Types
typedef Fsa::Alphabet Precursor
typedef std::unordered_map< const Allophone *, Fsa::LabelId, AllophonePtrHash, AllophonePtrEq > AllophoneMap
typedef std::unordered_set< Bliss::Phoneme::Id > PhonemeIdSet
Private Attributes
ConstPhonologyRef phonology_
Core::Ref< const Bliss::PhonemeInventory > pi_
bool isCrossWord_
AllophoneMap allophoneMap_
AllophoneList allophones_
PhonemeIdSet silPhonemes_
Fsa::LabelId nDisambiguators_
Friends
class ClassicTransducerBuilder
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Definition at line 87 of file ClassicStateModel.hh.
Member Function Documentation
void AllophoneAlphabet::add (Core::Ref< const Bliss::PhonemeInventory > pi) protected
Index all allophones.
Definition at line 141 of file ClassicStateModel.cc.
References Core::ProgressIndicator::finish(), Core::ProgressIndicator::notify(), and Core::ProgressIndicator::start().
void AllophoneAlphabet::add (Bliss::LexiconRef lexicon) protected
Index allophones in lexicon.
Definition at line 251 of file ClassicStateModel.cc.
References Core::Component::error(), Core::ProgressIndicator::finish(), Bliss::Pronunciation::length(), Core::ProgressIndicator::notify(), require, Core::ProgressIndicator::start(), Core::stripWhitespace(), verify, and Core::Component::warning().
AllophoneAlphabet::const_iterator AllophoneAlphabet::begin () const virtual
Returns an iterator pointing to the first symbol.
Note, that if the alphabet contains a hole in the space of label ids at the beginning the iterator must be winded to the first existing symbol.
Returns
a const iterator pointing to the first symbol or end()
Reimplemented from Fsa::Alphabet.
Definition at line 622 of file ClassicStateModel.cc.
void AllophoneAlphabet::clear () protected
reset
Definition at line 133 of file ClassicStateModel.cc.
AllophoneAlphabet::const_iterator AllophoneAlphabet::end () const virtual
Returns an iterator pointing behind the last symbol.
This usually does not need to be overloaded except for the case you need a different internal representation of the end iterator. Currently, InvalidLabelId is being used as end iterator.
Returns
a const iterator pointing to the first symbol or end()
Reimplemented from Fsa::Alphabet.
Definition at line 626 of file ClassicStateModel.cc.
Fsa::LabelId AllophoneAlphabet::index (const std::string & symbol) const virtual
Given a string representation of a symbol returns the label id.
Parameters
symbol the string representation of a symbol
Returns
the label id of the symbol or InvalidLabelId if the string represents no valid symbol
Reimplemented from Fsa::Alphabet.
Definition at line 528 of file ClassicStateModel.cc.
References Core::Component::criticalError(), defect, Bliss::ContextPhonology::PhonemeInContext::format(), Bliss::Token::id(), and verify.
std::pair< AllophoneAlphabet::AllophoneMap::iterator, bool > AllophoneAlphabet::insert (const Allophone * allo) const protected
takes ownership
Definition at line 118 of file ClassicStateModel.cc.
References verify.
bool AllophoneAlphabet::isDisambiguator (Fsa::LabelId index) const virtual
Determine wether a symbol is a disambiguator (see determinize for more details on the use of disambiguators).
Parameters
index the symbol's label id
Returns
true if the symbol is a disambiguator.
Reimplemented from Fsa::Alphabet.
Definition at line 613 of file ClassicStateModel.cc.
void AllophoneAlphabet::store (const std::string & filename) protected
Store list of allophones in alphabet.
Definition at line 467 of file ClassicStateModel.cc.
References Core::Component::error(), Bliss::Lemma::pronunciations(), and verify.
std::string AllophoneAlphabet::symbol (Fsa::LabelId index) const virtual
Returns the string representation of a symbol.
Parameters
index the symbol's label id
Returns
the string representation of the symbol or an empty string if there is no symbol with that label id
Implements Fsa::Alphabet.
Definition at line 513 of file ClassicStateModel.cc.
References Core::form(), and Core::Component::warning().
Referenced by Search::Wfst::StateSequenceBuilder::createSymbols(), and TestApplication::getUsage().
void AllophoneAlphabet::writeXml (Core::XmlWriter & o) const virtual
Write the alphabet to an XmlWriter.
Parameters
o the XmlWriter
Returns
true if the operation was successfull for all symbols, false otherwise
Reimplemented from Fsa::Alphabet.
Definition at line 630 of file ClassicStateModel.cc.
References defect, ensure, Core::form(), Core::strconv(), and verify.
The documentation for this class was generated from the following files:
ClassicStateModel.hh
ClassicStateModel.cc