Sprint: Signal::SlidingWindow< T > Class Template Reference
Signal::SlidingWindow< T > Class Template Reference
SlidingWindow over a sequence of data.
#include <SlidingWindow.hh>
Classes
struct copyMarginPolicy
Creates non-existing elements by copying the first resp.
struct fullMarginCondition
Condition is satisfied if the sliding window is full.
class marginCondition
Base class for margin conditions retrieving the state of the sliding window when loading or flushing.
class marginPolicy
Base class for margin policies creating missing elements.
struct meanMarginPolicy
Creates non-existing elements by average of the present elements in the sliding window.
struct notEmptyMarginCondition
Condition is satisfied if the sliding window contains at least one element.
struct oneMarginPolicy
Creates non-existing elements (all one) (Type of the Data structure T is: Flow::DataPtr<Flow::Vector<f32>)
struct presentNotEmptyMarginCondition
Condition is satisfied if the sliding window contains an element at the present position.
struct zeroMarginPolicy
Creates non-existing elements (all zero) (Type of the Data structure T is: Flow::DataPtr<Flow::Vector<f32>)
Public Types
enum MarginPolicyType { marginPolicyCopy, marginPolicyMean, marginPolicyZero, marginPolicyOne }
enum MarginConditionType { marginConditionNotEmpty, marginConditionPresentNotEmpty, marginConditionFull }
typedef Precursor::const_iterator ConstantIterator
typedef Precursor::iterator Iterator
typedef Precursor::const_reverse_iterator ConstantReverseIterator
typedef Precursor::reverse_iterator ReverseIterator
Public Member Functions
SlidingWindow (size_t maxSize=1, size_t right=0)
bool init (size_t maxSize, size_t right)
initializes the sliding window
void clear ()
void add (const T &add)
Adds a new element Removes the oldest element if number of past elements exceeded maxPastSize_.
void flush ()
Simulates adding one empty element.
void flushOut ()
Simulates adding at least so many (n) empty elements that output (.
bool get (int relativeIndex, T &out) const
returns the element at relative index
void getClosest (int relativeIndex, T &out) const
returns the closest existing element to relative index
bool out (T &out) const
returns the present element if contained.
bool presentEmpty () const
size_t futureSize () const
size_t maxFutureSize () const
size_t pastSize () const
size_t maxPastSize () const
bool removed (T &removed) const
bool removedValid () const
size_t maxSize () const
maximum number of elements set by the last call to init.
size_t size () const
number of elements
bool empty () const
bool full () const
const T & operator[] (size_t right) const
T & operator[] (size_t right)
const T & front () const
T & front ()
const T & back () const
T & back ()
ConstantIterator begin () const
Iterator begin ()
ConstantIterator end () const
Iterator end ()
ConstantReverseIterator reverseBegin () const
ReverseIterator reverseBegin ()
ConstantReverseIterator reverseEnd () const
ReverseIterator reverseEnd ()
Private Types
typedef std::deque< T > Precursor
Private Member Functions
int absoluteIndex (int relativeIndex) const
void removeOldest ()
Removes oldest element if necessary.
Private Attributes
size_t maxFutureSize_
size_t maxPastSize_
int indexOfPresent_
T removed_
bool removedValid_
Detailed Description
template<class T>
class Signal::SlidingWindow< T >
SlidingWindow over a sequence of data.
Usage: -call add to update the sliding window; -call flush to update the sliding window if no more input is available;
-call out to obtain the element at the output point (also called 'right' or 'present'); -call removed to obtain the removed element after the last call to add or flush; (Remark: neither out nor removed change the status of the sliding window) -call get to obtain the element at a index relative to the present position;
-use the iterators and operators to reach any arbitrary element in the sliding window.
Definition at line 38 of file SlidingWindow.hh.
Member Function Documentation
template<class T> void Signal::SlidingWindow< T >::add (const T & add)
Adds a new element Removes the oldest element if number of past elements exceeded maxPastSize_.
(
See also
init).
Definition at line 421 of file SlidingWindow.hh.
References Signal::SlidingWindow< T >::removeOldest(), and verify.
template<class T> const T& Signal::SlidingWindow< T >::back () const inline
Returns
is the oldest element
Definition at line 361 of file SlidingWindow.hh.
Referenced by Signal::SlidingWindow< StartEndTime >::back(), and Signal::SlidingWindow< T >::removeOldest().
template<class T> ConstantIterator Signal::SlidingWindow< T >::begin () const inline
Returns
is the iterator of the latest added element
Definition at line 369 of file SlidingWindow.hh.
Referenced by Signal::BayesClassification::argMin(), and Signal::SlidingWindow< StartEndTime >::begin().
template<class T> bool Signal::SlidingWindow< T >::empty () const inline
Returns
is true if the sliding-window is empty.
Definition at line 335 of file SlidingWindow.hh.
Referenced by Signal::SlidingWindow< T >::getClosest().
template<class T> ConstantIterator Signal::SlidingWindow< T >::end () const inline
Returns
is the iterator of the element after the oldest one
Definition at line 376 of file SlidingWindow.hh.
Referenced by Signal::PolinomialVectorInterpolation::copyControlPoint(), and Signal::SlidingWindow< StartEndTime >::end().
template<class T > void Signal::SlidingWindow< T >::flush ()
Simulates adding one empty element.
Present element will be the element at t+1. Removes the oldest element if number of past elements exceeded maxPastSize_ (
See also
init).
Definition at line 429 of file SlidingWindow.hh.
References Signal::SlidingWindow< T >::removeOldest().
Referenced by Signal::SlidingWindow< T >::flushOut().
template<class T > void Signal::SlidingWindow< T >::flushOut ()
Simulates adding at least so many (n) empty elements that output (.
See also
out) changes. Present element will be the element at t+n. Removes the oldest element if number of past elements exceeded maxPastSize_ (
init). Use this function instead of flush if one function call has to produce a valid output.
Definition at line 437 of file SlidingWindow.hh.
References Signal::SlidingWindow< T >::flush(), and Signal::SlidingWindow< T >::size().
template<class T> const T& Signal::SlidingWindow< T >::front () const inline
Returns
is the latest added element
Definition at line 354 of file SlidingWindow.hh.
Referenced by Signal::SlidingWindow< StartEndTime >::front().
template<class T> bool Signal::SlidingWindow< T >::full () const inline
Returns
is true if the sliding-window is full.
Definition at line 339 of file SlidingWindow.hh.
template<class T> size_t Signal::SlidingWindow< T >::futureSize () const inline
Returns
is number of future elements in sliding window.
Definition at line 298 of file SlidingWindow.hh.
template<class T> bool Signal::SlidingWindow< T >::get (int relativeIndex, T & out) const
returns the element at relative index
Parameters
relativeIndex.
relativeIndex
> 0 addresses the future elements,
== 0 addresses the present element,
< 0 addresses the past elements.
Returns
is true if sliding window contains an element at position
Parameters
relativeIndex.
Definition at line 454 of file SlidingWindow.hh.
References Signal::SlidingWindow< T >::operator[](), and Signal::SlidingWindow< T >::size().
template<class T> void Signal::SlidingWindow< T >::getClosest (int relativeIndex, T & out) const
returns the closest existing element to relative index
Parameters
relativeIndex. For further explanations
See also
get. Note: assertion is raised if sliding window is empty.
Definition at line 464 of file SlidingWindow.hh.
References Signal::SlidingWindow< T >::empty(), Signal::SlidingWindow< T >::operator[](), and Signal::SlidingWindow< T >::size().
template<class T > bool Signal::SlidingWindow< T >::init (size_t maxSize, size_t right)
initializes the sliding window
Parameters
maxSize gives the maximum number of elements in the sliding window.
right number of elements in the future.
Returns
is false if
Parameters
maxSize <=
right.
Definition at line 400 of file SlidingWindow.hh.
template<class T> size_t Signal::SlidingWindow< T >::maxSize () const inline
maximum number of elements set by the last call to init.
Definition at line 327 of file SlidingWindow.hh.
Referenced by Signal::SlidingWindow< StartEndTime >::full().
template<class T> const T& Signal::SlidingWindow< T >::operator[] (size_t right) const inline
Returns
is the right-th element (right = 0 is latest and right = size - 1 is the oldest element).
Definition at line 346 of file SlidingWindow.hh.
Referenced by Signal::SlidingWindow< T >::get(), Signal::SlidingWindow< T >::getClosest(), and Signal::SlidingWindow< StartEndTime >::operator[]().
template<class T> bool Signal::SlidingWindow< T >::out (T & out) const inline
returns the present element if contained.
Returns
is true if sliding window contains an element at 'present' position, i.e. sliding window is filled up so far or is not yet flushed so far.
Definition at line 288 of file SlidingWindow.hh.
Referenced by Signal::SlidingWindow< StartEndTime >::out().
template<class T> size_t Signal::SlidingWindow< T >::pastSize () const inline
Returns
is number of past elements in sliding window.
Definition at line 306 of file SlidingWindow.hh.
template<class T> bool Signal::SlidingWindow< T >::presentEmpty () const inline
Returns
is false if sliding window contains an element at 'present' position.
Definition at line 293 of file SlidingWindow.hh.
template<class T> bool Signal::SlidingWindow< T >::removed (T & removed) const inline
Parameters
removed is element removed during the last call to add or flushed.
Returns
is false if no element has been removed.
Definition at line 316 of file SlidingWindow.hh.
template<class T> bool Signal::SlidingWindow< T >::removedValid () const inline
Returns
is false if no element has been removed during the last call to add or flushed.
Definition at line 322 of file SlidingWindow.hh.
template<class T > void Signal::SlidingWindow< T >::removeOldest () private
Removes oldest element if necessary.
Definition at line 444 of file SlidingWindow.hh.
References Signal::SlidingWindow< T >::back(), and Signal::SlidingWindow< T >::size().
Referenced by Signal::SlidingWindow< T >::add(), and Signal::SlidingWindow< T >::flush().
template<class T> ConstantReverseIterator Signal::SlidingWindow< T >::reverseBegin () const inline
Returns
is the reverse iterator of the oldest element
Definition at line 384 of file SlidingWindow.hh.
Referenced by Signal::SlidingWindow< StartEndTime >::reverseBegin().
template<class T> ConstantReverseIterator Signal::SlidingWindow< T >::reverseEnd () const inline
Returns
is the reverse iterator of the element after the latest added one
Definition at line 391 of file SlidingWindow.hh.
Referenced by Signal::SlidingWindow< StartEndTime >::reverseEnd().
template<class T> size_t Signal::SlidingWindow< T >::size () const inline
number of elements
Definition at line 331 of file SlidingWindow.hh.
Referenced by Signal::SlidingWindow< T >::flushOut(), Signal::SlidingWindow< StartEndTime >::full(), Signal::SlidingWindow< StartEndTime >::futureSize(), Signal::SlidingWindow< T >::get(), Signal::SlidingWindow< T >::getClosest(), Signal::SlidingWindow< StartEndTime >::pastSize(), Signal::SlidingWindow< StartEndTime >::presentEmpty(), and Signal::SlidingWindow< T >::removeOldest().
The documentation for this class was generated from the following file:
SlidingWindow.hh