Sprint: Search::StateTree::SuffixSet Class Reference
Search::StateTree::SuffixSet Class Reference
A set of pronuncation suffixes (.
Classes
struct End
Public Types
typedef std::vector< PronunciationSuffix > ItemList
typedef std::vector< End > EndList
typedef std::vector< SuffixSet > SuffixSetList
Public Member Functions
void verifyGood () const
bool isSorted () const
bool isHashValid () const
u32 size () const
u32 hash () const
bool operator== (const SuffixSet &r) const
SuffixSet (const StateTree *m)
bool hasUniqueHead () const
StateDesc head () const
void addDirty (const PronunciationSuffix &s)
void sortAndHash ()
void addSorted (const PronunciationSuffix &s)
void partition (SuffixSetList &conts) const
Split the suffix set in a set of suffix sets, such that each resulting suffix set contains pronunciation suffixes with equal first state (w.r.t the state description.
void advance (ItemList &ends)
Go to the next state in all pronunciation suffixes.
void leap (std::vector< const Bliss::Pronunciation * > &leaps)
bool hasLeaped () const
u32 nStatesRemaining () const
Private Types
enum { dirty, sorted, hashValid }
Private Member Functions
void sort ()
void updateHash (const PronunciationSuffix &s) const
void updateHash () const
void add (const PronunciationSuffix &s)
Private Attributes
const StateTree * model_
ItemList items_
bool hasUniqueHead_
enum StateTree::SuffixSet:: { ... } consolidation_
u32 hash_
Detailed Description
A set of pronuncation suffixes (.
See also
PronunciationSuffix)
Definition at line 410 of file StateTree.cc.
Member Function Documentation
void Search::StateTree::SuffixSet::advance (ItemList & endingItems)
Go to the next state in all pronunciation suffixes.
Ending pronunciations are appended to endingItems
Definition at line 573 of file StateTree.cc.
References Core::form(), require, and Core::Component::warning().
Referenced by Search::StateTree::createBatch(), and Search::StateTree::pronunciationSuffixTransitEntry().
void Search::StateTree::SuffixSet::partition (SuffixSetList & conts) const
Split the suffix set in a set of suffix sets, such that each resulting suffix set contains pronunciation suffixes with equal first state (w.r.t the state description.
See also
StateDesc)
Todo:
Change the hash structure, instead of abusing TransitionModelIndex
Definition at line 544 of file StateTree.cc.
References Search::StateTree::head(), require, and verify.
Referenced by Search::StateTree::createBatch().
The documentation for this class was generated from the following file:
StateTree.cc