Sprint: Aligner Class Reference
Aligner Class Reference
Copyright 2020 RWTH Aachen University.
#include <Aligner.hh>
Public Member Functions
virtual ~Aligner ()
Destructor giving some statistics about the translation that was performed.
int main (const std::vector< std::string > &arguments)
Main entry point for an application.
std::string getConfiguration ()
void setMemberVariablesFromParameters ()
Public Member Functions inherited from Core::Application
virtual std::string getVariable () const
Return the name of the environment variable.
std::string getBaseName () const
Return the applications basename.
std::string getPath () const
Return the applications path.
virtual std::string getApplicationDescription () const
virtual std::string getParameterDescription () const
virtual std::string getDefaultParameterDescription () const
void reportLowLevelError (const std::string &msg="")
Errors messages are collected and later (during closeLogging()) printed to the error channel.
void setDefaultLoadConfigurationFile (bool f)
Configure default behaviour of loading a configuration file.
void setDefaultOutputXmlHeader (bool f)
Configure default behaviour of adding a valid xml header to standard channels.
void setTitle (const std::string &t)
Set the title of the application.
void setCommentCharacters (const std::string &c)
Set the set of possible comment characters for this application.
const std::string & getCommentCharacters (void) const
Return the string of comment characters.
Core::Channel & debugChannel (void)
Returns the debug binary outpput channel.
Core::XmlChannel & debugXmlChannel (void)
Returns the debug XML channel.
MappedArchiveReader getCacheArchiveReader (const std::string &archive_name, const std::string &item)
Returns a pointer to the cache-archive reader for the archive, and the specified item contained by the archive.
MappedArchiveWriter getCacheArchiveWriter (const std::string &archive_name, const std::string &item)
Returns a pointer to the cache-archive writer for the archive, and the specified item contained by the archive.
void exit (int status)
Terminate program execution.
void atexit (std::function< void()> f)
Like std::atexit() but will be execute sooner, at our own uninit, at the end of our main(), or in our exit().
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Private Member Functions
std::string getUsage () const
Overload this method to describe the usage of the application and to give a (short) description of the application.
void processFile (const std::string &sourceFilename, const std::string &targetFilename)
Fsa::ConstAutomatonRef createAlignAutomaton (std::string &sourceSentence, std::string &targetSentence, Translation::ConstConditionalLexiconRef conditionalLexicon)
Fsa::ConstAutomatonRef createAlignment (std::string &sourceSentence, std::string &targetSentence, Translation::ConstConditionalLexiconRef conditionalLexicon, Translation::Reordering *reordering)
void extract (Translation::ConditionalLexiconRef lexicon, Fsa::ConstAutomatonRef f, int extractionOrder)
Private Attributes
Fsa::Weight threshold_
Fsa::Weight beamThreshold_
float totalCost_
u32 nbest_
unsigned order_
unsigned extractionOrder_
unsigned normalizePoint_
unsigned iterations_
bool writeXml_
bool writeBiLang_
bool writeAachen_
bool writeLexicon_
bool normalize_
bool useSourceLm_
std::string sourceLmFilename_
Fsa::ConstAutomatonRef sourceLmAutomaton_
Core::CompressedOutputStream outputXml_
Core::CompressedOutputStream outputBiLang_
Core::CompressedOutputStream outputAachen_
Core::CompressedOutputStream outputLexicon_
std::vector< double > transitionProbs_
std::vector< int > iterationsOrder_
Translation::Reordering * reordering_
bool reorderLinear_
double perplexity_
double userTime_
Fsa::Weight factorReorder_
Fsa::Weight factorTransition_
Fsa::Weight factorLexicon_
Fsa::Weight factorSourceLm_
size_t sentence_
size_t sentences_
size_t oovs_
size_t words_
size_t arcs_
size_t maxMemory_
u32 segmentStart_
u32 segmentEnd_
Static Private Attributes
static Core::ParameterInt paramNBest_
static Core::ParameterFloatVector paramTransitionProbs_
static Core::ParameterFloat paramFactorTransition_
static Core::ParameterChoice paramLexiconType_
static Core::ParameterChoice paramModel_
static Core::ParameterFloat paramFactorReorder_
static Core::ParameterFloat paramFactorLexicon_
static Core::ParameterFloat paramFactorSourceLm_
static Core::ParameterInt paramSegmentStart_
static Core::ParameterInt paramNormalizePoint_
static Core::ParameterBool paramNormalize_
static Core::ParameterInt paramSegmentEnd_
static Core::ParameterString paramPrune_
static Core::ParameterString paramBeamPrune_
static Core::ParameterString paramOutputXmlFilename_
static Core::ParameterString paramOutputBiLangFilename_
static Core::ParameterString paramOutputAachenFilename_
static Core::ParameterString paramOutputLexiconFilename_
static Core::ParameterString paramSourceLmFilename_
static Core::ParameterInt paramOrder_
static Core::ParameterInt paramExtractionOrder_
static Core::ParameterInt paramIterations_
static Core::ParameterIntVector paramIterationsOrder_
Additional Inherited Members
Static Public Member Functions inherited from Core::Application
static Application * us ()
Get the global instance of the application (Singleton)
static int main (int argc, char *argv[])
private
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Application
void logSystemInfo () const
void logVersion () const
void logResources () const
void logResourceUsage () const
void logMemoryUsage () const
MappedArchive * getCacheArchive (const std::string &archive)
void openLogging ()
Opens channels and makes initial logs.
void closeLogging (bool configAvailable=true)
Closes down channels and makes final logs.
int run (const std::vector< std::string > &arguments)
void runAtExitFuncs ()
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Static Protected Member Functions inherited from Core::Application
static bool setFromEnvironment (const std::string &variable)
static bool setFromFile (const std::string &filename)
static std::vector< std::string > setFromCommandline (const std::vector< std::string > &arguments)
Protected Attributes inherited from Core::Application
Channel::Manager * channelManager_
Core::Channel * debugChannel_
Core::XmlChannel * debugXmlChannel_
std::map< std::string, MappedArchive * > cacheArchives_
bool defaultLoadConfigurationFile_
bool defaultOutputXmlHeader_
std::string comment_
std::string configFileName_
Timer timer_
std::list< std::function< void()> > atExitFuncs_
Protected Attributes inherited from Core::Configurable
Configuration config
Static Protected Attributes inherited from Core::Application
static const ParameterBool paramLogConfiguration
static const ParameterBool paramLogResolvedResources
static const ParameterString paramConfig
static const ParameterString paramCacheArchiveFile
static const ParameterBool paramCacheArchiveReadOnly
static const ParameterBool paramHelp
static std::string path_ = "."
static std::string basename_ = ""
static Application * app_ = 0
Detailed Description
Copyright 2020 RWTH Aachen University.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Definition at line 24 of file Tools/Aligner/Aligner.hh.
Constructor & Destructor Documentation
Aligner::~Aligner () virtual
Destructor giving some statistics about the translation that was performed.
Definition at line 100 of file Tools/Aligner/Aligner.cc.
References Core::getline(), Fsa::multiply(), Core::split(), and Fsa::staticCopy().
Member Function Documentation
std::string Aligner::getUsage () const private virtual
Overload this method to describe the usage of the application and to give a (short) description of the application.
Default return string is "usage: " + getBaseName() + "[OPTION(S)]\n" Return the usage of the application.
Normally, that method does not have to be overloaded; overload getApplicationDescription() and getParamterDescription() and getDefaultParameterDescription() instead.
Reimplemented from Core::Application.
Definition at line 44 of file Tools/Aligner/Aligner.cc.
int Aligner::main (const std::vector< std::string > & arguments) virtual
Main entry point for an application.
Implements Core::Application.
Definition at line 408 of file Tools/Aligner/Aligner.cc.
The documentation for this class was generated from the following files:
Tools/Aligner/Aligner.hh
Tools/Aligner/Aligner.cc