Sprint: Cart::XmlFloatBoxBuilderElement Class Reference
Cart::XmlFloatBoxBuilderElement Class Reference
<matrix-f64 nRows="2" nColumns="3"> 1.0 2.0 3.0 1.0 2.0 3.0 </matrix-f64>
#include <Parser.hh>
Public Member Functions
XmlFloatBoxBuilderElement (const char *name, XmlContext *context)
void start (const XmlAttributes atts)
Handle start of the current XML element.
void end ()
Handle end of the current XML element.
void characters (const char *ch, int len)
Handle charcter data in the current XML element.
Public Member Functions inherited from Core::XmlEmptyElement
virtual XmlElement * element (const char *name)
Determine the state to be entered for a nested XML element.
XmlEmptyElement (const char *_name, XmlContext *_context, bool allowWhitespace=true)
Public Member Functions inherited from Core::XmlElement
XmlElement (const char *_name, XmlContext *_context)
const char * name () const
XmlContext * context () const
virtual XmlSchemaParser * parser ()
virtual bool matches (const char *_name) const
Public Member Functions inherited from Core::BuildDelegation< T >
void setParsedHandler (ParsedHandler *handler)
template<class HandlerClass >
void setParsedHandler (HandlerClass &handler, void(HandlerClass::*deleg)(const T &))
void resetParsedHandler ()
void setCreatedHandler (CreatedHandler *handler)
template<class HandlerClass >
void setCreatedHandler (HandlerClass &handler, void(HandlerClass::*deleg)(T *))
void resetCreatedHandler ()
Protected Types
typedef XmlFloatBoxBuilderElement Self
typedef XmlEmptyElement Precursor
Private Attributes
size_t nRows_
size_t nCols_
std::string cdata_
Additional Inherited Members
Public Types inherited from Core::XmlElement
typedef XmlElement * pointer
Public Types inherited from Core::XmlContext
typedef XmlContext Self
typedef void(Self::* StartHandler) (const XmlAttributes atts)
typedef void(Self::* EndHandler) ()
typedef void(Self::* CharactersHandler) (const char *ch, int len)
Public Types inherited from Core::BuildDelegation< T >
typedef Delegation< const T & > ParsedDelegation
typedef Delegation< T * > CreatedDelegation
typedef ParsedDelegation::Target ParsedHandler
typedef CreatedDelegation::Target CreatedHandler
Static Public Member Functions inherited from Core::XmlContext
template<class T >
static StartHandler startHandler (void(T::*h)(const XmlAttributes atts))
template<class T >
static EndHandler endHandler (void(T::*h)())
template<class T >
static CharactersHandler charactersHandler (void(T::*h)(const char *ch, int len))
Static Public Attributes inherited from Core::XmlElement
static const char * wildcard = " * "
Protected Member Functions inherited from Core::XmlElement
XmlElement * collect (XmlElement *child)
Collects child elements.
Protected Member Functions inherited from Core::BuildDelegation< T >
void delegate (T *t)
Calls first parsed handler and then created handler.
void delegateOrDelete (T *t)
Calls first parsed handler and then created handler; if no created handler exists, t is deleted.
T * delegateAndCreate (T *t)
Calls first parsed handler and then created handler; return t if no created handler exists, else return a newly created instance of T .
bool delegateParsed (const T &t)
Calls parsed handler.
bool delegateCreated (T *t)
Calls created handler.
Protected Member Functions inherited from Core::Delegation< const T & >
void set (Target *target)
void set (TargetClass &tc, void(TargetClass::*tm)(const T &))
void reset ()
bool hasTarget ()
void delegate (const T &t)
Protected Member Functions inherited from Core::Delegation< T * >
void set (Target *target)
void set (TargetClass &tc, void(TargetClass::*tm)(T *))
void reset ()
bool hasTarget ()
void delegate (T *t)
Detailed Description
<matrix-f64 nRows="2" nColumns="3"> 1.0 2.0 3.0 1.0 2.0 3.0 </matrix-f64>
or (positions and types of whitespaces doesn't matter)
<matrix-f64 nRows="2" nColumns="3"> 1.0 2.0 3.0 1.0 2.0 3.0 </matrix-f64>
Definition at line 555 of file Parser.hh.
Member Function Documentation
void Cart::XmlFloatBoxBuilderElement::characters (const char * ch, int len) inline virtual
Handle charcter data in the current XML element.
Parameters
parser The XmlSchemaParser delegating the request.
Reimplemented from Core::XmlEmptyElement.
Definition at line 576 of file Parser.hh.
void XmlFloatBoxBuilderElement::end () virtual
Handle end of the current XML element.
end() is called when end tag of the current element is found.
Parameters
parser The XmlSchemaParser delegating the request.
Reimplemented from Core::XmlEmptyElement.
Definition at line 605 of file Parser.cc.
References Core::BuildDelegation< T >::delegateOrDelete(), Core::XmlEmptyElement::end(), Core::Component::error(), Core::Component::log(), require, Core::strconv(), and Core::Component::warning().
void XmlFloatBoxBuilderElement::start (const XmlAttributes atts) virtual
Handle start of the current XML element.
start() is called when the current state is entered.
Parameters
atts attributes of the XML start tag which caused the parser to enter this state. The name of the element will generally be implied by the fact that THIS state is entered.
Reimplemented from Core::XmlElement.
Definition at line 565 of file Parser.cc.
References Cart::XmlIndexedStringBuilderElement::end(), Core::Component::error(), Cart::XmlIndexedStringBuilderElement::start(), Core::XmlElement::start(), and Core::strconv().
The documentation for this class was generated from the following files:
Parser.hh
Parser.cc