Sprint: Signal::DcDetection Class Reference
Signal::DcDetection Class Reference
Public Types
typedef f32 Sample
typedef Flow::Time Time
typedef Flow::Vector< Sample > InputData
typedef Flow::Vector< Sample > OutputData
Public Member Functions
void setMaxDcIncrement (Sample maxDcIncrement)
void setMinDcLengthInS (Time minDcLengthInS)
void setMinNonDcSegmentLengthInS (Time minNonDcSegmentLengthInS)
void setMaximalOutputSize (u32 maximalOutputSize)
void setSampleRate (Time sampleRate)
bool put (const Flow::Vector< Sample > &in)
bool get (Flow::Vector< Sample > &out)
delivers a block of samples without DC segments
bool flush (Flow::Vector< Sample > &out)
delivers a last block of samples without DC segments
void reset ()
Private Member Functions
void init ()
bool isNonDC (const Sample &v)
bool isDcDetected ()
bool nextBlock ()
updates the dcLength_ and nonDcLength_ up to the next possible decision or up the end of the buffer
bool lastBlock ()
updates the dcLength_ and nonDcLength_ up to the end of the buffer
bool flushBlock (Flow::Vector< Sample > &out)
removes the first nonDcLength_ + dcLength_ samples from the buffer and copies first nonDcLength_ samples into out.
bool copyBlock (Flow::Vector< Sample > &out)
Copies first nonDcLength_ number of samples into out and sets the start- and end-time.
void eraseBlock ()
Removes the first nonDcLength_ + dcLength_ samples from the buffer.
Private Attributes
Time sampleRate_
Sample maxDcIncrement_
u32 minDcLength_
Minimum length of a DC segment.
Time minDcLengthInS_
u32 maximalOutputSize_
Size of output segments <= maximalOutputSize_.
u32 nonDcLength_
u32 dcLength_
u32 nOutputs_
u32 nonDcSegmentLength_
length of the last continuous non DC segment
u32 minNonDcSegmentLength_
non DC segments shorter than this value are discarded
Time minNonDcSegmentLengthInS_
non DC segments shorter than this value (given in seconds) are discarded
u32 totalRejected_
u32 totalAccepted_
std::deque< Sample > buffer_
Time bufferStartTime_
bool needInit_
Detailed Description
Definition at line 27 of file DcDetection.hh.
Member Function Documentation
bool DcDetection::copyBlock (Flow::Vector< Sample > & out) private
Copies first nonDcLength_ number of samples into out and sets the start- and end-time.
Returns
is false if the non DC segment is smaller than minNonDcSegmentLength_.
Definition at line 181 of file DcDetection.cc.
References verify.
Referenced by isDcDetected().
void DcDetection::eraseBlock () private
Removes the first nonDcLength_ + dcLength_ samples from the buffer.
Definition at line 203 of file DcDetection.cc.
Referenced by isDcDetected().
bool DcDetection::flush (Flow::Vector< Sample > & out)
delivers a last block of samples without DC segments
Returns
is false if buffer is empty
Definition at line 223 of file DcDetection.cc.
Referenced by isDcDetected().
bool DcDetection::flushBlock (Flow::Vector< Sample > & out) private
removes the first nonDcLength_ + dcLength_ samples from the buffer and copies first nonDcLength_ samples into out.
Definition at line 215 of file DcDetection.cc.
Referenced by isDcDetected().
bool DcDetection::get (Flow::Vector< Sample > & out)
delivers a block of samples without DC segments
Returns
is false if DC/non DC decision could not be made yet
remark: long non DC segments are delivered in blocks of length maximalOutputSize_
Definition at line 127 of file DcDetection.cc.
bool Signal::DcDetection::isDcDetected () inline private
Returns
is true if the number of DC samples at the end of the buffer are larger or equal to minDCLength_
Definition at line 82 of file DcDetection.hh.
References copyBlock(), eraseBlock(), flush(), flushBlock(), lastBlock(), minDcLength_, nextBlock(), and put().
bool Signal::DcDetection::isNonDC (const Sample & v) inline private
Returns
is true if the absolute difference between the sample v and the end of the non DC segment is larger then maxDcIncrement_
Definition at line 75 of file DcDetection.hh.
bool DcDetection::lastBlock () private
updates the dcLength_ and nonDcLength_ up to the end of the buffer
Returns
is false if buffer was empty Remark: assertion fails if a call to nextBlock could succeed.
Definition at line 166 of file DcDetection.cc.
References verify.
Referenced by isDcDetected().
bool DcDetection::nextBlock () private
updates the dcLength_ and nonDcLength_ up to the next possible decision or up the end of the buffer
Returns
is true if
DC decision could be made
buffer consist only of non DC samples and it is larger then input block size (maximalOutputSize_)
Definition at line 143 of file DcDetection.cc.
Referenced by isDcDetected().
bool DcDetection::put (const Flow::Vector< Sample > & in)
Returns
is false if the is a time gap between start time of in and end time of the buffer.
Definition at line 102 of file DcDetection.cc.
References verify.
Referenced by isDcDetected().
Member Data Documentation
u32 Signal::DcDetection::maximalOutputSize_ private
Size of output segments <= maximalOutputSize_.
Definition at line 47 of file DcDetection.hh.
u32 Signal::DcDetection::minDcLength_ private
Minimum length of a DC segment.
Definition at line 42 of file DcDetection.hh.
Referenced by isDcDetected().
u32 Signal::DcDetection::minNonDcSegmentLength_ private
non DC segments shorter than this value are discarded
Definition at line 57 of file DcDetection.hh.
Time Signal::DcDetection::minNonDcSegmentLengthInS_ private
non DC segments shorter than this value (given in seconds) are discarded
Definition at line 59 of file DcDetection.hh.
u32 Signal::DcDetection::nonDcSegmentLength_ private
length of the last continuous non DC segment
Definition at line 55 of file DcDetection.hh.
The documentation for this class was generated from the following files:
DcDetection.hh
DcDetection.cc