Sprint: Core::Condition Class Reference
Core::Condition Class Reference
A condition variable.
#include <Thread.hh>
Public Member Functions
bool signal (bool broadcastSignal=false)
Restarts one of the threads that are waiting on the condition variable.
bool broadcast ()
Restart all waiting threads.
bool wait ()
Wait for the condition to be signaled.
bool wait (Mutex &mutex)
bool timedWait (unsigned long microsonds)
Wait for the condition to be signaled with a bounded wait time.
Private Member Functions
timespec getTimeout (unsigned long microseconds)
Condition (const Condition &)
void operator= (const Condition &)
Private Attributes
pthread_cond_t cond_
Mutex mutex_
A condition variable must always be associated with a mutex, to avoid the race condition where a thread prepares to wait on a condition variable and another thread signals the condition just before the first thread actually waits on it.
Detailed Description
A condition variable.
A condition variable is a synchronization device that allows threads to suspend execution and relinquish the processors until some predicate on shared data is satisfied.
Definition at line 279 of file Thread.hh.
Member Function Documentation
bool Core::Condition::broadcast () inline
Restart all waiting threads.
See also
signal
Definition at line 305 of file Thread.hh.
Referenced by SimpleThreadPool::Thread::run().
bool Core::Condition::signal (bool broadcastSignal = false) inline
Restarts one of the threads that are waiting on the condition variable.
Parameters
broadcastSignal Restarts all waiting threads
Definition at line 295 of file Thread.hh.
bool Core::Condition::timedWait (unsigned long microsonds) inline
Wait for the condition to be signaled with a bounded wait time.
See also
wait
Definition at line 331 of file Thread.hh.
bool Core::Condition::wait () inline
Wait for the condition to be signaled.
The thread execution is suspended and does not consume any CPU time until the condition variable is signaled.
Definition at line 315 of file Thread.hh.
References Core::Thread::wait().
Referenced by SimpleThreadPool::Thread::run().
Member Data Documentation
Mutex Core::Condition::mutex_ private
A condition variable must always be associated with a mutex, to avoid the race condition where a thread prepares to wait on a condition variable and another thread signals the condition just before the first thread actually waits on it.
Definition at line 357 of file Thread.hh.
The documentation for this class was generated from the following file:
Thread.hh