Sprint: Signal::Warping Class Reference
Signal::Warping Class Reference
Classes
class AritmeticMeanInverseItem
AritmeticMeanInverseItem merges the interval [begin .
class CopyInverseItem
Copies the element at.
struct InsertZeroInverseItem
InsertZeroInverseItem creates values of the interval (first .
struct InverseItem
InverseItem is base class for items in inverseWarpingFunction.
struct KeepEndInverseItem
KeepEndInverseItem creates values of the interval (first .
class LinearInterpolationInverseItem
LinearInterpolationInverseItem creates values of the interval (first .
struct SelectBeginInverseItem
SelectBeginInverseItem merges the interval [begin .
Public Types
enum MergeType { AritmeticMean, SelectBegin }
enum InterpolationType { KeepEnd, InsertZero, LinearInterpolation }
typedef f32 Data
typedef f64 FloatIndex
typedef std::vector< FloatIndex > WarpingFunction
Public Member Functions
void setWarpingFunction (Math::UnaryAnalyticFunctionRef warpingFunction, size_t inputSize, MergeType mergeType, InterpolationType interpolationType)
void setInverseWarpingFunction (Math::UnaryAnalyticFunctionRef inverseWarpingFunction, size_t inputSize, InterpolationType interpolationType)
void apply (const std::vector< Data > &in, std::vector< Data > &out) const
Static Public Attributes
static const f64 copyTolerance
Private Member Functions
InverseItem * createMerger (MergeType type, u32 begin, u32 end) const
InverseItem * createInterpolator (InterpolationType type, u32 first, u32 last, f64 relativePosition) const
void deleteInverseItems ()
Static Private Member Functions
static bool equalRelativePosition (f64 x, f64 y)
Private Attributes
std::vector< InverseItem * > inverseWarpingFunction_
inverse of the warping function: contains commands (merge or interpolation) how create the value of the warped function at a given warped index
size_t inputSize_
Detailed Description
Definition at line 30 of file Warping.hh.
Member Function Documentation
void Warping::setInverseWarpingFunction (Math::UnaryAnalyticFunctionRef inverseWarpingFunction, size_t inputSize, InterpolationType interpolationType)
Parameters
inverseWarpingFunction contains indexes, i.e. maps warped indices to indices of the input vector.
For more to
Parameters
InterpolationType
See also
InverseItem.
Definition at line 63 of file Warping.cc.
References Core::abs(), defect, ensure, Core::floor(), and require.
Referenced by Signal::LinearWarpingNode::warping().
void Warping::setWarpingFunction (Math::UnaryAnalyticFunctionRef warpingFunction, size_t inputSize, MergeType mergeType, InterpolationType interpolationType)
Parameters
warpingFunction maps indexes of the input vector to indexes in the warped vector. For more to
mergeType and to
InterpolationType
See also
InverseItem.
Definition at line 26 of file Warping.cc.
References ensure, Core::floor(), require, and verify.
Referenced by Signal::LinearWarpingNode::warping().
Member Data Documentation
std::vector<InverseItem*> Signal::Warping::inverseWarpingFunction_ private
inverse of the warping function: contains commands (merge or interpolation) how create the value of the warped function at a given warped index
Definition at line 148 of file Warping.hh.
The documentation for this class was generated from the following files:
Warping.hh
Warping.cc