Sprint: Core::MappedArchive Class Reference
Core::MappedArchive Class Reference
This class represents an archive containing multiple "virtual" files, which can be mapped to memory.
#include <MappedArchive.hh>
Classes
struct MappedItem
struct Reader
The reader object which allows reading file contents from mapped archives.
struct Writer
The writer object which allows writing file contents into mapped archives.
Public Member Functions
MappedArchive (std::string archivePath, bool readOnly=false)
MappedArchiveWriter getWriter (std::string name)
Returns a writer which can be used to write the contents.
MappedArchiveReader getReader (std::string name)
Returns a reader object for the contained file.
Private Member Functions
void initializeTempFile ()
void releaseWriter (Writer *writer)
MappedItem getItem (std::string name) const
void finalize ()
bool loadData ()
bool loadFile ()
bool available (size_t size) const
template<class T >
T get ()
void skip (size_t size)
Private Attributes
std::string tempFile_
std::set< std::string > wroteTempFileItems_
std::vector< MappedItem > items_
MMappedFile * mapped_
std::string archivePath_
size_t readOffset_
Writer * currentWriter_
bool readOnly_
Detailed Description
This class represents an archive containing multiple "virtual" files, which can be mapped to memory.
The contained files can be accessed and written through the getWriter() and getReader() functions.
When a contained file is re-written, it is not really overwritten, but rather the contents of the new version is appended. Old versions are then removed during a cleanup phase when opening the archive the next time.
Definition at line 72 of file MappedArchive.hh.
Member Function Documentation
MappedArchiveReader Core::MappedArchive::getReader (std::string name)
Returns a reader object for the contained file.
The reader can be safely copied.
Definition at line 206 of file MappedArchive.cc.
References Core::MMappedFile::load(), Core::Component::log(), and Core::Application::us().
Referenced by Core::Application::getCacheArchiveReader().
MappedArchiveWriter Core::MappedArchive::getWriter (std::string name)
Returns a writer which can be used to write the contents.
Only one writer may be alive at each point in time. The changes are applied upon destruction of the writer. The writer can be safely copied.
Definition at line 128 of file MappedArchive.cc.
References Core::Component::log(), Core::Application::us(), and verify.
Referenced by Core::Application::getCacheArchiveWriter().
The documentation for this class was generated from the following files:
MappedArchive.hh
MappedArchive.cc