Sprint: Search::SearchSpace Class Reference
Search::SearchSpace Class Reference
Classes
struct AcousticPruning
struct BestTracePruning
struct Depth
struct FadeInPruning
struct FadeInPruningCollectMinimum
struct NoPruning
struct PerInstanceAcousticPruning
class PruningDesc
struct RecombinationSet
struct RecordMinimum
struct RecordMinimumPerInstance
struct ShortRecombinationDistance
Public Member Functions
void resetStatistics ()
void logStatistics (Core::XmlChannel &channel) const
void setAllowHmmSkips (bool allow)
--------— Public interface during search -----------—:
void addStartupWordEndHypothesis (TimeframeIndex)
void setCurrentTimeFrame (TimeframeIndex timeFrame, const Mm::FeatureScorer::Scorer &scorer)
void startNewTrees ()
void expandHmm ()
void pruneAndAddScores ()
void findWordEnds ()
void pruneEarlyWordEnds ()
Core::Ref< Trace > getModifiedTrace (TraceId trace, Bliss::Phoneme::Id initialPhone) const
void pruneWordEnds (Search::Score absoluteScoreThreshold)
void createTraces (TimeframeIndex time)
void recombineWordEnds (bool shallCreateLattice=false)
void hypothesizeEpsilonPronunciations (Score bestScore)
void clear ()
Search Management --------------------------------------------------------------------------—.
void rescale (Score offset, bool ignoreWordEnds=false)
bool needCleanup () const
void cleanup ()
void optimizeSilenceInWordLattice (const Bliss::Lemma *silence)
This is the simple lattice optimization selected by optimize-lattice=simple.
Core::Ref< Trace > getSentenceEnd (TimeframeIndex time, bool shallCreateLattice)
Find the best sentence end hypothesis.
Core::Ref< Trace > getSentenceEndFallBack (TimeframeIndex time, bool shallCreateLattice)
Fall back strategy for finding the best sentence hypothesis when there is no active word end hypothesis.
Core::Ref< Trace > getCommonPrefix () const
void changeInitialTrace (Core::Ref< Trace > trace)
u32 nStateHypotheses () const
u32 nEarlyWordEndHypotheses () const
u32 nWordEndHypotheses () const
u32 nActiveTrees () const
int lookAheadLength () const
void setLookAhead (const std::vector< Mm::FeatureVector > &)
Search::SearchAlgorithm::RecognitionContext setContext (Search::SearchAlgorithm::RecognitionContext)
Score bestProspect () const
Returns the best prospect, eg. the score of the best state hypothesis including the look-ahead score.
StateHypothesesList::const_iterator bestProspectStateHypothesis () const
Score bestScore () const
Returns the best score (the look-ahead score is not included)
StateHypothesesList::const_iterator bestScoreStateHypothesis () const
Score quantileStateScore (Score min, Score max, u32 nHyp) const
Score minimumWordEndScore () const
Returns the lowest word end score (without look-ahead) Always valid after findWordEnds was called.
Score quantileWordEndScore (Score min, Score max, u32 nHyp) const
SearchSpace (const Core::Configuration &configuration, Core::Ref< const Am::AcousticModel > acousticModel, Bliss::LexiconRef lexicon, Core::Ref< const Lm::ScaledLanguageModel > lm, Score wpScale)
----------— External Initialization -----------------—:
SearchAlgorithm::PruningRef describePruning ()
bool relaxPruning (f32 factor, f32 offset)
void resetPruning (SearchAlgorithm::PruningRef pruning)
Score beamPruning () const
void setMasterBeam (Score value)
virtual void initialize ()
void initializePruning ()
template<bool expandForward, bool expandSkip>
void expandStateSlow (const Search::StateHypothesis &hyp)
template<bool allowSkip>
void expandState (const Search::StateHypothesis &hyp)
template<bool sparseLookAhead, bool useBackOffOffset, class AcousticLookAhead , class Pruning >
void applyLookaheadInInstanceInternal (Instance *_instance, AcousticLookAhead &acousticLookAhead, Pruning &pruning)
template<class Pruning , class AcousticLookAhead >
void applyLookaheadInInstanceWithAcoustic (Instance *network, AcousticLookAhead &acousticLookAhead, Pruning &pruning)
template<bool onTheFlyRescoring>
void recombineTwoHypotheses (WordEndHypothesis &a, WordEndHypothesis &b, bool shallCreateLattice)
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Attributes
SearchSpaceStatistics * statistics
Statistics:
Core::Ref< PruningDesc > currentPruning_
Protected Types
typedef std::vector< StateHypothesis > StateHypothesesList
typedef std::vector< Instance * > InstanceList
typedef std::unordered_map< InstanceKey, Instance *, InstanceKey::Hash > KeyInstanceMap
typedef std::unordered_set< WordEndHypothesisList::iterator, WordEndHypothesis::Hash, WordEndHypothesis::Equality > WordEndHypothesisRecombinationMap
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions
PersistentStateTree const & network () const
bool encodeState () const
void filterStates ()
-------------— Search algorithm implementation details ---------------—:
void enforceCommonPrefix ()
void pruneStatesEarly ()
void pruneStatesPerLmState ()
LM State pruning: based on the prospect score grouped by StateId state.
template<class Pruning >
void addAcousticScoresInternal (Instance const &instance, Pruning &pruning, u32 from, u32 to)
template<class Pruning >
void addAcousticScores ()
template<class Pruning >
void pruneStates (Pruning &pruning)
Standard pruning:
void updateSsaLm ()
void correctPushedTransitions ()
void doStateStatisticsBeforePruning ()
void doStateStatistics ()
void doWordEndStatistics ()
void activateLmLookahead (Instance &instance, bool compute)
template<bool sparseLookAhead, bool reduceLookAheadBasedOnDepth, class AcousticLookAhead , class Pruning >
void applyLookaheadInInstanceInternal (Instance *_instance, AcousticLookAhead &acousticLookAhead, Pruning &pruning)
template<class Pruning , class AcousticLookAhead >
void applyLookaheadInInstanceWithAcoustic (Instance *network, AcousticLookAhead &acousticLookAhead, Pruning &pruning)
void applyLookaheadInInstance (Instance *network)
inline_ void addNewStateHypothesis (const StateHypothesis &hyp)
inline_ void activateOrUpdateStateHypothesisLoop (const StateHypothesis &hyp, Score score)
inline_ void activateOrUpdateStateHypothesisTransition (const StateHypothesis &hyp, Score score, StateId successorState)
inline_ void activateOrUpdateStateHypothesisDirectly (const StateHypothesis &hyp)
inline_ bool eventuallyDeactivateTree (Search::Instance *, bool increaseInactiveCounter)
Checks whether network should be deactivated, and if so do it.
Instance * createTreeInstance (const InstanceKey &key)
template<bool allowSkip>
inline_ void expandState (const Search::StateHypothesis &hyp)
template<bool expandForward, bool expandSkip>
inline_ void expandStateSlow (const Search::StateHypothesis &hyp)
Instance * instanceForKey (bool create, const InstanceKey &key, Lm::History const &lookaheadHistory, Lm::History const &scoreHistory)
------—— Search algorithm helpers ---------------------——:
template<bool earlyWordEndPruning, bool onTheFlyRescoring>
void processOneWordEnd (Instance const &at, StateHypothesis const &hyp, s32 exit, Score exitPenalty, Score relativePruning, Score &bestWordEndPruning)
template<bool earlyWordEndPruning, bool onTheFlyRescoring>
void findWordEndsInternal ()
template<bool onTheFlyRescoring>
void recombineWordEndsInternal (bool shallCreateLattice)
u32 getLastSyntacticToken (const Core::Ref< Trace > &_trace)
Instance * activateOrUpdateTree (const Core::Ref< Trace > &, Lm::History, Lm::History, Lm::History, StateId, Score)
Instance * getBackOffInstance (Instance *instance)
inline_ const Am::StateTransitionModel * transitionModel (const StateTree::StateDesc &desc) const
void getTransitionModels ()
StateId rootForCoarticulation (std::pair< Bliss::Phoneme::Id, Bliss::Phoneme::Id >) const
void initializeLanguageModel ()
void pruneSilenceSiblingTraces (Core::Ref< Trace >, const Bliss::Lemma *silence)
Remove sibling traces that are silence.
void dumpWordEnds (std::ostream &, Core::Ref< const Bliss::PhonemeInventory >) const
void extendHistoryByLemma (WordEndHypothesis &weh, const Bliss::Lemma *lemma) const
std::pair< Bliss::Phoneme::Id, Bliss::Phoneme::Id > describeRootState (StateId state) const
template<bool onTheFlyRescoring>
inline_ void recombineTwoHypotheses (WordEndHypothesis &a, WordEndHypothesis &b, bool shallCreateLattice)
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes
f64 globalScoreOffset_
-------— Data -------—:
TimeframeIndex timeFrame_
Mm::FeatureScorer::Scorer scorer_
Bliss::LexiconRef lexicon_
Persistent models:
Core::Ref< const Am::AcousticModel > acousticModel_
Core::Ref< const Lm::ScaledLanguageModel > lm_
Core::Ref< const Lm::ScaledLanguageModel > lookaheadLm_
Core::Ref< const Lm::LanguageModel > recombinationLm_
Lm::SearchSpaceAwareLanguageModel const * ssaLm_
AdvancedTreeSearch::LanguageModelLookahead * lmLookahead_
std::vector< const Am::StateTransitionModel * > transitionModels_
TraceManager trace_manager_
StaticSearchAutomaton const * automaton_
Lm::History unigramHistory_
AdvancedTreeSearch::LanguageModelLookahead::ContextLookaheadReference unigramLookAhead_
AdvancedTreeSearch::AcousticLookAhead * acousticLookAhead_
bool conditionPredecessorWord_
Search options.
bool decodeMesh_
bool correctPushedBoundaryTimes_
bool correctPushedAcousticScores_
bool earlyBeamPruning_
bool earlyWordEndPruning_
bool histogramPruningIsMasterPruning_
bool reducedContextWordRecombination_
unsigned reducedContextWordRecombinationLimit_
bool onTheFlyRescoring_
unsigned onTheFlyRescoringMaxHistories_
unsigned maximumMutableSuffixLength_
unsigned maximumMutableSuffixPruningInterval_
Score acousticPruning_
Pruning thresholds.
u32 acousticPruningLimit_
Score wordEndPruning_
u32 wordEndPruningLimit_
f64 lmStatePruning_
f32 wordEndPhonemePruningThreshold_
f32 acousticProspectFactor_
Score perInstanceAcousticPruningScale_
f32 minimumBeamPruning_
Boundary values for incremental search:
f32 maximumBeamPruning_
u32 minimumAcousticPruningLimit_
u32 maximumAcousticPruningLimit_
f32 minimumStatesAfterPruning_
f32 minimumWordEndsAfterPruning_
f32 minimumWordLemmasAfterRecombination_
f32 maximumStatesAfterPruning_
f32 maximumWordEndsAfterPruning_
f32 maximumAcousticPruningSaturation_
f64 earlyWordEndPruningAnticipatedLmScore_
u32 wordEndPruningFadeInInterval_
u32 instanceDeletionLatency_
-— Lookahead / Instance options ----------—
u32 fullLookAheadStateMinimum_
f32 fullLookAheadDominanceMinimum_
u32 currentLookaheadInstanceStateThreshold_
AdvancedTreeSearch::LanguageModelLookahead::LookaheadId fullLookaheadAfterId_
bool sparseLookahead_
bool overflowLmScoreToAm_
bool sparseLookaheadSlowPropagation_
f32 unigramLookaheadBackoffFactor_
bool earlyBackoff_
bool correctBackoff_
bool allowSkips_
Score wpScale_
bool extendStatistics_
bool encodeStateInTrace_
bool encodeStateInTraceAlways_
Score bestScore_
Temporary search variables:
Score bestProspect_
Score minWordEndScore_
Histogram stateHistogram_
Histogram wordEndHistogram_
std::unordered_map< InstanceKey, Score, InstanceKey::Hash > bestInstanceProspect_
StateHypothesesList stateHypotheses
The dynamic search space:
StateHypothesesList newStateHypotheses
WordEndHypothesisList wordEndHypotheses
EarlyWordEndHypothesisList earlyWordEndHypotheses
InstanceList activeInstances
KeyInstanceMap activeInstanceMap
StateHypothesisIndex currentTreeFirstNewStateHypothesis
Temporary search space helpers:
WordEndHypothesisRecombinationMap wordEndHypothesisMap
std::vector< StateHypothesisIndex > stateHypothesisRecombinationArray
ScoreDependentStatistic statesOnDepth_
ScoreDependentStatistic statesOnInvertedDepth_
bool hadWordEnd_
Statistics, which are reset whenever a new (partial) recognition is started.
Core::Statistics< u32 > currentStatesAfterPruning
Core::Statistics< u32 > currentWordEndsAfterPruning
Core::Statistics< u32 > currentWordLemmasAfterRecombination
Core::Statistics< f32 > currentAcousticPruningSaturation
Search::SearchAlgorithm::RecognitionContext recognitionContext_
Dynamically set context (i.e. left and right boundary conditions)
std::vector< Core::WeakRef< Trace > > altHistTraces_
Memory Leak workaround.
PerformanceCounter * applyLookaheadPerf_
PerformanceCounter * applyLookaheadSparsePerf_
PerformanceCounter * applyLookaheadSparsePrePerf_
PerformanceCounter * applyLookaheadStandardPerf_
PerformanceCounter * computeLookaheadPerf_
PerformanceCounter * extendedPerf_
Protected Attributes inherited from Core::Configurable
Configuration config
Friends
struct FadeInPruningCollectMinimum< RecordMinimum, true, false >
struct FadeInPruningCollectMinimum< RecordMinimum, false, false >
struct FadeInPruningCollectMinimum< RecordMinimum, true, true >
struct FadeInPruningCollectMinimum< RecordMinimum, false, true >
class AdvancedTreeSearch::AcousticLookAhead
Detailed Description
Definition at line 124 of file AdvancedTreeSearch/SearchSpace.hh.
Constructor & Destructor Documentation
Search::SearchSpace::SearchSpace (const Core::Configuration & configuration, Core::Ref< const Am::AcousticModel > acousticModel, Bliss::LexiconRef lexicon, Core::Ref< const Lm::ScaledLanguageModel > lm, Score wpScale)
----------— External Initialization -----------------—:
Definition at line 757 of file AdvancedTreeSearch/SearchSpace.cc.
References Core::Ref< T >::get(), Search::StaticSearchAutomaton::hmmLength, lexicon_, Core::Component::log(), Lm::LanguageModel::lookaheadLanguageModel(), Lm::LanguageModel::recombinationLanguageModel(), and Core::Component::warning().
Member Function Documentation
void Search::SearchSpace::activateLmLookahead (Search::Instance & instance, bool compute) protected
Parameters
compute If this is true, a new look-ahead table is computed. Otherwise, only existing tables are re-used.
Definition at line 1681 of file AdvancedTreeSearch/SearchSpace.cc.
References Search::Instance::backOffParent, AdvancedTreeSearch::LanguageModelLookahead::fill(), Core::Ref< T >::get(), AdvancedTreeSearch::LanguageModelLookahead::getLookahead(), Lm::History::isValid(), Search::Instance::lookaheadHistory, Search::Instance::totalBackOffOffset, and AdvancedTreeSearch::LanguageModelLookahead::tryToGetLookahead().
Referenced by eventuallyDeactivateTree().
Instance * Search::SearchSpace::activateOrUpdateTree (const Core::Ref< Trace > & trace, Lm::History recombinationHistory, Lm::History lookaheadHistory, Lm::History scoreHistory, StateId entry, Score score) protected
TODO (Nolden): getLastSyntacticToken is inefficient for long sequences. A simple rule would be better: Stay in same instance, or follow most recent pron.
Definition at line 3563 of file AdvancedTreeSearch/SearchSpace.cc.
References Lm::addLemmaPronunciationScoreOmitExtension(), Search::Instance::addLmScore(), conditionPredecessorWord_, Search::Instance::enter(), Core::Component::exit(), instanceForKey(), Bliss::LemmaPronunciation::invalidId, Lm::History::isValid(), lexicon_, Search::Instance::totalBackOffOffset, and verify.
Referenced by instanceForKey().
Score Search::SearchSpace::bestProspect () const
Returns the best prospect, eg. the score of the best state hypothesis including the look-ahead score.
Definition at line 1723 of file AdvancedTreeSearch/SearchSpace.cc.
References bestProspectStateHypothesis(), and stateHypotheses.
SearchSpace::StateHypothesesList::const_iterator Search::SearchSpace::bestProspectStateHypothesis () const
Warning
: Expensive, without caching
Definition at line 1753 of file AdvancedTreeSearch/SearchSpace.cc.
References bestScore(), and stateHypotheses.
Referenced by bestProspect().
Score Search::SearchSpace::bestScore () const
Returns the best score (the look-ahead score is not included)
Warning
: Expensive, but with caching
Definition at line 1732 of file AdvancedTreeSearch/SearchSpace.cc.
References bestScore_, bestScoreStateHypothesis(), and stateHypotheses.
Referenced by bestProspectStateHypothesis(), bestScoreStateHypothesis(), Search::Wfst::SearchSpace< N, S >::expandEpsilonArcs(), getSentenceEnd(), pruneStates(), and Search::Wfst::SearchSpace< N, S >::quantileStateScore().
SearchSpace::StateHypothesesList::const_iterator Search::SearchSpace::bestScoreStateHypothesis () const
Warning
: Expensive, without caching
Definition at line 1742 of file AdvancedTreeSearch/SearchSpace.cc.
References bestScore(), and stateHypotheses.
Referenced by bestScore(), and getSentenceEndFallBack().
void Search::SearchSpace::clear ()
Search Management --------------------------------------------------------------------------—.
Definition at line 1069 of file AdvancedTreeSearch/SearchSpace.cc.
References altHistTraces_, bestScore_, globalScoreOffset_, hadWordEnd_, Core::Ref< T >::reset(), and stateHypotheses.
Referenced by setAllowHmmSkips().
bool Search::SearchSpace::eventuallyDeactivateTree (Search::Instance * at, bool increaseInactiveCounter) inline protected
Checks whether network should be deactivated, and if so do it.
Returns true iff network has been deactivated
Definition at line 1107 of file AdvancedTreeSearch/SearchSpace.cc.
References activateLmLookahead(), Search::Instance::backOffChainStates(), Search::Instance::backOffInstance, Search::HMMStateNetwork::batchSuccessorsSimple(), Search::HMMStateNetwork::batchSuccessorsSimpleIgnoreLabels(), bestScore_, currentTreeFirstNewStateHypothesis, Core::Ref< T >::get(), getBackOffInstance(), Search::Instance::inactive, instanceDeletionLatency_, Search::Instance::lookaheadHistory, Mc::Component::scale(), Search::SingleSuccessorBatchMask, Search::HMMStateNetwork::state(), Search::HMMState::stateDesc, stateHypotheses, statistics, PerformanceCounter::stopAndYield(), Search::HMMState::successors, and verify.
Referenced by pruneStates(), and pruneStatesPerLmState().
void Search::SearchSpace::filterStates () protected
-------------— Search algorithm implementation details ---------------—:
Definition at line 1896 of file AdvancedTreeSearch/SearchSpace.cc.
References acousticPruning_, bestScore_, Search::SearchSpaceStatistics::customStatistics(), Bliss::Lemma::evaluationTokenSequences(), Search::TraceManager::getUnmodified(), globalScoreOffset_, Bliss::Lemma::hasEvaluationTokenSequence(), Search::TraceManager::isModified(), Search::TraceManager::modify(), Search::StaticSearchAutomaton::prefixFilter, pruneStates(), pruneStatesPerLmState(), require, Search::HMMStateNetwork::state(), Search::HMMState::stateDesc, stateHypotheses, statistics, Search::TraceManager::traceItem(), and verify.
template<bool earlyWordEndPruning, bool onTheFlyRescoring> void Search::SearchSpace::findWordEndsInternal () protected
With pushing, ca. 80% of all label-lists are single-labels, so optimize for this case
Definition at line 3641 of file AdvancedTreeSearch/SearchSpace.cc.
References acousticPruning_, Core::Component::exit(), Search::HMMStateNetwork::state(), Search::HMMState::stateDesc, stateHypotheses, statistics, and verify.
Instance * Search::SearchSpace::getBackOffInstance (Instance * instance) protected
Todo:
Mglicherweise wird der falsche backoff-score angewandt. Es sollte der score fr die verkrzte history benutzt werden.
Definition at line 3716 of file AdvancedTreeSearch/SearchSpace.cc.
References Search::Instance::backOffInstance, Search::Instance::backOffParent, Lm::BackingOffLm::getBackOffScores(), Lm::History::isValid(), Search::Instance::lookaheadHistory, Lm::BackingOffLm::reducedHistory(), Search::Instance::scoreHistory, and verify.
Referenced by eventuallyDeactivateTree().
Core::Ref< Trace > Search::SearchSpace::getSentenceEnd (TimeframeIndex time, bool shallCreateLattice)
Find the best sentence end hypothesis.
Returns a back-trace reference which can be used to determine the word sequence. The returned reference immediately points a trace-back item which includes the language model sentence end score. Its predecessor indicates the final word of the sentence. In case no word-end hypothesis is active, a null reference is returned. If creation of the word lattice is requested, the returned trace has siblings corresponding to sub-optimal sentence ends.
Definition at line 2565 of file AdvancedTreeSearch/SearchSpace.cc.
References Lm::addLemmaScore(), bestScore(), Core::Ref< T >::get(), globalScoreOffset_, hadWordEnd_, Lm::History::isValid(), recognitionContext_, Mc::Component::scale(), Lm::LanguageModel::sentenceEndScore(), stateHypotheses, Search::Instance::totalBackOffOffset, Search::TraceManager::traceItem(), and verify.
Core::Ref< Trace > Search::SearchSpace::getSentenceEndFallBack (TimeframeIndex time, bool shallCreateLattice)
Fall back strategy for finding the best sentence hypothesis when there is no active word end hypothesis.
Typically used when getBestSentenceEnd() fails. This problem can occur when the recording is truncated in the middle of a word and pruning is tight. The strategy is to select the best state from each active network and consider it as a "word end" without a pronunciation.
Todo:
This does not create a lattice for the last word. However a lattice structure is given for the previous words.
Definition at line 2712 of file AdvancedTreeSearch/SearchSpace.cc.
References Lm::addLemmaScore(), bestScoreStateHypothesis(), globalScoreOffset_, Lm::History::isValid(), Core::Component::log(), recognitionContext_, Mc::Component::scale(), Lm::LanguageModel::sentenceEndScore(), stateHypotheses, Search::TraceManager::traceItem(), Core::Application::us(), verify, and Core::Component::warning().
void Search::SearchSpace::hypothesizeEpsilonPronunciations (Score bestScore)
Todo:
Un-copy this code
Definition at line 2321 of file AdvancedTreeSearch/SearchSpace.cc.
References Lm::addLemmaPronunciationScoreOmitExtension(), Search::SearchSpaceStatistics::customStatistics(), Core::Component::exit(), globalScoreOffset_, lexicon_, Core::ref(), Mc::Component::scale(), Search::HMMStateNetwork::state(), Search::HMMState::stateDesc, and statistics.
Instance * Search::SearchSpace::instanceForKey (bool create, const InstanceKey & key, Lm::History const & lookaheadHistory, Lm::History const & scoreHistory) protected
------—— Search algorithm helpers ---------------------——:
Parameters
create Whether the network should be created if it doesn't exist yet
key The key, containing the unique properties of the network
Definition at line 3339 of file AdvancedTreeSearch/SearchSpace.cc.
References acousticPruning_, activateOrUpdateTree(), Core::Ref< T >::get(), hadWordEnd_, Search::Instance::lookaheadHistory, minimumBeamPruning_, recognitionContext_, Core::Ref< T >::reset(), Search::Instance::scoreHistory, stateHypotheses, statistics, and verify.
Referenced by activateOrUpdateTree().
Score Search::SearchSpace::minimumWordEndScore () const
Returns the lowest word end score (without look-ahead) Always valid after findWordEnds was called.
Definition at line 2112 of file AdvancedTreeSearch/SearchSpace.cc.
References acousticPruning_, Search::SearchSpaceStatistics::customStatistics(), Search::TraceManager::getModification(), globalScoreOffset_, Bliss::LemmaPronunciation::invalidId, Search::TraceManager::isModified(), Bliss::Pronunciation::length(), lexicon_, Bliss::PhonemeInventory::nPhonemes(), Bliss::PhonemeInventory::phoneme(), Bliss::Lexicon::phonemeInventory(), Bliss::Pronunciation::phonemes(), Core::ref(), statistics, Search::TraceManager::traceItem(), and verify.
void Search::SearchSpace::optimizeSilenceInWordLattice (const Bliss::Lemma * silence)
This is the simple lattice optimization selected by optimize-lattice=simple.
The effect is this: All partial sentence hypotheses ending with silence are suppressed from the lattice - except that the best scoring hypothesis is always preserved, even if it ends with silence.
Definition at line 2446 of file AdvancedTreeSearch/SearchSpace.cc.
References Core::Component::criticalError(), Core::Component::error(), Lm::LanguageModel::extendedHistory(), globalScoreOffset_, Lm::History::isValid(), lexicon_, Search::StaticSearchAutomaton::network, Bliss::PhonemeInventory::phoneme(), Bliss::Lexicon::phonemeInventory(), pruneSilenceSiblingTraces(), recognitionContext_, Lm::LanguageModel::startHistory(), Search::HMMStateNetwork::stateCount(), Bliss::Symbol::str(), Bliss::Token::symbol(), Core::Application::us(), and verify.
void Search::SearchSpace::pruneSilenceSiblingTraces (Core::Ref< Trace > trace, const Bliss::Lemma * silence) protected
Remove sibling traces that are silence.
Definition at line 2429 of file AdvancedTreeSearch/SearchSpace.cc.
Referenced by optimizeSilenceInWordLattice().
template<class Pruning > void Search::SearchSpace::pruneStates (Pruning & pruning) protected
Standard pruning:
Definition at line 1848 of file AdvancedTreeSearch/SearchSpace.cc.
References bestScore(), eventuallyDeactivateTree(), stateHypotheses, and verify.
Referenced by filterStates().
void Search::SearchSpace::pruneStatesPerLmState () protected
LM State pruning: based on the prospect score grouped by StateId state.
Definition at line 1775 of file AdvancedTreeSearch/SearchSpace.cc.
References acousticPruning_, eventuallyDeactivateTree(), stateHypotheses, and verify.
Referenced by filterStates().
void Search::SearchSpace::setAllowHmmSkips (bool allow)
--------— Public interface during search -----------—:
Definition at line 881 of file AdvancedTreeSearch/SearchSpace.cc.
References acousticPruning_, Search::StaticSearchAutomaton::buildBatches(), Search::StaticSearchAutomaton::buildNetwork(), clear(), Search::defaultBeamPruning, Core::Component::error(), AdvancedTreeSearch::LanguageModelLookahead::fill(), AdvancedTreeSearch::LanguageModelLookahead::fillZero(), AdvancedTreeSearch::LanguageModelLookahead::getLookahead(), Search::StaticSearchAutomaton::hmmLength, AdvancedTreeSearch::AcousticLookAhead::initializeModelsFromNetwork(), lexicon_, Core::Component::log(), Search::StaticSearchAutomaton::network, Search::StaticSearchAutomaton::prefixFilter, Lm::LanguageModel::reducedHistory(), Core::Ref< T >::reset(), Mc::Component::scale(), Lm::LanguageModel::startHistory(), Search::HMMStateNetwork::stateCount(), statistics, and Core::Component::warning().
Member Data Documentation
Score Search::SearchSpace::acousticPruning_ protected
Pruning thresholds.
Definition at line 180 of file AdvancedTreeSearch/SearchSpace.hh.
Referenced by filterStates(), findWordEndsInternal(), instanceForKey(), minimumWordEndScore(), pruneStatesPerLmState(), and setAllowHmmSkips().
std::vector<Core::WeakRef<Trace> > Search::SearchSpace::altHistTraces_ protected
Memory Leak workaround.
Definition at line 277 of file AdvancedTreeSearch/SearchSpace.hh.
Referenced by clear().
Score Search::SearchSpace::bestScore_ mutable protected
Temporary search variables:
Definition at line 235 of file AdvancedTreeSearch/SearchSpace.hh.
Referenced by bestScore(), clear(), eventuallyDeactivateTree(), and filterStates().
bool Search::SearchSpace::conditionPredecessorWord_ protected
Search options.
Definition at line 165 of file AdvancedTreeSearch/SearchSpace.hh.
Referenced by activateOrUpdateTree().
StateHypothesisIndex Search::SearchSpace::currentTreeFirstNewStateHypothesis protected
Temporary search space helpers:
Definition at line 258 of file AdvancedTreeSearch/SearchSpace.hh.
Referenced by eventuallyDeactivateTree().
f64 Search::SearchSpace::globalScoreOffset_ protected
-------— Data -------—:
Definition at line 137 of file AdvancedTreeSearch/SearchSpace.hh.
Referenced by clear(), filterStates(), getSentenceEnd(), getSentenceEndFallBack(), hypothesizeEpsilonPronunciations(), minimumWordEndScore(), and optimizeSilenceInWordLattice().
bool Search::SearchSpace::hadWordEnd_ protected
Statistics, which are reset whenever a new (partial) recognition is started.
Definition at line 269 of file AdvancedTreeSearch/SearchSpace.hh.
Referenced by clear(), getSentenceEnd(), and instanceForKey().
u32 Search::SearchSpace::instanceDeletionLatency_ protected
-— Lookahead / Instance options ----------—
Definition at line 205 of file AdvancedTreeSearch/SearchSpace.hh.
Referenced by eventuallyDeactivateTree().
Bliss::LexiconRef Search::SearchSpace::lexicon_ protected
Persistent models:
Definition at line 142 of file AdvancedTreeSearch/SearchSpace.hh.
Referenced by activateOrUpdateTree(), hypothesizeEpsilonPronunciations(), minimumWordEndScore(), optimizeSilenceInWordLattice(), SearchSpace(), and setAllowHmmSkips().
f32 Search::SearchSpace::minimumBeamPruning_ protected
Boundary values for incremental search:
Definition at line 190 of file AdvancedTreeSearch/SearchSpace.hh.
Referenced by instanceForKey().
Search::SearchAlgorithm::RecognitionContext Search::SearchSpace::recognitionContext_ protected
Dynamically set context (i.e. left and right boundary conditions)
Definition at line 274 of file AdvancedTreeSearch/SearchSpace.hh.
Referenced by getSentenceEnd(), getSentenceEndFallBack(), instanceForKey(), and optimizeSilenceInWordLattice().
StateHypothesesList Search::SearchSpace::stateHypotheses protected
The dynamic search space:
Definition at line 245 of file AdvancedTreeSearch/SearchSpace.hh.
Referenced by bestProspect(), bestProspectStateHypothesis(), bestScore(), bestScoreStateHypothesis(), clear(), eventuallyDeactivateTree(), filterStates(), findWordEndsInternal(), getSentenceEnd(), getSentenceEndFallBack(), instanceForKey(), pruneStates(), and pruneStatesPerLmState().
SearchSpaceStatistics* Search::SearchSpace::statistics
Statistics:
Definition at line 127 of file AdvancedTreeSearch/SearchSpace.hh.
Referenced by eventuallyDeactivateTree(), filterStates(), findWordEndsInternal(), hypothesizeEpsilonPronunciations(), instanceForKey(), minimumWordEndScore(), and setAllowHmmSkips().
The documentation for this class was generated from the following files:
AdvancedTreeSearch/SearchSpace.hh
AdvancedTreeSearch/SearchSpace.cc