Sprint: Fsa::AlphabetMapping Class Reference
Fsa::AlphabetMapping Class Reference
Represents the result of a call to one of the mapAlphabet functions.
#include <AlphabetUtility.hh>
Public Types
typedef u8 Type
Public Types inherited from Core::Vector< LabelId >
typedef std::vector< LabelId > Precursor
typedef Precursor::iterator iterator
typedef Precursor::const_iterator const_iterator
Public Member Functions
void clear ()
AlphabetMapping & operator= (const AlphabetMapping &)
Type type () const
bool isModifyingType () const
ConstAlphabetRef from () const
ConstAlphabetRef to () const
void map (LabelId from, LabelId to)
Add a mapping for a single label id.
void del (LabelId)
Add a mapping to delete a single label id.
const LabelId operator[] (LabelId i) const
Request the target label id for a source label id.
Public Member Functions inherited from Core::Vector< LabelId >
Vector (size_t size)
Vector (size_t size, const LabelId &def)
Vector (const Precursor &vector)
void grow (size_t maxId, const LabelId &def=LabelId())
grow to size maxId+1.
void yield ()
Free over-allocated storage.
void minimize ()
void set (size_t id, const LabelId &val, const LabelId &def=LabelId())
safe set
LabelId get (size_t id, const LabelId &def=LabelId()) const
safe get
size_t getMemoryUsed () const
Static Public Attributes
static const Type typeUnmapped = 0x01
all symbols have the same index in FROM and TO
static const Type typeComplete = 0x02
all symbols in FROM are also in TO
static const Type typeIdentity = 0x04
FROM and TO are identical (not just equal)
Private Attributes
ConstAlphabetRef from_
ConstAlphabetRef to_
Type type_
LabelId unkId_
Friends
void mapAlphabet (ConstAlphabetRef, ConstAlphabetRef, AlphabetMapping &, LabelId, u32)
Generally calculates the mapping between two alphabets.
Detailed Description
Represents the result of a call to one of the mapAlphabet functions.
This is a separate class and not simply a vector, because:
we need additional information of the type of mapping (injective, one-to-one, etc.)
seemlessly support all special labels
Definition at line 65 of file AlphabetUtility.hh.
Member Function Documentation
void Fsa::AlphabetMapping::del (LabelId from)
Add a mapping to delete a single label id.
Definition at line 67 of file AlphabetUtility.cc.
References Core::Vector< LabelId >::grow(), typeComplete, and typeIdentity.
Referenced by Fsa::mapAlphabet().
ConstAlphabetRef Fsa::AlphabetMapping::from () const inline
Returns
a reference to the alphabet from which to map
Definition at line 103 of file AlphabetUtility.hh.
Referenced by Fsa::mapAlphabet(), Ftl::mapInput(), Ftl::mapInputOutput(), and Ftl::mapOutput().
bool Fsa::AlphabetMapping::isModifyingType () const inline
Returns
true if this mapping requires an automaton to be modified. False if this is a trivial mapping where all label ids remain unchanged.
Definition at line 96 of file AlphabetUtility.hh.
Referenced by Fsa::mapAlphabet(), Ftl::mapInput(), Ftl::mapInputOutput(), and Ftl::mapOutput().
void Fsa::AlphabetMapping::map (LabelId from, LabelId to)
Add a mapping for a single label id.
Definition at line 58 of file AlphabetUtility.cc.
References Core::Vector< LabelId >::grow(), to(), typeIdentity, and typeUnmapped.
Referenced by Fsa::mapAlphabet(), and Ftl::ConcatUnionAutomaton< _Automaton >::uniteAlphabets().
const LabelId Fsa::AlphabetMapping::operator[] (LabelId i) const inline
Request the target label id for a source label id.
This method is aware of special label ids and does not map them.
Returns
the target label id
Definition at line 129 of file AlphabetUtility.hh.
References Fsa::mapAlphabet().
ConstAlphabetRef Fsa::AlphabetMapping::to () const inline
Returns
a reference to the alphabet to which we map
Definition at line 110 of file AlphabetUtility.hh.
Referenced by map(), Fsa::mapAlphabet(), Ftl::mapInput(), Ftl::mapInputOutput(), and Ftl::mapOutput().
Type Fsa::AlphabetMapping::type () const inline
Returns
the type of the mapping
Definition at line 87 of file AlphabetUtility.hh.
Referenced by Ftl::mapInput(), Ftl::mapInputOutput(), Ftl::mapOutput(), and Ftl::ConcatUnionAutomaton< _Automaton >::uniteAlphabets().
Friends And Related Function Documentation
void mapAlphabet (ConstAlphabetRef , ConstAlphabetRef , AlphabetMapping & , LabelId , u32) friend
Generally calculates the mapping between two alphabets.
Since alphabets match on symbol level, but algorithms work on integer labels only, mapping label ids between alphabets is a necessary step if two automata with different alphabets need to interact. Complexity: the complexity depends on the implementation of the underlying alphabets. In case of two static alphabets the worst-case complexity is O(|from| log |to|)
Parameters
from a reference to the alphabet to map from
to a reference to the alphabet to map to
mapping the resulting mapping (passed by reference to save overhead due to temporary object creation)
reportUnknowns maximum number of unknown symbols that should be reported
Definition at line 73 of file AlphabetUtility.cc.
Member Data Documentation
const Type Fsa::AlphabetMapping::typeComplete = 0x02 static
all symbols in FROM are also in TO
Definition at line 69 of file AlphabetUtility.hh.
Referenced by Fsa::countDisambiguators(), del(), and Ftl::ConcatUnionAutomaton< _Automaton >::uniteAlphabets().
const Type Fsa::AlphabetMapping::typeIdentity = 0x04 static
FROM and TO are identical (not just equal)
Definition at line 70 of file AlphabetUtility.hh.
Referenced by Fsa::countDisambiguators(), del(), map(), Fsa::mapAlphabet(), Ftl::mapInput(), Ftl::mapInputOutput(), and Ftl::mapOutput().
const Type Fsa::AlphabetMapping::typeUnmapped = 0x01 static
all symbols have the same index in FROM and TO
Definition at line 68 of file AlphabetUtility.hh.
Referenced by Fsa::countDisambiguators(), and map().
The documentation for this class was generated from the following files:
AlphabetUtility.hh
AlphabetUtility.cc