Sprint: Search::Wfst::FirstBestTraceRecorder Class Reference
Search::Wfst::FirstBestTraceRecorder Class Reference
storage of Trace objects used by ExpandingFsaSearch
#include <BookKeeping.hh>
Classes
struct Trace
Public Member Functions
FirstBestTraceRecorder (bool createLattice=false)
void setCreateLattice (bool create)
void clear ()
remove all trace objects
TraceRef addTrace (TraceRef sibling, TraceRef predecessor, OpenFst::Label output, const StateSequence *input, TimeframeIndex time, Score score, Score arcScore, bool wordEnd)
add a new trace
virtual void updateTime (TraceRef t, TimeframeIndex time)
Update the timestamp of the given trace object.
void purgeBegin ()
start purging process (reset all active flags)
void purgeEnd ()
remove all trace objects not labeled as active
void purgeNotify (TraceRef trace)
label the trace object and its predecessors as active (set active flag)
size_t memoryUsage () const
memory usage in bytes.
bool hasWordEndTime (const WordEndDetector &wordEnds, TraceRef end)
Check if the number of word boundary time stamps matches the number of output labels on the path ending in end.
void createBestPath (const WordEndDetector &wordEnds, bool ignoreLast, TraceRef end, BestPath *path)
Find the first best path ending in end.
Lattice * createLattice (TraceRef end)
Create a lattice.
Public Member Functions inherited from Search::Wfst::TraceRecorder
virtual void pruneBegin ()
start pruning process (for lattices only)
virtual void pruneEnd ()
finish pruning (for lattices only)
virtual void pruneNotify (TraceRef trace)
label the trace as currently active (for lattices only)
Protected Types
typedef OpenFst::Label Label
Private Types
typedef std::vector< Trace > TraceArray
Private Member Functions
void updateTrace (TraceRef sibling, TraceRef predecessor, Score score)
void purgeNotifyDfs (TraceRef trace)
void purgeNotifyLinear (TraceRef trace)
void enlarge ()
Private Attributes
TraceArray data_
TraceRef next_
bool createLattice_
Static Private Attributes
static const size_t incrementSize = 512
Additional Inherited Members
Public Types inherited from Search::Wfst::TraceRecorder
typedef u32 TraceRef
Static Public Attributes inherited from Search::Wfst::TraceRecorder
static const TraceRef InvalidTraceRef = -1
Detailed Description
storage of Trace objects used by ExpandingFsaSearch
free storage is organized using a linked list. trace.predecessor is used as pointer for list items
Definition at line 110 of file BookKeeping.hh.
Member Function Documentation
FirstBestTraceRecorder::TraceRef FirstBestTraceRecorder::addTrace (TraceRef sibling, TraceRef predecessor, OpenFst::Label output, const StateSequence * input, TimeframeIndex time, Score score, Score arcScore, bool wordEnd) virtual
add a new trace
Implements Search::Wfst::TraceRecorder.
Definition at line 28 of file BookKeeping.cc.
void FirstBestTraceRecorder::clear () virtual
remove all trace objects
Implements Search::Wfst::TraceRecorder.
Definition at line 23 of file BookKeeping.cc.
void FirstBestTraceRecorder::createBestPath (const WordEndDetector & wordEnds, bool ignoreLast, TraceRef end, BestPath * path) virtual
Find the first best path ending in end.
Implements Search::Wfst::TraceRecorder.
Definition at line 141 of file BookKeeping.cc.
Search::Wfst::Lattice * FirstBestTraceRecorder::createLattice (TraceRef) virtual
Create a lattice.
Implements Search::Wfst::TraceRecorder.
Definition at line 174 of file BookKeeping.cc.
References defect.
bool FirstBestTraceRecorder::hasWordEndTime (const WordEndDetector & wordEnds, TraceRef end) virtual
Check if the number of word boundary time stamps matches the number of output labels on the path ending in end.
Implements Search::Wfst::TraceRecorder.
Definition at line 127 of file BookKeeping.cc.
size_t Search::Wfst::FirstBestTraceRecorder::memoryUsage () const inline virtual
memory usage in bytes.
Reimplemented from Search::Wfst::TraceRecorder.
Definition at line 148 of file BookKeeping.hh.
References Search::Wfst::TraceRecorder::createBestPath(), Search::Wfst::TraceRecorder::createLattice(), and Search::Wfst::TraceRecorder::hasWordEndTime().
void FirstBestTraceRecorder::purgeBegin () virtual
start purging process (reset all active flags)
Reimplemented from Search::Wfst::TraceRecorder.
Definition at line 67 of file BookKeeping.cc.
void FirstBestTraceRecorder::purgeEnd () virtual
remove all trace objects not labeled as active
Reimplemented from Search::Wfst::TraceRecorder.
Definition at line 106 of file BookKeeping.cc.
void FirstBestTraceRecorder::purgeNotify (TraceRef trace) virtual
label the trace object and its predecessors as active (set active flag)
Reimplemented from Search::Wfst::TraceRecorder.
Definition at line 72 of file BookKeeping.cc.
void FirstBestTraceRecorder::updateTime (TraceRef t, TimeframeIndex time) virtual
Update the timestamp of the given trace object.
Implements Search::Wfst::TraceRecorder.
Definition at line 63 of file BookKeeping.cc.
The documentation for this class was generated from the following files:
BookKeeping.hh
BookKeeping.cc