Sprint: Core::TextInputStream Class Reference
Core::TextInputStream Class Reference
Stream for text input.
#include <TextStream.hh>
Classes
class Buffer
Public Member Functions
TextInputStream (std::istream *)
Create TextInputStream on top of an existing istream.
TextInputStream (const std::string &filename, int mode=0)
Open/create named file and construct a TextInputStream.
void adopt (std::istream *)
Set a new underlying istream.
void open (const std::string &filename, int mode=0)
Open/create named file.
void close ()
Close and delete underlying file or istream.
void setBufferSize (u32 s)
Limit amount of data to buffer internally.
void setPutBackBufferSize (u32 s)
Limit amount of data to put-back buffer internally.
const std::string & encoding () const
Character set encoding used in the external.
void setEncoding (const std::string &encoding=UnicodeInputConverter::defaultEncoding)
Change the character set encoding used in the external file.
bool good () const
operator bool () const
Private Member Functions
int getInputLine (std::string &) const
Private Attributes
Buffer * buffer_
std::istream * input_
Detailed Description
Stream for text input.
Use this for reading plain text files. For XML use XmlInputStream.
Features if TextInputStream:
word wrap
indentation
character set conversion Remember: all internal strings are considered UTF-8
TextInputStream redefines some ASCII control characters to control text formatting. Since these codes are old teletype legacy and have no use in modern computing environments, we should get away with this.
Definition at line 171 of file TextStream.hh.
Constructor & Destructor Documentation
TextInputStream::TextInputStream (std::istream * s) explicit
Create TextInputStream on top of an existing istream.
TextInputStream takes ownership of the istream passed, and will delete it.
Definition at line 483 of file TextStream.cc.
References setEncoding().
TextInputStream::TextInputStream (const std::string & filename, int mode = 0)
Open/create named file and construct a TextInputStream.
Definition at line 490 of file TextStream.cc.
References setEncoding().
Member Function Documentation
void TextInputStream::adopt (std::istream * i)
Set a new underlying istream.
TextInputStream takes ownership of the istream passed and will delete it.
Definition at line 498 of file TextStream.cc.
void TextInputStream::close ()
Close and delete underlying file or istream.
Definition at line 510 of file TextStream.cc.
Referenced by Speech::AlignmentDumpNode::work().
const std::string & TextInputStream::encoding () const
Character set encoding used in the external.
Definition at line 529 of file TextStream.cc.
void TextInputStream::open (const std::string & filename, int mode = 0)
Open/create named file.
Definition at line 504 of file TextStream.cc.
void TextInputStream::setBufferSize (u32 s)
Limit amount of data to buffer internally.
An argument of zero restores the default size.
Definition at line 516 of file TextStream.cc.
void TextInputStream::setEncoding (const std::string & encoding = UnicodeInputConverter::defaultEncoding)
Change the character set encoding used in the external file.
Remember, internal strings are expected to be UTF-8.
Definition at line 533 of file TextStream.cc.
References Core::getline().
Referenced by LmUtilityTool::main(), TextInputStream(), and Speech::AlignmentDumpNode::work().
void TextInputStream::setPutBackBufferSize (u32 s)
Limit amount of data to put-back buffer internally.
An argument of zero restores the default size.
Definition at line 520 of file TextStream.cc.
The documentation for this class was generated from the following files:
TextStream.hh
TextStream.cc