Sprint: Am::EmissionAlphabet Class Reference
Am::EmissionAlphabet Class Reference
Public Member Functions
EmissionAlphabet (Mm::MixtureIndex nMixtures=0)
Mm::MixtureIndex nMixtures () const
Fsa::LabelId nDisambiguators () const
Fsa::LabelId disambiguator (Fsa::LabelId d) const
virtual bool isDisambiguator (Fsa::LabelId m) const
Determine wether a symbol is a disambiguator (see determinize for more details on the use of disambiguators).
virtual const_iterator end () const
Returns an iterator pointing behind the last symbol.
virtual std::string symbol (Fsa::LabelId) const
Returns the string representation of a symbol.
virtual Fsa::LabelId index (const std::string &) const
Given a string representation of a symbol returns the label id.
virtual void writeXml (Core::XmlWriter &os) const
Write the alphabet to an XmlWriter.
EmissionAlphabet (Mm::MixtureIndex nMixtures=0)
Mm::MixtureIndex nMixtures () const
u32 nDisambiguators () const
Fsa::LabelId disambiguator (u32 d) const
virtual bool isDisambiguator (Fsa::LabelId m) const
Determine wether a symbol is a disambiguator (see determinize for more details on the use of disambiguators).
virtual const_iterator end () const
Returns an iterator pointing behind the last symbol.
virtual std::string symbol (Fsa::LabelId) const
Returns the string representation of a symbol.
virtual void writeXml (Core::XmlWriter &) const
Write the alphabet to an XmlWriter.
Public Member Functions inherited from Fsa::Alphabet
std::string specialSymbol (LabelId index) const
Retrieve a string representation of a special label id.
LabelId specialIndex (const std::string &symbol) const
Map a string representation of a special symbol to its label id.
virtual const_iterator begin () const
Returns an iterator pointing to the first symbol.
virtual LabelId next (LabelId id) const
Returns the label id of the next symbol in sequence.
virtual AlphabetTag tag (LabelId index) const
return symbol tag
virtual bool write (Core::BinaryOutputStream &o) const
Write the alphabet to BinaryOutputStream.
virtual size_t getMemoryUsed () const
Return the amount of memory used by this object.
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Private Attributes
Mm::MixtureIndex nMixtures_
Fsa::LabelId nDisambiguators_
u32 nDisambiguators_
Detailed Description
Definition at line 34 of file ClassicStateTying.hh.
Member Function Documentation
virtual const_iterator Am::EmissionAlphabet::end () const inline virtual
Returns an iterator pointing behind the last symbol.
This usually does not need to be overloaded except for the case you need a different internal representation of the end iterator. Currently, InvalidLabelId is being used as end iterator.
Returns
a const iterator pointing to the first symbol or end()
Reimplemented from Fsa::Alphabet.
Definition at line 53 of file StateModel.hh.
References index(), symbol(), and writeXml().
virtual const_iterator Am::EmissionAlphabet::end () const inline virtual
Returns an iterator pointing behind the last symbol.
This usually does not need to be overloaded except for the case you need a different internal representation of the end iterator. Currently, InvalidLabelId is being used as end iterator.
Returns
a const iterator pointing to the first symbol or end()
Reimplemented from Fsa::Alphabet.
Definition at line 56 of file ClassicStateTying.hh.
References index(), symbol(), and writeXml().
Fsa::LabelId Am::EmissionAlphabet::index (const std::string & symbol) const virtual
Given a string representation of a symbol returns the label id.
Parameters
symbol the string representation of a symbol
Returns
the label id of the symbol or InvalidLabelId if the string represents no valid symbol
Reimplemented from Fsa::Alphabet.
Definition at line 37 of file ClassicStateTying.cc.
References Fsa::Alphabet::specialIndex().
Referenced by Am::ClassicStateTying::createClassicStateTyingRef(), and end().
virtual bool Am::EmissionAlphabet::isDisambiguator (Fsa::LabelId index) const inline virtual
Determine wether a symbol is a disambiguator (see determinize for more details on the use of disambiguators).
Parameters
index the symbol's label id
Returns
true if the symbol is a disambiguator.
Reimplemented from Fsa::Alphabet.
Definition at line 49 of file StateModel.hh.
virtual bool Am::EmissionAlphabet::isDisambiguator (Fsa::LabelId index) const inline virtual
Determine wether a symbol is a disambiguator (see determinize for more details on the use of disambiguators).
Parameters
index the symbol's label id
Returns
true if the symbol is a disambiguator.
Reimplemented from Fsa::Alphabet.
Definition at line 53 of file ClassicStateTying.hh.
virtual std::string Am::EmissionAlphabet::symbol (Fsa::LabelId index) const virtual
Returns the string representation of a symbol.
Parameters
index the symbol's label id
Returns
the string representation of the symbol or an empty string if there is no symbol with that label id
Implements Fsa::Alphabet.
std::string Am::EmissionAlphabet::symbol (Fsa::LabelId index) const virtual
Returns the string representation of a symbol.
Parameters
index the symbol's label id
Returns
the string representation of the symbol or an empty string if there is no symbol with that label id
Implements Fsa::Alphabet.
Definition at line 26 of file ClassicStateTying.cc.
References Fsa::Alphabet::specialSymbol().
Referenced by end(), and Am::AllophoneStateAlphabet::next().
virtual void Am::EmissionAlphabet::writeXml (Core::XmlWriter & o) const virtual
Write the alphabet to an XmlWriter.
Parameters
o the XmlWriter
Returns
true if the operation was successfull for all symbols, false otherwise
Reimplemented from Fsa::Alphabet.
void Am::EmissionAlphabet::writeXml (Core::XmlWriter & o) const virtual
Write the alphabet to an XmlWriter.
Parameters
o the XmlWriter
Returns
true if the operation was successfull for all symbols, false otherwise
Reimplemented from Fsa::Alphabet.
Definition at line 53 of file ClassicStateTying.cc.
Referenced by end(), and Am::AllophoneStateAlphabet::next().
The documentation for this class was generated from the following files:
ClassicStateTying.hh
StateModel.hh
ClassicStateTying.cc