Sprint: Math::CudaMatrix< T > Class Template Reference
Math::CudaMatrix< T > Class Template Reference
Public Types
typedef T value_type
typedef T * iterator
typedef const T * const_iterator
Public Member Functions
CudaMatrix (u32 nRows=0, u32 nColumns=0)
CudaMatrix (const CudaMatrix< T > &X)
void initComputation (bool sync=true) const
void finishComputation (bool sync=true) const
bool isComputing () const
bool isInGpuMode () const
void print (std::ostream &os) const
void printToFile (const std::string &filename) const
void show ()
void syncAndShow ()
void clear ()
void write (Core::XmlWriter &os) const
T * d_elem ()
T * elem ()
void resize (u32 nRows, u32 nColumns, bool minimalSize=false)
void hostRegister ()
template<typename S >
void copyStructure (const CudaMatrix< S > &X)
u32 nRows () const
u32 nColumns () const
bool empty () const
bool isFinite () const
u32 size () const
void fill (T value)
void ensureMinimalValue (const T threshold)
T & at (u32 i, u32 j)
const T & at (u32 i, u32 j) const
void getRow (u32 rowIndex, Math::CudaVector< T > &row) const
void getColumn (u32 columnIndex, Math::CudaVector< T > &vec) const
void setColumn (u32 columnIndex, Math::CudaVector< T > &vec) const
void copyBlockFromMatrix (const Math::FastMatrix< T > &X, u32 rowIndexX, u32 colIndexX, u32 thisRowIndex, u32 thisColIndex, u32 nRows, u32 nCols=1)
void copyBlockFromMatrix (const Math::CudaMatrix< T > &X, u32 rowIndexX, u32 colIndexX, u32 thisRowIndex, u32 thisColIndex, u32 nRows, u32 nCols=1)
void copyToMatrix (Math::FastMatrix< T > &X) const
void copyToMatrix (Math::CudaMatrix< T > &X) const
Math::FastMatrix< T > & asWritableCpuMatrix ()
void setToZero ()
void setToZeroAsync (int stream=0)
T & operator() (s32 row, s32 column)
const T & operator() (s32 row, s32 column) const
CudaMatrix< T > & operator= (CudaMatrix< T > X)
void swap (CudaMatrix< T > &X)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
template<typename S >
void add (const CudaMatrix< S > &X, S alpha=1.0)
T l1norm () const
T sumOfSquares () const
T dot (const CudaMatrix< T > &X) const
void scale (T alpha)
template<typename S >
void copy (const CudaMatrix< S > &X)
template<typename S >
void copy (const FastMatrix< S > &matrix)
void copy (const T *X, u32 rowOffset=0, u32 colOffset=0)
template<typename S >
void copy (const Matrix< S > &matrix)
void copy (const std::vector< T > &X, u32 rowOffset=0, u32 colOffset=0)
void copySelectedRowsOfMatrixIntoColumns (const CudaMatrix< T > &matrix, const CudaMatrix< T > &x)
template<typename S >
void convert (Matrix< S > &matrix) const
void multiply (const CudaVector< T > &x, CudaVector< T > &y, bool transposed=false, T alpha=1.0, T beta=0.0, u32 lda=0) const
void addOuterProduct (const CudaVector< T > &x, const CudaVector< T > &y, T alpha, u32 lda=0)
template<typename S >
void addMatrixProduct (const CudaMatrix< S > &matrixA, const CudaMatrix< S > &matrixB, T scaleC=0, S scaleA=1, bool transposedA=false, bool transposedB=false)
matrix multiplication
int gemm (bool transposedA, bool transposedB, int m, int n, int k, T scaleA, const T *A, int lda, const T *B, int ldb, T scaleC, T *C, int ldc)
void sigmoid (T gamma=1.0)
void logSigmoid (T gamma=1.0)
void softmax ()
template<typename S >
void maxoutvar (const CudaVector< S > &mixture, const CudaVector< S > &offset, const CudaMatrix< T > &inputMatrix, CudaMatrix< S > &maxIndexOutputMatrix)
template<typename S >
void maxoutErrorExpand (const CudaVector< S > &mixture, const CudaVector< S > &offset, const CudaMatrix< S > &maxIndex, const CudaMatrix< T > &input)
void elementwiseMultiplicationWithSigmoidDerivative (const CudaMatrix< T > &X)
void elementwiseMultiplicationWithTanhDerivative (const CudaMatrix< T > &X)
void multiplicationWithSoftmaxDerivative (const CudaMatrix< T > &softmax)
void elementwiseMultiplicationWithRectifiedDerivative (const CudaMatrix< T > &X)
template<typename S >
void addKroneckerDelta (const CudaVector< S > &alignment, const T scale=1.0)
template<typename S , typename U >
void addKroneckerDelta (const CudaVector< S > &alignment, const CudaVector< U > &offset, const CudaMatrix< U > &maxIndex, const T scale=1.0)
template<typename S >
u32 nClassificationErrors (const CudaVector< S > &alignment)
template<typename S >
T crossEntropyObjectiveFunction (const CudaVector< S > &alignment)
template<typename S >
T weightedCrossEntropyObjectiveFunction (const CudaVector< S > &alignment, const CudaVector< T > &weights)
template<typename S >
T squaredErrorObjectiveFunction (const CudaVector< S > &alignment)
template<typename S >
T weightedSquaredErrorObjectiveFunction (const CudaVector< S > &alignment, const CudaVector< T > &weights)
template<typename S >
T binaryDivergenceObjectiveFunction (const CudaVector< S > &alignment)
template<typename S >
T weightedBinaryDivergenceObjectiveFunction (const CudaVector< S > &alignment, const CudaVector< T > &weights)
void binaryDivergenceSoftmaxGradient (const CudaMatrix< T > &Y, const CudaVector< u32 > &A)
T dotWithColumn (const CudaMatrix< T > &X, u32 thisColumnIndex) const
void setToSecondOrderFeatures (const CudaMatrix< T > &X)
void setToThirdOrderFeatures (const CudaMatrix< T > &X)
void dropout (const T dropoutProbability)
void addGaussianNoise (const T standardDeviation)
void l1clipping (const T value)
void clip (const T maxAbsValue)
void tanh ()
void exp ()
void log ()
void pow (T exponent)
u32 argAbsMax (u32 column)
void elementwiseMultiplication (const CudaMatrix< T > &X)
void elementwiseDivision (const CudaMatrix< T > &X)
void addConstantElementwise (T c)
void addToAllColumns (const CudaVector< T > &v, T alpha=1.0)
void addToAllColumnsWithOffset (const CudaVector< T > &v, u32 offset, T alpha=1.0)
template<typename S >
void expandAddToAllColumns (const CudaVector< S > &mixture, const CudaVector< S > &offset, const CudaVector< T > &v, T alpha)
void addToAllRows (const CudaVector< T > &v, T alpha=1.0)
void addWithColumnWeights (const CudaMatrix< T > &X, const CudaVector< T > &v)
void multiplyColumnsByScalars (const CudaVector< T > &scalars)
void divideColumnsByScalars (const CudaVector< T > &scalars)
void multiplyRowsByScalars (const CudaVector< T > &scalars)
void divideRowsByScalars (const CudaVector< T > &scalars)
void sign (const CudaMatrix< T > &X)
void addPoolingMax (const CudaMatrix< T > &input, CudaMatrix< u32 > &argmax, u32 poolingSize, bool poolingAbs)
void backpropPoolingMax (const CudaMatrix< u32 > &argmax, const CudaMatrix< T > &error)
void addPoolingPnorm (const CudaMatrix< T > &input, u32 poolingSize, u32 pnorm)
void backpropPoolingPnorm (const CudaMatrix< T > &error, u32 poolingSize, u32 pnorm)
void poolingRearrange (const CudaMatrix< T > &input, u32 numfilters, u32 dim)
void poolingSmooth (const CudaMatrix< T > &input, u32 len, u32 wintype)
void poolingSubsample (const CudaMatrix< T > &input, u32 vert, u32 hor)
void convInitPatchIndices (s32 input_height, s32 input_width, s32 filter_height, s32 filter_width, s32 num_input_streams, s32 filter_stride_vert)
void convExtractPatches (const CudaMatrix< T > &input, const CudaMatrix< s32 > &patchIdx, CudaMatrix< s32 > &inverse_patches, s32 num_streams)
void convRestoreFromPatches (const CudaMatrix< T > &warped_error, const CudaMatrix< s32 > &patchIdx, CudaMatrix< s32 > &inverse_patches, s32 num_input_elems)
void convUnwarpFrames (const CudaMatrix< T > &output_warped, const CudaVector< T > &bias, u32 filter_num, u32 shifts_num, u32 input_frames)
void convWarpFrames (const CudaMatrix< T > &error_unwarped, u32 filter_num, u32 shifts_num)
void elu (T alpha)
void elementwiseMultiplicationWithEluDerivative (const CudaMatrix< T > &X, T alpha)
template<>
void copy (const CudaMatrix< double > &X)
template<>
void copy (const CudaMatrix< float > &X)
template<>
void copy (const CudaMatrix< float > &X)
template<>
void addMatrixProduct (const CudaMatrix< float > &matrixA, const CudaMatrix< float > &matrixB, double scaleC, float scaleA, bool transposedA, bool transposedB)
Public Member Functions inherited from Math::CudaDataStructure
CudaDataStructure (const CudaDataStructure &x)
Protected Attributes
bool isComputing_
T * d_elem_
u32 gpuCapacity_
Protected Attributes inherited from Math::FastMatrix< T >
u32 nRows_
u32 nColumns_
T * elem_
u32 capacity_
s32 nThreads_
Protected Attributes inherited from Math::CudaDataStructure
const bool gpuMode_
Private Types
typedef FastMatrix< T > Precursor
Private Member Functions
bool allocateGpuMemory (bool minimalSize=false)
void appendSecondOrderFeatures (const FastMatrix< T > &X, u32 offset)
Static Private Member Functions
template<typename S >
static void _gemm (bool transposedA, bool transposedB, int M, int N, int K, S scaleA, const S *A, int lda, const S *B, int ldb, T scaleC, T *C, int ldc)
Private Attributes
T * bufferClassificationErrors_
size_t bufferClassificationErrorsSize_
std::map< int, cudaStream_t * > streamPool_
std::map< int, cublasHandle_t * > cublasHandlePool_
Friends
class CudaVector< T >
class CudaVector< double >
class CudaVector< float >
class CudaVector< u32 >
class CudaMatrix< double >
class CudaMatrix< float >
Additional Inherited Members
Static Public Member Functions inherited from Math::CudaDataStructure
static u32 getMultiprecisionBunchSize ()
static void setMultiprecisionBunchSize (u32 val)
static bool hasGpu ()
static int getActiveGpu ()
Protected Types inherited from Math::FastMatrix< T >
typedef T value_type
typedef T * iterator
typedef const T * const_iterator
Protected Member Functions inherited from Math::FastMatrix< T >
s32 getNumberOfThreads ()
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
FastMatrix (u32 nRows=0, u32 nColumns=0)
FastMatrix (const FastMatrix< T > &X)
FastMatrix (const FastMatrix< T > &X, u32 rowIndexX, u32 colIndexX, u32 thisRowIndex, u32 thisColIndex, u32 nRows, u32 nCols)
T & operator() (u32 row, u32 column)
T const & operator() (u32 row, u32 column) const
void clear ()
void swap (FastMatrix< T > &X)
void setNumberOfThreads (int nThreads)
FastMatrix< T > & operator= (FastMatrix< T > X)
void resize (u32 nRows, u32 nColumns, bool minimalSize=false)
void resizeRowsAndKeepContent (u32 nRows)
void resizeColsAndKeepContent (u32 nColumns, bool minimalSize=false, bool efficientSize=true)
void removeColumn (u32 column)
template<typename S >
void copyStructure (const FastMatrix< S > &X)
u32 nRows () const
template<typename S >
void copy (const FastMatrix< S > &X)
template<typename S >
void copy (const S *X, u32 rowOffset=0, u32 colOffset=0)
template<typename S >
void copy (const Matrix< S > &matrix)
template<typename S >
void copy (const std::vector< S > &X, u32 rowOffset=0, u32 colOffset=0)
void copySelectedRowsOfMatrixIntoColumns (const FastMatrix< T > &matrix, const FastMatrix< T > &x)
template<typename S >
void convert (Matrix< S > &matrix) const
u32 nColumns () const
bool empty () const
bool isFinite () const
u32 size () const
void fill (T value)
void ensureMinimalValue (const T threshold)
T & at (u32 i, u32 j)
const T & at (u32 i, u32 j) const
void write (Core::BinaryOutputStream &o) const
void read (Core::BinaryInputStream &i)
void print (std::ostream &os) const
void printToFile (const std::string &filename) const
void show () const
void getRow (u32 rowIndex, Math::FastVector< T > &row) const
void getColumn (u32 columnIndex, Math::FastVector< T > &column) const
void copyBlockFromMatrix (const Math::FastMatrix< T > &X, u32 rowIndexX, u32 colIndexX, u32 thisRowIndex, u32 thisColIndex, u32 nRows, u32 nCols=1)
void setToZero ()
template<typename S >
void add (const FastMatrix< S > &X, S alpha=1.0)
T l1norm () const
T sumOfSquares () const
T dot (const FastMatrix< T > &X) const
void scale (T alpha)
void multiply (const FastVector< T > &x, FastVector< T > &y, bool transposed=false, T alpha=1.0, T beta=0.0, u32 lda=0) const
void addOuterProduct (const FastVector< T > &x, const FastVector< T > &y, T alpha, u32 lda=0)
template<typename S >
void addMatrixProduct (const FastMatrix< S > &matrixA, const FastMatrix< S > &matrixB, T scaleC=0, S scaleA=1, bool transposeA=false, bool transposeB=false)
template<typename S >
void gemm (bool transposedA, bool transposedB, int M, int N, int K, S scaleA, const S *matrixA, int lda, const S *matrixB, int ldb, T scaleC, T *matrixC, int ldc)
void sigmoid (T gamma=1.0)
void logSigmoid (T gamma=1.0)
void softmax ()
template<typename S >
void maxoutvar (const FastVector< S > &mixture, const FastVector< S > &offset, const FastMatrix< T > &input, FastMatrix< S > &maxIndexOutputMatrix)
template<typename S >
void maxoutErrorExpand (const FastVector< S > &mixture, const FastVector< S > &offset, const FastMatrix< S > &maxIndex, const FastMatrix< T > &input)
void elementwiseMultiplicationWithSigmoidDerivative (const FastMatrix< T > &X)
void elementwiseMultiplicationWithTanhDerivative (const FastMatrix< T > &X)
void multiplicationWithSoftmaxDerivative (const FastMatrix< T > &softmax)
void elementwiseMultiplicationWithRectifiedDerivative (const FastMatrix< T > &X)
template<typename S >
void addKroneckerDelta (const FastVector< S > &alignment, const T scale=1.0)
template<typename S , typename U >
void addKroneckerDelta (const FastVector< S > &alignment, const FastVector< U > &offset, const FastMatrix< U > &maxIndex, const T scale=1.0)
template<typename S >
u32 nClassificationErrors (const FastVector< S > &alignment)
template<typename S >
T crossEntropyObjectiveFunction (const FastVector< S > &alignment)
template<typename S >
T weightedCrossEntropyObjectiveFunction (const FastVector< S > &alignment, const FastVector< T > &weights)
template<typename S >
T squaredErrorObjectiveFunction (const FastVector< S > &alignment)
template<typename S >
T weightedSquaredErrorObjectiveFunction (const FastVector< S > &alignment, const FastVector< T > &weights)
template<typename S >
T binaryDivergenceObjectiveFunction (const FastVector< S > &alignment)
template<typename S >
T weightedBinaryDivergenceObjectiveFunction (const FastVector< S > &alignment, const FastVector< T > &weights)
template<typename S >
void binaryDivergenceSoftmaxGradient (const FastMatrix< T > &Y, const FastVector< S > &A)
T dotWithColumn (const FastMatrix< T > &X, u32 thisColumnIndex) const
void setToSecondOrderFeatures (const FastMatrix< T > &X)
void setToThirdOrderFeatures (const FastMatrix< T > &X)
void dropout (const T dropoutProbability)
void addGaussianNoise (const T standardDeviation)
void l1clipping (const T value)
void clip (const T maxAbsValue)
void tanh ()
void exp ()
void log ()
void pow (T exp)
u32 argAbsMax (u32 column) const
u32 argMax (u32 column) const
void elementwiseMultiplication (const FastMatrix< T > &X)
void elementwiseDivision (const FastMatrix< T > &X)
void addConstantElementwise (T c)
void addToAllColumns (const FastVector< T > &v, T alpha=1.0)
void addToAllColumnsWithOffset (const FastVector< T > &v, u32 offset, T alpha=1.0)
template<typename S >
void expandAddToAllColumns (const FastVector< S > &mixture, const FastVector< S > &offset, const FastVector< T > &v, T alpha)
void addToAllRows (const FastVector< T > &v, T alpha=1.0)
void addWithColumnWeights (const FastMatrix< T > &X, const FastVector< T > &v)
void multiplyColumnsByScalars (const FastVector< T > &scalars)
void divideColumnsByScalars (const FastVector< T > &scalars)
void multiplyRowsByScalars (const FastVector< T > &scalars)
void divideRowsByScalars (const FastVector< T > &scalars)
void addPoolingMax (const FastMatrix< T > &input, FastMatrix< u32 > &argmax, u32 poolingSize, bool poolingAbs)
void addPoolingPnorm (const FastMatrix< T > &input, u32 poolingSize, u32 pnorm)
void convExtractPatches (const FastMatrix< T > &input, const FastMatrix< s32 > &patchIdx, FastMatrix< s32 > &inverse_patches)
void convUnwarpFrames (const FastMatrix< T > &output_warped, const FastVector< T > &bias, u32 shifts_num)
void elu (T)
void elementwiseMultiplicationWithEluDerivative (const FastMatrix< T > &X)
Protected Member Functions inherited from Math::CudaDataStructure
CudaDataStructure (const CudaDataStructure &x)
Static Protected Member Functions inherited from Math::FastMatrix< T >
static s32 initialize ()
Static Protected Member Functions inherited from Math::CudaDataStructure
static void initialize ()
static void log (const std::string &msg)
static void warning (const std::string &msg)
static void error (const std::string &msg)
static void criticalError (const std::string &msg)
static u32 getMultiprecisionBunchSize ()
static void setMultiprecisionBunchSize (u32 val)
static bool hasGpu ()
static int getActiveGpu ()
Static Protected Attributes inherited from Math::FastMatrix< T >
static bool initialized = false
static s32 maxThreads = 1
Static Protected Attributes inherited from Math::CudaDataStructure
static cublasHandle_t cublasHandle
static curandGenerator_t randomNumberGenerator
static u32 multiPrecisionBunchSize = 8
Detailed Description
template<typename T>
class Math::CudaMatrix< T >
Definition at line 54 of file CudaMatrix.hh.
Member Function Documentation
template<typename T > template<typename S > void Math::CudaMatrix< T >::addMatrixProduct (const CudaMatrix< S > & matrixA, const CudaMatrix< S > & matrixB, T scaleC = 0, S scaleA = 1, bool transposedA = false, bool transposedB = false)
matrix multiplication
interface supports multi-precision for the case with unique precision: use CUBLAS directly multi-precision case: work-around: convert single-precision matrices to double and use CUBLAS double precision routine
Definition at line 1730 of file CudaMatrix.hh.
References Core::Component::error(), require, and Core::Application::us().
Referenced by Nn::LinearLayer< T >::_forward().
The documentation for this class was generated from the following file:
CudaMatrix.hh