Sprint: CorpusVisitor Class Reference
CorpusVisitor Class Reference
Copyright 2020 RWTH Aachen University.
Public Member Functions
CorpusVisitor (const Core::Configuration &)
virtual void enterRecording (Bliss::Recording *)
Template method called when corpus traversal enters a recording.
Public Member Functions inherited from Bliss::CompositeCorpusStatisticsVisitor
CompositeCorpusStatisticsVisitor (const Core::Configuration &)
void add (CorpusStatisticsVisitor *)
virtual void leaveRecording (Recording *)
Template method called when corpus traversal leaves a recording.
virtual void visitSegment (Segment *)
Template method for processing segments.
virtual void visitSpeechSegment (SpeechSegment *)
Template method for processing speech segments.
virtual void reset ()
virtual void writeReport (Core::XmlWriter &) const
Public Member Functions inherited from Bliss::CorpusStatisticsVisitor
CorpusStatisticsVisitor (const Core::Configuration &c)
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Bliss::CorpusVisitor
virtual void enterCorpus (Corpus *)
Template method notifying start of a (sub-) corpus.
virtual void leaveCorpus (Corpus *)
Template method notifying end of a (sub-) corpus.
Static Public Attributes
static const Core::ParameterBool paramEvaluateRecordings
Private Types
typedef Bliss::CompositeCorpusStatisticsVisitor Precursor
Private Member Functions
void correctDuration (Bliss::Segment *)
Private Attributes
Flow::Network * extraction_
Flow::PortId dataPort_
Core::Channel recordingsChannel_
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Copyright 2020 RWTH Aachen University.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Definition at line 31 of file Costa.cc.
Member Function Documentation
void CorpusVisitor::enterRecording (Bliss::Recording *) virtual
Template method called when corpus traversal enters a recording.
Implement this to take appropriate actions, e.g. opening the audio file.
Reimplemented from Bliss::CompositeCorpusStatisticsVisitor.
Definition at line 65 of file Costa.cc.
References Bliss::CompositeCorpusStatisticsVisitor::enterRecording(), Flow::Network::getAttribute(), and Flow::Network::setParameter().
The documentation for this class was generated from the following file:
Costa.cc