Sprint: BisonParser::position Class Reference
BisonParser::position Class Reference
Abstract a position.
#include <position.hh>
Public Member Functions
position (std::string *f=YY_NULLPTR, unsigned int l=1u, unsigned int c=1u)
Construct a position.
void initialize (std::string *fn=YY_NULLPTR, unsigned int l=1u, unsigned int c=1u)
Initialization.
Line and Column related manipulators
void lines (int count=1)
(line related) Advance to the COUNT next lines.
void columns (int count=1)
(column related) Advance to the COUNT next columns.
Public Attributes
std::string * filename
File name to which this position refers.
unsigned int line
Current line number.
unsigned int column
Current column number.
Static Private Member Functions
static unsigned int add_ (unsigned int lhs, int rhs, unsigned int min)
Compute max(min, lhs+rhs) (provided min <= lhs).
Detailed Description
Abstract a position.
Definition at line 57 of file position.hh.
Constructor & Destructor Documentation
BisonParser::position::position (std::string * f = YY_NULLPTR, unsigned int l = 1u, unsigned int c = 1u) inline explicit
Construct a position.
Definition at line 61 of file position.hh.
Member Function Documentation
static unsigned int BisonParser::position::add_ (unsigned int lhs, int rhs, unsigned int min) inline static private
Compute max(min, lhs+rhs) (provided min <= lhs).
Definition at line 109 of file position.hh.
Referenced by columns(), and lines().
void BisonParser::position::columns (int count = 1) inline
(column related) Advance to the COUNT next columns.
Definition at line 94 of file position.hh.
References add_(), and column.
Referenced by BisonParser::operator+=().
void BisonParser::position::initialize (std::string * fn = YY_NULLPTR, unsigned int l = 1u, unsigned int c = 1u) inline
Initialization.
Definition at line 72 of file position.hh.
References column, filename, and line.
Referenced by BisonParser::location::initialize().
void BisonParser::position::lines (int count = 1) inline
(line related) Advance to the COUNT next lines.
Definition at line 84 of file position.hh.
References add_(), column, and line.
Referenced by BisonParser::location::lines().
Member Data Documentation
unsigned int BisonParser::position::column
Current column number.
Definition at line 105 of file position.hh.
Referenced by columns(), initialize(), lines(), BisonParser::operator<<(), and BisonParser::operator==().
std::string* BisonParser::position::filename
File name to which this position refers.
Definition at line 101 of file position.hh.
Referenced by initialize(), BisonParser::operator<<(), and BisonParser::operator==().
unsigned int BisonParser::position::line
Current line number.
Definition at line 103 of file position.hh.
Referenced by initialize(), lines(), and BisonParser::operator==().
The documentation for this class was generated from the following file:
position.hh