Sprint: Mm::Covariance Class Reference
Mm::Covariance Class Reference abstract
Interface class for covariance implementations.
#include <GaussDensity.hh>
Public Member Functions
virtual const std::vector< VarianceType > & diagonal () const =0
Returns diagonal of covariance.
virtual const std::vector< f64 > & weights () const =0
Returns weights of the features.
virtual void setFeatureWeights (const std::vector< f64 > &w)=0
set weights of the features.
virtual Score halfeLogNormFactor () const
1 / 2 { N * log(2 * pi) + log(determinant) }.
virtual Covariance * clone () const =0
virtual void setOffset (ComponentIndex offset)
virtual void setDimension (ComponentIndex size)=0
virtual ComponentIndex dimension () const =0
virtual bool isPositiveDefinite () const =0
virtual bool write (std::ostream &o) const
print/scan methods for std::iostreams used in operator<< resp.
virtual bool read (std::istream &i)
Detailed Description
Interface class for covariance implementations.
Definition at line 96 of file GaussDensity.hh.
Member Function Documentation
virtual const std::vector<VarianceType>& Mm::Covariance::diagonal () const pure virtual
Returns diagonal of covariance.
Remark: output type is const reference for the moment, might need to get changed.
Implemented in Mm::DiagonalCovariance.
Referenced by Mm::ConvertCovarianceEstimator::ConvertCovarianceEstimator(), Mm::DiscriminativeCovarianceEstimator::DiscriminativeCovarianceEstimator(), and Mm::ISmoothingCovarianceEstimator::ISmoothingCovarianceEstimator().
virtual Score Mm::Covariance::halfeLogNormFactor () const inline virtual
1 / 2 { N * log(2 * pi) + log(determinant) }.
Remark: default implementation uses only the diagonal elements.
Definition at line 117 of file GaussDensity.hh.
References Mm::gaussLogNormFactor(), and verify.
virtual void Mm::Covariance::setFeatureWeights (const std::vector< f64 > & w) pure virtual
set weights of the features.
Implemented in Mm::DiagonalCovariance.
virtual const std::vector<f64>& Mm::Covariance::weights () const pure virtual
Returns weights of the features.
Implemented in Mm::DiagonalCovariance.
virtual bool Mm::Covariance::write (std::ostream & o) const inline virtual
print/scan methods for std::iostreams used in operator<< resp.
operator>> overwrite these methodes in inherited classes
Reimplemented in Mm::DiagonalCovariance.
Definition at line 133 of file GaussDensity.hh.
References Core::Component::error(), Core::Application::us(), and write().
Referenced by write().
The documentation for this class was generated from the following file:
GaussDensity.hh