Sprint: Math::Vector< T, P > Class Template Reference
Math::Vector< T, P > Class Template Reference
Public Member Functions
Vector (size_t n, const T &value)
Vector (size_t n)
Vector (const Vector< T > &x)
Vector (const std::vector< T > &x)
template<typename S >
Vector (const std::vector< S > &x)
Vector (typename std::vector< T >::const_iterator first, typename std::vector< T >::const_iterator last)
T & operator[] (size_t n)
const T & operator[] (size_t n) const
T operator* (const Vector< T > &r) const
Inner product of two vectors (dot product).
const Vector< T, P > operator* (const T value) const
Vector< T, P > & operator*= (const T weight)
const Vector< T, P > operator+ (const Vector< T > &r) const
Vector< T, P > & operator+= (const Vector< T > &r)
const Vector< T, P > operator+ (const T value) const
Vector< T, P > & operator+= (const T value)
const Vector< T, P > operator- (const Vector< T > &r) const
Vector< T, P > & operator-= (const Vector< T > &r)
const Vector< T, P > operator- (const T value) const
Vector< T, P > & operator-= (const T value)
const Vector< T, P > operator/ (const T value) const
Vector< T, P > & operator/= (const T value)
void squareVector (const Vector< T > &r)
T logSum ()
void exponent ()
Vector< T, P > & takeReciprocal ()
For each element x = 1 / x.
Vector< T, P > & takeReciprocal (T zeroTolerance)
For each element x = 1 / x.
Vector< T, P > & takeSquareRoot ()
For each element x = sqrt(x).
Vector< T, P > & takeSquareRoot (T zeroTolerance)
For each element x = sqrt(x).
void permuteElements (const std::vector< size_t > &permutation)
void normalize (T norm=1, f32 p=2)
void print (std::ostream &os) const
void print_raw (std::ostream &os) const
bool write (Core::BinaryOutputStream &o) const
bool read (Core::BinaryInputStream &i)
bool read (std::istream &is)
Detailed Description
template<typename T, class P = VectorRangeCheckOffPolicy>
class Math::Vector< T, P >
Definition at line 51 of file Math/Vector.hh.
Member Function Documentation
template<typename T, class P = VectorRangeCheckOffPolicy> T Math::Vector< T, P >::operator* (const Vector< T > & r) const inline
Inner product of two vectors (dot product).
Definition at line 95 of file Math/Vector.hh.
template<typename T, class P = VectorRangeCheckOffPolicy> Vector<T, P>& Math::Vector< T, P >::takeReciprocal () inline
For each element x = 1 / x.
Definition at line 212 of file Math/Vector.hh.
Referenced by Math::EigenvalueProblem::normalizeDiagonal(), Signal::EigenTransform::work(), and Signal::ScatterTransform::writeScatterMatrix().
template<typename T, class P = VectorRangeCheckOffPolicy> Vector<T, P>& Math::Vector< T, P >::takeReciprocal (T zeroTolerance) inline
For each element x = 1 / x.
Elements |x| < zeroTolerance are set to 1.
Definition at line 222 of file Math/Vector.hh.
template<typename T, class P = VectorRangeCheckOffPolicy> Vector<T, P>& Math::Vector< T, P >::takeSquareRoot () inline
For each element x = sqrt(x).
Definition at line 236 of file Math/Vector.hh.
Referenced by Math::EigenvalueProblem::normalizeDiagonal(), Signal::EigenTransform::work(), and Signal::ScatterTransform::writeScatterMatrix().
template<typename T, class P = VectorRangeCheckOffPolicy> Vector<T, P>& Math::Vector< T, P >::takeSquareRoot (T zeroTolerance) inline
For each element x = sqrt(x).
Elements |x| < zeroTolerance are set to 0.
Definition at line 246 of file Math/Vector.hh.
The documentation for this class was generated from the following file:
Math/Vector.hh