Sprint: Math::EigenvalueProblem Class Reference
Math::EigenvalueProblem Class Reference abstract
Base class for eigenvalue problems.
#include <EigenvalueProblem.hh>
Public Types
enum Type { typeGeneral, typeSymmetric, typeSymmetricPositiveDefinite }
typedef f64 ValueType
Public Member Functions
EigenvalueProblem (const Core::Configuration &)
virtual bool solveSymmetric (const Matrix< ValueType > &a, Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)=0
Interface function for symmetric eigenvalue problem.
bool solveSymmetricAndFinalize (const Matrix< ValueType > &a, Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)
Solves the symmetric eigenvalue problem and performs finalization of results.
bool finalize (const Matrix< ValueType > &a, Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)
Performs final processing and verifications.
bool finalizeEigenvaluesAndVectors (const Matrix< ValueType > &a, Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)
Performs final processing of eigenvalues and eigenvectors.
bool isCorrectSolution (const Matrix< ValueType > &a, const Vector< ValueType > &eigenvalues, const Matrix< ValueType > &eigenvectors)
Verifies if eigenvectors and eigenvalues satisfy A*X = Lambda*B*X.
void sortEigenvalues (Vector< ValueType > &eigenvalues, Matrix< ValueType > &eigenvectors)
Sorts eigenvalues in descending order.
bool real (const Vector< std::complex< ValueType >> &, Vector< ValueType > &)
Extracts real part of the input vector.
bool real (const Matrix< std::complex< ValueType >> &, Matrix< ValueType > &)
Extracts real part of the input matrix.
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Attributes
static const Core::Choice choiceType
static const Core::ParameterChoice paramType
Protected Member Functions
bool areEqual (const Matrix< ValueType > &x, const Matrix< ValueType > &y)
bool normalizeDiagonal (const Matrix< ValueType > &a, Matrix< ValueType > &eigenvectors)
Eigenvectors are scaled so that eigenvector^T * A * eigenvector = I.
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Private Types
enum EigenvectorNormalizationType { nonEigenvectorNormalization, unityLength, unityDiagonal }
Normalization type eigenvectors.
enum EigenvalueSortType { noSort, decreasing, increasing }
Private Attributes
EigenvectorNormalizationType eigenvectorNormalizationType_
ValueType diagonalNormalizationTolerance_
ValueType relativeImaginaryMaximum_
ValueType verificationTolerance_
EigenvalueSortType eigenvalueSortType_
Static Private Attributes
static const Core::Choice choiceEigenvectorNormalizationType
static const Core::ParameterChoice paramEigenvectorNormalization
static const Core::ParameterFloat paramDiagonalNormalizationTolerance
static const Core::ParameterFloat paramVerificationTolerance
static const Core::ParameterFloat paramRelativeImaginaryMaximum
static const Core::Choice choiceEigenvalueSortType
static const Core::ParameterChoice paramEigenvalueSort
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Base class for eigenvalue problems.
Definition at line 28 of file EigenvalueProblem.hh.
Member Enumeration Documentation
enum Math::EigenvalueProblem::EigenvectorNormalizationType private
Normalization type eigenvectors.
Eigenvectors are scaled such that: -nonEigenvectorNormalization: no scaling; -unityLength: 2nd norm of eigenvectors is one; -unityDiagonal: eigenvector^T * A * eigenvector = I.
Definition at line 40 of file EigenvalueProblem.hh.
Member Function Documentation
bool EigenvalueProblem::areEqual (const Matrix< ValueType > & x, const Matrix< ValueType > & y) protected
Returns
is true if x and y are equal with a floating point tolerance of verificationTolerance_. If
is false, error message is generated.
Definition at line 160 of file EigenvalueProblem.cc.
References Core::Component::error(), and Math::Matrix< T, P >::isAlmostEqual().
bool EigenvalueProblem::finalize (const Matrix< ValueType > & a, Vector< ValueType > & eigenvalues, Matrix< ValueType > & eigenvectors)
Performs final processing and verifications.
1) Performs final processing of eigenvalues and eigenvectors. 2) Verifies solution.
Definition at line 80 of file EigenvalueProblem.cc.
References Core::Component::error().
Referenced by Math::GeneralizedEigenvalueProblem::solveSymmetric().
bool EigenvalueProblem::finalizeEigenvaluesAndVectors (const Matrix< ValueType > & a, Vector< ValueType > & eigenvalues, Matrix< ValueType > & eigenvectors)
Performs final processing of eigenvalues and eigenvectors.
1) Normalizes eigenvectors (configurable) 2) Sorts eigenvalues
Definition at line 92 of file EigenvalueProblem.cc.
References Core::Component::error(), Math::Matrix< T, P >::normalizeColumnDirection(), and Math::Matrix< T, P >::normalizeColumns().
Referenced by Math::GeneralizedEigenvalueProblem::solveSymmetric().
bool EigenvalueProblem::isCorrectSolution (const Matrix< ValueType > & a, const Vector< ValueType > & eigenvalues, const Matrix< ValueType > & eigenvectors)
Verifies if eigenvectors and eigenvalues satisfy A*X = Lambda*B*X.
Definition at line 146 of file EigenvalueProblem.cc.
References Core::Component::error().
Referenced by Math::GeneralizedEigenvalueProblem::solveSymmetric().
bool EigenvalueProblem::normalizeDiagonal (const Matrix< ValueType > & a, Matrix< ValueType > & eigenvectors) protected
Eigenvectors are scaled so that eigenvector^T * A * eigenvector = I.
Definition at line 118 of file EigenvalueProblem.cc.
References Core::abs(), Math::Matrix< T, P >::columnNorm(), Core::Component::error(), Core::Component::log(), Math::Vector< T, P >::takeReciprocal(), and Math::Vector< T, P >::takeSquareRoot().
bool EigenvalueProblem::real (const Vector< std::complex< ValueType >> & c, Vector< ValueType > & r)
Extracts real part of the input vector.
If one of the imaginary parts are larger than imaginaryMaximum_ then
Returns
is false.
Definition at line 207 of file EigenvalueProblem.cc.
References Core::Component::error(), and Core::maxAbsoluteElement().
Referenced by Math::Lapack::GenEigenProblemWithSchurDecomposition::solveSymmetric().
bool EigenvalueProblem::real (const Matrix< std::complex< ValueType >> & c, Matrix< ValueType > & r)
Extracts real part of the input matrix.
If one of the imaginary parts are larger than imaginaryMaximum_ then
Returns
is false.
Definition at line 225 of file EigenvalueProblem.cc.
References Core::abs(), and Core::Component::error().
virtual bool Math::EigenvalueProblem::solveSymmetric (const Matrix< ValueType > & a, Vector< ValueType > & eigenvalues, Matrix< ValueType > & eigenvectors) pure virtual
Interface function for symmetric eigenvalue problem.
Implemented in Math::GeneralizedEigenvalueProblem, and Math::Lapack::SymmetricEigenvalueProblem.
Referenced by Math::GeneralizedEigenvalueProblem::solveSymmetric().
bool EigenvalueProblem::solveSymmetricAndFinalize (const Matrix< ValueType > & a, Vector< ValueType > & eigenvalues, Matrix< ValueType > & eigenvectors)
Solves the symmetric eigenvalue problem and performs finalization of results.
If
Returns
is false, depending on the type of error, results can be stored in eigenvalues and eigenvectors
Definition at line 68 of file EigenvalueProblem.cc.
Referenced by Math::GeneralizedEigenvalueProblem::solveSymmetric(), and Signal::ScatterTransform::writeScatterMatrix().
void EigenvalueProblem::sortEigenvalues (Vector< ValueType > & eigenvalues, Matrix< ValueType > & eigenvectors)
Sorts eigenvalues in descending order.
Eigenvectors are permuted according to eigenvalues.
Definition at line 174 of file EigenvalueProblem.cc.
References Core::abs(), and Core::Component::error().
The documentation for this class was generated from the following files:
EigenvalueProblem.hh
EigenvalueProblem.cc