Sprint: Core::XmlEmptyElement Class Reference
Core::XmlEmptyElement Class Reference
XML Element declaration for the empty content model.
#include <XmlParser.hh>
Public Member Functions
virtual void end ()
Handle end of the current XML element.
virtual void characters (const char *ch, int len)
Handle charcter data in the current XML element.
virtual XmlElement * element (const char *name)
Determine the state to be entered for a nested XML element.
XmlEmptyElement (const char *_name, XmlContext *_context, bool allowWhitespace=true)
Public Member Functions inherited from Core::XmlElement
XmlElement (const char *_name, XmlContext *_context)
const char * name () const
XmlContext * context () const
virtual XmlSchemaParser * parser ()
virtual bool matches (const char *_name) const
virtual void start (const XmlAttributes atts)
Handle start of the current XML element.
Private Attributes
bool allowWhitespace_
Additional Inherited Members
Public Types inherited from Core::XmlElement
typedef XmlElement * pointer
Public Types inherited from Core::XmlContext
typedef XmlContext Self
typedef void(Self::* StartHandler) (const XmlAttributes atts)
typedef void(Self::* EndHandler) ()
typedef void(Self::* CharactersHandler) (const char *ch, int len)
Static Public Member Functions inherited from Core::XmlContext
template<class T >
static StartHandler startHandler (void(T::*h)(const XmlAttributes atts))
template<class T >
static EndHandler endHandler (void(T::*h)())
template<class T >
static CharactersHandler charactersHandler (void(T::*h)(const char *ch, int len))
Static Public Attributes inherited from Core::XmlElement
static const char * wildcard = " * "
Protected Member Functions inherited from Core::XmlElement
XmlElement * collect (XmlElement *child)
Collects child elements.
Detailed Description
XML Element declaration for the empty content model.
XmlEmptyElement must not have any content. characters() and element() will raise a validity error
Definition at line 350 of file XmlParser.hh.
Member Function Documentation
void XmlEmptyElement::characters (const char * ch, int len) virtual
Handle charcter data in the current XML element.
Parameters
parser The XmlSchemaParser delegating the request.
Implements Core::XmlElement.
Reimplemented in Cart::XmlFloatBoxBuilderElement, Core::XmlDataOnlyBuilderElement< P, C >, Core::XmlDataOnlyBuilderElement< P, ChoiceConversion< P > >, XmlBuilder2::XmlChoiceBuilderElement, XmlBuilder2::XmlDataOnlyBuilderElement< std::string, StringConversion< std::string > >, XmlBuilder2::XmlDataOnlyBuilderElement< T, Converter >, and Cart::XmlIndexedStringBuilderElement.
Definition at line 524 of file XmlParser.cc.
XmlElement * XmlEmptyElement::element (const char * name) virtual
Determine the state to be entered for a nested XML element.
Parameters
name of the XML element encountered
Returns
XmlElement to handle the encountered element, or 0 if the element should not be allowed.
Parameters
parser The XmlSchemaParser delegating the request.
Implements Core::XmlElement.
Definition at line 518 of file XmlParser.cc.
void XmlEmptyElement::end () virtual
Handle end of the current XML element.
end() is called when end tag of the current element is found.
Parameters
parser The XmlSchemaParser delegating the request.
Reimplemented from Core::XmlElement.
Reimplemented in Cart::XmlFloatBoxBuilderElement, Core::XmlDataOnlyBuilderElement< P, C >, Core::XmlDataOnlyBuilderElement< P, ChoiceConversion< P > >, XmlBuilder2::XmlChoiceBuilderElement, XmlBuilder2::XmlDataOnlyBuilderElement< std::string, StringConversion< std::string > >, XmlBuilder2::XmlDataOnlyBuilderElement< T, Converter >, and Cart::XmlIndexedStringBuilderElement.
Definition at line 516 of file XmlParser.cc.
Referenced by Cart::XmlIndexedStringBuilderElement::end(), Cart::XmlPropertiesDefinitionBuilderElement::end(), Cart::XmlQuestionRefListBuilderElement::end(), Cart::XmlTrainingInformationBuilderElement::end(), Cart::XmlBinaryTreeRootBuilderElement::end(), Cart::XmlDecisionTreeBuilderElement::end(), Cart::XmlPropertiesBuilderElement::end(), Cart::XmlFloatBoxBuilderElement::end(), Cart::XmlExampleListBuilderElement::end(), Cart::XmlExampleListMergerElement::end(), Cart::XmlStepBuilderElement::end(), and Cart::XmlTrainingPlanBuilderElement::end().
The documentation for this class was generated from the following files:
XmlParser.hh
XmlParser.cc