Sprint: Search::TraceManager Class Reference
Search::TraceManager Class Reference
Classes
struct Cleaner
struct Modification
Public Member Functions
void clear ()
TraceId getTrace (const TraceItem &item)
Returns a trace-id that represents only the given item.
TraceId getManagedTraceId (const TraceItem *item)
Returns the trace-id of a trace that already is managed by the TraceManager.
uint numTraceItems () const
Returns the current number of existing trace-items.
uint maxTraceItems () const
Returns the maximum number of trace-items.
bool needCleanup () const
Returns whether a cleanup is currently strictly necessary (see cleanup())
bool isModified (const TraceId trace) const
Returns whether the given trace-id is additionally modified by a custom value.
Modification getModification (TraceId trace) const
Returns the custom modification-value that was attached to the trace-id. Must only be called if isModified(trace).
TraceId getUnmodified (TraceId trace) const
Returns the unmodified version of the given trace.
TraceId getUnmodified (TraceId trace)
TraceId modify (TraceId trace, u32 value, u32 value2=0, u32 value3=0)
Modifies the given trace-id with a specific value.
TraceItem const & traceItem (TraceId trace) const
Returns the (first) trace-item associated to the given trace-id The trace-id must be valid.
TraceItem & traceItem (TraceId trace)
Cleaner getCleaner ()
Private Types
enum { ModifyMask = 0xff000000 }
enum { UnModifyMask = 0x00ffffff }
Private Attributes
SparseVector< TraceItem > items_
SparseVector< std::pair< u32, Modification > > modifications_
Detailed Description
Definition at line 142 of file TraceManager.hh.
Member Function Documentation
TraceId Search::TraceManager::getManagedTraceId (const TraceItem * item) inline
Returns the trace-id of a trace that already is managed by the TraceManager.
Definition at line 163 of file TraceManager.hh.
Modification Search::TraceManager::getModification (TraceId trace) const inline
Returns the custom modification-value that was attached to the trace-id. Must only be called if isModified(trace).
Definition at line 199 of file TraceManager.hh.
Referenced by Search::SearchSpace::minimumWordEndScore().
TraceId Search::TraceManager::getTrace (const TraceItem & item) inline
Returns a trace-id that represents only the given item.
Definition at line 158 of file TraceManager.hh.
Referenced by Search::Instance::enter().
TraceId Search::TraceManager::getUnmodified (TraceId trace) const inline
Returns the unmodified version of the given trace.
Definition at line 216 of file TraceManager.hh.
Referenced by Search::SearchSpace::filterStates().
bool Search::TraceManager::isModified (const TraceId trace) const inline
Returns whether the given trace-id is additionally modified by a custom value.
Definition at line 183 of file TraceManager.hh.
Referenced by Search::SearchSpace::filterStates(), and Search::SearchSpace::minimumWordEndScore().
uint Search::TraceManager::maxTraceItems () const inline
Returns the maximum number of trace-items.
Definition at line 173 of file TraceManager.hh.
TraceId Search::TraceManager::modify (TraceId trace, u32 value, u32 value2 = 0, u32 value3 = 0) inline
Modifies the given trace-id with a specific value.
The value can later be retrieved through getModification(traceid), where traceid is the returned value.
Definition at line 237 of file TraceManager.hh.
Referenced by Search::SearchSpace::filterStates().
bool Search::TraceManager::needCleanup () const inline
Returns whether a cleanup is currently strictly necessary (see cleanup())
Definition at line 178 of file TraceManager.hh.
uint Search::TraceManager::numTraceItems () const inline
Returns the current number of existing trace-items.
Definition at line 168 of file TraceManager.hh.
TraceItem const& Search::TraceManager::traceItem (TraceId trace) const inline
Returns the (first) trace-item associated to the given trace-id The trace-id must be valid.
Definition at line 262 of file TraceManager.hh.
Referenced by Search::SearchSpace::filterStates(), Search::SearchSpace::getSentenceEnd(), Search::SearchSpace::getSentenceEndFallBack(), and Search::SearchSpace::minimumWordEndScore().
The documentation for this class was generated from the following file:
TraceManager.hh