Sprint: Flf::UnionBoundaries Class Reference
Flf::UnionBoundaries Class Reference
Public Member Functions
UnionBoundaries (const ConstLatticeRefList &lats)
virtual bool valid () const
false, if the lattice provides no boundaries
virtual bool valid (Fsa::StateId unionSid) const
false, if that specific boundary does not exist or is invalid, e.g.
virtual const Boundary & get (Fsa::StateId unionSid) const
return a specific boundary; for every sid a boundary is returned !valid(sid) => !get(sid).valid()
Public Member Functions inherited from Flf::Boundaries
Speech::TimeframeIndex time (Fsa::StateId sid) const
undefined, if !valid(sid)
Boundary::Transit transit (Fsa::StateId sid) const
undefined, if !valid(sid)
void dumpBoundary (Fsa::StateId sid, std::ostream &os) const
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Private Member Functions
std::pair< Fsa::StateId, Fsa::StateId > fromUnionSid (Fsa::StateId unionSid) const
Private Attributes
Fsa::StateId nLats_
ConstBoundariesRefList boundaries_
Boundary initialBoundary_
Detailed Description
Definition at line 29 of file Union.cc.
Member Function Documentation
virtual const Boundary& Flf::UnionBoundaries::get (Fsa::StateId sid) const inline virtual
return a specific boundary; for every sid a boundary is returned !valid(sid) => !get(sid).valid()
Implements Flf::Boundaries.
Definition at line 68 of file Union.cc.
References Core::Vector< T >::get().
virtual bool Flf::UnionBoundaries::valid () const inline virtual
false, if the lattice provides no boundaries
Implements Flf::Boundaries.
Definition at line 60 of file Union.cc.
Referenced by valid().
virtual bool Flf::UnionBoundaries::valid (Fsa::StateId sid) const inline virtual
false, if that specific boundary does not exist or is invalid, e.g.
not set !valid() => !valid(sid) for all state id
Implements Flf::Boundaries.
Definition at line 64 of file Union.cc.
References valid().
The documentation for this class was generated from the following file:
Union.cc