Sprint: Flow::Network::Port Class Reference
Flow::Network::Port Class Reference
Public Member Functions
Port (const std::string &name="")
const std::string & name () const
void setLink (Link *l)
sets the link which is used when the network is used from outside by calling putData or getData.
Link * link ()
const Link * link () const
void setNode (AbstractNode *node, PortId nodePort)
sets the node and the port to which the link can connect
AbstractNode * node ()
const AbstractNode * node () const
PortId nodePort () const
bool linkConnected () const
void setLinkConnected ()
void unsetLinkConnected ()
int operator== (const Port &p) const
bool operator< (const Port &p) const
Protected Attributes
std::string name_
Link * link_
link which is used when the network's putData or getData is called.
AbstractNode * node_
PortId nodePort_
bool linkConnected_
shows if the link is connected, i.e.
Friends
std::ostream & operator<< (std::ostream &o, const Port &p)
std::ostream & operator<< (std::ostream &o, const Port *p)
Detailed Description
Definition at line 111 of file Flow/Network.hh.
Member Function Documentation
bool Flow::Network::Port::linkConnected () const inline
Returns
is true if link is connected to the inside of the network.
Definition at line 162 of file Flow/Network.hh.
Referenced by Flow::Network::activateOutput(), Flow::Network::configureOutputPort(), Flow::Network::connectInputPort(), Flow::Network::connectInputPortLink(), Flow::Network::connectOutputPort(), Flow::Network::connectOutputPortLink(), Flow::Network::disconnectInputPortLink(), Flow::Network::disconnectOutputPortLink(), Flow::Network::getAttribute(), Flow::Network::putAttributes(), Flow::Network::putData(), and Flow::Network::putOod().
AbstractNode* Flow::Network::Port::node () inline
Returns
is the node connected to the port
Definition at line 148 of file Flow/Network.hh.
Referenced by Flow::Network::connectInputFromInside(), Flow::Network::connectInputPort(), Flow::Network::connectInputPortLink(), Flow::Network::connectOutputFromInside(), Flow::Network::connectOutputPort(), Flow::Network::connectOutputPortLink(), Flow::Network::disconnectInputPortLink(), and Flow::Network::disconnectOutputPortLink().
PortId Flow::Network::Port::nodePort () const inline
Returns
is the PortId of the node connected to the port
Definition at line 157 of file Flow/Network.hh.
Referenced by Flow::Network::connectInputFromInside(), Flow::Network::connectInputPort(), Flow::Network::connectInputPortLink(), Flow::Network::connectOutputPort(), and Flow::Network::connectOutputPortLink().
void Network::Port::setLink (Link * l)
sets the link which is used when the network is used from outside by calling putData or getData.
Definition at line 38 of file Flow/Network.cc.
References require.
Referenced by Flow::Network::connectInputFromInside(), and Flow::Network::connectOutputFromInside().
void Network::Port::setNode (AbstractNode * node, PortId nodePort)
sets the node and the port to which the link can connect
Definition at line 45 of file Flow/Network.cc.
References require, and Core::Component::warning().
Referenced by Flow::Network::addParameterUse(), and Flow::Network::connectOutputFromInside().
Member Data Documentation
Link* Flow::Network::Port::link_ protected
link which is used when the network's putData or getData is called.
If the port is used by other abstract nodes the link is not connected.
Definition at line 117 of file Flow/Network.hh.
bool Flow::Network::Port::linkConnected_ protected
shows if the link is connected, i.e.
port is used either by putData or getData.
Definition at line 122 of file Flow/Network.hh.
The documentation for this class was generated from the following files:
Flow/Network.hh
Flow/Network.cc