Sprint: Search::AdvancedTreeSearchManager Class Reference
Search::AdvancedTreeSearchManager Class Reference
Public Types
enum LatticeOptimizationMethod { noLatticeOptimization, simpleSilenceLatticeOptimization }
enum SearchVariant { WordConditioned, TimeConditioned }
Public Types inherited from Search::SearchAlgorithm
typedef Speech::Score Score
typedef Speech::TimeframeIndex TimeframeIndex
typedef Core::Ref< Pruning > PruningRef
Public Member Functions
AdvancedTreeSearchManager (const Core::Configuration &)
AdvancedTreeSearchManager (const AdvancedTreeSearchManager &rhs)
virtual void setAllowHmmSkips (bool allow)
Allow HMM skips during decoding ? By default, HMM skips are allowed.
virtual bool setModelCombination (const Speech::ModelCombination &modelCombination)
virtual void setGrammar (Fsa::ConstAutomatonRef)
virtual void restart ()
virtual void setSegment (Bliss::SpeechSegment const *segment)
virtual void feed (const Mm::FeatureScorer::Scorer &)
virtual void getPartialSentence (Traceback &result)
Should return the longest fixed prefix of the final best sentence which has been been recognized since the last call to getPartialSentence.
virtual void getCurrentBestSentencePartial (Traceback &result) const
Should return the part of the current best sentence which has not yet been returned by getPartialSentence().
virtual void getCurrentBestSentence (Traceback &result) const
Should return the whole currently best sentence.
virtual Core::Ref< const LatticeAdaptor > getCurrentWordLattice () const
virtual Core::Ref< const LatticeAdaptor > getPartialWordLattice ()
virtual void resetStatistics ()
virtual void logStatistics () const
virtual bool relaxPruning (f32 factor, f32 offset)
Relaxes the pruning. Returns false if relaxing failed, otherwise true.
virtual void resetPruning (PruningRef pruning)
Resets pruning according to the given descriptor.
virtual PruningRef describePruning ()
Returns a descriptor of the current pruning thresholds, which can be used to re-activate the current pruning thresholds using resetPruning.
virtual u32 lookAheadLength ()
Length of acoustic look-ahead.
virtual void setLookAhead (const std::vector< Mm::FeatureVector > &lookahead)
Called before feed() with as many acoustic feature vectors from the future as returned by lookaheadLength().
virtual RecognitionContext setContext (RecognitionContext context)
Set LM context to be prepended (prefix) or appended(suffix) to the search hypotheses, and the acoustic phoneme coarticulation to be used for startup.
Public Member Functions inherited from Search::SearchAlgorithm
SearchAlgorithm (const Core::Configuration &)
virtual Speech::ModelCombination::Mode modelCombinationNeeded () const
virtual void init ()
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Private Member Functions
Core::Ref< Trace > sentenceEnd () const
void mergeEpsilonTraces (Core::Ref< Trace > trace) const
bool shouldComputeWordEnds ()
Core::Ref< Trace > getCorrectedCommonPrefix ()
Core::Ref< const LatticeAdaptor > buildLatticeForTrace (Core::Ref< Trace > trace) const
void traceback (Core::Ref< Trace >, Traceback &result, Core::Ref< Trace > boundary=Core::Ref< Trace >()) const
Private Attributes
Bliss::LexiconRef lexicon_
const Bliss::Lemma * silence_
Core::Ref< const Am::AcousticModel > acousticModel_
Core::Ref< const Lm::ScaledLanguageModel > lm_
Score wpScale_
bool shallCreateLattice_
bool allowSentenceEndFallBack_
LatticeOptimizationMethod shallOptimizeLattice_
u32 startTreesInterval_
u32 cleanupInterval_
f32 onlineSegmentationLength_
f32 onlineSegmentationMargin_
f32 onlineSegmentationTolerance_
bool onlineSegmentationIncludeGap_
TimeframeIndex time_
TimeframeIndex currentSegmentStart_
f32 frameShift_
std::chrono::time_point< std::chrono::steady_clock > segmentStartTime_
std::unique_ptr< DynamicBeamPruningStrategy > dynamicBeamPruningStrategy_
SearchSpace * ss_
Core::XmlChannel statisticsChannel_
Core::Ref< Trace > sentenceEnd_
Core::Ref< Trace > lastPartialTrace_
Friends
class ReverseWordLattice
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Definition at line 42 of file AdvancedTreeSearch.hh.
Member Function Documentation
SearchAlgorithm::PruningRef AdvancedTreeSearchManager::describePruning () virtual
Returns a descriptor of the current pruning thresholds, which can be used to re-activate the current pruning thresholds using resetPruning.
Reimplemented from Search::SearchAlgorithm.
Definition at line 629 of file AdvancedTreeSearch.cc.
void AdvancedTreeSearchManager::feed (const Mm::FeatureScorer::Scorer & emissionScores) virtual
Handle word-ends
Implements Search::SearchAlgorithm.
Definition at line 210 of file AdvancedTreeSearch.cc.
References defect, and require.
void AdvancedTreeSearchManager::getCurrentBestSentence (Traceback & result) const virtual
Should return the whole currently best sentence.
Implements Search::SearchAlgorithm.
Definition at line 445 of file AdvancedTreeSearch.cc.
References Core::Component::error().
void AdvancedTreeSearchManager::getCurrentBestSentencePartial (SearchAlgorithm::Traceback & result) const virtual
Should return the part of the current best sentence which has not yet been returned by getPartialSentence().
Optional: Only required for online recognition
Reimplemented from Search::SearchAlgorithm.
Definition at line 455 of file AdvancedTreeSearch.cc.
References Core::Ref< T >::get(), Core::ref(), verify, and Core::Component::warning().
void AdvancedTreeSearchManager::getPartialSentence (Traceback & result) virtual
Should return the longest fixed prefix of the final best sentence which has been been recognized since the last call to getPartialSentence.
Optional: Only required for online recognition
Reimplemented from Search::SearchAlgorithm.
Definition at line 291 of file AdvancedTreeSearch.cc.
u32 AdvancedTreeSearchManager::lookAheadLength () virtual
Length of acoustic look-ahead.
0 means no look-ahead is used.
Reimplemented from Search::SearchAlgorithm.
Definition at line 605 of file AdvancedTreeSearch.cc.
bool AdvancedTreeSearchManager::relaxPruning (f32 factor, f32 offset) virtual
Relaxes the pruning. Returns false if relaxing failed, otherwise true.
Reimplemented from Search::SearchAlgorithm.
Definition at line 621 of file AdvancedTreeSearch.cc.
void AdvancedTreeSearchManager::resetPruning (SearchAlgorithm::PruningRef pruning) virtual
Resets pruning according to the given descriptor.
Reimplemented from Search::SearchAlgorithm.
Definition at line 625 of file AdvancedTreeSearch.cc.
void AdvancedTreeSearchManager::setAllowHmmSkips (bool allow) virtual
Allow HMM skips during decoding ? By default, HMM skips are allowed.
Reimplemented from Search::SearchAlgorithm.
Definition at line 154 of file AdvancedTreeSearch.cc.
References verify.
Search::SearchAlgorithm::RecognitionContext AdvancedTreeSearchManager::setContext (RecognitionContext) virtual
Set LM context to be prepended (prefix) or appended(suffix) to the search hypotheses, and the acoustic phoneme coarticulation to be used for startup.
The context should never be forgotten, but can be reset by calling this function with default arguments. Should return the context which was used previously.
Reimplemented from Search::SearchAlgorithm.
Definition at line 609 of file AdvancedTreeSearch.cc.
void AdvancedTreeSearchManager::setLookAhead (const std::vector< Mm::FeatureVector > &) virtual
Called before feed() with as many acoustic feature vectors from the future as returned by lookaheadLength().
At the end of a segment, less than requested, or even zero feature vectors may be given.
Reimplemented from Search::SearchAlgorithm.
Definition at line 613 of file AdvancedTreeSearch.cc.
The documentation for this class was generated from the following files:
AdvancedTreeSearch.hh
AdvancedTreeSearch.cc