Sprint: Core::TextOutputStream Class Reference
Core::TextOutputStream Class Reference
Stream for text output.
#include <TextStream.hh>
Classes
class Buffer
Public Types
enum FormattingHint {
BEL = 7, BS = 8, HT = 9, LF = 10,
VT = 11, FF = 12, CR = 13, indentPlus = 1,
indentMinus = 2, describeEncoding = 3, protect = 4, unprotect = 5,
newWord = 6, softBlank = BEL, lineBreak = LF, newLine = 14
}
Public Member Functions
TextOutputStream (std::ostream *)
Create TextOutputStream on top of an existing ostream.
TextOutputStream (const std::string &filename, int mode=0)
Open/create named file and construct a TextOutputStream.
void adopt (std::ostream *)
Set a new underlying ostream.
void open (const std::string &filename, int mode=0)
Open/create named file.
void close ()
Close and delete underlying file or ostream.
void setLineBuffered (bool)
Restrict internal buffering to a single line.
void setBufferSize (size_t s)
Limit amount of data to buffer internally.
const std::string & encoding () const
Character set encoding to be used in the external.
void setEncoding (const std::string &encoding=UnicodeOutputConverter::defaultEncoding)
Change the character set encoding to be used in the external file.
void setIndentation (u32)
Set number of blank characters at the begining of each new line, PER LEVEL of indentation.
void setMargin (u32)
Set maximum number of characters per line.
bool good () const
operator bool () const
void flush ()
Private Attributes
Buffer * buffer_
std::ostream * output_
Detailed Description
Stream for text output.
Use this for writing plain text files. For XML use XmlOutoutStream.
Features if TextOutputStream:
word wrap
indentation
character set conversion Remeber: all internal string are considered UTF-8
TextOutputStream redefines some ASCII control characters to control text formatting. Since these codes are old teletype legacy and have no use in modern computing environments, we should get away with this.
Definition at line 45 of file TextStream.hh.
Member Enumeration Documentation
enum Core::TextOutputStream::FormattingHint
Enumerator
indentPlus
increase indentation level by one (effective after next newline)
indentMinus
decrease indentation level by one (effective after next newline)
describeEncoding
output name of output encoding used
protect
temporarily disable word-wrap (may be nested)
unprotect
reenable word-wrap
newWord
optional line break (even when protect is set)
softBlank
consecutive soft blanks are replaced by a single normal blank
lineBreak
start a new line uncoditionally
newLine
start a new line, ignore if the current position is the beginning of a line
Definition at line 47 of file TextStream.hh.
Constructor & Destructor Documentation
TextOutputStream::TextOutputStream (std::ostream * s) explicit
Create TextOutputStream on top of an existing ostream.
TextOutputStream takes ownership of the ostream passed, and will delete it.
Definition at line 309 of file TextStream.cc.
References setEncoding().
TextOutputStream::TextOutputStream (const std::string & filename, int mode = 0)
Open/create named file and construct a TextOutputStream.
Definition at line 316 of file TextStream.cc.
References setEncoding().
Member Function Documentation
void TextOutputStream::adopt (std::ostream * o)
Set a new underlying ostream.
TextOutputStream takes ownership of the ostream passed and will delete it.
Definition at line 324 of file TextStream.cc.
void TextOutputStream::close ()
Close and delete underlying file or ostream.
Definition at line 336 of file TextStream.cc.
Referenced by Speech::LemmaPronunciationId_hash_map::init(), Speech::AlignmentDumpNode::work(), and Speech::LatticeArcAccumulatorNode::~LatticeArcAccumulatorNode().
const std::string & TextOutputStream::encoding () const
Character set encoding to be used in the external.
Definition at line 362 of file TextStream.cc.
void TextOutputStream::open (const std::string & filename, int mode = 0)
Open/create named file.
Definition at line 330 of file TextStream.cc.
Referenced by LmUtilityTool::main().
void TextOutputStream::setBufferSize (size_t s)
Limit amount of data to buffer internally.
An argument of zero restores the default size.
Definition at line 358 of file TextStream.cc.
void TextOutputStream::setEncoding (const std::string & encoding = UnicodeOutputConverter::defaultEncoding)
Change the character set encoding to be used in the external file.
Remember, internal strings are expected to be UTF-8.
Definition at line 366 of file TextStream.cc.
Referenced by Flf::ConfusionNetworkArchive::ConfusionNetworkArchive(), Flf::PosteriorCnArchive::PosteriorCnArchive(), TextOutputStream(), Speech::AlignmentDumpNode::work(), and Speech::LatticeArcAccumulatorNode::~LatticeArcAccumulatorNode().
void TextOutputStream::setIndentation (u32 d)
Set number of blank characters at the begining of each new line, PER LEVEL of indentation.
The actual indentation level is changed using the indentPlus and indentMinus control characters.
Definition at line 370 of file TextStream.cc.
Referenced by Speech::LatticeArcAccumulatorNode::~LatticeArcAccumulatorNode().
void TextOutputStream::setLineBuffered (bool lb)
Restrict internal buffering to a single line.
Definition at line 354 of file TextStream.cc.
void TextOutputStream::setMargin (u32 m)
Set maximum number of characters per line.
This is not a hard limit: When a single word is longer than the margin it will not be broken. Also using the protect control character can cause the margin to be exceeded.
Definition at line 374 of file TextStream.cc.
The documentation for this class was generated from the following files:
TextStream.hh
TextStream.cc