Sprint: Speech::TextIndependentScatterMatricesEstimator Class Reference
Speech::TextIndependentScatterMatricesEstimator Class Reference
Text Independent Lda Estimator.
#include <ScatterMatricesEstimator.hh>
Public Member Functions
TextIndependentScatterMatricesEstimator (const Core::Configuration &configuration)
TextIndependentScatterMatricesEstimator (const Core::Configuration &configuration, Core::Ref< Signal::ScatterMatricesEstimator >)
EstimatorRef getEstimator () const
Public Member Functions inherited from Speech::LabeledFeatureProcessor
LabeledFeatureProcessor (const Core::Configuration &c)
virtual void signOn (CorpusVisitor &corpusVisitor)
Override this function to sign on to services of the corpus visitor.
virtual void enterSegment (Bliss::Segment *)
Override this function to perform preparations before first aligned features arrive.
virtual void leaveSegment (Bliss::Segment *)
Override this function to perform post processing after the last aligned features of the segment.
virtual void enterSpeechSegment (Bliss::SpeechSegment *)
Override this function to perform preparations before first aligned features arrive.
virtual void leaveSpeechSegment (Bliss::SpeechSegment *)
Override this function to perform post processing after the last aligned features of the segment.
virtual void setDataSource (Core::Ref< DataSource >)
Override this function to obtain the data source of corpus processor which produces the labels.
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Protected Member Functions
virtual void setFeatureDescription (const Mm::FeatureDescription &)
Override this function to achieve the attributes of the feature streams.
virtual void setLabels (const std::vector< std::string > &labels)
Override this function to achieve the labels.
virtual void processLabeledFeature (Core::Ref< const Feature > feature, LabelIndex labelIndex)
Override this function to implement the processing of aligned feature vectors.
virtual void processLabeledFeature (Core::Ref< const Feature > feature, LabelIndex labelIndex, Mm::Weight w)
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes
EstimatorRef estimator_
Protected Attributes inherited from Core::Configurable
Configuration config
Private Types
typedef Core::Ref< Signal::ScatterMatricesEstimator > EstimatorRef
Additional Inherited Members
Public Types inherited from Speech::LabeledFeatureProcessor
typedef u32 LabelIndex
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Detailed Description
Text Independent Lda Estimator.
Definition at line 52 of file ScatterMatricesEstimator.hh.
Member Function Documentation
virtual void Speech::TextIndependentScatterMatricesEstimator::processLabeledFeature (Core::Ref< const Feature > , LabelIndex) inline protected virtual
Override this function to implement the processing of aligned feature vectors.
Reimplemented from Speech::LabeledFeatureProcessor.
Definition at line 63 of file ScatterMatricesEstimator.hh.
References Core::Component::criticalError(), and Mm::Feature::mainStream().
void TextIndependentScatterMatricesEstimator::setFeatureDescription (const Mm::FeatureDescription &) protected virtual
Override this function to achieve the attributes of the feature streams.
This function is called once before the first feature vector is processed.
Reimplemented from Speech::LabeledFeatureProcessor.
Definition at line 49 of file ScatterMatricesEstimator.cc.
References Core::Description::Stream::getValue(), and Core::Description::verifyNumberOfStreams().
virtual void Speech::TextIndependentScatterMatricesEstimator::setLabels (const std::vector< std::string > &) inline protected virtual
Override this function to achieve the labels.
Reimplemented from Speech::LabeledFeatureProcessor.
Definition at line 59 of file ScatterMatricesEstimator.hh.
The documentation for this class was generated from the following files:
ScatterMatricesEstimator.hh
ScatterMatricesEstimator.cc