Sprint: Flf::ConfusionNetworkAlignment Class Reference
Flf::ConfusionNetworkAlignment Class Reference
Classes
class Cost
Public Types
typedef Core::Ref< const Cost > ConstCostRef
typedef std::vector< std::pair< u32, u32 > > Alignment
typedef Alignment::const_reverse_iterator const_iterator
Public Member Functions
ConfusionNetworkAlignment (ConstCostRef costFcn, u32 minBeamWidth)
void dump (std::ostream &os) const
ConstCostRef cost ()
u32 beamWidth () const
const_iterator begin () const
const_iterator end () const
Score align (const ConfusionNetwork &ref, const ConfusionNetwork &hyp) const
Levenshtein alignment with fixed beam around main diagonal.
Private Types
enum Operation {
Invalid, Start, Substitution, Deletion,
Insertion
}
typedef enum Flf::ConfusionNetworkAlignment::Operation OperationType
Private Member Functions
void allocate (u32 lenRef, u32 lenHyp) const
Allocate memory, adjust beam such that a successful alignment is guaranteed.
Private Attributes
ConstCostRef costFcn_
u32 minBeamWidth_
u32 beamWidth_
u32 beamDiameter_
u32 maxLen_
Score * D_
OperationType * B_
Alignment revAlignment_
Static Private Attributes
static const Score MaxCost = 0.5 * Core::Type<Score>::max
Detailed Description
Definition at line 33 of file ConfusionNetworkCombination.cc.
Member Function Documentation
Score Flf::ConfusionNetworkAlignment::align (const ConfusionNetwork & ref, const ConfusionNetwork & hyp) const inline
Levenshtein alignment with fixed beam around main diagonal.
Definition at line 164 of file ConfusionNetworkCombination.cc.
References allocate(), Core::Component::criticalError(), defect, Core::ProgressIndicator::finish(), Core::form(), Core::ProgressIndicator::notify(), Core::ProgressIndicator::start(), Core::Application::us(), and verify.
Referenced by Flf::ConfusionNetworkCombination::init(), and Flf::RoverCombination::init().
void Flf::ConfusionNetworkAlignment::allocate (u32 lenRef, u32 lenHyp) const inline private
Allocate memory, adjust beam such that a successful alignment is guaranteed.
Definition at line 101 of file ConfusionNetworkCombination.cc.
References verify.
Referenced by align().
The documentation for this class was generated from the following file:
ConfusionNetworkCombination.cc