Sprint: Signal::WindowBuffer Class Reference
Signal::WindowBuffer Class Reference
WindowBuffer is buffer collecting vectors of samples and delivering (overlapping) segments of a given length.
#include <WindowBuffer.hh>
Public Types
enum FlushPolicy { SendRest, PadRest, DiscardRest }
typedef Flow::Time Time
typedef f32 Sample
typedef Flow::Vector< Sample > InputData
typedef Flow::Vector< Sample > OutputData
Public Member Functions
bool put (const Flow::Vector< Sample > &in)
adds an input vector
bool get (Flow::Vector< Sample > &out)
returns one vector of the given length_ and removes shift_ number of elements from the begining of the buffer
bool flush (Flow::Vector< Sample > &out)
delivers the rest of the buffer_
virtual void reset ()
Clears the buffer and resets status variables.
void setShift (u32 shift)
set the number of samples removed after each call to get
u32 shift ()
the number of samples removed after each call to get
void setLength (u32 length)
sets the length of output vectors
u32 length () const
length of output vectors
void setSampleRate (Time sampleRate)
Time sampleRate () const
u32 nOutputs ()
number released of outputs
bool flushed ()
void setFlushAll (bool flushAll)
if
bool flushAll () const
void setFlushBeforeGap (bool flushBeforeGap)
bool shallFlushBeforeGap () const
Protected Member Functions
void setNeedInit ()
call to force initialization
virtual void init ()
overload to perform initialization
virtual void transform (Flow::Vector< Sample > &out)
overload to transform output vectors
Protected Attributes
u32 length_
length_ of output vectors
u32 shift_
number of elements removed from the beginning of the buffer after a call to get
Time bufferStartTime_
Time sampleRate_
bool flushBeforeGap_
std::deque< Sample > buffer_
u32 nOutputs_
number released of outputs
bool flushed_
true if buffer is flushed
bool flushAll_
if true, segments are delivered shift-by-shift until the buffer is empty if false, segments are delivered until the last segment contains the last sample
bool needInit_
Private Member Functions
void copy (Flow::Vector< f32 > &out, const u32 length)
copies
Detailed Description
WindowBuffer is buffer collecting vectors of samples and delivering (overlapping) segments of a given length.
Definition at line 27 of file WindowBuffer.hh.
Member Function Documentation
void WindowBuffer::copy (Flow::Vector< f32 > & out, const u32 length) private
copies
Parameters
length element form the beginning of the buffer to
out and sets the beginning and end time of
out
Definition at line 69 of file WindowBuffer.cc.
References length(), nOutputs_, and Signal::Window::transform().
Referenced by flush(), and get().
bool WindowBuffer::flush (Flow::Vector< Sample > & out)
delivers the rest of the buffer_
Returns
is false if the buffer_ is empty
Caution: an assertion fails if the buffer is larger then 2 * max(length_, shift_)
Definition at line 99 of file WindowBuffer.cc.
References copy(), flushed(), flushed_, Signal::Window::init(), length_, shift_, and verify.
Referenced by transform().
bool Signal::WindowBuffer::flushed () inline
Returns
is true if the last output is following
Definition at line 137 of file WindowBuffer.hh.
References flushed_.
Referenced by flush().
bool WindowBuffer::get (Flow::Vector< Sample > & out)
returns one vector of the given length_ and removes shift_ number of elements from the begining of the buffer
Returns
is false if buffer is smaller then 2 * max(length_, shift_)
Definition at line 81 of file WindowBuffer.cc.
References copy(), Signal::Window::init(), length_, shift_, and verify.
void WindowBuffer::init () protected virtual
overload to perform initialization
Reimplemented in Signal::WindowingFirFilter, and Signal::Window.
Definition at line 36 of file WindowBuffer.cc.
References reset(), and verify.
Referenced by setNeedInit().
u32 Signal::WindowBuffer::length () const inline
length of output vectors
Definition at line 120 of file WindowBuffer.hh.
References length_.
Referenced by copy(), and setLength().
u32 Signal::WindowBuffer::nOutputs () inline
number released of outputs
Definition at line 132 of file WindowBuffer.hh.
References nOutputs_.
bool WindowBuffer::put (const Flow::Vector< Sample > & in)
adds an input vector
Returns
is false if there is a time gap between the end time of the buffer and start time of in
Definition at line 50 of file WindowBuffer.cc.
References ensure, and Signal::Window::init().
Referenced by transform().
void WindowBuffer::reset (void) virtual
Clears the buffer and resets status variables.
Definition at line 43 of file WindowBuffer.cc.
References flushed_, and nOutputs_.
Referenced by init(), and transform().
void Signal::WindowBuffer::setFlushAll (bool flushAll) inline
if
Parameters
flushAll is true, segments are delivered shift-by-shift until the buffer is empty if
flushAll false, segments are delivered until the last segment contains the last sample
Definition at line 146 of file WindowBuffer.hh.
References flushAll_.
void Signal::WindowBuffer::setLength (u32 length) inline
sets the length of output vectors
Definition at line 116 of file WindowBuffer.hh.
References length().
void Signal::WindowBuffer::setNeedInit () inline protected
call to force initialization
Definition at line 69 of file WindowBuffer.hh.
References init().
void Signal::WindowBuffer::setShift (u32 shift) inline
set the number of samples removed after each call to get
Definition at line 107 of file WindowBuffer.hh.
References shift().
u32 Signal::WindowBuffer::shift () inline
the number of samples removed after each call to get
Definition at line 111 of file WindowBuffer.hh.
References shift_.
Referenced by setShift().
virtual void Signal::WindowBuffer::transform (Flow::Vector< Sample > & out) inline protected virtual
overload to transform output vectors
caution: update the start- and end-time of out if the size is changed
Reimplemented in Signal::WindowingFirFilter, and Signal::Window.
Definition at line 80 of file WindowBuffer.hh.
References flush(), put(), and reset().
Member Data Documentation
bool Signal::WindowBuffer::flushAll_ protected
if true, segments are delivered shift-by-shift until the buffer is empty if false, segments are delivered until the last segment contains the last sample
Definition at line 56 of file WindowBuffer.hh.
Referenced by setFlushAll().
bool Signal::WindowBuffer::flushed_ protected
true if buffer is flushed
Definition at line 52 of file WindowBuffer.hh.
Referenced by flush(), flushed(), and reset().
u32 Signal::WindowBuffer::length_ protected
length_ of output vectors
Definition at line 39 of file WindowBuffer.hh.
Referenced by flush(), get(), and length().
u32 Signal::WindowBuffer::nOutputs_ protected
number released of outputs
Definition at line 49 of file WindowBuffer.hh.
Referenced by copy(), nOutputs(), and reset().
u32 Signal::WindowBuffer::shift_ protected
number of elements removed from the beginning of the buffer after a call to get
Definition at line 41 of file WindowBuffer.hh.
Referenced by flush(), get(), and shift().
The documentation for this class was generated from the following files:
WindowBuffer.hh
WindowBuffer.cc