Sprint: Mm::MixtureSet Class Reference
Mm::MixtureSet Class Reference
MixtureSet administrates mixture, Gauss-density, mean, and covariance objects and their relations.
#include <MixtureSet.hh>
Public Member Functions
MixtureSet (ComponentIndex dimension=0)
MixtureSet.
MixtureSet * createOneMixtureCopy () const
MixtureSet * createOneMixtureClusterCopy (const Core::Configuration &clusteringConfiguration) const
virtual void clear ()
virtual void setOffset (ComponentIndex offset)
virtual void setDimension (ComponentIndex dimension)
void replaceMeans (const Mm::Mean &newMean)
Overwrites the means of a given mixture set (for debugging purposes).
virtual GaussDensity * density (DensityIndex index)
virtual const GaussDensity * density (DensityIndex index) const
MeanIndex addMean (MeanIndex index, Mean *mean)
MeanIndex addMean (Mean *mean)
MeanIndex nMeans () const
Mean * mean (MeanIndex index)
const Mean * mean (MeanIndex index) const
CovarianceIndex addCovariance (CovarianceIndex index, Covariance *covariance)
CovarianceIndex addCovariance (Covariance *covariance)
CovarianceIndex nCovariances () const
Covariance * covariance (CovarianceIndex index)
void setFeatureWeights (const std::vector< f64 > w)
const Covariance * covariance (CovarianceIndex index) const
void writeLogNormStatistics (Core::XmlWriter &) const
virtual bool write (Core::BinaryOutputStream &o) const
print/scan methods for std::iostreams used in operator<< resp.
virtual bool read (Core::BinaryInputStream &i)
virtual bool write (std::ostream &o) const
virtual bool read (std::istream &i)
Public Member Functions inherited from Mm::AbstractMixtureSet
AbstractMixtureSet (ComponentIndex dimension=0)
AbstractMixtureSet.
ComponentIndex dimension () const
MixtureIndex addMixture (MixtureIndex index, Mixture *mixture)
MixtureIndex addMixture (Mixture *mixture)
MixtureIndex nMixtures () const
Mixture * mixture (MixtureIndex index)
const Mixture * mixture (MixtureIndex index) const
DensityIndex addDensity (DensityIndex index, AbstractDensity *density)
DensityIndex addDensity (AbstractDensity *density)
DensityIndex nDensities () const
virtual void removeDensitiesWithLowWeight (Weight minWeight, bool normalizeWeights=true)
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Protected Attributes
PointerVector< Mean > meanTable_
PointerVector< Covariance > covarianceTable_
Protected Attributes inherited from Mm::AbstractMixtureSet
PointerVector< Mixture > mixtureTable_
PointerVector< AbstractDensity > densityTable_
ComponentIndex dimension_
Private Types
typedef AbstractMixtureSet Precursor
Detailed Description
MixtureSet administrates mixture, Gauss-density, mean, and covariance objects and their relations.
Definition at line 140 of file MixtureSet.hh.
Constructor & Destructor Documentation
MixtureSet::MixtureSet (ComponentIndex dimension = 0)
MixtureSet.
Definition at line 56 of file MixtureSet.cc.
Member Function Documentation
MixtureSet * MixtureSet::createOneMixtureClusterCopy (const Core::Configuration & clusteringConfiguration) const
Todo:
Move this method to somewhere else
Definition at line 87 of file MixtureSet.cc.
References defect.
Referenced by Speech::ClusterMixtureSetTrainer::ClusterMixtureSetTrainer().
void MixtureSet::replaceMeans (const Mm::Mean & newMean)
Overwrites the means of a given mixture set (for debugging purposes).
Parameters
newMean New mean.
Definition at line 97 of file MixtureSet.cc.
References Core::Component::criticalError(), Core::Component::error(), Core::Application::us(), and write().
bool MixtureSet::write (Core::BinaryOutputStream & o) const virtual
print/scan methods for std::iostreams used in operator<< resp.
operator>> overwrite these methodes in inherited classes
Reimplemented from Mm::AbstractMixtureSet.
Definition at line 215 of file MixtureSet.cc.
References Core::Component::criticalError(), Core::Component::error(), and Core::Application::us().
Referenced by replaceMeans().
The documentation for this class was generated from the following files:
MixtureSet.hh
MixtureSet.cc