Sprint: Bliss::SegmentVisitor Class Reference
Bliss::SegmentVisitor Class Reference
Abstract visitor base class for processing segments.
#include <CorpusDescription.hh>
Public Member Functions
virtual void visitSegment (Segment *)
Template method for processing segments.
virtual void visitSpeechSegment (SpeechSegment *s)
Template method for processing speech segments.
Detailed Description
Abstract visitor base class for processing segments.
See also
CorpusVisitor
Definition at line 472 of file CorpusDescription.hh.
Member Function Documentation
virtual void Bliss::SegmentVisitor::visitSegment (Segment *) inline virtual
Template method for processing segments.
Implement this to process speech and non-speech segments of a corpus.
Reimplemented in Bliss::ProgressReportingVisitorAdaptor, Bliss::CorpusDescription::ProgressIndicationVisitorAdaptor, Bliss::CorpusDescription::SegmentCountingVisitor, Bliss::CorpusDescription::SegmentPartitionVisitorAdaptor, Bliss::CompositeCorpusStatisticsVisitor, Bliss::CorpusConditionStatisticsVisitor, Speech::CorpusVisitor, Bliss::SegmentOrderingVisitor, and Bliss::CorpusSizeStatisticsVisitor.
Definition at line 478 of file CorpusDescription.hh.
Referenced by Bliss::Segment::accept(), Bliss::CorpusDescription::SegmentPartitionVisitorAdaptor::visitSegment(), and Bliss::CorpusDescription::ProgressIndicationVisitorAdaptor::visitSegment().
virtual void Bliss::SegmentVisitor::visitSpeechSegment (SpeechSegment * s) inline virtual
Template method for processing speech segments.
Implement this to process the speech segments of a corpus. By default the request will be forwarded to visitSegment(), so ignore this if you want to treat speech and non-speech segments alike.
Reimplemented in Bliss::ProgressReportingVisitorAdaptor, Bliss::CorpusDescription::ProgressIndicationVisitorAdaptor, Bliss::CorpusDescription::SegmentPartitionVisitorAdaptor, BuildSegmentToOrthMapVisitor, Bliss::CompositeCorpusStatisticsVisitor, Bliss::CorpusLexicalStatisticsVisitor, Bliss::CorpusSpeakerStatisticsVisitor, Lm::CorpusStatisticsVisitor, Speech::CorpusVisitor, Bliss::SegmentOrderingVisitor, Bliss::CorpusSizeStatisticsVisitor, and TestCorpusVisitor.
Definition at line 486 of file CorpusDescription.hh.
Referenced by Bliss::SpeechSegment::accept(), Bliss::CorpusDescription::SegmentPartitionVisitorAdaptor::visitSpeechSegment(), and Bliss::CorpusDescription::ProgressIndicationVisitorAdaptor::visitSpeechSegment().
The documentation for this class was generated from the following file:
CorpusDescription.hh