Sprint: Mm::DensityClusteringBase Class Reference
Mm::DensityClusteringBase Class Reference abstract
Public Types
typedef u8 ClusterIndex
typedef std::vector< ClusterIndex >::const_iterator ClusterIndexIterator
Public Member Functions
DensityClusteringBase (const Core::Configuration &config)
void init (u32 dimension, u32 nDensities)
Initialize the Clustering for the given feature dimension and number of densities.
ClusterIndex clusterIndexForDensity (size_t density) const
Maps densities to the assigned cluster index.
ClusterIndexIterator clusterIndexIterator (size_t density) const
Iterator over density to cluster index assignment.
u32 nClusters () const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Attributes
static const Core::ParameterInt paramClusteringIterations
static const Core::ParameterInt paramNumClusters
static const Core::ParameterInt paramSelectClusters
static const Core::ParameterString paramCacheArchive
static const Core::ParameterFloat paramBackoffScore
Protected Member Functions
bool write () const
Save the clustering to the cache.
bool load ()
Load the clustering from the cache.
virtual bool writeMeans (Core::MappedArchiveWriter) const =0
virtual bool readMeans (Core::MappedArchiveReader)=0
virtual bool writeTypes (Core::MappedArchiveWriter) const =0
virtual bool readTypes (Core::MappedArchiveReader) const =0
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes
std::vector< ClusterIndex > clusterIndexForDensity_
u32 nClusters_
u32 nSelected_
u32 dimension_
u32 nDensities_
const float backoffScore_
Protected Attributes inherited from Core::Configurable
Configuration config
Static Protected Attributes
static const std::string FileMagic = "SPRINT-DC"
static const u32 FileFormatVersion = 2
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Detailed Description
Definition at line 29 of file DensityClustering.hh.
Member Function Documentation
ClusterIndex Mm::DensityClusteringBase::clusterIndexForDensity (size_t density) const inline
Maps densities to the assigned cluster index.
Definition at line 51 of file DensityClustering.hh.
ClusterIndexIterator Mm::DensityClusteringBase::clusterIndexIterator (size_t density) const inline
Iterator over density to cluster index assignment.
Iterator starts at the given density index.
Definition at line 57 of file DensityClustering.hh.
void DensityClusteringBase::init (u32 dimension, u32 nDensities)
Initialize the Clustering for the given feature dimension and number of densities.
Must be called before build().
Definition at line 45 of file DensityClustering.cc.
References Core::Component::log(), and verify.
bool DensityClusteringBase::load () protected
Load the clustering from the cache.
Returns false on failure, true on success.
Definition at line 59 of file DensityClustering.cc.
References Core::MappedArchiveReader::check(), Core::Application::getCacheArchiveReader(), Core::MappedArchiveReader::good(), Core::Application::us(), and Core::Component::warning().
bool DensityClusteringBase::write () const protected
Save the clustering to the cache.
Returns whether writing was successful.
Definition at line 82 of file DensityClustering.cc.
References Core::Application::getCacheArchiveWriter(), and Core::Application::us().
The documentation for this class was generated from the following files:
DensityClustering.hh
DensityClustering.cc