Sprint: Speech::FeatureScorer Class Reference
Speech::FeatureScorer Class Reference
FeatureScorer.
#include <FeatureScorer.hh>
Classes
class Accumulator
Public Types
typedef Mm::Score Score
typedef f32 Weight
Public Member Functions
FeatureScorer (const Core::Configuration &configuration)
virtual void signOn (CorpusVisitor &corpusVisitor)
Override this function to sign on to services of the corpus visitor.
virtual void enterSpeechSegment (Bliss::SpeechSegment *)
Override this function to perform preparations before first aligned features arrive.
virtual void leaveSpeechSegment (Bliss::SpeechSegment *)
Override this function to perform post processing after the last aligned features of the segment.
virtual void processAlignedFeature (Core::Ref< const Feature >, Am::AllophoneStateIndex)
Override this function to implement the processing of Viterbi-aligned feature vectors.
virtual void setDataSource (Core::Ref< DataSource >)
Override this function to obtain the data source of corpus processor which produces the labels.
virtual void setFeatureDescription (const Mm::FeatureDescription &description)
Override this function to achieve the attributes of the feature streams.
virtual void setNumberOfLabels (size_t nLabels)
const CorpusKeyToScoreMap & scores () const
void reset ()
void write ()
Public Member Functions inherited from Speech::AcousticModelTrainer
AcousticModelTrainer (const Core::Configuration &c, Am::AcousticModel::Mode mode)
Public Member Functions inherited from Speech::AlignedFeatureProcessor
AlignedFeatureProcessor (const Core::Configuration &c)
virtual void enterCorpus (Bliss::Corpus *)
Override this function to perform preparations before first segment is processed.
virtual void leaveCorpus (Bliss::Corpus *)
Override this function to perform post processing after the last segment is processed.
virtual void enterSegment (Bliss::Segment *)
Override this function to perform preparations before first aligned features arrive.
virtual void leaveSegment (Bliss::Segment *)
Override this function to perform post processing after the last aligned features of the segment.
virtual void processAlignedFeature (Core::Ref< const Feature >, Am::AllophoneStateIndex, Mm::Weight, Mm::Weight)
Override this function to implement the processing of feature vectors with two weights.
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Attributes
static const Core::ParameterString paramWeightPortName
static const Core::ParameterInt paramPrecision
Private Types
typedef AcousticModelTrainer Precursor
typedef Core::StringHashMap< Accumulator > CorpusKeyToScoreMap
Private Member Functions
Weight featureScoreWeight (const Flow::Timestamp &featureTimestamp)
Private Attributes
bool weightScores_
Core::Ref< DataSource > weightSource_
Flow::PortId weightPort_
Core::Ref< Bliss::CorpusKey > corpusKey_
CorpusKeyToScoreMap corpusKeyToScoreMap_
Accumulator segmentAccumulator_
Core::XmlChannel outputChannel_
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Speech::AcousticModelTrainer
Bliss::LexiconRef lexicon () const
Core::Ref< Am::AcousticModel > acousticModel () const
virtual void processAlignedFeature (Core::Ref< const Feature >, Am::AllophoneStateIndex, Mm::Weight)
Override this function to implement the processing of Baum-Welch-aligned feature vectors.
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
FeatureScorer.
Definition at line 25 of file Speech/FeatureScorer.hh.
Member Function Documentation
void FeatureScorer::enterSpeechSegment (Bliss::SpeechSegment *) virtual
Override this function to perform preparations before first aligned features arrive.
Reimplemented from Speech::AlignedFeatureProcessor.
Definition at line 56 of file Speech/FeatureScorer.cc.
void FeatureScorer::leaveSpeechSegment (Bliss::SpeechSegment *) virtual
Override this function to perform post processing after the last aligned features of the segment.
Reimplemented from Speech::AlignedFeatureProcessor.
Definition at line 61 of file Speech/FeatureScorer.cc.
References Core::Component::log().
void FeatureScorer::processAlignedFeature (Core::Ref< const Feature > f, Am::AllophoneStateIndex e) virtual
Override this function to implement the processing of Viterbi-aligned feature vectors.
Reimplemented from Speech::AcousticModelTrainer.
Definition at line 72 of file Speech/FeatureScorer.cc.
References Core::Component::criticalError().
void FeatureScorer::setDataSource (Core::Ref< DataSource >) virtual
Override this function to obtain the data source of corpus processor which produces the labels.
Reimplemented from Speech::AlignedFeatureProcessor.
Definition at line 42 of file Speech/FeatureScorer.cc.
References Core::Component::criticalError(), Flow::Network::getOutput(), and require.
void FeatureScorer::setFeatureDescription (const Mm::FeatureDescription &) virtual
Override this function to achieve the attributes of the feature streams.
This function is called once before the first feature vector is processed.
Reimplemented from Speech::AlignedFeatureProcessor.
Definition at line 98 of file Speech/FeatureScorer.cc.
References Core::Component::criticalError().
void FeatureScorer::signOn (CorpusVisitor & corpusVisitor) virtual
Override this function to sign on to services of the corpus visitor.
Note: call the signOn function of your predecessor.
Reimplemented from Speech::AcousticModelTrainer.
Definition at line 37 of file Speech/FeatureScorer.cc.
The documentation for this class was generated from the following files:
Speech/FeatureScorer.hh
Speech/FeatureScorer.cc