Sprint: Flf::PivotArcCnBuilderNode Class Reference
Flf::PivotArcCnBuilderNode Class Reference
Public Types
enum DistanceFcn { WeightedTimeDistance, WeightedPivotTimeDistance }
Public Types inherited from Flf::Node
typedef u32 Port
typedef Core::Vector< Link > LinkList
Public Member Functions
PivotArcCnBuilderNode (const std::string &name, const Core::Configuration &config)
virtual void init (const std::vector< std::string > &arguments)
init, good, pull, and finalize are making up the used network protocol.
virtual void finalize ()
Finalize is called before any node in the network is deallocated.
virtual ConstLatticeRef sendLattice (Port to)
This section defines send handler for some common data types.
virtual ConstConfusionNetworkRef sendCn (Port to)
virtual void sync ()
Is called at every node before pull is called at the final nodes (see below); all nodes are initialized before sync is called the first time.
Public Member Functions inherited from Flf::Node
LinkList & in ()
LinkList & out ()
bool connected (Port from) const
ConstLatticeRef requestLattice (Port from=0)
This section defines request handler for some common data types.
Fsa::ConstAutomatonRef requestFsa (Port from)
ConstPosteriorCnRef requestPosteriorCn (Port from)
ConstConfusionNetworkRef requestCn (Port from)
ConstSegmentRef requestSegment (Port from)
bool requestBool (Port from)
s32 requestInt (Port from)
f64 requestFloat (Port from)
std::string requestString (Port from)
const void * requestData (Port from)
Node (const std::string &name, const Core::Configuration &config)
virtual bool blockSync () const
virtual bool good ()
Is called immediately after sync and has to return true, iff another data request is accepted.
virtual void pull ()
Is called after a sync for each final node.
virtual Fsa::ConstAutomatonRef sendFsa (Port to)
virtual ConstPosteriorCnRef sendPosteriorCn (Port to)
virtual ConstSegmentRef sendSegment (Port to)
virtual bool sendBool (Port to)
virtual s32 sendInt (Port to)
virtual f64 sendFloat (Port to)
virtual std::string sendString (Port to)
virtual const void * sendData (Port to)
void dump (std::ostream &o) const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Static Public Attributes
static const Core::Choice choiceDistanceFcn
static const Core::ParameterChoice paramDistanceFcn
static const Core::ParameterFloat paramPosteriorImpact
static const Core::ParameterBool paramEditDistance
static const Core::ParameterBool paramFast
static const Core::ParameterBool paramApproximateLatticeBoundaryTimes
static const Core::ParameterString paramConfKey
static const Core::ParameterBool paramMap
Static Public Attributes inherited from Flf::Node
static const Port InvalidPort = Core::Type<Node::Port>::max
Private Member Functions
ConstPivotArcCnBuilderRef getPivotArcCnBuilder (ConstLatticeRef l)
void computeFwdBwd ()
void computePivotArcCn ()
void computeConfidenceId ()
ConstConfusionNetworkRef getCn ()
ConstConfusionNetworkRef getNormalizedCn ()
ConstLatticeRef getBestLattice ()
ConstLatticeRef getUnionLattice ()
Private Attributes
u32 n_
Key confidenceKey_
FwdBwdBuilderRef fbBuilder_
ConstPivotArcCnBuilderRef cnBuilder_
bool map_
ConstLatticeRef union_
ConstFwdBwdRef fb_
ConstPivotArcCnRef pivotCn_
ConstConfusionNetworkRef posteriorCn_
ConstConfusionNetworkRef cn_
ConstLatticeRef best_
ConstSemiringRef lastSemiring_
ScoreId confidenceId_
Additional Inherited Members
Public Attributes inherited from Flf::Node
const std::string name
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Flf::Node
virtual bool init_ (NetworkCrawler &crawler, const std::vector< std::string > &arguments)
init_ is called directly before init(...) init_ should only be used by intermediate nodes and has to be passed through (in opposite to init(...), which should not be used by intermediate nodes at all) dito for sync_ and finalize_
virtual bool sync_ (NetworkCrawler &crawler)
virtual void finalize_ (NetworkCrawler &crawler)
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Definition at line 977 of file PivotArcConfusionNetworkBuilder.cc.
Member Function Documentation
virtual void Flf::PivotArcCnBuilderNode::finalize (void) inline virtual
Finalize is called before any node in the network is deallocated.
Reimplemented from Flf::Node.
Definition at line 1136 of file PivotArcConfusionNetworkBuilder.cc.
virtual void Flf::PivotArcCnBuilderNode::init (const std::vector< std::string > & arguments) inline virtual
init, good, pull, and finalize are making up the used network protocol.
they are called in the following order.
init while good: if is_final_node: pull sync finalize Is called after network is completely build and before the first lattice is processed by any node.
<arguments> is the argument of Core::Appliation::main, i.e. the not-sprint relevant command line arguments.
Reimplemented from Flf::Node.
Definition at line 1114 of file PivotArcConfusionNetworkBuilder.cc.
References Flf::log().
virtual ConstLatticeRef Flf::PivotArcCnBuilderNode::sendLattice (Port to) inline virtual
This section defines send handler for some common data types.
Note: Deliberately, no advanced, powerful, abstract data type handling was implemented. Keep software simple!
Reimplemented from Flf::Node.
Definition at line 1138 of file PivotArcConfusionNetworkBuilder.cc.
References Flf::cn2lattice(), and defect.
virtual void Flf::PivotArcCnBuilderNode::sync () inline virtual
Is called at every node before pull is called at the final nodes (see below); all nodes are initialized before sync is called the first time.
The sync request is propagated from the final nodes through all nodes which return 'false' on blockSync() (see below)
Reimplemented from Flf::Node.
Definition at line 1166 of file PivotArcConfusionNetworkBuilder.cc.
References Core::Ref< T >::reset().
The documentation for this class was generated from the following file:
PivotArcConfusionNetworkBuilder.cc