Sprint: Flow::Network Class Reference
Flow::Network Class Reference
Flow network class.
#include <Network.hh>
Classes
class Parameter
class Port
Public Member Functions
Network (const Core::Configuration &c, bool loadFromFile=true)
void buildFromString (const std::string &network)
Construct network from XML description string.
void buildFromFile (const std::string &filename)
Construct network from XML description file.
void setTypeName (const std::string &typeName)
const std::string & getTypeName () const
bool addNode (AbstractNode *node)
AbstractNode * getNode (const std::string &name)
bool addLink (const std::string &fromNodeName, const std::string &fromPortName, const std::string &toNodeName, const std::string &toPortName, u32 buffer=0)
void declareParameter (const std::string &name)
bool addParameterUse (AbstractNode *node, const std::string &name, const Core::StringExpression &value)
Register a node as user of a parameter.
bool addInput (const std::string &name)
virtual PortId getInput (const std::string &name)
Ask for an input port.
bool addOutput (const std::string &name)
virtual PortId getOutput (const std::string &name)
Ask for an output port.
const std::string & outputName (PortId out) const
void outputs (std::vector< std::pair< PortId, std::string >> &outputs) const
void activateOutput (PortId)
Prepares the output port for external usage.
virtual bool putData (PortId in, Data *d)
Put data on input port of network.
bool putEos (PortId out)
Send end-of-stream on output port.
bool putOod (PortId out)
Send out-of-data on output port.
Link * getPortLink (PortId out)
template<class T >
bool getData (PortId out, DataPtr< T > &d)
Fetch data from output port of network.
bool putAttributes (PortId, Core::Ref< const Attributes >)
Put attribute set on input node of network.
const std::string getAttribute (PortId out, const std::string &name)
Inquire an attribute on an output port of the network.
virtual bool setParameter (const std::string &name, const std::string &value)
Set node specific parameter.
virtual bool configure ()
Creates empy input attibutes for input ports without one an attribute.
virtual bool work (PortId in)
Repeats last non-data input on input port.
virtual ssize_t getRemainingDataLen (PortId out)
Returns the amount of remaining data items.
void reset ()
Resets all links and nodes.
void go ()
void setFilename (const std::string &f)
const std::string & filename () const
Public Member Functions inherited from Flow::AbstractNode
AbstractNode (const Core::Configuration &c)
virtual void Run ()
void setThreaded (bool threaded=true)
void setThreaded (const std::string &threaded)
bool isThreaded () const
virtual bool addParameter (const std::string &name, const Core::StringExpression &value)
addParameter adds a parameter to the node Constant parameters are simply delegated to setParameter, parameters dependent on network parameters are stored in parameters_.
virtual void eraseOutputAttributes ()
Erases attributes of all output links recursively over all successor nodes.
void addUnresolvedParameter (const std::string &key, const std::string &value)
Functions for saving and getting unresolved parameters.
const UnresolvedAttributes & unresolvedAttributes () const
bool operator< (const AbstractNode &n) const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Protected Member Functions
virtual PortId nInputs () const
virtual PortId inputConnected (PortId in) const
bool validInputPort (PortId in) const
virtual PortId nOutputs () const
virtual u32 nOutputLinks (PortId out) const
bool validOutputPort (PortId out) const
virtual PortId connectInputPort (PortId, Link *)
virtual void disconnectInputLink (Link *)
virtual PortId connectOutputPort (PortId, Link *)
virtual void disconnectOutputLink (Link *)
Protected Member Functions inherited from Flow::AbstractNode
template<class T >
bool getData (Link *l, DataPtr< T > &d)
Fetch data packet from the "from" port of link.
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Private Types
typedef AbstractNode Precursor
Private Member Functions
bool dump (const bool initialCall, Core::XmlChannel &dumpChannel, std::set< std::string > *dumpedNetworks=0)
bool connectInputFromInside (const std::string &portName, Link *l, u32 buffer)
Connects a link to a input port 1) connects the repeater output to the link.
bool connectOutputFromInside (const std::string &fromNodeName, const std::string &fromPortName, const std::string &toPortName, Link *l)
Connects a link to a output port 1) sets the link of the port.
bool connectNodeInput (const std::string &nodeName, const std::string &portName, Link *l)
Connects a link to a node input.
bool connectNodeOutput (const std::string &nodeName, const std::string &portName, Link *l)
Connects a link to a node output.
void connectInputPortLink (PortId)
Connects the link of the input port.
void disconnectInputPortLink (PortId)
Disconnects the link of the input port from its repeater node.
void connectOutputPortLink (PortId)
Connects the link of the output port.
void disconnectOutputPortLink (PortId)
Disconnects the link of the output port from its source node.
bool configureOutputPort (Port &out)
Configures the part of the network used by the output port.
bool setUserDefinedParameter (const std::string &name, const std::string &value)
Sets the value of parameter name in each node which uses it.
Private Attributes
Core::XmlChannel dumpChannel_
std::string filename_
std::string typeName_
Name given in network description (e.g.
std::list< Parameter > params_
std::vector< Port > inputs_
Controls if error is generated when setting the value of unknown parameters.
std::vector< Port > outputs_
std::list< AbstractNode * > nodes_
std::list< Link * > links_
bool started_
Data * lastNonData_
Remembers the last non data external input by putEos() or putEos().
Static Private Attributes
static const Core::ParameterString paramFilename
static const std::string inputRepeaterPrefix = "__input_"
Friends
std::ostream & operator<< (std::ostream &o, const Network &n)
Additional Inherited Members
Public Types inherited from Flow::AbstractNode
typedef std::map< std::string, std::string > UnresolvedAttributes
Static Public Attributes inherited from Flow::AbstractNode
static const Core::ParameterBool paramThreaded
static const Core::ParameterBool paramIgnoreUnknownParameters
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Flow network class.
Network serialization procedure:
~Network(): if network's "flow-dump-channel.channel" in the config file is open, call dump()
dump() serializes network's own content and that of each sub-network as XML to the channel
Basic configuration for dumping a network: dump.config: <
pre>
[*.network_to_dump] flow-dump-channel.channel = dump-channel
[*.channels] dump-channel.file = my_network.dump.flow dump-channel.append = false dump-channel.encoding = UTF-8
dump-channel.add-sprint-tags = false
Definition at line 56 of file Flow/Network.hh.
Member Function Documentation
void Network::activateOutput (PortId out)
Prepares the output port for external usage.
Ensures that the link of the output port is connect. This link will be used by getData and getAttribute. Outputs are activated at initialization. If the network is embedded into another one, outputs connected to another node get deactivated. In this way, we can prevent that data objects are put into the port link since these will never be taken out. Use this function only if you explicitely would like to read data from an embedded network.
Definition at line 348 of file Flow/Network.cc.
References Flow::Network::Port::linkConnected(), and require.
bool Network::addParameterUse (AbstractNode * node, const std::string & name, const Core::StringExpression & value)
Register a node as user of a parameter.
Parameters
node is the node which uses the parameter param.
name is the name of the parameter of the node
value is the parameter of the node which has at least one variable referencing a network parameter
Definition at line 382 of file Flow/Network.cc.
References Core::Component::error(), Flow::AbstractNode::getInput(), and Flow::Network::Port::setNode().
Referenced by Flow::NodeBuilder::createNode().
void Network::buildFromFile (const std::string & filename)
Construct network from XML description file.
Failure can be tested with hasFatalErrors().
Definition at line 103 of file Flow/Network.cc.
References Core::Component::error(), and Core::Component::log().
Referenced by Flow::NetworkParser::buildFromFile(), and TestApplication::main().
void Network::buildFromString (const std::string & network)
Construct network from XML description string.
Failure can be tested with hasFatalErrors().
Definition at line 95 of file Flow/Network.cc.
References Core::Component::error().
bool Network::configure () virtual
Creates empy input attibutes for input ports without one an attribute.
Implements Flow::AbstractNode.
Definition at line 655 of file Flow/Network.cc.
References Core::ref(), and Core::Component::warning().
Referenced by getData().
bool Network::configureOutputPort (Port & out) private
Configures the part of the network used by the output port.
Parameters
out.
Definition at line 358 of file Flow/Network.cc.
References Flow::AbstractNode::configure(), ensure, Core::Component::error(), Core::Component::hasFatalErrors(), Flow::Network::Port::linkConnected(), and Core::Application::us().
Referenced by putOod().
bool Network::connectInputFromInside (const std::string & portName, Link * l, u32 buffer) private
Connects a link to a input port 1) connects the repeater output to the link.
Parameters
l 2) creates a link for the port which gets connected to the input of the repeater (
See also
connectInputPortLink).
Definition at line 183 of file Flow/Network.cc.
References Core::Component::error(), Flow::Network::Port::node(), Flow::Network::Port::nodePort(), Flow::Network::Port::setLink(), and verify.
PortId Network::connectInputPort (PortId in, Link * l) protected virtual
Input ports are initialized for external usage, i.e. the input ports are used directly by external calls to Network::putData. If the network is embedded in an other network then the port 'in' is deactivated, i.e. the link of the port is disconnected from its to-node, and the new link 'l' is directly connected to this node.
Implements Flow::AbstractNode.
Definition at line 575 of file Flow/Network.cc.
References defect, ensure, Flow::Network::Port::linkConnected(), Flow::Network::Port::node(), Flow::Network::Port::nodePort(), require, and verify.
void Network::connectInputPortLink (PortId in) private
Connects the link of the input port.
Parameters
port to its repeater node. During initilization, input ports gets connected to the repeater node by a link. This link is used to put data and attributes to the network. The link is automatically disconnected if the network is embedded and the input port is connected to a predecessor node.
Definition at line 286 of file Flow/Network.cc.
References Flow::Network::Port::linkConnected(), Flow::Network::Port::node(), Flow::Network::Port::nodePort(), require, and verify.
bool Network::connectNodeInput (const std::string & nodeName, const std::string & portName, Link * l) private
Connects a link to a node input.
Definition at line 248 of file Flow/Network.cc.
References Core::Component::error(), and Flow::AbstractNode::getInput().
bool Network::connectNodeOutput (const std::string & nodeName, const std::string & portName, Link * l) private
Connects a link to a node output.
Definition at line 267 of file Flow/Network.cc.
References Core::Component::error(), and Flow::AbstractNode::getOutput().
bool Network::connectOutputFromInside (const std::string & fromNodeName, const std::string & fromPortName, const std::string & toPortName, Link * l) private
Connects a link to a output port 1) sets the link of the port.
Parameters
toPortName to
l 2) connects the link to the from node (
See also
connectOutputPortLink).
Definition at line 211 of file Flow/Network.cc.
References Core::Component::error(), Flow::AbstractNode::getOutput(), Flow::Network::Port::node(), Flow::Network::Port::setLink(), and Flow::Network::Port::setNode().
PortId Network::connectOutputPort (PortId out, Link * l) protected virtual
Output ports are initialized for external usage, i.e. the output ports are used directly by external calls to Network::getData. If the network is embedded in an other network then the port 'out' is deactivated, i.e. the link of the port is disconnected from its from-node, and the new link 'l' is directly connected to this node.
Implements Flow::AbstractNode.
Definition at line 606 of file Flow/Network.cc.
References Core::Component::error(), Flow::Network::Port::linkConnected(), Flow::Network::Port::node(), Flow::Network::Port::nodePort(), require, and verify.
void Network::connectOutputPortLink (PortId out) private
Connects the link of the output port.
Parameters
port to its source node. During initilization, output ports gets connected to their source node by a link. This link is used to get data and attributes from the network. The link is automatically disconnected if the network is embedded and the output port is connected to a successor node. In this way, we can prevent that data objects are put into this link since these will never be taken out. To reactivate the port for external usage see avtivateOutput.
Definition at line 318 of file Flow/Network.cc.
References Flow::Network::Port::linkConnected(), Flow::Network::Port::node(), Flow::Network::Port::nodePort(), require, and verify.
void Network::disconnectInputPortLink (PortId in) private
Disconnects the link of the input port from its repeater node.
For more details
See also
connectInputPortLink.
Definition at line 305 of file Flow/Network.cc.
References Flow::Network::Port::linkConnected(), Flow::Network::Port::node(), require, and verify.
void Network::disconnectOutputPortLink (PortId out) private
Disconnects the link of the output port from its source node.
For more details
See also
connectOutputPortLink.
Definition at line 335 of file Flow/Network.cc.
References Flow::Network::Port::linkConnected(), Flow::Network::Port::node(), require, and verify.
const std::string Network::getAttribute (PortId out, const std::string & name)
Inquire an attribute on an output port of the network.
Definition at line 489 of file Flow/Network.cc.
References ensure, Core::Component::error(), Flow::Network::Port::linkConnected(), and require.
Referenced by CorpusVisitor::enterRecording(), and getData().
template<class T > bool Flow::Network::getData (PortId out, DataPtr< T > & d) inline
Fetch data from output port of network.
Definition at line 386 of file Flow/Network.hh.
References configure(), getAttribute(), Flow::AbstractNode::getData(), getRemainingDataLen(), putAttributes(), reset(), setParameter(), and work().
Referenced by Flow::DataSource::getData().
PortId Network::getInput (const std::string &) virtual
Ask for an input port.
Implement this function to provide a mapping form names to port IDs. Consider using a Core::Choice. Remeber to create ports using addInput().
Returns
a valid port ID or IllegalPortId if there is to such port.
Implements Flow::AbstractNode.
Definition at line 428 of file Flow/Network.cc.
PortId Network::getOutput (const std::string &) virtual
Ask for an output port.
Implement this function to provide a mapping form names to port IDs. Consider using a Core::Choice. Remeber to create ports using addOutput().
Returns
a valid port ID or IllegalPortId if there is to such port.
Implements Flow::AbstractNode.
Definition at line 441 of file Flow/Network.cc.
Referenced by Speech::FeatureScorer::setDataSource().
ssize_t Network::getRemainingDataLen (PortId out) virtual
Returns the amount of remaining data items.
Should be fast.
Returns
-1 if not possible to calculate.
Reimplemented from Flow::AbstractNode.
Definition at line 676 of file Flow/Network.cc.
References require.
Referenced by getData().
bool Network::putAttributes (PortId in, Core::Ref< const Attributes > attributes)
Put attribute set on input node of network.
Definition at line 474 of file Flow/Network.cc.
References Flow::Network::Port::linkConnected(), require, and verify.
Referenced by getData().
bool Network::putData (PortId in, Data * d) virtual
Put data on input port of network.
Definition at line 463 of file Flow/Network.cc.
References Flow::Network::Port::linkConnected(), require, and verify.
Referenced by putEos(), and putOod().
bool Flow::Network::putEos (PortId out) inline
Send end-of-stream on output port.
Definition at line 358 of file Flow/Network.hh.
References putData().
bool Flow::Network::putOod (PortId out) inline
Send out-of-data on output port.
Definition at line 362 of file Flow/Network.hh.
References configureOutputPort(), Core::Component::error(), Flow::Network::Port::linkConnected(), putData(), and require.
void Network::reset ()
Resets all links and nodes.
Definition at line 684 of file Flow/Network.cc.
References Flow::AbstractNode::addUnresolvedParameter(), and inputs_.
Referenced by getData().
bool Network::setParameter (const std::string & name, const std::string & value) virtual
Set node specific parameter.
Implement this template function to handle parameters specific to your Node.
Parameters
name name of parameter
value new value for the parameter
Returns
true if successful, false if parameter name is not understood.
Reimplemented from Flow::AbstractNode.
Definition at line 542 of file Flow/Network.cc.
Referenced by CorpusVisitor::enterRecording(), getData(), and Speech::CorpusProcessorNode< CorpusProcessorType >::setParameter().
bool Network::setUserDefinedParameter (const std::string & name, const std::string & value) private
Sets the value of parameter name in each node which uses it.
Definition at line 548 of file Flow/Network.cc.
References verify.
bool Network::work (PortId in) virtual
Repeats last non-data input on input port.
Parameters
in.
Implements Flow::AbstractNode.
Definition at line 668 of file Flow/Network.cc.
References require.
Referenced by getData().
Member Data Documentation
std::vector<Port> Flow::Network::inputs_ private
Controls if error is generated when setting the value of unknown parameters.
Definition at line 199 of file Flow/Network.hh.
Referenced by reset().
Data* Flow::Network::lastNonData_ private
Remembers the last non data external input by putEos() or putEos().
If the input port link is empty the work(...) function is called. The work(...) function sends the lastNonData_ to the first node.
Definition at line 211 of file Flow/Network.hh.
std::string Flow::Network::typeName_ private
Name given in network description (e.g.
: <network name="network">)
Definition at line 191 of file Flow/Network.hh.
The documentation for this class was generated from the following files:
Flow/Network.hh
Flow/Network.cc