Sprint: Search::MinimumBayesRiskSearch Class Reference
Search::MinimumBayesRiskSearch Class Reference
Interface for performing a search for the best string in an Fsa w.r.t.
#include <MinimumBayesRiskSearch.hh>
Public Member Functions
MinimumBayesRiskSearch (const Core::Configuration &)
The only arguments a minimum Bayes risk search takes are a configuration.
virtual ~MinimumBayesRiskSearch ()
Virtual desructor without special purpose.
virtual void performSearch (Fsa::ConstAutomatonRef fsa)
The actual search process will be invoked calling this function.
virtual Fsa::ConstAutomatonRef getBestAutomaton () const
Getter for bestAutomaton .
u32 getEvaluationSpaceSize () const
Getter for evaluationSpace .
u32 getSummationSpaceSize () const
Getter for summationSpaceSize .
u32 getNumberEvaluations () const
Getter for numberEvaluations .
u32 getNumberComputations () const
Getter for numberComputations .
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Protected Attributes
Fsa::ConstAutomatonRef fsa_
The automaton to be searched.
Fsa::ConstAutomatonRef bestAutomaton_
The optimal string represented as a linear Fsa.
u32 evaluationSpaceSize_
The number of hypotheses which can be evaluated during the search.
u32 summationSpaceSize_
The number of hypotheses which are used for the summation in the Bayes risk formula.
u32 numberEvaluations_
The number of hypotheses that were actually used for minimization.
u32 numberComputations_
The number of relevant computations depending on the kind of search.
Core::XmlChannel statisticsChannel_
Protected Attributes inherited from Core::Configurable
Configuration config
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Detailed Description
Interface for performing a search for the best string in an Fsa w.r.t.
minimum Bayes risk. This kind of search takes only an Fsa and a configuration as an argument. For statistics purposes, the number of evaluated hypotheses and the number of computations performed during the search can be optionally computed by the implementing classes.
Definition at line 29 of file Search/MinimumBayesRiskSearch.hh.
Constructor & Destructor Documentation
Search::MinimumBayesRiskSearch::MinimumBayesRiskSearch (const Core::Configuration & config)
The only arguments a minimum Bayes risk search takes are a configuration.
The automaton being searched will be a parameter of the execution of the search.
Parameters
config configuration of the search.
Definition at line 25 of file Search/MinimumBayesRiskSearch.cc.
virtual Search::MinimumBayesRiskSearch::~MinimumBayesRiskSearch () inline virtual
Virtual desructor without special purpose.
Definition at line 68 of file Search/MinimumBayesRiskSearch.hh.
References getBestAutomaton(), getEvaluationSpaceSize(), getNumberComputations(), getNumberEvaluations(), getSummationSpaceSize(), and performSearch().
Member Function Documentation
Fsa::ConstAutomatonRef Search::MinimumBayesRiskSearch::getBestAutomaton () const virtual
Getter for bestAutomaton .
Returns the sentence with minimum Bayes risk as linear Fsa wich has the posterior probability as its weight.
Note: This value is only defined after performSearch was called!
Returns
the sentence having minumum Bayes risk as linear Fsa.
Definition at line 61 of file Search/MinimumBayesRiskSearch.cc.
References bestAutomaton_.
Referenced by Speech::MinimumBayesRiskSearchNode::processWordLattice(), and ~MinimumBayesRiskSearch().
u32 Search::MinimumBayesRiskSearch::getEvaluationSpaceSize () const
Getter for evaluationSpace .
Note: This value is only defined after performSearch was called!
Returns
the number of hypotheses used for minimization of bayes risk.
Definition at line 35 of file Search/MinimumBayesRiskSearch.cc.
References evaluationSpaceSize_.
Referenced by performSearch(), and ~MinimumBayesRiskSearch().
u32 Search::MinimumBayesRiskSearch::getNumberComputations () const
Getter for numberComputations .
The number of relevant computations (e.g. number of Levenshtein distances) strongly depends on the kind of search.
Note: This value is only defined after performSearch was called!
Returns
the number of computations performed during the search.
Definition at line 47 of file Search/MinimumBayesRiskSearch.cc.
References numberComputations_.
Referenced by performSearch(), and ~MinimumBayesRiskSearch().
u32 Search::MinimumBayesRiskSearch::getNumberEvaluations () const
Getter for numberEvaluations .
Hopefully, the actual number of evaluations is much lower than the number of hypotheses that have to be (theoretically) used.
Note: This value is only defined after performSearch was called!
Returns
the number of hypotheses actually used for minimization.
Definition at line 43 of file Search/MinimumBayesRiskSearch.cc.
References numberEvaluations_.
Referenced by performSearch(), and ~MinimumBayesRiskSearch().
u32 Search::MinimumBayesRiskSearch::getSummationSpaceSize () const
Getter for summationSpaceSize .
Note: This value is only defined after performSearch was called!
Returns
the number of hypotheses over which summation will be carried out for Bayes risk.
Definition at line 39 of file Search/MinimumBayesRiskSearch.cc.
References summationSpaceSize_.
Referenced by performSearch(), and ~MinimumBayesRiskSearch().
void Search::MinimumBayesRiskSearch::performSearch (Fsa::ConstAutomatonRef fsa) virtual
The actual search process will be invoked calling this function.
Parameters
fsa the automaton to be searched.
Reimplemented in Search::MinimumBayesRiskAStarSearch, Search::MinimumBayesRiskMapSearch, Search::MinimumBayesRiskNBestListNaiveSearch, and Search::MinimumBayesRiskNBestListSearch.
Definition at line 51 of file Search/MinimumBayesRiskSearch.cc.
References getEvaluationSpaceSize(), getNumberComputations(), getNumberEvaluations(), and getSummationSpaceSize().
Referenced by Search::MinimumBayesRiskNBestListNaiveSearch::performSearch(), Speech::MinimumBayesRiskSearchNode::processWordLattice(), and ~MinimumBayesRiskSearch().
Member Data Documentation
Fsa::ConstAutomatonRef Search::MinimumBayesRiskSearch::bestAutomaton_ protected
The optimal string represented as a linear Fsa.
Definition at line 35 of file Search/MinimumBayesRiskSearch.hh.
Referenced by getBestAutomaton(), Search::MinimumBayesRiskNBestListNaiveSearch::performSearch(), Search::MinimumBayesRiskMapSearch::performSearch(), and Search::MinimumBayesRiskAStarSearch::performSearch().
u32 Search::MinimumBayesRiskSearch::evaluationSpaceSize_ protected
The number of hypotheses which can be evaluated during the search.
I.e. the set of hypotheses over which the minimization will be performed.
Definition at line 41 of file Search/MinimumBayesRiskSearch.hh.
Referenced by getEvaluationSpaceSize(), Search::MinimumBayesRiskNBestListNaiveSearch::performSearch(), and Search::MinimumBayesRiskAStarSearch::performSearch().
Fsa::ConstAutomatonRef Search::MinimumBayesRiskSearch::fsa_ protected
The automaton to be searched.
Definition at line 32 of file Search/MinimumBayesRiskSearch.hh.
Referenced by Search::MinimumBayesRiskAStarSearch::createNewSearchNodes(), Search::MinimumBayesRiskAStarSearch::expand(), Search::MinimumBayesRiskAStarSearch::performSearch(), and Search::MinimumBayesRiskAStarSearch::updateStack().
u32 Search::MinimumBayesRiskSearch::numberComputations_ protected
The number of relevant computations depending on the kind of search.
Definition at line 52 of file Search/MinimumBayesRiskSearch.hh.
Referenced by Search::MinimumBayesRiskAStarSearch::expand(), and getNumberComputations().
u32 Search::MinimumBayesRiskSearch::numberEvaluations_ protected
The number of hypotheses that were actually used for minimization.
Definition at line 49 of file Search/MinimumBayesRiskSearch.hh.
Referenced by Search::MinimumBayesRiskAStarSearch::expand(), and getNumberEvaluations().
u32 Search::MinimumBayesRiskSearch::summationSpaceSize_ protected
The number of hypotheses which are used for the summation in the Bayes risk formula.
Definition at line 46 of file Search/MinimumBayesRiskSearch.hh.
Referenced by getSummationSpaceSize(), Search::MinimumBayesRiskNBestListNaiveSearch::performSearch(), and Search::MinimumBayesRiskAStarSearch::performSearch().
The documentation for this class was generated from the following files:
Search/MinimumBayesRiskSearch.hh
Search/MinimumBayesRiskSearch.cc