Sprint: Flf::IncrementalRecognizer Class Reference
Flf::IncrementalRecognizer Class Reference
Classes
struct RecognizedSequence
Public Member Functions
IncrementalRecognizer (const Core::Configuration &_config, ModelCombinationRef mc, bool backward=false, std::string forwardLmFile=std::string())
bool getData (FeatureRef &feature)
void newSegment ()
void startRecognition (const Bliss::SpeechSegment *segment, bool useDataSource=true)
void putFeature (FeatureRef feature)
void finalize ()
void reset ()
std::pair< ConstLatticeRef, ConstSegmentRef > buildLatticeAndSegment (Core::Ref< const Search::LatticeAdaptor > la)
bool recognitionPending () const
std::pair< ConstLatticeRef, ConstSegmentRef > recognize ()
void finishRecognition ()
Public Member Functions inherited from Speech::Recognizer
Recognizer (const Core::Configuration &)
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Attributes
static const Core::ParameterBool paramMeshRescoring
static const Core::ParameterBool paramExpandTransits
static const Core::ParameterBool paramMeshCombination
static const Core::ParameterBool paramForceForwardBackwardLattices
static const Core::ParameterInt paramRescoreWordEndLimit
static const Core::ParameterBool paramPronunciationScore
static const Core::ParameterBool paramCorrectWholeSegment
static const Core::ParameterBool paramCorrectForceEqualAlignment
static const Core::ParameterBool paramCorrectForceEqualScore
static const Core::ParameterBool paramCorrectStrictInitial
static const Core::ParameterBool paramCorrectIncludeNoise
static const Core::ParameterBool paramConfidenceScore
static const Core::ParameterFloat paramAlpha
static const Core::ParameterBool paramApplyNonWordClosureFilter
static const Core::ParameterBool paramApplyUniqueSentenceAlignmentFilter
static const Core::ParameterFloat paramPosteriorPruningThreshold
static const Core::ParameterBool paramVerboseRefinement
static const Core::ParameterBool paramConsiderSentenceBegin
static const Core::ParameterFloat paramScoreTolerance
static const Core::ParameterBool paramOnlyEnforceMinimumSearchSpace
static const Core::ParameterFloat paramMaxRtf
static const Core::ParameterInt paramCacheFrames
static const Core::ParameterBool paramPreCache
static const Core::ParameterInt paramLmContextLength
static const Core::ParameterFloat paramRelaxPruningFactor
static const Core::ParameterFloat paramRelaxPruningOffset
static const Core::ParameterFloat paramLatticeRelaxPruningFactor
static const Core::ParameterFloat paramLatticeRelaxPruningOffset
static const Core::ParameterFloat paramAdaptInitialUpdateRate
static const Core::ParameterFloat paramAdaptRelaxPruningFactor
static const Core::ParameterFloat paramAdaptRelaxPruningOffset
static const Core::ParameterInt paramLatticeRelaxPruningInterval
static const Core::ParameterInt paramAdaptCorrectionRatio
static const Core::ParameterFloat paramAdaptPruningFactor
static const Core::ParameterFloat paramMinArcsPerSecond
static const Core::ParameterFloat paramMaxArcsPerSecond
static const Core::ParameterInt paramMaxLatticeRegenerations
Static Public Attributes inherited from Speech::Recognizer
static const Core::Choice searchTypeChoice_
static const Core::ParameterChoice paramSearch
Protected Types
enum Extension { ExtendNone = 0, ExtendLeft = 1, ExtendRight = 2, ExtendBoth = 3 }
Protected Types inherited from Speech::Recognizer
typedef Search::SearchAlgorithm::Traceback Traceback
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions
void addPartialToTraceback (Search::SearchAlgorithm::Traceback &partialTraceback)
void processResult ()
ScoresRef buildScore (Fsa::LabelId label, Score amRecogScore, Score lmRecogScore)
std::pair< Flf::ConstLatticeRef, Flf::ConstLatticeRef > recognizeFeatures (const std::deque< FeatureRef > &features)
RecognizedSequence refine (int offset, const std::deque< FeatureRef > &features, const Bliss::LemmaPronunciation *forceFirstWord, const Bliss::LemmaPronunciation *forceLastWord, const std::vector< const Bliss::Lemma * > &lmPrefix, const std::vector< const Bliss::Lemma * > &lmSuffix, bool isInitial=false, bool isSecond=false)
ConstLatticeRef buildLattice (Core::Ref< const Search::LatticeAdaptor > la, bool zeroStartTime)
ConstLatticeRef postProcess (ConstLatticeRef l)
void logTraceback (const Search::SearchAlgorithm::Traceback &traceback)
Protected Member Functions inherited from Speech::Recognizer
void initializeRecognizer (Am::AcousticModel::Mode acousticModelMode)
void initializeRecognizer (const Speech::ModelCombination &)
virtual void createRecognizer ()
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Private Member Functions
f32 globalRtf () const
Private Attributes
std::unique_ptr< Speech::RecognizerDelayHandler > delayedRecognition_
Core::Ref< Mm::ContextScorerCache > contextScorerCache_
ModelCombinationRef mc_
SegmentwiseFeatureExtractorRef featureExtractor_
SegmentwiseModelAdaptorRef modelAdaptor_
Core::XmlChannel tracebackChannel_
Search::SearchAlgorithm::Traceback traceback_
std::vector< Flow::Timestamp > featureTimes_
std::unique_ptr< IncrementalRecognizer > backwardRecognizer_
Core::Timer globalTimer_
u32 segmentFeatureCount_
bool meshRescoring_
bool expandTransits_
bool meshCombination_
bool forceForwardBackwardLattices_
bool addPronunciationScores_
bool correctWholeSegment_
bool correctForceEqualAlignment_
bool correctForceEqualScore_
bool correctIncludeNoise_
bool addConfidenceScores_
bool applyNonWordClosureFilter_
bool applyUniqueSentenceAlignmentFilter_
std::deque< bool > secondOrderCorrectionHistory_
int rescoreWordEndLimit_
Core::Ref< const Bliss::LemmaPronunciationAlphabet > lpAlphabet_
Fsa::LabelId sentenceEndLabel_
LabelMapRef nonWordToEpsilonMap_
Score pronScale_
Score lmScale_
ScoreId amId_
ScoreId pronunciationId_
ScoreId lmId_
ScoreId confidenceId_
ConstSemiringRef semiring_
ConstSemiringRef posteriorSemiring_
Score fwdBwdThreshold_
u32 lmContextLength_
f32 relaxPruningFactor_
f32 relaxPruningOffset_
f32 latticeRelaxPruningFactor_
f32 latticeRelaxPruningOffset_
f32 adaptInitialUpdateRate_
f32 adaptRelaxPruningFactor_
f32 adaptRelaxPruningOffset_
s32 adaptCorrectionRatio_
f32 scoreTolerance_
f32 adaptPruningFactor_
f32 minArcsPerSecond_
f32 maxArcsPerSecond_
s32 maxLatticeRegenerations_
bool onlyEnforceMinimumSearchSpace_
bool correctStrictInitial_
f32 maximumRtf_
u32 latticeRelaxPruningInterval_
const Bliss::SpeechSegment * segment_
u32 subSegment_
bool verboseRefinement_
bool considerSentenceBegin_
bool preCacheAllFrames_
DataSourceRef dataSource_
Additional Inherited Members
Protected Attributes inherited from Speech::Recognizer
Core::Ref< const Bliss::Lexicon > lexicon_
Core::Ref< Am::AcousticModel > acousticModel_
Search::SearchAlgorithm * recognizer_
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Definition at line 553 of file IncrementalRecognizer.cc.
Member Function Documentation
void Flf::IncrementalRecognizer::startRecognition (const Bliss::SpeechSegment * segment, bool useDataSource = true) inline
Todo:
Also check compatibility when using the backward-recognizer. However we need all features.
Definition at line 1699 of file IncrementalRecognizer.cc.
References Lattice::WordLattice::acousticFsa, Flf::decodeRescoreLm(), Speech::DataSource::finalize(), Core::Ref< T >::get(), Speech::DataSource::initialize(), Flf::log(), Core::Ref< T >::reset(), verify, and Search::LatticeAdaptor::wordLattice().
Referenced by Flf::IncrementalRecognizerNode::finalize().
The documentation for this class was generated from the following file:
IncrementalRecognizer.cc