Sprint: Nn::BufferedAlignedFeatureProcessor< T > Class Template Reference
Nn::BufferedAlignedFeatureProcessor< T > Class Template Reference
The class combines the "BufferedFeatureExtractor" and the "AlignedFeatureProcessor" and provides the buffered processing of the features and alignment .
#include <BufferedAlignedFeatureProcessor.hh>
Public Member Functions
BufferedAlignedFeatureProcessor (const Core::Configuration &config, bool loadFromFile=true)
virtual void signOn (Speech::CorpusVisitor &corpusVisitor)
Override this function to sign on to services of the corpus visitor.
virtual void enterSegment (Bliss::Segment *segment)
virtual void leaveSegment (Bliss::Segment *segment)
virtual void leaveCorpus (Bliss::Corpus *corpus)
virtual NeuralNetworkTrainer< T > * createTrainer (const Core::Configuration &config)
Public Member Functions inherited from Speech::AlignedFeatureProcessor
AlignedFeatureProcessor (const Core::Configuration &c)
virtual void enterCorpus (Bliss::Corpus *)
Override this function to perform preparations before first segment is processed.
virtual void enterSpeechSegment (Bliss::SpeechSegment *)
Override this function to perform preparations before first aligned features arrive.
virtual void leaveSpeechSegment (Bliss::SpeechSegment *)
Override this function to perform post processing after the last aligned features of the segment.
virtual void processAlignedFeature (Core::Ref< const Feature >, Am::AllophoneStateIndex, Mm::Weight, Mm::Weight)
Override this function to implement the processing of feature vectors with two weights.
virtual void setDataSource (Core::Ref< DataSource >)
Override this function to obtain the data source of corpus processor which produces the labels.
virtual void setFeatureDescription (const Mm::FeatureDescription &)
Override this function to achieve the attributes of the feature streams.
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Attributes
static const Core::ParameterFloat paramSilenceWeight
static const Core::ParameterString paramClassWeightsFile
static const Core::ParameterBool paramWeightedAlignment
Protected Types
typedef Types< T >::NnVector NnVector
typedef Types< T >::NnMatrix NnMatrix
Protected Types inherited from Nn::BufferedFeatureExtractor< T >
typedef Types< T >::NnVector NnVector
typedef Types< T >::NnMatrix NnMatrix
enum BufferType { minibatch, batch, utterance }
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions
virtual void initAcousticModel ()
virtual void setClassWeights ()
virtual void initTrainer (const std::vector< NnMatrix > &miniBatch)
virtual void initBuffer (Core::Ref< const Speech::Feature > f)
Initialize the feature buffer.
virtual void resetBuffer ()
Update the feature buffer.
virtual void processBuffer ()
virtual void generateMiniBatch (std::vector< NnMatrix > &miniBatch, Math::CudaVector< u32 > &miniBatchAlignment, std::vector< f64 > &miniBatchAlignmentWeights, u32 batchSize)
virtual void processAlignedFeature (Core::Ref< const Speech::Feature > f, Am::AllophoneStateIndex e)
Override this function to implement the processing of Viterbi-aligned feature vectors.
virtual void processAlignedFeature (Core::Ref< const Speech::Feature > f, Am::AllophoneStateIndex e, Mm::Weight w)
Override this function to implement the processing of Baum-Welch-aligned feature vectors.
Mm::EmissionIndex classIndex (Am::AllophoneStateIndex e) const
Protected Member Functions inherited from Nn::BufferedFeatureExtractor< T >
void setWindowedFeature (u32 streamIndex, u32 indexInBuffer, u32 indexInMiniBatch, NnMatrix &miniBatch)
Initialize the shuffling.
void setWindowedFeatureDerivatives (u32 streamIndex, u32 indexInBuffer, u32 indexInMiniBatch, NnMatrix &miniBatch)
void getRelativePositionsInSlidingWindow (u32 indexOfCentralFeature, u32 windowSize, std::vector< s32 > &positions)
void computeFirstDerivative (u32 streamIndex, u32 indexInBuffer)
void computeSecondDerivative (u32 streamIndex, u32 indexInBuffer)
virtual void logProperties () const
void setEnteredSegment (Bliss::Segment *)
bool checkIsTooLongSegment ()
BufferedFeatureExtractor (const Core::Configuration &config, bool loadFromFile=true)
virtual void processSegment ()
virtual void processCorpus ()
virtual void processFeature (Core::Ref< const Speech::Feature > f)
Override this function to achieve the features extracted form data source one-by-one.
u32 bufferSize () const
Returns the maximal size of the (feature) buffer in frames.
u32 numberOfBufferedFeatures () const
Return the current number of buffered features.
bool isShuffled () const
Returns whether data shuffling is active or not.
u32 shuffledIndex (u32 index) const
Return the index of the random feature in the buffer.
u32 batchSize () const
Return the current size of a mini-batch.
Bliss::Segment * getCurSegment () const
returns current segment if in segment mode
virtual void initBuffer (std::vector< u32 > &nFeatures)
Initialize the (feature) buffer.
virtual void updateBufferedFeature (Core::Ref< const Speech::Feature > f)
Initialize the feature buffer.
virtual void prepareProcessBuffer ()
virtual void finalizeProcessBuffer ()
virtual void generateMiniBatch (std::vector< NnMatrix > &miniBatch, u32 batchSize)
virtual void initShuffle ()
Shuffle the indices of the buffer.
Protected Member Functions inherited from Speech::FeatureExtractor
virtual void setFeatureDescription (const Mm::FeatureDescription &)
Override this function to achieve the attributes of the feature streams.
FeatureExtractor (const Core::Configuration &c, bool loadFromFile=true)
virtual void processSegment (Bliss::Segment *segment)
Protected Member Functions inherited from Speech::DataExtractor
void setDataSource (Core::Ref< DataSource > s)
Core::Ref< DataSource > dataSource () const
DataExtractor (const Core::Configuration &c, bool loadFromFile=true)
virtual void enterCorpus (Bliss::Corpus *)
virtual void enterRecording (Bliss::Recording *)
Protected Member Functions inherited from Speech::CorpusProcessor
void reportRealTime (Flow::Time)
CorpusProcessor (const Core::Configuration &c)
virtual void leaveRecording (Bliss::Recording *recoding)
virtual void enterSpeechSegment (Bliss::SpeechSegment *)
virtual void processSpeechSegment (Bliss::SpeechSegment *segment)
virtual void leaveSpeechSegment (Bliss::SpeechSegment *)
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Protected Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Protected Member Functions inherited from Speech::AlignedFeatureProcessor
AlignedFeatureProcessor (const Core::Configuration &c)
virtual void enterCorpus (Bliss::Corpus *)
Override this function to perform preparations before first segment is processed.
virtual void enterSpeechSegment (Bliss::SpeechSegment *)
Override this function to perform preparations before first aligned features arrive.
virtual void leaveSpeechSegment (Bliss::SpeechSegment *)
Override this function to perform post processing after the last aligned features of the segment.
virtual void processAlignedFeature (Core::Ref< const Feature >, Am::AllophoneStateIndex, Mm::Weight, Mm::Weight)
Override this function to implement the processing of feature vectors with two weights.
virtual void setDataSource (Core::Ref< DataSource >)
Override this function to obtain the data source of corpus processor which produces the labels.
virtual void setFeatureDescription (const Mm::FeatureDescription &)
Override this function to achieve the attributes of the feature streams.
Protected Attributes
Core::Ref< const Am::AcousticModel > acousticModel_
Fsa::LabelId silence_
bool acousticModelNeedInit_
ClassLabelWrapper * classLabelWrapper_
Math::Vector< T > classWeights_
std::vector< u32 > alignmentBuffer_
std::vector< Mm::Weight > alignmentWeightsBuffer_
bool weightedAlignment_
Protected Attributes inherited from Nn::BufferedFeatureExtractor< T >
const BufferType bufferType_
const u32 regressionWindowSize_
Type of the buffer (single, batch, sequence)
const u32 slidingWindowSize_
const u32 slidingWindowSizeDerivatives_
bool shuffle_
Flag if feature shuffling is active.
std::vector< Math::FastMatrix< T > > featureBuffer_
std::vector< Math::FastMatrix< T > > derivativesBuffer_
std::vector< u32 > segmentIndexBuffer_
u32 maxBufferSize_
u32 nBufferedFeatures_
Maximal size for the feature buffer.
bool utteranceOverflow_
Number of frames in the feature buffer.
u32 nProcessedFeatures_
Set via checkIsTooLongSegment()
u32 segmentIndex_
Number of processed frames since last call to resetBuffer.
Bliss::Segment * curSegment_
u32 batchSize_
bool derivativesComputed_
Size of a batch in mini-batch mode.
u32 maxBufferedFeatureStreams_
std::vector< u32 > shuffledIndices_
Number of maximal feature streams in the buffer.
std::mt19937 shuffleRandomEngine_
Shuffled indices.
bool processRemainingFeatures_
bool needInit_
u32 nProcessedMiniBatches_
Flag to check for buffer initialization.
u32 totalNumberOfProcessedMiniBatches_
number of processed mini-batches, reset at resetBuffer
NeuralNetworkTrainer< T > * trainer_
not reset until corpus completely processed
Protected Attributes inherited from Speech::CorpusProcessor
Core::XmlChannel channelTimer_
Core::Timer timer_
Protected Attributes inherited from Core::Configurable
Configuration config
Private Types
typedef Core::Component Precursor
typedef BufferedFeatureExtractor< T > PrecursorBuffer
typedef Speech::AlignedFeatureProcessor PrecursorAligned
Additional Inherited Members
Static Protected Attributes inherited from Nn::BufferedFeatureExtractor< T >
static const Core::Choice choiceBufferType
static const Core::ParameterChoice paramBufferType
static const Core::ParameterInt paramBufferSize
static const Core::ParameterBool paramShuffleBuffer
static const Core::ParameterInt paramShuffleBufferSeed
static const Core::ParameterInt paramBatchSize
static const Core::ParameterInt paramRegressionWindowSize
static const Core::ParameterInt paramSlidingWindowSize
static const Core::ParameterInt paramSlidingWindowSizeDerivatives
Detailed Description
template<class T>
class Nn::BufferedAlignedFeatureProcessor< T >
The class combines the "BufferedFeatureExtractor" and the "AlignedFeatureProcessor" and provides the buffered processing of the features and alignment .
This should be used by Speech::AligningFeatureExtractor.
Definition at line 43 of file BufferedAlignedFeatureProcessor.hh.
Member Function Documentation
template<typename T > void BufferedAlignedFeatureProcessor::initBuffer (Core::Ref< const Speech::Feature > f) protected virtual
Initialize the feature buffer.
Reimplemented from Nn::BufferedFeatureExtractor< T >.
Definition at line 108 of file BufferedAlignedFeatureProcessor.cc.
template<typename T > void BufferedAlignedFeatureProcessor::processAlignedFeature (Core::Ref< const Speech::Feature > f, Am::AllophoneStateIndex e) protected virtual
Override this function to implement the processing of Viterbi-aligned feature vectors.
Reimplemented from Speech::AlignedFeatureProcessor.
Definition at line 124 of file BufferedAlignedFeatureProcessor.cc.
template<typename T > void BufferedAlignedFeatureProcessor::processAlignedFeature (Core::Ref< const Speech::Feature > , Am::AllophoneStateIndex , Mm::Weight) protected virtual
Override this function to implement the processing of Baum-Welch-aligned feature vectors.
Reimplemented from Speech::AlignedFeatureProcessor.
Definition at line 129 of file BufferedAlignedFeatureProcessor.cc.
References Core::Component::log(), Flf::log(), Nn::BufferedFeatureExtractor< f32 >::processFeature(), and require.
template<typename T > void BufferedAlignedFeatureProcessor::resetBuffer () protected virtual
Update the feature buffer.
Reset the feature buffer.
Clean up and free the feature buffer. The current number of frames are set to 0. The buffer has to be initialized again when used.
Reimplemented from Nn::BufferedFeatureExtractor< T >.
Definition at line 116 of file BufferedAlignedFeatureProcessor.cc.
template<class T> virtual void Nn::BufferedAlignedFeatureProcessor< T >::signOn (Speech::CorpusVisitor & corpusVisitor) inline virtual
Override this function to sign on to services of the corpus visitor.
Note: call the signOn function of your predecessor.
Reimplemented from Nn::BufferedFeatureExtractor< T >.
Definition at line 84 of file BufferedAlignedFeatureProcessor.hh.
The documentation for this class was generated from the following files:
BufferedAlignedFeatureProcessor.hh
BufferedAlignedFeatureProcessor.cc