Sprint: Core::Configuration Class Reference
Core::Configuration Class Reference
Central configuration class.
#include <Configuration.hh>
Classes
class Resource
Item of configuration.
class ResourceDataBase
Central storage place for all resources.
class SourceDescriptor
Describes where a resource comes from.
Public Member Functions
Configuration (const Configuration &c, const std::string &selection)
Configuration (const Configuration &c)
Configuration & operator= (const Configuration &c)
void enableLogging ()
Enable logging facility.
void writeSources (XmlWriter &) const
Report where configuration ressources came from.
void writeResolvedResources (XmlWriter &) const
Report all configuration resolved resources in the database.
void writeResources (XmlWriter &) const
Report all configuration resources in the database.
void writeUsage (XmlWriter &) const
Report how configuration ressources where used by which parameters.
const std::string & getSelection () const
const std::string & getName () const
void setSelection (const std::string &selection)
void set (const std::string &name, const std::string &value="true", const SourceDescriptor *source=0)
Add a resource.
bool tryToSet (const std::string &name, const std::string &value="true", const SourceDescriptor *source=0)
Try to add a resource.
bool setFromEnvironment (const std::string &variable)
bool setFromFile (const std::string &filename)
std::vector< std::string > setFromCommandline (const std::vector< std::string > &arguments)
bool get (const std::string &parameter, std::string &value) const
Query the configuration for a parameter.
std::string resolve (const std::string &value) const
Substitutes all parameter references, arithmetic expressions and cache manager commands in a string.
Static Public Member Functions
static bool isWellFormedResourceName (const std::string &)
Test if argument is a well-formed resource name.
static bool isWellFormedParameterName (const std::string &)
Test if argument is a well-formed parameter name.
static std::string prepareResourceName (const std::string &selection, const std::string &name)
static std::string resolveArithmeticExpressions (const std::string &value)
Substitute arithmetic expressions in a string.
Static Public Attributes
static const char resource_wildcard_char = '*'
static const char * resource_wildcard_string = "*"
static const char resource_separation_char = '.'
static const char * resource_separation_string = "."
Private Member Functions
void warning (const std::string &filename, int lineNumber, const std::string &description)
void error (const std::string &filename, int lineNumber, const std::string &description)
bool parseInclude (const std::string &line, std::string &includeFilename, std::string &warningDescription)
Parses include.
bool parseSelection (const std::string &line, std::string &selection, std::string &warningDescription)
bool parseComment (const std::string &line, std::string &warningDescription)
bool parseResource (const std::string &line, std::string &parameter, std::string &value, std::string &warningDescription)
bool setFromFile (const std::string &filename, const std::string &currentSelection)
std::vector< std::string > setFromCommandline (const std::vector< std::string > &arguments, const SourceDescriptor *source)
const Resource * find (const std::string &parameter) const
Find the resource for a given parameter.
std::string resolveReferences (const std::string &value) const
Substitute parameter references in a string.
std::string getResolvedValue (const Resource *resource) const
Static Private Member Functions
static bool isWellFormedName (const std::string &, bool allowWildcards)
Private Attributes
ResourceDataBase * db_
bool isDataBaseOwner_
std::string selection_
std::string name_
Detailed Description
Central configuration class.
Configuration
Definition at line 87 of file Configuration.hh.
Member Function Documentation
void Configuration::enableLogging ()
Enable logging facility.
Definition at line 973 of file Configuration.cc.
Referenced by Core::Application::openLogging().
const Configuration::Resource * Configuration::find (const std::string & parameter) const private
Find the resource for a given parameter.
Parameters
parameter the parameter specification string
Returns
the most specific resource matching parameter
Definition at line 815 of file Configuration.cc.
References resolve().
Referenced by get(), parseInclude(), and resolveReferences().
bool Configuration::get (const std::string & parameter, std::string & value) const
Query the configuration for a parameter.
It is strongly discouraged to use get() directly use one of the Parameter classes instead.
See also
Parameter
Parameters
parameter is the parameter identification string
value The value of the queried parameter is stored in value. Remains unchanged if the parameter is not specified in the configuration.
Returns
true if the parameter was configured
Definition at line 952 of file Configuration.cc.
References find(), and require.
Referenced by Flow::AbstractNode::checkAndSetParameter(), Core::ParameterBitVector::parseString(), Core::StringExpression::setVariables(), and AcousticModelTrainer::showMixtureSet().
bool Configuration::isWellFormedParameterName (const std::string & s) static
Test if argument is a well-formed parameter name.
A string is a well-formed resource name iff it matches the regular grammar: S -> [a-zA-Z0-1]+ | S '.' S
Definition at line 398 of file Configuration.cc.
References ensure, isWellFormedResourceName(), and require.
Referenced by Core::Configuration::ResourceDataBase::find(), and resolveReferences().
bool Configuration::isWellFormedResourceName (const std::string & s) static
Test if argument is a well-formed resource name.
A string is a well-formed resource name iff it matches the regular grammar: S -> '*' | [a-zA-Z0-1]+ | S '.' S
Definition at line 394 of file Configuration.cc.
Referenced by isWellFormedParameterName(), parseInclude(), Core::Configuration::ResourceDataBase::set(), set(), and tryToSet().
bool Configuration::parseInclude (const std::string & line, std::string & includeFilename, std::string & warningDescription) private
Parses include.
Syntax: include filename Include can be used within a selection as well. In this case, the including selection will be active until the first selection in the included file.
Definition at line 622 of file Configuration.cc.
References find(), Core::Application::getCommentCharacters(), Core::getline(), isWellFormedResourceName(), resolve(), tryToSet(), Core::Application::us(), and verify.
Referenced by tryToSet().
std::string Configuration::resolve (const std::string & value) const
Substitutes all parameter references, arithmetic expressions and cache manager commands in a string.
Cache manager commands are only resolved if the corresponding module is enabled
See also
Configuration::resolveReferences
Configuration::resolveArithmeticExpressions
Definition at line 839 of file Configuration.cc.
References resolveArithmeticExpressions(), and resolveReferences().
Referenced by find(), parseInclude(), and tryToSet().
std::string Configuration::resolveArithmeticExpressions (const std::string & value) static
Substitute arithmetic expressions in a string.
All occurances of $[expression] are substituted. expression can be any valid arithmetic expression, including standard math funcions. To cast the result of the expression to a specific type, use $[expression,format] Format may be int or float, default is float. Parameter references are not resolved! So use resolveReferences before.
Parameters
value is a string which may contain arithmetic expressions
Returns
value with all arith. expressions subsituted
Definition at line 899 of file Configuration.cc.
References Core::form(), and Core::stripWhitespace().
Referenced by resolve().
std::string Configuration::resolveReferences (const std::string & value) const private
Substitute parameter references in a string.
All occurances of are substituted based on the configuration. resolve() works recursively if necessary. resolve() will first try to find a resource for the reference expanded by the current selection (local lookup). If that fails the selection if succesively shortened until the unexpanded string is tried (global lookup). (So we try A.B.C.REF, A.B.REF, A.REF and REF in this order until one of them is found.)
Warning
Note that the result of local lookup depends on the Configuration which initiates the resolution!
resolve() is intended for transformation of strings given by the user. Do NOT use resolve() like this: resolve("$(fudge)"); use one of the Parameter classes instead.
See also
Parameter
Parameters
value is a string which may contain configuration references.
Returns
value with all references substituted.
Definition at line 846 of file Configuration.cc.
References find(), and isWellFormedParameterName().
Referenced by resolve().
void Configuration::set (const std::string & name, const std::string & value = "true", const SourceDescriptor * source = 0)
Add a resource.
If a resource with the same name already exists, its value is replaced.
Parameters
name of the resource to be added
value of the resource
Definition at line 493 of file Configuration.cc.
References isWellFormedResourceName(), and require.
bool Configuration::tryToSet (const std::string & name, const std::string & value = "true", const SourceDescriptor * source = 0)
Try to add a resource.
This is a safe veriosn of set(). If the resource name is not well-formed, an error message is printed and no resource is set.
Returns
true is name is well-formed.
See also
set()
Definition at line 511 of file Configuration.cc.
References Core::directoryName(), Core::getline(), Core::isRegularFile(), isWellFormedResourceName(), Core::joinPaths(), parseInclude(), and resolve().
Referenced by parseInclude().
void Configuration::writeResolvedResources (XmlWriter & os) const
Report all configuration resolved resources in the database.
Definition at line 988 of file Configuration.cc.
Referenced by Core::Application::setCommentCharacters().
void Configuration::writeResources (XmlWriter & os) const
Report all configuration resources in the database.
Definition at line 981 of file Configuration.cc.
Referenced by Core::Application::setCommentCharacters().
void Configuration::writeSources (XmlWriter & os) const
Report where configuration ressources came from.
Definition at line 977 of file Configuration.cc.
Referenced by Core::Application::setCommentCharacters().
void Configuration::writeUsage (XmlWriter & os) const
Report how configuration ressources where used by which parameters.
Definition at line 1001 of file Configuration.cc.
Referenced by Core::Application::setCommentCharacters().
The documentation for this class was generated from the following files:
Configuration.hh
Configuration.cc