Sprint: Search::LanguageModelLookahead Class Reference
Search::LanguageModelLookahead Class Reference
Language model look-ahead.
#include <LanguageModelLookahead.hh>
Classes
struct CacheStatistics
class ConstructionNode
class ConstructionTree
class ContextLookahead
struct Node
Public Types
typedef u32 LookaheadId
typedef f32 Score
typedef Core::Ref< const ContextLookahead > ContextLookaheadReference
Public Member Functions
LanguageModelLookahead (const Core::Configuration &, Lm::Score wpScale, Core::Ref< const Lm::ScaledLanguageModel >, const StateTree *)
void draw (std::ostream &) const
LookaheadId lookaheadId (StateTree::StateId s) const
ContextLookaheadReference getLookahead (const Lm::History &) const
ContextLookaheadReference tryToGetLookahead (const Lm::History &) const
void collectStatistics () const
void logStatistics () const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Attributes
static const Core::ParameterInt paramHistoryLimit
static const Core::ParameterInt paramTreeCutoff
static const Core::ParameterInt paramMinimumRepresentation
static const Core::ParameterInt paramCacheSizeLow
static const Core::ParameterInt paramCacheSizeHigh
Private Types
typedef std::vector< const Bliss::LemmaPronunciation * > Ends
typedef std::vector< LookaheadId > Successors
typedef std::list< ContextLookahead * > List
typedef std::unordered_map< Lm::History, ContextLookahead *, Lm::History::Hash > Map
Private Member Functions
bool shouldPruneConstructionNode (const ConstructionNode &sn) const
Decide whether a look-ahead node should be merged with its father.
void buildCompressesLookaheadStructure (const StateTree *, const ConstructionTree &)
Initialize internal compact look-ahead structure from construction tree.
void buildBatchRequest ()
void buildLookaheadStructure (const StateTree *)
void computeScores (const Lm::History &, std::vector< Score > &) const
ContextLookahead * acquireTable (const Lm::History &) const
ContextLookahead * getCachedTable (const Lm::History &) const
void releaseTable (const ContextLookahead *) const
u32 nTables () const
u32 nActiveTables () const
Private Attributes
u32 historyLimit_
s32 cutoffDepth_
u32 minimumRepresentation_
Lm::Score wpScale_
Core::Ref< const Lm::ScaledLanguageModel > lm_
Ends ends_
Successors successors_
std::vector< Node > nodes_
LookaheadId nEntries_
std::vector< LookaheadId > nodeId_
const Lm::CompiledBatchRequest * batchRequest_
u32 cacheSizeHighMark_
u32 cacheSizeLowMark_
List tables_
List freeTables_
u32 nTables_
u32 nFreeTables_
Map map_
CacheStatistics * cacheStatistics_
Core::XmlChannel statisticsChannel_
Static Private Attributes
static const LookaheadId invalidId = Core::Type<LanguageModelLookahead::LookaheadId>::max
Friends
class LanguageModelLookahead::ConstructionTree
class ContextLookahead
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Language model look-ahead.
Definition at line 34 of file LanguageModelLookahead.hh.
Member Function Documentation
void LanguageModelLookahead::buildCompressesLookaheadStructure (const StateTree * st, const ConstructionTree & ct) private
Initialize internal compact look-ahead structure from construction tree.
Definition at line 474 of file LanguageModelLookahead.cc.
References Search::LanguageModelLookahead::ConstructionTree::build(), ensure, Core::form(), Core::Configurable::fullName(), Core::Channel::isOpen(), Search::LanguageModelLookahead::ConstructionTree::isWellOrdered(), Search::LanguageModelLookahead::ConstructionTree::prune(), Search::LanguageModelLookahead::ConstructionTree::purge(), require, and verify.
bool LanguageModelLookahead::shouldPruneConstructionNode (const ConstructionNode & sn) const private
Decide whether a look-ahead node should be merged with its father.
Definition at line 416 of file LanguageModelLookahead.cc.
References ensure, Search::LanguageModelLookahead::ConstructionTree::prune(), Search::LanguageModelLookahead::ConstructionTree::purge(), shouldPruneConstructionNode(), and verify.
Referenced by Search::LanguageModelLookahead::ConstructionTree::prune(), and shouldPruneConstructionNode().
The documentation for this class was generated from the following files:
LanguageModelLookahead.hh
LanguageModelLookahead.cc