Sprint: Lm::BackingOffLm Class Reference
Lm::BackingOffLm Class Reference abstract
General backing-off language model.
#include <BackingOff.hh>
Classes
class Automaton
struct BackOffScores
struct InitItem
Back-off language model item.
class Internal
class Node
struct WordScore
Public Types
typedef Node HistoryDescriptor
Public Member Functions
virtual void load ()
virtual History startHistory () const
Language model history for beginning of a sentence.
virtual Lm::Score sentenceBeginScore () const
virtual History extendedHistory (const History &, Token w) const
Language model history for the next sentence position.
virtual History reducedHistory (const History &, u32 limit) const
Reduce amount on conditioning information.
virtual std::string formatHistory (const History &) const
Create string representation of history (mainly for debugging purposes).
virtual Lm::Score score (const History &, Token w) const
Probability of a token to occur with a given history.
virtual void getBatch (const History &, const CompiledBatchRequest *, std::vector< f32 > &result) const
Get probabilities for a (large) set of syntactic tokens given a history.
virtual Fsa::ConstAutomatonRef getFsa () const
Convert language model into an EQUIVALENT acceptor.
void historyTokens (const History &history, const Bliss::Token **target, u32 &size, u32 arraySize) const
Writes all tokens stored in the given history into the given vector.
u32 historyLenght (const History &history) const
BackOffScores getBackOffScores (const History &history, int depth=0) const
Directly returns the scores stored in the LM for the given context history.
Score getAccumulatedBackOffScore (const History &history, int limit) const
Returns the accumulated backing-off scores up the the given limit (not the actual contained word-scores) Examples: With limit 0, returns the sum of the back-off offsets up to the zerogram level.
Public Member Functions inherited from Lm::LanguageModel
Token sentenceBeginToken () const
Token sentenceEndToken () const
Token sentenceBoundaryToken () const
virtual void init ()
precondition: the token inventory is set and fixed
virtual void getDependencies (Core::DependencySet &dependencies) const
Bliss::LexiconRef lexicon () const
const TokenInventory & tokenInventory () const
Fsa::ConstAlphabetRef tokenAlphabet () const
virtual bool scoreCached (const History &, Token w) const
Some LMs might cache scores and thus provide fast access.
virtual Score sentenceEndScore (const History &) const
Probability for sentence to end in current position.
virtual CompiledBatchRequest * compileBatchRequest (const BatchRequest &, Score scale=1.0) const
Preprocess a batch request.
virtual Core::Ref< const LanguageModel > lookaheadLanguageModel () const
Returns the LanguageModel that shall be used for lookahead (useful for CombinedLM when we do not want to reinstanciate the model)
virtual Core::Ref< const LanguageModel > recombinationLanguageModel () const
Returns the LanguageModel that shall be used for recombination (useful for CombinedLM when we do not want to reinstanciate the model)
virtual void setSegment (Bliss::SpeechSegment const *s)
For some cheating language models we need to know the correct transcription.
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Protected Member Functions
BackingOffLm (const Core::Configuration &, Bliss::LexiconRef)
void initialize (InitItem *begin, InitItem *end)
Initialize back-off language model from list of InitItems.
void initialize (Core::Ref< Internal >)
Alternative initialization method.
virtual void read ()=0
Implement this this function to read the language model from a file.
Protected Member Functions inherited from Lm::LanguageModel
History history (HistoryHandle hd) const
template<class LM >
const LM::HistoryDescriptor * descriptor (const History &hh) const
void setTokenInventory (const TokenInventory *_tokenInventory)
void setTokenInventoryAndAlphabet (const TokenInventory *_tokenInventory, Fsa::ConstAlphabetRef _tokenAlphabet)
Token getToken (const std::string &word) const
virtual Token getSpecialToken (const std::string &name, bool required=false) const
const Bliss::SyntacticToken * getSpecialSyntacticToken (const std::string &name, bool required) const
Token fallbackToken () const
Find token to use for unknown words.
virtual void createSpecialTokens ()
void requireSentenceBoundaryToken ()
Call this function before init(), iff your language model requires a sentence boundary token to be defined in the lexicon.
LanguageModel (const Core::Configuration &c, Bliss::LexiconRef l)
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Private Types
typedef BackingOffLm Self
Private Member Functions
void logInitialization () const
Private Attributes
Core::Ref< Internal > internal_
Static Private Attributes
static const Core::ParameterString paramImage
Friends
class Internal
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Attributes inherited from Lm::LanguageModel
HistoryManager * historyManager_
Concrete LanguageModels should set this member in their constructor or load() method.
Core::Dependency dependency_
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
General backing-off language model.
Decendant classes only have to implement the read() method, which should build a range of InitItem and call initialize().
Definition at line 33 of file BackingOff.hh.
Member Function Documentation
History BackingOffLm::extendedHistory (const History & , Token w) const virtual
Language model history for the next sentence position.
This is the given history with given word appended, i.e. w becomes the most recent word. Typically the returned history will reflect the finite memory of the language model: for an m-gram it will only contain the m-1 most recent words. In WFST terminology this is the target state of the outgoin arc labeled w.
Implements Lm::LanguageModel.
Reimplemented in Lm::ArpaClassLm.
Definition at line 839 of file BackingOff.cc.
References Bliss::Token::id().
std::string BackingOffLm::formatHistory (const History & h) const virtual
Create string representation of history (mainly for debugging purposes).
By default this function just delegates to History::format(), but language models may specialize formatHistory() to give more readable information, which would be inaccessible from the HistoryDescriptor alone. If your language model is m-gram like, describe the history chronologically, i.e. most recent word last.
Reimplemented from Lm::LanguageModel.
Definition at line 863 of file BackingOff.cc.
Score BackingOffLm::getAccumulatedBackOffScore (const History & history, int limit) const
Returns the accumulated backing-off scores up the the given limit (not the actual contained word-scores) Examples: With limit 0, returns the sum of the back-off offsets up to the zerogram level.
With limit 1, returns the sum of the back-off offsets up to the unigram level.
Definition at line 882 of file BackingOff.cc.
BackingOffLm::BackOffScores BackingOffLm::getBackOffScores (const History & history, int depth = 0) const
Directly returns the scores stored in the LM for the given context history.
Definition at line 891 of file BackingOff.cc.
References verify.
Referenced by AdvancedTreeSearch::LanguageModelLookahead::computeScoresSparse(), and Search::SearchSpace::getBackOffInstance().
void BackingOffLm::getBatch (const History & h, const CompiledBatchRequest * r, std::vector< f32 > & result) const virtual
Get probabilities for a (large) set of syntactic tokens given a history.
This is mainly useful for LanguageModelLookahead.
Warning
Default implementation is inefficient.
Parameters
h history
r pre-compiled batch request created using compileBatchRequest()
result a vector in which results are stored (output parameter)
Reimplemented from Lm::LanguageModel.
Definition at line 914 of file BackingOff.cc.
References Bliss::Token::id(), and required_cast.
Fsa::ConstAutomatonRef BackingOffLm::getFsa () const virtual
Convert language model into an EQUIVALENT acceptor.
Keep in mind that the default method may produce transducers that are very large. Note: This does just convert your language model to a different format, it does NOT implement the language model.
Labels of the resulting acceptor are syntactic token ids.
Reimplemented from Lm::LanguageModel.
Reimplemented in Lm::ArpaClassLm.
Definition at line 1023 of file BackingOff.cc.
References Core::ref().
void BackingOffLm::historyTokens (const History & history, const Bliss::Token ** target, u32 & size, u32 arraySize) const
Writes all tokens stored in the given history into the given vector.
Definition at line 821 of file BackingOff.cc.
void BackingOffLm::initialize (InitItem * begin, InitItem * end) protected
Initialize back-off language model from list of InitItems.
Should be called from read(). The input data may be modified during the call, and is no longer needed afterwards.
Definition at line 686 of file BackingOff.cc.
References Core::ref().
void BackingOffLm::initialize (Core::Ref< Internal > i) protected
Alternative initialization method.
Should be called from read(). Build everything yourself, and pass over the finished internal data structure.
Definition at line 711 of file BackingOff.cc.
References Core::Ref< T >::get(), Core::Channel::isOpen(), Core::isRegularFile(), and Core::ref().
virtual void Lm::BackingOffLm::read () protected pure virtual
Implement this this function to read the language model from a file.
Implemented in Lm::ArpaLm.
History BackingOffLm::reducedHistory (const History & h, u32 limit) const virtual
Reduce amount on conditioning information.
In theory extendHistory() adds more and more information to the distory descriptor. Most reasonable language models will drop irrelevant information. E.g. a trigram LM will actually store only two words in its history objects; so the number of distinct histories is size of vocabulary squared. In some situations one wants to limit the number of histories considered, by reducing the amount of conditioning information in the history. E.g. when using a bigram lookahead in a trigram search. This is the purpose of reducedHistory().
Parameters
limit Maximum amount of conditioning information in the returned history. The meaning this parameter is dependent on the language model. In general higher values mean more longer histories. The default implementation returns the given history unchanged.
Reimplemented from Lm::LanguageModel.
Definition at line 843 of file BackingOff.cc.
References Bliss::Token::symbol().
Referenced by AdvancedTreeSearch::LanguageModelLookahead::computeScoresSparse(), and Search::SearchSpace::getBackOffInstance().
Lm::Score BackingOffLm::score (const History & , Token w) const virtual
Probability of a token to occur with a given history.
Returns
: negative natural(!) logarithm of probability of the token w to occur with history h , i.e. -log(p(w|h))
Note on syntactic classes: The Bliss lexicon can map several lexicon entries (lemmas) to the same syntactic token. Conceptually we can write this case as p(lemma | history) = p(lemma | synt) p(synt | history). However this function returns only p(synt | history). Clients have to add the lemmaScore -log(p(lemma | synt)) when needed.
Note on pronunciation variants: Pronuciation probabilities are not into account.
Implements Lm::LanguageModel.
Reimplemented in Lm::ArpaClassLm.
Definition at line 878 of file BackingOff.cc.
References Bliss::Token::id().
History BackingOffLm::startHistory () const virtual
Language model history for beginning of a sentence.
Typically this is the bigram history which contains just the sentence start (or boundary) token. In the terminology of finite-state automata this is the initial state.
Implements Lm::LanguageModel.
Definition at line 800 of file BackingOff.cc.
The documentation for this class was generated from the following files:
BackingOff.hh
BackingOff.cc