Sprint: Speech::CovarianceEstimator Class Reference
Speech::CovarianceEstimator Class Reference
Public Member Functions
CovarianceEstimator (const Core::Configuration &c)
Public Member Functions inherited from Speech::FeatureExtractor
FeatureExtractor (const Core::Configuration &c, bool loadFromFile=true)
virtual void processSegment (Bliss::Segment *segment)
Public Member Functions inherited from Speech::DataExtractor
DataExtractor (const Core::Configuration &c, bool loadFromFile=true)
virtual void signOn (CorpusVisitor &corpusVisitor)
Override this function to sign on to services of the corpus visitor.
virtual void enterCorpus (Bliss::Corpus *)
virtual void leaveCorpus (Bliss::Corpus *)
virtual void enterRecording (Bliss::Recording *)
virtual void enterSegment (Bliss::Segment *)
virtual void leaveSegment (Bliss::Segment *)
Public Member Functions inherited from Speech::CorpusProcessor
CorpusProcessor (const Core::Configuration &c)
virtual void leaveRecording (Bliss::Recording *recoding)
virtual void enterSpeechSegment (Bliss::SpeechSegment *)
virtual void processSpeechSegment (Bliss::SpeechSegment *segment)
virtual void leaveSpeechSegment (Bliss::SpeechSegment *)
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Signal::TotalScatterMatrixEstimator
TotalScatterMatrixEstimator (const Core::Configuration &c)
void accumulate (const Math::Vector< Data > &)
bool finalize (ScatterMatrix &covarianceMatrix)
bool write ()
Saves covariance matrix.
Public Member Functions inherited from Signal::ScatterMatrixEstimator
ScatterMatrixEstimator (const Core::Configuration &c)
void setDimension (size_t dimension)
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Protected Member Functions
virtual void processFeature (Core::Ref< const Feature > feature)
Override this function to achieve the features extracted form data source one-by-one.
virtual void setFeatureDescription (const Mm::FeatureDescription &description)
Override this function to achieve the attributes of the feature streams.
Protected Member Functions inherited from Speech::DataExtractor
void setDataSource (Core::Ref< DataSource > s)
Core::Ref< DataSource > dataSource () const
Protected Member Functions inherited from Speech::CorpusProcessor
void reportRealTime (Flow::Time)
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Member Functions inherited from Signal::TotalScatterMatrixEstimator
void initialize ()
Protected Member Functions inherited from Signal::ScatterMatrixEstimator
void initialize ()
void accumulate (const Math::Vector< Data > &, f32 weight=1.0)
bool accumulate (const ScatterMatrixEstimator &)
bool finalize ()
bool write (const std::string &filename, const std::string &scatterType, const ScatterMatrix &scatterMatrix)
virtual bool read (Core::BinaryInputStream &)
virtual bool write (Core::BinaryOutputStream &)
Private Types
typedef FeatureExtractor Extractor
typedef Signal::TotalScatterMatrixEstimator Estimator
Private Attributes
bool needResize_
Additional Inherited Members
Public Types inherited from Signal::ScatterMatrixEstimator
typedef u32 ClassIndex
typedef f32 Data
typedef f64 Sum
typedef f64 Count
typedef Math::Matrix< Sum > ScatterMatrix
Static Public Attributes inherited from Signal::ScatterMatrixEstimator
static const Core::ParameterInt paramOutputPrecision
static const Core::ParameterBool paramShallNormalize
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Attributes inherited from Speech::CorpusProcessor
Core::XmlChannel channelTimer_
Core::Timer timer_
Protected Attributes inherited from Core::Configurable
Configuration config
Protected Attributes inherited from Signal::TotalScatterMatrixEstimator
Math::Vector< Sum > vectorSum_
Count count_
Protected Attributes inherited from Signal::ScatterMatrixEstimator
size_t featureDimension_
Math::Matrix< Sum > vectorSquareSum_
Accumulates covariance matrix Remark: accumulate only lower triangle, because of symmetry.
bool needInit_
Detailed Description
Definition at line 23 of file CovarianceEstimator.hh.
Member Function Documentation
void CovarianceEstimator::processFeature (Core::Ref< const Feature >) protected virtual
Override this function to achieve the features extracted form data source one-by-one.
Reimplemented from Speech::FeatureExtractor.
Definition at line 25 of file CovarianceEstimator.cc.
References Mm::Feature::mainStream().
void CovarianceEstimator::setFeatureDescription (const Mm::FeatureDescription &) protected virtual
Override this function to achieve the attributes of the feature streams.
This function is called once before the first feature is processed.
Reimplemented from Speech::FeatureExtractor.
Definition at line 31 of file CovarianceEstimator.cc.
References Core::Description::Stream::getValue(), and Core::Description::verifyNumberOfStreams().
The documentation for this class was generated from the following files:
CovarianceEstimator.hh
CovarianceEstimator.cc