Sprint: Speech::LatticeSetProcessorRoot Class Reference
Speech::LatticeSetProcessorRoot Class Reference
root lattice set processor, i.e.
#include <LatticeSetProcessor.hh>
Public Member Functions
LatticeSetProcessorRoot (const Core::Configuration &)
LatticeSetProcessorRoot.
virtual void signOn (CorpusVisitor &)
Override this function to sign on to services of the corpus visitor.
virtual void enterCorpus (Bliss::Corpus *)
virtual void leaveCorpus (Bliss::Corpus *)
virtual void enterRecording (Bliss::Recording *)
virtual void leaveRecording (Bliss::Recording *)
virtual void enterSegment (Bliss::Segment *)
virtual void leaveSegment (Bliss::Segment *)
virtual void enterSpeechSegment (Bliss::SpeechSegment *)
virtual void leaveSpeechSegment (Bliss::SpeechSegment *)
virtual void initialize (Bliss::LexiconRef lexicon)
Override this function to achieve the lexicon of the input lattice set.
void initialize ()
Public Member Functions inherited from Speech::CorpusProcessor
CorpusProcessor (const Core::Configuration &c)
virtual void processSegment (Bliss::Segment *segment)
virtual void processSpeechSegment (Bliss::SpeechSegment *segment)
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Speech::LatticeSetProcessor
LatticeSetProcessor (const Core::Configuration &)
LatticeSetProcessor.
void setProcessor (Core::Ref< LatticeSetProcessor > processor)
This lattice set processor is used for cascading.
virtual void processWordLattice (Lattice::ConstWordLatticeRef, Bliss::SpeechSegment *)
Override this function to implement the processing of lattice sets.
virtual void getWordLatticeDescription (Lattice::WordLatticeDescription &)
Override this function to create the description of the output word lattices.
virtual void setWordLatticeDescription (const Lattice::WordLatticeDescription &)
Override this function to achieve the attributes of the input lattice set.
virtual void setSegmentwiseFeatureExtractor (Core::Ref< SegmentwiseFeatureExtractor >)
virtual void setAlignmentGenerator (Core::Ref< PhonemeSequenceAlignmentGenerator >)
virtual std::string name () const
virtual void logComputationTime () const
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Private Types
typedef LatticeSetProcessor Precursor
Precursor's functions are executed beforehand.
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Speech::CorpusProcessor
void reportRealTime (Flow::Time)
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Speech::CorpusProcessor
Core::XmlChannel channelTimer_
Core::Timer timer_
Protected Attributes inherited from Core::Configurable
Configuration config
Protected Attributes inherited from Speech::LatticeSetProcessor
f64 timeProcessSegment_
Core::Ref< LatticeSetProcessor > processor_
Detailed Description
root lattice set processor, i.e.
it is both a corpus and a lattice set processor
Definition at line 156 of file LatticeSetProcessor.hh.
Member Typedef Documentation
typedef LatticeSetProcessor Speech::LatticeSetProcessorRoot::Precursor private
Precursor's functions are executed beforehand.
Definition at line 159 of file LatticeSetProcessor.hh.
Constructor & Destructor Documentation
LatticeSetProcessorRoot::LatticeSetProcessorRoot (const Core::Configuration & c)
LatticeSetProcessorRoot.
Definition at line 84 of file LatticeSetProcessor.cc.
Member Function Documentation
virtual void Speech::LatticeSetProcessorRoot::initialize (Bliss::LexiconRef lexicon) inline virtual
Override this function to achieve the lexicon of the input lattice set.
Reimplemented from Speech::LatticeSetProcessor.
Reimplemented in Speech::LatticeSetReader, and Speech::NumeratorLatticeGenerator.
Definition at line 174 of file LatticeSetProcessor.hh.
Referenced by LatticeProcessor::main(), and signOn().
void LatticeSetProcessorRoot::signOn (CorpusVisitor & corpusVisitor) virtual
Override this function to sign on to services of the corpus visitor.
Note: call the signOn function of your predecessor.
Reimplemented from Speech::CorpusProcessor.
Reimplemented in Speech::NumeratorLatticeGenerator.
Definition at line 91 of file LatticeSetProcessor.cc.
References Speech::LatticeSetProcessor::enterCorpus(), Speech::LatticeSetProcessor::enterRecording(), Speech::LatticeSetProcessor::enterSegment(), Speech::LatticeSetProcessor::enterSpeechSegment(), initialize(), Speech::LatticeSetProcessor::leaveCorpus(), Speech::LatticeSetProcessor::leaveRecording(), Speech::LatticeSetProcessor::leaveSegment(), Speech::LatticeSetProcessor::leaveSpeechSegment(), Mc::Component::load(), Core::Component::respondToDelayedErrors(), Speech::CorpusProcessor::signOn(), and Speech::LatticeSetProcessor::signOn().
Referenced by Speech::NumeratorLatticeGenerator::signOn(), and LatticeProcessor::visitCorpus().
The documentation for this class was generated from the following files:
LatticeSetProcessor.hh
LatticeSetProcessor.cc