Sprint: Ftl::StaticAutomaton< _Automaton > Class Template Reference
Ftl::StaticAutomaton< _Automaton > Class Template Reference
Public Types
typedef _Automaton::Weight _Weight
typedef _Automaton::Arc _Arc
typedef _Automaton::State _State
typedef _Automaton::Semiring _Semiring
typedef Core::Ref< _State > _StateRef
typedef Core::Ref< const _State > _ConstStateRef
typedef Core::Ref< const _Semiring > _ConstSemiringRef
Public Types inherited from Ftl::StorageAutomaton< _Automaton >
typedef _Automaton::Weight _Weight
typedef _Automaton::State _State
typedef _Automaton::Semiring _Semiring
typedef Core::Ref< const _State > _ConstStateRef
typedef Core::Ref< const _Semiring > _ConstSemiringRef
Public Member Functions
StaticAutomaton (Fsa::Type type=Fsa::TypeUnknown)
StaticAutomaton (const std::string &desc, Fsa::Type type=Fsa::TypeUnknown)
virtual void clear ()
void setDescription (const std::string &desc)
virtual bool hasState (Fsa::StateId sid) const
_State * newState (Fsa::StateId tags=0)
_State * newState (Fsa::StateId tags, const _Weight &finalWeight)
_State * newFinalState (const _Weight &finalWeight)
void setStateFinal (_State *, const _Weight &finalWeight)
void setStateFinal (_State *)
_StateRef state (Fsa::StateId s)
_State * fastState (Fsa::StateId s)
const _State * fastState (Fsa::StateId s) const
virtual void setState (_State *sp)
virtual void deleteState (Fsa::StateId)
virtual _ConstStateRef getState (Fsa::StateId s) const
virtual void normalize ()
virtual Fsa::StateId maxStateId () const
Highest valid state ID.
virtual Fsa::StateId size () const
Smallest unused state ID, i.e.
virtual size_t getMemoryUsed () const
virtual void dumpMemoryUsage (Core::XmlWriter &o) const
virtual std::string describe () const
void compact (Fsa::StateMap &mapping)
Public Member Functions inherited from Ftl::StorageAutomaton< _Automaton >
StorageAutomaton (Fsa::Type type=Fsa::TypeUnknown)
virtual Fsa::Type type () const
virtual void setType (Fsa::Type type)
virtual void addProperties (Fsa::Property properties) const
virtual void setProperties (Fsa::Property knownProperties, Fsa::Property properties) const
virtual void unsetProperties (Fsa::Property unknownProperties) const
virtual _ConstSemiringRef semiring () const
virtual void setSemiring (_ConstSemiringRef semiring)
virtual Fsa::StateId initialStateId () const
virtual void setInitialStateId (Fsa::StateId initial)
virtual Fsa::ConstAlphabetRef getInputAlphabet () const
virtual void setInputAlphabet (Fsa::ConstAlphabetRef alphabet)
virtual Fsa::ConstAlphabetRef getOutputAlphabet () const
virtual void setOutputAlphabet (Fsa::ConstAlphabetRef alphabet)
virtual _State * createState (Fsa::StateId id=0, Fsa::StateTag tags=Fsa::StateTagNone) const
virtual _State * createState (Fsa::StateId id, Fsa::StateTag tags, const _Weight &) const
template<>
StorageAutomaton (Fsa::Type type)
template<>
StorageAutomaton (Fsa::Type type)
Private Types
typedef StorageAutomaton< _Automaton > Precursor
Private Member Functions
std::pair< size_t, size_t > getStateAndArcMemoryUsed () const
Private Attributes
std::string desc_
size_t memoryUsed_
Core::Vector< _StateRef > states_
Additional Inherited Members
Protected Attributes inherited from Ftl::StorageAutomaton< _Automaton >
Fsa::Type type_
_ConstSemiringRef semiring_
Fsa::StateId initial_
Fsa::ConstAlphabetRef input_
Fsa::ConstAlphabetRef output_
Detailed Description
template<class _Automaton>
class Ftl::StaticAutomaton< _Automaton >
Definition at line 24 of file tStatic.hh.
Member Function Documentation
template<class _Automaton> virtual Fsa::StateId Ftl::StaticAutomaton< _Automaton >::maxStateId () const inline virtual
Highest valid state ID.
Implements Ftl::StorageAutomaton< _Automaton >.
Definition at line 69 of file tStatic.hh.
Referenced by Search::Wfst::Builder::BuildGrammar::process(), and Flf::ExpandTransitsNode::sync().
template<class _Automaton> virtual Fsa::StateId Ftl::StaticAutomaton< _Automaton >::size () const inline virtual
Smallest unused state ID, i.e.
maxStateId()+1.
Implements Ftl::StorageAutomaton< _Automaton >.
Definition at line 72 of file tStatic.hh.
Referenced by Bliss::OrthographicParser::parse(), and Flf::ExpandTransitsNode::sync().
The documentation for this class was generated from the following files:
tStatic.hh
tStatic.cc