Sprint: Bliss::ContextPhonology Class Reference
Bliss::ContextPhonology Class Reference
Phonology for context dependent phonemes.
#include <Phonology.hh>
Classes
struct Context
class PhonemeInContext
class SemiContext
Public Types
typedef PhonemeInContext Allophone
Public Member Functions
ContextPhonology (PhonemeInventoryRef, u32 maximumHistoryLength=1, u32 maximumFutureLength=1)
PhonemeInventoryRef getPhonemeInventory () const
s32 maximumHistoryLength () const
s32 maximumFutureLength () const
void appendFuture (Allophone &, Phoneme::Id) const
void appendFuture (Context &, Phoneme::Id) const
void appendHistory (Allophone &, Phoneme::Id) const
void appendHistory (Context &, Phoneme::Id) const
void pushFuture (Allophone &, Phoneme::Id) const
void pushFuture (Context &, Phoneme::Id) const
void pushHistory (Allophone &, Phoneme::Id) const
void pushHistory (Context &, Phoneme::Id) const
Allophone allophone (const Pronunciation &, int i) const
Allophone operator() (const Pronunciation &p, int i) const
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Static Private Member Functions
static void append (SemiContext &, Phoneme::Id, s32 maximumLength)
Extend semi-context by one phoneme.
static void push (SemiContext &, Phoneme::Id, s32 maximumLength)
Push phoneme into semi-context.
Private Attributes
PhonemeInventoryRef pi_
s32 maximumHistoryLength_
s32 maximumFutureLength_
Detailed Description
Phonology for context dependent phonemes.
The ContextPhonology allophone is the PhonemeInContext. A phoneme in context is defined by its underlying phoneme and its left and right context phonemes. Such units are commonly referred to as "n-phones" (e.g. triphone, quinphone,...).
The conversion from a phoneme graph to a context-dependent phoneme graph involves replication of vertices and edges according to the various contexts in which they occur. The current implementation proceeds as follows:
Determine all left contexts (histories) of each vertex.
Determine all right contexts (futures) of each vertex.
For each phoneme graph vertex build the cartesian product of left and right contexts and create an allophone graph vertex for each context.
Definition at line 70 of file Phonology.hh.
Member Function Documentation
void ContextPhonology::append (SemiContext & ctxt, Phoneme::Id p, s32 maximumLength) static private
Extend semi-context by one phoneme.
The semi-context is extended by the given phoneme at the point farest from the present phoneme. Assertion is raised if maximumLength is exceeded.
Definition at line 81 of file Phonology.cc.
References Core::form(), Bliss::Pronunciation::length(), Bliss::PhonemeInventory::phoneme(), require, and Bliss::Token::symbol().
void ContextPhonology::push (SemiContext & ctxt, Phoneme::Id p, s32 maximumLength) static private
Push phoneme into semi-context.
The semi-context is extended by the given phoneme at a point closest close to present phoneme. If length exceeds maximumLength, the phoneme farest from present one is discarded.
Definition at line 59 of file Phonology.cc.
The documentation for this class was generated from the following files:
Phonology.hh
Phonology.cc