Sprint: Core::Configuration::ResourceDataBase Class Reference
Core::Configuration::ResourceDataBase Class Reference
Central storage place for all resources.
Public Member Functions
void set (const std::string &name, const std::string &value="true", const SourceDescriptor *source=0)
Add a resource.
const Resource * find (const std::string &parameter) const
Find the resource to be used for a given parameter.
const std::set< Resource > & getResources () const
const Resource * noResource () const
SourceDescriptor * addSource (const std::string &type, const std::string &data)
void enableLogging ()
void writeSources (XmlWriter &) const
void writeUsage (XmlWriter &) const
void write (std::ostream &) const
Private Types
typedef std::list< SourceDescriptor * > SourceList
Private Attributes
std::set< Resource > resources
Resource noResource_
bool isLogging_
SourceList sources_
Detailed Description
Central storage place for all resources.
Definition at line 171 of file Configuration.cc.
Member Function Documentation
const Configuration::Resource * Core::Configuration::ResourceDataBase::find (const std::string & parameter) const
Find the resource to be used for a given parameter.
Parameters
parameter the parameter specification string
Returns
the most specific resource matching parameter
Definition at line 251 of file Configuration.cc.
References Core::Configuration::isWellFormedParameterName(), Core::Configuration::Resource::match(), and require.
void Core::Configuration::ResourceDataBase::set (const std::string & name, const std::string & value = "true", const SourceDescriptor * source = 0)
Add a resource.
If a resource with the same name already exists, its value is replaced.
Parameters
name of the resource to be added
value of the resource
Definition at line 236 of file Configuration.cc.
References ensure, Core::Configuration::isWellFormedResourceName(), and require.
The documentation for this class was generated from the following file:
Configuration.cc