Sprint: Flow::Node Class Reference
Flow::Node Class Reference abstract
Abstract flow network node.
#include <Node.hh>
Public Member Functions
Node (const Core::Configuration &c)
virtual PortId getInput (const std::string &name)
Ask for an input port.
virtual PortId getOutput (const std::string &name)
Ask for an output port.
virtual bool configure ()
Performs static (independent of input data) configuration of node.
virtual bool work (PortId out)=0
Processes some data.
Public Member Functions inherited from Flow::AbstractNode
AbstractNode (const Core::Configuration &c)
virtual void Run ()
void setThreaded (bool threaded=true)
void setThreaded (const std::string &threaded)
bool isThreaded () const
virtual bool addParameter (const std::string &name, const Core::StringExpression &value)
addParameter adds a parameter to the node Constant parameters are simply delegated to setParameter, parameters dependent on network parameters are stored in parameters_.
virtual bool setParameter (const std::string &name, const std::string &value)
Set node specific parameter.
virtual ssize_t getRemainingDataLen (PortId out)
Returns the amount of remaining data items.
void addUnresolvedParameter (const std::string &key, const std::string &value)
Functions for saving and getting unresolved parameters.
const UnresolvedAttributes & unresolvedAttributes () const
bool operator< (const AbstractNode &n) const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Protected Member Functions
virtual PortId connectInputPort (PortId, Link *)
Connect link to input port.
virtual void disconnectInputLink (Link *)
virtual PortId connectOutputPort (PortId, Link *)
virtual void disconnectOutputLink (Link *)
PortId addInput (PortId in=IllegalPortId)
Create an input port.
PortId addInputs (u32 nPorts)
Create several input ports.
virtual PortId nInputs () const
Link * getInputLink (PortId in) const
virtual PortId inputConnected (PortId in) const
bool validInputPort (PortId in) const
PortId addOutput (PortId out=IllegalPortId)
Add an output port.
PortId addOutputs (u32 nPorts)
Create several output ports.
virtual PortId nOutputs () const
bool validOutputPort (PortId out) const
virtual u32 nOutputLinks (PortId out) const
Number of link connceted to an output port.
bool configureDatatype (Core::Ref< const Attributes > a, const Datatype *d)
template<class T >
bool getData (PortId in, DataPtr< T > &d)
Fetch data packet from input port.
virtual bool putData (PortId out, Data *d)
Send data packet on output port.
bool putEos (PortId out)
Send end-of-stream on output port.
bool putOod (PortId out)
Send out-of-data on output port.
Core::Ref< const Attributes > getInputAttributes (PortId in)
Retrieve attribute set from input port.
void getInputAttributes (PortId, Attributes &)
bool putOutputAttributes (PortId out, Core::Ref< const Attributes > a)
Put attribute set on output port.
void eraseOutputAttributes ()
Erases attributes of all output links recursively.
Protected Member Functions inherited from Flow::AbstractNode
template<class T >
bool getData (Link *l, DataPtr< T > &d)
Fetch data packet from the "from" port of link.
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Private Types
typedef AbstractNode Precursor
Private Attributes
const _Filter * filter_
const Datatype * datatype_
std::vector< Link * > inputs_
std::vector< std::vector< Link * > > outputs_
Core::XmlChannel attributesChannel_
Core::XmlChannel dataChannel_
Friends
class _Filter
Additional Inherited Members
Public Types inherited from Flow::AbstractNode
typedef std::map< std::string, std::string > UnresolvedAttributes
Static Public Attributes inherited from Flow::AbstractNode
static const Core::ParameterBool paramThreaded
static const Core::ParameterBool paramIgnoreUnknownParameters
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Abstract flow network node.
Definition at line 38 of file Flow/Node.hh.
Member Function Documentation
PortId Node::addInput (PortId in = IllegalPortId) protected
Create an input port.
Call this function getInput() to create ports dynamically.
Parameters
in the desired port ID. If not given the next free ID will be used.
See also
getInput()
Definition at line 66 of file Flow/Node.cc.
Referenced by Flow::CollectorNode< I, O >::getInput(), Signal::MatrixMultiplicationNode< T >::getInput(), and Signal::ProjectionNode< T >::getOutput().
PortId Node::addInputs (u32 nPorts) protected
Create several input ports.
Call this function from the constructor to create static ports.
See also
getInput()
Definition at line 76 of file Flow/Node.cc.
Referenced by Speech::AlignmentGeneratorNode::AlignmentGeneratorNode(), Speech::AlignmentRemoveEmissionScoreNode::AlignmentRemoveEmissionScoreNode(), Speech::AlignmentTransformNode::AlignmentTransformNode(), Speech::ApproximateDistanceLatticeRescorerNode::ApproximateDistanceLatticeRescorerNode(), Speech::BinaryAlignmentTransformNode::BinaryAlignmentTransformNode(), Speech::LatticeNBestNode::LatticeNBestNode(), Speech::LatticeRescorerNode::LatticeRescorerNode(), Speech::LatticeSemiringNode::LatticeSemiringNode(), Speech::LatticeTransform2Node::LatticeTransform2Node(), Speech::LatticeWriteNode::LatticeWriteNode(), Speech::SetAlignmentWeightsByTiedStateAlignmentWeightsNode::SetAlignmentWeightsByTiedStateAlignmentWeightsNode(), Speech::AlignmentNode::work(), Speech::LatticeSemiringNode::work(), Speech::LatticeSimpleModifyNode::work(), and Speech::LatticeNBestNode::work().
PortId Node::addOutput (PortId out = IllegalPortId) protected
Add an output port.
Call this function from getOutput() to create ports dynamically.
See also
getOutput()
Definition at line 84 of file Flow/Node.cc.
Referenced by Signal::ProjectionNode< T >::getOutput(), Signal::VectorSequenceConcatenation< T >::getOutput(), Signal::VectorSequenceAggregation< T >::getOutput(), Flow::VectorSplitNode< T >::getOutput(), and Signal::MatrixMultiplicationNode< T >::getOutput().
PortId Node::addOutputs (u32 nPorts) protected
Create several output ports.
Call this function from the constructor to create static ports.
See also
getOutput()
Definition at line 94 of file Flow/Node.cc.
Referenced by Speech::AlignmentGeneratorNode::AlignmentGeneratorNode(), Speech::AlignmentTransformNode::AlignmentTransformNode(), Speech::BinaryAlignmentTransformNode::BinaryAlignmentTransformNode(), Speech::LatticeNBestNode::LatticeNBestNode(), Speech::LatticeRescorerNode::LatticeRescorerNode(), Speech::LatticeSemiringNode::LatticeSemiringNode(), Speech::SetAlignmentWeightsByTiedStateAlignmentWeightsNode::SetAlignmentWeightsByTiedStateAlignmentWeightsNode(), Speech::AlignmentNode::work(), Speech::LatticeSemiringNode::work(), Speech::LatticeSimpleModifyNode::work(), and Speech::LatticeNBestNode::work().
bool Node::configure () virtual
Performs static (independent of input data) configuration of node.
Configure is called if one of the output attributes is not available. Override this function to evaluate all input attributes and pass them on to successor nodes. The default implementation simply forwards the merged attributes from all input links to all outputs. Note: -we assume no dead inputs here. -This function is the safest point to reset the algorithms used by the node. The alternative would be to reset the algorithms when a non-data object has been recieved. This solution can lead easily to unintended behaviour, since it is not garatinteed at all that every node receives for example a EOS object!
Implements Flow::AbstractNode.
Reimplemented in Flow::SimpleFunctionNode< Function >, Speech::LatticeDumpCtmNode, Signal::QuantileEqualizationNode, Speech::LatticeNBestNode, Signal::CrossCorrelationNode, Signal::NormalizationNode, Speech::SetAlignmentWeightsByTiedStateAlignmentWeightsNode, Signal::SilenceDetectionNode, Speech::AlignmentRemoveEmissionScoreNode, Signal::GammaToneNode, Signal::FilterBankNode, Signal::VectorCutNode< Algorithm >, Speech::AcousticLatticeRescorerNode, Speech::LatticeTransform2Node, Signal::FastFourierTransformNode< Algorithm >, Speech::LatticeTransformNode, Speech::AlignmentToSequenceSelectionNode, Signal::VectorNormalizationNode< NormalizationFunction >, Speech::LatticeSimpleModifyNode, Signal::WindowingFirFilterNode, Flow::CacheNode, Audio::SinkNode, Signal::BayesClassificationNode, Signal::ComplexVectorFunctionNode< Function >, Signal::MrastaFilteringNode, Signal::DcDetectionNode, Speech::SoftFramePhoneAccuracyLatticeRescorerNode, Speech::AlignmentDumpNode, Signal::CosineTransformNode, Speech::LatticeSemiringNode, Signal::LinearFilterNode, Speech::BinaryAlignmentTransformNode, Signal::HarmonicSumNode, Signal::PeakDetectionNode, Signal::SampleNormalizationNode, Audio::SourceNode, Signal::SilenceNormalizationNode, Flow::SynchronizationNode< Algorithm >, Signal::TemporalPatternNode, Speech::LatticeWriteNode, Flow::TypedDisaggregateNode< T >, Signal::SegmentwiseFormantExtractionNode, Signal::HistogramNormalizationNode, Signal::NthOrderFeaturesNode, Flow::TypeConverterNode< C >, Flow::VectorScalarFunctionNode< Function >, Flow::VectorMalformedNode< T, Policy >, Speech::AlignmentNode, Signal::DelayNode, Speech::ApproximateDistanceLatticeRescorerNode, Signal::AutocorrelationToAutoregressionNode, Flow::AggregationNode, Speech::LatticeIoNode, Signal::MatrixMultiplicationNode< T >, Speech::FeatureShiftAdaptor, Signal::TemporalIntegrationNode, Flow::CollectorNode< I, O >, Nn::NeuralNetworkForwardNode, Flow::CollectorNode< Vector< T >, Vector< T > >, Flow::CollectorNode< Aggregate::DataType, Aggregate >, Flow::CollectorNode< TypedAggregate< T >::DataType, TypedAggregate< T > >, Flow::CollectorNode< Flow::Vector< f32 >, Flow::Vector< f32 > >, Signal::SpectralIntegrationNode, Signal::WindowNode, Signal::ContinuousVectorTransformNode, Flow::DemoNode, Signal::LinearWarpingNode, Speech::ModelCombinationNode, Speech::LatticeArcAccumulatorNode, Signal::MeanEstimatorNode, Signal::AutoregressionToSpectrumNode, Signal::PreemphasisNode, Speech::SegmentwiseFeaturesNode, Flow::CoprusKeyMapNode, Flow::VectorSplitNode< T >, Signal::AllPolesPowerSpectrumNode, Signal::RandomVectorNode, Speech::AlignmentWithLinearSegmentationNode, Flow::VectorSelectNode< T >, Speech::AlignmentBaseNode, Flow::VectorAbsValDumpNode< content >, Signal::AutoregressionToCepstrumNode, Signal::VectorResizeNode< T >, Flow::SequenceFilterNode, Flow::VectorTextInputNodeBase, Flow::VectorDemultiplexNode< T >, Signal::VectorSequenceAggregation< T >, Flow::CutterNode, Signal::VectorSequenceConcatenation< T >, Signal::GenericWarpingNode, Speech::AlignmentFromLatticeNode, Flow::VectorConcatNode< T >, Signal::LinearPredictionCodingNode, Signal::ProjectionNode< T >, Flow::WarpTimeFilterNode, Speech::StatePosteriorFeatureScorerNode, Flow::MergerNode< I, O >, Flow::MergerNode< Vector< T >, Vector< T > >, Flow::MergerNode< Aggregate::DataType, Aggregate >, Flow::MergerNode< TypedAggregate< T >::DataType, TypedAggregate< T > >, Flow::MergerNode< Flow::Vector< f32 >, Flow::Vector< f32 > >, Speech::SegmentNode, Speech::FeatureScorerNode, Speech::LatticeRescorerNode, Signal::SleeveNode, Speech::AlignmentGeneratorNode, and Speech::AlignmentTransformNode.
Definition at line 32 of file Flow/Node.cc.
References ensure, Core::Component::error(), getInputAttributes(), and putOutputAttributes().
Referenced by Audio::SourceNode::getOutput(), getOutput(), and Audio::SinkNode::getOutput().
PortId Node::connectInputPort (PortId in, Link * l) protected virtual
Connect link to input port.
Do not connect more than one link to an input, will return InvalidPortId if anyone tries to do so.
Implements Flow::AbstractNode.
Definition at line 102 of file Flow/Node.cc.
References ensure, and require.
void Node::eraseOutputAttributes () protected virtual
Erases attributes of all output links recursively.
Reimplemented from Flow::AbstractNode.
Definition at line 262 of file Flow/Node.cc.
References Flow::AbstractNode::eraseOutputAttributes(), and Audio::SinkNode::work().
Referenced by putOod().
template<class T > bool Flow::Node::getData (PortId in, DataPtr< T > & d) inline protected
Fetch data packet from input port.
Parameters
in port id of input port to get data from
d data pointer to which retrieved packet is attached
Returns
true on success, or false if the out-of-data
Definition at line 114 of file Flow/Node.hh.
References Flow::AbstractNode::getData(), putData(), and require.
Referenced by Flow::CollectorNode< I, O >::getData(), Flow::SynchronizationNode< Algorithm >::nextData(), Flow::WeakSynchronizationNode< Algorithm >::nextData(), Speech::AlignmentTransformNode::work(), Speech::AlignmentGeneratorNode::work(), Flow::WarpTimeFilterNode::work(), Signal::ProjectionNode< T >::work(), Signal::FastMatrixMultiplicationNode< T >::work(), Signal::SlidingAlgorithmNode< Algorithm >::work(), Signal::AutoregressionToCepstrumNode::work(), Flow::VectorSelectNode< T >::work(), Speech::AlignmentWithLinearSegmentationNode::work(), Flow::VectorAbsValDumpNode< content >::work(), Flow::VectorDemultiplexNode< T >::work(), Signal::AutoregressionToSpectrumNode::work(), Signal::ContinuousVectorTransformNode::work(), Signal::VectorResizeNode< T >::work(), Speech::FeatureShiftAdaptor::work(), Signal::MatrixMultiplicationNode< T >::work(), Flow::VectorSplitNode< T >::work(), Speech::ApproximateDistanceLatticeRescorerNode::work(), Speech::AlignmentNode::work(), Signal::NthOrderFeaturesNode::work(), Speech::LatticeWriteNode::work(), Signal::TemporalPatternNode::work(), Speech::BinaryAlignmentTransformNode::work(), Speech::LatticeSemiringNode::work(), Speech::AlignmentDumpNode::work(), Speech::SoftFramePhoneAccuracyLatticeRescorerNode::work(), Speech::LatticeSimpleModifyNode::work(), Speech::LatticeTransformNode::work(), Speech::LatticeTransform2Node::work(), Speech::AcousticLatticeRescorerNode::work(), Speech::AlignmentRemoveEmissionScoreNode::work(), Speech::SetAlignmentWeightsByTiedStateAlignmentWeightsNode::work(), Speech::LatticeNBestNode::work(), and Speech::LatticeDumpCtmNode::work().
virtual PortId Flow::Node::getInput (const std::string &) inline virtual
Ask for an input port.
Implement this function to provide a mapping form names to port IDs. Consider using a Core::Choice. Remeber to create ports using addInput().
Returns
a valid port ID or IllegalPortId if there is to such port.
Implements Flow::AbstractNode.
Reimplemented in Speech::LatticeDumpCtmNode, Signal::CrossCorrelationNode, Speech::SetAlignmentWeightsByTiedStateAlignmentWeightsNode, Speech::AlignmentRemoveEmissionScoreNode, Signal::GammaToneNode, Signal::FilterBankNode, Signal::WarpingNode, Speech::LatticeTransform2Node, Speech::AcousticLatticeRescorerNode, Flow::SleeveNode, Speech::AlignmentToSequenceSelectionNode, Flow::SinkNode, Signal::WindowingFirFilterNode, Speech::AlignmentMultiplyAlignmentsNode, Flow::CacheNode, Signal::BayesClassificationNode, Audio::SinkNode, Signal::LinearFilterNode, Signal::CosineTransformNode, Speech::AlignmentDumpNode, Signal::PeakDetectionNode, Speech::LatticeWriteNode, Flow::SynchronizationNode< Algorithm >, Flow::TypedDisaggregateNode< T >, Signal::HistogramNormalizationNode, Signal::DelayNode, Speech::ApproximateDistanceLatticeRescorerNode, Signal::MatrixMultiplicationNode< T >, Tensorflow::TensorflowOverlappingForwardNode, Flow::CollectorNode< I, O >, Flow::CollectorNode< Vector< T >, Vector< T > >, Flow::CollectorNode< Aggregate::DataType, Aggregate >, Flow::CollectorNode< TypedAggregate< T >::DataType, TypedAggregate< T > >, Flow::CollectorNode< Flow::Vector< f32 >, Flow::Vector< f32 > >, Flow::DemoNode, Speech::FeatureShiftAdaptor, Signal::LinearWarpingNode, Flow::StringExpressionNode, Speech::LatticeArcAccumulatorNode, Speech::SegmentwiseFeaturesNode, Signal::LinearPredictionCodingNode, Flow::SequenceFilterNode, Signal::GenericWarpingNode, Speech::AlignmentFromLatticeNode, Signal::ProjectionNode< T >, Tensorflow::TensorflowForwardNode, Flow::WarpTimeFilterNode, Speech::LatticeRescorerNode, Speech::AlignmentGeneratorNode, and Flow::RepeaterNode.
Definition at line 155 of file Flow/Node.hh.
Core::Ref< const Attributes > Node::getInputAttributes (PortId in) protected
Retrieve attribute set from input port.
In order to avoid if-clauses in the overloaded Node::configure() function,
Returns
is always valid, e.i. reference points to a valid object. If the configuration of the predecessor node fails, an empty Attributes object is generated.
Definition at line 198 of file Flow/Node.cc.
References Flow::AbstractNode::configure(), ensure, Core::Component::error(), Core::ref(), and Core::Component::warning().
Referenced by Speech::AlignmentTransformNode::configure(), Speech::AlignmentGeneratorNode::configure(), Signal::SleeveNode::configure(), Speech::LatticeRescorerNode::configure(), Flow::WarpTimeFilterNode::configure(), Signal::ProjectionNode< T >::configure(), Signal::VectorSequenceConcatenation< T >::configure(), Signal::VectorSequenceAggregation< T >::configure(), Flow::VectorDemultiplexNode< T >::configure(), Signal::VectorResizeNode< T >::configure(), Signal::AutoregressionToCepstrumNode::configure(), Flow::VectorAbsValDumpNode< content >::configure(), Flow::VectorSelectNode< T >::configure(), Flow::VectorSplitNode< T >::configure(), Signal::AutoregressionToSpectrumNode::configure(), Signal::ContinuousVectorTransformNode::configure(), Flow::CollectorNode< I, O >::configure(), Speech::FeatureShiftAdaptor::configure(), Signal::MatrixMultiplicationNode< T >::configure(), Speech::ApproximateDistanceLatticeRescorerNode::configure(), Signal::NthOrderFeaturesNode::configure(), Speech::LatticeWriteNode::configure(), Signal::TemporalPatternNode::configure(), Signal::SilenceNormalizationNode::configure(), Speech::BinaryAlignmentTransformNode::configure(), Speech::LatticeSemiringNode::configure(), Speech::AlignmentDumpNode::configure(), configure(), Speech::SoftFramePhoneAccuracyLatticeRescorerNode::configure(), Speech::LatticeSimpleModifyNode::configure(), Speech::LatticeTransformNode::configure(), Speech::LatticeTransform2Node::configure(), Speech::AcousticLatticeRescorerNode::configure(), Speech::AlignmentRemoveEmissionScoreNode::configure(), Speech::SetAlignmentWeightsByTiedStateAlignmentWeightsNode::configure(), Speech::LatticeNBestNode::configure(), Speech::LatticeDumpCtmNode::configure(), putOod(), and Speech::AlignmentBaseNode::setParameter().
virtual PortId Flow::Node::getOutput (const std::string &) inline virtual
Ask for an output port.
Implement this function to provide a mapping form names to port IDs. Consider using a Core::Choice. Remeber to create ports using addOutput().
Returns
a valid port ID or IllegalPortId if there is to such port.
Implements Flow::AbstractNode.
Reimplemented in Signal::CrossCorrelationNode, Signal::SilenceDetectionNode, Signal::GammaToneNode, Signal::FilterBankNode, Signal::WarpingNode, Flow::SleeveNode, Flow::SourceNode, Speech::AlignmentToSequenceSelectionNode, Flow::CacheNode, Audio::SinkNode, Signal::CosineTransformNode, Speech::AlignmentDumpNode, Signal::PeakDetectionNode, Audio::SourceNode, Flow::SynchronizationNode< Algorithm >, Flow::TypedDisaggregateNode< T >, Signal::HistogramNormalizationNode, Signal::SegmentwiseFormantExtractionNode, Signal::DelayNode, Signal::MatrixMultiplicationNode< T >, Speech::FeatureShiftAdaptor, Flow::DemoNode, Flow::VectorSplitNode< T >, Signal::VectorSequenceAggregation< T >, Signal::VectorSequenceConcatenation< T >, Flow::SequenceFilterNode, Signal::LinearPredictionCodingNode, Signal::ProjectionNode< T >, Tensorflow::TensorflowForwardNode, Flow::WarpTimeFilterNode, and Flow::RepeaterNode.
Definition at line 158 of file Flow/Node.hh.
References configure(), and work().
virtual u32 Flow::Node::nOutputLinks (PortId out) const inline protected virtual
Number of link connceted to an output port.
Implements Flow::AbstractNode.
Definition at line 101 of file Flow/Node.hh.
References require.
Referenced by putData(), putOutputAttributes(), and Signal::MatrixMultiplicationNode< T >::work().
bool Node::putData (PortId out, Data * d) protected virtual
Send data packet on output port.
Parameters
out port id of output port to send to
d data packet to transmit. putData() receives ownership of d.
Precondition
If a "datatype" attribute has been set during the configuration phase, the data packet must conform to this.
Returns
true on success
Definition at line 167 of file Flow/Node.cc.
References Core::Configurable::fullName(), nOutputLinks(), and require.
Referenced by Signal::SlidingAlgorithmNode< Algorithm >::flushAllAndPut(), getData(), putEos(), Flow::CollectorNode< I, O >::putNullData(), putOod(), Flow::VectorTextInputNodeBase::setParameter(), Speech::AlignmentTransformNode::work(), Speech::AlignmentGeneratorNode::work(), Flow::WarpTimeFilterNode::work(), Signal::ProjectionNode< T >::work(), Signal::FastMatrixMultiplicationNode< T >::work(), Flow::PipeNode::work(), Signal::SlidingAlgorithmNode< Algorithm >::work(), Flow::MergerNode< I, O >::work(), Signal::AutoregressionToCepstrumNode::work(), Flow::VectorSelectNode< T >::work(), Speech::AlignmentWithLinearSegmentationNode::work(), Flow::VectorSequenceNode< T >::work(), Flow::VectorAbsValDumpNode< content >::work(), Signal::AutoregressionToSpectrumNode::work(), Flow::VectorDemultiplexNode< T >::work(), Signal::ContinuousVectorTransformNode::work(), Signal::VectorResizeNode< T >::work(), Signal::MatrixMultiplicationNode< T >::work(), Flow::VectorSplitNode< T >::work(), Speech::ApproximateDistanceLatticeRescorerNode::work(), Speech::AlignmentNode::work(), Signal::NthOrderFeaturesNode::work(), Speech::LatticeWriteNode::work(), Signal::TemporalPatternNode::work(), Speech::BinaryAlignmentTransformNode::work(), Speech::LatticeSemiringNode::work(), Speech::AlignmentDumpNode::work(), Speech::SoftFramePhoneAccuracyLatticeRescorerNode::work(), Speech::LatticeSimpleModifyNode::work(), Signal::VectorNormalizationNode< NormalizationFunction >::work(), Speech::LatticeTransformNode::work(), Speech::LatticeTransform2Node::work(), Speech::AcousticLatticeRescorerNode::work(), Signal::VectorCutNode< Algorithm >::work(), Speech::SetAlignmentWeightsByTiedStateAlignmentWeightsNode::work(), Speech::LatticeNBestNode::work(), and Speech::LatticeDumpCtmNode::work().
bool Flow::Node::putEos (PortId out) inline protected
Send end-of-stream on output port.
Definition at line 129 of file Flow/Node.hh.
References Flow::Data::eos(), and putData().
Referenced by Flow::CollectorNode< I, O >::putNullData(), Flow::PipeNode::work(), and Flow::VectorTextInputNodeBase::work().
bool Flow::Node::putOod (PortId out) inline protected
Send out-of-data on output port.
Definition at line 133 of file Flow/Node.hh.
References eraseOutputAttributes(), getInputAttributes(), Flow::Data::ood(), putData(), and putOutputAttributes().
bool Node::putOutputAttributes (PortId out, Core::Ref< const Attributes > a) protected
Put attribute set on output port.
Additionally, output links are reconfigured and cleared.
Definition at line 237 of file Flow/Node.cc.
References Core::Configurable::fullName(), nOutputLinks(), and require.
Referenced by Speech::AlignmentTransformNode::configure(), Speech::AlignmentGeneratorNode::configure(), Signal::SleeveNode::configure(), Speech::LatticeRescorerNode::configure(), Flow::WarpTimeFilterNode::configure(), Signal::ProjectionNode< T >::configure(), Signal::VectorSequenceConcatenation< T >::configure(), Flow::VectorDemultiplexNode< T >::configure(), Signal::VectorSequenceAggregation< T >::configure(), Flow::VectorTextInputNodeBase::configure(), Signal::AutoregressionToCepstrumNode::configure(), Signal::VectorResizeNode< T >::configure(), Flow::VectorAbsValDumpNode< content >::configure(), Flow::VectorSelectNode< T >::configure(), Flow::VectorSplitNode< T >::configure(), Signal::AutoregressionToSpectrumNode::configure(), Signal::ContinuousVectorTransformNode::configure(), Flow::CollectorNode< I, O >::configure(), Signal::MatrixMultiplicationNode< T >::configure(), Speech::FeatureShiftAdaptor::configure(), Signal::NthOrderFeaturesNode::configure(), Signal::TemporalPatternNode::configure(), Signal::SilenceNormalizationNode::configure(), Speech::BinaryAlignmentTransformNode::configure(), Speech::LatticeSemiringNode::configure(), Speech::AlignmentDumpNode::configure(), configure(), Speech::LatticeSimpleModifyNode::configure(), Speech::LatticeTransformNode::configure(), Speech::SetAlignmentWeightsByTiedStateAlignmentWeightsNode::configure(), Speech::LatticeNBestNode::configure(), Speech::LatticeDumpCtmNode::configure(), putOod(), and Speech::AlignmentBaseNode::setParameter().
virtual bool Flow::Node::work (PortId out) pure virtual
Processes some data.
Implement this function to do whatever your node is supposed to. You are required to produce at least one packet of data on the specified output out. You may send more packets, also to other outputs.
Returns
true on success, false on end-of-file or error. The idiom is:
return putData(out, d);
Implements Flow::AbstractNode.
Implemented in Signal::SegmentClusteringNode< Model >, Flow::SimpleFunctionNode< Function >, Signal::QuantileEqualizationNode, Speech::LatticeDumpCtmNode, Speech::LatticeNBestNode, Signal::CrossCorrelationNode, Signal::NormalizationNode, Speech::SetAlignmentWeightsByTiedStateAlignmentWeightsNode, Signal::SilenceDetectionNode, Speech::AlignmentRemoveEmissionScoreNode, Signal::VectorCutNode< Algorithm >, Signal::GammaToneNode, Signal::FilterBankNode, Signal::WarpingNode, Speech::AcousticLatticeRescorerNode, Speech::LatticeTransform2Node, Signal::FastFourierTransformNode< Algorithm >, Speech::LatticeTransformNode, Speech::AlignmentToSequenceSelectionNode, Signal::VectorNormalizationNode< NormalizationFunction >, Signal::BayesClassificationScoreNode, Speech::LatticeSimpleModifyNode, Signal::ComplexVectorFunctionNode< Function >, Signal::WindowingFirFilterNode, Flow::CacheNode, Audio::SinkNode, Signal::BayesClassificationNode, Signal::MrastaFilteringNode, Speech::SoftFramePhoneAccuracyLatticeRescorerNode, Speech::AlignmentDumpNode, Signal::CosineTransformNode, Signal::LinearFilterNode, Speech::LatticeSemiringNode, Speech::BinaryAlignmentTransformNode, Signal::PeakDetectionNode, Signal::HarmonicSumNode, Flow::SynchronizationNode< Algorithm >, Audio::SourceNode, Signal::TemporalPatternNode, Speech::LatticeWriteNode, Flow::TypedDisaggregateNode< T >, Signal::HistogramNormalizationNode, Signal::SegmentwiseFormantExtractionNode, Signal::NthOrderFeaturesNode, Flow::TypeConverterNode< C >, Flow::VectorScalarFunctionNode< Function >, Flow::VectorMalformedNode< T, Policy >, Speech::LatticeReadNode, Signal::DelayNode, Speech::AlignmentNode, Speech::ApproximateDistanceLatticeRescorerNode, Signal::AutocorrelationToAutoregressionNode, Flow::VectorSplitNode< T >, Signal::MatrixMultiplicationNode< T >, Speech::LatticeIoNode, Speech::FeatureShiftAdaptor, Tensorflow::TensorflowOverlappingForwardNode, Flow::CollectorNode< I, O >, Nn::NeuralNetworkForwardNode, Flow::CollectorNode< Vector< T >, Vector< T > >, Flow::CollectorNode< Aggregate::DataType, Aggregate >, Flow::CollectorNode< TypedAggregate< T >::DataType, TypedAggregate< T > >, Flow::CollectorNode< Flow::Vector< f32 >, Flow::Vector< f32 > >, Signal::VectorResizeNode< T >, Signal::SpectralIntegrationNode, Signal::ContinuousVectorTransformNode, Flow::DemoNode, Speech::LatticeArcAccumulatorNode, Signal::PreemphasisNode, Speech::ModelCombinationNode, Flow::VectorDemultiplexNode< T >, Signal::AutoregressionToSpectrumNode, Signal::MeanEstimatorNode, Flow::VectorAbsValDumpNode< content >, Signal::AllPolesPowerSpectrumNode, Speech::SegmentwiseFeaturesNode, Flow::CoprusKeyMapNode, Flow::VectorSequenceNode< T >, Signal::RandomVectorNode, Speech::NumeratorFromDenominatorNode, Speech::AlignmentWithLinearSegmentationNode, Flow::VectorSelectNode< T >, Signal::AutoregressionToCepstrumNode, Flow::VectorTextInputNodeBase, Flow::SequenceFilterNode, Flow::MergerNode< I, O >, Signal::LinearPredictionCodingNode, Flow::MergerNode< Vector< T >, Vector< T > >, Flow::MergerNode< Aggregate::DataType, Aggregate >, Flow::MergerNode< TypedAggregate< T >::DataType, TypedAggregate< T > >, Flow::MergerNode< Flow::Vector< f32 >, Flow::Vector< f32 > >, Flow::CutterNode, Flow::PipeNode, Signal::SlidingAlgorithmNode< Algorithm >, Signal::SlidingAlgorithmNode< LengthDependentSampleNormalization >, Signal::SlidingAlgorithmNode< WindowingFirFilter >, Signal::SlidingAlgorithmNode< SilenceNormalization >, Signal::SlidingAlgorithmNode< DcDetection >, Signal::SlidingAlgorithmNode< Window >, Signal::SlidingAlgorithmNode< TemporalIntegration >, Signal::FastMatrixMultiplicationNode< T >, Speech::CorpusProcessorNode< CorpusProcessorType >, Signal::ProjectionNode< T >, Speech::AlignmentFromLatticeNode, Flow::WarpTimeFilterNode, Speech::StatePosteriorFeatureScorerNode, Tensorflow::TensorflowForwardNode, Flow::DumpNode, Speech::SegmentNode, Speech::FeatureScorerNode, Speech::AlignmentGeneratorNode, Flow::RepeaterNode, and Speech::AlignmentTransformNode.
Referenced by Audio::SourceNode::getOutput(), getOutput(), and Audio::SinkNode::getOutput().
The documentation for this class was generated from the following files:
Flow/Node.hh
Flow/Node.cc