Sprint: Nn::Statistics< T > Class Template Reference
Nn::Statistics< T > Class Template Reference
Public Types
enum StatisticTypes {
NONE = 0, CLASS_COUNTS = 1, MEAN_AND_VARIANCE = 2, BASE_STATISTICS = 4,
GRADIENT = 8
}
Public Member Functions
Statistics (u32 nTrainableLayers, u32 statisticTypes)
Statistics (const Statistics< T > &statistics, bool onlyStructure=false)
void reset ()
resets the statistics to 0, but keeps sizes of matrices
void finalize (bool normalizeByNOfObservations=true)
transformation to a minimization problem and normalization
void incClassificationErrors (u32 increment=1)
void incObservations (u32 increment=1)
void decObservations (u32 decrement=1)
void addToTotalWeight (T weight)
void incClassCount (u32 label, u32 increment=1)
void addToObjectiveFunction (T value)
void addToEntropy (T value)
T objectiveFunction () const
T classificationError () const
u32 nObservations () const
T totalWeight () const
u32 classCount (u32 label) const
T entropy () const
NnVector & featureSum ()
NnVector & squaredFeatureSum ()
std::vector< NnMatrix > & gradientWeights (u32 layer)
return the gradient of a certain layer
NnVector & gradientBias (u32 layer)
T gradientL1Norm () const
computes the l1 norm of the gradient
bool hasClassCounts () const
bool hasBaseStatistics () const
bool hasGradient () const
template<typename S >
void initialize (const NeuralNetwork< S > &neuralNetwork)
initialize statistics from neural network
void initComputation (bool sync=true)
void finishComputation (bool sync=true)
bool isComputing () const
template<typename S >
void add (const Statistics< S > &rhs)
template<typename S >
void copyStructure (const Statistics< S > &rhs)
bool read (const std::string &filename)
bool read (Core::BinaryInputStream &is)
bool write (const std::string &filename) const
bool write (Core::BinaryOutputStream &os) const
bool write (std::ostream &os) const
bool write (Core::XmlWriter &o) const
void dumpGradientsToFiles (const std::string &prefix)
bool combine (const std::vector< std::string > &toCombine)
Static Public Member Functions
static bool getTypeFromFile (const std::string &filename, u32 &statisticsType, bool &singlePrecision)
Protected Types
typedef Types< T >::NnVector NnVector
typedef Types< T >::NnMatrix NnMatrix
Protected Attributes
u32 statisticTypes_
bool hasClassCounts_
bool hasMeanAndVariance_
bool hasBaseStatistics_
bool hasGradient_
bool singlePrecision_
std::vector< s32 > layerIndexToTrainableLayerIndex_
T objectiveFunction_
u32 nClassificationErrors_
u32 nObservations_
T totalWeight_
std::map< u32, u32 > classCount_
T entropy_
NnVector sum_
NnVector sumOfSquares_
std::vector< std::vector< NnMatrix > > gradientWeights_
std::vector< NnVector > gradientBias_
bool isComputing_
bool isFinalized_
Static Protected Attributes
static const u32 version_ = 2
Private Member Functions
void logProperties () const
void setPrecision ()
const std::string readHeader (Core::BinaryInputStream &)
bool writeHeader (Core::BinaryOutputStream &) const
const std::string getMagic () const
bool isConsistent (const std::string &magic) const
template<>
void setPrecision ()
template<>
void setPrecision ()
Static Private Member Functions
static bool checkConsistency (bool object, bool file, std::string description)
static bool isValid (const std::string &magic)
static bool hasBaseStatistics (const std::string &magic)
static bool hasMeanAndVariance (const std::string &magic)
static bool hasClassCounts (const std::string &magic)
static bool hasGradient (const std::string &magic)
static bool hasSinglePrecision (const std::string &magic)
Friends
class Statistics< f32 >
class Statistics< f64 >
Detailed Description
template<class T>
class Nn::Statistics< T >
Definition at line 31 of file BatchEstimator.hh.
Member Function Documentation
template<typename T > void Statistics::finalize (bool normalizeByNOfObservations = true)
transformation to a minimization problem and normalization
Definition at line 146 of file Nn/Statistics.cc.
Referenced by Nn::MeanAndVarianceTrainer< T >::writeMeanAndStandardDeviation().
template<typename T > T Statistics::gradientL1Norm () const
computes the l1 norm of the gradient
Definition at line 193 of file Nn/Statistics.cc.
References Math::copy(), Core::Component::criticalError(), Core::Component::error(), Core::form(), Core::Component::log(), require, and Core::Application::us().
Referenced by Nn::Statistics< f32 >::gradientWeights().
template<class T> std::vector<NnMatrix>& Nn::Statistics< T >::gradientWeights (u32 layer) inline
return the gradient of a certain layer
Definition at line 142 of file Nn/Statistics.hh.
Referenced by Nn::MeanNormalizedSgd< T >::estimate(), Nn::Adam< T >::estimate(), Nn::AdaGrad< T >::estimate(), Nn::AdaDelta< T >::estimate(), and Nn::RmsProp< T >::estimate().
template<typename T > template<typename S > void Nn::Statistics< T >::initialize (const NeuralNetwork< S > & neuralNetwork)
initialize statistics from neural network
Definition at line 212 of file Nn/Statistics.hh.
References Nn::NeuralNetwork< T >::getLayer(), require, and Nn::Statistics< T >::reset().
Referenced by Nn::Statistics< f32 >::gradientWeights(), and Nn::SegmentwiseNnTrainer< T >::leaveCorpus().
template<typename T > void Statistics::reset (void)
resets the statistics to 0, but keeps sizes of matrices
Definition at line 116 of file Nn/Statistics.cc.
Referenced by Nn::Statistics< T >::initialize().
The documentation for this class was generated from the following files:
BatchEstimator.hh
Nn/Statistics.hh
Nn/Statistics.cc