Sprint: Core::Configurable Class Reference
Core::Configurable Class Reference
Abstract base class for run-time configurable classes.
#include <Configurable.hh>
Public Member Functions
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Protected Attributes
Configuration config
Detailed Description
Abstract base class for run-time configurable classes.
Each run-time configurable class must inherit Configurable to ensure automatic creation of the selection hierarchy and passing of configuration.
Definition at line 32 of file Configurable.hh.
Member Function Documentation
const std::string& Core::Configurable::fullName () const inline
Run-time name of the component.
This is just the configuration path.
Definition at line 55 of file Configurable.hh.
Referenced by Search::LanguageModelLookahead::buildCompressesLookaheadStructure(), Flow::DemoNode::configure(), Speech::ModelCombination::distributeScaleUpdate(), Core::Component::exit(), Flow::DemoNode::getInput(), Flow::DemoNode::getOutput(), Core::Component::log(), Flow::Node::putData(), Flow::Node::putOutputAttributes(), Flow::DemoNode::setParameter(), Mc::Component::updateScales(), Core::Component::vErrorMessage(), and Flow::DemoNode::work().
The documentation for this class was generated from the following file:
Configurable.hh