Sprint: Signal::BICFullCovMonoGaussianModel Class Reference
Signal::BICFullCovMonoGaussianModel Class Reference
Public Member Functions
BICFullCovMonoGaussianModel (u32 dim)
BICFullCovMonoGaussianModel (u32 dim, f32 alpha)
BICFullCovMonoGaussianModel (u32 dim, const std::vector< BICFullCovMonoGaussianModel > &models)
BICFullCovMonoGaussianModel (u32 dim, f32 alpha, const std::vector< BICFullCovMonoGaussianModel > &models)
const f32 likelihood () const
const f32 score () const
const f32 stopscore () const
void computeGLR (const BICFullCovMonoGaussianModel &x, const BICFullCovMonoGaussianModel &y)
compute Brandt's generalized likelihood ratio (GLR) for the BIC criterion.
void finalize (const std::vector< BICFullCovMonoGaussianModel >)
useless??
void finalize ()
finalize the mean vector and variance matrix
void mergeModels (const BICFullCovMonoGaussianModel &x, const BICFullCovMonoGaussianModel &y)
First, the mean vectors and variance matrices of the left FullCovMonoGaussianModel x and right FullCovMonoGaussianModel y are merged into the current model.
Public Member Functions inherited from Signal::FullCovMonoGaussianModel
FullCovMonoGaussianModel (u32 dim)
represented as N(logDeterminant(variance))
const u32 dim () const
returns the feature dimension
const u32 nFrames () const
returns the number of frames seen so far
const Math::Vector< f64 > & mean () const
returns the mean vector of size dim()
const Math::Matrix< f64 > & variance () const
returns the variance matrix of size dim()xdim()
bool accumulate (const std::vector< f32 > &vec)
update the mean vector, the variance matrix, and the frame count
bool finalize ()
finalize the mean vector and variance matrix
void mergeModels (const FullCovMonoGaussianModel &x, const FullCovMonoGaussianModel &y)
merges the mean vectors and variance matrices of the left FullCovMonoGaussianModel x and right FullCovMonoGaussianModel y into the current model.
void mergeMeans (const FullCovMonoGaussianModel &x, const FullCovMonoGaussianModel &y)
merges the mean vectors of the left FullCovMonoGaussianModel x and right FullCovMonoGaussianModel y
void mergeVariance (const FullCovMonoGaussianModel &x, const FullCovMonoGaussianModel &y)
merges the variance matrices of the left FullCovMonoGaussianModel x and right FullCovMonoGaussianModel y
void reset (f32 x)
?
const f32 computeComplexity ()
BIC is a likelihood criterion penalized by the model complexity: the number of parameters in the model.
void computeL ()
compute the likelihood as N(logDeterminant(variance))
const f32 relativeLikelihood (const FullCovMonoGaussianModel &x) const
compute the relative likelihood
Private Attributes
f32 glr_
Additional Inherited Members
Protected Attributes inherited from Signal::FullCovMonoGaussianModel
Math::Vector< f64 > mean_
Math::Matrix< f64 > variance_
u32 nFrames_
f32 likelihood_
Detailed Description
Definition at line 159 of file SegmentClustering.hh.
Member Function Documentation
void BICFullCovMonoGaussianModel::computeGLR (const BICFullCovMonoGaussianModel & x, const BICFullCovMonoGaussianModel & y)
compute Brandt's generalized likelihood ratio (GLR) for the BIC criterion.
GLR is calculated as 1/2(alldataLikelihood - leftLikelihood - rightLikelihood)
Definition at line 137 of file SegmentClustering.cc.
References likelihood().
Referenced by mergeModels().
void Signal::BICFullCovMonoGaussianModel::finalize (const std::vector< BICFullCovMonoGaussianModel >) inline
useless??
Definition at line 197 of file SegmentClustering.hh.
void BICFullCovMonoGaussianModel::finalize (void)
finalize the mean vector and variance matrix
Definition at line 141 of file SegmentClustering.cc.
References Signal::FullCovMonoGaussianModel::computeL(), and Signal::FullCovMonoGaussianModel::finalize().
Referenced by Signal::CorrFullCovMonoGaussianModel::finalize().
const f32 Signal::BICFullCovMonoGaussianModel::likelihood () const inline
Returns
the N(logDeterminant(variance)) likelihood
Definition at line 175 of file SegmentClustering.hh.
Referenced by computeGLR().
void BICFullCovMonoGaussianModel::mergeModels (const BICFullCovMonoGaussianModel & x, const BICFullCovMonoGaussianModel & y)
First, the mean vectors and variance matrices of the left FullCovMonoGaussianModel x and right FullCovMonoGaussianModel y are merged into the current model.
Second, the likelihood of the current model is calculated, and finally the GLR is calculated for the merged, the left, and the right model.
Definition at line 146 of file SegmentClustering.cc.
References computeGLR(), Signal::FullCovMonoGaussianModel::computeL(), and Signal::FullCovMonoGaussianModel::mergeModels().
Referenced by Signal::KL2FullCovMonoGaussianModel::mergeModels(), and Signal::CorrFullCovMonoGaussianModel::mergeModels().
const f32 Signal::BICFullCovMonoGaussianModel::score () const inline
Returns
the generalized likelihood ratio (GLR) (or Gish distance)
Definition at line 180 of file SegmentClustering.hh.
const f32 Signal::BICFullCovMonoGaussianModel::stopscore () const inline
Returns
the GLR stop score for the BIC criterion
Definition at line 185 of file SegmentClustering.hh.
The documentation for this class was generated from the following files:
SegmentClustering.hh
SegmentClustering.cc