Sprint: Nn::NeuralNetworkTrainer< T > Class Template Reference
Nn::NeuralNetworkTrainer< T > Class Template Reference
Base class for any neural network trainer.
#include <NeuralNetworkTrainer.hh>
Public Types
enum TrainerType {
dummy, feedForwardTrainer, frameClassificationErrorAccumulator, meanAndVarianceAccumulator,
networkEvaluator, autoencoderTrainer, pythonTrainer, pythonEvaluator
}
Public Member Functions
NeuralNetworkTrainer (const Core::Configuration &config)
virtual void initializeTrainer (u32 batchSize)
virtual void initializeTrainer (u32 batchSize, std::vector< u32 > &streamSizes)
virtual void finalize ()
NnMatrix & getOutputActivation ()
get activations of output layer
bool hasNetwork () const
returns whether trainer has a network
bool hasEstimator () const
returns whether trainer has an estimator
bool weightedAccumulation () const
returns whether frame weights are used
u32 batchSize () const
returns current batch size (equal to size of activations)
bool isInitialized () const
returns whether trainer is initialized
bool measuresTime () const
returns whether trainer measures computation time
Criterion< T > & criterion ()
NeuralNetwork< T > & network ()
return reference to network
const NeuralNetwork< T > & network () const
u32 nLayers () const
return reference to network
Estimator< T > & estimator ()
return reference to estimator
const Estimator< T > & estimator () const
Regularizer< T > & regularizer ()
return reference to regularizer
const Regularizer< T > & regularizer () const
void setClassWeights (const Math::Vector< T > *vector)
sets class weights to values in vector
virtual bool needsToProcessAllFeatures () const
returns whether trainer needs to process all features, i.e.
virtual void setBatchSize (u32 batchSize)
resize activations (necessary when batch size has changed)
virtual bool isNetworkOutputRepresentingClassLabels ()
if we have a network, is its output layer representing the class label posterior probabilities
virtual bool hasClassLabelPosteriors ()
whether we can call getClassLabelPosteriors()
virtual NnMatrix & getClassLabelPosteriors ()
returns the posteriors after a call to processBatch_feedInput()
virtual int getClassLabelPosteriorDimension ()
returns posterior dimension
virtual bool allowsDownsampling () const
virtual void processBatch_feedInput (std::vector< NnMatrix > &features, NnVector *weights, Bliss::Segment *segment)
Override this method for the NN forward pass in NN training.
virtual void processBatch_finishWithError (T error, NnMatrix &errorSignal)
Override this method for supervised training.
virtual void processBatch_finishWithError_naturalPairing (T error, NnMatrix &errorSignal)
This is a special variant of processBatch_finishWithError(), where the error signal is already related to the natural pairing of the objective function with the last layer activation function.
virtual void processBatch_finishWithAlignment (Math::CudaVector< u32 > &alignment)
Override this method for supervised training with a criterion based on an alignment.
virtual void processBatch_finishWithSpeechSegment (Bliss::SpeechSegment &segment)
Override this method for supervised training with a criterion based on a segment.
virtual void processBatch_finish ()
Override this method for unsupervised training to finish a minibatch.
virtual void resetHistory ()
virtual void logBatchTimes () const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Member Functions
static NeuralNetworkTrainer< T > * createSupervisedTrainer (const Core::Configuration &config)
static NeuralNetworkTrainer< T > * createUnsupervisedTrainer (const Core::Configuration &config)
Static Public Attributes
static const Core::Choice choiceNetworkTrainer
static const Core::ParameterChoice paramNetworkTrainer
static const Core::ParameterInt paramEpoch
static const Core::ParameterBool paramWeightedAccumulation
static const Core::ParameterBool paramMeasureTime
Protected Member Functions
virtual void logProperties () const
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes
Criterion< T > * criterion_
bool weightedAccumulation_
const Math::Vector< T > * classWeights_
const bool measureTime_
bool needsNetwork_
Core::XmlChannel statisticsChannel_
bool needInit_
NeuralNetwork< T > * network_
Estimator< T > * estimator_
Regularizer< T > * regularizer_
Protected Attributes inherited from Core::Configurable
Configuration config
Private Types
typedef Core::Component Precursor
typedef Types< T >::NnVector NnVector
typedef Types< T >::NnMatrix NnMatrix
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Detailed Description
template<class T>
class Nn::NeuralNetworkTrainer< T >
Base class for any neural network trainer.
Unsupervised trainers are instantiated in BufferedFeatureExtractor, supervised trainers are instantiated in BufferedAlignedFeatureProcessor or BufferedSegmentFeatureProcessor.
"trainer" is maybe a bad word, because it is more like the base class for any possible action we can do on the features - however, training a NN is the most common one, so this base class already comes with these instances:
NeuralNetwork (optional in some cases)
Criterion (not used in all cases)
Estimator (not used in all cases)
Regularizer (not used in all cases)
For Criterion, Estimator and Regularizer, there exists dummy types which will be taken by default if you don't need it.
Definition at line 67 of file NeuralNetworkTrainer.hh.
Member Function Documentation
template<class T> u32 Nn::NeuralNetworkTrainer< T >::batchSize () const inline
returns current batch size (equal to size of activations)
Definition at line 147 of file NeuralNetworkTrainer.hh.
Referenced by Nn::PythonTrainer< T >::getClassLabelPosteriorDimension(), and Nn::FeedForwardAutoTrainer< T >::needsToProcessAllFeatures().
template<class T> Estimator<T>& Nn::NeuralNetworkTrainer< T >::estimator () inline
return reference to estimator
Definition at line 176 of file NeuralNetworkTrainer.hh.
Referenced by Nn::BufferedFeatureExtractor< T >::setWindowedFeature(), and Nn::FeedForwardTrainer< f64 >::statistics().
template<class T> virtual int Nn::NeuralNetworkTrainer< T >::getClassLabelPosteriorDimension () inline virtual
returns posterior dimension
Reimplemented in Nn::PythonTrainer< T >.
Definition at line 220 of file NeuralNetworkTrainer.hh.
template<class T> virtual NnMatrix& Nn::NeuralNetworkTrainer< T >::getClassLabelPosteriors () inline virtual
returns the posteriors after a call to processBatch_feedInput()
Reimplemented in Nn::PythonTrainer< T >.
Definition at line 214 of file NeuralNetworkTrainer.hh.
template<class T> NnMatrix& Nn::NeuralNetworkTrainer< T >::getOutputActivation () inline
get activations of output layer
Definition at line 130 of file NeuralNetworkTrainer.hh.
template<class T> virtual bool Nn::NeuralNetworkTrainer< T >::hasClassLabelPosteriors () inline virtual
whether we can call getClassLabelPosteriors()
Reimplemented in Nn::PythonTrainer< T >.
Definition at line 208 of file NeuralNetworkTrainer.hh.
template<class T> bool Nn::NeuralNetworkTrainer< T >::hasEstimator () const inline
returns whether trainer has an estimator
Definition at line 139 of file NeuralNetworkTrainer.hh.
Referenced by Nn::BufferedFeatureExtractor< T >::setWindowedFeature().
template<class T> bool Nn::NeuralNetworkTrainer< T >::hasNetwork () const inline
returns whether trainer has a network
Definition at line 135 of file NeuralNetworkTrainer.hh.
template<class T> bool Nn::NeuralNetworkTrainer< T >::isInitialized () const inline
returns whether trainer is initialized
Definition at line 151 of file NeuralNetworkTrainer.hh.
Referenced by Nn::BufferedFeatureExtractor< T >::setWindowedFeature().
template<class T> virtual bool Nn::NeuralNetworkTrainer< T >::isNetworkOutputRepresentingClassLabels () inline virtual
if we have a network, is its output layer representing the class label posterior probabilities
Reimplemented in Nn::PythonTrainer< T >.
Definition at line 204 of file NeuralNetworkTrainer.hh.
template<class T> bool Nn::NeuralNetworkTrainer< T >::measuresTime () const inline
returns whether trainer measures computation time
Definition at line 155 of file NeuralNetworkTrainer.hh.
template<class T> virtual bool Nn::NeuralNetworkTrainer< T >::needsToProcessAllFeatures () const inline virtual
returns whether trainer needs to process all features, i.e.
for batch training
Reimplemented in Nn::NetworkEvaluator< T >, Nn::MeanAndVarianceTrainer< T >, Nn::MeanAndVarianceTrainer< f32 >, Nn::FrameErrorEvaluator< T >, Nn::FeedForwardAutoTrainer< T >, and Nn::PythonEvaluator< T >.
Definition at line 197 of file NeuralNetworkTrainer.hh.
Referenced by Nn::BufferedFeatureExtractor< T >::setWindowedFeature().
template<class T> NeuralNetwork<T>& Nn::NeuralNetworkTrainer< T >::network () inline
return reference to network
Definition at line 163 of file NeuralNetworkTrainer.hh.
Referenced by Nn::FeedForwardTrainer< f64 >::statistics().
template<class T> u32 Nn::NeuralNetworkTrainer< T >::nLayers () const inline
return reference to network
Definition at line 172 of file NeuralNetworkTrainer.hh.
template<class T> virtual void Nn::NeuralNetworkTrainer< T >::processBatch_feedInput (std::vector< NnMatrix > & features, NnVector * weights, Bliss::Segment * segment) inline virtual
Override this method for the NN forward pass in NN training.
The weights are for the individual frames. Note that the pointer has to stay valid until the processBatch_finish* call. Can be NULL. The segment is only given if the calling feature extractor is in segmentwise mode. Otherwise it's NULL.
Reimplemented in Nn::NetworkEvaluator< T >, Nn::MeanAndVarianceTrainer< T >, Nn::MeanAndVarianceTrainer< f32 >, Nn::FrameErrorEvaluator< T >, Nn::FeedForwardAutoTrainer< T >, Nn::FeedForwardTrainer< T >, Nn::FeedForwardTrainer< f64 >, and Nn::PythonTrainer< T >.
Definition at line 238 of file NeuralNetworkTrainer.hh.
Referenced by Nn::BufferedFeatureExtractor< T >::setWindowedFeature().
template<class T> virtual void Nn::NeuralNetworkTrainer< T >::processBatch_finish () inline virtual
Override this method for unsupervised training to finish a minibatch.
Reimplemented in Nn::NetworkEvaluator< T >, Nn::FrameErrorEvaluator< T >, Nn::FeedForwardAutoTrainer< T >, Nn::PythonEvaluator< T >, and Nn::PythonTrainer< T >.
Definition at line 273 of file NeuralNetworkTrainer.hh.
Referenced by Nn::BufferedFeatureExtractor< T >::setWindowedFeature().
template<class T> virtual void Nn::NeuralNetworkTrainer< T >::processBatch_finishWithAlignment (Math::CudaVector< u32 > & alignment) inline virtual
Override this method for supervised training with a criterion based on an alignment.
Reimplemented in Nn::FrameErrorEvaluator< T >, Nn::FeedForwardAutoTrainer< T >, Nn::FeedForwardTrainer< T >, Nn::FeedForwardTrainer< f64 >, and Nn::PythonTrainer< T >.
Definition at line 263 of file NeuralNetworkTrainer.hh.
template<class T> virtual void Nn::NeuralNetworkTrainer< T >::processBatch_finishWithError (T error, NnMatrix & errorSignal) inline virtual
Override this method for supervised training.
It's usually used for backprop + collects the gradient, where error is the accumulated value of the objective function, and errorSignal is the gradient of the objective function. If you use this directly, you ignore the training criterion.
Definition at line 246 of file NeuralNetworkTrainer.hh.
template<class T> virtual void Nn::NeuralNetworkTrainer< T >::processBatch_finishWithError_naturalPairing (T error, NnMatrix & errorSignal) inline virtual
This is a special variant of processBatch_finishWithError(), where the error signal is already related to the natural pairing of the objective function with the last layer activation function.
Reimplemented in Nn::FeedForwardTrainer< T >, and Nn::FeedForwardTrainer< f64 >.
Definition at line 258 of file NeuralNetworkTrainer.hh.
template<class T> virtual void Nn::NeuralNetworkTrainer< T >::processBatch_finishWithSpeechSegment (Bliss::SpeechSegment & segment) inline virtual
Override this method for supervised training with a criterion based on a segment.
Reimplemented in Nn::NetworkEvaluator< T >, Nn::FrameErrorEvaluator< T >, Nn::FeedForwardTrainer< T >, Nn::FeedForwardTrainer< f64 >, Nn::PythonEvaluator< T >, and Nn::PythonTrainer< T >.
Definition at line 268 of file NeuralNetworkTrainer.hh.
template<class T> Regularizer<T>& Nn::NeuralNetworkTrainer< T >::regularizer () inline
return reference to regularizer
Definition at line 185 of file NeuralNetworkTrainer.hh.
template<typename T > void NeuralNetworkTrainer::setBatchSize (u32 batchSize) virtual
resize activations (necessary when batch size has changed)
Reimplemented in Nn::FeedForwardTrainer< T >, and Nn::FeedForwardTrainer< f64 >.
Definition at line 94 of file NeuralNetworkTrainer.cc.
Referenced by Nn::BufferedFeatureExtractor< T >::setWindowedFeature().
template<typename T> void NeuralNetworkTrainer::setClassWeights (const Math::Vector< T > * vector)
sets class weights to values in vector
Definition at line 114 of file NeuralNetworkTrainer.cc.
References Core::Component::criticalError(), Core::Component::log(), Core::Application::us(), and Core::Component::warning().
template<class T> bool Nn::NeuralNetworkTrainer< T >::weightedAccumulation () const inline
returns whether frame weights are used
Definition at line 143 of file NeuralNetworkTrainer.hh.
The documentation for this class was generated from the following files:
NeuralNetworkTrainer.hh
NeuralNetworkTrainer.cc