Sprint: Speech::FsaCache Class Reference
Speech::FsaCache Class Reference
Cache for Fsa object.
#include <FsaCache.hh>
Public Member Functions
FsaCache (const Core::Configuration &, Fsa::StoredComponents=Fsa::storeAll)
bool setDependencies (const Core::DependencySet &)
void forceInputAlphabet (Fsa::ConstAlphabetRef input)
Input alphabet of read transducer will be overwritten by.
void forceOutputAlphabet (Fsa::ConstAlphabetRef output)
Output alphabet of read transducer will be overwritten by.
Fsa::ConstAutomatonRef find (const std::string &id)
void insert (const std::string &id, Fsa::ConstAutomatonRef f)
template<class Builder >
Fsa::ConstAutomatonRef get (Builder)
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Private Member Functions
Fsa::ConstAutomatonRef read (const std::string &id)
void write (const std::string &id, Fsa::ConstAutomatonRef)
Private Attributes
Core::Archive * archive_
Fsa::ConstAlphabetRef inputAlphabet_
If valid, input alphabet of new transducers is overwritten by this one.
Fsa::ConstAlphabetRef outputAlphabet_
If valid, output alphabet of new transducers is overwritten by this one.
Fsa::StoredComponents whatToStore_
bool readOnly_
Static Private Attributes
static const Core::ParameterString paramPath
static const Core::ParameterBool paramReadOnly
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Cache for Fsa object.
Cache stores FSA objects in a archive. Use 'find', to get an existing object. Use 'insert' to add a new object. Use 'get', to retrieve object which will be created if not existent.
Remark: This is a simple implementation, once Core::ObjectCache supports reading of Core::Ref, this implementation could be easly merged with it.
Definition at line 39 of file FsaCache.hh.
Member Function Documentation
void Speech::FsaCache::forceInputAlphabet (Fsa::ConstAlphabetRef input) inline
Input alphabet of read transducer will be overwritten by.
Parameters
input.
Definition at line 64 of file FsaCache.hh.
void Speech::FsaCache::forceOutputAlphabet (Fsa::ConstAlphabetRef output) inline
Output alphabet of read transducer will be overwritten by.
Parameters
output.
Definition at line 68 of file FsaCache.hh.
References Core::log().
bool FsaCache::setDependencies (const Core::DependencySet & dependencies)
Warning
Apparently dependencies on Alpha and Intel differ.
Definition at line 51 of file FsaCache.cc.
References Core::Ref< T >::get(), Core::ref(), Core::Ref< T >::reset(), Core::DependencySet::satisfies(), and verify.
Referenced by Speech::AlignmentWithLinearSegmentationNode::configure().
Member Data Documentation
Fsa::ConstAlphabetRef Speech::FsaCache::inputAlphabet_ private
If valid, input alphabet of new transducers is overwritten by this one.
Definition at line 47 of file FsaCache.hh.
Fsa::ConstAlphabetRef Speech::FsaCache::outputAlphabet_ private
If valid, output alphabet of new transducers is overwritten by this one.
Definition at line 49 of file FsaCache.hh.
The documentation for this class was generated from the following files:
FsaCache.hh
FsaCache.cc