Sprint: Mm::DiscriminativeMixtureEstimator Class Reference
Mm::DiscriminativeMixtureEstimator Class Reference
discriminative mixture estimator: base class
#include <DiscriminativeMixtureEstimator.hh>
Public Member Functions
DiscriminativeMixtureEstimator (const Core::Configuration &)
DiscriminativeMixtureEstimator.
virtual void removeDensitiesWithLowWeight (Weight minObservationWeight, Weight minRelativeWeight=0)
Removes densities whose absolute mixture weight has less weight than.
virtual void accumulate (const AbstractMixtureEstimator &toAdd)
virtual void accumulateDenominator (DensityIndex, const FeatureVector &, Weight)
const std::vector< Weight > & previousMixtureWeights () const
Weight previousMixtureWeight (DensityIndex dns) const
Weight logPreviousMixtureWeight (DensityIndex dns) const
void setPreviousMixture (const Mixture *)
Public Member Functions inherited from Mm::AbstractMixtureEstimator
virtual void addDensity (Core::Ref< GaussDensityEstimator > densityEstimator)
AbstractMixtureEstimator: base class.
virtual void clear ()
void removeDensitiesWithZeroWeight ()
Removes densities whose mean estimator has weight 0.0.
void accumulate (DensityIndex, const FeatureVector &)
void accumulate (DensityIndex, const FeatureVector &, Weight)
virtual void reset ()
virtual Mixture * estimate (const ReferenceIndexMap< GaussDensityEstimator > &densityMap, bool normalizeWeights=true)
Weight getWeight () const
size_t nDensities () const
const DensityEstimators & densityEstimators () const
std::vector< Weight > & weights ()
const std::vector< Weight > & weights () const
void setDensityEstimators (DensityEstimators estimators)
bool checkEventsWithZeroWeight (std::string &message)
virtual void read (Core::BinaryInputStream &, const std::vector< Core::Ref< GaussDensityEstimator >> &, u32 version)
virtual void write (Core::BinaryOutputStream &, const ReferenceIndexMap< GaussDensityEstimator > &) const
virtual void write (Core::XmlWriter &, const ReferenceIndexMap< GaussDensityEstimator > &, std::string label="") const
bool equalTopology (const AbstractMixtureEstimator &toCompare, const ReferenceIndexMap< GaussDensityEstimator > &densityMap, const ReferenceIndexMap< GaussDensityEstimator > &densityMapToCompare) const
virtual bool equalWeights (const AbstractMixtureEstimator &toCompare) const
void addMixture (const AbstractMixtureEstimator &toAdd)
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Static Public Member Functions
static DensityIndex accumulate (Core::BinaryInputStreams &is, Core::BinaryOutputStream &os)
Static Public Member Functions inherited from Mm::AbstractMixtureEstimator
static DensityIndex accumulate (Core::BinaryInputStreams &is, Core::BinaryOutputStream &os)
Protected Member Functions
virtual void removeDensity (DensityIndex indexInMixture)
Protected Member Functions inherited from Mm::AbstractMixtureEstimator
DensityIndex densityIndexWithMaxWeight () const
Protected Attributes
std::vector< Weight > previousMixtureWeights_
Weight minimumObservationWeight_
Protected Attributes inherited from Mm::AbstractMixtureEstimator
DensityEstimators densityEstimators_
std::vector< Weight > weights_
Private Types
typedef AbstractMixtureEstimator Precursor
Static Private Attributes
static const Core::ParameterFloat paramMinObservationWeight
Friends
class MixtureSetEstimatorIndexMap
Additional Inherited Members
Public Types inherited from Mm::AbstractMixtureEstimator
typedef std::vector< Core::Ref< GaussDensityEstimator > > DensityEstimators
Detailed Description
discriminative mixture estimator: base class
Definition at line 27 of file DiscriminativeMixtureEstimator.hh.
Constructor & Destructor Documentation
DiscriminativeMixtureEstimator::DiscriminativeMixtureEstimator (const Core::Configuration & c)
DiscriminativeMixtureEstimator.
Definition at line 24 of file DiscriminativeMixtureEstimator.cc.
References verify.
Member Function Documentation
void DiscriminativeMixtureEstimator::removeDensitiesWithLowWeight (Weight minObservationWeight, Weight minRelativeWeight = 0) virtual
Removes densities whose absolute mixture weight has less weight than.
Parameters
minObservationWeight,or whose relative mixture weight is less than
minRelativeWeight. The density with the most density(!)-weight is kept by all means.
Reimplemented from Mm::AbstractMixtureEstimator.
Definition at line 34 of file DiscriminativeMixtureEstimator.cc.
References Core::Component::log(), require, required_cast, and Core::Application::us().
void DiscriminativeMixtureEstimator::setPreviousMixture (const Mixture * mixture)
Parameters
mixture previous mixture
Definition at line 80 of file DiscriminativeMixtureEstimator.cc.
References require.
Referenced by Mm::DiscriminativeMixtureSetEstimator::loadPreviousMixtureSet().
The documentation for this class was generated from the following files:
DiscriminativeMixtureEstimator.hh
DiscriminativeMixtureEstimator.cc