Sprint: Lm::WordlistInterfaceLm Class Reference
Lm::WordlistInterfaceLm Class Reference
Abstract bsse class for Philips- and (legacy) RWTH language model adaptors.
#include <WordlistInterface.hh>
Classes
class HistoryDescriptor
class InternalWordlist
Public Member Functions
WordlistInterfaceLm (const Core::Configuration &, Bliss::LexiconRef)
virtual History startHistory () const
Language model history for beginning of a sentence.
virtual History extendedHistory (const History &, Token w) const
Language model history for the next sentence position.
virtual History reducedHistory (const History &, u32 limit) const
Reduce amount on conditioning information.
virtual std::string formatHistory (const History &) const
Create string representation of history (mainly for debugging purposes).
Public Member Functions inherited from Lm::IndexMappedLm
IndexMappedLm (const Core::Configuration &, Bliss::LexiconRef)
Public Member Functions inherited from Lm::LanguageModel
Token sentenceBeginToken () const
virtual Lm::Score sentenceBeginScore () const
Token sentenceEndToken () const
Token sentenceBoundaryToken () const
virtual void init ()
precondition: the token inventory is set and fixed
virtual void getDependencies (Core::DependencySet &dependencies) const
Bliss::LexiconRef lexicon () const
const TokenInventory & tokenInventory () const
Fsa::ConstAlphabetRef tokenAlphabet () const
virtual Fsa::ConstAutomatonRef getFsa () const
Convert language model into an EQUIVALENT acceptor.
virtual Score score (const History &, Token w) const =0
Probability of a token to occur with a given history.
virtual bool scoreCached (const History &, Token w) const
Some LMs might cache scores and thus provide fast access.
virtual Score sentenceEndScore (const History &) const
Probability for sentence to end in current position.
virtual CompiledBatchRequest * compileBatchRequest (const BatchRequest &, Score scale=1.0) const
Preprocess a batch request.
virtual void getBatch (const History &h, const CompiledBatchRequest *r, std::vector< f32 > &result) const
Get probabilities for a (large) set of syntactic tokens given a history.
virtual Core::Ref< const LanguageModel > lookaheadLanguageModel () const
Returns the LanguageModel that shall be used for lookahead (useful for CombinedLM when we do not want to reinstanciate the model)
virtual Core::Ref< const LanguageModel > recombinationLanguageModel () const
Returns the LanguageModel that shall be used for recombination (useful for CombinedLM when we do not want to reinstanciate the model)
virtual void setSegment (Bliss::SpeechSegment const *s)
For some cheating language models we need to know the correct transcription.
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Attributes
static const u32 historyLengthLimit = 2
Built-in limit: maximum number of word in the history (excluding the current word)
static const Core::ParameterInt paramHistoryLimit
static const Core::ParameterBool paramUseBackingOff
Protected Member Functions
virtual const char * internalClassName (InternalClassIndex) const
u32 maxHistoryLength () const
Maximum number of word considered in the history (excluding the current word)
void setSignificantHistoryLength (u32 l)
Set the number of words which are significant to loaded language model (excluding the current word).
virtual HistoryHash hashKey (HistoryHandle) const
If isEquivalent() is true For two descriptors, hashKey() must return the same value for both of them.
virtual bool isEquivalent (HistoryHandle, HistoryHandle) const
Test if two descriptors represent the same context.
virtual std::string format (HistoryHandle) const
History history (const HistoryDescriptor *hd) const
virtual u32 backingOffHistoryLength (const WordlistInterfaceLm::HistoryDescriptor *) const
Protected Member Functions inherited from Lm::IndexMappedLm
void initializeMapping (InternalClassIndex nInternalClasses)
InternalClassIndex newClass ()
void mapToken (Token, InternalClassIndex idx)
bool isTokenMapped (Token t) const
void finalizeMapping ()
InternalClassIndex nInternalClasses () const
InternalClassIndex internalClassIndex (Token t) const
Token externalToken (InternalClassIndex i) const
bool isClassUsed (InternalClassIndex i) const
Score classEmissionScore (InternalClassIndex c) const
Protected Member Functions inherited from Lm::LanguageModel
History history (HistoryHandle hd) const
template<class LM >
const LM::HistoryDescriptor * descriptor (const History &hh) const
void setTokenInventory (const TokenInventory *_tokenInventory)
void setTokenInventoryAndAlphabet (const TokenInventory *_tokenInventory, Fsa::ConstAlphabetRef _tokenAlphabet)
Token getToken (const std::string &word) const
virtual Token getSpecialToken (const std::string &name, bool required=false) const
const Bliss::SyntacticToken * getSpecialSyntacticToken (const std::string &name, bool required) const
Token fallbackToken () const
Find token to use for unknown words.
virtual void createSpecialTokens ()
virtual void load ()
void requireSentenceBoundaryToken ()
Call this function before init(), iff your language model requires a sentence boundary token to be defined in the lexicon.
LanguageModel (const Core::Configuration &c, Bliss::LexiconRef l)
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Member Functions inherited from Lm::ReferenceCountingHistoryManager
virtual HistoryHandle acquire (HistoryHandle hd)
Create a new reference to this history.
virtual void release (HistoryHandle hd)
Destroy a reference to this history.
Protected Attributes
InternalWordlist * wl
Protected Attributes inherited from Lm::LanguageModel
HistoryManager * historyManager_
Concrete LanguageModels should set this member in their constructor or load() method.
Core::Dependency dependency_
Protected Attributes inherited from Core::Configurable
Configuration config
Private Types
typedef WordlistInterfaceLm Self
Private Member Functions
void setMaxHistoryLength (u32 l)
Private Attributes
u32 maxHistoryLength_
bool useBackingOff_
u32 * backingOffCounterBase_
u32 ** backingOffCounter_
Core::XmlChannel backingOffStatistics_
Additional Inherited Members
Protected Types inherited from Lm::IndexMappedLm
typedef u32 InternalClassIndex
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Static Protected Attributes inherited from Lm::IndexMappedLm
static const InternalClassIndex invalidClass
Detailed Description
Abstract bsse class for Philips- and (legacy) RWTH language model adaptors.
Definition at line 33 of file WordlistInterface.hh.
Member Function Documentation
History WordlistInterfaceLm::extendedHistory (const History & , Token w) const virtual
Language model history for the next sentence position.
This is the given history with given word appended, i.e. w becomes the most recent word. Typically the returned history will reflect the finite memory of the language model: for an m-gram it will only contain the m-1 most recent words. In WFST terminology this is the target state of the outgoin arc labeled w.
Implements Lm::LanguageModel.
Definition at line 156 of file WordlistInterface.cc.
std::string WordlistInterfaceLm::formatHistory (const History & h) const virtual
Create string representation of history (mainly for debugging purposes).
By default this function just delegates to History::format(), but language models may specialize formatHistory() to give more readable information, which would be inaccessible from the HistoryDescriptor alone. If your language model is m-gram like, describe the history chronologically, i.e. most recent word last.
Reimplemented from Lm::LanguageModel.
Definition at line 187 of file WordlistInterface.cc.
References Core::form(), and Lm::History::format().
HistoryHash WordlistInterfaceLm::hashKey (HistoryHandle) const protected virtual
If isEquivalent() is true For two descriptors, hashKey() must return the same value for both of them.
Implements Lm::HistoryManager.
Definition at line 102 of file WordlistInterface.cc.
bool WordlistInterfaceLm::isEquivalent (HistoryHandle , HistoryHandle) const protected virtual
Test if two descriptors represent the same context.
Note: The "check for equal pointers" optimization is already done before this function is called.
Implements Lm::HistoryManager.
Definition at line 117 of file WordlistInterface.cc.
References Core::form().
u32 Lm::WordlistInterfaceLm::maxHistoryLength () const inline protected
Maximum number of word considered in the history (excluding the current word)
Definition at line 64 of file WordlistInterface.hh.
References setSignificantHistoryLength().
History WordlistInterfaceLm::reducedHistory (const History & h, u32 limit) const virtual
Reduce amount on conditioning information.
Parameters
limit number of predecessor word taken into account. (The effective m-grammity of the returned history is limit + 1.)
Reimplemented from Lm::LanguageModel.
Definition at line 172 of file WordlistInterface.cc.
void WordlistInterfaceLm::setSignificantHistoryLength (u32 l) protected
Set the number of words which are significant to loaded language model (excluding the current word).
Should be called during initialization to indicate actual m-grammity of the loaded language model file.
Definition at line 88 of file WordlistInterface.cc.
References ensure, Core::Component::log(), and Core::Component::warning().
Referenced by maxHistoryLength().
History WordlistInterfaceLm::startHistory () const virtual
Language model history for beginning of a sentence.
Typically this is the bigram history which contains just the sentence start (or boundary) token. In the terminology of finite-state automata this is the initial state.
Implements Lm::LanguageModel.
Definition at line 138 of file WordlistInterface.cc.
References require.
Member Data Documentation
const u32 Lm::WordlistInterfaceLm::historyLengthLimit = 2 static
Built-in limit: maximum number of word in the history (excluding the current word)
Definition at line 40 of file WordlistInterface.hh.
The documentation for this class was generated from the following files:
WordlistInterface.hh
WordlistInterface.cc