Sprint: Cart::XmlTrainingPlanBuilderElement Class Reference
Cart::XmlTrainingPlanBuilderElement Class Reference
<decision-tree-training> <properties-definition> ...
#include <Parser.hh>
Public Types
typedef DecisionTreeTrainer::TrainingPlan::Step Step
typedef DecisionTreeTrainer::TrainingPlan TrainingPlan
Public Types inherited from Core::XmlRegularElement
typedef int State
Public Types inherited from Core::XmlElement
typedef XmlElement * pointer
Public Types inherited from Core::XmlContext
typedef XmlContext Self
typedef void(Self::* StartHandler) (const XmlAttributes atts)
typedef void(Self::* EndHandler) ()
typedef void(Self::* CharactersHandler) (const char *ch, int len)
Public Types inherited from Core::BuildDelegation< T >
typedef Delegation< const T & > ParsedDelegation
typedef Delegation< T * > CreatedDelegation
typedef ParsedDelegation::Target ParsedHandler
typedef CreatedDelegation::Target CreatedHandler
Public Member Functions
XmlTrainingPlanBuilderElement (const char *name, XmlContext *context)
void set (TrainingPlan *trainigPlan)
void start (const XmlAttributes atts)
Handle start of the current XML element.
void end ()
Handle end of the current XML element.
void characters (const char *ch, int len)
Handle charcter data in the current XML element.
Public Member Functions inherited from Core::XmlRegularElement
XmlRegularElement (const char *_name, XmlContext *_context)
virtual XmlElement * element (const char *name)
Determine the state to be entered for a nested XML element.
void addTransition (State from, State to, XmlElement *child)
Add a transition to the automaton.
void addFinalState (State state)
Mark state as final.
void draw (std::ostream &) const
Write automaton in Graphviz Dot format.
Public Member Functions inherited from Core::XmlParentElement
XmlParentElement (const char *_name, XmlContext *_context)
void flattenUnknownElements ()
void ignoreUnknownElements ()
Public Member Functions inherited from Core::XmlElement
XmlElement (const char *_name, XmlContext *_context)
const char * name () const
XmlContext * context () const
virtual XmlSchemaParser * parser ()
virtual bool matches (const char *_name) const
Public Member Functions inherited from Core::BuildDelegation< T >
void setParsedHandler (ParsedHandler *handler)
template<class HandlerClass >
void setParsedHandler (HandlerClass &handler, void(HandlerClass::*deleg)(const T &))
void resetParsedHandler ()
void setCreatedHandler (CreatedHandler *handler)
template<class HandlerClass >
void setCreatedHandler (HandlerClass &handler, void(HandlerClass::*deleg)(T *))
void resetCreatedHandler ()
Protected Types
typedef XmlTrainingPlanBuilderElement Self
typedef XmlRegularElement Precursor
Protected Member Functions
void map (const PropertyMap &map)
void maxLeaves (const u32 &maxLeaves)
void step (Step *step)
Protected Member Functions inherited from Core::XmlParentElement
virtual XmlElement * unexpectedElement ()
Protected Member Functions inherited from Core::XmlElement
XmlElement * collect (XmlElement *child)
Collects child elements.
Protected Member Functions inherited from Core::BuildDelegation< T >
void delegate (T *t)
Calls first parsed handler and then created handler.
void delegateOrDelete (T *t)
Calls first parsed handler and then created handler; if no created handler exists, t is deleted.
T * delegateAndCreate (T *t)
Calls first parsed handler and then created handler; return t if no created handler exists, else return a newly created instance of T .
bool delegateParsed (const T &t)
Calls parsed handler.
bool delegateCreated (T *t)
Calls created handler.
Protected Member Functions inherited from Core::Delegation< const T & >
void set (Target *target)
void set (TargetClass &tc, void(TargetClass::*tm)(const T &))
void reset ()
bool hasTarget ()
void delegate (const T &t)
Protected Member Functions inherited from Core::Delegation< T * >
void set (Target *target)
void set (TargetClass &tc, void(TargetClass::*tm)(T *))
void reset ()
bool hasTarget ()
void delegate (T *t)
Private Attributes
TrainingPlan * trainingPlan_
u32 stepCount_
PropertyMap * mapFromFile_
XmlPropertiesDefinitionBuilderElement * propertyMapParser_
XmlUnsignedBuilderElement * maxLeavesParser_
XmlStepBuilderElement * stepBuilder_
Additional Inherited Members
Static Public Member Functions inherited from Core::XmlContext
template<class T >
static StartHandler startHandler (void(T::*h)(const XmlAttributes atts))
template<class T >
static EndHandler endHandler (void(T::*h)())
template<class T >
static CharactersHandler charactersHandler (void(T::*h)(const char *ch, int len))
Static Public Attributes inherited from Core::XmlRegularElement
static const State initial = 0
static const State final = -1
Static Public Attributes inherited from Core::XmlElement
static const char * wildcard = " * "
Protected Attributes inherited from Core::XmlParentElement
XmlElement * unexpectedElement_
Detailed Description
<decision-tree-training> <properties-definition> ...
</properties-definition> [<max-leaves> ... </max-leaves>] <step name="..."> ... </step> ... </decision-tree-training>
Definition at line 846 of file Parser.hh.
Member Function Documentation
void XmlTrainingPlanBuilderElement::characters (const char * ch, int len) virtual
Handle charcter data in the current XML element.
Parameters
parser The XmlSchemaParser delegating the request.
Reimplemented from Core::XmlRegularElement.
Definition at line 992 of file Parser.cc.
void XmlTrainingPlanBuilderElement::end () virtual
Handle end of the current XML element.
end() is called when end tag of the current element is found.
Parameters
parser The XmlSchemaParser delegating the request.
Reimplemented from Core::XmlRegularElement.
Definition at line 985 of file Parser.cc.
References Core::BuildDelegation< T >::delegate(), Core::XmlEmptyElement::end(), and require.
void XmlTrainingPlanBuilderElement::start (const XmlAttributes atts) virtual
Handle start of the current XML element.
start() is called when the current state is entered.
Parameters
atts attributes of the XML start tag which caused the parser to enter this state. The name of the element will generally be implied by the fact that THIS state is entered.
Reimplemented from Core::XmlRegularElement.
Definition at line 979 of file Parser.cc.
References require, and Core::XmlElement::start().
The documentation for this class was generated from the following files:
Parser.hh
Parser.cc