Sprint: FsaTool Class Reference
FsaTool Class Reference
Classes
class OperationSpecification
Public Member Functions
std::string getUsage () const
Overload this method to describe the usage of the application and to give a (short) description of the application.
void writeAlphabet (ConstAlphabetRef alphabet, const std::string &fname)
OperationSpecification parseOperation (const std::string &operation) const
int main (const std::vector< std::string > &arguments)
Main entry point for an application.
Public Member Functions inherited from Core::Application
virtual std::string getVariable () const
Return the name of the environment variable.
std::string getBaseName () const
Return the applications basename.
std::string getPath () const
Return the applications path.
virtual std::string getApplicationDescription () const
virtual std::string getParameterDescription () const
virtual std::string getDefaultParameterDescription () const
void reportLowLevelError (const std::string &msg="")
Errors messages are collected and later (during closeLogging()) printed to the error channel.
void setDefaultLoadConfigurationFile (bool f)
Configure default behaviour of loading a configuration file.
void setDefaultOutputXmlHeader (bool f)
Configure default behaviour of adding a valid xml header to standard channels.
void setTitle (const std::string &t)
Set the title of the application.
void setCommentCharacters (const std::string &c)
Set the set of possible comment characters for this application.
const std::string & getCommentCharacters (void) const
Return the string of comment characters.
Core::Channel & debugChannel (void)
Returns the debug binary outpput channel.
Core::XmlChannel & debugXmlChannel (void)
Returns the debug XML channel.
MappedArchiveReader getCacheArchiveReader (const std::string &archive_name, const std::string &item)
Returns a pointer to the cache-archive reader for the archive, and the specified item contained by the archive.
MappedArchiveWriter getCacheArchiveWriter (const std::string &archive_name, const std::string &item)
Returns a pointer to the cache-archive writer for the archive, and the specified item contained by the archive.
void exit (int status)
Terminate program execution.
void atexit (std::function< void()> f)
Like std::atexit() but will be execute sooner, at our own uninit, at the end of our main(), or in our exit().
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Private Types
enum Operation {
op_best, op_cache, op_closure, op_collect,
op_complement, op_compose, op_concat, op_copy,
op_count, op_default, op_delete, op_determinize,
op_difference, op_draw, op_duplicate, op_expm,
op_extend, op_fuse, op_info, op_invert,
op_levenshtein, op_map_input, op_map_output, op_memory,
op_minimize, op_multiply, op_normalize, op_partial,
op_permute, op_posterior, op_posterior_64, op_posterior_expectation,
op_posterior_fail, op_project, op_prune, op_push,
op_random, op_remove, op_semiring, op_sort,
op_sync_prune, op_time, op_transpose, op_trim,
op_unite, op_wait, op_write
}
Private Member Functions
void oneOperand ()
void twoOperands ()
Private Attributes
Operation operation_
Stack< ConstAutomatonRef > stack_
ConstAutomatonRef first_
ConstAutomatonRef second_
ConstSemiringRef semiring_
Static Private Attributes
static Core::Choice OperationChoice
static Core::ParameterBool paramProgress
Additional Inherited Members
Static Public Member Functions inherited from Core::Application
static Application * us ()
Get the global instance of the application (Singleton)
static int main (int argc, char *argv[])
private
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Application
void logSystemInfo () const
void logVersion () const
void logResources () const
void logResourceUsage () const
void logMemoryUsage () const
MappedArchive * getCacheArchive (const std::string &archive)
void openLogging ()
Opens channels and makes initial logs.
void closeLogging (bool configAvailable=true)
Closes down channels and makes final logs.
int run (const std::vector< std::string > &arguments)
void runAtExitFuncs ()
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Static Protected Member Functions inherited from Core::Application
static bool setFromEnvironment (const std::string &variable)
static bool setFromFile (const std::string &filename)
static std::vector< std::string > setFromCommandline (const std::vector< std::string > &arguments)
Protected Attributes inherited from Core::Application
Channel::Manager * channelManager_
Core::Channel * debugChannel_
Core::XmlChannel * debugXmlChannel_
std::map< std::string, MappedArchive * > cacheArchives_
bool defaultLoadConfigurationFile_
bool defaultOutputXmlHeader_
std::string comment_
std::string configFileName_
Timer timer_
std::list< std::function< void()> > atExitFuncs_
Protected Attributes inherited from Core::Configurable
Configuration config
Static Protected Attributes inherited from Core::Application
static const ParameterBool paramLogConfiguration
static const ParameterBool paramLogResolvedResources
static const ParameterString paramConfig
static const ParameterString paramCacheArchiveFile
static const ParameterBool paramCacheArchiveReadOnly
static const ParameterBool paramHelp
static std::string path_ = "."
static std::string basename_ = ""
static Application * app_ = 0
Detailed Description
Definition at line 55 of file Tools/Fsa/Fsa.cc.
Member Function Documentation
std::string FsaTool::getUsage () const inline virtual
Overload this method to describe the usage of the application and to give a (short) description of the application.
Default return string is "usage: " + getBaseName() + "[OPTION(S)]\n" Return the usage of the application.
Normally, that method does not have to be overloaded; overload getApplicationDescription() and getParamterDescription() and getDefaultParameterDescription() instead.
Reimplemented from Core::Application.
Definition at line 148 of file Tools/Fsa/Fsa.cc.
References Core::Choice::printIdentifiers(), and Fsa::Alphabet::writeXml().
int FsaTool::main (const std::vector< std::string > & arguments) inline virtual
Main entry point for an application.
Implements Core::Application.
Definition at line 266 of file Tools/Fsa/Fsa.cc.
References Fsa::count(), Fsa::drawDot(), Fsa::multiply(), Fsa::posterior4SpecialSymbols(), Fsa::prunePosterior(), Fsa::random(), Core::Ref< T >::reset(), Fsa::staticCopy(), and Fsa::write().
The documentation for this class was generated from the following file:
Tools/Fsa/Fsa.cc