Sprint: Bliss::SpeechSegment Class Reference
Bliss::SpeechSegment Class Reference
Segment of a Recording containing speech.
#include <CorpusDescription.hh>
Public Member Functions
const std::string & orth () const
void setOrth (std::string const &o)
std::string const & leftContextOrth () const
void setLeftContextOrth (std::string const &o)
std::string const & rightContextOrth () const
void setRightContextOrth (std::string const &o)
const Speaker * speaker () const
Speaker of this utterance.
void setSpeaker (const Speaker *speaker)
SpeechSegment (Recording *)
virtual void accept (SegmentVisitor *)
Have this segment processed by a SegmentVisitor.
Public Member Functions inherited from Bliss::Segment
Segment (Type, Recording *)
Recording * recording () const
void setRecording (Recording *r)
Recording * parent () const
Type type () const
void setType (Type t)
Time start () const
Start time in seconds from begin of recording.
void setStart (Time s)
Time end () const
End time in seconds from begin of recording.
void setEnd (Time e)
TrackId track () const
Track number of this segment.
void setTrack (TrackId track)
const AcousticCondition * condition () const
Acoustic condition of this segment.
void setCondition (const AcousticCondition *condition)
Public Member Functions inherited from Bliss::ParentEntity
bool isNameReserved (const std::string &n) const
void reserveName (const std::string &n)
Public Member Functions inherited from Bliss::NamedCorpusEntity
ParentEntity * parent () const
void setParent (ParentEntity *_parent)
const std::string & name () const
std::string fullName () const
void setName (const std::string &n)
bool isAnonymous () const
Private Attributes
const Speaker * speaker_
std::string lang_
std::string orth_
std::string leftContextOrth_
std::string rightContextOrth_
Friends
class CorpusDescriptionParser
Additional Inherited Members
Public Types inherited from Bliss::Segment
enum Type { typeSpeech, typeOther, nTypes }
Static Public Attributes inherited from Bliss::Segment
static const char * typeId [nTypes]
Protected Member Functions inherited from Bliss::ParentEntity
ParentEntity (ParentEntity *_parent=0)
Protected Member Functions inherited from Bliss::NamedCorpusEntity
NamedCorpusEntity (ParentEntity *_parent=0)
Detailed Description
Segment of a Recording containing speech.
Extends Segment by (optional) speaker, language and transcription. Also has left/right-context transcription. These can be used during forced alignment as optional words to align (Usefull in case of noisy transcriptions)
Definition at line 407 of file CorpusDescription.hh.
Member Function Documentation
void SpeechSegment::accept (SegmentVisitor * v) virtual
Have this segment processed by a SegmentVisitor.
(This is an application of the Visitor pattern, in order to avoid type-information and downcasts.)
Reimplemented from Bliss::Segment.
Definition at line 148 of file CorpusDescription.cc.
References Bliss::SegmentVisitor::visitSpeechSegment().
const Speaker* Bliss::SpeechSegment::speaker () const inline
Speaker of this utterance.
Returns
Speaker of this segment, or 0 if no speaker is specified in the corpus description
See also
Speaker
Definition at line 454 of file CorpusDescription.hh.
Referenced by Nn::PythonTrainer< T >::processBatch_finishWithAlignment(), TestCorpusVisitor::visitSpeechSegment(), Bliss::SegmentOrderingVisitor::visitSpeechSegment(), Bliss::CorpusSpeakerStatisticsVisitor::visitSpeechSegment(), and Bliss::ProgressReportingVisitorAdaptor::visitSpeechSegment().
The documentation for this class was generated from the following files:
CorpusDescription.hh
CorpusDescription.cc