Sprint: Lm::BackingOffLm::Internal Class Reference
Lm::BackingOffLm::Internal Class Reference
Classes
struct InitItemOrdering
struct InitItemRange
Public Types
typedef const Bliss::Token * Token
Public Member Functions
void mapToken (TokenIndex, Token)
void reserve (NodeIndex nNodes, WordScoreIndex nWordScores)
void build (InitItem *, InitItem *)
bool writeImage (int fd, const std::string &info) const
bool mountImage (int fd, std::string &info, const Bliss::TokenInventory &)
bool isMapped () const
u32 nNodes () const
u32 nWordScores () const
void draw (std::ostream &, const std::string &title) const
Write back-off tree as DOT file for diagnostic purposes.
const BackingOffLm::Node * root () const
const Node * startHistory (TokenIndex w) const
const Node * extendedHistory (const Node *old, TokenIndex w) const
std::string formatHistory (const Node *)
const WordScore * scoresBegin (const Node *node) const
const WordScore * scoresEnd (const Node *node) const
Score score (const Node *, TokenIndex) const
Token token (TokenIndex ti) const
NodeIndex nodeIndex (const Node *node) const
const Node * node (NodeIndex index) const
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Static Public Member Functions
static Core::Ref< const Internal > peek (Core::Ref< const BackingOffLm > lm)
Protected Types
typedef std::vector< Token > Tokens
Protected Member Functions
void changeNodeCapacity (NodeIndex nNodes)
Node * newNode ()
void changeWordScoreCapacity (WordScoreIndex nWordScores)
WordScore * newWordScore ()
void buildNode (NodeIndex)
void makeRoot ()
void finalize ()
bool writeImageTokenTable (int fd) const
Protected Member Functions inherited from Lm::StaticHistoryManager
virtual HistoryHandle acquire (HistoryHandle hd)
Create a new reference to this history.
virtual void release (HistoryHandle hd)
Destroy a reference to this history.
virtual HistoryHash hashKey (HistoryHandle hd) const
If isEquivalent() is true For two descriptors, hashKey() must return the same value for both of them.
virtual bool isEquivalent (HistoryHandle lhs, HistoryHandle rhs) const
Test if two descriptors represent the same context.
Protected Member Functions inherited from Lm::HistoryManager
virtual std::string format (HistoryHandle hd) const
Protected Attributes
Tokens tokens_
Node * nodes_
Node * nodesTail_
Node * nodesEnd_
WordScore * wordScores_
WordScore * wordScoresTail_
WordScore * wordScoresEnd_
std::vector< InitItemRange > * init_
char * mmap_
size_t mmapSize_
Detailed Description
Definition at line 104 of file BackingOffInternal.hh.
Member Function Documentation
void BackingOffLm::Internal::draw (std::ostream & os, const std::string & title) const
Write back-off tree as DOT file for diagnostic purposes.
Definition at line 257 of file BackingOff.cc.
References Core::form(), Bliss::Symbol::str(), and Bliss::Token::symbol().
bool BackingOffLm::Internal::mountImage (int fd, std::string & info, const Bliss::TokenInventory & inventory)
Parameters
info on success the info string from the header is returned in info. On failure a failure message is stored in info
Returns
true if successful
Definition at line 630 of file BackingOff.cc.
References ensure, Core::form(), Bliss::Token::id(), and verify.
bool BackingOffLm::Internal::writeImage (int fd, const std::string & info) const
Returns
true if successful
Definition at line 561 of file BackingOff.cc.
References Core::writeLargeBlock().
The documentation for this class was generated from the following files:
BackingOffInternal.hh
BackingOff.cc