Sprint: Mm::EbwDiscriminativeMixtureEstimator Class Reference
Mm::EbwDiscriminativeMixtureEstimator Class Reference
discriminative mixture estimator: EBW
#include <EbwDiscriminativeMixtureEstimator.hh>
Public Member Functions
EbwDiscriminativeMixtureEstimator (const Core::Configuration &)
virtual void addDensity (Core::Ref< GaussDensityEstimator >)
AbstractMixtureEstimator: base class.
virtual void clear ()
virtual void accumulate (const AbstractMixtureEstimator &toAdd)
virtual void accumulateDenominator (DensityIndex, const FeatureVector &, Weight)
virtual void reset ()
virtual Mixture * estimate (const ReferenceIndexMap< GaussDensityEstimator > &densityMap, bool normalizeWeights=true)
virtual void read (Core::BinaryInputStream &, const std::vector< Core::Ref< GaussDensityEstimator >> &, u32 version)
virtual void write (Core::BinaryOutputStream &, const ReferenceIndexMap< GaussDensityEstimator > &) const
virtual void write (Core::XmlWriter &, const ReferenceIndexMap< GaussDensityEstimator > &) const
virtual bool equalWeights (const AbstractMixtureEstimator &toCompare) const
Weight getDenWeight () const
Public Member Functions inherited from Mm::DiscriminativeMixtureEstimator
DiscriminativeMixtureEstimator (const Core::Configuration &)
DiscriminativeMixtureEstimator.
virtual void removeDensitiesWithLowWeight (Weight minObservationWeight, Weight minRelativeWeight=0)
Removes densities whose absolute mixture weight has less weight than.
const std::vector< Weight > & previousMixtureWeights () const
Weight previousMixtureWeight (DensityIndex dns) const
Weight logPreviousMixtureWeight (DensityIndex dns) const
void setPreviousMixture (const Mixture *)
Public Member Functions inherited from Mm::AbstractMixtureEstimator
void removeDensitiesWithZeroWeight ()
Removes densities whose mean estimator has weight 0.0.
void accumulate (DensityIndex, const FeatureVector &)
void accumulate (DensityIndex, const FeatureVector &, Weight)
Weight getWeight () const
size_t nDensities () const
const DensityEstimators & densityEstimators () const
std::vector< Weight > & weights ()
const std::vector< Weight > & weights () const
void setDensityEstimators (DensityEstimators estimators)
bool checkEventsWithZeroWeight (std::string &message)
virtual void write (Core::XmlWriter &, const ReferenceIndexMap< GaussDensityEstimator > &, std::string label="") const
bool equalTopology (const AbstractMixtureEstimator &toCompare, const ReferenceIndexMap< GaussDensityEstimator > &densityMap, const ReferenceIndexMap< GaussDensityEstimator > &densityMapToCompare) const
void addMixture (const AbstractMixtureEstimator &toAdd)
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Static Public Member Functions
static DensityIndex accumulate (Core::BinaryInputStreams &is, Core::BinaryOutputStream &os)
Static Public Member Functions inherited from Mm::DiscriminativeMixtureEstimator
static DensityIndex accumulate (Core::BinaryInputStreams &is, Core::BinaryOutputStream &os)
Static Public Member Functions inherited from Mm::AbstractMixtureEstimator
static DensityIndex accumulate (Core::BinaryInputStreams &is, Core::BinaryOutputStream &os)
Protected Member Functions
virtual void removeDensity (DensityIndex indexInMixture)
void estimateMixtureWeights (std::vector< Weight > &, bool normalizeWeights=true) const
virtual Weight weight (DensityIndex dns) const
Protected Member Functions inherited from Mm::AbstractMixtureEstimator
DensityIndex densityIndexWithMaxWeight () const
Protected Attributes
std::vector< Weight > denWeights_
u32 nIterations_
Protected Attributes inherited from Mm::DiscriminativeMixtureEstimator
std::vector< Weight > previousMixtureWeights_
Weight minimumObservationWeight_
Protected Attributes inherited from Mm::AbstractMixtureEstimator
DensityEstimators densityEstimators_
std::vector< Weight > weights_
Private Types
typedef DiscriminativeMixtureEstimator Precursor
Static Private Attributes
static const Core::ParameterInt paramNumberOfIterations
EbwDiscriminativeMixtureEstimator: extended Baum Welch (EBW)
Friends
class MixtureSetEstimatorIndexMap
Additional Inherited Members
Public Types inherited from Mm::AbstractMixtureEstimator
typedef std::vector< Core::Ref< GaussDensityEstimator > > DensityEstimators
Detailed Description
discriminative mixture estimator: EBW
Definition at line 27 of file EbwDiscriminativeMixtureEstimator.hh.
Member Function Documentation
void EbwDiscriminativeMixtureEstimator::addDensity (Core::Ref< GaussDensityEstimator > densityEstimator) virtual
AbstractMixtureEstimator: base class.
Reimplemented from Mm::AbstractMixtureEstimator.
Definition at line 93 of file EbwDiscriminativeMixtureEstimator.cc.
References required_cast.
void EbwDiscriminativeMixtureEstimator::estimateMixtureWeights (std::vector< Weight > & weights, bool normalizeWeights = true) const protected
Cambridge University mixture weight update scheme
Definition at line 39 of file EbwDiscriminativeMixtureEstimator.cc.
References Core::Component::log(), Core::Application::us(), and Core::Component::warning().
Member Data Documentation
const Core::ParameterInt EbwDiscriminativeMixtureEstimator::paramNumberOfIterations static private
EbwDiscriminativeMixtureEstimator: extended Baum Welch (EBW)
Definition at line 32 of file EbwDiscriminativeMixtureEstimator.hh.
The documentation for this class was generated from the following files:
EbwDiscriminativeMixtureEstimator.hh
EbwDiscriminativeMixtureEstimator.cc