Sprint: Speech::AcousticModelTrainer Class Reference
Speech::AcousticModelTrainer Class Reference
Base class for acoustic training applications.
#include <AcousticModelTrainer.hh>
Public Member Functions
void signOn (CorpusVisitor &corpusVisitor)
Override this function to sign on to services of the corpus visitor.
AcousticModelTrainer (const Core::Configuration &c, Am::AcousticModel::Mode mode)
Public Member Functions inherited from Speech::AlignedFeatureProcessor
AlignedFeatureProcessor (const Core::Configuration &c)
virtual void enterCorpus (Bliss::Corpus *)
Override this function to perform preparations before first segment is processed.
virtual void leaveCorpus (Bliss::Corpus *)
Override this function to perform post processing after the last segment is processed.
virtual void enterSegment (Bliss::Segment *)
Override this function to perform preparations before first aligned features arrive.
virtual void leaveSegment (Bliss::Segment *)
Override this function to perform post processing after the last aligned features of the segment.
virtual void enterSpeechSegment (Bliss::SpeechSegment *)
Override this function to perform preparations before first aligned features arrive.
virtual void leaveSpeechSegment (Bliss::SpeechSegment *)
Override this function to perform post processing after the last aligned features of the segment.
virtual void processAlignedFeature (Core::Ref< const Feature >, Am::AllophoneStateIndex, Mm::Weight, Mm::Weight)
Override this function to implement the processing of feature vectors with two weights.
virtual void setDataSource (Core::Ref< DataSource >)
Override this function to obtain the data source of corpus processor which produces the labels.
virtual void setFeatureDescription (const Mm::FeatureDescription &)
Override this function to achieve the attributes of the feature streams.
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Protected Member Functions
Bliss::LexiconRef lexicon () const
Core::Ref< Am::AcousticModel > acousticModel () const
virtual void processAlignedFeature (Core::Ref< const Feature > f, Am::AllophoneStateIndex e)
Override this function to implement the processing of Viterbi-aligned feature vectors.
virtual void processAlignedFeature (Core::Ref< const Feature >, Am::AllophoneStateIndex, Mm::Weight)
Override this function to implement the processing of Baum-Welch-aligned feature vectors.
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Private Types
typedef AlignedFeatureProcessor Precursor
Private Attributes
Bliss::LexiconRef lexicon_
Core::Ref< Am::AcousticModel > acousticModel_
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Base class for acoustic training applications.
Extends the AlignedFeatureProcessor by adding an acoustic model and a lexicon
Definition at line 30 of file Speech/AcousticModelTrainer.hh.
Member Function Documentation
virtual void Speech::AcousticModelTrainer::processAlignedFeature (Core::Ref< const Feature > f, Am::AllophoneStateIndex e) inline protected virtual
Override this function to implement the processing of Viterbi-aligned feature vectors.
Reimplemented from Speech::AlignedFeatureProcessor.
Reimplemented in Speech::TiedTextDependentMixtureSetTrainer, Speech::FeatureScorer, Speech::KeyedEstimator, Speech::TextDependentMixtureSetTrainer, Speech::FeatureAccumulator, and Speech::TextDependentScatterMatricesEstimator.
Definition at line 44 of file Speech/AcousticModelTrainer.hh.
virtual void Speech::AcousticModelTrainer::processAlignedFeature (Core::Ref< const Feature > , Am::AllophoneStateIndex , Mm::Weight) inline protected virtual
Override this function to implement the processing of Baum-Welch-aligned feature vectors.
Reimplemented from Speech::AlignedFeatureProcessor.
Reimplemented in Speech::TiedTextDependentMixtureSetTrainer, Speech::KeyedEstimator, Speech::TextDependentMixtureSetTrainer, Speech::FeatureAccumulator, and Speech::TextDependentScatterMatricesEstimator.
Definition at line 47 of file Speech/AcousticModelTrainer.hh.
References Core::Component::criticalError(), and signOn().
void AcousticModelTrainer::signOn (CorpusVisitor & corpusVisitor) virtual
Override this function to sign on to services of the corpus visitor.
Note: call the signOn function of your predecessor.
Reimplemented from Speech::AlignedFeatureProcessor.
Reimplemented in Speech::FeatureScorer, and Speech::KeyedEstimator.
Definition at line 39 of file Speech/AcousticModelTrainer.cc.
Referenced by processAlignedFeature().
The documentation for this class was generated from the following files:
Speech/AcousticModelTrainer.hh
Speech/AcousticModelTrainer.cc