Sprint: Search::SearchAlgorithm::Pruning Class Reference
Search::SearchAlgorithm::Pruning Class Reference abstract
Public Member Functions
virtual Core::Ref< Pruning > clone () const =0
Merge in timeframe-specific pruning specifiers, creating a pruning-map.
virtual bool merge (const Core::Ref< Pruning > &, TimeframeIndex, TimeframeIndex, TimeframeIndex endTime)
virtual bool extend (Score, Score, TimeframeIndex)
Extend the pruning-thresholds by a score offset, a score factor, and by a specific number of timeframes.
virtual std::string format () const
virtual bool checkSearchSpace () const
Should return false if the search space was too tight and must be relaxed.
virtual Score masterBeam () const =0
Currently configured master beam size (relative to LM scale, eg. typically around 13)
virtual Score maxMasterBeam () const =0
Maximum recorded size of the master beam.
Public Member Functions inherited from Core::ReferenceCounted
ReferenceCounted (const ReferenceCounted &)
ReferenceCounted & operator= (const ReferenceCounted &)
u32 refCount () const
void acquireReference () const
bool releaseReference () const
void acquireWeakReference (WeakRefBase *) const
void releaseWeakReference (WeakRefBase *) const
void free () const
Detailed Description
Definition at line 131 of file Search/Search.hh.
Member Function Documentation
virtual bool Search::SearchAlgorithm::Pruning::checkSearchSpace () const inline virtual
Should return false if the search space was too tight and must be relaxed.
Reimplemented in Search::SearchSpace::PruningDesc.
Definition at line 149 of file Search/Search.hh.
References Search::SearchAlgorithm::describePruning(), Search::SearchAlgorithm::relaxPruning(), and Search::SearchAlgorithm::resetPruning().
virtual Core::Ref<Pruning> Search::SearchAlgorithm::Pruning::clone () const pure virtual
Merge in timeframe-specific pruning specifiers, creating a pruning-map.
Returns false if the operation is not supported.
Implemented in Search::SearchSpace::PruningDesc.
virtual bool Search::SearchAlgorithm::Pruning::extend (Score , Score , TimeframeIndex) inline virtual
Extend the pruning-thresholds by a score offset, a score factor, and by a specific number of timeframes.
Reimplemented in Search::SearchSpace::PruningDesc.
Definition at line 142 of file Search/Search.hh.
virtual Score Search::SearchAlgorithm::Pruning::masterBeam () const pure virtual
Currently configured master beam size (relative to LM scale, eg. typically around 13)
Implemented in Search::SearchSpace::PruningDesc.
virtual Score Search::SearchAlgorithm::Pruning::maxMasterBeam () const pure virtual
Maximum recorded size of the master beam.
Implemented in Search::SearchSpace::PruningDesc.
The documentation for this class was generated from the following file:
Search/Search.hh