Sprint: Search::Wfst::Builder::SleeveOperation Class Reference
Search::Wfst::Builder::SleeveOperation Class Reference
base class for operations with 1 input and 1 output automaton
#include <Builder.hh>
Public Member Functions
SleeveOperation (const Core::Configuration &c, Resources &r)
virtual u32 nInputAutomata () const
number of automata required as input
virtual bool addInput (AutomatonRef f)
add input automaton (will be called nInputAutomata() times)
void deleteInput ()
Public Member Functions inherited from Search::Wfst::Builder::Operation
Operation (const Core::Configuration &c, Resources &r)
virtual bool consumeInput () const
should input automata be removed
virtual bool hasOutput () const
operation is expected to produce an output automaton.
AutomatonRef getResult ()
do the actual processing and create an output automaton
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Protected Member Functions
virtual bool precondition () const
precondition for getResult()
Protected Member Functions inherited from Search::Wfst::Builder::Operation
virtual AutomatonRef process ()=0
do the actual processing
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Attributes
AutomatonRef input_
Protected Attributes inherited from Search::Wfst::Builder::Operation
Resources & resources_
Core::XmlChannel timerChannel_
Core::Timer timer_
Protected Attributes inherited from Core::Configurable
Configuration config
Additional Inherited Members
Public Types inherited from Search::Wfst::Builder::Operation
typedef Automaton * AutomatonRef
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Detailed Description
base class for operations with 1 input and 1 output automaton
Definition at line 144 of file Builder.hh.
Member Function Documentation
virtual bool Search::Wfst::Builder::SleeveOperation::addInput (AutomatonRef) inline virtual
add input automaton (will be called nInputAutomata() times)
Reimplemented from Search::Wfst::Builder::Operation.
Reimplemented in Search::Wfst::Builder::CreateLookahead, Search::Wfst::Builder::RemovePhoneDisambiguators, and Search::Wfst::Builder::Compose.
Definition at line 151 of file Builder.hh.
Referenced by Search::Wfst::Builder::Compose::addInput(), Search::Wfst::Builder::RemovePhoneDisambiguators::addInput(), Search::Wfst::Builder::CreateLookahead::addInput(), Search::Wfst::Builder::CreateLookahead::hasOutput(), and Search::Wfst::Builder::Compose::nInputAutomata().
virtual u32 Search::Wfst::Builder::SleeveOperation::nInputAutomata () const inline virtual
number of automata required as input
Reimplemented from Search::Wfst::Builder::Operation.
Reimplemented in Search::Wfst::Builder::CreateLookahead, Search::Wfst::Builder::AddNonWordTokens, Search::Wfst::Builder::RemovePhoneDisambiguators, and Search::Wfst::Builder::Compose.
Definition at line 148 of file Builder.hh.
Referenced by Search::Wfst::Builder::CreateLookahead::hasOutput(), Search::Wfst::Builder::RemovePhoneDisambiguators::nInputAutomata(), and Search::Wfst::Builder::AddNonWordTokens::nInputAutomata().
virtual bool Search::Wfst::Builder::SleeveOperation::precondition () const inline protected virtual
precondition for getResult()
Reimplemented from Search::Wfst::Builder::Operation.
Reimplemented in Search::Wfst::Builder::CreateStateSequences, Search::Wfst::Builder::Compose, and Search::Wfst::Builder::WriteOperation.
Definition at line 163 of file Builder.hh.
Referenced by Search::Wfst::Builder::Compose::nInputAutomata(), Search::Wfst::Builder::WriteOperation::precondition(), Search::Wfst::Builder::Compose::precondition(), and Search::Wfst::Builder::CreateStateSequences::precondition().
The documentation for this class was generated from the following file:
Builder.hh