Sprint: Core::Archive Class Reference
Core::Archive Class Reference abstract
Abstract base class for archives.
#include <Archive.hh>
Classes
class _const_iterator
class const_iterator
class Sizes
Public Types
enum Type { TypeUnknown, TypeDirectory, TypeFile, TypeBundle }
Different types of archives handled by this class.
typedef u32 AccessMode
Different access types to archives.
typedef u32 Size
Public Member Functions
const std::string & path () const
bool hasAccess (AccessMode a) const
virtual const_iterator files () const =0
bool hasFile (const std::string &name) const
bool readFile (const std::string &name, std::string &buffer)
bool writeFile (const std::string &name, const std::string &ufferb, bool compress=true)
bool removeFile (const std::string &name)
bool copyFile (const Archive &src, const std::string &name, const std::string &prefix=std::string())
virtual bool clear ()=0
Resets the complete archive.
virtual bool recover ()=0
Recover broken archive.
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Member Functions
static Type test (const std::string &path)
Returns the archive type of a given filesystem object.
static Archive * create (const Configuration &config, const std::string &path="", AccessMode access=AccessModeReadWrite)
Creates and returns an archive.
Static Public Attributes
static const AccessMode AccessModeNone = 0
static const AccessMode AccessModeRead = 1
static const AccessMode AccessModeWrite = 2
static const AccessMode AccessModeReadWrite = 3
Protected Member Functions
bool setAccess (AccessMode access)
void lock () const
void release () const
virtual bool discover (const std::string &name, Sizes &sizes) const
virtual bool read (const std::string &name, std::string &buffer) const =0
virtual bool write (const std::string &name, const std::string &buffer, const Sizes &sizes)=0
virtual bool remove (const std::string &name)=0
Archive (const Configuration &config, const std::string &path="", AccessMode access=AccessModeReadWrite)
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Private Attributes
std::string path_
AccessMode access_
Mutex mutex_
Friends
class BundleArchive
std::ostream & operator<< (std::ostream &s, const Archive &a)
Additional Inherited Members
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Abstract base class for archives.
Used for abstract access to archives.
Definition at line 35 of file Core/Archive.hh.
Member Typedef Documentation
typedef u32 Core::Archive::AccessMode
Different access types to archives.
Definition at line 48 of file Core/Archive.hh.
Member Enumeration Documentation
enum Core::Archive::Type
Different types of archives handled by this class.
Definition at line 40 of file Core/Archive.hh.
Member Function Documentation
virtual bool Core::Archive::clear () pure virtual
Resets the complete archive.
Implemented in Core::FileArchive, Core::BundleArchive, and Core::DirectoryArchive.
Archive * Archive::create (const Configuration & config, const std::string & path = "", AccessMode access = AccessModeReadWrite) static
Creates and returns an archive.
An existing archive is auto-detected by test(). For non-existing archives the type is determined by the path name itself. A trailing path separator switches between directory or file archives.
Parameters
path destination path to the archive
Returns
zero on failure, a valid archive otherwise
Definition at line 296 of file Core/Archive.cc.
References defect, and Core::Component::hasFatalErrors().
Referenced by Speech::AlignmentDumpNode::configure(), Flf::ConfusionNetworkArchive::ConfusionNetworkArchive(), ArchiverApplication::getUsage(), Speech::PhonemeSequenceAlignmentGenerator::Cache::initializeArchive(), ArchiverApplication::main(), Flf::PosteriorCnArchive::PosteriorCnArchive(), Nn::MeanAndVarianceTrainer< T >::processBatch_feedInput(), Nn::PythonTrainer< T >::processBatch_finish(), Flf::LatticeArchiveWriterNode::sendLattice(), and Speech::SegmentwiseAlignmentGenerator::setSegmentwiseFeatureExtractor().
virtual bool Core::Archive::recover () pure virtual
Recover broken archive.
Implemented in Core::FileArchive, Core::BundleArchive, and Core::DirectoryArchive.
Referenced by ArchiverApplication::main().
Archive::Type Archive::test (const std::string & path) static
Returns the archive type of a given filesystem object.
Parameters
path valid path pointing to a filesystem object
Definition at line 284 of file Core/Archive.cc.
The documentation for this class was generated from the following files:
Core/Archive.hh
Core/Archive.cc