Sprint: Audio::SourceNode Class Reference
Audio::SourceNode Class Reference abstract
Abstract Flow node for audio input.
#include <Node.hh>
Public Member Functions
bool setStartTime (Flow::Time)
bool setEndTime (Flow::Time)
SourceNode (const Core::Configuration &c)
virtual bool setParameter (const std::string &name, const std::string &value)
Set node specific parameter.
virtual Flow::PortId getOutput (const std::string &name)
Ask for an output port.
virtual bool configure ()
Post sample format to output port.
virtual bool work (Flow::PortId out)
Processes some data.
Public Member Functions inherited from Audio::Node
virtual void setSampleRate (Flow::Time _sampleRate)
virtual void setSampleSize (u8 _sampleSize)
virtual void setTrackCount (u8 _trackCount)
virtual bool isFileOpen () const
bool openFile ()
void closeFile ()
virtual void setFilename (const std::string &_filename)
Node (const Core::Configuration &c)
Public Member Functions inherited from Flow::Node
Node (const Core::Configuration &c)
virtual PortId getInput (const std::string &name)
Ask for an input port.
Public Member Functions inherited from Flow::AbstractNode
AbstractNode (const Core::Configuration &c)
virtual void Run ()
void setThreaded (bool threaded=true)
void setThreaded (const std::string &threaded)
bool isThreaded () const
virtual bool addParameter (const std::string &name, const Core::StringExpression &value)
addParameter adds a parameter to the node Constant parameters are simply delegated to setParameter, parameters dependent on network parameters are stored in parameters_.
virtual ssize_t getRemainingDataLen (PortId out)
Returns the amount of remaining data items.
void addUnresolvedParameter (const std::string &key, const std::string &value)
Functions for saving and getting unresolved parameters.
const UnresolvedAttributes & unresolvedAttributes () const
bool operator< (const AbstractNode &n) const
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Attributes
static const Core::ParameterInt paramBlockSize
static const Core::ParameterFloat paramStartTime
static const Core::ParameterFloat paramEndTime
Static Public Attributes inherited from Audio::Node
static const SampleCount invalidSampleCount
static const Core::ParameterString paramFilename
Static Public Attributes inherited from Flow::AbstractNode
static const Core::ParameterBool paramThreaded
static const Core::ParameterBool paramIgnoreUnknownParameters
Protected Member Functions
void setTotalSampleCount (SampleCount)
Set total number of sample in audio file.
virtual bool openFile_ ()=0
Open audio file and read sample format.
virtual bool seek (SampleCount newSamplePos)
Set file position.
virtual u32 read (u32 nSamples, Flow::Timestamp *&d)=0
Read at most nSamples samples from file.
SampleCount getStartSample () const
SampleCount getEndSample () const
void setBlockSize (u32 blockSize)
u32 blockSize () const
Protected Member Functions inherited from Audio::Node
virtual void closeFile_ ()=0
Protected Member Functions inherited from Flow::Node
virtual PortId connectInputPort (PortId, Link *)
Connect link to input port.
virtual void disconnectInputLink (Link *)
virtual PortId connectOutputPort (PortId, Link *)
virtual void disconnectOutputLink (Link *)
PortId addInput (PortId in=IllegalPortId)
Create an input port.
PortId addInputs (u32 nPorts)
Create several input ports.
virtual PortId nInputs () const
Link * getInputLink (PortId in) const
virtual PortId inputConnected (PortId in) const
bool validInputPort (PortId in) const
PortId addOutput (PortId out=IllegalPortId)
Add an output port.
PortId addOutputs (u32 nPorts)
Create several output ports.
virtual PortId nOutputs () const
bool validOutputPort (PortId out) const
virtual u32 nOutputLinks (PortId out) const
Number of link connceted to an output port.
bool configureDatatype (Core::Ref< const Attributes > a, const Datatype *d)
template<class T >
bool getData (PortId in, DataPtr< T > &d)
Fetch data packet from input port.
virtual bool putData (PortId out, Data *d)
Send data packet on output port.
bool putEos (PortId out)
Send end-of-stream on output port.
bool putOod (PortId out)
Send out-of-data on output port.
Core::Ref< const Attributes > getInputAttributes (PortId in)
Retrieve attribute set from input port.
void getInputAttributes (PortId, Attributes &)
bool putOutputAttributes (PortId out, Core::Ref< const Attributes > a)
Put attribute set on output port.
void eraseOutputAttributes ()
Erases attributes of all output links recursively.
Protected Member Functions inherited from Flow::AbstractNode
template<class T >
bool getData (Link *l, DataPtr< T > &d)
Fetch data packet from the "from" port of link.
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Private Types
typedef Node Predecessor
Private Attributes
Flow::Time startTime_
Flow::Time endTime_
u32 blockSize_
SampleCount totalSampleCount_
Additional Inherited Members
Public Types inherited from Audio::Node
typedef u32 SampleCount
Public Types inherited from Flow::AbstractNode
typedef std::map< std::string, std::string > UnresolvedAttributes
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Attributes inherited from Audio::Node
std::string filename_
Flow::Time sampleRate_
u8 sampleSize_
u8 trackCount_
SampleCount sampleCount_
Protected Attributes inherited from Core::Configurable
Configuration config
Detailed Description
Abstract Flow node for audio input.
Definition at line 85 of file Audio/Node.hh.
Member Function Documentation
bool SourceNode::configure () virtual
Post sample format to output port.
If necessary open file.
Reimplemented from Flow::Node.
Definition at line 84 of file Audio/Node.cc.
References Core::Component::error(), and verify.
SourceNode::SampleCount SourceNode::getEndSample () const protected
Returns
is sample position of endTime_.
Definition at line 152 of file Audio/Node.cc.
virtual Flow::PortId Audio::SourceNode::getOutput (const std::string &) inline virtual
Ask for an output port.
Implement this function to provide a mapping form names to port IDs. Consider using a Core::Choice. Remeber to create ports using addOutput().
Returns
a valid port ID or IllegalPortId if there is to such port.
Reimplemented from Flow::Node.
Definition at line 147 of file Audio/Node.hh.
References Flow::Node::configure(), and Flow::Node::work().
SourceNode::SampleCount SourceNode::getStartSample () const protected
Returns
is sample position of startTime_.
Definition at line 143 of file Audio/Node.cc.
virtual bool Audio::SourceNode::openFile_ () protected pure virtual
Open audio file and read sample format.
Implement this in concrete input nodes.
Returns
true on success. On failure call error() and return false.
Implements Audio::Node.
Implemented in Audio::FfmpegInputNode, Audio::RawFileInputNode, Audio::FlacInputNode, and Audio::WavInputNode.
virtual u32 Audio::SourceNode::read (u32 nSamples, Flow::Timestamp *& d) protected pure virtual
Read at most nSamples samples from file.
Implement this in concrete input nodes.
Parameters
nSamples number of samples to read
d store pointer of new data packet here. If EOF or an error occurs d must be set to zero.
Returns
number of samples read, may be less than nSamples. On failure call error() and return 0. Note: One samples always means one sample per track!
Implemented in Audio::OpenSoundSystemInputNode, Audio::RawFileInputNode, Audio::FfmpegInputNode, Audio::FlacInputNode, and Audio::WavInputNode.
bool SourceNode::seek (SampleCount newSamplePos) protected virtual
Set file position.
Implement this in concrete file input nodes, iff seeking is possible. Default implementation disallows seeking.
Parameters
newSamplePos number of next sample to be read, counted from beginning of stream
Returns
true on success. On failure call error() and return false.
Reimplemented in Audio::FfmpegInputNode, Audio::RawFileInputNode, Audio::FlacInputNode, and Audio::WavInputNode.
Definition at line 124 of file Audio/Node.cc.
References Core::Component::error(), and verify.
bool SourceNode::setParameter (const std::string & name, const std::string & value) virtual
Set node specific parameter.
Implement this template function to handle parameters specific to your Node.
Parameters
name name of parameter
value new value for the parameter
Returns
true if successful, false if parameter name is not understood.
Reimplemented from Audio::Node.
Reimplemented in Audio::RawFileInputNode, Audio::FfmpegInputNode, and Audio::RawSourceNode.
Definition at line 69 of file Audio/Node.cc.
Referenced by Audio::FfmpegInputNode::setParameter().
void SourceNode::setTotalSampleCount (SampleCount c) protected
Set total number of sample in audio file.
Call this function from openFile(), if you know the total length of the audio file. Note: One samples always means one sample per track!
Definition at line 120 of file Audio/Node.cc.
bool SourceNode::work (Flow::PortId out) virtual
Processes some data.
Implement this function to do whatever your node is supposed to. You are required to produce at least one packet of data on the specified output out. You may send more packets, also to other outputs.
Returns
true on success, false on end-of-file or error. The idiom is:
return putData(out, d);
Implements Flow::Node.
Definition at line 159 of file Audio/Node.cc.
References ensure, and Core::isAlmostEqual().
The documentation for this class was generated from the following files:
Audio/Node.hh
Audio/Node.cc