Sprint: Math::FastFourierTransform Class Reference
Math::FastFourierTransform Class Reference
Fast Fourier Transformation.
#include <FastFourierTransform.hh>
Public Member Functions
FastFourierTransform ()
Initialize DFFT for arrays of size size.
void transform (std::vector< f32 > &v, bool inverse=false)
Apply discrete Fourier transform to complex values in v.
void transformReal (std::vector< float > &v, bool inverse=false)
Apply discrete Fourier transform to real values in v.
Protected Member Functions
void setSize (u32 size)
void bitReversalReordering (std::vector< f32 > &v)
Reorder values in the array &v by bit reversal.
void createBitReversalReordering (u32 length)
create the mapping for bit reversal reording
Protected Attributes
std::vector< size_t > reording_
u32 size_
Static Private Attributes
static const f64 Pi = 3.141592653589793238
static const f64 DPi = 6.28318530717959
Detailed Description
Fast Fourier Transformation.
Based on the implementation in "Numerical Recipes in C"
Todo:
Optimization, e.g. use of SSE instructions
Definition at line 27 of file Math/FastFourierTransform.hh.
Constructor & Destructor Documentation
FastFourierTransform::FastFourierTransform ()
Initialize DFFT for arrays of size size.
Parameters
size size of arrays to transform, has to be 2^n
Definition at line 25 of file Math/FastFourierTransform.cc.
Member Function Documentation
void FastFourierTransform::bitReversalReordering (std::vector< f32 > & v) protected
Reorder values in the array &v by bit reversal.
Parameters
v vector of complex values
Definition at line 49 of file Math/FastFourierTransform.cc.
References createBitReversalReordering(), and verify.
Referenced by transform().
void FastFourierTransform::createBitReversalReordering (u32 length) protected
create the mapping for bit reversal reording
Parameters
length number of complex values (array size / 2)
Definition at line 28 of file Math/FastFourierTransform.cc.
Referenced by bitReversalReordering().
void FastFourierTransform::transform (std::vector< f32 > & v, bool inverse = false)
Apply discrete Fourier transform to complex values in v.
Transformation is done in place.
Parameters
v vector of complex values, has to be of size 2^n
inverse apply inverse discrete fourier transform
Definition at line 59 of file Math/FastFourierTransform.cc.
References bitReversalReordering().
Referenced by Signal::FastFourierTransform::estimateContinuous(), and transformReal().
void FastFourierTransform::transformReal (std::vector< float > & v, bool inverse = false)
Apply discrete Fourier transform to real values in v.
Transformation is done in place.
Parameters
v values, vector has to be of size 2^n
inverse apply inverse discrete fourier transform
Definition at line 95 of file Math/FastFourierTransform.cc.
References transform().
The documentation for this class was generated from the following files:
Math/FastFourierTransform.hh
Math/FastFourierTransform.cc