Sprint: Search::Wfst::Builder::CreateLookahead Class Reference
Search::Wfst::Builder::CreateLookahead Class Reference
converts the input automaton to an FstLib::StdOLabelLookAheadFst and writes it do disk.
#include <FstOperations.hh>
Public Member Functions
CreateLookahead (const Core::Configuration &c, Resources &r)
virtual bool consumeInput () const
should input automata be removed
virtual bool hasOutput () const
operation is expected to produce an output automaton.
virtual u32 nInputAutomata () const
number of automata required as input
virtual bool addInput (AutomatonRef)
add input automaton (will be called nInputAutomata() times)
Public Member Functions inherited from Search::Wfst::Builder::WriteOperation
WriteOperation (const Core::Configuration &c, Resources &r)
Public Member Functions inherited from Search::Wfst::Builder::SleeveOperation
SleeveOperation (const Core::Configuration &c, Resources &r)
void deleteInput ()
Public Member Functions inherited from Search::Wfst::Builder::Operation
Operation (const Core::Configuration &c, Resources &r)
AutomatonRef getResult ()
do the actual processing and create an output automaton
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Static Public Member Functions
static std::string name ()
Protected Member Functions
virtual AutomatonRef process ()
do the actual processing
Protected Member Functions inherited from Search::Wfst::Builder::WriteOperation
virtual bool precondition () const
precondition for getResult()
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Member Functions inherited from Search::Wfst::Builder::FileOperation
std::string filename () const
FileOperation (const Core::Configuration &c, Resources &r)
Protected Attributes
AutomatonRef toRelabel_
Protected Attributes inherited from Search::Wfst::Builder::SleeveOperation
AutomatonRef input_
Protected Attributes inherited from Search::Wfst::Builder::Operation
Resources & resources_
Core::XmlChannel timerChannel_
Core::Timer timer_
Protected Attributes inherited from Core::Configurable
Configuration config
Static Protected Attributes
static const Core::ParameterString paramRelabelFile
static const Core::ParameterBool paramRelabelInput
static const Core::ParameterBool paramSwap
static const Core::ParameterBool paramKeepRelabelingData
Static Protected Attributes inherited from Search::Wfst::Builder::FileOperation
static const Core::ParameterString paramFilename
static const Core::Choice choiceType
static const Core::ParameterChoice paramType
Private Member Functions
template<class F >
void relabel (const F &f)
Additional Inherited Members
Public Types inherited from Search::Wfst::Builder::Operation
typedef Automaton * AutomatonRef
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Types inherited from Search::Wfst::Builder::FileOperation
enum FileType { TypeVector, TypeConst, TypeCompact, TypeNGram }
Detailed Description
converts the input automaton to an FstLib::StdOLabelLookAheadFst and writes it do disk.
optionally writes the relabeling (paramRelabelFile). optionally relabels the second input automaton.
Definition at line 359 of file FstOperations.hh.
Member Function Documentation
bool CreateLookahead::addInput (AutomatonRef) virtual
add input automaton (will be called nInputAutomata() times)
Reimplemented from Search::Wfst::Builder::SleeveOperation.
Definition at line 380 of file FstOperations.cc.
References Search::Wfst::Builder::SleeveOperation::addInput(), and Core::Component::log().
virtual bool Search::Wfst::Builder::CreateLookahead::consumeInput () const inline virtual
should input automata be removed
Reimplemented from Search::Wfst::Builder::Operation.
Definition at line 369 of file FstOperations.hh.
virtual bool Search::Wfst::Builder::CreateLookahead::hasOutput () const inline virtual
operation is expected to produce an output automaton.
i.e. getResult() != 0
Reimplemented from Search::Wfst::Builder::Operation.
Definition at line 372 of file FstOperations.hh.
References Search::Wfst::Builder::SleeveOperation::addInput(), Search::Wfst::Builder::SleeveOperation::nInputAutomata(), and Search::Wfst::Builder::Minimize::process().
u32 CreateLookahead::nInputAutomata () const virtual
number of automata required as input
Reimplemented from Search::Wfst::Builder::SleeveOperation.
Definition at line 376 of file FstOperations.cc.
Operation::AutomatonRef CreateLookahead::process () protected virtual
do the actual processing
Implements Search::Wfst::Builder::Operation.
Definition at line 395 of file FstOperations.cc.
References Core::Component::log(), and verify.
The documentation for this class was generated from the following files:
FstOperations.hh
FstOperations.cc