Sprint: Speech::TextIndependentMixtureSetTrainer Class Reference
Speech::TextIndependentMixtureSetTrainer Class Reference
LabelingFeatureExtractor.
#include <TextIndependentMixtureSetTrainer.hh>
Public Member Functions
TextIndependentMixtureSetTrainer (const Core::Configuration &c)
Public Member Functions inherited from Speech::LabeledFeatureProcessor
LabeledFeatureProcessor (const Core::Configuration &c)
virtual void signOn (CorpusVisitor &corpusVisitor)
Override this function to sign on to services of the corpus visitor.
virtual void enterSegment (Bliss::Segment *)
Override this function to perform preparations before first aligned features arrive.
virtual void leaveSegment (Bliss::Segment *)
Override this function to perform post processing after the last aligned features of the segment.
virtual void enterSpeechSegment (Bliss::SpeechSegment *)
Override this function to perform preparations before first aligned features arrive.
virtual void leaveSpeechSegment (Bliss::SpeechSegment *)
Override this function to perform post processing after the last aligned features of the segment.
virtual void setDataSource (Core::Ref< DataSource >)
Override this function to obtain the data source of corpus processor which produces the labels.
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Public Member Functions inherited from Speech::MlMixtureSetTrainer
MlMixtureSetTrainer (const Core::Configuration &)
Maximum likelihood mixture set trainer.
Public Member Functions inherited from Speech::MixtureSetTrainer
MixtureSetTrainer (const Core::Configuration &)
void initializeAccumulation (size_t nMixtures, size_t dimension, Core::Ref< const Mm::AssigningFeatureScorer > assigningFeatureScorer=Core::Ref< Mm::AssigningFeatureScorer >(), Core::Ref< Mm::MixtureSet > mixtureSet=Core::Ref< Mm::MixtureSet >())
void accumulate (Core::Ref< const Feature::Vector > f, Mm::MixtureIndex m)
void accumulate (Core::Ref< const Feature::Vector > f, Mm::MixtureIndex m, Mm::Weight w)
virtual void read ()
bool combine (const std::vector< std::string > &toCombine)
bool combinePartitions (const std::vector< std::string > &toCombine)
void write () const
void write (Core::XmlWriter &o, std::map< int, std::string > &mixtureLabels) const
size_t dimension () const
size_t nMixtures () const
bool map (const std::string &mappingFilename)
void setWeightThreshold (Mm::Weight weightThreshold)
void setAssigningFeatureScorer (Core::Ref< const Mm::AssigningFeatureScorer > assigningFeatureScorer)
Protected Member Functions
virtual void setFeatureDescription (const Mm::FeatureDescription &description)
Override this function to achieve the attributes of the feature streams.
virtual void setLabels (const std::vector< std::string > &labels)
Override this function to achieve the labels.
virtual void processLabeledFeature (Core::Ref< const Feature > feature, LabelIndex labelIndex)
Override this function to implement the processing of aligned feature vectors.
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Protected Member Functions inherited from Speech::MlMixtureSetTrainer
virtual Mm::MixtureSetEstimator * createMixtureSetEstimator () const
Protected Member Functions inherited from Speech::MixtureSetTrainer
const Core::Ref< Mm::MixtureSet > estimate () const
void setAssigningFeatureScorer (const Core::Ref< Mm::MixtureSet >, Core::Ref< const Mm::AssigningFeatureScorer > assigningFeatureScorer=Core::Ref< Mm::AssigningFeatureScorer >())
bool firstRun ()
void checkCovarianceTying ()
void clear ()
bool read (const std::string &filename, Mm::AbstractMixtureSetEstimator &)
void read (const std::string &filename)
void write (const std::string &filename) const
virtual const Core::Ref< Mm::MixtureSet > getMixtureSet (size_t nMixtures, size_t dimension)
Private Attributes
LabelIndex nLabels_
Mm::FeatureDescription featureDescription_
bool initialized_
Additional Inherited Members
Public Types inherited from Speech::LabeledFeatureProcessor
typedef u32 LabelIndex
Static Public Attributes inherited from Speech::MixtureSetTrainer
static const Core::ParameterString paramOldMixtureSetFilename
Mixture set trainer: base class.
static const Core::ParameterString paramNewMixtureSetFilename
static const Core::ParameterBool paramSplitFirst
static const Core::ParameterBool paramForceCovarianceTying
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Attributes inherited from Core::Configurable
Configuration config
Protected Attributes inherited from Speech::MixtureSetTrainer
Mm::AbstractMixtureSetEstimator * estimator_
Core::Ref< const Mm::AssigningFeatureScorer > assigningFeatureScorer_
Detailed Description
LabelingFeatureExtractor.
Definition at line 25 of file TextIndependentMixtureSetTrainer.hh.
Member Function Documentation
virtual void Speech::TextIndependentMixtureSetTrainer::processLabeledFeature (Core::Ref< const Feature > , LabelIndex) inline protected virtual
Override this function to implement the processing of aligned feature vectors.
Reimplemented from Speech::LabeledFeatureProcessor.
Definition at line 38 of file TextIndependentMixtureSetTrainer.hh.
References Mm::Feature::mainStream().
void TextIndependentMixtureSetTrainer::setFeatureDescription (const Mm::FeatureDescription &) protected virtual
Override this function to achieve the attributes of the feature streams.
This function is called once before the first feature vector is processed.
Reimplemented from Speech::LabeledFeatureProcessor.
Definition at line 30 of file TextIndependentMixtureSetTrainer.cc.
References Core::Component::criticalError(), Core::Description::Stream::getValue(), and Speech::LabeledFeatureProcessor::setFeatureDescription().
virtual void Speech::TextIndependentMixtureSetTrainer::setLabels (const std::vector< std::string > &) inline protected virtual
Override this function to achieve the labels.
Reimplemented from Speech::LabeledFeatureProcessor.
Definition at line 34 of file TextIndependentMixtureSetTrainer.hh.
The documentation for this class was generated from the following files:
TextIndependentMixtureSetTrainer.hh
TextIndependentMixtureSetTrainer.cc