Sprint: Bliss::SegmentOrderingVisitor Class Reference
Bliss::SegmentOrderingVisitor Class Reference
Changes the order of processed segments according to a given segment id list (full segment names).
#include <SegmentOrdering.hh>
Classes
class CorpusCopy
struct CustomCorpusGuide
class RecordingCopy
Public Member Functions
SegmentOrderingVisitor (const SegmentOrderingVisitor &)
virtual SegmentOrderingVisitor * copy ()
void setVisitor (CorpusVisitor *v)
virtual void setShortNameLookup (bool enabled)
virtual void setAutoShuffle (bool enabled)
void shuffleRandomSeed (u32 seed)
virtual void setSegmentList (const std::string &filename)
void setSortByTimeLength (bool enabled, long chunkSize)
virtual void enterRecording (Recording *r)
Template method called when corpus traversal enters a recording.
virtual void enterCorpus (Corpus *c)
Template method notifying start of a (sub-) corpus.
virtual void leaveCorpus (Corpus *corpus)
Template method notifying end of a (sub-) corpus.
virtual void visitSegment (Segment *s)
Template method for processing segments.
virtual void visitSpeechSegment (SpeechSegment *s)
Template method for processing speech segments.
Public Member Functions inherited from Bliss::CorpusVisitor
virtual void leaveRecording (Recording *)
Template method called when corpus traversal leaves a recording.
Protected Types
typedef Core::StringHashMap< Segment * > SegmentMap
typedef Core::StringHashMap< Speaker * > SpeakerMap
typedef Core::StringHashMap< AcousticCondition * > ConditionMap
typedef std::vector< std::pair< Corpus *, Corpus * > > CorpusMap
Protected Member Functions
Segment * getSegmentByName (const std::string &name)
void prepareSegmentLoop ()
void finishSegmentLoop ()
Protected Attributes
CorpusVisitor * visitor_
std::vector< Recording * > recordings_
std::vector< Corpus * > corpus_
CorpusMap curCorpus_
SpeakerMap speakers_
ConditionMap conditions_
const Segment * curSegment_
const Recording * curRecording_
SegmentMap segments_
std::vector< std::string > segmentList_
bool shortNameLookup_
bool autoShuffle_
std::mt19937 shuffleRandomEngine_
bool sortByTimeLength_
long sortByTimeLengthChunkSize_
bool predefinedOrder_
Private Member Functions
void addSegment (Segment *segment)
template<class T , class C >
const T * updateSegmentData (Segment *segment, const T *entry, C &map)
void updateCondition (Segment *segment)
void updateSpeaker (SpeechSegment *segment)
template<class T >
const std::string _getName (const T *entry)
Detailed Description
Changes the order of processed segments according to a given segment id list (full segment names).
This visitor needs to make a copy of each sub-corpus, recording, and segment object, because they are immediately deleted by the CorpusDescriptionParser
Definition at line 30 of file SegmentOrdering.hh.
Member Function Documentation
void SegmentOrderingVisitor::enterCorpus (Corpus *) virtual
Template method notifying start of a (sub-) corpus.
This is rarely needed.
Reimplemented from Bliss::CorpusVisitor.
Definition at line 200 of file SegmentOrdering.cc.
References Bliss::Segment::end(), require, and Bliss::Segment::start().
void SegmentOrderingVisitor::enterRecording (Recording *) virtual
Template method called when corpus traversal enters a recording.
Implement this to take appropriate actions, e.g. opening the audio file.
Reimplemented from Bliss::CorpusVisitor.
Definition at line 193 of file SegmentOrdering.cc.
void SegmentOrderingVisitor::leaveCorpus (Corpus *) virtual
Template method notifying end of a (sub-) corpus.
This is rarely needed.
Reimplemented from Bliss::CorpusVisitor.
Reimplemented in Bliss::PythonSegmentOrderingVisitor, and Bliss::TheanoSegmentOrderingVisitor.
Definition at line 249 of file SegmentOrdering.cc.
References Bliss::Segment::accept(), Core::Component::error(), and Core::Application::us().
virtual void Bliss::SegmentOrderingVisitor::visitSegment (Segment *) inline virtual
Template method for processing segments.
Implement this to process speech and non-speech segments of a corpus.
Reimplemented from Bliss::SegmentVisitor.
Definition at line 56 of file SegmentOrdering.hh.
References visitSpeechSegment().
void SegmentOrderingVisitor::visitSpeechSegment (SpeechSegment * s) virtual
Template method for processing speech segments.
Implement this to process the speech segments of a corpus. By default the request will be forwarded to visitSegment(), so ignore this if you want to treat speech and non-speech segments alike.
Reimplemented from Bliss::SegmentVisitor.
Definition at line 185 of file SegmentOrdering.cc.
References Bliss::SpeechSegment::speaker().
Referenced by visitSegment().
The documentation for this class was generated from the following files:
SegmentOrdering.hh
SegmentOrdering.cc