Sprint: LatticeProcessor Class Reference
LatticeProcessor Class Reference
Copyright 2020 RWTH Aachen University.
#include <LatticeProcessor.hh>
Classes
struct ActionDescription
Public Types
enum Action {
actionNotGiven, actionRead, actionWrite, actionDumpWordBoundaries,
actionGenerateNumerator, actionMerge, actionUnite, actionNumeratorFromDenominator,
actionRemoveSilencesAndNoises, actionRemoveRedundantSilencesAndNoises, actionExtractNBestList, actionSpokenAndCompeting,
actionPrune, actionTimeConditioned, actionLemmaPronunciationToEvaluationToken, actionEvaluationTokenToLemmaPronunciation,
actionLemmaPronunciationToSyntacticToken, actionCopy, actionCache, actionChangeSemiring,
actionPartial, actionSkipEmpty, actionWordToPhonemeLattice, actionMultiply,
actionLinearCombination, actionExpm, actionExtendBestPath, actionRescore,
actionTimeframeError, actionDeterminization, actionEpsilonRemoval, actionInfo,
actionDensity, actionGer, actionSingleBestLegacy, actionWpConfidence,
actionSearchMinimumBayesRisk, actionSingleBest, actionTraceback, actionEvaluate,
actionCovariance, actionSegmentSingleWord, actionMapOrthToPhonemes, actionMapToNonCoarticulation,
actionCollectLatticeCoverageStatistics, actionAccumulateDiscriminatively, actionCrf
}
Actions:
Public Member Functions
LatticeProcessor ()
Copyright 2020 RWTH Aachen University.
virtual std::string getApplicationDescription () const
virtual std::string getParameterDescription () const
virtual int main (const std::vector< std::string > &arguments)
Do these steps:
Public Member Functions inherited from Core::Application
virtual std::string getVariable () const
Return the name of the environment variable.
std::string getBaseName () const
Return the applications basename.
std::string getPath () const
Return the applications path.
virtual std::string getUsage () const
Overload this method to describe the usage of the application and to give a (short) description of the application.
virtual std::string getDefaultParameterDescription () const
void reportLowLevelError (const std::string &msg="")
Errors messages are collected and later (during closeLogging()) printed to the error channel.
void setDefaultLoadConfigurationFile (bool f)
Configure default behaviour of loading a configuration file.
void setDefaultOutputXmlHeader (bool f)
Configure default behaviour of adding a valid xml header to standard channels.
void setTitle (const std::string &t)
Set the title of the application.
void setCommentCharacters (const std::string &c)
Set the set of possible comment characters for this application.
const std::string & getCommentCharacters (void) const
Return the string of comment characters.
Core::Channel & debugChannel (void)
Returns the debug binary outpput channel.
Core::XmlChannel & debugXmlChannel (void)
Returns the debug XML channel.
MappedArchiveReader getCacheArchiveReader (const std::string &archive_name, const std::string &item)
Returns a pointer to the cache-archive reader for the archive, and the specified item contained by the archive.
MappedArchiveWriter getCacheArchiveWriter (const std::string &archive_name, const std::string &item)
Returns a pointer to the cache-archive writer for the archive, and the specified item contained by the archive.
void exit (int status)
Terminate program execution.
void atexit (std::function< void()> f)
Like std::atexit() but will be execute sooner, at our own uninit, at the end of our main(), or in our exit().
Public Member Functions inherited from Core::Component
XmlWriter & clog () const
Message log (const char *msg,...) const __attribute__((format(printf
Print an information message.
Message Message log () const
Message vLog (const char *msg, va_list) const
Message warning (const char *msg=0,...) const __attribute__((format(printf
Print a warning message.
Message Message vWarning (const char *msg, va_list) const
Message error (const char *msg=0,...) const __attribute__((format(printf
Print an error message.
Message Message vError (const char *msg, va_list) const
Message criticalError (const char *msg=0,...) const __attribute__((format(printf
Print a critical error message.
Message Message vCriticalError (const char *msg, va_list) const
Component (const Configuration &c)
Component (const Component &)
Component & operator= (const Component &)
bool hasFatalErrors () const
Test whether non-ignored errors have occured.
void respondToDelayedErrors () const
Terminate execution iff an error has occured previously.
Public Member Functions inherited from Core::Configurable
Configurable (const Configuration &c)
Configuration & getConfiguration ()
const Configuration & getConfiguration () const
const std::string & name () const
const std::string & fullName () const
Run-time name of the component.
Configuration select (const std::string &selection) const
Private Types
enum CorpusType { bliss }
enum ApplicationType { speech, tagging }
typedef std::string Selection
Private Member Functions
void parseActionsSelections (std::vector< Action > &, std::vector< Selection > &)
Parse the actions and selections statements in the configuration.
void visitCorpus (Core::Ref< Speech::LatticeSetProcessorRoot >)
Walk through the corpus.
void finalize (Core::Ref< Speech::LatticeSetProcessorRoot >)
template<class T >
void registerProcessor (Action action, const char *desc="", const char *options="")
Core::Ref< Speech::LatticeSetProcessor > getProcessor (Action action, const Core::Configuration &config) const
void setupProcessors ()
void setupSharedNeuralNetwork ()
void setSharedNeuralNetwork (Core::Ref< Speech::LatticeSetProcessor > &processor)
void addDescription (Action a, const char *desc, const char *options)
Static Private Member Functions
template<class T >
static Speech::LatticeSetProcessor * createProcessor (const Core::Configuration &c)
static Speech::LatticeSetProcessor * createTrainer (const Core::Configuration &config)
Private Attributes
Core::ComponentFactory< Speech::LatticeSetProcessor, Action > processorFactory_
std::map< Action, ActionDescription > descriptions_
Static Private Attributes
static const Core::Choice choiceAction
static const Core::ParameterStringVector paramActions
static const Core::ParameterStringVector paramSelections
static const Core::Choice choiceCorpusType
static const Core::ParameterChoice paramCorpusType
static Core::Choice choiceApplication
static Core::ParameterChoice paramApplication
Additional Inherited Members
Static Public Member Functions inherited from Core::Application
static Application * us ()
Get the global instance of the application (Singleton)
static int main (int argc, char *argv[])
private
Protected Types inherited from Core::Component
enum ErrorType {
ErrorTypeInfo, ErrorTypeWarning, ErrorTypeError, ErrorTypeCriticalError,
nErrorTypes
}
Protected Member Functions inherited from Core::Application
void logSystemInfo () const
void logVersion () const
void logResources () const
void logResourceUsage () const
void logMemoryUsage () const
MappedArchive * getCacheArchive (const std::string &archive)
void openLogging ()
Opens channels and makes initial logs.
void closeLogging (bool configAvailable=true)
Closes down channels and makes final logs.
int run (const std::vector< std::string > &arguments)
void runAtExitFuncs ()
Protected Member Functions inherited from Core::Component
virtual XmlChannel * vErrorMessage (ErrorType mt, const char *msg, va_list) const
Output a warning/error message on the appropriate channel.
Static Protected Member Functions inherited from Core::Application
static bool setFromEnvironment (const std::string &variable)
static bool setFromFile (const std::string &filename)
static std::vector< std::string > setFromCommandline (const std::vector< std::string > &arguments)
Protected Attributes inherited from Core::Application
Channel::Manager * channelManager_
Core::Channel * debugChannel_
Core::XmlChannel * debugXmlChannel_
std::map< std::string, MappedArchive * > cacheArchives_
bool defaultLoadConfigurationFile_
bool defaultOutputXmlHeader_
std::string comment_
std::string configFileName_
Timer timer_
std::list< std::function< void()> > atExitFuncs_
Protected Attributes inherited from Core::Configurable
Configuration config
Static Protected Attributes inherited from Core::Application
static const ParameterBool paramLogConfiguration
static const ParameterBool paramLogResolvedResources
static const ParameterString paramConfig
static const ParameterString paramCacheArchiveFile
static const ParameterBool paramCacheArchiveReadOnly
static const ParameterBool paramHelp
static std::string path_ = "."
static std::string basename_ = ""
static Application * app_ = 0
Detailed Description
Copyright 2020 RWTH Aachen University.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. corpus driven lattice processor
The lattice processor is an application, creating a lattice processor node chain to parse a corpus lattice by lattice.
Definition at line 51 of file LatticeProcessor.hh.
Member Enumeration Documentation
enum LatticeProcessor::Action
Actions:
Definition at line 57 of file LatticeProcessor.hh.
Constructor & Destructor Documentation
LatticeProcessor::LatticeProcessor ()
Copyright 2020 RWTH Aachen University.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Definition at line 27 of file LatticeProcessor.cc.
References Core::Component::criticalError(), ensure, Core::Ref< T >::get(), Core::Component::log(), Core::Factory< BaseClass, CreationFunction, Identifier >::registerClass(), and Core::Application::setTitle().
Member Function Documentation
int LatticeProcessor::main (const std::vector< std::string > & arguments) virtual
Do these steps:
read the configuration and build a lattice processor node chain from the actions and selections lists
initialize the chain (starting at the root processor) -> caution: to simplify interface 'actionAccumulateDiscriminatively' there is a factory function 'create...'. To understand what your setup is doing you have to parse through the create functions :-(or you have some time and start a table...
call visitCorpus(rootProcessor)
Implements Core::Application.
Definition at line 402 of file LatticeProcessor.cc.
References Core::Component::criticalError(), ensure, Core::Ref< T >::get(), Speech::LatticeSetProcessorRoot::initialize(), parseActionsSelections(), require, Speech::LatticeSetProcessor::setProcessor(), verify, and visitCorpus().
void LatticeProcessor::parseActionsSelections (std::vector< Action > & actions, std::vector< Selection > & selections) private
Parse the actions and selections statements in the configuration.
Definition at line 471 of file LatticeProcessor.cc.
References Core::Component::criticalError(), Core::Component::error(), and require.
Referenced by main().
void LatticeProcessor::visitCorpus (Core::Ref< Speech::LatticeSetProcessorRoot > root) private
Walk through the corpus.
Create a CorpusVisitor class. The corpus visitor is the class coordinating the walk through the corpus.
Call signOn to the root processor node (which will call signOn of the corpus visitor as well).
Create a corpus description class.
Call corpusDescription.accept to start the walk through the corpus
Definition at line 495 of file LatticeProcessor.cc.
References Bliss::CorpusDescription::accept(), defect, require, and Speech::LatticeSetProcessorRoot::signOn().
Referenced by main().
The documentation for this class was generated from the following files:
LatticeProcessor.hh
LatticeProcessor.cc