Sprint: OpenFst Namespace Reference
OpenFst Namespace Reference
Copyright 2020 RWTH Aachen University.
Classes
class CompactReplaceFst
A simple and compact ReplaceFst.
class CompactReplaceFstImpl
Implementation of the CompactReplaceFst.
class CompactReplaceStateTable
State table for the CompactReplaceFst.
struct CompactReplaceStateTuple
State in the CompactReplaceFst consisting of the id of the original fst, the state id in the original fst, and the replaced arc's target state.
struct CompactReplaceStateTupleHash
Hash functor for CompactReplaceStateTuples.
class ConvertFsaDfsState
class EpsilonEncodeMapper
Behaves like EncodeMapper, except for epsilon arcs with trivial weight, which are always mapped to label 0.
class FsaMapperArcIteratorBase
required for ArcIterators of FsaMapperAutomaton objects.
class FsaMapperAutomaton
OpenFst's fst-Interface for classes of the Fsa Toolkit.
class FsaMapperAutomatonImpl
implementation class for FsaMapperAutomaton
class FsaMapperStateIteratorBase
required for StateIterators of FsaMapperAutomaton objects.
class FstMapperAutomaton
class FstMapperAutomaton< Fsa::Semiring, FstArc, WeightConverter >
class FstMapperAutomatonImpl
struct ImplicitWeightConverter
convert weights using casting operators of the involved weight classes
struct ImplicitWeightConverter< FstLib::FloatWeightTpl< T >, WeightTo >
struct ImplicitWeightConverter< FstLib::LogWeightTpl< T >, WeightTo >
struct ImplicitWeightConverter< FstLib::TropicalWeightTpl< T >, WeightTo >
class InDegree
class LabelMap
label to label mapping.
class Module_
class ScaleMapper
Multiply all (float) weights by a scaling factor.
class WeightCompare
Typedefs
typedef Core::SingletonHolder< Module_ > Module
typedef std::pair< Label, Label > LabelPair
typedef std::vector< LabelPair > LabelMapping
typedef fst::StdVectorFst VectorFst
typedef fst::StdArc Arc
typedef fst::StdArc::StateId StateId
typedef fst::StdArc::Weight Weight
typedef fst::StdArc::Label Label
typedef fst::SymbolTable SymbolTable
typedef fst::StateIterator< VectorFst > StateIterator
typedef fst::ArcIterator< VectorFst > ArcIterator
typedef fst::MutableArcIterator< VectorFst > MutableArcIterator
typedef fst::LogArc LogArc
typedef fst::VectorFst< LogArc > LogVectorFst
Functions
template<class A >
void shortestPaths (const FstLib::Fst< A > &fst, typename A::Weight beam, FstLib::VectorFst< A > *lattice)
Arc-synchronous breadth-first beam search.
template<class A >
Fsa::AutomatonCounts count (const FstLib::Fst< A > &f)
template<class A >
u32 maxLabelId (const FstLib::Fst< A > &f, bool inputLabel)
bool readOpenFst (const Fsa::Resources &resources, Fsa::StorageAutomaton *f, std::istream &i)
template<class A >
Core::Ref< Fsa::StaticAutomaton > convertToFsa (const FstLib::Fst< A > &f, Fsa::ConstSemiringRef s=Fsa::TropicalSemiring)
bool writeFsa (Fsa::ConstAutomatonRef f, const std::string &file)
write a Fsa transducer in the OpenFst format.
bool writeOpenFst (const Fsa::Resources &resources, Fsa::ConstAutomatonRef f, std::ostream &o, Fsa::StoredComponents what, bool progress)
VectorFst * convertFromFsa (Fsa::ConstAutomatonRef f)
bool write (const VectorFst &fst, const std::string &filename)
convenience method to write a FstLib::VectorFst<StdArc> object to disk using FstLib::VectorFst<StdArc>::Write
template<class _Automaton , class _FstAutomaton >
_FstAutomaton * convertFromFsa (typename _Automaton::ConstRef f)
convert an arbitrary Fsa Toolkit transducer to a _FstAutomaton object (has to be a subclass of FstLib::Fst).
void Relabel (FstLib::MutableFst< Arc > *fst, const std::map< Label, Label > &ilabels, const std::map< Label, Label > &olabels)
template<class Arc >
void scaleWeights (FstLib::MutableFst< Arc > *fst, f32 scale)
SymbolTable * convertAlphabet (Fsa::ConstAlphabetRef alphabet, const std::string &name, s32 keyOffset=0)
convert a Fsa::Alphabet to a OpenFst::SymbolTable
Fsa::ConstAlphabetRef convertAlphabet (const SymbolTable *symbolTable)
convert an OpenFst::SymbolTable to a Fsa::Alphabet
Label convertLabelFromFsa (Fsa::LabelId l)
convert label id from Fsa to OpenFst.
Fsa::LabelId convertLabelToFsa (Label l)
convert label id from OpenFst to Fsa.
template<class A >
bool isFinalState (const FstLib::Fst< A > &fst, StateId s)
template<class F >
OpenFst::StateId findFinalState (const F &fst, bool *moreThanOne)
template<class A >
void addArcs (FstLib::VectorFst< A > *fst, OpenFst::StateId s, const std::vector< A > &arcs)
Variables
static const Label Epsilon = 0
static const StateId InvalidStateId = FstLib::kNoStateId
static const Label InvalidLabelId = FstLib::kNoLabel
Detailed Description
Copyright 2020 RWTH Aachen University.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. The namespace OpenFst includes all entities required to access and to use functionality of the OpenFst library. The classes and functions of the library itself are defined in the namespace FstLib
Function Documentation
SymbolTable * OpenFst::convertAlphabet (Fsa::ConstAlphabetRef alphabet, const std::string & name, s32 keyOffset)
convert a Fsa::Alphabet to a OpenFst::SymbolTable
Definition at line 19 of file SymbolTable.cc.
References convertLabelFromFsa().
Referenced by convertLabelToFsa(), Search::Wfst::LexiconBuilder::createSymbolTables(), and Search::Wfst::Builder::AddPronunciationWeight::process().
Fsa::ConstAlphabetRef OpenFst::convertAlphabet (const SymbolTable * symbolTable)
convert an OpenFst::SymbolTable to a Fsa::Alphabet
Definition at line 28 of file SymbolTable.cc.
References Fsa::StaticAlphabet::addIndexedSymbol(), and convertLabelToFsa().
template<class _Automaton , class _FstAutomaton > _FstAutomaton* OpenFst::convertFromFsa (typename _Automaton::ConstRef f)
convert an arbitrary Fsa Toolkit transducer to a _FstAutomaton object (has to be a subclass of FstLib::Fst).
delayed transducers are expanded.
Definition at line 119 of file OpenFst/Output.hh.
References write(), and writeFsa().
Label OpenFst::convertLabelFromFsa (Fsa::LabelId l) inline
convert label id from Fsa to OpenFst.
required because Fsa::Epsilon != OpenFst::Epsilon
Definition at line 26 of file SymbolTable.hh.
Referenced by Search::Wfst::LexiconBuilder::build(), Search::Wfst::LexiconBuilder::close(), convertAlphabet(), Search::Wfst::StateSequenceBuilder::createSymbols(), Search::Wfst::ExpandingFsaSearch::getCurrentBestSentence(), Search::Wfst::LexiconBuilder::getPronsWithoutNonWords(), Search::Wfst::Builder::CreateStateSequenceSymbols::process(), Search::Wfst::Builder::AddPronunciationWeight::process(), Search::Wfst::Builder::CheckLabels::process(), Search::Wfst::Builder::CreateSubwordGrammar::process(), Search::Wfst::Builder::Factorize::process(), Search::Wfst::Builder::ExpandStates::process(), and Search::Wfst::StateSequenceBuilder::relabelTransducer().
Fsa::LabelId OpenFst::convertLabelToFsa (Label l) inline
convert label id from OpenFst to Fsa.
required because Fsa::Epsilon != OpenFst::Epsilon
Definition at line 34 of file SymbolTable.hh.
References convertAlphabet().
Referenced by convertAlphabet(), Search::Wfst::StateSequenceBuilder::createSymbols(), Search::Wfst::DynamicLmFstImpl::Final(), TestApplication::getUsage(), Search::Wfst::Builder::Factorize::process(), and Search::Wfst::Builder::ExpandStates::process().
template<class A > void OpenFst::shortestPaths (const FstLib::Fst< A > & fst, typename A::Weight beam, FstLib::VectorFst< A > * lattice)
Arc-synchronous breadth-first beam search.
Todo:
garbage collection in the traceback: remove non-reachable states
Definition at line 39 of file BeamSearch.hh.
References verify.
bool OpenFst::write (const VectorFst & fst, const std::string & filename)
convenience method to write a FstLib::VectorFst<StdArc> object to disk using FstLib::VectorFst<StdArc>::Write
Definition at line 46 of file OpenFst/Output.cc.
Referenced by convertFromFsa().
bool OpenFst::writeFsa (Fsa::ConstAutomatonRef f, const std::string & file)
write a Fsa transducer in the OpenFst format.
transducer will be written as FstLib::VectorFst<StdArc>
Definition at line 20 of file OpenFst/Output.cc.
Referenced by convertFromFsa().