Sprint: Signal Namespace Reference
Signal Namespace Reference
Copyright 2020 RWTH Aachen University.
Classes
class AllPolesPowerSpectrumNode
Calculate the all poles (also called as maximum entropy) power spectrum estimate.
struct alternatingComplexVectorAmplitude
returns the amplitude vector of the input alternating complex vector length of output is set according to the number of input complex numbers
struct alternatingComplexVectorImaginaryPart
returns the imaginary part vector of the input alternating complex vector length of output is set according to the number of input complex numbers
struct alternatingComplexVectorPhase
returns the phase vector of the input alternating complex vector length of output is set according to the number of input complex numbers
struct alternatingComplexVectorRealPart
returns the real part vector of the input alternating complex vector length of output is set according to the number of input complex numbers
struct alternatingComplexVectorToComplexVector
converts alternating complex vector to vector of objects of the class complex<T> length of output is set according to the number of input complex numbers.
class AmplitudeSpectrumEnergyVectorNormalization
AmplitudeSpectrumEnergyVectorNormalization: divides each element by square of frame energy calculated form (half) amplitude spectrum.
class AprioriProbability
Base class for a-priori probability.
class ArxEstimator
class AutocorrelationToAutoregressionNode
Estimates autoregression parameters from autocorrelation.
class AutoregressionToCepstrumNode
Calculate cepstrum coefficients from autoregressive coefficients.
class AutoregressionToSpectrumNode
Calculate spectrum coefficients (CRBE) from autoregressive coefficients.
class AutoregressiveCoefficients
Flow network parameter for autoregressive coefficients.
class BandpassAutocorrelation
Autocorrelation of from segment of amplitude spectrum.
class BartlettWindowFunction
BartlettWindowFunction.
class BayesClassification
Implementation of bayes decision rule for "simple" distributions.
class BayesClassificationNode
BayesClassificationNode.
class BayesClassificationScoreNode
class BICFullCovMonoGaussianModel
class BlackmanWindowFunction
BlackmanWindowFunction.
class ComplexFastFourierTransform
ComplexFastFourierTransform: performs complex fast fourier transform Algorithm taken from "Numerical Recepies in C++" Delivers N complex values real and imaginary part alternating, where N is number of FFT points.
class ComplexInverseFastFourierTransform
ComplexInverseFastFourierTransform: performs complex inverse fast fourier transform Algorithm taken from "Numerical Recepies in C++" Delivers N complex values real and imaginary part alternating, where N is number of FFT points.
class ComplexVectorFunctionNode
ComplexVectorFunctionNode is a node class for different complex unary functions (derived from std::unary_function)
struct complexVectorToAlternatingComplexVector
converts vector of objects of class complex<T> to alternating complex vector length of output is set according to the number size of input.
class ContinuousVectorTransformNode
For each ith element x in vector X performs x = op(x, f(i)).
class Convolution
Convolution: Fast Fourier Transform based implementation of time doimain convolution.
class CorrFullCovMonoGaussianModel
class CosineTransform
Discrete Cosine Transform with an optional warping of the input 'omega' range.
class CosineTransformNode
Cosine Transform Node Performs cosine transform with several options: -arbitrary integrated warping function.
class CovarianceBuilder
class CrossCorrelation
CrossCorrelation Rxy(m) = sum_{t = max(0, -m)}^{min(sizeX_ - m, sizeY_)} similarity(x_{t + m}, y_{t})
class CrossCorrelationNode
CrossCorrelationNode.
class DcDetection
class DcDetectionNode
class DelayNode
Packet delay filter.
class Delimiter
Delimiter class for start stop detection.
class DiagCovMonoGaussianModel
class DivideByMean
Output is divided by arithmetic mean of the sliding window.
class DynamicProgramingSegmentEstimator
class EigenTransform
Base class for eigenvalue analysis based transformations.
class EnergyVectorNormalization
EnergyVectorNormalization: divides each element by square of frame energy.
class FastFourierTransform
FastFourierTransform: base class to perform fast fourier transform.
class FastFourierTransformNode
FastFourierTransformNode.
class FastHartleyTransform
HartleyFourierTransform: performs fourier transform of real vector based on Hartley transform Delivers N / 2 + 1 complex values real and imaginary part alternating, where N is number of FFT points.
class FastMatrixMultiplicationNode
class FilterBank
Filter bank Constrains and parameters: -Each filter is assumed to have the same length.
class FilterBankNode
Filter Bank Node.
class Formant
class FormantExtraction
class FrameInterpolationNode
FrameInterpolationNode: creates one elements for each elements read from "target" stream by interpolation at target start-times.
class FramePredictionNode
FramePredictionNode: creates one elements for each elements read from "target" stream by prediction for target start-times.
class FullCovMonoGaussianModel
class GammaTone
Provides an auditory-based Gammatone filter bank.
class GammaToneNode
Gammatone filter bank node.
class GenericWarpingNode
Warping node with arbitrary warping function Warping function can be any kind supported by Math::AnalyticFunctionFactory.
class HammingWindowFunction
HammingWindowFunction.
class HanningWindowFunction
HanningWindowFunction.
class HarmonicProductNode
HarmonicProductNode.
class HarmonicSumNode
HarmonicSumNode.
class Histogram
Histogram: supports estimation of histograms calculation of probability distribution function (pdf) calculation of cummulative probability distribution function (cdf) calculation of percentiles.
class HistogramNormalization
HistogramNormalization.
class HistogramNormalizationNode
HistogramNormalizationNode.
class HistogramVector
Histogram Vector.
class IndependentSequenceLikelihood
IndependentSequenceLikelihood implements the class dependent density of feature vector sequence: sum_{t} (- log p(x_t | k))
class InstrumentalVariablesBuilder
class KaiserWindowFunction
KaiserWindowFunction.
class KL2FullCovMonoGaussianModel
class LeastSquares
class LeastSquaresBuilder
class LengthDependentSampleNormalization
class LevelNormalization
Maximum of the sliding window gets substracted from the output.
class LikelihoodFunction
Base class for likelihood functions implementing the class dependent density of feature vector sequence: p(x_1^t | k).
class LinearDiscriminantAnalysis
Linear Discriminant Analysis Input: between class and within class scatter matrices.
class LinearFilter
class LinearFilterNode
class LinearFilterParameter
class LinearPredictionCodingNode
class LinearWarpingNode
Two piece linear warping function node.
class LookupTable
LookupTable: array of Values indexed by arbitrary numbers of type Index.
class MatrixMultiplicationNode
Matrix multiplication filter.
class MaximumVectorNormalization
MaximumVectorNormalization: divides each element of frame by maximum element.
class MeanAndVarianceNormalization
Arithmetic average of the sliding window is substracted from the output, followed by division with standard deviation.
class MeanAndVarianceNormalization1D
1D MVN.
class MeanEnergyVectorNormalization
MeanEnergyVectorNormalization: divides each element by square of frame mean energy.
class MeanEstimator
Estimator class for covariance matrix.
class MeanEstimatorNode
class MeanNormalization
Arithmetic average of the sliding window is substracted from the output.
class MeanNormNormalization
Output is divided by the arithmetic mean of the norm of the elements of the sliding window.
class MeanVectorNormalization
MeanVectorNormalization.
class Module_
class MrastaFiltering
Implementation of the MRasta filtering as introduced in "Multi-resolution RASTA filtering for TANDEM-based ASR" by Hynek Hermansky, Petr Fousek in Interspeech 2005.
class MrastaFilteringNode
Apply the MRASTA filtering to critical band energies (CRBE) Input: sequence of concatenated CRBE vectors.
class Normalization
Base class for normalization algorithms.
class NormalizationNode
NormalizationNode.
class normalizeCrossAbsoluteDifferenceUpperBound
normalizeCrossAbsoluteDifferenceUpperBound: normalizes upper bound of cross-absolute-difference to 1 0 <= Dxy(m) / [sum(abs(x(t))) + sum(abs(y(t)))] <= 1
class normalizeCrossCorrelationEstimate
normalizeCrossCorrelationEstimate: normalizes cross-correlation estimate by number of addands Leads to the so called unbiased estimate of the cross-correaltion function
class normalizeCrossCorrelationUpperBound
normalizeCrossCorrelationUpperBound: normalizes upper bound of cross-correlation to 1 |Rxy(m)| / sqrt(Rxx(0)Ryy(0)) <= 1 With other words, the two sequences x, y are normalized such that the zeroth lag of their autocorrelation is 1.
class normalizeCrossSquareDifferenceUpperBound
normalizeCrossSquareDifferenceUpperBound: normalizes upper bound of cross-square-difference to 1.
class NthOrderFeatures
NthOrderFeatures Calculates nth order features.
class NthOrderFeaturesNode
Nth Order Features Node Augments the incoming first order features with zeroth and higher order features.
class PeakDetection
PeakDetection.
class PeakDetectionNode
PeakDetectionNode.
class PolinomialVectorInterpolation
PolinomialVectorInterpolation: creates new vectors at given target start-times by polinomial interpolation.
class Preemphasis
Preemphasis.
class PreemphasisNode
PreemphasisNode.
class PrincipalComponentAnalysis
Principal Component Analysis.
class ProjectionNode
class QrLeastSquares
class QuantileEqualization
class QuantileEqualizationNode
class RandomVectorNode
Generates random vectors Parameters: -type: type of random vector (.
class RealFastFourierTransform
RealFastFourierTransform: performs fourier transform of real vector Algorithm taken from "Numerical Recepies in C++" Input: N real values; Output N / 2 + 1 complex values real and imaginary part alternating; where N is number of FFT points.
class RealInverseFastFourierTransform
RealInverseFastFourierTransform: performs inverse fourier transform of real vector Algorithm taken from "Numerical Recepies in C++" Input: N / 2 + 1 complex values real and imaginary part alternating; Output N real values; where N is number of FFT points.
class RectangularWindowFunction
RectangularWindowFunction.
class Regression
Calculation of derivatives with linear regression coefficients.
class RegressionNode
class RepeatingFramePrediction
RepeatingFramePrediction: predicts input at given target start-times by copying the previous element.
class SampleNormalization
class SampleNormalizationNode
SampleNormalizationNode.
class ScatterDiagonalNormalization
Calculates a transformation which makes the diagonal of the input scatter matrix to be unity.
class ScatterMatricesEstimator
Estimator class for between and within class scatter matrices.
class ScatterMatrixEstimator
Base class for scatter matrix estimators.
class ScatterThresholding
class ScatterTransform
Base class for scatter matrix based tranformations.
class SegmentClustering
Segment Clustering.
class SegmentClusteringNode
class SegmentModelEstimator
class SegmentwiseArEstimator
Autoregression estimator for segments of amplitude spectrum.
class SegmentwiseEstimator
class SegmentwiseFormantExtraction
class SegmentwiseFormantExtractionNode
class SietillDelimiter
Sietill Delimiter (silence proportion may be large)
class SilenceDetection
class SilenceDetectionNode
class SilenceNormalization
This node normalizes the fraction of silence in the outgoing signal.
class SilenceNormalizationNode
class SleeveNode
Signal processing network node.
class SlidingAlgorithmNode
Base class for driving algorithms with buffer of arbitrary length.
class SlidingWindow
SlidingWindow over a sequence of data.
class SpectralIntegration
Performs a reduction of the spectral dimension of a (Gammatone) filterbank output.
class SpectralIntegrationNode
Spectral Integration Node Parameters: shift: shift length length: window length.
class SvdLeastSquares
class TemporalIntegration
Performs a reduction of the temporal dimension of a (Gammatone) filterbank output.
class TemporalIntegrationNode
Temporal Integration Node.
class TemporalPattern
Estimation of temporal pattern (TRAP).
class TemporalPatternNode
Calculate spectrum coefficients (CRBE) from autoregressive coefficients.
class TimeWindowBuffer
TWindowBuffer is buffer collecting vectors of samples and delivering (overlapping) segments of a given length.
class TotalScatterMatrixEstimator
Estimator class for total scatter(covariance) matrix.
class Tracker
class UniformAprioriProbability
Uniform class a-priori probability.
class VarianceVectorNormalization
VarianceVectorNormalization.
class VectorCutLength
VectorCutLength cuts out [first..last] interval of input vector.
class VectorCutNode
class VectorCutRelativeLength
VectorCutRelativeLength cuts out [first..last] interval of input vector.
class VectorCutRelativeSurface
VectorCutRelativeSurface cuts out [first..last] interval of input vector.
class VectorNormalizationNode
VectorNormalizationNode.
class VectorResizeNode
class VectorSequenceAggregation
class VectorSequenceConcatenation
struct vectorToAlternatingComplexVector
converts vector of real parts into alternating complex vector Imaginary parts are set to 0.
class Warping
class WarpingFunction
class WarpingNode
class Window
Window.
class WindowBuffer
WindowBuffer is buffer collecting vectors of samples and delivering (overlapping) segments of a given length.
class WindowFunction
WindowFunction is base class for different windowing functions.
class WindowingFirFilter
class WindowingFirFilterNode
WindowingFirFilterNode.
class WindowingFirFilterParameter
class WindowNode
WindowNode.
Typedefs
typedef Core::SingletonHolder< Module_ > Module
typedef ScatterMatrixEstimator::ScatterMatrix ScatterMatrix
Scatter matrix type;.
Functions
template<class T >
void allPolesPowerSpectrum (float gain, const std::vector< float > &a, size_t totalLength, std::vector< T > &powerSpectrum)
Calculate the all poles (also called as maximum entropy) power spectrum estimate.
void autoregressionToCepstrum (f32 gain, const std::vector< f32 > &a, std::vector< f32 > &c)
Calculate cepstrum coefficients from autoregressive coefficients.
template<class T >
void convolution (const std::vector< T > &x, const std::vector< T > &h, std::vector< T > &y)
convolution y_t = sum_{tau} (x_tau * h_{t - tau})
void hartleyToFourier (const std::vector< f32 > &hartley, std::vector< f32 > &fourier)
hartleyToFourier: converts Hartley coefficients to Fourier coefficients
void hartleyToFourierAmplitude (const std::vector< f32 > &hartley, std::vector< f32 > &amplitude)
hartleyToFourierAmplitude: converts Hartley coefficients to amplitude of Fourier coefficients
void hartleyToFourierPhase (const std::vector< f32 > &hartley, std::vector< f32 > &phase)
hartleyToFourierPhase: converts Hartley coefficients to phase of Fourier coefficients
void fourierToHartley (const std::vector< f32 > &fourier, std::vector< f32 > &hartley)
fourierToHartley: converts Fourier coefficients to Hartley coefficients
template<class Type >
void harmonicSum (const std::vector< Type > &x, std::vector< Type > &s, u32 H)
harmonicSum s(n) = sum_{h = 1}^{h = H} (x_{(h * n) mod T) where
template<class Type >
void harmonicProduct (const std::vector< Type > &x, std::vector< Type > &s, u32 H)
harmonicProduct s(n) = prod_{h = 1}^{h = H} (x_{(h * n) mod T) where
template<class Value , class Index >
LookupTable< Value, Index > operator* (const Value scalar, const LookupTable< Value, Index > &lt)
template<class Value , class Index >
Core::XmlWriter & operator<< (Core::XmlWriter &o, const LookupTable< Value, Index > &lt)
template<class Value , class Index >
Core::BinaryOutputStream & operator<< (Core::BinaryOutputStream &o, const LookupTable< Value, Index > &lt)
template<class Value , class Index >
Core::BinaryInputStream & operator>> (Core::BinaryInputStream &i, LookupTable< Value, Index > &lt)
double frequency2MelFrequency (double f)
double melFrequency2Frequency (double m)
double sinc (double x)
Variables
const Core::ParameterInt paramFftLength
const Core::ParameterFloat paramFftMaximumInputSize
static double halsec [20]
static double costab [20]
static double sintab [20]
Core::ParameterInt paramFrameInterpolationOrder ("order","order of interpolation function", 1, 0)
Core::ParameterBool paramPredictOnlyMissing ("predict-only-missing","no prediction for times existing in input stream", true)
If true, prediction is only made for target times not found in the input stream.
Core::ParameterBool paramSyncEndTimes ("sync-end-times","synchronize start and end times", false)
If false (default), the output stream has the same number of frames as the target streams, but only start times are synchronized.
const f64 eps64 = 1.1103e-16 * 2.0
const f32 eps32 = 5.9605e-8 * 2.0
const Core::ParameterString paramMatrixMultiplicationFileName ("file","name of matrix file to load")
const Core::ParameterBool paramMatrixMultiplicationUseCache ("use-cache","uses a cache for different matrices.", false)
const Core::ParameterBool paramIgnoreTimestamps ("ignore-timestamps","ignore timestamps, i.e. update matrix for every frame", false)
const Core::ParameterInt paramMultipleDataProcessing ("multi-data","multiple data processing, i.e. more than one vector at a time, this parameter can only be set using a config file", 1)
static const u32 maxFilter = 8
const std::string totalScatterType
const std::string betweenClassScatterType
const std::string withinClassScatterType
const Core::ParameterFloat paramVectorCutFirst ("first","first element", 0, 0)
VectorCutNode.
const Core::ParameterFloat paramVectorCutLast ("last","last element", 0, 0)
const Core::ParameterFloat paramVectorResizeNewSize ("new-size","new size of vector in continuous (or discrete) units", 0, 0)
VectorResizeNode resizes input vector to a given size If new size is larger than the current size, the vector is extended by initial-value.
const Core::ParameterInt paramVectorResizeNewDiscreteSize ("new-discrete-size","new size of vector in discrete units", 0)
const Core::ParameterFloat paramVectorResizeInitialValue ("initial-value","appended value", 0)
const Core::ParameterBool paramVectorResizeChangeFront ("change-front","change front/back", false)
const Core::ParameterBool paramVectorResizeRelativeChange ("relative-change","specified size is relative", false)
const Core::ParameterBool paramVectorSequenceAggregationExpandTimestamp
Filter collects a vector sequence into an aggregate Input is sequence of vectors Output is an aggregate with vectors as aggregate streams Input vectors are collected with preceding and succeeding vectors.
const Core::ParameterBool paramVectorSequenceConcatExpandTimestamp
Filter concatenating of vector sequence Input is sequence of vectors Output is a sequence of concatenated vectors.
Detailed Description
Copyright 2020 RWTH Aachen University.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Typedef Documentation
typedef ScatterMatrixEstimator::ScatterMatrix Signal::ScatterMatrix
Scatter matrix type;.
Definition at line 81 of file ScatterEstimator.hh.
Function Documentation
template<class T > void Signal::allPolesPowerSpectrum (float gain, const std::vector< float > & a, size_t totalLength, std::vector< T > & powerSpectrum)
Calculate the all poles (also called as maximum entropy) power spectrum estimate.
Parameters
a is all poles (autoregression) coefficients a1, ..., aN,
gain is all poles gain,
totalLength is total length of the estimated power spectrum.
powerSpectrum is result buffer. Its length is set to totalLength / 2 + 1, since power spectrum of real functions is always symmetric.
Definition at line 31 of file AllPolesPowerSpectrum.hh.
References require.
Referenced by Signal::AllPolesPowerSpectrumNode::work().
void Signal::autoregressionToCepstrum (f32 gain, const std::vector< f32 > & a, std::vector< f32 > & c)
Calculate cepstrum coefficients from autoregressive coefficients.
c[n] = a[n] + sum_{k=1}^{n-1} ((n-k)/n c[n-k] a[k]), c[0] = 2 log(gain), where c contains the cepstrum coefficients, a constains the autoregressive coefficients (starting at a1), gain is autoregression gain = sqrt(prediction error).
Definition at line 21 of file AutoregressionToCepstrum.cc.
References require.
Referenced by Signal::AutoregressionToCepstrumNode::work().
template<class T > void Signal::convolution (const std::vector< T > & x, const std::vector< T > & h, std::vector< T > & y)
convolution y_t = sum_{tau} (x_tau * h_{t - tau})
Definition at line 28 of file Convolution.hh.
void Signal::fourierToHartley (const std::vector< f32 > & fourier, std::vector< f32 > & hartley)
fourierToHartley: converts Fourier coefficients to Hartley coefficients
Definition at line 374 of file FastHartleyTransform.cc.
References ensure.
template<class Type > void Signal::harmonicProduct (const std::vector< Type > & x, std::vector< Type > & s, u32 H)
harmonicProduct s(n) = prod_{h = 1}^{h = H} (x_{(h * n) mod T) where
The x is expected to be periodic (!) with a periodicity of T. Thus
Parameters
x represents one periode, i.e. it is of length T.
Length of
Parameters
s determines the interval for the index n.
H gives the maximum schrinkage.
normalization: to keep the product representable at high values of H
for each h the normalization factor is square root of the product of the energy of signal shrunken by h and the energy of the harmonic product at h -1
this normalization is motivated by the fourier transformed equivalent of product of symethric functions: cross-correlation.
Definition at line 73 of file HarmonicSum.hh.
References ensure.
template<class Type > void Signal::harmonicSum (const std::vector< Type > & x, std::vector< Type > & s, u32 H)
harmonicSum s(n) = sum_{h = 1}^{h = H} (x_{(h * n) mod T) where
The x is expected to be periodic (!) with a periodicity of T. Thus
Parameters
x represents one periode, i.e. it is of length T.
Length of
Parameters
s determines the interval for the index n.
H gives the maximum schrinkage.
Definition at line 40 of file HarmonicSum.hh.
References ensure.
void Signal::hartleyToFourier (const std::vector< f32 > & hartley, std::vector< f32 > & fourier)
hartleyToFourier: converts Hartley coefficients to Fourier coefficients
Definition at line 317 of file FastHartleyTransform.cc.
void Signal::hartleyToFourierAmplitude (const std::vector< f32 > & hartley, std::vector< f32 > & amplitude)
hartleyToFourierAmplitude: converts Hartley coefficients to amplitude of Fourier coefficients
Parameters
hartley and
amplitude can be the same object
Definition at line 334 of file FastHartleyTransform.cc.
References Core::abs().
void Signal::hartleyToFourierPhase (const std::vector< f32 > & hartley, std::vector< f32 > & phase)
hartleyToFourierPhase: converts Hartley coefficients to phase of Fourier coefficients
Parameters
hartley and
phase can be the same object
Definition at line 357 of file FastHartleyTransform.cc.
Variable Documentation
double Signal::costab[20] static
Initial value:
= {
        .00000000000000000000000000000000000000000000000000,
        .70710678118654752440084436210484903928483593768847,
        .92387953251128675612818318939678828682241662586364,
        .98078528040323044912618223613423903697393373089333,
        .99518472667219688624483695310947992157547486872985,
        .99879545620517239271477160475910069444320361470461,
        .99969881869620422011576564966617219685006108125772,
        .99992470183914454092164649119638322435060646880221,
        .99998117528260114265699043772856771617391725094433,
        .99999529380957617151158012570011989955298763362218,
        .99999882345170190992902571017152601904826792288976,
        .99999970586288221916022821773876567711626389934930,
        .99999992646571785114473148070738785694820115568892,
        .99999998161642929380834691540290971450507605124278,
        .99999999540410731289097193313960614895889430318945,
        .99999999885102682756267330779455410840053741619428}
Definition at line 110 of file FastHartleyTransform.cc.
double Signal::halsec[20] static
Initial value:
= {
        0,
        0,
        .54119610014619698439972320536638942006107206337801,
        .50979557910415916894193980398784391368261849190893,
        .50241928618815570551167011928012092247859337193963,
        .50060299823519630134550410676638239611758632599591,
        .50015063602065098821477101271097658495974913010340,
        .50003765191554772296778139077905492847503165398345,
        .50000941253588775676512870469186533538523133757983,
        .50000235310628608051401267171204408939326297376426,
        .50000058827484117879868526730916804925780637276181,
        .50000014706860214875463798283871198206179118093251,
        .50000003676714377807315864400643020315103490883972,
        .50000000919178552207366560348853455333939112569380,
        .50000000229794635411562887767906868558991922348920,
        .50000000057448658687873302235147272458812263401372}
Definition at line 93 of file FastHartleyTransform.cc.
Core::ParameterBool Signal::paramPredictOnlyMissing
If true, prediction is only made for target times not found in the input stream.
If false, prediction is made for each target time.
Definition at line 25 of file FramePrediction.hh.
Referenced by Signal::FramePredictionNode< Algorithm >::setParameter().
Core::ParameterBool Signal::paramSyncEndTimes
If false (default), the output stream has the same number of frames as the target streams, but only start times are synchronized.
If true, start- and end-times are synchronized, so the frames of target and output-stream have the same length
Definition at line 31 of file FramePrediction.hh.
Referenced by Signal::FramePredictionNode< Algorithm >::setParameter().
const Core::ParameterFloat Signal::paramVectorCutFirst("first","first element", 0, 0)
VectorCutNode.
Referenced by Signal::VectorCutRelativeSurface< T >::last(), and Signal::VectorCutNode< Algorithm >::setParameter().
const Core::ParameterFloat Signal::paramVectorResizeNewSize
VectorResizeNode resizes input vector to a given size If new size is larger than the current size, the vector is extended by initial-value.
Size is given in continuous units.
Definition at line 28 of file VectorResize.hh.
Referenced by Signal::VectorResizeNode< T >::setParameter().
const Core::ParameterBool Signal::paramVectorSequenceAggregationExpandTimestamp
Filter collects a vector sequence into an aggregate Input is sequence of vectors Output is an aggregate with vectors as aggregate streams Input vectors are collected with preceding and succeeding vectors.
Parameters -expand-timestamp: if true timestamp of output encompasses the timestamps of its element; if false timestamp of the "present" element is copied to timestamp of output. -for further parameters
See also
DelayNode Note: in output vector oldest frames are first and recent frames last.
Referenced by Signal::VectorSequenceAggregation< T >::getOutput(), and Signal::VectorSequenceAggregation< T >::setParameter().
const Core::ParameterBool Signal::paramVectorSequenceConcatExpandTimestamp
Filter concatenating of vector sequence Input is sequence of vectors Output is a sequence of concatenated vectors.
Input vectors are concatenated with preceding and succeeding vectors. Parameters -expand-timestamp: if true timestamp of output encompasses the timestamps of its element; if false timestamp if the "present" element is copied to timestamp of output. -for further parameters
See also
DelayNode Note: in output vector oldest frames are first and recent frames last.
Referenced by Signal::VectorSequenceConcatenation< T >::getOutput(), and Signal::VectorSequenceConcatenation< T >::setParameter().
double Signal::sintab[20] static
Initial value:
= {
        1.0000000000000000000000000000000000000000000000000,
        .70710678118654752440084436210484903928483593768846,
        .38268343236508977172845998403039886676134456248561,
        .19509032201612826784828486847702224092769161775195,
        .09801714032956060199419556388864184586113667316749,
        .04906767432741801425495497694268265831474536302574,
        .02454122852291228803173452945928292506546611923944,
        .01227153828571992607940826195100321214037231959176,
        .00613588464915447535964023459037258091705788631738,
        .00306795676296597627014536549091984251894461021344,
        .00153398018628476561230369715026407907995486457522,
        .00076699031874270452693856835794857664314091945205,
        .00038349518757139558907246168118138126339502603495,
        .00019174759731070330743990956198900093346887403385,
        .00009587379909597734587051721097647635118706561284,
        .00004793689960306688454900399049465887274686668768}
Definition at line 127 of file FastHartleyTransform.cc.