Sprint: Ftl Namespace Reference
Ftl Namespace Reference
Copyright 2020 RWTH Aachen University.
Classes
struct Accumulator
class AllPrefixesAutomaton
class AllSuffixesAutomaton
struct Arc
The basic arc structure.
class AreBothLabels
class ArrayArcContainer
stores arcs in self managed memory.
class Automaton
The basic automaton data structure.
class BestAutomaton
class BestAutomaton4SpecialSymbols
A best automaton which is able to work with FAIL arcs.
struct byArc
struct byInput
struct byInputAndOutput
struct byInputAndOutputAndTarget
struct byInputAndTarget
struct byOutput
struct byWeight
class CacheAutomaton
class ChangeInputAlphabetAutomaton
class ChangeInputOutputAlphabetAutomaton
class ChangeOutputAlphabetAutomaton
class ChangeSemiringAutomaton
class ClosureAutomaton
class CoaccessibleDfsState
class CollectAutomaton
class ComplementAutomaton
class ComposeAutomaton
Composition result of two transducers.
class ComposeMapping
class ComposeMatchingAutomaton
class ComposeSequencingAutomaton
class ConcatAutomaton
class ConcatUnionAutomaton
class ConverterAutomaton
Functor defining a mapping between the two sets.
class CopyDfsState
class CountDfsState
class CountInputDfsState
class CountLinearStatesDfsState
class CountOutputDfsState
class CountPathsAutomaton
class CountPathsSemiring_
class DeterminizeAutomaton
class DfsState
Due to the principle of on-demand computation, exploring automata becomes an important issue as states are not directly accessable.
class DotDrawer
class DrawDotDfsState
visualization
class EdgeTrWGWriter
class ExtendAutomaton
class ExtendFinalAutomaton
class FifoSsspQueue
class FirstBestAutomaton
class FusionAutomaton
class GeneralComposeAutomaton
class HypothesisAutomaton
class InDegreeDfsState
class InputMappedAutomaton
class InputOutputMappedAutomaton
class InvertAutomaton
class IsInputLabel
class IsInvalidArc
class KleeneClosureAutomaton
class LeftComposeMapping
class LocalDeterminizeAutomaton
class LogSemiring
class MappedAutomaton
class MinimizeAutomaton
class ModifyAutomaton
class NBestAutomaton
class NBestTraces
class NodeTrWGWriter
class NormalizeAutomaton
class NormalizeMapping
class OutputMappedAutomaton
class PartialAutomaton
class PosteriorAutomaton
class PosteriorAutomaton4SpecialSymbols
class PosteriorPruneAutomaton
pruning based on posterior scores still has some problems with floating point accuracy (some single arcs may not be pruned, but trimming afterwards helps)
class ProbabilitySemiring
class ProjectInputAutomaton
class ProjectOutputAutomaton
class PrunePosteriorAutomaton4SpecialSymbols
class PushToFinalAutomaton
class PushToInitialAutomaton
class RemoveEpsilons
remove epsilon (input) transitions
class RemoveFailure4SpecialSymbols
A FAIL arc removal automaton.
class ReplaceDisambiguationSymbolsAutomaton
class Resources
class RightComposeMapping
class Semiring
class SemiringAdapter
class SimpleRemoveEpsilonsAutomaton
remove "simple" epsilon arcs in a transducer
class SlaveAutomaton
class SortByArcAutomaton
class SortByInputAndOutputAndTargetAutomaton
class SortByInputAndOutputAutomaton
class SortByInputAndTargetAutomaton
class SortByInputAutomaton
class SortByOutputAutomaton
class SortByWeightAutomaton
struct SsspArcFilter
class SsspBackward4SpecialSymbols
A backward single source shortest distance for fsas with Failure transitions.
class SsspForward4SpecialSymbols
class SsspQueue
queue:
class State
The basic state class.
class StateMappedAutomaton
class StatePotentials
class StaticAutomaton
class StorageAutomaton
class StorageAutomatonXmlParser
class SyncPruneAutomaton
class TopologicallySortDfsState
TopologicallySortDfsState Helper class for the topologicallySort function.
class TopologicalSsspQueue
struct Trace
class TraceCache
class TransposeDfsState
class TrimAutomaton
trim deletes all non-accessible and non-coaccessible states, optimized by using SCC's
class TropicalSemiring
class UnionAutomaton
class UniteMapping
class VectorArcContainer
stores arcs in a STL vector.
class WeightModifyAutomaton
class WrapperAutomaton
class WriteAttDfsState
Transformations done in order to support AT&T's ascii based format:
class WriteBinaryDfsState
class WriteLinearDfsState
class WriteXmlDfsState
Typedefs
typedef Ftl::LogSemiring< Weight, s32 > LogIntegerSemiring_
typedef size_t Count
CountPathsAutomaton.
typedef Semiring< Count > CountSemiring
typedef Automaton< CountSemiring > CountAutomaton
Functions
template<class _Automaton >
_Automaton::ConstRef mapInput (typename _Automaton::ConstRef f, const Fsa::AlphabetMapping &)
Maps the input alphabet of the input automaton using an existing mapping.
template<class _Automaton >
_Automaton::ConstRef mapOutput (typename _Automaton::ConstRef f, const Fsa::AlphabetMapping &)
Maps the output alphabet of the input automaton using an existing mapping.
template<class _Automaton >
_Automaton::ConstRef mapInputOutput (typename _Automaton::ConstRef, const Fsa::AlphabetMapping &)
When the given automaton is an acceptor or has the same input and output alphabets, maps the input and output labels.
template<class _Automaton >
_Automaton::ConstRef mapInput (typename _Automaton::ConstRef f, Fsa::ConstAlphabetRef alphabet, u32 reportUnknowns=10)
Maps the input alphabet of the input automaton and calculates the mapping to the target alphabet beforehand.
template<class _Automaton >
_Automaton::ConstRef mapOutput (typename _Automaton::ConstRef f, Fsa::ConstAlphabetRef alphabet, u32 reportUnknowns=10)
Maps the output alphabet of the input automaton and calculates the mapping to the target alphabet beforehand.
template<class _Automaton >
_Automaton::ConstRef mapInputOutput (typename _Automaton::ConstRef f, Fsa::ConstAlphabetRef, u32 reportUnknowns=10)
When the given automaton is an acceptor or has the same input and output alphabets, maps the input and output labels.
template<class _Automaton >
_Automaton::ConstRef collect (typename _Automaton::ConstRef f, typename _Automaton::Weight value)
Collect each arc weight with the specified weight.
template<class _Automaton >
_Automaton::ConstRef extend (typename _Automaton::ConstRef f, typename _Automaton::Weight value)
Extend each arc weight with the specified weight.
template<class _Automaton >
_Automaton::ConstRef extendFinal (typename _Automaton::ConstRef f, typename _Automaton::Weight value)
Extend each final state weight with the specified weight.
template<class _Automaton , class Modifier >
_Automaton::ConstRef modifyWeight (typename _Automaton::ConstRef f, const Modifier &modifier)
template<class _Automaton , class Modifier >
_Automaton::ConstRef modify (typename _Automaton::ConstRef f, const Modifier &modifier=Modifier())
Modify each weight using the given functor of type Modifier.
template<class _Automaton >
_Automaton::ConstRef normalize (typename _Automaton::ConstRef f)
Normalize the state ids of an automaton.
template<class _Automaton >
Fsa::ConstMappingRef mapNormalized (typename _Automaton::ConstRef f)
Mapping returning the state's id in the original automaton.
template<class _Automaton >
_Automaton::ConstRef trim (typename _Automaton::ConstRef f, bool progress=false)
Keeps only states that are both accessible and coaccessible.
template<class _Automaton >
_Automaton::ConstRef partial (typename _Automaton::ConstRef f, Fsa::StateId initialStateOfPartialAutomaton)
Returns a partial automaton, i.e.
template<class _Automaton >
_Automaton::ConstRef partial (typename _Automaton::ConstRef f, Fsa::StateId initialStateOfPartialAutomaton, typename _Automaton::Weight additionalFinalWeight)
template<class _Automaton >
_Automaton::ConstRef hypothesis (typename _Automaton::ConstRef f, Fsa::StateId n)
Same as partial but preserving the scores for n-best lists.
template<class _Automaton >
_Automaton::ConstRef changeSemiring (typename _Automaton::ConstRef f, typename _Automaton::ConstSemiringRef semiring)
Changes the semiring of an automaton.
template<class _AutomatonFrom , class _AutomatonTo , class _Mapping >
Core::Ref< const _AutomatonTo > convert (Core::Ref< const _AutomatonFrom > f, Core::Ref< const typename _AutomatonTo::Semiring > semiring, const _Mapping &map=_Mapping())
Changes the semiring and the set of an automaton.
template<class _AutomatonFrom , class _Semiring , class _Mapping >
Core::Ref< const Automaton< State< Arc< typename _Semiring::Weight > > > > changeSemiringAndSet (Core::Ref< const _AutomatonFrom > f, Core::Ref< const _Semiring > semiring, const _Mapping &map=_Mapping())
template<class _Automaton >
_Automaton::Weight bestscore (typename _Automaton::ConstRef f)
Calculates the score of the best path through a weighted automaton.
template<class _Automaton >
_Automaton::ConstRef best (typename _Automaton::ConstRef f)
Calculates the best path through a weighted automaton.
template<class _Automaton >
_Automaton::ConstRef best (typename _Automaton::ConstRef f, const StatePotentials< typename _Automaton::Weight > &backward)
Calculates the best path through a weighted automaton using precalculated backward scores.
template<class _Automaton >
_Automaton::ConstRef nbest (typename _Automaton::ConstRef f, size_t n=1, bool bestSequences=true)
Calculates the n best paths through a weighted automaton.
template<class _Automaton >
_Automaton::ConstRef firstbest (typename _Automaton::ConstRef f)
Compute best path through an automaton using Dijkstra's algorithm (best first search).
template<class _Automaton >
Core::Ref< const _Automaton > cache (Core::Ref< const _Automaton > f, u32 maxAge=10000)
Caches states of an automaton.
template<class _Automaton >
_Automaton::ConstRef composeMatching (typename _Automaton::ConstRef fl, typename _Automaton::ConstRef fr, bool reportUnknowns=true)
Calculates the composition result of two input transducers using the matching epsilon filter.
template<class _Automaton >
_Automaton::ConstRef difference (typename _Automaton::ConstRef fl, typename _Automaton::ConstRef fr)
Calculates an automaton that represents a language equal to the difference of the two input languages L = L_l \ L_r.
template<class _Automaton >
_Automaton::ConstRef composeSequencing (typename _Automaton::ConstRef fl, typename _Automaton::ConstRef fr, bool reportUnknowns=true)
Calculates the composition result of two input transducers using a so-called sequencing epsilon filter.
template<class _Automaton >
Fsa::ConstMappingRef mapToLeft (typename _Automaton::ConstRef f)
Mapping returning the state's id in the left original automaton.
template<class _Automaton >
Fsa::ConstMappingRef mapToRight (typename _Automaton::ConstRef f)
Mapping returning the state's id in the right original automaton.
template<class _Automaton >
void copy (StorageAutomaton< _Automaton > *f, typename _Automaton::ConstRef f2)
template<class _Automaton >
void copy (StorageAutomaton< _Automaton > *f, const std::string &str)
template<class _Automaton >
void copy (StorageAutomaton< _Automaton > *f, const Fsa::Hash< std::string, Core::StringHash > &tokens, u32 sausage)
template<class _Automaton >
Core::Ref< StaticAutomaton< _Automaton > > staticCopy (typename _Automaton::ConstRef f)
template<class _Automaton >
Core::Ref< StaticAutomaton< _Automaton > > staticCompactCopy (typename _Automaton::ConstRef f)
template<class _Automaton >
Core::Ref< StaticAutomaton< _Automaton > > staticCopy (const std::string &str, typename _Automaton::ConstSemiringRef semiring)
template<class _Automaton >
Core::Ref< StaticAutomaton< _Automaton > > staticCopy (const Fsa::Hash< std::string, Core::StringHash > strings, typename _Automaton::ConstSemiringRef semiring, u32 sausage=0)
template<class _Automaton >
_Automaton::ConstRef determinize (typename _Automaton::ConstRef f, bool disambiguate)
template<class _Automaton >
_Automaton::ConstRef localDeterminize (typename _Automaton::ConstRef f)
template<class _Automaton >
_Automaton::ConstRef removeDisambiguationSymbols (typename _Automaton::ConstRef f)
template<class _Automaton >
_Automaton::ConstRef replaceDisambiguationSymbols (typename _Automaton::ConstRef f, Fsa::LabelId ll)
template<class _Automaton >
_Automaton::ConstRef removeInputDisambiguationSymbols (typename _Automaton::ConstRef f)
template<class _Automaton >
_Automaton::ConstRef replaceInputDisambiguationSymbols (typename _Automaton::ConstRef f, Fsa::LabelId ll)
template<class _Automaton >
bool drawDot (typename _Automaton::ConstRef f, std::ostream &o, Fsa::Hint hint, bool progress)
template<class _Automaton >
bool drawDot (typename _Automaton::ConstRef f, const std::string &file, Fsa::Hint hint, bool progress)
template<class _Automaton >
Fsa::AutomatonCounts count (typename _Automaton::ConstRef f, bool progress=false)
Calculates some interesting statistics of the size of an automaton.
template<class _Automaton >
bool isEmpty (typename _Automaton::ConstRef f)
Test for emptyness.
template<class _Automaton >
size_t countLinearStates (typename _Automaton::ConstRef f, bool progress=false)
Calculates some number of linear states, i.e.
template<class _Automaton >
Core::Vector< u32 > inDegree (typename _Automaton::ConstRef f, bool progress=false)
Calculates the in-degree for each state, i.e.
template<class _Automaton >
size_t countInput (typename _Automaton::ConstRef f, Fsa::LabelId label, bool progress=false)
Calculates some number of occurances of the given input label in an automaton.
template<class _Automaton >
size_t countOutput (typename _Automaton::ConstRef f, Fsa::LabelId label, bool progress=false)
Calculates some number of occurances of the given output label in an automaton.
template<class _Automaton >
void basicInfo (typename _Automaton::ConstRef f, Core::XmlWriter &o)
template<class _Automaton >
void info (typename _Automaton::ConstRef f, Core::XmlWriter &o, bool progress=false)
Report information about an FSA automaton.
template<class _Automaton >
void cheapInfo (typename _Automaton::ConstRef f, Core::XmlWriter &o)
Report some information about an FSA automaton.
template<class _Automaton >
void memoryInfo (typename _Automaton::ConstRef f, Core::XmlWriter &o)
Report some information about an FSA automaton.
template<class _Automaton >
_Automaton::ConstRef read (const Resources< _Automaton > &resources, const std::string &format, std::istream &i)
template<class _Automaton >
bool read (const Resources< _Automaton > &resources, StorageAutomaton< _Automaton > *f, const std::string &format, std::istream &i)
template<class _Automaton >
_Automaton::ConstRef read (const Resources< _Automaton > &resources, const std::string &file)
template<class _Automaton >
bool read (const Resources< _Automaton > &resources, StorageAutomaton< _Automaton > *f, const std::string &file)
template<class _Automaton >
void assertSemiring (const Resources< _Automaton > &resources, StorageAutomaton< _Automaton > *f)
template<class _Automaton >
bool readAtt (const Resources< _Automaton > &resources, StorageAutomaton< _Automaton > *f, std::istream &i)
template<class _Automaton >
bool readBinary (const Resources< _Automaton > &resources, StorageAutomaton< _Automaton > *f, std::istream &i)
template<class _Automaton >
bool readLinear (const Resources< _Automaton > &resources, StorageAutomaton< _Automaton > *f, std::istream &i)
template<class _Automaton >
bool readXml (const Resources< _Automaton > &resources, StorageAutomaton< _Automaton > *f, std::istream &i)
template<class _Automaton >
bool isLinear (typename _Automaton::ConstRef)
Test if automaton is linear explicitly.
template<class _Automaton >
void getLinearInput (typename _Automaton::ConstRef, std::vector< Fsa::LabelId > &result)
Convert linear automaton to vector of input symbols.
template<class _Automaton >
void getLinearOutput (typename _Automaton::ConstRef, std::vector< Fsa::LabelId > &result)
Convert linear automaton to vector of output symbols.
template<class _Automaton >
_Automaton::Weight getLinearWeight (typename _Automaton::ConstRef)
Compute total weight of linear automaton.
template<class A >
A::ConstRef minimize (typename A::ConstRef f, bool progress)
template<class A >
A::ConstRef minimize (typename A::ConstRef f, Fsa::OptimizationHint hint, bool progress)
template<class A >
A::ConstRef minimizeSimple (typename A::ConstRef f)
template<class _Automaton >
_Automaton::ConstRef minimize (typename _Automaton::ConstRef f, bool progress=false)
template<class _Automaton >
_Automaton::ConstRef minimize (typename _Automaton::ConstRef f, Fsa::OptimizationHint hint, bool progress=false)
template<class _Automaton >
_Automaton::ConstRef minimizeSimple (typename _Automaton::ConstRef f)
template<class _Automaton >
bool write (const Resources< _Automaton > &resources, typename _Automaton::ConstRef f, const std::string &format, std::ostream &o, Fsa::StoredComponents what=Fsa::storeAll, bool progress=false)
storage
template<class _Automaton >
bool write (const Resources< _Automaton > &resources, typename _Automaton::ConstRef f, const std::string &file, Fsa::StoredComponents what, bool progress)
template<class _Automaton >
bool writeAtt (const Resources< _Automaton > &resources, typename _Automaton::ConstRef f, std::ostream &o, Fsa::StoredComponents what, bool progress)
template<class _Automaton >
bool writeAtt (const Resources< _Automaton > &resources, typename _Automaton::ConstRef f, const std::string &file, Fsa::StoredComponents what, bool progress)
template<class _Automaton >
bool writeBinary (const Resources< _Automaton > &resources, typename _Automaton::ConstRef f, std::ostream &o, Fsa::StoredComponents what, bool progress)
template<class _Automaton >
bool writeBinary (const Resources< _Automaton > &resources, typename _Automaton::ConstRef f, const std::string &file, Fsa::StoredComponents what, bool progress)
template<class _Automaton >
bool writeLinear (const Resources< _Automaton > &resources, typename _Automaton::ConstRef f, std::ostream &o, Fsa::StoredComponents what, bool progress, bool printAll)
template<class _Automaton >
bool writeLinear (const Resources< _Automaton > &resources, typename _Automaton::ConstRef f, std::ostream &o, Fsa::StoredComponents what, bool progress)
template<class _Automaton >
bool writeLinear (const Resources< _Automaton > &resources, typename _Automaton::ConstRef f, const std::string &file, Fsa::StoredComponents what, bool progress)
template<class _Automaton >
bool writeXml (const Resources< _Automaton > &resources, typename _Automaton::ConstRef f, std::ostream &o, Fsa::StoredComponents what, bool progress)
template<class _Automaton >
bool writeXml (const Resources< _Automaton > &resources, typename _Automaton::ConstRef f, const std::string &file, Fsa::StoredComponents what, bool progress)
template<class _Automaton >
bool writeTrXml (const Resources< _Automaton > &resources, typename _Automaton::ConstRef f, std::ostream &o, Fsa::StoredComponents what, bool progress)
template<class _Automaton >
bool writeTrXml (const Resources< _Automaton > &resources, typename _Automaton::ConstRef f, const std::string &file, Fsa::StoredComponents what, bool progress)
template<class _Automaton >
_Automaton::ConstRef projectInput (typename _Automaton::ConstRef f)
template<class _Automaton >
_Automaton::ConstRef projectOutput (typename _Automaton::ConstRef f)
template<class _Automaton >
_Automaton::ConstRef invert (typename _Automaton::ConstRef f)
template<class _Automaton >
Fsa::Property getProperties (typename _Automaton::ConstRef f, Fsa::Property properties=Fsa::PropertyAll)
Get properties.
template<class _Automaton >
bool hasProperties (typename _Automaton::ConstRef f, Fsa::Property properties)
Test properties.
template<class _Automaton >
_Automaton::ConstRef prunePosterior (typename _Automaton::ConstRef f, const typename _Automaton::Weight &threshold, bool relative)
template<class _Automaton >
_Automaton::ConstRef prunePosterior (typename _Automaton::ConstRef f, const typename _Automaton::Weight &threshold, const StatePotentials< typename _Automaton::Weight > &fw, const StatePotentials< typename _Automaton::Weight > &bw, bool relative)
template<class _Automaton >
_Automaton::ConstRef pruneSync (typename _Automaton::ConstRef f, const typename _Automaton::Weight &threshold)
template<class _Automaton >
_Automaton::ConstRef identity (Fsa::ConstAlphabetRef ab, typename _Automaton::ConstSemiringRef sr)
template<class _Automaton >
_Automaton::ConstRef closure (typename _Automaton::ConstRef f)
template<class _Automaton >
_Automaton::ConstRef kleeneClosure (typename _Automaton::ConstRef f)
template<class _Automaton >
_Automaton::ConstRef complement (typename _Automaton::ConstRef f)
template<class _Automaton >
_Automaton::ConstRef concat (const Core::Vector< typename _Automaton::ConstRef > &f)
template<class _Automaton >
_Automaton::ConstRef concat (typename _Automaton::ConstRef f1, typename _Automaton::ConstRef f2)
template<class _Automaton >
_Automaton::ConstRef unite (const Core::Vector< typename _Automaton::ConstRef > &f, const Core::Vector< typename _Automaton::Weight > &initialWeights)
template<class _Automaton >
_Automaton::ConstRef unite (typename _Automaton::ConstRef f1, typename _Automaton::ConstRef f2)
template<class _Automaton >
Fsa::ConstMappingRef mapToSubAutomaton (typename _Automaton::ConstRef f, u32 subAutomaton)
Mapping returning the state's id in the respective original sub-automaton.
template<class _Automaton >
_Automaton::ConstRef fuse (const Core::Vector< typename _Automaton::ConstRef > &f)
Fuse initial states.
template<class _Automaton >
_Automaton::ConstRef fuse (typename _Automaton::ConstRef f1, typename _Automaton::ConstRef f2)
template<class _Automaton >
_Automaton::ConstRef transpose (typename _Automaton::ConstRef f, bool progress)
template<class _Automaton >
_Automaton::ConstRef allPrefixes (typename _Automaton::ConstRef f)
template<class _Automaton >
_Automaton::ConstRef allSuffixes (typename _Automaton::ConstRef f)
template<class _Automaton >
Core::Ref< const _Automaton > removeEpsilons (Core::Ref< const _Automaton > f)
template<class _Automaton >
Core::Ref< const _Automaton > removeSimpleEpsilonArcs (Core::Ref< const _Automaton > f)
template<class _Automaton >
_Automaton::ConstRef sort (typename _Automaton::ConstRef f, Fsa::SortType type)
Sorts arcs leaving a state.
template<class _Automaton >
Fsa::StateMap topologicallySort (typename _Automaton::ConstRef f, bool progress=false)
Topologically sorts states of the given automaton.
template<class _Automaton >
bool isAcyclic (typename _Automaton::ConstRef)
Test if automaton is acyclic using DFS.
template<class _Automaton , class Queue >
StatePotentials< typename _Automaton::Weight > ssspLoop (Queue &q, typename _Automaton::ConstRef f, Fsa::StateId start, const SsspArcFilter< _Automaton > &arcFilter, bool progress)
template<class _Automaton >
StatePotentials< typename _Automaton::Weight > sssp (typename _Automaton::ConstRef f, Fsa::StateId start, const SsspArcFilter< _Automaton > &arcFilter, bool progress)
template<class _Automaton >
StatePotentials< typename _Automaton::Weight > sssp (typename _Automaton::ConstRef f, bool progress=false)
see Weighted Automata Algorithms, Mehryar Mohri, Handbook of weighted automata, 2009, page 10 (http://www.cs.nyu.edu/~mohri/postscript/hwa.pdf)
template<class _Automaton >
StatePotentials< typename _Automaton::Weight > ssspBackward (typename _Automaton::ConstRef f, const SsspArcFilter< _Automaton > &arcFilter, bool progress)
template<class _Automaton >
StatePotentials< typename _Automaton::Weight > ssspBackward (typename _Automaton::ConstRef f, bool progress)
template<class _Automaton >
_Automaton::ConstRef pushToFinal (typename _Automaton::ConstRef f, bool progress)
template<class _Automaton >
_Automaton::ConstRef pushToInitial (typename _Automaton::ConstRef f, bool progress)
template<class _Automaton >
_Automaton::ConstRef posterior (typename _Automaton::ConstRef f)
template<class _Automaton >
_Automaton::ConstRef posterior (typename _Automaton::ConstRef f, const StatePotentials< typename _Automaton::Weight > &forward)
template<class _Automaton >
_Automaton::ConstRef posterior (typename _Automaton::ConstRef f, typename _Automaton::Weight &totalInv)
template<class _SrcAutomaton >
size_t countPaths (typename _SrcAutomaton::ConstRef f)
template<class _Automaton >
size_t countPaths (typename _Automaton::ConstRef f)
Calculates the number of paths through the given automaton starting from the initial state to one of the final states.
template<class _Automaton >
_Automaton::ConstRef posterior4SpecialSymbols (typename _Automaton::ConstRef f)
template<class _Automaton >
_Automaton::ConstRef posterior4SpecialSymbols (typename _Automaton::ConstRef f, typename _Automaton::Weight &totalInv, s32 tol)
template<class _Automaton , class _SsspSemiring , class _SsspWeight >
_Automaton::ConstRef posterior4SpecialSymbols (typename _Automaton::ConstRef f, typename _Automaton::Weight &totalInv, s32 tol)
template<class _Automaton >
_Automaton::ConstRef best4SpecialSymbols (typename _Automaton::ConstRef f)
template<class _Automaton >
_Automaton::ConstRef removeFailure4SpecialSymbols (typename _Automaton::ConstRef f)
template<class _Automaton >
_Automaton::ConstRef prunePosterior4SpecialSymbols (typename _Automaton::ConstRef f, const typename _Automaton::Weight &threshold, bool relative)
template<class _Automaton , class _SsspSemiring , class _SsspWeight >
_Automaton::ConstRef prunePosterior4SpecialSymbols (typename _Automaton::ConstRef f, const typename _Automaton::Weight &threshold, bool relative)
template<class _Automaton >
void removeNonAccessibleStates (Core::Ref< StaticAutomaton< _Automaton >> s)
template<class _Automaton >
void trimInPlace (Core::Ref< StaticAutomaton< _Automaton >> sa)
template<class _Automaton >
void removeInvalidArcsInPlace (Core::Ref< StaticAutomaton< _Automaton >> sa)
Variables
template<class _Automaton >
Core::Ref< StaticAutomaton< _Automaton > > staticCopy (typename _Automaton::ConstRef)
template<class _Automaton >
Core::Ref< StaticAutomaton< _Automaton > > staticCompactCopy (typename _Automaton::ConstRef)
Detailed Description
Copyright 2020 RWTH Aachen University.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Typedef Documentation
typedef size_t Ftl::Count
CountPathsAutomaton.
Sets the semiring to CountPathSemiring, all arc weights to 1 and adds a super final state to the automaton in order to do sssp in a single forward pass.
Parameters
f the automaton to count paths for
Definition at line 472 of file tSssp.cc.
Function Documentation
template<class _Automaton > _Automaton::ConstRef Ftl::best (typename _Automaton::ConstRef f)
Calculates the best path through a weighted automaton.
Category: on-demand with precalculations Complexity: worst-case: O(sssp(f) + V + E), best-case: O(sssp(f) + n * E') where n is the length if the best path
Parameters
f the automaton
Returns
the best path represented as automaton
Definition at line 114 of file tBest.cc.
template<class _Automaton > _Automaton::ConstRef Ftl::best (typename _Automaton::ConstRef f, const StatePotentials< typename _Automaton::Weight > & backward)
Calculates the best path through a weighted automaton using precalculated backward scores.
This simply skips the additional precalculation step. Category: on-demand
Parameters
f the automaton
backward backward state potentials
Returns
the best path represented as automaton
Definition at line 119 of file tBest.cc.
template<class _Automaton > _Automaton::Weight Ftl::bestscore (typename _Automaton::ConstRef f)
Calculates the score of the best path through a weighted automaton.
Todo:
make bestscore more efficient
Currently, this is only well defined in the tropical semiring. Complexity: O(sssp(f) +)
Parameters
f the automaton
Returns
total score of the best path
Definition at line 103 of file tBest.cc.
template<class _Automaton > Core::Ref< const _Automaton > Ftl::cache (Core::Ref< const _Automaton > f, u32 maxAge = 10000)
Caches states of an automaton.
Helps to substantially reduce computational complexity by using more memory. Caching is only done for none-storage (e.g. static or packed) and non-cache automata. Currently complete states together with their associated outgoing arcs are cached. Uses a simple 8-bit depth ageing algorithm.
Parameters
f the automaton we want to cache
maxAge the number of calls to getState() necessary to trigger one ageing step
Returns
the cached automaton
Definition at line 75 of file tCache.cc.
References Fsa::PropertyStorage.
template<class _Automaton > _Automaton::ConstRef Ftl::changeSemiring (typename _Automaton::ConstRef f, typename _Automaton::ConstSemiringRef semiring)
Changes the semiring of an automaton.
Only the semiring is exchanges, the binary representation of weight is unchanged. There is no check whether this gives meaningful results. At the moment you are only able to change between log and tropical semiring. Category: on-demand
Parameters
f input automaton
semiring the new semiring
Returns
returns an automaton over the new semiring
Definition at line 278 of file tBasic.cc.
template<class _Automaton > void Ftl::cheapInfo (typename _Automaton::ConstRef f, Core::XmlWriter & o)
Report some information about an FSA automaton.
Like info(), but restricted to information that can be obtained in O(1), i.e. omits state and arc statistics. Complexity: O(1)
Definition at line 294 of file tInfo.cc.
template<class _Automaton > _Automaton::ConstRef Ftl::collect (typename _Automaton::ConstRef f, typename _Automaton::Weight value)
Collect each arc weight with the specified weight.
Category: on-demand Complexity: O(V + E)
Parameters
f the input automaton
value the weight
Returns
returns an automaton with all arc weights being collected with value
Definition at line 51 of file tArithmetic.cc.
template<class _Automaton > _Automaton::ConstRef Ftl::composeMatching (typename _Automaton::ConstRef fl, typename _Automaton::ConstRef fr, bool reportUnknowns = true)
Calculates the composition result of two input transducers using the matching epsilon filter.
This is not guaranteed to do the same than what the AT&T FSM library matching composition filter does although we haven't seen a case yet where results were different.
Parameters
fl "left" automaton
fr "right" automaton
reportUnknowns tell the user (on stdout) wether mapping of alphabet symbols reveiled unknowns in the "right" automaton
Returns
the result automaton of the composition (an acceptor in the case of two input acceptors, a transducer in all other cases)
Definition at line 463 of file tCompose.cc.
template<class _Automaton > _Automaton::ConstRef Ftl::composeSequencing (typename _Automaton::ConstRef fl, typename _Automaton::ConstRef fr, bool reportUnknowns = true)
Calculates the composition result of two input transducers using a so-called sequencing epsilon filter.
This is not guaranteed to do the same than what the AT&T FSM library sequencing composition filter does although we haven't seen a case yet where results were different.
Parameters
fl "left" automaton
fr "right" automaton
reportUnknowns tell the user (on stdout) wether mapping of alphabet symbols reveiled unknowns in the "right" automaton
Returns
the result automaton of the composition (an acceptor in the case of two input acceptors, a transducer in all other cases)
Definition at line 528 of file tCompose.cc.
template<class _AutomatonFrom , class _AutomatonTo , class _Mapping > Core::Ref< const _AutomatonTo > Ftl::convert (Core::Ref< const _AutomatonFrom > f, Core::Ref< const typename _AutomatonTo::Semiring > semiring, const _Mapping & map = _Mapping())
Changes the semiring and the set of an automaton.
Thus, it is necessary to define a mapping between the two sets. Category: on-demand
Parameters
f input automaton
semiring the new semiring determinizing the new set
map a functor defining a mapping from the old to the new set
Returns
returns an automaton over the new semiring
Definition at line 328 of file tBasic.cc.
template<class _Automaton > Fsa::AutomatonCounts Ftl::count (typename _Automaton::ConstRef f, bool progress = false)
Calculates some interesting statistics of the size of an automaton.
This function uses dfs(). Complexity: O(V + E)
Parameters
f the automaton
progress set to true if function should show a progress indicator on current tty
Returns
returns a data structure containing the counts
Definition at line 61 of file tInfo.cc.
References Ftl::DfsState< _Automaton >::dfs().
template<class _Automaton > size_t Ftl::countInput (typename _Automaton::ConstRef f, Fsa::LabelId label, bool progress = false)
Calculates some number of occurances of the given input label in an automaton.
This function uses dfs(). Complexity: O(V + E)
Parameters
f the automaton
label the input label
progress set to true if function should show a progress indicator on current tty
Returns
returns the number of occurances of label as an input label
Definition at line 181 of file tInfo.cc.
References Ftl::DfsState< _Automaton >::dfs().
template<class _Automaton > size_t Ftl::countLinearStates (typename _Automaton::ConstRef f, bool progress = false)
Calculates some number of linear states, i.e.
the number of states with an in-degree of 1. This function uses dfs(). Complexity: O(V + E)
Parameters
f the automaton
progress set to true if function should show a progress indicator on current tty
Returns
returns the number of linear states
Definition at line 128 of file tInfo.cc.
References Ftl::DfsState< _Automaton >::dfs().
template<class _Automaton > size_t Ftl::countOutput (typename _Automaton::ConstRef f, Fsa::LabelId label, bool progress = false)
Calculates some number of occurances of the given output label in an automaton.
This function uses dfs(). Complexity: O(V + E)
Parameters
f the automaton
label the output label
progress set to true if function should show a progress indicator on current tty
Returns
returns the number of occurances of label as an output label
Definition at line 224 of file tInfo.cc.
References Fsa::count(), and Ftl::DfsState< _Automaton >::dfs().
template<class _Automaton > size_t Ftl::countPaths (typename _Automaton::ConstRef f)
Calculates the number of paths through the given automaton starting from the initial state to one of the final states.
Complexity: see sssp()
Parameters
f the automaton
Returns
returns the number of paths or Core::Type<size_t>::max(=2147483647 for s32) if the number was larger than that
template<class _Automaton > _Automaton::ConstRef Ftl::difference (typename _Automaton::ConstRef fl, typename _Automaton::ConstRef fr)
Calculates an automaton that represents a language equal to the difference of the two input languages L = L_l \ L_r.
Parameters
fl "left" automaton
fr "right" automaton
Returns
the result automaton of the difference operation
Definition at line 468 of file tCompose.cc.
template<class _Automaton > _Automaton::ConstRef Ftl::extend (typename _Automaton::ConstRef f, typename _Automaton::Weight value)
Extend each arc weight with the specified weight.
Category: on-demand Complexity: O(V + E)
Parameters
f the input automaton
value the weight
Returns
returns an automaton with all arc weights being extended by value
Definition at line 83 of file tArithmetic.cc.
template<class _Automaton > _Automaton::ConstRef Ftl::extendFinal (typename _Automaton::ConstRef f, typename _Automaton::Weight value)
Extend each final state weight with the specified weight.
Category: on-demand Complexity: O(V + E)
Parameters
f the input automaton
value the weight
Returns
returns an automaton with all final state weights being extended by value
Definition at line 121 of file tArithmetic.cc.
template<class _Automaton > _Automaton::ConstRef Ftl::firstbest (typename _Automaton::ConstRef f)
Compute best path through an automaton using Dijkstra's algorithm (best first search).
This routine is functionally equivalent to best(), but uses a different search alogrithm. In particular firstBest() is not exhaustive.
Parameters
f the automaton
Returns
the subset of containing only the best path
Definition at line 494 of file tBest.cc.
template<class _Automaton > _Automaton::ConstRef Ftl::fuse (const Core::Vector< typename _Automaton::ConstRef > & f)
Fuse initial states.
The result automaton will contain the union of the states of the source automata, except for their initial states. The initial state of all source automata will be merged into a single initial state. For certain (but common) cases this is equivalent to closure(unite()), but does not produce the nasty epsilon loops.
Definition at line 555 of file tRational.cc.
template<class _Automaton > void Ftl::getLinearInput (typename _Automaton::ConstRef , std::vector< Fsa::LabelId > & result)
Convert linear automaton to vector of input symbols.
The automaton must be linear. Epsilon labels are suppressed.
Definition at line 41 of file tLinear.cc.
References require.
template<class _Automaton > void Ftl::getLinearOutput (typename _Automaton::ConstRef , std::vector< Fsa::LabelId > & result)
Convert linear automaton to vector of output symbols.
The automaton must be linear. Epsilon labels are suppressed.
Definition at line 54 of file tLinear.cc.
References require.
template<class _Automaton > _Automaton::Weight Ftl::getLinearWeight (typename _Automaton::ConstRef)
Compute total weight of linear automaton.
The automaton must be linear.
Definition at line 67 of file tLinear.cc.
References require.
template<class _Automaton > Fsa::Property Ftl::getProperties (typename _Automaton::ConstRef f, Fsa::Property properties = Fsa::PropertyAll)
Get properties.
If necessary the requested properties are computed using isAcyclic() or isLinear().
See also
Fsa/Types.hh
Parameters
f automaton to get the properties for
properties the properties to get
Returns
properties of the automaton
Definition at line 21 of file tProperties.cc.
template<class _Automaton > bool Ftl::hasProperties (typename _Automaton::ConstRef f, Fsa::Property properties)
Test properties.
If necessary the requested properties are computed. This is a convienance function to getProperties().
See also
Fsa/Types.hh
Parameters
f automaton to test the properties for
properties the properties to test for
Returns
true if the automaton has any of the properties passed to the funtion.
Definition at line 44 of file tProperties.hh.
template<class _Automaton > _Automaton::ConstRef Ftl::hypothesis (typename _Automaton::ConstRef f, Fsa::StateId n)
Same as partial but preserving the scores for n-best lists.
Category: on-demand
Parameters
f input automaton
initial the id of the new initial state
Returns
returns an automaton with the new initial state
Definition at line 246 of file tBasic.cc.
template<class _Automaton > Core::Vector< u32 > Ftl::inDegree (typename _Automaton::ConstRef f, bool progress = false)
Calculates the in-degree for each state, i.e.
the number of incoming arcs to a state. This function uses dfs(). Complexity: O(V + E)
Parameters
f the automaton
progress set to true if function should show a progress indicator on current tty
Returns
returns a vector that contains the in-degree for each state
Definition at line 140 of file tInfo.cc.
References Ftl::DfsState< _Automaton >::dfs().
template<class _Automaton > void Ftl::info (typename _Automaton::ConstRef f, Core::XmlWriter & o, bool progress = false)
Report information about an FSA automaton.
Warning
info() exhaustively counts all states and arcs, which may take a considerable amount of time. Be careful when applying to large automata. Complexity: O(I + O + V + E)
Definition at line 263 of file tInfo.cc.
template<class _Automaton > bool Ftl::isAcyclic (typename _Automaton::ConstRef)
Test if automaton is acyclic using DFS.
Returns
true is automatic contains no cycles (except trivial ones). i.e. automaton is topologically sortable.
Definition at line 273 of file tSort.cc.
References Ftl::DfsState< _Automaton >::dfs().
template<class _Automaton > bool Ftl::isEmpty (typename _Automaton::ConstRef f)
Test for emptyness.
Returns
true if the automaton represents the empty language (or relation).
Definition at line 73 of file tInfo.cc.
References Ftl::DfsState< _Automaton >::dfs().
template<class _Automaton > bool Ftl::isLinear (typename _Automaton::ConstRef)
Test if automaton is linear explicitly.
You should use hasProperty() to avoid redundant checks.
Definition at line 22 of file tLinear.cc.
template<class _Automaton > _Automaton::ConstRef Ftl::mapInput (typename _Automaton::ConstRef f, const Fsa::AlphabetMapping &)
Maps the input alphabet of the input automaton using an existing mapping.
Note, that the mapping must fits the alphabet of the input automaton. Category: on-demand
Parameters
f the input automaton
alphabet the alphabet to map to
Definition at line 251 of file tAlphabet.cc.
References Fsa::AlphabetMapping::from(), Fsa::AlphabetMapping::isModifyingType(), require, Fsa::AlphabetMapping::to(), Fsa::AlphabetMapping::type(), and Fsa::AlphabetMapping::typeIdentity.
template<class _Automaton > _Automaton::ConstRef Ftl::mapInput (typename _Automaton::ConstRef f, Fsa::ConstAlphabetRef alphabet, u32 reportUnknowns = 10)
Maps the input alphabet of the input automaton and calculates the mapping to the target alphabet beforehand.
Category: on-demand with precalculations
Parameters
f the input automaton
alphabet the alphabet to map to
reportUnknowns maximum number of unknown symbols that should be reported
Definition at line 280 of file tAlphabet.cc.
References Fsa::mapAlphabet().
template<class _Automaton > _Automaton::ConstRef Ftl::mapInputOutput (typename _Automaton::ConstRef , const Fsa::AlphabetMapping &)
When the given automaton is an acceptor or has the same input and output alphabets, maps the input and output labels.
This is more efficient than calling both mapInput() and mapOutput(), and in the case of accetors, this prevents the type from being changed to transducer. Category: on-demand
Parameters
f the input automaton
alphabet the alphabet to map to
Definition at line 269 of file tAlphabet.cc.
References Fsa::AlphabetMapping::from(), Fsa::AlphabetMapping::isModifyingType(), require, Fsa::AlphabetMapping::to(), Fsa::AlphabetMapping::type(), and Fsa::AlphabetMapping::typeIdentity.
template<class _Automaton > _Automaton::ConstRef Ftl::mapInputOutput (typename _Automaton::ConstRef f, Fsa::ConstAlphabetRef , u32 reportUnknowns = 10)
When the given automaton is an acceptor or has the same input and output alphabets, maps the input and output labels.
This is more efficient than calling both mapInput() and mapOutput(), and in the case of accetors, this prevents the type from being changed to transducer. Category: on-demand with precalculations
Parameters
f the input automaton
alphabet the alphabet to map to
reportUnknowns maximum number of unknown symbols that should be reported
Definition at line 292 of file tAlphabet.cc.
References Fsa::mapAlphabet(), and require.
template<class _Automaton > Fsa::ConstMappingRef Ftl::mapNormalized (typename _Automaton::ConstRef f)
Mapping returning the state's id in the original automaton.
Definition at line 99 of file tBasic.cc.
template<class _Automaton > _Automaton::ConstRef Ftl::mapOutput (typename _Automaton::ConstRef f, const Fsa::AlphabetMapping &)
Maps the output alphabet of the input automaton using an existing mapping.
Note, that the mapping must fits the alphabet of the input automaton. Category: on-demand
Parameters
f the input automaton
alphabet the alphabet to map to
Definition at line 260 of file tAlphabet.cc.
References Fsa::AlphabetMapping::from(), Fsa::AlphabetMapping::isModifyingType(), require, Fsa::AlphabetMapping::to(), Fsa::AlphabetMapping::type(), and Fsa::AlphabetMapping::typeIdentity.
template<class _Automaton > _Automaton::ConstRef Ftl::mapOutput (typename _Automaton::ConstRef f, Fsa::ConstAlphabetRef alphabet, u32 reportUnknowns = 10)
Maps the output alphabet of the input automaton and calculates the mapping to the target alphabet beforehand.
Category: on-demand with precalculations
Parameters
f the input automaton
alphabet the alphabet to map to
reportUnknowns maximum number of unknown symbols that should be reported
Definition at line 286 of file tAlphabet.cc.
References Fsa::mapAlphabet().
template<class _Automaton > Fsa::ConstMappingRef Ftl::mapToLeft (typename _Automaton::ConstRef f)
Mapping returning the state's id in the left original automaton.
Definition at line 568 of file tCompose.cc.
template<class _Automaton > Fsa::ConstMappingRef Ftl::mapToRight (typename _Automaton::ConstRef f)
Mapping returning the state's id in the right original automaton.
Definition at line 589 of file tCompose.cc.
template<class _Automaton > Fsa::ConstMappingRef Ftl::mapToSubAutomaton (typename _Automaton::ConstRef f, u32 subAutomaton)
Mapping returning the state's id in the respective original sub-automaton.
Definition at line 487 of file tRational.cc.
template<class _Automaton > void Ftl::memoryInfo (typename _Automaton::ConstRef f, Core::XmlWriter & o)
Report some information about an FSA automaton.
Like info(), but restricted to information that can be obtained in O(1), i.e. omits state and arc statistics. Complexity: as the full lazy cascade of automata may be traversed there is no upper bound for this function. Look at specific implementations for a more detailled analysis
Definition at line 301 of file tInfo.cc.
template<class _Automaton , class Modifier > _Automaton::ConstRef Ftl::modify (typename _Automaton::ConstRef f, const Modifier & modifier = Modifier())
Modify each weight using the given functor of type Modifier.
concept Modifier { Weight operator() (const Weight &) const; std::string describe() const; }
Category: on-demand Complexity: O(V + E)
Parameters
f the input automaton
value the weight
Returns
returns an automaton with all arc weights being multiplied by value
template<class _Automaton > _Automaton::ConstRef Ftl::nbest (typename _Automaton::ConstRef f, size_t n = 1, bool bestSequences = true)
Calculates the n best paths through a weighted automaton.
The result is an acyclic automaton where all state except the initial one have only a single successor: 0: initial state 1 .. n: start states for n-best paths So you can extract the i-th best path using partial(i). Category: on-demand with precalculations Complexity: O(sssp(determinize(remove-epsilons(f)))
Parameters
f the original automaton
n is an upper limit on the number of paths to generate. The actual number of paths in the result automaton may be smaller (if the original automaton does not contain that many paths.) The actual number of n-bests can be determined by counting the number of arcs leaving the initial state.
bestSequences set to false if you want to calculate the n-best paths instead of the n-best unique sequences, true by default
Returns
an automaton representing the n-best sequences
Definition at line 342 of file tBest.cc.
template<class _Automaton > _Automaton::ConstRef Ftl::normalize (typename _Automaton::ConstRef f)
Normalize the state ids of an automaton.
With the "destructive" algorithms, e.g. trimming, pruning, it happens that the sequence of state ids get holes. As some other algorithms allocate vectors based on state ids as index this may result in poor memory efficiency. This function removes all holes in state ids on-demand by renumbering them in the order they are requested. We found out empirically that mapping the indices on-demand is quicker and more memory efficient than using hash tables instead of vectors. Category: on-demand
Parameters
f the input automaton
Returns
returns an automaton with all state ids being normalized
Definition at line 74 of file tBasic.cc.
template<class _Automaton > _Automaton::ConstRef Ftl::partial (typename _Automaton::ConstRef f, Fsa::StateId initialStateOfPartialAutomaton)
Returns a partial automaton, i.e.
an automaton where the initial state is moved to different one. This is helpful in order to extract linear automata from n-best lists. Category: on-demand
Parameters
f input automaton
initial the id of the new initial state
Returns
returns an automaton with the new initial state
Definition at line 209 of file tBasic.cc.
template<class _Automaton > _Automaton::ConstRef Ftl::sort (typename _Automaton::ConstRef f, Fsa::SortType type)
Sorts arcs leaving a state.
Category: on-demand Complexity: average case: O(V + E' log E'), worst-case: O(V + E log E)
Parameters
f automaton
type what to sort
Returns
returns an abstract automaton with arcs begin sorted
Definition at line 169 of file tSort.cc.
References defect.
template<class _Automaton > StatePotentials< typename _Automaton::Weight > Ftl::sssp (typename _Automaton::ConstRef f, bool progress)
see Weighted Automata Algorithms, Mehryar Mohri, Handbook of weighted automata, 2009, page 10 (http://www.cs.nyu.edu/~mohri/postscript/hwa.pdf)
Definition at line 225 of file tSssp.cc.
References Core::ProgressIndicator::finish(), Core::ProgressIndicator::notify(), and Core::ProgressIndicator::start().
template<class _Automaton > Fsa::StateMap Ftl::topologicallySort (typename _Automaton::ConstRef f, bool progress = false)
Topologically sorts states of the given automaton.
As this may take some time this function displays a progress indicator on demand. Complexity: O(V + E)
Parameters
f an arbitrary automaton
progress if true displays a progress indicator on current tty
Returns
returns a structure that maps automaton state ids to topologically sorted times
Definition at line 254 of file tSort.cc.
References Ftl::DfsState< _Automaton >::dfs().
template<class _Automaton > _Automaton::ConstRef Ftl::trim (typename _Automaton::ConstRef f, bool progress = false)
Keeps only states that are both accessible and coaccessible.
Category: on-demand with precalculations Complexity: O(V + E) for the precalculations
Parameters
f input automaton
progress set to true if function should show a progress indicator on current tty
Returns
returns an automaton with non-accessible and non-coaccessible states being removed
Definition at line 167 of file tBasic.cc.
template<class _Automaton > bool Ftl::write (const Resources< _Automaton > & resources, typename _Automaton::ConstRef f, const std::string & format, std::ostream & o, Fsa::StoredComponents what, bool progress)
storage
Definition at line 36 of file tOutput.cc.