Sprint: FtlWrapper Namespace Reference
FtlWrapper Namespace Reference
Copyright 2020 RWTH Aachen University.
Functions
Flf::ConstLatticeRef best (Flf::ConstLatticeRef l)
Flf::ScoresRef bestscore (Flf::ConstLatticeRef l)
Flf::ConstLatticeRef cache (Flf::ConstLatticeRef l, u32 maxAge=10000)
Flf::ConstLatticeRef changeSemiring (Flf::ConstLatticeRef l, Flf::ConstSemiringRef semiring)
void cheapInfo (Flf::ConstLatticeRef l, Core::XmlWriter &o)
Flf::ConstLatticeRef composeMatching (Flf::ConstLatticeRef l, Flf::ConstLatticeRef r)
compose two lattices
Flf::ConstLatticeRef composeSequencing (Flf::ConstLatticeRef l, Flf::ConstLatticeRef r)
compose two lattices
Fsa::AutomatonCounts count (Flf::ConstLatticeRef l, bool progress)
size_t countInput (Flf::ConstLatticeRef l, Fsa::LabelId label, bool progress=false)
size_t countOutput (Flf::ConstLatticeRef l, Fsa::LabelId label, bool progress=false)
Flf::ConstLatticeRef determinize (Flf::ConstLatticeRef l, bool disambiguate=false)
Flf::ConstLatticeRef difference (Flf::ConstLatticeRef l, Flf::ConstLatticeRef r)
bool drawDot (Flf::ConstLatticeRef l, std::ostream &o, Fsa::Hint hint=Fsa::HintNone, bool progress=false)
visualization
bool drawDot (Flf::ConstLatticeRef l, const std::string &file, Fsa::Hint hint=Fsa::HintNone, bool progress=false)
Flf::ConstLatticeRef firstbest (Flf::ConstLatticeRef l)
Fsa::Property getProperties (Flf::ConstLatticeRef l, Fsa::Property properties=Fsa::PropertyAll)
void info (Flf::ConstLatticeRef l, Core::XmlWriter &o, bool progress=false)
Flf::ConstLatticeRef invert (Flf::ConstLatticeRef l)
bool isAcyclic (Flf::ConstLatticeRef l)
Properties.
bool isLinear (Flf::ConstLatticeRef l)
bool isEmpty (Flf::ConstLatticeRef l)
Flf::ConstLatticeRef mapInput (Flf::ConstLatticeRef l, const Fsa::AlphabetMapping &m)
Flf::ConstLatticeRef mapInputOutput (Flf::ConstLatticeRef l, const Fsa::AlphabetMapping &m)
Flf::ConstLatticeRef mapOutput (Flf::ConstLatticeRef l, const Fsa::AlphabetMapping &m)
Fsa::ConstMappingRef mapToLeft (Flf::ConstLatticeRef l)
Fsa::ConstMappingRef mapToRight (Flf::ConstLatticeRef l)
Flf::ConstLatticeRef minimize (Flf::ConstLatticeRef l)
minimization
void memoryInfo (Flf::ConstLatticeRef l, Core::XmlWriter &o)
Flf::ConstLatticeRef nbest (Flf::ConstLatticeRef l, size_t n=1, bool bestSequences=true)
Flf::ConstLatticeRef normalize (Flf::ConstLatticeRef l)
Flf::ConstLatticeRef partial (Flf::ConstLatticeRef l, Fsa::StateId initial)
Miscellaneous functions.
Flf::ConstLatticeRef projectInput (Flf::ConstLatticeRef l)
Flf::ConstLatticeRef projectOutput (Flf::ConstLatticeRef l)
Flf::ConstLatticeRef removeEpsilons (Flf::ConstLatticeRef l)
Flf::ConstLatticeRef sort (Flf::ConstLatticeRef l, Fsa::SortType type)
Flf::ConstLatticeRef trim (Flf::ConstLatticeRef l, bool progress=false)
void trimInPlace (Flf::StaticLatticeRef l)
Detailed Description
Copyright 2020 RWTH Aachen University.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Function Documentation
Flf::ConstLatticeRef FtlWrapper::composeMatching (Flf::ConstLatticeRef l, Flf::ConstLatticeRef r)
compose two lattices
Definition at line 65 of file Ftl.cc.
References composeMatching().
Referenced by Flf::composeMatching().
Flf::ConstLatticeRef FtlWrapper::composeSequencing (Flf::ConstLatticeRef l, Flf::ConstLatticeRef r)
compose two lattices
Definition at line 68 of file Ftl.cc.
References composeSequencing().
Referenced by Flf::composeSequencing(), Flf::composeWithFsa(), and Flf::intersect().
bool FtlWrapper::drawDot (Flf::ConstLatticeRef l, std::ostream & o, Fsa::Hint hint = Fsa::HintNone, bool progress = false)
visualization
Definition at line 87 of file Ftl.cc.
References drawDot(), Core::Application::us(), and Core::Component::warning().
Referenced by Aligner::WordLatticeBuilder::Converter::build(), Speech::AllophoneStateGraphBuilder::buildTransducer(), Flf::drawDot(), Speech::AllophoneStateGraphBuilder::finalizeTransducer(), Search::Aligner::getAlignmentFsa(), Search::Aligner::getAlignmentPosteriorFsa(), and FsaTool::main().
bool FtlWrapper::isAcyclic (Flf::ConstLatticeRef l)
Properties.
getProperties computes missing acyclic/linear property.
Definition at line 149 of file Ftl.cc.
References isAcyclic().
Referenced by Flf::isAcyclic().
Flf::ConstLatticeRef FtlWrapper::minimize (Flf::ConstLatticeRef l)
minimization
Definition at line 123 of file Ftl.cc.
References minimize().
Referenced by Flf::minimize().
Flf::ConstLatticeRef FtlWrapper::partial (Flf::ConstLatticeRef l, Fsa::StateId initial)
Miscellaneous functions.
Definition at line 38 of file Ftl.cc.
References partial().
Referenced by Flf::partial(), and Flf::SelectNBestNode::sendLattice().