Sprint: Lm Namespace Reference
Lm Namespace Reference
Copyright 2020 RWTH Aachen University.
Classes
class AbstractNNLanguageModel
class ArpaClassLm
class ArpaLm
ARPA backing-off language model.
class BackingOffLm
General backing-off language model.
class BlasNceSoftmaxAdapter
class CheatingSegmentLm
class ClassLm
class ClassMapping
class ClassMappingAutomaton
class ClassToken
class CombineLanguageModel
class CompiledBatchRequest
class ComposeAutomaton
class CompressedVector
class CompressedVectorFactory
class CompressionParameterEstimator
struct CompressionParameters
class ContiguousBlockInfo
class CorpusStatisticsVisitor
Corpus statistics for language model related information such as perplexity.
class DummyCompressedVectorFactory
class FFNeuralNetworkLanguageModel
class FixedQuantizationCompressedVectorFactory
class FsaLm
class History
class HistoryManager
The HistoryManager serves as a memory manger for the HistoryDescriptors used by a LanguageModel.
class IndexedString
class IndexMappedLm
class LanguageModel
Abstract language model.
class LanguageModelAutomaton
class LanguageModelScaling
Scaling of language model scores Wrapper class which multiplies the scores of an arbitrary language model object by predefined scale.
class LstmStateManager
class Module_
struct MyHash
class NceSoftmaxAdapter
class NGrams
struct NNCacheBase
struct NNCacheWithStats
class NNHistoryManager
class PassthroughSoftmaxAdapter
class QuantizedBlasNceSoftmaxAdapter
class QuantizedCompressedVectorFactory
class QuantizedCompressionParameterEstimator
struct QuantizedCompressionParameters
class QuantizedFloatVector
class QuantizedFloatVectorFixedBits
class ReducedBitsFloatVector
class ReducedPrecisionCompressedVectorFactory
class ReferenceCountingHistoryManager
HistoryManager for reference counted descriptors.
struct Request
class ScaledLanguageModel
Base class for scaled language models.
class SearchSpaceAwareLanguageModel
struct SearchSpaceInformation
class SingletonHistoryManager
class SoftmaxAdapter
class StateManager
class StaticHistoryManager
Manager for statically allocated HistoryHandles.
struct StringHash
class StringIndex
class TFRecurrentLanguageModel
struct TokenIdSequencePtrEq
struct TokenIdSequencePtrHash
class TransformerStateManager
class TransformerStateManagerWithCommonPrefix
class UncompressedVector
class WordlistInterfaceLm
Abstract bsse class for Philips- and (legacy) RWTH language model adaptors.
class Zerogram
Typedefs
typedef Core::Ref< const ClassMapping > ConstClassMappingRef
template<typename T >
using CompressedVectorPtr = std::unique_ptr< CompressedVector< T >>
using CompressionParametersPtr = std::unique_ptr< CompressionParameters >
template<typename U >
using CompressionParameterEstimatorPtr = std::unique_ptr< CompressionParameterEstimator< U >>
template<typename T >
using CompressedVectorFactoryPtr = std::unique_ptr< CompressedVectorFactory< T >>
using QuantizedFloatVector16Bits = QuantizedFloatVectorFixedBits< s16 >
using QuantizedFloatVector8Bits = QuantizedFloatVectorFixedBits< s8 >
typedef const void * HistoryHandle
Abstract Language Model State.
typedef size_t HistoryHash
using Score = f32
Language model probabilities are generally represented by the negative of their natural (!) logarithm: probability = exp(- score)
typedef const Bliss::Token * Token
typedef Bliss::TokenInventory TokenInventory
typedef std::vector< Request > BatchRequest
typedef Core::SingletonHolder< Module_ > Module
typedef std::vector< Bliss::Token::Id > TokenIdSequence
using QuantizedBlasNceSoftmaxAdapter16Bit = QuantizedBlasNceSoftmaxAdapter< s16 >
using QuantizedBlasNceSoftmaxAdapter8Bit = QuantizedBlasNceSoftmaxAdapter< s8 >
Enumerations
enum LanguageModelType {
lmTypeArpa, lmTypeArpaWithClasses, lmTypeFsa, lmTypeZerogram,
lmTypeFFNN, lmTypeCombine, lmTypeTFRNN, lmTypeCheatingSegment
}
enum StateManagerType {
LstmStateManagerType, TransformerStateManagerType, TransformerStateManager16BitType, TransformerStateManager8BitType,
TransformerStateManagerWithCommonPrefixType, TransformerStateManagerWithCommonPrefix16BitType, TransformerStateManagerWithCommonPrefix8BitType
}
enum SoftmaxAdapterType { BlasNceSoftmaxAdapterType, NceSoftmaxAdapterType, PassthroughSoftmaxAdapterType, QuantizedBlasNceSoftmaxAdapter16BitType }
Functions
Core::Ref< const ComposeAutomaton > compose (Fsa::ConstAutomatonRef left, Core::Ref< const Lm::LanguageModel > right, Score lmScale, Score syntaxEmissionScale=1.0)
Add language model scores to a Fsa automaton.
Core::Ref< const ComposeAutomaton > compose (Fsa::ConstAutomatonRef left, Core::Ref< const ScaledLanguageModel > right, Score syntaxEmissionScale)
Core::Ref< const ComposeAutomaton > composePron (Fsa::ConstAutomatonRef left, Core::Ref< const ScaledLanguageModel > right, Score pronunciationScale, Score syntaxEmissionScale)
void extendHistoryByLemma (Core::Ref< const LanguageModel > lm, const Bliss::Lemma *lemma, History &history)
Language model score convenience function for lemma pronunciations.
void extendHistoryByLemmaPronunciation (Core::Ref< const LanguageModel > lm, const Bliss::LemmaPronunciation *pronunciation, History &history)
Language model score convenience function for lemma pronunciations.
size_t token_id_sequence_hash (TokenIdSequence const &ts)
size_t token_id_sequence_ptr_eq (TokenIdSequence const *lhs, TokenIdSequence const *rhs)
__attribute__ ((optimize("unroll-loops"))) void QuantizedFloatVector
float score (const IndexedString *ngram, int len, const std::vector< NGrams > &ngrams, const StringIndex &stringIndex)
float sentenceScore (const IndexedString *sentence, int len, const std::vector< NGrams > &ngrams, const StringIndex &index, bool print=false)
void reverseArpaLm (const std::string &inName, const std::string &outName, int testSamples, std::string testFile)
void addSyntacticTokenScore (Core::Ref< const LanguageModel > lm, Score lmScale, const Bliss::SyntacticToken *st, Score syntaxEmissionScale, const History &history, Score &score)
Language model score convenience function for syntactic tokens.
void addSyntacticTokenScore (Core::Ref< const ScaledLanguageModel > lm, const Bliss::SyntacticToken *st, Score syntaxEmissionScale, const History &history, Score &score)
void addLemmaScore (Core::Ref< const LanguageModel > lm, Score lmScale, const Bliss::Lemma *lemma, Score syntaxEmissionScale, History &history, Score &score)
Language model score convenience function for lemmas.
void addLemmaScoreOmitExtension (Core::Ref< const LanguageModel > lm, Score lmScale, const Bliss::Lemma *lemma, Score syntaxEmissionScale, const History &history, Score &score)
Language model score convenience function for lemmas.
void addLemmaScore (Core::Ref< const ScaledLanguageModel > lm, const Bliss::Lemma *lemma, Score syntaxEmissionScale, History &history, Score &score)
void addLemmaScoreOmitExtension (Core::Ref< const ScaledLanguageModel > lm, const Bliss::Lemma *lemma, Score syntaxEmissionScale, const History &history, Score &score)
void addLemmaPronunciationScore (Core::Ref< const LanguageModel > lm, Score lmScale, const Bliss::LemmaPronunciation *pronunciation, Score wpScale, Score syntaxEmissionScale, History &history, Score &score)
Language model score convenience function for lemma-pronunciations.
void addLemmaPronunciationScoreOmitExtension (Core::Ref< const ScaledLanguageModel > lm, const Bliss::LemmaPronunciation *pronunciation, Score wpScale, Score syntaxEmissionScale, const History &history, Score &score)
Language model score convenience function for lemma-pronunciations.
void addLemmaPronunciationScore (Core::Ref< const ScaledLanguageModel > lm, const Bliss::LemmaPronunciation *pronunciation, Score wpScale, Score syntaxEmissionScale, History &history, Score &score)
Language model score convenience function for lemma-pronunciations.
std::unique_ptr< StateManager > createStateManager (Core::Configuration const &config)
std::unique_ptr< SoftmaxAdapter > createSoftmaxAdapter (Core::Configuration const &config)
Variables
static const Token InvalidToken = Token(0)
static const bool skipSentenceBegin = false
const Core::Choice stateManagerTypeChoice ("lstm", LstmStateManagerType,"transformer", TransformerStateManagerType,"transformer-16bit", TransformerStateManager16BitType,"transformer-8bit", TransformerStateManager8BitType,"transformer-with-common-prefix", TransformerStateManagerWithCommonPrefixType,"transformer-with-common-prefix-16bit", TransformerStateManagerWithCommonPrefix16BitType,"transformer-with-common-prefix-8bit", TransformerStateManagerWithCommonPrefix8BitType, Core::Choice::endMark())
const Core::ParameterChoice stateManagerTypeParam ("type",&stateManagerTypeChoice,"type of the state manager", LstmStateManagerType)
const Core::Choice softmaxAdapterTypeChoice ("blas_nce", BlasNceSoftmaxAdapterType,"blas-nce", BlasNceSoftmaxAdapterType,"nce", NceSoftmaxAdapterType,"passthrough", PassthroughSoftmaxAdapterType,"quantized-blas-nce-16bit", QuantizedBlasNceSoftmaxAdapter16BitType, Core::Choice::endMark())
const Core::ParameterChoice softmaxAdapterTypeParam ("type",&softmaxAdapterTypeChoice,"type of the softmax adapter", PassthroughSoftmaxAdapterType)
Detailed Description
Copyright 2020 RWTH Aachen University.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. Classes for vector compression using quantization. Quantization is done with unsigned values. No clipping of the range of values is performed, i.e. the min and max value will be restored correctly.
Typedef Documentation
typedef const void* Lm::HistoryHandle
Abstract Language Model State.
Definition at line 28 of file HistoryManager.hh.
typedef float Lm::Score
Language model probabilities are generally represented by the negative of their natural (!) logarithm: probability = exp(- score)
Definition at line 40 of file Lm/LanguageModel.hh.
Function Documentation
void Lm::addLemmaPronunciationScore (Core::Ref< const LanguageModel > lm, Score lmScale, const Bliss::LemmaPronunciation * pronunciation, Score wpScale, Score syntaxEmissionScale, History & history, Score & score) inline
Language model score convenience function for lemma-pronunciations.
Definition at line 202 of file ScaledLanguageModel.hh.
References addLemmaScore(), require, and Lm::LanguageModel::score().
Referenced by WordConditionedTreeSearch::SearchSpace::WordEndHypothesis::addLmScore(), LmComposeInternal::LemmaPronunciationComposeAutomaton::addScore(), Search::LinearSearch::feed(), Search::LinearSearch::getPartialSentence(), and Speech::LmLatticeRescorerAutomaton::score().
void Lm::addLemmaPronunciationScore (Core::Ref< const ScaledLanguageModel > lm, const Bliss::LemmaPronunciation * pronunciation, Score wpScale, Score syntaxEmissionScale, History & history, Score & score) inline
Language model score convenience function for lemma-pronunciations.
Definition at line 225 of file ScaledLanguageModel.hh.
References addLemmaScore(), require, and Lm::LanguageModel::score().
void Lm::addLemmaPronunciationScoreOmitExtension (Core::Ref< const ScaledLanguageModel > lm, const Bliss::LemmaPronunciation * pronunciation, Score wpScale, Score syntaxEmissionScale, const History & history, Score & score) inline
Language model score convenience function for lemma-pronunciations.
Definition at line 215 of file ScaledLanguageModel.hh.
References addLemmaScoreOmitExtension(), require, and Lm::LanguageModel::score().
Referenced by Search::SearchSpace::activateOrUpdateTree(), Search::Instance::addLmScore(), and Search::SearchSpace::hypothesizeEpsilonPronunciations().
void Lm::addLemmaScore (Core::Ref< const LanguageModel > lm, Score lmScale, const Bliss::Lemma * lemma, Score syntaxEmissionScale, History & history, Score & score) inline
Language model score convenience function for lemmas.
Definition at line 137 of file ScaledLanguageModel.hh.
References addSyntacticTokenScore(), Lm::LanguageModel::extendedHistory(), and require.
Referenced by addLemmaPronunciationScore(), addLemmaScoreOmitExtension(), LmComposeInternal::LemmaComposeAutomaton::addScore(), Flf::decodeRescoreLm(), Search::SearchSpace::getSentenceEnd(), and Search::SearchSpace::getSentenceEndFallBack().
void Lm::addLemmaScoreOmitExtension (Core::Ref< const LanguageModel > lm, Score lmScale, const Bliss::Lemma * lemma, Score syntaxEmissionScale, const History & history, Score & score) inline
Language model score convenience function for lemmas.
Definition at line 153 of file ScaledLanguageModel.hh.
References addLemmaScore(), addSyntacticTokenScore(), Lm::LanguageModel::extendedHistory(), require, Mc::Component::scale(), and Lm::LanguageModel::score().
Referenced by addLemmaPronunciationScoreOmitExtension().
void Lm::addSyntacticTokenScore (Core::Ref< const LanguageModel > lm, Score lmScale, const Bliss::SyntacticToken * st, Score syntaxEmissionScale, const History & history, Score & score) inline
Language model score convenience function for syntactic tokens.
Definition at line 113 of file ScaledLanguageModel.hh.
References Bliss::SyntacticToken::classEmissionScore(), Mc::Component::scale(), and Lm::LanguageModel::score().
Referenced by addLemmaScore(), and addLemmaScoreOmitExtension().
Core::Ref< const ComposeAutomaton > Lm::compose (Fsa::ConstAutomatonRef left, Core::Ref< const Lm::LanguageModel > right, Score lmScale, Score syntaxEmissionScale = 1.0)
Add language model scores to a Fsa automaton.
This is theoretically almost equivalent to using Fsa::compose() with the FSA representation of the language model obtained from getFsa(), but there are the following differences:
This function works for any LanguageModel, even if it does not implement getFsa().
Since the LanguageModel interface presents a deterministic epsilon-free automaton, this alogrithm is simpler.
No back-off paths are included. So the result is also correct if getFsa() suffers from the back-off arc shortcut phenomenon.
As a corrolary: If the (left) automaton is epsilon-free, so is the result
The alphabets of left should meet one of the following requirements: 1) The output alphabet is the lemma alphabet of the lexicon used by the language model. 2) The input alphabet of left is the lemma pronunciation alphabet of the lexicon used by the language model. In case of ties 1) is chosen.
Definition at line 255 of file Lm/Compose.cc.
References Core::ref(), require, and Mc::Component::scale().
void Lm::extendHistoryByLemma (Core::Ref< const LanguageModel > lm, const Bliss::Lemma * lemma, History & history) inline
Language model score convenience function for lemma pronunciations.
Definition at line 521 of file Lm/LanguageModel.hh.
References Lm::LanguageModel::extendedHistory(), and require.
Referenced by extendHistoryByLemmaPronunciation().
void Lm::extendHistoryByLemmaPronunciation (Core::Ref< const LanguageModel > lm, const Bliss::LemmaPronunciation * pronunciation, History & history) inline
Language model score convenience function for lemma pronunciations.
Definition at line 536 of file Lm/LanguageModel.hh.
References extendHistoryByLemma(), and require.
Referenced by Search::LinearSearch::feed(), and Search::LinearSearch::getCurrentBestSentence().