Sprint: Flf Namespace Reference
Flf Namespace Reference
Copyright 2020 RWTH Aachen University.
Namespaces
Cn
Abstract Confusion Networks; arc type is abstract.
Classes
struct Add
class AllPairsShortestDistance
class AlphabetMapNode
class AppendScoresNode
struct Arc
Lattice arc.
class ArcFilterLattice
class Archive
Archives.
class ArcRemovalLattice
class ArcRemovalNode
class ArcSortLattice
Filter: true, if arc has to be removed.
struct ArcTraceback
class ArithmeticLattice
f(x;const)
class ArithmeticNode
class BatchNode
class BestNode
class BinaryLookUp
A reduced binary map (like std::map):
class BinaryPriorityQueue
Collection of fast hash functions taken from http://www.concentric.net/~Ttwang/tech/inthash.htm.
class Boundaries
State Boundaries; collection of state boundary.
class BoundariesCopyBuilder
struct BoundariesDescriptor
class Boundary
State Boundary.
struct BoundedSegment
class CacheBuilder
class CacheNode
class CachingInPlaceStateRescorer
class CachingMapBuilder
class CenterFrameCn
class CenterFrameCnBuilder
class CenterFrameCnBuilderNode
class CenterFrameCnFactory
class ChangeSemiringNode
struct ChronologicalWeakOrder
class CleanUpNode
class CloningStateRescorer
class ClusterBuilder
class ClusteredLattice
class CnDecoderNode
struct CnFeatureConfiguration
CN features.
class CnFeatureNode
class CnFeatures
class CnGammaCorrectionNode
class CnPruningNode
struct Collector
Collect over multiple values guaranteeing numerical stability; semiring type must be tropical or log.
class CombinationHelper
struct CompareSecond
class ComposeMatchingNode
class ComposeNode
class ComposeSequencingNode
class ComposeWithFsaNode
class ComposeWithLmNode
class CompoundEvaluationTokenSplittingMap
class CompoundLemmaPronunciationSplittingMap
class CompoundLemmaSplittingMap
class CompoundSyntacticTokenSplittingMap
class CompoundWordSplittingMap
class ConcatenateFCnsNode
class ConcatenateLatticesNode
class ConcatenateNode
class ConcatenateSemiringCombination
Concatenating semiring combination.
class ConfusionNetwork
(General) Confusion Network; an arc stores basically all available information.
class ConfusionNetworkAlignment
class ConfusionNetworkArchive
class ConfusionNetworkArchiveReader
class ConfusionNetworkArchiveReaderNode
class ConfusionNetworkArchiveWriter
class ConfusionNetworkArchiveWriterNode
class ConfusionNetworkCombination
class ConfusionNetworkCombinationNode
class ConfusionNetworkFactory
struct Constant
class CopyBuilder
class CopyNode
struct CopyStateByReference
struct CopyStateByValue
class CorpusProcessor
class CostCollector
Arc e with probability p and cost c: v := c * p.
class CtmReaderNode
class DecodeRescoreLmNode
struct DeepCopyStateByValue
class DeterminizeNode
class DifferenceNode
class DiscardSemiringCombination
Discarding semiring combination.
class DrawerNode
class DummyFilterNode
class DumpAllPairsShortestDistanceNode
class DumpConfusionNetworkNode
class DumpNBestNode
class DumpPosteriorCnNode
class DumpTracebackNode
class EditDistance
class EpsilonArcFilter
class EpsilonRemovalNode
class EvaluationTokenAlphabetMap
class Evaluator
class EvaluatorNode
struct Exp
class ExpandTransitsNode
class ExtendByFramePosteriorConfidenceLattice
class ExtendByLemmaSpecificPenaltyLattice
class ExtendByLocalRiskLattice
class ExtendByPenaltyLattice
extend non-eps arcs by fixed score
class ExtendByPenaltyNode
class ExtendByPosteriorCnConfidenceNode
class ExtendByPronunciationScoreLattice
extend by pronunciation scores
class ExtendByPronunciationScoreNode
class FilterArcNode
class FilterNode
class FindTopologicalOrder
class FitLatticeNode
class FittingLattice
Fits the lattice into [begin, end]:
class FlfArchiveReader
reads lattices from an archive, the lattices must be stored in the fsa-based lattice format
class FlfArchiveWriter
writes lattices to an archive, the lattices are stored in the fsa-based lattice format
class FlfContext
struct FlfDescriptor
class FlfLatticeAdaptor
class FlfReader
reads lattices stored in the fsa-based lattice format
class FlfWriter
writes lattices using the fsa-based lattice format
struct ForwardBackwardAlignment
class FrameCnSearchSpace
class FramePosteriorCnBuilderNode
No support for pre-calculated scoers yet.
class FramePosteriorCnCombinationNode
class FramePosteriorCnFeatureLattice
class FramePosteriorCnFeatureNode
class FramePosteriorCnFeatures
class FramewiseCollector
Calculate time frame wise word posterior distribution from arc confidence score, i.e.
struct FsaDescriptor
class FsaReaderNode
class FsaToLattice
fsa to lattice
class FsaVectorLattice
struct FsaWeightToConstant
struct FsaWeightToScores
class FwdBwd
class FwdBwdBuilder
class FwdBwdBuilderNode
class FwdBwdPruner
class FwdBwdPruningLattice
class FwdBwdPruningNode
class FwdBwdScorer
struct HistoryLemmaPairHash
class HtkSlfArchiveReader
reads lattices from an archive, the lattices must be stored in HTK's standard lattice format
class HtkSlfArchiveWriter
writes lattices to an archive, the lattices are stored in HTK's standard lattice format
class HtkSlfBuilder
class HtkSlfContext
struct HtkSlfHeader
class HtkSlfReader
class HtkSlfWriter
writes lattices using HTK's standard lattice format
struct Hyp
class IncrementalRecognizer
class IncrementalRecognizerNode
class InfoNode
class InPlaceStateRescorer
struct InputFilter
struct InputStream
Convinient wrapper, read from archive, if given read from file system, else.
class IntersectionNode
class InvalidBoundaries_
class IoFlag
i/o flags
class IoFormat
i/o formats
class LabelMap
class LabelMapNode
class LabelMapper
class Lattice
Lattice.
class LatticeAlignment
class LatticeAlignmentBuilder
class LatticeArchive
class LatticeArchiveReader
class LatticeArchiveReaderNode
class LatticeArchiveWriter
class LatticeArchiveWriterNode
class LatticeBufferNode
struct LatticeClosure
class LatticeHandler
class LatticeIo
class LatticeProcessorArchiveWriter
deprecated
class LatticeReader
class LatticeReaderNode
class LatticeWriter
class LatticeWriterNode
class LayeredComponent
class LayerEndNode
class LayerStartNode
class LemmaAlphabetMap
class LemmaPronunciationAlphabetMap
class LemmaPronunciationToWordVariant
class LemmaToWordVariant
class Lexicon
struct LinearCombination
class LmComposeLattice
compose with lm
class LocalCostDecoder
class LocalCostDecoderBuilder
class LocalCostDecoderNode
struct Log
struct LogCollector
class LogSemiring
Log semiring.
class MapInputFromLemmaPronunciationToLemmaLattice
The following mappings guarantee mapping success, i.e.
class MapInputFromLemmaToSingleLemmaPronunciationLattice
class MapOutputFromLemmaPronunciationToLemmaLattice
class MapOutputFromLemmaToSingleLemmaPronunciationLattice
class MappedBoundaries
class MappingBuilder
struct MeshEntry
class MeshNode
class MeshSearchSpace
min.
class MinimizeNode
class MinimumFrameWerDecoder
class MinimumFrameWerDecoderNode
class Module_
struct Multiply
class NBestBuilder
class NBestNode
class Network
class NetworkCrawler
class NetworkParser
Parse a config file defining a network and store the resulting nodes in topological order (if acyclic).
class Node
struct NodeCreator
class NodeFactory
Class to register node creator and creates node from given name and node config.
class NonLemmaPronunciationToEpsilonMap
class NonLemmaToEpsilonMap
class NonWordClosureFilterNode
class NonWordClosureNormalizationFilterNode
class NonWordClosureRemovalFilterNode
class NonWordClosureStrongDeterminizationFilterNode
class NonWordClosureWeakDeterminizationFilterNode
class NonWordToEpsilonMap
class NormalizedCnGammaCorrectionNode
class NormalizedCnPruningNode
class NormalizeEpsilonClosureLattice
class NullArcFilter
class NullArcsRemovalNode
class OneToOneLabelMappingLattice
class OracleAlignment
class OracleAlignmentNode
struct OutputFilter
struct OutputStream
Convinient wrapper, write to archive, if given write to file system, else.
class PenaltyMap
class PhoneCoveragePruningLattice
class PhonemeAlphabetMap
class PivotArcCn
class PivotArcCnBuilder
class PivotArcCnBuilderNode
class PivotArcCnFactory
class PosteriorCn
Posterior Probability Confusion Network; an arc stores only the label and the posterior probability of the label.
class PosteriorCnArchive
class PosteriorCnArchiveReader
class PosteriorCnArchiveReaderNode
class PosteriorCnArchiveWriter
class PosteriorCnArchiveWriterNode
class PosteriorCnGammaCorrectionNode
class PosteriorCnPruningNode
class PrecalculatedArcScores
class Processor
Base class of a network processor.
struct Projection
class ProjectSemiringLattice
class ProjectSemiringNode
class PropertiesNode
class PushForwardRescorer
class PushForwardRescoringNode
class ReaderNode
class Recognizer
class RecognizerNode
class RecordingSegmentation
class RecordingSegmentationSet
class ReduceScoresLattice
reduce many scores to a single score; the sum of the scalar product remains unchanged
class ReduceScoresNode
class ReplaceSingleDimensionLattice
class RescaleNode
class RescoreLattice
Rescore lattice; specialisation of modify lattice, structure preserving flf-to-flf.
class RescoreNode
Abstract rescore node.
class RescoreSingleDimensionNode
Abstract single dimension rescore node.
class ReverseTopologicalOrderQueue
class RoverCombination
class RoverCombinationNode
class ScoreAppendLattice
class Scores
class ScoresRef
class Segment
class SegmentBuilderNode
class SegmentwiseFeatureExtractor
Adpat feature extraction on segment.
class SegmentwiseModelAdaptor
Adpat basic models on segment.
class SegmentwiseSpeechProcessor
1) adapt feature extraction and models on segment 2) process all features in segment, verify consistence with acoustic model -> call processFeature for each extracted feature
class SelectNBestNode
class Semiring
class SemiringCombinationHelper
class Sink
class SortInTopologicalOrder
class SpeechSegmentNode
struct StandardHash
struct StateBoundary
class StateBoundaryList
class StateClusterCnBuilderNode
struct StateIdPair
class StateMap
Mapping from (or to) state id to (or from) state id; the direction is task dependent.
class StaticBoundaries
class StaticLabelMap
class StaticScoreLattice
class StringConverterNode
string to lattice
class SymbolicMapping
class SyntacticTokenAlphabetMap
class TextFileParser
Parse Textfile line by line and split at (sequences of) white spaces into columns; empty lines and lines containing a comment only are discarded.
class TimeAlignmentBuilder
class TimeAlignmentNode
class TimeframeError
class TimeframeErrorNode
class ToLowerCaseMap
class TopologicalOrderBuilder
class TopologicalOrderLattice
class TopologicalOrderQueue
class TransducerLattice
class TraverseState
Traverse a lattice.
struct TropicalCollector
class TropicalSemiring
Tropical semiring.
class UnionBoundaries
class UnionLattice
class UnionNode
class UnionSearchSpace
min.
class UniqueSentenceAlignmentFilterNode
class UnknownAlphabet
class UnknownAlphabetMap
class UnweightLattice
struct WeakReverseTopologicalOrder
Priority queue for states using the reverse topological state order.
struct WeakTopologicalOrder
Priority queue for states using the topological order for states.
struct WordEndHypothesis
class WordListExtractorNode
struct WordTraceback
class WriterNode
Typedefs
typedef Core::Ref< const AllPairsShortestDistance > ConstAllPairsShortestDistanceRef
typedef Core::Ref< const StateBoundaryList > ConstStateBoundaryListRef
typedef s32 Id
typedef std::vector< Id > IdList
typedef std::vector< Time > FrameList
typedef Core::Ref< const CenterFrameCn > ConstCenterFrameCnRef
typedef Core::Ref< CenterFrameCnBuilder > CenterFrameCnBuilderRef
typedef Core::Ref< SemiringCombinationHelper > SemiringCombinationHelperRef
typedef Core::Ref< CombinationHelper > CombinationHelperRef
typedef Core::Ref< RecordingSegmentation > RecordingSegmentationRef
typedef std::vector< BoundedSegment > BoundedSegmentList
typedef Core::Ref< CnFeatures > CnFeaturesRef
typedef Core::Ref< ConfusionNetworkFactory > ConfusionNetworkFactoryRef
typedef std::vector< ConfusionNetworkAlignment * > ConfusionNetworkAlignmentPtrList
typedef Core::Ref< const ConfusionNetworkCombination > ConstConfusionNetworkCombinationRef
typedef Core::Ref< const RoverCombination > ConstRoverCombinationRef
typedef Core::Ref< const OracleAlignment > ConstOracleAlignmentRef
typedef std::vector< ScoreList > ProjectionMatrix
typedef Core::Ref< const Boundaries > ConstBoundariesRef
typedef Core::Vector< ConstBoundariesRef > ConstBoundariesRefList
typedef Core::Ref< StaticBoundaries > StaticBoundariesRef
typedef Ftl::State< Arc > State
Lattice state.
typedef State::Ref StateRef
typedef Core::Vector< StateRef > StateRefList
typedef State::ConstRef ConstStateRef
typedef Core::Vector< ConstStateRef > ConstStateRefList
typedef Core::Vector< Fsa::StateId > StateIdList
typedef Core::Ref< StateMap > StateMapRef
typedef Core::Ref< const StateMap > ConstStateMapRef
typedef Lattice::ConstRef ConstLatticeRef
typedef Core::Vector< ConstLatticeRef > ConstLatticeRefList
typedef Ftl::StaticAutomaton< Lattice > StaticLattice
typedef Core::Ref< StaticLattice > StaticLatticeRef
typedef Core::Vector< ConfusionNetwork > ConfusionNetworkList
typedef Core::Ref< ConfusionNetwork > ConfusionNetworkRef
typedef Core::Vector< ConfusionNetworkRef > ConfusionNetworkRefList
typedef Core::Ref< const ConfusionNetwork > ConstConfusionNetworkRef
typedef Core::Vector< ConstConfusionNetworkRef > ConstConfusionNetworkRefList
typedef Core::Vector< PosteriorCn > PosteriorCnList
typedef Core::Ref< PosteriorCn > PosteriorCnRef
typedef Core::Vector< PosteriorCnRef > PosteriorCnRefList
typedef Core::Ref< const PosteriorCn > ConstPosteriorCnRef
typedef Core::Vector< ConstPosteriorCnRef > ConstPosteriorCnRefList
typedef Ftl::WrapperAutomaton< Fsa::Automaton, Lattice > FsaToFlfWrapperLattice
Wrapper lattice/automaton; generic fsa-to-flf and flf-to-fsa.
typedef Ftl::WrapperAutomaton< Lattice, Lattice > FlfToFlfWrapperLattice
typedef Ftl::SlaveAutomaton< Lattice > SlaveLattice
Slave lattice; specialisation of wrapper lattice, generic flf-to-flf.
typedef Ftl::ModifyAutomaton< Lattice > ModifyLattice
Modify lattice; specialisation of slave lattice, structure preserving flf-to-flf.
typedef std::string Key
typedef std::vector< Key > KeyList
typedef Core::Ref< const Semiring > ConstSemiringRef
typedef Core::Vector< ConstSemiringRef > ConstSemiringRefList
typedef Core::Ref< TopologicalOrderQueue > TopologicalOrderQueueRef
typedef Core::Ref< ReverseTopologicalOrderQueue > ReverseTopologicalOrderQueueRef
typedef Ftl::DfsState< Lattice > DfsState
Traverse lattice using dfs, see Fsa/tDfs.hh.
typedef Speech::TimeframeIndex Time
typedef Fsa::Property Property
Extensions for FSA properties.
typedef Fsa::Hint Hint
Extensions for FSA hints.
typedef Core::Vector< u8 > ByteVector
typedef std::vector< Fsa::LabelId > LabelIdList
typedef Fsa::SemiringType SemiringType
Semiring type.
typedef f32 Score
typedef Core::Vector< Score > ScoreList
typedef size_t ScoreId
typedef Core::Vector< ScoreId > ScoreIdList
typedef f64 Probability
typedef Core::Vector< Probability > ProbabilityList
typedef std::vector< FsaDescriptor > FsaDescriptorList
typedef Core::Ref< FlfDescriptor > FlfDescriptorRef
typedef Core::Ref< FlfContext > FlfContextRef
typedef Core::Ref< FwdBwd > FwdBwdRef
typedef Core::Ref< const FwdBwd > ConstFwdBwdRef
typedef Core::Ref< FwdBwdBuilder > FwdBwdBuilderRef
typedef Core::Ref< HtkSlfContext > HtkSlfContextRef
typedef Fsa::AutomatonCounts LatticeCounts
typedef Core::Ref< const Lm::LanguageModel > ConstLanguageModelRef
typedef Fsa::Hash< Lm::History, Lm::History::Hash > HistoryHashList
typedef Core::Vector< HistoryHashList > HistoriesList
typedef Core::Ref< const Lm::ScaledLanguageModel > ConstScaledLanguageModelRef
typedef Bliss::Lemma Lemma
typedef Bliss::LemmaPronunciation LemmaPronunciation
typedef Bliss::Lemma::LemmaPronunciationRange LemmaPronunciationRange
typedef Core::Ref< Lexicon > LexiconRef
typedef Core::Ref< EditDistance > ConstEditDistanceRef
typedef Core::Ref< const LocalCostDecoder > ConstLocalCostDecoderRef
typedef Core::Ref< const LocalCostDecoderBuilder > ConstLocalCostDecoderBuilderRef
typedef Core::Ref< LabelMap > LabelMapRef
typedef Core::Vector< LabelMapRef > LabelMapList
typedef Core::SingletonHolder< Module_ > Module
typedef Core::Ref< NetworkCrawler > NetworkCrawlerRef
typedef Core::Ref< Node > NodeRef
typedef NodeRef(* NodeCreatorFcn) (const std::string &name, const Core::Configuration &config)
Function producing a node.
typedef Core::Vector< Hyp > HypList
typedef Core::Ref< const PivotArcCn > ConstPivotArcCnRef
typedef Core::Ref< const PivotArcCnBuilder > ConstPivotArcCnBuilderRef
typedef Core::Ref< FwdBwdPruner > FwdBwdPrunerRef
typedef std::vector< std::string > StringList
extend by lemma specific penalty
typedef std::vector< StringList > StringListList
typedef Core::Ref< PenaltyMap > PenaltyMapRef
typedef Core::Ref< Segment > SegmentRef
typedef Core::Ref< const Segment > ConstSegmentRef
typedef Core::Ref< Am::AcousticModel > AcousticModelRef
Segmentwise model adaptation and feature extraction.
typedef Core::Ref< Lm::LanguageModel > LanguageModelRef
typedef Core::Ref< Lm::ScaledLanguageModel > ScaledLanguageModelRef
typedef Core::Ref< Speech::ModelCombination > ModelCombinationRef
typedef Core::Ref< SegmentwiseModelAdaptor > SegmentwiseModelAdaptorRef
typedef Core::Ref< Speech::DataSource > DataSourceRef
Feature extraction.
typedef Core::Ref< Speech::Feature > FeatureRef
typedef std::vector< FeatureRef > FeatureList
typedef Core::Ref< SegmentwiseFeatureExtractor > SegmentwiseFeatureExtractorRef
typedef Core::Ref< ClusteredLattice > ClusteredLatticeRef
typedef Core::Ref< ClusterBuilder > ClusterBuilderRef
typedef Core::Ref< TimeAlignmentBuilder > TimeAlignmentBuilderRef
typedef Core::Ref< FramePosteriorCnFeatures > FramePosteriorCnFeaturesRef
typedef std::vector< ScoreList > WeightsList
typedef Core::Ref< TimeframeError > TimeframeErrorRef
typedef Core::Ref< LatticeAlignmentBuilder > LatticeAlignmentBuilderRef
typedef Core::Ref< const LatticeAlignment > ConstLatticeAlignmentRef
Enumerations
enum SingleSourceShortestPathAlgorithm { Dijkstra, BellmanFord, ProjectingBellmanFord }
Dijkstra:
enum RescoreMode { RescoreModeClone = 0, RescoreModeInPlaceCache = 1, RescoreModeInPlace = 2 }
Rescore mode.
enum InfoType { InfoTypeCheap = 0, InfoTypeNormal = 1, InfoTypeExtended = 2, InfoTypeMemory = 3 }
Info type.
enum HtkSlfType { HtkSlfForward, HtkSlfBackward }
enum AlphabetMappingAction {
UndefinedAlphabetMapping, MapToPhoneme, MapToLemmaPronunciation, MapToPreferredLemmaPronunciation,
MapToLemma, MapToSyntacticTokenSequence, MapToEvaluationTokenSequences, MapToPreferredEvaluationTokenSequence
}
Map alphabets.
enum NBestAlgorithm { Eppstein, Mori }
enum MeshType { MeshTypeFullBoundary, MeshTypeTimeBoundary }
time or boundary conditioned lattice; join either all states having identical boundaries(boundary information includes time) or having identical time
Functions
NodeRef createLatticeArchiveReaderNode (const std::string &name, const Core::Configuration &config)
NodeRef createLatticeArchiveWriterNode (const std::string &name, const Core::Configuration &config)
NodeRef createConfusionNetworkArchiveReaderNode (const std::string &name, const Core::Configuration &config)
NodeRef createConfusionNetworkArchiveWriterNode (const std::string &name, const Core::Configuration &config)
NodeRef createPosteriorCnArchiveReaderNode (const std::string &name, const Core::Configuration &config)
NodeRef createPosteriorCnArchiveWriterNode (const std::string &name, const Core::Configuration &config)
std::pair< ConstLatticeRef, Score > bestProjection (ConstLatticeRef l)
void dumpBest (ConstLatticeRef l, std::ostream &os)
ConstLatticeRef best (ConstLatticeRef l, SingleSourceShortestPathAlgorithm algo)
NodeRef createBestNode (const std::string &name, const Core::Configuration &config)
NodeRef createDumpAllPairsShortestDistanceNode (const std::string &name, const Core::Configuration &config)
Format:
from to score
<from-id> <to-id> <score> ...
ConstStateBoundaryListRef cacheLattice (ConstLatticeRef l)
Cache complete lattice; allows fast state/boundary lookup; similar to copy by reference.
ConstLatticeRef cache (ConstLatticeRef l, u32 maxAge)
NodeRef createCacheNode (const std::string &name, const Core::Configuration &config)
NodeRef createCenterFrameCnBuilderNode (const std::string &name, const Core::Configuration &config)
ConstLatticeRef unweight (ConstLatticeRef l, ConstSemiringRef semiring=ConstSemiringRef())
ConstLatticeRef unifySemirings (ConstLatticeRef l, ConstLatticeRef r)
void composeBoundaries (ConstLatticeRef composition, ConstLatticeRef l, ConstLatticeRef r)
ConstLatticeRef composeMatching (ConstLatticeRef l, ConstLatticeRef r)
compose two lattices
NodeRef createComposeMatchingNode (const std::string &name, const Core::Configuration &config)
ConstLatticeRef composeSequencing (ConstLatticeRef l, ConstLatticeRef r)
compose two lattices
NodeRef createComposeSequencingNode (const std::string &name, const Core::Configuration &config)
ConstLatticeRef differ (ConstLatticeRef l, ConstLatticeRef r)
build difference of two lattices
NodeRef createDifferenceNode (const std::string &name, const Core::Configuration &config)
ConstLatticeRef intersect (ConstLatticeRef l, ConstLatticeRef r, bool appendScores)
intersect two lattices
NodeRef createIntersectionNode (const std::string &name, const Core::Configuration &config)
ConstLatticeRef composeWithFsa (ConstLatticeRef l, Fsa::ConstAutomatonRef f, Score scale)
compose with fsa
ConstLatticeRef composeWithFsa (ConstLatticeRef l, Fsa::ConstAutomatonRef f, ScoreId id, Score scale)
NodeRef createComposeWithFsaNode (const std::string &name, const Core::Configuration &config)
BoundedSegmentList buildBoundedSegments (const RecordingSegmentation &recSeg)
Distribute recording time over segments: In case of overlaps, the begining of the next next segment is cut.
void dumpBoundedSegments (std::ostream &os, const BoundedSegmentList &boundedSegs)
NodeRef createConcatenateLatticesNode (const std::string &name, const Core::Configuration &config)
NodeRef createConcatenateFCnsNode (const std::string &name, const Core::Configuration &config)
ConstConfusionNetworkRef sausageLattice2cn (ConstLatticeRef l, bool keepEpsArcs=true)
Build a confusion network from a lattice with "sausage" topology.
ConstLatticeRef cn2lattice (ConstConfusionNetworkRef cn, bool approximateBoundaryTimes=false)
Convert a CN into a lattice with "sausage" topology.
ConstConfusionNetworkRef normalizeCn (ConstConfusionNetworkRef cn, ScoreId posterirorId)
Normalizes an arbitrary CN.
bool isNormalizeCn (ConstConfusionNetworkRef cn, ScoreId posteriorId)
ConstLatticeRef decodeCn (ConstConfusionNetworkRef cn, ScoreId posterirorId=Semiring::InvalidId)
Decodes a normalized CN; if the CN is not normalized, a valid posteriroId is required and the CN is normalized beforehand.
NodeRef createCnDecoderNode (const std::string &name, const Core::Configuration &config)
ConstLatticeRef composeAndAddCnFeatures (ConstLatticeRef l, const CnFeatures &cnFeatures)
ConstLatticeRef composeAndAddCnFeatures (ConstLatticeRef l, const CnFeatureConfiguration &cnConfig)
Add CN features to lattice Optionally, perform the "composition" of the lattice and the CN derived from the lattice: each path in the resulting lattice has the same length.
NodeRef createCnFeatureNode (const std::string &name, const Core::Configuration &config)
NodeRef createConfusionNetworkCombinationNode (const std::string &name, const Core::Configuration &config)
NodeRef createRoverCombinationNode (const std::string &name, const Core::Configuration &config)
NodeRef createOracleAlignmentNode (const std::string &name, const Core::Configuration &config)
void writeConfusionNetworkAsText (std::ostream &os, ConstConfusionNetworkRef cn, ConstSegmentRef segment)
Ouput.
ConstConfusionNetworkRef readConfusionNetworkFromXml (std::istream &is, ConfusionNetworkRef cn=ConfusionNetworkRef())
Input.
void writeConfusionNetworkAsXml (Core::XmlWriter &xml, ConstConfusionNetworkRef cn, ConstSegmentRef segment, u32 ioFlag)
NodeRef createDumpConfusionNetworkNode (const std::string &name, const Core::Configuration &config)
ConstLatticeRef offsetSemiring (ConstLatticeRef l, ConstSemiringRef targetSemiring, ScoreId offset=0)
dim i -> dim+offest
NodeRef createChangeSemiringNode (const std::string &name, const Core::Configuration &config)
change semiring (and set)
NodeRef createProjectSemiringNode (const std::string &name, const Core::Configuration &config)
project source semiring to target semiring
ConstLatticeRef fromFsa (Fsa::ConstAutomatonRef f, ConstSemiringRef semiring, ScoresRef defaultScore, ScoreId id, Lexicon::AlphabetId inputAlphabetId, Lexicon::AlphabetId outputAlphabetId=Lexicon::UnknownAlphabetId)
from fsa to flf, incl.
ConstLatticeRef fromUnweightedFsa (Fsa::ConstAutomatonRef fsa, ConstSemiringRef semiring, ScoresRef constScore, Lexicon::AlphabetId inputAlphabetId, Lexicon::AlphabetId outputAlphabetId)
NodeRef createStringConverterNode (const std::string &name, const Core::Configuration &config)
string to lattice
ConstLatticeRef normalizeSemiring (ConstLatticeRef l, bool normalizeNames=true)
normalize semiring: apply scales to scores, set scales and keys to defaults (i.e.
template<class CopyState >
std::pair< bool, bool > copy_ (ConstLatticeRef l, StaticLattice *staticLattice, StaticBoundaries *staticBoundaries)
template<class CopyState >
ConstLatticeRef copy_ (ConstLatticeRef l)
std::pair< bool, bool > persistent (ConstLatticeRef l, StaticLattice *staticLattice, StaticBoundaries *staticBoundaries)
Behaviour of copy and deepCopy:
std::pair< bool, bool > copy (ConstLatticeRef l, StaticLattice *staticLattice, StaticBoundaries *staticBoundaries)
std::pair< bool, bool > deepCopy (ConstLatticeRef l, StaticLattice *staticLattice, StaticBoundaries *staticBoundaries)
ConstLatticeRef persistent (ConstLatticeRef l)
ConstLatticeRef copy (ConstLatticeRef l)
ConstLatticeRef deepCopy (ConstLatticeRef l)
template<class CopyState >
std::pair< bool, bool > normalizeCopy_ (ConstLatticeRef l, StaticLattice *staticLattice, StaticBoundaries *staticBoundaries)
template<class CopyState >
ConstLatticeRef normalizeCopy_ (ConstLatticeRef l)
std::pair< bool, bool > normalizeCopy (ConstLatticeRef l, StaticLattice *staticLattice, StaticBoundaries *staticBoundaries)
Normalize state numbering, Copy, copy states, but no weights Deep Copy, copy states and weights.
std::pair< bool, bool > normalizeDeepCopy (ConstLatticeRef l, StaticLattice *staticLattice, StaticBoundaries *staticBoundaries)
ConstLatticeRef normalizeCopy (ConstLatticeRef l)
ConstLatticeRef normalizeDeepCopy (ConstLatticeRef l)
bool copyBoundaries (ConstLatticeRef l, StaticBoundaries *staticBoundaries)
Behaviour of copyBoundaries:
ConstLatticeRef copyBoundaries (ConstLatticeRef l)
NodeRef createCopyNode (const std::string &name, const Core::Configuration &config)
NodeRef createSpeechSegmentNode (const std::string &name, const Core::Configuration &config)
ConstLatticeRef determinize (ConstLatticeRef l)
determinization
NodeRef createDeterminizeNode (const std::string &name, const Core::Configuration &config)
ConstLatticeRef minimize (ConstLatticeRef l)
minimization
NodeRef createMinimizeNode (const std::string &name, const Core::Configuration &config)
bool drawDot (ConstLatticeRef l, std::ostream &o, Fsa::Hint hint, bool progress)
visualization
bool drawDot (ConstLatticeRef l, const std::string &file, Fsa::Hint hint, bool progress)
ConstLatticeRef fastRemoveEpsilons (ConstLatticeRef l)
ConstLatticeRef removeEpsilons (ConstLatticeRef l)
NodeRef createEpsilonRemovalNode (const std::string &name, const Core::Configuration &config)
ConstLatticeRef fastRemoveNullArcs (ConstLatticeRef l)
NodeRef createNullArcsRemovalNode (const std::string &name, const Core::Configuration &config)
void evaluate (ConstLatticeRef l, const std::string &ref)
NodeRef createEvaluatorNode (const std::string &name, const Core::Configuration &config)
ConstLatticeRef filterByInput (ConstLatticeRef l, Fsa::LabelId input)
ConstLatticeRef filterByInput (ConstLatticeRef l, const std::string &label)
ConstLatticeRef filterByOutput (ConstLatticeRef l, Fsa::LabelId output)
ConstLatticeRef filterByOutput (ConstLatticeRef l, const std::string &label)
NodeRef createFilterArcNode (const std::string &name, const Core::Configuration &config)
ConstLatticeRef changeSemiring (ConstLatticeRef l, ConstSemiringRef targetSemiring)
ConstLatticeRef rescale (ConstLatticeRef l, const ScoreList &scales, const KeyList &keys=KeyList())
Replace semiring.
ConstLatticeRef rescale (ConstLatticeRef l, ScoreId id, Score scale, const Key &key)
ConstLatticeRef projectSemiring (ConstLatticeRef l, ConstSemiringRef targetSemiring, const ProjectionMatrix &mapping)
ConstLatticeRef fromFsa (Fsa::ConstAutomatonRef f, ConstSemiringRef semiring, ScoreId id, ScoresRef defaultScore=ScoresRef())
Fsa to Flf.
ConstLatticeRef fromFsaVector (const std::vector< Fsa::ConstAutomatonRef > &fsas, ConstSemiringRef semiring)
ConstLatticeRef fromUnweightedFsa (Fsa::ConstAutomatonRef f, ConstSemiringRef semiring, ScoresRef defaultScore)
Fsa::ConstAutomatonRef toFsa (ConstLatticeRef l, const ScoreList &scales=ScoreList())
Flf to Fsa.
Fsa::ConstAutomatonRef toFsa (ConstLatticeRef l, ScoreId id, bool scaled)
std::vector< Fsa::ConstAutomatonRef > toFsaVector (ConstLatticeRef l, bool scaled)
Fsa::ConstAutomatonRef toUnweightedFsa (ConstLatticeRef l, const Fsa::Weight &constWeight)
ConstStateMapRef sortTopologically (ConstLatticeRef l)
Topological/Chronological Order.
ConstStateMapRef findTopologicalOrder (ConstLatticeRef l)
ConstStateMapRef sortChronologically (ConstLatticeRef l)
ConstLatticeRef sortByTopologicalOrder (ConstLatticeRef l)
The states of the resulting lattice are enumerated by increasing topological order, i.e.
bool isAcyclic (ConstLatticeRef l)
Properties.
ConstLatticeRef partial (ConstLatticeRef l, Fsa::StateId initial)
Miscellaneous functions.
ConstLatticeRef sort (ConstLatticeRef l, Fsa::SortType type)
ConstLatticeRef trim (ConstLatticeRef l, bool progress)
void trimInPlace (StaticLatticeRef l)
ConstLatticeRef appendScores (ConstLatticeRef l1, ConstLatticeRef l2, ConstSemiringRef semiring=ConstSemiringRef())
Append.
State * clone (const Semiring &semiring, ConstStateRef sr)
void incScoresRefCounter ()
void decScoresRefCounter ()
u32 nScoresRef ()
ConstSemiringRef cloneSemiring (ConstSemiringRef semiring)
Manipulate semirings; the original semiring is not modified.
ConstSemiringRef appendSemiring (ConstSemiringRef sr1, Score scale, const Key &key)
ConstSemiringRef appendSemiring (ConstSemiringRef sr1, ConstSemiringRef sr2)
ConstSemiringRef rescaleSemiring (ConstSemiringRef semiring, const ScoreList &scales, const KeyList &keys)
ConstSemiringRef rescaleSemiring (ConstSemiringRef semiring, ScoreId id, Score scale, const Key &key)
ConstSemiringRef toLogSemiring (ConstSemiringRef semiring, Score scale)
ConstSemiringRef toTropicalSemiring (ConstSemiringRef semiring)
TopologicalOrderQueueRef createTopologicalOrderQueue (ConstLatticeRef l, ConstStateMapRef topologicalOrder)
ReverseTopologicalOrderQueueRef createReverseTopologicalOrderQueue (ConstLatticeRef l, ConstStateMapRef topologicalOrder)
SemiringType getSemiringType (const std::string &s)
std::string getSemiringTypeName (SemiringType type)
RescoreMode getRescoreMode (const std::string &s)
const std::string & getRescoreModeName (RescoreMode mode)
InfoType getInfoType (const std::string &s)
const std::string & getInfoTypeName (InfoType type)
Collector * createCollector (Fsa::SemiringType semiringType)
Score add (Score a, Score b)
Score logAdd (Score a, Score b)
NodeRef createLayerStartNode (const std::string &name, const Core::Configuration &config)
NodeRef createLayerEndNode (const std::string &name, const Core::Configuration &config)
NodeRef createFwdBwdBuilderNode (const std::string &name, const Core::Configuration &config)
void gammaCorrection (ConstConfusionNetworkRef cnRef, f64 gamma, bool normalize)
void gammaCorrection (ConstPosteriorCnRef cnRef, f64 gamma, bool normalize)
NodeRef createNormalizedCnGammaCorrectionNode (const std::string &name, const Core::Configuration &config)
NodeRef createPosteriorCnGammaCorrectionNode (const std::string &name, const Core::Configuration &config)
NodeRef createIncrementalRecognizerNode (const std::string &name, const Core::Configuration &config)
bool isEmpty (ConstLatticeRef l)
LatticeCounts count (ConstLatticeRef l, bool progress)
size_t countInput (ConstLatticeRef l, Fsa::LabelId label, bool progress)
size_t countOutput (ConstLatticeRef l, Fsa::LabelId label, bool progress)
void cheapInfo (ConstLatticeRef l, Core::XmlWriter &o)
void normalInfo (ConstLatticeRef l, Core::XmlWriter &o)
void extendedInfo (ConstLatticeRef l, Core::XmlWriter &o, LatticeStatistics &stats, BestStatistics &bestStats)
void extendedInfo (ConstLatticeRef l, Core::XmlWriter &o)
void memoryInfo (ConstLatticeRef l, Core::XmlWriter &o)
void info (ConstLatticeRef l, Core::XmlWriter &o, InfoType infoType)
NodeRef createInfoNode (const std::string &name, const Core::Configuration &config)
std::pair< std::string, bool > stripExtension (const std::string &filename)
1) Removes .gz, if existent 2) Removes the last dot-seperated suffix, if existent Returns stripped filename and true if ending .gz was detected (and removed)
bool readBinary (StaticBoundaries *b, std::istream &is)
bool readBoundariesBinary (ConstLatticeRef l, std::istream &is)
boundaries i/o
bool writeBinary (const StaticBoundaries *b, std::ostream &os)
bool writeBoundariesBinary (ConstLatticeRef l, std::ostream &os)
NodeRef createLatticeReaderNode (const std::string &name, const Core::Configuration &config)
NodeRef createFsaReaderNode (const std::string &name, const Core::Configuration &config)
fsa i/ -> use lattice/flf-format for writing fsas
NodeRef createCtmReaderNode (const std::string &name, const Core::Configuration &config)
ctm i/ -> use dump-traceback node for writing ctms
NodeRef createLatticeWriterNode (const std::string &name, const Core::Configuration &config)
NodeRef createDrawerNode (const std::string &name, const Core::Configuration &config)
dot /o
ConstLatticeRef composeWithLm (ConstLatticeRef l, ConstLanguageModelRef lm, ScoreId id, Score scale=Semiring::DefaultScale, bool forceSentenceEnd=false)
composition of lattice and lm
NodeRef createComposeWithLmNode (const std::string &name, const Core::Configuration &config)
NodeRef createWordListExtractorNode (const std::string &name, const Core::Configuration &config)
Extract vocab out of all seen lattices.
NodeRef createLocalCostDecoderNode (const std::string &name, const Core::Configuration &config)
ConstLatticeRef transducer (ConstLatticeRef l)
Switch between acceptor and transducer.
ConstLatticeRef projectInput (ConstLatticeRef l)
ConstLatticeRef projectOutput (ConstLatticeRef l)
ConstLatticeRef invert (ConstLatticeRef l)
AlphabetMappingAction getAlphabetMappingAction (const std::string &name)
const std::string & getAlphabetMappingActionName (AlphabetMappingAction action)
ConstLatticeRef mapInput (Fsa::ConstAutomatonRef f, ConstLatticeRef l)
ConstLatticeRef mapOutput (ConstLatticeRef l, Fsa::ConstAutomatonRef f)
ConstLatticeRef mapInput (ConstLatticeRef l, Lexicon::AlphabetId alphabetId)
ConstLatticeRef mapOutput (ConstLatticeRef l, Lexicon::AlphabetId alphabetId)
ConstLatticeRef mapInput (ConstLatticeRef l, AlphabetMappingAction action)
ConstLatticeRef mapOutput (ConstLatticeRef l, AlphabetMappingAction action)
ConstLatticeRef mapInputToLemmaOrLemmaPronunciation (ConstLatticeRef l)
ConstLatticeRef mapOutputToLemmaOrLemmaPronunciation (ConstLatticeRef l)
NodeRef createAlphabetMapNode (const std::string &name, const Core::Configuration &config)
ConstLatticeRef applyOneToOneLabelMap (ConstLatticeRef l, LabelMapRef labelMap)
ConstLatticeRef applyLabelMap (ConstLatticeRef l, LabelMapRef labelMap)
NodeRef createLabelMapNode (const std::string &name, const Core::Configuration &config)
ConstLatticeRef fit (ConstLatticeRef l, bool forceSentenceEndLabels=false)
Fits the lattice into [begin, end]:
ConstLatticeRef fit (ConstLatticeRef l, s32 startTime, s32 endTime, bool forceSentenceEndLabels)
NodeRef createFitLatticeNode (const std::string &name, const Core::Configuration &config)
bool isValidTarget (Fsa::StateId sid)
bool isValidLabel (Fsa::ConstAlphabetRef alphabet, Fsa::LabelId label)
bool isFinite (ConstSemiringRef semiring, ScoresRef scores)
StaticLatticeRef cleanUp (ConstLatticeRef l)
Remove arcs that.
NodeRef createCleanUpNode (const std::string &name, const Core::Configuration &config)
void dumpNBest (ConstLatticeRef l, std::ostream &os)
ConstLatticeRef nbest (ConstLatticeRef l, u32 n, bool removeDuplicates, NBestAlgorithm algo)
NodeRef createNBestNode (const std::string &name, const Core::Configuration &config)
NodeRef createSelectNBestNode (const std::string &name, const Core::Configuration &config)
NodeRef createDumpNBestNode (const std::string &name, const Core::Configuration &config)
NodeRef createDummyFilterNode (const std::string &name, const Core::Configuration &config)
NodeRef createLatticeBufferNode (const std::string &name, const Core::Configuration &config)
NodeRef createSink (const std::string &name, const Core::Configuration &config)
NodeRef createPropertiesNode (const std::string &name, const Core::Configuration &config)
NodeRef createSegmentBuilderNode (const std::string &name, const Core::Configuration &config)
NodeRef createAppendScoresNode (const std::string &name, const Core::Configuration &config)
void registerNodeCreators (NodeFactory *factory)
List of nodes:
void expandFilterStates (std::vector< std::vector< s32 >> &expanded, const std::vector< s32 > &labels, const std::map< std::pair< s32, s32 >, s32 > &initialFilters, const std::multimap< s32, s32 > &initialFilterSuccessors, s32 filterState)
StaticLatticeRef uniqueSentenceAlignmentFilter (ConstLatticeRef l, u32 maxWidth=100000, u32 maxDepth=10, int maxClosureLength=1000)
Filters the lattice by removing redundant paths which represent word sequences for which a better scoring path is available in the lattice.
NodeRef createUniqueSentenceAlignmentFilterNode (const std::string &name, const Core::Configuration &config)
StaticLatticeRef applyEpsClosureFilter (ConstLatticeRef l)
Epsilon Closure Filter:
StaticLatticeRef applyEpsClosureWeakDeterminizationFilter (ConstLatticeRef l)
StaticLatticeRef applyEpsClosureStrongDeterminizationFilter (ConstLatticeRef l)
NodeRef createNonWordClosureFilterNode (const std::string &name, const Core::Configuration &config)
Non-word Closure Filter:
NodeRef createNonWordClosureWeakDeterminizationFilterNode (const std::string &name, const Core::Configuration &config)
NodeRef createNonWordClosureStrongDeterminizationFilterNode (const std::string &name, const Core::Configuration &config)
ConstLatticeRef normalizeEpsClosure (ConstLatticeRef l)
Epsilon Closure Normalization:
NodeRef createNonWordClosureNormalizationFilterNode (const std::string &name, const Core::Configuration &config)
Non-Word Closure Normalization:
NodeRef createNonWordClosureRemovalFilterNode (const std::string &name, const Core::Configuration &config)
Non-Word Closure Removal:
NodeRef createPivotArcCnBuilderNode (const std::string &name, const Core::Configuration &config)
NodeRef createBatchNode (const std::string &name, const Core::Configuration &config)
ConstLatticeRef pruneByFwdBwdScores (ConstLatticeRef l, ConstFwdBwdRef fb, Score t, f32 minArcsPerSec, f32 maxArcsPerSec, s32 maxArcsPerSegment)
NodeRef createFwdBwdPruningNode (const std::string &name, const Core::Configuration &config)
void prune (ConstConfusionNetworkRef cnRef, Score threshold, u32 maxSlotSize, bool normalize)
void prune (ConstPosteriorCnRef cnRef, Score threshold, u32 maxSlotSize, bool normalize)
void removeEpsSlots (ConstConfusionNetworkRef cnRef, Score threshold)
void removeEpsSlots (ConstPosteriorCnRef cnRef, Score threshold)
NodeRef createNormalizedCnPruningNode (const std::string &name, const Core::Configuration &config)
NodeRef createPosteriorCnPruningNode (const std::string &name, const Core::Configuration &config)
NodeRef createPushForwardRescoringNode (const std::string &name, const Core::Configuration &config)
NodeRef createRecognizerNode (const std::string &name, const Core::Configuration &config)
NodeRef createRescaleNode (const std::string &name, const Core::Configuration &config)
rescale the lattice's semiring
NodeRef createReduceScoresNode (const std::string &name, const Core::Configuration &config)
Reduce many scores to a single score.
template<class Func >
ConstLatticeRef func (ConstLatticeRef l, ScoreId id, Score c, RescoreMode rescoreMode)
template<class Func >
NodeRef createFuncNode (const std::string &name, const Core::Configuration &config)
ConstLatticeRef add (ConstLatticeRef l, ScoreId id, Score c, RescoreMode rescoreMode=RescoreModeClone)
arithmetic operations nodes
NodeRef createAddNode (const std::string &name, const Core::Configuration &config)
ConstLatticeRef multiply (ConstLatticeRef l, ScoreId id, Score c, RescoreMode rescoreMode=RescoreModeClone)
f(x,c) = c * x
NodeRef createMultiplyNode (const std::string &name, const Core::Configuration &config)
ConstLatticeRef exp (ConstLatticeRef l, ScoreId id, Score c, RescoreMode rescoreMode=RescoreModeClone)
f(x,c) = exp(c * x)
NodeRef createExpNode (const std::string &name, const Core::Configuration &config)
ConstLatticeRef log (ConstLatticeRef l, ScoreId id, Score c, RescoreMode rescoreMode=RescoreModeClone)
f(x,c) = c * log(x)
NodeRef createLogNode (const std::string &name, const Core::Configuration &config)
PenaltyMapRef buildPenaltyMap (const StringListList &orthClasses, const ScoreList &orthClassPenalties)
NodeRef createExtendByPenaltyNode (const std::string &name, const Core::Configuration &config)
extend by fixed or lemma dependent penalties
ConstLatticeRef extendByPronunciationScore (ConstLatticeRef l, Core::Ref< const Bliss::LemmaPronunciationAlphabet > lpAlphabet, ScoreId id, Score scale, RescoreMode rescoreMode=RescoreModeClone)
extend by pronunciation score
NodeRef createExtendByPronunciationScoreNode (const std::string &name, const Core::Configuration &config)
RescoreMode getRescoreMode (const Core::Configuration &config)
ConstLatticeRef decodeRescoreLm (ConstLatticeRef lat, Core::Ref< Lm::LanguageModel > lm, float wordEndBeam=20, u32 wordEndLimit=50000, const std::vector< const Bliss::Lemma * > &prefix=std::vector< const Bliss::Lemma * >(), const std::vector< const Bliss::Lemma * > &suffix=std::vector< const Bliss::Lemma * >())
Performs a time-synchronous rescoring.
NodeRef createDecodeRescoreLmNode (const std::string &name, const Core::Configuration &config)
s32 nFrames (f32 startTime, f32 endTime)
s32 nFrames (ConstSegmentRef segment)
std::ostream & printAsText (std::ostream &os, ConstSegmentRef segment)
void printSegmentHeader (std::ostream &os, ConstSegmentRef segment, const std::string &head)
AcousticModelRef getAm (const Core::Configuration &config)
ScaledLanguageModelRef getLm (const Core::Configuration &config)
ModelCombinationRef getModelCombination (const Core::Configuration &config, AcousticModelRef acousticModel, ScaledLanguageModelRef languageModel)
NodeRef createStateClusterCnBuilderNode (const std::string &name, const Core::Configuration &config)
ConstLatticeRef staticScore (ConstLatticeRef l, ConstSemiringRef semiring, ScoresRef weight)
NodeRef createTimeAlignmentNode (const std::string &name, const Core::Configuration &config)
ConstLatticeRef posteriorCn2lattice (ConstPosteriorCnRef cn)
ConstLatticeRef decodePosteriorCn (ConstPosteriorCnRef cn)
void normalizePosteriorCn (PosteriorCn &cn)
bool isNormalizedPosteriorCn (ConstPosteriorCnRef cn)
ConstLatticeRef extendByFCnConfidence (ConstLatticeRef l, ConstPosteriorCnRef cn, ScoreId id, RescoreMode rescoreMode)
NodeRef createExtendByPosteriorCnConfidenceNode (const std::string &name, const Core::Configuration &config)
NodeRef createFramePosteriorCnFeatureNode (const std::string &name, const Core::Configuration &config)
ConstPosteriorCnRef buildFramePosteriorCn (ConstLatticeRef l, ConstFwdBwdRef fwdBwd)
Build framewise posterior CN from fwd/bwd scores.
ConstPosteriorCnRef buildFramePosteriorCn (ConstLatticeRef l, ScoreId id)
Build framewise posterior CN from scores stored in dimension "id".
NodeRef createFramePosteriorCnBuilderNode (const std::string &name, const Core::Configuration &config)
f64 slotEntropy (const PosteriorCn::Slot &slot)
entropy
void minEntropyWeights (WeightsList &weightsList, const ConstPosteriorCnRefList &cns, const ScoreList &_weights)
minimum entropy weighting
f64 inverseSlotEntropy (const PosteriorCn::Slot &slot)
inverse, thresholded entropy weighting
void inverseEntropyWeights (WeightsList &weightsList, const ConstPosteriorCnRefList &cns, const ScoreList &_weights)
void estimateJointPosteriorCn (PosteriorCn &jointCn, const ConstPosteriorCnRefList &cns, const WeightsList &weightsList)
void estimateMaxPosteriorCn (PosteriorCn &maxCn, const ConstPosteriorCnRefList &cns, const WeightsList &weightsList)
NodeRef createFramePosteriorCnCombinationNode (const std::string &name, const Core::Configuration &config)
void estimateJointPosteriorCn (PosteriorCn &jointCn, const ConstPosteriorCnRefList &cns, const ScoreList &weights)
void estimateMaxPosteriorCn (PosteriorCn &maxCn, const ConstPosteriorCnRefList &cns)
Attention: No timeframe-wise probability distr.
void writePosteriorCnAsText (std::ostream &os, ConstPosteriorCnRef cn, ConstSegmentRef segment)
Text-Format: #word probability.
ConstPosteriorCnRef readPosteriorCnFromXml (std::istream &is, PosteriorCnRef cn=PosteriorCnRef())
Input.
void writePosteriorCnAsXml (Core::XmlWriter &xml, ConstPosteriorCnRef cn, ConstSegmentRef segment, u32 ioFlag)
void writePosteriorCnAsFlowAlignment (Flow::Cache &cache, ConstPosteriorCnRef cn, ConstSegmentRef segment)
NodeRef createDumpPosteriorCnNode (const std::string &name, const Core::Configuration &config)
NodeRef createTimeframeErrorNode (const std::string &name, const Core::Configuration &config)
NodeRef createMinimumFrameWerDecoderNode (const std::string &name, const Core::Configuration &config)
NodeRef createDumpTracebackNode (const std::string &name, const Core::Configuration &config)
ConstLatticeRef unite (const ConstLatticeRefList &lats, ConstSemiringRef semiring)
ConstLatticeRef unite (ConstLatticeRef l1, ConstLatticeRef l2, ConstSemiringRef semiring=ConstSemiringRef())
union
NodeRef createUnionNode (const std::string &name, const Core::Configuration &config)
ConstLatticeRef expandTransits (ConstLatticeRef lat, Bliss::Phoneme::Id leftContext=Bliss::Phoneme::term, Bliss::Phoneme::Id rightContext=Bliss::Phoneme::term)
Boundary states are expanded so that each state corresponds to exactly one co-articulated cross-word transition (and eventually one non-coarticulated).
NodeRef createExpandTransitsNode (const std::string &name, const Core::Configuration &config)
template<class MeshedBoundaryBuilder >
ConstLatticeRef buildMesh (const std::vector< MeshEntry > &entries, ConstSemiringRef semiring, const MeshedBoundaryBuilder &meshedBoundaryBuilder=MeshedBoundaryBuilder())
ConstLatticeRef mesh (const std::vector< MeshEntry > &lattices, ConstSemiringRef semiring, MeshType meshType)
ConstLatticeRef mesh (ConstLatticeRef l1, ConstLatticeRef l2, ConstSemiringRef semiring, MeshType meshType)
ConstLatticeRef mesh (ConstLatticeRef l, MeshType meshType)
NodeRef createMeshNode (const std::string &name, const Core::Configuration &config)
Variables
const Core::ParameterBool paramInfo ("info","info", false)
s32 startFrame
s32 endFrame
ConstBoundariesRef InvalidBoundaries = ConstBoundariesRef(new InvalidBoundaries_)
const Boundary InvalidBoundary (Speech::InvalidTimeframeIndex, Boundary::Transit())
const Core::ParameterString paramType ("type","semiring type","")
const Core::ParameterInt paramTolerance ("tolerance","tolerance used for score comparisons", Semiring::DefaultTolerance)
const Core::ParameterStringVector paramKeys ("keys","list of keys")
const Core::ParameterFloat paramScale ("scale","scale", Semiring::DefaultScale)
static const Time InvalidTime = Speech::InvalidTimeframeIndex
static const u8 AcrossWordBoundary = 0
static const u8 WithinWordBoundary = 1
static const Property PropertyCrossWord = 0x00010000
Cross Word context is known.
static const Hint HintUnscaled = 0x00000008
Draw scores unscaled; requires Fsa::HintShowDetails, exclusive to Fsa::HintAsProbability.
const Core::Choice ContextModeChoice
class Flf::FwdBwd::Builder buildFwdBwd
const Core::Choice alphabetMappingActionChoice ("undefined", UndefinedAlphabetMapping,"to-phoneme", MapToPhoneme,"to-lemma-pron", MapToLemmaPronunciation,"to-preferred-lemma-pron", MapToPreferredLemmaPronunciation,"to-lemma", MapToLemma,"to-synt", MapToSyntacticTokenSequence,"to-eval", MapToEvaluationTokenSequences,"to-preferred-eval", MapToPreferredEvaluationTokenSequence, Core::Choice::endMark())
map alphabet
static const Core::ParameterInt paramMaxWidth ("max-width","maximum number of concurrent hypotheses allowed during unique alignment filtering", 100000)
static const Core::ParameterInt paramMaxDepth ("max-depth","maximum local expansion depth allowed during unique alignment filtering", 10)
static const Core::ParameterInt paramMaxClosureLength ("max-closure-length","maximum length of non-word closures (in timeframes)", 1000)
Detailed Description
Copyright 2020 RWTH Aachen University.
XML-Format: <posterior-cn n="#slots" version="1.0"> <head> <alphabet name="..."> </head> <slot n="#words"> <word p="..."> ...
XML-Format: <cn n="#slots" version="1.0"> <head> ...
Read/Write CNs.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. CN construction algorithm based on the selection of a frame representing the center of the next CN slot, for details see my thesis, chapter 4.4.4 (The Center-Frame CN Construction Algorithm)
Text-Format:
oracle
#word begin duration <key[0]>/<scale[0]> <key[1]>/<scale[0]> ...
slot
#word begin duration <key[0]>/<scale[0]> <key[1]>/<scale[0]> ...
oracle 1
<word> <begin> <duration> <score[0]> <score[1]> ...
slot 1
<word> <begin> <duration> <score[0]> <score[1]> ... ...
Attention: oracle is optional
</head> <slot n="#arcs"> ... </slot> </cn>
<cn version="1.1"> <head> <alphabet name="..."> <semiring> ... </semiring> [<normalized posterior-key="...">] [<n-best n="..."/>] [<oracle> <semiring> ... </semiring> </oracle>] </head> <body [n="#slots"]> <slot [n="#arcs"]> [<oracle> <word> ... </word> <begin> ... </begin> <end> ... </end> <from> ... </from> <to> ... </to> <score> ... </score> ... </oracle>] <arc> <word> ... </word> <begin> ... </begin> <end> ... </end> <from> ... </from> <to> ... </to> <score> ... </score> ... </arc> ... </slot> ... </body> </cn>
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. Implementation of RWTH's fsa based lattice format
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. Implementation of HTK's standard lattice format
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. Implementation of local costs of the first and the second type, for details see my thesis, chapter 3.3.3 (The Bayes Risk Decoding Framework with Local Cost Functions)
The implementations of the following Levenshtein distance approximations:
Symmetrically Normalized Frame Errors (arc and path normalization, see my thesis, chapter 4.2.2)
Local Alignment based Errors (see my thesis, chapter 4.3)
Other local cost functions have separate implementations, see *ConfusionNetworkBuilder.hh
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. CN construction algorithm based on a direct arc clustering driven by a pivot element, for details see my thesis, chapter 4.4.2 (The Arc-Cluster CN Construction Algorithm)
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. CN construction algorithm based on a state clustering, for details see my thesis, chapter 4.4.3 (The State-Cluster CN Construction Algorithm)
</word> ... </slot> ... </posterior-cn>
<posterior-cn version="1.1"> <head> <alphabet name="..."> </head> <body [n="#slots"]> <slot [n="#arcs"]> <arc> <word> ... </word> <probability> ... </probability> </arc> ... </slot> ... </body> </posterior-cn>
Words have to be sorted in decreasing order of p!
Typedef Documentation
typedef Core::Ref<Am::AcousticModel> Flf::AcousticModelRef
Segmentwise model adaptation and feature extraction.
Basic models
Definition at line 36 of file SegmentwiseSpeechProcessor.hh.
typedef Core::Ref<Speech::DataSource> Flf::DataSourceRef
Feature extraction.
Definition at line 75 of file SegmentwiseSpeechProcessor.hh.
typedef Ftl::DfsState<Lattice> Flf::DfsState
Traverse lattice using dfs, see Fsa/tDfs.hh.
Definition at line 26 of file Traverse.hh.
typedef Ftl::WrapperAutomaton<Fsa::Automaton, Lattice> Flf::FsaToFlfWrapperLattice
Wrapper lattice/automaton; generic fsa-to-flf and flf-to-fsa.
Definition at line 50 of file LatticeInternal.hh.
typedef Fsa::Hint Flf::Hint
Extensions for FSA hints.
Definition at line 52 of file Flf/FlfCore/Types.hh.
typedef Ftl::ModifyAutomaton<Lattice> Flf::ModifyLattice
Modify lattice; specialisation of slave lattice, structure preserving flf-to-flf.
Definition at line 66 of file LatticeInternal.hh.
typedef NodeRef(* Flf::NodeCreatorFcn) (const std::string &name, const Core::Configuration &config)
Function producing a node.
Definition at line 29 of file NodeFactory.hh.
typedef Fsa::Property Flf::Property
Extensions for FSA properties.
Definition at line 43 of file Flf/FlfCore/Types.hh.
typedef Fsa::SemiringType Flf::SemiringType
Semiring type.
So far, only log- and tropical semiring are supported.
Definition at line 71 of file Flf/FlfCore/Types.hh.
typedef Ftl::SlaveAutomaton<Lattice> Flf::SlaveLattice
Slave lattice; specialisation of wrapper lattice, generic flf-to-flf.
Definition at line 59 of file LatticeInternal.hh.
typedef Ftl::State<Arc> Flf::State
Lattice state.
Definition at line 83 of file Flf/FlfCore/Lattice.hh.
typedef std::vector<std::string> Flf::StringList
extend by lemma specific penalty
Definition at line 342 of file Rescore.cc.
Enumeration Type Documentation
enum Flf::AlphabetMappingAction
Map alphabets.
Definition at line 39 of file Map.hh.
enum Flf::InfoType
Info type.
Collect information and statistics about a lattice. Runtime/memory requirements: cheap: O(1), lattice is not traversed. normal: O(N), lattice is traversed exactly once, no state caching. extended: O(N), lattice can be traversed several times. memory: no runtime/memory requirements.
Definition at line 107 of file Flf/FlfCore/Types.hh.
enum Flf::MeshType
time or boundary conditioned lattice; join either all states having identical boundaries(boundary information includes time) or having identical time
Definition at line 58 of file Union.hh.
enum Flf::RescoreMode
Rescore mode.
Clone is always safe. In-place cached is always safe in linear command networks, normally faster than clone, but more memory demanding. In-place is unsafe, but always fastet mode.
Definition at line 86 of file Flf/FlfCore/Types.hh.
enum Flf::SingleSourceShortestPathAlgorithm
Dijkstra:
aka Ftl::firstBest
extend path scores, find path with minimum w.r.t. to projection of extended path scores
uses priority queue to follow currently best path Bellman-Ford:
aka Ftl::best
extend path scores, collect extended path scores
general single source shortest path (SSSP) algorithm Projecting-Bellman-Ford:
project scores, sum projected scores, find path with minimum sum of projected path scores For the tropical semiring and if the projection of each score is positive, then all three algorithms yield the same result.
Definition at line 37 of file Flf/Best.hh.
Function Documentation
ConstLatticeRef Flf::add (ConstLatticeRef l, ScoreId id, Score c, RescoreMode rescoreMode = RescoreModeClone)
arithmetic operations nodes
f(x,c) = x + c
Definition at line 219 of file Rescore.cc.
ConstLatticeRef Flf::appendScores (ConstLatticeRef l1, ConstLatticeRef l2, ConstSemiringRef semiring = ConstSemiringRef())
Append.
appends the scores of two topologically equivalent (down to state numbering!) lattices; scores are concatenated, i.e. new semiring is the concatentation
Definition at line 583 of file Flf/FlfCore/Basic.cc.
Referenced by Flf::AppendScoresNode::sendLattice().
StaticLatticeRef Flf::applyEpsClosureFilter (ConstLatticeRef l)
Epsilon Closure Filter:
Given states s and e. Pathes_w(s,e) is the set of all pathes from s to e having exactly one arc labeled with w and all others labeled with epsilon. Arcs_w(s,e) is the set of all arcs in Pathes_w(s,e) labeled with w. Arcs_s'/w(s,e) is the set of all arcs in Arcs_w(s,e) having source state s'. Pathes_s'/w(s,e) is the subset of Pathes_w(s,e), such that each path in Pathes_s'/w(s,e) includes an arc in Arcs_s'/w(s,e).
for each w, (s,e): 1) for each a in Arcs_w(s,e) keep only the best scoring path in Pathes_w(s,e) that includes a. -> classical epsilon-removal over the tropical semiring 2) for each s' keep only the best scoring path in Pathes_s'/w(s,e) -> classical epsilon-removal over the tropical semiring with statewise determinization 3) keep only the best scoring path in Pathes_w(s,e) -> classical epsilon-removal over the tropical semiring with determinization over all pathes from s to e; attention: under some circumstances the determinization is not given; the problem could be avoided by introducing new states and arcs, but that could result in a (huge???) blow up of the lattice size
Arcs and states are removed, but never new states and arcs are intorduced. The implementation is static, i.e not lazy.
Definition at line 723 of file NonWordFilter.cc.
References Core::form(), Core::PriorityQueueBase< T_Heap, T_PriorityFunction >::insert(), persistent(), Core::PriorityQueueBase< T_Heap, T_PriorityFunction >::pop(), require, Core::PriorityQueueBase< T_Heap, T_PriorityFunction >::top(), and verify.
BoundedSegmentList Flf::buildBoundedSegments (const RecordingSegmentation & recSeg)
Distribute recording time over segments: In case of overlaps, the begining of the next next segment is cut.
Definition at line 57 of file Concatenate.cc.
References Core::Application::us(), verify, and Core::Component::warning().
Referenced by Flf::ConcatenateFCnsNode::finalize(), and Flf::ConcatenateLatticesNode::sendLattice().
ConstPosteriorCnRef Flf::buildFramePosteriorCn (ConstLatticeRef l, ConstFwdBwdRef fb)
Build framewise posterior CN from fwd/bwd scores.
Definition at line 136 of file TimeframeConfusionNetworkBuilder.cc.
References verify.
Referenced by Flf::MinimumFrameWerDecoderNode::sendLattice().
ConstPosteriorCnRef Flf::buildFramePosteriorCn (ConstLatticeRef l, ScoreId id)
Build framewise posterior CN from scores stored in dimension "id".
Definition at line 188 of file TimeframeConfusionNetworkBuilder.cc.
References verify.
ConstStateBoundaryListRef Flf::cacheLattice (ConstLatticeRef l)
Cache complete lattice; allows fast state/boundary lookup; similar to copy by reference.
Definition at line 46 of file Flf/Cache.cc.
StaticLatticeRef Flf::cleanUp (ConstLatticeRef l)
Remove arcs that.
close a cycle
have an invalid label id
have an invalid or zero score at one dimension
Definition at line 475 of file Miscellaneous.cc.
References Core::Component::criticalError(), Core::Vector< T >::grow(), HintUnscaled, Core::Component::log(), Ftl::State< _Arc, _ArcContainer >::newArc(), Core::Application::us(), verify, and Core::Component::warning().
ConstSemiringRef Flf::cloneSemiring (ConstSemiringRef semiring)
Manipulate semirings; the original semiring is not modified.
appendSemiring: Append another semiring or a single dimension.
rescaleSemiring: Rescale/rename all dimesnions or a single dimension.
toLogSemiring: Return log-aquivalent of semiring. If scale is not set, the dimensional scales are normalized, i.e. scale = 1.0 / (sum of dimensional scales). Thus, a scale of 1.0 leaves the dimensional scales untouched.
Definition at line 684 of file Flf/FlfCore/Semiring.cc.
References Flf::Semiring::create().
Referenced by Speech::LatticeTransformNode::work(), and Speech::LatticeTransform2Node::work().
ConstLatticeRef Flf::cn2lattice (ConstConfusionNetworkRef cn, bool approximateBoundaryTimes = false)
Convert a CN into a lattice with "sausage" topology.
If approximateBoundaryTimes is set, then the boundary times in the lattice are approximated by inheriting them from the adjacent confusion network arc with highest probability. Otherwise boundary times are omitted.
Definition at line 408 of file ConfusionNetwork.cc.
Referenced by Flf::DumpConfusionNetworkNode::sendLattice(), Flf::CenterFrameCnBuilderNode::sendLattice(), Flf::ConfusionNetworkCombinationNode::sendLattice(), Flf::PivotArcCnBuilderNode::sendLattice(), Flf::StateClusterCnBuilderNode::sendLattice(), and Flf::RoverCombinationNode::sendLattice().
ConstLatticeRef Flf::composeAndAddCnFeatures (ConstLatticeRef l, const CnFeatureConfiguration & cnConfig)
Add CN features to lattice Optionally, perform the "composition" of the lattice and the CN derived from the lattice: each path in the resulting lattice has the same length.
Definition at line 873 of file ConfusionNetwork.cc.
ConstLatticeRef Flf::composeMatching (ConstLatticeRef l, ConstLatticeRef r)
compose two lattices
Definition at line 180 of file Flf/Compose.cc.
References FtlWrapper::composeMatching().
Referenced by composeMatching().
ConstLatticeRef Flf::composeSequencing (ConstLatticeRef l, ConstLatticeRef r)
compose two lattices
Definition at line 208 of file Flf/Compose.cc.
References FtlWrapper::composeSequencing().
Referenced by composeSequencing(), composeWithFsa(), and intersect().
ConstLatticeRef Flf::composeWithFsa (ConstLatticeRef l, Fsa::ConstAutomatonRef f, Score scale)
compose with fsa
composition of lattice and fsa
Definition at line 311 of file Flf/Compose.cc.
References composeSequencing(), fromFsa(), Fsa::multiply(), and offsetSemiring().
ConstLatticeRef Flf::composeWithLm (ConstLatticeRef l, ConstLanguageModelRef lm, ScoreId id, Score scale = Semiring::DefaultScale, bool forceSentenceEnd = false)
composition of lattice and lm
For more information please read Lm/Compose.hh.
The result is almost equvivalent to the lm-rescorer implementation in LanguageModelRescorer.hh; a slight difference concers the syntax-emission-probabilities (see the comments in Compose.cc).
Additional features:
the result of the composition has exactly as many final states as the input lattice
Definition at line 216 of file Flf/LanguageModel.cc.
References transducer().
bool Flf::copyBoundaries (ConstLatticeRef l, StaticBoundaries * staticBoundaries)
Behaviour of copyBoundaries:
l is traversed exactly once and only boundaries associated with accessible states are copied Behaviour of bool copyBoundaries(ConstLatticeRef l, StaticBoundaries *staticBoundaries);
staticBoundaries are cleared; the boundaries object of l is not touched
if !l or if boundaries of l are invalid then false is returned
else true is returned Behaviour of ConstLatticeRef copyBoundaries(ConstLatticeRef l):
the boundaries of l are copied and set at l and l is returned, i.e. l is modified!
Definition at line 278 of file Copy.cc.
References require.
Referenced by decodeRescoreLm(), readBoundariesBinary(), and Flf::ExpandTransitsNode::sync().
NodeRef Flf::createChangeSemiringNode (const std::string & name, const Core::Configuration & config)
change semiring (and set)
Definition at line 173 of file Convert.cc.
Referenced by registerNodeCreators().
NodeRef Flf::createCtmReaderNode (const std::string & name, const Core::Configuration & config)
ctm i/ -> use dump-traceback node for writing ctms
Definition at line 777 of file Io.cc.
Referenced by registerNodeCreators().
NodeRef Flf::createDrawerNode (const std::string & name, const Core::Configuration & config)
dot /o
Definition at line 935 of file Io.cc.
Referenced by registerNodeCreators().
NodeRef Flf::createDumpAllPairsShortestDistanceNode (const std::string & name, const Core::Configuration & config)
Format:
from to score
<from-id> <to-id> <score> ...
Output is sorted by from/to in increasing order
Definition at line 369 of file Flf/Best.cc.
Referenced by registerNodeCreators().
NodeRef Flf::createExtendByPenaltyNode (const std::string & name, const Core::Configuration & config)
extend by fixed or lemma dependent penalties
Definition at line 493 of file Rescore.cc.
Referenced by registerNodeCreators().
NodeRef Flf::createFsaReaderNode (const std::string & name, const Core::Configuration & config)
fsa i/ -> use lattice/flf-format for writing fsas
Definition at line 517 of file Io.cc.
Referenced by registerNodeCreators().
NodeRef Flf::createNonWordClosureFilterNode (const std::string & name, const Core::Configuration & config)
Non-word Closure Filter:
The non-word filter nodes work only on acceptors: mapOutputToInput(epsClosure...Filter(mapNonWordToEps(mapInputToOutput(l))))
The three strategies corresponds to the three eps-closure filter strategies (see above).
Definition at line 1222 of file NonWordFilter.cc.
Referenced by registerNodeCreators().
NodeRef Flf::createNonWordClosureNormalizationFilterNode (const std::string & name, const Core::Configuration & config)
Non-Word Closure Normalization:
The non-word normalization node works only on acceptors: normalizeEpsClosure(mapInputToOutput(mapNonWordToEps(l)))
Definition at line 1404 of file NonWordFilter.cc.
Referenced by registerNodeCreators().
NodeRef Flf::createNonWordClosureRemovalFilterNode (const std::string & name, const Core::Configuration & config)
Non-Word Closure Removal:
see epsilonRemoval and fastEpsilonRemoval Attention: resulting word boundaries might be incorrect
The non-word removal node works only on acceptors: removeEpsClosure(mapInputToOutput(mapNonWordToEps(l)))
Definition at line 1430 of file NonWordFilter.cc.
Referenced by registerNodeCreators().
NodeRef Flf::createProjectSemiringNode (const std::string & name, const Core::Configuration & config)
project source semiring to target semiring
Definition at line 217 of file Convert.cc.
Referenced by registerNodeCreators().
NodeRef Flf::createReduceScoresNode (const std::string & name, const Core::Configuration & config)
Reduce many scores to a single score.
Definition at line 120 of file Rescore.cc.
Referenced by registerNodeCreators().
NodeRef Flf::createRescaleNode (const std::string & name, const Core::Configuration & config)
rescale the lattice's semiring
Definition at line 74 of file Rescale.cc.
Referenced by registerNodeCreators().
NodeRef Flf::createStringConverterNode (const std::string & name, const Core::Configuration & config)
string to lattice
Definition at line 430 of file Convert.cc.
Referenced by registerNodeCreators().
NodeRef Flf::createWordListExtractorNode (const std::string & name, const Core::Configuration & config)
Extract vocab out of all seen lattices.
Definition at line 797 of file Flf/Lexicon.cc.
Referenced by registerNodeCreators().
ConstLatticeRef Flf::decodeCn (ConstConfusionNetworkRef cn, ScoreId posteriorId)
Decodes a normalized CN; if the CN is not normalized, a valid posteriroId is required and the CN is normalized beforehand.
Definition at line 420 of file ConfusionNetwork.cc.
Referenced by Flf::ConfusionNetworkCombinationNode::sendLattice(), and Flf::RoverCombinationNode::sendLattice().
ConstLatticeRef Flf::decodeRescoreLm (ConstLatticeRef lat, Core::Ref< Lm::LanguageModel > lm, float wordEndBeam = 20, u32 wordEndLimit = 50000, const std::vector< const Bliss::Lemma * > & prefix = std::vector< const Bliss::Lemma * >(), const std::vector< const Bliss::Lemma * > & suffix = std::vector< const Bliss::Lemma * >())
Performs a time-synchronous rescoring.
The input lattice may be a mesh lattice, in which case a huge lattice may be expanded. Pruning must be used to prevent the resulting lattice from exploding in that case.
wordEndBeam and wordEndLimit are equivalent to word end pruning used during standard decoding (wordEndBeam is relative to the LM scale)
Definition at line 60 of file RescoreLm.cc.
References Lm::addLemmaScore(), copyBoundaries(), defect, Core::Ref< T >::get(), Bliss::Lemma::hasSyntacticTokenSequence(), Bliss::Token::id(), Lm::History::isValid(), Lm::LanguageModel::sentenceEndScore(), Flf::StaticBoundaries::set(), sortByTopologicalOrder(), Lm::LanguageModel::startHistory(), and verify.
Referenced by Flf::IncrementalRecognizer::startRecognition().
ConstLatticeRef Flf::determinize (ConstLatticeRef l)
determinization
Definition at line 24 of file Flf/Determinize.cc.
Referenced by Flf::NBestBuilder::initialize().
ConstLatticeRef Flf::differ (ConstLatticeRef l, ConstLatticeRef r)
build difference of two lattices
difference between two lattices
Definition at line 236 of file Flf/Compose.cc.
bool Flf::drawDot (ConstLatticeRef l, std::ostream & o, Fsa::Hint hint, bool progress)
visualization
Definition at line 25 of file Draw.cc.
References FtlWrapper::drawDot(), Core::Application::us(), and Core::Component::warning().
void Flf::estimateMaxPosteriorCn (PosteriorCn & maxCn, const ConstPosteriorCnRefList & cns)
Attention: No timeframe-wise probability distr.
anymore
ConstLatticeRef Flf::exp (ConstLatticeRef l, ScoreId id, Score c, RescoreMode rescoreMode)
f(x,c) = exp(c * x)
Definition at line 273 of file Rescore.cc.
Referenced by Signal::GammaTone::initCoefficients(), and Flf::Semiring::read().
ConstLatticeRef Flf::expandTransits (ConstLatticeRef lat, Bliss::Phoneme::Id leftContext = Bliss::Phoneme::term, Bliss::Phoneme::Id rightContext = Bliss::Phoneme::term)
Boundary states are expanded so that each state corresponds to exactly one co-articulated cross-word transition (and eventually one non-coarticulated).
Note: Doesn't correctly consider epsilon arcs in other places than behind the initial state This transformation may be required when the decoder does not separate all allophones at word boundary.
Definition at line 266 of file Union.cc.
References Bliss::Pronunciation::length(), Bliss::Pronunciation::phonemes(), Flf::StaticBoundaries::set(), sortByTopologicalOrder(), Core::Application::us(), verify, and Core::Component::warning().
ConstLatticeRef Flf::extendByPronunciationScore (ConstLatticeRef l, Core::Ref< const Bliss::LemmaPronunciationAlphabet > lpAlphabet, ScoreId id, Score scale, RescoreMode rescoreMode)
extend by pronunciation score
Definition at line 539 of file Rescore.cc.
Referenced by Flf::LatticeArchiveWriterNode::sendLattice().
ConstLatticeRef Flf::fit (ConstLatticeRef l, bool forceSentenceEndLabels = false)
Fits the lattice into [begin, end]:
begin and end are relative to the lattices initial state
fitting lattice has exactly one initial state with time 0 and one final state with time end-begin, i.e. all pathes have the same length
the time of all states but the final state is less than end (and >= 0)
for each path the in origianl lattice there exist a path with the same score in the fitting lattice; those are the only pathes in the fitting lattice (i.e. according to the begin and end times words at the beginning or end of a path might be discarded).
optional: the last arc carries the sentence-end-symbol
if begin and end time are not given, then begin is 0 and end time is the max time over all states.
Definition at line 389 of file Miscellaneous.cc.
Referenced by Flf::ConcatenateLatticesNode::sendLattice().
ConstLatticeRef Flf::fromFsa (Fsa::ConstAutomatonRef f, ConstSemiringRef semiring, ScoreId id, ScoresRef defaultScore = ScoresRef())
Fsa to Flf.
Definition at line 105 of file Flf/FlfCore/Basic.cc.
References Core::Application::us(), and Core::Component::warning().
ConstLatticeRef Flf::fromFsa (Fsa::ConstAutomatonRef f, ConstSemiringRef semiring, ScoresRef defaultScore, ScoreId id, Lexicon::AlphabetId inputAlphabetId, Lexicon::AlphabetId outputAlphabetId = Lexicon::UnknownAlphabetId)
from fsa to flf, incl.
alphabet mapping (and symbol insertion)
Definition at line 334 of file Convert.cc.
References Flf::Semiring::create(), and verify.
Referenced by composeWithFsa(), Flf::FsaReaderNode::sendLattice(), Speech::ApproximateDistanceLatticeRescorerNode::work(), Speech::SoftFramePhoneAccuracyLatticeRescorerNode::work(), Speech::LatticeTransformNode::work(), and Speech::LatticeTransform2Node::work().
ConstLatticeRef Flf::intersect (ConstLatticeRef l, ConstLatticeRef r, bool appendScores)
intersect two lattices
intersection of two lattices; extend or append scores
Definition at line 264 of file Flf/Compose.cc.
References composeSequencing(), and offsetSemiring().
f64 Flf::inverseSlotEntropy (const PosteriorCn::Slot & slot)
inverse, thresholded entropy weighting
Definition at line 68 of file TimeframeConfusionNetworkCombination.cc.
References ensure, slotEntropy(), and verify.
bool Flf::isAcyclic (ConstLatticeRef l)
Properties.
getProperties computes missing acyclic/linear property.
Definition at line 478 of file Flf/FlfCore/Basic.cc.
References FtlWrapper::isAcyclic().
Referenced by isAcyclic().
ConstLatticeRef Flf::log (ConstLatticeRef l, ScoreId id, Score c, RescoreMode rescoreMode)
f(x,c) = c * log(x)
Definition at line 301 of file Rescore.cc.
Referenced by Flf::InfoNode::finalize(), Flf::ConcatenateFCnsNode::finalize(), Flf::FilterArcNode::init(), Flf::ArcRemovalNode::init(), Flf::UnionNode::init(), Flf::FramePosteriorCnBuilderNode::init(), Flf::ComposeWithLmNode::init(), Flf::DecodeRescoreLmNode::init(), Flf::ExtendByPosteriorCnConfidenceNode::init(), Flf::DumpAllPairsShortestDistanceNode::init(), Flf::ComposeWithFsaNode::init(), Flf::TimeAlignmentNode::init(), Flf::ConcatenateLatticesNode::init(), Flf::FitLatticeNode::init(), Flf::FramePosteriorCnFeatureNode::init(), Flf::ConcatenateFCnsNode::init(), Flf::CnDecoderNode::init(), Flf::FwdBwdPruningNode::init(), Flf::CnPruningNode::init(), Flf::CtmReaderNode::init(), Flf::UniqueSentenceAlignmentFilterNode::init(), Flf::MeshNode::init(), Flf::CenterFrameCnBuilderNode::init(), Flf::ConfusionNetworkCombinationNode::init(), Flf::CnFeatureNode::init(), Flf::PivotArcCnBuilderNode::init(), Flf::NBestNode::init(), Flf::LocalCostDecoderNode::init(), Flf::RoverCombinationNode::init(), Flf::OracleAlignmentNode::init(), Nn::BufferedAlignedFeatureProcessor< T >::processAlignedFeature(), Flf::ConcatenateLatticesNode::sendLattice(), and Flf::IncrementalRecognizer::startRecognition().
void Flf::minEntropyWeights (WeightsList & weightsList, const ConstPosteriorCnRefList & cns, const ScoreList & _weights)
minimum entropy weighting
Definition at line 45 of file TimeframeConfusionNetworkCombination.cc.
References slotEntropy().
ConstLatticeRef Flf::minimize (ConstLatticeRef l)
minimization
Definition at line 88 of file Flf/Determinize.cc.
References FtlWrapper::minimize().
Referenced by minimize().
ConstLatticeRef Flf::multiply (ConstLatticeRef l, ScoreId id, Score c, RescoreMode rescoreMode)
f(x,c) = c * x
Definition at line 243 of file Rescore.cc.
Referenced by Flf::LatticeArchiveWriterNode::sendLattice().
ConstConfusionNetworkRef Flf::normalizeCn (ConstConfusionNetworkRef cn, ScoreId posterirorId)
Normalizes an arbitrary CN.
Requires a dimension storing posteriror probabilities, i.e. a dimension defining a slot-wise prob. distribution, where missing prob. mass is assigned to the eps-arc. Each slot in the resulting normalized CN
is sorted by word label
each word label occurs at most once
the slot-wise sum over dimension "posterirorId" equals one
Definition at line 412 of file ConfusionNetwork.cc.
std::pair< bool, bool > Flf::normalizeCopy (ConstLatticeRef l, StaticLattice * staticLattice, StaticBoundaries * staticBoundaries)
Normalize state numbering, Copy, copy states, but no weights Deep Copy, copy states and weights.
Definition at line 240 of file Copy.cc.
ConstLatticeRef Flf::normalizeEpsClosure (ConstLatticeRef l)
Epsilon Closure Normalization:
For each state s and each state s_end being a final state of the eps-closure of s, keep exactly one eps-arc having the correct score w.r.t to the used semiring (i.e. best score for tropical semiring) and occupying the time needed for "crossing" the closure.
The implementation is lazy.
Definition at line 1377 of file NonWordFilter.cc.
ConstLatticeRef Flf::normalizeSemiring (ConstLatticeRef l, bool normalizeNames = true)
normalize semiring: apply scales to scores, set scales and keys to defaults (i.e.
scales to 1.0)
ConstLatticeRef Flf::offsetSemiring (ConstLatticeRef l, ConstSemiringRef targetSemiring, ScoreId offset)
dim i -> dim+offest
Definition at line 142 of file Convert.cc.
Referenced by composeWithFsa(), Flf::RescoreSingleDimensionNode::init_(), and intersect().
ConstLatticeRef Flf::partial (ConstLatticeRef l, Fsa::StateId initial)
Miscellaneous functions.
Definition at line 497 of file Flf/FlfCore/Basic.cc.
References FtlWrapper::partial().
Referenced by partial(), and Flf::SelectNBestNode::sendLattice().
std::pair< bool, bool > Flf::persistent (ConstLatticeRef l, StaticLattice * staticLattice, StaticBoundaries * staticBoundaries)
Behaviour of copy and deepCopy:
l is traversed exactly once, i.e. getState is called exactly once for every accessible state Behaviour of std::pair<bool,bool> copyXXX(ConstLatticeRef l, StaticLattice *staticLattice, StaticBoundaries *staticBoundaries);
staticLattice and staticBoundaries are cleared; the boundaries object of staticLattice is not touched
if !l then (false,false) is returned
else if boundaries of l are invalid or staticBoundaries is null, then (true,false) is returned
else (true,true) is returned Persistent: Copy state references, i.e. the states are made persistent -> used for random or repeated state access (and insito state modifications) Copy: Copy states, make weights persistent, i.e. states are copied, but not the weights -> used for topology modifications (and insito weight modifications) Deep Copy: Copy states and weights, i.e. states as well as any weight are copied -> used for weight (and topology) modifications
Definition at line 140 of file Copy.cc.
Referenced by applyEpsClosureFilter(), and Flf::LatticeArchiveWriterNode::sendLattice().
ConstLatticeRef Flf::pruneByFwdBwdScores (ConstLatticeRef l, ConstFwdBwdRef fb, Score t, f32 minArcsPerSec, f32 maxArcsPerSec, s32 maxArcsPerSegment)
Todo:
binary search instead of static steps
Todo:
binary search instead of static steps
Definition at line 59 of file Flf/Prune.cc.
References Core::Component::log(), Core::Application::us(), verify, and Core::Component::warning().
bool Flf::readBoundariesBinary (ConstLatticeRef l, std::istream & is)
boundaries i/o
Definition at line 207 of file Io.cc.
References copyBoundaries(), defect, and Core::Ref< T >::get().
ConstConfusionNetworkRef Flf::readConfusionNetworkFromXml (std::istream & is, ConfusionNetworkRef cn)
Input.
Definition at line 523 of file ConfusionNetworkIo.cc.
References Core::form(), Core::Ref< T >::get(), and Core::Application::us().
Referenced by Flf::ConfusionNetworkArchive::ConfusionNetworkArchive().
ConstPosteriorCnRef Flf::readPosteriorCnFromXml (std::istream & is, PosteriorCnRef cn)
Input.
Definition at line 292 of file TimeframeConfusionNetworkIo.cc.
References Core::form(), Core::Ref< T >::get(), Speech::Alignment::sortItems(), Core::Application::us(), and verify.
Referenced by Flf::PosteriorCnArchive::PosteriorCnArchive().
void Flf::registerNodeCreators (NodeFactory * factory)
List of nodes:
Fwd/Bwd scores
Pruning
fCN
CN
local cost decoder
Time alignment
Definition at line 72 of file NodeRegistration.hh.
References createChangeSemiringNode(), createCtmReaderNode(), createDrawerNode(), createDumpAllPairsShortestDistanceNode(), createExtendByPenaltyNode(), createFsaReaderNode(), createNonWordClosureFilterNode(), createNonWordClosureNormalizationFilterNode(), createNonWordClosureRemovalFilterNode(), createProjectSemiringNode(), createReduceScoresNode(), createRescaleNode(), createStringConverterNode(), and createWordListExtractorNode().
Referenced by Flf::NodeFactory::NodeFactory().
ConstLatticeRef Flf::rescale (ConstLatticeRef l, const ScoreList & scales, const KeyList & keys = KeyList())
Replace semiring.
Rescale semiring: new semiring is old semiring, where scales and/or key names are changed Change semiring: old and new semiring must have same size Project semiring: size(projection-matrix) = length(new semiring) x length(old semiring)
Definition at line 34 of file Flf/FlfCore/Basic.cc.
References Core::form(), and verify.
ConstConfusionNetworkRef Flf::sausageLattice2cn (ConstLatticeRef l, bool keepEpsArcs = true)
Build a confusion network from a lattice with "sausage" topology.
Remark: a linear lattice has a "sausage" topology.
Definition at line 100 of file ConfusionNetwork.cc.
References Core::Component::criticalError(), Core::Ref< T >::get(), Ftl::State< _Arc, _ArcContainer >::newArc(), Core::round(), Flf::StaticBoundaries::set(), Core::Application::us(), verify, and Core::Component::warning().
Referenced by Flf::RoverCombination::init().
f64 Flf::slotEntropy (const PosteriorCn::Slot & slot)
entropy
Definition at line 33 of file TimeframeConfusionNetworkCombination.cc.
Referenced by inverseSlotEntropy(), and minEntropyWeights().
ConstLatticeRef Flf::sortByTopologicalOrder (ConstLatticeRef l)
The states of the resulting lattice are enumerated by increasing topological order, i.e.
state id = topological order
Definition at line 472 of file Flf/FlfCore/Basic.cc.
Referenced by decodeRescoreLm(), expandTransits(), and uniqueSentenceAlignmentFilter().
ConstStateMapRef Flf::sortTopologically (ConstLatticeRef l)
Topological/Chronological Order.
sort in topological order: order -> state id find topological order : state id -> order, or
if l has no topological order, i.e. l is cyclic, the resulting map is empty
if a chronological exists, that does not violates the topological order, then the returned chronological order is as well a topological order (many algorithm require acyclic lattices that doe not violate the time contraint; for those lattices the property is given).
if you need both, topological sort and order, calculate first sort and order is calculated fast by making use of the topological sort
Definition at line 331 of file Flf/FlfCore/Basic.cc.
Referenced by Flf::TopologicalOrderLattice::TopologicalOrderBoundaries::get(), Flf::NBestBuilder::initialize(), and Flf::ExpandTransitsNode::sync().
std::pair< std::string, bool > Flf::stripExtension (const std::string & filename)
1) Removes .gz, if existent 2) Removes the last dot-seperated suffix, if existent Returns stripped filename and true if ending .gz was detected (and removed)
Strips the extension of the.
Definition at line 38 of file Io.cc.
References defect, Core::Component::error(), Core::normalizePath(), Core::Application::us(), and Core::Component::warning().
Fsa::ConstAutomatonRef Flf::toFsa (ConstLatticeRef l, const ScoreList & scales = ScoreList())
Flf to Fsa.
Definition at line 229 of file Flf/FlfCore/Basic.cc.
References require.
Referenced by Flf::Evaluator::logEvaluation(), Flf::LatticeArchiveWriterNode::sendLattice(), Speech::LatticeTransformNode::work(), and Speech::LatticeTransform2Node::work().
ConstLatticeRef Flf::transducer (ConstLatticeRef l)
Switch between acceptor and transducer.
Definition at line 53 of file Map.cc.
References alphabetMappingActionChoice.
Referenced by composeWithLm().
StaticLatticeRef Flf::uniqueSentenceAlignmentFilter (ConstLatticeRef l, u32 maxWidth, u32 maxDepth, int maxClosureLength)
Filters the lattice by removing redundant paths which represent word sequences for which a better scoring path is available in the lattice.
Definition at line 326 of file NonWordFilter.cc.
References Core::form(), sortByTopologicalOrder(), and verify.
ConstLatticeRef Flf::unite (ConstLatticeRef l1, ConstLatticeRef l2, ConstSemiringRef semiring)
union
Definition at line 178 of file Union.cc.
ConstLatticeRef Flf::unweight (ConstLatticeRef l, ConstSemiringRef semiring = ConstSemiringRef())
set weight of arcs and states in l to l->semiring()->one() (or to semiring->one(), if a semiring is given)
remove word boundaries
application: intersections, i.e. composition of a weighted and an unweighted transducer
Definition at line 65 of file Flf/Compose.cc.
Referenced by Flf::ComposeNode::sendLattice().
void Flf::writeConfusionNetworkAsText (std::ostream & os, ConstConfusionNetworkRef cn, ConstSegmentRef segment)
Ouput.
Definition at line 149 of file ConfusionNetworkIo.cc.
References Core::XmlRegularElement::addFinalState(), Core::XmlRegularElement::addTransition(), Flf::Semiring::create(), Core::Ref< T >::reset(), Core::round(), Core::strconv(), and verify.
Referenced by Flf::ConfusionNetworkArchive::ConfusionNetworkArchive().
void Flf::writePosteriorCnAsText (std::ostream & os, ConstPosteriorCnRef cn, ConstSegmentRef segment)
Text-Format: #word probability.
Output.
slot 1
<word> <probability> ...
Definition at line 105 of file TimeframeConfusionNetworkIo.cc.
References Core::XmlRegularElement::addFinalState(), Core::XmlRegularElement::addTransition(), Core::strconv(), and verify.
Referenced by Flf::PosteriorCnArchive::PosteriorCnArchive().
Variable Documentation
const Core::Choice Flf::alphabetMappingActionChoice("undefined", UndefinedAlphabetMapping,"to-phoneme", MapToPhoneme,"to-lemma-pron", MapToLemmaPronunciation,"to-preferred-lemma-pron", MapToPreferredLemmaPronunciation,"to-lemma", MapToLemma,"to-synt", MapToSyntacticTokenSequence,"to-eval", MapToEvaluationTokenSequences,"to-preferred-eval", MapToPreferredEvaluationTokenSequence, Core::Choice::endMark())
map alphabet
Referenced by transducer().
const Core::Choice Flf::ContextModeChoice
Initial value:
= Core::Choice(
        "trust", 0,
        "adapt", 1,
        "update", 5,
        Core::Choice::endMark())
Definition at line 605 of file FlfIo.cc.
const Hint Flf::HintUnscaled = 0x00000008 static
Draw scores unscaled; requires Fsa::HintShowDetails, exclusive to Fsa::HintAsProbability.
Definition at line 57 of file Flf/FlfCore/Types.hh.
Referenced by cleanUp(), Flf::FittingLattice::Boundaries::get(), Flf::CtmReaderNode::init(), and Flf::Semiring::read().
const Property Flf::PropertyCrossWord = 0x00010000 static
Cross Word context is known.
Definition at line 47 of file Flf/FlfCore/Types.hh.