Sprint: Lattice Namespace Reference
Lattice Namespace Reference
Copyright 2020 RWTH Aachen University.
Namespaces
Core
Copyright 2020 RWTH Aachen University.
Mm
Copyright 2020 RWTH Aachen University.
Classes
class AcousticAccumulator
AcousticAccumulator.
class ApproximateAccuracyAutomaton
ApproximateAccuracyAutomaton.
class ApproximatePhoneAccuracyAutomaton
ApproximatePhoneAccuracyAutomaton.
class ApproximatePhoneAccuracyMaskAutomaton
ApproximatePhoneAccuracyMaskAutomaton.
class ApproximateWordAccuracyAutomaton
ApproximateWordAccuracyAutomaton: Word lattices may contain epsilon arcs (input labels) but they must have vanishing duration.
class Archive
class ArchiveReader
class ArchiveWriter
class BaseAccumulator
BaseAccumulator.
class CachedAcousticAccumulator
class CachedAcousticSparseAccumulator
CachedAcousticSparseAccumulator.
class CheckPosteriorDfsState
class Collector
struct Cutter
class DensityCachedAcousticAccumulator
DensityCachedAcousticAccumulator.
class DensityDfsState
class DfsState
class ExactAccuracyGenerator
ExactAccuracyGenerator: base class.
class ExactPhonemeAccuracyGenerator
ExactPhonemeAccuracyGenerator.
class ExactWordAccuracyGenerator
ExactWordAccuracyGenerator: on word level.
struct Exponentiator
struct Extender
struct FailureRemover
struct FinalExtension
class FramePhoneAccuracyAutomaton
FramePhoneAccuracyAutomaton.
class FrameStateAccuracyAutomaton
FrameStateAccuracyAutomaton.
class FsaArchiveReader
class FsaArchiveWriter
struct GreaterEqual
class HtkReader
Parse a lattice in HTK SLF format.
class HtkWriter
Write word lattices in HTK format.
class IsInputLabel
struct Key
CachedAcousticAccumulator.
struct KeyEquality
struct KeyHash
class LatticeCounts
class LatticeWeights
class LemmaMapping
map to lemma ids
class LmAccumulator
LmAccumulator.
class LogSmoothingFunction
class Mapping
Mapping of label ids: base class implementing trivial mapping.
class MaximumTimeframeErrorAutomaton
maximum scoring
class MergeWordLattice
merge
class ModifyWordLattice
class MorphismAutomaton
struct Multiplier
class NaryMorphismAutomaton
class NBestListExtractor
NBestListExtractor Produces an n-best list with word boundaries.
struct PruneAndRemoveFail
struct Remover
struct SemiringChanger
class SigmoidSmoothingFunction
struct SingleBest
class SlaveWordLattice
class SmoothedFrameStateAccuracyAutomaton
SmoothedFrameStateAccuracyAutomaton.
class SmoothingFunction
class SoftFramePhoneAccuracyAutomaton
SoftFramePhoneAccuracyAutomaton.
class StandardWordLattice
A "normal" word lattice with acoustic and language model scores and word boundary information as it is produced by WordConditionedTreeSearch.
class SumTimeframeErrorAutomaton
sum scoring
class TdpAccumulator
TdpAccumulator.
class TimeConditionedWordLattice
class TimeframeErrorAutomaton
timeframe error automaton: base class
class TimeframeErrorDfsState
Calculate 1 - p_t(w_n|x_1,...,x_T) for each time frame and word index.
struct Trimmer
class TurnOffCompetingHypothesesLattice
turnOffCompetingHypotheses
class UnaryMorphismAutomaton
class UnsupervizedSmoothingFunction
class WeightedCachedAcousticAccumulator
WeightedCachedAcousticAccumulator.
class WeightedDensityCachedAcousticAccumulator
WeightedDensityCachedAcousticAccumulator.
class WeightedFramePhoneAccuracyAutomaton
WeightedFramePhoneAccuracyAutomaton.
class WordBoundaries
class WordBoundary
class WordLattice
class WordLatticeAdaptor
class WordLatticeDescription
class WordTimeframeAccuracyAutomaton
WordTimeframeAccuracyAutomaton.
class WordTimeframeAccuracyDfsState
WordTimeframeAccuracyDfsState.
Typedefs
typedef int8_t s8
typedef uint8_t u8
typedef int16_t s16
typedef uint16_t u16
typedef int32_t s32
typedef uint32_t u32
typedef int64_t s64
typedef uint64_t u64
typedef float f32
typedef double f64
typedef Fsa::SsspArcFilter Predicate
typedef Core::Ref< WordLattice > WordLatticeRef
typedef Core::Ref< const WordLattice > ConstWordLatticeRef
typedef std::unordered_set< Fsa::LabelId > ShortPauses
Enumerations
enum LatticeFormat {
formatFsa, formatHtk, formatLuna, formatLin,
formatSourceFile, formatWolfgang
}
enum Alphabet {
unknownAlphabet, lemmaPronunciationAlphabet, lemmaPronunciationAlphabetAcceptor, lemmaAlphabet,
syntacticTokenAlphabet, evaluationTokenAlphabet, noLexiconCheck
}
Functions
ConstWordLatticeRef getExactWordAccuracy (ConstWordLatticeRef lattice, const std::string &orth, Bliss::OrthographicParser *orthToLemma, Fsa::ConstAutomatonRef lemmaPronToLemma, Fsa::ConstAutomatonRef lemmaToEval)
Calculate the exact word accuracies.
ConstWordLatticeRef getExactPhonemeAccuracy (ConstWordLatticeRef lattice, const std::string &orth, Bliss::OrthographicParser *orthToLemma, Fsa::ConstAutomatonRef lemmaPronToPhoneme, Fsa::ConstAutomatonRef lemmaToPhoneme)
The same as getExactWordAccuracy() but for the phoneme accuracy.
ConstWordLatticeRef getApproximateAccuracy (Core::Ref< const ApproximateAccuracyAutomaton > a)
ConstWordLatticeRef getApproximateWordAccuracy (ConstWordLatticeRef lattice, ConstWordLatticeRef correct, const ShortPauses &shortPauses, bool useLemmata=false)
Calculate the approximate word accuracies after Povey.
ConstWordLatticeRef getApproximatePhoneAccuracy (ConstWordLatticeRef lattice, ConstWordLatticeRef correct, const ShortPauses &shortPauses, Speech::AlignmentGeneratorRef alignmentGenerator)
ConstWordLatticeRef getApproximatePhoneAccuracyMask (ConstWordLatticeRef lattice, ConstWordLatticeRef correct, const Speech::Confidences &mask, const ShortPauses &shortPauses, Speech::AlignmentGeneratorRef alignmentGenerator)
ConstWordLatticeRef getFramePhoneAccuracy (ConstWordLatticeRef lattice, ConstWordLatticeRef correct, const ShortPauses &shortPauses, Speech::AlignmentGeneratorRef alignmentGenerator, f32 normalization)
ConstWordLatticeRef getFrameStateAccuracy (ConstWordLatticeRef lattice, ConstWordLatticeRef correct, const ShortPauses &shortPauses, Speech::AlignmentGeneratorRef alignmentGenerator)
ConstWordLatticeRef getSoftFramePhoneAccuracy (ConstWordLatticeRef lattice, ConstWordLatticeRef correct, const ShortPauses &shortPauses, Speech::AlignmentGeneratorRef alignmentGenerator)
ConstWordLatticeRef getSoftFramePhoneAccuracy (ConstWordLatticeRef lattice, const Speech::Alignment &forcedAlignment, const ShortPauses &shortPauses, Speech::AlignmentGeneratorRef alignmentGenerator)
ConstWordLatticeRef getWeightedFramePhoneAccuracy (ConstWordLatticeRef lattice, ConstWordLatticeRef correct, const ShortPauses &shortPauses, Speech::AlignmentGeneratorRef alignmentGenerator, f32 beta, f32 margin)
ConstWordLatticeRef getApproximatePhoneAccuracy (ConstWordLatticeRef lattice, ConstWordLatticeRef correct, const ShortPauses &shortPauses, Core::Ref< Speech::PhonemeSequenceAlignmentGenerator > alignmentGenerator)
Calculate the approximate phone accuracies after Povey.
ConstWordLatticeRef getApproximatePhoneAccuracyMask (ConstWordLatticeRef lattice, ConstWordLatticeRef correct, const Speech::Confidences &mask, const ShortPauses &shortPauses, Core::Ref< Speech::PhonemeSequenceAlignmentGenerator > alignmentGenerator)
Calculate the approximate phone accuracies after Povey (as in getApproximatePhoneAccuracy), but the accuracy is masked based on the provided confidence alignment.
ConstWordLatticeRef getFramePhoneAccuracy (ConstWordLatticeRef lattice, ConstWordLatticeRef correct, const ShortPauses &shortPauses, Core::Ref< Speech::PhonemeSequenceAlignmentGenerator > alignmentGenerator, f32 normalization)
Calculate the frame phone accuracies after Wessel.
ConstWordLatticeRef getFrameStateAccuracy (ConstWordLatticeRef lattice, ConstWordLatticeRef correct, const ShortPauses &shortPauses, Core::Ref< Speech::PhonemeSequenceAlignmentGenerator > alignmentGenerator)
Calculate the frame state accuracies (aka state-based Hamming distance).
ConstWordLatticeRef getSoftFramePhoneAccuracy (ConstWordLatticeRef lattice, ConstWordLatticeRef correct, const ShortPauses &shortPauses, Core::Ref< Speech::PhonemeSequenceAlignmentGenerator > alignmentGenerator)
Calculate the soft frame phone accuracies for.
ConstWordLatticeRef getSoftFramePhoneAccuracy (ConstWordLatticeRef lattice, const Speech::Alignment &forcedAlignment, const ShortPauses &shortPauses, Core::Ref< Speech::PhonemeSequenceAlignmentGenerator > alignmentGenerator)
ConstWordLatticeRef getWeightedFramePhoneAccuracy (ConstWordLatticeRef lattice, ConstWordLatticeRef correct, const ShortPauses &shortPauses, Core::Ref< Speech::PhonemeSequenceAlignmentGenerator > alignmentGenerator, f32 beta, f32 margin=0)
Calculate the weighted frame phone accuracies according to MCE on state level.
ConstWordLatticeRef multiply (ConstWordLatticeRef l, Fsa::Weight value)
ConstWordLatticeRef multiply (ConstWordLatticeRef lattice, const std::vector< Fsa::Weight > &values)
ConstWordLatticeRef extend (ConstWordLatticeRef l, Fsa::Weight value)
ConstWordLatticeRef extendFinal (ConstWordLatticeRef l, Fsa::Weight value)
ConstWordLatticeRef expm (ConstWordLatticeRef l)
ConstWordLatticeRef linearCombination (ConstWordLatticeRef lattice, const std::vector< Fsa::Weight > &scales)
ConstWordLatticeRef linearCombination (ConstWordLatticeRef lattice, const Core::StringHashMap< std::vector< Fsa::Weight >> &outputs)
ConstWordLatticeRef getParts (ConstWordLatticeRef lattice, const std::vector< std::string > &parts)
ConstWordLatticeRef getPart (ConstWordLatticeRef lattice, const std::string &part)
ConstWordLatticeRef isGreaterEqual (ConstWordLatticeRef l, Fsa::Weight threshold)
ConstWordLatticeRef normalize (ConstWordLatticeRef lattice)
ConstWordLatticeRef trim (ConstWordLatticeRef lattice, bool progress)
ConstWordLatticeRef partial (ConstWordLatticeRef lattice, Fsa::StateId initial)
ConstWordLatticeRef partial (ConstWordLatticeRef lattice, Fsa::StateId initial, Fsa::Weight additionalFinalWeight)
ConstWordLatticeRef changeSemiring (ConstWordLatticeRef lattice, Fsa::ConstSemiringRef semiring)
bool isEmpty (ConstWordLatticeRef lattice)
f32 density (ConstWordLatticeRef)
number of arcs per timeframe
std::pair< u32, u32 > densityInfo (ConstWordLatticeRef wordLattice)
u32 nArcs (ConstWordLatticeRef lattice, Predicate pred)
std::pair< Fsa::Weight, Fsa::Weight > minMaxWeights (ConstWordLatticeRef lattice)
template<class Modifier >
ConstWordLatticeRef apply (ConstWordLatticeRef lattice, Modifier &m, bool copyWordBoundaries=true)
ConstWordLatticeRef nbest (ConstWordLatticeRef l, u32 n)
ConstWordLatticeRef best (ConstWordLatticeRef lattice, bool listFormat)
ConstWordLatticeRef cache (ConstWordLatticeRef l, u32 maxAge)
ConstWordLatticeRef composeMatching (Fsa::ConstAutomatonRef left, ConstWordLatticeRef right, bool reportUnknowns=true)
remember that for the intersection of a word lattice with an automaton the automaton needs to be deterministic to avoid path duplicating important for word posterior probabilities
ConstWordLatticeRef composeMatching (ConstWordLatticeRef left, Fsa::ConstAutomatonRef right, bool reportUnknowns)
ConstWordLatticeRef composeLm (ConstWordLatticeRef left, Core::Ref< const Lm::ScaledLanguageModel > right, f32 pronunciationScale)
Corresponds to Lm::compose but the word boundaries are restored.
ConstWordLatticeRef timeConditionedWordLattice (ConstWordLatticeRef in)
ConstWordLatticeRef merge (ConstWordLatticeRef numerator, ConstWordLatticeRef denominator, Core::Ref< const Lm::LanguageModel >)
ConstWordLatticeRef extractNumerator (const std::string &orth, ConstWordLatticeRef denominator, Bliss::OrthographicParser *orthToLemma, Fsa::ConstAutomatonRef lemmaPronToLemma, Fsa::ConstAutomatonRef lemmaToLemmaConfusion)
extractNumerator
ConstWordLatticeRef turnOffCompetingHypotheses (const std::string &orth, ConstWordLatticeRef denominator, Bliss::OrthographicParser *orthToLemma, Fsa::ConstAutomatonRef lemmaPronToLemma, Fsa::ConstAutomatonRef lemmaToLemmaConfusion)
Generate a lattice which shares the topology with.
ConstWordLatticeRef resolveMorphism (ConstWordLatticeRef l, Core::Ref< const WordBoundaries > wordBoundaries, Fsa::ConstMappingRef morphism)
ConstWordLatticeRef resolveNaryMorphism (ConstWordLatticeRef l, const Core::Vector< Core::Ref< const WordBoundaries >> &wordBoundaries, const Core::Vector< Fsa::ConstMappingRef > &morphisms)
ConstWordLatticeRef posterior (ConstWordLatticeRef lattice, Fsa::Weight &totalInv, s32 tol)
ConstWordLatticeRef posterior (ConstWordLatticeRef lattice, f64 &totalInv, s32 tol)
ConstWordLatticeRef posterior (ConstWordLatticeRef lattice, s32 tol)
ConstWordLatticeRef checkPosterior (ConstWordLatticeRef lattice, s32 tolerance)
ConstWordLatticeRef prune (ConstWordLatticeRef lattice, const Fsa::Weight &threshold, bool relative, bool backward, bool hasFailArcs)
ConstWordLatticeRef transpose (ConstWordLatticeRef l, bool progress, WordBoundary final)
ConstWordLatticeRef unite (ConstWordLatticeRef l1, ConstWordLatticeRef l2)
ConstWordLatticeRef unite (const Core::Vector< ConstWordLatticeRef > &lattices)
ConstWordLatticeRef removeEpsilons (ConstWordLatticeRef l)
ConstWordLatticeRef removeFailures (ConstWordLatticeRef l)
ConstWordLatticeRef getSmoothedFrameStateAccuracy (ConstWordLatticeRef lattice, ConstWordLatticeRef correct, Speech::AlignmentGeneratorRef alignmentGenerator, SmoothingFunction &smoothing)
ConstWordLatticeRef getSmoothedFrameStateAccuracy (ConstWordLatticeRef lattice, ConstWordLatticeRef correct, Core::Ref< Speech::PhonemeSequenceAlignmentGenerator > alignmentGenerator, SmoothingFunction &smoothingFunction)
Calculate the smoothed frame state accuracies (cf.
ConstWordLatticeRef staticCopy (ConstWordLatticeRef l, const std::vector< std::string > &names)
ConstWordLatticeRef staticCopy (ConstWordLatticeRef l, const std::string &name)
ConstWordLatticeRef staticCopy (ConstWordLatticeRef l)
ConstWordLatticeRef getSumTimeframeErrors (ConstWordLatticeRef total, const ShortPauses &shortPauses, bool useLemmata, f32 normalization)
Calculate the summed timeframe errors.
ConstWordLatticeRef getMaximumTimeframeErrors (ConstWordLatticeRef total, const ShortPauses &shortPauses, bool useLemmata)
Calculate the maximum timeframe errors.
ConstWordLatticeRef getWordTimeframeAccuracy (ConstWordLatticeRef lattice, ConstWordLatticeRef correct, const ShortPauses &shortPauses, bool useLemmata, f32 normalization)
Calcluate the word timeframe accuracy.
bool dumpWordBoundaries (Core::Ref< const WordBoundaries > wordBoundaries, Core::XmlWriter &xo)
bool dumpWordBoundaries (Core::Ref< const WordBoundaries > wordBoundaries, const std::string &file)
std::wstring widen (const std::string &)
Convert UTF-8 Unicode string to wide character string (UCS-4)
std::string narrow (const std::wstring &)
Convert wide character (UCS-4) Unicode string to UTF-8.
size_t __stl_hash_wstring (const wchar_t *__s)
Detailed Description
Copyright 2020 RWTH Aachen University.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Function Documentation
ConstWordLatticeRef Lattice::composeLm (ConstWordLatticeRef left, Core::Ref< const Lm::ScaledLanguageModel > right, f32 pronunciationScale)
Corresponds to Lm::compose but the word boundaries are restored.
Advantage: no sentence hypotheses are duplicated by construction of the Lm::compose and, thus, no determinisation is needed beforehand. See Lm/Compose.hh for further comments.
Definition at line 75 of file Lattice/Compose.cc.
References Lm::ComposeAutomaton::mapToLeft(), Lattice::Core::ref(), and require.
ConstWordLatticeRef Lattice::composeMatching (Fsa::ConstAutomatonRef left, ConstWordLatticeRef right, bool reportUnknowns)
remember that for the intersection of a word lattice with an automaton the automaton needs to be deterministic to avoid path duplicating important for word posterior probabilities
Definition at line 23 of file Lattice/Compose.cc.
References Lattice::Core::ref().
Referenced by Lattice::HtkReader::addState(), extractNumerator(), and Speech::MinimumBayesRiskSearchNode::~MinimumBayesRiskSearchNode().
f32 Lattice::density (ConstWordLatticeRef wordLattice)
number of arcs per timeframe
Definition at line 149 of file Lattice/Basic.cc.
References Ftl::DfsState< _Automaton >::dfs().
Referenced by Lattice::DensityDfsState::finish().
ConstWordLatticeRef Lattice::extractNumerator (const std::string & orth, ConstWordLatticeRef denominator, Bliss::OrthographicParser * orthToLemma, Fsa::ConstAutomatonRef lemmaPronToLemma, Fsa::ConstAutomatonRef lemmaToLemmaConfusion)
extractNumerator
Extract all sentence hypotheses from.
Parameters
denominator which share the orthography
orth.
Definition at line 299 of file Merge.cc.
References composeMatching().
Referenced by Speech::OrthographyTimeAlignmentBasedMetricLatticeBuilder::OrthographyTimeAlignmentBasedMetricLatticeBuilder(), Speech::WordLatticeUnion::processWordLattice(), Speech::NumeratorFromDenominatorExtractor::processWordLattice(), and Speech::NumeratorFromDenominatorNode::work().
ConstWordLatticeRef Lattice::getApproximatePhoneAccuracy (ConstWordLatticeRef lattice, ConstWordLatticeRef correct, const ShortPauses & shortPauses, Core::Ref< Speech::PhonemeSequenceAlignmentGenerator > alignmentGenerator)
Calculate the approximate phone accuracies after Povey.
Parameters
correct represents the reference hypotheses (aka numerator lattice).
shortPauses defines label ids which are discarded for the accuracy like for example silence. Remarks: 1) Unlike Povey the phone boundaries are not given. 2) The phone accuracies of a word arc are accumulated and stored as arc weight.
correct must have confidences as arc weights.
The resulting word lattice has the same topology and identical state ids as the
Parameters
lattice.
ConstWordLatticeRef Lattice::getApproximatePhoneAccuracyMask (ConstWordLatticeRef lattice, ConstWordLatticeRef correct, const Speech::Confidences & mask, const ShortPauses & shortPauses, Core::Ref< Speech::PhonemeSequenceAlignmentGenerator > alignmentGenerator)
Calculate the approximate phone accuracies after Povey (as in getApproximatePhoneAccuracy), but the accuracy is masked based on the provided confidence alignment.
ConstWordLatticeRef Lattice::getApproximateWordAccuracy (ConstWordLatticeRef lattice, ConstWordLatticeRef correct, const ShortPauses & shortPauses, bool useLemmata = false)
Calculate the approximate word accuracies after Povey.
Parameters
correct represents the reference hypotheses (aka numerator lattice).
shortPauses defines label ids which are discarded for the accuracy like for example silence. By default the accuracies are calculated on the lemma pronunciations. Optionally the accuracies can be calculated on the lemmata, cf.
useLemmata. This is useful if
correct does not contain all pronunciation variants (at the moment the numerator lattices do not contain pronunciation variants).
correct must have confidences as arc weights.
The resulting word lattice has the same topology and identical state ids as the
Parameters
lattice.
Definition at line 648 of file Accuracy.cc.
Referenced by Speech::ArchiveApproximateWordAccuracyLatticeBuilder::ArchiveApproximateWordAccuracyLatticeBuilder(), and Speech::OrthographyApproximateWordAccuracyLatticeBuilder::OrthographyApproximateWordAccuracyLatticeBuilder().
ConstWordLatticeRef Lattice::getExactPhonemeAccuracy (ConstWordLatticeRef lattice, const std::string & orth, Bliss::OrthographicParser * orthToLemma, Fsa::ConstAutomatonRef lemmaPronToPhoneme, Fsa::ConstAutomatonRef lemmaToPhoneme)
The same as getExactWordAccuracy() but for the phoneme accuracy.
Note that the phoneme accuracies are represented on word level, i.e. the output is a word lattice.
Definition at line 282 of file Accuracy.cc.
References Lattice::WordLattice::accuracyFsa, and Fsa::multiply().
ConstWordLatticeRef Lattice::getExactWordAccuracy (ConstWordLatticeRef lattice, const std::string & orth, Bliss::OrthographicParser * orthToLemma, Fsa::ConstAutomatonRef lemmaPronToLemma, Fsa::ConstAutomatonRef lemmaToEval)
Calculate the exact word accuracies.
Parameters
orth is the reference orthography.
The resulting word lattice contains the same hypotheses as
Parameters
lattice but the topology may be different.
Definition at line 168 of file Accuracy.cc.
References Lattice::WordLattice::accuracyFsa.
ConstWordLatticeRef Lattice::getFramePhoneAccuracy (ConstWordLatticeRef lattice, ConstWordLatticeRef correct, const ShortPauses & shortPauses, Core::Ref< Speech::PhonemeSequenceAlignmentGenerator > alignmentGenerator, f32 normalization)
Calculate the frame phone accuracies after Wessel.
Parameters
correct represents the reference hypotheses (aka numerator lattice).
shortPauses defines label ids which are discarded for the accuracy like for example silence. Remarks: 1) The phone accuracies of a word arc are accumulated and stored as arc weight.
The resulting word lattice has the same topology and identical state ids as the
Parameters
lattice.
ConstWordLatticeRef Lattice::getFrameStateAccuracy (ConstWordLatticeRef lattice, ConstWordLatticeRef correct, const ShortPauses & shortPauses, Core::Ref< Speech::PhonemeSequenceAlignmentGenerator > alignmentGenerator)
Calculate the frame state accuracies (aka state-based Hamming distance).
Parameters
correct represents the reference hypotheses (aka numerator lattice). Remarks: 1) The accuracies are accumulated and stored as word arc weight.
The resulting word lattice has the same topology and identical state ids as
Parameters
lattice.
ConstWordLatticeRef Lattice::getMaximumTimeframeErrors (ConstWordLatticeRef total, const ShortPauses & shortPauses, bool useLemmata)
Calculate the maximum timeframe errors.
Definition at line 278 of file Lattice/TimeframeError.cc.
ConstWordLatticeRef Lattice::getSmoothedFrameStateAccuracy (ConstWordLatticeRef lattice, ConstWordLatticeRef correct, Core::Ref< Speech::PhonemeSequenceAlignmentGenerator > alignmentGenerator, SmoothingFunction & smoothingFunction)
Calculate the smoothed frame state accuracies (cf.
state-based Hamming distance).
Parameters
correct represents the reference hypotheses (aka numerator lattice). The arc weights are assumed to be set to the word posteriors.
smoothingFunction implementation of smoothing function f.
Returns
: word lattice with the same topology as
Parameters
lattice but with arc weights set to {t}f'(E[{spk,t}]){spk,t} where E[{spk,t}] are the accumulated posteriors of
correct at timeframe t. Remark: The accuracies are accumulated and stored as word arc weight.
ConstWordLatticeRef Lattice::getSoftFramePhoneAccuracy (ConstWordLatticeRef lattice, ConstWordLatticeRef correct, const ShortPauses & shortPauses, Core::Ref< Speech::PhonemeSequenceAlignmentGenerator > alignmentGenerator)
Calculate the soft frame phone accuracies for.
Parameters
lattice after Zheng.
correct represents the reference hypotheses (aka numerator lattice), which contains the posteriors.
shortPauses defines label ids which are discarded for the accuracy like for example silence. Remarks: 1) The phone accuracies of a word arc are accumulated and stored as arc weight.
The resulting word lattice has the same topology and identical state ids as the
Parameters
lattice.
ConstWordLatticeRef Lattice::getSumTimeframeErrors (ConstWordLatticeRef total, const ShortPauses & shortPauses, bool useLemmata, f32 normalization)
Calculate the summed timeframe errors.
Parameters
total contains the total scores.
normalization 1 = normalization on word level 0 = normalization on timeframe level
Definition at line 263 of file Lattice/TimeframeError.cc.
ConstWordLatticeRef Lattice::getWeightedFramePhoneAccuracy (ConstWordLatticeRef lattice, ConstWordLatticeRef correct, const ShortPauses & shortPauses, Core::Ref< Speech::PhonemeSequenceAlignmentGenerator > alignmentGenerator, f32 beta, f32 margin = 0)
Calculate the weighted frame phone accuracies according to MCE on state level.
Parameters
correct represents the reference hypotheses (aka numerator lattice).
shortPauses defines label ids which are discarded for the accuracy like for example silence. Remarks: 1) The phone accuracies of a word arc are accumulated and stored as arc weight.
The resulting word lattice has the same topology and identical state ids as the
Parameters
lattice.
ConstWordLatticeRef Lattice::getWordTimeframeAccuracy (ConstWordLatticeRef lattice, ConstWordLatticeRef correct, const ShortPauses & shortPauses, bool useLemmata, f32 normalization)
Calcluate the word timeframe accuracy.
Definition at line 382 of file Lattice/TimeframeError.cc.
Referenced by Speech::OrthographySmoothedFrameStateAccuracyLatticeBuilder::OrthographySmoothedFrameStateAccuracyLatticeBuilder().
ConstWordLatticeRef Lattice::merge (ConstWordLatticeRef numerator, ConstWordLatticeRef denominator, Core::Ref< const Lm::LanguageModel >)
Parameters
numerator is incorporated into
denominator without duplicating sentence hypotheses of
denominator. The resulting word lattice is word-conditioned w.r.t. the given language model.
Definition at line 285 of file Merge.cc.
Referenced by Speech::WordLatticeMerger::processWordLattice().
std::string Lattice::narrow (const std::wstring &)
Convert wide character (UCS-4) Unicode string to UTF-8.
Definition at line 86 of file Unicode.cc.
References ensure, and require.
ConstWordLatticeRef Lattice::turnOffCompetingHypotheses (const std::string & orth, ConstWordLatticeRef denominator, Bliss::OrthographicParser * orthToLemma, Fsa::ConstAutomatonRef lemmaPronToLemma, Fsa::ConstAutomatonRef lemmaToLemmaConfusion)
Generate a lattice which shares the topology with.
Parameters
denominator,and the arc weights are set as follows: weight of input
denominator a path corresponding to the orthography
orth goes through this arc 0: otherwise
Definition at line 408 of file Merge.cc.
std::wstring Lattice::widen (const std::string &)
Convert UTF-8 Unicode string to wide character string (UCS-4)
Definition at line 39 of file Unicode.cc.
References require.