Sprint: Flow Namespace Reference
Flow Namespace Reference
Copyright 2020 RWTH Aachen University.
Classes
class _Filter
Flow filter identifier.
class AbsoluteValueFunction
class AbstractNode
Abstract flow network node.
class AdditionFunction
class AdjacentDifference
Calculates the differences of adjacent elements.
class Aggregate
Aggregate of Flow objects Aggregate collects objects of different streams into one object.
class AggregationNode
Aggregation filter.
struct ArchiveWriter
class Attributes
Set of Flow network attributes.
class Cache
class Cacheable
class Cached
class CacheNode
class CacheReader
class CacheWriter
class CollectorNode
Abstract base class for nodes merging several packets into one stream, e.g.
struct Converter
Base class for converter functors.
class CoprusKeyMapNode
class CopyMalformedPolicy
class CosFunction
class CutterNode
Flow network.
class Data
Base class for Data class in Flow Features: -Multithread safe reference counting.
class DataAdaptor
Predefinition of DataAdaptor.
class DataPtr
Class template for Data smart pointers Extends the features of Core::TsRef by: -up and down cast using dynamic_cast -makePrivate() which ensures that the object is referenced only by this DataPtr.
class DataSource
Flow::Network handling several ports.
class Datatype
Flow data type identifier.
class DatatypeTemplate
Flow data type definition.
class DemoNode
class DismissMalformedPolicy
class DumpNode
Flow network.
class EnergyFunction
EnergyFunction: energy of input vector energy = sum_i |x_i|^2.
class ExpFunction
class ExternalInput
Wrapper for network input port Supported features:
class Filter
Flow filter definition.
class FloorMalformedPolicy
class KeepMalformedPolicy
class Link
class LnFunction
class LogFunction
class LogPlusFunction
class MaximumFunction
class MergerNode
Abstract base class for nodes merging several packets into one packet, e.g.
class MinimumFunction
class Module_
class MultiplicationFunction
class NamedVector
Flow::Vector extended by an identifier.
class Network
Flow network class.
class NetworkParser
NetworkParser.
class NetworkTemplate
NetworkTemplate.
class Node
Abstract flow network node.
class NodeBuilder
NodeBuilder.
class NormFunction
NormFunction: parameter-th norm of input vector norm = (sum_i |x_i|^parameter)^{1/parameter}.
class PipeNode
class PowerFunction
class Queue
class Registry_
central registry for Flow filters and datatypes.
class RepeaterNode
Flow network repeater.
struct ScalarToStringConverter
Converts scalar In to String.
struct ScalarToVectorConverter
Converts In to Vector<Out> of size 1.
class SequenceFilterNode
Filters input sequence according to a selection object.
class SimpleFunction
Base class for functions vith one parameter.
class SimpleFunctionNode
class SinkNode
Base class for nodes with a single input.
class SleeveNode
class SourceNode
Base class for nodes with a single output.
class SqrtFunction
struct StringConverter
Converts String to Out.
class StringExpressionNode
String expression resolved by node inputs.
class Synchronization
Synchronization: ensures that the input stream has the same number of elements and the same start-times than "target-time" stream.
class SynchronizationNode
Base class for algorithms which synchronise the input stream to a "target" stream according to the start-times.
class Timestamp
Base class for Flow packets with time stamp information.
class TimestampCopy
TimestampCopy: copy timestamps of the target stream to the input stream.
class TypeConverterNode
Converts object of type C::InputType to type C::OutputType by using the functor C.
class TypedAggregate
Aggregate of instances of class T.
class TypedAggregateNode
Pointer Vector Filter.
class TypedDisaggregateNode
class Vector
Vector.
class VectorAbsoluteValueFunction
class VectorAbsValDumpNode
Dump node for vector absolutes.
class VectorConcatNode
Vector concatenation filter.
struct VectorConverter
Converts Vector<In> to Vector<Out>
class VectorCosFunction
class VectorDemultiplexNode
class VectorExpFunction
class VectorInterleaveNode
Vector interleave filter.
class VectorLinearFunction
SimpleFunctionNode for neural network activation function LINEAR y_i = x_i.
class VectorLnFunction
class VectorLnFunctionSave
Add small value to avoid -infs.
class VectorLogFunction
class VectorLogPlusFunction
class VectorMalformed
class VectorMalformedNode
class VectorMaximumFunction
class VectorMinimumFunction
class VectorMultNode
class VectorPowerFunction
class VectorQuantizationFunction
Quantize (i.e.
class VectorScalarAdditionFunction
class VectorScalarFunction
Base class for vector-scalar functions.
class VectorScalarFunctionNode
VectorScalarFunctionNode maps a vector to a scalar value.
class VectorScalarMultiplicationFunction
class VectorSelectNode
Allow to select elemnts from a feature vector without resorting to concat and split Parameter selection takes form of 0-2,2,4,5,23-234,2-3 where 23-234 is the range from dimension 23 up to 234 (234 included) Original code by Christian Plahl.
class VectorSequenceNode
class VectorSigmoidFunction
SimpleFunctionNode for neural network activation function SIGMOID y_i = 1 / (1 + EXP(-x_i))
class VectorSoftmaxFunction
SimpleFunctionNode for neural network activation function SOFTMAX y_i = EXP(x_i - MAX(x)) / SUM(EXP(x_i - MAX(i)))
class VectorSplitNode
class VectorSqrtFunction
class VectorSumNode
class VectorTanhFunction
SimpleFunctionNode for neural network activation function TANH y_i = TANH(x_i)
class VectorTextInputNode
VectorTextInputNode: data source using XML input.
class VectorTextInputNodeBase
struct VectorToScalarConverter
Converts Vector<In> of size 1 to Out.
class WarpTimeFilterNode
Makes the timeframes of the incoming packets consecutive, and logs a warping map which describes the applied mapping.
class WeakSynchronizationNode
Typedefs
typedef DataAdaptor< f32 > Float32
Network timestamp adaptor for type f32.
typedef DataAdaptor< f64 > Float64
Network timestamp adaptor for type f64.
typedef DataAdaptor< std::string > String
Network string class with timestamp.
typedef Core::SingletonHolder< Module_ > Module
typedef Core::SingletonHolder< Registry_ > Registry
typedef s32 PortId
typedef f64 Time
Time interval or point in time measures in seconds.
Functions
template<class T >
DataPtr< T > dataPtr (T *o)
Convenience constructors for DataPtr smart pointers.
template<class Type , class NetworkData >
Core::XmlWriter & operator<< (Core::XmlWriter &o, const DataAdaptor< Type, NetworkData > &v)
template<class Type , class NetworkData >
Core::BinaryOutputStream & operator<< (Core::BinaryOutputStream &o, const DataAdaptor< Type, NetworkData > &v)
template<class Type , class NetworkData >
Core::BinaryInputStream & operator>> (Core::BinaryInputStream &i, DataAdaptor< Type, NetworkData > &v)
template<class T >
Core::XmlWriter & operator<< (Core::XmlWriter &o, const Vector< T > &v)
template<class T >
Core::BinaryOutputStream & operator<< (Core::BinaryOutputStream &o, const Vector< T > &v)
template<class T >
Core::BinaryInputStream & operator>> (Core::BinaryInputStream &i, Vector< T > &v)
template<class T >
Core::XmlWriter & operator<< (Core::XmlWriter &o, const NamedVector< T > &v)
template<class T >
Core::BinaryOutputStream & operator<< (Core::BinaryOutputStream &o, const NamedVector< T > &v)
template<class T >
Core::BinaryInputStream & operator>> (Core::BinaryInputStream &i, NamedVector< T > &v)
Variables
const Core::ParameterBool paramCollectorNodeCheckSameLength ("check-same-length","if true, error raised if input streams are of different length", false)
Switches on/off the check of length input streams.
const Core::ParameterString paramCollectorNodeTimestampPortName ("timestamp-port","name of port to take timestamps from")
const Core::ParameterFloat paramExternalInputSampleRate ("sample-rate","sample rate/frequency of input the data", 16000, 1)
const Core::ParameterFloat paramSimpleFunctionParameter ("value","parametric value", 0)
SimpleFunctionNode template for functions with one parameter.
Core::ParameterBool paramSynchronizationIgnoreErrors ("ignore-errors","ignore if the synchronization algorithm fails", false)
Ignore if the algorithm could not create a synchronised element for a target start-time.
static const s32 IllegalPortId = -1
const Time timeTolerance = (Time)1e7
const s32 timeToleranceUlp = 100000
const Core::ParameterInt parameterTrack ("track","track number 0, 1, 2, ...", 0, 0)
const Core::ParameterFloat paramVectorScalarFunctionParameter ("value","parametric value", 0)
const Core::ParameterBool paramVectorSequenceNodeReverse ("reverse","if true, indices run backwards starting at the back of the inputs", false)
Vector sequence filter.
const Core::ParameterBool paramVectorSequenceNodeTimeStamp ("timestamp","if true, change timestamp in the sequence", false)
const Core::ParameterBool paramVectorSplitNodeReverse ("reverse","if true, indices run backwards starting at the back of the input vector", false)
const Core::ParameterBool paramVectorSplitNodeTimeStamp ("timestamp","if true, split timestamp too", false)
Detailed Description
Copyright 2020 RWTH Aachen University.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Typedef Documentation
typedef DataAdaptor<f32> Flow::Float32
Network timestamp adaptor for type f32.
Definition at line 26 of file DataAdaptor.hh.
typedef DataAdaptor<f64> Flow::Float64
Network timestamp adaptor for type f64.
Definition at line 33 of file DataAdaptor.hh.
typedef DataAdaptor<std::string> Flow::String
Network string class with timestamp.
Definition at line 37 of file DataAdaptor.hh.
typedef f64 Flow::Time
Time interval or point in time measures in seconds.
Definition at line 32 of file Flow/Types.hh.
Function Documentation
template<class T > DataPtr<T> Flow::dataPtr (T * o) inline
Convenience constructors for DataPtr smart pointers.
Definition at line 261 of file Data.hh.
Referenced by Signal::SlidingAlgorithmNode< Algorithm >::flushAllAndPut(), Signal::AutocorrelationToAutoregressionNode::work(), and Signal::LinearFilterNode::work().
Variable Documentation
const Core::ParameterBool Flow::paramCollectorNodeCheckSameLength("check-same-length","if true, error raised if input streams are of different length", false)
Switches on/off the check of length input streams.
If on and input streams have different length, a critical error is raised.
Referenced by Flow::CollectorNode< I, O >::setParameter().
const Core::ParameterFloat Flow::paramSimpleFunctionParameter("value","parametric value", 0)
SimpleFunctionNode template for functions with one parameter.
Referenced by Flow::SimpleFunctionNode< Function >::setParameter().
Core::ParameterBool Flow::paramSynchronizationIgnoreErrors
Ignore if the algorithm could not create a synchronised element for a target start-time.
Definition at line 87 of file Synchronization.hh.
Referenced by Flow::SynchronizationNode< Algorithm >::setParameter().
const Core::ParameterBool Flow::paramVectorSequenceNodeReverse("reverse","if true, indices run backwards starting at the back of the inputs", false)
Vector sequence filter.
All input packets must be vectors, which will be put into a sequence of vectors.
Inputs: many (e.g extracted at same timestamp), dynamically generated. Outputs: the same, but on one stream. All inputs consume the same number of packets. The dimension of each output vector will be the same than each input vector.
Todo:
check the time stamps of the input and output vectors
Referenced by Flow::VectorSequenceNode< T >::setParameter().