Sprint: Lattice::Core Namespace Reference
Lattice::Core Namespace Reference
Copyright 2020 RWTH Aachen University.
Classes
struct absoluteValue
absoluteValue: functor for absolute value
class AbstractChoiceParameter
Base class template for multiple-choice parameters.
class AbstractParameter
Abstract base class for parameter declaration.
class Application
Application class:
class BinaryInputStream
BinaryInputStream.
class BinaryInputStreams
class BinaryOutputStream
BinaryOutputStream.
class BinaryStream
class BinaryStreamIos
class Channel
Configurable text output stream.
class CharsetConverter
class Choice
Choice class.
class ChoiceStatistics
class Component
Base class for configurable components with logging and error logging facilities.
class composedBinaryFunction
Functor for f(g(x), h(y))
class Condition
A condition variable.
class Configurable
Abstract base class for run-time configurable classes.
class Configuration
Central configuration class.
struct conversion
Generic unary functor for type conversion.
class Dependable
class Dependency
class DependencySet
class Description
Vector of stream descriptions Stream descriptions if a set of attributes describing a (feature) stream.
class HashMap
class HistogramStatistics
A histogram statistics class for simple unsigned integers.
class LockingPointer
A thread-safety smart pointer.
struct maximum
max: functor for max function
struct minimum
min: functor for min function
class Mutex
A mutex.
class MutexLock
Lock mutex in current scope.
class NameHelper
Use this class for naming your basic classes.
class NameHelper< bool >
class NameHelper< Mm::AbstractMixtureSet >
class NameHelper< Mm::MixtureSet >
class NameHelper< std::complex< T > >
class NameHelper< std::string >
class NameHelper< std::vector< T > >
class Parameter
Base class template for parameter declaration.
class ParameterBitVector
Declaration class for bit vector parameters.
class ParameterBool
Declaration class for boolean valued parameters.
class ParameterChoice
Declaration class for discrete multiple-choice parameters.
class ParameterFloat
Declaration class for floating point parameters.
class ParameterFloatVector
Declaration class for float vector parameters.
class ParameterInt
Declaration class for integer valued parameters.
class ParameterIntVector
Declaration class for int vector parameters.
class ParameterString
Declaration class for string parameters.
class ParameterStringVector
Declaration class for string vector parameters.
class ParameterWeightVector
Declaration class for weight vector parameters.
struct PointerHash
struct power
power: functor for pow function
class RangedParameter
Base class template for parameters with lower und upper bounds.
class ReadWriteLock
A read-write lock.
class Ref
Class template for smart pointers using intrusive reference-counting.
class ReferenceCounted
Base class for reference-counted objects.
class Statistics
struct StringEquality
struct StringHash
class StringHashMap
class StringHashSet
class TextInputStream
Stream for text input.
class TextOutputStream
Stream for text output.
class Thread
Abstract Thread.
class tied
A helper for conveniently assigning the two values from a pair into separate variables.
class Timer
struct Type
Static information about elementary types.
struct Type< f32 >
struct Type< f64 >
struct Type< s16 >
struct Type< s32 >
struct Type< s64 >
struct Type< s8 >
struct Type< u16 >
struct Type< u32 >
struct Type< u64 >
struct Type< u8 >
class UnicodeInputConverter
Converter for reading text data.
class UnicodeOutputConverter
Converter for writing text data.
class VectorParameter
Base class template for vector parameter declaration.
class VersionRegistry
Access to source code version information.
class WeakRef
Class template for smart pointers provining weak referencing.
class WeakRefBase
Base class of the WeakRef template.
class XmlAttribute
Streaming objects for XML output.
class XmlBlank
A blank character.
class XmlChannel
Configurable XML output stream.
class XmlClose
class XmlCloseComment
class XmlComment
class XmlEmpty
class XmlFull
class XmlOpen
class XmlOpenComment
class XmlOutputStream
Stream for writing XML files.
class XmlWriter
Stream adaptor for producing XML output.
Functions
template<size_t size>
void swapEndianess (void *buf, size_t count=1)
Change endianess of a block of data.
template<>
void swapEndianess< 1 > (void *buf, size_t count)
void normalizeWhitespace (std::string &s)
Definition: A string has "normalized whitespace" if and only if it matches one the following regular expressions: (+)* or (+)* + where matches any non-whitespace character.
void enforceTrailingBlank (std::string &s)
Ensure that a string ends with a single blank character.
void suppressTrailingBlank (std::string &s)
Remove trailing blank character.
bool isWhitespaceNormalized (const std::string &s, char trailingBlank=prohibitTrailingBlank)
Test if a string is whitespace-normalized.
void stripWhitespace (std::string &)
Remove leading and trailing whitespace.
std::string convertToLowerCase (const std::string &)
Convert UTF-8 string to lower case.
std::string convertToUpperCase (const std::string &)
Convert UTF-8 string to upper case.
std::string form (const char *format,...) __attribute__((format(printf
Formatted output conversion.
std::string std::string vform (const char *format, va_list args)
std::vector< std::string > split (const std::string &string, const std::string &separator)
Split string into tokens.
bool startsWith (const std::string &string, const std::string &search)
Like the python startswith method of strings.
template<typename T >
bool strconv (const std::string &, T &)
Convinient functions to parse strings.
template<typename T >
bool strconv (const std::string &, T &, const Choice &)
Maps a given string to value of type T via the given Choice object; returns true on successful mapping.
template<typename T >
bool str2vector (const std::string &, std::vector< T > &, const std::string &elemDelim)
String to list conversion.
template<typename T >
bool str2vector (const std::string &, std::vector< T > &, const std::string &elemDelim, const std::string &rangeDelim, const T &min=Core::Type< T >::min, const T &max=Core::Type< T >::max, const T &step=T(1))
template<typename T >
bool str2vector (const std::string &, std::vector< T > &, const std::string &elemDelim, const std::string &rangeDelim, const std::string &assignDelim, const T &min=Core::Type< T >::min, const T &max=Core::Type< T >::max, const T &step=T(1))
template<typename T >
std::string vector2str (const std::vector< T > &vec, const std::string &elemDelim=" ")
convert vector to string, elements are separated by elemDelim
template<typename Signed >
bool str2signed (const std::string &s, Signed &i)
Primitive data type conversion.
template<typename Unsigned >
bool str2unsigned (const std::string &s, Unsigned &u)
template<typename Float >
bool str2float (const std::string &s, Float &f)
template<>
bool strconv< bool > (const std::string &s, bool &b)
template<>
bool strconv (const std::string &s, s8 &i)
template<>
bool strconv (const std::string &s, s16 &i)
template<>
bool strconv (const std::string &s, s32 &i)
template<>
bool strconv (const std::string &s, s64 &i)
template<>
bool strconv (const std::string &s, u8 &u)
template<>
bool strconv (const std::string &s, u16 &u)
template<>
bool strconv (const std::string &s, u32 &u)
template<>
bool strconv (const std::string &s, u64 &u)
template<>
bool strconv (const std::string &s, f32 &f)
template<>
bool strconv (const std::string &s, f64 &f)
template<>
bool strconv (const std::string &s, std::string &ss)
String conversion; strips whitspaces.
template<typename T >
bool str2vector (const std::string &s, std::vector< T > &e, const std::string &elemDelim, const std::string &rangeDelim, const T &minValue, const T &maxValue, const u32 &minSize, const u32 &maxSize, const T &step)
template<typename T >
bool str2vector (const std::string &s, std::vector< T > &e, const std::string &elemDelim, const std::string &rangeDelim, const std::string &assignDelim, const T &minValue, const T &maxValue, const u32 &minSize, const u32 &maxSize, const T &step)
template<>
bool strconv (const std::string &s, std::vector< u8 > &v)
template<>
bool strconv (const std::string &s, std::vector< u16 > &v)
template<>
bool strconv (const std::string &s, std::vector< u32 > &v)
template<>
bool strconv (const std::string &s, std::vector< u64 > &v)
template<>
bool strconv (const std::string &s, std::vector< s8 > &v)
template<>
bool strconv (const std::string &s, std::vector< s16 > &v)
template<>
bool strconv (const std::string &s, std::vector< s32 > &v)
template<>
bool strconv (const std::string &s, std::vector< s64 > &v)
template<>
bool strconv (const std::string &s, std::vector< f32 > &v)
template<>
bool strconv (const std::string &s, std::vector< f64 > &v)
template<>
bool strconv (const std::string &s, std::vector< std::string > &v)
Vector of strings conversion; strips whitespaces.
int getline (std::istream &, std::string &, std::string delim="\n")
reads from input stream until one of the specified delimiters
int wsgetline (std::istream &is, std::string &str, std::string delim="\n")
std::string & itoa (std::string &s, unsigned int val)
std::string itoa (u32 i)
template<class A , class B >
tied< A, B > tie (A &a, B &b)
int abs (int v)
Core::abs : wrapper for several absolute value functions.
long int abs (long int v)
long long int abs (long long int v)
float abs (float v)
double abs (double v)
long double abs (long double v)
template<class T >
T abs (const std::complex< T > &v)
template<class InputIterator , class M >
void maxAbsoluteElement (InputIterator begin, InputIterator end, M &m)
Maximal absolute value in v is returned in m.
template<class T >
T maxAbsoluteElement (const std::vector< T > &v)
template<class T >
T maxAbsoluteElement (const std::vector< std::complex< T >> &v)
float round (float v)
Core::round : wrapper for several round functions.
double round (double v)
float ceil (float v)
Core::ceil : wrapper for several ceil functions.
double ceil (double v)
float floor (float v)
Core::floor : wrapper for several floor functions.
double floor (double v)
template<class InputIterator >
bool isNormal (InputIterator begin, InputIterator end)
template<class F >
bool isMalformed (F f)
template<class T >
T clip (T x)
Checks if.
float log (float v)
Core::log : numerically robust wrapper for log functions.
double log (double v)
template<class InputIterator >
bool isMalformed (InputIterator begin, InputIterator end)
template<class F , class G , class H >
composedBinaryFunction< F, G, H > composeBinaryFunction (const F &f, const G &g, const H &h)
bool isAlmostEqual (f32 a, f32 b, f32 tolerance=(f32) 1)
Test for near-equality of floating point numbers.
bool isAlmostEqual (f64 a, f64 b, f64 tolerance=(f64) 1)
bool isAlmostEqual (const std::complex< f32 > &a, const std::complex< f32 > &b, const std::complex< f32 > tolerance=std::complex< f32 >((f32) 1,(f32) 1))
bool isAlmostEqual (const std::complex< f64 > &a, const std::complex< f64 > &b, const std::complex< f64 > tolerance=std::complex< f64 >((f64) 1,(f64) 1))
bool isSignificantlyGreater (f32 a, f32 b, f32 tolerance=(f32) 1)
bool isSignificantlyGreater (f64 a, f64 b, f64 tolerance=(f64) 1)
bool isSignificantlyLess (f32 a, f32 b, f32 tolerance=(f32) 1)
bool isSignificantlyLess (f64 a, f64 b, f64 tolerance=(f64) 1)
s32 differenceUlp (f32 a, f32 b)
Difference between two floating-point values in units of least precision (ULP).
s64 differenceUlp (f64 a, f64 b)
bool isAlmostEqualUlp (f32 a, f32 b, s32 tolerance)
Test for near-equality of floating point numbers with tolerance given in unit of least precision.
bool isAlmostEqualUlp (f64 a, f64 b, s64 tolerance)
bool isAlmostEqualUlp (f64 a, f64 b, s32 tolerance)
bool isSignificantlyLessUlp (f32 a, f32 b, s32 tolerance)
bool isSignificantlyLessUlp (f64 a, f64 b, s64 tolerance)
double timeDiff (timeval &start, timeval &end)
template<class T >
XmlWriter & operator<< (XmlWriter &os, const Statistics< T > &t)
XmlWriter & operator<< (XmlWriter &os, const HistogramStatistics &t)
template<class T >
Ref< T > ref (T *o)
Convenience constructors for Ref smart pointers.
template<class T >
BinaryOutputStream & operator<< (BinaryOutputStream &o, const std::vector< T > &vec)
template<class T1 , class T2 >
BinaryOutputStream & operator<< (BinaryOutputStream &o, const std::map< T1, T2 > &m)
template<class T >
BinaryOutputStream & operator<< (BinaryOutputStream &o, const std::set< T > &s)
template<class T >
BinaryInputStream & operator>> (BinaryInputStream &is, std::vector< T > &vec)
template<class T1 , class T2 >
BinaryInputStream & operator>> (BinaryInputStream &is, std::map< T1, T2 > &m)
template<class T >
BinaryInputStream & operator>> (BinaryInputStream &is, std::set< T > &s)
Variables
const Choice boolChoice
Predefined Choice for boolean values.
const Choice infinityChoice
Predefined Choice for "inifinite" numbers.
const char *const defaultEncoding = "ISO-8859-1"
const char requireTrailingBlank = 'Y'
const char prohibitTrailingBlank = 'N'
const char tolerateTrailingBlank = '='
Detailed Description
Copyright 2020 RWTH Aachen University.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.Copyright 2020 RWTH Aachen University. All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.Copyright 2020 RWTH Aachen University. All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.Copyright 2020 RWTH Aachen University. All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.Copyright 2020 RWTH Aachen University. All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.Copyright 2020 RWTH Aachen University. All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.Copyright 2020 RWTH Aachen University. All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.Copyright 2020 RWTH Aachen University. All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.Copyright 2020 RWTH Aachen University. All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.Copyright 2020 RWTH Aachen University. All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.Copyright 2020 RWTH Aachen University. All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Function Documentation
int Lattice::Core::abs (int v) inline
Core::abs : wrapper for several absolute value functions.
Definition at line 110 of file WeightedAccumulator.hh.
Referenced by Lattice::CheckPosteriorDfsState::finish().
float Lattice::Core::ceil (float v) inline
Core::ceil : wrapper for several ceil functions.
Definition at line 206 of file WeightedAccumulator.hh.
template<class T > T Lattice::Core::clip (T x)
Checks if.
Parameters
x is infinite and clips it to the largest representable value.
Returns
is clipped value of
Parameters
x.
Definition at line 247 of file WeightedAccumulator.hh.
std::string Lattice::Core::convertToLowerCase (const std::string &)
Convert UTF-8 string to lower case.
std::string Lattice::Core::convertToUpperCase (const std::string &)
Convert UTF-8 string to upper case.
s32 Lattice::Core::differenceUlp (f32 a, f32 b)
Difference between two floating-point values in units of least precision (ULP).
Returns
The number of distinct floating-point values between a and b. I.e. If b is the smallest value greater than a, the return value is 1.
void Lattice::Core::enforceTrailingBlank (std::string & s)
Ensure that a string ends with a single blank character.
float Lattice::Core::floor (float v) inline
Core::floor : wrapper for several floor functions.
Definition at line 215 of file WeightedAccumulator.hh.
std::string Lattice::Core::form (const char * format, ...)
Formatted output conversion.
form() is equivalent to snprintf(3) but returns the result as a string.
Parameters
format a printf-like format string
Returns
the formatted string
int Lattice::Core::getline (std::istream & , std::string & , std::string delim = "\n")
reads from input stream until one of the specified delimiters
Parameters
istream input stream to read from
string resulting string that has been read; will not include a trailing delimiter
delim string of delimiters
Returns
returns EOF if nothing has been read, but the end of stream has been reached, returns 0 at the end of the stream, but no delimiter has been found, returns the position + 1 of the delimiter in delim that the resulting string ends with
bool Lattice::Core::isAlmostEqual (f32 a, f32 b, f32 tolerance = (f32)1) inline
Test for near-equality of floating point numbers.
Due to finite precision, the bit-wise test (a == b) is almost always false. isAlmostEqual() compares the relative difference of a and b to the machine precision (epsilon) times the given tolerance factor.
Deprecation warning: For new code you should prefer isAlmostEqualUlp.
Remark: -A similar idea can be found under the name "chordal metric": chord(a, b) = |a - b| / (sqrt(1+a^2) * sqrt(1 + b^2)). -sorry for repeating the same implementation for each floating point type, but specialization to complex numbers seems to be a hard nut with templates.
Definition at line 316 of file WeightedAccumulator.hh.
bool Lattice::Core::isAlmostEqualUlp (f32 a, f32 b, s32 tolerance) inline
Test for near-equality of floating point numbers with tolerance given in unit of least precision.
Due to finite precision, the bit-wise test (a == b) should not be use for floating point values. This function was taken from "Comparing floating point numbers" by Bruce Dawson [http://www.cygnus-software.com/papers/comparingfloats/comparingfloats.htm]. You will probably not be able to make sense of this code without reading the article.
Parameters
tolerance allowed difference between a and b measured in units of least precision (Ulp). This can be thought of as the number of different normalized floating point numbers between a and b.
This method is preferrable to the older isAlmostEqual(), because it is faster and theoretically more sound. So maybe isAlmostEqual() should be removed some time.
Definition at line 384 of file WeightedAccumulator.hh.
Referenced by Lattice::CheckPosteriorDfsState::finish().
template<class F > bool Lattice::Core::isMalformed (F f)
Returns
is true if
Parameters
f is "inf" or "nan".
Definition at line 238 of file WeightedAccumulator.hh.
template<class InputIterator > bool Lattice::Core::isMalformed (InputIterator begin, InputIterator end)
Returns
is true if [begin..end) interval contains any malformed value (
See also
isMalformed(F f)).
Definition at line 268 of file WeightedAccumulator.hh.
template<class InputIterator > bool Lattice::Core::isNormal (InputIterator begin, InputIterator end)
Returns
is true if [begin..end) interval does not contain any "inf", "nan" etc. value.
Definition at line 227 of file WeightedAccumulator.hh.
bool Lattice::Core::isWhitespaceNormalized (const std::string & s, char trailingBlank = prohibitTrailingBlank)
Test if a string is whitespace-normalized.
Returns
true iff s matches (+)*
Parameters
trailingBlank specifies if a trailing blank is required. The default is to classify strings ending with a blank as not normalized. If requireTrailingBlank is given, the string is considered normalized only if it ends with a single blank.
float Lattice::Core::log (float v) inline
Core::log : numerically robust wrapper for log functions.
Definition at line 255 of file WeightedAccumulator.hh.
template<class InputIterator , class M > void Lattice::Core::maxAbsoluteElement (InputIterator begin, InputIterator end, M & m)
Maximal absolute value in v is returned in m.
If v is empty, result is set to Type<T>::min.
Definition at line 149 of file WeightedAccumulator.hh.
void Lattice::Core::normalizeWhitespace (std::string & s)
Definition: A string has "normalized whitespace" if and only if it matches one the following regular expressions: (+)* or (+)* + where matches any non-whitespace character.
I.e. There are no whitespaces other than single blanks; the first character is non-blank, and the last character may be blank. Normalize whitespace in a string. All consecutive whitespaces in the passed string are replaced by a single blank. Leading whitespace is removed.
Attention: If tailing whitspaces exist, a single whitspace has to remain!
Parameters
s the string to be normalized
template<class T > Ref<T> Lattice::Core::ref (T * o) inline
Convenience constructors for Ref smart pointers.
Definition at line 301 of file WeightedAccumulator.hh.
Referenced by Lattice::composeLm(), and Lattice::composeMatching().
float Lattice::Core::round (float v) inline
Core::round : wrapper for several round functions.
Definition at line 197 of file WeightedAccumulator.hh.
std::vector<std::string> Lattice::Core::split (const std::string & string, const std::string & separator)
Split string into tokens.
Return a list of the tokens in the string, using separator as the delimiter string. Any Leading or trailing whitespace is stripped ffrom the word returned. Consecutive delimiters are not grouped together and are deemed to delimit empty strings (for example, split("1,,2", ",") returns ["1", "", "2"]"). The separator argument may consist of multiple characters (for example, split("1, 2, 3", ", ") returns ["1", "2", "3"]). Splitting an empty string with a specified separator returns an empty list.
bool Lattice::Core::startsWith (const std::string & string, const std::string & search)
Like the python startswith method of strings.
return true is string starts with search
template<typename Signed > bool Lattice::Core::str2signed (const std::string & s, Signed & i)
Primitive data type conversion.
Definition at line 217 of file WeightedAccumulator.hh.
template<typename T > bool Lattice::Core::str2vector (const std::string & s, std::vector< T > & e, const std::string & elemDelim)
String to list conversion.
Vector of primitive datatypes conversion.
Used by strconv to convert a string to a list. Use instead of strconv if you need to specify element and range delimiter and range borders and step width. Default seperator is space or tab for strings and comma for any others; number ranges can be specified by placing a - between two numbers.
Definition at line 349 of file WeightedAccumulator.hh.
template<typename T > bool Lattice::Core::strconv (const std::string & s, T & t)
Convinient functions to parse strings.
Generalized conversion.
returns true on successful conversion; the string argument may contain leading and tailing whitspaces. general string to something conversion; currently specialized for:
standard datatypes
strings
vectors of standard datatypes
vectors of standard strings supports:
different representations of bool values
+/-inf for numerical types
ranges for numerical values
Definition at line 185 of file WeightedAccumulator.hh.
template<typename T > bool Lattice::Core::strconv (const std::string & s, T & t, const Choice & c)
Maps a given string to value of type T via the given Choice object; returns true on successful mapping.
Choice conversion.
Definition at line 197 of file WeightedAccumulator.hh.
template<> bool Lattice::Core::strconv (const std::string & s, std::string & ss) inline
String conversion; strips whitspaces.
Definition at line 336 of file WeightedAccumulator.hh.
template<> bool Lattice::Core::strconv (const std::string & s, std::vector< std::string > & v) inline
Vector of strings conversion; strips whitespaces.
Definition at line 537 of file WeightedAccumulator.hh.
void Lattice::Core::stripWhitespace (std::string &)
Remove leading and trailing whitespace.
void Lattice::Core::suppressTrailingBlank (std::string & s)
Remove trailing blank character.
Removes the last character if it is a blank.
template<size_t size> void Lattice::Core::swapEndianess (void * buf, size_t count = 1)
Change endianess of a block of data.
The size argument is given as a template parameter, so the compiler can unroll the loop.
Parameters
buf pointer to an array of data
size size of the element data type in bytes.
count number of elements
Definition at line 75 of file Core/Types.cc.
template<typename T > std::string Lattice::Core::vector2str (const std::vector< T > & vec, const std::string & elemDelim = " ")
convert vector to string, elements are separated by elemDelim
Definition at line 559 of file WeightedAccumulator.hh.
Variable Documentation
const Choice Lattice::Core::boolChoice
Predefined Choice for boolean values.
(e.g. "true", "false, "yes", "no" ...).
const Choice Lattice::Core::infinityChoice
Predefined Choice for "inifinite" numbers.
(e.g. "infinite", "-infinity", "unlimited" ...)