Sprint: Mm Namespace Reference
Mm Namespace Reference
Copyright 2020 RWTH Aachen University.
Classes
class AbstractAdaptationAccumulator
Abstract interface for adaptation accumulators.
class AbstractCovarianceEstimator
AbstractCovarianceEstimator.
class AbstractDensity
AbstractDensity.
class AbstractEstimationAccumulator
AbstractEstimationAccumulator.
class AbstractMeanEstimator
AbstractMeanEstimator.
class AbstractMixtureEstimator
AbstractMixtureEstimator: base class.
class AbstractMixtureSet
AbstractMixtureSet administrates mixture objects and their relations.
class AbstractMixtureSetEstimator
Base Class for accumulator and estimator class for mixture sets.
struct AbstractMixtureSetLoader
class AccumulatorBase
Base class for accumulators.
class Adaptor
Base class for adaptors.
class AdaptorEstimator
Base class for adaptor estimators.
class AffineFeatureTransformAccumulator
AffineFeatureTransformAccumulator.
class AssigningFeatureScorer
Abstract feature scorer interface with assignment to the best density.
class BandMllrEstimator
Estimator for MLLR using band matrices.
class BatchFeatureScorerBase
Feature scorer computing scores for multiple feature vectors in advance.
class BatchFloatFeatureScorer
Batched feature scorer using floats.
class BatchIntFeatureScorer
Batched feature scorer using integer computations.
class BatchPreselectionFloatFeatureScorer
class BatchPreselectionIntFeatureScorer
class BatchUnrolledIntFeatureScorer
Batched feature scorer using integer computations for a fixed size feature vector.
class Cache
Cache class optimized for short creation time.
class Cache2D
Two dimensional cache class optimized for short creation time.
class CachedAssigningFeatureScorer
Abstract feature scorer interface with cached scores and assignment.
class CachedAssigningTransformingFeatureScorer
Abstract feature scorer interface with cached scores and assignment using feature transforming distance functions .
class CachedFeatureScorer
Abstract feature scorer interface with cached scores.
class CombinedFeatureScorer
class ContextScorerCache
class ConvertCovarianceEstimator
ConvertCovarianceEstimator.
class ConvertGaussDensityEstimator
ConvertGaussDensityEstimator.
class ConvertMeanEstimator
ConvertMeanEstimator.
class ConvertMixtureEstimator
ConvertMixtureEstimator.
class ConvertMixtureSetEstimator
ConvertMixtureSetEstimator.
class Covariance
Interface class for covariance implementations.
class CovarianceEstimator
CovarianceEstimator.
class CovarianceFeatureScorerElement
class CovarianceToMeanSetMap
CovarianceToMeanSetMap.
class CovarianceWeightedFeatureScorerElement
class DensityClustering
class DensityClusteringBase
class DensitySpecificCachedAssigningFeatureScorer
class DensityToWeightMap
class DiagonalCovariance
DiagonalCovariance.
class DiscriminativeCovarianceEstimator
DiscriminativeCovarianceEstimator.
class DiscriminativeGaussDensityEstimator
DiscriminativeGaussDensityEstimator.
class DiscriminativeMeanEstimator
DiscriminativeMeanEstimator.
class DiscriminativeMixtureEstimator
discriminative mixture estimator: base class
class DiscriminativeMixtureSetEstimator
DiscriminativeMixtureSetEstimator.
class DynamicCache
Dynamic Cache class Note: this cache class should only be used with types or classes with fast initialization time Optimizations:
class EbwDiscriminativeCovarianceEstimator
EbwDiscriminativeCovarianceEstimator.
class EbwDiscriminativeCovarianceEstimatorWithISmoothing
EbwDiscriminativeCovarianceEstimatorWithISmoothing.
class EbwDiscriminativeGaussDensityEstimator
EbwDiscriminativeGaussDensityEstimator.
class EbwDiscriminativeGaussDensityEstimatorWithISmoothing
EbwDiscriminativeGaussDensityEstimatorWithISmoothing.
class EbwDiscriminativeMeanEstimator
EbwDiscriminativeMeanEstimator.
class EbwDiscriminativeMeanEstimatorWithISmoothing
EbwDiscriminativeMeanEstimatorWithISmoothing.
class EbwDiscriminativeMixtureEstimator
discriminative mixture estimator: EBW
class EbwDiscriminativeMixtureEstimatorWithISmoothing
discriminative mixture estimator with i-smoothing: EBW
class EbwDiscriminativeMixtureSetEstimator
EbwDiscriminativeMixtureSetEstimator.
class EbwDiscriminativeMixtureSetEstimatorWithISmoothing
DiscriminativeMixtureSetEstimatorWithISmoothing: EBW.
struct EmptyMixtureSetLoader
struct equalReferenced
class Feature
Feature is container for objects comming from different feature stream at the same time.
class FeatureDescription
Vector of stream descriptions Stream description is a set of attributes describing a feature stream.
class FeatureScorer
Abstract feature scorer interface.
class FeatureScorerFactory
Factory for FeatureScorer objects.
class FeatureScorerIntelOptimization
FeatureScorerIntelOptimization.
class FeatureScorerScaling
Wraper class for Feature scorer with log linear scale.
class FullAdaptor
Adaptor for full matrix MLLR.
class FullAdaptorViterbiEstimator
Estimator for full matrix adaptor.
class GaussDensity
GaussDensity.
class GaussDensityEstimator
GaussDensityEstimator.
class GaussDensityTopology
GaussDensityTopology.
class GaussDiagonalMaximumFeatureScorer
Feature-scorer for MixtureSet of Gauss densities with diagonal covariance matrices Scores are calculated with maximum approximation.
class GaussDiagonalSumFeatureScorer
Feature-scorer for MixtureSet of Gauss densities with diagonal covariance matrices The maximum approximation is not applied here.
struct hashReference
Creates hash key from a pointer by casting to unsigned int.
struct IdSetEntry
struct IdSetEntryLess
class IntelMMXL2NormCodeGenerator
class IntelMMXResetCodeGenerator
struct inverseSquareRoot
1 / sqrt(x)
class ISmoothingCovarianceEstimator
ISmoothingCovarianceEstimator.
class ISmoothingGaussDensityEstimator
ISmoothingGaussDensityEstimator.
class ISmoothingMeanEstimator
ISmoothingMeanEstimator.
class ISmoothingMixtureEstimator
i-smoothing mixture estimator
class ISmoothingMixtureSetEstimator
ISmoothingMixtureSetEstimator.
class IterationConstants
IterationConstants: base class.
class LogLinearDensity
LogLinearDensity.
class LogLinearMixtureSet
class Mean
Mean.
class MeanEstimator
MeanEstimator.
class minusLog
-factor * log (x)
class Mixture
Could be derived from Density...
class MixtureEstimator
maximum likelihood MixtureEstimator
class MixtureFeatureScorerElement
MixtureFeatureScorerElement.
class MixtureSet
MixtureSet administrates mixture, Gauss-density, mean, and covariance objects and their relations.
class MixtureSetBuilder
MixtureSetTopologyBuilder creates a mixture set with independend densities.
class MixtureSetEstimator
Maximum Likelihood accumulator and estimator class for mixture sets.
class MixtureSetEstimatorIndexMap
Reference table representation of AbstractMixtureSetEstimator.
class MixtureSetReader
Read a mixture set from various file formats.
class MixtureSetSplitter
class MixtureSpecificCovarianceBuilder
MixtureSpecificCovarianceTopologyBuilder creates a mixture set with mixture specific covariance matrices.
class MixtureToMixtureMap
defines a mixture-to-mixture id mapping based on a mapping file
class MixtureTopology
MixtureTopology.
class Module_
class normalizedMinus
(x - y) / normalization
class plusNormalizedSquare
x + y^2 / normalization_
struct plusSquare
x + y^2
struct plusSquareWeighted
x + weight*y^2
struct plusWeighted
x + weight*y
class PointerIndexMap
class PointerVector
Container of object references in the form of pointers.
class PooledCovarianceBuilder
PooledCovarianceTopologyBuilder creates a mixture set with one pooled covariance matrix.
class ProbabilityStatistics
Histogram statistics for probabilities.
class quantize
class QuantizedMixtureFeatureScorerElement
Container for precalculated data within a mixture Precalculated members for each density: -prepared mean, -constant precalucated weight -and convariance index which references the corresponding precalculated feature vector.
class ReferenceIndexMap
class RpropDiscriminativeCovarianceEstimator
RpropDiscriminativeCovarianceEstimator.
class RpropDiscriminativeCovarianceEstimatorWithISmoothing
RpropDiscriminativeCovarianceEstimatorWithISmoothing.
class RpropDiscriminativeGaussDensityEstimator
RpropDiscriminativeGaussDensityEstimator.
class RpropDiscriminativeGaussDensityEstimatorWithISmoothing
RpropDiscriminativeGaussDensityEstimatorWithISmoothing.
class RpropDiscriminativeMeanEstimator
RpropDiscriminativeMeanEstimator.
class RpropDiscriminativeMeanEstimatorWithISmoothing
RpropDiscriminativeMeanEstimatorWithISmoothing.
class RpropDiscriminativeMixtureEstimator
discriminative mixture estimator: Rprop
class RpropDiscriminativeMixtureEstimatorWithISmoothing
discriminative mixture estimator with i-smoothing: Rprop
class RpropDiscriminativeMixtureSetEstimator
RpropDiscriminativeMixtureSetEstimator.
class RpropDiscriminativeMixtureSetEstimatorWithISmoothing
DiscriminativeMixtureSetEstimatorWithISmoothing: Rprop.
class RpropOptimization
RpropOptimization.
class RpropSettings
RpropSettings.
class ScaledFeatureScorer
Feature scorer with log linear scale.
class SemiTiedEstimator
class SemiTiedOptimizationFunction
class SemiTiedOptimizationGradient
class ShiftAdaptor
Adaptor for shift adaptation.
class ShiftAdaptorViterbiEstimator
Estimator for shift adaptor.
class SimdGaussDiagonalMaximumFeatureScorer
Accelerated feature-scorer for MixtureSet of Gauss densities with diagonal covariance matrices Scores are calculated on quantized (8 bit) features with maximum approximation.
class SSE2L2NormCodeGenerator
class StatePosteriorFeatureScorer
Base feature-scorer for MixtureSet of log linear densities.
class VectorAccumulator
Typedefs
typedef Core::Ref< CachedFeatureScorer::CachedContextScorerOverlay > CachedContextScorer
typedef Core::BinaryTree::Id NodeId
typedef Core::BinaryTree::LeafNumber LeafNumber
typedef Core::Ref< Math::ReferenceCountedVector< LeafNumber > > LeafIndexVector
typedef Math::Matrix< double > Matrix
typedef std::map< NodeId, Matrix >::const_iterator MatrixConstIterator
typedef std::map< NodeId, Matrix >::iterator MatrixIterator
typedef div_t my_div_t
typedef std::set< IdSetEntry >::const_iterator IdSetConstIterator
typedef std::set< IdSetEntry >::iterator IdSetIterator
typedef Core::SingletonHolder< Module_ > Module
typedef f32 Score
typedef f32 FeatureType
typedef f32 MeanType
typedef f32 VarianceType
typedef f64 Weight
typedef f64 IterationConstant
typedef u32 ComponentIndex
typedef u32 MixtureIndex
typedef MixtureIndex EmissionIndex
typedef u32 DensityIndex
typedef u32 DensityInMixture
typedef u32 MeanIndex
typedef u32 CovarianceIndex
typedef u32 Count
typedef f64 Sum
typedef std::string ClusterId
typedef f32 ScaleType
typedef u32 ExpertIndex
typedef std::vector< FeatureType > FeatureVector
typedef std::vector< ScaleType > Scales
Functions
std::ostream & operator<< (std::ostream &o, const Mean &m)
std::istream & operator>> (std::istream &i, Mean &m)
std::ostream & operator<< (std::ostream &o, const Covariance &c)
std::istream & operator>> (std::istream &i, Covariance &c)
std::ostream & operator<< (std::ostream &o, const Mixture &ms)
Core::BinaryOutputStream & operator<< (Core::BinaryOutputStream &o, const AbstractMixtureSet &ms)
Core::BinaryInputStream & operator>> (Core::BinaryInputStream &i, AbstractMixtureSet &ms)
std::ostream & operator<< (std::ostream &o, const AbstractMixtureSet &ms)
std::istream & operator>> (std::istream &i, AbstractMixtureSet &ms)
std::ostream & operator<< (std::ostream &o, const GaussDensityTopology &gdt)
std::istream & operator>> (std::istream &i, GaussDensityTopology &gdt)
static bool operator< (const Mm::IdSetEntry &ls, const Mm::IdSetEntry &rs)
Math::Matrix< double > adaptationUnitMatrix (ComponentIndex dim)
Core::BinaryOutputStream & operator<< (Core::BinaryOutputStream &o, const AccumulatorBase &a)
Core::BinaryInputStream & operator>> (Core::BinaryInputStream &i, AccumulatorBase &a)
Math::Vector< double > convert2Vector (const std::map< NodeId, Math::Vector< double >> &l, const Math::Matrix< double > &u, const Math::Matrix< double > &v)
void convert2Matrices (const Math::Vector< double > &x, std::map< NodeId, Math::Vector< double >> &l, Math::Matrix< double > &u, Math::Matrix< double > &v, ComponentIndex dim)
template<class InputIterator >
double logExpNorm (InputIterator begin, InputIterator end)
log (sum_i exp(v_i))
template<class InputIterator >
double logNorm (InputIterator begin, InputIterator end)
sum_i log(v_i)
template<class InputIterator , class WeightIterator >
double logNorm (InputIterator beginDiagonal, InputIterator endDiagonal, WeightIterator beginWeights, WeightIterator endWeights)
sum_i (weight_i * log(v_i))
template<class InputIterator >
double gaussLogNormFactor (InputIterator begin, InputIterator end)
N * log(2 * pi) + sum_i log(v_i)
template<class InputIterator , class WeightIterator >
double gaussLogNormFactor (InputIterator beginDiagonal, InputIterator endDiagonal, WeightIterator beginWeights, WeightIterator endWeights)
N * log(2 * pi) + sum_i (weight_i * log(v_i))
template<class InputIterator1 , class InputIterator2 , class OutputIterator , class Operation >
void unrolledTransform (InputIterator1 begin1, InputIterator1 end1, InputIterator2 begin2, OutputIterator result, Operation operation)
template<class T , class DistanceType >
DistanceType unrolledVectorDistance (const T *a, const T *b, size_t dimension)
Variables
const MixtureIndex invalidMixture = Core::Type<MixtureIndex>::max
Detailed Description
Copyright 2020 RWTH Aachen University.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Function Documentation
template<class InputIterator > double Mm::gaussLogNormFactor (InputIterator begin, InputIterator end)
N * log(2 * pi) + sum_i log(v_i)
Definition at line 73 of file Mm/Utilities.hh.
References logNorm().
Referenced by Mm::Covariance::halfeLogNormFactor().
template<class InputIterator , class WeightIterator > double Mm::gaussLogNormFactor (InputIterator beginDiagonal, InputIterator endDiagonal, WeightIterator beginWeights, WeightIterator endWeights)
N * log(2 * pi) + sum_i (weight_i * log(v_i))
Definition at line 80 of file Mm/Utilities.hh.
References logNorm().
template<class InputIterator > double Mm::logExpNorm (InputIterator begin, InputIterator end)
log (sum_i exp(v_i))
Definition at line 44 of file Mm/Utilities.hh.
template<class InputIterator > double Mm::logNorm (InputIterator begin, InputIterator end)
sum_i log(v_i)
Definition at line 55 of file Mm/Utilities.hh.
References Core::abs().
Referenced by gaussLogNormFactor().
template<class InputIterator , class WeightIterator > double Mm::logNorm (InputIterator beginDiagonal, InputIterator endDiagonal, WeightIterator beginWeights, WeightIterator endWeights)
sum_i (weight_i * log(v_i))
Definition at line 63 of file Mm/Utilities.hh.
References Core::abs().