Sprint: Core Namespace Reference
Core Namespace Reference
Copyright 2020 RWTH Aachen University.
Classes
struct absoluteValue
absoluteValue: functor for absolute value
class AbstractChoiceParameter
Base class template for multiple-choice parameters.
class AbstractParameter
Abstract base class for parameter declaration.
struct AlignedAlloc
class Application
Application class:
class Archive
Abstract base class for archives.
class ArchiveReader
class ArchiveWriter
class ArithmeticExpressionParserDriver
struct binary_compose
struct BinaryFormat
Template helper class for registering binary formats.
class BinaryInputStream
BinaryInputStream.
class BinaryInputStreams
class BinaryOutputStream
BinaryOutputStream.
class BinaryStream
class BinaryStreamIos
class BinaryTree
class BitStream
class BuildDelegation
class BundleArchive
class Channel
Configurable text output stream.
class CharsetConverter
class Choice
Choice class.
struct ChoiceConversion
class ChoiceStatistics
class CodeGenerator
class Component
Base class for configurable components with logging and error logging facilities.
class ComponentFactory
Object factory for subclasses of Core::Component.
class composedBinaryFunction
Functor for f(g(x), h(y))
struct CompressedBinaryFormat
Template helper class for registering compressed binary formats.
class CompressedInputStream
class CompressedOutputStream
struct CompressedPlainTextFormat
Template helper class for registering plain text formats.
class Condition
A condition variable.
class Configurable
Abstract base class for run-time configurable classes.
class Configuration
Central configuration class.
class ConstantVector
An optionally non-changeable and mappable vector, which can either have a real vector as back-end storage, or can be memory-mapped.
struct conversion
Generic unary functor for type conversion.
struct CreateByContext
struct CreateStatic
struct CreateUsingNew
class DefaultHashMap
class Delegation
Implements a kind of the delegation pattern.
class Dependable
class Dependency
class DependencySet
class Description
Vector of stream descriptions Stream descriptions if a set of attributes describing a (feature) stream.
class DirectoryArchive
class DirectoryFileIterator
DirectoryFileIterator iterates recursively thought the directory.
class Factory
Object factory based on Alexandrescu, Andrei "Modern C++ Design".
class FileArchive
class FormatSet
Set of format-qualifiers.
class HashMap
class HistogramStatistics
A histogram statistics class for simple unsigned integers.
struct identity
class IoRef
IoRef extends Ref by allowing reading and writing to binary streams.
struct ListWriter
Prints a list of values.
class LockingPointer
A thread-safety smart pointer.
class MappedArchive
This class represents an archive containing multiple "virtual" files, which can be mapped to memory.
class MappedArchiveReader
class MappedArchiveWriter
struct maximum
max: functor for max function
class MD5
class MemoryInfo
process memory information
struct minimum
min: functor for min function
class MMappedFile
This class represents a simple memory-mapped file.
class MruObjectCacheList
MruObjectCacheList: list of ObjectCacheItems implementing the most recently used strategy.
class Mutex
A mutex.
class MutexLock
Lock mutex in current scope.
class NameHelper
Use this class for naming your basic classes.
class NameHelper< bool >
class NameHelper< Flf::ConstLatticeRef >
class NameHelper< Flow::Aggregate >
class NameHelper< Flow::DataPtr< T > >
class NameHelper< Flow::TypedAggregate< T > >
class NameHelper< Flow::Vector< T > >
class NameHelper< Math::Matrix< T, P > >
class NameHelper< Math::RefernceCountedMatrix< T, P > >
class NameHelper< Math::Vector< T, P > >
class NameHelper< Mm::AbstractMixtureSet >
class NameHelper< Mm::MixtureSet >
class NameHelper< Nn::Statistics< f32 > >
class NameHelper< Nn::Statistics< f64 > >
class NameHelper< Sparse::SingleValueSparseVector< T > >
class NameHelper< Sparse::Vector< T > >
class NameHelper< Speech::Alignment >
class NameHelper< Speech::AlignmentGeneratorRef >
class NameHelper< Speech::ConstSegmentwiseFeaturesRef >
class NameHelper< Speech::ModelCombinationRef >
class NameHelper< std::complex< T > >
class NameHelper< std::string >
class NameHelper< std::vector< T > >
class NullMapper
class NullReducer
A basic thread pool implementation offering a very simple shared memory Map-Reduce framework.
class ObjectCache
ObjectCache: implements the caching of larger objects.
class ObjectCacheItem
ObjectCacheItem: class handling the data_ object (read, write, dirty)
class Obstack
struct OStreamWriter
class Parameter
Base class template for parameter declaration.
class ParameterBitVector
Declaration class for bit vector parameters.
class ParameterBool
Declaration class for boolean valued parameters.
class ParameterChoice
Declaration class for discrete multiple-choice parameters.
class ParameterFloat
Declaration class for floating point parameters.
class ParameterFloatVector
Declaration class for float vector parameters.
class ParameterInt
Declaration class for integer valued parameters.
class ParameterIntVector
Declaration class for int vector parameters.
class ParameterString
Declaration class for string parameters.
class ParameterStringVector
Declaration class for string vector parameters.
class ParameterWeightVector
Declaration class for weight vector parameters.
struct PlainTextFormat
Template helper class for registering plain text formats.
struct PointerHash
struct power
power: functor for pow function
class PriorityQueue
Simple heap-based priority queue template.
class PriorityQueueBase
class ProgressIndicator
Provide assurance to impatient users.
class RandomObjectCacheList
RandomObjectCacheList: list of ObjectCacheItems implementing the random strategy.
class RangedParameter
Base class template for parameters with lower und upper bounds.
class ReadWriteLock
A read-write lock.
class Ref
Class template for smart pointers using intrusive reference-counting.
class ReferenceCounted
Base class for reference-counted objects.
class ResourceUsageInfo
process resource usage information
struct select1st
struct select2nd
class SingletonHolder
Implementation of the Singleton Pattern.
class Statistics
struct StringConversion
struct StringConversion< std::string >
struct StringEquality
class StringExpression
String parameter with variable parts.
class StringExpressionParser
Builder for StringExpression.
struct StringHash
class StringHashMap
class StringHashSet
class StringTokenizer
Splits a string in tokens.
class TextInputStream
Stream for text input.
class TextOutputStream
Stream for text output.
class Thread
Abstract Thread.
class ThreadPool
The class Task (T) should carry the input data.
class ThreadPoolImpl
Thread pool implementation used by ThreadPool.
class ThreadPoolThread
class ThreadSafeReferenceCounted
Base class for reference-counted objects used in a multithreaded environment.
class tied
A helper for conveniently assigning the two values from a pair into separate variables.
class Timer
struct TimeStampWriter
Prints a timestamp.
struct TList
struct TList< FirstElem, OtherElems... >
class TracedHeap
class TracedPriorityQueue
Heap-based priority queue class template with random access.
class TsRef
Class template for smart pointers using intrusive reference-counting in a multithreaded environment.
struct Type
Static information about elementary types.
struct Type< f32 >
struct Type< f64 >
struct Type< s16 >
struct Type< s32 >
struct Type< s64 >
struct Type< s8 >
struct Type< u16 >
struct Type< u32 >
struct Type< u64 >
struct Type< u8 >
class UnicodeInputConverter
Converter for reading text data.
class UnicodeOutputConverter
Converter for writing text data.
class UntracedHeap
class Vector
class VectorParameter
Base class template for vector parameter declaration.
class VersionRegistry
Access to source code version information.
class WeakRef
Class template for smart pointers provining weak referencing.
class WeakRefBase
Base class of the WeakRef template.
class WithoutProgressIndicator
class WithProgressIndicator
class XmlAttribute
Streaming objects for XML output.
class XmlAttributes
XML element attributes.
class XmlBlank
A blank character.
class XmlBuilderElement
class XmlBuilderElement< P, CM, CreateByContext >
class XmlBuilderElement< P, CM, CreateStatic >
class XmlBuilderElement< P, CM, CreateUsingNew >
class XmlBuilderElementTemplate
class XmlChannel
Configurable XML output stream.
class XmlChoiceBuilderElement
class XmlClose
class XmlCloseComment
class XmlComment
class XmlContext
class XmlDataOnlyBuilderElement
class XmlDocumentElement
Helper class used by XmlSchemaParser when outside the document's root element.
class XmlElement
Abstract XML element declaration for use with XmlSchemaParser.
class XmlElementGarbageCollector
Easy solution for collecting and destroying XmlElements.
class XmlEmpty
class XmlEmptyElement
XML Element declaration for the empty content model.
class XmlEmptyElementRelay
class XmlFlattenElement
Helper class.used for flattening unknown elements.
class XmlFlattenElementRelay
struct XmlFormat
Template helper class for registering xml formats.
class XmlFull
class XmlIgnoreElement
Helper class.used for ignoring unknown elements.
class XmlMapDocument
XML document containing one single map.
class XmlMapElement
XmlMapElement implements XmlBuilderElement for an arbitrary XmlSchemaParser which parses a map.
struct XmlMatchTagNameHandler
class XmlMatrixDocument
XML document containing one single matrix.
class XmlMatrixElement
XmlMatrixElement implements XmlBuilderElement for an arbitrary XmlSchemaParser which parses a matrix of a given type.
class XmlMixedElement
XML element declaration for the mixed content model.
class XmlMixedElementRelay
class XmlOpen
class XmlOpenComment
class XmlOutputStream
Stream for writing XML files.
class XmlParentElement
XML Element declarator base class for elments with child elements.
class XmlParser
Basic event driven XML parser.
class XmlRegularElement
XML element declaration for the regular content model.
class XmlRegularElementRelay
class XmlSchemaParser
Stack based XML parser.
class XmlVectorDocument
XML document containing one single vector.
class XmlVectorElement
XmlVectorElement implements XmlBuilderElement for an arbitrary XmlSchemaParser which parses a vector of a given type.
class XmlWriter
Stream adaptor for producing XML output.
Typedefs
typedef TList< s8, u8, s16, u16, s32, u32, s64, u64, f32, f64 > NumberTypeList
typedef XmlDataOnlyBuilderElement< std::string > XmlStringBuilderElement
typedef XmlDataOnlyBuilderElement< bool > XmlBooleanBuilderElement
typedef XmlDataOnlyBuilderElement< u32 > XmlUnsignedBuilderElement
typedef XmlDataOnlyBuilderElement< s32 > XmlSignedBuilderElement
typedef XmlDataOnlyBuilderElement< f32 > XmlFloatBuilderElement
typedef XmlChoiceBuilderElement< Choice::Value > XmlChoiceElement
Enumerations
enum { Version = 0x17231 }
Functions
template<class T >
bool allocateAlignedVector (T **ptr, size_t size, T initialValue=static_cast< T >(0), size_t alignment=16)
Aligned memory allocation for an array.
template<class T >
BinaryOutputStream & operator<< (BinaryOutputStream &o, const std::vector< T > &vec)
template<class T1 , class T2 >
BinaryOutputStream & operator<< (BinaryOutputStream &o, const std::map< T1, T2 > &m)
template<class T >
BinaryOutputStream & operator<< (BinaryOutputStream &o, const std::set< T > &s)
template<class T >
BinaryInputStream & operator>> (BinaryInputStream &is, std::vector< T > &vec)
template<class T1 , class T2 >
BinaryInputStream & operator>> (BinaryInputStream &is, std::map< T1, T2 > &m)
template<class T >
BinaryInputStream & operator>> (BinaryInputStream &is, std::set< T > &s)
Core::BinaryOutputStream & operator<< (Core::BinaryOutputStream &o, const BinaryTree &t)
Core::BinaryInputStream & operator>> (Core::BinaryInputStream &i, BinaryTree &t)
std::string extendCompressedFilename (const std::string &filename, const std::string &extension)
void printWarning (const char *msg,...)
void printLog (const char *msg,...)
bool AmIBeingDebugged ()
void stackTrace (std::ostream &os, int cutoff)
std::string directoryName (const std::string &path)
Return the directory name of a pathname.
std::string baseName (const std::string &path)
Strip directory from filename.
std::string joinPaths (const std::string &path1, const std::string &path2)
Join two path components intelligently.
std::string normalizePath (const std::string &path)
Normalize a pathname.
std::string filenameExtension (const std::string &path)
Get filename extension.
std::string stripExtension (const std::string &path)
Strips the extension of the.
bool createDirectory (const std::string &path)
Create directory.
bool clearDirectory (const std::string &path)
Remove all contents of a directory recursively.
bool removeDirectory (const std::string &path)
Remove a directory.
bool isValidPath (const std::string &path)
Test for pathname.
bool isDirectory (const std::string &path)
Test for directory.
bool isRegularFile (const std::string &path)
Test for regular file.
bool isSymbolicLink (const std::string &path)
Test for symbolic link.
bool isReadable (const std::string &path)
Test if file / directory is readable.
bool isWritable (const std::string &path)
Test if file / directory is writable.
bool isExecutable (const std::string &path)
Test if file / directory is executable.
bool writeLargeBlock (int fd, const char *buf, u64 count)
Write a larger (>2GB) block of memory to a file.
std::ostream & timestamp (std::ostream &out)
template<typename T >
ListWriter< typename std::vector< T >::const_iterator > str (const std::vector< T > &v, const std::string &delim=", ")
template<typename T >
ListWriter< typename std::set< T >::const_iterator > str (const std::set< T > &v, const std::string &delim=", ")
template<typename T >
ListWriter< typename std::list< T >::const_iterator > str (const std::list< T > &v, const std::string &delim=", ")
XmlWriter & operator<< (XmlWriter &os, const MemoryInfo &i)
void MurmurHash3_x86_32 (const void *key, int len, uint32_t seed, void *out)
void MurmurHash3_x86_128 (const void *key, int len, uint32_t seed, void *out)
void MurmurHash3_x64_128 (const void *key, int len, uint32_t seed, void *out)
uint64_t MurmurHash3_x64_64 (const void *key, const int len, const uint32_t seed)
const std::string objectCacheDumpExtension (".dump")
template<class T >
Ref< T > ref (T *o)
Convenience constructors for Ref smart pointers.
XmlWriter & operator<< (XmlWriter &os, const ResourceUsageInfo &i)
template<class T >
XmlWriter & operator<< (XmlWriter &os, const Statistics< T > &t)
XmlWriter & operator<< (XmlWriter &os, const HistogramStatistics &t)
StringExpression makeStringExpression (const std::string &stringExpression, const std::string &openTag="$(", const std::string &closeTag=")")
helper function to parse and create a StringExpression
void normalizeWhitespace (std::string &s)
Definition: A string has "normalized whitespace" if and only if it matches one the following regular expressions: (+)* or (+)* + where matches any non-whitespace character.
void enforceTrailingBlank (std::string &s)
Ensure that a string ends with a single blank character.
void suppressTrailingBlank (std::string &s)
Remove trailing blank character.
bool isWhitespaceNormalized (const std::string &s, char trailingBlank=prohibitTrailingBlank)
Test if a string is whitespace-normalized.
void stripWhitespace (std::string &)
Remove leading and trailing whitespace.
std::string convertToLowerCase (const std::string &)
Convert UTF-8 string to lower case.
std::string convertToUpperCase (const std::string &)
Convert UTF-8 string to upper case.
std::string form (const char *format,...) __attribute__((format(printf
Formatted output conversion.
std::string std::string vform (const char *format, va_list args)
std::vector< std::string > split (const std::string &string, const std::string &separator)
Split string into tokens.
bool startsWith (const std::string &string, const std::string &search)
Like the python startswith method of strings.
template<typename T >
bool strconv (const std::string &, T &)
Convinient functions to parse strings.
template<typename T >
bool strconv (const std::string &, T &, const Choice &)
Maps a given string to value of type T via the given Choice object; returns true on successful mapping.
template<typename T >
bool str2vector (const std::string &, std::vector< T > &, const std::string &elemDelim)
String to list conversion.
template<typename T >
bool str2vector (const std::string &, std::vector< T > &, const std::string &elemDelim, const std::string &rangeDelim, const T &min=Core::Type< T >::min, const T &max=Core::Type< T >::max, const T &step=T(1))
template<typename T >
bool str2vector (const std::string &, std::vector< T > &, const std::string &elemDelim, const std::string &rangeDelim, const std::string &assignDelim, const T &min=Core::Type< T >::min, const T &max=Core::Type< T >::max, const T &step=T(1))
template<typename T >
std::string vector2str (const std::vector< T > &vec, const std::string &elemDelim=" ")
convert vector to string, elements are separated by elemDelim
template<typename Signed >
bool str2signed (const std::string &s, Signed &i)
Primitive data type conversion.
template<typename Unsigned >
bool str2unsigned (const std::string &s, Unsigned &u)
template<typename Float >
bool str2float (const std::string &s, Float &f)
template<>
bool strconv< bool > (const std::string &s, bool &b)
template<>
bool strconv (const std::string &s, s8 &i)
template<>
bool strconv (const std::string &s, s16 &i)
template<>
bool strconv (const std::string &s, s32 &i)
template<>
bool strconv (const std::string &s, s64 &i)
template<>
bool strconv (const std::string &s, u8 &u)
template<>
bool strconv (const std::string &s, u16 &u)
template<>
bool strconv (const std::string &s, u32 &u)
template<>
bool strconv (const std::string &s, u64 &u)
template<>
bool strconv (const std::string &s, f32 &f)
template<>
bool strconv (const std::string &s, f64 &f)
template<>
bool strconv (const std::string &s, std::string &ss)
String conversion; strips whitspaces.
template<typename T >
bool str2vector (const std::string &s, std::vector< T > &e, const std::string &elemDelim, const std::string &rangeDelim, const T &minValue, const T &maxValue, const u32 &minSize, const u32 &maxSize, const T &step)
template<typename T >
bool str2vector (const std::string &s, std::vector< T > &e, const std::string &elemDelim, const std::string &rangeDelim, const std::string &assignDelim, const T &minValue, const T &maxValue, const u32 &minSize, const u32 &maxSize, const T &step)
template<>
bool strconv (const std::string &s, std::vector< u8 > &v)
template<>
bool strconv (const std::string &s, std::vector< u16 > &v)
template<>
bool strconv (const std::string &s, std::vector< u32 > &v)
template<>
bool strconv (const std::string &s, std::vector< u64 > &v)
template<>
bool strconv (const std::string &s, std::vector< s8 > &v)
template<>
bool strconv (const std::string &s, std::vector< s16 > &v)
template<>
bool strconv (const std::string &s, std::vector< s32 > &v)
template<>
bool strconv (const std::string &s, std::vector< s64 > &v)
template<>
bool strconv (const std::string &s, std::vector< f32 > &v)
template<>
bool strconv (const std::string &s, std::vector< f64 > &v)
template<>
bool strconv (const std::string &s, std::vector< std::string > &v)
Vector of strings conversion; strips whitespaces.
template<class T >
TsRef< T > tsRef (T *o)
Convenience constructors for TsRef smart pointers.
template<template< typename > class XmlElemThisType, typename T >
std::enable_if<!NumberTypeList::contains< T >::value, bool >::type xmlMatchTagName (const XmlElemThisType< T > &elem, const char *name)
template<template< typename > class XmlElemThisType, typename T >
std::enable_if< NumberTypeList::contains< T >::value, bool >::type xmlMatchTagName (const XmlElemThisType< T > &elem, const char *name)
template<size_t size>
void swapEndianess (void *buf, size_t count=1)
Change endianess of a block of data.
template void swapEndianess< 2 > (void *buf, size_t count)
template void swapEndianess< 4 > (void *buf, size_t count)
template void swapEndianess< 8 > (void *buf, size_t count)
template<>
void swapEndianess< 1 > (void *buf, size_t count)
int getline (std::istream &, std::string &, std::string delim="\n")
reads from input stream until one of the specified delimiters
int wsgetline (std::istream &is, std::string &str, std::string delim="\n")
std::string & itoa (std::string &s, unsigned int val)
std::string itoa (u32 i)
template<class A , class B >
tied< A, B > tie (A &a, B &b)
int abs (int v)
Core::abs : wrapper for several absolute value functions.
long int abs (long int v)
long long int abs (long long int v)
float abs (float v)
double abs (double v)
long double abs (long double v)
template<class T >
T abs (const std::complex< T > &v)
template<class InputIterator , class M >
void maxAbsoluteElement (InputIterator begin, InputIterator end, M &m)
Maximal absolute value in v is returned in m.
template<class T >
T maxAbsoluteElement (const std::vector< T > &v)
template<class T >
T maxAbsoluteElement (const std::vector< std::complex< T >> &v)
float round (float v)
Core::round : wrapper for several round functions.
double round (double v)
float ceil (float v)
Core::ceil : wrapper for several ceil functions.
double ceil (double v)
float floor (float v)
Core::floor : wrapper for several floor functions.
double floor (double v)
template<class InputIterator >
bool isNormal (InputIterator begin, InputIterator end)
template<class F >
bool isMalformed (F f)
template<class T >
T clip (T x)
Checks if.
float log (float v)
Core::log : numerically robust wrapper for log functions.
double log (double v)
template<class InputIterator >
bool isMalformed (InputIterator begin, InputIterator end)
template<class F , class G , class H >
composedBinaryFunction< F, G, H > composeBinaryFunction (const F &f, const G &g, const H &h)
bool isAlmostEqual (f32 a, f32 b, f32 tolerance=(f32) 1)
Test for near-equality of floating point numbers.
bool isAlmostEqual (f64 a, f64 b, f64 tolerance=(f64) 1)
bool isAlmostEqual (const std::complex< f32 > &a, const std::complex< f32 > &b, const std::complex< f32 > tolerance=std::complex< f32 >((f32) 1,(f32) 1))
bool isAlmostEqual (const std::complex< f64 > &a, const std::complex< f64 > &b, const std::complex< f64 > tolerance=std::complex< f64 >((f64) 1,(f64) 1))
bool isSignificantlyGreater (f32 a, f32 b, f32 tolerance=(f32) 1)
bool isSignificantlyGreater (f64 a, f64 b, f64 tolerance=(f64) 1)
bool isSignificantlyLess (f32 a, f32 b, f32 tolerance=(f32) 1)
bool isSignificantlyLess (f64 a, f64 b, f64 tolerance=(f64) 1)
s32 differenceUlp (f32 a, f32 b)
Difference between two floating-point values in units of least precision (ULP).
s64 differenceUlp (f64 a, f64 b)
bool isAlmostEqualUlp (f32 a, f32 b, s32 tolerance)
Test for near-equality of floating point numbers with tolerance given in unit of least precision.
bool isAlmostEqualUlp (f64 a, f64 b, s64 tolerance)
bool isAlmostEqualUlp (f64 a, f64 b, s32 tolerance)
bool isSignificantlyLessUlp (f32 a, f32 b, s32 tolerance)
bool isSignificantlyLessUlp (f64 a, f64 b, s64 tolerance)
double timeDiff (timeval &start, timeval &end)
template<class T >
Core::BinaryOutputStream & operator<< (Core::BinaryOutputStream &o, const std::complex< T > &c)
binary output for std::complex<T>
template<class T >
Core::BinaryInputStream & operator>> (Core::BinaryInputStream &i, std::complex< T > &c)
binary input for std::complex<T>
TEST (Core, StringUtilities, StripWhiteSpace)
TEST (Core, StringUtilities, Split)
TEST (Core, StringUtilities, StartsWith)
TEST (Core, StringUtilities, Form)
Variables
const Choice boolChoice
Predefined Choice for boolean values.
const Choice infinityChoice
Predefined Choice for "inifinite" numbers.
const ParameterInt parameterObjectCacheSize ("size","max number of objects in the cache memory", 1, 1)
const ParameterString parameterObjectCacheDirectory ("directory","directory of cached objects")
const ParameterBool parameterObjectCacheDump ("dump","on/off dumping of objects", false)
const u8 reuseObjectCacheMode = 0
const u8 appendObjectCacheMode = 1
const u8 createObjectCacheMode = 2
const char requireTrailingBlank = 'Y'
const char prohibitTrailingBlank = 'N'
const char tolerateTrailingBlank = '='
const char *const defaultEncoding = "ISO-8859-1"
Detailed Description
Copyright 2020 RWTH Aachen University.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. Examples for Sprint Test Cases using TEST()
The test cases themself are not very useful and do not fully verify the functionality of the tested methods.
Function Documentation
int Core::abs (int v) inline
Core::abs : wrapper for several absolute value functions.
Definition at line 110 of file Core/Utility.hh.
Referenced by Math::Lapack::GenEigenProblemWithSchurDecomposition::calculateEigenvalue(), Math::Matrix< T, P >::columnNorm(), Signal::CrossCorrelation::crossCorrelation(), differenceUlp(), Signal::SilenceNormalization::flush(), Signal::hartleyToFourierAmplitude(), isAlmostEqual(), Mm::logNorm(), maxAbsoluteElement(), Math::Matrix< T, P >::normalizeColumnDirection(), Math::EigenvalueProblem::normalizeDiagonal(), Mm::SimdGaussDiagonalMaximumFeatureScorer::quantizationScalingFactor(), Math::EigenvalueProblem::real(), Mm::RpropOptimization< T >::RpropOptimization(), Signal::Warping::setInverseWarpingFunction(), Math::EigenvalueProblem::sortEigenvalues(), Math::Vector< Math::Vector< T, P >, P >::takeReciprocal(), Math::Vector< Math::Vector< T, P >, P >::takeSquareRoot(), and Signal::ScatterTransform::writeScatterMatrix().
template<class T > bool Core::allocateAlignedVector (T ** ptr, size_t size, T initialValue = static_cast<T>(0), size_t alignment = 16)
Aligned memory allocation for an array.
Definition at line 68 of file Allocator.hh.
References ensure.
std::string Core::baseName (const std::string & path)
Strip directory from filename.
Parameters
path a pathname
Returns
pathname with any leading directory components removed. If path ends with a slash, the result will be empty.
Definition at line 45 of file Directory.cc.
Referenced by Core::Application::getCacheArchiveWriter(), isExecutable(), and ArchiverApplication::main().
float Core::ceil (float v) inline
Core::ceil : wrapper for several ceil functions.
Definition at line 206 of file Core/Utility.hh.
bool Core::clearDirectory (const std::string & path)
Remove all contents of a directory recursively.
Definition at line 126 of file Directory.cc.
References joinPaths(), and removeDirectory().
Referenced by Core::DirectoryArchive::clear(), and removeDirectory().
template<class T > T Core::clip (T x)
Checks if.
Parameters
x is infinite and clips it to the largest representable value.
Returns
is clipped value of
Parameters
x.
Definition at line 247 of file Core/Utility.hh.
References require.
std::string Core::convertToLowerCase (const std::string & s)
Convert UTF-8 string to lower case.
Definition at line 92 of file StringUtilities.cc.
References narrow(), and widen().
Referenced by Bliss::CorpusDescriptionParser::includeFile().
std::string Core::convertToUpperCase (const std::string & s)
Convert UTF-8 string to upper case.
Definition at line 99 of file StringUtilities.cc.
References narrow(), and widen().
Referenced by Lattice::HtkReader::addState(), and Bliss::CorpusDescriptionParser::includeFile().
bool Core::createDirectory (const std::string & path)
Create directory.
Create given directory path. If consists of several components parent directories are created as needed. (similar to "mkdir -p")
Returns
true if path was created successfully or already existed.
Definition at line 113 of file Directory.cc.
Referenced by ArchiverApplication::getUsage(), Flf::WriterNode::init(), Audio::WavOutputNode::openFile_(), Speech::AffineFeatureTransformEstimator::postProcess(), and Core::ObjectCache< List >::writeBack().
s32 Core::differenceUlp (f32 a, f32 b)
Difference between two floating-point values in units of least precision (ULP).
Returns
The number of distinct floating-point values between a and b. I.e. If b is the smallest value greater than a, the return value is 1.
Definition at line 61 of file Core/Utility.cc.
References abs().
Referenced by isAlmostEqual(), and isAlmostEqualUlp().
std::string Core::directoryName (const std::string & path)
Return the directory name of a pathname.
Parameters
path a pathname
Returns
directory name of pathname path. If there is no slash in path, the result will be empty. The result will have no trailing slashes unless it is the root
Definition at line 26 of file Directory.cc.
Referenced by Flow::NetworkParser::buildFromFile(), Core::Application::getCacheArchiveWriter(), Core::ObjectCache< Core::MruObjectCacheList< std::string, Core::IoRef< Mm::AdaptorEstimator >, Core::StringHash, Core::StringEquality > >::getDirectory(), ArchiverApplication::getUsage(), Bliss::CorpusDescriptionParser::includeFile(), Audio::WavOutputNode::openFile_(), Speech::AffineFeatureTransformEstimator::postProcess(), Core::ObjectCache< List >::setDirectory(), Core::Configuration::tryToSet(), and Core::ObjectCache< List >::writeBack().
void Core::enforceTrailingBlank (std::string & s)
Ensure that a string ends with a single blank character.
Definition at line 64 of file StringUtilities.cc.
Referenced by Bliss::CorpusDescriptionParser::includeFile(), Bliss::OrthographicParser::parse(), Flf::Evaluator::setReference(), and Lm::CheatingSegmentLm::setSegment().
std::string Core::filenameExtension (const std::string & path)
Get filename extension.
If path is of the form "name.ext" return ".ext". Returns the empty string if does not contain ".".
Definition at line 99 of file Directory.cc.
Referenced by Flow::NetworkParser::buildFromFile(), isExecutable(), and Mm::MixtureSetReader::read().
float Core::floor (float v) inline
Core::floor : wrapper for several floor functions.
Definition at line 215 of file Core/Utility.hh.
Referenced by Signal::SampleNormalization::flush(), Signal::Warping::setInverseWarpingFunction(), Signal::Warping::setWarpingFunction(), and Core::ProgressIndicator::start().
std::string Core::form (const char * format, ...)
Formatted output conversion.
form() is equivalent to snprintf(3) but returns the result as a string.
Parameters
format a printf-like format string
Returns
the formatted string
Definition at line 106 of file StringUtilities.cc.
Referenced by Search::StateTree::SuffixSet::advance(), Flf::ConfusionNetworkAlignment::align(), Bliss::ContextPhonology::append(), Flf::applyEpsClosureFilter(), Search::Wfst::LexiconBuilder::build(), Search::LanguageModelLookahead::buildCompressesLookaheadStructure(), AdvancedTreeSearch::LanguageModelLookahead::buildCompressesLookaheadStructure(), Math::Lapack::GenEigenProblemWithSchurDecomposition::calculateEigenvalue(), Signal::PolinomialVectorInterpolation::checkInterpolationTime(), Am::ClassicStateTying::createClassicStateTyingRef(), Lm::BackingOffLm::Internal::draw(), Search::PersistentStateTree::dumpDotGraph(), Signal::FastFourierTransform::estimateContinuous(), Lm::WordlistInterfaceLm::formatHistory(), Flf::FittingLattice::Boundaries::get(), Flf::TopologicalOrderLattice::TopologicalOrderBoundaries::get(), Nn::NeuralNetwork< T >::getLayer(), TestApplication::getUsage(), ArchiverApplication::getUsage(), Core::Description::Stream::getValue(), Nn::Statistics< T >::gradientL1Norm(), Bliss::CorpusDescriptionParser::includeFile(), Flf::FramePosteriorCnCombinationNode::init(), Flf::ConfusionNetworkCombinationNode::init(), Flf::RoverCombinationNode::init(), Flf::ConcatenateNode::init_(), Flf::NBestBuilder::initialize(), Lm::WordlistInterfaceLm::isEquivalent(), AllophoneTool::main(), InternalIc::Icb::minimumDk(), Lm::BackingOffLm::Internal::mountImage(), Core::ParameterBitVector::parseString(), Core::MemoryInfo::peak(), Search::Wfst::Builder::CreateStateSequenceSymbols::process(), Flf::Semiring::read(), Flf::readConfusionNetworkFromXml(), Flf::readPosteriorCnFromXml(), Mm::AbstractMixtureEstimator::removeDensitiesWithLowWeight(), Flf::rescale(), Core::Configuration::resolveArithmeticExpressions(), Speech::Alignment::setAlphabet(), TransitionModel::Applicator::stateType(), Flf::UnknownAlphabet::symbol(), Am::AllophoneAlphabet::symbol(), Fsa::StaticAlphabet::symbol(), Am::AllophoneStateAlphabet::symbol(), Flf::uniqueSentenceAlignmentFilter(), Core::MemoryInfo::update(), Core::Description::verifyNumberOfStreams(), Speech::AlignmentDumpNode::work(), Speech::LatticeDumpCtmNode::work(), Am::AllophoneAlphabet::writeXml(), Am::AllophoneStateAlphabet::writeXml(), and BisonParser::ArithmeticExpressionParser::yytranslate_().
int Core::getline (std::istream & is, std::string & str, std::string delim = "\n")
reads from input stream until one of the specified delimiters
Parameters
istream input stream to read from
string resulting string that has been read; will not include a trailing delimiter
delim string of delimiters
Returns
returns EOF if nothing has been read, but the end of stream has been reached, returns 0 at the end of the stream, but no delimiter has been found, returns the position + 1 of the delimiter in delim that the resulting string ends with
Definition at line 24 of file Core/Utility.cc.
Referenced by ArchiverApplication::getUsage(), Bliss::CorpusDescription::SegmentPartitionVisitorAdaptor::leaveCorpus(), Mm::MixtureToMixtureMap::load(), ArchiverApplication::main(), Core::Configuration::parseInclude(), Core::TextInputStream::setEncoding(), Core::Configuration::tryToSet(), Speech::AlignmentDumpNode::work(), and Aligner::~Aligner().
bool Core::isAlmostEqual (f32 a, f32 b, f32 tolerance = (f32)1) inline
Test for near-equality of floating point numbers.
Due to finite precision, the bit-wise test (a == b) is almost always false. isAlmostEqual() compares the relative difference of a and b to the machine precision (epsilon) times the given tolerance factor.
Deprecation warning: For new code you should prefer isAlmostEqualUlp.
Remark: -A similar idea can be found under the name "chordal metric": chord(a, b) = |a - b| / (sqrt(1+a^2) * sqrt(1 + b^2)). -sorry for repeating the same implementation for each floating point type, but specialization to complex numbers seems to be a hard nut with templates.
Definition at line 316 of file Core/Utility.hh.
References abs(), and differenceUlp().
Referenced by Signal::HistogramNormalization::areScalesNormalized(), Signal::CrossCorrelationNode::configure(), Signal::PolinomialVectorInterpolation::copyControlPoint(), Search::Aligner::feed(), StretchToCover::init(), Math::Matrix< T, P >::isAlmostEqual(), Signal::LookupTable< Value, Index >::isMonotonous(), Search::Wfst::LexicalFstFactory::load(), Lm::ArpaLm::read(), Signal::FastFourierTransform::setLength(), Math::LevinsonLeastSquares::work(), and Audio::SourceNode::work().
bool Core::isAlmostEqualUlp (f32 a, f32 b, s32 tolerance) inline
Test for near-equality of floating point numbers with tolerance given in unit of least precision.
Due to finite precision, the bit-wise test (a == b) should not be use for floating point values. This function was taken from "Comparing floating point numbers" by Bruce Dawson [http://www.cygnus-software.com/papers/comparingfloats/comparingfloats.htm]. You will probably not be able to make sense of this code without reading the article.
Parameters
tolerance allowed difference between a and b measured in units of least precision (Ulp). This can be thought of as the number of different normalized floating point numbers between a and b.
This method is preferrable to the older isAlmostEqual(), because it is faster and theoretically more sound. So maybe isAlmostEqual() should be removed some time.
Definition at line 384 of file Core/Utility.hh.
References differenceUlp().
Referenced by Signal::SegmentClustering< Model >::computeAlpha(), Mm::CovarianceEstimator::estimate(), Flf::Semiring::extend(), and Flf::NBestBuilder::initialize().
bool Core::isDirectory (const std::string & path)
Test for directory.
Returns
true if path exists and is a directory.
Definition at line 147 of file Directory.cc.
Referenced by ArchiverApplication::getUsage(), Flf::WriterNode::init(), and Core::ObjectCache< List >::writeBack().
bool Core::isExecutable (const std::string & path)
Test if file / directory is executable.
Returns
true if path exists and is executable
Definition at line 178 of file Directory.cc.
References baseName(), defect, filenameExtension(), joinPaths(), and verify.
template<class F > bool Core::isMalformed (F f)
Returns
is true if
Parameters
f is "inf" or "nan".
Definition at line 238 of file Core/Utility.hh.
Referenced by Signal::CrossCorrelation::crossCorrelation(), Signal::PeakDetection::getHeightConfidence(), isMalformed(), and log().
template<class InputIterator > bool Core::isMalformed (InputIterator begin, InputIterator end)
Returns
is true if [begin..end) interval contains any malformed value (
See also
isMalformed(F f)).
Definition at line 268 of file Core/Utility.hh.
References isMalformed().
template<class InputIterator > bool Core::isNormal (InputIterator begin, InputIterator end)
Returns
is true if [begin..end) interval does not contain any "inf", "nan" etc. value.
Definition at line 227 of file Core/Utility.hh.
bool Core::isReadable (const std::string & path)
Test if file / directory is readable.
Returns
true if path exists and is readable
Definition at line 170 of file Directory.cc.
bool Core::isRegularFile (const std::string & path)
Test for regular file.
Returns
true if path exists and is a regular file.
Definition at line 155 of file Directory.cc.
Referenced by Flow::NetworkParser::buildFromFile(), Lm::BackingOffLm::initialize(), Core::Configuration::tryToSet(), and Mm::Module_::writeMixtureSetEstimator().
bool Core::isSymbolicLink (const std::string & path)
Test for symbolic link.
Returns
true if path exists and is a symbolic link
Definition at line 163 of file Directory.cc.
bool Core::isValidPath (const std::string & path)
Test for pathname.
Returns
true if path exists.
Definition at line 142 of file Directory.cc.
Referenced by Speech::AlignmentDumpNode::configure(), and Flf::BatchNode::init().
bool Core::isWhitespaceNormalized (const std::string & s, char trailingBlank = prohibitTrailingBlank)
Test if a string is whitespace-normalized.
Returns
true iff s matches (+)*
Parameters
trailingBlank specifies if a trailing blank is required. The default is to classify strings ending with a blank as not normalized. If requireTrailingBlank is given, the string is considered normalized only if it ends with a single blank.
Definition at line 24 of file StringUtilities.cc.
References require.
Referenced by Bliss::OrthographicParser::parse().
bool Core::isWritable (const std::string & path)
Test if file / directory is writable.
Returns
true if path exists and is writable
Definition at line 174 of file Directory.cc.
std::string Core::joinPaths (const std::string & path1, const std::string & path2)
Join two path components intelligently.
Parameters
path1 first pathname component
path2 second pathname component
Returns
the concatenation of path1 and path2, with exactly one slash ('/') inserted in between, unless one of them is empty. If path2 is an absolute path path1 is thrown away.
Definition at line 55 of file Directory.cc.
Referenced by Flow::NetworkParser::buildFromFile(), Core::DirectoryArchive::clear(), Core::ObjectCache< List >::clear(), clearDirectory(), ArchiverApplication::getUsage(), Bliss::CorpusDescriptionParser::includeFile(), Flf::WriterNode::init(), isExecutable(), Core::ObjectCache< List >::ObjectCache(), Speech::AffineFeatureTransformEstimator::postProcess(), and Core::Configuration::tryToSet().
float Core::log (float v) inline
Core::log : numerically robust wrapper for log functions.
Definition at line 255 of file Core/Utility.hh.
References isMalformed(), and require.
Referenced by Signal::SegmentClustering< Model >::computePenalty(), Nn::TrainerFeatureScorer::flush(), Speech::FsaCache::forceOutputAlphabet(), Flf::BatchNode::init(), TestApplication::main(), ArchiverApplication::main(), Core::DirectoryArchive::recover(), Core::FileArchive::recover(), Core::FileArchive::remove(), and Signal::MeanEstimator::write().
StringExpression Core::makeStringExpression (const std::string & stringExpression, const std::string & openTag = "$(", const std::string & closeTag = ")")
helper function to parse and create a StringExpression
Definition at line 138 of file StringExpression.cc.
Referenced by Flow::StringExpressionNode::getInput().
template<class InputIterator , class M > void Core::maxAbsoluteElement (InputIterator begin, InputIterator end, M & m)
Maximal absolute value in v is returned in m.
If v is empty, result is set to Type<T>::min.
Definition at line 149 of file Core/Utility.hh.
References abs().
Referenced by Math::Lapack::GenEigenProblemWithSchurDecomposition::copyEigenvalues(), and Math::EigenvalueProblem::real().
std::string Core::normalizePath (const std::string & path)
Normalize a pathname.
This collapses redundant separators and up-level references, e.g. A//B, A/./B and A/foo/../B all become A/B. It should be understood that this may change the meaning of the path if it contains symbolic links.
Definition at line 67 of file Directory.cc.
Referenced by Flf::stripExtension().
void Core::normalizeWhitespace (std::string & s)
Definition: A string has "normalized whitespace" if and only if it matches one the following regular expressions: (+)* or (+)* + where matches any non-whitespace character.
I.e. There are no whitespaces other than single blanks; the first character is non-blank, and the last character may be blank. Normalize whitespace in a string. All consecutive whitespaces in the passed string are replaced by a single blank. Leading whitespace is removed.
Attention: If tailing whitspaces exist, a single whitspace has to remain!
Parameters
s the string to be normalized
Definition at line 45 of file StringUtilities.cc.
Referenced by ArchiverApplication::getUsage(), ArchiverApplication::main(), Speech::OrthographyFrameStateAccuracyLatticeBuilder::OrthographyFrameStateAccuracyLatticeBuilder(), Lm::ArpaLm::read(), Flf::Evaluator::setReference(), and Lm::CheatingSegmentLm::setSegment().
template<class T > Core::BinaryOutputStream& Core::operator<< (Core::BinaryOutputStream & o, const std::complex< T > & c)
binary output for std::complex<T>
Definition at line 145 of file Complex.hh.
template<class T > Core::BinaryInputStream& Core::operator>> (Core::BinaryInputStream & i, std::complex< T > & c)
binary input for std::complex<T>
Definition at line 151 of file Complex.hh.
template<class T > Ref<T> Core::ref (T * o) inline
Convenience constructors for Ref smart pointers.
Definition at line 301 of file ReferenceCounting.hh.
Referenced by Speech::AlignmentToSequenceSelectionNode::Set::acceptParameterNamePrefix(), Bliss::EditDistance::align(), Speech::LatticeSetGenerator::alignmentGenerator(), Aligner::WordLatticeBuilder::Converter::build(), Speech::ClusterMixtureSetTrainer::ClusterMixtureSetTrainer(), Lm::compose(), Speech::AlignmentDumpNode::configure(), Flow::CacheNode::configure(), Flow::Network::configure(), Speech::DataSource::convert(), Am::Module_::createAcousticModel(), Lm::Module_::createLanguageModel(), Mm::Module_::createMixtureSet(), WordConditionedTreeSearch::SearchSpace::createTraces(), Ftl::CopyDfsState< _Automaton >::discoverState(), Search::Wfst::ExpandingFsaSearch::getCurrentBestSentence(), Search::AdvancedTreeSearchManager::getCurrentBestSentencePartial(), Lm::BackingOffLm::getFsa(), Flow::Node::getInputAttributes(), Search::LinearSearch::getPartialSentence(), ArchiverApplication::getUsage(), WordConditionedTreeSearch::SearchSpace::hypothesizeEpsilonPronunciations(), Search::SearchSpace::hypothesizeEpsilonPronunciations(), Lm::BackingOffLm::initialize(), Speech::NumeratorLatticeGenerator::initialize(), Am::AdaptationTree::loadDecisionTree(), AllophoneTool::main(), TestApplication::main(), Search::SearchSpace::minimumWordEndScore(), Speech::OfflineRecognizer::processResult(), Core::FormatSet::registerFormat(), Speech::LatticeSetGenerator::segmentwiseFeatureExtractor(), Flf::LatticeArchiveWriterNode::sendLattice(), Speech::FsaCache::setDependencies(), Am::AcousticModel::setKey(), AcousticModelTrainer::showMixtureSet(), TransitionModel::Applicator::stateType(), Am::AllophoneStateAlphabet::symbol(), Speech::AlignmentGeneratorNode::work(), Speech::StatePosteriorFeatureScorerNode::work(), Signal::MatrixMultiplicationNode< T >::work(), and Bliss::PhonemeInventory::writeBinary().
bool Core::removeDirectory (const std::string & path)
Remove a directory.
This recursively removes all contents from the given directory, then removes the directory itself (similar to "rm -r").
Definition at line 138 of file Directory.cc.
References clearDirectory().
Referenced by clearDirectory().
float Core::round (float v) inline
Core::round : wrapper for several round functions.
Definition at line 197 of file Core/Utility.hh.
Referenced by Flf::DumpAllPairsShortestDistanceNode::init(), Signal::FilterBank::Boundary::init(), Flf::ConfusionNetworkCombination::init(), Flf::sausageLattice2cn(), Flf::CtmReaderNode::sendLattice(), TrapezeRastaFilterBuilder::setEnd(), TrapezeRastaFilterBuilder::setStart(), and Flf::writeConfusionNetworkAsText().
std::vector< std::string > Core::split (const std::string & string, const std::string & separator)
Split string into tokens.
Return a list of the tokens in the string, using separator as the delimiter string. Any Leading or trailing whitespace is stripped ffrom the word returned. Consecutive delimiters are not grouped together and are deemed to delimit empty strings (for example, split("1,,2", ",") returns ["1", "", "2"]"). The separator argument may consist of multiple characters (for example, split("1, 2, 3", ", ") returns ["1", "2", "3"]). Splitting an empty string with a specified separator returns an empty list.
Definition at line 167 of file StringUtilities.cc.
References stripWhitespace().
Referenced by Am::ClassicStateTying::createClassicStateTyingRef(), Search::Wfst::StateSequenceBuilder::createSymbols(), Speech::LemmaPronunciationId_hash_map::init(), Mm::MixtureToMixtureMap::load(), Math::MatrixTool::main(), Search::Wfst::Builder::FileOperation::precondition(), Translation::ConditionalLexiconSri::read(), Translation::ConditionalLexiconPlain::read(), Nn::NeuralNetwork< T >::saveParameters(), Signal::NthOrderFeaturesNode::setParameter(), Speech::LatticeArcAccumulatorNode::work(), Speech::AlignmentDumpNode::work(), and Aligner::~Aligner().
bool Core::startsWith (const std::string & string, const std::string & search)
Like the python startswith method of strings.
return true is string starts with search
Definition at line 191 of file StringUtilities.cc.
template<typename Signed > bool Core::str2signed (const std::string & s, Signed & i)
Primitive data type conversion.
Definition at line 217 of file StringUtilities.hh.
References boolChoice, infinityChoice, and strconv().
template<typename T > bool Core::str2vector (const std::string & s, std::vector< T > & e, const std::string & elemDelim)
String to list conversion.
Vector of primitive datatypes conversion.
Used by strconv to convert a string to a list. Use instead of strconv if you need to specify element and range delimiter and range borders and step width. Default seperator is space or tab for strings and comma for any others; number ranges can be specified by placing a - between two numbers.
Definition at line 349 of file StringUtilities.hh.
References require, and strconv().
Referenced by Core::ParameterBitVector::parseString(), and Nn::NeuralNetwork< T >::saveParameters().
template<typename T > bool Core::strconv (const std::string & s, T & t)
Convinient functions to parse strings.
Generalized conversion.
returns true on successful conversion; the string argument may contain leading and tailing whitspaces. general string to something conversion; currently specialized for:
standard datatypes
strings
vectors of standard datatypes
vectors of standard strings supports:
different representations of bool values
+/-inf for numerical types
ranges for numerical values
Definition at line 185 of file StringUtilities.hh.
Referenced by Lattice::HtkReader::addState(), Cart::XmlPropertiesBuilderElement::characters(), Cart::XmlExampleListMergerElement::characters(), Am::ClassicStateTying::createClassicStateTyingRef(), Cart::XmlFloatBoxBuilderElement::end(), Flf::BatchNode::finalize(), Flf::UnknownAlphabet::index(), Flf::ExtendByPenaltyNode::init(), Flf::RescoreSingleDimensionNode::init_(), Core::AbstractChoiceParameter< T >::printParseHelp(), Core::ParameterInt::printParseHelp(), Core::ParameterFloat::printParseHelp(), Search::Wfst::Builder::Relabel::process(), Translation::ConditionalLexiconPlain::read(), Cart::XmlIndexedStringBuilderElement::start(), Cart::XmlBinaryTreeRootBuilderElement::start(), Cart::XmlFloatBoxBuilderElement::start(), str2signed(), str2vector(), Speech::AlignmentNode::work(), Speech::AlignmentDumpNode::work(), Flf::writeConfusionNetworkAsText(), Flf::writePosteriorCnAsText(), and Am::AllophoneAlphabet::writeXml().
template<typename T > bool Core::strconv (const std::string & s, T & t, const Choice & c)
Maps a given string to value of type T via the given Choice object; returns true on successful mapping.
Choice conversion.
Definition at line 197 of file StringUtilities.hh.
template<> bool Core::strconv (const std::string & s, std::string & ss) inline
String conversion; strips whitspaces.
Definition at line 336 of file StringUtilities.hh.
template<> bool Core::strconv (const std::string & s, std::vector< std::string > & v) inline
Vector of strings conversion; strips whitespaces.
Definition at line 537 of file StringUtilities.hh.
std::string Core::stripExtension (const std::string & path)
Strips the extension of the.
Parameters
path. If
path does not have an extenstion
Returns
is
Parameters
path without changes.
Strips the extension of the.
Definition at line 106 of file Directory.cc.
References defect, Core::Component::error(), normalizePath(), Core::Application::us(), and Core::Component::warning().
void Core::stripWhitespace (std::string & s)
Remove leading and trailing whitespace.
Definition at line 74 of file StringUtilities.cc.
References ensure.
Referenced by Am::AllophoneAlphabet::add(), Lattice::HtkReader::addState(), Cart::XmlPropertiesDefinitionBuilderElement::characters(), Am::ClassicStateTying::createClassicStateTyingRef(), Search::Wfst::StateSequenceBuilder::createSymbols(), Cart::XmlIndexedStringBuilderElement::end(), XmlBuilder2::XmlChoiceBuilderElement::end(), Bliss::CorpusDescription::SegmentPartitionVisitorAdaptor::leaveCorpus(), Core::MemoryInfo::peak(), Core::Configuration::resolveArithmeticExpressions(), and split().
void Core::suppressTrailingBlank (std::string & s)
Remove trailing blank character.
Removes the last character if it is a blank.
Definition at line 69 of file StringUtilities.cc.
Referenced by ArchiverApplication::getUsage(), ArchiverApplication::main(), and Lm::ArpaLm::read().
template<size_t size> void Core::swapEndianess (void * buf, size_t count = 1)
Change endianess of a block of data.
The size argument is given as a template parameter, so the compiler can unroll the loop.
Parameters
buf pointer to an array of data
size size of the element data type in bytes.
count number of elements
Definition at line 75 of file Core/Types.cc.
template<class T > TsRef<T> Core::tsRef (T * o) inline
Convenience constructors for TsRef smart pointers.
Definition at line 247 of file ThreadSafeReference.hh.
Referenced by Speech::StatePosteriorFeatureScorerNode::work().
template<typename T > std::string Core::vector2str (const std::vector< T > & vec, const std::string & elemDelim = " ")
convert vector to string, elements are separated by elemDelim
Definition at line 559 of file StringUtilities.hh.
Referenced by Nn::MeanNormalizedSgd< T >::estimate(), Nn::Adam< T >::estimate(), Nn::AdaGrad< T >::estimate(), Nn::AdaDelta< T >::estimate(), and Nn::RmsProp< T >::estimate().
bool Core::writeLargeBlock (int fd, const char * buf, u64 count)
Write a larger (>2GB) block of memory to a file.
Parameters as in write(2) returns true on success
Definition at line 39 of file IoUtilities.cc.
Referenced by Lm::BackingOffLm::Internal::writeImage().
Variable Documentation
const Choice Core::boolChoice
Predefined Choice for boolean values.
(e.g. "true", "false, "yes", "no" ...).
Referenced by Core::Choice::printIdentifiers(), and str2signed().
const Choice Core::infinityChoice
Predefined Choice for "inifinite" numbers.
(e.g. "infinite", "-infinity", "unlimited" ...)
Referenced by Core::Choice::printIdentifiers(), and str2signed().