Sprint: Search Namespace Reference
Search Namespace Reference
Copyright 2020 RWTH Aachen University.
Classes
class AccessiblePriorityQueue
class AdvancedTreeSearchManager
class Aligner
Forced state-level alignment of network with observation seqeuence.
struct AlternativeHistory
struct AlternativeHistoryCompare
class ApproxLinearIntHash
For efficiency-reasons, the default-value is hardcoded to U16_MAX This is a tiny bit faster than the standard approximative mini-hash, but also a bit less precise.
class ApproxLinearMiniHash
For efficiency-reasons, the default-value is hardcoded to F32_MAX.
struct ConvertTree
struct CountSizeTreeWalkerBackend
class DynamicBeamPruningStrategy
struct EarlyWordEndHypothesis
class Histogram
histogram of scores for histogram pruning
struct HistoryStateHash
struct HMMState
The standard network state, representing a state and its successor-links.
class HMMStateNetwork
class InitialTraceChanger
struct Instance
struct InstanceKey
Object that contains the information that conditions a network, and thereby makes the network unique.
class LanguageModelLookahead
Language model look-ahead.
class LatticeAdaptor
Basic interface for various types of lattices generated by the decoders.
class LatticeHandler
Input and output of lattices in various formats.
class LinearMiniHash
A specialized hash-map, which is optimized for the following case:
class LinearPrediction
class LinearSearch
struct LinearSearchHistoryData
class LmCache
struct LmCacheEqual
struct LmCacheHash
struct LmCacheItem
struct LmCacheKey
class MaximumDelayBeamPruningStrategy
class MinimumBayesRiskAStarSearch
Computes minimum Bayes risk hypothesis as proposed by Byrne and Goel.
class MinimumBayesRiskMapSearch
The standard approach to speech recognition is based on a 0-1-loss Bayes decision rule.
class MinimumBayesRiskNBestListNaiveSearch
Implementation of the naive approach for minimum Bayes risk using an nbestlist for both the evaluation space as well as for the summation space.
class MinimumBayesRiskNBestListSearch
Interface for search process of minimum Bayes risk using nbestlists as evaluation space, i.e.
class MinimumBayesRiskSearch
Interface for performing a search for the best string in an Fsa w.r.t.
struct MinimumCombine
class Module_
class PartialNbestlist
class PathRecombination
class PathRecombinationApproximation
class PathTrace
class PersistentStateTree
class PrefixFilter
class RootTraceSearcher
class ScoreDependentStatistic
class ScoreDependentVectorStatistic
class SearchAlgorithm
class SearchSpace
struct SearchSpaceStatistics
class SentenceEndAutomaton
class SparseVector
struct StandardApproxValueHash
struct StandardValueHash
struct StateHypothesis
A state hypothesis consists of the probability of a network state within one specific network copy, together with its back-pointer (the trace).
class StateTree
Acoustic prefix tree.
class StateTreeIo
State tree input / output functions.
class StateTreeReader
Reconstructs a state tree from a file.
class StateTreeWriter
Writes a state tree to a binary file.
class StaticSearchAutomaton
struct StringHypothesis
class SubTreeWalker
Inherit this, and then in the given base, implement nodeVisited(TreeNodeIndex, token), visitExit(uint exit, token), and visitNode(TreeNodeIndex, token)
class Trace
struct TraceItem
class TraceManager
struct Tree
class WordConditionedTreeSearch
struct WordEndHypothesis
class WordPronunciationState
class WordSequenceAligner
Typedefs
typedef s32 StateHypothesisIndex
typedef std::vector< WordEndHypothesis > WordEndHypothesisList
typedef std::vector< EarlyWordEndHypothesis > EarlyWordEndHypothesisList
typedef std::pair< Lm::History, StateId > ReducedContextRecombinationKey
typedef std::unordered_map< ReducedContextRecombinationKey, WordEndHypothesisList::iterator, HistoryStateHash > ReducedContextRecombinationMap
using AlternativeHistoryQueue = AccessiblePriorityQueue< AlternativeHistory, std::vector< AlternativeHistory >, AlternativeHistoryCompare >
typedef u32 TraceId
typedef u32 SuccessorBatchId
This index represents an arbitrary list of successor-states and labels.
typedef u32 TreeIndex
Global index of a tree or subtree.
typedef u32 StateId
Index of a state or label (see IS_LABEL, ID_FROM_LABEL, and LABEL_FROM_ID)
typedef u32 SubTreeListId
Index representing the batch of all nodes that are contained by one tree.
typedef Search::SubTreeWalker< int, CountSizeTreeWalkerBackend > CountSizeTreeWalker
typedef Core::Ref< WordPronunciationState > WordPronunciationStatePointer
The pronunciation including its current state.
typedef MinimumBayesRiskAStarSearch::ConstSearchNodeRef ConstSearchNodeRef
typedef MinimumBayesRiskAStarSearch::SearchNodeRef SearchNodeRef
typedef std::vector< Fsa::LabelId > Sentence
typedef std::vector< StringHypothesis > HypothesisVector
typedef Core::SingletonHolder< Module_ > Module
typedef f32 Score
typedef u32 TimeframeIndex
typedef u32 Index
typedef std::vector< Index > IndexVector
Enumerations
enum { MaxFadeInPruningDistance = 255 }
enum { SingleSuccessorBatchMask = 1 << 30, LabelMask = 1 << 27 }
enum { InvalidBatchId = 0 }
enum SearchType { WordConditionedTreeSearchType, AdvancedTreeSearch, LinearSearchType, ExpandingFsaSearchType }
Functions
std::unique_ptr< DynamicBeamPruningStrategy > createDynamicBeamPruningStrategy (Core::Configuration const &config, SearchAlgorithm::PruningRef initialPruning)
template<class T >
MappedArchiveReader & operator>> (MappedArchiveReader &reader, std::set< T > &target)
template<class T >
MappedArchiveWriter & operator<< (MappedArchiveWriter &writer, const std::set< T > &set)
template<class T , class T2 >
MappedArchiveReader & operator>> (MappedArchiveReader &reader, std::map< T, T2 > &target)
template<class T , class T2 >
MappedArchiveWriter & operator<< (MappedArchiveWriter &writer, const std::map< T, T2 > &set)
inline_ bool IS_LABEL (const StateId x)
Returns whether the given edge-successor index represents a label rather than a state.
inline_ StateId ID_FROM_LABEL (const u32 x)
Returns the representation index of this label as an edge-successor.
inline_ u32 LABEL_FROM_ID (StateId x)
Encodes the given index as an edge-successor so that it represents a label.
void extractAlignment (Speech::Alignment &out, Fsa::ConstAutomatonRef alignmentPosteriorFsa, Mm::Weight minProbGT=0.0, Mm::Weight gamma=1.0)
void computeLevenshteinColumn (const Fsa::LabelId symbol, const std::vector< Fsa::LabelId > &hypothesis, const std::vector< u32 > &oldScores, std::vector< u32 > &newScores, const u32 initialNewScore)
Computes one column of the DP levenshtein distance algorithm.
u32 minimum (const std::vector< u32 > &scores)
bool operator< (SearchNodeRef &lower, SearchNodeRef &taller)
Fsa::Weight posteriorRiskNBestList (const std::vector< Fsa::LabelId > &trueSentence, const std::vector< StringHypothesis > &hypotheses, Fsa::Weight &distanceOne, Fsa::Weight &maximumDistanceOne)
Naive computation of Bayes posterior risk assuming the Levenshtein loss function.
Fsa::Weight posteriorRiskNBestList (const std::vector< Fsa::LabelId > &trueSentence, const std::vector< StringHypothesis > &hypotheses, const Fsa::Weight &pruningThreshold=Fsa::LogSemiring->max())
Naive computation of Bayes posterior risk assuming the Levenshtein loss function.
u32 levenshteinDistance (const std::vector< LabelId > &A, const std::vector< LabelId > &B)
std::set< StateId > getContour (std::set< StateId > oldContour, ConstAutomatonRef fsa)
std::vector< Fsa::StateId > getDistances (ConstAutomatonRef fsa)
ConstAutomatonRef createLinearAutomatonFromVector (const std::vector< LabelId > &sequence, const Weight &score, ConstAlphabetRef inputAlphabet, ConstAlphabetRef outputAlphabet, ConstSemiringRef semiring)
Weight getNbestNormalizationConstant (ConstAutomatonRef nbestlist)
ConstAutomatonRef normalizeNbestlist (ConstAutomatonRef nbest)
ConstAutomatonRef partialNbestlist (ConstAutomatonRef nbestlist, u32 size)
Weight posteriorExpectedRisk (ConstAutomatonRef center, ConstAutomatonRef hypotheses)
Weight collectWeights (ConstSemiringRef sr, const Core::Vector< Weight > &weights)
Fsa::Weight getNbestNormalizationConstant (Fsa::ConstAutomatonRef nbestlist)
Fsa::ConstAutomatonRef normalizeNbestlist (Fsa::ConstAutomatonRef nbestlist)
Fsa::ConstAutomatonRef partialNbestlist (Fsa::ConstAutomatonRef nbestlist, u32 size)
u32 levenshteinDistance (const std::vector< Fsa::LabelId > &A, const std::vector< Fsa::LabelId > &B)
Compute levenshtein distance between two sentences using the dynamic programming algorithm.
std::set< Fsa::StateId > getContour (std::set< Fsa::StateId > oldContour, Fsa::ConstAutomatonRef fsa)
std::vector< Fsa::StateId > getDistances (Fsa::ConstAutomatonRef fsa)
Computes the longest distance for a state from the source of the fsa.
Fsa::ConstAutomatonRef createLinearAutomatonFromVector (const std::vector< Fsa::LabelId > &sequence, const Fsa::Weight &score=Fsa::Weight(), Fsa::ConstAlphabetRef inputAlphabet=Fsa::ConstAlphabetRef(), Fsa::ConstAlphabetRef outputAlphabet=Fsa::ConstAlphabetRef(), Fsa::ConstSemiringRef semiring=Fsa::ConstSemiringRef(Fsa::UnknownSemiring))
Fsa::Weight posteriorExpectedRisk (Fsa::ConstAutomatonRef center, Fsa::ConstAutomatonRef hypotheses)
Fsa::Weight collectWeights (Fsa::ConstSemiringRef sr, const Core::Vector< Fsa::Weight > &weights)
template<>
void StateTreeIo::read< StateTree::Exit > (Input &i, StateTree::Exit &exit) const
template<>
void StateTreeIo::write< StateTree::Exit > (Output &o, const StateTree::Exit &exit) const
template<>
void StateTreeIo::read< StateTree::StateDesc > (Input &i, StateTree::StateDesc &desc) const
template<>
void StateTreeIo::write< StateTree::StateDesc > (Output &o, const StateTree::StateDesc &desc) const
template<>
void StateTreeIo::read< StateTree::State > (Input &i, StateTree::State &state) const
template<>
void StateTreeIo::write< StateTree::State > (Output &o, const StateTree::State &state) const
template<>
void StateTreeIo::read< StateTree::CoarticulationStructure::PhonemePair > (Input &i, StateTree::CoarticulationStructure::PhonemePair &pair) const
template<>
void StateTreeIo::write< StateTree::CoarticulationStructure::PhonemePair > (Output &o, const StateTree::CoarticulationStructure::PhonemePair &pair) const
Variables
const Core::ParameterString paramPrefixWords ("prefix-words","","")
static const f32 defaultBeamPruning = 12.0
Pruning (NOTE: pruning values are relative to the lm-scale, if not noted otherwise):
const Core::ParameterFloat paramBeamPruning ("beam-pruning","Beam size used for pruning state hypotheses, relative to the lm-scale. \ Typically between 8 and 12. Default: 12.0 if nothing else is set.", Core::Type< f32 >::max, 0)
const Core::ParameterBool paramHistogramIsMasterPruning ("histogram-pruning-is-master-pruning","", false)
const Core::ParameterFloat paramAcousticPruning ("acoustic-pruning","DEPRECATED: Use beam-pruning instead! (difference: beam-pruning is relative to the lm-scale, while this is not)", Core::Type< f32 >::max, 0.0)
const Core::ParameterInt paramBeamPruningLimit ("beam-pruning-limit","maximum number of active states, enforced by histogram pruning \ this value is important, because it sets an upper bound for the runtime.", 500000, 1)
const Core::ParameterInt paramAcousticPruningLimit ("acoustic-pruning-limit","DEPRECATED: Use beam-pruning-limit instead.", Core::Type< s32 >::max, 1)
const Core::ParameterFloat paramWordEndPruning ("word-end-pruning","threshold for pruning of word end hypotheses \ If the value is below 1.0, eg. 0.7, then it is relative to acoustic-pruning (recommended).", Core::Type< f32 >::max, 0.0)
const Core::ParameterInt paramWordEndPruningLimit ("word-end-pruning-limit","maximum number of word ends, enforced by histogram pruning \ this value is important, because it sets an upper bound for the runtime \ 20000 is a good default value, reduce it more if the runtime becomes too slow for some segments.", Core::Type< s32 >::max, 1)
const Core::ParameterFloat paramLmPruning ("lm-pruning","DEPRECATED: Use word-end-pruning instead (difference: word-end-pruning is relative to the lm-scale, while this value is absolute).", Core::Type< f32 >::max, 0.0)
const Core::ParameterInt paramLmPruningLimit ("lm-pruning-limit","DEPRECATED: Use word-end-pruning-limit instead.", Core::Type< s32 >::max, 1)
const Core::ParameterFloat lmStatePruning ("lm-state-pruning","pruning that is applied to all state hypotheses which are on the same state in the prefix network (can be lower than lm-pruning) \ If the value is below one, eg. 0.7, then it is relative to word-end-pruning (recommended). \ This pruning is effective only if the search network is minimized (eg. build-minimized-tree-from-scratch=true and min-phones <= 1)", Core::Type< f32 >::max)
const Core::ParameterFloat paramAcousticLookaheadTemporalApproximationScale ("acoustic-lookahead-temporal-approximation-scale","scaling factor of temporal acoustic look-ahead (1.5 is a good value)", 0)
const Core::ParameterFloat paramPerInstanceAcousticPruningScale ("per-instance-acoustic-pruning-scale","when using per instance pruning thresholds the pruning threshold is the beam-pruning threshold times this scale", 1.0)
const Core::ParameterFloat paramEarlyWordEndPruningMinimumLmScore ("early-word-end-pruning-minimum-lm-score","expected lm-score that will be used for early word-end pruning (safe if it is always lower than the real score)", 0)
const Core::ParameterFloat paramWordEndPhonemePruningThreshold ("word-end-phoneme-pruning","pruning applied to word ends which have the same final phoneme (relative to word-end-pruning if the value is below 1.0)", Core::Type< Score >::max)
const Core::ParameterInt paramWordEndPruningFadeInInterval ("word-end-pruning-fadein","inverted depth at which the lm pruning influence reaches zero", 0, 0, MaxFadeInPruningDistance)
const Core::ParameterBool paramBuildMinimizedTreeFromScratch ("build-minimized-network-from-scratch","", true)
Internal parameters (with good default-values)
const Core::ParameterBool paramConditionPredecessorWord ("condition-on-predecessor-word","", false)
const Core::ParameterBool paramDecodeMesh ("decode-mesh","produce a mesh-like reduced lattice, which can later be expanded by mesh-construction and lattice-decoding to the full search space", false)
const Core::ParameterInt paramDecodeMeshPhones ("decode-mesh-phones","-1 means full pronunciation, eg. word pair approximation. 0 means no context. otherwise number of condition phones.",-1,-1)
const Core::ParameterBool paramEnableLmLookahead ("lm-lookahead","enable language model lookahead (recommended)", true)
const Core::ParameterBool paramSeparateLookaheadLm ("separate-lookahead-lm","use a separate lm for lookahead (one that is not provided by the main language-model)", false)
const Core::ParameterBool paramSeparateRecombinationLm ("separate-recombination-lm","use a separate lm for recombination (one that is not provided by the main language-model)", false)
const Core::ParameterBool paramDisableUnigramLookahead ("disable-unigram-lookahead","", false)
const Core::ParameterBool paramSparseLmLookAhead ("sparse-lm-lookahead","use sparse n-gram LM look-ahead (recommended)", true)
const Core::ParameterBool paramSymmetrizePenalties ("symmetrize-penalties","", false)
const Core::ParameterInt paramReduceLookAheadBeforeDepth ("full-lookahead-min-depth","only apply unigram lookahead for states that have a lookahead-network-depth lower than this. negative values allow considering the pushed fan-out.", 0)
const Core::ParameterInt paramReduceLookAheadStateMinimum ("full-lookahead-min-states","apply full lookahead in instances that more than this number of active states", 0)
const Core::ParameterFloat paramReduceLookAheadDominanceMinimum ("full-lookahead-min-dominance","apply full-order lookahead in instances that have at least this dominance", 0.05)
const Core::ParameterBool paramEarlyBeamPruning ("early-beam-pruning","Whether beam pruning should already be performed before computing the acoustic scores, but after look-ahead scores have been applied.", true)
const Core::ParameterBool paramEarlyWordEndPruning ("early-word-end-pruning","enable earlier pruning of word-ends during the recombiniation", true)
const Core::ParameterBool paramReducedContextWordRecombination ("reduced-context-word-recombination","reduce the context of word-end hypotheses before recombination", false)
const Core::ParameterInt paramReducedContextWordRecombinationLimit ("reduced-context-word-recombination-limit","the maximum context length to consider when doing word combination", 1, 0)
const Core::ParameterBool paramReducedContextTreeKey ("reduced-context-tree-key","reduce the context of tree instance key (to reuse the tree)", false)
const Core::ParameterBool paramOnTheFlyRescoring ("on-the-fly-rescoring","keep track of recombined histories and use those aswell when searching for word ends", false)
const Core::ParameterInt paramOnTheFlyRescoringMaxHistories ("on-the-fly-rescoring-history-limit","what is the maximum number of alternative histories that should be kept", 5, 0)
const Core::ParameterInt paramMaximumMutableSuffixLength ("maximum-mutable-suffix-length","maximum length of words that are allowed to change", Core::Type< int >::max, 0)
const Core::ParameterInt paramMaximumMutableSuffixPruningInterval ("maximum-mutable-suffix-pruning-interval","perform mutable-suffix-pruning every n frames", 0, 0)
const Core::ParameterBool paramExtendedStatistics ("expensive-statistics","add additional performance-wise expensive statistics", false)
const Core::ParameterBool paramEarlyBackOff ("early-backoff","enable early backing-off right at the root states, as done in WFST based decoders (lazy dominance-based look-ahead activation is recommended, eg. for example full-lookahead-min-dominance=0.1)", false)
const Core::ParameterBool paramCorrectPushedWordBoundaryTimes ("correct-pushed-word-boundary-times","correct the word boundary times that are changed through word-end pushing. Activate this if you want to generate alignments or similar", true)
const Core::ParameterBool paramCorrectPushedAcousticScores ("correct-pushed-acoustic-scores","correct the acoustic scores that were changed through word-end pushing. Activate this if you need to compute confidence-scores or similar", true)
const Core::ParameterFloat paramUnigramLookaheadBackOffFactor ("unigram-lookahead-backoff-factor","", 0.0)
const Core::ParameterBool paramOverflowLmScoreToAm ("overflow-lm-score-to-am","if the models can produce negative scores, then sometimes it can happen that an acoustic word score is negative in the lattice, thereby making the lattice invalid. \ with this option, the acoustic score 'overflows' into the LM score, leading to a valid lattice with correct per-word scores, but with wrong score distribution \ between AM/LM", false)
const Core::ParameterBool paramSparseLmLookaheadSlowPropagation ("sparse-lm-lookahead-slow-propagation","prevent skipping multiple look-ahead n-gram order levels at the same timeframe (very minor effect)", false)
const Core::ParameterInt paramWordEndPruningBins ("word-end-pruning-bins","number of bins for histogram pruning of word ends (very minor effect)", 100, 2)
const Core::ParameterInt paramAcousticPruningBins ("acoustic-pruning-bins","number of bins for histogram pruning of states (very minor effect)", 100, 2)
const Core::ParameterInt paramInstanceDeletionLatency ("instance-deletion-latency","timeframes of inactivity before an instance is deleted", 3, 0)
const Core::ParameterString paramDumpDotGraph ("search-network-dump-dot-graph","","")
const Core::ParameterBool paramEncodeStateInTrace ("encode-state-in-trace","encode the network state in the boundary transition-information of lattices. this is only useful in auto-correcting search, and only actually used if lattice-generation is explicitly disabled in the recognition-context.", true)
Special parameters for auto-correcting search:
const Core::ParameterBool paramEncodeStateInTraceAlways ("encode-state-in-trace-always","", false)
const Core::ParameterFloat paramMinimumBeamPruning ("minimum-beam-pruning","minimum beam pruning allowed during automatic tightening for auto-correcting search", 2.0)
const Core::ParameterFloat paramMaximumBeamPruning ("maximum-beam-pruning","maximum beam pruning allowed during automatic relaxation for auto-correcting search", 100, 0)
const Core::ParameterInt paramMaximumAcousticPruningLimit ("maximum-beam-pruning-limit","", 250000, 1)
const Core::ParameterInt paramMinimumAcousticPruningLimit ("minimum-beam-pruning-limit","", 100, 1)
const Core::ParameterFloat paramMinimumWordLemmasAfterRecombination ("minimum-word-lemmas-after-recombination","minimum number of average different observed word lemmas per timeframe to consider the search-space non-degenerated for auto-correcting search", 0)
const Core::ParameterFloat paramMinimumStatesAfterPruning ("minimum-states-after-pruning","minimum number of average states after pruning to consider the search-space non-degenerated for auto-correcting search (better: use minimum-word-lemmas-after-recombination)", 50)
const Core::ParameterFloat paramMinimumWordEndsAfterPruning ("minimum-word-ends-after-pruning","minimum number of average word ends after pruning to consider the search-space non-degenerated for auto-correcting search (better: use minimum-word-lemmas-after-recombination)", 10)
const Core::ParameterFloat paramMaximumAcousticPruningSaturation ("maximum-acoustic-pruning-saturation","maximum percentage of frames at which the acoustic-pruning-limit may be hit during auto-correcting search", 0.5, 0.0, 0.9)
const Core::ParameterFloat paramMaximumStatesAfterPruning ("maximum-states-after-pruning","maximum absolute number of states after pruning allowed during auto-correcting-search (better: use maximum-acoustic-pruning-saturation and acoustic-pruning-limit instead)", Core::Type< Score >::max)
const Core::ParameterFloat paramMaximumWordEndsAfterPruning ("maximum-word-ends-after-pruning","maximum absolute number of word end hypotheses after pruning allowed during auto-correcting-search (better: use maximum-acoustic-pruning-saturation and acoustic-pruning-limit instead)", Core::Type< Score >::max)
static const TraceId invalidTraceId = Core::Type<TraceId>::max
static const StateId invalidTreeNodeIndex = (StateId)-1
static constexpr TimeframeIndex InvalidTimeframeIndex = Core::Type<u32>::max
static const Index noIndex = Core::Type<Index>::max
Detailed Description
Copyright 2020 RWTH Aachen University.
This file contains a storable, efficient and dynamic structure that allows representing the state-network in speech recognition flexibly.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
The structure can dynamically be changed by creating new states and successor-links, and a "cleanup" operation can be used to optimize the structure after significant changes.
Todo:
Enable batch-merging (mergeBatches_), and make sure the structure is optimal.
Todo:
Allow "freezing" all batches: No follower-gap in the middle (should save 1/3 of space for the batches)
Typedef Documentation
typedef u32 Search::StateId
Index of a state or label (see IS_LABEL, ID_FROM_LABEL, and LABEL_FROM_ID)
Definition at line 49 of file TreeStructure.hh.
typedef u32 Search::SubTreeListId
Index representing the batch of all nodes that are contained by one tree.
Definition at line 55 of file TreeStructure.hh.
typedef u32 Search::SuccessorBatchId
This index represents an arbitrary list of successor-states and labels.
Definition at line 36 of file TreeStructure.hh.
typedef u32 Search::TreeIndex
Global index of a tree or subtree.
Definition at line 46 of file TreeStructure.hh.
typedef Core::Ref<WordPronunciationState> Search::WordPronunciationStatePointer
The pronunciation including its current state.
Definition at line 30 of file LinearSearch.hh.
Enumeration Type Documentation
anonymous enum
Enumerator
SingleSuccessorBatchMask
When this bitmask set on an SuccessorBatchId, the id represents only one successor (or label), and the index can be extracted through "id & (~SingleSuccessorBatchMask)".
Definition at line 38 of file TreeStructure.hh.
Function Documentation
void Search::computeLevenshteinColumn (const Fsa::LabelId symbol, const std::vector< Fsa::LabelId > & hypothesis, const std::vector< u32 > & oldScores, std::vector< u32 > & newScores, const u32 initialNewScore) inline
Computes one column of the DP levenshtein distance algorithm.
Definition at line 76 of file MinimumBayesRiskAStarSearch.cc.
References require.
Referenced by Search::MinimumBayesRiskAStarSearch::updateStack().
std::set<Fsa::StateId> Search::getContour (std::set< Fsa::StateId > oldContour, Fsa::ConstAutomatonRef fsa)
Returns
contour for all states in oldContour
std::vector<Fsa::StateId> Search::getDistances (Fsa::ConstAutomatonRef fsa)
Computes the longest distance for a state from the source of the fsa.
Returns
vector assigning each state id a distance.
inline_ StateId Search::ID_FROM_LABEL (const u32 x)
Returns the representation index of this label as an edge-successor.
Definition at line 63 of file TreeStructure.hh.
Referenced by Search::HMMStateNetwork::addOutputToEdge(), and Search::HMMStateNetwork::clearOutputEdges().
inline_ bool Search::IS_LABEL (const StateId x)
Returns whether the given edge-successor index represents a label rather than a state.
Definition at line 58 of file TreeStructure.hh.
Referenced by Search::HMMStateNetwork::batchSuccessorsSimple(), Search::HMMStateNetwork::cleanup(), and Search::HMMStateNetwork::clearOutputEdges().
inline_ u32 Search::LABEL_FROM_ID (StateId x)
Encodes the given index as an edge-successor so that it represents a label.
Definition at line 68 of file TreeStructure.hh.
Referenced by Search::HMMStateNetwork::clearOutputEdges().
u32 Search::levenshteinDistance (const std::vector< Fsa::LabelId > & A, const std::vector< Fsa::LabelId > & B)
Compute levenshtein distance between two sentences using the dynamic programming algorithm.
Returns
levenshtein distance between sentence A and sentence B
bool Search::operator< (SearchNodeRef & lower, SearchNodeRef & taller)
Stack nodes are first sorted by their underestimate ascending and then by their probability mass descending.
Definition at line 203 of file MinimumBayesRiskAStarSearch.cc.
Fsa::Weight Search::posteriorRiskNBestList (const std::vector< Fsa::LabelId > & trueSentence, const std::vector< StringHypothesis > & hypotheses, Fsa::Weight & distanceOne, Fsa::Weight & maximumDistanceOne)
Naive computation of Bayes posterior risk assuming the Levenshtein loss function.
This method is usually used for computation of Bayes risk for the MAP hypothesis, as it sets the values needed for checking whether the distance-one criterion is fulfilled.
Parameters
trueSentence the sentence for which the risk shall be computed.
hypotheses vector with concurrent hypotheses
distanceOne this parameter will store the accumulated weight of all hypotheses with Levenshtein distance = 1.
maxdistanceOne this parameter will store the maximum weight of all hypotheses with Levenshtein distance = 1.
Returns
the Bayes risk of the true sentence as Fsa::Weight.
Definition at line 161 of file MinimumBayesRiskNBestListSearch.cc.
Referenced by Search::MinimumBayesRiskNBestListNaiveSearch::performSearch().
Fsa::Weight Search::posteriorRiskNBestList (const std::vector< Fsa::LabelId > & trueSentence, const std::vector< StringHypothesis > & hypotheses, const Fsa::Weight & pruningThreshold = Fsa::LogSemiring->max())
Naive computation of Bayes posterior risk assuming the Levenshtein loss function.
If the present risk exceeds the pruning threshold the computation will be stopped immidiately and the maximum possible value for the weight type will be returned.
Parameters
trueSentence the sentence for which the risk shall be computed.
hypotheses vector with concurrent hypotheses
pruningThreshold pruning threshold
Returns
the Bayes risk of the true sentence as Fsa::Weight.
Definition at line 199 of file MinimumBayesRiskNBestListSearch.cc.
Variable Documentation
const f32 Search::defaultBeamPruning = 12.0 static
Pruning (NOTE: pruning values are relative to the lm-scale, if not noted otherwise):
Definition at line 43 of file AdvancedTreeSearch/SearchSpace.cc.
Referenced by Search::SearchSpace::setAllowHmmSkips().
const StateId Search::invalidTreeNodeIndex = (StateId)-1 static
Todo:
Maybe this should be zero!
Definition at line 52 of file TreeStructure.hh.
const Core::ParameterBool Search::paramBuildMinimizedTreeFromScratch("build-minimized-network-from-scratch","", true)
Internal parameters (with good default-values)
const Core::ParameterBool Search::paramEncodeStateInTrace("encode-state-in-trace","encode the network state in the boundary transition-information of lattices. this is only useful in auto-correcting search, and only actually used if lattice-generation is explicitly disabled in the recognition-context.", true)
Special parameters for auto-correcting search: