Sprint: Fsa Namespace Reference
Fsa Namespace Reference
Copyright 2020 RWTH Aachen University.
Classes
class AlignAutomaton
class AlignLinearNbestAutomaton
class Alphabet
The abstract definition of an alphabet.
class AlphabetCounts
An object the contains all information that is gathered by the count function for alphabets.
class AlphabetMapping
Represents the result of a call to one of the mapAlphabet functions.
class AlphabetXmlParser
The Alphabet XML parser.
struct ApplyExp
struct ApplyLog
class Archive
class ArchiveReader
class ArchiveWriter
class Automaton
class AutomatonCounts
An object the contains all information that is gathered by the count function for automata.
class Bitvector
class ChangePropertiesAutomaton
class ConditionalAlignAutomaton
class CountSemiring_
class DoubleLocalPermuteAutomaton
struct equal_LabelIdVector
class ExtendByFsaAutomaton
class FirstOrderAlignAutomaton
struct GreaterEqual
class Hash
struct hash_LabelIdVector
class IBMPermuteAutomaton
struct IdentityKey
class InverseIBMPermuteAutomaton
class ITGPermuteAutomaton
class LabelIdStrings
class LevenshteinAutomaton
class LevenshteinDfsState
struct LevenshteinInfo
class LocalPermuteAutomaton
struct LogWeighting
class Mapping
Mapping between state ids of two automatons; see compose for examples.
struct Multiplier
class nBestAutomaton
struct NoProcessing
class PackedAutomaton
class PermuteAutomaton
class PermuteAutomatonBase
class PooledFirstOrderAlignAutomaton
class Posterior64Automaton
class PosteriorEAutomaton
class PredefinedLogSemiring64_
class PredefinedLogSemiring_
class PredefinedProbabilitySemiring_
class PredefinedTropicalSemiring_
class RandomPathAutomaton
class RemoveInvalidArcsAutomaton
class ReorderAutomaton
class Search
class SimpleAlignAutomaton
class Stack
class StatePotentials64DfsState
class StatePotentialsEDfsState
class StaticAlphabet
The implementation of a statically allocated alphabet.
class StorageAutomatonXmlParser
class TranslationLexicon
class TropicalIntegerSemiring_
class UnknownSemiring_
class Weight
class Weight64
class ZeroOrderAlignAutomaton
class ZeroOrderNoEmptyAlignAutomaton
class ZeroOrderSimpleAlignAutomaton
Typedefs
typedef Ftl::CoaccessibleDfsState< Automaton > CoaccessibleDfsState
typedef Core::Ref< const Alphabet > ConstAlphabetRef
This abstract smart pointer should be used to handle alphabets in your program.
typedef Automaton::ConstRef ConstAutomatonRef
typedef Automaton::Arc Arc
typedef Automaton::State State
typedef Automaton::StateRef StateRef
typedef Automaton::ConstStateRef ConstStateRef
typedef Ftl::SlaveAutomaton< Automaton > SlaveAutomaton
typedef Ftl::ModifyAutomaton< Automaton > ModifyAutomaton
typedef Ftl::DfsState< Fsa::Automaton > DfsState
typedef Core::Ref< const Mapping > ConstMappingRef
typedef Ftl::LogSemiring< Fsa::Weight, f32 > LogSemiring_
typedef Ftl::TropicalSemiring< Fsa::Weight, f32 > TropicalSemiring_
typedef Ftl::ProbabilitySemiring< Fsa::Weight, f32 > ProbabilitySemiring_
typedef Ftl::Resources< Automaton > Resources
typedef Ftl::Accumulator< Weight > Accumulator
typedef Ftl::Semiring< Weight > Semiring
typedef Semiring::Ref SemiringRef
typedef Semiring::ConstRef ConstSemiringRef
typedef Ftl::LogSemiring< Weight64, f64 > LogSemiring64_
typedef Ftl::Accumulator< Weight64 > Accumulator64
typedef Ftl::Semiring< Weight64 > Semiring64
typedef Semiring64::Ref Semiring64Ref
typedef Semiring64::ConstRef ConstSemiring64Ref
typedef Ftl::byArc< Automaton > byArc
typedef Ftl::byInput< Automaton > byInput
typedef Ftl::byInputAndTarget< Automaton > byInputTarget
typedef Ftl::byOutput< Automaton > byOutput
typedef Ftl::byInputAndOutputAndTarget< Automaton > byInputAndOutputAndTarget
typedef Ftl::byWeight< Automaton > byWeight
typedef Ftl::StatePotentials< Weight > StatePotentials
typedef Ftl::SsspArcFilter< Automaton > SsspArcFilter
typedef Ftl::IsInputLabel< Automaton > IsInputLabel
typedef Ftl::AreBothLabels< Automaton > AreBothLabels
typedef Core::Vector< f64 > StatePotentials64
typedef Ftl::StaticAutomaton< Automaton > StaticAutomaton
typedef Ftl::StorageAutomaton< Automaton > StorageAutomaton
typedef u32 StateId
state indices and tags
typedef StateId StateTag
typedef Core::Vector< StateId > StateMap
typedef s32 LabelId
label indices and special symbols
typedef u32 Property
properties
typedef u32 Hint
Formatting hints.
typedef u32 StoredComponents
Components to be stored.
typedef u8 AlphabetTag
Alphabet Tags use higher 4 bits for user-defined tags other tags may be defined in future versions.
typedef u32 OptimizationHint
Optimization hints.
typedef std::pair< std::string, std::string > QualifiedFilename
typedef ConditionalAlignAutomaton HVConditionalAlignAutomaton
typedef Vector< LabelId > LabelIdVector
Enumerations
enum SortType {
SortTypeNone, SortTypeByArc, SortTypeByInput, SortTypeByInputAndOutput,
SortTypeByInputAndTarget, SortTypeByInputAndOutputAndTarget, SortTypeByOutput, SortTypeByWeight
}
enum Type { TypeUnknown = 0, TypeAcceptor = 1, TypeTransducer = 2 }
enum SemiringType {
SemiringTypeUnknown = 0, SemiringTypeLog = 1, SemiringTypeTropical = 2, SemiringTypeTropicalInteger = 3,
SemiringTypeCount = 4, SemiringTypeProbability = 5, SemiringTypeExpectation = 6
}
semiring type deprecated, use symbolic resolution
enum models { modelSimple, modelZeroOrder, modelZeroOrderNoEmpty, modelConditional }
Functions
Core::Ref< StaticAlphabet > staticCopy (ConstAlphabetRef)
Create a deep copy of an alphabet.
AlphabetCounts count (ConstAlphabetRef a, bool progress=false)
Calculates some interesting statistics of the size of an alphabet.
LabelId countDisambiguators (ConstAlphabetRef a)
Calculates the number of disambiguators of an alphabet.
void mapAlphabet (ConstAlphabetRef from, ConstAlphabetRef to, AlphabetMapping &mapping, LabelId unknownId=InvalidLabelId, u32 reportUnknowns=0)
Generally calculates the mapping between two alphabets.
ConstAutomatonRef collect (ConstAutomatonRef f, Weight value)
ConstAutomatonRef extend (ConstAutomatonRef f, Weight value)
ConstAutomatonRef multiply (ConstAutomatonRef f, Weight value)
Multiply each arc weight with the specified weight.
ConstAutomatonRef expm (ConstAutomatonRef f)
ConstAutomatonRef logm (ConstAutomatonRef f)
ConstAutomatonRef extend (ConstAutomatonRef f1, ConstAutomatonRef f2)
ConstAutomatonRef extendFinal (ConstAutomatonRef f, Weight value)
ConstAutomatonRef isGreaterEqual (ConstAutomatonRef f, Weight threshold)
ConstAutomatonRef mapInput (ConstAutomatonRef f, ConstAlphabetRef a, u32 reportUnknowns)
ConstAutomatonRef mapOutput (ConstAutomatonRef f, ConstAlphabetRef a, u32 reportUnknowns)
ConstAutomatonRef mapInputOutput (ConstAutomatonRef f, ConstAlphabetRef a, u32 reportUnknowns)
ConstAutomatonRef mapInput (ConstAutomatonRef f, const AlphabetMapping &m)
ConstAutomatonRef mapOutput (ConstAutomatonRef f, const AlphabetMapping &m)
ConstAutomatonRef mapInputOutput (ConstAutomatonRef f, const AlphabetMapping &m)
ConstAutomatonRef normalize (ConstAutomatonRef f)
ConstAutomatonRef trim (ConstAutomatonRef f, bool progress)
ConstAutomatonRef partial (ConstAutomatonRef f, StateId initialStateOfPartialAutomaton)
ConstAutomatonRef partial (ConstAutomatonRef f, StateId initialStateOfPartialAutomaton, Weight additionalFinalWeight)
ConstAutomatonRef hypothesis (ConstAutomatonRef f, StateId n)
ConstAutomatonRef changeSemiring (ConstAutomatonRef f, ConstSemiringRef semiring)
ConstMappingRef mapNormalized (ConstAutomatonRef f)
AutomatonCounts count (ConstAutomatonRef f, bool progress)
bool isEmpty (ConstAutomatonRef f)
Core::Vector< u32 > inDegree (ConstAutomatonRef f, bool progress)
size_t countLinearStates (ConstAutomatonRef f, bool progress)
size_t countInput (ConstAutomatonRef f, LabelId label, bool progress)
size_t countOutput (ConstAutomatonRef f, LabelId label, bool progress)
void info (ConstAutomatonRef f, Core::XmlWriter &o, bool progress)
void cheapInfo (ConstAutomatonRef f, Core::XmlWriter &o)
void memoryInfo (ConstAutomatonRef f, Core::XmlWriter &o)
Weight bestscore (ConstAutomatonRef f)
ConstAutomatonRef best (ConstAutomatonRef f)
ConstAutomatonRef best (ConstAutomatonRef f, const StatePotentials &backward)
ConstAutomatonRef nbest (ConstAutomatonRef f, size_t n, bool bestSequences)
ConstAutomatonRef firstbest (ConstAutomatonRef f)
ConstAutomatonRef cache (ConstAutomatonRef f, u32 maxAge)
ConstAutomatonRef composeMatching (ConstAutomatonRef fl, ConstAutomatonRef fr, bool reportUnknowns)
ConstAutomatonRef composeSequencing (ConstAutomatonRef fl, ConstAutomatonRef fr, bool reportUnknowns)
ConstAutomatonRef difference (ConstAutomatonRef fl, ConstAutomatonRef fr)
ConstMappingRef mapToLeft (ConstAutomatonRef f)
ConstMappingRef mapToRight (ConstAutomatonRef f)
ConstAutomatonRef localDeterminize (ConstAutomatonRef f)
ConstAutomatonRef determinize (ConstAutomatonRef f, bool disambiguate)
ConstAutomatonRef removeDisambiguationSymbols (ConstAutomatonRef f)
ConstAutomatonRef removeInputDisambiguationSymbols (ConstAutomatonRef f)
ConstAutomatonRef replaceDisambiguationSymbols (ConstAutomatonRef f, LabelId ll)
ConstAutomatonRef replaceInputDisambiguationSymbols (ConstAutomatonRef f, LabelId ll)
ConstAutomatonRef read (const std::string &argument, ConstSemiringRef semiring)
bool read (StorageAutomaton *f, const std::string &file)
bool read (StorageAutomaton *f, const std::string &format, std::istream &i)
bool readAtt (StorageAutomaton *f, std::istream &i)
bool readBinary (StorageAutomaton *f, std::istream &i)
bool readLinear (StorageAutomaton *f, std::istream &i)
bool readXml (StorageAutomaton *f, std::istream &i)
ConstAutomatonRef levenshtein (ConstAutomatonRef ref, ConstAutomatonRef test, f32 delCost, f32 insCost, f32 subCost, f32 corCost)
LevenshteinInfo levenshteinInfo (ConstAutomatonRef levensh)
bool isLinear (ConstAutomatonRef la)
void getLinearInput (ConstAutomatonRef la, std::vector< LabelId > &result)
void getLinearOutput (ConstAutomatonRef la, std::vector< LabelId > &result)
Weight getLinearWeight (ConstAutomatonRef la)
ConstAutomatonRef minimize (ConstAutomatonRef f, bool progress)
ConstAutomatonRef minimize (ConstAutomatonRef f, Fsa::OptimizationHint hint, bool progress)
ConstAutomatonRef minimizeSimple (ConstAutomatonRef f)
bool write (ConstAutomatonRef f, const std::string &format, std::ostream &o, StoredComponents what, bool progress)
storage
bool write (ConstAutomatonRef f, const std::string &file, StoredComponents what, bool progress)
bool writeAtt (ConstAutomatonRef f, std::ostream &o, StoredComponents what, bool progress)
bool writeAtt (ConstAutomatonRef f, const std::string &file, StoredComponents what, bool progress)
bool writeBinary (ConstAutomatonRef f, std::ostream &o, StoredComponents what, bool progress)
bool writeBinary (ConstAutomatonRef f, const std::string &file, StoredComponents what, bool progress)
bool writeLinear (ConstAutomatonRef f, std::ostream &o, StoredComponents what, bool progress, bool printAll)
bool writeLinear (ConstAutomatonRef f, const std::string &file, StoredComponents what, bool progress)
bool writeXml (ConstAutomatonRef f, std::ostream &o, StoredComponents what, bool progress)
bool writeXml (ConstAutomatonRef f, const std::string &file, StoredComponents what, bool progress)
bool writeTrXml (ConstAutomatonRef f, std::ostream &o, StoredComponents what, bool progress)
bool writeTrXml (ConstAutomatonRef f, const std::string &file, StoredComponents what, bool progress)
bool drawDot (ConstAutomatonRef f, std::ostream &o, Fsa::Hint hint, bool progress)
visualization
bool drawDot (ConstAutomatonRef f, const std::string &file, Fsa::Hint hint, bool progress)
Core::Ref< PackedAutomaton > packedCopy (ConstAutomatonRef f)
template<class T >
ConstAutomatonRef permute (ConstAutomatonRef f, u32 windowSize, u16 distortionLimit)
ConstAutomatonRef localPermute (ConstAutomatonRef f, u32 windowSize, u16 distortionLimit)
ConstAutomatonRef inverseIBMPermute (ConstAutomatonRef f, u32 windowSize, u16 distortionLimit)
ConstAutomatonRef doubleLocalPermute (ConstAutomatonRef f, u32 windowSize, u16 distortionLimit)
ConstAutomatonRef ITGPermute (ConstAutomatonRef f, u32 windowSize, u16 distortionLimit)
ConstAutomatonRef projectInput (ConstAutomatonRef f)
ConstAutomatonRef projectOutput (ConstAutomatonRef f)
ConstAutomatonRef invert (ConstAutomatonRef f)
Fsa::Property getProperties (ConstAutomatonRef f, Fsa::Property requested)
bool hasProperties (ConstAutomatonRef f, Property properties)
ConstAutomatonRef prunePosterior (ConstAutomatonRef f, const Weight &threshold, bool relative=true)
Pruning based on posteriors.
ConstAutomatonRef prunePosterior (ConstAutomatonRef f, const Weight &threshold, const StatePotentials &fw, const StatePotentials &bw, bool relative)
ConstAutomatonRef pruneSync (ConstAutomatonRef f, const Weight &threshold)
ConstAutomatonRef random (ConstAutomatonRef f, f32 weight=0.0, u32 maximumSize=0)
Create a random path.
ConstAutomatonRef identity (ConstAlphabetRef ab, ConstSemiringRef sr)
ConstAutomatonRef closure (ConstAutomatonRef f)
ConstAutomatonRef kleeneClosure (ConstAutomatonRef f)
ConstAutomatonRef complement (ConstAutomatonRef f)
ConstAutomatonRef concat (const Core::Vector< ConstAutomatonRef > &f)
ConstAutomatonRef concat (ConstAutomatonRef f1, ConstAutomatonRef f2)
ConstAutomatonRef unite (const Core::Vector< ConstAutomatonRef > &f, const Core::Vector< Weight > &initialWeights)
ConstAutomatonRef unite (ConstAutomatonRef f1, ConstAutomatonRef f2)
ConstMappingRef mapToSubAutomaton (ConstAutomatonRef f, u32 subAutomaton)
ConstAutomatonRef fuse (const Core::Vector< ConstAutomatonRef > &f)
ConstAutomatonRef fuse (ConstAutomatonRef f1, ConstAutomatonRef f2)
ConstAutomatonRef transpose (ConstAutomatonRef f, bool progress)
ConstAutomatonRef allPrefixes (ConstAutomatonRef f)
ConstAutomatonRef allSuffixes (ConstAutomatonRef f)
ConstAutomatonRef removeEpsilons (ConstAutomatonRef f)
ConstAutomatonRef removeSimpleEpsilonArcs (ConstAutomatonRef f)
Resources & getResources ()
ConstSemiringRef getSemiring (SemiringType type)
SemiringType getSemiringType (ConstSemiringRef semiring)
ConstAutomatonRef sort (ConstAutomatonRef f, SortType type)
StateMap topologicallySort (ConstAutomatonRef f, bool progress)
bool isAcyclic (ConstAutomatonRef f)
StatePotentials sssp (ConstAutomatonRef f, StateId start, const SsspArcFilter &arcFilter, bool progress)
StatePotentials sssp (ConstAutomatonRef f, bool progress)
ConstAutomatonRef pushToInitial (ConstAutomatonRef f, bool progress)
ConstAutomatonRef pushToFinal (ConstAutomatonRef f, bool progress)
ConstAutomatonRef posterior (ConstAutomatonRef f)
ConstAutomatonRef posterior (ConstAutomatonRef f, const StatePotentials &forward)
ConstAutomatonRef posterior (ConstAutomatonRef f, Weight &totalInv)
size_t countPaths (ConstAutomatonRef f)
void sssp64 (ConstAutomatonRef f, StatePotentials64 &potentials)
ConstAutomatonRef posterior64 (ConstAutomatonRef fsa, Weight &totalInv, s32 tol)
ConstAutomatonRef posterior64 (ConstAutomatonRef fsa, f64 &totalInv, s32 tol)
ConstAutomatonRef posterior64 (ConstAutomatonRef fsa, s32 tol)
ConstAutomatonRef posterior64 (ConstAutomatonRef fsa, Weight &totalInv, bool normalize, s32 tol)
void ssspE (ConstAutomatonRef f, ConstAutomatonRef r, StatePotentials64 &potentials, StatePotentials64 &generalized)
ConstAutomatonRef posteriorE (ConstAutomatonRef f, ConstAutomatonRef r, Weight &expectation, bool vNormalized, s32 tol)
ConstAutomatonRef posteriorE (ConstAutomatonRef f, ConstAutomatonRef r, Weight &expectation, Weight &totalInv, bool vNormalized, s32 tol)
Weight expectation (ConstAutomatonRef f, ConstAutomatonRef r)
void ssspE (ConstAutomatonRef, ConstAutomatonRef, StatePotentials64 &, StatePotentials64 &, StatePotentials64 &, f32)
ConstAutomatonRef posterior4SpecialSymbols (ConstAutomatonRef f)
Super posterior.
ConstAutomatonRef posterior4SpecialSymbols (ConstAutomatonRef f, Weight &totalInv, s32 tol=100)
same as posterior4SpecialSymbols, but return total flow of automaton and prints a warning if the tolerance tol is exceeded.
ConstAutomatonRef best4SpecialSymbols (ConstAutomatonRef f)
Super best.
ConstAutomatonRef removeFailure4SpecialSymbols (ConstAutomatonRef f)
ConstAutomatonRef posteriorPrune4SpecialSymbols (ConstAutomatonRef f, const Weight &threshold, bool relative)
void removeNonAccessibleStates (Core::Ref< StaticAutomaton > s)
void trimInPlace (Core::Ref< StaticAutomaton > s)
void removeInvalidArcsInPlace (Core::Ref< StaticAutomaton > s)
Core::Ref< StaticAutomaton > staticCopy (ConstAutomatonRef f)
Core::Ref< StaticAutomaton > staticCompactCopy (ConstAutomatonRef f)
Core::Ref< StaticAutomaton > staticCopy (const std::string &str, ConstSemiringRef semiring)
void copy (StorageAutomaton *f, ConstAutomatonRef f2)
void copy (StorageAutomaton *f, const std::string &str)
u32 estimateBytes (u32 x)
void setBytes (Core::Vector< u8 >::iterator i, u32 x, int nBytes)
void appendBytes (Core::Vector< u8 > &v, u32 x, int nBytes)
u32 getBytesAndIncrement (Core::Vector< u8 >::const_iterator &a, int nBytes)
u32 getBytes (Core::Vector< u8 >::const_iterator a, int nBytes)
QualifiedFilename splitQualifiedFilename (const std::string &file, const std::string &defaultQualifier)
static ConstAutomatonRef _removeInvalidArcs (ConstAutomatonRef fsa)
ConstAutomatonRef getTestAutomaton ()
ConstAutomatonRef getTestAutomatonWithAnyAndElse ()
TEST (Fsa, Sssp4SpecialSymbols, removeFailure4SpecialSymbols)
TEST (Fsa, Sssp4SpecialSymbols, best4SpecialSymbols)
TEST (Fsa, Sssp4SpecialSymbols, posterior4SpecialSymbolsLog)
TEST (Fsa, Sssp4SpecialSymbols, posterior4SpecialSymbolsTropical)
void writeBiLang (ConstAutomatonRef f, std::ostream &o)
void writeAachen (ConstAutomatonRef f, std::ostream &o, size_t sentenceNumber, bool oneToOne, double threshold)
ConstAutomatonRef reorderNbest (std::string sourceSentence, std::string targetSentence, const TranslationLexicon *lex, u32 n=1)
ConstAutomatonRef nbestReorder (std::string sourceSentence, std::string targetSentence, const TranslationLexicon *lex, u32 n=1)
Variables
ConstSemiringRef UnknownSemiring = ConstSemiringRef(new UnknownSemiring_())
ConstSemiringRef LogSemiring = ConstSemiringRef(new PredefinedLogSemiring_())
ConstSemiringRef TropicalSemiring = ConstSemiringRef(new PredefinedTropicalSemiring_())
ConstSemiringRef TropicalIntegerSemiring = ConstSemiringRef(new TropicalIntegerSemiring_())
ConstSemiringRef ProbabilitySemiring = ConstSemiringRef(new PredefinedProbabilitySemiring_())
ConstSemiringRef CountSemiring = ConstSemiringRef(new CountSemiring_())
Core::Choice SemiringTypeChoice ("log", SemiringTypeLog,"tropical", SemiringTypeTropical,"tropical-integer", SemiringTypeTropicalInteger,"count", SemiringTypeCount,"probability", SemiringTypeProbability, Core::Choice::endMark())
ConstSemiring64Ref LogSemiring64 = ConstSemiring64Ref(new PredefinedLogSemiring64_())
const f64 Zero = Core::Type<f64>::max
Core::Choice TypeChoice ("unknown", TypeUnknown,"acceptor", TypeAcceptor,"transducer", TypeTransducer, Core::Choice::endMark())
Core::Choice PropertyChoice ("storage", PropertyStorage,"sorted-by-arc", PropertySortedByArc,"sorted-by-input", PropertySortedByInput,"sorted-by-output", PropertySortedByOutput,"linear", PropertyLinear,"acyclic", PropertyAcyclic,"cached", PropertyCached, Core::Choice::endMark())
static const StateTag StateTagNone = 0x00000000
static const StateTag StateTagFinal = 0x80000000
static const StateTag StateTagUser = 0x40000000
static const StateTag StateTagAll = 0xc0000000
static const StateTag StateTagMask = 0xc0000000
static const StateTag StateIdMask = 0x3fffffff
static const int StateIdBits = 30
static const StateId InvalidStateId = StateIdMask
static const LabelId Epsilon = -1
static const LabelId FirstLabelId = 0
static const LabelId LastLabelId = 2147483647 - 4
static const LabelId Else = 2147483647 - 3
static const LabelId Failure = 2147483647 - 2
static const LabelId Any = 2147483647 - 1
static const LabelId InvalidLabelId = Core::Type<LabelId>::max
static const Property PropertyNone = 0x00000000
static const Property PropertyAll = 0xffffffff
static const Property PropertyStorage = 0x00000001
automaton properties
static const Property PropertyCached = 0x00000040
static const Property PropertyLinear = 0x00000010
static const Property PropertyAcyclic = 0x00000020
static const Property PropertySausages = 0x00000080
static const Property PropertySorted = 0x00000f0e
static const Property PropertySortedByArc = 0x00000002
static const Property PropertySortedByInput = 0x00000004
static const Property PropertySortedByOutput = 0x00000008
static const Property PropertySortedByInputAndOutput = 0x00000400
static const Property PropertySortedByInputAndTarget = 0x00000100
static const Property PropertySortedByInputAndOutputAndTarget = 0x00000800
static const Property PropertySortedByWeight = 0x00000200
static const Property PropertySemiringAll = 0x000007ff
semiring properties
static const Property PropertyCommutative = 0x00000001
static const Property PropertyRightDistributive = 0x00000002
static const Property PropertyZeroSumFree = 0x00000004
static const Property PropertyWeaklyLeftDivisble = 0x00000008
static const Property PropertyCancellative = 0x00000012
static const Property PropertyLeftDivisible = 0x00000038
static const Property PropertyPartialOrder = 0x00000040
static const Property PropertyStrictOrder = 0x00000080
static const Property PropertySemiringIo = 0x00000300
static const Property PropertyStringIo = 0x00000100
static const Property PropertyBinaryIo = 0x00000200
static const Hint HintNone = 0x00000000
static const Hint HintAll = 0x00000007
static const Hint HintShowDetails = 0x00000001
static const Hint HintMarkBest = 0x00000002
static const Hint HintAsProbability = 0x00000004
static const Hint HintUserMask = 0xffff0000
static const StoredComponents storeStates = 0x00000001
static const StoredComponents storeInputAlphabet = 0x00000002
static const StoredComponents storeOutputAlphabet = 0x00000004
static const StoredComponents storeAlphabets = 0x00000006
static const StoredComponents storeAll = 0xffffffff
static const AlphabetTag alphabetTagDisambiguator = 0x01
static const AlphabetTag alphabetTagUserMask = 0xf0
static const OptimizationHint OptimizationHintNone = 0x00000000
static const OptimizationHint OptimizarionHintAll = 0x00000003
static const OptimizationHint OptimizationHintMemory = 0x00000001
static const OptimizationHint OptimizationHintSpeed = 0x00000002
Core::Choice OptimizationHintChoice
const Core::Choice modelChoice ("simple", modelSimple,"zeroOrder", modelZeroOrder,"zeroOrderNoEmpty", modelZeroOrderNoEmpty,"conditional", modelConditional, Core::Choice::endMark())
Detailed Description
Copyright 2020 RWTH Aachen University.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Typedef Documentation
typedef u8 Fsa::AlphabetTag
Alphabet Tags use higher 4 bits for user-defined tags other tags may be defined in future versions.
Definition at line 159 of file Fsa/Types.hh.
Fsa::ConstAlphabetRef
This abstract smart pointer should be used to handle alphabets in your program.
Definition at line 206 of file Alphabet.hh.
typedef u32 Fsa::Hint
Formatting hints.
Definition at line 136 of file Fsa/Types.hh.
typedef s32 Fsa::LabelId
label indices and special symbols
Definition at line 43 of file Fsa/Types.hh.
typedef u32 Fsa::OptimizationHint
Optimization hints.
Definition at line 180 of file Fsa/Types.hh.
typedef u32 Fsa::Property
properties
Definition at line 63 of file Fsa/Types.hh.
typedef u32 Fsa::StateId
state indices and tags
Definition at line 26 of file Fsa/Types.hh.
typedef u32 Fsa::StoredComponents
Components to be stored.
Definition at line 147 of file Fsa/Types.hh.
Enumeration Type Documentation
enum Fsa::SemiringType
semiring type deprecated, use symbolic resolution
Definition at line 167 of file Fsa/Types.hh.
Function Documentation
ConstAutomatonRef Fsa::best4SpecialSymbols (ConstAutomatonRef f)
Super best.
same features/assumptions as posterior4SpecialSymbols
Definition at line 39 of file Sssp4SpecialSymbols.cc.
Referenced by Ftl::BestAutomaton4SpecialSymbols< _Automaton >::getState().
AlphabetCounts Fsa::count (ConstAlphabetRef a, bool progress = false)
Calculates some interesting statistics of the size of an alphabet.
Complexity: O(I)
Parameters
a the alphabet
progress set to true if function should show a progress indicator on current tty
Returns
returns a data structure containing the counts
Definition at line 20 of file AlphabetUtility.cc.
Referenced by Ftl::countOutput(), FsaTool::main(), Search::Wfst::Builder::BuildGrammar::process(), and Bliss::Evaluator::reportLatticeDensity().
LabelId Fsa::countDisambiguators (ConstAlphabetRef a)
Calculates the number of disambiguators of an alphabet.
Complexity: O(I)
Parameters
a the alphabet
Returns
the number of disambiguators
Definition at line 32 of file AlphabetUtility.cc.
References Fsa::AlphabetMapping::typeComplete, Fsa::AlphabetMapping::typeIdentity, and Fsa::AlphabetMapping::typeUnmapped.
bool Fsa::drawDot (ConstAutomatonRef f, std::ostream & o, Fsa::Hint hint, bool progress)
visualization
Definition at line 75 of file Fsa/Output.cc.
Referenced by Aligner::WordLatticeBuilder::Converter::build(), Speech::AllophoneStateGraphBuilder::buildTransducer(), Flf::drawDot(), Speech::AllophoneStateGraphBuilder::finalizeTransducer(), Search::Aligner::getAlignmentFsa(), Search::Aligner::getAlignmentPosteriorFsa(), and FsaTool::main().
void Fsa::mapAlphabet (ConstAlphabetRef from, ConstAlphabetRef to, AlphabetMapping & mapping, LabelId unknownId = InvalidLabelId, u32 reportUnknowns = 0)
Generally calculates the mapping between two alphabets.
Since alphabets match on symbol level, but algorithms work on integer labels only, mapping label ids between alphabets is a necessary step if two automata with different alphabets need to interact. Complexity: the complexity depends on the implementation of the underlying alphabets. In case of two static alphabets the worst-case complexity is O(|from| log |to|)
Parameters
from a reference to the alphabet to map from
to a reference to the alphabet to map to
mapping the resulting mapping (passed by reference to save overhead due to temporary object creation)
reportUnknowns maximum number of unknown symbols that should be reported
Definition at line 73 of file AlphabetUtility.cc.
References Fsa::AlphabetMapping::del(), Fsa::AlphabetMapping::from(), Fsa::AlphabetMapping::isModifyingType(), Fsa::AlphabetMapping::map(), Fsa::AlphabetMapping::to(), Fsa::AlphabetMapping::typeIdentity, Core::Application::us(), and Core::Component::warning().
Referenced by Ftl::mapInput(), Ftl::mapInputOutput(), Ftl::mapOutput(), Fsa::AlphabetMapping::operator[](), and Ftl::ConcatUnionAutomaton< _Automaton >::uniteAlphabets().
ConstAutomatonRef Fsa::multiply (ConstAutomatonRef f, Weight value)
Multiply each arc weight with the specified weight.
Currently, this is only possibly in real-valued semirings like the log or tropical semiring. Category: on-demand Complexity: O(V + E)
Parameters
f the input automaton
value the weight
Returns
returns an automaton with all arc weights being multiplied by value
Definition at line 39 of file Fsa/Arithmetic.cc.
Referenced by Aligner::WordLatticeBuilder::Converter::build(), Flf::composeWithFsa(), Search::Aligner::getAlignmentPosteriorFsa(), Lattice::getExactPhonemeAccuracy(), Lm::LanguageModelScaling::getFsa(), Lm::ArpaClassLm::getFsa(), Flf::ComposeWithFsaNode::init(), Speech::TokenMappingLatticeProcessorNode::initialize(), Speech::MinimumBayesRiskSearchNode::initialize(), Speech::LemmaPronunciationToSyntacticToken::initialize(), FsaTool::main(), Lattice::NBestListExtractor::NBestListExtractor(), Search::Wfst::Builder::LemmaMapping::process(), Speech::MinimumErrorSegmentwiseGmmTrainer::processWordLattice(), Speech::LemmaPronunciationToEvaluationToken::processWordLattice(), Speech::OfflineRecognizer::setFeatureDescription(), and Aligner::~Aligner().
ConstAutomatonRef Fsa::posterior4SpecialSymbols (ConstAutomatonRef f)
Super posterior.
Features:
FAIL arcs
efficient implementations for Tropical and LogSemiring
64 bit precision for LogSemiring
general implementation for every Semiring
Assumptions:
only one FAIL arc per state
FAIL state include all arcs their parents have (weight is not important)
no cycles
Drawbacks:
very hard to read :-(
Definition at line 28 of file Sssp4SpecialSymbols.cc.
Referenced by FsaTool::main().
ConstAutomatonRef Fsa::posterior4SpecialSymbols (ConstAutomatonRef f, Weight & totalInv, s32 tol)
same as posterior4SpecialSymbols, but return total flow of automaton and prints a warning if the tolerance tol is exceeded.
Definition at line 32 of file Sssp4SpecialSymbols.cc.
ConstAutomatonRef Fsa::prunePosterior (ConstAutomatonRef f, const Weight & threshold, bool relative = true)
Pruning based on posteriors.
If the posterior of an arc is below the minimum posterior of the automaton, it is omitted. Minimum is defined as minimum of all arcs extended by the threshold if relative==true, else minimum is defined as the backward potential of the initial state extended by the threshold.
prunePosterior(ConstAutomatonRef, const Weight &threshold, bool relative = true) is used by command "prune" of the Fsa tool and the Lattice Processor.
Definition at line 19 of file Fsa/Prune.cc.
Referenced by Lattice::CheckPosteriorDfsState::finish(), Search::Aligner::getAlignmentPosteriorFsa(), Lattice::NBestListExtractor::getNBestListWithoutWordBoundaries(), FsaTool::main(), and Search::MinimumBayesRiskAStarSearch::performSearch().
ConstAutomatonRef Fsa::random (ConstAutomatonRef f, f32 weight = 0.0, u32 maximumSize = 0)
Create a random path.
Parameters
f the automaton
weight control how much transition weights affect sampling probability. When weight equals zero, all arcs have equal probability. Values other than zero, are allowed only for log-semirings: Then p(arc) is proportional to exp(- arc.weight * weight).
maximumSize maximum size of result. (Some algrithms may enter a non-terminaint loop, e.g. when the input automaton is not trimmed.) When maximumSize greater than 0, the result automaton contains at most maximumSize states.
Returns
a linear automaton representing a randomly chosen path through f.
Definition at line 133 of file Fsa/Random.cc.
Referenced by FsaTool::main().
Core::Ref< StaticAlphabet > Fsa::staticCopy (ConstAlphabetRef)
Create a deep copy of an alphabet.
As alphabets are usually reference counted to reduce memory and runtime requirements this call really copies an alphabet.
Definition at line 245 of file Alphabet.cc.
References Fsa::StaticAlphabet::addIndexedSymbol().
Referenced by Lattice::HtkReader::addState(), Aligner::WordLatticeBuilder::Converter::build(), Fsa::StaticAlphabet::end(), Bliss::Evaluator::evaluatePhonemes(), Bliss::Evaluator::evaluateWords(), Lattice::NBestListExtractor::getNBestListWithoutWordBoundaries(), Flf::ComposeWithFsaNode::init(), Speech::LatticeCopyNode::LatticeCopyNode(), FsaTool::main(), Search::Wfst::Builder::BuildGrammar::process(), Speech::OfflineRecognizer::setFeatureDescription(), and Aligner::~Aligner().
bool Fsa::write (ConstAutomatonRef f, const std::string & format, std::ostream & o, StoredComponents what, bool progress)
storage
Definition at line 24 of file Fsa/Output.cc.
Referenced by Aligner::WordLatticeBuilder::Converter::build(), Speech::AllophoneStateGraphBuilder::buildTransducer(), Speech::AllophoneStateGraphBuilder::finalizeTransducer(), Search::Aligner::getAlignmentFsa(), Search::Aligner::getAlignmentPosteriorFsa(), FsaTool::main(), Search::Wfst::Builder::WriteFsa::process(), and Flf::LatticeArchiveWriterNode::sendLattice().
Variable Documentation
const Property Fsa::PropertySemiringAll = 0x000007ff static
semiring properties
Definition at line 116 of file Fsa/Types.hh.
const Property Fsa::PropertyStorage = 0x00000001 static
automaton properties
storage:
automaton stores all states and arcs (instead of calculating them)
linear:
outdegree (and therefore indegree) of all states is 1
sausages:
automaton has an initial and a single final state
indegree and outdegree of all states except initial and final is 1
acyclic:
automaton does not contain any cycle except the trivial ones
cached:
automaton is being cached; helps to avoid multiple caching (we will use a special class field for this in the future)
for compatibility reasons only append new properties to the end
CAUTION: Do not change the numbers! Extend the list only with unused values!
Definition at line 92 of file Fsa/Types.hh.
Referenced by Speech::AllophoneStateGraphBuilder::build(), Ftl::cache(), Speech::LatticeRescorer::extract(), Ftl::StorageAutomaton< _Automaton >::StorageAutomaton(), and Ftl::ConcatUnionAutomaton< _Automaton >::uniteAlphabets().