Sprint: Math Namespace Reference
Math Namespace Reference
Copyright 2020 RWTH Aachen University.
Classes
struct absoluteDifference
absolute difference function
class absoluteDifferencePower
absolute difference to the power function
struct absoluteDifferenceSquare
absolute difference square function
struct absoluteDifferenceSquareRoot
absolute difference square-root function
struct AdditionFunction
f(x, y) = x + y
class AnalyticFunction
Interface class for analytic functions.
class AnalyticFunctionFactory
Analytic function factory.
class AnalyticMultiplication
f(x)*g(x)
class AnalyticNesting
f(g(x))
class AnalyticSummation
f(x)+g(x)
class AnalyticUnaryComposition
Base class for Composition of two analytic functions.
struct ArcCosh
f(x) = acosh(x) Remarks: -acosh(x) = log(x + sqrt(x^2 - 1)).
struct ArcSinh
f(x) = asinh(x) Remarks: -asinh(x) = log(x + sqrt(x^2 + 1)).
struct BilinearTransform
Bilinear Transform.
class BinaryAnalyticFunction
Interface class for binary analytic functions.
class CgPreconditioner
struct conjugateMultiplies
functors for x * conjugate(y)
class ConstantFunction
f(x) = c
struct Cosh
f(x) = cosh(x)
struct cublasHandle_t
class CudaDataStructure
class CudaMatrix
class CudaVector
struct curandGenerator_t
struct DerivedArcCosh
f(x) = d acosh(x) / dx = 1 / sqrt(x^2 - 1)
struct DerivedArcSinh
f(x) = d asinh(x) / dx = 1 / sqrt(x^2 + 1)
struct DerivedMelWarpingCore
Derived Mel warping function core: d f_{Mel} / df = 1.0 / log(10) / (700.0 + f)
class DiagonalCgPreconditioner
struct DivisionFunction
f(x, y) = x / y
class EigenvalueProblem
Base class for eigenvalue problems.
struct EqualLoudnessPreemphasis
Equal Loudness Preemphasis E(f) = (omega^4 * (omega^2 + 56.8e6)) / ((omega^2 + 6.3e6))^2 * (omega^2 + 0.38e9) * (omega^6 + 9.58e26)) E(f) *= 9.58e26 (last pole's omega) to get values in order of magnitude of 1 at 4000 Hz.
struct EqualLoudnessPreemphasis40dB
40dB equal Loudness Preemphasis (taken from Sprachcore/ICSI) E(f) = (f^2 / (f^2 + 1.6e5)) * (f^2 / (f^2 + 1.6e5))
struct EqualLoudnessPreemphasis4Khz
Equal Loudness Preemphasis optimized for 4KHz bandwidth E(f) = (omega^4 * (omega^2 + 56.8e6)) / ((omega^2 + 6.3e6))^2 * (omega^2 + 0.38e9))
class FastFourierTransform
Fast Fourier Transformation.
class FastMatrix
class FastVector
struct FloorFloatFunction
f(x) = floorf(x)
class GeneralizedEigenvalueProblem
Base class for generalized eigenvalue problems.
struct IdentityFunction
f(x) = x
struct InverseMelWarpingCore
Inverse of Mel warping function core: f = (10^(f_{Mel}) - 1) * 700.
class LbfgsPreconditioner
class LbfgsSolver
class LevinsonLeastSquares
Levinson algorithm to estimate all-pole linear predication parameters.
class LinearConjugateGradient
struct makeComplex
functor for the template constructor std::complex<T>::complex
class Matrix
Class for two-dimensional arrays.
class MatrixTool
struct MelWarpingCore
Mel warping function core f_{Mel} = log10 (1 + f / 700)
class Module_
struct MultiplicationFunction
f(x, y) = x * y
class OffsetFunction
f(x) = x + b
class PiecewiseConstantFunction
Piecewise constant function.
class PiecewiseLinearFunction
struct pointerAbs
function pointer functor to the template function abs(const std::complex<T> &)
struct pointerArg
function pointer functor to the template function arg(const std::complex<T> &)
struct pointerImag
function pointer functor to the template function imag(const std::complex<T> &)
struct pointerReal
function pointer functor to the template function real(const std::complex<T> &)
class ReferenceCountedVector
class RefernceCountedMatrix
Refernce Counted Matrix.
class ScalingFunction
f(x) = a * x
struct Sinh
f(x) = sinh(x)
struct SubstractionFunction
f(x, y) = x - y
class UnaryAnalyticFunction
Interface class for unary analytic functions.
class Vector
struct VectorRangeCheckOffPolicy
struct VectorRangeCheckOnPolicy
Typedefs
typedef Core::Ref< const UnaryAnalyticFunction > UnaryAnalyticFunctionRef
typedef Core::Ref< const BinaryAnalyticFunction > BinaryAnalyticFunctionRef
typedef int curandRngType_t
typedef void * cudaStream_t
typedef Core::SingletonHolder< Module_ > Module
Enumerations
enum cudaError_t { cudaSuccess = 0 }
enum cublasStatus_t { CUBLAS_STATUS_SUCCESS = 0 }
enum curandStatus_t { CURAND_STATUS_SUCCESS = 0 }
Functions
UnaryAnalyticFunctionRef operator+ (UnaryAnalyticFunctionRef f, UnaryAnalyticFunctionRef g)
Creates an AnalyticSummation object.
UnaryAnalyticFunctionRef operator* (UnaryAnalyticFunctionRef f, UnaryAnalyticFunctionRef g)
Creates an AnalyticMultiplication object.
UnaryAnalyticFunctionRef nest (UnaryAnalyticFunctionRef f, UnaryAnalyticFunctionRef g)
Creates an AnalyticNesting object.
template<typename T >
void swap (const int N, T *X, const int incX, T *Y, const int incY)
swap ()
template<>
void swap (const int N, float *X, const int incX, float *Y, const int incY)
template<>
void swap (const int N, double *X, const int incX, double *Y, const int incY)
template<typename T >
T nrm2 (const int N, const T *X, const int incX)
nrm2 (Euclidean norm)
template<>
float nrm2 (const int N, const float *X, const int incX)
template<>
double nrm2 (const int N, const double *X, const int incX)
template<typename T >
T asum (const int N, const T *X, const int incX)
asum (one-norm)
template<>
double asum< double > (const int N, const double *X, const int incX)
template<>
float asum< float > (const int N, const float *X, const int incX)
template<typename T >
T iamax (const int N, const T *X, const int incX)
iamax
template<>
double iamax< double > (const int N, const double *X, const int incX)
template<>
float iamax< float > (const int N, const float *X, const int incX)
template<typename T >
void scal (const int N, const T alpha, T *X, const int incX)
scal (vector scaling)
template<>
void scal< double > (const int N, const double alpha, double *X, const int incX)
template<>
void scal< float > (const int N, const float alpha, float *X, const int incX)
template<typename T , typename S >
void axpy (const int N, const T alpha, const T *X, const int incX, S *Y, const int incY)
axpy (weighted vector sum)
template<>
void axpy< double, double > (const int N, const double alpha, const double *X, const int incX, double *Y, const int incY)
template<>
void axpy< float, float > (const int N, const float alpha, const float *X, const int incX, float *Y, const int incY)
template<typename T , typename S >
T dot (const int N, const T *X, const int incX, const S *Y, const int incY, int nThreads=1)
dot (dot product)
template<>
double dot< double, double > (const int N, const double *X, const int incX, const double *Y, const int incY, int nThreads)
template<>
float dot< float, float > (const int N, const float *X, const int incX, const float *Y, const int incY, int nThreads)
template<typename T , typename S >
void copy (const int N, const T *X, const int incX, S *Y, const int incY)
copy
template<>
void copy< double, double > (const int N, const double *X, const int incX, double *Y, const int incY)
template<>
void copy< float, float > (const int N, const float *X, const int incX, float *Y, const int incY)
template<typename T >
void ger (const CBLAS_ORDER order, const int M, const int N, const T alpha, const T *X, const int incX, const T *Y, const int incY, T *A, const int lda)
template<>
void ger (const CBLAS_ORDER order, const int M, const int N, const float alpha, const float *X, const int incX, const float *Y, const int incY, float *A, const int lda)
template<>
void ger (const CBLAS_ORDER order, const int M, const int N, const double alpha, const double *X, const int incX, const double *Y, const int incY, double *A, const int lda)
template<typename T >
void gemv (const CBLAS_ORDER order, const CBLAS_TRANSPOSE TransA, const int M, const int N, const T alpha, const T *A, const int lda, const T *X, const int incX, const T beta, T *Y, const int incY)
template<>
void gemv< double > (const CBLAS_ORDER order, const CBLAS_TRANSPOSE TransA, const int M, const int N, const double alpha, const double *A, const int lda, const double *X, const int incX, const double beta, double *Y, const int incY)
template<>
void gemv< float > (const CBLAS_ORDER order, const CBLAS_TRANSPOSE TransA, const int M, const int N, const float alpha, const float *A, const int lda, const float *X, const int incX, const float beta, float *Y, const int incY)
template<typename T >
void gemm (const CBLAS_ORDER order, const CBLAS_TRANSPOSE TransA, const CBLAS_TRANSPOSE TransB, const int M, const int N, const int K, const T alpha, const T *A, const int lda, const T *B, const int ldb, const T beta, T *C, const int ldc)
template<>
void gemm< float > (const CBLAS_ORDER order, const CBLAS_TRANSPOSE transMatrixA, const CBLAS_TRANSPOSE transMatrixB, const int sizeM, const int sizeN, const int sizeK, const float scaleMatrixA, const float *matrixA, const int lda, const float *matrixB, const int ldab, const float scaleMatrixC, float *matrixC, const int ldc)
template<>
void gemm< double > (const CBLAS_ORDER order, const CBLAS_TRANSPOSE transMatrixA, const CBLAS_TRANSPOSE transMatrixB, const int sizeM, const int sizeN, const int sizeK, const double scaleMatrixA, const double *matrixA, const int lda, const double *matrixB, const int ldb, const double scaleMatrixC, double *matrixC, const int ldc)
std::string getMathLibrary ()
template<typename T >
void mt_scal (int N, T alpha, T *X, int nThreads)
(simplified) multithreaded versions that are not automatically parallelized by corresponding math library
void __mt_scal_f (int N, float alpha, const float *dummy, float *X)
template<>
void mt_scal (int N, float alpha, float *X, int nThreads)
void __mt_scal_d (int N, double alpha, const double *dummy, double *X)
template<>
void mt_scal (int N, double alpha, double *X, int nThreads)
template<typename T >
void mt_axpy (int N, T alpha, const T *X, T *Y, int nThreads)
void __mt_axpy_f (int N, float alpha, const float *X, float *Y)
template<>
void mt_axpy (int N, float alpha, const float *X, float *Y, int nThreads)
void __mt_axpy_d (int N, double alpha, const double *X, double *Y)
template<>
void mt_axpy (int N, double alpha, const double *X, double *Y, int nThreads)
template<typename T >
T mt_dot (int N, const T *X, const T *Y, int nThreads)
template<typename T >
T mt_dot (int N, T alpha, const T *X, const T *Y, int nThreads)
float __mt_dot_f (int N, float dummy, const float *X, const float *Y)
template<>
float mt_dot (int N, const float *X, const float *Y, int nThreads)
double __mt_dot_d (int N, double dummy, const double *X, const double *Y)
template<>
double mt_dot (int N, const double *X, const double *Y, int nThreads)
template<typename T >
T mt_nrm2 (int N, const T *X, int nThreads)
template<typename T >
T mt_nrm2 (int N, T alpha, const T *X, int nThreads)
float __mt_nrm2_f (int N, float dummy1, const float *X, const float *dummy2)
template<>
float mt_nrm2 (int N, const float *X, int nThreads)
double __mt_nrm2_d (int N, double dummy1, const double *X, const double *dummy2)
template<>
double mt_nrm2 (int N, const double *X, int nThreads)
template<typename T >
T mt_asum (int N, const T *X, int nThreads)
template<typename T >
T mt_asum (int N, T alpha, const T *X, int nThreads)
float __mt_asum_f (int N, float dummy1, const float *X, const float *dummy2)
template<>
float mt_asum (int N, const float *X, int nThreads)
double __mt_asum_d (int N, double dummy1, const double *X, const double *dummy2)
template<>
double mt_asum (int N, const double *X, int nThreads)
template<class InputIterator , class OutputIterator , class Operation >
void transformAlternatingComplex (InputIterator first, InputIterator last, OutputIterator result, Operation operation)
tranforms alternating complex vector into an arbitrary type (Alternating complex vectors are stored in a standard container by storing the real and the imaginary parts alternating.)
template<class InputIterator , class OutputIterator , class Operation >
void transformToAlternatingComplex (InputIterator first, InputIterator last, OutputIterator result, Operation operation)
tranforms a vector of arbitrary type into an alternating complex vector (Alternating complex vectors are stored in a standard container by storing the real and the imaginary parts alternating.) Operation is a unary function (derived from std::unary_function): Argument is of arbitrary type For the result type the functions real and imag must exist.
template<class InputIterator , class OutputIterator , class Operation >
void transformAlternatingComplexToAlternatingComplex (InputIterator first1, InputIterator last1, InputIterator first2, OutputIterator result, Operation operation)
tranforms an alternating complex vector into an alternating complex vector (Alternating complex vectors are stored in a standard container by storing the real and the imaginary parts alternating.)
template<typename T >
Core::XmlWriter & operator<< (Core::XmlWriter &os, const CudaVector< T > &v)
template<typename T >
Core::XmlWriter & operator<< (Core::XmlWriter &os, const FastVector< T > &v)
template<typename T >
void vr_exp (int n, T *x, T *y)
template<typename T >
void mt_vr_exp (int n, T *x, T *y, int nThreads)
template<typename T >
void vr_log (int n, T *x, T *y)
template<typename T >
void vr_powx (int n, T *x, T y, T *z)
template<class T >
Matrix< T > makeDiagonalMatrix (size_t dimension, T init=(T) 1)
template<class T , class P >
Matrix< T, P > makeDiagonalMatrix (const Vector< T, P > &diagonal)
template<class T , class P >
Vector< T, P > diagonal (const Matrix< T, P > &m)
template<class T , class P >
Matrix< T, P > operator* (const T &scalar, const Matrix< T, P > &matrix)
template<class T , class P >
Matrix< T, P > multiplyElementwise (const Matrix< T, P > &m1, const Matrix< T, P > &m2)
template<class T , class P >
Matrix< T, P > vectorInnerProduct (const Vector< T, P > &l, const Vector< T, P > &r)
template<class T , class P >
Matrix< T, P > real (const Matrix< std::complex< T >, P > &m)
template<class T , class P >
Matrix< T, P > imag (const Matrix< std::complex< T >, P > &m)
template<class T , class P , class TA , class PA >
void abs (const Matrix< T, P > &m, Matrix< TA, PA > &a)
template<class T , class P >
Matrix< T, P > abs (const Matrix< T, P > &m)
template<class T , class P >
Matrix< T, P > abs (const Matrix< std::complex< T >, P > &m)
template<class T , class P , class M >
void maxAbsoluteElement (const Matrix< T, P > &m, M &r)
template<class T , class P >
T maxAbsoluteElement (const Matrix< T, P > &m)
template<class T , class P >
T maxAbsoluteElement (const Matrix< std::complex< T >, P > &m)
template<class T , class P >
std::istream & operator>> (std::istream &is, Matrix< T, P > &m)
template<class T , class P >
Core::XmlWriter & operator<< (Core::XmlWriter &os, const Matrix< T, P > &m)
template<class T , class P >
Core::BinaryOutputStream & operator<< (Core::BinaryOutputStream &o, const Matrix< T, P > &m)
template<class T , class P >
Core::BinaryInputStream & operator>> (Core::BinaryInputStream &i, Matrix< T, P > &m)
template<typename T1 , typename P1 , typename T2 , typename P2 >
bool operator== (const Matrix< T1, P1 > &m1, const Matrix< T2, P2 > &m2)
template<typename T >
void mt_sv2v (int N, T alpha, const T *X, T *Y, void(*fn)(int, T, const T *, T *), int nThreads)
generic multithreading for vector operations useful for BLAS 1 operations or similar which are not automatically parallelized
template<typename T >
void mt_v2v (int N, T *X, T *Y, void(*fn)(int, T *, T *), int nThreads)
template<typename T >
T mt_svv2s (int N, T alpha, const T *X, const T *Y, T(*fn)(int, T, const T *, const T *), int nThreads)
void randomSeed (long seed)
static std::uniform_int_distribution randIntUniform (0, RAND_MAX)
int rand ()
template<typename Iter >
void random_shuffle (Iter begin, Iter end)
UnaryAnalyticFunctionRef createConstant (UnaryAnalyticFunction::Argument c)
Creates a ConstantFunction object.
template<typename T >
bool solveQuadraticEquation (T p, T q, T &xplus, T &xminus)
template<typename T >
bool isnan (T val)
isnan(val) returns true if val is nan.
template<>
bool isnan< float > (float val)
template<>
bool isnan< double > (double val)
template<>
bool isnan< long double > (long double val)
template<typename T >
bool isinf (T val)
same as isnan (see above)
template<>
bool isinf< float > (float val)
template<>
bool isinf< double > (double val)
template<>
bool isinf< long double > (long double val)
template<typename T >
T scoreSum (T a, T b)
compute the sum of two scores in probability space and convert back to score space (e.g.
template<class T , class P >
Vector< T, P > operator* (const T weight, const Vector< T, P > &v)
template<class T , class P >
Core::BinaryOutputStream & operator<< (Core::BinaryOutputStream &o, const Vector< T, P > &v)
template<class T , class P >
Core::BinaryInputStream & operator>> (Core::BinaryInputStream &i, Vector< T, P > &v)
template<typename T , class P >
Vector< T, P > real (const Vector< std::complex< T >, P > &v)
template<typename T , class P >
Vector< T, P > imag (const Vector< std::complex< T >, P > &v)
template<typename V >
std::istream & operator>> (std::istream &is, Vector< V > &v)
template<typename T , class P >
Core::XmlWriter & operator<< (Core::XmlWriter &os, const Vector< T, P > &v)
template<typename T1 , typename P1 , typename T2 , typename P2 >
bool operator== (const Vector< T1, P1 > &v1, const Vector< T2, P2 > &v2)
Variables
std::mt19937 randomEngine
const double MINLOGEPS = 11.513f
Detailed Description
Copyright 2020 RWTH Aachen University.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.to use require() for convert functions to use std::cout
Function Documentation
template<typename T > T Math::asum (const int N, const T * X, const int incX) inline
asum (one-norm)
Returns
sum_i abs(x_i)
Parameters
N input vector dimension
X input vector
incX increment of X
Referenced by mt_scal().
template<typename T , typename S > void Math::axpy (const int N, const T alpha, const T * X, const int incX, S * Y, const int incY) inline
axpy (weighted vector sum)
y += alpha * x
Parameters
N input vector dimension
alpha scaling factor
X input vector
incX increment of X
Y result vector
incY increment of Y
Definition at line 184 of file Blas.hh.
References dot().
Referenced by mt_scal().
template<typename T , typename S > void Math::copy (const int N, const T * X, const int incX, S * Y, const int incY) inline
copy
y = x
Parameters
N result vector dimension
X input vector
incX increment of X
Y result vector
incY increment of Y
Definition at line 274 of file Blas.hh.
References mt_scal(), and scal().
Referenced by Math::FastMatrix< T >::allocate(), Math::Lapack::GenEigenProblemWithSchurDecomposition::copyEigenvectors(), dot(), Math::Lapack::SymmetricEigenvalueProblem::dsyevr(), Math::Lapack::GenSymmetricDefiniteEigenProblem::dsygvx(), Nn::EmissionLatticeRescorer::finalize(), Nn::Statistics< T >::gradientL1Norm(), Math::Lapack::Matrix< f64 >::resize(), and Math::Lapack::GenEigenProblemWithSchurDecomposition::solveSymmetric().
UnaryAnalyticFunctionRef Math::createConstant (UnaryAnalyticFunction::Argument c) inline
Creates a ConstantFunction object.
Definition at line 43 of file SimpleAnalyticFunctions.hh.
Referenced by Math::AnalyticFunctionFactory::createConstant(), and Math::AnalyticFunctionFactory::parseConstant().
template<typename T , typename S > T Math::dot (const int N, const T * X, const int incX, const S * Y, const int incY, int nThreads = 1) inline
dot (dot product)
Returns
x^T y
Parameters
N input vector dimension
X first input vector
incX increment of X
Y second input vector
incY increment of Y
Definition at line 228 of file Blas.hh.
References copy().
Referenced by Math::FastMatrix< T >::allocate(), axpy(), Math::FastVector< T >::copy(), and mt_scal().
template<typename T > T Math::iamax (const int N, const T * X, const int incX) inline
iamax
Returns
the first index of the maximum absolute value of vector x
Parameters
N input vector dimension
X input vector
incX increment of X
Referenced by Math::FastMatrix< T >::allocate().
template<typename T > bool Math::isinf (T val)
same as isnan (see above)
Referenced by Lm::TFRecurrentLanguageModel::scoreCached().
template<typename T > bool Math::isnan (T val)
isnan(val) returns true if val is nan.
We cannot rely on std::isnan or x!=x, because GCC may wrongly optimize it away when compiling with -ffast-math (default in RASR), even with volatile, because -ffast-math implies -ffinite-math-only. Earlier, we checked the binary representation here, but that is of course architecture dependent. Most platforms have __isnan, which is not handled by the compiler, but implemented in libm (C stdlib). Some references: http://refspecs.linuxbase.org/LSB_3.1.1/LSB-Core-generic/LSB-Core-generic/baselib&mdash;isnan.html http://stackoverflow.com/questions/22931147/stdisinf-does-not-work-with-ffast-math-how-to-check-for-infinity
Referenced by Math::FastMatrix< T >::allocate(), Math::FastVector< T >::copy(), Nn::CtcCriterion< FloatT >::inputSpeechSegment(), Speech::LmLatticeRescorerAutomaton::score(), and scoreSum().
template<typename T > void Math::mt_scal (int N, T alpha, T * X, int nThreads) inline
(simplified) multithreaded versions that are not automatically parallelized by corresponding math library
Definition at line 474 of file Blas.hh.
References asum(), axpy(), dot(), mt_sv2v(), nrm2(), and scal().
Referenced by Math::FastMatrix< T >::allocate(), and copy().
template<typename T > void Math::mt_sv2v (int N, T alpha, const T * X, T * Y, void(*)(int, T, const T *, T *) fn, int nThreads)
generic multithreading for vector operations useful for BLAS 1 operations or similar which are not automatically parallelized
(application would be much easier in C++x11 with std::bind)
Definition at line 38 of file MultithreadingHelper.hh.
Referenced by mt_scal().
UnaryAnalyticFunctionRef Math::nest (UnaryAnalyticFunctionRef f, UnaryAnalyticFunctionRef g) inline
Creates an AnalyticNesting object.
Definition at line 128 of file AnalyticFunction.hh.
Referenced by Math::AnalyticFunctionFactory::createBarkWarpingFunction(), Math::AnalyticFunctionFactory::createLinear(), Math::AnalyticFunctionFactory::createMaximumNormalization(), Math::AnalyticFunctionFactory::createMelWarpingFunction(), and Math::AnalyticFunctionFactory::parseNesting().
template<typename T > T Math::nrm2 (const int N, const T * X, const int incX) inline
nrm2 (Euclidean norm)
Returns
(X^T X)^0.5
Parameters
N input vector dimension
X input vector
incX increment of X
Referenced by mt_scal().
UnaryAnalyticFunctionRef Math::operator* (UnaryAnalyticFunctionRef f, UnaryAnalyticFunctionRef g) inline
Creates an AnalyticMultiplication object.
Definition at line 105 of file AnalyticFunction.hh.
Referenced by Math::Vector< Math::Vector< T, P >, P >::operator*(), and Math::Vector< Math::Vector< T, P >, P >::takeSquareRoot().
UnaryAnalyticFunctionRef Math::operator+ (UnaryAnalyticFunctionRef f, UnaryAnalyticFunctionRef g) inline
Creates an AnalyticSummation object.
Definition at line 83 of file AnalyticFunction.hh.
Referenced by Math::Vector< Math::Vector< T, P >, P >::operator*().
template<typename T > void Math::scal (const int N, const T alpha, T * X, const int incX) inline
scal (vector scaling)
X = alpha * X
Parameters
N input vector dimension
X input vector
alpha scaling factor
incX increment of X
Referenced by Math::FastMatrix< T >::allocate(), copy(), and mt_scal().
template<typename T > T Math::scoreSum (T a, T b)
compute the sum of two scores in probability space and convert back to score space (e.g.
-log(exp(-a) + exp(-b))) in a numerically stable way
Definition at line 177 of file Math/Utilities.hh.
References isnan().
Referenced by Lm::CombineLanguageModel::score(), and Lm::CombineLanguageModel::sentenceEndScore().
template<typename T > void Math::swap (const int N, T * X, const int incX, T * Y, const int incY) inline
swap ()
Parameters
N input vector dimension
X input vector
incX increment of X
Y input vector
incY increment of X
template<class InputIterator , class OutputIterator , class Operation > void Math::transformAlternatingComplex (InputIterator first, InputIterator last, OutputIterator result, Operation operation)
tranforms alternating complex vector into an arbitrary type (Alternating complex vectors are stored in a standard container by storing the real and the imaginary parts alternating.)
Alternating complex numbers are first transformed to a complex<InputType> object. Operation is transforms the complex<InputType> object: operation must support the function: OutputType operator()(const complex<InputType> &). Operation is a unary function (derived from std::unary_function): Argument must have a constructor with two parameters Result is of arbitrary type
Definition at line 77 of file Complex.hh.
Referenced by Signal::alternatingComplexVectorAmplitude< T >::operator()(), Signal::alternatingComplexVectorPhase< T >::operator()(), Signal::alternatingComplexVectorRealPart< T >::operator()(), and Signal::alternatingComplexVectorImaginaryPart< T >::operator()().
template<class InputIterator , class OutputIterator , class Operation > void Math::transformAlternatingComplexToAlternatingComplex (InputIterator first1, InputIterator last1, InputIterator first2, OutputIterator result, Operation operation)
tranforms an alternating complex vector into an alternating complex vector (Alternating complex vectors are stored in a standard container by storing the real and the imaginary parts alternating.)
Operation is a binary function derived from std::binary_function: Arguments must have a constructor with two parameters For the result type the functions real and imag must exist.
Definition at line 116 of file Complex.hh.
Referenced by Signal::Convolution::apply(), and Signal::CrossCorrelation::crossCorrelation().
template<class InputIterator , class OutputIterator , class Operation > void Math::transformToAlternatingComplex (InputIterator first, InputIterator last, OutputIterator result, Operation operation)
tranforms a vector of arbitrary type into an alternating complex vector (Alternating complex vectors are stored in a standard container by storing the real and the imaginary parts alternating.) Operation is a unary function (derived from std::unary_function): Argument is of arbitrary type For the result type the functions real and imag must exist.
Definition at line 97 of file Complex.hh.