Sprint: Search::ConvertTree Struct Reference
Search::ConvertTree Struct Reference
Public Member Functions
ConvertTree (const Search::StateTree *_tree, HMMStateNetwork &_subtrees)
void convert ()
Public Attributes
const Search::StateTree * tree
HMMStateNetwork & subtrees
TreeIndex masterTreeIndex
StateId rootSubTree
StateId ciRootNode
std::map< StateTree::Exit, u32 > exits
std::vector< PersistentStateTree::Exit > exitVector
Core::HashMap< StateId, StateTree::StateId > statesForNodes
Core::HashMap< StateTree::StateId, StateId > nodesForStates
std::set< StateId > coarticulatedRootNodes
u32 lostNodeIndices
std::map< StateId, std::pair< Bliss::Phoneme::Id, Bliss::Phoneme::Id > > rootTransitDescriptions
Private Member Functions
void convert (StateTree::StateId stateId, StateId node)
Detailed Description
Definition at line 38 of file PersistentStateTree.cc.
Member Function Documentation
void Search::ConvertTree::convert () inline
Make sure a node is created for every single state, so that also the coarticulated roots are respected
Care about outputs
Definition at line 56 of file PersistentStateTree.cc.
References Search::HMMStateNetwork::addNodeToEdge(), Search::HMMStateNetwork::addOutputToEdge(), Search::HMMStateNetwork::allocateTreeNode(), Bliss::LemmaPronunciation::invalidId, Search::HMMStateNetwork::state(), Search::HMMState::stateDesc, Search::StateTree::states_, Search::HMMState::successors, and verify.
Referenced by Search::PersistentStateTree::build().
The documentation for this struct was generated from the following file:
PersistentStateTree.cc