Sprint: Search::SearchSpaceStatistics Struct Reference
Search::SearchSpaceStatistics Struct Reference
Public Member Functions
Core::Statistics< f32 > & customStatistics (const std::string &name)
Can be used to easily do statistics, when performance does not matter.
Core::HistogramStatistics & customHistogramStatistics (const std::string &name, u32 buckets=10)
void clear ()
void write (Core::XmlWriter &) const
Public Attributes
Core::Statistics< u32 > treesBeforePruning
Core::Statistics< u32 > treesAfterPrePruning
Core::Statistics< u32 > treesAfterPruning
Core::Statistics< u32 > statesBeforePruning
Core::Statistics< u32 > statesAfterPrePruning
Core::Statistics< u32 > statesAfterPruning
Core::Statistics< u32 > wordEndsBeforePruning
Core::Statistics< u32 > wordEndsAfterPruning
Core::Statistics< u32 > epsilonWordEndsAdded
Core::Statistics< u32 > wordEndsAfterRecombination
Core::Statistics< u32 > wordEndsAfterSecondPruning
Core::Statistics< Score > acousticHistogramPruningThreshold
Core::Statistics< Score > lmHistogramPruningThreshold
Core::HistogramStatistics entryStateHypotheses
Core::HistogramStatistics rootStateHypothesesPerTree
Private Attributes
std::map< std::string, Core::Statistics< f32 > * > customStatistics_
std::map< std::string, Core::HistogramStatistics * > customHistogramStatistics_
Detailed Description
Definition at line 25 of file SearchSpaceStatistics.hh.
Member Function Documentation
Core::Statistics< f32 > & Search::SearchSpaceStatistics::customStatistics (const std::string & name)
Can be used to easily do statistics, when performance does not matter.
Definition at line 87 of file SearchSpaceStatistics.cc.
Referenced by Search::SearchSpace::filterStates(), Search::SearchSpace::hypothesizeEpsilonPronunciations(), and Search::SearchSpace::minimumWordEndScore().
The documentation for this struct was generated from the following files:
SearchSpaceStatistics.hh
SearchSpaceStatistics.cc