Sprint: BisonParser::ArithmeticExpressionParser::basic_symbol< Base > Struct Template Reference
BisonParser::ArithmeticExpressionParser::basic_symbol< Base > Struct Template Reference
A complete symbol.
#include <ArithmeticExpressionParser.hh>
Public Types
typedef Base super_type
Alias to Base.
Public Member Functions
basic_symbol ()
Default constructor.
basic_symbol (const basic_symbol &other)
Copy constructor.
basic_symbol (typename Base::kind_type t, const location_type &l)
Constructor for valueless symbols.
basic_symbol (typename Base::kind_type t, const semantic_type &v, const location_type &l)
Constructor for symbols with semantic value.
~basic_symbol ()
Destroy the symbol.
void clear ()
Destroy contents, and record that is empty.
bool empty () const
Whether empty.
void move (basic_symbol &s)
Destructive move, s is emptied into this.
Public Attributes
semantic_type value
The semantic value.
location_type location
The location.
Private Member Functions
basic_symbol & operator= (const basic_symbol &other)
Assignment operator.
Detailed Description
template<typename Base>
struct BisonParser::ArithmeticExpressionParser::basic_symbol< Base >
A complete symbol.
Expects its Base type to provide access to the symbol type via type_get().
Provide access to semantic value and location.
Definition at line 255 of file ArithmeticExpressionParser.hh.
Member Typedef Documentation
template<typename Base> typedef Base BisonParser::ArithmeticExpressionParser::basic_symbol< Base >::super_type
Alias to Base.
Definition at line 258 of file ArithmeticExpressionParser.hh.
Constructor & Destructor Documentation
template<typename Base > BisonParser::ArithmeticExpressionParser::basic_symbol< Base >::basic_symbol () inline
Default constructor.
Definition at line 220 of file ArithmeticExpressionParser.cc.
template<typename Base > BisonParser::ArithmeticExpressionParser::basic_symbol< Base >::basic_symbol (const basic_symbol< Base > & other) inline
Copy constructor.
Definition at line 226 of file ArithmeticExpressionParser.cc.
References BisonParser::ArithmeticExpressionParser::basic_symbol< Base >::value.
template<typename Base> BisonParser::ArithmeticExpressionParser::basic_symbol< Base >::basic_symbol (typename Base::kind_type t, const location_type & l) inline
Constructor for valueless symbols.
Definition at line 247 of file ArithmeticExpressionParser.cc.
template<typename Base> BisonParser::ArithmeticExpressionParser::basic_symbol< Base >::basic_symbol (typename Base::kind_type t, const semantic_type & v, const location_type & l) inline
Constructor for symbols with semantic value.
Definition at line 237 of file ArithmeticExpressionParser.cc.
template<typename Base > BisonParser::ArithmeticExpressionParser::basic_symbol< Base >::~basic_symbol () inline
Destroy the symbol.
Definition at line 255 of file ArithmeticExpressionParser.cc.
References BisonParser::ArithmeticExpressionParser::basic_symbol< Base >::clear().
Member Function Documentation
template<typename Base > void BisonParser::ArithmeticExpressionParser::basic_symbol< Base >::clear () inline
Destroy contents, and record that is empty.
Definition at line 263 of file ArithmeticExpressionParser.cc.
Referenced by BisonParser::ArithmeticExpressionParser::parse(), and BisonParser::ArithmeticExpressionParser::basic_symbol< Base >::~basic_symbol().
template<typename Base > bool BisonParser::ArithmeticExpressionParser::basic_symbol< Base >::empty () const inline
Whether empty.
Definition at line 271 of file ArithmeticExpressionParser.cc.
Referenced by BisonParser::ArithmeticExpressionParser::parse(), BisonParser::ArithmeticExpressionParser::yy_print_(), and BisonParser::ArithmeticExpressionParser::yysyntax_error_().
template<typename Base > void BisonParser::ArithmeticExpressionParser::basic_symbol< Base >::move (basic_symbol< Base > & s) inline
Destructive move, s is emptied into this.
Definition at line 279 of file ArithmeticExpressionParser.cc.
References BisonParser::ArithmeticExpressionParser::basic_symbol< Base >::location, and BisonParser::ArithmeticExpressionParser::basic_symbol< Base >::value.
template<typename Base> basic_symbol& BisonParser::ArithmeticExpressionParser::basic_symbol< Base >::operator= (const basic_symbol< Base > & other) private
Assignment operator.
Member Data Documentation
template<typename Base> location_type BisonParser::ArithmeticExpressionParser::basic_symbol< Base >::location
The location.
Definition at line 291 of file ArithmeticExpressionParser.hh.
Referenced by BisonParser::ArithmeticExpressionParser::basic_symbol< Base >::move(), BisonParser::ArithmeticExpressionParser::stack_symbol_type::operator=(), BisonParser::ArithmeticExpressionParser::parse(), and BisonParser::ArithmeticExpressionParser::yy_print_().
template<typename Base> semantic_type BisonParser::ArithmeticExpressionParser::basic_symbol< Base >::value
The semantic value.
Definition at line 288 of file ArithmeticExpressionParser.hh.
Referenced by BisonParser::ArithmeticExpressionParser::basic_symbol< Base >::basic_symbol(), BisonParser::ArithmeticExpressionParser::basic_symbol< Base >::move(), BisonParser::ArithmeticExpressionParser::stack_symbol_type::operator=(), BisonParser::ArithmeticExpressionParser::parse(), BisonParser::ArithmeticExpressionParser::stack_symbol_type::stack_symbol_type(), and BisonParser::ArithmeticExpressionParser::yy_print_().
The documentation for this struct was generated from the following files:
ArithmeticExpressionParser.hh
ArithmeticExpressionParser.cc