Sprint: WordConditionedTreeSearch::SearchSpace::WordEndHypothesis Struct Reference
WordConditionedTreeSearch::SearchSpace::WordEndHypothesis Struct Reference
Classes
struct Equality
struct Hash
Public Member Functions
WordEndHypothesis (const Lm::History &h, StateTree::StateId e, const Bliss::LemmaPronunciation *p, ScoreVector s, const Ref< Trace > &t)
void addLmScore (Core::Ref< const Lm::ScaledLanguageModel > lm, Score wpScale)
add lm score and update history
void addLmScore (Core::Ref< const Lm::ScaledLanguageModel > lm, Score wpScale, TreeInstance::LmCache &lmCache)
add lm score and update history using the cached entries
u32 hashKey () const
Public Attributes
Lm::History history
StateTree::StateId transitEntry
const Bliss::LemmaPronunciation * pronunciation
ScoreVector score
Ref< Trace > trace
Detailed Description
Definition at line 200 of file WordConditionedTreeSearch.cc.
Member Function Documentation
void WordConditionedTreeSearch::SearchSpace::WordEndHypothesis::addLmScore (Core::Ref< const Lm::ScaledLanguageModel > lm, Score wpScale) inline
add lm score and update history
Definition at line 664 of file WordConditionedTreeSearch.cc.
References Lm::addLemmaPronunciationScore(), and Mc::Component::scale().
Referenced by WordConditionedTreeSearch::SearchSpace::findWordEnds(), and WordConditionedTreeSearch::SearchSpace::hypothesizeEpsilonPronunciations().
void WordConditionedTreeSearch::SearchSpace::WordEndHypothesis::addLmScore (Core::Ref< const Lm::ScaledLanguageModel > lm, Score wpScale, TreeInstance::LmCache & lmCache) inline
add lm score and update history using the cached entries
Definition at line 671 of file WordConditionedTreeSearch.cc.
References require.
The documentation for this struct was generated from the following file:
WordConditionedTreeSearch.cc