Sprint: Unicode.hh File Reference
Unicode.hh File Reference
Unicode support functions.
#include <functional>
#include <string>
#include <iconv.h>
#include "Assertions.hh"
Classes
class Core::CharsetConverter
class Core::UnicodeInputConverter
Converter for reading text data.
class Core::UnicodeOutputConverter
Converter for writing text data.
Namespaces
Core
Copyright 2020 RWTH Aachen University.
Macros
#define _CORE_UNICODE_HH
Copyright 2020 RWTH Aachen University.
Enumerations
enum utf8::ByteType { singleByte, multiByteHead, multiByteTail, illegal }
UTF-8 is based on bytes (8 bit).
Functions
ByteType utf8::byteType (char u)
size_t utf8::length (const char *)
Count unicode characters in a UTF-8 string.
std::wstring widen (const std::string &)
Convert UTF-8 Unicode string to wide character string (UCS-4)
std::string narrow (const std::wstring &)
Convert wide character (UCS-4) Unicode string to UTF-8.
Variables
const char utf8::blank = ' '
const char utf8::whitespace [] = " \t\n\r\f\v"
const char *const Core::defaultEncoding = "ISO-8859-1"
Detailed Description
Unicode support functions.
See also
Unicode
Definition in file Unicode.hh.
Macro Definition Documentation
#define _CORE_UNICODE_HH
Copyright 2020 RWTH Aachen University.
All rights reserved.
Licensed under the RWTH ASR License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.hltpr.rwth-aachen.de/rwth-asr/rwth-asr-license.html
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Definition at line 17 of file WeightedAccumulator.hh.
Enumeration Type Documentation
enum utf8::ByteType
UTF-8 is based on bytes (8 bit).
Codepoints below 128 (i.e. ASCII characters) are represented as a singleByte. Other codepoints are encoded as multi-byte sequence, which consists of a multiByteHead followed by one up to five multiByteTail bytes. The two byte values 0xfe and 0xff are illegal, they can never occur in a UTF-8 string.
Definition at line 86 of file Unicode.hh.
Function Documentation
size_t utf8::length (const char * uu)
Count unicode characters in a UTF-8 string.
Unlike normal strlen(), this function handles multi-byte characters correctly.
Definition at line 29 of file Unicode.cc.
References utf8::length().
Referenced by utf8::length().
std::string narrow (const std::wstring &)
Convert wide character (UCS-4) Unicode string to UTF-8.
Definition at line 86 of file Unicode.cc.
Referenced by Core::convertToLowerCase(), and Core::convertToUpperCase().
std::wstring widen (const std::string &)
Convert UTF-8 Unicode string to wide character string (UCS-4)
Definition at line 39 of file Unicode.cc.
Referenced by Core::convertToLowerCase(), and Core::convertToUpperCase().